#!/usr/bin/env python3
"""Turn uv's Linux version resolution into one hash-pinned CPython 3.12 wheel each.

This is an explicit maintenance command, never a container build/install step.
It reads published PyPI file hashes (and hash-bearing official PyTorch URLs).
"""
from __future__ import annotations

import argparse
from concurrent.futures import ThreadPoolExecutor
import json
from pathlib import Path
import urllib.parse
import urllib.request

from packaging.requirements import Requirement
from packaging.specifiers import SpecifierSet
from packaging.tags import compatible_tags, cpython_tags
from packaging.utils import canonicalize_name, parse_wheel_filename


def linux_tags():
    platforms = [f"manylinux_2_{minor}_x86_64" for minor in range(36, 4, -1)]
    platforms += ["manylinux2014_x86_64", "manylinux2010_x86_64", "manylinux1_x86_64", "linux_x86_64"]
    tags = list(cpython_tags((3, 12), platforms=platforms))
    tags += list(compatible_tags((3, 12), interpreter="cp312", platforms=platforms))
    return {tag: index for index, tag in reversed(list(enumerate(tags)))}


def resolve(line):
    requirement = Requirement(line)
    name = canonicalize_name(requirement.name)
    if requirement.url:
        url, fragment = urllib.parse.urldefrag(requirement.url)
        digest = urllib.parse.parse_qs(fragment).get("sha256", [""])[0]
        if len(digest) != 64:
            raise ValueError(f"Direct wheel lacks an exact published hash: {name}")
        return name, url, digest
    version = next(iter(requirement.specifier)).version
    if str(requirement.specifier) != f"=={version}":
        raise ValueError(f"Expected exactly one version for {name}")
    with urllib.request.urlopen(f"https://pypi.org/pypi/{name}/{version}/json", timeout=30) as response:
        metadata = json.load(response)
    supported = linux_tags()
    candidates = []
    for asset in metadata["urls"]:
        if asset["packagetype"] != "bdist_wheel" or asset.get("yanked"):
            continue
        if asset.get("requires_python") and "3.12.14" not in SpecifierSet(asset["requires_python"]):
            continue
        _, _, _, tags = parse_wheel_filename(asset["filename"])
        ranks = [supported[tag] for tag in tags if tag in supported]
        if ranks:
            candidates.append((min(ranks), asset["filename"], asset))
    if not candidates:
        raise ValueError(f"No CPython 3.12 Linux/amd64 wheel for {name}=={version}")
    asset = min(candidates)[2]
    return name, asset["url"], asset["digests"]["sha256"]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("versions", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    lines = [line.strip() for line in args.versions.read_text().splitlines()
             if line.strip() and not line.startswith("#")]
    with ThreadPoolExecutor(max_workers=8) as pool:
        wheels = sorted(pool.map(resolve, lines))
    header = ("# Generated by container/resolve_wheel_lock.py; CPython 3.12.14, Linux/amd64.\n"
              "# Exactly one official wheel URL and SHA-256 per distribution; no source builds.\n"
              "# The container installs with --require-hashes --no-deps, then pip check.\n")
    args.output.write_text(header + "\n".join(
        f"{name} @ {url} " + chr(92) + "\n    --hash=sha256:" + digest
        for name, url, digest in wheels
    ) + "\n")
    print(f"Locked {len(wheels)} exact wheels to {args.output}")


if __name__ == "__main__":
    main()
