{
  "hash": "6d6c89859d4239b77439ba0ab763ab5a",
  "result": {
    "engine": "jupyter",
    "markdown": "# CNNs: Making the Filters Learnable {#sec-08-cnn}\n\n<!-- lecture-source: m04_lecture-4-convolutional-neural-networks-cnns_s6xDEvdz3tY.txt (spine #13–18),\n     [coding]_m04_dl4-2-coding-up-your-first-cnn_Dprs8jH13GA.txt (code spine)\n     seeds: sources/4.1-CNN.tex (§The Leap to Learning, §Building Blocks of a\n            Convolutional Layer, §Pooling: Engineering Translation Invariance)\n     note: sources/4.2-CNN-2.tex (efficiency principles, modern architectures) is\n           @sec-09-modern-cnns-transfer material and is not used here. -->\n\n@sec-07-filters-convolution applied a fixed local kernel with shared coefficients at\nevery position. We now keep that spatial structure and optimize the coefficients against a\ntask loss.\n\nTo do so, we declare the kernel coefficients to be learnable parameters. That single change is\nthe core of this chapter. Everything else introduced here (channels, padding, stride and\npooling) turns the learnable filter into a working network. By the end of the chapter we will\nhave assembled [LeNet](https://doi.org/10.1109/5.726791), trained it on the Fashion-MNIST\nimages of @sec-06-generalization-inductive-bias, and repeated that chapter's shift experiment\nto test whether LeNet tolerates the shift better than the MLP did.\n\n:::: {.plan-code}\n::: {.plan}\n1. Load imports and the Fashion-MNIST subset.\n:::\n\n::: {#setup .cell execution_count=1}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: imports and the Fashion-MNIST subset\"}\nimport torch\nimport torch.nn as nn\nimport torch.nn.functional as F\nimport matplotlib.pyplot as plt\ntorch.set_num_threads(4)  # pinned: results depend on the CPU thread count\n\n# [1]\ntorch.manual_seed(6050)\ndevelopment = torch.load(\"../../data/fashion-train.pt\")\nholdout = torch.load(\"../../data/fashion-test.pt\")\nX_dev = development[\"X\"].float().unsqueeze(1) / 255.0  # (1200, 1, 28, 28)\ny_dev, classes = development[\"y\"], development[\"classes\"]\nX_test = holdout[\"X\"].float().unsqueeze(1) / 255.0     # (600, 1, 28, 28)\ny_test = holdout[\"y\"]\n\nsplit = torch.randperm(len(X_dev), generator=torch.Generator().manual_seed(6050))\nfit_idx, val_idx = split[:1000], split[1000:]\nX_tr, y_tr = X_dev[fit_idx], y_dev[fit_idx]      # (1000,1,28,28), (1000,)\nX_val, y_val = X_dev[val_idx], y_dev[val_idx]    # (200,1,28,28), (200,)\n```\n:::\n\n\n::::\nNote the shapes. In Part I our MLPs flattened every image into a vector of 784 pixels,\ndiscarding its two-dimensional arrangement at the first layer. A convolutional network keeps\nthat geometry: the images stay rectangular grids, and they gain an explicit *channel*\ndimension, whose purpose we explain below.\n\n::: {.callout-warning}\n## The book's batch convention: NCHW\n\nThroughout this book, every image **batch** uses PyTorch's **NCHW** order: (batch,\nchannels, height, width). A single grayscale batch is therefore shaped `(1, 1, 28,\n28)`. `Conv2d` can also accept an unbatched `(C, H, W)` input, but keeping the batch\ndimension explicit makes downstream shapes predictable. The kernels of a conv layer\nare stored in a 4-D tensor too: (out-channels,\nin-channels, height, width). This bookkeeping is a common source of\nerrors in convolutional code: when a shape error appears, count dimensions before\nchanging anything else. @sec-07-filters-convolution's `conv2d` helper hid this with `x[None, None]`;\nfrom here on we handle it in the open.\n:::\n\n## Learning a kernel from input–output pairs {#nine-numbers-learned}\n\nConsider a game. A feature detector, one of the fixed filters of @sec-07-filters-convolution,\nis hidden from us; we observe only what it does: images go in, feature maps come out.\nOur job is to build a detector that matches it.\n\nThe tools of Part I suffice. A kernel applied by @eq-crosscorr is\njust nine numbers entering a dot product $\\rightarrow$ the output is differentiable\nwith respect to those numbers $\\rightarrow$ gradient descent applies. Start from a\nrandom kernel and run the loop we have run since @sec-01-linear-regression: predict $\\rightarrow$\nmeasure $\\rightarrow$ step.\n\n:::: {.plan-code}\n::: {.plan}\n1. Compute the hidden `mystery` kernel's `target` maps on 256 garments and draw a small\n   random `K`.\n2. Recover a mystery kernel by gradient descent.\n:::\n\n::: {#learn-kernel .cell execution_count=2}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: recover a mystery kernel by gradient descent\"}\n# [1]\nmystery = torch.tensor([[-1., 0., 1.],\n                        [-2., 0., 2.],\n                        [-1., 0., 1.]])            # (don't peek)\nimgs = X_tr[:256]                                  # (256, 1, 28, 28)\nwith torch.no_grad():\n    target = F.conv2d(imgs, mystery[None, None])   # what the detector does\n\ntorch.manual_seed(0)\nK = 0.1 * torch.randn(1, 1, 3, 3)\nK_init = K.clone().squeeze()\nK.requires_grad_(True)\n\nlr = 0.5\n# [2]\nfor step in range(601):\n    pred = F.conv2d(imgs, K)                       # predict\n    loss = F.mse_loss(pred, target)                # measure\n    loss.backward()\n    with torch.no_grad():                          # step\n        K -= lr * K.grad\n        K.grad.zero_()\n    if step % 200 == 0:\n        print(f\"step {step:3d}   loss {loss.item():.2e}\")\n\nprint(f\"\\nlearned kernel, rounded:\\n{K.detach().squeeze().round(decimals=2)}\")\nprint(f\"max |learned - mystery| = {(K.detach().squeeze() - mystery).abs().max():.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nstep   0   loss 1.37e+00\nstep 200   loss 5.53e-04\nstep 400   loss 4.80e-05\nstep 600   loss 4.42e-06\n\nlearned kernel, rounded:\ntensor([[-1.0100, -0.0000,  1.0100],\n        [-1.9800, -0.0100,  1.9900],\n        [-1.0100,  0.0100,  1.0000]])\nmax |learned - mystery| = 0.018\n```\n:::\n:::\n\n\n::::\nThe loss falls more than five orders of magnitude, and the learned kernel is the vertical Sobel\ndetector to within 0.02 in every entry. Gradient descent, given nothing but\ninput–output pairs, has *recovered* a filter that computer-vision researchers\noriginally designed by hand.\n\n::: {.cell execution_count=3}\n\n::: {.cell-output .cell-output-display}\n![The mystery-detector game. Left: the random starting kernel. Middle: the kernel gradient descent found from input–output pairs alone. Right: the hand-crafted vertical Sobel detector from @sec-07-filters-convolution. The middle kernel was fitted without any definition of an edge.](08-cnn_files/figure-pdf/fig-learned-kernel-output-1.pdf){#fig-learned-kernel fig-alt='Three three-by-three heatmaps compare a disordered random kernel, a learned signed pattern, and the vertical Sobel pattern. The learned and Sobel panels have nearly identical positive and negative columns.'}\n:::\n:::\n\n\n::: {.callout-tip}\n## Kernels learned from data\n\nDeep learning for vision is that experiment at scale. @sec-07-filters-convolution ended with the bottleneck: someone has to design the kernel,\nchoosing its coefficients for a specific low-level operation such as smoothing or\ndetecting intensity changes. *What if\nthe template were learnable?* A convolutional network makes it learnable:\nit puts the coefficients on the gradient tape and fits them to the task loss, with\nmachinery we have used since @sec-04-training-loss-sgd.\n:::\n\nTwo differences make the real thing *harder* than the game, not easier. First, the game was rigged: the target came from a known kernel,\nso a perfect answer existed and the loss surface was a clean convex bowl (the output\nis linear in the kernel $K$, and squared error in a linear map is @sec-01-linear-regression's setting all over\nagain). Second, and more important: **in a real CNN, nobody supplies the target\nfeature maps.** The only supervision is the classification loss at the far end of the\nnetwork. The gradient flows backward through every layer (exactly the mechanics of\n@sec-05-backpropagation) and the kernels that emerge are whatever detectors the task\nloss favors. We chose Sobel here; a trained network may arrive at kernels that match\nno named filter.\n\nBackpropagation through a convolutional layer applies the accumulation rule of @sec-05-backpropagation:\na quantity used in several places of a computation receives the sum of the gradients from all\nof them. The kernel is such a quantity. In the notation of @eq-crosscorr, write the kernel as\n$V$ (the $K$ of the game) and the output map as $H$. The weight $[V]_{u,v}$ enters every\noutput entry $[H]_{i,j}$, each time multiplied by the pixel $[X]_{i+u,\\,j+v}$, so\n\n$$\n\\frac{\\partial L}{\\partial [V]_{u,v}} \\;=\\; \\sum_{i,j} \\delta_{i,j}\\,[X]_{i+u,\\,j+v},\n\\qquad \\delta_{i,j} = \\frac{\\partial L}{\\partial [H]_{i,j}},\n$$\n\nwith one more sum over the images of the batch. The gradient is itself a cross-correlation with\nthe roles exchanged: the map of sensitivities $\\delta$ acts as the kernel and slides over\n$X$, and its $k \\times k$ stops give the entries of $\\partial L/\\partial V$. With the default\n`reduction=\"mean\"` of `F.mse_loss`, each $\\delta_{i,j}$ carries a factor of one over the\nnumber of averaged entries. Weight sharing on the forward pass therefore means summed gradients\non the backward pass: every patch of every image contributes to the update of the one shared\ntemplate.\n\n## Channels: from one detector to many {#from-one-detector-to-a-layer-of-detectives}\n\nOne learnable kernel gives one feature map, and one feature map records one pattern: a\nvertical edge, a horizontal edge, a local average. The examples of fixed filters in @sec-07-filters-convolution\nshowed that an image carries many such patterns at once, and a classifier needs evidence about\nseveral of them at every position. A layer therefore applies several kernels to the same input,\na team of specialized detectors, each producing its own feature map. Their responses at one\nposition form a vector, and the representation gains a dimension: the **channels**.\n\nChannels enter a convolutional layer at two places, with different roles:\n\n- **Out-channels add kernels.** A conv layer with 6 output channels owns 6\n  independent kernels and produces a stack of 6 feature maps.\n- **In-channels let each kernel span the whole stack.** The next layer's input is that\n  6-deep stack, so the input at each position is a vector of 6 responses rather than one\n  pixel. Each kernel of the next layer therefore grows a third dimension: a $6 \\times 5\n  \\times 5$ volume that covers all six incoming maps at once.\n\nFor an input stack $X$ with $C_{\\text{in}}$ channels, output feature map\n$o \\in \\{1, \\dots, C_{\\text{out}}\\}$ is\n\n$$\n[H_o]_{i,j} \\;=\\; b_o \\;+\\; \\sum_{c=1}^{C_{\\text{in}}}\\;\n\\Bigl(\\,\\sum_{u=-\\Delta}^{\\Delta}\\;\\sum_{v=-\\Delta}^{\\Delta}\n[V_{o,c}]_{u,v}\\,[X_c]_{i+u,\\,j+v}\\Bigr),\n$$ {#eq-conv-layer}\n\nand a pointwise activation follows; as in @sec-07-filters-convolution, the kernel is\n$k \\times k$ with $k = 2\\Delta + 1$. The inner double sum is the cross-correlation of @eq-crosscorr,\napplied to input channel $c$ with the slice $V_{o,c}$ of the kernel; the outer sum adds the\n$C_{\\text{in}}$ results, and $b_o$ is the bias of output channel $o$. The\ncomputation for one output pixel is one dot product between a\n$C_{\\text{in}} \\times k \\times k$ patch of the input and the $C_{\\text{in}} \\times k \\times k$\nkernel of output channel $o$, plus the bias $b_o$. A dense layer of an MLP takes a dot product\nacross all of its input features; a convolutional layer takes the same kind of dot product\nacross all input channels but only a small spatial window, and slides it over the grid. The\nrecipe of the layer (dot products, bias, activation) is the MLP's; only the wiring of the\nlinear part differs.\n\n:::: {.plan-code}\n::: {.plan}\n1. Build `conv1` (1 to 6 channels) and `conv2` (6 to 16), then feed one garment through\n   both with ReLU.\n2. Run one grayscale image through two conv layers.\n:::\n\n::: {#channels .cell execution_count=4}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: one grayscale image through two conv layers\"}\n# [1]\nconv1 = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=5, padding=2)\nconv2 = nn.Conv2d(in_channels=6, out_channels=16, kernel_size=5)\n\nx = X_tr[:1]                                   # (1, 1, 28, 28): one garment\nh1 = F.relu(conv1(x))\nh2 = F.relu(conv2(h1))\n# [2]\nprint(f\"input   {tuple(x.shape)}\")\nprint(f\"conv1   {tuple(h1.shape)}   kernels: {tuple(conv1.weight.shape)}\")\nprint(f\"conv2   {tuple(h2.shape)}  kernels: {tuple(conv2.weight.shape)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ninput   (1, 1, 28, 28)\nconv1   (1, 6, 28, 28)   kernels: (6, 1, 5, 5)\nconv2   (1, 16, 24, 24)  kernels: (16, 6, 5, 5)\n```\n:::\n:::\n\n\n::::\nEach kernel of `conv2` spans all six maps of `conv1`, so it computes combinations of the first\nlayer's responses rather than of raw pixels. If earlier channels respond to edges of different\norientations, a later channel can combine them into a response to corners or crossings. We\nbuild one such combination by hand on a filled square: two first-layer channels compute\nvertical and horizontal edge energy, and one second-layer kernel with equal positive weights on\nboth channels sums them over a local window (@fig-corner-detector).\n\n:::: {.plan-code}\n::: {.plan}\n1. Make a filled-square image and compute edge magnitudes `v` and `h` with `sobel_v` and\n   its transpose.\n2. Run a corner detector built from two edge experts.\n:::\n\n::: {#corner-detector-values .cell execution_count=5}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: a corner detector built from two edge detectors\"}\n# [1]\nsquare = torch.zeros(28, 28)\nsquare[7:21, 7:21] = 1.0\nsobel_v = torch.tensor([[-1., 0., 1.], [-2., 0., 2.], [-1., 0., 1.]])\nv = F.conv2d(square[None, None], sobel_v[None, None], padding=1).abs()\nh = F.conv2d(square[None, None], sobel_v.T.contiguous()[None, None], padding=1).abs()\n\n# [2]\nexperts = torch.cat([v, h], dim=1)              # (1, 2, 28, 28): two reports\ncorner_k = torch.full((1, 2, 5, 5), 1 / 50)     # one kernel, spanning both\ncorners = F.conv2d(experts, corner_k, padding=2).squeeze()\n```\n:::\n\n\n::::\n\n::: {.cell execution_count=6}\n\n::: {.cell-output .cell-output-display}\n![Combining two edge maps by hand. The input is a 28×28 image of zeros whose central 14×14 block (rows and columns 7 to 20) is set to 1. Two first-layer channels compute edge energy, the absolute response to the vertical Sobel kernel and to its transpose, each with padding 1. One second-layer kernel of shape 2×5×5, every entry 1/50 (@eq-conv-layer with two input channels, padding 2), sums both edge maps over a local window, and its response is strongest near the square's four corners.](08-cnn_files/figure-pdf/fig-corner-detector-output-1.pdf){#fig-corner-detector fig-alt='Four grayscale panels progress from a filled square to vertical-edge energy, horizontal-edge energy, and their combined response. Only the last panel concentrates its brightest responses at all four corners.'}\n:::\n:::\n\n\nFor this square, the combined response is strongest near the corners, where both channels\nrespond. The kernel only sums local edge responses, so a sufficiently strong response in\neither channel could also produce a large output. In a trained CNN, the coefficients of these\ncombinations are learned from the task loss.\n\n::: {.callout-tip}\n## Modules and functional operations\n\n`nn.Conv2d` stores its kernels and biases as registered\nparameters. `F.conv2d` applies the operation using tensors\nsupplied as arguments. Both support differentiation: the first\nexperiment optimizes the kernel $K$ directly, while LeNet uses modules\nto organize its trainable parameters.\n:::\n\n## Padding and stride: controlling the output size {#padding-and-stride-the-bookkeeping-with-a-payoff}\n\n@sec-07-filters-convolution left a practical problem: a $k \\times k$ kernel on an $n \\times n$ image\nyields only $(n-k+1) \\times (n-k+1)$ outputs, because the window must stay inside the\nframe. For one layer this is a small loss. For a deep stack it is fatal: unpadded\n$5 \\times 5$ convolutions take a $28 \\times 28$ image to 24, 20, 16, 12, 8 and then 4 pixels\non a side, and a seventh layer would leave nothing.\n\nUnpadded convolution also treats pixels unequally. A pixel enters one dot product for every\nwindow position that covers it, and near the border there are fewer such positions: a corner\npixel is covered by a single window, an interior pixel by $k^2$. Border pixels therefore\ncontribute fewer terms to the output, and receive fewer gradient terms, than central ones.\n\nThe remedy is **padding**: a border of extra pixels, usually zeros, added around the input\nbefore the window slides. Padding serves two purposes. It decouples depth from shrinkage, so a\nnetwork can be deep without its feature maps vanishing. It also narrows the border imbalance:\nfor a $3 \\times 3$ kernel with one pixel of padding, a corner pixel enters 4 windows and an\nedge pixel 6, against 9 in the interior. For our $5 \\times 5$ kernels, a 2-pixel border keeps\na $28 \\times 28$ image at $28 \\times 28$, which is why the first convolutional layer above\nuses `padding=2`.\n\nSometimes we want to shrink a map on purpose: coarser maps cost less computation, and every\nlater window then covers more of the image. **Stride** moves the window $s$ pixels at a time\ninstead of one. A stride of 2 roughly halves each spatial dimension and divides the number of\nactivations by about four. A strided convolution downsamples with learned weights; pooling\ndownsamples with a fixed rule. Padding, kernel size and stride enter one formula:\n\n$$\nn_{\\text{out}} \\;=\\; \\left\\lfloor \\frac{n + 2p - k}{s} \\right\\rfloor + 1 .\n$$ {#eq-outsize}\n\nPadding restores the output positions that the window would otherwise lose; stride\nskips stops on purpose.\nThe numerator is the padded length minus the window, i.e. how far the window can\ntravel; dividing by the step and flooring counts the stops; $+1$ counts the starting\nposition. Three worked cases make the arithmetic visible:\n\n:::: {.plan-code}\n::: {.plan}\n1. Create a random 8×8 single-channel image `x8` as a batch of one.\n2. Implement the output-size formula, three regimes.\n:::\n\n::: {#shapes .cell execution_count=7}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: the output-size formula, three regimes\"}\n# [1]\nx8 = torch.randn(1, 1, 8, 8)\n# [2]\nfor p, s in [(0, 1), (1, 1), (1, 2)]:\n    out = F.conv2d(x8, torch.randn(1, 1, 3, 3), padding=p, stride=s)\n    n_out = (8 + 2 * p - 3) // s + 1\n    print(f\"n=8, k=3, p={p}, s={s}:  formula {n_out}  torch {tuple(out.shape[2:])}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nn=8, k=3, p=0, s=1:  formula 6  torch (6, 6)\nn=8, k=3, p=1, s=1:  formula 8  torch (8, 8)\nn=8, k=3, p=1, s=2:  formula 4  torch (4, 4)\n```\n:::\n:::\n\n\n::::\n## Pooling: trading exact location for local tolerance\n\n@sec-07-filters-convolution established that stride-one\nconvolution is translation-equivariant on the interior under\nmatched boundary rules: shifting the input shifts the feature map.\nFor classification, we also want the final decision to remain\nstable under the small, label-preserving shifts considered in @sec-06-generalization-inductive-bias.\n\n**Pooling** summarizes a neighborhood of each feature map\nwith one number. It reduces spatial resolution and can make some\nlocal rearrangements irrelevant to the pooled output. Whether\nthat produces useful shift tolerance depends on the activations,\nwindow alignment, and subsequent layers. Two summaries are common,\nand neither has parameters:\n\n- **Max pooling** keeps the largest activation in each window and discards\n  the rest.\n- **Average pooling** takes the mean of each window. The result is smoother,\n  but a single large activation is diluted by small neighbors.\n\n:::: {.plan-code}\n::: {.plan}\n1. Fill a 4×4 grid `t` with the values 0 through 15, row by row.\n2. Max and average pooling on a known grid.\n:::\n\n::: {#pooling .cell execution_count=8}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: max and average pooling on a known grid\"}\n# [1]\nt = torch.arange(16.).reshape(1, 1, 4, 4)\n# [2]\nprint(f\"input:\\n{t.squeeze()}\")\nprint(f\"max pool 2x2:\\n{F.max_pool2d(t, 2).squeeze()}\")\nprint(f\"avg pool 2x2:\\n{F.avg_pool2d(t, 2).squeeze()}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ninput:\ntensor([[ 0.,  1.,  2.,  3.],\n        [ 4.,  5.,  6.,  7.],\n        [ 8.,  9., 10., 11.],\n        [12., 13., 14., 15.]])\nmax pool 2x2:\ntensor([[ 5.,  7.],\n        [13., 15.]])\navg pool 2x2:\ntensor([[ 2.5000,  4.5000],\n        [10.5000, 12.5000]])\n```\n:::\n:::\n\n\n::::\nThe common configuration is the one above: $2 \\times 2$ windows with stride 2,\nnon-overlapping, halving each spatial dimension. Our LeNet uses max pooling. Exercise 4 compares it with average\npooling under the same training recipe.\n\nHow can this give local tolerance? Start with a deliberately clean construction in\nwhich max pooling removes the effect of a shift:\n\n:::: {.plan-code}\n::: {.plan}\n1. Place clues of 9 and 3 on a blank 4×4 `scene`, and build `shifted` with both moved\n   one pixel right.\n2. Run one constructed shift that pooling cannot see.\n:::\n\n::: {#pool-invariance .cell execution_count=9}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: one constructed shift that pooling cannot see\"}\n# [1]\nscene = torch.zeros(1, 1, 4, 4)\nscene[0, 0, 1, 0] = 9.0        # a strong clue, upper-left region\nscene[0, 0, 2, 2] = 3.0        # a weaker clue, lower-right region\n\nshifted = torch.zeros_like(scene)\nshifted[0, 0, 1, 1] = 9.0      # both clues moved one pixel right\nshifted[0, 0, 2, 3] = 3.0\n\n# [2]\nprint(f\"pooled original: {F.max_pool2d(scene,   2).squeeze().tolist()}\")\nprint(f\"pooled shifted:  {F.max_pool2d(shifted, 2).squeeze().tolist()}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\npooled original: [[9.0, 0.0], [0.0, 3.0]]\npooled shifted:  [[9.0, 0.0], [0.0, 3.0]]\n```\n:::\n:::\n\n\n::::\nBoth activations moved, yet these particular pooled maps are *identical*: each isolated\nmaximum stayed inside its $2 \\times 2$ window. That equality belongs to this\nconstruction, not to max pooling in general. A shift can change which values share a\nwindow, which maximum wins, or what crosses the boundary. Pooling can therefore absorb\nsome jitter, but the amount depends on the activations and alignment;\nwe test the complete network on shifted garments rather than assume\ntolerance.\n\n::: {.callout-warning}\n## Pooling reduces spatial detail\n\nPooling retains a coarse spatial grid while discarding information\nwithin each window. This can be useful when exact position is\nirrelevant to the task, but it can also remove distinctions needed\nfor recognition or localization. The choice of pooling operation\nand resolution therefore belongs in the experimental comparison.\n:::\n\n## Receptive fields grow with depth {#how-far-a-deep-neuron-sees}\n\nStacking has one more consequence: it resolves the tension @sec-06-generalization-inductive-bias\nleft us with. Every kernel here is tiny and local: $5 \\times 5$. Yet\nrecognizing a garment is a *global* judgment. Where does globality come from?\n\nFrom depth. A neuron in the first feature map depends on a $5 \\times 5$ patch of the image:\nits **receptive field**. A neuron one layer up depends on a $5 \\times 5$ patch *of feature\nmaps*, each pixel of which already summarizes a patch below $\\rightarrow$ its\nreceptive field on the original image is wider. Pooling accelerates this: after a\n$2\\times2$/stride-2 pool, neighboring pixels in the pooled map stand two original\npixels apart, so every later window covers twice the ground. For our upcoming network\nthe count runs: conv1 covers $5 \\times 5$ $\\rightarrow$ pooling nudges it to $6 \\times\n6$ $\\rightarrow$ conv2's $5\\times5$ window, at stride-2 spacing, expands it to $14\n\\times 14$ $\\rightarrow$ the final pool reaches $16 \\times 16$, over half the frame\nin every direction, using only $5 \\times 5$ kernels.\n\n::: {.cell execution_count=10}\n\n::: {.cell-output .cell-output-display}\n![Receptive fields by depth. Each box is the patch of the input that one unit depends on after a stage, drawn concentric for comparison. On the coat, the nested fields cross visible sleeves, torso, and boundary. One unit depends on a 5×5 patch after conv1, 6×6 after the first pool, 14×14 after conv2, and 16×16 after the final pool. Local wiring yields increasingly large fields; the dense head then combines all 25 overlapping final fields at once.](08-cnn_files/figure-pdf/fig-receptive-field-output-1.pdf){#fig-receptive-field fig-alt='Four nested outline boxes are drawn concentric on a coat image. Their side lengths grow from five pixels after the first convolution to six after the first pool, fourteen after the second convolution, and sixteen after the final pool. Convolution stages are drawn solid and pooling stages dotted.'}\n:::\n:::\n\n\nThis is the compositional hierarchy of @sec-03-nonlinearity-mlp, now encouraged by\nthe architecture. MLP layers also compose features. Convolution adds local\nconnectivity and spatial sharing to that composition, and growing receptive fields let\nlater layers compose earlier responses over larger regions. Learned channels often progress from edge-like patterns to\ntextures and parts, but the architecture does not force those human labels. The CNN\ncombines information across the frame gradually, through depth.^[Attention (@sec-13-attention)\ncombines information across the whole input in a single step, at a different cost.]\n\n## LeNet: the whole machine\n\nThe canonical blueprint is **LeNet**, Yann LeCun's digit-reading\nnetwork, and its rhythm is the CNN design pattern to this day: *convolve, shrink,\ndeepen; repeat; then decide.* Spatial size falls (28 $\\rightarrow$ 14 $\\rightarrow$ 5)\nwhile feature depth grows (1 $\\rightarrow$ 6 $\\rightarrow$ 16): the network trades\n\"where\" for \"what\" stage by stage, until a small dense head maps the final $16 \\times\n5 \\times 5$ summary to class scores.\n\n:::: {.plan-code}\n::: {.plan}\n1. LeNet.\n:::\n\n::: {#lenet .cell execution_count=11}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: LeNet\"}\n# [1]\nclass LeNet(nn.Module):\n    def __init__(self):\n        super().__init__()\n        self.conv1 = nn.Conv2d(1, 6, 5, padding=2)  # (N,1,28,28)->(N,6,28,28)\n        self.conv2 = nn.Conv2d(6, 16, 5)            # (N,6,14,14)->(N,16,10,10)\n        self.fc1 = nn.Linear(16 * 5 * 5, 120)\n        self.fc2 = nn.Linear(120, 84)\n        self.fc3 = nn.Linear(84, 10)\n\n    def forward(self, x: torch.Tensor) -> torch.Tensor:\n        x = F.max_pool2d(F.relu(self.conv1(x)), 2)   # -> (N, 6, 14, 14)\n        x = F.max_pool2d(F.relu(self.conv2(x)), 2)   # -> (N, 16, 5, 5)\n        x = x.flatten(1)                             # -> (N, 400)\n        x = F.relu(self.fc1(x))\n        x = F.relu(self.fc2(x))\n        return self.fc3(x)                           # logits, (N, 10)\n```\n:::\n\n\n::::\nEvery line is a tool we already own: @eq-conv-layer twice, @eq-outsize behind\nthe choice of `padding=2`, pooling twice, then @sec-03-nonlinearity-mlp's MLP as the\ndecision head. The\nconvolutional layers form the backbone, and `fc1` through `fc3` replace @sec-02-logistic-softmax's\nsingle linear head with a small MLP. Per @sec-02-logistic-softmax's advice, the model returns raw\nlogits and lets `F.cross_entropy` handle the probabilities.\n\n::: {.callout-note}\n## LeNet, then and now\n\nThe LeNet family (LeCun and colleagues, 1989–1998) began by reading handwritten ZIP\ncodes for the US Postal Service, and its mature form, LeNet-5, went on to read a\nsubstantial share of America's bank checks. Our variant keeps the classic\nskeleton but changes its internals: ReLU where the original used sigmoid-family activations\n(@sec-03-nonlinearity-mlp, @sec-05-backpropagation), max pooling where it used\nsubsampling based on averaging, Adam as the optimizer. Our later CNNs add one more\nmodern stabilizer, batch normalization, which we meet properly in @sec-09-modern-cnns-transfer.\n:::\n\nBefore training, we count the parameters: weight sharing in @sec-07-filters-convolution\nshould save many, and @sec-06-generalization-inductive-bias's MLP is the yardstick:\n\n:::: {.plan-code}\n::: {.plan}\n1. Define the reusable `make_mlp` helper.\n2. Instantiate a fresh `LeNet` and a fresh MLP from `make_mlp`.\n3. Parameter audit, LeNet vs. @sec-06-generalization-inductive-bias's MLP.\n:::\n\n::: {#params .cell execution_count=12}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: parameter audit, LeNet vs. Chapter 6's MLP\"}\n# [1]\ndef make_mlp() -> nn.Sequential:\n    return nn.Sequential(nn.Flatten(),\n                         nn.Linear(784, 256), nn.ReLU(), nn.Linear(256, 10))\n\n# [2]\nlenet, mlp = LeNet(), make_mlp()\n# [3]\nfor name, p in lenet.named_parameters():\n    print(f\"{name:14s} {str(tuple(p.shape)):16s} {p.numel():>7,}\")\nn_conv = sum(p.numel() for n, p in lenet.named_parameters() if \"conv\" in n)\nn_lenet = sum(p.numel() for p in lenet.parameters())\nn_mlp = sum(p.numel() for p in mlp.parameters())\nprint(f\"\\nLeNet: {n_lenet:,} parameters ({n_conv:,} of them convolutional)\")\nprint(f\"MLP:   {n_mlp:,} parameters\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nconv1.weight   (6, 1, 5, 5)         150\nconv1.bias     (6,)                   6\nconv2.weight   (16, 6, 5, 5)      2,400\nconv2.bias     (16,)                 16\nfc1.weight     (120, 400)        48,000\nfc1.bias       (120,)               120\nfc2.weight     (84, 120)         10,080\nfc2.bias       (84,)                 84\nfc3.weight     (10, 84)             840\nfc3.bias       (10,)                 10\n\nLeNet: 61,706 parameters (2,572 of them convolutional)\nMLP:   203,530 parameters\n```\n:::\n:::\n\n\n::::\nThese parameter counts can be read two ways. Against the MLP of @sec-06-generalization-inductive-bias,\nrebuilt here as `make_mlp` (the network of that chapter with an `nn.Flatten()` in front: 784\ninputs, 256 hidden ReLU units and 10 outputs), LeNet carries 61,706 parameters to the MLP's\n203,530 (less than a third) while performing far richer spatial computation. This is the saving\nthat @sec-07-filters-convolution's matrix view showed. Within LeNet, the two convolutional\nlayers, which compute the spatial features, hold 2,572 parameters (about 4%), and the dense\nhead holds the rest. We reduce that imbalance in @sec-09-modern-cnns-transfer, where modern\narchitectures go deeper in convolution and lighter in the head.\n\nNow train both models under one shared optimization recipe: same fitting split,\noptimizer, minibatch size, number of epochs, and therefore number of parameter updates.\nThe comparison does **not** match parameter count or floating-point work; a convolution\nand a dense layer spend different computation per update. Architecture is the intended\ndifference; compute is not controlled:\n\n:::: {.plan-code}\n::: {.plan}\n1. Define the reusable helpers: `train_model` and `accuracy`.\n2. Run one recipe, two architectures.\n3. Print train and validation accuracy for the MLP and for LeNet.\n:::\n\n::: {#train-both .cell execution_count=13}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: one recipe, two architectures\"}\nfrom dlbook.supervised import fit_supervised   # Listing 4.1\n\n# [1]\ndef train_model(\n    model_fn, X_fit: torch.Tensor = X_tr, y_fit: torch.Tensor = y_tr,\n    epochs: int = 150, batch: int = 128, seed: int = 6050\n) -> nn.Module:\n    # Listing 4.1 verbatim; this chapter's deltas are the budget (150\n    # epochs, batch 128) and, below, the models that get trained.\n    return fit_supervised(\n        model_fn, X_fit, y_fit, epochs=epochs, batch=batch, seed=seed\n    )\n\n@torch.no_grad()\ndef accuracy(model: nn.Module, X: torch.Tensor, y: torch.Tensor) -> float:\n    model.eval()\n    return (model(X).argmax(1) == y).float().mean().item()\n\n# [2]\nmlp = train_model(make_mlp)\nlenet = train_model(LeNet)\n# [3]\nfor name, model in [(\"MLP  \", mlp), (\"LeNet\", lenet)]:\n    print(f\"{name}  train {accuracy(model, X_tr, y_tr):.1%}   \"\n          f\"validation {accuracy(model, X_val, y_val):.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMLP    train 100.0%   validation 75.5%\nLeNet  train 99.5%   validation 74.5%\n```\n:::\n:::\n\n\n::::\nRead the clean-validation column: the MLP scores 75.5% and LeNet 74.5% in this\nsingle seeded run. A one-point difference is descriptive, not an uncertainty estimate,\nso it does not establish which architecture has higher expected clean accuracy.\nBoth models nearly interpolate the fitting split. Our small-data\nregime makes a narrower point: LeNet reaches comparable clean accuracy with less than a\nthird of the parameters. The shift experiment now compares the two models on shifted\ngarments.\n\n## LeNet under the two-pixel shift {#the-rematch}\n\nIn @sec-06-generalization-inductive-bias, shifting every validation image two pixels to the\nright took our MLP from 76.0% to 46.5% accuracy. We now give LeNet the same test. Retrained\nhere on LeNet's schedule, the MLP starts from 75.5% clean validation accuracy and LeNet from\n74.5%, so the two begin level. The question is whether the convolutional structure makes the\nclassifier more tolerant of the shift.\n\n:::: {.plan-code}\n::: {.plan}\n1. Define the reusable `shift_right` helper.\n2. Compute `acc_mlp` and `acc_cnn`, validation accuracy under right shifts of 0 to 4\n   pixels.\n3. Plot accuracy vs. shift, both models.\n:::\n\n::: {.cell execution_count=14}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: accuracy vs. shift, both models\"}\n# [1]\ndef shift_right(X: torch.Tensor, px: int) -> torch.Tensor:\n    out = torch.zeros_like(X)\n    if px == 0:\n        return X.clone()\n    out[..., px:] = X[..., :-px]\n    return out\n\n# [2]\nshifts = list(range(5))\nacc_mlp = [accuracy(mlp, shift_right(X_val, s), y_val) for s in shifts]\nacc_cnn = [accuracy(lenet, shift_right(X_val, s), y_val) for s in shifts]\n# [3]\nfor s in shifts:\n    print(f\"shift {s}px:   MLP {acc_mlp[s]:.1%}   LeNet {acc_cnn[s]:.1%}\")\n\nplt.figure(figsize=(5.5, 3.2))\nplt.plot(shifts, acc_mlp, \"o-\", color=\"#E57200\", lw=2, ms=7, label=\"MLP (Ch. 6)\")\nplt.plot(shifts, acc_cnn, \"s-\", color=\"#232D4B\", lw=2, ms=7, label=\"LeNet\")\nplt.axhline(0.1, ls=\":\", color=\"#B8B8A8\")\nplt.xlabel(\"shift (pixels right)\"); plt.ylabel(\"validation accuracy\")\nplt.ylim(0, 0.9); plt.xticks(shifts); plt.legend()\nplt.tight_layout(); plt.show()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nshift 0px:   MLP 75.5%   LeNet 74.5%\nshift 1px:   MLP 64.0%   LeNet 66.0%\nshift 2px:   MLP 42.0%   LeNet 57.5%\nshift 3px:   MLP 27.0%   LeNet 42.0%\nshift 4px:   MLP 18.5%   LeNet 23.0%\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![Validation accuracy under right shifts. Both architectures use the same optimizer schedule, though not matched compute. At two pixels the MLP falls from 75.5% to 42.0%, while LeNet falls from 74.5% to 57.5%. The dotted line is chance.](08-cnn_files/figure-pdf/fig-cliff-rematch-output-2.pdf){#fig-cliff-rematch fig-alt='Two accuracy curves decline as images shift right. They begin at similar clean accuracy, but the LeNet curve stays above the MLP curve at every nonzero shift; a dotted horizontal line marks chance.' fig-pos='H'}\n:::\n:::\n\n\n::::\nLeNet stays above the MLP at every nonzero shift, and the gap is largest at two and three\npixels. At one pixel the two are close, 66.0% for LeNet and 64.0% for the MLP. At two pixels\nthe MLP loses 33.5 points and LeNet 17.0; at three, LeNet scores 42.0% against 27.0%, and at\nfour, 23.0% against 18.5%. These numbers come from one deterministic validation split, not a\nsampling distribution, but the within-run contrast is large.\n\nThe comparison changes the complete architecture, so it does not isolate the contributions of\nlocality, weight sharing, pooling or the classifier head. Several operations can still\nintroduce shift sensitivity: cropping and padding affect the responses at the border, pooling\ndepends on window alignment, and the dense head gives each spatial position retained after\nflattening its own weights. @sec-09-modern-cnns-transfer replaces that position-sensitive\nhead with global pooling.\n\nIn @sec-06-generalization-inductive-bias, the MLP's first-layer weights were full-frame\ntemplates with broad, diffuse patterns. @fig-learned-filters shows the six $5 \\times 5$\nkernels of LeNet's first layer and, under each, its feature map after the ReLU on the coat\nof @fig-receptive-field, a validation image.\n\n:::: {.plan-code}\n::: {.plan}\n1. Extract first-layer kernels and their feature maps.\n:::\n\n::: {#learned-filter-values .cell execution_count=15}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: first-layer kernels and their feature maps\"}\n# [1]\nexample_index = 3                                   # the Figure 9.3 coat\nimg = X_val[example_index:example_index + 1]\nwith torch.no_grad():\n    fmaps = F.relu(lenet.conv1(img)).squeeze(0)     # (6, 28, 28)\nkernels = lenet.conv1.weight.detach().squeeze(1)    # (6, 5, 5)\n```\n:::\n\n\n::::\n\n::: {.cell execution_count=16}\n\n::: {.cell-output .cell-output-display}\n![What LeNet's first layer learned. Top: six first-layer 5×5 kernels (red positive, blue negative). Bottom: their feature maps on the coat of @fig-receptive-field, a validation image whose sleeves and torso make spatial responses easy to compare. The maps respond differently, but several kernels remain diffuse and should not be over-interpreted.](08-cnn_files/figure-pdf/fig-learned-filters-output-1.pdf){#fig-learned-filters fig-alt='Six small signed kernel heatmaps form the top row, and six larger activation maps for the same coat form the bottom row. The response maps emphasize different local regions even where the kernels remain diffuse.'}\n:::\n:::\n\n\nThe six local kernels produce distinct response maps on the same image. Some show directional\nstructure; others remain noisy enough that naming them as detectors would claim more than this\none run supports. Nobody designed them: they result from optimizer steps on the\nclassification loss, with gradients flowing backward through @eq-conv-layer.\n\n## One sealed test check\n\nWith both architectures, the optimizer schedule, the shift size and the two reported metrics\nfixed, we refit each model on all 1,200 development images with the same training budget, open\nthe 600-image test set once, and score each refit model on the clean test images and on the\nsame images shifted two pixels right. *Sealed* is chapter-local here: these 600 images also\nserve other chapters as an endpoint, as [the experiment\ninterlude](../interludes/learning-by-experiment.qmd) explains, but no choice in this chapter\nlooked at them.\n\n:::: {.plan-code}\n::: {.plan}\n1. Run one final test-set check.\n2. Print clean and two-pixel-shifted test accuracy for the refit MLP and LeNet.\n:::\n\n::: {#final-holdout .cell execution_count=17}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: one final test-set check\"}\n# [1]\nmlp_final = train_model(make_mlp, X_dev, y_dev)\nlenet_final = train_model(LeNet, X_dev, y_dev)\n# [2]\nfor name, model in [(\"MLP  \", mlp_final), (\"LeNet\", lenet_final)]:\n    print(f\"{name}  clean {accuracy(model, X_test, y_test):.1%}   \"\n          f\"shift-2 {accuracy(model, shift_right(X_test, 2), y_test):.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMLP    clean 82.2%   shift-2 41.8%\nLeNet  clean 82.5%   shift-2 62.3%\n```\n:::\n:::\n\n\n::::\nThe sealed check confirms the validation comparison. On clean test images the MLP scores\n82.2% and LeNet 82.5%, a descriptive 0.3-point gap from one seed. Under the predeclared\ntwo-pixel shift the MLP falls to 41.8% and LeNet to 62.3%, with less than a third of the\nMLP's parameters.\n\n::: {.callout-note}\n## Check yourself\n\nClose the book for one minute and rebuild the CNN.\n\n- Which kernel entries become learnable, and which convolutional structure remains built in?\n- What do channels, pooling, and receptive-field growth each contribute?\n- What does the shift comparison establish under this recipe, and why does it not isolate one architectural constraint?\n:::\n\n## Okay, so: the kernel became learnable\n\n1. **One change**: the kernel's numbers became parameters.\n   Gradient descent can recover a hand-crafted detector from data (our rigged game)\n   and, more importantly, learn kernels nobody designed, supervised only by the\n   task loss at the far end.\n2. **Channels turn one detector into many**: out-channels stack the feature maps\n   of several kernels; in-channels let each next-layer kernel combine all maps at once\n   (@eq-conv-layer).\n3. **Padding and stride are the shape budget**: $n_{\\text{out}} = \\lfloor (n + 2p -\n   k)/s \\rfloor + 1$ (@eq-outsize). Padding lets networks go deep without shrinking to\n   nothing; stride shrinks on purpose.\n4. **Pooling summarizes each window by one number**: max pooling keeps the largest\n   activation and discards its exact position within the window. Any resulting shift\n   tolerance depends on the activations, window alignment, and later layers.\n5. **Receptive fields grow with depth**: $5 \\rightarrow 6 \\rightarrow 14 \\rightarrow\n   16$ in our LeNet. Stacked local layers cover more of the frame at each stage. Like the MLP layers of @sec-03-nonlinearity-mlp,\n   they compose features, now with local connectivity and\n   spatial sharing.\n6. **The verdict**: on the sealed test set, one seed puts clean accuracy at 82.2% for\n   the MLP and 82.5% for LeNet; this does not establish an expected clean-accuracy\n   difference. Under the predeclared two-pixel shift, the same models score 41.8% and\n   62.3%. Under this training recipe, LeNet achieves higher accuracy on\n   the shifted images with fewer parameters. This compares the\n   two complete models, rather than isolating one architectural\n   constraint.\n\nMost of LeNet's parameters remain in its dense head, and its\naccuracy still declines under image shifts. The next chapter\nexamines smaller classifier heads, deeper convolutional networks,\nand the training choices needed to compare them.\n\n## Sources and further reading {.unnumbered}\n\n- LeCun et al.,\n  [\"Gradient-Based Learning Applied to Document Recognition\"](https://doi.org/10.1109/5.726791)\n  (1998): the primary LeNet account, including the architecture's document-recognition\n  setting.\n- Fukushima,\n  [\"Neocognitron: A Self-organizing Neural Network Model\"](https://doi.org/10.1007/BF00344251)\n  (1980): historical context for alternating feature extraction and spatial tolerance.\n- Zeiler and Fergus,\n  [\"Visualizing and Understanding Convolutional Networks\"](https://arxiv.org/abs/1311.2901)\n  (2014): methods and evidence for inspecting learned convolutional features without\n  over-reading a single filter image.\n- Dumoulin and Visin,\n  [\"A Guide to Convolution Arithmetic for Deep Learning\"](https://arxiv.org/abs/1603.07285)\n  (2016): a compact companion for checking convolution, pooling, and receptive-field\n  shapes.\n\n## Exercises {.unnumbered}\n\n1. **(Pencil.)** Run @eq-outsize through LeNet layer by layer, starting from $28\n   \\times 28$: verify every shape comment in the `LeNet` class, then verify the\n   parameter counts of `conv1` and `conv2` from the table (weights *and* biases).\n2. **(Pencil.)** Verify the receptive-field growth $5 \\rightarrow 6 \\rightarrow 14\n   \\rightarrow 16$. (Track two numbers per stage: the field size, and the *jump*, the\n   spacing in input pixels between neighboring units, which each stride-2 pool\n   doubles.) Then show that no convolutional or pooling unit in LeNet has a receptive field covering the\n   full $28 \\times 28$ frame. Where does globality finally enter the network?\n3. **(Code.)** Play the mystery-detector game with the $3 \\times 3$ blur kernel as\n   the target. Does gradient descent recover it as cleanly as Sobel? Now rerun with\n   only 8 training images instead of 256. What happens to the recovered kernel, and\n   what does that say about data volume versus parameter identifiability?\n4. **(Code.)** Swap LeNet's max pooling for average pooling and retrain. Compare\n   clean accuracy and the shift curve. Which changes more, and does the result match\n   the contrast drawn above between keeping the largest\n   activation and averaging the window?\n5. **(Pencil.)** The final dense head receives 25 spatial positions per feature map.\n   Explain why this can reintroduce shift sensitivity after equivariant convolutions.\n   Describe what information a position-insensitive head would keep and discard; we\n   will build one in @sec-09-modern-cnns-transfer.\n\n",
    "supporting": [
      "08-cnn_files/figure-pdf"
    ],
    "filters": []
  }
}