<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>10&nbsp; Sequences and Recurrence – Deep Learning: Making It Learnable</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/part3/11-encoder-decoder.html" rel="next">
<link href="../../chapters/part2/09-modern-cnns-transfer.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-7bbffa5cb1ba97d2e0b97962360040e5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>
  // Book math macros — keep in sync with tex/macros.tex (PDF path).
  // MathJax reads this config because it is defined before the MathJax
  // script loads (Quarto places include-in-header above its math script).
  window.MathJax = {
    tex: {
      macros: {
        E: "\\mathbb{E}",
        Ex: "\\operatorname{E}",
        var: "\\operatorname{Var}",
        cov: "\\operatorname{Cov}",
        imp: "\\Rightarrow",
        argmax: "\\operatorname*{arg\\,max}",
        argmin: "\\operatorname*{arg\\,min}",
        norm: ["\\left\\lVert#1\\right\\rVert", 1],
        vect: ["\\mathbf{#1}", 1],
        matr: ["\\mathbf{#1}", 1],
        R: "\\mathbb{R}",
        dd: "\\mathrm{d}",
        loss: "\\mathcal{L}"
      }
    }
  };
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/part3/10-sequences-rnn.html">III · Sequences</a></li><li class="breadcrumb-item"><a href="../../chapters/part3/10-sequences-rnn.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Sequences and Recurrence</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Deep Learning: Making It Learnable</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/Shakeri-Lab/dl-book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">I · From Lines to Networks</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/01-linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Linear Regression, the Mother Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/02-logistic-softmax.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Linear Models that Classify: Logistic and Softmax</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/03-nonlinearity-mlp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Nonlinearity and the MLP</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/04-training-loss-sgd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Training: Loss and Stochastic Gradient Descent</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/05-backpropagation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Backpropagation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/06-generalization-inductive-bias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">When It Fails: Generalization in Pictures, and Inductive Bias</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">II · Vision: Learning the Filters</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/07-filters-convolution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Filters and Convolution (Fixed Kernels)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/08-cnn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">CNNs: Making the Filters Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/09-modern-cnns-transfer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Modern CNNs and Transfer Learning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">III · Sequences</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part3/10-sequences-rnn.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Sequences and Recurrence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part3/11-encoder-decoder.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Encoder–Decoder, Teacher Forcing, Beam Search</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">IV · Attention: Learning the Similarity</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/12-kernel-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Kernel Regression: Attention Before It Was Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/13-attention.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Attention: Making the Kernel Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/14-self-attention-transformer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Self-Attention and the Transformer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/15-bert-pretraining.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">The BERT Moment: Pretraining as the New Regime</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/16-vit-scaling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Vision Transformers and Scaling Laws</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">V · The Pretrained Era</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/17-peft-quantization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Adapting Pretrained Models: Prompting, PEFT, Quantization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/18-alignment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Alignment and RL Fine-Tuning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/19-generative.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Generative Models: From PCA to Diffusion</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a1-linear-algebra.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Linear Algebra and the SVD</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a2-tensors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Tensors in Practice</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a3-notation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Notation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a4-floating-point.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Floating Point and Machine Precision</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#stretching-the-old-toolkit" id="toc-stretching-the-old-toolkit" class="nav-link active" data-scroll-target="#stretching-the-old-toolkit"><span class="header-section-number">10.1</span> Stretching the old toolkit</a></li>
  <li><a href="#a-network-with-a-loop" id="toc-a-network-with-a-loop" class="nav-link" data-scroll-target="#a-network-with-a-loop"><span class="header-section-number">10.2</span> A network with a loop</a></li>
  <li><a href="#blame-through-time" id="toc-blame-through-time" class="nav-link" data-scroll-target="#blame-through-time"><span class="header-section-number">10.3</span> Blame through time</a>
  <ul class="collapse">
  <li><a href="#training-with-a-finite-horizon" id="toc-training-with-a-finite-horizon" class="nav-link" data-scroll-target="#training-with-a-finite-horizon">Training with a finite horizon</a></li>
  </ul></li>
  <li><a href="#engineering-a-memory-the-lstm" id="toc-engineering-a-memory-the-lstm" class="nav-link" data-scroll-target="#engineering-a-memory-the-lstm"><span class="header-section-number">10.4</span> Engineering a memory: the LSTM</a>
  <ul class="collapse">
  <li><a href="#the-memory-test" id="toc-the-memory-test" class="nav-link" data-scroll-target="#the-memory-test">The memory test</a></li>
  </ul></li>
  <li><a href="#gru-the-streamlined-cousin" id="toc-gru-the-streamlined-cousin" class="nav-link" data-scroll-target="#gru-the-streamlined-cousin"><span class="header-section-number">10.5</span> GRU: the streamlined cousin</a></li>
  <li><a href="#the-book-reads-itself" id="toc-the-book-reads-itself" class="nav-link" data-scroll-target="#the-book-reads-itself"><span class="header-section-number">10.6</span> The book reads itself</a></li>
  <li><a href="#what-a-fixed-size-state-cannot-hold" id="toc-what-a-fixed-size-state-cannot-hold" class="nav-link" data-scroll-target="#what-a-fixed-size-state-cannot-hold"><span class="header-section-number">10.7</span> What a fixed-size state cannot hold</a></li>
  <li><a href="#okay-so" id="toc-okay-so" class="nav-link" data-scroll-target="#okay-so"><span class="header-section-number">10.8</span> Okay, so —</a></li>
  <li><a href="#sources-and-further-reading" id="toc-sources-and-further-reading" class="nav-link" data-scroll-target="#sources-and-further-reading">Sources and further reading</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/Shakeri-Lab/dl-book/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/part3/10-sequences-rnn.html">III · Sequences</a></li><li class="breadcrumb-item"><a href="../../chapters/part3/10-sequences-rnn.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Sequences and Recurrence</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-10-sequences-rnn" class="quarto-section-identifier"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Sequences and Recurrence</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<!-- lecture-source: m07_lecture-7-recurrent-neural-networks_qyU35PKg_NE.txt,
     m07_lecture-7-2-recurrent-neural-networks-part-2__2NGDmVNUrM.txt,
     [coding]_m07_lecture-7-3-recurrent-neural-networks-part-3_Az0K6fyf-X4.txt
     (spine via ds6050_07_rnn/MODULE_NOTES.md)
     seeds: sources/7.1-RNN-v3.tex (§Naive/Shared-weight RNN, §VEGP, §Truncated BPTT,
            §From RNN to LSTM: design-by-constraints, §Case Study long-term
            dependency, §GRU)
     note: the lecture motivates RNNs against Module 6's autoencoders; the book has
           not met autoencoders yet (@sec-19-generative), so the opening motivates
           from the book's own Part II toolkit instead. Same destination. -->
<p>Part II taught machines to see, and every trick in it leaned on one fact about images: an image arrives <em>all at once</em>, at a fixed size. This part is about data that refuses both conditions. Text, audio, sensor streams, stock prices — they come one piece at a time, they stop whenever they please, and their meaning lives in the <em>order</em> of the pieces.</p>
<p>Order deserves a moment, because the book has been here before with the opposite verdict. Chapter 6 shuffled every pixel with one fixed permutation and retrained the MLP to the same accuracy: because that coordinate map was invertible, the first-layer weights could absorb it. The trained MLP was still position-specific; it was not a bag model. Now shuffle the words of <em>this sentence</em> and read it back. For sequences, no single compensating remap preserves arbitrary order — order is most of the signal. We need models whose computation represents it explicitly.</p>
<section id="stretching-the-old-toolkit" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="stretching-the-old-toolkit"><span class="header-section-number">10.1</span> Stretching the old toolkit</h2>
<p>Before building anything new, the book’s habit: try what we own.</p>
<p><strong>A window.</strong> Predict the next element from the last <span class="math inline">\(k\)</span>: slide a width-<span class="math inline">\(k\)</span> window along the sequence and feed each snapshot to an MLP. This should feel familiar twice over: it is autoregression, and the <em>sliding</em> is Chapter 7’s one-dimensional convolution — locality, transplanted from space to time. Windows are genuinely useful (they power real forecasting systems), but they inherit locality’s blind spot: anything older than <span class="math inline">\(k\)</span> steps ago does not exist. Widen <span class="math inline">\(k\)</span> and the parameter count grows with it, yet no finite window survives the sentence “The company whose first-day price we recorded back in January finally …”. Context has no fixed radius.</p>
<p><strong>A function per timestep.</strong> Then let the model change over time: learn <span class="math inline">\(f_1\)</span> for step one, <span class="math inline">\(f_2\)</span> for step two, each passing a summary forward. The lecture builds this strawman carefully, because its failure names the cure. The parameter count now grows with sequence <em>length</em>; a length-500 essay needs 500 learned functions; and the model is <strong>non-stationary</strong> — it insists the rules of language at position 17 differ from the rules at position 18, when the whole point of language is that they do not.</p>
<p>You have watched this book face that exact configuration twice. A template for every image position was wasteful and brittle <span class="math inline">\(\rightarrow\)</span> share the kernel across space (<a href="../part2/07-filters-convolution.html" class="quarto-xref"><span>Chapter 7</span></a>). A detector per location was the wrong prior <span class="math inline">\(\rightarrow\)</span> share it (<a href="../part2/08-cnn.html" class="quarto-xref"><span>Chapter 8</span></a>). The move is the same here, and it is the chapter’s one big idea: <strong>share the function across time</strong>,</p>
<p><span id="eq-recurrence"><span class="math display">\[
\vect{h}_t = f(\vect{h}_{t-1}, \vect{x}_t),
\tag{10.1}\]</span></span></p>
<p>one learned rule <span class="math inline">\(f\)</span>, applied at every step, carrying a running summary <span class="math inline">\(\vect{h}_t\)</span> — the <strong>hidden state</strong> — from each step to the next. This is the book’s third weight sharing: across examples (every chapter since the first), across space (Part II), and now across <em>time</em>. Stationarity is to sequences what translation equivariance was to images: the same pattern means the same thing whenever it occurs.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The hidden state is a running memory — and a Markov claim
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(\vect{h}_t\)</span> is whatever <span class="math inline">\(f\)</span> chooses to remember about everything seen so far, compressed into one fixed-size vector. Feeding it back in makes a claim with a classical name, the <strong>Markov property</strong>: <span class="math inline">\(\vect{h}_{t-1}\)</span> and <span class="math inline">\(\vect{x}_t\)</span> together contain everything needed for the next step. Nothing else from the past gets a second look. That claim buys streaming (process tokens as they arrive), any sequence length (the loop doesn’t care), and — later in this chapter — the license to train on chopped-up chunks. Its price is that the memory is <em>finite</em>, and this part of the book ends when we finally refuse to pay that price (<a href="../part4/12-kernel-regression.html" class="quarto-xref"><span>Chapter 12</span></a>).</p>
</div>
</div>
</section>
<section id="a-network-with-a-loop" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="a-network-with-a-loop"><span class="header-section-number">10.2</span> A network with a loop</h2>
<p>The simplest choice of <span class="math inline">\(f\)</span> is Chapter 3’s recipe with the state concatenated in: a linear map of <span class="math inline">\((\vect{h}_{t-1}, \vect{x}_t)\)</span>, squashed by a <span class="math inline">\(\tanh\)</span>:</p>
<p><span id="eq-rnn-cell"><span class="math display">\[
\vect{h}_t \;=\; \tanh\!\left(\matr{W}_{hh}\,\vect{h}_{t-1} + \matr{W}_{xh}\,\vect{x}_t + \vect{b}_h\right),
\qquad
\vect{o}_t \;=\; \matr{W}_{hq}\,\vect{h}_t + \vect{b}_q ,
\tag{10.2}\]</span></span></p>
<p>the <strong>vanilla recurrent neural network</strong>. Three weight matrices total, reused at every step, regardless of whether the sequence has five tokens or five thousand. The readout <span class="math inline">\(\vect{o}_t\)</span> produces logits — Chapter 2’s machinery — and you can collect one at every step (predicting each next character, labeling each word) or only at the end (classifying the whole sequence); both designs appear below.</p>
<p>Per the book’s habit, build the loop by hand, then verify against the framework:</p>
<div id="setup-and-manual-rnn" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Code: the recurrence, written as the loop it is</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.nn <span class="im">as</span> nn</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.nn.functional <span class="im">as</span> F</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>torch.manual_seed(<span class="dv">6050</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>V, H, T, B <span class="op">=</span> <span class="dv">8</span>, <span class="dv">16</span>, <span class="dv">12</span>, <span class="dv">4</span>                       <span class="co"># vocab, hidden, time, batch</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>rnn <span class="op">=</span> nn.RNN(V, H, batch_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> torch.randn(B, T, V)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>out_ref, _ <span class="op">=</span> rnn(x)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>W_xh, W_hh <span class="op">=</span> rnn.weight_ih_l0, rnn.weight_hh_l0</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>b <span class="op">=</span> rnn.bias_ih_l0 <span class="op">+</span> rnn.bias_hh_l0</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>h <span class="op">=</span> torch.zeros(B, H)                            <span class="co"># h_0 = 0, the standard start</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>outs <span class="op">=</span> []</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> t <span class="kw">in</span> <span class="bu">range</span>(T):                               <span class="co"># the loop IS the architecture</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    h <span class="op">=</span> torch.tanh(x[:, t] <span class="op">@</span> W_xh.T <span class="op">+</span> h <span class="op">@</span> W_hh.T <span class="op">+</span> b)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    outs.append(h)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>manual <span class="op">=</span> torch.stack(outs, <span class="dv">1</span>)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"manual loop vs. nn.RNN: max |diff| = </span><span class="sc">{</span>(manual <span class="op">-</span> out_ref)<span class="sc">.</span><span class="bu">abs</span>()<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.1e}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>manual loop vs. nn.RNN: max |diff| = 1.2e-07</code></pre>
</div>
</div>
<p>Notice what the shapes say. <code>nn.RNN</code> eats <code>(batch, time, features)</code> — a third axis has joined Chapter 8’s NCHW discipline — and the loop runs over that middle axis carrying <code>h</code> along. Unroll the loop on paper and the RNN is an ordinary feed-forward network that happens to be <span class="math inline">\(T\)</span> layers deep with every layer’s weights tied. Hold that thought; it is about to matter enormously.</p>
</section>
<section id="blame-through-time" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="blame-through-time"><span class="header-section-number">10.3</span> Blame through time</h2>
<p>Tied depth means Chapter 5’s rules apply verbatim. To train on a sequence, run the loop forward, collect losses at the readouts, and backpropagate through the <em>unrolled</em> network, a procedure called <strong>backpropagation through time</strong> (BPTT). Blame that lands on <span class="math inline">\(\vect{h}_T\)</span> must travel back through every application of <a href="#eq-rnn-cell" class="quarto-xref">Equation&nbsp;<span>10.2</span></a> to reach an early input. Define <span class="math inline">\(\matr{D}_t = \mathrm{diag}\!\left(\tanh'(\cdot)\right)\)</span> at step <span class="math inline">\(t\)</span>. The forward Jacobian for one hop is <span class="math inline">\(\matr{D}_t\matr{W}_{hh}\)</span>, so the full Jacobian is</p>
<p><span id="eq-bptt"><span class="math display">\[
\frac{\partial \vect{h}_T}{\partial \vect{h}_1}
= (\matr{D}_T\matr{W}_{hh})\cdots
  (\matr{D}_2\matr{W}_{hh}),
\qquad
\vect{g}_{t-1}=\matr{W}_{hh}^{\!\top}\matr{D}_t\vect{g}_t .
\tag{10.3}\]</span></span></p>
<p>A product of <span class="math inline">\(T\)</span> near-identical matrices. The second expression shows the reverse-mode order explicitly: the derivative gate acts on incoming blame, then <span class="math inline">\(\matr{W}_{hh}^{\top}\)</span> carries it to the previous state. Chapter 5 taught you to fear this shape. If the factors shrink the signal, the product dies exponentially; if they grow it, it explodes exponentially. Since <span class="math inline">\(\tanh' \le 1\)</span> and <span class="math inline">\(\matr{W}_{hh}\)</span> repeats at every step, keeping every relevant direction near unit gain over a long sequence is a fragile special case. Depth was measured in layers there; here it is measured in <em>time</em>, and a paragraph of text is a hundred layers deep. Watch the collapse, in the spirit of Chapter 5’s depth experiment:</p>
<div id="cell-fig-vanishing-time" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code: gradient reaching the first input vs.&nbsp;lag</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> grad_at_first_input(rec: nn.Module, lags: <span class="bu">list</span>[<span class="bu">int</span>],</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>                        vocab: <span class="bu">int</span> <span class="op">=</span> <span class="dv">4</span>) <span class="op">-&gt;</span> <span class="bu">list</span>[<span class="bu">float</span>]:</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    norms <span class="op">=</span> []</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> T <span class="kw">in</span> lags:</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>        generator <span class="op">=</span> torch.Generator().manual_seed(<span class="dv">100</span> <span class="op">+</span> T)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> torch.randn(<span class="dv">8</span>, T, vocab, generator<span class="op">=</span>generator, requires_grad<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>        o, _ <span class="op">=</span> rec(x)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>        o[:, <span class="op">-</span><span class="dv">1</span>].<span class="bu">sum</span>().backward()</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>        norms.append(x.grad[:, <span class="dv">0</span>].norm().item())    <span class="co"># blame on input #1</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> norms</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>lags <span class="op">=</span> [<span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">40</span>, <span class="dv">60</span>]</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>torch.manual_seed(<span class="dv">0</span>)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>vanilla <span class="op">=</span> nn.RNN(<span class="dv">4</span>, <span class="dv">32</span>, batch_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>g_rnn <span class="op">=</span> grad_at_first_input(vanilla, lags)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"lag:      "</span> <span class="op">+</span> <span class="st">"   "</span>.join(<span class="ss">f"</span><span class="sc">{</span>l<span class="sc">:&gt;7d}</span><span class="ss">"</span> <span class="cf">for</span> l <span class="kw">in</span> lags))</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"|grad|:   "</span> <span class="op">+</span> <span class="st">"   "</span>.join(<span class="ss">f"</span><span class="sc">{</span>g<span class="sc">:.1e}</span><span class="ss">"</span> <span class="cf">for</span> g <span class="kw">in</span> g_rnn))</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="fl">6.2</span>, <span class="fl">3.2</span>))</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>plt.semilogy(lags, g_rnn, <span class="st">"o-"</span>, color<span class="op">=</span><span class="st">"#E57200"</span>, ms<span class="op">=</span><span class="dv">5</span>, label<span class="op">=</span><span class="st">"vanilla RNN"</span>)</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"lag $T$ between output and first input"</span>)</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="vs">r"</span><span class="dv">$</span><span class="ch">\|</span><span class="er">\</span><span class="vs">partial L / </span><span class="er">\</span><span class="vs">partial </span><span class="dv">\m</span><span class="vs">athbf{x}_1</span><span class="ch">\|</span><span class="dv">$</span><span class="vs">"</span>)</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>plt.legend()<span class="op">;</span> plt.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>lag:            1         5        10        20        40        60
|grad|:   2.9e+00   6.8e-01   2.6e-02   7.2e-05   3.4e-10   1.1e-15</code></pre>
</div>
<div class="cell-output cell-output-display">
<div id="fig-vanishing-time" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-vanishing-time-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-sequences-rnn_files/figure-html/fig-vanishing-time-output-2.png" width="584" height="297" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-vanishing-time-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.1: How much a freshly initialized vanilla RNN’s output can blame its first input, as the lag between them grows. Fifteen orders of magnitude gone by sixty steps: the same exponential decay Chapter 5 measured down a deep network, now measured across time — because an unrolled RNN <em>is</em> a deep network with tied weights.
</figcaption>
</figure>
</div>
</div>
</div>
<p>By lag 60 the gradient reaching the first input is <span class="math inline">\(10^{-15}\)</span>: at initialization, whatever happened at the start supplies almost no usable learning signal. That makes success fragile rather than mathematically impossible — a later experiment catches one lucky seed. The mirror-image failure, explosion, is just as real — one large spike in <a href="#eq-bptt" class="quarto-xref">Equation&nbsp;<span>10.3</span></a>’s product can make an update destabilize training.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Gradient clipping is a seatbelt, not a cure
</div>
</div>
<div class="callout-body-container callout-body">
<p>Practice handles explosion with <strong>gradient clipping</strong>: if the gradient’s norm exceeds a threshold, rescale it down to the threshold before stepping (<code>nn.utils.clip_grad_norm_</code> — it appears in every training loop below). The lecture is blunt about what this buys: it tames the spikes so training survives, at the cost of damping legitimately large steps — and it does <em>nothing</em> for vanishing. You cannot clip your way to a longer memory.</p>
</div>
</div>
<section id="training-with-a-finite-horizon" class="level3">
<h3 class="anchored" data-anchor-id="training-with-a-finite-horizon">Training with a finite horizon</h3>
<p>BPTT has a second, blunter problem: unrolling a book-length sequence costs book-length memory and compute per step. The standard fix leans on the Markov claim from the callout above. In <strong>truncated BPTT</strong>, contiguous chunks carry the recurrent state forward but detach it at each boundary. The values cross the boundary; the gradient graph does not. This bounds memory while preserving running context.</p>
<p>The final experiment below uses a simpler finite-horizon recipe: it samples random 100-character windows and starts each from zero state. That is <strong>fixed-window training</strong>, not truncated BPTT, because no state is carried between windows. It is cheap and appropriate for this small demonstration, but the model can neither see nor learn dependencies beyond 100 characters. In production character models, contiguous chunks of roughly 20–50 steps with carried-and-detached state are common. In either recipe, clipping handles spikes; neither creates gradients beyond the truncation horizon.</p>
</section>
</section>
<section id="engineering-a-memory-the-lstm" class="level2" data-number="10.4">
<h2 data-number="10.4" class="anchored" data-anchor-id="engineering-a-memory-the-lstm"><span class="header-section-number">10.4</span> Engineering a memory: the LSTM</h2>
<p>So the vanilla RNN’s memory dies of repeated multiplication. The seed notes stage the fix as a design-by-constraints exercise, and it is worth walking, because you already own its key move. We want a memory pathway that is:</p>
<ol type="1">
<li><strong>Preserved by default.</strong> Repeated <em>multiplication</em> killed the signal <span class="math inline">\(\rightarrow\)</span> make the carried state <strong>additive</strong>: <span class="math inline">\(\vect{c}_t = \vect{c}_{t-1} + \Delta_t\)</span>. A conveyor belt: information rides along untouched unless something deliberately intervenes. You met this exact maneuver one chapter ago — <a href="../part2/09-modern-cnns-transfer.html" class="quarto-xref"><span>Chapter 9</span></a>’s residual connection, <span class="math inline">\(H(x) = F(x) + x\)</span>, whose Jacobian’s identity term let gradients cross forty layers. Same trick, laid across time.</li>
<li><strong>Forgettable on command.</strong> Memory is finite; some of it should expire. Install a valve: <span class="math inline">\(\vect{f}_t \in (0,1)\)</span> multiplying <span class="math inline">\(\vect{c}_{t-1}\)</span>.</li>
<li><strong>Writable on command.</strong> New information enters through a second valve <span class="math inline">\(\vect{i}_t\)</span> scaling a candidate <span class="math inline">\(\tilde{\vect{c}}_t\)</span>.</li>
<li><strong>Readable on command.</strong> Expose only what the current step needs, through a third valve <span class="math inline">\(\vect{o}_t\)</span>.</li>
</ol>
<p>Each valve is a small learned layer squashed by a sigmoid — Chapter 2’s machine, reinterpreted: a number in <span class="math inline">\((0,1)\)</span> read as <em>what fraction passes</em>. The candidate content is shaped by <span class="math inline">\(\tanh\)</span>, keeping it bounded and centered. Assembled, this is the <strong>Long Short-Term Memory</strong> cell (Hochreiter &amp; Schmidhuber, 1997):</p>
<p><span id="eq-lstm"><span class="math display">\[
\begin{aligned}
\vect{f}_t &amp;= \sigma\!\left(\matr{W}_f\,[\vect{h}_{t-1}, \vect{x}_t] + \vect{b}_f\right)
&amp;\quad
\vect{i}_t &amp;= \sigma\!\left(\matr{W}_i\,[\vect{h}_{t-1}, \vect{x}_t] + \vect{b}_i\right)
\\
\tilde{\vect{c}}_t &amp;= \tanh\!\left(\matr{W}_c\,[\vect{h}_{t-1}, \vect{x}_t] + \vect{b}_c\right)
&amp;\quad
\vect{o}_t &amp;= \sigma\!\left(\matr{W}_o\,[\vect{h}_{t-1}, \vect{x}_t] + \vect{b}_o\right)
\\[2pt]
\vect{c}_t &amp;= \vect{f}_t \odot \vect{c}_{t-1} \;+\; \vect{i}_t \odot \tilde{\vect{c}}_t
&amp;\quad
\vect{h}_t &amp;= \vect{o}_t \odot \tanh(\vect{c}_t).
\end{aligned}
\tag{10.4}\]</span></span></p>
<div id="cell-fig-lstm-conveyor" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code: draw the LSTM conveyor belt and its three gates</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib.patches <span class="im">import</span> FancyBboxPatch, Circle</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">7.4</span>, <span class="fl">3.3</span>))</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>ax.set_xlim(<span class="dv">0</span>, <span class="dv">11</span>)<span class="op">;</span> ax.set_ylim(<span class="dv">0</span>, <span class="dv">5</span>)<span class="op">;</span> ax.axis(<span class="st">"off"</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> gate_box(x: <span class="bu">float</span>, y: <span class="bu">float</span>, label: <span class="bu">str</span>,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>             color: <span class="bu">str</span> <span class="op">=</span> <span class="st">"#F9DCBF"</span>) <span class="op">-&gt;</span> <span class="va">None</span>:</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    patch <span class="op">=</span> FancyBboxPatch((x <span class="op">-</span> <span class="fl">0.42</span>, y <span class="op">-</span> <span class="fl">0.32</span>), <span class="fl">0.84</span>, <span class="fl">0.64</span>,</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>                           boxstyle<span class="op">=</span><span class="st">"round,pad=0.06"</span>, facecolor<span class="op">=</span>color,</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>                           edgecolor<span class="op">=</span><span class="st">"#232D4B"</span>, linewidth<span class="op">=</span><span class="fl">1.2</span>)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    ax.add_patch(patch)</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>    ax.text(x, y, label, ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> operation(x: <span class="bu">float</span>, y: <span class="bu">float</span>, symbol: <span class="bu">str</span>) <span class="op">-&gt;</span> <span class="va">None</span>:</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>    patch <span class="op">=</span> Circle((x, y), <span class="fl">0.25</span>, facecolor<span class="op">=</span><span class="st">"white"</span>,</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>                   edgecolor<span class="op">=</span><span class="st">"#E57200"</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>)</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>    ax.add_patch(patch)</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>    ax.text(x, y, symbol, ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>ax.text(<span class="fl">0.45</span>, <span class="fl">3.6</span>, <span class="st">"$c_{t-1}$"</span>, ha<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">11</span>)</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>gate_box(<span class="fl">2.1</span>, <span class="fl">3.6</span>, <span class="st">"$f_t$"</span>)</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>operation(<span class="fl">3.2</span>, <span class="fl">3.6</span>, <span class="vs">r"</span><span class="dv">$</span><span class="ch">\t</span><span class="vs">imes</span><span class="dv">$</span><span class="vs">"</span>)</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>operation(<span class="fl">6.8</span>, <span class="fl">3.6</span>, <span class="st">"+"</span>)</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>ax.text(<span class="fl">10.45</span>, <span class="fl">3.6</span>, <span class="st">"$c_t$"</span>, ha<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">11</span>)</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>ax.annotate(<span class="st">""</span>, (<span class="fl">1.62</span>, <span class="fl">3.6</span>), (<span class="fl">0.85</span>, <span class="fl">3.6</span>), arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>, lw<span class="op">=</span><span class="dv">2</span>, color<span class="op">=</span><span class="st">"#E57200"</span>))</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>ax.annotate(<span class="st">""</span>, (<span class="fl">2.95</span>, <span class="fl">3.6</span>), (<span class="fl">2.52</span>, <span class="fl">3.6</span>), arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>, lw<span class="op">=</span><span class="dv">2</span>, color<span class="op">=</span><span class="st">"#E57200"</span>))</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>ax.annotate(<span class="st">""</span>, (<span class="fl">6.55</span>, <span class="fl">3.6</span>), (<span class="fl">3.45</span>, <span class="fl">3.6</span>), arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>, lw<span class="op">=</span><span class="dv">2</span>, color<span class="op">=</span><span class="st">"#E57200"</span>))</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>ax.annotate(<span class="st">""</span>, (<span class="fl">10.05</span>, <span class="fl">3.6</span>), (<span class="fl">7.05</span>, <span class="fl">3.6</span>), arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>, lw<span class="op">=</span><span class="dv">2</span>, color<span class="op">=</span><span class="st">"#E57200"</span>))</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>ax.text(<span class="fl">0.9</span>, <span class="fl">1.0</span>, <span class="st">"$[h_{t-1},x_t]$"</span>, ha<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>gate_box(<span class="fl">3.0</span>, <span class="fl">1.55</span>, <span class="st">"$i_t$"</span>)</span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>gate_box(<span class="fl">3.0</span>, <span class="fl">0.55</span>, <span class="vs">r"</span><span class="dv">$</span><span class="ch">\t</span><span class="vs">ilde{c}_t</span><span class="dv">$</span><span class="vs">"</span>, <span class="st">"#E8F0F8"</span>)</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>operation(<span class="fl">4.35</span>, <span class="fl">1.05</span>, <span class="vs">r"</span><span class="dv">$</span><span class="ch">\t</span><span class="vs">imes</span><span class="dv">$</span><span class="vs">"</span>)</span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>ax.annotate(<span class="st">""</span>, (<span class="fl">2.55</span>, <span class="fl">1.55</span>), (<span class="fl">1.45</span>, <span class="fl">1.12</span>), arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>, lw<span class="op">=</span><span class="fl">1.3</span>, color<span class="op">=</span><span class="st">"#232D4B"</span>))</span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a>ax.annotate(<span class="st">""</span>, (<span class="fl">2.55</span>, <span class="fl">0.55</span>), (<span class="fl">1.45</span>, <span class="fl">0.92</span>), arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>, lw<span class="op">=</span><span class="fl">1.3</span>, color<span class="op">=</span><span class="st">"#232D4B"</span>))</span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a>ax.annotate(<span class="st">""</span>, (<span class="fl">4.1</span>, <span class="fl">1.15</span>), (<span class="fl">3.45</span>, <span class="fl">1.55</span>), arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>, lw<span class="op">=</span><span class="fl">1.3</span>, color<span class="op">=</span><span class="st">"#232D4B"</span>))</span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a>ax.annotate(<span class="st">""</span>, (<span class="fl">4.1</span>, <span class="fl">0.95</span>), (<span class="fl">3.45</span>, <span class="fl">0.55</span>), arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>, lw<span class="op">=</span><span class="fl">1.3</span>, color<span class="op">=</span><span class="st">"#232D4B"</span>))</span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a>ax.plot([<span class="fl">4.6</span>, <span class="fl">6.8</span>, <span class="fl">6.8</span>], [<span class="fl">1.05</span>, <span class="fl">1.05</span>, <span class="fl">3.35</span>], color<span class="op">=</span><span class="st">"#232D4B"</span>, lw<span class="op">=</span><span class="fl">1.5</span>)</span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a>ax.annotate(<span class="st">""</span>, (<span class="fl">6.8</span>, <span class="fl">3.35</span>), (<span class="fl">6.8</span>, <span class="fl">2.65</span>), arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>, lw<span class="op">=</span><span class="fl">1.5</span>, color<span class="op">=</span><span class="st">"#232D4B"</span>))</span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a>gate_box(<span class="fl">8.55</span>, <span class="fl">1.45</span>, <span class="st">"$o_t$"</span>)</span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a>gate_box(<span class="fl">8.55</span>, <span class="fl">2.45</span>, <span class="vs">r"</span><span class="dv">$</span><span class="ch">\t</span><span class="vs">anh</span><span class="dv">$</span><span class="vs">"</span>, <span class="st">"#E8F0F8"</span>)</span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a>operation(<span class="fl">9.65</span>, <span class="fl">1.95</span>, <span class="vs">r"</span><span class="dv">$</span><span class="ch">\t</span><span class="vs">imes</span><span class="dv">$</span><span class="vs">"</span>)</span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a>ax.plot([<span class="fl">8.15</span>, <span class="fl">7.8</span>, <span class="fl">7.8</span>, <span class="fl">8.1</span>], [<span class="fl">2.45</span>, <span class="fl">2.45</span>, <span class="fl">3.6</span>, <span class="fl">3.6</span>], color<span class="op">=</span><span class="st">"#232D4B"</span>, lw<span class="op">=</span><span class="fl">1.3</span>)</span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a>ax.annotate(<span class="st">""</span>, (<span class="fl">8.1</span>, <span class="fl">2.45</span>), (<span class="fl">7.8</span>, <span class="fl">2.45</span>), arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>, lw<span class="op">=</span><span class="fl">1.3</span>, color<span class="op">=</span><span class="st">"#232D4B"</span>))</span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a>ax.annotate(<span class="st">""</span>, (<span class="fl">9.4</span>, <span class="fl">2.05</span>), (<span class="fl">9.0</span>, <span class="fl">2.45</span>), arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>, lw<span class="op">=</span><span class="fl">1.3</span>, color<span class="op">=</span><span class="st">"#232D4B"</span>))</span>
<span id="cb5-47"><a href="#cb5-47" aria-hidden="true" tabindex="-1"></a>ax.annotate(<span class="st">""</span>, (<span class="fl">9.4</span>, <span class="fl">1.85</span>), (<span class="fl">9.0</span>, <span class="fl">1.45</span>), arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>, lw<span class="op">=</span><span class="fl">1.3</span>, color<span class="op">=</span><span class="st">"#232D4B"</span>))</span>
<span id="cb5-48"><a href="#cb5-48" aria-hidden="true" tabindex="-1"></a>ax.annotate(<span class="st">""</span>, (<span class="fl">10.45</span>, <span class="fl">1.95</span>), (<span class="fl">9.9</span>, <span class="fl">1.95</span>), arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>, lw<span class="op">=</span><span class="fl">1.5</span>, color<span class="op">=</span><span class="st">"#232D4B"</span>))</span>
<span id="cb5-49"><a href="#cb5-49" aria-hidden="true" tabindex="-1"></a>ax.text(<span class="fl">10.65</span>, <span class="fl">1.95</span>, <span class="st">"$h_t$"</span>, ha<span class="op">=</span><span class="st">"left"</span>, va<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">11</span>)</span>
<span id="cb5-50"><a href="#cb5-50" aria-hidden="true" tabindex="-1"></a>ax.text(<span class="fl">5.2</span>, <span class="fl">4.25</span>, <span class="st">"additive cell-state highway"</span>, color<span class="op">=</span><span class="st">"#B45309"</span>,</span>
<span id="cb5-51"><a href="#cb5-51" aria-hidden="true" tabindex="-1"></a>        ha<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb5-52"><a href="#cb5-52" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-lstm-conveyor" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lstm-conveyor-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-sequences-rnn_files/figure-html/fig-lstm-conveyor-output-1.png" width="701" height="307" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lstm-conveyor-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.2: The LSTM cell as a conveyor belt with valves. The forget gate <span class="math inline">\(f_t\)</span> controls how much old cell state continues; the input gate <span class="math inline">\(i_t\)</span> controls how much candidate content is added; the output gate <span class="math inline">\(o_t\)</span> controls what becomes visible as <span class="math inline">\(h_t\)</span>. The upper additive route is the long-memory highway.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Two states now travel: the cell state <span class="math inline">\(\vect{c}_t\)</span> (long-term memory, the conveyor belt) and the hidden state <span class="math inline">\(\vect{h}_t\)</span> (working memory, playing the vanilla RNN’s old role). The line that changes everything is the <span class="math inline">\(\vect{c}_t\)</span> update — read its gradient the way the seed’s notes do:</p>
<p><span id="eq-lstm-highway"><span class="math display">\[
\frac{\partial \vect{c}_t}{\partial \vect{c}_{t-1}} \approx \vect{f}_t
\qquad\Longrightarrow\qquad
\frac{\partial L}{\partial \vect{c}_{t-k}} \approx
\left(\prod_{j=t-k+1}^{t} \vect{f}_j\right) \odot \frac{\partial L}{\partial \vect{c}_t}.
\tag{10.5}\]</span></span></p>
<p>Still a product — but of <em>learned, data-dependent gates</em>, not a fixed weight matrix. Where Chapter 9’s residual highway kept an unconditional identity lane open, the LSTM’s lane has a valve the network controls: hold <span class="math inline">\(\vect{f}_j\)</span> near 1 and gradients ride the conveyor belt across dozens of steps; drop it toward 0 and the memory (deliberately) expires. The practical corollary, straight from the lecture notes: <em>initialize the forget-gate bias positive</em> (say <span class="math inline">\(+1\)</span>), so the cell starts life remembering by default. PyTorch stores separate input-hidden and hidden-hidden bias vectors, then adds them. The code sets their <strong>sum</strong> to <span class="math inline">\(+1\)</span>; setting both slices to <span class="math inline">\(+1\)</span> would silently create an effective bias of <span class="math inline">\(+2\)</span>. Watch what that buys, on the same axes as before:</p>
<div id="cell-fig-highway-time" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code: gradient vs.&nbsp;lag, vanilla RNN against LSTM</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>torch.manual_seed(<span class="dv">0</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>lstm <span class="op">=</span> nn.LSTM(<span class="dv">4</span>, <span class="dv">32</span>, batch_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> torch.no_grad():</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> lstm.bias_ih_l0.shape[<span class="dv">0</span>] <span class="op">//</span> <span class="dv">4</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    lstm.bias_ih_l0[n:<span class="dv">2</span> <span class="op">*</span> n].fill_(<span class="fl">1.0</span>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    lstm.bias_hh_l0[n:<span class="dv">2</span> <span class="op">*</span> n].zero_()             <span class="co"># the two bias slices sum to +1</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>g_lstm <span class="op">=</span> grad_at_first_input(lstm, lags)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="fl">6.2</span>, <span class="fl">3.2</span>))</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>plt.semilogy(lags, g_rnn, <span class="st">"o-"</span>, color<span class="op">=</span><span class="st">"#E57200"</span>, ms<span class="op">=</span><span class="dv">5</span>, label<span class="op">=</span><span class="st">"vanilla RNN"</span>)</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>plt.semilogy(lags, g_lstm, <span class="st">"s-"</span>, color<span class="op">=</span><span class="st">"#232D4B"</span>, ms<span class="op">=</span><span class="dv">5</span>, label<span class="op">=</span><span class="st">"LSTM (forget bias +1)"</span>)</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"lag $T$ between output and first input"</span>)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="vs">r"</span><span class="dv">$</span><span class="ch">\|</span><span class="er">\</span><span class="vs">partial L / </span><span class="er">\</span><span class="vs">partial </span><span class="dv">\m</span><span class="vs">athbf{x}_1</span><span class="ch">\|</span><span class="dv">$</span><span class="vs">"</span>)</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>plt.legend()<span class="op">;</span> plt.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-highway-time" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-highway-time-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-sequences-rnn_files/figure-html/fig-highway-time-output-1.png" width="584" height="297" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-highway-time-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.3: The gradient-vs-lag experiment, rerun with an LSTM whose effective forget-gate bias is initialized to +1. The vanilla RNN’s blame signal dies exponentially; the LSTM’s rides the cell-state conveyor belt and arrives at lag 60 attenuated but alive, about ten orders of magnitude stronger. Chapter 9 built this highway across layers; the LSTM builds it across time, with a learned valve on the on-ramp.
</figcaption>
</figure>
</div>
</div>
</div>
<section id="the-memory-test" class="level3">
<h3 class="anchored" data-anchor-id="the-memory-test">The memory test</h3>
<p>Gradients at initialization are promissory notes; training is where they get cashed. The seed notes pose the decisive task as a two-company story: Company A’s prices open at 0, Company B’s at 1, then both trade identically for days — and the correct day-5 prediction is whatever day 1 said. Everything hinges on carrying one early bit across a long stretch of identical noise. Here is that story as an executable task: sequences of 80 random tokens, where the label to predict at the end is simply <em>the first token</em>. Chance is 25%. Three contenders, three seeds each: the vanilla RNN, the LSTM as PyTorch hands it to you, and the LSTM with the lecture’s remember-by-default initialization.</p>
<div id="recall-task" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code: recall-the-first-token at lag 80, three configurations</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> make_recall(n: <span class="bu">int</span>, T: <span class="bu">int</span>, vocab: <span class="bu">int</span> <span class="op">=</span> <span class="dv">4</span>,</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>                seed: <span class="bu">int</span> <span class="op">=</span> <span class="dv">0</span>) <span class="op">-&gt;</span> <span class="bu">tuple</span>[torch.Tensor, torch.Tensor]:</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    g <span class="op">=</span> torch.Generator().manual_seed(seed)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    X <span class="op">=</span> torch.randint(<span class="dv">0</span>, vocab, (n, T), generator<span class="op">=</span>g)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> F.one_hot(X, vocab).<span class="bu">float</span>(), X[:, <span class="dv">0</span>]     <span class="co"># label = first token</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> SeqClassifier(nn.Module):</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, cell: <span class="bu">str</span>, vocab<span class="op">=</span><span class="dv">4</span>, hidden<span class="op">=</span><span class="dv">32</span>, forget_bias<span class="op">=</span><span class="va">None</span>):</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.rec <span class="op">=</span> {<span class="st">"rnn"</span>: nn.RNN, <span class="st">"lstm"</span>: nn.LSTM}[cell](vocab, hidden,</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>                                                          batch_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> forget_bias <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>:</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>            <span class="cf">with</span> torch.no_grad():</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>                n <span class="op">=</span> <span class="va">self</span>.rec.bias_ih_l0.shape[<span class="dv">0</span>] <span class="op">//</span> <span class="dv">4</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>                <span class="va">self</span>.rec.bias_ih_l0[n:<span class="dv">2</span> <span class="op">*</span> n].fill_(forget_bias)</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>                <span class="va">self</span>.rec.bias_hh_l0[n:<span class="dv">2</span> <span class="op">*</span> n].zero_()</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.out <span class="op">=</span> nn.Linear(hidden, vocab)</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x: torch.Tensor) <span class="op">-&gt;</span> torch.Tensor:</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>        o, _ <span class="op">=</span> <span class="va">self</span>.rec(x)</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">self</span>.out(o[:, <span class="op">-</span><span class="dv">1</span>])                    <span class="co"># read out at the </span><span class="re">END</span><span class="co"> only</span></span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> train_recall(cell: <span class="bu">str</span>, T: <span class="bu">int</span>, seed: <span class="bu">int</span>, forget_bias: <span class="bu">float</span> <span class="op">|</span> <span class="va">None</span> <span class="op">=</span> <span class="va">None</span>,</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>                 epochs: <span class="bu">int</span> <span class="op">=</span> <span class="dv">80</span>) <span class="op">-&gt;</span> <span class="bu">float</span>:</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>    torch.manual_seed(seed)</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>    net <span class="op">=</span> SeqClassifier(cell, forget_bias<span class="op">=</span>forget_bias)</span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>    X_tr, y_tr <span class="op">=</span> make_recall(<span class="dv">2000</span>, T, seed<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>    X_te, y_te <span class="op">=</span> make_recall(<span class="dv">500</span>, T, seed<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a>    opt <span class="op">=</span> torch.optim.Adam(net.parameters(), lr<span class="op">=</span><span class="fl">3e-3</span>)</span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(epochs):</span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a>        perm <span class="op">=</span> torch.randperm(<span class="bu">len</span>(X_tr))</span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>, <span class="bu">len</span>(X_tr), <span class="dv">128</span>):</span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a>            idx <span class="op">=</span> perm[i:i <span class="op">+</span> <span class="dv">128</span>]</span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a>            loss <span class="op">=</span> F.cross_entropy(net(X_tr[idx]), y_tr[idx])</span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a>            opt.zero_grad()<span class="op">;</span> loss.backward()</span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a>            nn.utils.clip_grad_norm_(net.parameters(), <span class="fl">1.0</span>)</span>
<span id="cb7-36"><a href="#cb7-36" aria-hidden="true" tabindex="-1"></a>            opt.step()</span>
<span id="cb7-37"><a href="#cb7-37" aria-hidden="true" tabindex="-1"></a>    <span class="cf">with</span> torch.no_grad():</span>
<span id="cb7-38"><a href="#cb7-38" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> (net(X_te).argmax(<span class="dv">1</span>) <span class="op">==</span> y_te).<span class="bu">float</span>().mean().item()</span>
<span id="cb7-39"><a href="#cb7-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-40"><a href="#cb7-40" aria-hidden="true" tabindex="-1"></a>T <span class="op">=</span> <span class="dv">80</span></span>
<span id="cb7-41"><a href="#cb7-41" aria-hidden="true" tabindex="-1"></a>configs <span class="op">=</span> [(<span class="st">"vanilla RNN"</span>, <span class="st">"rnn"</span>, <span class="va">None</span>),</span>
<span id="cb7-42"><a href="#cb7-42" aria-hidden="true" tabindex="-1"></a>           (<span class="st">"LSTM, default init"</span>, <span class="st">"lstm"</span>, <span class="va">None</span>),</span>
<span id="cb7-43"><a href="#cb7-43" aria-hidden="true" tabindex="-1"></a>           (<span class="st">"LSTM, forget bias +1"</span>, <span class="st">"lstm"</span>, <span class="fl">1.0</span>)]</span>
<span id="cb7-44"><a href="#cb7-44" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"recall accuracy at lag </span><span class="sc">{</span>T<span class="sc">}</span><span class="ss"> (chance 25%), seeds 0 / 1 / 6050:"</span>)</span>
<span id="cb7-45"><a href="#cb7-45" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> label, cell, fb <span class="kw">in</span> configs:</span>
<span id="cb7-46"><a href="#cb7-46" aria-hidden="true" tabindex="-1"></a>    accs <span class="op">=</span> [train_recall(cell, T, s, fb) <span class="cf">for</span> s <span class="kw">in</span> [<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">6050</span>]]</span>
<span id="cb7-47"><a href="#cb7-47" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>label<span class="sc">:22s}</span><span class="ss"> "</span> <span class="op">+</span> <span class="st">"   "</span>.join(<span class="ss">f"</span><span class="sc">{</span>a<span class="sc">:.0%}</span><span class="ss">"</span> <span class="cf">for</span> a <span class="kw">in</span> accs))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>recall accuracy at lag 80 (chance 25%), seeds 0 / 1 / 6050:
  vanilla RNN            25%   100%   25%
  LSTM, default init     24%   26%   26%
  LSTM, forget bias +1   100%   100%   100%</code></pre>
</div>
</div>
<p>Three rows, one lesson each. The vanilla RNN is a <em>lottery</em>: two seeds sit at chance, one cracks the task. <a href="#fig-vanishing-time" class="quarto-xref">Figure&nbsp;<span>10.1</span></a> says the teaching gradient is astronomically attenuated, not exactly zero — so once in a while optimization stumbles onto a solution anyway, and you cannot build a system on once-in-a-while. The default-initialized LSTM loses on <em>every</em> seed — worth a long pause, because it says the architecture alone is not the cure. A fresh LSTM’s forget gates hover near <span class="math inline">\(\sigma(0) = \tfrac12\)</span>, and <span class="math inline">\(0.5^{80} \approx 10^{-24}\)</span>: a half-closed valve, compounded eighty times, is as fatal as no valve. The third row flips the single bias that opens the valve, and the task is solved outright, every seed. The highway was built by the architecture; <em>initialization opened it</em> — the same lesson Chapter 5 taught about signal scales at birth, now with a memory attached. And the deliverable is not raw capability but <strong>reliability</strong>: what the gates buy is that memory stops being a lottery. (For shorter stretches the drama disappears: at lag 20 all three rows solve the task under this budget. The gates earn their keep precisely where <a href="#eq-bptt" class="quarto-xref">Equation&nbsp;<span>10.3</span></a> says the vanilla cell must fail.)</p>
</section>
</section>
<section id="gru-the-streamlined-cousin" class="level2" data-number="10.5">
<h2 data-number="10.5" class="anchored" data-anchor-id="gru-the-streamlined-cousin"><span class="header-section-number">10.5</span> GRU: the streamlined cousin</h2>
<p>The <strong>Gated Recurrent Unit</strong> (Cho et al., 2014) folds the same ideas into a smaller box: cell and hidden state merged into one <span class="math inline">\(\vect{h}_t\)</span>, forget and input valves merged into a single <strong>update gate</strong> <span class="math inline">\(\vect{z}_t\)</span> (what you keep you don’t overwrite, and vice versa), plus a <strong>reset gate</strong> <span class="math inline">\(\vect{r}_t\)</span> that can blank the past when a fresh start is called for:</p>
<p><span id="eq-gru"><span class="math display">\[
\begin{aligned}
\vect{z}_t &amp;= \sigma\!\left(\matr{W}_z [\vect{h}_{t-1}, \vect{x}_t]\right), \qquad
\vect{r}_t = \sigma\!\left(\matr{W}_r [\vect{h}_{t-1}, \vect{x}_t]\right),\\
\tilde{\vect{h}}_t &amp;= \tanh\!\left(\matr{W}_h [\vect{r}_t \odot \vect{h}_{t-1},\, \vect{x}_t]\right), \qquad
\vect{h}_t = \vect{z}_t \odot \vect{h}_{t-1} + (1 - \vect{z}_t) \odot \tilde{\vect{h}}_t .
\end{aligned}
\tag{10.6}\]</span></span></p>
<p>Two gates instead of three, one state instead of two, comparable performance in most settings. The lecture explicitly skips the derivation, and the book follows suit. With the equations on record and Exercise 3 waiting, you can build one yourself and let it compete on the memory test.</p>
<p>One convention matters before you compare code. <a href="#eq-gru" class="quarto-xref">Equation&nbsp;<span>10.6</span></a> applies the reset gate to <span class="math inline">\(\vect{h}_{t-1}\)</span> <strong>before</strong> the candidate’s hidden-state linear map. PyTorch’s <code>nn.GRU</code> uses a reset-after form, <span class="math inline">\(\tanh(W_{in}x+b_{in}+r\odot(W_{hn}h+b_{hn}))\)</span>, for implementation efficiency. The gates serve the same purpose, but the two cells are not algebraically identical for the same weights. An exact manual-loop verification must implement PyTorch’s ordering rather than <a href="#eq-gru" class="quarto-xref">Equation&nbsp;<span>10.6</span></a>’s.</p>
</section>
<section id="the-book-reads-itself" class="level2" data-number="10.6">
<h2 data-number="10.6" class="anchored" data-anchor-id="the-book-reads-itself"><span class="header-section-number">10.6</span> The book reads itself</h2>
<p>Time to put fixed windows, clipping, gates, and Chapter 2’s softmax over a vocabulary to work on real text. In keeping with a book whose every experiment runs on its own pages, the training corpus is <em>the nine chapters you have already read</em>: their prose, stripped of code cells, more than 130,000 characters. The task is the oldest one in language modeling: read a character, predict the next.</p>
<div id="char-lm-train" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code: a character-level LSTM trained on Chapters 1–9</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> glob, re</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>files <span class="op">=</span> <span class="bu">sorted</span>(glob.glob(<span class="st">"../part*/0*.qmd"</span>))          <span class="co"># chapters 1-9, not this one</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>text <span class="op">=</span> <span class="st">""</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> f <span class="kw">in</span> files:</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    raw <span class="op">=</span> <span class="bu">open</span>(f).read()</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    raw <span class="op">=</span> re.sub(<span class="vs">r"```</span><span class="ch">\{</span><span class="vs">python</span><span class="ch">\}</span><span class="dv">.</span><span class="op">*?</span><span class="vs">```"</span>, <span class="st">""</span>, raw, flags<span class="op">=</span>re.S)   <span class="co"># drop code cells</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    raw <span class="op">=</span> re.sub(<span class="vs">r"&lt;!--</span><span class="dv">.</span><span class="op">*?</span><span class="vs">--&gt;"</span>, <span class="st">""</span>, raw, flags<span class="op">=</span>re.S)            <span class="co"># drop comments</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    text <span class="op">+=</span> raw</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>chars <span class="op">=</span> <span class="bu">sorted</span>(<span class="bu">set</span>(text))</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>stoi <span class="op">=</span> {c: i <span class="cf">for</span> i, c <span class="kw">in</span> <span class="bu">enumerate</span>(chars)}</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> torch.tensor([stoi[c] <span class="cf">for</span> c <span class="kw">in</span> text])</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>split <span class="op">=</span> <span class="bu">int</span>(<span class="fl">0.9</span> <span class="op">*</span> <span class="bu">len</span>(data))</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>train_data, valid_data <span class="op">=</span> data[:split], data[split:]</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"corpus: </span><span class="sc">{</span><span class="bu">len</span>(files)<span class="sc">}</span><span class="ss"> chapters, </span><span class="sc">{</span><span class="bu">len</span>(text)<span class="sc">:,}</span><span class="ss"> characters, vocab </span><span class="sc">{</span><span class="bu">len</span>(chars)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"deterministic split: </span><span class="sc">{</span><span class="bu">len</span>(train_data)<span class="sc">:,}</span><span class="ss"> train / </span><span class="sc">{</span><span class="bu">len</span>(valid_data)<span class="sc">:,}</span><span class="ss"> held out"</span>)</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> CharLSTM(nn.Module):</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, vocab: <span class="bu">int</span>, hidden: <span class="bu">int</span> <span class="op">=</span> <span class="dv">128</span>):</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.vocab <span class="op">=</span> vocab</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.lstm <span class="op">=</span> nn.LSTM(vocab, hidden, batch_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.out <span class="op">=</span> nn.Linear(hidden, vocab)</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>, x: torch.Tensor,</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>        state: <span class="bu">tuple</span>[torch.Tensor, torch.Tensor] <span class="op">|</span> <span class="va">None</span> <span class="op">=</span> <span class="va">None</span>,</span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>    ) <span class="op">-&gt;</span> <span class="bu">tuple</span>[torch.Tensor, <span class="bu">tuple</span>[torch.Tensor, torch.Tensor]]:</span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>        o, state <span class="op">=</span> <span class="va">self</span>.lstm(F.one_hot(x, <span class="va">self</span>.vocab).<span class="bu">float</span>(), state)</span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">self</span>.out(o), state                      <span class="co"># logits at EVERY step</span></span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a>torch.manual_seed(<span class="dv">6050</span>)</span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> CharLSTM(<span class="bu">len</span>(chars))</span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>opt <span class="op">=</span> torch.optim.Adam(model.parameters(), lr<span class="op">=</span><span class="fl">2e-3</span>)</span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a>chunk, batch <span class="op">=</span> <span class="dv">100</span>, <span class="dv">64</span>                                 <span class="co"># random fixed-context windows</span></span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> step <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">2501</span>):</span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a>    s <span class="op">=</span> torch.randint(<span class="dv">0</span>, <span class="bu">len</span>(train_data) <span class="op">-</span> chunk <span class="op">-</span> <span class="dv">1</span>, (batch,))</span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a>    xb <span class="op">=</span> torch.stack([train_data[j:j <span class="op">+</span> chunk] <span class="cf">for</span> j <span class="kw">in</span> s])</span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a>    yb <span class="op">=</span> torch.stack([train_data[j <span class="op">+</span> <span class="dv">1</span>:j <span class="op">+</span> chunk <span class="op">+</span> <span class="dv">1</span>] <span class="cf">for</span> j <span class="kw">in</span> s])</span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a>    logits, _ <span class="op">=</span> model(xb)</span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a>    loss <span class="op">=</span> F.cross_entropy(logits.reshape(<span class="op">-</span><span class="dv">1</span>, <span class="bu">len</span>(chars)), yb.reshape(<span class="op">-</span><span class="dv">1</span>))</span>
<span id="cb9-41"><a href="#cb9-41" aria-hidden="true" tabindex="-1"></a>    opt.zero_grad()<span class="op">;</span> loss.backward()</span>
<span id="cb9-42"><a href="#cb9-42" aria-hidden="true" tabindex="-1"></a>    nn.utils.clip_grad_norm_(model.parameters(), <span class="fl">1.0</span>)</span>
<span id="cb9-43"><a href="#cb9-43" aria-hidden="true" tabindex="-1"></a>    opt.step()</span>
<span id="cb9-44"><a href="#cb9-44" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> step <span class="op">%</span> <span class="dv">500</span> <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb9-45"><a href="#cb9-45" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"step </span><span class="sc">{</span>step<span class="sc">:4d}</span><span class="ss">   loss </span><span class="sc">{</span>loss<span class="sc">.</span>item()<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb9-46"><a href="#cb9-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-47"><a href="#cb9-47" aria-hidden="true" tabindex="-1"></a><span class="at">@torch.no_grad</span>()</span>
<span id="cb9-48"><a href="#cb9-48" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> fixed_window_loss(net: nn.Module, sequence: torch.Tensor,</span>
<span id="cb9-49"><a href="#cb9-49" aria-hidden="true" tabindex="-1"></a>                      window: <span class="bu">int</span> <span class="op">=</span> <span class="dv">100</span>) <span class="op">-&gt;</span> <span class="bu">float</span>:</span>
<span id="cb9-50"><a href="#cb9-50" aria-hidden="true" tabindex="-1"></a>    net.<span class="bu">eval</span>()</span>
<span id="cb9-51"><a href="#cb9-51" aria-hidden="true" tabindex="-1"></a>    total_loss, n_tokens <span class="op">=</span> <span class="fl">0.0</span>, <span class="dv">0</span></span>
<span id="cb9-52"><a href="#cb9-52" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> start <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>, <span class="bu">len</span>(sequence) <span class="op">-</span> <span class="dv">1</span>, window):</span>
<span id="cb9-53"><a href="#cb9-53" aria-hidden="true" tabindex="-1"></a>        stop <span class="op">=</span> <span class="bu">min</span>(start <span class="op">+</span> window, <span class="bu">len</span>(sequence) <span class="op">-</span> <span class="dv">1</span>)</span>
<span id="cb9-54"><a href="#cb9-54" aria-hidden="true" tabindex="-1"></a>        xb <span class="op">=</span> sequence[start:stop].unsqueeze(<span class="dv">0</span>)</span>
<span id="cb9-55"><a href="#cb9-55" aria-hidden="true" tabindex="-1"></a>        yb <span class="op">=</span> sequence[start <span class="op">+</span> <span class="dv">1</span>:stop <span class="op">+</span> <span class="dv">1</span>]</span>
<span id="cb9-56"><a href="#cb9-56" aria-hidden="true" tabindex="-1"></a>        logits, _ <span class="op">=</span> net(xb)                         <span class="co"># state resets at each window</span></span>
<span id="cb9-57"><a href="#cb9-57" aria-hidden="true" tabindex="-1"></a>        total_loss <span class="op">+=</span> F.cross_entropy(</span>
<span id="cb9-58"><a href="#cb9-58" aria-hidden="true" tabindex="-1"></a>            logits.reshape(<span class="op">-</span><span class="dv">1</span>, <span class="bu">len</span>(chars)), yb, reduction<span class="op">=</span><span class="st">"sum"</span>).item()</span>
<span id="cb9-59"><a href="#cb9-59" aria-hidden="true" tabindex="-1"></a>        n_tokens <span class="op">+=</span> yb.numel()</span>
<span id="cb9-60"><a href="#cb9-60" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> total_loss <span class="op">/</span> n_tokens</span>
<span id="cb9-61"><a href="#cb9-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-62"><a href="#cb9-62" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"held-out fixed-window loss </span><span class="sc">{</span>fixed_window_loss(model, valid_data)<span class="sc">:.2f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>corpus: 9 chapters, 148,594 characters, vocab 104
deterministic split: 133,734 train / 14,860 held out
step    0   loss 4.62
step  500   loss 2.28
step 1000   loss 1.93
step 1500   loss 1.75
step 2000   loss 1.57
step 2500   loss 1.42
held-out fixed-window loss 1.89</code></pre>
</div>
</div>
<p>The loss falls from <span class="math inline">\(\ln(V) \approx 4.6\)</span> for the printed vocabulary size (uniform guessing) to 1.42 on the last sampled training minibatch. The deterministic held-out tail is harder, at 1.89, but both are far below uniform guessing. The model has learned a great deal about what this book’s next character tends to be. To <em>hear</em> what it learned, generate: feed a prompt, sample the next character from the softmax (divided by a <strong>temperature</strong> that sharpens or flattens it, Chapter 2’s dial between hard max and uniform), feed that character back in, repeat. The hidden state streams; nothing is recomputed.</p>
<div id="char-lm-sample" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Code: sampling from the model, one character at a time</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="at">@torch.no_grad</span>()</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> sample(prompt: <span class="bu">str</span>, n: <span class="bu">int</span> <span class="op">=</span> <span class="dv">300</span>, temp: <span class="bu">float</span> <span class="op">=</span> <span class="fl">0.8</span>) <span class="op">-&gt;</span> <span class="bu">str</span>:</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    model.<span class="bu">eval</span>()</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    idx <span class="op">=</span> torch.tensor([[stoi.get(c, <span class="dv">0</span>) <span class="cf">for</span> c <span class="kw">in</span> prompt]])</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    logits, state <span class="op">=</span> model(idx)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    out <span class="op">=</span> prompt</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(n):</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>        p <span class="op">=</span> F.softmax(logits[<span class="dv">0</span>, <span class="op">-</span><span class="dv">1</span>] <span class="op">/</span> temp, <span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>        nxt <span class="op">=</span> torch.multinomial(p, <span class="dv">1</span>)[<span class="va">None</span>]</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>        out <span class="op">+=</span> chars[nxt.item()]</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>        logits, state <span class="op">=</span> model(nxt, state)              <span class="co"># consume each sample once</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> out</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(sample(<span class="st">"The gradient "</span>, n<span class="op">=</span><span class="dv">300</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>The gradient mupolition both
lates
chood each the burk's map into a mack from the bupfured way
   intene agmenten. Pyout nothing buith and why the dirge melies to exactly. What algien is

$$
\logit_i).
   ixsections.

## Exercise reseds the barkwarper from to twe optimized $\rightarrow$ and classitivations, in t</code></pre>
</div>
</div>
<p>Read the output honestly, because both halves of the verdict teach. What it <em>got</em>: words, spacing, sentence rhythm, markdown furniture (asterisks, pipes, colons), and the book’s working vocabulary (training, batch, layer, convolution in various misspellings), all learned from raw characters by a one-layer recurrence reading 100-character chunks. What it <em>lacks</em>: meaning. Clauses trail off; equations open and never close; the prose has the book’s accent with none of its intent. Some of that is scale (a 130k-character corpus and 128 hidden units is a <em>tiny</em> language model), and some of it is the finite state. By the end of a sentence, the beginning has been squeezed through the LSTM’s two 128-dimensional states, <span class="math inline">\((\vect{h}, \vect{c})\)</span>: 256 scalars in all. Both diagnoses point down the road this part of the book is traveling.</p>
</section>
<section id="what-a-fixed-size-state-cannot-hold" class="level2" data-number="10.7">
<h2 data-number="10.7" class="anchored" data-anchor-id="what-a-fixed-size-state-cannot-hold"><span class="header-section-number">10.7</span> What a fixed-size state cannot hold</h2>
<p>The lecture closes with the bridge this part of the book now crosses. If a recurrent cell can read a sequence into a state, then two of them can translate: an <strong>encoder</strong> reads the source sentence into its final state, a <strong>decoder</strong> spins that state back out as words in another language. That architecture, plus its training tricks, is <a href="11-encoder-decoder.html" class="quarto-xref"><span>Chapter 11</span></a>. But notice what the design asks of one fixed-size state: the <em>entire sentence</em>, compressed into <span class="math inline">\((\vect{h},\vect{c})\)</span>, no matter how long the sentence runs. The char-LM’s trailing clauses were this bottleneck in miniature. The honest fix is not a bigger vector; it is admitting that the decoder should be allowed to <em>look back at all of the encoder’s states</em>, not just the last. Choosing where to look, on the fly, is a similarity computation you have been prepared for since Chapter 1’s dot products. That is attention (<a href="../part4/12-kernel-regression.html" class="quarto-xref"><span>Chapter 12</span></a>, <a href="../part4/13-attention.html" class="quarto-xref"><span>Chapter 13</span></a>), and it is two chapters away.</p>
</section>
<section id="okay-so" class="level2" data-number="10.8">
<h2 data-number="10.8" class="anchored" data-anchor-id="okay-so"><span class="header-section-number">10.8</span> Okay, so —</h2>
<ol type="1">
<li><strong>Order is the signal.</strong> Chapter 6’s MLP could absorb one fixed pixel permutation when retrained; shuffle a sentence into arbitrary orders and its meaning changes. Sequences add variable length and streaming, and the fixed-size toolkit of Parts I–II has no honest answer.</li>
<li><strong>The third weight sharing</strong>: one function <span class="math inline">\(f\)</span>, applied at every timestep, carrying a hidden state (<a href="#eq-recurrence" class="quarto-xref">Equation&nbsp;<span>10.1</span></a>, <a href="#eq-rnn-cell" class="quarto-xref">Equation&nbsp;<span>10.2</span></a>). This is stationarity as inductive bias, exactly as sharing across space was in Part II. The unrolled RNN is a deep network with tied weights.</li>
<li><strong>Tied depth in time = Chapter 5’s nightmare</strong>: BPTT multiplies <span class="math inline">\(T\)</span> near-identical Jacobians (<a href="#eq-bptt" class="quarto-xref">Equation&nbsp;<span>10.3</span></a>) <span class="math inline">\(\rightarrow\)</span> vanishing or exploding, unless their gains are carefully controlled. Clipping belts in the explosions; truncation caps the cost, but neither lengthens memory. Windows of roughly 20–50 steps are a common practical horizon, not a universal vanilla-RNN ceiling.</li>
<li><strong>The LSTM engineers the memory</strong>: an additive cell-state conveyor belt, Chapter 9’s residual highway laid across time, with three sigmoid valves (forget, input, output; <a href="#eq-lstm" class="quarto-xref">Equation&nbsp;<span>10.4</span></a>). Its gradient rides a product of <em>gates</em>, not weights (<a href="#eq-lstm-highway" class="quarto-xref">Equation&nbsp;<span>10.5</span></a>).</li>
<li><strong>Architecture proposes, initialization disposes</strong>: at lag 80 the default LSTM scores chance (<span class="math inline">\(\sigma(0)^{80} \approx 10^{-24}\)</span>); set the forget bias to <span class="math inline">\(+1\)</span> and the task is solved on every seed. GRU packs the same ideas into two gates and one state (<a href="#eq-gru" class="quarto-xref">Equation&nbsp;<span>10.6</span></a>).</li>
<li><strong>A one-layer character LSTM learns this book’s accent</strong> (words, rhythm, LaTeX tics) but not its meaning: part scale, part the finite-state bottleneck. Cramming a whole sequence into 256 recurrent-state scalars is the debt Part III carries forward, and attention is how the book repays it.</li>
</ol>
</section>
<section id="sources-and-further-reading" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="sources-and-further-reading">Sources and further reading</h2>
<ul>
<li><a href="https://doi.org/10.1207/s15516709cog1402_1">Elman, <em>Finding Structure in Time</em></a>: the classic simple recurrent network and its view of hidden state as temporal context.</li>
<li><a href="https://doi.org/10.1162/neco.1997.9.8.1735">Hochreiter &amp; Schmidhuber, <em>Long Short-Term Memory</em></a>: the original gated-memory architecture and constant-error pathway.</li>
<li><a href="https://aclanthology.org/D14-1179/">Cho et al., <em>Learning Phrase Representations using RNN Encoder–Decoder for Statistical Machine Translation</em></a>: introduces the gated recurrent unit in its encoder–decoder setting.</li>
<li><a href="https://proceedings.mlr.press/v28/pascanu13.html">Pascanu, Mikolov, &amp; Bengio, <em>On the Difficulty of Training Recurrent Neural Networks</em></a>: geometric analysis of vanishing/exploding gradients and gradient clipping.</li>
</ul>
</section>
<section id="exercises" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercises">Exercises</h2>
<ol type="1">
<li><strong>(Pencil.)</strong> Count parameters: a width-<span class="math inline">\(k\)</span> window MLP mapping <span class="math inline">\(k\)</span> one-hot tokens (vocabulary <span class="math inline">\(V\)</span>) through hidden width <span class="math inline">\(H\)</span> to <span class="math inline">\(V\)</span> logits, versus the vanilla RNN of <a href="#eq-rnn-cell" class="quarto-xref">Equation&nbsp;<span>10.2</span></a> with the same <span class="math inline">\(V\)</span> and <span class="math inline">\(H\)</span>. Which count depends on how much context the model can use, and why is that the whole argument of this chapter in two numbers?</li>
<li><strong>(Pencil.)</strong> From <a href="#eq-bptt" class="quarto-xref">Equation&nbsp;<span>10.3</span></a>, show that if <span class="math inline">\(\tanh\)</span> operated in its linear regime (<span class="math inline">\(\tanh' \approx 1\)</span>), the gradient norm grows or decays like the spectral radius of <span class="math inline">\(\matr{W}_{hh}\)</span> raised to <span class="math inline">\(T\)</span>. What does <span class="math inline">\(\tanh'(0) = 1\)</span> say about the moment right after initialization, when <span class="math inline">\(\vect{h} \approx \vect{0}\)</span>?</li>
<li><strong>(Code.)</strong> Implement the reset-before GRU in <a href="#eq-gru" class="quarto-xref">Equation&nbsp;<span>10.6</span></a> as a manual loop and enter it in the lag-80 memory test. Then change only the candidate update to PyTorch’s reset-after convention and verify that version against <code>nn.GRU</code>. Does either need an initialization trick, and which bias would you set?</li>
<li><strong>(Code.)</strong> The chapter starts every sequence with <span class="math inline">\(\vect{h}_0 = \vect{0}\)</span>. Make <span class="math inline">\(\vect{h}_0\)</span> a learned <code>nn.Parameter</code> in the recall task and retrain. Where does its gradient come from, and when could a learned start plausibly matter?</li>
<li><strong>(Code.)</strong> Sample the character model at temperatures 0.2, 0.8, and 1.5, and with the temperature near zero compare against picking the argmax at every step. Connect what you see to Chapter 2’s hard-max-versus-softmax discussion: which failure mode of the hard max does greedy decoding reproduce?</li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/shakeri-lab\.github\.io\/dl-book\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../chapters/part2/09-modern-cnns-transfer.html" class="pagination-link" aria-label="Modern CNNs and Transfer Learning">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Modern CNNs and Transfer Learning</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/part3/11-encoder-decoder.html" class="pagination-link" aria-label="Encoder–Decoder, Teacher Forcing, Beam Search">
        <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Encoder–Decoder, Teacher Forcing, Beam Search</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Heman Shakeri · Text CC BY-NC-SA 4.0 · Code MIT · School of Data Science, University of Virginia</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/Shakeri-Lab/dl-book/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Companion to <a href="https://shakeri-lab.github.io/dl-course-site/">DS 6050 Deep Learning</a></p>
</div>
  </div>
</footer>




</body></html>