<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>11&nbsp; Encoder–Decoder, Teacher Forcing, Beam Search – Deep Learning: Making It Learnable</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/part4/12-kernel-regression.html" rel="next">
<link href="../../chapters/part3/10-sequences-rnn.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-c90f29e1247290e1dfbeb1da338aa877.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>
  // Book math macros — keep in sync with tex/macros.tex (PDF path).
  // MathJax reads this config because it is defined before the MathJax
  // script loads (Quarto places include-in-header above its math script).
  window.MathJax = {
    tex: {
      macros: {
        E: "\\mathbb{E}",
        Ex: "\\operatorname{E}",
        var: "\\operatorname{Var}",
        cov: "\\operatorname{Cov}",
        imp: "\\Rightarrow",
        argmax: "\\operatorname*{arg\\,max}",
        argmin: "\\operatorname*{arg\\,min}",
        norm: ["\\left\\lVert#1\\right\\rVert", 1],
        vect: ["\\boldsymbol{#1}", 1],
        matr: ["\\boldsymbol{#1}", 1],
        R: "\\mathbb{R}",
        dd: "\\mathrm{d}",
        loss: "\\mathcal{L}"
      }
    }
  };
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/part3/10-sequences-rnn.html">Sequences</a></li><li class="breadcrumb-item"><a href="../../chapters/part3/11-encoder-decoder.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Encoder–Decoder, Teacher Forcing, Beam Search</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Deep Learning: Making It Learnable</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/Shakeri-Lab/dl-book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">From Lines to Networks</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/01-linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Linear Regression, the Mother Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/02-logistic-softmax.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Linear Models that Classify: Logistic and Softmax</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/03-nonlinearity-mlp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Nonlinearity and the MLP</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/04-training-loss-sgd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Training: Loss and Stochastic Gradient Descent</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/05-backpropagation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Backpropagation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/06-generalization-inductive-bias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">When It Fails: Generalization in Pictures, and Inductive Bias</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/interludes/learning-by-experiment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Who Trains the Trainer? Learning by Experiment</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Vision: Learning the Filters</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/07-filters-convolution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Filters and Convolution (Fixed Kernels)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/08-cnn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">CNNs: Making the Filters Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/09-modern-cnns-transfer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Modern CNNs and Transfer Learning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/interludes/making-pca-learnable.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Interlude: Making PCA Learnable</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Sequences</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part3/10-sequences-rnn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Sequences and Recurrence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part3/11-encoder-decoder.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Encoder–Decoder, Teacher Forcing, Beam Search</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Attention: Learning the Similarity</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/12-kernel-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Kernel Regression: Attention Before It Was Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/13-attention.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Attention: Making the Kernel Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/14-self-attention-transformer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Self-Attention and the Transformer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/15-bert-pretraining.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">The BERT Moment: Pretraining as the New Regime</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/16-vit-scaling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Vision Transformers and Scaling Laws</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">The Pretrained Era</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/17-peft-quantization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Adapting Pretrained Models: Prompting, PEFT, Quantization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/18-alignment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Alignment and RL Fine-Tuning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/19-generative.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Generative Models: From Codes to Samples</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/20-multimodal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Multimodal Learning: One Space, Two Views</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/epilogue.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Epilogue: The Question Is Yours</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a1-linear-algebra.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Linear Algebra and the SVD</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a2-tensors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Tensors in Practice</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a3-precision-performance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Numerical Precision and Hardware Efficiency</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a4-notation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Notation</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#two-rnns-and-a-handoff" id="toc-two-rnns-and-a-handoff" class="nav-link active" data-scroll-target="#two-rnns-and-a-handoff"><span class="header-section-number">11.1</span> Two RNNs and a handoff</a></li>
  <li><a href="#the-padding-trap" id="toc-the-padding-trap" class="nav-link" data-scroll-target="#the-padding-trap"><span class="header-section-number">11.2</span> The padding trap</a></li>
  <li><a href="#teacher-forcing-training-on-the-gold-rail" id="toc-teacher-forcing-training-on-the-gold-rail" class="nav-link" data-scroll-target="#teacher-forcing-training-on-the-gold-rail"><span class="header-section-number">11.3</span> Teacher forcing: training on the gold rail</a></li>
  <li><a href="#getting-answers-out-search" id="toc-getting-answers-out-search" class="nav-link" data-scroll-target="#getting-answers-out-search"><span class="header-section-number">11.4</span> Getting answers out: search</a></li>
  <li><a href="#the-fixed-size-state-in-the-middle" id="toc-the-fixed-size-state-in-the-middle" class="nav-link" data-scroll-target="#the-fixed-size-state-in-the-middle"><span class="header-section-number">11.5</span> The fixed-size state in the middle</a></li>
  <li><a href="#okay-so-the-fixed-size-handoff-is-the-bottleneck" id="toc-okay-so-the-fixed-size-handoff-is-the-bottleneck" class="nav-link" data-scroll-target="#okay-so-the-fixed-size-handoff-is-the-bottleneck"><span class="header-section-number">11.6</span> Okay, so — the fixed-size handoff is the bottleneck</a></li>
  <li><a href="#sources-and-further-reading" id="toc-sources-and-further-reading" class="nav-link" data-scroll-target="#sources-and-further-reading">Sources and further reading</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/Shakeri-Lab/dl-book/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/part3/10-sequences-rnn.html">Sequences</a></li><li class="breadcrumb-item"><a href="../../chapters/part3/11-encoder-decoder.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Encoder–Decoder, Teacher Forcing, Beam Search</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-11-encoder-decoder" class="quarto-section-identifier"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Encoder–Decoder, Teacher Forcing, Beam Search</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<!-- lecture-source: m06_lecture-6-encoder-decoder-architectures_XxePU8jubto.txt
     (spine #1-3, #9: fixed-size contract, variable-length challenge, bridge to
     translation), m07 spine #11 (encoder-decoder bottleneck bridge)
     seeds: sources/7.2-TF-Beam.tex (§Teacher Forcing, §Exposure Bias, §Scheduled
            Sampling, §Masking & Padded Sequences, §Greedy, §Beam, §Length Norm),
            his old/train_seq2seq.py (architecture template) + rnn_data_prep.py
            (special-token conventions; its dataset pipeline is D2L-derived and is
            NOT used — the book's task is synthetic and self-contained)
     note: m06's PCA/autoencoder spine (#4-8) is restored before recurrence in
           @sec-interlude-autoencoders; this chapter harvests its static contract
           with recurrent maps on both sides. -->
<p>Chapter 10 ended with a promise: if one recurrent cell can read a sequence <em>into</em> a state, two cells can translate: one reads, one writes. This chapter builds that machine and the craft around it: how to train it fast (teacher forcing), what poisonous bookkeeping to avoid (padding), and how to get answers back out of it (greedy versus beam search). It ends where Part III must: staring at the fixed-size recurrent state in the middle.</p>
<p>The names are not new. In the autoencoder interlude, an encoder compressed a fixed object and a decoder reconstructed it. Here both maps become recurrent processes. The encoder consumes however many source tokens arrive; the decoder produces however many target tokens are needed. What survives is the handoff: every source detail still has to cross through one fixed-size context.</p>
<p>The lecture frames the stakes well. Before recurrence, every model lived on a <strong>fixed-size contract</strong>: 784 pixels in, 10 logits out; <span class="math inline">\(28 \times 28\)</span> garments in, one verdict out. The interesting world breaks that contract on both ends at once: translation maps a sentence of <em>any</em> length to a sentence of <em>some other</em> length, in a different vocabulary. Chapter 10’s recurrent cell broke the contract on the input side; today we break it on both.</p>
<section id="two-rnns-and-a-handoff" class="level2" data-number="11.1">
<h2 data-number="11.1" class="anchored" data-anchor-id="two-rnns-and-a-handoff"><span class="header-section-number">11.1</span> Two RNNs and a handoff</h2>
<p>The architecture is one idea long. An <strong>encoder</strong> RNN reads the source sequence and keeps nothing but its final state, the entire input compressed into fixed-size memory, the <strong>context</strong>. A <strong>decoder</strong> RNN starts <em>from</em> that state and generates the output token by token, feeding each token back in, exactly like Chapter 10’s character model. A language model, in other words, but one with something to say.</p>
<p>Our laboratory task keeps the core mechanics of translation and none of the downloads: <strong>date normalization</strong>. The source language is human-written dates in several dialects; the target language is ISO 8601:</p>
<pre><code>march 5, 2021        -&gt; 2021-03-05
26 september 2024    -&gt; 2024-09-26
12/15/1950           -&gt; 1950-12-15</code></pre>
<p>Variable-length input, a different output alphabet, and real long-range structure (the year arrives <em>last</em> in most sources but must be emitted <em>first</em>). The target is deliberately fixed at ten characters, so this laboratory does <strong>not</strong> test variable-length target padding. It does include a dialect ambiguity that gives beam search something genuine to reveal: numeric dates are written <code>mm/dd/yyyy</code> by 70% of our imaginary writers (the US convention) and <code>dd/mm/yyyy</code> by 30%, and nothing in <code>03/05/2021</code> says which. Machine translation in miniature.</p>
<div id="date-data" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Code: the two date languages, generated on the fly</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> random, torch</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.nn <span class="im">as</span> nn</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.nn.functional <span class="im">as</span> F</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>MONTHS <span class="op">=</span> [<span class="st">"january"</span>, <span class="st">"february"</span>, <span class="st">"march"</span>, <span class="st">"april"</span>, <span class="st">"may"</span>, <span class="st">"june"</span>, <span class="st">"july"</span>,</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>          <span class="st">"august"</span>, <span class="st">"september"</span>, <span class="st">"october"</span>, <span class="st">"november"</span>, <span class="st">"december"</span>]</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>DAYS <span class="op">=</span> <span class="bu">dict</span>(<span class="bu">zip</span>(MONTHS, [<span class="dv">31</span>, <span class="dv">28</span>, <span class="dv">31</span>, <span class="dv">30</span>, <span class="dv">31</span>, <span class="dv">30</span>, <span class="dv">31</span>, <span class="dv">31</span>, <span class="dv">30</span>, <span class="dv">31</span>, <span class="dv">30</span>, <span class="dv">31</span>]))</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> make_date(rng: random.Random) <span class="op">-&gt;</span> <span class="bu">tuple</span>[<span class="bu">str</span>, <span class="bu">str</span>]:</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    mo <span class="op">=</span> rng.randrange(<span class="dv">12</span>)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    d <span class="op">=</span> rng.randrange(<span class="dv">1</span>, DAYS[MONTHS[mo]] <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> rng.randrange(<span class="dv">1950</span>, <span class="dv">2026</span>)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    iso <span class="op">=</span> <span class="ss">f"</span><span class="sc">{</span>y<span class="sc">:04d}</span><span class="ss">-</span><span class="sc">{</span>mo<span class="op">+</span><span class="dv">1</span><span class="sc">:02d}</span><span class="ss">-</span><span class="sc">{</span>d<span class="sc">:02d}</span><span class="ss">"</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    style <span class="op">=</span> rng.random()</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> style <span class="op">&lt;</span> <span class="fl">0.35</span>:</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>        src <span class="op">=</span> <span class="ss">f"</span><span class="sc">{</span>MONTHS[mo]<span class="sc">}</span><span class="ss"> </span><span class="sc">{</span>d<span class="sc">}</span><span class="ss">, </span><span class="sc">{</span>y<span class="sc">}</span><span class="ss">"</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> style <span class="op">&lt;</span> <span class="fl">0.6</span>:</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>        src <span class="op">=</span> <span class="ss">f"</span><span class="sc">{</span>d<span class="sc">}</span><span class="ss"> </span><span class="sc">{</span>MONTHS[mo]<span class="sc">}</span><span class="ss"> </span><span class="sc">{</span>y<span class="sc">}</span><span class="ss">"</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> rng.random() <span class="op">&lt;</span> <span class="fl">0.7</span>:</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>        src <span class="op">=</span> <span class="ss">f"</span><span class="sc">{</span>mo<span class="op">+</span><span class="dv">1</span><span class="sc">:02d}</span><span class="ss">/</span><span class="sc">{</span>d<span class="sc">:02d}</span><span class="ss">/</span><span class="sc">{</span>y<span class="sc">}</span><span class="ss">"</span>            <span class="co"># US convention: mm/dd</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>        src <span class="op">=</span> <span class="ss">f"</span><span class="sc">{</span>d<span class="sc">:02d}</span><span class="ss">/</span><span class="sc">{</span>mo<span class="op">+</span><span class="dv">1</span><span class="sc">:02d}</span><span class="ss">/</span><span class="sc">{</span>y<span class="sc">}</span><span class="ss">"</span>            <span class="co"># EU convention: dd/mm</span></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> src, iso</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> random.Random(<span class="dv">6050</span>)</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>pairs, seen_sources <span class="op">=</span> [], <span class="bu">set</span>()</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a><span class="cf">while</span> <span class="bu">len</span>(pairs) <span class="op">&lt;</span> <span class="dv">9000</span>:</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>    pair <span class="op">=</span> make_date(rng)</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> pair[<span class="dv">0</span>] <span class="kw">not</span> <span class="kw">in</span> seen_sources:</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>        seen_sources.add(pair[<span class="dv">0</span>])</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>        pairs.append(pair)</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>train_pairs <span class="op">=</span> pairs[:<span class="dv">8000</span>]</span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>valid_pairs <span class="op">=</span> pairs[<span class="dv">8000</span>:<span class="dv">8500</span>]</span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>test_pairs <span class="op">=</span> pairs[<span class="dv">8500</span>:]</span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="op">*</span>pairs[:<span class="dv">4</span>], sep<span class="op">=</span><span class="st">"</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>train_sources <span class="op">=</span> {s <span class="cf">for</span> s, _ <span class="kw">in</span> train_pairs}</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>valid_sources <span class="op">=</span> {s <span class="cf">for</span> s, _ <span class="kw">in</span> valid_pairs}</span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>test_sources <span class="op">=</span> {s <span class="cf">for</span> s, _ <span class="kw">in</span> test_pairs}</span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"exact-source overlaps: "</span></span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"train/valid </span><span class="sc">{</span><span class="bu">len</span>(train_sources <span class="op">&amp;</span> valid_sources)<span class="sc">}</span><span class="ss">, "</span></span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"train/test </span><span class="sc">{</span><span class="bu">len</span>(train_sources <span class="op">&amp;</span> test_sources)<span class="sc">}</span><span class="ss">, "</span></span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"valid/test </span><span class="sc">{</span><span class="bu">len</span>(valid_sources <span class="op">&amp;</span> test_sources)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a>PAD, BOS, EOS <span class="op">=</span> <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>                             <span class="co"># special tokens first</span></span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a>SRC <span class="op">=</span> <span class="bu">sorted</span>(<span class="bu">set</span>(<span class="st">""</span>.join(s <span class="cf">for</span> s, _ <span class="kw">in</span> pairs)))</span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a>TGT <span class="op">=</span> <span class="bu">sorted</span>(<span class="bu">set</span>(<span class="st">""</span>.join(t <span class="cf">for</span> _, t <span class="kw">in</span> pairs)))</span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a>src_stoi <span class="op">=</span> {c: i <span class="op">+</span> <span class="dv">3</span> <span class="cf">for</span> i, c <span class="kw">in</span> <span class="bu">enumerate</span>(SRC)}</span>
<span id="cb2-49"><a href="#cb2-49" aria-hidden="true" tabindex="-1"></a>tgt_stoi <span class="op">=</span> {c: i <span class="op">+</span> <span class="dv">3</span> <span class="cf">for</span> i, c <span class="kw">in</span> <span class="bu">enumerate</span>(TGT)}</span>
<span id="cb2-50"><a href="#cb2-50" aria-hidden="true" tabindex="-1"></a>tgt_itos <span class="op">=</span> {i: c <span class="cf">for</span> c, i <span class="kw">in</span> tgt_stoi.items()}</span>
<span id="cb2-51"><a href="#cb2-51" aria-hidden="true" tabindex="-1"></a>V_src, V_tgt <span class="op">=</span> <span class="bu">len</span>(SRC) <span class="op">+</span> <span class="dv">3</span>, <span class="bu">len</span>(TGT) <span class="op">+</span> <span class="dv">3</span></span>
<span id="cb2-52"><a href="#cb2-52" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"source vocab </span><span class="sc">{</span>V_src<span class="sc">}</span><span class="ss">, target vocab </span><span class="sc">{</span>V_tgt<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>('26 september 2024', '2024-09-26')
('april 7, 1962', '1962-04-07')
('12/15/1950', '1950-12-15')
('14 february 1997', '1997-02-14')
exact-source overlaps: train/valid 0, train/test 0, valid/test 0
source vocab 37, target vocab 14</code></pre>
</div>
</div>
<p>The rejection loop is evaluation hygiene, not decoration. It removes duplicate source strings <strong>before</strong> the 8,000/500/500 train/validation/test split. We use validation sources for every learning curve and reserve test sources for one final audit after the design is fixed. The same underlying date may appear in another written dialect, which is the structural generalization we want; exact-string memorization is no longer available.</p>
<p>Three special tokens run the show, the same conventions as the course’s full translation pipeline: <code>&lt;pad&gt;</code> fills the short sequences of a batch out to a rectangle, <code>&lt;bos&gt;</code> tells the decoder “begin,” and <code>&lt;eos&gt;</code> lets the <em>model</em> say “I’m done” — remember, the machine must be free to choose its output length.</p>
<p>One more new tool, and it earns a pause. Chapter 10 fed characters in as one-hot vectors. This chapter gives each token a learned vector instead: <code>nn.Embedding</code>, a table with one trainable row per vocabulary entry. There is no new math — an embedding is exactly a one-hot vector times a weight matrix, Chapter 1’s linear map wearing a lookup table’s clothes — but the reading matters: <em>the address is hard, the content is learned</em>. Row 17 is fetched by index, rigidly; what lives in row 17 is whatever training decides that token should mean. Keep the phrase “hard address, learned content” nearby: in <a href="../part4/13-attention.html" class="quarto-xref"><span>Chapter 13</span></a> we soften the address too, and that will be the whole story.</p>
<div id="seq2seq-model" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code: encoder, decoder, and the handoff</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> Seq2Seq(nn.Module):</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, v_src: <span class="bu">int</span>, v_tgt: <span class="bu">int</span>, embed: <span class="bu">int</span> <span class="op">=</span> <span class="dv">32</span>,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>                 hidden: <span class="bu">int</span> <span class="op">=</span> <span class="dv">128</span>, packed: <span class="bu">bool</span> <span class="op">=</span> <span class="va">True</span>):</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.packed <span class="op">=</span> packed</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.src_emb <span class="op">=</span> nn.Embedding(v_src, embed, padding_idx<span class="op">=</span>PAD)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.tgt_emb <span class="op">=</span> nn.Embedding(v_tgt, embed, padding_idx<span class="op">=</span>PAD)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.encoder <span class="op">=</span> nn.LSTM(embed, hidden, batch_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.decoder <span class="op">=</span> nn.LSTM(embed, hidden, batch_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.out <span class="op">=</span> nn.Linear(hidden, v_tgt)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> encode(</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>, S: torch.Tensor, lengths: torch.Tensor,</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>    ) <span class="op">-&gt;</span> <span class="bu">tuple</span>[torch.Tensor, torch.Tensor]:</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>        e <span class="op">=</span> <span class="va">self</span>.src_emb(S)                          <span class="co"># (B, T_src, embed)</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="va">self</span>.packed:                              <span class="co"># stop at each true length</span></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>            e <span class="op">=</span> nn.utils.rnn.pack_padded_sequence(</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>                e, lengths, batch_first<span class="op">=</span><span class="va">True</span>, enforce_sorted<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>        _, state <span class="op">=</span> <span class="va">self</span>.encoder(e)</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> state                                 <span class="co"># (h, c): the context</span></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, S: torch.Tensor, lengths: torch.Tensor,</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>                T_in: torch.Tensor) <span class="op">-&gt;</span> torch.Tensor:  <span class="co"># teacher-forced pass</span></span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>        o, _ <span class="op">=</span> <span class="va">self</span>.decoder(<span class="va">self</span>.tgt_emb(T_in), <span class="va">self</span>.encode(S, lengths))</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">self</span>.out(o)                           <span class="co"># (B, T_tgt, V_tgt) logits</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>The whole architecture is that <code>encode</code> return value: the LSTM’s final <span class="math inline">\((\vect{h},
\vect{c})\)</span>, handed to the decoder as its <em>initial</em> state. With hidden width 128, that bridge carries two 128-dimensional vectors, or <strong>256 scalars</strong>. Everything the decoder will ever know about the source crosses it.</p>
<div id="cell-fig-encoder-decoder-handoff" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code: draw the packed encoder, fixed-state bridge, and decoder</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib.patches <span class="im">import</span> FancyBboxPatch</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">7.6</span>, <span class="fl">3.1</span>))</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>ax.set_xlim(<span class="dv">0</span>, <span class="dv">12</span>)<span class="op">;</span> ax.set_ylim(<span class="dv">0</span>, <span class="dv">5</span>)<span class="op">;</span> ax.axis(<span class="st">"off"</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> token_box(x: <span class="bu">float</span>, y: <span class="bu">float</span>, label: <span class="bu">str</span>, color: <span class="bu">str</span>,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>              alpha: <span class="bu">float</span> <span class="op">=</span> <span class="fl">1.0</span>) <span class="op">-&gt;</span> <span class="va">None</span>:</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    patch <span class="op">=</span> FancyBboxPatch((x <span class="op">-</span> <span class="fl">0.42</span>, y <span class="op">-</span> <span class="fl">0.35</span>), <span class="fl">0.84</span>, <span class="fl">0.7</span>,</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>                           boxstyle<span class="op">=</span><span class="st">"round,pad=0.04"</span>, facecolor<span class="op">=</span>color,</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>                           edgecolor<span class="op">=</span><span class="st">"#232D4B"</span>, linewidth<span class="op">=</span><span class="fl">1.2</span>, alpha<span class="op">=</span>alpha)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    ax.add_patch(patch)</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>    ax.text(x, y, label, ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">9</span>, alpha<span class="op">=</span>alpha)</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>source_labels <span class="op">=</span> [<span class="st">"m"</span>, <span class="st">"a"</span>, <span class="st">"r"</span>, <span class="st">"5"</span>, <span class="st">"&lt;pad&gt;"</span>, <span class="st">"&lt;pad&gt;"</span>]</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> j, label <span class="kw">in</span> <span class="bu">enumerate</span>(source_labels):</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>    faded <span class="op">=</span> label <span class="op">==</span> <span class="st">"&lt;pad&gt;"</span></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>    token_box(<span class="fl">0.75</span> <span class="op">+</span> <span class="fl">1.05</span> <span class="op">*</span> j, <span class="fl">3.15</span>, label,</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>              <span class="st">"#F4F4EF"</span> <span class="cf">if</span> faded <span class="cf">else</span> <span class="st">"#E8F0F8"</span>, <span class="fl">0.4</span> <span class="cf">if</span> faded <span class="cf">else</span> <span class="fl">1.0</span>)</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> j <span class="op">&lt;</span> <span class="dv">3</span>:</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>        ax.annotate(<span class="st">""</span>, (<span class="fl">1.25</span> <span class="op">+</span> <span class="fl">1.05</span> <span class="op">*</span> j, <span class="fl">3.15</span>), (<span class="fl">1.05</span> <span class="op">+</span> <span class="fl">1.05</span> <span class="op">*</span> j, <span class="fl">3.15</span>),</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>                    arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>, color<span class="op">=</span><span class="st">"#5379AA"</span>, lw<span class="op">=</span><span class="fl">1.2</span>))</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>ax.annotate(<span class="st">""</span>, (<span class="fl">6.55</span>, <span class="fl">3.15</span>), (<span class="fl">4.32</span>, <span class="fl">3.15</span>),</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>            arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>, color<span class="op">=</span><span class="st">"#E57200"</span>, lw<span class="op">=</span><span class="dv">2</span>,</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>                            connectionstyle<span class="op">=</span><span class="st">"arc3,rad=-0.45"</span>))</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>ax.text(<span class="fl">5.4</span>, <span class="fl">4.25</span>, <span class="st">"packing bypasses padding"</span>, color<span class="op">=</span><span class="st">"#B45309"</span>,</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>        ha<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>token_box(<span class="fl">7.0</span>, <span class="fl">3.15</span>, <span class="st">"$(h,c)$"</span>, <span class="st">"#F9DCBF"</span>)</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>ax.text(<span class="fl">7.0</span>, <span class="fl">3.9</span>, <span class="st">"256 scalars"</span>, color<span class="op">=</span><span class="st">"#B45309"</span>, ha<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> j, label <span class="kw">in</span> <span class="bu">enumerate</span>([<span class="st">"&lt;bos&gt;"</span>, <span class="st">"2"</span>, <span class="st">"0"</span>, <span class="st">"2"</span>, <span class="st">"1"</span>, <span class="st">"…"</span>]):</span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>    token_box(<span class="fl">7.9</span> <span class="op">+</span> <span class="fl">0.72</span> <span class="op">*</span> j, <span class="fl">1.35</span>, label, <span class="st">"#F4F4EF"</span>)</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> j <span class="op">&lt;</span> <span class="dv">5</span>:</span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>        ax.annotate(<span class="st">""</span>, (<span class="fl">8.25</span> <span class="op">+</span> <span class="fl">0.72</span> <span class="op">*</span> j, <span class="fl">1.35</span>), (<span class="fl">8.15</span> <span class="op">+</span> <span class="fl">0.72</span> <span class="op">*</span> j, <span class="fl">1.35</span>),</span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a>                    arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>, color<span class="op">=</span><span class="st">"#232D4B"</span>, lw<span class="op">=</span><span class="fl">1.0</span>))</span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a>ax.annotate(<span class="st">""</span>, (<span class="fl">7.9</span>, <span class="fl">1.72</span>), (<span class="fl">7.15</span>, <span class="fl">2.8</span>),</span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a>            arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>, color<span class="op">=</span><span class="st">"#E57200"</span>, lw<span class="op">=</span><span class="fl">1.8</span>))</span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a>ax.text(<span class="fl">2.7</span>, <span class="fl">2.25</span>, <span class="st">"encoder"</span>, ha<span class="op">=</span><span class="st">"center"</span>, color<span class="op">=</span><span class="st">"#232D4B"</span>, fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a>ax.text(<span class="fl">9.7</span>, <span class="fl">0.55</span>, <span class="st">"decoder"</span>, ha<span class="op">=</span><span class="st">"center"</span>, color<span class="op">=</span><span class="st">"#232D4B"</span>, fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-encoder-decoder-handoff" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Source tokens flow through an encoder until the last real token, while faded padding boxes are bypassed. One fixed h-and-c state crosses to initialize a decoder that emits the target sequence one token at a time.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-encoder-decoder-handoff-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="11-encoder-decoder_files/figure-html/fig-encoder-decoder-handoff-output-1.png" alt="Source tokens flow through an encoder until the last real token, while faded padding boxes are bypassed. One fixed h-and-c state crosses to initialize a decoder that emits the target sequence one token at a time." width="720" height="288" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-encoder-decoder-handoff-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11.1: The encoder–decoder handoff. Packing stops each encoder at its last real source token, rather than marching through right-padding. Only the final <span class="math inline">\((h,c)\)</span> pair crosses the bridge to initialize the decoder; the earlier encoder states are discarded. Part IV will keep those states and let the decoder look back.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="the-padding-trap" class="level2" data-number="11.2">
<h2 data-number="11.2" class="anchored" data-anchor-id="the-padding-trap"><span class="header-section-number">11.2</span> The padding trap</h2>
<p>Before the machinery works, an honest detour through the way it <em>fails</em>, because the seed notes devote a full section to this and experience says everyone hits it once. Batching variable-length sequences means padding them to a rectangle, and padding poisons two places:</p>
<ol type="1">
<li><strong>The loss.</strong> Positions holding <code>&lt;pad&gt;</code> are not predictions to be graded. <code>F.cross_entropy(..., ignore_index=PAD)</code> excludes them. Our ISO targets all have the same length, so this branch is dormant here, but it makes the loop correct for genuinely variable-length targets.</li>
<li><strong>The encoder.</strong> Subtler and far worse: an LSTM does not know your zeros are padding. It keeps stepping through them, and every pad step smears the final state, the context pair, for every sequence shorter than the batch’s longest. Worse still, at inference you feed single sequences with <em>no</em> padding, so the model is tested in a regime it never trained in.</li>
</ol>
<p>Watch what that costs. Same model, same data, same budget; the only difference is whether the encoder is told the true lengths (<code>pack_padded_sequence</code>, which runs the recurrence only through each sequence’s real tokens):</p>
<div id="padding-experiment" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code: train twice — naive right-padding vs.&nbsp;packed sequences</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> batchify(prs: <span class="bu">list</span>[<span class="bu">tuple</span>[<span class="bu">str</span>, <span class="bu">str</span>]], idx: <span class="bu">list</span>[<span class="bu">int</span>]) <span class="op">-&gt;</span> <span class="bu">tuple</span>[</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    torch.Tensor, torch.Tensor, torch.Tensor</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>]:</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    srcs <span class="op">=</span> [torch.tensor([src_stoi[c] <span class="cf">for</span> c <span class="kw">in</span> prs[i][<span class="dv">0</span>]]) <span class="cf">for</span> i <span class="kw">in</span> idx]</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    lengths <span class="op">=</span> torch.tensor([<span class="bu">len</span>(s) <span class="cf">for</span> s <span class="kw">in</span> srcs])</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    tgts <span class="op">=</span> [torch.tensor([BOS] <span class="op">+</span> [tgt_stoi[c] <span class="cf">for</span> c <span class="kw">in</span> prs[i][<span class="dv">1</span>]] <span class="op">+</span> [EOS])</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>            <span class="cf">for</span> i <span class="kw">in</span> idx]</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    S <span class="op">=</span> nn.utils.rnn.pad_sequence(srcs, batch_first<span class="op">=</span><span class="va">True</span>, padding_value<span class="op">=</span>PAD)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    T <span class="op">=</span> nn.utils.rnn.pad_sequence(tgts, batch_first<span class="op">=</span><span class="va">True</span>, padding_value<span class="op">=</span>PAD)</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> S, lengths, T</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> train_seq2seq(mode: <span class="bu">str</span> <span class="op">=</span> <span class="st">"tf"</span>, packed: <span class="bu">bool</span> <span class="op">=</span> <span class="va">True</span>, epochs: <span class="bu">int</span> <span class="op">=</span> <span class="dv">25</span>,</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>                  seed: <span class="bu">int</span> <span class="op">=</span> <span class="dv">6050</span>, batch: <span class="bu">int</span> <span class="op">=</span> <span class="dv">128</span>,</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>                  checkpoints: <span class="bu">tuple</span>[<span class="bu">int</span>, ...] <span class="op">=</span> ()) <span class="op">-&gt;</span> <span class="bu">tuple</span>[</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>                      Seq2Seq, <span class="bu">dict</span>[<span class="bu">int</span>, <span class="bu">float</span>]</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>                  ]:</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>    torch.manual_seed(seed)</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>    model <span class="op">=</span> Seq2Seq(V_src, V_tgt, packed<span class="op">=</span>packed)</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>    opt <span class="op">=</span> torch.optim.Adam(model.parameters(), lr<span class="op">=</span><span class="fl">1e-3</span>)</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>    n, curve <span class="op">=</span> <span class="bu">len</span>(train_pairs), {}</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> ep <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, epochs <span class="op">+</span> <span class="dv">1</span>):</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>        model.train()</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>        perm <span class="op">=</span> torch.randperm(n)</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>, n, batch):</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>            S, L, T <span class="op">=</span> batchify(train_pairs, perm[i:i <span class="op">+</span> batch].tolist())</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> mode <span class="op">==</span> <span class="st">"tf"</span>:                         <span class="co"># gold rail: one fused call</span></span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>                logits <span class="op">=</span> model(S, L, T[:, :<span class="op">-</span><span class="dv">1</span>])</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>            <span class="cf">else</span>:                                    <span class="co"># free-running: its own rail</span></span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>                state <span class="op">=</span> model.encode(S, L)</span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>                tok, outs <span class="op">=</span> T[:, :<span class="dv">1</span>], []</span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a>                <span class="cf">for</span> t <span class="kw">in</span> <span class="bu">range</span>(T.shape[<span class="dv">1</span>] <span class="op">-</span> <span class="dv">1</span>):</span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a>                    o, state <span class="op">=</span> model.decoder(model.tgt_emb(tok), state)</span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a>                    logit <span class="op">=</span> model.out(o)</span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a>                    outs.append(logit)</span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a>                    tok <span class="op">=</span> logit.argmax(<span class="op">-</span><span class="dv">1</span>)           <span class="co"># feed its own prediction</span></span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a>                logits <span class="op">=</span> torch.cat(outs, <span class="dv">1</span>)</span>
<span id="cb6-37"><a href="#cb6-37" aria-hidden="true" tabindex="-1"></a>            loss <span class="op">=</span> F.cross_entropy(logits.reshape(<span class="op">-</span><span class="dv">1</span>, V_tgt),</span>
<span id="cb6-38"><a href="#cb6-38" aria-hidden="true" tabindex="-1"></a>                                   T[:, <span class="dv">1</span>:].reshape(<span class="op">-</span><span class="dv">1</span>), ignore_index<span class="op">=</span>PAD)</span>
<span id="cb6-39"><a href="#cb6-39" aria-hidden="true" tabindex="-1"></a>            opt.zero_grad()<span class="op">;</span> loss.backward()</span>
<span id="cb6-40"><a href="#cb6-40" aria-hidden="true" tabindex="-1"></a>            nn.utils.clip_grad_norm_(model.parameters(), <span class="fl">5.0</span>)</span>
<span id="cb6-41"><a href="#cb6-41" aria-hidden="true" tabindex="-1"></a>            opt.step()</span>
<span id="cb6-42"><a href="#cb6-42" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> ep <span class="kw">in</span> checkpoints:</span>
<span id="cb6-43"><a href="#cb6-43" aria-hidden="true" tabindex="-1"></a>            curve[ep] <span class="op">=</span> exact_match(model, valid_unamb[:<span class="dv">400</span>])</span>
<span id="cb6-44"><a href="#cb6-44" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> model, curve</span>
<span id="cb6-45"><a href="#cb6-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-46"><a href="#cb6-46" aria-hidden="true" tabindex="-1"></a><span class="at">@torch.no_grad</span>()</span>
<span id="cb6-47"><a href="#cb6-47" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> translate(model: Seq2Seq, src: <span class="bu">str</span>, maxlen: <span class="bu">int</span> <span class="op">=</span> <span class="dv">12</span>) <span class="op">-&gt;</span> <span class="bu">str</span>:</span>
<span id="cb6-48"><a href="#cb6-48" aria-hidden="true" tabindex="-1"></a>    model.<span class="bu">eval</span>()</span>
<span id="cb6-49"><a href="#cb6-49" aria-hidden="true" tabindex="-1"></a>    S <span class="op">=</span> torch.tensor([[src_stoi[c] <span class="cf">for</span> c <span class="kw">in</span> src]])</span>
<span id="cb6-50"><a href="#cb6-50" aria-hidden="true" tabindex="-1"></a>    state <span class="op">=</span> model.encode(S, torch.tensor([<span class="bu">len</span>(src)]))</span>
<span id="cb6-51"><a href="#cb6-51" aria-hidden="true" tabindex="-1"></a>    tok, out <span class="op">=</span> torch.tensor([[BOS]]), <span class="st">""</span></span>
<span id="cb6-52"><a href="#cb6-52" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(maxlen):</span>
<span id="cb6-53"><a href="#cb6-53" aria-hidden="true" tabindex="-1"></a>        o, state <span class="op">=</span> model.decoder(model.tgt_emb(tok), state)</span>
<span id="cb6-54"><a href="#cb6-54" aria-hidden="true" tabindex="-1"></a>        tok <span class="op">=</span> model.out(o).argmax(<span class="op">-</span><span class="dv">1</span>)                <span class="co"># greedy: best next char</span></span>
<span id="cb6-55"><a href="#cb6-55" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> tok.item() <span class="op">==</span> EOS:</span>
<span id="cb6-56"><a href="#cb6-56" aria-hidden="true" tabindex="-1"></a>            <span class="cf">break</span></span>
<span id="cb6-57"><a href="#cb6-57" aria-hidden="true" tabindex="-1"></a>        out <span class="op">+=</span> tgt_itos.get(tok.item(), <span class="st">"?"</span>)</span>
<span id="cb6-58"><a href="#cb6-58" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> out</span>
<span id="cb6-59"><a href="#cb6-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-60"><a href="#cb6-60" aria-hidden="true" tabindex="-1"></a><span class="at">@torch.no_grad</span>()</span>
<span id="cb6-61"><a href="#cb6-61" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> exact_match(model: Seq2Seq, prs: <span class="bu">list</span>[<span class="bu">tuple</span>[<span class="bu">str</span>, <span class="bu">str</span>]]) <span class="op">-&gt;</span> <span class="bu">float</span>:</span>
<span id="cb6-62"><a href="#cb6-62" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="bu">sum</span>(translate(model, s) <span class="op">==</span> t <span class="cf">for</span> s, t <span class="kw">in</span> prs) <span class="op">/</span> <span class="bu">len</span>(prs)</span>
<span id="cb6-63"><a href="#cb6-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-64"><a href="#cb6-64" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> unambiguous(prs: <span class="bu">list</span>[<span class="bu">tuple</span>[<span class="bu">str</span>, <span class="bu">str</span>]]) <span class="op">-&gt;</span> <span class="bu">list</span>[<span class="bu">tuple</span>[<span class="bu">str</span>, <span class="bu">str</span>]]:</span>
<span id="cb6-65"><a href="#cb6-65" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> [(s, t) <span class="cf">for</span> s, t <span class="kw">in</span> prs</span>
<span id="cb6-66"><a href="#cb6-66" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> <span class="st">"/"</span> <span class="kw">not</span> <span class="kw">in</span> s <span class="kw">or</span> <span class="bu">int</span>(s[:<span class="dv">2</span>]) <span class="op">&gt;</span> <span class="dv">12</span> <span class="kw">or</span> <span class="bu">int</span>(s[<span class="dv">3</span>:<span class="dv">5</span>]) <span class="op">&gt;</span> <span class="dv">12</span>]</span>
<span id="cb6-67"><a href="#cb6-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-68"><a href="#cb6-68" aria-hidden="true" tabindex="-1"></a>valid_unamb <span class="op">=</span> unambiguous(valid_pairs)</span>
<span id="cb6-69"><a href="#cb6-69" aria-hidden="true" tabindex="-1"></a>test_unamb <span class="op">=</span> unambiguous(test_pairs)</span>
<span id="cb6-70"><a href="#cb6-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-71"><a href="#cb6-71" aria-hidden="true" tabindex="-1"></a>cps <span class="op">=</span> (<span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">8</span>, <span class="dv">12</span>, <span class="dv">16</span>, <span class="dv">20</span>, <span class="dv">25</span>)</span>
<span id="cb6-72"><a href="#cb6-72" aria-hidden="true" tabindex="-1"></a>naive, _ <span class="op">=</span> train_seq2seq(packed<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb6-73"><a href="#cb6-73" aria-hidden="true" tabindex="-1"></a>packed, packed_curve <span class="op">=</span> train_seq2seq(packed<span class="op">=</span><span class="va">True</span>, checkpoints<span class="op">=</span>cps)</span>
<span id="cb6-74"><a href="#cb6-74" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"naive right-padding:   validation exact match "</span></span>
<span id="cb6-75"><a href="#cb6-75" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>exact_match(naive, valid_unamb)<span class="sc">:.1%}</span><span class="ss">"</span>)</span>
<span id="cb6-76"><a href="#cb6-76" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"packed (true lengths): validation exact match "</span></span>
<span id="cb6-77"><a href="#cb6-77" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>exact_match(packed, valid_unamb)<span class="sc">:.1%}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>naive right-padding:   validation exact match 37.3%
packed (true lengths): validation exact match 95.7%</code></pre>
</div>
</div>
<p>Validation exact match jumps from 37.3% to 95.7%, a 58.4-point gap. Not from a better architecture, optimizer, or dataset; from telling the encoder where the sentences actually end. Let the gap sink in, because this is the cheapest lesson in the book: the two runs are identical except for bookkeeping, and the bookkeeping was worth more than every design decision in Part III so far. The sealed test set remains untouched until both training-mode designs below are fixed.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Trap: the model will happily read your padding
</div>
</div>
<div class="callout-body-container callout-body">
<p>Nothing in the tensor marks <code>&lt;pad&gt;</code> as meaningless; meaning is something <em>you</em> enforce, in two places: <code>ignore_index</code> for the loss, <code>pack_padded_sequence</code> (or an explicit mask) for the encoder. When a sequence model underperforms mysteriously, audit the padding before touching the architecture. And file the general shape of this tool away: telling a model <em>which positions it may not look at</em> is called <strong>masking</strong>, and it returns center-stage in <a href="../part4/14-self-attention-transformer.html" class="quarto-xref"><span>Chapter 14</span></a>, where a <em>causal</em> mask is what turns a transformer into a language model.</p>
</div>
</div>
</section>
<section id="teacher-forcing-training-on-the-gold-rail" class="level2" data-number="11.3">
<h2 data-number="11.3" class="anchored" data-anchor-id="teacher-forcing-training-on-the-gold-rail"><span class="header-section-number">11.3</span> Teacher forcing: training on the gold rail</h2>
<p>Look back at the two <code>mode</code> branches in the training loop; they are this section. When the decoder is trained, what should it see as <em>its own previous output</em>?</p>
<p><strong>Free-running</strong> (“fr”) is the honest answer: feed the model’s own predictions back in, exactly as at inference. But its flaws are structural. Early in training those predictions are garbage <span class="math inline">\(\rightarrow\)</span> the decoder learns conditioned on garbage <span class="math inline">\(\rightarrow\)</span> every sequence must be generated token-by-token in a Python loop, because step <span class="math inline">\(t\)</span>’s input does not exist until step <span class="math inline">\(t-1\)</span> is computed. Slow, and unstable exactly when training is young.</p>
<p><strong>Teacher forcing</strong> (“tf”) conditions each step on the <em>ground-truth</em> previous token instead, the gold rail. Every conditioning input is then known in advance <span class="math inline">\(\rightarrow\)</span> the whole target can be submitted in <strong>one fused decoder call</strong> (the <code>model(S, L, T[:, :-1])</code> line), rather than a Python feedback loop. The LSTM still processes time recurrently inside that call; teacher forcing does not make its timesteps mathematically parallel. Every step nevertheless learns from a sensible context from epoch one. Watch both effects:</p>
<div id="cell-fig-tf-vs-fr" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code: teacher forcing vs.&nbsp;free-running, learning curves</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>tf_model, tf_curve <span class="op">=</span> packed, packed_curve</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>fr_model, fr_curve <span class="op">=</span> train_seq2seq(<span class="st">"fr"</span>, checkpoints<span class="op">=</span>cps)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"one final test audit (unambiguous sources):"</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> label, candidate <span class="kw">in</span> [(<span class="st">"naive padding"</span>, naive),</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>                         (<span class="st">"packed / teacher forced"</span>, tf_model),</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>                         (<span class="st">"packed / free-running"</span>, fr_model)]:</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>label<span class="sc">:25s}</span><span class="ss"> </span><span class="sc">{</span>exact_match(candidate, test_unamb)<span class="sc">:.1%}</span><span class="ss">"</span>)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">6</span>, <span class="fl">3.2</span>))</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>plt.plot(cps, [tf_curve[c] <span class="cf">for</span> c <span class="kw">in</span> cps], <span class="st">"o-"</span>, color<span class="op">=</span><span class="st">"#232D4B"</span>, lw<span class="op">=</span><span class="dv">2</span>,</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>         label<span class="op">=</span><span class="st">"teacher forcing"</span>)</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>plt.plot(cps, [fr_curve[c] <span class="cf">for</span> c <span class="kw">in</span> cps], <span class="st">"s-"</span>, color<span class="op">=</span><span class="st">"#E57200"</span>, lw<span class="op">=</span><span class="dv">2</span>,</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>         label<span class="op">=</span><span class="st">"free-running"</span>)</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"epoch"</span>)<span class="op">;</span> plt.ylabel(<span class="st">"exact match"</span>)</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>plt.legend()<span class="op">;</span> plt.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>one final test audit (unambiguous sources):
  naive padding             34.3%
  packed / teacher forced   93.1%
  packed / free-running     99.1%</code></pre>
</div>
<div class="cell-output cell-output-display">
<div id="fig-tf-vs-fr" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Exact-match accuracy rises with epoch for both training modes. Teacher forcing leads strongly in early and middle epochs, then the free-running curve catches it near the top by epoch twenty.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tf-vs-fr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="11-encoder-decoder_files/figure-html/fig-tf-vs-fr-output-2.png" alt="Exact-match accuracy rises with epoch for both training modes. Teacher forcing leads strongly in early and middle epochs, then the free-running curve catches it near the top by epoch twenty." width="567" height="297" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tf-vs-fr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11.2: Learning curves on a fixed subset of 400 unambiguous validation source strings, disjoint from both training and test. Teacher forcing leads through the early and middle epochs (53.8% vs.&nbsp;23.8% at epoch 6; 95.0% vs.&nbsp;81.2% at epoch 12) and uses one fused decoder call per batch where free-running needs a Python token loop. By epoch 20 the validation curves meet; the single final test audit favors free-running.
</figcaption>
</figure>
</div>
</div>
</div>
<p>So teacher forcing is the pragmatic default: fused, stable, and fast out of the gate. What it costs has a name. A teacher-forced decoder has <em>only ever seen perfect histories</em>. At inference it must condition on its own imperfect predictions — a distribution it never trained on. This mismatch is <strong>exposure bias</strong>: the model never learned to recover from its own mistakes, so one early slip can send the rest of the sequence somewhere strange. You can see the shape of this failure in our model’s rare residual errors:</p>
<div id="error-gallery" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code: the residual errors, up close</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>errs <span class="op">=</span> [(s, t, translate(tf_model, s))</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> s, t <span class="kw">in</span> test_unamb <span class="cf">if</span> translate(tf_model, s) <span class="op">!=</span> t]</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="bu">len</span>(errs)<span class="sc">}</span><span class="ss"> errors on </span><span class="sc">{</span><span class="bu">len</span>(test_unamb)<span class="sc">}</span><span class="ss"> unambiguous test dates; a sample:"</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> s, t, g <span class="kw">in</span> errs[:<span class="dv">3</span>]:</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>s<span class="sc">!r}</span><span class="ss"> -&gt; </span><span class="sc">{</span>g<span class="sc">!r}</span><span class="ss">   (truth </span><span class="sc">{</span>t<span class="sc">}</span><span class="ss">)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>30 errors on 437 unambiguous test dates; a sample:
  '03/21/1958' -&gt; '1958-03-22'   (truth 1958-03-21)
  '01/22/1996' -&gt; '1996-02-12'   (truth 1996-01-22)
  '21 november 2013' -&gt; '2013-11-22'   (truth 2013-11-21)</code></pre>
</div>
</div>
<p>The errors are plausible-looking digit substitutions and order slips. The decoder has learned a date-shaped language, but no hard mechanism forces each output field to copy the corresponding source fact. Off the gold rail, one wrong character can alter the context for every character after it. Hold that thought two sections.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Scheduled sampling: renting the rail
</div>
</div>
<div class="callout-body-container callout-body">
<p>The engineered compromise (Bengio et al., 2015): during training, at <em>each timestep</em> flip a biased coin — probability <span class="math inline">\(\epsilon\)</span> of the gold token, <span class="math inline">\(1 -
\epsilon\)</span> of the model’s own prediction — and anneal <span class="math inline">\(\epsilon\)</span> from 1 toward 0 as training matures. Early epochs enjoy the gold rail; late epochs practice recovery. One design detail from the original paper worth repeating: flip <strong>per token, not per sequence</strong> — committing a whole sequence to model predictions early in training lets consecutive errors amplify. Exercise 3 has you build it.</p>
</div>
</div>
</section>
<section id="getting-answers-out-search" class="level2" data-number="11.4">
<h2 data-number="11.4" class="anchored" data-anchor-id="getting-answers-out-search"><span class="header-section-number">11.4</span> Getting answers out: search</h2>
<p>Training is settled; now the neglected half. At inference the decoder defines a probability for every possible output sequence, and we want the best one. That is a <em>search problem</em> over a tree where every node branches <span class="math inline">\(V_{\text{tgt}}\)</span> ways; exhaustive search is <span class="math inline">\(V^{T}\)</span>, hopeless. Everything practical is a heuristic walk through that tree.</p>
<p><strong>Greedy search</strong>, which <code>translate</code> above already performs, takes the single most probable token at each step and never looks back. Complexity <span class="math inline">\(O(V \cdot T)\)</span>, quality: usually fine, occasionally myopic. The failure mode is structural: a token that looks best <em>right now</em> can commit the decoder to a mediocre continuation, when a slightly worse token now would have opened a much better path. Maximizing each step is not maximizing the sequence. You met this exact gap in <a href="../part1/02-logistic-softmax.html" class="quarto-xref"><span>Chapter 2</span></a>, where the hard max’s stepwise confidence hid the alternatives softmax kept alive.</p>
<p><strong>Beam search</strong> widens the walk: carry the <span class="math inline">\(k\)</span> best partial sequences (the <em>beam</em>), expand each by all <span class="math inline">\(V\)</span> tokens, keep the top <span class="math inline">\(k\)</span> by <em>cumulative</em> log-probability, repeat. Complexity <span class="math inline">\(O(k \cdot V \cdot T)\)</span>, a small multiple of greedy, nothing like exhaustive.</p>
<div id="beam-search" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Code: beam search, k candidate rails at once</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="at">@torch.no_grad</span>()</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> beam_search(model: Seq2Seq, src: <span class="bu">str</span>, k: <span class="bu">int</span> <span class="op">=</span> <span class="dv">5</span>,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>                maxlen: <span class="bu">int</span> <span class="op">=</span> <span class="dv">12</span>) <span class="op">-&gt;</span> <span class="bu">list</span>[<span class="bu">tuple</span>[<span class="bu">str</span>, <span class="bu">float</span>]]:</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    model.<span class="bu">eval</span>()</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    S <span class="op">=</span> torch.tensor([[src_stoi[c] <span class="cf">for</span> c <span class="kw">in</span> src]])</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    state <span class="op">=</span> model.encode(S, torch.tensor([<span class="bu">len</span>(src)]))</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    beams <span class="op">=</span> [([], <span class="fl">0.0</span>, state, <span class="va">False</span>)]               <span class="co"># (tokens, logp, state, done)</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(maxlen):</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>        cand <span class="op">=</span> []</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> seq, lp, st, done <span class="kw">in</span> beams:</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> done:</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>                cand.append((seq, lp, st, <span class="va">True</span>))<span class="op">;</span> <span class="cf">continue</span></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>            tok <span class="op">=</span> torch.tensor([[seq[<span class="op">-</span><span class="dv">1</span>] <span class="cf">if</span> seq <span class="cf">else</span> BOS]])</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>            o, st2 <span class="op">=</span> model.decoder(model.tgt_emb(tok), st)</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>            logp <span class="op">=</span> F.log_softmax(model.out(o)[<span class="dv">0</span>, <span class="op">-</span><span class="dv">1</span>], <span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>            top <span class="op">=</span> torch.topk(logp, k)</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>            <span class="cf">for</span> lg, ix <span class="kw">in</span> <span class="bu">zip</span>(top.values, top.indices):</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>                cand.append((seq <span class="op">+</span> [ix.item()], lp <span class="op">+</span> lg.item(), st2,</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>                             ix.item() <span class="op">==</span> EOS))</span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>        beams <span class="op">=</span> <span class="bu">sorted</span>(cand, key<span class="op">=</span><span class="kw">lambda</span> b: <span class="op">-</span>b[<span class="dv">1</span>])[:k]</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="bu">all</span>(b[<span class="dv">3</span>] <span class="cf">for</span> b <span class="kw">in</span> beams):</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>            <span class="cf">break</span></span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> [(<span class="st">""</span>.join(tgt_itos.get(i, <span class="st">"?"</span>) <span class="cf">for</span> i <span class="kw">in</span> seq <span class="cf">if</span> i <span class="op">&gt;</span> <span class="dv">2</span>), lp)</span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a>            <span class="cf">for</span> seq, lp, _, _ <span class="kw">in</span> beams]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Now the payoff, and it is exactly where we buried it: the ambiguous dates. For <code>03/05/2021</code>, “the one best answer” is the wrong question. The training world itself was split 70/30 between two readings. Greedy silently hands you one sequence; beam search shows which complete alternatives the model ranks highly:</p>
<div id="beam-demo" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Code: beam search on genuinely ambiguous dates</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>amb <span class="op">=</span> [(s, t) <span class="cf">for</span> s, t <span class="kw">in</span> test_pairs</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>       <span class="cf">if</span> <span class="st">"/"</span> <span class="kw">in</span> s <span class="kw">and</span> <span class="bu">int</span>(s[:<span class="dv">2</span>]) <span class="op">&lt;=</span> <span class="dv">12</span> <span class="kw">and</span> <span class="bu">int</span>(s[<span class="dv">3</span>:<span class="dv">5</span>]) <span class="op">&lt;=</span> <span class="dv">12</span>]</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> s, t <span class="kw">in</span> amb[:<span class="dv">4</span>]:</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>s<span class="sc">!r}</span><span class="ss">   truth: </span><span class="sc">{</span>t<span class="sc">!r}</span><span class="ss">   greedy: </span><span class="sc">{</span>translate(tf_model, s)<span class="sc">!r}</span><span class="ss">"</span>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> text, lp <span class="kw">in</span> beam_search(tf_model, s, k<span class="op">=</span><span class="dv">4</span>)[:<span class="dv">2</span>]:</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"   beam: </span><span class="sc">{</span>text<span class="sc">!r}</span><span class="ss">   joint log score = </span><span class="sc">{</span>lp<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>'09/02/1995'   truth: '1995-09-02'   greedy: '1995-09-02'
   beam: '1995-09-02'   joint log score = -0.23
   beam: '1995-09-20'   joint log score = -1.84

'12/06/2006'   truth: '2006-06-12'   greedy: '2006-12-06'
   beam: '2006-12-06'   joint log score = -0.21
   beam: '2006-06-12'   joint log score = -2.51

'08/01/1989'   truth: '1989-08-01'   greedy: '1989-08-01'
   beam: '1989-08-01'   joint log score = -0.14
   beam: '1989-01-08'   joint log score = -2.51

'01/03/1991'   truth: '1991-01-03'   greedy: '1991-01-03'
   beam: '1991-01-03'   joint log score = -0.54
   beam: '1991-03-01'   joint log score = -1.23
</code></pre>
</div>
</div>
<p>Each displayed score is the sum of token log-probabilities along that one sequence, including <code>&lt;eos&gt;</code> when it was reached. These are <strong>raw joint log scores</strong>, not a normalized distribution over the printed beam, so exponentiating two of them and calling the result a 70/30 posterior would be wrong. Some pairs correspond cleanly to the month/day and day/month readings. Others include a high-scoring hybrid that matches neither convention, an honest reminder that beam search searches the model; it does not install a calendar constraint. The ranking still exposes alternatives that greedy search hides.</p>
<p>Honesty requires the other half of the report:</p>
<div id="beam-vs-greedy-stat" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>Code: how often beam actually changes the answer</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>sub <span class="op">=</span> random.Random(<span class="dv">0</span>).sample(test_pairs, <span class="dv">200</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>n_diff <span class="op">=</span> <span class="bu">sum</span>(beam_search(tf_model, s, k<span class="op">=</span><span class="dv">5</span>)[<span class="dv">0</span>][<span class="dv">0</span>] <span class="op">!=</span> translate(tf_model, s)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>             <span class="cf">for</span> s, _ <span class="kw">in</span> sub)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"beam-5 disagrees with greedy on </span><span class="sc">{</span>n_diff<span class="sc">}</span><span class="ss"> of </span><span class="sc">{</span><span class="bu">len</span>(sub)<span class="sc">}</span><span class="ss"> test dates"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>beam-5 disagrees with greedy on 1 of 200 test dates</code></pre>
</div>
</div>
<p>On this small, well-trained model, beam search changes almost nothing. Beam search earns its keep at the margins, but real translation, with vocabularies of tens of thousands and long sentences, lives entirely at those margins, which is why beam decoding became a standard tool of the seq2seq era.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Length normalization
</div>
</div>
<div class="callout-body-container callout-body">
<p>Summed log-probabilities shrink as sequences grow <span class="math inline">\(\rightarrow\)</span> a raw beam quietly favors short outputs. The standard correction divides the score by <span class="math inline">\(L^{\alpha}\)</span> with <span class="math inline">\(\alpha \approx 0.6\)</span>–<span class="math inline">\(0.75\)</span>. Our dates all have the same length, so the bias is largely invisible for correct outputs here (Exercise 4 makes you check the remaining error cases); in free-length generation it matters enormously.</p>
</div>
</div>
</section>
<section id="the-fixed-size-state-in-the-middle" class="level2" data-number="11.5">
<h2 data-number="11.5" class="anchored" data-anchor-id="the-fixed-size-state-in-the-middle"><span class="header-section-number">11.5</span> The fixed-size state in the middle</h2>
<p>Time to stare at the handoff. Every property of the source that the decoder will ever use crossed one bridge: <span class="math inline">\((\vect{h},\vect{c})\)</span>, two 128-dimensional vectors and therefore 256 scalars. Our task fits because a date is three facts, yet its residual digit and order errors are consistent with a decoder reconstructing from a compressed summary rather than consulting source positions directly. They do not, by themselves, prove that compression caused each error. Now scale the ambition: a forty-word sentence, clause structure, names, negations, all crammed through the same fixed pipe, <em>regardless of length</em>. Chapter 10 called this the price of the Markov claim; here the bill arrives itemized.</p>
<p>And notice what the architecture throws away: the encoder <em>had</em> a state at every step, a whole trajectory of summaries, one per source position, and we kept only the last. The fix that defines Part IV is almost embarrassingly direct: keep them all, and let the decoder <em>look back</em> at whichever ones matter for the token it is writing right now. Choosing where to look, by similarity, on the fly: you have owned the primitive since Chapter 1’s dot product, and Chapter 2 promised you the “soft lookup” that makes it differentiable. <a href="../part4/12-kernel-regression.html" class="quarto-xref"><span>Chapter 12</span></a> builds the classical version; <a href="../part4/13-attention.html" class="quarto-xref"><span>Chapter 13</span></a> makes it learnable and comes back for this very date task with an alignment map to show where the decoder looks.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Check yourself
</div>
</div>
<div class="callout-body-container callout-body">
<p>Close the book for one minute and reconstruct the sequence pipeline from memory.</p>
<ul>
<li>Which two places must exclude padding, and what tool handles each one?</li>
<li>What mismatch does teacher forcing create between training and inference?</li>
<li>What does beam search change, and what part of the learned model does it leave unchanged?</li>
</ul>
</div>
</div>
</section>
<section id="okay-so-the-fixed-size-handoff-is-the-bottleneck" class="level2" data-number="11.6">
<h2 data-number="11.6" class="anchored" data-anchor-id="okay-so-the-fixed-size-handoff-is-the-bottleneck"><span class="header-section-number">11.6</span> Okay, so — the fixed-size handoff is the bottleneck</h2>
<ol type="1">
<li><strong>Encoder–decoder = two RNNs and a handoff</strong>: read the source into a final state, hand it over, generate from it. <code>&lt;bos&gt;</code> starts the decoder, <code>&lt;eos&gt;</code> lets it choose its length, embeddings replace one-hots (hard address, learned content).</li>
<li><strong>Padding poisons twice</strong>: the loss (<code>ignore_index</code>) and the encoder (<code>pack_padded_sequence</code>). On never-seen source strings, the same model and budget score 34.3% naive versus 93.1% packed. Target padding is included for reuse but not exercised by these fixed-length ISO targets. Audit bookkeeping before architecture.</li>
<li><strong>Teacher forcing</strong> trains the decoder on the gold rail: one fused call with no Python feedback loop and stable early learning, at the cost of <strong>exposure bias</strong>, the train/inference mismatch that free-running avoids by paying with speed and early instability. Scheduled sampling anneals between them, flipping per token.</li>
<li><strong>Decoding is search.</strong> Greedy maximizes steps, not sequences; beam search carries <span class="math inline">\(k\)</span> rails for <span class="math inline">\(O(k V T)\)</span> and surfaces high-scoring alternatives. Its raw joint log scores are rankings, not a normalized posterior, and a beam can contain invalid hybrids. Length normalization (<span class="math inline">\(L^{\alpha}\)</span>) keeps long outputs competitive.</li>
<li><strong>The bottleneck is now the story.</strong> One fixed-size <span class="math inline">\((\vect{h},\vect{c})\)</span> pair, 256 scalars here, connects reader and writer regardless of input length. The encoder’s per-step states were there all along. Part IV is what happens when we stop throwing them away.</li>
</ol>
</section>
<section id="sources-and-further-reading" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="sources-and-further-reading">Sources and further reading</h2>
<ul>
<li><a href="https://proceedings.neurips.cc/paper/2014/hash/a14ac55a4f27472c5d894ec1c3c743d2-Abstract.html">Sutskever, Vinyals, &amp; Le, <em>Sequence to Sequence Learning with Neural Networks</em></a>: the canonical fixed-state LSTM encoder–decoder and source-reversal result.</li>
<li><a href="https://proceedings.neurips.cc/paper/2015/hash/e995f98d56967d946471af29d7bf99f1-Abstract.html">Bengio et al., <em>Scheduled Sampling for Sequence Prediction with Recurrent Neural Networks</em></a>: the original exposure-bias intervention used in Exercise 3.</li>
<li><a href="https://arxiv.org/abs/1409.0473">Bahdanau, Cho, &amp; Bengio, <em>Neural Machine Translation by Jointly Learning to Align and Translate</em></a>: removes the single-state bottleneck by learning where to look; Chapter 13 performs the full harvest.</li>
</ul>
</section>
<section id="exercises" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercises">Exercises</h2>
<ol type="1">
<li><strong>(Pencil.)</strong> Count this chapter’s parameters: two embeddings, two LSTMs, one output layer (<span class="math inline">\(V_{\text{src}} = 37\)</span>, <span class="math inline">\(V_{\text{tgt}} = 14\)</span>, embed 32, hidden 128; an LSTM holds <span class="math inline">\(4\left[(e + h)h + 2h\right]\)</span> — derive that first). Where do most parameters live, and why is the answer different from Chapter 8’s LeNet audit?</li>
<li><strong>(Pencil.)</strong> With vocabulary <span class="math inline">\(10^4\)</span> and output length 10, compare the number of sequences examined by exhaustive search, greedy, and beam-5. Then explain why beam search with <span class="math inline">\(k = V^{T}\)</span> is exact and with <span class="math inline">\(k = 1\)</span> is greedy — and why neither endpoint is usable.</li>
<li><strong>(Code.)</strong> Implement scheduled sampling: per token, use the gold input with probability <span class="math inline">\(\epsilon\)</span>, the model’s own prediction otherwise, annealing <span class="math inline">\(\epsilon\)</span> linearly <span class="math inline">\(1 \to 0\)</span> over 25 epochs. Compare its learning curve with both curves in <a href="#fig-tf-vs-fr" class="quarto-xref">Figure&nbsp;<span>11.2</span></a>. Does it inherit teacher forcing’s fast start <em>and</em> free-running’s finish?</li>
<li><strong>(Code.)</strong> Add length normalization (<span class="math inline">\(/L^{\alpha}\)</span>) to <code>beam_search</code> and sweep <span class="math inline">\(\alpha \in \{0, 0.7, 1\}\)</span> on the date task. Explain why correct ten-character outputs are unaffected, inspect whether any erroneous beams change, and design the smallest change to the <em>task</em> that would make <span class="math inline">\(\alpha\)</span> matter.</li>
<li><strong>(Code.)</strong> Sutskever et al.&nbsp;(2014) famously improved translation by feeding the source sentence <em>reversed</em>. Try it here. Whatever you observe, explain it with this chapter’s tools: which source-target dependencies does reversal shorten in their setting, and which does it shorten — or lengthen — for dates, where the year sits at the end of the source but the start of the target?</li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/shakeri-lab\.github\.io\/dl-book\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../chapters/part3/10-sequences-rnn.html" class="pagination-link" aria-label="Sequences and Recurrence">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Sequences and Recurrence</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/part4/12-kernel-regression.html" class="pagination-link" aria-label="Kernel Regression: Attention Before It Was Learnable">
        <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Kernel Regression: Attention Before It Was Learnable</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Heman Shakeri · Text CC BY-NC-SA 4.0 · Code MIT · School of Data Science, University of Virginia</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/Shakeri-Lab/dl-book/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Companion to <a href="https://shakeri-lab.github.io/dl-course-site/">DS 6050 Deep Learning</a></p>
</div>
  </div>
</footer>




</body></html>