{
  "hash": "81b32ef8ebbd5b6201cd2067c64ad0a8",
  "result": {
    "engine": "jupyter",
    "markdown": "# Interlude: Attention as Test-Time Regression {#sec-interlude-test-time-regression .unnumbered}\n\n<!-- provenance:\n     Promoted from Chapter 14's verified memory-spectrum unit. Primary sources\n     appear below. Equations, code, figures, and the sealed CPU study are original\n     to the book. -->\n\nChapter 14 kept visible evidence in a growing key--value table. This interlude holds\nthe regression question fixed and changes the forward-pass solver. The comparison\nreveals what each solver retains, what it costs, and which statistical contract it\naccepts.\n\n\n\n## One regression, three solvers\n\nThe Transformer resolved Chapter 10's bottleneck by keeping the visible evidence\navailable. Its quadratic routing bill was the price. There is another resolution:\nkeep the *problem* Chapter 12 posed, but change how the forward pass solves it.\n\nThat move has become a live architecture program under names such as test-time\nregression, fast weights, linear attention, DeltaNet, and state-space sequence models.\nThe useful unit is not the model name. It is one objective and the statistical bargain\nmade by its solver.\n\n### One objective, four dials\n\nAt time $t$, let learned projections turn token representation $\\vect{x}_\\tau$ into\ntwo views,\n\n$$\n\\vect{k}_\\tau=\\matr{W}_K\\vect{x}_\\tau,\n\\qquad\n\\vect{v}_\\tau=\\matr{W}_V\\vect{x}_\\tau.\n$$\n\nA memory layer can be described as building an online predictor\n$M_t:\\mathbb{R}^{d_k}\\rightarrow\\mathbb{R}^{d_v}$:\n\n$$\nM_t\n=\\arg\\min_{M\\in\\mathcal{M}}\n\\frac{1}{2}\\sum_{\\tau\\le t}w_{t,\\tau}\n\\norm{M(\\vect{k}_\\tau)-\\vect{v}_\\tau}^{2}\n+\\Omega(M),\n\\qquad\n\\vect{y}_t=M_t(\\vect{q}_t),\n\\quad \\vect{q}_t=\\matr{W}_Q\\vect{x}_t.\n$$\n\nThis is Wang, Shi, and Fox's test-time-regression frame, written for vector values.\nIt exposes four dials the book already knows.\n\n**The views.** $W_Q,W_K,W_V$ are Chapter 13's learned comparison and payload spaces.\nThe token is not assigned one permanent meaning; it learns what to ask, advertise,\nand carry.\n\n**The history weights.** $w_{t,\\tau}$ decide how much an older residual matters to\nthe fitting problem. Chapter 10's forget gates prepared the idea that retention can\ndepend on time and content. A geometric schedule can privilege recent errors; an\ninput-dependent schedule can decide that one token deserves a longer trace.\n\n**The model and regularizer.** The class $\\mathcal{M}$ decides whether the predictor\nis a local constant, a linear map, or something richer. $\\Omega$ brings back ridge\npenalties from Chapter 1 and weight decay from Chapter 4. Regularization controls the\nfitted map; it is not, by itself, the same operation as forgetting old observations.\n\n**The solver.** A closed-form local fit, a running sufficient statistic, and one\ngradient step do different work and preserve different information. This is the new\nrung: *what if the solver itself were a design choice, or even learned?*\n\nThis objective is an umbrella, not an equivalence theorem. Its\nmethods can restrict different function classes, use different weights, and stop at\ndifferent approximations. Those differences are the lesson.\n\n### Solver 1: keep the data and fit at the query\n\nChapter 12 was more precise than saying “attention minimizes\nthe shared objective.” For a query $\\vect{q}$, softmax attention solves the\nlocal-constant problem\n\n$$\n\\vect{c}^{*}(\\vect{q})\n=\\arg\\min_{\\vect{c}}\n\\frac{1}{2}\\sum_{\\tau\\le t}\n\\kappa(\\vect{q},\\vect{k}_\\tau)\n\\norm{\\vect{c}-\\vect{v}_\\tau}^{2}.\n$$\n\nWrite $\\kappa_\\tau=\\kappa(\\vect{q},\\vect{k}_\\tau)$. Differentiation gives\n\n$$\n\\nabla_{\\vect{c}}=\n\\sum_{\\tau\\le t}\\kappa_\\tau(\\vect{c}-\\vect{v}_\\tau)=\\vect{0}\n\\quad\\Longrightarrow\\quad\n\\vect{c}^{*}=\n\\frac{\\sum_\\tau\\kappa_\\tau\\vect{v}_\\tau}{\\sum_\\tau\\kappa_\\tau}.\n$$\n\nChoose\n$\\kappa(\\vect{q},\\vect{k})=\\exp(\\vect{q}^{\\top}\\vect{k}/\\sqrt{d_k})$ and the\nnormalized coefficients are exactly a row of scaled dot-product softmax. The kernel\nsupplies the weights; the constant fit supplies the average. An unrestricted $M$ with\nunit observation weights and no regularizer would instead interpolate compatible\ntraining pairs and be undetermined away from them. We will not smuggle the average\ninto a stronger claim.\n\nHere is the numerical stationarity audit. Subtracting the largest score rescales every\n$\\kappa_\\tau$ by the same positive constant and leaves the minimizer unchanged.\n\n:::: {.plan-code}\n::: {.plan}\n1. Prepare the inputs and fixed settings for the example.\n2. Verify softmax attention's local-constant optimum.\n3. Report or visualize the measured result.\n:::\n\n::: {#local-constant-attention-check .cell execution_count=2}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: verify softmax attention's local-constant optimum\"}\n# [1]\nms_rng = np.random.default_rng(6050)\nms_d, ms_T = 8, 12\nms_K = ms_rng.standard_normal((ms_T, ms_d))\nms_V = ms_rng.standard_normal((ms_T, 3))\nms_q = ms_rng.standard_normal(ms_d)\nms_scores = ms_K @ ms_q / np.sqrt(ms_d)\nms_kappa = np.exp(ms_scores - ms_scores.max())\nms_c = (ms_kappa[:, None] * ms_V).sum(0) / ms_kappa.sum()\nms_attention = (ms_kappa / ms_kappa.sum()) @ ms_V\nms_gradient = (ms_kappa[:, None] * (ms_c - ms_V)).sum(0)\n# [2]\nassert np.allclose(ms_c, ms_attention)\n# [3]\nprint(f\"max |stationarity gradient|: {np.abs(ms_gradient).max():.3e}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmax |stationarity gradient|: 3.053e-16\n```\n:::\n:::\n\n\n::::\nThis solver retains the key--value rows because a future query may weight every row\ndifferently. That is why dense causal attention carries a growing dataset forward.\n\n### Solver 2: collapse a factorized kernel into sufficient state\n\nSuppose the kernel factors through a finite feature map\n$\\phi:\\mathbb{R}^{d_k}\\rightarrow\\mathbb{R}^{r}$:\n\n$$\n\\kappa(\\vect{q},\\vect{k})\n=\\phi(\\vect{q})^{\\top}\\phi(\\vect{k}).\n$$\n\nSubstitute that factorization into the weighted average and regroup terms:\n\n$$\n\\begin{aligned}\n\\vect{y}_t(\\vect{q})\n&=\\frac{\\sum_{\\tau\\le t}\n\\bigl[\\phi(\\vect{q})^{\\top}\\phi(\\vect{k}_\\tau)\\bigr]\\vect{v}_\\tau}\n{\\sum_{\\tau\\le t}\\phi(\\vect{q})^{\\top}\\phi(\\vect{k}_\\tau)} \\\\\n&=\\frac{\\phi(\\vect{q})^{\\top}\\matr{S}_t}\n{\\phi(\\vect{q})^{\\top}\\vect{z}_t},\n\\end{aligned}\n$$\n\nwhere\n\n$$\n\\matr{S}_t=\\sum_{\\tau\\le t}\\phi(\\vect{k}_\\tau)\\vect{v}_\\tau^{\\top},\n\\qquad\n\\vect{z}_t=\\sum_{\\tau\\le t}\\phi(\\vect{k}_\\tau).\n$$\n\nThe sufficient state is the pair $(\\matr{S}_t,\\vect{z}_t)$, not $\\matr{S}_t$ alone:\nthe numerator needs accumulated value-weighted features and the denominator needs its\nnormalizer. Each new pair updates that fixed-size state once. Any later query reads the\nsame answer as a full traversal of all pairs, for this factorized kernel.\n\n:::: {.plan-code}\n::: {.plan}\n1. Define the reusable `ms_phi` helper.\n2. Prepare the inputs and fixed settings for the example.\n3. Compare a factorized-kernel traversal with its running state.\n4. Check the claimed identities, shapes, or invariants.\n5. Report or visualize the measured result.\n:::\n\n::: {#linear-attention-sufficient-state-check .cell execution_count=3}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: compare a factorized-kernel traversal with its running state\"}\n# [1]\ndef ms_phi(x):\n    return np.where(x > 0, x + 1, np.exp(x))\n\n# [2]\nms_S = np.zeros((ms_d, ms_V.shape[1]))\nms_z = np.zeros(ms_d)\n# [3]\nfor ms_key, ms_value in zip(ms_K, ms_V, strict=True):\n    ms_S += np.outer(ms_phi(ms_key), ms_value)\n    ms_z += ms_phi(ms_key)\nms_streaming = (ms_S.T @ ms_phi(ms_q)) / (ms_z @ ms_phi(ms_q))\nms_weights = ms_phi(ms_K) @ ms_phi(ms_q)\nms_traversal = (ms_weights[:, None] * ms_V).sum(0) / ms_weights.sum()\n# [4]\nassert np.allclose(ms_streaming, ms_traversal)\n# [5]\nprint(\"streaming equals traversal:\", np.allclose(ms_streaming, ms_traversal))\nprint(f\"max |difference|: {np.abs(ms_streaming-ms_traversal).max():.3e}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nstreaming equals traversal: True\nmax |difference|: 3.469e-17\n```\n:::\n:::\n\n\n::::\nThe equality is exact up to floating-point order: the full dataset traversal has\ncollapsed into two running sums. With $r$ and $d_v$ fixed, storage no longer grows\nwith the prefix. This is the honest content behind “Transformers are RNNs” for\ncausal **linear** attention: the recurrent state returns, dignified, as a sufficient\nstatistic of a regression.\n\nThere is a price. Ordinary softmax's exponential dot-product kernel does not have the\nfinite exact feature map used above. Changing to a finite factorization changes the\nkernel, or approximates it. Collisions in $(S_t,z_t)$ cannot be undone by revisiting a\ndiscarded row. The traversal equality is exact for the chosen factorized kernel, not a\nproof that finite-state linear attention reproduces exact softmax for arbitrary\nprefixes.\n\n### Solver 3: take one gradient step and get the delta rule\n\nNow restrict the predictor to a scalar linear map\n$M(\\vect{q})=\\vect{h}^{\\top}\\vect{q}$ and let the solver take one SGD step on only\nthe newest pair. Its instantaneous loss and gradient are\n\n$$\n\\ell_t(\\vect{h})\n=\\frac{1}{2}(\\vect{h}^{\\top}\\vect{k}_t-v_t)^2,\n\\qquad\n\\nabla_{\\vect{h}}\\ell_t\n=\\vect{k}_t(\\vect{k}_t^{\\top}\\vect{h}-v_t).\n$$\n\nSubstituting the gradient into the update gives the delta recurrence in three lines:\n\n$$\n\\begin{aligned}\n\\vect{h}_t\n&=\\vect{h}_{t-1}-\\eta_t\\vect{k}_t\n  (\\vect{k}_t^{\\top}\\vect{h}_{t-1}-v_t)\\\\\n&=(\\matr{I}-\\eta_t\\vect{k}_t\\vect{k}_t^{\\top})\\vect{h}_{t-1}\n  +\\eta_t v_t\\vect{k}_t.\n\\end{aligned}\n$$\n\n:::: {.plan-code}\n::: {.plan}\n1. Prepare the inputs and fixed settings for the example.\n2. Verify that one SGD step is the delta recurrence.\n3. Report or visualize the measured result.\n:::\n\n::: {#delta-sgd-check .cell execution_count=4}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: verify that one SGD step is the delta recurrence\"}\n# [1]\nms_eta = 0.3\nms_h = ms_rng.standard_normal(ms_d)\nms_k = ms_rng.standard_normal(ms_d)\nms_v = ms_rng.standard_normal()\nms_sgd = ms_h - ms_eta * ms_k * (ms_k @ ms_h - ms_v)\nms_delta = ((np.eye(ms_d) - ms_eta * np.outer(ms_k, ms_k)) @ ms_h\n            + ms_eta * ms_v * ms_k)\n# [2]\nassert np.allclose(ms_sgd, ms_delta)\n# [3]\nprint(\"SGD equals Delta recurrence:\", np.allclose(ms_sgd, ms_delta))\nprint(f\"max |difference|: {np.abs(ms_sgd-ms_delta).max():.3e}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSGD equals Delta recurrence: True\nmax |difference|: 4.441e-16\n```\n:::\n:::\n\n\n::::\nFor vector values, store\n$\\matr{H}_t\\in\\mathbb{R}^{d_v\\times d_k}$ and replace the update by\n\n$$\n\\matr{H}_t\n=\\matr{H}_{t-1}\n+\\eta_t(\\vect{v}_t-\\matr{H}_{t-1}\\vect{k}_t)\\vect{k}_t^{\\top}.\n$$\n\nEach outer product writes the residual left by the current key. DeltaNet turns that\nclassical online least-squares step into a sequence layer. The recurrence also exposes\na state-space form: its transition is\n$\\matr{A}_t=\\matr{I}-\\eta_t\\vect{k}_t\\vect{k}_t^{\\top}$ and its input write is\n$\\eta_t v_t\\vect{k}_t$. The state transition is therefore determined by the current\ntoken's learned key.\n\nForgetting needs one more careful distinction. Exponential history weights\n$w_{t,\\tau}=\\gamma^{t-\\tau}$ define an exponentially weighted least-squares\n*objective*, but its exact minimizer generally requires a recursive least-squares\ncovariance state. Writing $\\gamma\\matr{H}_{t-1}$ into a one-step delta recurrence is\na fading-memory solver choice, not an algebraic consequence of those weights. Gates\ncan make that retention and the step size depend on the current token.\n\nThis is the derivation-first connection to the wider SSM family. Mamba makes parts of\nits state transition, input injection, and readout depend on the token; in the present\nlanguage, those mechanisms play roles analogous to a learnable retention-and-write\nschedule. Gated DeltaNet adds learned gating around delta-style updates. That is an\ninterpretive bridge, not a claim that Mamba is literally obtained by differentiating\nthe shared regression objective. Structured SSMs also use different state parameterizations\nand can have costs below the dense outer-product ledger here.\n\n### The price list\n\n::: {#ttrfig-solver-costs}\n\n::: {.cell fig-height='4.8' fig-width='8.8' execution_count=5}\n\n::: {.cell-output .cell-output-display}\n![](attention-as-test-time-regression_files/figure-pdf/cell-6-output-1.pdf){fig-alt='A qualitative two-axis map places three memory solvers by retained-history growth and per-token read or update cost. Softmax attention sits at growing history and growing query cost. The factorized-kernel and delta-state solvers sit at fixed retained state with dimension-dependent fixed per-token costs. Different marker shapes and direct labels identify all three.'}\n:::\n:::\n\n\nThe solver map compares retained state and per-token work. Its positions are\nqualitative; the formulas and direct labels carry the exact ledger.\n:::\n\nThe asymptotic labels in @ttrfig-solver-costs name this dense educational setup, not\nevery implementation.\nFeature width $r$, head dimensions, low-rank structure, convolutions, and hardware\nschedules change constants and sometimes orders. Most importantly, “retains every\nrow” does not mean “recalls every association exactly.” Softmax still returns a convex\nmixture whose quality depends on keys, temperature, and interference.\n\n::: {.callout-warning}\n## Trap: attention's memory is a dataset, not a hidden box\n\nAttention does not *have* a separate memory in the recurrent sense. The attention\noperation is the estimator; during causal decoding, the KV cache is the observed\nkey--value dataset it must retain. A nonparametric query rule keeps growing data so it\ncan form a new local fit. A parametric state instead compresses those data into a\nfixed-size object. FlashAttention changes how the uncompressed fit is scheduled; it\ndoes not turn it into the compressed contract in the second or third row.\n:::\n\n### Mechanism test: recall under a fixed capacity\n\n@ttrfig-solver-costs makes a prediction we can test without pretending to train a\nlanguage model. Store $N$ random unit key--value pairs, then query every stored key. Decode a\nread by the nearest stored value. Exact softmax attention keeps all pairs. A dense\ndelta state has $d^2$ numbers regardless of $N$. A selective delta arm receives one\nextra priority bit and writes ordinary pairs at only one tenth strength, so it can\nchoose what to sacrifice.\n\nThe study was designed on seed branches 0 and 1. Those branches fixed\n$\\eta=0.20$, the 25% priority rate, the 0.10 ordinary write gate, dimensions\n$(8,16,32)$, and loads $N/d\\in(0.5,1,2,4,8)$. Only then was disjoint branch 2 opened\nfor 30 endpoint repetitions. All methods in a trial receive the same keys, values,\norder, queries, and decoder. The endpoint code below is the frozen protocol; it runs\non CPU in under a second on the reference machine.\n\n:::: {.plan-code .plan-code-wide}\n::: {.plan}\n1. Prepare the inputs and fixed settings for the example.\n2. Define the reusable helpers: `ms_unit` and `ms_decode`.\n3. Define the reusable helpers: `ms_trial` and `ms_panel`.\n4. Run the sealed synthetic recall-under-capacity study.\n:::\n\n::: {#memory-capacity-study .cell execution_count=6}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: run the sealed synthetic recall-under-capacity study\"}\n# [1]\nMS_SEED, MS_ETA, MS_GATE = 6050, 0.20, 0.10\nMS_DIMS, MS_LOADS, MS_REPEATS = (8, 16, 32), (0.5, 1, 2, 4, 8), 30\n\n# [2]\ndef ms_unit(x):\n    return x / np.linalg.norm(x, axis=1, keepdims=True)\n\ndef ms_decode(prediction, values):\n    return np.argmax(prediction @ values.T, axis=1)\n\n# [3]\ndef ms_trial(rng, repeat, d, load):\n    n = max(4, round(load * d))\n    keys = ms_unit(rng.standard_normal((n, d)))\n    values = ms_unit(rng.standard_normal((n, d)))\n    priority = np.zeros(n, dtype=bool)\n    priority[rng.permutation(n)[:max(1, round(0.25 * n))]] = True\n\n    scores = 32.0 * (keys @ keys.T)\n    scores -= scores.max(axis=1, keepdims=True)\n    weights = np.exp(scores); weights /= weights.sum(axis=1, keepdims=True)\n    attention = weights @ values\n\n    def delta(write_gate):\n        state = np.zeros((d, d))\n        for key, value, gate in zip(keys, values, write_gate, strict=True):\n            state += MS_ETA * gate * np.outer(value - state @ key, key)\n        return keys @ state.T\n\n    plain = delta(np.ones(n))\n    selective = delta(np.where(priority, 1.0, MS_GATE))\n    truth = np.arange(n)\n    correct = lambda pred: ms_decode(pred, values) == truth\n    a_ok, d_ok, s_ok = correct(attention), correct(plain), correct(selective)\n    ordinary = ~priority\n    return [repeat, d, n, load, a_ok.mean(), ((attention-values)**2).mean(),\n            d_ok.mean(), d_ok[priority].mean(), d_ok[ordinary].mean(),\n            s_ok.mean(), s_ok[priority].mean(), s_ok[ordinary].mean()]\n\ndef ms_panel(tag, repeats):\n    seeds = np.random.SeedSequence([MS_SEED, tag]).spawn(\n        repeats * len(MS_DIMS) * len(MS_LOADS))\n    rows, index = [], 0\n    for repeat in range(repeats):\n        for d in MS_DIMS:\n            for load in MS_LOADS:\n                rows.append(ms_trial(np.random.default_rng(seeds[index]),\n                                     repeat, d, load))\n                index += 1\n    return np.asarray(rows)\n\n# Tags 0 and 1 were development; tag 2 remained sealed until settings were fixed.\nms_development = np.vstack([ms_panel(tag, 5) for tag in (0, 1)])\nassert np.all(ms_development[:, 4] == 1.0)\nms_endpoint = ms_panel(2, MS_REPEATS)\nassert np.all(ms_endpoint[:, 4] == 1.0)\n\nprint(\"study_seed=6050; development_tags=(0, 1); sealed_endpoint_tag=2\")\nprint(\"endpoint_trials=30 x 3 dimensions; d=(8, 16, 32); \"\n      \"N/d=(0.5, 1, 2, 4, 8)\")\nprint(\"fixed: eta=0.20; priority_fraction=0.25; ordinary_write_gate=0.10\")\nprint(\"load  attention  Delta  gated-all  gated-priority  gated-ordinary\")\n# [4]\nfor load in MS_LOADS:\n    block = ms_endpoint[ms_endpoint[:, 3] == load]\n    means = block[:, [4, 6, 9, 10, 11]].mean(0)\n    print(f\"{load:>4.1f}   \" + \"  \".join(f\"{value:.3f}\" for value in means))\n\nhard = ms_endpoint[ms_endpoint[:, 3] == 8]\npriority_gain = hard[:, 10] - hard[:, 7]\nordinary_gain = hard[:, 11] - hard[:, 8]\nprint(f\"N/d=8 gated-minus-Delta priority: {priority_gain.mean():+.3f} \"\n      f\"(SD {priority_gain.std(ddof=1):.3f})\")\nprint(f\"N/d=8 gated-minus-Delta ordinary: {ordinary_gain.mean():+.3f} \"\n      f\"(SD {ordinary_gain.std(ddof=1):.3f})\")\nprint(f\"attention top-1 failures=0/{int(ms_endpoint[:, 2].sum())}\")\nprint(f\"mean value MSE={ms_endpoint[:, 5].mean():.2e}; \"\n      f\"max trial MSE={ms_endpoint[:, 5].max():.2e}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nstudy_seed=6050; development_tags=(0, 1); sealed_endpoint_tag=2\nendpoint_trials=30 x 3 dimensions; d=(8, 16, 32); N/d=(0.5, 1, 2, 4, 8)\nfixed: eta=0.20; priority_fraction=0.25; ordinary_write_gate=0.10\nload  attention  Delta  gated-all  gated-priority  gated-ordinary\n 0.5   1.000  0.988  0.471  1.000  0.294\n 1.0   1.000  0.910  0.352  0.992  0.139\n 2.0   1.000  0.657  0.282  0.982  0.048\n 4.0   1.000  0.338  0.228  0.848  0.022\n 8.0   1.000  0.134  0.138  0.522  0.010\nN/d=8 gated-minus-Delta priority: +0.387 (SD 0.156)\nN/d=8 gated-minus-Delta ordinary: -0.124 (SD 0.065)\nattention top-1 failures=0/26040\nmean value MSE=5.43e-06; max trial MSE=4.55e-04\n```\n:::\n:::\n\n\n::::\n::: {#ttrfig-memory-capacity-spectrum}\n\n::: {.cell execution_count=7}\n\n::: {.cell-output .cell-output-display}\n![](attention-as-test-time-regression_files/figure-pdf/cell-8-output-1.pdf){fig-alt='Two line charts. In the left chart softmax top-1 recall stays at one while Delta recall falls with load for dimensions 8, 16, and 32. In the right chart a gated Delta update preserves priority items better than ordinary items, especially at high load, while the ungated update does not make that trade as strongly.'}\n:::\n:::\n\n\nA sealed synthetic mechanism test, not a language-model or state-space benchmark.\nThe uncompressed table keeps perfect top-1 identification in this sharp-softmax\nconstruction, while the fixed delta state loses associations as $N/d$ grows. The\nselective arm receives an unmatched priority bit and trades ordinary recall for\npriority recall. Keys, values, order, queries, decoder, and state width are matched;\nstored data, side information, and inference arithmetic are not.\n:::\nAt $N/d=8$, the gate raises priority recall over the plain delta state by 0.387 on\naverage and lowers ordinary recall by 0.124. That is selective forgetting made\nvisible, not a claim that the gated arm is globally better. Overall gated recall is\n0.138 while plain Delta recall is 0.134 at that load. The useful result is the trade:\ngiven an extra signal, a fixed state can spend capacity differently.\n\nThe fixed-size state could not hold everything in @sec-10-sequences-rnn. It still\ncannot. Now we know the price list on which that failure was one entry. Keeping the\ndataset buys uncompressed access at growing cost; sufficient statistics buy an exact\nstream for a restricted kernel; online updates buy a steerable fixed state and accept\ninterference. The RNN state has returned as a statistical choice rather than a design\nwe were supposed to declare dead.\n\n::: {.callout-note}\n## Check yourself\n\nClose the book for one minute and reconstruct the three memory contracts.\n\n- Which solver retains the original key--value rows?\n- Why does a factorized kernel need both $S_t$ and $z_t$?\n- What information can a fixed delta state overwrite as its load grows?\n:::\n\n## Okay, so — the solver is part of the architecture\n\n1. **The objective alone does not specify the memory system.** Views, history\n   weights, function class, regularizer, and solver jointly define the result.\n2. **Softmax attention keeps a query-dependent dataset.** It preserves every\n   key--value row and pays a growing read cost.\n3. **A finite kernel feature map admits sufficient state.** The pair $(S_t,z_t)$\n   reproduces the chosen factorized-kernel traversal without retaining raw rows.\n4. **One SGD step yields a delta update.** Its fixed matrix writes residuals online,\n   which makes capacity and interference explicit.\n5. **Selective retention spends a budget.** The sealed recall study shows a gate\n   trading ordinary recall for priority recall; it does not establish a universal\n   architecture ranking.\n\n## Sources and further reading {.unnumbered}\n\n- [Katharopoulos et al., *Transformers Are RNNs: Fast Autoregressive Transformers with Linear Attention*](https://arxiv.org/abs/2006.16236):\n  the recurrent sufficient-state form for causal linear attention.\n- [Schlag, Irie, and Schmidhuber, *Linear Transformers Are Secretly Fast Weight Programmers*](https://proceedings.mlr.press/v139/schlag21a.html):\n  the connection among linear attention, fast weights, and the delta update.\n- [Gu and Dao, *Mamba: Linear-Time Sequence Modeling with Selective State Spaces*](https://arxiv.org/abs/2312.00752):\n  input-dependent state-space parameters; this interlude uses selectivity as an\n  analogy, not an exact regression equivalence.\n- [Yang et al., *Gated Delta Networks: Improving Mamba2 with Delta Rule*](https://arxiv.org/abs/2412.06464):\n  learned gating around delta-style associative updates.\n- [Wang, Shi, and Fox, *Test-Time Regression: A Unifying Framework for Designing Sequence Models with Associative Memory*](https://arxiv.org/abs/2501.12352):\n  the shared regression objective and solver-design perspective.\n\n## Exercises {.unnumbered}\n\n1. **(Pencil.)** Starting from the local-constant objective, derive its stationarity\n   equation and normalized solution. Identify exactly where the local-constant\n   restriction enters. Why would an unrestricted function with no regularizer not\n   imply the same average?\n2. **(Code.)** Reproduce the factorized-kernel sufficient-state identity with a\n   positive feature map of your choice. Assert that full traversal and the running\n   pair $(S_t,z_t)$ agree for every prefix. Which assertion fails if you omit $z_t$?\n3. **(Pencil.)** Derive the delta recurrence from one SGD step. Then multiply the old\n   state by $\\gamma$. Explain why this is a fading-memory solver choice rather than\n   the exact minimizer of exponentially weighted least squares.\n4. **(Code.)** Sweep the capacity study over at least five state widths $d$. Preserve\n   the sealed-seed protocol, plot recall against both $N$ and $N/d$, and report where\n   the curves align. Do not call top-1 identification exact value recall.\n5. **(Audit.)** For each solver in the cost diagram, record state size, update cost,\n   query cost, and information that cannot be reconstructed. Identify what is\n   compute-matched and storage-matched, then design one rematch for a claim you would\n   be willing to make.\n\n",
    "supporting": [
      "attention-as-test-time-regression_files/figure-pdf"
    ],
    "filters": []
  }
}
