{
  "hash": "a8bb7a5055e1be43337390efa33e7f5a",
  "result": {
    "engine": "jupyter",
    "markdown": "# When It Fails: Generalization in Pictures, and Inductive Bias {#sec-06-generalization-inductive-bias}\n\n<!-- lecture-source: m04_lecture-4-convolutional-neural-networks-cnns_s6xDEvdz3tY.txt (opening),\n     m03 sessions; outline approved by author 2026-07-08 (drafts/part1/06-outline.md)\n     seeds: sources/4.1-CNN.tex (§Fundamental Problem, Fatal Flaw, Two Key Principles),\n            sources/ML_concepts_roadmap.tex; weight-viz: m02-03-shared.ipynb\n     pacing: 3Blue1Brown \"Gradient descent\" lesson (author-cited) — show, then name -->\n\nPart I has given us everything a course could promise: models with universal expressive\npower (@sec-03-nonlinearity-mlp), losses grounded in maximum likelihood\n(@sec-02-logistic-softmax), an optimizer that scales (@sec-04-training-loss-sgd), and\ngradients for anything (@sec-05-backpropagation). This chapter takes all of it, aims it\nat real images, and succeeds completely.\n\nThen we will look a little closer, and the wheels will come off. Watching *how* they\ncome off — in pictures rather than theorems — is the most important lesson of Part I,\nbecause the cure is the idea the entire rest of this book is built on.\n\n## Victory\n\nThe data is a subset of Fashion-MNIST, the classic benchmark from our live sessions:\n28×28 grayscale images of clothing in ten classes. The model and training loop hold no\nsurprises: an MLP from @sec-03-nonlinearity-mlp, trained exactly as in\n@sec-04-training-loss-sgd:\n\n::: {#victory .cell execution_count=1}\n``` {.python .cell-code}\nimport torch\nfrom torch import nn\n\ntorch.manual_seed(6050)\ndevelopment = torch.load(\"../../data/fashion-train.pt\")\nholdout = torch.load(\"../../data/fashion-test.pt\")\nX_dev = development[\"X\"].float().reshape(-1, 784) / 255.0  # (1200, 784)\ny_dev, classes = development[\"y\"], development[\"classes\"]\nX_test = holdout[\"X\"].float().reshape(-1, 784) / 255.0     # (600, 784)\ny_test = holdout[\"y\"]\n\nsplit = torch.randperm(len(X_dev), generator=torch.Generator().manual_seed(6050))\nfit_idx, val_idx = split[:1000], split[1000:]\nX_tr, y_tr = X_dev[fit_idx], y_dev[fit_idx]                 # (1000, 784), (1000,)\nX_val, y_val = X_dev[val_idx], y_dev[val_idx]               # (200, 784), (200,)\n\ndef train_mlp(\n    X: torch.Tensor, y: torch.Tensor, hidden: int = 256,\n    epochs: int = 40, seed: int = 6050\n) -> nn.Sequential:\n    torch.manual_seed(seed)\n    net = nn.Sequential(nn.Linear(784, hidden), nn.ReLU(), nn.Linear(hidden, 10))\n    opt = torch.optim.Adam(net.parameters(), lr=1e-3)\n    for _ in range(epochs):\n        perm = torch.randperm(len(X))\n        for i in range(0, len(X), 64):\n            idx = perm[i:i + 64]\n            opt.zero_grad()\n            nn.functional.cross_entropy(net(X[idx]), y[idx]).backward()\n            opt.step()\n    return net\n\ndef accuracy(net: nn.Module, X: torch.Tensor, y: torch.Tensor) -> float:\n    net.eval()\n    with torch.no_grad():\n        return (net(X).argmax(1) == y).float().mean().item()\n\nnet = train_mlp(X_tr, y_tr)\nprint(f\"train accuracy: {accuracy(net, X_tr, y_tr):.1%}\")\nprint(f\"validation accuracy: {accuracy(net, X_val, y_val):.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ntrain accuracy: 95.0%\nvalidation accuracy: 76.0%\n```\n:::\n:::\n\n\nSeventy-six percent on held-out validation images, from one thousand fitting examples\nand a few seconds of CPU. The split was fixed before any experiment, and the separate\ntest set remains sealed until the end of the chapter. By every metric we have learned\nto compute, we might be done.\n\nThe rest of this chapter is about why we are not.\n\n## Two experiments that should worry you\n\n### Experiment 1: move everything two pixels\n\nTake the validation images and shift each one two pixels to the right. Nothing about any\ngarment changes: a coat is a coat, wherever it hangs in the frame. Any human would\ncall the original and shifted batches equivalent for classification.\n\n::: {#shift-experiment .cell execution_count=2}\n``` {.python .cell-code}\ndef shift_right(X: torch.Tensor, px: int) -> torch.Tensor:\n    img = X.reshape(-1, 28, 28)\n    out = torch.zeros_like(img)\n    if px > 0:\n        out[:, :, px:] = img[:, :, :-px]\n    else:\n        out = img.clone()\n    return out.reshape(-1, 784)\n\nfor px in [0, 2]:\n    print(f\"shift {px}px: validation accuracy \"\n          f\"{accuracy(net, shift_right(X_val, px), y_val):.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nshift 0px: validation accuracy 76.0%\nshift 2px: validation accuracy 46.5%\n```\n:::\n:::\n\n\nTwo pixels, and the accuracy is nearly cut in half. Push further and the collapse\ncompletes:\n\n::: {#cell-fig-shift-cliff .cell execution_count=3}\n``` {.python .cell-code code-summary=\"Code: accuracy vs. shift\"}\nimport matplotlib.pyplot as plt\n\nshifts = list(range(5))\naccs = [accuracy(net, shift_right(X_val, s), y_val) for s in shifts]\nplt.figure(figsize=(5.6, 3.3))\nplt.plot(shifts, accs, \"o-\", color=\"#E57200\", lw=2, ms=7)\nplt.axhline(0.1, ls=\":\", color=\"#B8B8A8\")\nplt.text(0.1, 0.115, \"chance (10 classes)\", color=\"#8A8A7A\", fontsize=9)\nplt.xlabel(\"shift (pixels right)\"); plt.ylabel(\"validation accuracy\")\nplt.ylim(0, 0.9); plt.xticks(shifts)\nplt.tight_layout(); plt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![The validation cliff. Each pixel of horizontal shift destroys accuracy although the garments themselves never changed. By four pixels the model is approaching guesswork.](06-generalization-inductive-bias_files/figure-html/fig-shift-cliff-output-1.png){#fig-shift-cliff width=529 height=307}\n:::\n:::\n\n\n### Experiment 2: destroy the images entirely\n\nNow the stranger experiment, from the lecture's \"fatal flaw\" argument. Choose one fixed\nrandom permutation of the 784 pixel positions and apply it to *every* image, fit and\nvalidation alike. The displayed arrays are not recognizable pictures anymore — the\nordinary grid adjacency has been destroyed. Retrain the same MLP on this scrambled world:\n\n::: {#shuffle-experiment .cell execution_count=4}\n``` {.python .cell-code}\ntorch.manual_seed(0)\npixel_perm = torch.randperm(784)          # one fixed scrambling for all images\n\nnet_shuffled = train_mlp(X_tr[:, pixel_perm], y_tr)\nprint(f\"original images:  validation accuracy {accuracy(net, X_val, y_val):.1%}\")\nprint(f\"shuffled pixels:  validation accuracy \"\n      f\"{accuracy(net_shuffled, X_val[:, pixel_perm], y_val):.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\noriginal images:  validation accuracy 76.0%\nshuffled pixels:  validation accuracy 77.0%\n```\n:::\n:::\n\n\nThe two validation accuracies are close in this one deterministic run. That is not an\nuncertainty estimate, but it is enough for the structural point: after retraining, an\ninvertible relabeling of pixel coordinates costs this MLP no visible accuracy.\n\nHold the two results side by side and the diagnosis writes itself:\n\n> The MLP hypothesis class and training procedure show no preference for the structure\n> that matters, including pixel adjacency and image geometry, yet the fitted model is\n> **hypersensitive** to a nuisance that should not matter: where the garment happens to\n> sit. It learned the dataset without needing an image-aware representation.\n\n## The autopsy, in pictures\n\nWhy exactly does shifting hurt a model that shuffling cannot? Look at what the model\nactually learned. Each row of the first layer's weight matrix is a 784-vector — which\nmeans we can reshape it into a 28×28 image and look at it. And we know from\n@sec-01-linear-regression what such a row *is*: a **template**, scored against the\ninput by dot product.\n\n::: {#cell-fig-templates .cell execution_count=5}\n``` {.python .cell-code code-summary=\"Code: first-layer weights as images\"}\nW1 = net[0].weight.detach()               # (256, 784)\norder = W1.norm(dim=1).argsort(descending=True)[:16]\n\nfig, axes = plt.subplots(2, 8, figsize=(7.6, 2.2))\nfor ax, i in zip(axes.ravel(), order):\n    ax.imshow(W1[i].reshape(28, 28), cmap=\"RdBu_r\")\n    ax.set_xticks([]); ax.set_yticks([])\nplt.tight_layout(); plt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Sixteen first-layer templates, reshaped into images. Each is a global, full-frame pattern; many are diffuse rather than recognizable garment detectors. A template that spans the whole frame changes its score when the input pattern moves.](06-generalization-inductive-bias_files/figure-html/fig-templates-output-1.png){#fig-templates width=720 height=186}\n:::\n:::\n\n\nThere is the whole story in one figure. Every template is **global** — a pattern\nstretched across the entire frame, tuned to where garments sat in the training images.\nShift the input two pixels and every pixel of every template now scores against the\nwrong part of the garment; hundreds of learned template scores change at once.\nConversely, the fixed permutation is merely an invertible relabeling of coordinates.\nRetraining can permute the first-layer weights in the opposite direction, so the same\nfunctions remain available even though adjacency has been destroyed. A model trained\non ordinary images is not itself invariant to arbitrary pixel permutations.\n\nCapacity was never the issue. By @sec-03-nonlinearity-mlp's universal approximation\ntheorem, this network *can represent* a perfectly shift-tolerant classifier. It has no\nreason to find one: nothing in its architecture, loss, or data ever told it that\nposition is a nuisance and adjacency is meaningful.\n\n## Naming the disease\n\nWith the failure in hand, the classical concepts of Part I snap into focus.\n\n### Hunting the U-curve\n\nThe textbook story (@sec-01-linear-regression's cartoon) predicts that as capacity\ngrows, validation error should fall and then *rise* as the model overfits. We now have\neverything needed to test the cartoon on real data: a width sweep at two dataset\nsizes:\n\n::: {#cell-fig-ucurve .cell execution_count=6}\n``` {.python .cell-code code-summary=\"Code: the width sweep\"}\nwidths = [2, 4, 8, 16, 64, 256]\nplt.figure(figsize=(6, 3.5))\nfor n, color in [(300, \"#5379AA\"), (1000, \"#232D4B\")]:\n    errs = [1 - accuracy(train_mlp(X_tr[:n], y_tr[:n], hidden=h, epochs=60),\n                         X_val, y_val)\n            for h in widths]\n    plt.semilogx(widths, errs, \"o-\", color=color, label=f\"n = {n}\", base=2)\nplt.xlabel(\"hidden width (capacity)\"); plt.ylabel(\"validation error\")\nplt.legend(); plt.tight_layout(); plt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Hunting the U-curve: validation error vs. hidden width at two fitting-set sizes. Error falls steeply as capacity grows, then flattens. In this one seeded sweep, n=300 shows a small late upturn while n=1000 does not. The result describes this regime; it does not estimate a scaling law.](06-generalization-inductive-bias_files/figure-html/fig-ucurve-output-1.png){#fig-ucurve width=567 height=325}\n:::\n:::\n\n\nRead it honestly. The left side of the cartoon is emphatically real: too little\ncapacity underfits badly. But the dreaded right side barely materializes, with a\nwhisper of an upturn at the small dataset and nothing at the larger one. This is exactly\nthe caveat planted in @sec-01-linear-regression: the U is a helpful cartoon, not a law\nof nature. The optimizer, sample size, and data structure can all shape the curve. This\none seeded Adam sweep does not identify their separate effects, and it does not\nestablish a $1/n$ variance law.\n\nWhich sharpens our problem instead of solving it: **our model does not fail for having\ntoo much capacity. It fails for having no knowledge.** No point on either curve\nsurvives a two-pixel shift.\n\n### The curse of dimensionality\n\nCould we fix everything with data alone, just by showing the model garments at every\nposition? Count what that costs. Our images live in 784 dimensions; a small color image\n(32×32×3) needs 3,072 numbers, a one-megapixel photo three million, an ImageNet input\n150,528. And covering a $d$-dimensional space densely requires exponentially many\nexamples: if 9 points cover a 1-D interval at some resolution, matching that density\ntakes $9^2$ points in 2-D and $9^d$ in $d$ dimensions. For $d = 784$, there are not\nenough atoms in the universe, at any exchange rate.\n\nHigh dimensionality also breaks the very idea of \"similar examples\":\n\n::: {#cell-fig-curse .cell execution_count=7}\n``` {.python .cell-code code-summary=\"Code: nearest/farthest ratio vs. dimension\"}\ntorch.manual_seed(6050)\ndims = [2, 10, 100, 784, 5000]\nratios = []\nfor d in dims:\n    P = torch.rand(300, d)\n    D = torch.cdist(P, P)\n    ratios.append(((D + torch.eye(300) * 1e9).min(1).values / D.max(1).values).mean())\n\nplt.figure(figsize=(5.6, 3.2))\nplt.semilogx(dims, ratios, \"o-\", color=\"#722F37\", lw=2)\nplt.axvline(784, ls=\":\", color=\"#B8B8A8\")\nplt.text(830, 0.25, \"Fashion-MNIST\\n(d = 784)\", fontsize=9, color=\"#8A8A7A\")\nplt.xlabel(\"dimension $d$\"); plt.ylabel(\"nearest / farthest distance\")\nplt.ylim(0, 1); plt.tight_layout(); plt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Distance concentration for 300 points sampled uniformly from a unit cube: the average ratio of nearest-neighbor to farthest-neighbor distance, by ambient dimension. At d=784 the ratio reaches 0.89. This is a controlled geometry example, not a claim that natural images fill the 784-dimensional cube uniformly.](06-generalization-inductive-bias_files/figure-html/fig-curse-output-1.png){#fig-curse width=529 height=297}\n:::\n:::\n\n\nIn the uniform cube, brute-force interpolation loses genuinely near neighbors as the\nambient dimension grows. Natural images are highly structured and may concentrate near\na much lower-dimensional set, so this experiment is not their empirical distance\ndistribution. It shows the price of trying to cover an *unconstrained* 784-dimensional\nspace and why useful structure must enter through data, representation, or architecture.\n\n## The cure has a name\n\nReturn to the word planted on the very first pages of this book\n(@sec-01-linear-regression): **inductive bias** — the nudge that steers a learner\ntoward the functions we want, among the infinitely many that fit. Our MLP's failure is\nnot a capacity problem or (fixably) a data problem. It is a *knowledge* problem: we\nknew things about images that we never told the model.\n\nSay them out loud — the two principles from the lecture:\n\n1. **Locality.** Nearby pixels are related; a pixel and its neighbor jointly form\n   edges, textures, parts. Distant pixels, far less so. (The shuffle experiment proved\n   our MLP holds no such belief.)\n2. **Translation structure.** A local detector's response should move with the feature\n   (**equivariance**), while a classifier's final verdict should tolerate or ignore\n   small changes in position (**invariance**). The shift experiment showed that our\n   fitted MLP did neither reliably.\n\nHere is the move that powers the rest of this book: **build these beliefs into the\narchitecture itself** — as constraints. Constrain each template to look at a small\nlocal patch instead of the whole frame. Then *share* that template across every\nposition, so the detection rule itself does not depend on where. Two constraints, and\nboth pathologies are attacked at their root. The parameter count falls too: our MLP has\n203,530 parameters, while the LeNet model in @sec-08-cnn will have 61,706, less than a\nthird as many. Sharing is a massive economy.\n\n::: {.callout-tip}\n## Constraints are knowledge\n\nA constraint looks like a *reduction* in power: the constrained model is a strict\nsubset of the MLP. That is exactly the point. By @sec-01-linear-regression's\nbias–variance lens, we are spending bias — assumptions we are confident of — to\ncollapse the search space onto functions that respect the structure of images,\nslashing variance and sample complexity. Inductive bias is not a limitation of a\nmodel; done right, it is everything you know about the world, cast in architecture.\nAnd it is a dial, not a dogma: give a weakly-biased model enough data and it can win\nagain — a trade we will meet at the frontier in @sec-16-vit-scaling.\n:::\n\n## The pivot\n\nLook once more at the templates figure. The fix is almost visible in it: the templates\nshould not span the frame. They should be **small and local** — and they should\n**slide**, scoring every neighborhood of the image with the same little pattern,\nso that a sleeve found anywhere is the same sleeve.\n\nA local template, slid across the image, scoring each position by dot product. That\nmachine has a name, it predates deep learning by decades, and Part II opens by building\nit with our bare hands — then asking this book's favorite question about it:\n\n*What if the template were learnable?*\n\n## One sealed test check\n\nThe architecture, optimizer, shift size, and reported metrics are now fixed. Only now\ndo we fit the same MLP on all 1,200 development examples and open the 600-example test\nset once:\n\n::: {#final-holdout .cell execution_count=8}\n``` {.python .cell-code code-summary=\"Code: one final test-set check\"}\nnet_final = train_mlp(X_dev, y_dev)\nprint(f\"clean test accuracy:   {accuracy(net_final, X_test, y_test):.1%}\")\nprint(f\"shift-2 test accuracy: \"\n      f\"{accuracy(net_final, shift_right(X_test, 2), y_test):.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nclean test accuracy:   80.8%\nshift-2 test accuracy: 42.0%\n```\n:::\n:::\n\n\nThe sealed check confirms the diagnostic rather than creating it: 80.8% on clean test\nimages becomes 42.0% after the predeclared two-pixel shift.\n\n## Okay, so — the lesson of Part I\n\n1. **Every metric can say yes while the model has learned the wrong thing.** Our MLP\n   scored well on clean held-out data while its hypothesis class showed no adjacency\n   preference (fixed shuffle) and its fitted predictions were hypersensitive to a\n   nuisance shift.\n2. **The autopsy is visual**: global templates, tuned to position, blind to adjacency.\n3. **Capacity is not the culprit in this experiment.** The U-curve barely appears in\n   one seeded sweep, while the uniform-cube example shows why unconstrained ambient\n   coverage becomes expensive.\n4. **The cure is inductive bias**: locality and translation structure, built in as\n   constraints. Knowledge, cast in architecture.\n\n## Deeper dive {.unnumbered}\n\n::: {.callout-note collapse=\"true\"}\n## For the curious: how deep this rabbit hole goes\n\n**Networks can memorize random labels.** Zhang et al. reported 100% training accuracy\non randomly labeled CIFAR-10 and 95.20% on randomly labeled ImageNet under their finite\ntraining budget, not 100% on ImageNet. Capacity is abundant enough that fitting noise\nis easy (Exercise 4 reproduces the phenomenon on our subset). Capacity alone therefore\ndoes not explain generalization; the data, optimizer, and architecture must enter the\naccount.\n\n**The bias–variance picture, updated.** Our flattened U-curve is a mild case of a\nbroader phenomenon: with modern training, test error can even *descend again* beyond\nthe interpolation point — \"double descent.\" The cartoon survives as intuition for the\nunderfit regime; the overparameterized regime plays by subtler rules.\n\n**Further reading**\n\n- Zhang, Bengio, Hardt, Recht, Vinyals,\n  [\"Understanding deep learning requires rethinking generalization\"](https://openreview.net/pdf?id=Sy8gdB9xx)\n  (ICLR 2017), the primary source for the random-label experiment.\n- Neal,\n  [\"On the Bias-Variance Tradeoff: Textbooks Need an Update\"](https://arxiv.org/abs/1912.08286)\n  (2020), the source of this book's \"cartoon, not a law\" stance.\n- Belkin et al.,\n  [\"Reconciling modern machine-learning practice and the classical bias–variance trade-off\"](https://doi.org/10.1073/pnas.1903070116)\n  (PNAS 2019), a primary account of double descent.\n- 3Blue1Brown,\n  [*Gradient descent, how neural networks learn*](https://www.youtube.com/watch?v=IHZwWFHWa-w),\n  the visual companion to this chapter's pacing, including the demonstration that a\n  trained MLP can classify pure noise confidently.\n:::\n\n## Exercises {.unnumbered}\n\n1. **(Pencil.)** Explain algebraically why the pixel shuffle costs the MLP nothing:\n   if $\\matr{P}$ is a permutation matrix and we train on $\\matr{P}\\vect{x}$ instead of\n   $\\vect{x}$, exhibit the weight matrix that makes the two networks identical. Why\n   does no analogous argument work for the shift?\n2. **(Code.)** Augment the training set with random shifts of ±3 pixels and retrain.\n   Re-plot the cliff. How much robustness did augmentation buy, what did it cost in\n   clean accuracy and compute, and — the real question — what *knowledge* did\n   augmentation encode, compared to building invariance into the architecture?\n3. **(Code.)** The U-curve hunt used widths up to 256. Push to 1024 and 4096 at\n   $n = 300$, repeating each width across several seeds. Then compare Adam with\n   minibatch SGD from @sec-04-training-loss-sgd. Which patterns are stable enough to\n   interpret?\n4. **(Code.)** Randomly permute the training *labels* and train a wide MLP for long\n   enough. Report train and test accuracy, and state in one sentence what this proves\n   about capacity as an explanation of generalization.\n5. **(Pencil.)** Estimate the first-layer parameter count of an MLP with 1,000 hidden\n   units on an ImageNet-scale input (224×224×3). At one float32 per parameter, how\n   much memory is that — and how does the number change if each unit instead sees only\n   a 7×7×3 patch?\n\n",
    "supporting": [
      "06-generalization-inductive-bias_files/figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}