{
  "hash": "7734331d5513f73870cf012daabdff89",
  "result": {
    "engine": "jupyter",
    "markdown": "# When It Fails: Generalization in Pictures, and Inductive Bias {#sec-06-generalization-inductive-bias}\n\n<!-- lecture-source: m04_lecture-4-convolutional-neural-networks-cnns_s6xDEvdz3tY.txt (opening),\n     m03 sessions; outline approved by author 2026-07-08 (drafts/part1/06-outline.md)\n     seeds: sources/4.1-CNN.tex (§Fundamental Problem, Fatal Flaw, Two Key Principles),\n            sources/ML_concepts_roadmap.tex; weight-viz: m02-03-shared.ipynb\n     pacing: 3Blue1Brown \"Gradient descent\" lesson (author-cited) — show, then name -->\n\nWe now have\n[expressive models](03-nonlinearity-mlp.qmd#sec-03-nonlinearity-mlp),\n[likelihood-derived losses](02-logistic-softmax.qmd#sec-02-logistic-softmax),\n[an optimizer that scales](04-training-loss-sgd.qmd#sec-04-training-loss-sgd), and\n[an efficient way to compute gradients](05-backpropagation.qmd#sec-05-backpropagation).\nApplied to Fashion-MNIST, this machinery reaches respectable accuracy on held-out\nvalidation images.\n\nYet a validation score only estimates performance under the original\ndata-generating distribution. It does not tell us which transformations of the\ndata the classifier will tolerate. A small shift, for example, preserves the\ngarment's visual identity, so we expect a robust model to keep its prediction. A\ncomplete pixel scramble, by contrast, destroys the two-dimensional spatial\narrangement; requiring a model to preserve its output under arbitrary scrambling is\nneither expected nor desirable. Task-relevant invariance is selective: an image\nmodel should tolerate nuisance displacements while remaining sensitive to the\nspatial structure that defines an object.\n\nWe compare these transformations under two protocols: evaluating an already\ntrained model on transformed inputs, and retraining on transformed data. The\ndistinction separates the behavior of a particular fitted model from the\nsymmetries of its model family. It also motivates the locality and weight\nsharing developed in Part II.\n\n## The baseline fit: empirical risk and clean validation\n\nWe use a subset of Fashion-MNIST, a classic benchmark of 28×28 grayscale images of\nclothing in ten classes. The model and training loop come from earlier chapters: we\ntrain an MLP from @sec-03-nonlinearity-mlp exactly as in @sec-04-training-loss-sgd:\n\n:::: {.plan-code .plan-code-wide}\n::: {.plan}\n1. Load and flatten the Fashion-MNIST subset, split off 200 validation images, and\n   import `fit_supervised`.\n2. Define the reusable helpers: `train_mlp` and `accuracy`.\n3. Fit the @sec-04-training-loss-sgd recipe on the fixed Fashion-MNIST development split.\n4. Print the train and validation accuracy.\n:::\n\n::: {#victory .cell execution_count=1}\n``` {.python .cell-code code-fold=\"false\"}\nimport torch\nfrom torch import nn\n\n# [1]\ntorch.manual_seed(6050)\ndevelopment = torch.load(\"../../data/fashion-train.pt\")\nholdout = torch.load(\"../../data/fashion-test.pt\")\nX_dev = development[\"X\"].float().reshape(-1, 784) / 255.0  # (1200, 784)\ny_dev, classes = development[\"y\"], development[\"classes\"]\nX_test = holdout[\"X\"].float().reshape(-1, 784) / 255.0     # (600, 784)\ny_test = holdout[\"y\"]\n\nsplit = torch.randperm(len(X_dev), generator=torch.Generator().manual_seed(6050))\nfit_idx, val_idx = split[:1000], split[1000:]\nX_tr, y_tr = X_dev[fit_idx], y_dev[fit_idx]                 # (1000, 784), (1000,)\nX_val, y_val = X_dev[val_idx], y_dev[val_idx]               # (200, 784), (200,)\n\nfrom dlbook.supervised import fit_supervised   # Listing 4.1\ntorch.set_num_threads(4)  # pinned: results depend on the CPU thread count\n\n# [2]\ndef train_mlp(\n    X: torch.Tensor, y: torch.Tensor, hidden: int = 256,\n    epochs: int = 40, seed: int = 6050\n) -> nn.Module:\n    # The delta from Listing 4.1 is one line: this chapter's model.\n    return fit_supervised(\n        lambda: nn.Sequential(\n            nn.Linear(784, hidden), nn.ReLU(), nn.Linear(hidden, 10)\n        ),\n        X, y, epochs=epochs, seed=seed,\n    )\n\ndef accuracy(net: nn.Module, X: torch.Tensor, y: torch.Tensor) -> float:\n    net.eval()\n    with torch.no_grad():\n        return (net(X).argmax(1) == y).float().mean().item()\n\n# [3]\nnet = train_mlp(X_tr, y_tr)\n# [4]\nprint(f\"train accuracy: {accuracy(net, X_tr, y_tr):.1%}\")\nprint(f\"validation accuracy: {accuracy(net, X_val, y_val):.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ntrain accuracy: 95.0%\nvalidation accuracy: 76.0%\n```\n:::\n:::\n\n\n::::\n<!-- NOVEL: needs sign-off -->\nThis MLP has no layer that behaves differently in training and evaluation, but keep the\n`net.eval()` line: it disables training-only behavior such as the dropout mechanism\nfrom @sec-04-training-loss-sgd before evaluation.\n\nThe model makes useful predictions on held-out images from the same distribution\nas its fitting data. We fixed the split before any experiment, and the separate\ntest set remains sealed until the end of the chapter. What the validation score\ndoes not establish is whether those predictions respond appropriately when the\nspatial arrangement changes.\n\nBefore probing the model, separate three questions that are often collapsed into\n“the model worked.” Each question needs different evidence.\n\n| Question | Evidence that answers it | What that evidence does not settle |\n|---|---|---|\n| **Representation:** can the model family express a useful rule? | A construction, approximation argument, or fitted witness | Whether the optimizer will find that rule |\n| **Optimization:** did this training procedure reach low empirical risk? | The loss trace, gradients, restarts, and a final training-set check | Behavior on fresh or shifted data |\n| **Generalization:** does the fitted procedure work on the distribution we care about? | Independent evaluation drawn from that declared distribution | Performance under an undeclared deployment shift |\n\n: Three claims that require three kinds of evidence. Low training error is evidence\nabout one optimization run and, indirectly, the available capacity. It is not a\ngeneralization result. {#tbl-three-learning-questions}\n\n## Two experiments that challenge the baseline\n\n### Experiment 1: shift every image two pixels\n\nWe take the validation images and shift each one two pixels to the right. This is a\nchange in position that should preserve the class of a recognizable garment.\nBecause shifting within a finite frame can also crop the image, we will check\nthat effect separately. Before you run the cell, predict the accuracy: the model\nscores 76% on the original images; what do you expect after the shift?\n\n:::: {.plan-code}\n::: {.plan}\n1. Define the reusable `shift_right` helper.\n2. Shift validation images while keeping the trained MLP fixed.\n:::\n\n::: {#shift-experiment .cell execution_count=2}\n``` {.python .cell-code code-fold=\"false\"}\n# [1]\ndef shift_right(X: torch.Tensor, px: int) -> torch.Tensor:\n    img = X.reshape(-1, 28, 28)\n    out = torch.zeros_like(img)\n    if px > 0:\n        out[:, :, px:] = img[:, :, :-px]\n    else:\n        out = img.clone()\n    return out.reshape(-1, 784)\n\n# [2]\nfor px in [0, 2]:\n    print(f\"shift {px}px: validation accuracy \"\n          f\"{accuracy(net, shift_right(X_val, px), y_val):.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nshift 0px: validation accuracy 76.0%\nshift 2px: validation accuracy 46.5%\n```\n:::\n:::\n\n\n::::\nAfter the two-pixel shift, the accuracy falls from 76.0% to 46.5%.\n\nDoes the shift fail because it pushes garments off the canvas? Fashion-MNIST scales each\ngarment's longest edge to fill the frame (Xiao et al.), so wide items such as sandals,\nsneakers, and ankle boots reach the right border, and a two-pixel shift crops them.\nWe measure the crop on its own by zeroing the same two columns without moving\nanything.\n\n:::: {.plan-code}\n::: {.plan}\n1. Measure how much ink the two cropped columns hold.\n2. Zero those columns in place, leaving every garment where it was.\n3. Print the two ink measurements and the validation accuracy with those columns zeroed.\n:::\n\n::: {#edge-crop-control .cell execution_count=3}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: separate cropping from moving\"}\n# [1]\nedge = X_val.reshape(-1, 28, 28)[:, :, -2:]        # the columns a 2px shift crops\ntouched = (edge.flatten(1) > 0).any(dim=1).float().mean().item()\nink_share = (edge.sum() / X_val.sum()).item()\n# [2]\ncropped = X_val.reshape(-1, 28, 28).clone()\ncropped[:, :, -2:] = 0\n# [3]\nprint(f\"images with ink in the two cropped columns: {touched:.1%}\")\nprint(f\"share of all ink in those columns:          {ink_share:.1%}\")\nprint(f\"columns zeroed in place, nothing moved:     validation accuracy \"\n      f\"{accuracy(net, cropped.reshape(-1, 784), y_val):.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nimages with ink in the two cropped columns: 35.0%\nshare of all ink in those columns:          1.2%\ncolumns zeroed in place, nothing moved:     validation accuracy 74.0%\n```\n:::\n:::\n\n\n::::\nRemoving those columns in place costs two percentage points, far less than the\nfull shift. The crop-only control therefore does not account for the much larger\nloss after displacement.\n\nThis is the distinction from @sec-01-linear-regression: validation data drawn from the\ndata-generating distribution $P$ estimates performance under $P$, not automatically under\na transformed distribution. If $T$ shifts an image while preserving its label, then\n\n$$\nR_{T_\\#P}(\\theta)\n=\n\\E_{(X,Y)\\sim P}\n\\left[\\ell\\bigl(f_\\theta(T(X)),Y\\bigr)\\right],\n$$ {#eq-shifted-risk}\n\nwhere $T_\\#P$ is the distribution obtained by transforming inputs drawn\nfrom $P$ while retaining their labels.\nThe MLP generalized moderately from its fitting sample to fresh clean examples from\n$P$, but it was not robust under $T_\\#P$. There is no\ncontradiction. Clean validation and shift robustness answer different questions. We trained\nthe model on clean images, then asked it to recognize shifted ones. The loss did not\nrequire robustness to that shift.\n@sec-a5-statistical-learning gathers the $P$, $T_\\#P$, and deployment-distribution\nnotation in one place.\n\nAs the validation images move right by 0 to 4 pixels, @fig-shift-cliff follows the same\nfixed network. We call the resulting drop in accuracy the shift cliff.\n\n:::: {.plan-code}\n::: {.plan}\n1. Measure validation accuracy at right shifts of 0 to 4 pixels and open the figure.\n2. Plot accuracy vs. shift.\n:::\n\n::: {.cell execution_count=4}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: accuracy vs. shift\"}\nimport matplotlib.pyplot as plt\n\n# [1]\nshifts = list(range(5))\naccs = [accuracy(net, shift_right(X_val, s), y_val) for s in shifts]\nplt.figure(figsize=(5.6, 3.3))\n# [2]\nplt.plot(shifts, accs, \"o-\", color=\"#E57200\", lw=2, ms=7)\nplt.axhline(0.1, ls=\":\", color=\"#B8B8A8\")\nplt.text(0.1, 0.115, \"chance (10 classes)\", color=\"#8A8A7A\", fontsize=9)\nplt.xlabel(\"shift (pixels right)\"); plt.ylabel(\"validation accuracy\")\nplt.ylim(0, 0.9); plt.xticks(shifts)\nplt.tight_layout(); plt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Validation accuracy of the clean-trained network under rightward shifts of the validation images. The network is not retrained, and the original labels are retained. The dotted line marks the ten-class chance level; accuracy approaches it by four pixels of shift.](06-generalization-inductive-bias_files/figure-pdf/fig-shift-cliff-output-1.pdf){#fig-shift-cliff fig-alt='Validation accuracy falls sharply with each additional pixel of right shift, moving from a strong clean score toward the dotted ten-class chance line by four pixels.' fig-pos='H'}\n:::\n:::\n\n\n::::\n### Experiment 2: permute the pixel coordinates\n\nWe choose one fixed random permutation of the 784 pixel positions and apply it to\n*every* image, fitting and validation alike. We keep the original labels attached to\nthe examples. The displayed arrays are no longer recognizable garments: the ordinary grid\nadjacency has been destroyed.\n\nUnlike a small shift, this is not a transformation under which we require the\nclean-trained classifier to preserve its decision. A changed prediction after\nscrambling is not, by itself, a robustness failure. Nor does the scramble specify\na different correct garment class. Instead, we ask a separate question: can a\nfresh model learn the original labels from this consistently re-encoded dataset?\nThe permutation is invertible, so it changes where information is stored without\nremoving it. Predict before retraining: does the altered arrangement cost this\nMLP five points, twenty, or almost nothing?\n\n:::: {.plan-code}\n::: {.plan}\n1. Set the seed to 0 and draw `pixel_perm`, a random reordering of the 784 pixel\n   positions.\n2. Retrain on one fixed permutation of the pixel coordinates.\n3. Print validation accuracy for the original MLP and for the retrained MLP on shuffled\n   images.\n:::\n\n::: {#shuffle-experiment .cell execution_count=5}\n``` {.python .cell-code code-fold=\"false\"}\n# [1]\ntorch.manual_seed(0)\npixel_perm = torch.randperm(784)          # one fixed scrambling for all images\n\n# [2]\nnet_shuffled = train_mlp(X_tr[:, pixel_perm], y_tr)\n# [3]\nprint(f\"original images:  validation accuracy {accuracy(net, X_val, y_val):.1%}\")\nprint(f\"shuffled pixels:  validation accuracy \"\n      f\"{accuracy(net_shuffled, X_val[:, pixel_perm], y_val):.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\noriginal images:  validation accuracy 76.0%\nshuffled pixels:  validation accuracy 77.0%\n```\n:::\n:::\n\n\n::::\nThe two validation accuracies are close in this one deterministic run. This is\nnot an uncertainty estimate; it shows that the training recipe can learn a useful\nclassifier in the scrambled representation.\n\nThe two experiments used different protocols. Experiment 1 kept the clean-trained\nmodel and changed only the validation images. Experiment 2 transformed both the\nfitting and validation images and retrained.\nComplete the other two cells of that two-by-two design:\n\n:::: {.plan-code}\n::: {.plan}\n1. Evaluate the clean model on scrambled images, without retraining.\n2. Retrain the same MLP on shifted images, then evaluate it on shifted images.\n3. Print validation accuracy for the scrambled, trained-clean case and the shifted,\n   retrained case.\n:::\n\n::: {#protocol-matrix .cell execution_count=6}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: complete the two-by-two protocol\"}\n# [1]\nzero_shot_scramble = accuracy(net, X_val[:, pixel_perm], y_val)\n# [2]\nnet_shifted = train_mlp(shift_right(X_tr, 2), y_tr)\nretrained_shift = accuracy(net_shifted, shift_right(X_val, 2), y_val)\n# [3]\nprint(f\"scramble, trained clean:     validation accuracy {zero_shot_scramble:.1%}\")\nprint(f\"two-pixel shift, retrained:  validation accuracy {retrained_shift:.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nscramble, trained clean:     validation accuracy 8.0%\ntwo-pixel shift, retrained:  validation accuracy 76.5%\n```\n:::\n:::\n\n\n::::\n\n::: {.callout-note appearance=\"simple\"}\n## Diagnostic protocol: a fixed model versus retraining\n\nValidation accuracy for the four combinations of transformation and protocol;\nthe clean-trained model scores 76.0% on untouched validation images. All scores\nuse the original labels, including those attached to the scrambled inputs.\n\n| Protocol | Two-pixel shift | Fixed pixel scramble |\n|---|---|---|\n| **Fixed model:** trained clean, evaluated transformed | 46.5% | 8.0% |\n| **Retrained:** trained and evaluated on transformed data | 76.5% | 77.0% |\n\nThe two results in the first row have different interpretations. The shift result\nshows a failure of the desired tolerance to small position changes. The scramble\nresult shows sensitivity to a much larger change in spatial organization, for which\nwe did not require invariance. These are not two instances of the same robustness failure.\n\nThe second row shows that retraining recovers similar accuracy in both transformed\ndatasets under this recipe. For the fixed scramble, the next section gives an exact\ncoordinate-permutation argument. A zero-filled shift also discards boundary pixels,\nso its retrained result is empirical, not a consequence of that invertible symmetry.\n:::\n\n## Inside the weights: full-frame templates {#inside-the-weights-full-frame-matched-filters}\n\nThe distinction between a fitted model and its model family is explicit in the\nfirst layer. Write the fixed scramble as a permutation matrix $\\matr{P}$, so a\nscrambled image is $\\matr{P}\\vect{x}$. For any first-layer matrix $\\matr{W}_1$,\nset $\\matr{W}_1' = \\matr{W}_1\\matr{P}^\\top$. Then\n\n$$\n\\matr{W}_1'(\\matr{P}\\vect{x})\n= \\matr{W}_1\\matr{P}^\\top\\matr{P}\\vect{x}\n= \\matr{W}_1\\vect{x},\n$$ {#eq-permutation-symmetry}\n\nbecause $\\matr{P}^\\top\\matr{P} = \\matr{I}$. With the bias and later layers\nunchanged, the entire network produces the same output. Every function this MLP\ncan compute in the original coordinates has a corresponding parameterization in\nthe scrambled coordinates.\n\nThis is a property of the **model family**, not invariance of one fitted model.\nThe equation changes the first-layer weights along with the inputs; keeping the\nweights fixed does not give the same identity. The initialization is exchangeable\nacross input coordinates, and Adam applies the same coordinate-wise rule, so the\ntraining procedures correspond in distribution under a fixed permutation\n(Exercise 1). Resetting the seed does not itself permute the initial weights,\nso the two particular runs need not have identical accuracies.\n\nThe dense parameterization therefore gives no built-in preference to the original\npixel adjacency over another ordering. It can still learn spatial regularities\nfrom data; it does not impose locality or translation invariance.\n\nWe can inspect that parameterization directly. Each row $\\vect{w}_j^\\top$ of\n$\\matr{W}_1\\in\\mathbb{R}^{256\\times784}$ assigns a separate coefficient to every\ninput pixel. As in @sec-01-linear-regression, it is a **template**\nscored by the inner product $\\langle\\vect{w}_j,\\vect{x}\\rangle$. Reshaping the row\ninto a 28×28 image shows its coordinate weights.\n\n:::: {.plan-code}\n::: {.plan}\n1. Select the largest-norm first-layer templates.\n:::\n\n::: {#first-layer-template-selection .cell execution_count=7}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: select first-layer templates\"}\n# [1]\nW1 = net[0].weight.detach()               # (256, 784)\norder = W1.norm(dim=1).argsort(descending=True)[:16]\nscale = float(W1[order].abs().max())\n```\n:::\n\n\n::::\n\n::: {.cell execution_count=8}\n\n::: {.cell-output .cell-output-display}\n![Sixteen first-layer weight rows with the largest norms, reshaped into images. The labeled scale runs from negative weights at the blue end through pale zero to positive weights at the red end. Each map shows a separate coefficient for every input pixel; its appearance alone does not establish what the full network recognizes or how robustly it does so.](06-generalization-inductive-bias_files/figure-pdf/fig-templates-output-1.pdf){#fig-templates fig-alt='Sixteen full-frame weight maps fill a two-by-eight grid. Dark red cells mark positive weights, dark blue cells mark negative weights, and pale cells are near zero; broad diffuse patterns span most of each frame.'}\n:::\n:::\n\n\nWe should not expect these maps to resolve into edges, contours, or parts that a person\nwould name, and reading them is subjective. A picture of the weights cannot tell us whether\nthe network will tolerate a spatial change or fail under it; only a transformation test\ncan. What the maps do display is the **full-frame parameterization**: each hidden unit\nscores the image with an unconstrained template that spans the whole canvas, with an\nindependent coefficient at every pixel coordinate. The layer contains no compact local\ndetector that is reused at other positions.\n\nFor the pre-activation $z_j(\\vect{x})=\\vect{w}_j^\\top\\vect{x}+b_j$, a transformation\n$T$ changes the score by\n\n$$\nz_j(T(\\vect{x}))-z_j(\\vect{x})\n=\\vect{w}_j^\\top\\bigl(T(\\vect{x})-\\vect{x}\\bigr).\n$$\n\nThe transformations of interest are **label-preserving**: small shifts of the garment\nwithin the frame, or a symmetry such as the left–right reflection of a shirt, after which\nthe garment remains recognizable and its class is unchanged. A shift moves each intensity\nto a neighboring coordinate, where it is multiplied by a different coefficient, one that\nthe dense parameterization leaves free of any tie to the first; only training decides how\nsimilar the two are. For a shift of $s$ columns to the right, the ink in the $s$\nrightmost columns leaves the frame and changes the score as zeroing those columns in place\nwould, the crop that Experiment 1 measured on its own. Every other pixel $p$ moves to the\nposition $p+s$, $s$ columns to its right, and these pixels contribute the rest of the\ndifference, $\\sum_p (w_{j,p+s}-w_{j,p})\\,x_p$, with the sum taken over them. The score\nchange is therefore set by how each coefficient compares with its neighbor $s$ columns\naway, a relation the dense layer leaves untied.\n\nAsking each unit's score to stay fixed would be the wrong remedy: for $s=1$ it would\nforce a template that is constant along every row and blind to horizontal arrangement.\nWhat the dense layer lacks is a unit tied to the shifted copy of $\\vect{w}_j$, so that\nthe response could move with the garment, as the response of a shared local detector does.\nA change in one hidden score does not by itself settle the classifier's decision either:\nthe ReLU and the output layer combine all 256 hidden scores, whose changes can cancel or\naccumulate. Tolerance must therefore be measured at the output, as in Experiment 1.\n\nDuring training, the gradient for row $j$ is a weighted sum of the input images,\n$\\sum_i\\delta_{ij}\\,\\vect{x}_i$, from the batched form of @eq-bp3.\nAdam rescales the coordinates separately, but neither that update nor the\nparameterization enforces a compact template or shared coefficients across\npositions. Expressive power alone does not supply the particular invariances\nwe want. We next examine how clean performance changes with capacity.\n\n## Diagnosing the failure: capacity versus geometry\n\nIs the model too flexible, or is the data too sparse for 784 dimensions?\n\n### Capacity: testing the classical U-curve {#capacity-hunting-the-u-curve}\n\nThe classical picture, the cartoon of @sec-01-linear-regression, predicts that as\ncapacity grows, validation error first falls and then *rises* as the model overfits.\nA width sweep at two dataset sizes tests that prediction on real data:\n\n:::: {.plan-code}\n::: {.plan}\n1. Choose the hidden widths to sweep, from 2 up to 256 units.\n2. Measure validation error across widths and fitting-set sizes.\n:::\n\n::: {#width-sweep .cell execution_count=9}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: measure the width sweep\"}\n# [1]\nwidths = [2, 4, 8, 16, 64, 256]\n# [2]\nwidth_errors = {\n    n: [1 - accuracy(train_mlp(X_tr[:n], y_tr[:n], hidden=h, epochs=60),\n                       X_val, y_val)\n        for h in widths]\n    for n in (300, 1000)\n}\n```\n:::\n\n\n::::\n\n::: {.cell execution_count=10}\n\n::: {.cell-output .cell-output-display}\n![Testing the classical U-curve: validation error vs. hidden width at two fitting-set sizes. Error falls steeply as capacity grows, then flattens. In this one seeded sweep, n=300 shows a small late upturn while n=1000 does not.](06-generalization-inductive-bias_files/figure-pdf/fig-ucurve-output-1.pdf){#fig-ucurve fig-alt='Both validation-error curves fall steeply as hidden width increases and then flatten. The smaller fitting set turns slightly upward at the widest models, while the larger fitting set does not.'}\n:::\n:::\n\n\nThe left side of the cartoon appears in both curves: networks with too little capacity\nunderfit badly. The right side barely appears: a slight upturn at $n = 300$ and a flat\nplateau at $n = 1000$. The classical picture predicts a sustained rise in validation\nerror once the width passes its best value; neither curve shows one. The U is a useful\ncartoon, not a law of nature (@sec-01-linear-regression): the optimizer, the sample\nsize, and the structure of the data can all shape the curve. A\nsingle seeded Adam sweep describes its own regime, so it cannot separate their effects,\nestimate a scaling law, or establish a $1/n$ variance law.\n\nThe sweep measures **clean validation performance**, not shift robustness. It does\nnot show that a smaller network would repair the baseline's sensitivity to position:\ncapacity and the response to a transformation require separate measurements.\n\n### Geometry: the curse of dimensionality\n\nThe width sweep leaves the shift failure unexplained, so we turn from the model to the\nrepresentation it receives. How informative is distance between raw pixel vectors? Our\nimages use 784 numbers; a small color image (32×32×3) uses 3,072, a one-megapixel color\nphoto three million, and a 224×224×3 input 150,528. Covering every combination of\npixel values is out of reach: a grid with 9 values per coordinate contains\n$9^2$ points in two dimensions and $9^d$ in $d$ dimensions.\n\nHigh dimension also erodes the contrast between near and far points:\n\n:::: {.plan-code}\n::: {.plan}\n1. Fix the seed, list dimensions from 2 to 5000, and start an empty `ratios` list.\n2. Measure the nearest-to-farthest distance ratio by dimension.\n:::\n\n::: {#distance-concentration-audit .cell execution_count=11}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: nearest/farthest ratio versus dimension\"}\n# [1]\ntorch.manual_seed(6050)\ndims = [2, 10, 100, 784, 5000]\nratios = []\n# [2]\nfor d in dims:\n    P = torch.rand(300, d)\n    D = torch.cdist(P, P)\n    ratios.append(((D + torch.eye(300) * 1e9).min(1).values / D.max(1).values).mean())\n```\n:::\n\n\n::::\n\n::: {.cell execution_count=12}\n\n::: {.cell-output .cell-output-display}\n![Distance concentration for 300 points sampled uniformly from a unit cube: the average ratio of nearest-neighbor to farthest-neighbor distance, by ambient dimension. At d=784 the ratio reaches 0.89. This is a controlled geometry example, not a claim that natural images fill the 784-dimensional cube uniformly.](06-generalization-inductive-bias_files/figure-pdf/fig-curse-output-1.pdf){#fig-curse fig-alt='The average nearest-to-farthest distance ratio rises toward one as dimension increases on a logarithmic horizontal axis. A vertical guide at dimension 784 meets the curve near 0.89.'}\n:::\n:::\n\n\nIn the uniform cube, nearest and farthest distances draw together as the dimension\ngrows. Natural images are structured and may concentrate\nnear a much lower-dimensional set, so this is not their empirical distance\ndistribution. Nor is the $9^d$ grid count a bound on the data needed for translation\ntolerance: a translation is described by two numbers, a horizontal and a vertical\noffset, not by independent changes to every pixel.\n\nWe now measure the pixel geometry of the actual images. How far does a\ntwo-pixel shift carry an image, compared with its distance to the nearest\nfitting image?\n\n:::: {.plan-code}\n::: {.plan}\n1. Measure how far the shift moves each validation image, and how far its nearest\n   training image is.\n2. Print the share of validation images where `moved` exceeds `nearest`, and both median\n   distances.\n:::\n\n::: {#shift-distance .cell execution_count=13}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: how far does a two-pixel shift move an image?\"}\n# [1]\nmoved = (X_val - shift_right(X_val, 2)).norm(dim=1)     # (200,)\nnearest = torch.cdist(X_val, X_tr).min(dim=1).values    # (200,)\n# [2]\nprint(f\"shift moves farther than the nearest training image: \"\n      f\"{(moved > nearest).float().mean().item():.1%} of validation images\")\nprint(f\"median distances: shifted copy {moved.median().item():.2f}, \"\n      f\"nearest training image {nearest.median().item():.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nshift moves farther than the nearest training image: 91.0% of validation images\nmedian distances: shifted copy 7.78, nearest training image 4.55\n```\n:::\n:::\n\n\n::::\nIn raw pixel space, then, a label-preserving shift can carry an image farther from the\noriginal than the nearest fitting image is. This diagnoses a mismatch between Euclidean\npixel distance and the tolerance the task requires; it does not show that more data or\naugmentation cannot improve robustness. We next consider how to build the relevant\nstructure into training and into the architecture.\n\n## Inductive bias: constraints as knowledge\n\nRecall **inductive bias** from @sec-01-linear-regression: the\nassumptions and preferences that distinguish fitted solutions beyond their\nagreement with the training sample. Here we have prior knowledge about image\nstructure and about which position changes should preserve the label. Two\nprinciples suggest how to use it:\n\n1. **Locality.** Nearby pixels jointly form edges, textures, and parts.\n   Local connectivity gives these relationships a structural role that the dense\n   parameterization does not assign them.\n2. **Translation structure.** A local detector's response should move with the feature\n   (**equivariance**), while a classifier's final prediction should tolerate or ignore\n   small changes in position (**invariance**). The shift experiment tests\n   this desired tolerance at the classifier's output.\n\n<!-- NOVEL: needs sign-off -->\n### Data augmentation: specifying label-preserving transformations {#data-augmentation-put-the-belief-in-the-examples}\n\nThe shift cliff suggests another route. If moving a garment a little should not change\nits class, let $T$ be a random label-preserving transformation drawn from a declared\ndistribution $\\mathcal{A}$. The population objective becomes\n\n$$\nR_{\\mathcal A}(\\theta)\n=\n\\E_{(X,Y)\\sim P}\n\\E_{T\\sim\\mathcal{A}}\n\\left[\\ell\\bigl(f_\\theta(T(X)),Y\\bigr)\\right].\n$$ {#eq-data-augmentation}\n\nThis is **data augmentation**, and its role is larger than making the dataset look\nbigger. It is a **data-side inductive bias**: the transformation distribution states\nwhich changes we believe should preserve the target. Sampling shifts from $-3$ to $+3$\npixels says that location within that window is a nuisance. This is an assumption\nabout the task: complete pixel scrambling is not included in that invariance\nrequirement. Retraining on one fixed scramble instead changes the encoding of the\nwhole dataset. The empirical augmented\nobjective used in training replaces the outer expectation with the sample average.\nDrawing one fresh $T$ when an example enters a batch then gives a Monte Carlo estimate\nof the inner expectation. Exercise 2 asks you to include those shifts in the training\nbatches and measure both what the augmentation buys on the shift curve and what it costs on clean\nimages. @sec-a5-statistical-learning summarizes the corresponding estimators and\ndistributions.\n\nAugmentation encourages translation tolerance by training on shifted examples.\nIt does not tie parameters across positions: a dense network still assigns them\nseparate coefficients. Weight sharing imposes that relation directly. Exercise 2\nmeasures the effect of augmentation with the current MLP; Part II develops the\narchitectural alternative.\n\nWe can now place three familiar levers side by side:\n\n1. **Architecture-side bias** changes which functions are available or easy to learn.\n   Local connectivity and shared convolutional filters are the route Part II will take.\n2. **Objective- or training-side bias** changes which fitted solution is preferred.\n   Weight penalties, dropout, and early stopping from @sec-04-training-loss-sgd are\n   examples; the minibatch noise discussed there may also bias which solution training\n   reaches.\n3. **Data-side bias** changes the examples the model is fitted to.\n   Augmentation encodes a chosen family of label-preserving transformations.\n\nThese routes can work together, but they are not interchangeable. A finite set\nof augmented shifts encourages consistency; it does not prove exact invariance. An\narchitectural constraint can make a symmetry exact in a layer, but may exclude useful\nfunctions. A penalty prefers some solutions without specifying which input changes\nshould preserve a label. And augmentation needs a label-preserving transformation:\nflipping a garment may be harmless, while flipping a digit or a directional sign may\nchange the answer.\n\nFor Part II we begin with the architecture-side move: **build locality and translation\nstructure into the network itself** as constraints. Constrain each template to look at\na small local patch instead of the whole frame. Then *share* that template across every\nposition, so the local detection rule uses the same parameters throughout the image.\nThese constraints supply locality and sharing; the full classifier's shift tolerance\nwill still need to be evaluated. The parameter count falls too: our MLP has\n203,530 parameters, while the LeNet model in @sec-08-cnn will have 61,706, less than a\nthird as many.\n\n<!-- NOVEL: needs sign-off -->\n::: {.callout-tip}\n## Why a constraint can add knowledge\n\nLocal connectivity and weight sharing constrain a corresponding dense network\nwith the same layer sizes. Through @sec-01-linear-regression's\nbias–variance lens, we accept assumptions about image structure to reduce the\nspace of solutions considered. When those assumptions are appropriate, the\nrestriction can improve data efficiency. The choice remains task-dependent:\nwe want tolerance to small position changes, not indifference to arbitrary\nrearrangements of the pixels. With sufficient data and a suitable training\nrecipe, architectures with weaker spatial constraints can also perform well,\nas Vision Transformers illustrate in @sec-16-vit-scaling.\n:::\n\n## Toward local, shared detectors {#the-pivot-toward-local-shared-detectors}\n\nThe dense templates of @fig-templates assign separate coefficients across\nthe whole image. Our next model will instead use **small, local** templates\nand apply the **same weights at each position**. Learning a local detection\nrule will then determine how that rule is applied elsewhere in the image.\n\nSliding a local template across the image and scoring each position by an inner\nproduct is a classical operation, decades older than deep learning. Part II opens by\nbuilding this operation by hand and then poses the following question:\n\n*What if the template were learnable?*\n\n## One sealed test check\n\nWe have now fixed the architecture, optimizer, shift size, and reported metrics. Only now\ndo we fit the same MLP on all 1,200 development examples and open the 600-example test\nset once:\n\n:::: {.plan-code}\n::: {.plan}\n1. Run one final test-set check.\n2. Print the final model's test accuracy on clean and two-pixel-shifted images.\n:::\n\n::: {#final-holdout .cell execution_count=14}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: one final test-set check\"}\n# [1]\nnet_final = train_mlp(X_dev, y_dev)\n# [2]\nprint(f\"clean test accuracy:   {accuracy(net_final, X_test, y_test):.1%}\")\nprint(f\"shift-2 test accuracy: \"\n      f\"{accuracy(net_final, shift_right(X_test, 2), y_test):.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nclean test accuracy:   80.8%\nshift-2 test accuracy: 42.0%\n```\n:::\n:::\n\n\n::::\nThe sealed check confirms the diagnostic rather than creating it: 80.8% on clean test\nimages becomes 42.0% after the predeclared two-pixel shift.\n\n::: {.callout-note}\n## Check yourself\n\nClose the book for one minute and test the argument on these three questions.\n\n- Why do we require tolerance to a small shift but not to complete pixel\n  scrambling? What separate question does retraining on a fixed scramble answer?\n- Where can inductive bias enter: architecture, objective, or data? Give one example of each.\n- Why can high clean validation accuracy coexist with collapse after a two-pixel shift?\n:::\n\n## Okay, so: the missing ingredient is inductive bias\n\n<!-- NOVEL: needs sign-off -->\n1. **Clean accuracy and shift robustness are different claims.** The MLP\n   predicts well on clean held-out images but loses accuracy after a small,\n   label-preserving displacement.\n2. **Invariance must match the task.** A complete scramble changes the\n   spatial organization and need not preserve a clean-trained model's decision.\n   Retraining on that fixed permutation tests learning in a different encoding,\n   not invariance of the original classifier.\n3. **The model family has a coordinate symmetry.** The reparameterization\n   in @eq-permutation-symmetry explains why a dense architecture gives no\n   built-in preference to the original pixel ordering. The weight maps display\n   its coordinate-specific coefficients; appearance alone does not establish\n   robustness or its cause.\n4. **Capacity and ambient dimension do not settle the diagnosis.** The\n   width sweep describes one clean-data regime, and the uniform-cube example\n   illustrates distance concentration under its own distribution. Neither gives\n   a general limit on what structured data or augmentation can achieve.\n5. **Inductive bias specifies useful structure.** It can enter through\n   architecture, objectives, training procedures, or data. Part II develops\n   locality and weight sharing; augmentation is a complementary way to specify\n   which transformations should preserve the label.\n\n## Deeper dive {.unnumbered}\n\n::: {.callout-note collapse=\"true\"}\n## For the curious: memorization, confidence, and double descent\n\n**Networks can memorize random labels.** Zhang et al. reported 100% training accuracy\non randomly labeled CIFAR-10 and 95.20% on randomly labeled ImageNet under their finite\ntraining budget, not 100% on ImageNet. Capacity is abundant enough that fitting noise\nis easy (Exercise 4 reproduces the phenomenon on our subset). Capacity alone therefore\ndoes not explain generalization; the data, optimizer, and architecture must enter the\naccount.\n\n**Confident far from the data.** A trained ReLU network is piecewise affine:\nits input space splits into polyhedral regions, and on each one the logits\n$o_k=\\vect{w}_k^\\top\\vect{x}+b_k$ are affine in $\\vect{x}$. Along a ray that\nremains in one such region, if one logit has a strictly larger slope than the\nothers, its softmax probability approaches 1 as the distance increases.\nHein, Andriushchenko, and Bitterwolf analyze this behavior for ReLU classifiers.\nHigh softmax confidence therefore need not indicate that an input resembles the\ntraining data. This is a separate question from the label-preserving shift test.\n\n**The bias–variance picture, updated.** Test error can sometimes\n*descend again* beyond the interpolation threshold, where the model first becomes\nable to fit the training sample exactly: \"double descent.\" The width sweep above does\nnot establish that pattern. It illustrates why a classical U-shaped curve\nshould not be assumed in every training regime.\n\n**Further reading**\n\n- Zhang, Bengio, Hardt, Recht, Vinyals,\n  [\"Understanding deep learning requires rethinking generalization\"](https://openreview.net/pdf?id=Sy8gdB9xx)\n  (ICLR 2017), the primary source for the random-label experiment.\n- Neal,\n  [\"On the Bias-Variance Tradeoff: Textbooks Need an Update\"](https://arxiv.org/abs/1912.08286)\n  (2019), the source of the \"cartoon, not a law\" view.\n- Belkin et al.,\n  [\"Reconciling modern machine-learning practice and the classical bias–variance trade-off\"](https://doi.org/10.1073/pnas.1903070116)\n  (PNAS 2019), a primary account of double descent.\n- Hein, Andriushchenko, and Bitterwolf,\n  [\"Why ReLU networks yield high-confidence predictions far away from the training data and how to mitigate the problem\"](https://openaccess.thecvf.com/content_CVPR_2019/html/Hein_Why_ReLU_Networks_Yield_High-Confidence_Predictions_Far_Away_From_the_CVPR_2019_paper.html)\n  (CVPR 2019), the theorem behind confident predictions far from the data.\n:::\n\n## Sources and further reading {.unnumbered}\n\n- [Grant Sanderson, *Analyzing Our Neural Network*](https://www.3blue1brown.com/lessons/neural-network-analysis/)\n  (3Blue1Brown, 2017; text adaptation by Josh Pullen): a related visual examination\n  of first-layer weights and the limits of a trained digit classifier. The\n  transformation comparisons here use the Fashion-MNIST model and protocols\n  specified in this chapter.\n- [Xiao, Rasul, and Vollgraf, *Fashion-MNIST: a Novel Image Dataset for Benchmarking\n  Machine Learning Algorithms*](https://arxiv.org/abs/1708.07747): the benchmark\n  dataset used throughout this chapter and several later mechanism studies.\n- [Geirhos et al., *Shortcut Learning in Deep Neural Networks*](https://www.nature.com/articles/s42256-020-00257-z):\n  a framework for recognizing decision rules that succeed on the benchmark but fail\n  at the intended task.\n- [Koh et al., *WILDS: A Benchmark of in-the-Wild Distribution Shifts*](https://proceedings.mlr.press/v139/koh21a.html):\n  datasets and evaluation protocols that name the deployment distribution rather than\n  treating clean validation as a robustness test.\n- [Shorten and Khoshgoftaar, *A Survey on Image Data Augmentation for Deep Learning*](https://link.springer.com/article/10.1186/s40537-019-0197-0):\n  a broad survey of data-side transformations and the invariances they encourage.\n- [Bach, *Learning Theory from First Principles*](https://www.di.ens.fr/~fbach/ltfp/):\n  develops the formal capacity and generalization tools behind Exercise 6; the\n  exercise itself stops at counting.\n\n## Exercises {.unnumbered}\n\n1. **(Pencil.)** @eq-permutation-symmetry handles a fixed permutation. (a) Write the\n   zero-fill two-pixel shift as a $784\\times784$ matrix $\\matr{S}$ and show that it is\n   a *partial* permutation: which rows are zero, and why, for a general $\\matr{W}_1$,\n   can no $\\matr{W}_1'$ satisfy $\\matr{W}_1'\\matr{S}\\vect{x} = \\matr{W}_1\\vect{x}$\n   for every image? (b) Argue that if the initialization is exchangeable across input\n   coordinates and the optimizer treats coordinates alike, training on\n   $\\matr{P}\\vect{x}$ produces, in distribution, the weights $\\matr{W}_1\\matr{P}^\\top$.\n   With the same seed, the scrambled run scores 77.0% and the original run 76.0%.\n   Which random choices do the two runs share, and which of them do not correspond\n   under the permutation?\n2. **(Code.)** Augment the training set with random shifts of ±3 pixels and retrain.\n   Re-plot the cliff. How much shift robustness did augmentation buy, what did it cost\n   in clean accuracy and compute, and what data-side inductive bias\n   did augmentation encode, compared with imposing locality and weight sharing in the\n   architecture?\n3. **(Code.)** The width sweep used widths up to 256. Push to 1024 and 4096 at\n   $n = 300$, repeating each width across several seeds. Then compare Adam with\n   minibatch SGD from @sec-04-training-loss-sgd. Which patterns are stable enough to\n   interpret?\n4. **(Code.)** Random-label audit. (a) Randomly permute the training *labels* and train a wide MLP for long\n   enough. Report train and test accuracy.\n   **(Audit.)** (b) Use @tbl-three-learning-questions to state what successful\n   fitting supports. Explain why one successful run proves neither that the objective\n   is convex, nor that bad local minima are absent, nor that the fitted rule will\n   generalize.\n5. **(Pencil.)** Estimate the first-layer parameter count of an MLP with 1,000 hidden\n   units on an ImageNet-scale input (224×224×3). At one float32 per parameter, how\n   much memory is that, and how does the number change if each unit instead sees only\n   a 7×7×3 patch?\n6. **(Pencil.)** Count the labelings of $N$ ordered points realizable by (a)\n   positive rays on a line, (b) intervals on a line, and (c) affine linear\n   separators for $N$ points in general position in two dimensions. Obtain\n   $N+1$, $N(N+1)/2+1$, and\n   $2\\sum_{i=0}^{2}\\binom{N-1}{i}$, respectively. Compare each with $2^N$.\n   Do not invoke VC dimension: the point is to see, with arithmetic, how restricting\n   the hypothesis menu changes its growth.\n\n",
    "supporting": [
      "06-generalization-inductive-bias_files/figure-pdf"
    ],
    "filters": []
  }
}