<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>12&nbsp; Kernel Regression: Attention Before It Was Learnable – Deep Learning: Making It Learnable</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/part4/13-attention.html" rel="next">
<link href="../../chapters/part3/11-encoder-decoder.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-c90f29e1247290e1dfbeb1da338aa877.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>
  // Book math macros — keep in sync with tex/macros.tex (PDF path).
  // MathJax reads this config because it is defined before the MathJax
  // script loads (Quarto places include-in-header above its math script).
  window.MathJax = {
    tex: {
      macros: {
        E: "\\mathbb{E}",
        Ex: "\\operatorname{E}",
        var: "\\operatorname{Var}",
        cov: "\\operatorname{Cov}",
        imp: "\\Rightarrow",
        argmax: "\\operatorname*{arg\\,max}",
        argmin: "\\operatorname*{arg\\,min}",
        norm: ["\\left\\lVert#1\\right\\rVert", 1],
        vect: ["\\mathbf{#1}", 1],
        matr: ["\\mathbf{#1}", 1],
        R: "\\mathbb{R}",
        dd: "\\mathrm{d}",
        loss: "\\mathcal{L}"
      }
    }
  };
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/part4/12-kernel-regression.html">IV · Attention: Learning the Similarity</a></li><li class="breadcrumb-item"><a href="../../chapters/part4/12-kernel-regression.html"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Kernel Regression: Attention Before It Was Learnable</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Deep Learning: Making It Learnable</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/Shakeri-Lab/dl-book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">I · From Lines to Networks</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/01-linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Linear Regression, the Mother Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/02-logistic-softmax.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Linear Models that Classify: Logistic and Softmax</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/03-nonlinearity-mlp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Nonlinearity and the MLP</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/04-training-loss-sgd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Training: Loss and Stochastic Gradient Descent</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/05-backpropagation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Backpropagation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/06-generalization-inductive-bias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">When It Fails: Generalization in Pictures, and Inductive Bias</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">II · Vision: Learning the Filters</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/07-filters-convolution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Filters and Convolution (Fixed Kernels)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/08-cnn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">CNNs: Making the Filters Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/09-modern-cnns-transfer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Modern CNNs and Transfer Learning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">III · Sequences</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part3/10-sequences-rnn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Sequences and Recurrence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part3/11-encoder-decoder.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Encoder–Decoder, Teacher Forcing, Beam Search</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">IV · Attention: Learning the Similarity</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/12-kernel-regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Kernel Regression: Attention Before It Was Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/13-attention.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Attention: Making the Kernel Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/14-self-attention-transformer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Self-Attention and the Transformer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/15-bert-pretraining.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">The BERT Moment: Pretraining as the New Regime</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/16-vit-scaling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Vision Transformers and Scaling Laws</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">V · The Pretrained Era</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/17-peft-quantization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Adapting Pretrained Models: Prompting, PEFT, Quantization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/18-alignment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Alignment and RL Fine-Tuning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/19-generative.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Generative Models: From PCA to Diffusion</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a1-linear-algebra.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Linear Algebra and the SVD</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a2-tensors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Tensors in Practice</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a3-precision-performance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Numerical Precision and Hardware Efficiency</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a4-notation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Notation</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#chapter-1-already-mixed-old-answers" id="toc-chapter-1-already-mixed-old-answers" class="nav-link active" data-scroll-target="#chapter-1-already-mixed-old-answers"><span class="header-section-number">12.1</span> Chapter 1 already mixed old answers</a></li>
  <li><a href="#the-magnifying-glass-becomes-a-kernel" id="toc-the-magnifying-glass-becomes-a-kernel" class="nav-link" data-scroll-target="#the-magnifying-glass-becomes-a-kernel"><span class="header-section-number">12.2</span> The magnifying glass becomes a kernel</a></li>
  <li><a href="#chapter-2s-scores-to-weights-machine" id="toc-chapter-2s-scores-to-weights-machine" class="nav-link" data-scroll-target="#chapter-2s-scores-to-weights-machine"><span class="header-section-number">12.3</span> Chapter 2’s scores-to-weights machine</a></li>
  <li><a href="#bandwidth-the-honesty-gate" id="toc-bandwidth-the-honesty-gate" class="nav-link" data-scroll-target="#bandwidth-the-honesty-gate"><span class="header-section-number">12.4</span> Bandwidth: the honesty gate</a></li>
  <li><a href="#from-one-query-to-an-attention-matrix" id="toc-from-one-query-to-an-attention-matrix" class="nav-link" data-scroll-target="#from-one-query-to-an-attention-matrix"><span class="header-section-number">12.5</span> From one query to an attention matrix</a></li>
  <li><a href="#return-the-fixed-operator-to-the-memory-bank" id="toc-return-the-fixed-operator-to-the-memory-bank" class="nav-link" data-scroll-target="#return-the-fixed-operator-to-the-memory-bank"><span class="header-section-number">12.6</span> Return the fixed operator to the memory bank</a></li>
  <li><a href="#okay-so" id="toc-okay-so" class="nav-link" data-scroll-target="#okay-so"><span class="header-section-number">12.7</span> Okay, so —</a></li>
  <li><a href="#sources-and-further-reading" id="toc-sources-and-further-reading" class="nav-link" data-scroll-target="#sources-and-further-reading">Sources and further reading</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/Shakeri-Lab/dl-book/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/part4/12-kernel-regression.html">IV · Attention: Learning the Similarity</a></li><li class="breadcrumb-item"><a href="../../chapters/part4/12-kernel-regression.html"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Kernel Regression: Attention Before It Was Learnable</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-12-kernel-regression" class="quarto-section-identifier"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Kernel Regression: Attention Before It Was Learnable</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<!-- lecture-source: m08_lecture-8-attention-mechanism-part-1_8WBIyiaW7Cc.txt
     (spine via ds6050_08_attention/MODULE_NOTES.md; S03 scene composition)
     seeds: sources/8.1-Attention.tex (§Kernel Regression: The Conceptual Bridge,
            §From Kernel Regression to Attention), sources/Bridge_to_attention.tex
            (§Part 4 fixed score→normalize→mix, §Memory vs. access, Q/K/V roles)
     note: learned compatibility functions, projected Q/K/V, masking, and the
           date-task rematch wait for Chapter 13. The fixed-design Monte Carlo
           laboratory and all code here are book-original implementations. -->
<p>Chapter 11 ended with a machine that could translate, and one uncomfortable picture: every source fact had to cross a single fixed-size bridge before the decoder wrote its first token. The encoder had computed a state at every source position. Then we threw all but the last one away.</p>
<p>The lecture’s repair begins with an almost embarrassing question: why throw them away? Keep the whole sequence of encoder states as a <strong>memory bank</strong>. At each decoding step, ask what the decoder needs, compare that query with every stored state, and retrieve a weighted mixture of the relevant content. Keeping a bank does not make its entries lossless, but it removes the rule that <em>all</em> source information must pass through the last entry alone.</p>
<p>One problem remains: how should a query decide the mixture? A nearest-neighbor rule changes its chosen slot abruptly. We first need a smooth similarity-weighted rule, and statistics had one in 1964, half a century before modern neural attention.</p>
<p>Let us start with three observed pairs:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">observation</th>
<th style="text-align: right;">location <span class="math inline">\(x_i\)</span></th>
<th style="text-align: right;">response <span class="math inline">\(y_i\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.5</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2.8</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">1.8</td>
</tr>
</tbody>
</table>
<p>For a query <span class="math inline">\(q=3.5\)</span>, a Gaussian similarity with bandwidth <span class="math inline">\(h=0.6\)</span> assigns weights <span class="math inline">\((0.0002, 0.9413, 0.0585)\)</span>. Their weighted mixture is <span class="math inline">\(2.7412\)</span>. The second observation dominates because its location is closest, the third contributes a little, and the distant first observation is nearly silent. No similarity function was learned; the chosen metric and bandwidth did the routing.</p>
<section id="chapter-1-already-mixed-old-answers" class="level2" data-number="12.1">
<h2 data-number="12.1" class="anchored" data-anchor-id="chapter-1-already-mixed-old-answers"><span class="header-section-number">12.1</span> Chapter 1 already mixed old answers</h2>
<p>There is a piece of unfinished business from Chapter 1. Linear regression makes a prediction by mixing the observed targets. It hid that fact inside the normal equation.</p>
<p>Let the augmented design matrix <span class="math inline">\(\widetilde{\matr{X}}\in\mathbb{R}^{n\times(d+1)}\)</span> include the intercept column, let <span class="math inline">\(\widetilde{\vect{q}}\in\mathbb{R}^{d+1}\)</span> be a new query with its leading 1, and let <span class="math inline">\(\vect{y}\in\mathbb{R}^{n}\)</span> contain the observed targets. Assuming full column rank,</p>
<p><span class="math display">\[
\widehat{\vect{\beta}}
= (\widetilde{\matr{X}}^\top\widetilde{\matr{X}})^{-1}
  \widetilde{\matr{X}}^\top\vect{y}.
\]</span></p>
<p>The prediction at the query is therefore</p>
<p><span id="eq-ols-target-weights"><span class="math display">\[
\widehat f(\vect{q})
= \widetilde{\vect{q}}^\top\widehat{\vect{\beta}}
= \underbrace{\left[
  \widetilde{\matr{X}}
  (\widetilde{\matr{X}}^\top\widetilde{\matr{X}})^{-1}
  \widetilde{\vect{q}}
  \right]}_{\vect{\lambda}(\vect{q})}^{\!\top}\vect{y}.
\tag{12.1}\]</span></span></p>
<p>So Chapter 1’s promise was exact: <span class="math inline">\(\widehat f(\vect{q})\)</span> is a weighted combination of the training targets. With an intercept, the weights sum to one because OLS reproduces a constant response. But <strong>weighted combination</strong> is not the same as <strong>weighted average</strong>. The entries of <span class="math inline">\(\vect{\lambda}\)</span> may be negative.</p>
<p>For keys <span class="math inline">\((-2,-1,0,1,2)\)</span> and query <span class="math inline">\(q=1.5\)</span>, the OLS weights are</p>
<p><span class="math display">\[
(-0.10, 0.05, 0.20, 0.35, 0.50).
\]</span></p>
<p>They sum to one, yet the first is negative. If the targets are <span class="math inline">\((1,0,0,0,0)\)</span>, OLS predicts <span class="math inline">\(-0.10\)</span>, outside the observed range <span class="math inline">\([0,1]\)</span>. Linear regression is allowed to leave the observed targets’ convex hull even when the query lies inside the observed key range. For local smoothing, we want a stricter contract: nearby evidence should receive more weight, every weight should be nonnegative, and the weights should sum to one.</p>
</section>
<section id="the-magnifying-glass-becomes-a-kernel" class="level2" data-number="12.2">
<h2 data-number="12.2" class="anchored" data-anchor-id="the-magnifying-glass-becomes-a-kernel"><span class="header-section-number">12.2</span> The magnifying glass becomes a kernel</h2>
<p>A <strong>smoothing kernel</strong> is a similarity rule. It looks at a query and a stored key and returns a nonnegative affinity: large when they are close, small when they are far. To avoid confusing the kernel function with the matrix of keys later, we write it as <span class="math inline">\(\kappa_h\)</span>. The Gaussian choice is</p>
<p><span id="eq-gaussian-kernel"><span class="math display">\[
\kappa_h(\vect{q},\vect{k})
= \exp\!\left(-\frac{\norm{\vect{q}-\vect{k}}^2}{2h^2}\right),
\qquad h&gt;0.
\tag{12.2}\]</span></span></p>
<p>The bandwidth <span class="math inline">\(h\)</span> sets the width of the magnifying glass. A small value sees only the closest keys; a large value blends a broad neighborhood.</p>
<p>Given observed pairs <span class="math inline">\((\vect{x}_i,y_i)\)</span>, normalize the affinities,</p>
<p><span id="eq-nadaraya-watson"><span class="math display">\[
\alpha_i(\vect{q})
= \frac{\kappa_h(\vect{q},\vect{x}_i)}
       {\sum_{j=1}^{n}\kappa_h(\vect{q},\vect{x}_j)},
\qquad
\widehat f_h(\vect{q})=\sum_{i=1}^{n}\alpha_i(\vect{q})y_i.
\tag{12.3}\]</span></span></p>
<p>This is the <strong>Nadaraya–Watson estimator</strong>, proposed independently by Nadaraya and Watson in 1964. For the strictly positive Gaussian, each <span class="math inline">\(\alpha_i&gt;0\)</span> and <span class="math inline">\(\sum_i\alpha_i=1\)</span>. Scalar predictions remain between the smallest and largest observed values. Unlike OLS, this operator smooths locally while keeping every prediction inside the observed values’ convex hull.</p>
<p>The endpoint behavior is worth stating precisely. As <span class="math inline">\(h\to0^+\)</span>, the weight concentrates on the unique nearest key; exact nearest-key ties split the mass. At <span class="math inline">\(h=0\)</span> the formula is undefined. As <span class="math inline">\(h\to\infty\)</span>, every finite distance looks alike and the weights approach <span class="math inline">\(1/n\)</span>.</p>
<p>Now let us make the lecture’s change of names. Locations <span class="math inline">\(\vect{x}_i\)</span> become <strong>keys</strong> <span class="math inline">\(\vect{k}_i\)</span>, observed responses become <strong>values</strong> <span class="math inline">\(\vect{v}_i\)</span>, and <span class="math inline">\(\vect{q}\)</span> remains the <strong>query</strong>. The formula does not change. Here is the whole operator in NumPy. The shapes come before the multiplication: queries are <span class="math inline">\((m,d)\)</span>, keys are <span class="math inline">\((n,d)\)</span>, values are <span class="math inline">\((n,p)\)</span>, and the returned mixture is <span class="math inline">\((m,p)\)</span>.</p>
<div id="fixed-gaussian-attention" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Code: fixed Gaussian attention, from scores to mixtures</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> __future__ <span class="im">import</span> annotations</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>torch.manual_seed(<span class="dv">6050</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>np.set_printoptions(precision<span class="op">=</span><span class="dv">4</span>, suppress<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> row_softmax(scores: np.ndarray) <span class="op">-&gt;</span> np.ndarray:</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Normalize each row after a stability-preserving shift."""</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    shifted <span class="op">=</span> scores <span class="op">-</span> scores.<span class="bu">max</span>(axis<span class="op">=</span><span class="dv">1</span>, keepdims<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    weights <span class="op">=</span> np.exp(shifted)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> weights <span class="op">/</span> weights.<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">1</span>, keepdims<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> gaussian_attention(</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    queries: np.ndarray,</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    keys: np.ndarray,</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    values: np.ndarray,</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>    bandwidth: <span class="bu">float</span>,</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>) <span class="op">-&gt;</span> <span class="bu">tuple</span>[np.ndarray, np.ndarray]:</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Fixed Gaussian attention for Q:(m,d), K:(n,d), V:(n,p)."""</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="kw">not</span> np.isfinite(bandwidth) <span class="kw">or</span> bandwidth <span class="op">&lt;=</span> <span class="dv">0</span>:</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="st">"bandwidth must be positive and finite"</span>)</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> queries.ndim <span class="op">!=</span> <span class="dv">2</span> <span class="kw">or</span> keys.ndim <span class="op">!=</span> <span class="dv">2</span> <span class="kw">or</span> values.ndim <span class="op">!=</span> <span class="dv">2</span>:</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="st">"queries, keys, and values must be matrices"</span>)</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> queries.shape[<span class="dv">1</span>] <span class="op">!=</span> keys.shape[<span class="dv">1</span>] <span class="kw">or</span> keys.shape[<span class="dv">0</span>] <span class="op">!=</span> values.shape[<span class="dv">0</span>]:</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="st">"Q/K feature dimensions and K/V row counts must agree"</span>)</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>    distances2 <span class="op">=</span> ((queries[:, <span class="va">None</span>, :] <span class="op">-</span> keys[<span class="va">None</span>, :, :]) <span class="op">**</span> <span class="dv">2</span>).<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>    log_scores <span class="op">=</span> <span class="op">-</span>distances2 <span class="op">/</span> (<span class="fl">2.0</span> <span class="op">*</span> bandwidth<span class="op">**</span><span class="dv">2</span>)  <span class="co"># (m, n)</span></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>    weights <span class="op">=</span> row_softmax(log_scores)                <span class="co"># (m, n)</span></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> weights <span class="op">@</span> values, weights                 <span class="co"># (m, p), (m, n)</span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>keys3 <span class="op">=</span> np.array([[<span class="fl">1.0</span>], [<span class="fl">3.0</span>], [<span class="fl">5.0</span>]])</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>values3 <span class="op">=</span> np.array([[<span class="fl">1.5</span>], [<span class="fl">2.8</span>], [<span class="fl">1.8</span>]])</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>query3 <span class="op">=</span> np.array([[<span class="fl">3.5</span>]])</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>pred3, weights3 <span class="op">=</span> gaussian_attention(query3, keys3, values3, bandwidth<span class="op">=</span><span class="fl">0.6</span>)</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"weights:"</span>, weights3[<span class="dv">0</span>])</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"prediction: </span><span class="sc">{</span>pred3<span class="sc">.</span>item()<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>weights: [0.0002 0.9413 0.0585]
prediction: 2.7412</code></pre>
</div>
</div>
<div id="cell-fig-kernel-lookup" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Figure: the three-point lookup</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="fl">7.2</span>, <span class="fl">3.0</span>), constrained_layout<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].scatter(keys3[:, <span class="dv">0</span>], values3[:, <span class="dv">0</span>], s<span class="op">=</span><span class="dv">55</span>, color<span class="op">=</span><span class="st">"#232D4B"</span>, zorder<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].axvline(query3.item(), color<span class="op">=</span><span class="st">"#E57200"</span>, ls<span class="op">=</span><span class="st">"--"</span>, lw<span class="op">=</span><span class="fl">1.4</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].scatter(query3.item(), pred3.item(), marker<span class="op">=</span><span class="st">"*"</span>, s<span class="op">=</span><span class="dv">130</span>,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>                color<span class="op">=</span><span class="st">"#E57200"</span>, zorder<span class="op">=</span><span class="dv">4</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> key, value, weight <span class="kw">in</span> <span class="bu">zip</span>(keys3[:, <span class="dv">0</span>], values3[:, <span class="dv">0</span>], weights3[<span class="dv">0</span>]):</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">0</span>].plot([query3.item(), key], [pred3.item(), value],</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>                 color<span class="op">=</span><span class="st">"#B45309"</span>, lw<span class="op">=</span><span class="fl">0.8</span> <span class="op">+</span> <span class="fl">5.0</span> <span class="op">*</span> weight,</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>                 alpha<span class="op">=</span><span class="fl">0.25</span> <span class="op">+</span> <span class="fl">0.7</span> <span class="op">*</span> weight)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].<span class="bu">set</span>(xlabel<span class="op">=</span><span class="st">"location"</span>, ylabel<span class="op">=</span><span class="st">"value"</span>, title<span class="op">=</span><span class="st">"Query nearby evidence"</span>)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xticks([<span class="dv">1</span>, <span class="dv">3</span>, <span class="fl">3.5</span>, <span class="dv">5</span>], [<span class="st">"1"</span>, <span class="st">"3"</span>, <span class="st">"q=3.5"</span>, <span class="st">"5"</span>])</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].annotate(<span class="vs">r"</span><span class="dv">$</span><span class="er">\</span><span class="vs">hat f</span><span class="kw">(</span><span class="vs">q</span><span class="kw">)</span><span class="vs">=2</span><span class="dv">.</span><span class="vs">74</span><span class="dv">$</span><span class="vs">"</span>, (query3.item(), pred3.item()),</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>                 xytext<span class="op">=</span>(<span class="dv">8</span>, <span class="op">-</span><span class="dv">22</span>), textcoords<span class="op">=</span><span class="st">"offset points"</span>, color<span class="op">=</span><span class="st">"#B45309"</span>)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].bar([<span class="st">"$k_1$"</span>, <span class="st">"$k_2$"</span>, <span class="st">"$k_3$"</span>], weights3[<span class="dv">0</span>],</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>            color<span class="op">=</span>[<span class="st">"#B0B7C3"</span>, <span class="st">"#E57200"</span>, <span class="st">"#B45309"</span>])</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, weight <span class="kw">in</span> <span class="bu">enumerate</span>(weights3[<span class="dv">0</span>]):</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">1</span>].text(i, weight <span class="op">+</span> <span class="fl">0.025</span>, <span class="ss">f"</span><span class="sc">{</span>weight<span class="sc">:.4f}</span><span class="ss">"</span>, ha<span class="op">=</span><span class="st">"center"</span>)</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].<span class="bu">set</span>(ylabel<span class="op">=</span><span class="st">"normalized weight"</span>, ylim<span class="op">=</span>(<span class="dv">0</span>, <span class="fl">1.05</span>),</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>            title<span class="op">=</span><span class="st">"Similarity decides the mix"</span>)</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-kernel-lookup" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-kernel-lookup-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="12-kernel-regression_files/figure-html/fig-kernel-lookup-output-1.png" width="702" height="299" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-kernel-lookup-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.1: A fixed Gaussian lookup. The bars give the normalized weights, and the connecting lines show which observations feed the query. The query lands close to the second location, so its response dominates the mixture; no similarity function was learned.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The same code makes the OLS distinction concrete:</p>
<div id="ols-versus-kernel-weights" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code: signed OLS weights versus convex kernel weights</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>ols_keys <span class="op">=</span> np.array([<span class="op">-</span><span class="fl">2.0</span>, <span class="op">-</span><span class="fl">1.0</span>, <span class="fl">0.0</span>, <span class="fl">1.0</span>, <span class="fl">2.0</span>])</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>ols_query <span class="op">=</span> <span class="fl">1.5</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>design <span class="op">=</span> np.column_stack([np.ones_like(ols_keys), ols_keys])</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>query_design <span class="op">=</span> np.array([<span class="fl">1.0</span>, ols_query])</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>ols_weights <span class="op">=</span> query_design <span class="op">@</span> np.linalg.solve(design.T <span class="op">@</span> design, design.T)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>witness_values <span class="op">=</span> np.array([[<span class="fl">1.0</span>], [<span class="fl">0.0</span>], [<span class="fl">0.0</span>], [<span class="fl">0.0</span>], [<span class="fl">0.0</span>]])</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>nw_pred, nw_weights <span class="op">=</span> gaussian_attention(</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    np.array([[ols_query]]), ols_keys[:, <span class="va">None</span>], witness_values, bandwidth<span class="op">=</span><span class="fl">1.0</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"OLS weights:"</span>, ols_weights, <span class="st">"sum:"</span>, ols_weights.<span class="bu">sum</span>())</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"NW  weights:"</span>, nw_weights[<span class="dv">0</span>], <span class="st">"sum:"</span>, nw_weights.<span class="bu">sum</span>())</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"witness predictions: OLS </span><span class="sc">{</span>ols_weights <span class="op">@</span> witness_values[:, <span class="dv">0</span>]<span class="sc">:.4f}</span><span class="ss">, "</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"NW </span><span class="sc">{</span>nw_pred<span class="sc">.</span>item()<span class="sc">:.4f}</span><span class="ss">; target range [0, 1]"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>OLS weights: [-0.1   0.05  0.2   0.35  0.5 ] sum: 1.0
NW  weights: [0.001  0.0206 0.152  0.4132 0.4132] sum: 1.0
witness predictions: OLS -0.1000, NW 0.0010; target range [0, 1]</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Which kernels make a convex average?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Only nonnegative smoothing kernels make this convex average. A Gaussian gives positive weights; a compact-support kernel may give zeros. Other objects also bear the name <em>kernel</em>. <a href="#eq-nadaraya-watson" class="quarto-xref">Equation&nbsp;<span>12.3</span></a> needs nonnegative numerators and a positive denominator.</p>
</div>
</div>
</section>
<section id="chapter-2s-scores-to-weights-machine" class="level2" data-number="12.3">
<h2 data-number="12.3" class="anchored" data-anchor-id="chapter-2s-scores-to-weights-machine"><span class="header-section-number">12.3</span> Chapter 2’s scores-to-weights machine</h2>
<p>Now harvest the second promise. Chapter 2 introduced softmax as the machine that turns arbitrary scores into nonnegative weights summing to one. Nadaraya–Watson has exactly that form. For any strictly positive kernel,</p>
<p><span id="eq-log-kernel-softmax"><span class="math display">\[
\alpha_i(\vect{q})
= \frac{\kappa_h(\vect{q},\vect{k}_i)}
       {\sum_j\kappa_h(\vect{q},\vect{k}_j)}
= \operatorname{softmax}_i\!\left(
  \log\kappa_h(\vect{q},\vect{k}_i)\right).
\tag{12.4}\]</span></span></p>
<p>The <strong>score</strong> is the log-kernel. With the Gaussian,</p>
<p><span class="math display">\[
a_i(\vect{q})
= -\frac{\norm{\vect{q}-\vect{k}_i}^2}{2h^2}.
\]</span></p>
<p>This also makes the temperature connection exact. If the unscaled score is <span class="math inline">\(s_i=-\norm{\vect{q}-\vect{k}_i}^2\)</span>, then</p>
<p><span id="eq-bandwidth-temperature"><span class="math display">\[
\vect{\alpha}(\vect{q})
= \operatorname{softmax}\!\left(\frac{\vect{s}}{\tau}\right),
\qquad \tau=2h^2.
\tag{12.5}\]</span></span></p>
<p>Small bandwidth <span class="math inline">\(\rightarrow\)</span> low temperature <span class="math inline">\(\rightarrow\)</span> sharp lookup. Large bandwidth <span class="math inline">\(\rightarrow\)</span> high temperature <span class="math inline">\(\rightarrow\)</span> diffuse averaging. The factor <span class="math inline">\(2\)</span> belongs to this score convention; if we had defined <span class="math inline">\(s_i=-\norm{\vect{q}-\vect{k}_i}^2/2\)</span>, the temperature would be <span class="math inline">\(h^2\)</span> instead.</p>
<p>Notice the implementation never computes <span class="math inline">\(\kappa_h\)</span> and then takes its logarithm. It computes the log-score directly, subtracts the largest score in each row, and only then exponentiates. That is Chapter 2’s stable-softmax hygiene, now paying rent again.</p>
</section>
<section id="bandwidth-the-honesty-gate" class="level2" data-number="12.4">
<h2 data-number="12.4" class="anchored" data-anchor-id="bandwidth-the-honesty-gate"><span class="header-section-number">12.4</span> Bandwidth: the honesty gate</h2>
<p>The three-point example makes a narrow bandwidth look wonderful. That is not evidence that narrower is better. A tiny neighborhood follows every noisy bump; a huge neighborhood washes real structure away. Chapter 1 called this bias versus variance. Here the bandwidth controls the trade.</p>
<p>Because this is a synthetic laboratory, we can do something ordinary observed data does not permit: hold 60 key locations fixed, redraw the response noise 1,000 times, and compare every prediction with the known function</p>
<p><span class="math display">\[
f(x)=\sin(1.5x)+0.3\cos(4x),
\qquad y_i=f(x_i)+\epsilon_i,
\qquad \epsilon_i\sim\mathcal{N}(0,0.25^2).
\]</span></p>
<p>The key locations are seeded uniform draws on <span class="math inline">\([-3,3]\)</span>. The 241 query locations lie on <span class="math inline">\([-2.9,2.9]\)</span> and share no exact coordinate with a key. Holding the design fixed lets us separate squared bias from variance over independent noise draws. The population identity</p>
<p><span class="math display">\[
\operatorname{MSE}=\operatorname{bias}^2+\operatorname{variance}
\]</span></p>
<p>has no irreducible-noise term because we evaluate against the noiseless <span class="math inline">\(f\)</span>; predicting a fresh noisy response would add the irreducible variance <span class="math inline">\(0.25^2\)</span> to every row. In our finite 1,000-world ensemble, the analogous empirical decomposition closes to floating-point roundoff.</p>
<div id="bandwidth-sweep" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code: fixed-design bias/variance sweep over 1,000 noisy worlds</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> truth(x: np.ndarray) <span class="op">-&gt;</span> np.ndarray:</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.sin(<span class="fl">1.5</span> <span class="op">*</span> x) <span class="op">+</span> <span class="fl">0.3</span> <span class="op">*</span> np.cos(<span class="fl">4.0</span> <span class="op">*</span> x)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>data_rng <span class="op">=</span> np.random.default_rng(<span class="dv">605012</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>keys <span class="op">=</span> np.sort(data_rng.uniform(<span class="op">-</span><span class="fl">3.0</span>, <span class="fl">3.0</span>, size<span class="op">=</span><span class="dv">60</span>))</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>observed_rng <span class="op">=</span> np.random.default_rng(<span class="dv">605013</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>observed_values <span class="op">=</span> truth(keys) <span class="op">+</span> observed_rng.normal(<span class="fl">0.0</span>, <span class="fl">0.25</span>, size<span class="op">=</span>keys.size)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>queries <span class="op">=</span> np.linspace(<span class="op">-</span><span class="fl">2.9</span>, <span class="fl">2.9</span>, <span class="dv">241</span>)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>mc_rng <span class="op">=</span> np.random.default_rng(<span class="dv">605014</span>)</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>responses <span class="op">=</span> truth(keys)[<span class="va">None</span>, :] <span class="op">+</span> mc_rng.normal(</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.0</span>, <span class="fl">0.25</span>, size<span class="op">=</span>(<span class="dv">1_000</span>, keys.size)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>bandwidths <span class="op">=</span> np.array([<span class="fl">0.05</span>, <span class="fl">0.08</span>, <span class="fl">0.12</span>, <span class="fl">0.18</span>, <span class="fl">0.28</span>, <span class="fl">0.42</span>, <span class="fl">0.65</span>, <span class="fl">1.00</span>])</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> []</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> bandwidth <span class="kw">in</span> bandwidths:</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>    _, weights <span class="op">=</span> gaussian_attention(</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>        queries[:, <span class="va">None</span>], keys[:, <span class="va">None</span>], observed_values[:, <span class="va">None</span>], bandwidth</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>    predictions <span class="op">=</span> responses <span class="op">@</span> weights.T                 <span class="co"># (world, query)</span></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>    mean_prediction <span class="op">=</span> predictions.mean(axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>    squared_bias <span class="op">=</span> np.mean((mean_prediction <span class="op">-</span> truth(queries)) <span class="op">**</span> <span class="dv">2</span>)</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>    variance <span class="op">=</span> np.mean(np.var(predictions, axis<span class="op">=</span><span class="dv">0</span>))</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>    mse <span class="op">=</span> np.mean((predictions <span class="op">-</span> truth(queries)[<span class="va">None</span>, :]) <span class="op">**</span> <span class="dv">2</span>)</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>    rows.append((bandwidth, <span class="dv">2</span> <span class="op">*</span> bandwidth<span class="op">**</span><span class="dv">2</span>, squared_bias, variance, mse))</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">" h     2h^2    bias^2  variance     MSE"</span>)</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> row <span class="kw">in</span> rows:</span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>row[<span class="dv">0</span>]<span class="sc">:.2f}</span><span class="ss">   </span><span class="sc">{</span>row[<span class="dv">1</span>]<span class="sc">:.4f}</span><span class="ss">   </span><span class="sc">{</span>row[<span class="dv">2</span>]<span class="sc">:.4f}</span><span class="ss">   "</span></span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"</span><span class="sc">{</span>row[<span class="dv">3</span>]<span class="sc">:.4f}</span><span class="ss">   </span><span class="sc">{</span>row[<span class="dv">4</span>]<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a>best <span class="op">=</span> rows[<span class="bu">int</span>(np.argmin([row[<span class="op">-</span><span class="dv">1</span>] <span class="cf">for</span> row <span class="kw">in</span> rows]))]</span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"grid minimum: h=</span><span class="sc">{</span>best[<span class="dv">0</span>]<span class="sc">:.2f}</span><span class="ss">, MSE=</span><span class="sc">{</span>best[<span class="op">-</span><span class="dv">1</span>]<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> h     2h^2    bias^2  variance     MSE
0.05   0.0050   0.0119   0.0343   0.0462
0.08   0.0128   0.0101   0.0247   0.0348
0.12   0.0288   0.0090   0.0169   0.0259
0.18   0.0648   0.0127   0.0109   0.0236
0.28   0.1568   0.0304   0.0069   0.0373
0.42   0.3528   0.0747   0.0047   0.0794
0.65   0.8450   0.1721   0.0031   0.1753
1.00   2.0000   0.3142   0.0022   0.3164
grid minimum: h=0.18, MSE=0.0236</code></pre>
</div>
</div>
<p>The variance falls at every step, from <span class="math inline">\(0.0343\)</span> at <span class="math inline">\(h=0.05\)</span> to <span class="math inline">\(0.0022\)</span> at <span class="math inline">\(h=1.00\)</span>. Bias squared is not perfectly monotone at the sharp end of this sparse, random design; it bottoms at <span class="math inline">\(0.0090\)</span> for <span class="math inline">\(h=0.12\)</span>, then rises to <span class="math inline">\(0.3142\)</span> at <span class="math inline">\(h=1.00\)</span>. Their sum is the U-shaped quantity we care about. On this predeclared grid, <span class="math inline">\(h=0.18\)</span> has the smallest MSE, <span class="math inline">\(0.0236\)</span>.</p>
<p>One noisy world shows what those numbers mean:</p>
<div id="cell-fig-bandwidth-fits" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Figure: bandwidth as the smoothness dial</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">7.2</span>, <span class="fl">4.1</span>), constrained_layout<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>dense <span class="op">=</span> np.linspace(<span class="op">-</span><span class="fl">3.0</span>, <span class="fl">3.0</span>, <span class="dv">601</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>ax.plot(dense, truth(dense), color<span class="op">=</span><span class="st">"black"</span>, lw<span class="op">=</span><span class="fl">2.0</span>, label<span class="op">=</span><span class="st">"truth"</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>ax.scatter(keys, observed_values, s<span class="op">=</span><span class="dv">15</span>, color<span class="op">=</span><span class="st">"#555555"</span>, alpha<span class="op">=</span><span class="fl">0.72</span>,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>           label<span class="op">=</span><span class="st">"one noisy sample"</span>, zorder<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> bandwidth, color <span class="kw">in</span> [(<span class="fl">0.05</span>, <span class="st">"#D55E00"</span>),</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>                         (<span class="fl">0.18</span>, <span class="st">"#0072B2"</span>),</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>                         (<span class="fl">0.65</span>, <span class="st">"#009E73"</span>)]:</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    predictions, _ <span class="op">=</span> gaussian_attention(</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>        dense[:, <span class="va">None</span>], keys[:, <span class="va">None</span>], observed_values[:, <span class="va">None</span>], bandwidth</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>    ax.plot(dense, predictions[:, <span class="dv">0</span>], color<span class="op">=</span>color, lw<span class="op">=</span><span class="fl">1.8</span>,</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>            label<span class="op">=</span><span class="vs">fr"</span><span class="dv">$</span><span class="vs">h=</span><span class="sc">{</span>bandwidth<span class="sc">:.2f}</span><span class="dv">$</span><span class="vs">"</span>)</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>ax.<span class="bu">set</span>(xlabel<span class="op">=</span><span class="st">"query $q$"</span>, ylabel<span class="op">=</span><span class="st">"prediction"</span>,</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>       title<span class="op">=</span><span class="st">"Bandwidth is a smoothness dial"</span>)</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>ax.legend(ncol<span class="op">=</span><span class="dv">2</span>, frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-bandwidth-fits" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bandwidth-fits-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="12-kernel-regression_files/figure-html/fig-bandwidth-fits-output-1.png" width="702" height="405" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bandwidth-fits-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.2: One fixed noisy sample under three bandwidths. The narrow rule follows local noise, the middle rule tracks the signal, and the broad rule erases the function’s smaller-scale structure. The blue bandwidth is the grid minimum in the 1,000-world audit, not a hand-picked attractive curve.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Selecting <span class="math inline">\(h\)</span> when the truth is hidden
</div>
</div>
<div class="callout-body-container callout-body">
<p>The known black curve is a laboratory privilege. On real data, choose the bandwidth using a validation set, then report once on a sealed test set. Training error alone will usually reward an extremely narrow kernel for copying each noisy target back to itself. The generalization protocol from Chapter 6 still applies even when nothing is trained by gradient descent.</p>
</div>
</div>
</section>
<section id="from-one-query-to-an-attention-matrix" class="level2" data-number="12.5">
<h2 data-number="12.5" class="anchored" data-anchor-id="from-one-query-to-an-attention-matrix"><span class="header-section-number">12.5</span> From one query to an attention matrix</h2>
<p>Now write the operator in the vocabulary that the rest of Part IV will keep. Let</p>
<p><span class="math display">\[
\matr{Q}\in\mathbb{R}^{m\times d},\qquad
\matr{K}\in\mathbb{R}^{n\times d},\qquad
\matr{V}\in\mathbb{R}^{n\times p}
\]</span></p>
<p>hold <span class="math inline">\(m\)</span> queries, <span class="math inline">\(n\)</span> keys, and one <span class="math inline">\(p\)</span>-dimensional value per key. The score and weight matrices are</p>
<p><span id="eq-fixed-attention-matrix"><span class="math display">\[
S_{ri}=-\frac{\norm{\vect{q}_r-\vect{k}_i}^2}{2h^2},
\qquad
\matr{A}=\operatorname{rowsoftmax}(\matr{S})
\in\mathbb{R}^{m\times n}.
\tag{12.6}\]</span></span></p>
<p>Every row of <span class="math inline">\(\matr{A}\)</span> sums to one; columns generally do not. The pooled outputs are one matrix multiplication,</p>
<p><span id="eq-fixed-attention"><span class="math display">\[
\operatorname{Attention}_h(\matr{Q},\matr{K},\matr{V})
=\matr{A}\matr{V}\in\mathbb{R}^{m\times p}.
\tag{12.7}\]</span></span></p>
<p>This is the book’s first <strong>attention-weight matrix</strong>. It is not a learned alignment. It is the allocation imposed by Euclidean distance and the chosen bandwidth.</p>
<div id="cell-fig-fixed-attention-map" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Figure: measured trade-off and the first attention map</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="fl">7.4</span>, <span class="fl">3.25</span>), constrained_layout<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>row_array <span class="op">=</span> np.asarray(rows)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].plot(row_array[:, <span class="dv">0</span>], row_array[:, <span class="dv">2</span>], <span class="st">"o-"</span>, label<span class="op">=</span><span class="vs">r"bias</span><span class="dv">$^</span><span class="vs">2</span><span class="dv">$</span><span class="vs">"</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].plot(row_array[:, <span class="dv">0</span>], row_array[:, <span class="dv">3</span>], <span class="st">"o-"</span>, label<span class="op">=</span><span class="st">"variance"</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].plot(row_array[:, <span class="dv">0</span>], row_array[:, <span class="dv">4</span>], <span class="st">"o-"</span>, lw<span class="op">=</span><span class="fl">2.2</span>, label<span class="op">=</span><span class="st">"MSE"</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].axvline(best[<span class="dv">0</span>], color<span class="op">=</span><span class="st">"#888888"</span>, ls<span class="op">=</span><span class="st">"--"</span>, lw<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xscale(<span class="st">"log"</span>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].<span class="bu">set</span>(xlabel<span class="op">=</span><span class="st">"bandwidth $h$"</span>, ylabel<span class="op">=</span><span class="st">"error against true $f$"</span>,</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>            title<span class="op">=</span><span class="st">"The trade-off is measurable"</span>)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>map_queries <span class="op">=</span> np.linspace(<span class="op">-</span><span class="fl">2.9</span>, <span class="fl">2.9</span>, <span class="dv">31</span>)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>map_predictions, attention_map <span class="op">=</span> gaussian_attention(</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>    map_queries[:, <span class="va">None</span>], keys[:, <span class="va">None</span>], observed_values[:, <span class="va">None</span>], best[<span class="dv">0</span>]</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>image <span class="op">=</span> axes[<span class="dv">1</span>].imshow(</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>    attention_map, origin<span class="op">=</span><span class="st">"lower"</span>, aspect<span class="op">=</span><span class="st">"auto"</span>, cmap<span class="op">=</span><span class="st">"magma"</span>,</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>    extent<span class="op">=</span>(<span class="op">-</span><span class="fl">0.5</span>, <span class="bu">len</span>(keys) <span class="op">-</span> <span class="fl">0.5</span>, map_queries[<span class="dv">0</span>], map_queries[<span class="op">-</span><span class="dv">1</span>]),</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>key_index_at_query <span class="op">=</span> np.interp(map_queries, keys, np.arange(<span class="bu">len</span>(keys)))</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].plot(key_index_at_query, map_queries, color<span class="op">=</span><span class="st">"white"</span>, lw<span class="op">=</span><span class="fl">1.0</span>, alpha<span class="op">=</span><span class="fl">0.8</span>)</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>ticks <span class="op">=</span> np.array([<span class="dv">0</span>, <span class="dv">15</span>, <span class="dv">30</span>, <span class="dv">45</span>, <span class="dv">59</span>])</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xticks(ticks, [<span class="ss">f"</span><span class="sc">{</span>keys[i]<span class="sc">:.1f}</span><span class="ss">"</span> <span class="cf">for</span> i <span class="kw">in</span> ticks])</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].<span class="bu">set</span>(xlabel<span class="op">=</span><span class="st">"key location $k_i$ (sorted)"</span>, ylabel<span class="op">=</span><span class="st">"query $q$"</span>,</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>            title<span class="op">=</span><span class="vs">fr"Fixed attention matrix, </span><span class="dv">$</span><span class="vs">h=</span><span class="sc">{</span>best[<span class="dv">0</span>]<span class="sc">:.2f}</span><span class="dv">$</span><span class="vs">"</span>)</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>fig.colorbar(image, ax<span class="op">=</span>axes[<span class="dv">1</span>], label<span class="op">=</span><span class="st">"weight"</span>, fraction<span class="op">=</span><span class="fl">0.05</span>, pad<span class="op">=</span><span class="fl">0.04</span>)</span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Q </span><span class="sc">{</span>map_queries[:, <span class="va">None</span>]<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">, K </span><span class="sc">{</span>keys[:, <span class="va">None</span>]<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">, "</span></span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"V </span><span class="sc">{</span>observed_values[:, <span class="va">None</span>]<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">, A </span><span class="sc">{</span>attention_map<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">, "</span></span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"AV </span><span class="sc">{</span>map_predictions<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"maximum row-sum error:"</span>,</span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">max</span>(np.<span class="bu">abs</span>(attention_map.<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">1</span>) <span class="op">-</span> <span class="dv">1</span>))<span class="sc">:.2e}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-fixed-attention-map" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fixed-attention-map-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="12-kernel-regression_files/figure-html/fig-fixed-attention-map-output-1.png" width="721" height="323" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fixed-attention-map-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.3: Left: the fixed-design bias–variance audit. Right: the same Gaussian rule written as a 31-query by 60-key attention matrix at <span class="math inline">\(h=0.18\)</span>. Bright cells receive more of a row’s unit mass; the white trace marks the <span class="math inline">\(k=q\)</span> locus in sorted-key coordinates. The map is local and interpretable, but it was specified rather than learned.
</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Q (31, 1), K (60, 1), V (60, 1), A (31, 60), AV (31, 1)
maximum row-sum error: 2.22e-16</code></pre>
</div>
</div>
<p>Read the bright band as a moving magnifying glass. Each query row reallocates one unit of weight across the stored keys. Where keys are dense, that unit is divided among several neighbors. Where keys are sparse, one or two slots carry most of it. Changing <span class="math inline">\(h\)</span> changes the width of the band, exactly as changing temperature changes the spread of a softmax distribution.</p>
<p>There is one numerical trap. A Gaussian is mathematically positive everywhere, but a distant query and small bandwidth can make every directly exponentiated kernel value underflow to zero. Normalizing those zeros produces <code>0/0</code>. The log-score version still has a largest entry, so the shifted softmax remains finite. This is one of the stable- algorithm case studies reunited in <a href="../appendices/a3-precision-performance.html" class="quarto-xref"><span>Appendix C</span></a>:</p>
<div id="log-kernel-stability" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Code: verify the log-kernel identity and survive underflow</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>identity_query, identity_h <span class="op">=</span> <span class="fl">0.37</span>, <span class="fl">0.28</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>log_kernel <span class="op">=</span> <span class="op">-</span><span class="fl">0.5</span> <span class="op">*</span> ((identity_query <span class="op">-</span> keys) <span class="op">/</span> identity_h) <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>direct_kernel <span class="op">=</span> np.exp(log_kernel)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>direct_weights <span class="op">=</span> direct_kernel <span class="op">/</span> direct_kernel.<span class="bu">sum</span>()</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>softmax_weights <span class="op">=</span> row_softmax(log_kernel[<span class="va">None</span>, :])[<span class="dv">0</span>]</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>far_log_kernel <span class="op">=</span> <span class="op">-</span><span class="fl">0.5</span> <span class="op">*</span> ((<span class="fl">1_000.0</span> <span class="op">-</span> keys) <span class="op">/</span> <span class="fl">0.1</span>) <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>far_kernel <span class="op">=</span> np.exp(far_log_kernel)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> np.errstate(divide<span class="op">=</span><span class="st">"ignore"</span>, invalid<span class="op">=</span><span class="st">"ignore"</span>):</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    naive_far_weights <span class="op">=</span> far_kernel <span class="op">/</span> far_kernel.<span class="bu">sum</span>()</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>stable_far_weights <span class="op">=</span> row_softmax(far_log_kernel[<span class="va">None</span>, :])[<span class="dv">0</span>]</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"max |normalize(K)-softmax(log K)|:"</span>,</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">max</span>(np.<span class="bu">abs</span>(direct_weights <span class="op">-</span> softmax_weights))<span class="sc">:.2e}</span><span class="ss">"</span>)</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"far query: naive denominator=</span><span class="sc">{</span>far_kernel<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:.1f}</span><span class="ss">, "</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"all finite=</span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">all</span>(np.isfinite(naive_far_weights))<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"stable: sum=</span><span class="sc">{</span>stable_far_weights<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:.1f}</span><span class="ss">, "</span></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"nearest key=</span><span class="sc">{</span>keys[np.argmax(stable_far_weights)]<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>max |normalize(K)-softmax(log K)|: 2.78e-17
far query: naive denominator=0.0, all finite=False
stable: sum=1.0, nearest key=2.9886</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Similarity weights are not uncertainty probabilities
</div>
</div>
<div class="callout-body-container callout-body">
<p>The entries of <span class="math inline">\(\matr{A}\)</span> are probability-like allocations: nonnegative and row-normalized. They are not calibrated probabilities that the corresponding key is “correct,” and a sharp row is not automatically confidence. It may simply mean the bandwidth is small.</p>
</div>
</div>
</section>
<section id="return-the-fixed-operator-to-the-memory-bank" class="level2" data-number="12.6">
<h2 data-number="12.6" class="anchored" data-anchor-id="return-the-fixed-operator-to-the-memory-bank"><span class="header-section-number">12.6</span> Return the fixed operator to the memory bank</h2>
<p>The regression names now return to Chapter 11’s memory bank. Each one names a different job:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>job</th>
<th>kernel regression</th>
<th>sequence memory preview</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>query</strong></td>
<td>location <span class="math inline">\(\vect{q}\)</span> where we need an answer</td>
<td>what the decoder needs now</td>
</tr>
<tr class="even">
<td><strong>keys</strong></td>
<td>stored coordinates <span class="math inline">\(\vect{k}_i\)</span></td>
<td>descriptors used to match encoder memory slots</td>
</tr>
<tr class="odd">
<td><strong>values</strong></td>
<td>observed responses <span class="math inline">\(\vect{v}_i\)</span></td>
<td>content retrieved from those slots</td>
</tr>
<tr class="even">
<td><strong>weights</strong></td>
<td>normalized fixed similarities <span class="math inline">\(\alpha_i(\vect{q})\)</span></td>
<td>how much each slot contributes</td>
</tr>
<tr class="odd">
<td><strong>output</strong></td>
<td><span class="math inline">\(\sum_i\alpha_i\vect{v}_i\)</span></td>
<td>a query-specific context vector</td>
</tr>
</tbody>
</table>
<p>Queries specify what is needed; keys provide what to compare against; values provide what to retrieve. In the simplest sequence model, the same encoder state can play both roles, just as our one-dimensional example stores a location and its response together. Later, learned projections will let keys and values carry different representations.</p>
<p>Chapter 1 also planted one more similarity primitive, the dot product:</p>
<p><span class="math display">\[
\vect{q}^\top\vect{k}
=\norm{\vect{q}}\,\norm{\vect{k}}\cos\theta.
\]</span></p>
<p>It is pure angular similarity only when the norms are controlled. If <span class="math inline">\(\vect{q}=(1,0)\)</span>, <span class="math inline">\(\vect{k}_1=(1,0)\)</span>, and <span class="math inline">\(\vect{k}_2=(2,0)\)</span>, both keys point in the same direction as the query, but their dot products are 1 and 2. Magnitude participates. That is not a defect; it is a reminder that the score defines what “similar” means.</p>
<p>Our score today is a hand-written negative squared Euclidean distance, and <span class="math inline">\(h\)</span> is selected rather than learned. The operator stores the data, computes a fixed map, and pools the values. It shares attention’s normalized similarity-pooling algebra, but it has no learned compatibility function.</p>
<p>Now the Part II rhyme returns. Chapter 7 ended with a fixed image kernel and asked what would happen if the filter became learnable. Chapter 8 answered with a CNN. We end Part IV’s opening chapter with the same question:</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>What if the similarity itself were learnable?
</div>
</div>
<div class="callout-body-container callout-body">
<p>The memory bank is ready. Query, keys, values, scores, row-wise softmax, and weighted pooling are ready. Only one hand-designed piece remains: the rule that decides whether a query and key belong together. Chapter 13 makes that rule learnable, then returns to Chapter 11’s date task so the decoder can show us where it looked.</p>
</div>
</div>
</section>
<section id="okay-so" class="level2" data-number="12.7">
<h2 data-number="12.7" class="anchored" data-anchor-id="okay-so"><span class="header-section-number">12.7</span> Okay, so —</h2>
<ol type="1">
<li><strong>Chapter 1’s linear prediction already mixed training targets.</strong> OLS gives <span class="math inline">\(\widehat f(\vect{q})=\vect{\lambda}(\vect{q})^\top\vect{y}\)</span>, but its weights may be signed, so the prediction can leave the targets’ convex hull.</li>
<li><strong>Nadaraya–Watson turns locality into a convex mixture.</strong> A nonnegative kernel scores query–key similarity; normalization makes the weights sum to one; their weighted values form the prediction.</li>
<li><strong>Bandwidth is temperature in geometric clothing.</strong> For Gaussian distance scores, <span class="math inline">\(\tau=2h^2\)</span>: narrow is sharp and variable, wide is diffuse and biased. Our fixed audit reached its grid-minimum MSE of <span class="math inline">\(0.0236\)</span> at <span class="math inline">\(h=0.18\)</span>.</li>
<li><strong>Chapter 2’s softmax is the normalization exactly.</strong> Positive-kernel weights equal <code>softmax(log kernel)</code>. Computing log-scores directly and shifting each row avoids the distant-query <code>0/0</code> trap.</li>
<li><strong>Fixed attention is <span class="math inline">\(\matr{A}\matr{V}\)</span>.</strong> Queries score keys, row-softmax produces an <span class="math inline">\(m\times n\)</span> allocation matrix, and that matrix pools the values. The algebra is complete; learning the score is the next chapter’s move.</li>
</ol>
</section>
<section id="sources-and-further-reading" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="sources-and-further-reading">Sources and further reading</h2>
<ul>
<li><a href="https://doi.org/10.1137/1109020">Nadaraya, <em>On Estimating Regression</em></a>: the 1964 two-page paper introducing one side of the estimator now bearing Nadaraya and Watson’s names.</li>
<li><a href="https://www.jstor.org/stable/25049340">Watson, <em>Smooth Regression Analysis</em></a>: the independent 1964 development of smooth regression by local weighting.</li>
<li><a href="https://arxiv.org/abs/1409.0473">Bahdanau, Cho, &amp; Bengio, <em>Neural Machine Translation by Jointly Learning to Align and Translate</em></a>: the neural-attention step that replaces one fixed context with learned soft alignment; Chapter 13 performs that harvest.</li>
</ul>
</section>
<section id="exercises" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercises">Exercises</h2>
<ol type="1">
<li><strong>(Pencil.)</strong> Prove that <a href="#eq-nadaraya-watson" class="quarto-xref">Equation&nbsp;<span>12.3</span></a> is a convex combination when <span class="math inline">\(\kappa_h\ge0\)</span> and its denominator is positive. Then prove that a scalar prediction lies in <span class="math inline">\([\min_i v_i,\max_i v_i]\)</span>. Which step fails for the OLS weights in <a href="#eq-ols-target-weights" class="quarto-xref">Equation&nbsp;<span>12.1</span></a>?</li>
<li><strong>(Pencil.)</strong> For keys <span class="math inline">\((-2,-1,0,1,2)\)</span>, derive the five OLS target weights at <span class="math inline">\(q=1.5\)</span> without using code. Verify that they sum to one, identify the negative weight, and construct a second target vector for which OLS leaves the target range.</li>
<li><strong>(Code.)</strong> Split a fresh noisy sample from this chapter’s function into training, validation, and sealed test sets. Select <span class="math inline">\(h\)</span> on validation data, report the test MSE once, and compare your selected curve with the synthetic-truth grid minimum above. Explain why the two procedures need not select the same bandwidth.</li>
<li><strong>(Pencil + code.)</strong> Derive <a href="#eq-bandwidth-temperature" class="quarto-xref">Equation&nbsp;<span>12.5</span></a>. Then use keys <span class="math inline">\([0,0,1]\)</span>, query 0, and successively smaller positive bandwidths. What weights does stable softmax assign to the exact nearest-key tie, and why is <span class="math inline">\(h=0\)</span> still invalid?</li>
<li><strong>(Code.)</strong> Extend <code>gaussian_attention</code> to two-dimensional keys whose coordinates have very different units. Compare the attention map before and after standardizing each feature using training-set statistics. What does this reveal about the metric hidden inside a fixed kernel?</li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/shakeri-lab\.github\.io\/dl-book\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../chapters/part3/11-encoder-decoder.html" class="pagination-link" aria-label="Encoder–Decoder, Teacher Forcing, Beam Search">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Encoder–Decoder, Teacher Forcing, Beam Search</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/part4/13-attention.html" class="pagination-link" aria-label="Attention: Making the Kernel Learnable">
        <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Attention: Making the Kernel Learnable</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Heman Shakeri · Text CC BY-NC-SA 4.0 · Code MIT · School of Data Science, University of Virginia</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/Shakeri-Lab/dl-book/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Companion to <a href="https://shakeri-lab.github.io/dl-course-site/">DS 6050 Deep Learning</a></p>
</div>
  </div>
</footer>




</body></html>