<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>13&nbsp; Attention: Making the Kernel Learnable – Deep Learning: Making It Learnable</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/part4/14-self-attention-transformer.html" rel="next">
<link href="../../chapters/part4/12-kernel-regression.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-c90f29e1247290e1dfbeb1da338aa877.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>
  // Book math macros — keep in sync with tex/macros.tex (PDF path).
  // MathJax reads this config because it is defined before the MathJax
  // script loads (Quarto places include-in-header above its math script).
  window.MathJax = {
    tex: {
      macros: {
        E: "\\mathbb{E}",
        Ex: "\\operatorname{E}",
        var: "\\operatorname{Var}",
        cov: "\\operatorname{Cov}",
        imp: "\\Rightarrow",
        argmax: "\\operatorname*{arg\\,max}",
        argmin: "\\operatorname*{arg\\,min}",
        norm: ["\\left\\lVert#1\\right\\rVert", 1],
        vect: ["\\mathbf{#1}", 1],
        matr: ["\\mathbf{#1}", 1],
        R: "\\mathbb{R}",
        dd: "\\mathrm{d}",
        loss: "\\mathcal{L}"
      }
    }
  };
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/part4/12-kernel-regression.html">IV · Attention: Learning the Similarity</a></li><li class="breadcrumb-item"><a href="../../chapters/part4/13-attention.html"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Attention: Making the Kernel Learnable</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Deep Learning: Making It Learnable</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/Shakeri-Lab/dl-book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">I · From Lines to Networks</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/01-linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Linear Regression, the Mother Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/02-logistic-softmax.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Linear Models that Classify: Logistic and Softmax</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/03-nonlinearity-mlp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Nonlinearity and the MLP</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/04-training-loss-sgd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Training: Loss and Stochastic Gradient Descent</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/05-backpropagation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Backpropagation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/06-generalization-inductive-bias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">When It Fails: Generalization in Pictures, and Inductive Bias</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">II · Vision: Learning the Filters</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/07-filters-convolution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Filters and Convolution (Fixed Kernels)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/08-cnn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">CNNs: Making the Filters Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/09-modern-cnns-transfer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Modern CNNs and Transfer Learning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">III · Sequences</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part3/10-sequences-rnn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Sequences and Recurrence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part3/11-encoder-decoder.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Encoder–Decoder, Teacher Forcing, Beam Search</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">IV · Attention: Learning the Similarity</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/12-kernel-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Kernel Regression: Attention Before It Was Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/13-attention.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Attention: Making the Kernel Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/14-self-attention-transformer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Self-Attention and the Transformer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/15-bert-pretraining.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">The BERT Moment: Pretraining as the New Regime</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/16-vit-scaling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Vision Transformers and Scaling Laws</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">V · The Pretrained Era</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/17-peft-quantization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Adapting Pretrained Models: Prompting, PEFT, Quantization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/18-alignment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Alignment and RL Fine-Tuning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/19-generative.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Generative Models: From PCA to Diffusion</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a1-linear-algebra.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Linear Algebra and the SVD</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a2-tensors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Tensors in Practice</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a3-precision-performance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Numerical Precision and Hardware Efficiency</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a4-notation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Notation</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-scores-to-weights-machine-one-more-time" id="toc-the-scores-to-weights-machine-one-more-time" class="nav-link active" data-scroll-target="#the-scores-to-weights-machine-one-more-time"><span class="header-section-number">13.1</span> The scores-to-weights machine, one more time</a></li>
  <li><a href="#additive-attention-learn-the-comparison-itself" id="toc-additive-attention-learn-the-comparison-itself" class="nav-link" data-scroll-target="#additive-attention-learn-the-comparison-itself"><span class="header-section-number">13.2</span> Additive attention: learn the comparison itself</a></li>
  <li><a href="#scaled-dot-product-learn-the-spaces-simplify-the-score" id="toc-scaled-dot-product-learn-the-spaces-simplify-the-score" class="nav-link" data-scroll-target="#scaled-dot-product-learn-the-spaces-simplify-the-score"><span class="header-section-number">13.3</span> Scaled dot product: learn the spaces, simplify the score</a>
  <ul class="collapse">
  <li><a href="#why-divide-by-sqrtd_k" id="toc-why-divide-by-sqrtd_k" class="nav-link" data-scroll-target="#why-divide-by-sqrtd_k">Why divide by <span class="math inline">\(\sqrt{d_k}\)</span>?</a></li>
  </ul></li>
  <li><a href="#mask-before-softmax-and-mask-the-right-thing" id="toc-mask-before-softmax-and-mask-the-right-thing" class="nav-link" data-scroll-target="#mask-before-softmax-and-mask-the-right-thing"><span class="header-section-number">13.4</span> Mask before softmax, and mask the right thing</a></li>
  <li><a href="#return-to-chapter-11s-date-task" id="toc-return-to-chapter-11s-date-task" class="nav-link" data-scroll-target="#return-to-chapter-11s-date-task"><span class="header-section-number">13.5</span> Return to Chapter 11’s date task</a>
  <ul class="collapse">
  <li><a href="#put-the-learned-read-inside-the-recurrent-decoder" id="toc-put-the-learned-read-inside-the-recurrent-decoder" class="nav-link" data-scroll-target="#put-the-learned-read-inside-the-recurrent-decoder">Put the learned read inside the recurrent decoder</a></li>
  <li><a href="#the-matched-schedule-rematch" id="toc-the-matched-schedule-rematch" class="nav-link" data-scroll-target="#the-matched-schedule-rematch">The matched-schedule rematch</a></li>
  </ul></li>
  <li><a href="#one-learned-view-for-now" id="toc-one-learned-view-for-now" class="nav-link" data-scroll-target="#one-learned-view-for-now"><span class="header-section-number">13.6</span> One learned view, for now</a></li>
  <li><a href="#the-bottleneck-that-remains" id="toc-the-bottleneck-that-remains" class="nav-link" data-scroll-target="#the-bottleneck-that-remains"><span class="header-section-number">13.7</span> The bottleneck that remains</a></li>
  <li><a href="#okay-so" id="toc-okay-so" class="nav-link" data-scroll-target="#okay-so"><span class="header-section-number">13.8</span> Okay, so —</a></li>
  <li><a href="#sources-and-further-reading" id="toc-sources-and-further-reading" class="nav-link" data-scroll-target="#sources-and-further-reading">Sources and further reading</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/Shakeri-Lab/dl-book/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/part4/12-kernel-regression.html">IV · Attention: Learning the Similarity</a></li><li class="breadcrumb-item"><a href="../../chapters/part4/13-attention.html"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Attention: Making the Kernel Learnable</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-13-attention" class="quarto-section-identifier"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Attention: Making the Kernel Learnable</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<!-- lecture-source:
     m08_lecture-8-2-attention-mechanism-part-2_oq92FA-_xa4.txt
     [coding]_m08_lecture-8-3-implementing-attention-in-seq2seq-de_nDcFkXXFzJs.txt
     (spine via ds6050_08_attention/MODULE_NOTES.md; S04-S08 scene compositions)
     seeds: sources/8.1-Attention.tex (§Additive Attention through §Where
            Cross-Attention Fits), sources/Bridge_to_attention.tex (§Part 4,
            §Alignment Matrix, §Query/Keys/Values)
     primary sources: Bahdanau et al. 2014/2015; Luong et al. 2015;
                      Vaswani et al. 2017
     provenance note: the date generator and split are copied byte-for-byte from
     the book-original Chapter 11 cell. The attention code is an independent
     implementation from the lecture equations and Chapter 11 architecture.
     D2L-like reference implementations in the source snapshot were omitted under
     sources/README.md and were not used. The coding lecture omitted the
     source-padding attention mask; this chapter adds it as a correctness repair.
     Self-attention, causal masking, and the full multi-head implementation wait
     for Chapter 14. -->
<p>Chapter 12 built the whole attention operator except for one piece. It had a query, a bank of keys and values, a score for every query–key pair, softmax weights, and a weighted read. But Euclidean distance decided what counted as similar. The task could tune the bandwidth; it could not invent a better notion of relevance.</p>
<p>Chapter 11 left us a more pointed promise: <strong>hard address, learned content</strong>. An embedding can learn what lives at row 17, but fetching row 17 is still a rigid indexing operation. Chapter 2 told us how to soften that hard choice. Replace the single address with a differentiable distribution over addresses, let the loss send blame through every score, and learn which memory locations deserve weight. A differentiable lookup, Chapter 2 promised, is precisely attention. The promise comes due here.</p>
<!-- NOVEL: needs sign-off - opening preview of the seeded date-rematch results. -->
<p>The result is visible in the date task before we name all its parts. For the fixed validation source</p>
<pre class="text"><code>may 17, 1971  -&gt;  1971-05-17</code></pre>
<p>the trained decoder emits the year first even though those four characters sit at the end of the source. Across the fixed 400-example validation audit, its first four attention rows place <strong>97.5%</strong> of their mass on the four contextual encoder states indexed by the source-year characters. When the example above emits its second character, <strong>9</strong>, the largest weight is 0.856 on the state indexed by the source’s 9; when it emits <strong>7</strong>, the largest weight is 0.985 on the state indexed by the 7 in the year region. Those weights were not supervised as alignments. The date loss taught the model where useful information lived.</p>
<!-- /NOVEL -->
<section id="the-scores-to-weights-machine-one-more-time" class="level2" data-number="13.1">
<h2 data-number="13.1" class="anchored" data-anchor-id="the-scores-to-weights-machine-one-more-time"><span class="header-section-number">13.1</span> The scores-to-weights machine, one more time</h2>
<p>Let the encoder retain its full memory</p>
<p><span class="math display">\[
\matr{H}=[\vect{h}_1,\ldots,\vect{h}_n]^\top
\in\mathbb{R}^{n\times d_e}.
\]</span></p>
<p>At decoder step <span class="math inline">\(t\)</span>, use the previous decoder hidden state <span class="math inline">\(\vect{s}_{t-1}\in\mathbb{R}^{d_d}\)</span> as the query. A learned compatibility function <span class="math inline">\(a_\theta\)</span> produces one score per source position:</p>
<p><span class="math display">\[
e_{t,i}=a_\theta(\vect{s}_{t-1},\vect{h}_i).
\]</span></p>
<p>For each padded batch item <span class="math inline">\(b\)</span>, let <span class="math inline">\(M_{b,i}=0\)</span> at real source positions and <span class="math inline">\(M_{b,i}=-\infty\)</span> at padding. Suppress the batch index below. Then</p>
<p><span id="eq-learned-cross-attention"><span class="math display">\[
\alpha_{t,i}
=\operatorname{softmax}_i(e_{t,i}+M_i),
\qquad
\vect{c}_t=\sum_{i=1}^{n}\alpha_{t,i}\vect{h}_i.
\tag{13.1}\]</span></span></p>
<p>This is Chapter 12’s fixed matrix <span class="math inline">\(\matr{A}\matr{V}\)</span> with a learned score. It is also Chapter 2’s <strong>scores <span class="math inline">\(\rightarrow\)</span> weights</strong> machine in exactly the form that chapter advertised. A hard source-position choice would use argmax and one-hot indexing. The soft weights move continuously when the scores move, so backpropagation can tell the scorer how each valid address affected the loss. We have <strong>softened the hard</strong>.</p>
<p>Because the query comes from the decoder and the memory comes from the encoder, this is <strong>cross-attention</strong>. It bridges two sequences. The model still initializes the decoder from the encoder’s final state, but that fixed bridge is no longer the only path from source to output: every decoder step receives its own context <span class="math inline">\(\vect{c}_t\)</span>. Chapters 10 and 11 called the old handoff a <strong>finite-state bottleneck</strong>. Chapter 12 kept the memory bank; this chapter completes that relay by learning its access rule.</p>
<p>Chapter 8 made one other promise. A CNN buys global sight by stacking local operations until its receptive field spans the input. One cross-attention read can score every encoder position in a single layer. It buys global access directly, paying for all query–key comparisons and, for now, for the RNNs that created those states sequentially.</p>
</section>
<section id="additive-attention-learn-the-comparison-itself" class="level2" data-number="13.2">
<h2 data-number="13.2" class="anchored" data-anchor-id="additive-attention-learn-the-comparison-itself"><span class="header-section-number">13.2</span> Additive attention: learn the comparison itself</h2>
<p>The most literal answer to “make similarity learnable” is a small neural network. Choose an alignment width <span class="math inline">\(d_a\)</span>. For one decoder query and one encoder state,</p>
<p><span id="eq-additive-attention"><span class="math display">\[
e_{t,i}
=\vect{v}_a^\top
\tanh\!\left(
  \matr{W}_q\vect{s}_{t-1}
  +\matr{W}_k\vect{h}_i
\right),
\tag{13.2}\]</span></span></p>
<p>where</p>
<p><span class="math display">\[
\matr{W}_q\in\mathbb{R}^{d_a\times d_d},
\qquad
\matr{W}_k\in\mathbb{R}^{d_a\times d_e},
\qquad
\vect{v}_a\in\mathbb{R}^{d_a}.
\]</span></p>
<p>The two projections put objects of different native sizes into one alignment space. The tanh creates match features, and <span class="math inline">\(\vect{v}_a\)</span> selects which of those features matter for the scalar score. The same parameters are reused for every decoder step <span class="math inline">\(t\)</span> and source position <span class="math inline">\(i\)</span>. Remember Chapter 7’s sliding filter: one learned rule, applied everywhere. Attention shares a compatibility rule across pairs.</p>
<p>For a batch, let <span class="math inline">\(\matr{S}_{t-1}\in\mathbb{R}^{B\times1\times d_d}\)</span> collect the queries. The row-major shapes make the broadcasting explicit:</p>
<p><span class="math display">\[
\matr{S}_{t-1}\matr{W}_q^\top: (B,1,d_a),
\qquad
\matr{H}\matr{W}_k^\top: (B,n,d_a).
\]</span></p>
<p>Their sum produces <span class="math inline">\((B,n,d_a)\)</span> match features. Reduction by <span class="math inline">\(\vect{v}_a\)</span> produces <span class="math inline">\((B,n)\)</span> scores, softmax runs over the <span class="math inline">\(n\)</span> source positions, and the weighted read returns a <span class="math inline">\((B,d_e)\)</span> context. That last axis choice is not bookkeeping: softmax over the wrong dimension answers the wrong question.</p>
<p>The lecture’s scene freezes one simple parameter snapshot so we can watch the arithmetic. With identity projections and an all-ones selector, three source states receive scores <span class="math inline">\((1.015,1.562,1.124)\)</span> and therefore weights <span class="math inline">\((0.260,0.450,0.290)\)</span>:</p>
<div id="cell-fig-additive-scorer" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Figure: the additive scorer and a three-key numerical snapshot</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> __future__ <span class="im">import</span> annotations</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> math</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> random</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib.patches <span class="im">import</span> FancyBboxPatch</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.nn <span class="im">as</span> nn</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.nn.functional <span class="im">as</span> F</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>torch.manual_seed(<span class="dv">6050</span>)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>query_snapshot <span class="op">=</span> np.array([<span class="fl">0.5</span>, <span class="fl">0.5</span>, <span class="fl">0.2</span>, <span class="op">-</span><span class="fl">0.1</span>])</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>key_snapshot <span class="op">=</span> np.array([</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>    [<span class="op">-</span><span class="fl">0.3</span>, <span class="fl">0.1</span>, <span class="fl">0.2</span>, <span class="fl">0.0</span>],</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    [<span class="fl">0.6</span>, <span class="fl">0.5</span>, <span class="fl">0.1</span>, <span class="op">-</span><span class="fl">0.2</span>],</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>    [<span class="fl">0.0</span>, <span class="op">-</span><span class="fl">0.4</span>, <span class="fl">0.3</span>, <span class="fl">0.2</span>],</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>snapshot_scores <span class="op">=</span> np.tanh(query_snapshot <span class="op">+</span> key_snapshot).<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>snapshot_weights <span class="op">=</span> np.exp(snapshot_scores <span class="op">-</span> snapshot_scores.<span class="bu">max</span>())</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>snapshot_weights <span class="op">/=</span> snapshot_weights.<span class="bu">sum</span>()</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="fl">7.5</span>, <span class="fl">3.0</span>),</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>                         gridspec_kw<span class="op">=</span>{<span class="st">"width_ratios"</span>: [<span class="fl">1.35</span>, <span class="dv">1</span>]})</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> axes[<span class="dv">0</span>]</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>ax.set_xlim(<span class="dv">0</span>, <span class="dv">10</span>)<span class="op">;</span> ax.set_ylim(<span class="dv">0</span>, <span class="dv">5</span>)<span class="op">;</span> ax.axis(<span class="st">"off"</span>)</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> stage_box(x: <span class="bu">float</span>, y: <span class="bu">float</span>, label: <span class="bu">str</span>, color: <span class="bu">str</span>,</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>              width: <span class="bu">float</span> <span class="op">=</span> <span class="fl">1.25</span>) <span class="op">-&gt;</span> <span class="va">None</span>:</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>    box <span class="op">=</span> FancyBboxPatch(</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>        (x <span class="op">-</span> width <span class="op">/</span> <span class="dv">2</span>, y <span class="op">-</span> <span class="fl">0.36</span>), width, <span class="fl">0.72</span>,</span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>        boxstyle<span class="op">=</span><span class="st">"round,pad=0.06"</span>, facecolor<span class="op">=</span>color,</span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>        edgecolor<span class="op">=</span><span class="st">"#232D4B"</span>, linewidth<span class="op">=</span><span class="fl">1.1</span>,</span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>    ax.add_patch(box)</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>    ax.text(x, y, label, ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>stage_box(<span class="fl">0.9</span>, <span class="fl">3.7</span>, <span class="vs">r"</span><span class="dv">$</span><span class="vs">s_{t-1}</span><span class="dv">$</span><span class="vs">"</span>, <span class="st">"#F9DCBF"</span>)</span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a>stage_box(<span class="fl">0.9</span>, <span class="fl">1.5</span>, <span class="vs">r"</span><span class="dv">$</span><span class="vs">h_i</span><span class="dv">$</span><span class="vs">"</span>, <span class="st">"#DCEAF7"</span>)</span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a>stage_box(<span class="fl">3.0</span>, <span class="fl">3.7</span>, <span class="vs">r"</span><span class="dv">$</span><span class="vs">W_q</span><span class="dv">$</span><span class="vs">"</span>, <span class="st">"#F9DCBF"</span>)</span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a>stage_box(<span class="fl">3.0</span>, <span class="fl">1.5</span>, <span class="vs">r"</span><span class="dv">$</span><span class="vs">W_k</span><span class="dv">$</span><span class="vs">"</span>, <span class="st">"#DCEAF7"</span>)</span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a>stage_box(<span class="fl">5.0</span>, <span class="fl">2.6</span>, <span class="st">"+"</span>, <span class="st">"#F4F4EF"</span>, <span class="fl">0.8</span>)</span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a>stage_box(<span class="fl">6.7</span>, <span class="fl">2.6</span>, <span class="st">"tanh"</span>, <span class="st">"#E8E3F2"</span>)</span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a>stage_box(<span class="fl">8.3</span>, <span class="fl">2.6</span>, <span class="vs">r"</span><span class="dv">$</span><span class="vs">v_a</span><span class="dv">^</span><span class="ch">\t</span><span class="vs">op</span><span class="dv">$</span><span class="vs">"</span>, <span class="st">"#FCE8B2"</span>)</span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a>ax.text(<span class="fl">9.6</span>, <span class="fl">2.6</span>, <span class="vs">r"</span><span class="dv">$</span><span class="vs">e_{t,i}</span><span class="dv">$</span><span class="vs">"</span>, ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"center"</span>,</span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span><span class="st">"#B45309"</span>, fontsize<span class="op">=</span><span class="dv">11</span>)</span>
<span id="cb2-49"><a href="#cb2-49" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> start, end <span class="kw">in</span> [</span>
<span id="cb2-50"><a href="#cb2-50" aria-hidden="true" tabindex="-1"></a>    ((<span class="fl">1.55</span>, <span class="fl">3.7</span>), (<span class="fl">2.35</span>, <span class="fl">3.7</span>)), ((<span class="fl">1.55</span>, <span class="fl">1.5</span>), (<span class="fl">2.35</span>, <span class="fl">1.5</span>)),</span>
<span id="cb2-51"><a href="#cb2-51" aria-hidden="true" tabindex="-1"></a>    ((<span class="fl">3.65</span>, <span class="fl">3.7</span>), (<span class="fl">4.55</span>, <span class="fl">2.85</span>)), ((<span class="fl">3.65</span>, <span class="fl">1.5</span>), (<span class="fl">4.55</span>, <span class="fl">2.35</span>)),</span>
<span id="cb2-52"><a href="#cb2-52" aria-hidden="true" tabindex="-1"></a>    ((<span class="fl">5.4</span>, <span class="fl">2.6</span>), (<span class="fl">6.08</span>, <span class="fl">2.6</span>)), ((<span class="fl">7.32</span>, <span class="fl">2.6</span>), (<span class="fl">7.68</span>, <span class="fl">2.6</span>)),</span>
<span id="cb2-53"><a href="#cb2-53" aria-hidden="true" tabindex="-1"></a>    ((<span class="fl">8.95</span>, <span class="fl">2.6</span>), (<span class="fl">9.25</span>, <span class="fl">2.6</span>)),</span>
<span id="cb2-54"><a href="#cb2-54" aria-hidden="true" tabindex="-1"></a>]:</span>
<span id="cb2-55"><a href="#cb2-55" aria-hidden="true" tabindex="-1"></a>    ax.annotate(<span class="st">""</span>, end, start,</span>
<span id="cb2-56"><a href="#cb2-56" aria-hidden="true" tabindex="-1"></a>                arrowprops<span class="op">=</span>{<span class="st">"arrowstyle"</span>: <span class="st">"-&gt;"</span>, <span class="st">"color"</span>: <span class="st">"#4A5568"</span>, <span class="st">"lw"</span>: <span class="fl">1.2</span>})</span>
<span id="cb2-57"><a href="#cb2-57" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"One shared learned scorer"</span>, fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb2-58"><a href="#cb2-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-59"><a href="#cb2-59" aria-hidden="true" tabindex="-1"></a>labels <span class="op">=</span> [<span class="vs">r"</span><span class="dv">$</span><span class="vs">h_1</span><span class="dv">$</span><span class="vs">"</span>, <span class="vs">r"</span><span class="dv">$</span><span class="vs">h_2</span><span class="dv">$</span><span class="vs">"</span>, <span class="vs">r"</span><span class="dv">$</span><span class="vs">h_3</span><span class="dv">$</span><span class="vs">"</span>]</span>
<span id="cb2-60"><a href="#cb2-60" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].bar(labels, snapshot_weights,</span>
<span id="cb2-61"><a href="#cb2-61" aria-hidden="true" tabindex="-1"></a>            color<span class="op">=</span>[<span class="st">"#A9B7C9"</span>, <span class="st">"#E57200"</span>, <span class="st">"#C99456"</span>])</span>
<span id="cb2-62"><a href="#cb2-62" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, (score, weight) <span class="kw">in</span> <span class="bu">enumerate</span>(<span class="bu">zip</span>(snapshot_scores, snapshot_weights)):</span>
<span id="cb2-63"><a href="#cb2-63" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">1</span>].text(i, weight <span class="op">+</span> <span class="fl">0.018</span>, <span class="ss">f"</span><span class="sc">{</span>weight<span class="sc">:.3f}</span><span class="ss">"</span>,</span>
<span id="cb2-64"><a href="#cb2-64" aria-hidden="true" tabindex="-1"></a>                 ha<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb2-65"><a href="#cb2-65" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">1</span>].text(i, <span class="fl">0.025</span>, <span class="ss">f"$e=</span><span class="sc">{</span>score<span class="sc">:.3f}</span><span class="ss">$"</span>,</span>
<span id="cb2-66"><a href="#cb2-66" aria-hidden="true" tabindex="-1"></a>                 ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"bottom"</span>, fontsize<span class="op">=</span><span class="dv">8</span>, rotation<span class="op">=</span><span class="dv">90</span>, color<span class="op">=</span><span class="st">"white"</span>)</span>
<span id="cb2-67"><a href="#cb2-67" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].<span class="bu">set</span>(ylabel<span class="op">=</span><span class="st">"softmax weight"</span>, ylim<span class="op">=</span>(<span class="dv">0</span>, <span class="fl">0.53</span>),</span>
<span id="cb2-68"><a href="#cb2-68" aria-hidden="true" tabindex="-1"></a>            title<span class="op">=</span><span class="st">"Scores decide the read"</span>)</span>
<span id="cb2-69"><a href="#cb2-69" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb2-70"><a href="#cb2-70" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-additive-scorer" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-additive-scorer-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="13-attention_files/figure-html/fig-additive-scorer-output-1.png" width="710" height="278" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-additive-scorer-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.1: Additive attention learns a compatibility function. Query and key enter separate projections, their alignment features interact through tanh, and a learned selector reduces those features to one score. The right panel freezes one parameter setting to show the resulting scores-to-weights calculation; it is arithmetic, not a trained result.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>“Learned kernel” is an analogy
</div>
</div>
<div class="callout-body-container callout-body">
<p>Exponentiating a learned score and normalizing it reproduces the Nadaraya–Watson algebra. It does not make every attention score a classical kernel. Separate query and key projections can make <span class="math inline">\(a_\theta(q,k)\)</span> asymmetric and not positive semidefinite. What survives exactly is the operational pattern: compare <span class="math inline">\(\rightarrow\)</span> normalize <span class="math inline">\(\rightarrow\)</span> mix.</p>
</div>
</div>
</section>
<section id="scaled-dot-product-learn-the-spaces-simplify-the-score" class="level2" data-number="13.3">
<h2 data-number="13.3" class="anchored" data-anchor-id="scaled-dot-product-learn-the-spaces-simplify-the-score"><span class="header-section-number">13.3</span> Scaled dot product: learn the spaces, simplify the score</h2>
<p>For <span class="math inline">\(m\)</span> decoder queries, additive attention is vectorized, but it forms a <span class="math inline">\((B,m,n,d_a)\)</span> intermediate, applies an elementwise tanh, and reduces it. Dense matrix multiplication has a simpler computational path. Chapter 1 introduced the dot product as a similarity score against a template. Here the key is the template, and training learns the space in which that comparison is useful.</p>
<p>The lecture first walks one four-dimensional query past three keys. Its raw dot products are <span class="math inline">\((1.10,-0.60,0.15)\)</span>. Since <span class="math inline">\(\sqrt{4}=2\)</span>, scaling gives <span class="math inline">\((0.55,-0.30,0.075)\)</span>, and softmax gives <span class="math inline">\((0.488,0.209,0.303)\)</span>:</p>
<div id="scaled-dot-snapshot" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code: one query through dot product, scaling, and softmax</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>query_walk <span class="op">=</span> torch.tensor([<span class="fl">0.9</span>, <span class="op">-</span><span class="fl">0.3</span>, <span class="fl">0.2</span>, <span class="fl">0.6</span>])</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>key_walk <span class="op">=</span> torch.tensor([</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    [<span class="fl">0.8</span>, <span class="op">-</span><span class="fl">0.2</span>, <span class="fl">0.1</span>, <span class="fl">0.5</span>],</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    [<span class="op">-</span><span class="fl">0.5</span>, <span class="fl">0.9</span>, <span class="fl">0.0</span>, <span class="fl">0.2</span>],</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    [<span class="fl">0.3</span>, <span class="fl">0.0</span>, <span class="fl">0.6</span>, <span class="op">-</span><span class="fl">0.4</span>],</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>raw_walk <span class="op">=</span> key_walk <span class="op">@</span> query_walk</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>scaled_walk <span class="op">=</span> raw_walk <span class="op">/</span> math.sqrt(query_walk.numel())</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>weight_walk <span class="op">=</span> torch.softmax(scaled_walk, dim<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"raw scores:"</span>, raw_walk.numpy())</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"scaled scores:"</span>, scaled_walk.numpy())</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"weights:"</span>, weight_walk.numpy(), <span class="st">"sum:"</span>, weight_walk.<span class="bu">sum</span>().item())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>raw scores: [ 1.0999999 -0.6        0.15     ]
scaled scores: [ 0.54999995 -0.3         0.075     ]
weights: [0.4879715  0.20856632 0.3034622 ] sum: 1.0</code></pre>
</div>
</div>
<p>Now let raw decoder features <span class="math inline">\(\matr{D}\in\mathbb{R}^{B\times m\times d_d}\)</span> and encoder memory <span class="math inline">\(\matr{H}\in\mathbb{R}^{B\times n\times d_e}\)</span> enter learned projections:</p>
<p><span class="math display">\[
\begin{aligned}
\matr{Q}&amp;=\matr{D}\matr{W}_Q,
&amp;\matr{W}_Q&amp;\in\mathbb{R}^{d_d\times d_k},\\
\matr{K}&amp;=\matr{H}\matr{W}_K,
&amp;\matr{W}_K&amp;\in\mathbb{R}^{d_e\times d_k},\\
\matr{V}&amp;=\matr{H}\matr{W}_V,
&amp;\matr{W}_V&amp;\in\mathbb{R}^{d_e\times d_v}.
\end{aligned}
\]</span></p>
<p>The resulting tensors have shapes</p>
<p><span class="math display">\[
\matr{Q}\in\mathbb{R}^{B\times m\times d_k},\qquad
\matr{K}\in\mathbb{R}^{B\times n\times d_k},\qquad
\matr{V}\in\mathbb{R}^{B\times n\times d_v}.
\]</span></p>
<p>Only the projected query and key widths must agree. The raw encoder and decoder widths need not. Let <span class="math inline">\(\matr{M}\in\mathbb{R}^{B\times1\times n}\)</span> broadcast across queries. <strong>Scaled dot-product attention</strong> is</p>
<p><span id="eq-scaled-dot-product"><span class="math display">\[
\operatorname{Attention}(\matr{Q},\matr{K},\matr{V})
=\operatorname{softmax}\!\left(
  \frac{\matr{Q}\matr{K}^{\top}}{\sqrt{d_k}}+\matr{M}
\right)\matr{V},
\tag{13.3}\]</span></span></p>
<p>where <span class="math inline">\(\matr{K}^{\top}\)</span> transposes the last two axes within each batch. Softmax runs over the last, key-position axis. The hot path is two dense products: <span class="math inline">\(\matr{Q}\matr{K}^{\top}\)</span> and <span class="math inline">\(\matr{A}\matr{V}\)</span>. Additive attention remains useful and accelerator-compatible; scaled dot product simply maps more directly to the matrix operations modern numerical libraries optimize heavily. Appendix C turns that intuition into a conditional performance model—dense products can earn high arithmetic intensity through reuse, but shapes, data movement, implementation, and hardware decide the actual regime (<a href="../appendices/a3-precision-performance.html" class="quarto-xref"><span>Appendix C</span></a>).</p>
<p>Luong and colleagues compared unscaled dot, general, and concat scores in recurrent translation. Vaswani and colleagues later introduced the <span class="math inline">\(1/\sqrt{d_k}\)</span> scaling in the Transformer formulation. The mechanisms belong in one conceptual family, not a single inevitable historical derivation.</p>
<p>The dot product is not magically semantic. <span class="math inline">\(\matr{W}_Q\)</span> and <span class="math inline">\(\matr{W}_K\)</span> learn which features to compare, including their magnitudes, while the surrounding RNN has already built nonlinear sequence features. In Chapter 14, a feed-forward network will help provide that nonlinear feature transformation after recurrence disappears.</p>
<section id="why-divide-by-sqrtd_k" class="level3">
<h3 class="anchored" data-anchor-id="why-divide-by-sqrtd_k">Why divide by <span class="math inline">\(\sqrt{d_k}\)</span>?</h3>
<p>Suppose, for the moment, that projected coordinates <span class="math inline">\(q_\ell\)</span> and <span class="math inline">\(k_\ell\)</span> are independent, mean zero, and variance one, and that their products are independent across coordinates. Then</p>
<p><span class="math display">\[
\E[\vect{q}^{\top}\vect{k}]=0,
\qquad
\var(\vect{q}^{\top}\vect{k})
=\sum_{\ell=1}^{d_k}\var(q_\ell k_\ell)=d_k.
\]</span></p>
<p>The score’s standard deviation grows as <span class="math inline">\(\sqrt{d_k}\)</span>. Dividing by that quantity returns the idealized variance to one. This is a variance-control rationale, not a promise that trained projections remain independent or unit variance.</p>
<!-- NOVEL: needs sign-off - seeded sqrt(d_k) variance/softmax audit and results. -->
<p>Let us test both the variance and what softmax sees. For each width, draw 20,000 queries and 16 independent keys per query:</p>
<div id="cell-fig-sqrt-d-audit" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code: audit score variance and softmax concentration versus width</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>scaling_gen <span class="op">=</span> torch.Generator().manual_seed(<span class="dv">6050132</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>scaling_rows <span class="op">=</span> []</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> width <span class="kw">in</span> (<span class="dv">8</span>, <span class="dv">32</span>, <span class="dv">128</span>, <span class="dv">512</span>):</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    raw_parts, raw_max_parts, scaled_max_parts <span class="op">=</span> [], [], []</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">20_000</span> <span class="op">//</span> <span class="dv">500</span>):</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>        q <span class="op">=</span> torch.randn(<span class="dv">500</span>, <span class="dv">1</span>, width, generator<span class="op">=</span>scaling_gen)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>        k <span class="op">=</span> torch.randn(<span class="dv">500</span>, <span class="dv">16</span>, width, generator<span class="op">=</span>scaling_gen)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>        raw <span class="op">=</span> (q <span class="op">*</span> k).<span class="bu">sum</span>(<span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>        raw_parts.append(raw.reshape(<span class="op">-</span><span class="dv">1</span>))</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>        raw_max_parts.append(torch.softmax(raw, dim<span class="op">=-</span><span class="dv">1</span>).<span class="bu">max</span>(<span class="op">-</span><span class="dv">1</span>).values)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>        scaled_max_parts.append(</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>            torch.softmax(raw <span class="op">/</span> math.sqrt(width), dim<span class="op">=-</span><span class="dv">1</span>).<span class="bu">max</span>(<span class="op">-</span><span class="dv">1</span>).values</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    raw_scores <span class="op">=</span> torch.cat(raw_parts)</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>    scaling_rows.append((</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>        width,</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>        raw_scores.var(unbiased<span class="op">=</span><span class="va">True</span>).item(),</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>        (raw_scores <span class="op">/</span> math.sqrt(width)).var(unbiased<span class="op">=</span><span class="va">True</span>).item(),</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>        torch.cat(raw_max_parts).mean().item(),</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>        torch.cat(scaled_max_parts).mean().item(),</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>    ))</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"d_k   raw var   scaled var   raw max-w   scaled max-w"</span>)</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> row <span class="kw">in</span> scaling_rows:</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>row[<span class="dv">0</span>]<span class="sc">:3d}</span><span class="ss">   </span><span class="sc">{</span>row[<span class="dv">1</span>]<span class="sc">:8.3f}</span><span class="ss">   </span><span class="sc">{</span>row[<span class="dv">2</span>]<span class="sc">:10.3f}</span><span class="ss">   "</span></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"</span><span class="sc">{</span>row[<span class="dv">3</span>]<span class="sc">:9.3f}</span><span class="ss">   </span><span class="sc">{</span>row[<span class="dv">4</span>]<span class="sc">:12.3f}</span><span class="ss">"</span>)</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>scaling_array <span class="op">=</span> np.asarray(scaling_rows)</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="fl">7.3</span>, <span class="fl">3.0</span>), constrained_layout<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].plot(scaling_array[:, <span class="dv">0</span>], scaling_array[:, <span class="dv">1</span>], <span class="st">"o-"</span>,</span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>             color<span class="op">=</span><span class="st">"#E57200"</span>, label<span class="op">=</span><span class="st">"raw"</span>)</span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].plot(scaling_array[:, <span class="dv">0</span>], scaling_array[:, <span class="dv">2</span>], <span class="st">"s-"</span>,</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>             color<span class="op">=</span><span class="st">"#232D4B"</span>, label<span class="op">=</span><span class="vs">r"divided by </span><span class="dv">$\s</span><span class="vs">qrt{d_k}</span><span class="dv">$</span><span class="vs">"</span>)</span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].<span class="bu">set</span>(xscale<span class="op">=</span><span class="st">"log"</span>, yscale<span class="op">=</span><span class="st">"log"</span>, xlabel<span class="op">=</span><span class="vs">r"projected width </span><span class="dv">$</span><span class="vs">d_k</span><span class="dv">$</span><span class="vs">"</span>,</span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a>            ylabel<span class="op">=</span><span class="st">"empirical score variance"</span>, title<span class="op">=</span><span class="st">"Control the score scale"</span>)</span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].plot(scaling_array[:, <span class="dv">0</span>], scaling_array[:, <span class="dv">3</span>], <span class="st">"o-"</span>,</span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a>             color<span class="op">=</span><span class="st">"#E57200"</span>, label<span class="op">=</span><span class="st">"raw"</span>)</span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].plot(scaling_array[:, <span class="dv">0</span>], scaling_array[:, <span class="dv">4</span>], <span class="st">"s-"</span>,</span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a>             color<span class="op">=</span><span class="st">"#232D4B"</span>, label<span class="op">=</span><span class="st">"scaled"</span>)</span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].<span class="bu">set</span>(xscale<span class="op">=</span><span class="st">"log"</span>, ylim<span class="op">=</span>(<span class="dv">0</span>, <span class="dv">1</span>), xlabel<span class="op">=</span><span class="vs">r"projected width </span><span class="dv">$</span><span class="vs">d_k</span><span class="dv">$</span><span class="vs">"</span>,</span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a>            ylabel<span class="op">=</span><span class="st">"mean largest weight"</span>, title<span class="op">=</span><span class="st">"Control softmax concentration"</span>)</span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>d_k   raw var   scaled var   raw max-w   scaled max-w
  8      8.023        1.003       0.564          0.241
 32     32.142        1.004       0.779          0.246
128    127.985        1.000       0.889          0.246
512    510.347        0.997       0.944          0.247</code></pre>
</div>
<div class="cell-output cell-output-display">
<div id="fig-sqrt-d-audit" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sqrt-d-audit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="13-attention_files/figure-html/fig-sqrt-d-audit-output-2.png" width="712" height="299" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sqrt-d-audit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.2: The scaling argument under its stated random-feature assumptions. Left: raw dot-product variance grows with width, while division by the square root of the width keeps it near one. Right: without scaling, a 16-key softmax becomes nearly one-hot as width grows; scaling keeps its mean largest weight near 0.25. These are seeded synthetic draws about concentration, not a claim about every trained layer’s gradients.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Raw variance rises from <span class="math inline">\(8.02\)</span> to <span class="math inline">\(510.35\)</span> as <span class="math inline">\(d_k\)</span> grows from 8 to 512. Scaled variance stays between <span class="math inline">\(0.997\)</span> and <span class="math inline">\(1.004\)</span>. Over the same range, the average largest unscaled softmax weight climbs from <span class="math inline">\(0.564\)</span> to <span class="math inline">\(0.944\)</span>; the scaled value stays near <span class="math inline">\(0.24\)</span>. This is Chapter 2’s <strong>temperature dial</strong> returning with a dimension-dependent setting. Scaling corrects the dimension-induced spread; it does not normalize the vectors.</p>
<!-- /NOVEL -->
</section>
</section>
<section id="mask-before-softmax-and-mask-the-right-thing" class="level2" data-number="13.4">
<h2 data-number="13.4" class="anchored" data-anchor-id="mask-before-softmax-and-mask-the-right-thing"><span class="header-section-number">13.4</span> Mask before softmax, and mask the right thing</h2>
<p>Chapter 11 showed that padding can poison an encoder’s final state. Attention creates a third place to enforce sequence lengths: the score matrix. A padded key must not receive a merely mediocre score. It must be excluded before normalization. Setting its score to zero is wrong because <span class="math inline">\(\exp(0)=1\)</span> still earns weight.</p>
<!-- NOVEL: needs sign-off - independent mask implementation and all-masked guard. -->
<p>Here is an independently written scaled-dot operator. It accepts already projected queries, keys, and values, then audits a batch whose second example has two padded keys:</p>
<div id="cell-fig-padding-mask" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code: scaled dot-product attention with a source-padding mask</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> scaled_dot_attention(</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    queries: torch.Tensor,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    keys: torch.Tensor,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    values: torch.Tensor,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    key_is_valid: torch.Tensor,</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>) <span class="op">-&gt;</span> <span class="bu">tuple</span>[torch.Tensor, torch.Tensor]:</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Attend with Q:(B,m,d_k), K:(B,n,d_k), V:(B,n,d_v)."""</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> queries.ndim <span class="op">!=</span> <span class="dv">3</span> <span class="kw">or</span> keys.ndim <span class="op">!=</span> <span class="dv">3</span> <span class="kw">or</span> values.ndim <span class="op">!=</span> <span class="dv">3</span>:</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="st">"Q, K, and V must be three-dimensional"</span>)</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> queries.shape[<span class="op">-</span><span class="dv">1</span>] <span class="op">!=</span> keys.shape[<span class="op">-</span><span class="dv">1</span>]:</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="st">"projected Q and K widths must match"</span>)</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> keys.shape[:<span class="dv">2</span>] <span class="op">!=</span> values.shape[:<span class="dv">2</span>]:</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="st">"K and V must have the same batch and key axes"</span>)</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> key_is_valid.shape <span class="op">!=</span> keys.shape[:<span class="dv">2</span>] <span class="kw">or</span> <span class="kw">not</span> key_is_valid.<span class="bu">any</span>(dim<span class="op">=</span><span class="dv">1</span>).<span class="bu">all</span>():</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="st">"every example needs at least one valid key"</span>)</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>    scores <span class="op">=</span> queries <span class="op">@</span> keys.transpose(<span class="op">-</span><span class="dv">2</span>, <span class="op">-</span><span class="dv">1</span>) <span class="op">/</span> math.sqrt(keys.shape[<span class="op">-</span><span class="dv">1</span>])</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>    scores <span class="op">=</span> scores.masked_fill(<span class="op">~</span>key_is_valid[:, <span class="va">None</span>, :], <span class="op">-</span>torch.inf)</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>    weights <span class="op">=</span> torch.softmax(scores, dim<span class="op">=-</span><span class="dv">1</span>)</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> weights <span class="op">@</span> values, weights</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>mask_gen <span class="op">=</span> torch.Generator().manual_seed(<span class="dv">6050133</span>)</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>Q_demo <span class="op">=</span> torch.randn(<span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">4</span>, generator<span class="op">=</span>mask_gen)</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>K_demo <span class="op">=</span> torch.randn(<span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">4</span>, generator<span class="op">=</span>mask_gen)</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>V_demo <span class="op">=</span> torch.randn(<span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">3</span>, generator<span class="op">=</span>mask_gen)</span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>valid_demo <span class="op">=</span> torch.tensor([[<span class="va">True</span>, <span class="va">True</span>, <span class="va">True</span>, <span class="va">True</span>],</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>                           [<span class="va">True</span>, <span class="va">True</span>, <span class="va">False</span>, <span class="va">False</span>]])</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a>context_demo, mask_weights <span class="op">=</span> scaled_dot_attention(</span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>    Q_demo, K_demo, V_demo, valid_demo</span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> torch.allclose(</span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a>    mask_weights.<span class="bu">sum</span>(<span class="op">-</span><span class="dv">1</span>), torch.ones_like(mask_weights[..., <span class="dv">0</span>])</span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> torch.count_nonzero(mask_weights[<span class="dv">1</span>, :, <span class="dv">2</span>:]) <span class="op">==</span> <span class="dv">0</span></span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Q"</span>, <span class="bu">tuple</span>(Q_demo.shape), <span class="st">"K"</span>, <span class="bu">tuple</span>(K_demo.shape),</span>
<span id="cb7-36"><a href="#cb7-36" aria-hidden="true" tabindex="-1"></a>      <span class="st">"V"</span>, <span class="bu">tuple</span>(V_demo.shape), <span class="st">"A"</span>, <span class="bu">tuple</span>(mask_weights.shape),</span>
<span id="cb7-37"><a href="#cb7-37" aria-hidden="true" tabindex="-1"></a>      <span class="st">"AV"</span>, <span class="bu">tuple</span>(context_demo.shape))</span>
<span id="cb7-38"><a href="#cb7-38" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"maximum row-sum error:"</span>,</span>
<span id="cb7-39"><a href="#cb7-39" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>(mask_weights.<span class="bu">sum</span>(<span class="op">-</span><span class="dv">1</span>) <span class="op">-</span> <span class="dv">1</span>)<span class="sc">.</span><span class="bu">abs</span>()<span class="sc">.</span><span class="bu">max</span>()<span class="sc">.</span>item()<span class="sc">:.2e}</span><span class="ss">"</span>)</span>
<span id="cb7-40"><a href="#cb7-40" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"maximum padded weight:"</span>,</span>
<span id="cb7-41"><a href="#cb7-41" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>mask_weights[<span class="dv">1</span>, :, <span class="dv">2</span>:]<span class="sc">.</span><span class="bu">max</span>()<span class="sc">.</span>item()<span class="sc">:.1f}</span><span class="ss">"</span>)</span>
<span id="cb7-42"><a href="#cb7-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-43"><a href="#cb7-43" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">5.8</span>, <span class="fl">2.5</span>), constrained_layout<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb7-44"><a href="#cb7-44" aria-hidden="true" tabindex="-1"></a>shown <span class="op">=</span> mask_weights[<span class="dv">1</span>].detach().numpy()</span>
<span id="cb7-45"><a href="#cb7-45" aria-hidden="true" tabindex="-1"></a>image <span class="op">=</span> ax.imshow(shown, vmin<span class="op">=</span><span class="dv">0</span>, vmax<span class="op">=</span>shown.<span class="bu">max</span>(), cmap<span class="op">=</span><span class="st">"magma"</span>, aspect<span class="op">=</span><span class="st">"auto"</span>)</span>
<span id="cb7-46"><a href="#cb7-46" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> row <span class="kw">in</span> <span class="bu">range</span>(shown.shape[<span class="dv">0</span>]):</span>
<span id="cb7-47"><a href="#cb7-47" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> col <span class="kw">in</span> <span class="bu">range</span>(shown.shape[<span class="dv">1</span>]):</span>
<span id="cb7-48"><a href="#cb7-48" aria-hidden="true" tabindex="-1"></a>        label <span class="op">=</span> <span class="st">"PAD"</span> <span class="cf">if</span> col <span class="op">&gt;=</span> <span class="dv">2</span> <span class="cf">else</span> <span class="ss">f"</span><span class="sc">{</span>shown[row, col]<span class="sc">:.2f}</span><span class="ss">"</span></span>
<span id="cb7-49"><a href="#cb7-49" aria-hidden="true" tabindex="-1"></a>        ax.text(col, row, label, ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"center"</span>,</span>
<span id="cb7-50"><a href="#cb7-50" aria-hidden="true" tabindex="-1"></a>                color<span class="op">=</span><span class="st">"white"</span> <span class="cf">if</span> shown[row, col] <span class="op">&lt;</span> <span class="fl">0.65</span> <span class="op">*</span> shown.<span class="bu">max</span>() <span class="cf">else</span> <span class="st">"black"</span>)</span>
<span id="cb7-51"><a href="#cb7-51" aria-hidden="true" tabindex="-1"></a>ax.<span class="bu">set</span>(xticks<span class="op">=</span><span class="bu">range</span>(<span class="dv">4</span>), xticklabels<span class="op">=</span>[<span class="st">"key 1"</span>, <span class="st">"key 2"</span>, <span class="st">"pad"</span>, <span class="st">"pad"</span>],</span>
<span id="cb7-52"><a href="#cb7-52" aria-hidden="true" tabindex="-1"></a>       yticks<span class="op">=</span><span class="bu">range</span>(<span class="dv">2</span>), yticklabels<span class="op">=</span>[<span class="st">"query 1"</span>, <span class="st">"query 2"</span>],</span>
<span id="cb7-53"><a href="#cb7-53" aria-hidden="true" tabindex="-1"></a>       xlabel<span class="op">=</span><span class="st">"source/key position"</span>, title<span class="op">=</span><span class="st">"Mask source padding before softmax"</span>)</span>
<span id="cb7-54"><a href="#cb7-54" aria-hidden="true" tabindex="-1"></a>fig.colorbar(image, ax<span class="op">=</span>ax, label<span class="op">=</span><span class="st">"attention weight"</span>, fraction<span class="op">=</span><span class="fl">0.05</span>, pad<span class="op">=</span><span class="fl">0.04</span>)</span>
<span id="cb7-55"><a href="#cb7-55" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Q (2, 2, 4) K (2, 4, 4) V (2, 4, 3) A (2, 2, 4) AV (2, 2, 3)
maximum row-sum error: 0.00e+00
maximum padded weight: 0.0</code></pre>
</div>
<div class="cell-output cell-output-display">
<div id="fig-padding-mask" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-padding-mask-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="13-attention_files/figure-html/fig-padding-mask-output-2.png" width="567" height="251" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-padding-mask-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.3: A source-padding mask acts before softmax. The second example has only two real keys; its last two score cells are excluded and receive exactly zero weight. Cross-attention may read every real source position, so no causal triangle belongs here.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Three masks are not one mask
</div>
</div>
<div class="callout-body-container callout-body">
<p>The target loss mask says which output positions should not be graded; it remains good general hygiene but is dormant for this fixed-length ISO target. The cross-attention padding mask says which source positions do not exist. A causal mask says which future target positions may not be seen. Our recurrent decoder generates one step at a time and the entire source is already available, so the source-padding attention mask is the one exercised here. Chapter 14 will use causal masking inside decoder self-attention.</p>
<p>An all-masked row has no sensible distribution and would make softmax of all <span class="math inline">\(-\infty\)</span> undefined. Good hygiene is to assert that every example has at least one real key, as the function does above.</p>
</div>
</div>
<!-- /NOVEL -->
</section>
<section id="return-to-chapter-11s-date-task" class="level2" data-number="13.5">
<h2 data-number="13.5" class="anchored" data-anchor-id="return-to-chapter-11s-date-task"><span class="header-section-number">13.5</span> Return to Chapter 11’s date task</h2>
<p>The abstraction has earned a real rematch. We will change one architectural idea and keep the experimental contract fixed:</p>
<ul>
<li>the same date generator and duplicate-source rejection;</li>
<li>the same 8,000/500/500 train/validation/test split;</li>
<li>the same embedding width 32 and LSTM hidden width 128;</li>
<li>the same Adam learning rate <span class="math inline">\(10^{-3}\)</span>, batch size 128, 25 epochs, teacher forcing, gradient clip 5, and seed 6050;</li>
<li>the same first 400 unambiguous validation sources for every learning curve;</li>
<li>one final scalar audit on the same 437 unambiguous test sources.</li>
</ul>
<p>The generator and split below are deliberately byte-for-byte copies of Chapter 11. Changing them would end the running benchmark:</p>
<div id="date-data-rematch" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code: reconstruct Chapter 11’s sealed date benchmark</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> random, torch</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.nn <span class="im">as</span> nn</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.nn.functional <span class="im">as</span> F</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>MONTHS <span class="op">=</span> [<span class="st">"january"</span>, <span class="st">"february"</span>, <span class="st">"march"</span>, <span class="st">"april"</span>, <span class="st">"may"</span>, <span class="st">"june"</span>, <span class="st">"july"</span>,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>          <span class="st">"august"</span>, <span class="st">"september"</span>, <span class="st">"october"</span>, <span class="st">"november"</span>, <span class="st">"december"</span>]</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>DAYS <span class="op">=</span> <span class="bu">dict</span>(<span class="bu">zip</span>(MONTHS, [<span class="dv">31</span>, <span class="dv">28</span>, <span class="dv">31</span>, <span class="dv">30</span>, <span class="dv">31</span>, <span class="dv">30</span>, <span class="dv">31</span>, <span class="dv">31</span>, <span class="dv">30</span>, <span class="dv">31</span>, <span class="dv">30</span>, <span class="dv">31</span>]))</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> make_date(rng: random.Random) <span class="op">-&gt;</span> <span class="bu">tuple</span>[<span class="bu">str</span>, <span class="bu">str</span>]:</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>    mo <span class="op">=</span> rng.randrange(<span class="dv">12</span>)</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>    d <span class="op">=</span> rng.randrange(<span class="dv">1</span>, DAYS[MONTHS[mo]] <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> rng.randrange(<span class="dv">1950</span>, <span class="dv">2026</span>)</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>    iso <span class="op">=</span> <span class="ss">f"</span><span class="sc">{</span>y<span class="sc">:04d}</span><span class="ss">-</span><span class="sc">{</span>mo<span class="op">+</span><span class="dv">1</span><span class="sc">:02d}</span><span class="ss">-</span><span class="sc">{</span>d<span class="sc">:02d}</span><span class="ss">"</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>    style <span class="op">=</span> rng.random()</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> style <span class="op">&lt;</span> <span class="fl">0.35</span>:</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>        src <span class="op">=</span> <span class="ss">f"</span><span class="sc">{</span>MONTHS[mo]<span class="sc">}</span><span class="ss"> </span><span class="sc">{</span>d<span class="sc">}</span><span class="ss">, </span><span class="sc">{</span>y<span class="sc">}</span><span class="ss">"</span></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> style <span class="op">&lt;</span> <span class="fl">0.6</span>:</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>        src <span class="op">=</span> <span class="ss">f"</span><span class="sc">{</span>d<span class="sc">}</span><span class="ss"> </span><span class="sc">{</span>MONTHS[mo]<span class="sc">}</span><span class="ss"> </span><span class="sc">{</span>y<span class="sc">}</span><span class="ss">"</span></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> rng.random() <span class="op">&lt;</span> <span class="fl">0.7</span>:</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>        src <span class="op">=</span> <span class="ss">f"</span><span class="sc">{</span>mo<span class="op">+</span><span class="dv">1</span><span class="sc">:02d}</span><span class="ss">/</span><span class="sc">{</span>d<span class="sc">:02d}</span><span class="ss">/</span><span class="sc">{</span>y<span class="sc">}</span><span class="ss">"</span>            <span class="co"># US convention: mm/dd</span></span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>        src <span class="op">=</span> <span class="ss">f"</span><span class="sc">{</span>d<span class="sc">:02d}</span><span class="ss">/</span><span class="sc">{</span>mo<span class="op">+</span><span class="dv">1</span><span class="sc">:02d}</span><span class="ss">/</span><span class="sc">{</span>y<span class="sc">}</span><span class="ss">"</span>            <span class="co"># EU convention: dd/mm</span></span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> src, iso</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> random.Random(<span class="dv">6050</span>)</span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>pairs, seen_sources <span class="op">=</span> [], <span class="bu">set</span>()</span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a><span class="cf">while</span> <span class="bu">len</span>(pairs) <span class="op">&lt;</span> <span class="dv">9000</span>:</span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a>    pair <span class="op">=</span> make_date(rng)</span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> pair[<span class="dv">0</span>] <span class="kw">not</span> <span class="kw">in</span> seen_sources:</span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a>        seen_sources.add(pair[<span class="dv">0</span>])</span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a>        pairs.append(pair)</span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>train_pairs <span class="op">=</span> pairs[:<span class="dv">8000</span>]</span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a>valid_pairs <span class="op">=</span> pairs[<span class="dv">8000</span>:<span class="dv">8500</span>]</span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a>test_pairs <span class="op">=</span> pairs[<span class="dv">8500</span>:]</span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="op">*</span>pairs[:<span class="dv">4</span>], sep<span class="op">=</span><span class="st">"</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a>train_sources <span class="op">=</span> {s <span class="cf">for</span> s, _ <span class="kw">in</span> train_pairs}</span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a>valid_sources <span class="op">=</span> {s <span class="cf">for</span> s, _ <span class="kw">in</span> valid_pairs}</span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a>test_sources <span class="op">=</span> {s <span class="cf">for</span> s, _ <span class="kw">in</span> test_pairs}</span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"exact-source overlaps: "</span></span>
<span id="cb9-41"><a href="#cb9-41" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"train/valid </span><span class="sc">{</span><span class="bu">len</span>(train_sources <span class="op">&amp;</span> valid_sources)<span class="sc">}</span><span class="ss">, "</span></span>
<span id="cb9-42"><a href="#cb9-42" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"train/test </span><span class="sc">{</span><span class="bu">len</span>(train_sources <span class="op">&amp;</span> test_sources)<span class="sc">}</span><span class="ss">, "</span></span>
<span id="cb9-43"><a href="#cb9-43" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"valid/test </span><span class="sc">{</span><span class="bu">len</span>(valid_sources <span class="op">&amp;</span> test_sources)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb9-44"><a href="#cb9-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-45"><a href="#cb9-45" aria-hidden="true" tabindex="-1"></a>PAD, BOS, EOS <span class="op">=</span> <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>                             <span class="co"># special tokens first</span></span>
<span id="cb9-46"><a href="#cb9-46" aria-hidden="true" tabindex="-1"></a>SRC <span class="op">=</span> <span class="bu">sorted</span>(<span class="bu">set</span>(<span class="st">""</span>.join(s <span class="cf">for</span> s, _ <span class="kw">in</span> pairs)))</span>
<span id="cb9-47"><a href="#cb9-47" aria-hidden="true" tabindex="-1"></a>TGT <span class="op">=</span> <span class="bu">sorted</span>(<span class="bu">set</span>(<span class="st">""</span>.join(t <span class="cf">for</span> _, t <span class="kw">in</span> pairs)))</span>
<span id="cb9-48"><a href="#cb9-48" aria-hidden="true" tabindex="-1"></a>src_stoi <span class="op">=</span> {c: i <span class="op">+</span> <span class="dv">3</span> <span class="cf">for</span> i, c <span class="kw">in</span> <span class="bu">enumerate</span>(SRC)}</span>
<span id="cb9-49"><a href="#cb9-49" aria-hidden="true" tabindex="-1"></a>tgt_stoi <span class="op">=</span> {c: i <span class="op">+</span> <span class="dv">3</span> <span class="cf">for</span> i, c <span class="kw">in</span> <span class="bu">enumerate</span>(TGT)}</span>
<span id="cb9-50"><a href="#cb9-50" aria-hidden="true" tabindex="-1"></a>tgt_itos <span class="op">=</span> {i: c <span class="cf">for</span> c, i <span class="kw">in</span> tgt_stoi.items()}</span>
<span id="cb9-51"><a href="#cb9-51" aria-hidden="true" tabindex="-1"></a>V_src, V_tgt <span class="op">=</span> <span class="bu">len</span>(SRC) <span class="op">+</span> <span class="dv">3</span>, <span class="bu">len</span>(TGT) <span class="op">+</span> <span class="dv">3</span></span>
<span id="cb9-52"><a href="#cb9-52" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"source vocab </span><span class="sc">{</span>V_src<span class="sc">}</span><span class="ss">, target vocab </span><span class="sc">{</span>V_tgt<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>('26 september 2024', '2024-09-26')
('april 7, 1962', '1962-04-07')
('12/15/1950', '1950-12-15')
('14 february 1997', '1997-02-14')
exact-source overlaps: train/valid 0, train/test 0, valid/test 0
source vocab 37, target vocab 14</code></pre>
</div>
</div>
<p>Numeric dates can be ambiguous, so we retain the same unambiguous subsets as Chapter 11. Design decisions and the heatmap use validation only. The test set remains a single number at the end.</p>
<section id="put-the-learned-read-inside-the-recurrent-decoder" class="level3">
<h3 class="anchored" data-anchor-id="put-the-learned-read-inside-the-recurrent-decoder">Put the learned read inside the recurrent decoder</h3>
<p>The packed encoder now returns two things: its final <span class="math inline">\((\vect{h},\vect{c})\)</span> state, which still initializes the decoder, and a padded memory tensor containing every real encoder output plus a validity mask that excludes the padded slots. At step <span class="math inline">\(t\)</span>:</p>
<ol type="1">
<li>use decoder hidden state <span class="math inline">\(\vect{s}_{t-1}\)</span> as the query;</li>
<li>compute additive scores over the encoder memory and mask padding;</li>
<li>form the context <span class="math inline">\(\vect{c}_t\)</span>;</li>
<li>concatenate <span class="math inline">\(\vect{c}_t\)</span> with the embedding of the previous target token;</li>
<li>advance one decoder LSTM step, then predict from <span class="math inline">\([\vect{s}_t;\vect{c}_t]\)</span>.</li>
</ol>
<p>This timing follows the Bahdanau-style formulation. Luong-style variants often score with the current decoder state instead; both are valid, but silently mixing their indices makes an implementation impossible to audit.</p>
<p>For this date model, the shape ledger is concrete:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>quantity</th>
<th>shape</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>previous hidden query</td>
<td><span class="math inline">\((B,128)\)</span></td>
</tr>
<tr class="even">
<td>encoder memory</td>
<td><span class="math inline">\((B,T_{\text{src}},128)\)</span></td>
</tr>
<tr class="odd">
<td>attention weights</td>
<td><span class="math inline">\((B,T_{\text{src}})\)</span></td>
</tr>
<tr class="even">
<td>context</td>
<td><span class="math inline">\((B,128)\)</span></td>
</tr>
<tr class="odd">
<td>token embedding joined with context</td>
<td><span class="math inline">\((B,1,160)\)</span></td>
</tr>
<tr class="even">
<td>decoder output</td>
<td><span class="math inline">\((B,1,128)\)</span></td>
</tr>
<tr class="odd">
<td>output-head input <span class="math inline">\([\vect{s}_t;\vect{c}_t]\)</span></td>
<td><span class="math inline">\((B,256)\)</span></td>
</tr>
</tbody>
</table>
<!-- NOVEL: needs sign-off - independently written attentive date model and rematch. -->
<div id="attentive-seq2seq" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code: a masked additive-attention LSTM decoder</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> batchify(prs: <span class="bu">list</span>[<span class="bu">tuple</span>[<span class="bu">str</span>, <span class="bu">str</span>]], idx: <span class="bu">list</span>[<span class="bu">int</span>]) <span class="op">-&gt;</span> <span class="bu">tuple</span>[</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    torch.Tensor, torch.Tensor, torch.Tensor</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>]:</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    srcs <span class="op">=</span> [torch.tensor([src_stoi[c] <span class="cf">for</span> c <span class="kw">in</span> prs[i][<span class="dv">0</span>]]) <span class="cf">for</span> i <span class="kw">in</span> idx]</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    lengths <span class="op">=</span> torch.tensor([<span class="bu">len</span>(s) <span class="cf">for</span> s <span class="kw">in</span> srcs])</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    tgts <span class="op">=</span> [torch.tensor([BOS] <span class="op">+</span> [tgt_stoi[c] <span class="cf">for</span> c <span class="kw">in</span> prs[i][<span class="dv">1</span>]] <span class="op">+</span> [EOS])</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>            <span class="cf">for</span> i <span class="kw">in</span> idx]</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    S <span class="op">=</span> nn.utils.rnn.pad_sequence(srcs, batch_first<span class="op">=</span><span class="va">True</span>, padding_value<span class="op">=</span>PAD)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    T <span class="op">=</span> nn.utils.rnn.pad_sequence(tgts, batch_first<span class="op">=</span><span class="va">True</span>, padding_value<span class="op">=</span>PAD)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> S, lengths, T</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> unambiguous(prs: <span class="bu">list</span>[<span class="bu">tuple</span>[<span class="bu">str</span>, <span class="bu">str</span>]]) <span class="op">-&gt;</span> <span class="bu">list</span>[<span class="bu">tuple</span>[<span class="bu">str</span>, <span class="bu">str</span>]]:</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> [(s, t) <span class="cf">for</span> s, t <span class="kw">in</span> prs</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> <span class="st">"/"</span> <span class="kw">not</span> <span class="kw">in</span> s <span class="kw">or</span> <span class="bu">int</span>(s[:<span class="dv">2</span>]) <span class="op">&gt;</span> <span class="dv">12</span> <span class="kw">or</span> <span class="bu">int</span>(s[<span class="dv">3</span>:<span class="dv">5</span>]) <span class="op">&gt;</span> <span class="dv">12</span>]</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>valid_unamb <span class="op">=</span> unambiguous(valid_pairs)</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>test_unamb <span class="op">=</span> unambiguous(test_pairs)</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>valid_fixed <span class="op">=</span> valid_unamb[:<span class="dv">400</span>]</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"fixed validation </span><span class="sc">{</span><span class="bu">len</span>(valid_fixed)<span class="sc">}</span><span class="ss">; final test </span><span class="sc">{</span><span class="bu">len</span>(test_unamb)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> LearnedAlignment(nn.Module):</span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, hidden: <span class="bu">int</span> <span class="op">=</span> <span class="dv">128</span>, alignment: <span class="bu">int</span> <span class="op">=</span> <span class="dv">128</span>):</span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.key_map <span class="op">=</span> nn.Linear(hidden, alignment, bias<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.query_map <span class="op">=</span> nn.Linear(hidden, alignment, bias<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.selector <span class="op">=</span> nn.Linear(alignment, <span class="dv">1</span>, bias<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(</span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>,</span>
<span id="cb11-30"><a href="#cb11-30" aria-hidden="true" tabindex="-1"></a>        memory: torch.Tensor,</span>
<span id="cb11-31"><a href="#cb11-31" aria-hidden="true" tabindex="-1"></a>        query: torch.Tensor,</span>
<span id="cb11-32"><a href="#cb11-32" aria-hidden="true" tabindex="-1"></a>        valid: torch.Tensor,</span>
<span id="cb11-33"><a href="#cb11-33" aria-hidden="true" tabindex="-1"></a>    ) <span class="op">-&gt;</span> <span class="bu">tuple</span>[torch.Tensor, torch.Tensor]:</span>
<span id="cb11-34"><a href="#cb11-34" aria-hidden="true" tabindex="-1"></a>        match_features <span class="op">=</span> torch.tanh(</span>
<span id="cb11-35"><a href="#cb11-35" aria-hidden="true" tabindex="-1"></a>            <span class="va">self</span>.key_map(memory) <span class="op">+</span> <span class="va">self</span>.query_map(query).unsqueeze(<span class="dv">1</span>)</span>
<span id="cb11-36"><a href="#cb11-36" aria-hidden="true" tabindex="-1"></a>        )                                                   <span class="co"># (B, T_src, d_a)</span></span>
<span id="cb11-37"><a href="#cb11-37" aria-hidden="true" tabindex="-1"></a>        scores <span class="op">=</span> <span class="va">self</span>.selector(match_features).squeeze(<span class="op">-</span><span class="dv">1</span>)  <span class="co"># (B, T_src)</span></span>
<span id="cb11-38"><a href="#cb11-38" aria-hidden="true" tabindex="-1"></a>        scores <span class="op">=</span> scores.masked_fill(<span class="op">~</span>valid, <span class="op">-</span>torch.inf)</span>
<span id="cb11-39"><a href="#cb11-39" aria-hidden="true" tabindex="-1"></a>        weights <span class="op">=</span> torch.softmax(scores, dim<span class="op">=-</span><span class="dv">1</span>)</span>
<span id="cb11-40"><a href="#cb11-40" aria-hidden="true" tabindex="-1"></a>        context <span class="op">=</span> torch.bmm(weights.unsqueeze(<span class="dv">1</span>), memory).squeeze(<span class="dv">1</span>)</span>
<span id="cb11-41"><a href="#cb11-41" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> context, weights</span>
<span id="cb11-42"><a href="#cb11-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-43"><a href="#cb11-43" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> AttentiveSeq2Seq(nn.Module):</span>
<span id="cb11-44"><a href="#cb11-44" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, v_src: <span class="bu">int</span>, v_tgt: <span class="bu">int</span>, embed: <span class="bu">int</span> <span class="op">=</span> <span class="dv">32</span>,</span>
<span id="cb11-45"><a href="#cb11-45" aria-hidden="true" tabindex="-1"></a>                 hidden: <span class="bu">int</span> <span class="op">=</span> <span class="dv">128</span>, alignment: <span class="bu">int</span> <span class="op">=</span> <span class="dv">128</span>):</span>
<span id="cb11-46"><a href="#cb11-46" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb11-47"><a href="#cb11-47" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.src_emb <span class="op">=</span> nn.Embedding(v_src, embed, padding_idx<span class="op">=</span>PAD)</span>
<span id="cb11-48"><a href="#cb11-48" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.tgt_emb <span class="op">=</span> nn.Embedding(v_tgt, embed, padding_idx<span class="op">=</span>PAD)</span>
<span id="cb11-49"><a href="#cb11-49" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.encoder <span class="op">=</span> nn.LSTM(embed, hidden, batch_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb11-50"><a href="#cb11-50" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.attention <span class="op">=</span> LearnedAlignment(hidden, alignment)</span>
<span id="cb11-51"><a href="#cb11-51" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.decoder <span class="op">=</span> nn.LSTM(embed <span class="op">+</span> hidden, hidden, batch_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb11-52"><a href="#cb11-52" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.out <span class="op">=</span> nn.Linear(<span class="dv">2</span> <span class="op">*</span> hidden, v_tgt)</span>
<span id="cb11-53"><a href="#cb11-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-54"><a href="#cb11-54" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> encode(</span>
<span id="cb11-55"><a href="#cb11-55" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>, S: torch.Tensor, lengths: torch.Tensor,</span>
<span id="cb11-56"><a href="#cb11-56" aria-hidden="true" tabindex="-1"></a>    ) <span class="op">-&gt;</span> <span class="bu">tuple</span>[torch.Tensor, <span class="bu">tuple</span>[torch.Tensor, torch.Tensor], torch.Tensor]:</span>
<span id="cb11-57"><a href="#cb11-57" aria-hidden="true" tabindex="-1"></a>        packed <span class="op">=</span> nn.utils.rnn.pack_padded_sequence(</span>
<span id="cb11-58"><a href="#cb11-58" aria-hidden="true" tabindex="-1"></a>            <span class="va">self</span>.src_emb(S), lengths, batch_first<span class="op">=</span><span class="va">True</span>, enforce_sorted<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb11-59"><a href="#cb11-59" aria-hidden="true" tabindex="-1"></a>        packed_memory, state <span class="op">=</span> <span class="va">self</span>.encoder(packed)</span>
<span id="cb11-60"><a href="#cb11-60" aria-hidden="true" tabindex="-1"></a>        memory, _ <span class="op">=</span> nn.utils.rnn.pad_packed_sequence(</span>
<span id="cb11-61"><a href="#cb11-61" aria-hidden="true" tabindex="-1"></a>            packed_memory, batch_first<span class="op">=</span><span class="va">True</span>, total_length<span class="op">=</span>S.shape[<span class="dv">1</span>])</span>
<span id="cb11-62"><a href="#cb11-62" aria-hidden="true" tabindex="-1"></a>        valid <span class="op">=</span> torch.arange(S.shape[<span class="dv">1</span>])[<span class="va">None</span>, :] <span class="op">&lt;</span> lengths[:, <span class="va">None</span>]</span>
<span id="cb11-63"><a href="#cb11-63" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> memory, state, valid</span>
<span id="cb11-64"><a href="#cb11-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-65"><a href="#cb11-65" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> decode_step(</span>
<span id="cb11-66"><a href="#cb11-66" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>,</span>
<span id="cb11-67"><a href="#cb11-67" aria-hidden="true" tabindex="-1"></a>        token: torch.Tensor,</span>
<span id="cb11-68"><a href="#cb11-68" aria-hidden="true" tabindex="-1"></a>        state: <span class="bu">tuple</span>[torch.Tensor, torch.Tensor],</span>
<span id="cb11-69"><a href="#cb11-69" aria-hidden="true" tabindex="-1"></a>        memory: torch.Tensor,</span>
<span id="cb11-70"><a href="#cb11-70" aria-hidden="true" tabindex="-1"></a>        valid: torch.Tensor,</span>
<span id="cb11-71"><a href="#cb11-71" aria-hidden="true" tabindex="-1"></a>    ) <span class="op">-&gt;</span> <span class="bu">tuple</span>[torch.Tensor, <span class="bu">tuple</span>[torch.Tensor, torch.Tensor], torch.Tensor]:</span>
<span id="cb11-72"><a href="#cb11-72" aria-hidden="true" tabindex="-1"></a>        query <span class="op">=</span> state[<span class="dv">0</span>][<span class="op">-</span><span class="dv">1</span>]                              <span class="co"># previous hidden state</span></span>
<span id="cb11-73"><a href="#cb11-73" aria-hidden="true" tabindex="-1"></a>        context, weights <span class="op">=</span> <span class="va">self</span>.attention(memory, query, valid)</span>
<span id="cb11-74"><a href="#cb11-74" aria-hidden="true" tabindex="-1"></a>        decoder_input <span class="op">=</span> torch.cat(</span>
<span id="cb11-75"><a href="#cb11-75" aria-hidden="true" tabindex="-1"></a>            (<span class="va">self</span>.tgt_emb(token), context.unsqueeze(<span class="dv">1</span>)), dim<span class="op">=-</span><span class="dv">1</span></span>
<span id="cb11-76"><a href="#cb11-76" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb11-77"><a href="#cb11-77" aria-hidden="true" tabindex="-1"></a>        decoder_output, state <span class="op">=</span> <span class="va">self</span>.decoder(decoder_input, state)</span>
<span id="cb11-78"><a href="#cb11-78" aria-hidden="true" tabindex="-1"></a>        logits <span class="op">=</span> <span class="va">self</span>.out(torch.cat((decoder_output[:, <span class="dv">0</span>], context), dim<span class="op">=-</span><span class="dv">1</span>))</span>
<span id="cb11-79"><a href="#cb11-79" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> logits, state, weights</span>
<span id="cb11-80"><a href="#cb11-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-81"><a href="#cb11-81" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(</span>
<span id="cb11-82"><a href="#cb11-82" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>, S: torch.Tensor, lengths: torch.Tensor, T_in: torch.Tensor,</span>
<span id="cb11-83"><a href="#cb11-83" aria-hidden="true" tabindex="-1"></a>    ) <span class="op">-&gt;</span> torch.Tensor:</span>
<span id="cb11-84"><a href="#cb11-84" aria-hidden="true" tabindex="-1"></a>        memory, state, valid <span class="op">=</span> <span class="va">self</span>.encode(S, lengths)</span>
<span id="cb11-85"><a href="#cb11-85" aria-hidden="true" tabindex="-1"></a>        logits <span class="op">=</span> []</span>
<span id="cb11-86"><a href="#cb11-86" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> t <span class="kw">in</span> <span class="bu">range</span>(T_in.shape[<span class="dv">1</span>]):</span>
<span id="cb11-87"><a href="#cb11-87" aria-hidden="true" tabindex="-1"></a>            logit, state, _ <span class="op">=</span> <span class="va">self</span>.decode_step(</span>
<span id="cb11-88"><a href="#cb11-88" aria-hidden="true" tabindex="-1"></a>                T_in[:, t:t <span class="op">+</span> <span class="dv">1</span>], state, memory, valid)</span>
<span id="cb11-89"><a href="#cb11-89" aria-hidden="true" tabindex="-1"></a>            logits.append(logit)</span>
<span id="cb11-90"><a href="#cb11-90" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> torch.stack(logits, dim<span class="op">=</span><span class="dv">1</span>)                 <span class="co"># (B, T_tgt, V_tgt)</span></span>
<span id="cb11-91"><a href="#cb11-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-92"><a href="#cb11-92" aria-hidden="true" tabindex="-1"></a><span class="at">@torch.inference_mode</span>()</span>
<span id="cb11-93"><a href="#cb11-93" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> greedy_batch(</span>
<span id="cb11-94"><a href="#cb11-94" aria-hidden="true" tabindex="-1"></a>    model: AttentiveSeq2Seq,</span>
<span id="cb11-95"><a href="#cb11-95" aria-hidden="true" tabindex="-1"></a>    prs: <span class="bu">list</span>[<span class="bu">tuple</span>[<span class="bu">str</span>, <span class="bu">str</span>]],</span>
<span id="cb11-96"><a href="#cb11-96" aria-hidden="true" tabindex="-1"></a>    batch: <span class="bu">int</span> <span class="op">=</span> <span class="dv">128</span>,</span>
<span id="cb11-97"><a href="#cb11-97" aria-hidden="true" tabindex="-1"></a>    maxlen: <span class="bu">int</span> <span class="op">=</span> <span class="dv">12</span>,</span>
<span id="cb11-98"><a href="#cb11-98" aria-hidden="true" tabindex="-1"></a>) <span class="op">-&gt;</span> <span class="bu">list</span>[<span class="bu">tuple</span>[<span class="bu">str</span>, <span class="bu">str</span>, torch.Tensor]]:</span>
<span id="cb11-99"><a href="#cb11-99" aria-hidden="true" tabindex="-1"></a>    model.<span class="bu">eval</span>()</span>
<span id="cb11-100"><a href="#cb11-100" aria-hidden="true" tabindex="-1"></a>    outputs <span class="op">=</span> []</span>
<span id="cb11-101"><a href="#cb11-101" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> start <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>, <span class="bu">len</span>(prs), batch):</span>
<span id="cb11-102"><a href="#cb11-102" aria-hidden="true" tabindex="-1"></a>        subset <span class="op">=</span> prs[start:start <span class="op">+</span> batch]</span>
<span id="cb11-103"><a href="#cb11-103" aria-hidden="true" tabindex="-1"></a>        S, lengths, _ <span class="op">=</span> batchify(subset, <span class="bu">list</span>(<span class="bu">range</span>(<span class="bu">len</span>(subset))))</span>
<span id="cb11-104"><a href="#cb11-104" aria-hidden="true" tabindex="-1"></a>        memory, state, valid <span class="op">=</span> model.encode(S, lengths)</span>
<span id="cb11-105"><a href="#cb11-105" aria-hidden="true" tabindex="-1"></a>        token <span class="op">=</span> torch.full((<span class="bu">len</span>(subset), <span class="dv">1</span>), BOS)</span>
<span id="cb11-106"><a href="#cb11-106" aria-hidden="true" tabindex="-1"></a>        token_steps, weight_steps <span class="op">=</span> [], []</span>
<span id="cb11-107"><a href="#cb11-107" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(maxlen):</span>
<span id="cb11-108"><a href="#cb11-108" aria-hidden="true" tabindex="-1"></a>            logits, state, weights <span class="op">=</span> model.decode_step(</span>
<span id="cb11-109"><a href="#cb11-109" aria-hidden="true" tabindex="-1"></a>                token, state, memory, valid)</span>
<span id="cb11-110"><a href="#cb11-110" aria-hidden="true" tabindex="-1"></a>            token <span class="op">=</span> logits.argmax(<span class="op">-</span><span class="dv">1</span>, keepdim<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb11-111"><a href="#cb11-111" aria-hidden="true" tabindex="-1"></a>            token_steps.append(token[:, <span class="dv">0</span>])</span>
<span id="cb11-112"><a href="#cb11-112" aria-hidden="true" tabindex="-1"></a>            weight_steps.append(weights)</span>
<span id="cb11-113"><a href="#cb11-113" aria-hidden="true" tabindex="-1"></a>        predicted <span class="op">=</span> torch.stack(token_steps, dim<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb11-114"><a href="#cb11-114" aria-hidden="true" tabindex="-1"></a>        attention <span class="op">=</span> torch.stack(weight_steps, dim<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb11-115"><a href="#cb11-115" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> row, (source, _) <span class="kw">in</span> <span class="bu">enumerate</span>(subset):</span>
<span id="cb11-116"><a href="#cb11-116" aria-hidden="true" tabindex="-1"></a>            chars <span class="op">=</span> []</span>
<span id="cb11-117"><a href="#cb11-117" aria-hidden="true" tabindex="-1"></a>            <span class="cf">for</span> index <span class="kw">in</span> predicted[row].tolist():</span>
<span id="cb11-118"><a href="#cb11-118" aria-hidden="true" tabindex="-1"></a>                <span class="cf">if</span> index <span class="op">==</span> EOS:</span>
<span id="cb11-119"><a href="#cb11-119" aria-hidden="true" tabindex="-1"></a>                    <span class="cf">break</span></span>
<span id="cb11-120"><a href="#cb11-120" aria-hidden="true" tabindex="-1"></a>                chars.append(tgt_itos.get(index, <span class="st">"?"</span>))</span>
<span id="cb11-121"><a href="#cb11-121" aria-hidden="true" tabindex="-1"></a>            outputs.append((</span>
<span id="cb11-122"><a href="#cb11-122" aria-hidden="true" tabindex="-1"></a>                source,</span>
<span id="cb11-123"><a href="#cb11-123" aria-hidden="true" tabindex="-1"></a>                <span class="st">""</span>.join(chars),</span>
<span id="cb11-124"><a href="#cb11-124" aria-hidden="true" tabindex="-1"></a>                attention[row, :, :lengths[row]].clone(),</span>
<span id="cb11-125"><a href="#cb11-125" aria-hidden="true" tabindex="-1"></a>            ))</span>
<span id="cb11-126"><a href="#cb11-126" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> outputs</span>
<span id="cb11-127"><a href="#cb11-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-128"><a href="#cb11-128" aria-hidden="true" tabindex="-1"></a><span class="at">@torch.inference_mode</span>()</span>
<span id="cb11-129"><a href="#cb11-129" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> exact_match(</span>
<span id="cb11-130"><a href="#cb11-130" aria-hidden="true" tabindex="-1"></a>    model: AttentiveSeq2Seq, prs: <span class="bu">list</span>[<span class="bu">tuple</span>[<span class="bu">str</span>, <span class="bu">str</span>]],</span>
<span id="cb11-131"><a href="#cb11-131" aria-hidden="true" tabindex="-1"></a>) <span class="op">-&gt;</span> <span class="bu">float</span>:</span>
<span id="cb11-132"><a href="#cb11-132" aria-hidden="true" tabindex="-1"></a>    generated <span class="op">=</span> greedy_batch(model, prs)</span>
<span id="cb11-133"><a href="#cb11-133" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="bu">sum</span>(</span>
<span id="cb11-134"><a href="#cb11-134" aria-hidden="true" tabindex="-1"></a>        guess <span class="op">==</span> truth</span>
<span id="cb11-135"><a href="#cb11-135" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> (_, truth), (_, guess, _) <span class="kw">in</span> <span class="bu">zip</span>(prs, generated)</span>
<span id="cb11-136"><a href="#cb11-136" aria-hidden="true" tabindex="-1"></a>    ) <span class="op">/</span> <span class="bu">len</span>(prs)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>fixed validation 400; final test 437</code></pre>
</div>
</div>
<p>Notice what changed relative to Chapter 11. The embeddings and encoder width are untouched. Values are the contextual encoder states themselves; learned projections create match features for keys and queries. The decoder must now advance one target step at a time because its next context depends on its previous state. Teacher forcing still supplies the true previous token, but it no longer permits one fused decoder call.</p>
</section>
<section id="the-matched-schedule-rematch" class="level3">
<h3 class="anchored" data-anchor-id="the-matched-schedule-rematch">The matched-schedule rematch</h3>
<p>The full Chapter 11 validation curve below is frozen from a byte-identical re-execution of that chapter’s published baseline. We do not retrain it here. We train the attentive model once, inspect only validation alignments, and then request one final test scalar:</p>
<div id="attention-date-training" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Code: matched-schedule date rematch and sealed test audit</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>checkpoints <span class="op">=</span> (<span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">8</span>, <span class="dv">12</span>, <span class="dv">16</span>, <span class="dv">20</span>, <span class="dv">25</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>baseline_curve <span class="op">=</span> {</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    <span class="dv">2</span>: <span class="fl">0.0025</span>, <span class="dv">4</span>: <span class="fl">0.1475</span>, <span class="dv">6</span>: <span class="fl">0.5375</span>, <span class="dv">8</span>: <span class="fl">0.7575</span>,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    <span class="dv">12</span>: <span class="fl">0.9500</span>, <span class="dv">16</span>: <span class="fl">0.9500</span>, <span class="dv">20</span>: <span class="fl">0.9950</span>, <span class="dv">25</span>: <span class="fl">0.9575</span>,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>torch.manual_seed(<span class="dv">6050</span>)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>attention_model <span class="op">=</span> AttentiveSeq2Seq(V_src, V_tgt)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>optimizer <span class="op">=</span> torch.optim.Adam(attention_model.parameters(), lr<span class="op">=</span><span class="fl">1e-3</span>)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>attention_curve <span class="op">=</span> {}</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> epoch <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">26</span>):</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>    attention_model.train()</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>    permutation <span class="op">=</span> torch.randperm(<span class="bu">len</span>(train_pairs))</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> start <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>, <span class="bu">len</span>(train_pairs), <span class="dv">128</span>):</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>        ids <span class="op">=</span> permutation[start:start <span class="op">+</span> <span class="dv">128</span>].tolist()</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>        S, lengths, T <span class="op">=</span> batchify(train_pairs, ids)</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>        logits <span class="op">=</span> attention_model(S, lengths, T[:, :<span class="op">-</span><span class="dv">1</span>])</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>        loss <span class="op">=</span> F.cross_entropy(</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>            logits.reshape(<span class="op">-</span><span class="dv">1</span>, V_tgt),</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>            T[:, <span class="dv">1</span>:].reshape(<span class="op">-</span><span class="dv">1</span>),</span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>            ignore_index<span class="op">=</span>PAD,</span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a>        optimizer.zero_grad()</span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a>        loss.backward()</span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a>        nn.utils.clip_grad_norm_(attention_model.parameters(), <span class="fl">5.0</span>)</span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a>        optimizer.step()</span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> epoch <span class="kw">in</span> checkpoints:</span>
<span id="cb13-29"><a href="#cb13-29" aria-hidden="true" tabindex="-1"></a>        attention_curve[epoch] <span class="op">=</span> exact_match(</span>
<span id="cb13-30"><a href="#cb13-30" aria-hidden="true" tabindex="-1"></a>            attention_model, valid_fixed)</span>
<span id="cb13-31"><a href="#cb13-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-32"><a href="#cb13-32" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"epoch   fixed-state   attention"</span>)</span>
<span id="cb13-33"><a href="#cb13-33" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> epoch <span class="kw">in</span> checkpoints:</span>
<span id="cb13-34"><a href="#cb13-34" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>epoch<span class="sc">:2d}</span><span class="ss">       </span><span class="sc">{</span>baseline_curve[epoch]<span class="sc">:6.2%}</span><span class="ss">       "</span></span>
<span id="cb13-35"><a href="#cb13-35" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"</span><span class="sc">{</span>attention_curve[epoch]<span class="sc">:6.2%}</span><span class="ss">"</span>)</span>
<span id="cb13-36"><a href="#cb13-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-37"><a href="#cb13-37" aria-hidden="true" tabindex="-1"></a>validation_outputs <span class="op">=</span> greedy_batch(attention_model, valid_fixed)</span>
<span id="cb13-38"><a href="#cb13-38" aria-hidden="true" tabindex="-1"></a>source_example, truth_example <span class="op">=</span> valid_fixed[<span class="dv">0</span>]           <span class="co"># fixed before training</span></span>
<span id="cb13-39"><a href="#cb13-39" aria-hidden="true" tabindex="-1"></a>_, generated_example, alignment_example <span class="op">=</span> validation_outputs[<span class="dv">0</span>]</span>
<span id="cb13-40"><a href="#cb13-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-41"><a href="#cb13-41" aria-hidden="true" tabindex="-1"></a>year_mass, year_top1, row_errors <span class="op">=</span> [], [], []</span>
<span id="cb13-42"><a href="#cb13-42" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (source, _), (_, _, weights) <span class="kw">in</span> <span class="bu">zip</span>(valid_fixed, validation_outputs):</span>
<span id="cb13-43"><a href="#cb13-43" aria-hidden="true" tabindex="-1"></a>    year_positions <span class="op">=</span> <span class="bu">list</span>(<span class="bu">range</span>(<span class="bu">len</span>(source) <span class="op">-</span> <span class="dv">4</span>, <span class="bu">len</span>(source)))</span>
<span id="cb13-44"><a href="#cb13-44" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> step <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">4</span>):</span>
<span id="cb13-45"><a href="#cb13-45" aria-hidden="true" tabindex="-1"></a>        year_mass.append(weights[step, year_positions].<span class="bu">sum</span>().item())</span>
<span id="cb13-46"><a href="#cb13-46" aria-hidden="true" tabindex="-1"></a>        year_top1.append(<span class="bu">int</span>(weights[step].argmax().item() <span class="kw">in</span> year_positions))</span>
<span id="cb13-47"><a href="#cb13-47" aria-hidden="true" tabindex="-1"></a>    row_errors.append((weights[:<span class="dv">10</span>].<span class="bu">sum</span>(<span class="dv">1</span>) <span class="op">-</span> <span class="dv">1</span>).<span class="bu">abs</span>().<span class="bu">max</span>().item())</span>
<span id="cb13-48"><a href="#cb13-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-49"><a href="#cb13-49" aria-hidden="true" tabindex="-1"></a>attention_params <span class="op">=</span> <span class="bu">sum</span>(p.numel() <span class="cf">for</span> p <span class="kw">in</span> attention_model.parameters())</span>
<span id="cb13-50"><a href="#cb13-50" aria-hidden="true" tabindex="-1"></a>baseline_params <span class="op">=</span> <span class="dv">169_326</span></span>
<span id="cb13-51"><a href="#cb13-51" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"parameters: baseline </span><span class="sc">{</span>baseline_params<span class="sc">:,}</span><span class="ss">; "</span></span>
<span id="cb13-52"><a href="#cb13-52" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"attention </span><span class="sc">{</span>attention_params<span class="sc">:,}</span><span class="ss"> "</span></span>
<span id="cb13-53"><a href="#cb13-53" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"(+</span><span class="sc">{</span>(attention_params <span class="op">/</span> baseline_params <span class="op">-</span> <span class="dv">1</span>)<span class="sc">:.1%}</span><span class="ss">)"</span>)</span>
<span id="cb13-54"><a href="#cb13-54" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"validation example: </span><span class="sc">{</span>source_example<span class="sc">!r}</span><span class="ss"> -&gt; "</span></span>
<span id="cb13-55"><a href="#cb13-55" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>generated_example<span class="sc">!r}</span><span class="ss"> (truth </span><span class="sc">{</span>truth_example<span class="sc">}</span><span class="ss">)"</span>)</span>
<span id="cb13-56"><a href="#cb13-56" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"validation year-region mass: </span><span class="sc">{</span>np<span class="sc">.</span>mean(year_mass)<span class="sc">:.3%}</span><span class="ss">; "</span></span>
<span id="cb13-57"><a href="#cb13-57" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"top key in region: </span><span class="sc">{</span>np<span class="sc">.</span>mean(year_top1)<span class="sc">:.3%}</span><span class="ss">"</span>)</span>
<span id="cb13-58"><a href="#cb13-58" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"maximum validation row-sum error:"</span>, <span class="ss">f"</span><span class="sc">{</span><span class="bu">max</span>(row_errors)<span class="sc">:.2e}</span><span class="ss">"</span>)</span>
<span id="cb13-59"><a href="#cb13-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-60"><a href="#cb13-60" aria-hidden="true" tabindex="-1"></a>test_exact <span class="op">=</span> exact_match(attention_model, test_unamb)     <span class="co"># one final test audit</span></span>
<span id="cb13-61"><a href="#cb13-61" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"one final test audit (</span><span class="sc">{</span><span class="bu">len</span>(test_unamb)<span class="sc">}</span><span class="ss"> sources): "</span></span>
<span id="cb13-62"><a href="#cb13-62" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"baseline 93.1%; attention </span><span class="sc">{</span>test_exact<span class="sc">:.1%}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>epoch   fixed-state   attention
 2        0.25%        9.50%
 4       14.75%       74.50%
 6       53.75%       93.25%
 8       75.75%       99.00%
12       95.00%       99.75%
16       95.00%       99.75%
20       99.50%       99.75%
25       95.75%       99.75%
parameters: baseline 169,326; attention 269,550 (+59.2%)
validation example: 'may 17, 1971' -&gt; '1971-05-17' (truth 1971-05-17)
validation year-region mass: 97.469%; top key in region: 99.688%
maximum validation row-sum error: 2.38e-07
one final test audit (437 sources): baseline 93.1%; attention 100.0%</code></pre>
</div>
</div>
<div id="cell-fig-attention-rematch" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Figure: convergence rematch and learned date alignment</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib.patches <span class="im">import</span> Rectangle</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    <span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="fl">9.8</span>, <span class="fl">3.45</span>),</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    gridspec_kw<span class="op">=</span>{<span class="st">"width_ratios"</span>: [<span class="fl">1.0</span>, <span class="fl">1.35</span>]},</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    constrained_layout<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].plot(</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>    checkpoints, [baseline_curve[c] <span class="cf">for</span> c <span class="kw">in</span> checkpoints],</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"o-"</span>, color<span class="op">=</span><span class="st">"#8D99AE"</span>, lw<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">"fixed-state baseline"</span>,</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].plot(</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>    checkpoints, [attention_curve[c] <span class="cf">for</span> c <span class="kw">in</span> checkpoints],</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"s-"</span>, color<span class="op">=</span><span class="st">"#E57200"</span>, lw<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">"learned attention"</span>,</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].<span class="bu">set</span>(</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>    xlabel<span class="op">=</span><span class="st">"epoch"</span>, ylabel<span class="op">=</span><span class="st">"validation exact match"</span>,</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>    ylim<span class="op">=</span>(<span class="op">-</span><span class="fl">0.02</span>, <span class="fl">1.03</span>), title<span class="op">=</span><span class="st">"Same schedule, learned access"</span>,</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>heatmap <span class="op">=</span> alignment_example[:<span class="bu">len</span>(generated_example)].numpy()</span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>image <span class="op">=</span> axes[<span class="dv">1</span>].imshow(</span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>    heatmap, cmap<span class="op">=</span><span class="st">"Blues"</span>, aspect<span class="op">=</span><span class="st">"auto"</span>, vmin<span class="op">=</span><span class="dv">0</span>, vmax<span class="op">=</span><span class="dv">1</span>,</span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>source_labels <span class="op">=</span> [<span class="st">"·"</span> <span class="cf">if</span> char <span class="op">==</span> <span class="st">" "</span> <span class="cf">else</span> char <span class="cf">for</span> char <span class="kw">in</span> source_example]</span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xticks(<span class="bu">range</span>(<span class="bu">len</span>(source_example)), source_labels)</span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_yticks(<span class="bu">range</span>(<span class="bu">len</span>(generated_example)), <span class="bu">list</span>(generated_example))</span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].<span class="bu">set</span>(</span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a>    xlabel<span class="op">=</span><span class="st">"source character / encoder state"</span>,</span>
<span id="cb15-31"><a href="#cb15-31" aria-hidden="true" tabindex="-1"></a>    ylabel<span class="op">=</span><span class="st">"emitted character"</span>,</span>
<span id="cb15-32"><a href="#cb15-32" aria-hidden="true" tabindex="-1"></a>    title<span class="op">=</span><span class="ss">f"</span><span class="sc">{</span>source_example<span class="sc">}</span><span class="ss">  -&gt;  </span><span class="sc">{</span>generated_example<span class="sc">}</span><span class="ss">"</span>,</span>
<span id="cb15-33"><a href="#cb15-33" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-34"><a href="#cb15-34" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].add_patch(Rectangle(</span>
<span id="cb15-35"><a href="#cb15-35" aria-hidden="true" tabindex="-1"></a>    (<span class="bu">len</span>(source_example) <span class="op">-</span> <span class="fl">4.5</span>, <span class="op">-</span><span class="fl">0.5</span>), <span class="dv">4</span>, <span class="dv">4</span>,</span>
<span id="cb15-36"><a href="#cb15-36" aria-hidden="true" tabindex="-1"></a>    fill<span class="op">=</span><span class="va">False</span>, edgecolor<span class="op">=</span><span class="st">"#E57200"</span>, linewidth<span class="op">=</span><span class="dv">2</span>,</span>
<span id="cb15-37"><a href="#cb15-37" aria-hidden="true" tabindex="-1"></a>))</span>
<span id="cb15-38"><a href="#cb15-38" aria-hidden="true" tabindex="-1"></a>fig.colorbar(</span>
<span id="cb15-39"><a href="#cb15-39" aria-hidden="true" tabindex="-1"></a>    image, ax<span class="op">=</span>axes[<span class="dv">1</span>], fraction<span class="op">=</span><span class="fl">0.047</span>, pad<span class="op">=</span><span class="fl">0.03</span>,</span>
<span id="cb15-40"><a href="#cb15-40" aria-hidden="true" tabindex="-1"></a>    label<span class="op">=</span><span class="st">"attention weight"</span>,</span>
<span id="cb15-41"><a href="#cb15-41" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-42"><a href="#cb15-42" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-attention-rematch" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-attention-rematch-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="13-attention_files/figure-html/fig-attention-rematch-output-1.png" width="952" height="342" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-attention-rematch-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.4: Left: exact-sequence accuracy on Chapter 11’s fixed 400-source validation subset. Both models use the same data, embedding and recurrent hidden widths, optimizer, top-level seed, and epoch schedule; attention adds parameters and a stepwise decoder, so this is not a parameter- or compute-matched ablation. Right: the predeclared first validation example. Rows are emitted ISO characters, columns are contextual encoder states indexed by source character, and the orange box marks the source year. The first four rows concentrate there.
</figcaption>
</figure>
</div>
</div>
</div>
<p>At epoch 6, the fixed-state baseline is at <span class="math inline">\(53.8\%\)</span> and the attentive model is at <span class="math inline">\(93.25\%\)</span>, a 39.5-point lead. At epoch 12 the comparison is <span class="math inline">\(95.0\%\)</span> versus <span class="math inline">\(99.75\%\)</span>. The one final test audit is <span class="math inline">\(93.1\%\)</span> versus <span class="math inline">\(100.0\%\)</span> on 437 unambiguous sources.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Faster convergence is not a one-variable proof
</div>
</div>
<div class="callout-body-container callout-body">
<p>We matched examples, embedding and recurrent hidden widths, optimizer, top-level seed, number of updates, and epochs. We did <strong>not</strong> match parameter count, computation, or minibatch order: constructing models with different parameter counts consumes different random draws before their first permutation. The attentive model has 269,550 parameters versus 169,326, an increase of 59.2%, and its input-feeding decoder uses a Python step loop where Chapter 11’s teacher-forced baseline uses one fused target-sequence call. This one seeded synthetic rematch shows that the attention-equipped model reaches higher accuracy in fewer epochs and optimizer updates, not in less wall-clock time. It does not isolate bottleneck removal as the only possible cause.</p>
</div>
</div>
<p>The heatmap answers a narrower question. On the fixed validation example, the year must travel from the last four source positions to the first four outputs. The orange block catches that movement, and across all 400 fixed validation examples, 97.5% of those four rows’ mass lands on states indexed by the source-year region. The top-weighted state is indexed inside that region 99.7% of the time.</p>
<p>Columns are indexed by source characters, but their values are encoder states. Each state summarizes a recurrent prefix, so a delimiter can legitimately carry information about a field that just ended. Attention weights are internal allocation weights, not calibrated confidence and not a causal explanation of the model. The quantitative audit and the visual alignment complement each other; neither substitutes for the other.</p>
<!-- /NOVEL -->
</section>
</section>
<section id="one-learned-view-for-now" class="level2" data-number="13.6">
<h2 data-number="13.6" class="anchored" data-anchor-id="one-learned-view-for-now"><span class="header-section-number">13.6</span> One learned view, for now</h2>
<p>One attention head learns one set of query, key, and value projections. Multi-head attention repeats that operator with several projection sets, concatenates the reads, and learns an output projection. It works for cross-attention as well as self-attention, and different heads <em>can</em> learn different relationships without any guarantee that they will. We keep one head in the date rematch so its alignment stays easy to inspect. Chapter 14 derives the multi-head shapes and implements the full operator in its self-attention setting.</p>
</section>
<section id="the-bottleneck-that-remains" class="level2" data-number="13.7">
<h2 data-number="13.7" class="anchored" data-anchor-id="the-bottleneck-that-remains"><span class="header-section-number">13.7</span> The bottleneck that remains</h2>
<p>Cross-attention has repaired the fixed handoff. A decoder output can read any encoder state through one learned allocation. Yet both surrounding LSTMs remain recurrent: <span class="math inline">\(\vect{h}_i\)</span> waits for <span class="math inline">\(\vect{h}_{i-1}\)</span>, and <span class="math inline">\(\vect{s}_t\)</span> waits for <span class="math inline">\(\vect{s}_{t-1}\)</span>. Within either sequence, training cannot create all recurrent states at once.</p>
<p>The Q/K/V operator itself does not care where its three inputs came from. What if every position in one sequence supplied queries, keys, and values to every other position? Using that operator in place of the RNN can remove recurrence within each layer, but it also removes the RNN’s built-in sense of order. Chapter 8 warned that throwing away <em>where</em> incurs a debt; Chapter 14 pays it back with positional information. Chapter 11’s masking warning also returns there: a causal mask will decide which future positions an autoregressive model may not see.</p>
</section>
<section id="okay-so" class="level2" data-number="13.8">
<h2 data-number="13.8" class="anchored" data-anchor-id="okay-so"><span class="header-section-number">13.8</span> Okay, so —</h2>
<ol type="1">
<li><strong>Attention softens the address.</strong> Chapter 11 learned embedding content while keeping lookup indices hard. Chapter 2’s differentiable-lookup promise is now paid: learned scores become a distribution over memory locations.</li>
<li><strong>Additive attention learns the compatibility function.</strong> Query and key enter a shared alignment space, tanh creates match features, and one selector produces each score. The same scorer is reused across all decoder/source pairs.</li>
<li><strong>Scaled dot product learns comparison spaces.</strong> Projected <span class="math inline">\(\matr{Q}\matr{K}^{\top}/\sqrt{d_k}\)</span> maps directly to dense matrix products. Under the idealized independent unit-variance model, scaling holds score variance near one instead of letting it grow with <span class="math inline">\(d_k\)</span>.</li>
<li><strong>Masking is part of the operator.</strong> Padding is excluded before softmax; zero is not a mask. Cross-attention sees all real source positions, while causal masking belongs to the self-attentive decoder in Chapter 14.</li>
<li><strong>The date rematch exposes learned access.</strong> Under the shared schedule, attention reaches 93.25% validation exact match at epoch 6 and 100.0% on the final test audit. Its year rows route 97.5% of validation weight to states indexed by the source-year region, with the parameter/compute caveat stated in full.</li>
</ol>
</section>
<section id="sources-and-further-reading" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="sources-and-further-reading">Sources and further reading</h2>
<ul>
<li><a href="https://arxiv.org/abs/1409.0473">Bahdanau, Cho, &amp; Bengio, <em>Neural Machine Translation by Jointly Learning to Align and Translate</em></a>: conjectures that the fixed-length encoder vector is a bottleneck, then tests differentiable soft search with an additive scorer.</li>
<li><a href="https://aclanthology.org/D15-1166/">Luong, Pham, &amp; Manning, <em>Effective Approaches to Attention-based Neural Machine Translation</em></a>: compares dot, general, and concat scoring functions and clarifies a second recurrent-attention timing convention.</li>
<li><a href="https://papers.nips.cc/paper/7181-attention-is-all-you-need">Vaswani et al., <em>Attention Is All You Need</em></a>: introduces scaled dot-product and multi-head attention in the architecture Chapter 14 builds.</li>
</ul>
</section>
<section id="exercises" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercises">Exercises</h2>
<ol type="1">
<li><strong>(Pencil.)</strong> Starting from <a href="#eq-additive-attention" class="quarto-xref">Equation&nbsp;<span>13.2</span></a>, write every batched shape for <span class="math inline">\(B=32\)</span>, source length 17, <span class="math inline">\(d_e=128\)</span>, <span class="math inline">\(d_d=96\)</span>, and <span class="math inline">\(d_a=64\)</span>. Which axis must softmax normalize, and why can the raw encoder and decoder widths differ?</li>
<li><strong>(Code.)</strong> Extend the scaled-dot function with a deliberately all-false mask row. Confirm the guard catches it. Remove the guard and inspect the result of softmax over all <span class="math inline">\(-\infty\)</span>. Then replace the mask with zero scores and explain why padding receives weight.</li>
<li><strong>(Pencil + code.)</strong> Generalize the scaling derivation to independent coordinates with variances <span class="math inline">\(\sigma_q^2\)</span> and <span class="math inline">\(\sigma_k^2\)</span>. Modify the seeded audit and check which divisor returns score variance near one.</li>
<li><strong>(Code.)</strong> Replace the date model’s additive scorer with learned projected scaled-dot attention. Keep the split, schedule, and validation subset fixed. Select any design choices on validation, report the sealed test once, and compare both convergence and year-region alignment. Explain why a large weight is neither calibrated confidence nor a causal explanation.</li>
<li><strong>(Pencil.)</strong> The heatmap labels columns by source characters even though each value is a recurrent prefix state. Give two reasons a delimiter state might carry useful month or day information. Then state one conclusion the heatmap supports and one conclusion it cannot support.</li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/shakeri-lab\.github\.io\/dl-book\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../chapters/part4/12-kernel-regression.html" class="pagination-link" aria-label="Kernel Regression: Attention Before It Was Learnable">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Kernel Regression: Attention Before It Was Learnable</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/part4/14-self-attention-transformer.html" class="pagination-link" aria-label="Self-Attention and the Transformer">
        <span class="nav-page-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Self-Attention and the Transformer</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Heman Shakeri · Text CC BY-NC-SA 4.0 · Code MIT · School of Data Science, University of Virginia</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/Shakeri-Lab/dl-book/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Companion to <a href="https://shakeri-lab.github.io/dl-course-site/">DS 6050 Deep Learning</a></p>
</div>
  </div>
</footer>




</body></html>