<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>14&nbsp; Self-Attention and the Transformer – Deep Learning: Making It Learnable</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/part4/15-bert-pretraining.html" rel="next">
<link href="../../chapters/part4/13-attention.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-c90f29e1247290e1dfbeb1da338aa877.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>
  // Book math macros — keep in sync with tex/macros.tex (PDF path).
  // MathJax reads this config because it is defined before the MathJax
  // script loads (Quarto places include-in-header above its math script).
  window.MathJax = {
    tex: {
      macros: {
        E: "\\mathbb{E}",
        Ex: "\\operatorname{E}",
        var: "\\operatorname{Var}",
        cov: "\\operatorname{Cov}",
        imp: "\\Rightarrow",
        argmax: "\\operatorname*{arg\\,max}",
        argmin: "\\operatorname*{arg\\,min}",
        norm: ["\\left\\lVert#1\\right\\rVert", 1],
        vect: ["\\mathbf{#1}", 1],
        matr: ["\\mathbf{#1}", 1],
        R: "\\mathbb{R}",
        dd: "\\mathrm{d}",
        loss: "\\mathcal{L}"
      }
    }
  };
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/part4/12-kernel-regression.html">IV · Attention: Learning the Similarity</a></li><li class="breadcrumb-item"><a href="../../chapters/part4/14-self-attention-transformer.html"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Self-Attention and the Transformer</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Deep Learning: Making It Learnable</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/Shakeri-Lab/dl-book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">I · From Lines to Networks</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/01-linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Linear Regression, the Mother Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/02-logistic-softmax.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Linear Models that Classify: Logistic and Softmax</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/03-nonlinearity-mlp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Nonlinearity and the MLP</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/04-training-loss-sgd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Training: Loss and Stochastic Gradient Descent</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/05-backpropagation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Backpropagation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/06-generalization-inductive-bias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">When It Fails: Generalization in Pictures, and Inductive Bias</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">II · Vision: Learning the Filters</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/07-filters-convolution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Filters and Convolution (Fixed Kernels)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/08-cnn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">CNNs: Making the Filters Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/09-modern-cnns-transfer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Modern CNNs and Transfer Learning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">III · Sequences</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part3/10-sequences-rnn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Sequences and Recurrence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part3/11-encoder-decoder.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Encoder–Decoder, Teacher Forcing, Beam Search</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">IV · Attention: Learning the Similarity</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/12-kernel-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Kernel Regression: Attention Before It Was Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/13-attention.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Attention: Making the Kernel Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/14-self-attention-transformer.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Self-Attention and the Transformer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/15-bert-pretraining.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">The BERT Moment: Pretraining as the New Regime</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/16-vit-scaling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Vision Transformers and Scaling Laws</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">V · The Pretrained Era</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/17-peft-quantization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Adapting Pretrained Models: Prompting, PEFT, Quantization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/18-alignment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Alignment and RL Fine-Tuning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/19-generative.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Generative Models: From PCA to Diffusion</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a1-linear-algebra.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Linear Algebra and the SVD</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a2-tensors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Tensors in Practice</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a3-precision-performance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Numerical Precision and Hardware Efficiency</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a4-notation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Notation</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#let-the-sequence-query-itself" id="toc-let-the-sequence-query-itself" class="nav-link active" data-scroll-target="#let-the-sequence-query-itself"><span class="header-section-number">14.1</span> Let the sequence query itself</a>
  <ul class="collapse">
  <li><a href="#the-position-debt" id="toc-the-position-debt" class="nav-link" data-scroll-target="#the-position-debt">The position debt</a></li>
  </ul></li>
  <li><a href="#position-as-a-bank-of-clocks" id="toc-position-as-a-bank-of-clocks" class="nav-link" data-scroll-target="#position-as-a-bank-of-clocks"><span class="header-section-number">14.2</span> Position as a bank of clocks</a></li>
  <li><a href="#one-routing-operation-many-heads" id="toc-one-routing-operation-many-heads" class="nav-link" data-scroll-target="#one-routing-operation-many-heads"><span class="header-section-number">14.3</span> One routing operation, many heads</a>
  <ul class="collapse">
  <li><a href="#the-mask-is-part-of-the-model" id="toc-the-mask-is-part-of-the-model" class="nav-link" data-scroll-target="#the-mask-is-part-of-the-model">The mask is part of the model</a></li>
  </ul></li>
  <li><a href="#build-a-transformer-block" id="toc-build-a-transformer-block" class="nav-link" data-scroll-target="#build-a-transformer-block"><span class="header-section-number">14.4</span> Build a Transformer block</a>
  <ul class="collapse">
  <li><a href="#the-residual-stream" id="toc-the-residual-stream" class="nav-link" data-scroll-target="#the-residual-stream">The residual stream</a></li>
  <li><a href="#the-position-wise-feed-forward-network" id="toc-the-position-wise-feed-forward-network" class="nav-link" data-scroll-target="#the-position-wise-feed-forward-network">The position-wise feed-forward network</a></li>
  </ul></li>
  <li><a href="#from-the-original-transformer-to-this-experiment" id="toc-from-the-original-transformer-to-this-experiment" class="nav-link" data-scroll-target="#from-the-original-transformer-to-this-experiment"><span class="header-section-number">14.5</span> From the original Transformer to this experiment</a></li>
  <li><a href="#the-book-reads-itself-again" id="toc-the-book-reads-itself-again" class="nav-link" data-scroll-target="#the-book-reads-itself-again"><span class="header-section-number">14.6</span> The book reads itself, again</a>
  <ul class="collapse">
  <li><a href="#what-did-the-heads-route" id="toc-what-did-the-heads-route" class="nav-link" data-scroll-target="#what-did-the-heads-route">What did the heads route?</a></li>
  <li><a href="#listen-but-do-not-grade-by-fluency" id="toc-listen-but-do-not-grade-by-fluency" class="nav-link" data-scroll-target="#listen-but-do-not-grade-by-fluency">Listen, but do not grade by fluency</a></li>
  </ul></li>
  <li><a href="#what-the-architecture-bought" id="toc-what-the-architecture-bought" class="nav-link" data-scroll-target="#what-the-architecture-bought"><span class="header-section-number">14.7</span> What the architecture bought</a></li>
  <li><a href="#okay-so" id="toc-okay-so" class="nav-link" data-scroll-target="#okay-so"><span class="header-section-number">14.8</span> Okay, so—</a></li>
  <li><a href="#sources-and-further-reading" id="toc-sources-and-further-reading" class="nav-link" data-scroll-target="#sources-and-further-reading">Sources and further reading</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/Shakeri-Lab/dl-book/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/part4/12-kernel-regression.html">IV · Attention: Learning the Similarity</a></li><li class="breadcrumb-item"><a href="../../chapters/part4/14-self-attention-transformer.html"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Self-Attention and the Transformer</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-14-self-attention-transformer" class="quarto-section-identifier"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Self-Attention and the Transformer</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<!-- lecture-source:
     m09_lecture-9-transformer_N4ePLi42ADk.txt
     [coding]_m09_lecture-9-2-transformer-part-2_tG8b2eNm6Gg.txt
     (spine via ds6050_09_transformer/MODULE_NOTES.md; scene compositions from
     that module's Manim source)
     seeds: sources/9.1-self-attention.tex,
            sources/9.A.1-positional_encoding.tex,
            sources/9.1A-Normalization_in_Transformers.tex
     primary sources: Vaswani et al. 2017; Ba et al. 2016;
                      Xiong et al. 2020; Geva et al. 2021;
                      Jain and Wallace 2019
     provenance note: all executable implementations were independently derived
     from the displayed equations. The book-corpus schedule is reconstructed from
     the book-original Chapter 10 cell. The experiment uses a custom decoder-only,
     pre-LayerNorm Transformer rather than the original encoder-decoder,
     post-LayerNorm architecture. It makes no measured hardware-speed claim. -->
<p><a href="13-attention.html" class="quarto-xref"><span>Chapter 13</span></a> ended with a question that the attention operator itself had already answered. A query, key, and value need not come from an encoder or a decoder. They need not come from a recurrent network at all. If all three come from the same sequence, each token can ask every token—including itself—what matters and route the answers directly. The recurrent state—the last serial bottleneck left standing—becomes optional.</p>
<p>That substitution is the core of a <em>Transformer</em>. It is also easy to state too quickly. Removing recurrence creates a position problem. Splitting one attention operation into heads creates a bookkeeping problem. Stacking the resulting operations creates an optimization problem. This chapter solves each one—from the equations outward—then returns to the book-corpus benchmark from <a href="../part3/10-sequences-rnn.html" class="quarto-xref"><span>Chapter 10</span></a> with a deliberately small causal Transformer.</p>
<!-- NOVEL: needs sign-off - opening preview of the seeded book-corpus rematch. -->
<p>Here is the result we have to explain on the same 14,860-character held-out tail. In one exactly matched seed, positional encoding improves the Transformer’s loss from 2.3405 to 1.9190. Yet Chapter 10’s compact LSTM remains better at 1.8881. The new architecture has learned, and position matters in this run—but at this scale, the LSTM still wins.</p>
<!-- /NOVEL -->
<section id="let-the-sequence-query-itself" class="level2" data-number="14.1">
<h2 data-number="14.1" class="anchored" data-anchor-id="let-the-sequence-query-itself"><span class="header-section-number">14.1</span> Let the sequence query itself</h2>
<p>Suppose the sentence contains the words <em>bank</em>, <em>river</em>, and <em>boats</em>. A useful representation of <em>bank</em> should route information from <em>river</em> and <em>boats</em>, while another occurrence—now near <em>loan</em> and <em>interest</em>—should route different information. Chapter 13 built exactly this kind of content-dependent routing. Self-attention changes only the source of the three inputs.</p>
<p>The lecture’s three questions still fit: a query asks “what am I looking for?”, a key advertises “what do I offer?”, and a value carries “what information do I contain?”</p>
<p>Let a batch of token representations be</p>
<p><span class="math display">\[
X \in \mathbb{R}^{B \times n \times d},
\]</span></p>
<p>where <span class="math inline">\(B\)</span> is batch size, <span class="math inline">\(n\)</span> is sequence length, and <span class="math inline">\(d\)</span> is model width. Learned projections produce</p>
<p><span class="math display">\[
Q=XW_Q,\qquad K=XW_K,\qquad V=XW_V,
\]</span></p>
<p>with <span class="math inline">\(W_Q,W_K,W_V\in\mathbb{R}^{d\times d}\)</span>. Scaled dot-product attention is</p>
<p><span class="math display">\[
\operatorname{Attention}(Q,K,V)
=
\operatorname{softmax}\left(\frac{QK^\top}{\sqrt d}\right)V.
\]</span></p>
<p>For one sequence, <span class="math inline">\(QK^\top\)</span> has shape <span class="math inline">\(n\times n\)</span>. Row <span class="math inline">\(i\)</span> contains the scores from query position <span class="math inline">\(i\)</span> to every key position <span class="math inline">\(j\)</span>. The row-wise softmax makes each row a distribution, and multiplying by <span class="math inline">\(V\)</span> returns one weighted sum for each query:</p>
<p><span class="math display">\[
(n,d)(d,n)\to(n,n),\qquad (n,n)(n,d)\to(n,d).
\]</span></p>
<p>Chapter 10 named time as the book’s third sharing axis. An RNN shares one transition rule across time. Self-attention keeps that stationarity and extends the shared rule across every ordered pair of positions. The weights in a particular attention row still depend on the content; what is shared is the machinery that produces them.</p>
<p>All query positions can be evaluated together during training because none waits for a hidden state from the preceding position. That is a structural statement—not a timing result. Dense self-attention still forms <span class="math inline">\(n^2\)</span> pairwise scores, and autoregressive generation still emits one new token at a time.</p>
<section id="the-position-debt" class="level3">
<h3 class="anchored" data-anchor-id="the-position-debt">The position debt</h3>
<p>Bare self-attention knows content but not slot number. A precise proof is more useful than the slogan.</p>
<p>Let <span class="math inline">\(P\)</span> be an <span class="math inline">\(n\times n\)</span> permutation matrix, so <span class="math inline">\(PX\)</span> reorders the tokens. Then</p>
<p><span class="math display">\[
Q'=PQ,\quad K'=PK,\quad V'=PV
\]</span></p>
<p>and therefore</p>
<p><span class="math display">\[
Q'K'^\top=P(QK^\top)P^\top.
\]</span></p>
<p>Write <span class="math inline">\(S=QK^\top/\sqrt d\)</span>; then <span class="math inline">\(S'=PSP^\top\)</span>. Row-wise softmax respects the same simultaneous row-and-column permutation:</p>
<p><span class="math display">\[
\operatorname{softmax}(PSP^\top)
=P\operatorname{softmax}(S)P^\top.
\]</span></p>
<p>Putting the pieces together gives</p>
<p><span class="math display">\[
\operatorname{SA}(PX)
=P\operatorname{SA}(X).
\]</span></p>
<p>Self-attention is <em>permutation equivariant</em>: permute the inputs and the outputs permute in the same way. It is not permutation invariant—the token outputs do not all become identical. But without another signal, the operator has no basis for distinguishing “first” from “fifth.” A pooled sequence summary can consequently become invariant to order.</p>
<p><a href="../part2/08-cnn.html" class="quarto-xref"><span>Chapter 8</span></a> planted this debt when convolution received locality “for free.” A convolution knows which values are neighbors because its kernel is tied to nearby offsets. Global attention abandons that built-in geometry—so we must pay to put position back in.</p>
<!-- NOVEL: needs sign-off - seeded permutation/position audits and figures. -->
<div id="cell-fig-permutation-debt" class="cell" data-fig-height="3.4" data-fig-width="10" data-execution_count="1">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> math</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> numpy_attention(x: np.ndarray) <span class="op">-&gt;</span> np.ndarray:</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    scores <span class="op">=</span> x <span class="op">@</span> x.T <span class="op">/</span> math.sqrt(x.shape[<span class="op">-</span><span class="dv">1</span>])</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    scores <span class="op">=</span> scores <span class="op">-</span> scores.<span class="bu">max</span>(axis<span class="op">=-</span><span class="dv">1</span>, keepdims<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    weights <span class="op">=</span> np.exp(scores)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    weights <span class="op">=</span> weights <span class="op">/</span> weights.<span class="bu">sum</span>(axis<span class="op">=-</span><span class="dv">1</span>, keepdims<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> weights <span class="op">@</span> x</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> numpy_positions(length: <span class="bu">int</span>, width: <span class="bu">int</span>) <span class="op">-&gt;</span> np.ndarray:</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    position <span class="op">=</span> np.arange(length)[:, <span class="va">None</span>]</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    frequency <span class="op">=</span> np.exp(</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>        np.arange(<span class="dv">0</span>, width, <span class="dv">2</span>) <span class="op">*</span> (<span class="op">-</span>math.log(<span class="fl">10_000.0</span>) <span class="op">/</span> width)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    pe <span class="op">=</span> np.zeros((length, width))</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    pe[:, <span class="dv">0</span>::<span class="dv">2</span>] <span class="op">=</span> np.sin(position <span class="op">*</span> frequency)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    pe[:, <span class="dv">1</span>::<span class="dv">2</span>] <span class="op">=</span> np.cos(position <span class="op">*</span> frequency)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> pe</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">6050</span>)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> rng.normal(size<span class="op">=</span>(<span class="dv">5</span>, <span class="dv">8</span>))</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>permutation <span class="op">=</span> np.array([<span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">3</span>])</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>bare_error <span class="op">=</span> np.<span class="bu">abs</span>(</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>    numpy_attention(x[permutation]) <span class="op">-</span> numpy_attention(x)[permutation]</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>).<span class="bu">max</span>()</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>pe <span class="op">=</span> numpy_positions(<span class="dv">5</span>, <span class="dv">8</span>)</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>with_position <span class="op">=</span> numpy_attention(x <span class="op">+</span> pe)</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>fixed_slot_change <span class="op">=</span> np.<span class="bu">abs</span>(</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>    numpy_attention(x[permutation] <span class="op">+</span> pe) <span class="op">-</span> with_position[permutation]</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>).<span class="bu">max</span>()</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>)</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>token_ids <span class="op">=</span> np.arange(<span class="dv">5</span>)</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>tokens <span class="op">=</span> np.array([<span class="st">"bank"</span>, <span class="st">"by"</span>, <span class="st">"the"</span>, <span class="st">"river"</span>, <span class="st">"."</span>])</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].imshow(</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>    np.stack([token_ids, token_ids[permutation]]),</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>    cmap<span class="op">=</span><span class="st">"tab10"</span>, aspect<span class="op">=</span><span class="st">"auto"</span>, vmin<span class="op">=</span><span class="dv">0</span>, vmax<span class="op">=</span><span class="dv">9</span>,</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> row, order <span class="kw">in</span> <span class="bu">enumerate</span>([token_ids, token_ids[permutation]]):</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> column, token_id <span class="kw">in</span> <span class="bu">enumerate</span>(order):</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>        axes[<span class="dv">0</span>].text(column, row, tokens[token_id], ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"center"</span>)</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_yticks([<span class="dv">0</span>, <span class="dv">1</span>], [<span class="st">"$X$"</span>, <span class="st">"$PX$"</span>])</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xticks(<span class="bu">range</span>(<span class="dv">5</span>), [<span class="ss">f"slot </span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">"</span> <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">5</span>)])</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">"content moves with the permutation"</span>)</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].bar(</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>    [<span class="st">"bare equivariance</span><span class="ch">\n</span><span class="st">error"</span>, <span class="st">"+ fixed position</span><span class="ch">\n</span><span class="st">difference"</span>],</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>    [bare_error, fixed_slot_change],</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span>[<span class="st">"#6b7280"</span>, <span class="st">"#d37b29"</span>],</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_yscale(<span class="st">"log"</span>)</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_ylabel(<span class="st">"maximum rematched difference"</span>)</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">"position breaks the rematch"</span>)</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"bare permutation-equivariance error: </span><span class="sc">{</span>bare_error<span class="sc">:.2e}</span><span class="ss">"</span>)</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"fixed-slot difference after adding position: </span><span class="sc">{</span>fixed_slot_change<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-permutation-debt" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-permutation-debt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="14-self-attention-transformer_files/figure-html/fig-permutation-debt-output-1.png" width="662" height="469" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-permutation-debt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.1: The same content is permuted across slots (left). The audit (right) shows bare self-attention rematches after the same output permutation, while fixed positional signals break that rematch.
</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>bare permutation-equivariance error: 2.22e-16
fixed-slot difference after adding position: 1.581</code></pre>
</div>
</div>
<p>The first error is numerical roundoff, about <span class="math inline">\(2.2\times10^{-16}\)</span>. Adding a fixed signal to each slot changes the rematched outputs by about 1.581 in this example. Position has not been inferred from content; it has been supplied.</p>
</section>
</section>
<section id="position-as-a-bank-of-clocks" class="level2" data-number="14.2">
<h2 data-number="14.2" class="anchored" data-anchor-id="position-as-a-bank-of-clocks"><span class="header-section-number">14.2</span> Position as a bank of clocks</h2>
<p>The simplest additive code repeats <span class="math inline">\(i/(n-1)\)</span> in every coordinate. It supplies order, but every position vector lies on the same ray and differs only in magnitude; attention receives no multidirectional geometry. A binary code supplies more coordinates, yet adjacent integers can flip many bits and have poor locality. These are not impossible designs—they are weak inductive biases for a model that must reason about shifts and distances.</p>
<p>Sinusoidal encoding gives every position a bank of clocks. For even model width <span class="math inline">\(d\)</span>, define</p>
<p><span class="math display">\[
\begin{aligned}
\operatorname{PE}(i,2j)
&amp;=\sin\left(i\,10000^{-2j/d}\right),\\
\operatorname{PE}(i,2j+1)
&amp;=\cos\left(i\,10000^{-2j/d}\right).
\end{aligned}
\]</span></p>
<p>Small <span class="math inline">\(j\)</span> gives a fast clock; large <span class="math inline">\(j\)</span> gives a slow one. Every sine coordinate is paired with a cosine at the same frequency. The model receives</p>
<p><span class="math display">\[
Z_i=\sqrt d\,E_i+\operatorname{PE}(i),
\]</span></p>
<p>where <span class="math inline">\(E_i\)</span> is the token embedding. Scaling the embedding keeps its initial magnitude commensurate with the position vector.</p>
<p>Why pair sine and cosine? For frequency <span class="math inline">\(\omega\)</span>, advancing by offset <span class="math inline">\(\delta\)</span> is a rotation—an algebraic answer to a geometric question:</p>
<p><span class="math display">\[
\begin{bmatrix}
\sin((i+\delta)\omega)\\
\cos((i+\delta)\omega)
\end{bmatrix}
=
\begin{bmatrix}
\cos(\delta\omega)&amp;\sin(\delta\omega)\\
-\sin(\delta\omega)&amp;\cos(\delta\omega)
\end{bmatrix}
\begin{bmatrix}
\sin(i\omega)\\
\cos(i\omega)
\end{bmatrix}.
\]</span></p>
<p>The rotation depends on the offset, not the absolute position. This gives learned linear maps a convenient raw material for representing relative shifts. It is a property of the positional pair itself—not a guarantee that arbitrary learned <span class="math inline">\(W_Q\)</span> and <span class="math inline">\(W_K\)</span> will preserve or use it.</p>
<div id="cell-fig-position-build" class="cell" data-fig-height="5" data-fig-width="10" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>pe <span class="op">=</span> numpy_positions(<span class="dv">100</span>, <span class="dv">32</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>delta <span class="op">=</span> <span class="dv">7</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>j <span class="op">=</span> <span class="dv">5</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>omega <span class="op">=</span> <span class="dv">10_000</span> <span class="op">**</span> (<span class="op">-</span><span class="dv">2</span> <span class="op">*</span> j <span class="op">/</span> <span class="dv">32</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>rotation <span class="op">=</span> np.array([</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    [np.cos(delta <span class="op">*</span> omega), np.sin(delta <span class="op">*</span> omega)],</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    [<span class="op">-</span>np.sin(delta <span class="op">*</span> omega), np.cos(delta <span class="op">*</span> omega)],</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>pair_i <span class="op">=</span> pe[<span class="dv">13</span>, <span class="dv">2</span> <span class="op">*</span> j : <span class="dv">2</span> <span class="op">*</span> j <span class="op">+</span> <span class="dv">2</span>]</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>pair_shifted <span class="op">=</span> pe[<span class="dv">13</span> <span class="op">+</span> delta, <span class="dv">2</span> <span class="op">*</span> j : <span class="dv">2</span> <span class="op">*</span> j <span class="op">+</span> <span class="dv">2</span>]</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>rotation_error <span class="op">=</span> np.<span class="bu">abs</span>(rotation <span class="op">@</span> pair_i <span class="op">-</span> pair_shifted).<span class="bu">max</span>()</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>norm_error <span class="op">=</span> np.<span class="bu">abs</span>(np.linalg.norm(pe, axis<span class="op">=</span><span class="dv">1</span>) <span class="op">-</span> <span class="fl">4.0</span>).<span class="bu">max</span>()</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>    <span class="dv">2</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">5</span>), gridspec_kw<span class="op">=</span>{<span class="st">"height_ratios"</span>: [<span class="dv">1</span>, <span class="dv">2</span>]}</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">0</span>].plot(pe[:, <span class="dv">0</span>], label<span class="op">=</span><span class="st">"sin"</span>)</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">0</span>].plot(pe[:, <span class="dv">1</span>], label<span class="op">=</span><span class="st">"cos"</span>)</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">0</span>].set_title(<span class="st">"fast clock: coordinates 0–1"</span>)</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">0</span>].legend(frameon<span class="op">=</span><span class="va">False</span>, ncol<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">1</span>].plot(pe[:, <span class="dv">20</span>], label<span class="op">=</span><span class="st">"sin"</span>)</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">1</span>].plot(pe[:, <span class="dv">21</span>], label<span class="op">=</span><span class="st">"cos"</span>)</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">1</span>].set_title(<span class="st">"slow clock: coordinates 20–21"</span>)</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">1</span>].legend(frameon<span class="op">=</span><span class="va">False</span>, ncol<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>heat <span class="op">=</span> axes[<span class="dv">1</span>, <span class="dv">0</span>].imshow(pe.T, aspect<span class="op">=</span><span class="st">"auto"</span>, cmap<span class="op">=</span><span class="st">"coolwarm"</span>, vmin<span class="op">=-</span><span class="dv">1</span>, vmax<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">0</span>].set_xlabel(<span class="st">"position"</span>)</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">0</span>].set_ylabel(<span class="st">"coordinate"</span>)</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">0</span>].set_title(<span class="st">"the complete position code"</span>)</span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a>fig.colorbar(heat, ax<span class="op">=</span>axes[<span class="dv">1</span>, <span class="dv">0</span>], fraction<span class="op">=</span><span class="fl">0.05</span>)</span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib.patches <span class="im">import</span> FancyArrowPatch</span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a>angles <span class="op">=</span> np.arange(<span class="dv">0</span>, <span class="dv">2</span> <span class="op">*</span> np.pi, <span class="fl">0.01</span>)</span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">1</span>].plot(np.sin(angles), np.cos(angles), color<span class="op">=</span><span class="st">"0.8"</span>)</span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">1</span>].scatter(<span class="op">*</span>pair_i, label<span class="op">=</span><span class="st">"position 13"</span>)</span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">1</span>].scatter(<span class="op">*</span>pair_shifted, label<span class="op">=</span><span class="ss">f"position </span><span class="sc">{</span><span class="dv">13</span> <span class="op">+</span> delta<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">1</span>].plot([<span class="dv">0</span>, pair_i[<span class="dv">0</span>]], [<span class="dv">0</span>, pair_i[<span class="dv">1</span>]], color<span class="op">=</span><span class="st">"0.4"</span>)</span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">1</span>].plot([<span class="dv">0</span>, pair_shifted[<span class="dv">0</span>]], [<span class="dv">0</span>, pair_shifted[<span class="dv">1</span>]], color<span class="op">=</span><span class="st">"0.4"</span>)</span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">1</span>].add_patch(</span>
<span id="cb3-42"><a href="#cb3-42" aria-hidden="true" tabindex="-1"></a>    FancyArrowPatch(</span>
<span id="cb3-43"><a href="#cb3-43" aria-hidden="true" tabindex="-1"></a>        pair_i,</span>
<span id="cb3-44"><a href="#cb3-44" aria-hidden="true" tabindex="-1"></a>        pair_shifted,</span>
<span id="cb3-45"><a href="#cb3-45" aria-hidden="true" tabindex="-1"></a>        connectionstyle<span class="op">=</span><span class="st">"arc3,rad=0.25"</span>,</span>
<span id="cb3-46"><a href="#cb3-46" aria-hidden="true" tabindex="-1"></a>        arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>,</span>
<span id="cb3-47"><a href="#cb3-47" aria-hidden="true" tabindex="-1"></a>        mutation_scale<span class="op">=</span><span class="dv">12</span>,</span>
<span id="cb3-48"><a href="#cb3-48" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span><span class="st">"black"</span>,</span>
<span id="cb3-49"><a href="#cb3-49" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb3-50"><a href="#cb3-50" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-51"><a href="#cb3-51" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">1</span>].axis(<span class="st">"equal"</span>)</span>
<span id="cb3-52"><a href="#cb3-52" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">1</span>].set_title(<span class="ss">f"offset </span><span class="sc">{</span>delta<span class="sc">}</span><span class="ss"> is a rotation"</span>)</span>
<span id="cb3-53"><a href="#cb3-53" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">1</span>].legend(frameon<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb3-54"><a href="#cb3-54" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb3-55"><a href="#cb3-55" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb3-56"><a href="#cb3-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-57"><a href="#cb3-57" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"rotation identity maximum error: </span><span class="sc">{</span>rotation_error<span class="sc">:.2e}</span><span class="ss">"</span>)</span>
<span id="cb3-58"><a href="#cb3-58" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"constant position-vector norm maximum error: </span><span class="sc">{</span>norm_error<span class="sc">:.2e}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-position-build" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-position-build-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="14-self-attention-transformer_files/figure-html/fig-position-build-output-1.png" width="951" height="471" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-position-build-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.2: Sinusoidal position is a bank of clocks. Fast coordinates track local offsets; slow coordinates vary across longer ranges. Each sine/cosine pair acts like a clock, and a fixed offset rotates that pair by a start-independent angle.
</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>rotation identity maximum error: 1.11e-16
constant position-vector norm maximum error: 0.00e+00</code></pre>
</div>
</div>
<p>For <span class="math inline">\(d=32\)</span>, each position vector has norm <span class="math inline">\(\sqrt{d/2}=4\)</span> because every <span class="math inline">\(\sin^2+\cos^2\)</span> pair contributes one. Adding this vector does <em>not</em> preserve the norm of the combined token representation—the embedding and position vector can reinforce or cancel one another. Layer normalization will soon manage scale at the block level.</p>
<!-- /NOVEL -->
</section>
<section id="one-routing-operation-many-heads" class="level2" data-number="14.3">
<h2 data-number="14.3" class="anchored" data-anchor-id="one-routing-operation-many-heads"><span class="header-section-number">14.3</span> One routing operation, many heads</h2>
<p>A single attention distribution must make one compromise about what to retrieve. Multi-head attention lets several smaller routing systems—separate views of the same residual stream—operate in parallel. Choose a number of heads <span class="math inline">\(h\)</span> that divides <span class="math inline">\(d\)</span>, and let <span class="math inline">\(d_h=d/h\)</span>. For each head <span class="math inline">\(r\)</span>,</p>
<p><span class="math display">\[
Q_r=XW_Q^{(r)},\quad
K_r=XW_K^{(r)},\quad
V_r=XW_V^{(r)},
\]</span></p>
<p>where <span class="math inline">\(W_Q^{(r)},W_K^{(r)},W_V^{(r)}\in\mathbb{R}^{d\times d_h}\)</span>. The head output is</p>
<p><span class="math display">\[
H_r=
\operatorname{softmax}\left(
\frac{Q_rK_r^\top}{\sqrt{d_h}}+M
\right)V_r.
\]</span></p>
<p>Here <span class="math inline">\(M\)</span> is the visibility mask defined next; <span class="math inline">\(M=0\)</span> for unmasked attention.</p>
<p>The complete operation concatenates the heads and mixes them:</p>
<p><span class="math display">\[
\operatorname{MHA}(X)
=\operatorname{Concat}(H_1,\ldots,H_h)W_O,
\qquad W_O\in\mathbb{R}^{d\times d}.
\]</span></p>
<p>The shape ledger is the safest implementation guide:</p>
<p><span class="math display">\[
(B,n,d)
\to(B,h,n,d_h)
\to(B,h,n,n)
\to(B,h,n,d_h)
\to(B,n,d).
\]</span></p>
<p>Scaling uses <span class="math inline">\(\sqrt{d_h}\)</span>, not <span class="math inline">\(\sqrt d\)</span>, because a head’s dot product sums <span class="math inline">\(d_h\)</span> terms. With fixed <span class="math inline">\(d\)</span>, splitting into heads does not multiply the leading projection count: <span class="math inline">\(W_Q,W_K,W_V,W_O\)</span> together contribute about <span class="math inline">\(4d^2\)</span> weights regardless of <span class="math inline">\(h\)</span>. Heads divide the representational subspace—they do not each receive a fresh width-<span class="math inline">\(d\)</span> model.</p>
<section id="the-mask-is-part-of-the-model" class="level3">
<h3 class="anchored" data-anchor-id="the-mask-is-part-of-the-model">The mask is part of the model</h3>
<p><a href="../part3/11-encoder-decoder.html" class="quarto-xref"><span>Chapter 11</span></a> called masking the rule that tells a model <em>which positions it may not look at</em>. Here that rule is causal: position <span class="math inline">\(i\)</span> may use tokens at positions <span class="math inline">\(j\le i\)</span> but must not inspect future tokens <span class="math inline">\(j&gt;i\)</span>. Rows are queries and columns are keys, so the forbidden region is the strict upper triangle. We add</p>
<p><span class="math display">\[
M_{ij}=
\begin{cases}
0,&amp;j\le i,\\
-\infty,&amp;j&gt;i
\end{cases}
\]</span></p>
<p><em>before</em> softmax. Replacing forbidden probabilities with zero afterward would leave the remaining row unnormalized. Masking every key in a row is invalid—softmax would receive only negative infinity. Here the diagonal remains visible: the representation at a character may use that character while predicting the next one.</p>
<!-- NOVEL: needs sign-off - independent causal multi-head implementation and mask audit. -->
<div id="cell-fig-causal-multihead" class="cell" data-fig-height="7" data-fig-width="10" data-execution_count="3">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> torch <span class="im">import</span> nn</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib.patches <span class="im">import</span> FancyBboxPatch</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> CausalMultiHeadAttention(nn.Module):</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, width: <span class="bu">int</span>, heads: <span class="bu">int</span>) <span class="op">-&gt;</span> <span class="va">None</span>:</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> width <span class="op">%</span> heads <span class="op">!=</span> <span class="dv">0</span>:</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>            <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="st">"width must be divisible by heads"</span>)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.heads <span class="op">=</span> heads</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.head_width <span class="op">=</span> width <span class="op">//</span> heads</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.qkv <span class="op">=</span> nn.Linear(width, <span class="dv">3</span> <span class="op">*</span> width)</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.project <span class="op">=</span> nn.Linear(width, width)</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>        nn.init.xavier_uniform_(<span class="va">self</span>.qkv.weight)</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>        nn.init.zeros_(<span class="va">self</span>.qkv.bias)</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x: torch.Tensor, return_weights: <span class="bu">bool</span> <span class="op">=</span> <span class="va">False</span>):</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>        batch, length, width <span class="op">=</span> x.shape</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>        qkv <span class="op">=</span> <span class="va">self</span>.qkv(x)</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>        qkv <span class="op">=</span> qkv.reshape(</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>            batch, length, <span class="dv">3</span>, <span class="va">self</span>.heads, <span class="va">self</span>.head_width</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>        ).permute(<span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">4</span>)</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>        q, k, v <span class="op">=</span> qkv.unbind(dim<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>        scores <span class="op">=</span> q <span class="op">@</span> k.transpose(<span class="op">-</span><span class="dv">2</span>, <span class="op">-</span><span class="dv">1</span>) <span class="op">/</span> math.sqrt(<span class="va">self</span>.head_width)</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>        forbidden <span class="op">=</span> torch.triu(</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>            torch.ones(length, length, dtype<span class="op">=</span>torch.<span class="bu">bool</span>, device<span class="op">=</span>x.device),</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>            diagonal<span class="op">=</span><span class="dv">1</span>,</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>        scores <span class="op">=</span> scores.masked_fill(forbidden, <span class="bu">float</span>(<span class="st">"-inf"</span>))</span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>        weights <span class="op">=</span> torch.softmax(scores, dim<span class="op">=-</span><span class="dv">1</span>)</span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>        routed <span class="op">=</span> weights <span class="op">@</span> v</span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>        routed <span class="op">=</span> routed.transpose(<span class="dv">1</span>, <span class="dv">2</span>).reshape(batch, length, width)</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>        output <span class="op">=</span> <span class="va">self</span>.project(routed)</span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> return_weights:</span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a>            <span class="cf">return</span> output, weights</span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> output</span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a>torch.manual_seed(<span class="dv">6050</span>)</span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a>demo_attention <span class="op">=</span> CausalMultiHeadAttention(width<span class="op">=</span><span class="dv">32</span>, heads<span class="op">=</span><span class="dv">4</span>)</span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a>demo_x <span class="op">=</span> torch.randn(<span class="dv">1</span>, <span class="dv">12</span>, <span class="dv">32</span>)</span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a>_, demo_weights <span class="op">=</span> demo_attention(demo_x, return_weights<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a>future <span class="op">=</span> torch.triu(torch.ones(<span class="dv">12</span>, <span class="dv">12</span>, dtype<span class="op">=</span>torch.<span class="bu">bool</span>), diagonal<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> demo_weights[<span class="dv">0</span>, :, future].<span class="bu">max</span>().item() <span class="op">==</span> <span class="fl">0.0</span></span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> torch.allclose(</span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a>    demo_weights.<span class="bu">sum</span>(dim<span class="op">=-</span><span class="dv">1</span>),</span>
<span id="cb5-47"><a href="#cb5-47" aria-hidden="true" tabindex="-1"></a>    torch.ones_like(demo_weights.<span class="bu">sum</span>(dim<span class="op">=-</span><span class="dv">1</span>)),</span>
<span id="cb5-48"><a href="#cb5-48" aria-hidden="true" tabindex="-1"></a>    atol<span class="op">=</span><span class="fl">1e-6</span>,</span>
<span id="cb5-49"><a href="#cb5-49" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-50"><a href="#cb5-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-51"><a href="#cb5-51" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">7</span>), layout<span class="op">=</span><span class="st">"constrained"</span>)</span>
<span id="cb5-52"><a href="#cb5-52" aria-hidden="true" tabindex="-1"></a>grid <span class="op">=</span> fig.add_gridspec(<span class="dv">2</span>, <span class="dv">4</span>, height_ratios<span class="op">=</span>[<span class="dv">1</span>, <span class="dv">3</span>])</span>
<span id="cb5-53"><a href="#cb5-53" aria-hidden="true" tabindex="-1"></a>flow_axis <span class="op">=</span> fig.add_subplot(grid[<span class="dv">0</span>, :])</span>
<span id="cb5-54"><a href="#cb5-54" aria-hidden="true" tabindex="-1"></a>flow_axis.set_xlim(<span class="dv">0</span>, <span class="dv">10</span>)</span>
<span id="cb5-55"><a href="#cb5-55" aria-hidden="true" tabindex="-1"></a>flow_axis.set_ylim(<span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb5-56"><a href="#cb5-56" aria-hidden="true" tabindex="-1"></a>flow_axis.axis(<span class="st">"off"</span>)</span>
<span id="cb5-57"><a href="#cb5-57" aria-hidden="true" tabindex="-1"></a>flow <span class="op">=</span> [</span>
<span id="cb5-58"><a href="#cb5-58" aria-hidden="true" tabindex="-1"></a>    (<span class="fl">0.1</span>, <span class="st">"$X$"</span>, <span class="st">"#d8ecff"</span>),</span>
<span id="cb5-59"><a href="#cb5-59" aria-hidden="true" tabindex="-1"></a>    (<span class="fl">2.1</span>, <span class="st">"split $Q,K,V$</span><span class="ch">\n</span><span class="st">into $h$ heads"</span>, <span class="st">"#f9dfb5"</span>),</span>
<span id="cb5-60"><a href="#cb5-60" aria-hidden="true" tabindex="-1"></a>    (<span class="fl">4.5</span>, <span class="st">"$h$ attention</span><span class="ch">\n</span><span class="st">routes"</span>, <span class="st">"#f9dfb5"</span>),</span>
<span id="cb5-61"><a href="#cb5-61" aria-hidden="true" tabindex="-1"></a>    (<span class="fl">6.9</span>, <span class="st">"concatenate"</span>, <span class="st">"#d9f2d0"</span>),</span>
<span id="cb5-62"><a href="#cb5-62" aria-hidden="true" tabindex="-1"></a>    (<span class="fl">8.7</span>, <span class="st">"$W_O$"</span>, <span class="st">"#d9f2d0"</span>),</span>
<span id="cb5-63"><a href="#cb5-63" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb5-64"><a href="#cb5-64" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> index, (left, label, color) <span class="kw">in</span> <span class="bu">enumerate</span>(flow):</span>
<span id="cb5-65"><a href="#cb5-65" aria-hidden="true" tabindex="-1"></a>    width <span class="op">=</span> <span class="fl">1.2</span> <span class="cf">if</span> index <span class="kw">in</span> [<span class="dv">0</span>, <span class="dv">4</span>] <span class="cf">else</span> <span class="fl">1.7</span></span>
<span id="cb5-66"><a href="#cb5-66" aria-hidden="true" tabindex="-1"></a>    flow_axis.add_patch(FancyBboxPatch(</span>
<span id="cb5-67"><a href="#cb5-67" aria-hidden="true" tabindex="-1"></a>        (left, <span class="fl">0.2</span>), width, <span class="fl">0.6</span>,</span>
<span id="cb5-68"><a href="#cb5-68" aria-hidden="true" tabindex="-1"></a>        boxstyle<span class="op">=</span><span class="st">"round,pad=0.05"</span>,</span>
<span id="cb5-69"><a href="#cb5-69" aria-hidden="true" tabindex="-1"></a>        facecolor<span class="op">=</span>color, edgecolor<span class="op">=</span><span class="st">"0.25"</span>,</span>
<span id="cb5-70"><a href="#cb5-70" aria-hidden="true" tabindex="-1"></a>    ))</span>
<span id="cb5-71"><a href="#cb5-71" aria-hidden="true" tabindex="-1"></a>    flow_axis.text(left <span class="op">+</span> width <span class="op">/</span> <span class="dv">2</span>, <span class="fl">0.5</span>, label, ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"center"</span>)</span>
<span id="cb5-72"><a href="#cb5-72" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> index <span class="op">&lt;</span> <span class="bu">len</span>(flow) <span class="op">-</span> <span class="dv">1</span>:</span>
<span id="cb5-73"><a href="#cb5-73" aria-hidden="true" tabindex="-1"></a>        next_left <span class="op">=</span> flow[index <span class="op">+</span> <span class="dv">1</span>][<span class="dv">0</span>]</span>
<span id="cb5-74"><a href="#cb5-74" aria-hidden="true" tabindex="-1"></a>        flow_axis.annotate(</span>
<span id="cb5-75"><a href="#cb5-75" aria-hidden="true" tabindex="-1"></a>            <span class="st">""</span>, xy<span class="op">=</span>(next_left, <span class="fl">0.5</span>), xytext<span class="op">=</span>(left <span class="op">+</span> width, <span class="fl">0.5</span>),</span>
<span id="cb5-76"><a href="#cb5-76" aria-hidden="true" tabindex="-1"></a>            arrowprops<span class="op">=</span>{<span class="st">"arrowstyle"</span>: <span class="st">"-&gt;"</span>, <span class="st">"color"</span>: <span class="st">"0.25"</span>},</span>
<span id="cb5-77"><a href="#cb5-77" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb5-78"><a href="#cb5-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-79"><a href="#cb5-79" aria-hidden="true" tabindex="-1"></a>axes <span class="op">=</span> [fig.add_subplot(grid[<span class="dv">1</span>, head]) <span class="cf">for</span> head <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">4</span>)]</span>
<span id="cb5-80"><a href="#cb5-80" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> head, axis <span class="kw">in</span> <span class="bu">enumerate</span>(axes):</span>
<span id="cb5-81"><a href="#cb5-81" aria-hidden="true" tabindex="-1"></a>    image <span class="op">=</span> axis.imshow(</span>
<span id="cb5-82"><a href="#cb5-82" aria-hidden="true" tabindex="-1"></a>        demo_weights[<span class="dv">0</span>, head].detach().numpy(),</span>
<span id="cb5-83"><a href="#cb5-83" aria-hidden="true" tabindex="-1"></a>        cmap<span class="op">=</span><span class="st">"viridis"</span>, vmin<span class="op">=</span><span class="dv">0</span>, vmax<span class="op">=</span><span class="dv">1</span>,</span>
<span id="cb5-84"><a href="#cb5-84" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb5-85"><a href="#cb5-85" aria-hidden="true" tabindex="-1"></a>    axis.set_title(<span class="ss">f"head </span><span class="sc">{</span>head <span class="op">+</span> <span class="dv">1</span><span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb5-86"><a href="#cb5-86" aria-hidden="true" tabindex="-1"></a>    axis.set_xlabel(<span class="st">"key position"</span>)</span>
<span id="cb5-87"><a href="#cb5-87" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> head <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb5-88"><a href="#cb5-88" aria-hidden="true" tabindex="-1"></a>        axis.set_ylabel(<span class="st">"query position"</span>)</span>
<span id="cb5-89"><a href="#cb5-89" aria-hidden="true" tabindex="-1"></a>fig.colorbar(image, ax<span class="op">=</span>axes, fraction<span class="op">=</span><span class="fl">0.025</span>)</span>
<span id="cb5-90"><a href="#cb5-90" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb5-91"><a href="#cb5-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-92"><a href="#cb5-92" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"maximum forbidden attention:"</span>, demo_weights[<span class="dv">0</span>, :, future].<span class="bu">max</span>().item())</span>
<span id="cb5-93"><a href="#cb5-93" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(</span>
<span id="cb5-94"><a href="#cb5-94" aria-hidden="true" tabindex="-1"></a>    <span class="st">"maximum row-sum error:"</span>,</span>
<span id="cb5-95"><a href="#cb5-95" aria-hidden="true" tabindex="-1"></a>    (demo_weights.<span class="bu">sum</span>(dim<span class="op">=-</span><span class="dv">1</span>) <span class="op">-</span> <span class="dv">1</span>).<span class="bu">abs</span>().<span class="bu">max</span>().item(),</span>
<span id="cb5-96"><a href="#cb5-96" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-causal-multihead" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-causal-multihead-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="14-self-attention-transformer_files/figure-html/fig-causal-multihead-output-1.png" width="969" height="649" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-causal-multihead-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.3: Multi-head attention splits, routes in parallel, concatenates, and projects (top). In the untrained causal heads below, every query row sums to one and every future key has exactly zero weight.
</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>maximum forbidden attention: 0.0
maximum row-sum error: 1.1920928955078125e-07</code></pre>
</div>
</div>
<p>The assertions are part of the derivation. A visually plausible triangle can still be transposed, shifted by one, or applied after softmax. Executable shape and normalization checks catch those errors—before training can disguise them.</p>
<!-- /NOVEL -->
<p>The mask changes visibility, not dense computation. The implementation still forms all <span class="math inline">\(n^2\)</span> scores and stores <span class="math inline">\(Bhn^2\)</span> attention weights, alongside roughly <span class="math inline">\(Bnd^2\)</span> projection work and <span class="math inline">\(Bndd_{ff}\)</span> work in the FFN. Self-attention shortens the graph path between distant tokens to one routing step—but “one step away” is not “constant runtime.” <a href="../appendices/a3-precision-performance.html" class="quarto-xref"><span>Appendix C</span></a> returns to this <span class="math inline">\(n^2\)</span> ledger through Roofline analysis and FlashAttention’s I/O-aware schedule.</p>
</section>
</section>
<section id="build-a-transformer-block" class="level2" data-number="14.4">
<h2 data-number="14.4" class="anchored" data-anchor-id="build-a-transformer-block"><span class="header-section-number">14.4</span> Build a Transformer block</h2>
<p>Attention routes information between token positions. A Transformer block needs two more ingredients—a stable path through depth and a nonlinear computation at each position.</p>
<section id="the-residual-stream" class="level3">
<h3 class="anchored" data-anchor-id="the-residual-stream">The residual stream</h3>
<p><a href="../part2/09-modern-cnns-transfer.html" class="quarto-xref"><span>Chapter 9</span></a> introduced the residual stream with one durable sentence: every block reads the stream and writes a correction back. If a sublayer computes <span class="math inline">\(F(x)\)</span>, the residual update is</p>
<p><span class="math display">\[
x\leftarrow x+F(x).
\]</span></p>
<p>The identity branch provides a direct route for representations and gradients while the learned branch proposes a correction. It makes deep optimization more tractable—it does not guarantee that gradients can never vanish or explode.</p>
<p>Layer normalization controls each token’s feature scale. For one token vector <span class="math inline">\(x\in\mathbb{R}^{d}\)</span>,</p>
<p><span class="math display">\[
\mu=\frac1d\sum_{k=1}^{d}x_k,\qquad
\sigma^2=\frac1d\sum_{k=1}^{d}(x_k-\mu)^2,
\]</span></p>
<p><span class="math display">\[
\operatorname{LN}(x)_k
=\gamma_k\frac{x_k-\mu}{\sqrt{\sigma^2+\epsilon}}+\beta_k,
\qquad \gamma,\beta\in\mathbb{R}^d.
\]</span></p>
<p>This is Chapter 9’s normalization equation applied along a different axis—the same equation, different axis. Chapter 9’s BatchNorm2d used batch and spatial axes for each channel. LayerNorm flips to the feature axis of each token: it computes statistics across the features within one token, without aggregating statistics across other tokens or examples. Its calculation is the same at training and evaluation time. Before the learned <span class="math inline">\(\gamma\)</span> and <span class="math inline">\(\beta\)</span>, the vector is approximately zero mean and unit variance. After applying them, that claim need not remain true.</p>
<div id="cell-fig-transformer-block" class="cell" data-fig-height="4.5" data-fig-width="9" data-execution_count="4">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib.patches <span class="im">import</span> FancyBboxPatch, FancyArrowPatch</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="fl">4.5</span>))</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>axis <span class="op">=</span> axes[<span class="dv">0</span>]</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>axis.set_xlim(<span class="dv">0</span>, <span class="dv">10</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>axis.set_ylim(<span class="dv">0</span>, <span class="dv">10</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>axis.axis(<span class="st">"off"</span>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> box(</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    axis: plt.Axes,</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    x: <span class="bu">float</span>,</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>    y: <span class="bu">float</span>,</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>    width: <span class="bu">float</span>,</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>    height: <span class="bu">float</span>,</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>    text: <span class="bu">str</span>,</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>    color: <span class="bu">str</span>,</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>) <span class="op">-&gt;</span> <span class="va">None</span>:</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>    patch <span class="op">=</span> FancyBboxPatch(</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>        (x, y), width, height,</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>        boxstyle<span class="op">=</span><span class="st">"round,pad=0.08"</span>,</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>        facecolor<span class="op">=</span>color, edgecolor<span class="op">=</span><span class="st">"0.25"</span>,</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>    axis.add_patch(patch)</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>    axis.text(x <span class="op">+</span> width <span class="op">/</span> <span class="dv">2</span>, y <span class="op">+</span> height <span class="op">/</span> <span class="dv">2</span>, text, ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"center"</span>)</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>axis.plot([<span class="dv">2</span>, <span class="dv">2</span>], [<span class="fl">0.7</span>, <span class="fl">9.3</span>], color<span class="op">=</span><span class="st">"0.25"</span>, linewidth<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>axis.text(<span class="fl">0.2</span>, <span class="fl">0.25</span>, <span class="st">"residual stream"</span>, color<span class="op">=</span><span class="st">"0.25"</span>)</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a>box(axis, <span class="fl">3.5</span>, <span class="fl">1.0</span>, <span class="fl">2.5</span>, <span class="fl">1.0</span>, <span class="st">"LayerNorm"</span>, <span class="st">"#d8ecff"</span>)</span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>box(axis, <span class="fl">3.5</span>, <span class="fl">2.6</span>, <span class="fl">2.5</span>, <span class="fl">1.0</span>, <span class="st">"causal MHA"</span>, <span class="st">"#f9dfb5"</span>)</span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a>box(axis, <span class="fl">3.5</span>, <span class="fl">5.7</span>, <span class="fl">2.5</span>, <span class="fl">1.0</span>, <span class="st">"LayerNorm"</span>, <span class="st">"#d8ecff"</span>)</span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>box(axis, <span class="fl">3.5</span>, <span class="fl">7.3</span>, <span class="fl">2.5</span>, <span class="fl">1.0</span>, <span class="st">"FFN"</span>, <span class="st">"#d9f2d0"</span>)</span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> stream_y <span class="kw">in</span> [<span class="fl">1.5</span>, <span class="fl">6.2</span>]:</span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a>    axis.add_patch(</span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a>        FancyArrowPatch((<span class="dv">2</span>, stream_y), (<span class="fl">3.5</span>, stream_y), arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>)</span>
<span id="cb7-36"><a href="#cb7-36" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb7-37"><a href="#cb7-37" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> box_top, stream_y <span class="kw">in</span> [(<span class="fl">3.6</span>, <span class="fl">4.3</span>), (<span class="fl">8.3</span>, <span class="fl">9.0</span>)]:</span>
<span id="cb7-38"><a href="#cb7-38" aria-hidden="true" tabindex="-1"></a>    axis.add_patch(</span>
<span id="cb7-39"><a href="#cb7-39" aria-hidden="true" tabindex="-1"></a>        FancyArrowPatch((<span class="fl">4.75</span>, box_top), (<span class="dv">2</span>, stream_y), arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>)</span>
<span id="cb7-40"><a href="#cb7-40" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb7-41"><a href="#cb7-41" aria-hidden="true" tabindex="-1"></a>axis.add_patch(FancyArrowPatch((<span class="fl">4.75</span>, <span class="fl">2.0</span>), (<span class="fl">4.75</span>, <span class="fl">2.6</span>), arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>))</span>
<span id="cb7-42"><a href="#cb7-42" aria-hidden="true" tabindex="-1"></a>axis.add_patch(FancyArrowPatch((<span class="fl">4.75</span>, <span class="fl">6.7</span>), (<span class="fl">4.75</span>, <span class="fl">7.3</span>), arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>))</span>
<span id="cb7-43"><a href="#cb7-43" aria-hidden="true" tabindex="-1"></a>axis.text(<span class="fl">2.25</span>, <span class="fl">4.05</span>, <span class="st">"+"</span>, fontsize<span class="op">=</span><span class="dv">18</span>)</span>
<span id="cb7-44"><a href="#cb7-44" aria-hidden="true" tabindex="-1"></a>axis.text(<span class="fl">2.25</span>, <span class="fl">8.75</span>, <span class="st">"+"</span>, fontsize<span class="op">=</span><span class="dv">18</span>)</span>
<span id="cb7-45"><a href="#cb7-45" aria-hidden="true" tabindex="-1"></a>axis.set_title(<span class="st">"reads, computes, writes"</span>)</span>
<span id="cb7-46"><a href="#cb7-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-47"><a href="#cb7-47" aria-hidden="true" tabindex="-1"></a>audit <span class="op">=</span> torch.tensor([</span>
<span id="cb7-48"><a href="#cb7-48" aria-hidden="true" tabindex="-1"></a>    [[<span class="fl">1.0</span>, <span class="fl">3.0</span>, <span class="fl">5.0</span>, <span class="fl">7.0</span>], [<span class="fl">40.0</span>, <span class="fl">50.0</span>, <span class="fl">60.0</span>, <span class="fl">70.0</span>]],</span>
<span id="cb7-49"><a href="#cb7-49" aria-hidden="true" tabindex="-1"></a>    [[<span class="op">-</span><span class="fl">3.0</span>, <span class="fl">1.0</span>, <span class="fl">5.0</span>, <span class="fl">9.0</span>], [<span class="fl">2.0</span>, <span class="fl">2.5</span>, <span class="fl">3.0</span>, <span class="fl">3.5</span>]],</span>
<span id="cb7-50"><a href="#cb7-50" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb7-51"><a href="#cb7-51" aria-hidden="true" tabindex="-1"></a>normalized <span class="op">=</span> nn.functional.layer_norm(audit, (<span class="dv">4</span>,))</span>
<span id="cb7-52"><a href="#cb7-52" aria-hidden="true" tabindex="-1"></a>token_means <span class="op">=</span> normalized.mean(dim<span class="op">=-</span><span class="dv">1</span>)</span>
<span id="cb7-53"><a href="#cb7-53" aria-hidden="true" tabindex="-1"></a>token_vars <span class="op">=</span> normalized.var(dim<span class="op">=-</span><span class="dv">1</span>, unbiased<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb7-54"><a href="#cb7-54" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> token_means.<span class="bu">abs</span>().<span class="bu">max</span>().item() <span class="op">&lt;</span> <span class="fl">1e-6</span></span>
<span id="cb7-55"><a href="#cb7-55" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> (token_vars <span class="op">-</span> <span class="dv">1</span>).<span class="bu">abs</span>().<span class="bu">max</span>().item() <span class="op">&lt;</span> <span class="fl">1e-4</span></span>
<span id="cb7-56"><a href="#cb7-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-57"><a href="#cb7-57" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> token, values <span class="kw">in</span> <span class="bu">enumerate</span>(normalized.reshape(<span class="op">-</span><span class="dv">1</span>, <span class="dv">4</span>)):</span>
<span id="cb7-58"><a href="#cb7-58" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">1</span>].plot(</span>
<span id="cb7-59"><a href="#cb7-59" aria-hidden="true" tabindex="-1"></a>        <span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">5</span>), values.numpy(), marker<span class="op">=</span><span class="st">"o"</span>, label<span class="op">=</span><span class="ss">f"token </span><span class="sc">{</span>token <span class="op">+</span> <span class="dv">1</span><span class="sc">}</span><span class="ss">"</span></span>
<span id="cb7-60"><a href="#cb7-60" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb7-61"><a href="#cb7-61" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].axhline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">"0.7"</span>, linestyle<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb7-62"><a href="#cb7-62" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xticks(<span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">5</span>))</span>
<span id="cb7-63"><a href="#cb7-63" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xlabel(<span class="st">"feature within token"</span>)</span>
<span id="cb7-64"><a href="#cb7-64" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_ylabel(<span class="st">"normalized activation"</span>)</span>
<span id="cb7-65"><a href="#cb7-65" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">"each token centers and scales itself"</span>)</span>
<span id="cb7-66"><a href="#cb7-66" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].legend(frameon<span class="op">=</span><span class="va">False</span>, ncol<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb7-67"><a href="#cb7-67" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb7-68"><a href="#cb7-68" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb7-69"><a href="#cb7-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-70"><a href="#cb7-70" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"maximum absolute token mean:"</span>, token_means.<span class="bu">abs</span>().<span class="bu">max</span>().item())</span>
<span id="cb7-71"><a href="#cb7-71" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"maximum token variance error:"</span>, (token_vars <span class="op">-</span> <span class="dv">1</span>).<span class="bu">abs</span>().<span class="bu">max</span>().item())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-transformer-block" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-transformer-block-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="14-self-attention-transformer_files/figure-html/fig-transformer-block-output-1.png" width="854" height="422" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-transformer-block-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.4: A pre-LayerNorm Transformer block (left): each sublayer reads a normalized view of the residual stream and writes a correction back. LayerNorm centers and scales every token across its own feature axis (right).
</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>maximum absolute token mean: 0.0
maximum token variance error: 3.2067298889160156e-05</code></pre>
</div>
</div>
<p>The original Transformer normalized <em>after</em> each residual addition:</p>
<p><span class="math display">\[
x\leftarrow\operatorname{LN}(x+\operatorname{MHA}(x)),\qquad
x\leftarrow\operatorname{LN}(x+\operatorname{FFN}(x)).
\]</span></p>
<p>Our small experiment uses the now-common pre-LayerNorm arrangement:</p>
<p><span class="math display">\[
\begin{aligned}
x&amp;\leftarrow x+\operatorname{MHA}(\operatorname{LN}(x)),\\
x&amp;\leftarrow x+\operatorname{FFN}(\operatorname{LN}(x)).
\end{aligned}
\]</span></p>
<p>Pre-LayerNorm leaves an unobstructed identity route along the residual stream and often improves optimization at initialization. This is an implementation choice, not a universal theorem that post-LayerNorm fails or that pre-LayerNorm eliminates every need for careful optimization.</p>
</section>
<section id="the-position-wise-feed-forward-network" class="level3">
<h3 class="anchored" data-anchor-id="the-position-wise-feed-forward-network">The position-wise feed-forward network</h3>
<p>After tokens communicate through attention, the same two-layer network processes each position independently:</p>
<p><span class="math display">\[
\operatorname{FFN}(z)
=W_2\operatorname{ReLU}(W_1z+b_1)+b_2.
\]</span></p>
<p>Here <span class="math inline">\(W_1\in\mathbb{R}^{d_{ff}\times d}\)</span>, <span class="math inline">\(b_1\in\mathbb{R}^{d_{ff}}\)</span>, <span class="math inline">\(W_2\in\mathbb{R}^{d\times d_{ff}}\)</span>, and <span class="math inline">\(b_2\in\mathbb{R}^{d}\)</span>.</p>
<p>If <span class="math inline">\(w_{1j}^\top\)</span> is row <span class="math inline">\(j\)</span> of <span class="math inline">\(W_1\)</span> and <span class="math inline">\(v_j\)</span> is column <span class="math inline">\(j\)</span> of <span class="math inline">\(W_2\)</span>, the same operation can be written</p>
<p><span class="math display">\[
\operatorname{FFN}(z)
=\sum_j [w_{1j}^\top z+b_{1j}]_+\,v_j+b_2.
\]</span></p>
<p>This form motivates an associative-memory lens. Each first-layer row tests whether the current representation lies in a learned half-space; its positive activation controls how much of the corresponding output vector is written. Empirically, Transformer FFNs can behave like key-value memories. The analogy has limits—the selectors are half-spaces rather than point anchors, the gates do not sum to one, and the operation is not literally kernel regression or a normalized lookup.</p>
<p>The complete block therefore alternates two kinds of computation:</p>
<ol type="1">
<li>causal multi-head attention moves information <em>between positions</em>; and</li>
<li>the FFN transforms information <em>within each position</em>.</li>
</ol>
<p>Residual additions keep both results in one shared stream—a common workspace that survives the full stack.</p>
</section>
</section>
<section id="from-the-original-transformer-to-this-experiment" class="level2" data-number="14.5">
<h2 data-number="14.5" class="anchored" data-anchor-id="from-the-original-transformer-to-this-experiment"><span class="header-section-number">14.5</span> From the original Transformer to this experiment</h2>
<p>The 2017 Transformer was an encoder–decoder system for translation. Its encoder stack uses unmasked self-attention to build a representation of the source sentence. Its decoder stack uses causal self-attention over the partial target, then cross-attention whose queries come from the decoder while keys and values come from the encoder. In compact form:</p>
<p><span class="math display">\[
\begin{array}{lll}
\text{encoder:}&amp;X_s\to\text{self-attention}\to\text{FFN},\\
\text{decoder:}&amp;X_t\to\text{causal self-attention}
\to\text{cross-attention to encoder}\to\text{FFN}.
\end{array}
\]</span></p>
<p>The book-corpus task predicts the next character from earlier characters. It has no separate source sentence, so the encoder and cross-attention are unnecessary. What remains—a <strong>decoder-only causal Transformer</strong>—has token plus position embeddings, two pre-LayerNorm blocks, a final LayerNorm, and a linear map to vocabulary logits. The logits go directly to cross-entropy. Softmax belongs inside attention and, later, inside sampling—not between the output layer and the loss.</p>
<!-- NOVEL: needs sign-off - exact-schedule book-corpus rematch, positional ablation,
     learned-map audit, and deterministic samples. -->
</section>
<section id="the-book-reads-itself-again" class="level2" data-number="14.6">
<h2 data-number="14.6" class="anchored" data-anchor-id="the-book-reads-itself-again"><span class="header-section-number">14.6</span> The book reads itself, again</h2>
<p>A fair rematch begins by preserving what can be preserved. Chapter 10 trained on the code-stripped text of Chapters 1–9: 148,594 characters, vocabulary 104, a contiguous 90/10 split, 100-character windows, batch size 64, and 2,501 updates with Adam at learning rate 0.002 and gradient clipping at norm 1. The held-out metric resets state at each fixed window.</p>
<p>The two architectures cannot be made identical—one has recurrent gates and the other has attention blocks—but their opportunity to see training targets can be. The code below reconstructs Chapter 10’s exact random-window schedule, then gives both Transformer variants the same initial weights and all 16,006,400 target characters in the same order. The held-out tail has been inspected repeatedly across chapters, so treat it as a stable validation benchmark—not a newly sealed test set.</p>
<div id="transformer-data-model" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code: exact Chapter 10 corpus and schedule, plus a custom tiny Transformer</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> glob</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> hashlib</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> re</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.nn.functional <span class="im">as</span> F</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>torch.set_num_threads(<span class="dv">4</span>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>torch.use_deterministic_algorithms(<span class="va">True</span>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>SEED <span class="op">=</span> <span class="dv">6050</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>CONTEXT <span class="op">=</span> <span class="dv">100</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>BATCH <span class="op">=</span> <span class="dv">64</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>UPDATES <span class="op">=</span> <span class="dv">2501</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>WIDTH <span class="op">=</span> <span class="dv">84</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>HEADS <span class="op">=</span> <span class="dv">4</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>FF_WIDTH <span class="op">=</span> <span class="dv">168</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>BLOCKS <span class="op">=</span> <span class="dv">2</span></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>fence <span class="op">=</span> <span class="bu">chr</span>(<span class="dv">96</span>) <span class="op">*</span> <span class="dv">3</span></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>files <span class="op">=</span> <span class="bu">sorted</span>(glob.glob(<span class="st">"../part*/0*.qmd"</span>))</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>text <span class="op">=</span> <span class="st">""</span></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> filename <span class="kw">in</span> files:</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>    raw <span class="op">=</span> <span class="bu">open</span>(filename).read()</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>    code_pattern <span class="op">=</span> (</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>        re.escape(fence) <span class="op">+</span> <span class="vs">r"</span><span class="ch">\{</span><span class="vs">python</span><span class="ch">\}</span><span class="dv">.</span><span class="op">*?</span><span class="vs">"</span> <span class="op">+</span> re.escape(fence)</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>    raw <span class="op">=</span> re.sub(code_pattern, <span class="st">""</span>, raw, flags<span class="op">=</span>re.S)</span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>    raw <span class="op">=</span> re.sub(<span class="vs">r"&lt;!--</span><span class="dv">.</span><span class="op">*?</span><span class="vs">--&gt;"</span>, <span class="st">""</span>, raw, flags<span class="op">=</span>re.S)</span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>    text <span class="op">+=</span> raw</span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>chars <span class="op">=</span> <span class="bu">sorted</span>(<span class="bu">set</span>(text))</span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a>stoi <span class="op">=</span> {char: index <span class="cf">for</span> index, char <span class="kw">in</span> <span class="bu">enumerate</span>(chars)}</span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> torch.tensor([stoi[char] <span class="cf">for</span> char <span class="kw">in</span> text])</span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>split <span class="op">=</span> <span class="bu">int</span>(<span class="fl">0.9</span> <span class="op">*</span> <span class="bu">len</span>(data))</span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a>train_data, valid_data <span class="op">=</span> data[:split], data[split:]</span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> sinusoidal_positions(length: <span class="bu">int</span>, width: <span class="bu">int</span>) <span class="op">-&gt;</span> torch.Tensor:</span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a>    position <span class="op">=</span> torch.arange(length, dtype<span class="op">=</span>torch.float32).unsqueeze(<span class="dv">1</span>)</span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a>    frequency <span class="op">=</span> torch.exp(</span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a>        torch.arange(<span class="dv">0</span>, width, <span class="dv">2</span>, dtype<span class="op">=</span>torch.float32)</span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a>        <span class="op">*</span> (<span class="op">-</span>math.log(<span class="fl">10_000.0</span>) <span class="op">/</span> width)</span>
<span id="cb9-41"><a href="#cb9-41" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb9-42"><a href="#cb9-42" aria-hidden="true" tabindex="-1"></a>    table <span class="op">=</span> torch.zeros(length, width)</span>
<span id="cb9-43"><a href="#cb9-43" aria-hidden="true" tabindex="-1"></a>    table[:, <span class="dv">0</span>::<span class="dv">2</span>] <span class="op">=</span> torch.sin(position <span class="op">*</span> frequency)</span>
<span id="cb9-44"><a href="#cb9-44" aria-hidden="true" tabindex="-1"></a>    table[:, <span class="dv">1</span>::<span class="dv">2</span>] <span class="op">=</span> torch.cos(position <span class="op">*</span> frequency)</span>
<span id="cb9-45"><a href="#cb9-45" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> table</span>
<span id="cb9-46"><a href="#cb9-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-47"><a href="#cb9-47" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> TransformerBlock(nn.Module):</span>
<span id="cb9-48"><a href="#cb9-48" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>) <span class="op">-&gt;</span> <span class="va">None</span>:</span>
<span id="cb9-49"><a href="#cb9-49" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb9-50"><a href="#cb9-50" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.norm1 <span class="op">=</span> nn.LayerNorm(WIDTH)</span>
<span id="cb9-51"><a href="#cb9-51" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.attention <span class="op">=</span> CausalMultiHeadAttention(WIDTH, HEADS)</span>
<span id="cb9-52"><a href="#cb9-52" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.norm2 <span class="op">=</span> nn.LayerNorm(WIDTH)</span>
<span id="cb9-53"><a href="#cb9-53" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.ff <span class="op">=</span> nn.Sequential(</span>
<span id="cb9-54"><a href="#cb9-54" aria-hidden="true" tabindex="-1"></a>            nn.Linear(WIDTH, FF_WIDTH),</span>
<span id="cb9-55"><a href="#cb9-55" aria-hidden="true" tabindex="-1"></a>            nn.ReLU(),</span>
<span id="cb9-56"><a href="#cb9-56" aria-hidden="true" tabindex="-1"></a>            nn.Linear(FF_WIDTH, WIDTH),</span>
<span id="cb9-57"><a href="#cb9-57" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb9-58"><a href="#cb9-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-59"><a href="#cb9-59" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x: torch.Tensor, return_weights: <span class="bu">bool</span> <span class="op">=</span> <span class="va">False</span>):</span>
<span id="cb9-60"><a href="#cb9-60" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> return_weights:</span>
<span id="cb9-61"><a href="#cb9-61" aria-hidden="true" tabindex="-1"></a>            attended, weights <span class="op">=</span> <span class="va">self</span>.attention(<span class="va">self</span>.norm1(x), <span class="va">True</span>)</span>
<span id="cb9-62"><a href="#cb9-62" aria-hidden="true" tabindex="-1"></a>            x <span class="op">=</span> x <span class="op">+</span> attended</span>
<span id="cb9-63"><a href="#cb9-63" aria-hidden="true" tabindex="-1"></a>            <span class="cf">return</span> x <span class="op">+</span> <span class="va">self</span>.ff(<span class="va">self</span>.norm2(x)), weights</span>
<span id="cb9-64"><a href="#cb9-64" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> x <span class="op">+</span> <span class="va">self</span>.attention(<span class="va">self</span>.norm1(x))</span>
<span id="cb9-65"><a href="#cb9-65" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> x <span class="op">+</span> <span class="va">self</span>.ff(<span class="va">self</span>.norm2(x))</span>
<span id="cb9-66"><a href="#cb9-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-67"><a href="#cb9-67" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> TinyTransformerLM(nn.Module):</span>
<span id="cb9-68"><a href="#cb9-68" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, vocab: <span class="bu">int</span>, positions: <span class="bu">bool</span>) <span class="op">-&gt;</span> <span class="va">None</span>:</span>
<span id="cb9-69"><a href="#cb9-69" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb9-70"><a href="#cb9-70" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.positions <span class="op">=</span> positions</span>
<span id="cb9-71"><a href="#cb9-71" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.token_embedding <span class="op">=</span> nn.Embedding(vocab, WIDTH)</span>
<span id="cb9-72"><a href="#cb9-72" aria-hidden="true" tabindex="-1"></a>        nn.init.normal_(</span>
<span id="cb9-73"><a href="#cb9-73" aria-hidden="true" tabindex="-1"></a>            <span class="va">self</span>.token_embedding.weight,</span>
<span id="cb9-74"><a href="#cb9-74" aria-hidden="true" tabindex="-1"></a>            mean<span class="op">=</span><span class="fl">0.0</span>,</span>
<span id="cb9-75"><a href="#cb9-75" aria-hidden="true" tabindex="-1"></a>            std<span class="op">=</span><span class="dv">1</span> <span class="op">/</span> math.sqrt(WIDTH),</span>
<span id="cb9-76"><a href="#cb9-76" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb9-77"><a href="#cb9-77" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.blocks <span class="op">=</span> nn.ModuleList(</span>
<span id="cb9-78"><a href="#cb9-78" aria-hidden="true" tabindex="-1"></a>            [TransformerBlock() <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(BLOCKS)]</span>
<span id="cb9-79"><a href="#cb9-79" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb9-80"><a href="#cb9-80" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.final_norm <span class="op">=</span> nn.LayerNorm(WIDTH)</span>
<span id="cb9-81"><a href="#cb9-81" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.output <span class="op">=</span> nn.Linear(WIDTH, vocab)</span>
<span id="cb9-82"><a href="#cb9-82" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.register_buffer(</span>
<span id="cb9-83"><a href="#cb9-83" aria-hidden="true" tabindex="-1"></a>            <span class="st">"position_table"</span>,</span>
<span id="cb9-84"><a href="#cb9-84" aria-hidden="true" tabindex="-1"></a>            sinusoidal_positions(CONTEXT, WIDTH),</span>
<span id="cb9-85"><a href="#cb9-85" aria-hidden="true" tabindex="-1"></a>            persistent<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb9-86"><a href="#cb9-86" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb9-87"><a href="#cb9-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-88"><a href="#cb9-88" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, tokens: torch.Tensor, return_weights: <span class="bu">bool</span> <span class="op">=</span> <span class="va">False</span>):</span>
<span id="cb9-89"><a href="#cb9-89" aria-hidden="true" tabindex="-1"></a>        length <span class="op">=</span> tokens.shape[<span class="dv">1</span>]</span>
<span id="cb9-90"><a href="#cb9-90" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> <span class="va">self</span>.token_embedding(tokens) <span class="op">*</span> math.sqrt(WIDTH)</span>
<span id="cb9-91"><a href="#cb9-91" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="va">self</span>.positions:</span>
<span id="cb9-92"><a href="#cb9-92" aria-hidden="true" tabindex="-1"></a>            x <span class="op">=</span> x <span class="op">+</span> <span class="va">self</span>.position_table[:length]</span>
<span id="cb9-93"><a href="#cb9-93" aria-hidden="true" tabindex="-1"></a>        maps <span class="op">=</span> []</span>
<span id="cb9-94"><a href="#cb9-94" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> block <span class="kw">in</span> <span class="va">self</span>.blocks:</span>
<span id="cb9-95"><a href="#cb9-95" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> return_weights:</span>
<span id="cb9-96"><a href="#cb9-96" aria-hidden="true" tabindex="-1"></a>                x, weights <span class="op">=</span> block(x, <span class="va">True</span>)</span>
<span id="cb9-97"><a href="#cb9-97" aria-hidden="true" tabindex="-1"></a>                maps.append(weights)</span>
<span id="cb9-98"><a href="#cb9-98" aria-hidden="true" tabindex="-1"></a>            <span class="cf">else</span>:</span>
<span id="cb9-99"><a href="#cb9-99" aria-hidden="true" tabindex="-1"></a>                x <span class="op">=</span> block(x)</span>
<span id="cb9-100"><a href="#cb9-100" aria-hidden="true" tabindex="-1"></a>        logits <span class="op">=</span> <span class="va">self</span>.output(<span class="va">self</span>.final_norm(x))</span>
<span id="cb9-101"><a href="#cb9-101" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> (logits, maps) <span class="cf">if</span> return_weights <span class="cf">else</span> logits</span>
<span id="cb9-102"><a href="#cb9-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-103"><a href="#cb9-103" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> HistoricalCharLSTM(nn.Module):</span>
<span id="cb9-104"><a href="#cb9-104" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, vocab: <span class="bu">int</span>, hidden: <span class="bu">int</span> <span class="op">=</span> <span class="dv">128</span>) <span class="op">-&gt;</span> <span class="va">None</span>:</span>
<span id="cb9-105"><a href="#cb9-105" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb9-106"><a href="#cb9-106" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.vocab <span class="op">=</span> vocab</span>
<span id="cb9-107"><a href="#cb9-107" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.lstm <span class="op">=</span> nn.LSTM(vocab, hidden, batch_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb9-108"><a href="#cb9-108" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.out <span class="op">=</span> nn.Linear(hidden, vocab)</span>
<span id="cb9-109"><a href="#cb9-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-110"><a href="#cb9-110" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> state_digest(state: <span class="bu">dict</span>[<span class="bu">str</span>, torch.Tensor]) <span class="op">-&gt;</span> <span class="bu">str</span>:</span>
<span id="cb9-111"><a href="#cb9-111" aria-hidden="true" tabindex="-1"></a>    digest <span class="op">=</span> hashlib.sha256()</span>
<span id="cb9-112"><a href="#cb9-112" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> name, value <span class="kw">in</span> state.items():</span>
<span id="cb9-113"><a href="#cb9-113" aria-hidden="true" tabindex="-1"></a>        digest.update(name.encode())</span>
<span id="cb9-114"><a href="#cb9-114" aria-hidden="true" tabindex="-1"></a>        digest.update(value.detach().cpu().numpy().tobytes())</span>
<span id="cb9-115"><a href="#cb9-115" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> digest.hexdigest()</span>
<span id="cb9-116"><a href="#cb9-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-117"><a href="#cb9-117" aria-hidden="true" tabindex="-1"></a><span class="co"># Reconstruct the random-number state immediately after Chapter 10 created</span></span>
<span id="cb9-118"><a href="#cb9-118" aria-hidden="true" tabindex="-1"></a><span class="co"># its LSTM, then draw that chapter's complete minibatch-start schedule.</span></span>
<span id="cb9-119"><a href="#cb9-119" aria-hidden="true" tabindex="-1"></a>torch.manual_seed(SEED)</span>
<span id="cb9-120"><a href="#cb9-120" aria-hidden="true" tabindex="-1"></a>_ <span class="op">=</span> HistoricalCharLSTM(<span class="bu">len</span>(chars))</span>
<span id="cb9-121"><a href="#cb9-121" aria-hidden="true" tabindex="-1"></a>schedule_generator <span class="op">=</span> torch.Generator()</span>
<span id="cb9-122"><a href="#cb9-122" aria-hidden="true" tabindex="-1"></a>schedule_generator.set_state(torch.random.get_rng_state())</span>
<span id="cb9-123"><a href="#cb9-123" aria-hidden="true" tabindex="-1"></a>starts <span class="op">=</span> torch.randint(</span>
<span id="cb9-124"><a href="#cb9-124" aria-hidden="true" tabindex="-1"></a>    <span class="dv">0</span>,</span>
<span id="cb9-125"><a href="#cb9-125" aria-hidden="true" tabindex="-1"></a>    <span class="bu">len</span>(train_data) <span class="op">-</span> CONTEXT <span class="op">-</span> <span class="dv">1</span>,</span>
<span id="cb9-126"><a href="#cb9-126" aria-hidden="true" tabindex="-1"></a>    (UPDATES, BATCH),</span>
<span id="cb9-127"><a href="#cb9-127" aria-hidden="true" tabindex="-1"></a>    generator<span class="op">=</span>schedule_generator,</span>
<span id="cb9-128"><a href="#cb9-128" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-129"><a href="#cb9-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-130"><a href="#cb9-130" aria-hidden="true" tabindex="-1"></a><span class="co"># The two Transformer variants begin with exactly the same tensors.</span></span>
<span id="cb9-131"><a href="#cb9-131" aria-hidden="true" tabindex="-1"></a>torch.manual_seed(SEED)</span>
<span id="cb9-132"><a href="#cb9-132" aria-hidden="true" tabindex="-1"></a>base_model <span class="op">=</span> TinyTransformerLM(<span class="bu">len</span>(chars), positions<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb9-133"><a href="#cb9-133" aria-hidden="true" tabindex="-1"></a>initial_state <span class="op">=</span> {</span>
<span id="cb9-134"><a href="#cb9-134" aria-hidden="true" tabindex="-1"></a>    name: value.clone() <span class="cf">for</span> name, value <span class="kw">in</span> base_model.state_dict().items()</span>
<span id="cb9-135"><a href="#cb9-135" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb9-136"><a href="#cb9-136" aria-hidden="true" tabindex="-1"></a>initial_hash <span class="op">=</span> state_digest(initial_state)</span>
<span id="cb9-137"><a href="#cb9-137" aria-hidden="true" tabindex="-1"></a>schedule_hash <span class="op">=</span> hashlib.sha256(starts.numpy().tobytes()).hexdigest()</span>
<span id="cb9-138"><a href="#cb9-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-139"><a href="#cb9-139" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(</span>
<span id="cb9-140"><a href="#cb9-140" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"corpus: </span><span class="sc">{</span><span class="bu">len</span>(files)<span class="sc">}</span><span class="ss"> chapters, </span><span class="sc">{</span><span class="bu">len</span>(text)<span class="sc">:,}</span><span class="ss"> characters, "</span></span>
<span id="cb9-141"><a href="#cb9-141" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"vocab </span><span class="sc">{</span><span class="bu">len</span>(chars)<span class="sc">}</span><span class="ss">"</span></span>
<span id="cb9-142"><a href="#cb9-142" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-143"><a href="#cb9-143" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(</span>
<span id="cb9-144"><a href="#cb9-144" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"deterministic split: </span><span class="sc">{</span><span class="bu">len</span>(train_data)<span class="sc">:,}</span><span class="ss"> train / "</span></span>
<span id="cb9-145"><a href="#cb9-145" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"</span><span class="sc">{</span><span class="bu">len</span>(valid_data)<span class="sc">:,}</span><span class="ss"> held out"</span></span>
<span id="cb9-146"><a href="#cb9-146" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-147"><a href="#cb9-147" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(</span>
<span id="cb9-148"><a href="#cb9-148" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"Transformer parameters: "</span></span>
<span id="cb9-149"><a href="#cb9-149" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"</span><span class="sc">{</span><span class="bu">sum</span>(parameter.numel() <span class="cf">for</span> parameter <span class="kw">in</span> base_model.parameters())<span class="sc">:,}</span><span class="ss">"</span></span>
<span id="cb9-150"><a href="#cb9-150" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-151"><a href="#cb9-151" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"first eight window starts: </span><span class="sc">{</span>starts[<span class="dv">0</span>, :<span class="dv">8</span>]<span class="sc">.</span>tolist()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb9-152"><a href="#cb9-152" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"initial tensors: </span><span class="sc">{</span>initial_hash[:<span class="dv">12</span>]<span class="sc">}</span><span class="ss">…"</span>)</span>
<span id="cb9-153"><a href="#cb9-153" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"window schedule: </span><span class="sc">{</span>schedule_hash[:<span class="dv">12</span>]<span class="sc">}</span><span class="ss">…"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>corpus: 9 chapters, 148,594 characters, vocab 104
deterministic split: 133,734 train / 14,860 held out
Transformer parameters: 132,488
first eight window starts: [24368, 94128, 60074, 121547, 118001, 4396, 17011, 8495]
initial tensors: 4d2f7f434cb5…
window schedule: e470a091bd50…</code></pre>
</div>
</div>
<p>The model has 132,488 trainable parameters—736 fewer than Chapter 10’s 133,224. That difference is only 0.55%—close enough to remove model size as an easy explanation. The model width is 84, split into four 21-dimensional heads; each of the two FFNs expands to 168 features. Token embeddings are initialized with coordinate standard deviation <span class="math inline">\(1/\sqrt d\)</span> before the displayed <span class="math inline">\(\sqrt d\)</span> scaling, so their coordinates and the sinusoidal coordinates begin on comparable scales. <code>ModuleList</code> registers the two repeated blocks with the model. The nonpersistent position buffer moves with the model but is neither optimized nor included in the state-dictionary fingerprint; its contents follow deterministically from the displayed formula. There is no dropout, so resetting the trainable/state-dictionary tensors and window schedule makes the positional ablation exact and repeatable.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>One seed call was not enough
</div>
</div>
<div class="callout-body-container callout-body">
<p>Calling the same random seed before both training runs would not, by itself, prove that they saw the same windows. Model construction consumes random numbers, and different construction paths can silently shift every later draw. The experiment precomputes the full start-index tensor with an explicit generator and copies one saved initialization into both models. It also prints fingerprints for both artifacts.</p>
</div>
</div>
<div id="transformer-training-function" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code: one matched training and evaluation protocol</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> train_transformer(</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    positions: <span class="bu">bool</span>,</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>) <span class="op">-&gt;</span> <span class="bu">tuple</span>[nn.Module, <span class="bu">list</span>[<span class="bu">tuple</span>[<span class="bu">int</span>, <span class="bu">float</span>]]]:</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    net <span class="op">=</span> TinyTransformerLM(<span class="bu">len</span>(chars), positions<span class="op">=</span>positions)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    net.load_state_dict(initial_state, strict<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">assert</span> state_digest(net.state_dict()) <span class="op">==</span> initial_hash</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    optimizer <span class="op">=</span> torch.optim.Adam(net.parameters(), lr<span class="op">=</span><span class="fl">2e-3</span>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    curve <span class="op">=</span> []</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> step, batch_starts <span class="kw">in</span> <span class="bu">enumerate</span>(starts):</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>        xb <span class="op">=</span> torch.stack([</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>            train_data[j : j <span class="op">+</span> CONTEXT] <span class="cf">for</span> j <span class="kw">in</span> batch_starts</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>        ])</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>        yb <span class="op">=</span> torch.stack([</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>            train_data[j <span class="op">+</span> <span class="dv">1</span> : j <span class="op">+</span> CONTEXT <span class="op">+</span> <span class="dv">1</span>] <span class="cf">for</span> j <span class="kw">in</span> batch_starts</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>        ])</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>        logits <span class="op">=</span> net(xb)</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>        loss <span class="op">=</span> F.cross_entropy(</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>            logits.reshape(<span class="op">-</span><span class="dv">1</span>, <span class="bu">len</span>(chars)), yb.reshape(<span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>        optimizer.zero_grad()</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>        loss.backward()</span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>        nn.utils.clip_grad_norm_(net.parameters(), <span class="fl">1.0</span>)</span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>        optimizer.step()</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> step <span class="op">%</span> <span class="dv">250</span> <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a>            curve.append((step, loss.item()))</span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a>            <span class="bu">print</span>(<span class="ss">f"step </span><span class="sc">{</span>step<span class="sc">:4d}</span><span class="ss">   loss </span><span class="sc">{</span>loss<span class="sc">.</span>item()<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> net, curve</span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a><span class="at">@torch.no_grad</span>()</span>
<span id="cb11-30"><a href="#cb11-30" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> fixed_window_loss(</span>
<span id="cb11-31"><a href="#cb11-31" aria-hidden="true" tabindex="-1"></a>    net: nn.Module,</span>
<span id="cb11-32"><a href="#cb11-32" aria-hidden="true" tabindex="-1"></a>    sequence: torch.Tensor,</span>
<span id="cb11-33"><a href="#cb11-33" aria-hidden="true" tabindex="-1"></a>    window: <span class="bu">int</span> <span class="op">=</span> CONTEXT,</span>
<span id="cb11-34"><a href="#cb11-34" aria-hidden="true" tabindex="-1"></a>) <span class="op">-&gt;</span> <span class="bu">float</span>:</span>
<span id="cb11-35"><a href="#cb11-35" aria-hidden="true" tabindex="-1"></a>    net.<span class="bu">eval</span>()</span>
<span id="cb11-36"><a href="#cb11-36" aria-hidden="true" tabindex="-1"></a>    total_loss, n_tokens <span class="op">=</span> <span class="fl">0.0</span>, <span class="dv">0</span></span>
<span id="cb11-37"><a href="#cb11-37" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> start <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>, <span class="bu">len</span>(sequence) <span class="op">-</span> <span class="dv">1</span>, window):</span>
<span id="cb11-38"><a href="#cb11-38" aria-hidden="true" tabindex="-1"></a>        stop <span class="op">=</span> <span class="bu">min</span>(start <span class="op">+</span> window, <span class="bu">len</span>(sequence) <span class="op">-</span> <span class="dv">1</span>)</span>
<span id="cb11-39"><a href="#cb11-39" aria-hidden="true" tabindex="-1"></a>        xb <span class="op">=</span> sequence[start:stop].unsqueeze(<span class="dv">0</span>)</span>
<span id="cb11-40"><a href="#cb11-40" aria-hidden="true" tabindex="-1"></a>        yb <span class="op">=</span> sequence[start <span class="op">+</span> <span class="dv">1</span> : stop <span class="op">+</span> <span class="dv">1</span>]</span>
<span id="cb11-41"><a href="#cb11-41" aria-hidden="true" tabindex="-1"></a>        logits <span class="op">=</span> net(xb)</span>
<span id="cb11-42"><a href="#cb11-42" aria-hidden="true" tabindex="-1"></a>        total_loss <span class="op">+=</span> F.cross_entropy(</span>
<span id="cb11-43"><a href="#cb11-43" aria-hidden="true" tabindex="-1"></a>            logits.reshape(<span class="op">-</span><span class="dv">1</span>, <span class="bu">len</span>(chars)),</span>
<span id="cb11-44"><a href="#cb11-44" aria-hidden="true" tabindex="-1"></a>            yb,</span>
<span id="cb11-45"><a href="#cb11-45" aria-hidden="true" tabindex="-1"></a>            reduction<span class="op">=</span><span class="st">"sum"</span>,</span>
<span id="cb11-46"><a href="#cb11-46" aria-hidden="true" tabindex="-1"></a>        ).item()</span>
<span id="cb11-47"><a href="#cb11-47" aria-hidden="true" tabindex="-1"></a>        n_tokens <span class="op">+=</span> yb.numel()</span>
<span id="cb11-48"><a href="#cb11-48" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> total_loss <span class="op">/</span> n_tokens</span>
<span id="cb11-49"><a href="#cb11-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-50"><a href="#cb11-50" aria-hidden="true" tabindex="-1"></a><span class="at">@torch.no_grad</span>()</span>
<span id="cb11-51"><a href="#cb11-51" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> transformer_sample(</span>
<span id="cb11-52"><a href="#cb11-52" aria-hidden="true" tabindex="-1"></a>    net: nn.Module,</span>
<span id="cb11-53"><a href="#cb11-53" aria-hidden="true" tabindex="-1"></a>    prompt: <span class="bu">str</span>,</span>
<span id="cb11-54"><a href="#cb11-54" aria-hidden="true" tabindex="-1"></a>    n: <span class="bu">int</span> <span class="op">=</span> <span class="dv">300</span>,</span>
<span id="cb11-55"><a href="#cb11-55" aria-hidden="true" tabindex="-1"></a>    temperature: <span class="bu">float</span> <span class="op">=</span> <span class="fl">0.8</span>,</span>
<span id="cb11-56"><a href="#cb11-56" aria-hidden="true" tabindex="-1"></a>) <span class="op">-&gt;</span> <span class="bu">str</span>:</span>
<span id="cb11-57"><a href="#cb11-57" aria-hidden="true" tabindex="-1"></a>    net.<span class="bu">eval</span>()</span>
<span id="cb11-58"><a href="#cb11-58" aria-hidden="true" tabindex="-1"></a>    generator <span class="op">=</span> torch.Generator().manual_seed(<span class="dv">1_406_050</span>)</span>
<span id="cb11-59"><a href="#cb11-59" aria-hidden="true" tabindex="-1"></a>    tokens <span class="op">=</span> [stoi.get(char, <span class="dv">0</span>) <span class="cf">for</span> char <span class="kw">in</span> prompt]</span>
<span id="cb11-60"><a href="#cb11-60" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(n):</span>
<span id="cb11-61"><a href="#cb11-61" aria-hidden="true" tabindex="-1"></a>        context <span class="op">=</span> torch.tensor(tokens[<span class="op">-</span>CONTEXT:]).unsqueeze(<span class="dv">0</span>)</span>
<span id="cb11-62"><a href="#cb11-62" aria-hidden="true" tabindex="-1"></a>        probabilities <span class="op">=</span> F.softmax(</span>
<span id="cb11-63"><a href="#cb11-63" aria-hidden="true" tabindex="-1"></a>            net(context)[<span class="dv">0</span>, <span class="op">-</span><span class="dv">1</span>] <span class="op">/</span> temperature, dim<span class="op">=-</span><span class="dv">1</span></span>
<span id="cb11-64"><a href="#cb11-64" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb11-65"><a href="#cb11-65" aria-hidden="true" tabindex="-1"></a>        next_token <span class="op">=</span> torch.multinomial(</span>
<span id="cb11-66"><a href="#cb11-66" aria-hidden="true" tabindex="-1"></a>            probabilities, <span class="dv">1</span>, generator<span class="op">=</span>generator</span>
<span id="cb11-67"><a href="#cb11-67" aria-hidden="true" tabindex="-1"></a>        ).item()</span>
<span id="cb11-68"><a href="#cb11-68" aria-hidden="true" tabindex="-1"></a>        tokens.append(next_token)</span>
<span id="cb11-69"><a href="#cb11-69" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="st">""</span>.join(chars[index] <span class="cf">for</span> index <span class="kw">in</span> tokens)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>The training function is defined once, then called in separate cells so each substantial run stays within the chapter’s execution budget.</p>
<div id="train-transformer-positions" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Code: train the positional Transformer</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>position_model, position_curve <span class="op">=</span> train_transformer(positions<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>position_train_loss <span class="op">=</span> fixed_window_loss(position_model, train_data)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>position_valid_loss <span class="op">=</span> fixed_window_loss(position_model, valid_data)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"fixed-window train loss: </span><span class="sc">{</span>position_train_loss<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"fixed-window held-out loss: </span><span class="sc">{</span>position_valid_loss<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>step    0   loss 4.7550
step  250   loss 2.1850
step  500   loss 1.7159
step  750   loss 1.5176
step 1000   loss 1.3955
step 1250   loss 1.3444
step 1500   loss 1.2813
step 1750   loss 1.2386
step 2000   loss 1.1708
step 2250   loss 1.1525
step 2500   loss 1.1083
fixed-window train loss: 1.1132
fixed-window held-out loss: 1.9190</code></pre>
</div>
</div>
<div id="train-transformer-no-positions" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Code: repeat with position removed and everything else fixed</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>no_position_model, no_position_curve <span class="op">=</span> train_transformer(positions<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>no_position_train_loss <span class="op">=</span> fixed_window_loss(no_position_model, train_data)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>no_position_valid_loss <span class="op">=</span> fixed_window_loss(no_position_model, valid_data)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"fixed-window train loss: </span><span class="sc">{</span>no_position_train_loss<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"fixed-window held-out loss: </span><span class="sc">{</span>no_position_valid_loss<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>step    0   loss 4.7289
step  250   loss 2.4955
step  500   loss 2.3612
step  750   loss 2.2436
step 1000   loss 2.2153
step 1250   loss 2.1826
step 1500   loss 2.0792
step 1750   loss 1.9876
step 2000   loss 1.9527
step 2250   loss 1.8986
step 2500   loss 1.8435
fixed-window train loss: 1.8672
fixed-window held-out loss: 2.3405</code></pre>
</div>
</div>
<div id="cell-fig-book-corpus-rematch" class="cell" data-fig-height="4" data-fig-width="10" data-execution_count="9">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>lstm_valid_loss <span class="op">=</span> <span class="fl">1.888110429</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">4</span>))</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> curve, label, color <span class="kw">in</span> [</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    (position_curve, <span class="st">"Transformer + position"</span>, <span class="st">"#3566a8"</span>),</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    (no_position_curve, <span class="st">"Transformer, no position"</span>, <span class="st">"#d37b29"</span>),</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>]:</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    steps, losses <span class="op">=</span> <span class="bu">zip</span>(<span class="op">*</span>curve)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">0</span>].plot(steps, losses, marker<span class="op">=</span><span class="st">"o"</span>, ms<span class="op">=</span><span class="dv">3</span>, label<span class="op">=</span>label, color<span class="op">=</span>color)</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xlabel(<span class="st">"update"</span>)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"sampled training-minibatch loss"</span>)</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">"same windows, same initialization"</span>)</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].legend(frameon<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>labels <span class="op">=</span> [<span class="st">"Ch. 10</span><span class="ch">\n</span><span class="st">LSTM"</span>, <span class="st">"Transformer</span><span class="ch">\n</span><span class="st">+ position"</span>, <span class="st">"Transformer</span><span class="ch">\n</span><span class="st">no position"</span>]</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>values <span class="op">=</span> [lstm_valid_loss, position_valid_loss, no_position_valid_loss]</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>bars <span class="op">=</span> axes[<span class="dv">1</span>].bar(labels, values, color<span class="op">=</span>[<span class="st">"#6b7280"</span>, <span class="st">"#3566a8"</span>, <span class="st">"#d37b29"</span>])</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_ylim(<span class="fl">1.5</span>, <span class="fl">2.7</span>)</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_ylabel(<span class="st">"held-out loss ↓"</span>)</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">"fixed-window rematch"</span>)</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].bar_label(bars, fmt<span class="op">=</span><span class="st">"</span><span class="sc">%.4f</span><span class="st">"</span>, padding<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a>improvement <span class="op">=</span> no_position_valid_loss <span class="op">-</span> position_valid_loss</span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a>relative <span class="op">=</span> improvement <span class="op">/</span> no_position_valid_loss</span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a>lstm_gap <span class="op">=</span> position_valid_loss <span class="op">-</span> lstm_valid_loss</span>
<span id="cb16-28"><a href="#cb16-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(</span>
<span id="cb16-29"><a href="#cb16-29" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"position improvement: </span><span class="sc">{</span>improvement<span class="sc">:.4f}</span><span class="ss"> loss "</span></span>
<span id="cb16-30"><a href="#cb16-30" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"(</span><span class="sc">{</span>relative<span class="sc">:.1%}</span><span class="ss"> relative)"</span></span>
<span id="cb16-31"><a href="#cb16-31" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-32"><a href="#cb16-32" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"positional Transformer minus LSTM: </span><span class="sc">{</span>lstm_gap<span class="sc">:.4f}</span><span class="ss"> loss"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-book-corpus-rematch" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-book-corpus-rematch-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="14-self-attention-transformer_files/figure-html/fig-book-corpus-rematch-output-1.png" width="951" height="374" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-book-corpus-rematch-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.5: Matched training curves (left) and fixed-window held-out loss (right). Position helps in this seed, while the Chapter 10 LSTM remains the strongest small model.
</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>position improvement: 0.4214 loss (18.0% relative)
positional Transformer minus LSTM: 0.0309 loss</code></pre>
</div>
</div>
<p>The positional model finishes at 1.1132 on a deterministic pass over the training text and 1.9190 on the held-out tail. Removing position raises those values to 1.8672 and 2.3405. Position lowers held-out loss by 0.4214, or 18.0% relative to the no-position variant.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>What this matched run can—and cannot—show
</div>
</div>
<div class="callout-body-container callout-body">
<p>The causal mask already gives a position some weak structural information: row <span class="math inline">\(i\)</span> sees a prefix of length <span class="math inline">\(i+1\)</span>, and stacked layers can propagate clues from those nested prefixes. That is why the no-position model does better than a purely orderless caricature might suggest—fixed sinusoidal encoding still produces a large improvement in this run.</p>
<p>But Chapter 10’s LSTM remains ahead by 0.0309 held-out loss, or 1.64%. At 100 characters of context and roughly 133,000 parameters, the LSTM wins this regime. This comparison matches corpus, parameter scale, updates, minibatch order, optimizer, clipping, and evaluation. It does not match internal architecture—or promise that either model has been tuned to its own optimum. We did not repeat the comparison across initialization seeds, so the 0.4214 gap is a controlled case study, not an estimate of an average effect.</p>
</div>
</div>
<section id="what-did-the-heads-route" class="level3">
<h3 class="anchored" data-anchor-id="what-did-the-heads-route">What did the heads route?</h3>
<p>An attention map records routing weights, not reasons, confidence, or a guaranteed explanation of a prediction. Still, inspecting real learned maps can verify the mask and reveal the kinds of patterns a trained model happened to use. The next cell sends the prompt <em>The gradient</em> through the positional model and plots the second block’s four heads.</p>
<div id="cell-fig-learned-attention" class="cell" data-fig-height="6" data-fig-width="10" data-execution_count="10">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>prompt <span class="op">=</span> <span class="st">"The gradient "</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>prompt_tokens <span class="op">=</span> torch.tensor([[stoi[char] <span class="cf">for</span> char <span class="kw">in</span> prompt]])</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>position_model.<span class="bu">eval</span>()</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> torch.no_grad():</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    _, learned_maps <span class="op">=</span> position_model(prompt_tokens, return_weights<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>learned <span class="op">=</span> learned_maps[<span class="op">-</span><span class="dv">1</span>][<span class="dv">0</span>]</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>future <span class="op">=</span> torch.triu(</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>    torch.ones(<span class="bu">len</span>(prompt), <span class="bu">len</span>(prompt), dtype<span class="op">=</span>torch.<span class="bu">bool</span>), diagonal<span class="op">=</span><span class="dv">1</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> learned[:, future].<span class="bu">max</span>().item() <span class="op">==</span> <span class="fl">0.0</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> torch.allclose(</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>    learned.<span class="bu">sum</span>(dim<span class="op">=-</span><span class="dv">1</span>),</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>    torch.ones_like(learned.<span class="bu">sum</span>(dim<span class="op">=-</span><span class="dv">1</span>)),</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>    atol<span class="op">=</span><span class="fl">1e-6</span>,</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>display_tokens <span class="op">=</span> [<span class="st">"·"</span> <span class="cf">if</span> char <span class="op">==</span> <span class="st">" "</span> <span class="cf">else</span> char <span class="cf">for</span> char <span class="kw">in</span> prompt]</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>), layout<span class="op">=</span><span class="st">"constrained"</span>)</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> head, axis <span class="kw">in</span> <span class="bu">enumerate</span>(axes.flat):</span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>    image <span class="op">=</span> axis.imshow(</span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a>        learned[head].numpy(), cmap<span class="op">=</span><span class="st">"viridis"</span>, vmin<span class="op">=</span><span class="dv">0</span>, vmax<span class="op">=</span><span class="dv">1</span></span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a>    axis.set_title(<span class="ss">f"block 2, head </span><span class="sc">{</span>head <span class="op">+</span> <span class="dv">1</span><span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a>    axis.set_xticks(<span class="bu">range</span>(<span class="bu">len</span>(prompt)), display_tokens)</span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a>    axis.set_yticks(<span class="bu">range</span>(<span class="bu">len</span>(prompt)), display_tokens)</span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a>    axis.set_xlabel(<span class="st">"key"</span>)</span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a>    axis.set_ylabel(<span class="st">"query"</span>)</span>
<span id="cb18-29"><a href="#cb18-29" aria-hidden="true" tabindex="-1"></a>fig.colorbar(image, ax<span class="op">=</span>axes, fraction<span class="op">=</span><span class="fl">0.025</span>, shrink<span class="op">=</span><span class="fl">0.8</span>, pad<span class="op">=</span><span class="fl">0.02</span>)</span>
<span id="cb18-30"><a href="#cb18-30" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb18-31"><a href="#cb18-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-32"><a href="#cb18-32" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"maximum future attention:"</span>, learned[:, future].<span class="bu">max</span>().item())</span>
<span id="cb18-33"><a href="#cb18-33" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(</span>
<span id="cb18-34"><a href="#cb18-34" aria-hidden="true" tabindex="-1"></a>    <span class="st">"maximum row-sum error:"</span>,</span>
<span id="cb18-35"><a href="#cb18-35" aria-hidden="true" tabindex="-1"></a>    (learned.<span class="bu">sum</span>(dim<span class="op">=-</span><span class="dv">1</span>) <span class="op">-</span> <span class="dv">1</span>).<span class="bu">abs</span>().<span class="bu">max</span>().item(),</span>
<span id="cb18-36"><a href="#cb18-36" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-learned-attention" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-learned-attention-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="14-self-attention-transformer_files/figure-html/fig-learned-attention-output-1.png" width="788" height="587" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-learned-attention-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.6: Learned attention weights in the second block for the prompt “The gradient ”. The maps are real routing distributions, not explanations or named head roles.
</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>maximum future attention: 0.0
maximum row-sum error: 1.1920928955078125e-07</code></pre>
</div>
</div>
<p>The maps obey the contract exactly: no future key receives weight and every row sums to one. The heads also differ from one another, but naming one “the previous character head” or another “the word head” from this single prompt would outrun the evidence. Attention shows where values were mixed—the rest of the network can transform, cancel, or ignore what was retrieved.</p>
</section>
<section id="listen-but-do-not-grade-by-fluency" class="level3">
<h3 class="anchored" data-anchor-id="listen-but-do-not-grade-by-fluency">Listen, but do not grade by fluency</h3>
<p>Both Transformer variants can now generate by repeatedly truncating to the most recent 100 characters, predicting a distribution for the next one, sampling, and feeding the result back. Unlike Chapter 10’s LSTM, this simple implementation does not carry a recurrent state; it recomputes the current context on every step.</p>
<div id="transformer-samples" class="cell" data-execution_count="11">
<details class="code-fold">
<summary>Code: deterministic samples from both Transformer variants</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"WITH POSITION</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(transformer_sample(position_model, <span class="st">"The gradient "</span>))</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n\n</span><span class="st">WITHOUT POSITION</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(transformer_sample(no_position_model, <span class="st">"The gradient "</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>WITH POSITION

The gradient choing fine on autograd it by tweight the clue larges of calling functions in What independes the gradients $\rightarrow$ well $\rightarrow$ with nexp for logits collapse it is the stanged
normalized of the argument builds give if the five is the funit or principled update a threshat mactumes at tow


WITHOUT POSITION

The gradient explens ine. The beveuind or clos? we the canlay. Wet orurle
this moples doing ther diest the the contive losio thes despunction erbiveng or of a the
corno isy la prenod in thrathe s to derngexperevive. With the chate is the compfathes bl. Thicte olo
tat ur is $L$\vect{w}^\vect{w} = \mectrimes \vect</code></pre>
</div>
</div>
<p>The positional sample has the book’s punctuation, fragments of mathematical vocabulary, and stretches that resemble prose. It still loses its argument. The no-position sample is visibly rougher. Neither qualitative judgment replaces the held-out loss—a sample is one stochastic path, while the loss evaluates every held-out target under the model’s full probability distribution.</p>
<!-- /NOVEL -->
</section>
</section>
<section id="what-the-architecture-bought" class="level2" data-number="14.7">
<h2 data-number="14.7" class="anchored" data-anchor-id="what-the-architecture-bought"><span class="header-section-number">14.7</span> What the architecture bought</h2>
<p>The rematch is not a referendum on all Transformers—it isolates what this small one bought and what it paid.</p>
<p><strong>Direct content routing.</strong> Any earlier visible token can contribute to the next representation in one attention sublayer. The recurrent state no longer has to compress the entire past before the current token can consult it.</p>
<p><strong>Short paths, dense work.</strong> The graph distance between visible tokens is short, but the routing matrix is quadratic in context length. Global access is a different tradeoff, not free memory.</p>
<p><strong>Position becomes a modeling choice.</strong> Convolution and recurrence bake in local order. Attention asks the designer to supply position—and decide visibility. <a href="15-bert-pretraining.html" class="quarto-xref"><span>Chapter 15</span></a> will change visibility itself; <a href="16-vit-scaling.html" class="quarto-xref"><span>Chapter 16</span></a> will revisit what happens when global routing trades away an image model’s locality bias.</p>
<p><strong>A modular residual stream.</strong> Attention moves information, the FFN transforms it, and residual additions let both write into a shared representation. LayerNorm keeps each token’s feature scale manageable along the way.</p>
<p>The causal mask is therefore more than an implementation detail. It says which information a representation is allowed to use. “Visibility is a modeling decision” is the seed this chapter hands forward.</p>
</section>
<section id="okay-so" class="level2" data-number="14.8">
<h2 data-number="14.8" class="anchored" data-anchor-id="okay-so"><span class="header-section-number">14.8</span> Okay, so—</h2>
<ol type="1">
<li><strong>Self-attention reuses Chapter 13’s operator within one sequence.</strong> <span class="math inline">\(Q\)</span>, <span class="math inline">\(K\)</span>, and <span class="math inline">\(V\)</span> all come from <span class="math inline">\(X\)</span>; one learned comparison rule is shared over every ordered pair. Training positions can be evaluated together, while autoregressive generation remains sequential.</li>
<li><strong>Bare attention is permutation equivariant, not invariant.</strong> <span class="math inline">\(\operatorname{SA}(PX)=P\operatorname{SA}(X)\)</span>. Sinusoidal clocks repay Chapter 8’s position debt, and their sine/cosine pairs turn relative shifts into rotations.</li>
<li><strong>Multi-head attention is shape discipline.</strong> Split <span class="math inline">\((B,n,d)\to(B,h,n,d_h)\)</span>, scale by <span class="math inline">\(\sqrt{d_h}\)</span>, form <span class="math inline">\((B,h,n,n)\)</span> routing weights, concatenate, and project. At fixed <span class="math inline">\(d\)</span>, the four leading projections remain about <span class="math inline">\(4d^2\)</span> parameters.</li>
<li><strong>The causal mask defines visibility.</strong> Future scores become negative infinity before softmax. The dense operator still performs quadratic work; the mask does not make the forbidden half computationally disappear.</li>
<li><strong>The block alternates routing and computation.</strong> Multi-head attention mixes positions, the FFN transforms each position, and both write corrections into Chapter 9’s residual stream. LayerNorm is the same normalization equation over a token’s feature axis.</li>
<li><strong>Position wins this seed’s controlled ablation.</strong> It lowers held-out loss from 2.3405 to 1.9190. <strong>The LSTM narrowly wins the small-model rematch</strong>, 1.8881 versus 1.9190. Architecture changes inductive bias; it does not guarantee victory in every data and scale regime.</li>
</ol>
</section>
<section id="sources-and-further-reading" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="sources-and-further-reading">Sources and further reading</h2>
<ul>
<li><a href="https://papers.nips.cc/paper_files/paper/2017/hash/3f5ee243547dee91fbd053c1c4a845aa-Abstract.html">Vaswani et al., <em>Attention Is All You Need</em></a>: multi-head attention, sinusoidal position, and the original post-LayerNorm encoder–decoder.</li>
<li><a href="https://arxiv.org/abs/1607.06450">Ba, Kiros, and Hinton, <em>Layer Normalization</em></a>: normalization within one example and identical train/evaluation computation.</li>
<li><a href="https://proceedings.mlr.press/v119/xiong20b.html">Xiong et al., <em>On Layer Normalization in the Transformer Architecture</em></a>: a qualified comparison of pre- and post-LayerNorm optimization.</li>
<li><a href="https://aclanthology.org/2021.emnlp-main.446/">Geva et al., <em>Transformer Feed-Forward Layers Are Key-Value Memories</em></a>: empirical evidence behind the associative-memory interpretation of FFNs.</li>
<li><a href="https://aclanthology.org/N19-1357/">Jain and Wallace, <em>Attention Is Not Explanation</em></a>: an important limit on reading attention maps as explanations.</li>
</ul>
</section>
<section id="exercises" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercises">Exercises</h2>
<ol type="1">
<li><strong>(Pencil.)</strong> Starting from <span class="math inline">\(Q'=PQ\)</span>, <span class="math inline">\(K'=PK\)</span>, and <span class="math inline">\(V'=PV\)</span>, prove each step of <span class="math inline">\(\operatorname{SA}(PX)=P\operatorname{SA}(X)\)</span>. Then show that mean-pooling the token outputs produces a permutation-<em>invariant</em> sequence representation.</li>
<li><strong>(Pencil.)</strong> For width <span class="math inline">\(d=512\)</span> and <span class="math inline">\(h=8\)</span>, write every tensor shape in multi-head attention for <span class="math inline">\(B=32\)</span> and <span class="math inline">\(n=100\)</span>. Count the weights in <span class="math inline">\(W_Q,W_K,W_V,W_O\)</span>. Repeat for <span class="math inline">\(h=16\)</span> and explain which dimensions change while the leading parameter count does not.</li>
<li><strong>(Code.)</strong> Deliberately transpose the causal mask in <a href="#fig-causal-multihead" class="quarto-xref">Figure&nbsp;<span>14.3</span></a>, then design an assertion that identifies the first leaked query-key pair. Next set forbidden probabilities to zero <em>after</em> softmax and measure the row-sum error.</li>
<li><strong>(Code.)</strong> Replace the fixed sinusoidal table with a learned <span class="math inline">\(\text{Embedding}(100,d)\)</span> while preserving the exact initialization and window schedule protocol. Compare held-out loss. Then extend the sinusoidal buffer by evaluating its formula beyond position 99, and propose an explicit extension rule for the learned table before testing either model on a longer context. Which design has a natural extension, and which has to invent one?</li>
<li><strong>(Code and interpretation.)</strong> Aggregate learned attention by relative offset across the held-out tail rather than naming heads from one prompt. Report a distribution for every head and block. Then perturb the highest-weight key’s value vector and measure the logit change. Explain why routing weight and causal influence need not rank tokens identically.</li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/shakeri-lab\.github\.io\/dl-book\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../chapters/part4/13-attention.html" class="pagination-link" aria-label="Attention: Making the Kernel Learnable">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Attention: Making the Kernel Learnable</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/part4/15-bert-pretraining.html" class="pagination-link" aria-label="The BERT Moment: Pretraining as the New Regime">
        <span class="nav-page-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">The BERT Moment: Pretraining as the New Regime</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Heman Shakeri · Text CC BY-NC-SA 4.0 · Code MIT · School of Data Science, University of Virginia</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/Shakeri-Lab/dl-book/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Companion to <a href="https://shakeri-lab.github.io/dl-course-site/">DS 6050 Deep Learning</a></p>
</div>
  </div>
</footer>




</body></html>