<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>15&nbsp; The BERT Moment: Pretraining as the New Regime – Deep Learning: Making It Learnable</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/part4/16-vit-scaling.html" rel="next">
<link href="../../chapters/part4/14-self-attention-transformer.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-2c6940bf2fa6cf01ae6e8f10fcb58cc9.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>
  // Book math macros — keep in sync with tex/macros.tex (PDF path).
  // MathJax reads this config because it is defined before the MathJax
  // script loads (Quarto places include-in-header above its math script).
  window.MathJax = {
    tex: {
      macros: {
        E: "\\mathbb{E}",
        Ex: "\\operatorname{E}",
        var: "\\operatorname{Var}",
        cov: "\\operatorname{Cov}",
        imp: "\\Rightarrow",
        argmax: "\\operatorname*{arg\\,max}",
        argmin: "\\operatorname*{arg\\,min}",
        norm: ["\\left\\lVert#1\\right\\rVert", 1],
        vect: ["\\boldsymbol{#1}", 1],
        matr: ["\\boldsymbol{#1}", 1],
        R: "\\mathbb{R}",
        dd: "\\mathrm{d}",
        loss: "\\mathcal{L}"
      }
    }
  };
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/part4/12-kernel-regression.html">Attention: Learning the Similarity</a></li><li class="breadcrumb-item"><a href="../../chapters/part4/15-bert-pretraining.html"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">The BERT Moment: Pretraining as the New Regime</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Deep Learning: Making It Learnable</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/Shakeri-Lab/dl-book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">From Lines to Networks</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/01-linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Linear Regression, the Mother Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/02-logistic-softmax.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Linear Models that Classify: Logistic and Softmax</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/03-nonlinearity-mlp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Nonlinearity and the MLP</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/04-training-loss-sgd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Training: Loss and Stochastic Gradient Descent</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/05-backpropagation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Backpropagation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/06-generalization-inductive-bias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">When It Fails: Generalization in Pictures, and Inductive Bias</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/interludes/learning-by-experiment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Who Trains the Trainer? Learning by Experiment</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Vision: Learning the Filters</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/07-filters-convolution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Filters and Convolution (Fixed Kernels)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/08-cnn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">CNNs: Making the Filters Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/09-modern-cnns-transfer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Modern CNNs and Transfer Learning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/interludes/making-pca-learnable.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Interlude: Making PCA Learnable</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Sequences</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part3/10-sequences-rnn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Sequences and Recurrence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part3/11-encoder-decoder.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Encoder–Decoder, Teacher Forcing, Beam Search</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Attention: Learning the Similarity</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/12-kernel-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Kernel Regression: Attention Before It Was Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/13-attention.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Attention: Making the Kernel Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/14-self-attention-transformer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Self-Attention and the Transformer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/15-bert-pretraining.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">The BERT Moment: Pretraining as the New Regime</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/16-vit-scaling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Vision Transformers and Scaling Laws</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">The Pretrained Era</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/17-peft-quantization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Adapting Pretrained Models: Prompting, PEFT, Quantization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/18-alignment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Alignment and RL Fine-Tuning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/19-generative.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Generative Models: From Codes to Samples</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/20-multimodal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Multimodal Learning: One Space, Two Views</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/epilogue.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Epilogue: The Question Is Yours</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a1-linear-algebra.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Linear Algebra and the SVD</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a2-tensors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Tensors in Practice</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a3-precision-performance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Numerical Precision and Hardware Efficiency</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a4-notation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Notation</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
<div class="quarto-sidebar-footer"><div class="sidebar-footer-item">
<p><a href="https://shakeri-lab.github.io/dl-book/#revision-notes">Revision notes</a></p>
</div></div></nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#separate-controls-not-one-mask" id="toc-separate-controls-not-one-mask" class="nav-link active" data-scroll-target="#separate-controls-not-one-mask"><span class="header-section-number">15.1</span> Separate controls, not one mask</a></li>
  <li><a href="#text-supplies-supervision" id="toc-text-supplies-supervision" class="nav-link" data-scroll-target="#text-supplies-supervision"><span class="header-section-number">15.2</span> Text supplies supervision</a></li>
  <li><a href="#the-masked-language-model-objective" id="toc-the-masked-language-model-objective" class="nav-link" data-scroll-target="#the-masked-language-model-objective"><span class="header-section-number">15.3</span> The masked-language-model objective</a>
  <ul class="collapse">
  <li><a href="#fifteen-percent-then-801010" id="toc-fifteen-percent-then-801010" class="nav-link" data-scroll-target="#fifteen-percent-then-801010">Fifteen percent, then 80/10/10</a></li>
  </ul></li>
  <li><a href="#from-a-transformer-encoder-to-bert" id="toc-from-a-transformer-encoder-to-bert" class="nav-link" data-scroll-target="#from-a-transformer-encoder-to-bert"><span class="header-section-number">15.4</span> From a Transformer encoder to BERT</a>
  <ul class="collapse">
  <li><a href="#cls-is-a-learned-meeting-place" id="toc-cls-is-a-learned-meeting-place" class="nav-link" data-scroll-target="#cls-is-a-learned-meeting-place"><code>[CLS]</code> is a learned meeting place</a></li>
  </ul></li>
  <li><a href="#fine-tuning-means-the-backbone-moves" id="toc-fine-tuning-means-the-backbone-moves" class="nav-link" data-scroll-target="#fine-tuning-means-the-backbone-moves"><span class="header-section-number">15.5</span> Fine-tuning means the backbone moves</a></li>
  <li><a href="#a-controlled-transfer-lab" id="toc-a-controlled-transfer-lab" class="nav-link" data-scroll-target="#a-controlled-transfer-lab"><span class="header-section-number">15.6</span> A controlled transfer lab</a>
  <ul class="collapse">
  <li><a href="#build-a-latent-regularity" id="toc-build-a-latent-regularity" class="nav-link" data-scroll-target="#build-a-latent-regularity">Build a latent regularity</a></li>
  <li><a href="#a-small-bert-style-encoder" id="toc-a-small-bert-style-encoder" class="nav-link" data-scroll-target="#a-small-bert-style-encoder">A small BERT-style encoder</a></li>
  <li><a href="#pretrain-then-adapt" id="toc-pretrain-then-adapt" class="nav-link" data-scroll-target="#pretrain-then-adapt">Pretrain, then adapt</a></li>
  <li><a href="#what-transferred" id="toc-what-transferred" class="nav-link" data-scroll-target="#what-transferred">What transferred?</a></li>
  </ul></li>
  <li><a href="#three-pretraining-families" id="toc-three-pretraining-families" class="nav-link" data-scroll-target="#three-pretraining-families"><span class="header-section-number">15.7</span> Three pretraining families</a></li>
  <li><a href="#what-changed-after-2018" id="toc-what-changed-after-2018" class="nav-link" data-scroll-target="#what-changed-after-2018"><span class="header-section-number">15.8</span> What changed after 2018</a></li>
  <li><a href="#okay-so-pretraining-manufactures-supervision" id="toc-okay-so-pretraining-manufactures-supervision" class="nav-link" data-scroll-target="#okay-so-pretraining-manufactures-supervision"><span class="header-section-number">15.9</span> Okay, so — pretraining manufactures supervision</a></li>
  <li><a href="#sources-and-further-reading" id="toc-sources-and-further-reading" class="nav-link" data-scroll-target="#sources-and-further-reading">Sources and further reading</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/Shakeri-Lab/dl-book/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/part4/12-kernel-regression.html">Attention: Learning the Similarity</a></li><li class="breadcrumb-item"><a href="../../chapters/part4/15-bert-pretraining.html"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">The BERT Moment: Pretraining as the New Regime</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-15-bert-pretraining" class="quarto-section-identifier"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">The BERT Moment: Pretraining as the New Regime</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<!-- lecture-source:
     m10_10-2-pretrained-transformer-models_SDHOqinS8dg.txt
     (spine via ds6050_10_foundation_models/MODULE_NOTES.md; scene concepts
     checked against that module's Manim source)
     seeds: sources/bert.tex, sources/10.2_pretrained.tex
     subword bridge: machine-local course seed
                     LaTeX/Module 8,9-Transformer/8S.tex, BPE section only;
                     the mechanism code below is independently written
     primary sources: Peters et al. 2018; Howard and Ruder 2018;
                      Radford et al. 2018; Devlin et al. 2019;
                      Liu et al. 2019; Raffel et al. 2020
     provenance note: the executable MLM and encoder implementations are
     independently derived from the displayed equations. The synthetic
     transfer study is book-original, uses atomic word tokens rather than
     WordPiece, and is a mechanism demonstration rather than a BERT replica.
     The lecture scene depicts a frozen Transformer; the chapter corrects that
     view by reserving “frozen” for a probe and showing original BERT-style
     fine-tuning as updates through the full backbone. -->
<p>Chapter 9 left a decision rule unfinished. Transfer should pay when <strong>labels are scarce, the target is feature-hungry, and source coverage is useful at a matched scale</strong>. Images supplied a natural source task—learn visual features from many labeled photographs, then adapt them. What should play the same role for language, where task labels are expensive but raw text is everywhere?</p>
<p>Text can write its own questions. Hide <em>bank</em> in “the boat reached the bank,” and the surrounding words contain the answer. Hide the same spelling in “the bank approved the loan,” and a different neighborhood supplies a different answer. No person had to label either sense. The answer is already inside the sequence; corruption turns it into a question.</p>
<p>That move depends on the seed from <a href="14-self-attention-transformer.html" class="quarto-xref"><span>Chapter 14</span></a>: <strong>visibility is a modeling decision</strong>. A next-token model used a causal triangle because looking right would reveal its target. A representation model can instead let every nonpadding token consult both sides—provided selected targets are treated so copying cannot solve the whole task. This chapter separates those controls, derives <strong>masked language modeling (MLM)</strong>, and shows how pretraining changed the default workflow from “initialize and train” to “pretrain, then adapt.”</p>
<section id="separate-controls-not-one-mask" class="level2" data-number="15.1">
<h2 data-number="15.1" class="anchored" data-anchor-id="separate-controls-not-one-mask"><span class="header-section-number">15.1</span> Separate controls, not one mask</h2>
<p>Bidirectional Encoder Representations from Transformers—<strong>BERT</strong>—uses a few special tokens. <code>[CLS]</code> is a learned summary placeholder, <code>[SEP]</code> marks a boundary, and <code>[PAD]</code> fills unused batch slots. Consider six positions:</p>
<p><span class="math display">\[
[\text{CLS}],\quad \text{the},\quad \text{bank},\quad \text{rose},\quad
[\text{SEP}],\quad [\text{PAD}].
\]</span></p>
<p>There are four distinct decisions in play.</p>
<ol type="1">
<li><strong>Attention visibility</strong> decides which key positions each query may use. A causal decoder blocks future keys; a BERT encoder permits all nonpadding keys.</li>
<li><strong>The MLM target selector</strong> chooses which ordinary positions contribute loss.</li>
<li><strong>The corruption branch</strong> replaces some selected tokens by <code>[MASK]</code>, replaces some by random tokens, and deliberately leaves some unchanged.</li>
<li><strong>The padding mask</strong> prevents real tokens from routing information from placeholder slots used only to make batch shapes rectangular.</li>
</ol>
<div id="cell-fig-visibility-corruption" class="cell" data-fig-height="3.2" data-fig-width="10" data-execution_count="1">
<details class="code-fold">
<summary>Figure code: separate attention visibility from MLM selection</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> copy</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> itertools</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> torch <span class="im">import</span> nn</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.nn.functional <span class="im">as</span> F</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>tokens <span class="op">=</span> [<span class="st">"[CLS]"</span>, <span class="st">"the"</span>, <span class="st">"bank"</span>, <span class="st">"rose"</span>, <span class="st">"[SEP]"</span>, <span class="st">"[PAD]"</span>]</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>nonpadding <span class="op">=</span> np.array([<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>], dtype<span class="op">=</span><span class="bu">bool</span>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>causal <span class="op">=</span> np.tril(np.ones((<span class="dv">6</span>, <span class="dv">6</span>), dtype<span class="op">=</span><span class="bu">int</span>)) <span class="op">*</span> nonpadding[<span class="va">None</span>, :]</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>full <span class="op">=</span> np.ones((<span class="dv">6</span>, <span class="dv">6</span>), dtype<span class="op">=</span><span class="bu">int</span>) <span class="op">*</span> nonpadding[<span class="va">None</span>, :]</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>selector <span class="op">=</span> np.zeros((<span class="dv">1</span>, <span class="dv">6</span>), dtype<span class="op">=</span><span class="bu">int</span>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>selector[<span class="dv">0</span>, <span class="dv">2</span>] <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    <span class="dv">1</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="fl">3.2</span>), gridspec_kw<span class="op">=</span>{<span class="st">"width_ratios"</span>: [<span class="dv">1</span>, <span class="dv">1</span>, <span class="fl">0.45</span>]}</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> axis, matrix, title <span class="kw">in</span> [</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>    (axes[<span class="dv">0</span>], causal, <span class="st">"causal visibility"</span>),</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    (axes[<span class="dv">1</span>], full, <span class="st">"full nonpadding visibility"</span>),</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>]:</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>    axis.imshow(matrix, cmap<span class="op">=</span><span class="st">"Blues"</span>, vmin<span class="op">=</span><span class="dv">0</span>, vmax<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>    axis.set_xticks(<span class="bu">range</span>(<span class="dv">6</span>), tokens, rotation<span class="op">=</span><span class="dv">55</span>, ha<span class="op">=</span><span class="st">"right"</span>)</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>    axis.set_yticks(<span class="bu">range</span>(<span class="dv">6</span>), tokens)</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>    axis.set_xlabel(<span class="st">"key"</span>)</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>    axis.set_ylabel(<span class="st">"query"</span>)</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>    axis.set_title(title)</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].imshow(selector.T, cmap<span class="op">=</span><span class="st">"Oranges"</span>, vmin<span class="op">=</span><span class="dv">0</span>, vmax<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_yticks(<span class="bu">range</span>(<span class="dv">6</span>), tokens)</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_xticks([<span class="dv">0</span>], [<span class="st">"loss"</span>])</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_title(<span class="st">"MLM selector"</span>)</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-visibility-corruption" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Three aligned matrices for the tokens CLS, the, bank, rose, SEP, and PAD. Causal visibility forms a dark lower triangle and excludes PAD; full nonpadding visibility forms a dark rectangle over the first five key columns for every query; the separate one-column loss selector highlights only the token bank.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-visibility-corruption-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="15-bert-pretraining_files/figure-html/fig-visibility-corruption-output-1.png" alt="Three aligned matrices for the tokens CLS, the, bank, rose, SEP, and PAD. Causal visibility forms a dark lower triangle and excludes PAD; full nonpadding visibility forms a dark rectangle over the first five key columns for every query; the separate one-column loss selector highlights only the token bank." width="884" height="299" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-visibility-corruption-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15.1: Visibility and supervision are separate controls. A causal decoder sees a lower triangle (left); BERT-style attention sees every nonpadding key (center). The MLM selector marks one selected target position (right).
</figcaption>
</figure>
</div>
</div>
</div>
<p>The center matrix contains no future-blocking triangle. Every nonpadding query can route from every nonpadding key—including itself. That is what <em>bidirectional</em> means here: a token’s representation can jointly use left and right context in every layer. It does not mean running two separate recurrent networks, and it does not define a left-to-right probability for the whole sentence.</p>
<p>Only padding <em>keys</em> are blocked in the drawing. A <code>[PAD]</code> query row can still produce an output, but downstream computation ignores that row; the important guarantee is that real queries cannot retrieve padding as information.</p>
<p>Now suppose <em>bank</em> is selected and replaced:</p>
<p><span class="math display">\[
[\text{CLS}]\ \text{the}\ [\text{MASK}]\ \text{rose}\ [\text{SEP}].
\]</span></p>
<p>Every ordinary token may attend to <code>[MASK]</code>, because <code>[MASK]</code> is an input token—not an attention prohibition. Only the selector says that position 2 contributes MLM loss. The padding mask separately blocks the final slot as a key. Reusing <em>mask</em> for visibility, selection, corruption, and padding is convenient shorthand—and a reliable source of bugs.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>The copy trap
</div>
</div>
<div class="callout-body-container callout-body">
<p>If full attention received the original token at <em>every</em> selected position, the model could copy answers through the residual stream. BERT’s policy corrupts 90% of selected sites, so copying cannot solve the whole task; the deliberate 10% unchanged branch has a separate purpose below. Conversely, replacing a token by <code>[MASK]</code> does not make it invisible—its neighbors still see the placeholder and one another. Always audit visibility, selection, corruption, and padding separately.</p>
</div>
</div>
</section>
<section id="text-supplies-supervision" class="level2" data-number="15.2">
<h2 data-number="15.2" class="anchored" data-anchor-id="text-supplies-supervision"><span class="header-section-number">15.2</span> Text supplies supervision</h2>
<p>In ordinary supervised learning, an external label <span class="math inline">\(y\)</span> accompanies input <span class="math inline">\(x\)</span>. Masked language modeling derives both from one unlabeled sequence: the corrupted sequence is the input, and the original selected tokens are the targets. This is <em>self-supervised learning</em>—the supervision is constructed from the data rather than supplied by a human annotator.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Self-supervised does not mean target-free
</div>
</div>
<div class="callout-body-container callout-body">
<p>The method still has labels and a loss. What changes is their origin. The clean text supplies a target for every selected position, so a large corpus can create many training examples without a task-specific annotation campaign.</p>
</div>
</div>
<p>This idea was part of a broader 2018 convergence, not a solitary invention.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Work</th>
<th>Pretraining signal</th>
<th>What moved downstream</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ELMo</td>
<td>Forward and backward LSTM language models</td>
<td>Fixed contextual features</td>
</tr>
<tr class="even">
<td>ULMFiT</td>
<td>Causal language modeling</td>
<td>The entire adapted language model</td>
</tr>
<tr class="odd">
<td>GPT</td>
<td>Causal Transformer language modeling</td>
<td>A pretrained Transformer plus task head</td>
</tr>
<tr class="even">
<td>BERT</td>
<td>Masked tokens in full context, plus NSP</td>
<td>A deeply bidirectional Transformer encoder plus task head</td>
</tr>
</tbody>
</table>
<p>ELMo demonstrated that a word’s useful vector should depend on its sentence. ULMFiT supplied a robust recipe for adapting a pretrained language model rather than freezing it. GPT paired Transformer pretraining with supervised fine-tuning. BERT’s decisive change was to pretrain every encoder layer with joint left-and-right context. The workflow mattered as much as the architecture: learn broadly from raw text first, then spend scarce labels on adaptation.</p>
</section>
<section id="the-masked-language-model-objective" class="level2" data-number="15.3">
<h2 data-number="15.3" class="anchored" data-anchor-id="the-masked-language-model-objective"><span class="header-section-number">15.3</span> The masked-language-model objective</h2>
<p>Let us pin the idea to shapes before writing code. Let a tokenized sequence be</p>
<p><span class="math display">\[
x=(x_1,\ldots,x_T),\qquad x_t\in\{1,\ldots,|V|\},
\]</span></p>
<p>where <span class="math inline">\(T\)</span> is sequence length and <span class="math inline">\(V\)</span> is the vocabulary. Choose a random set <span class="math inline">\(M\)</span> of eligible positions, then apply a corruption operator <span class="math inline">\(c\)</span> to obtain <span class="math inline">\(\widetilde{x}=c(x,M)\)</span>. A bidirectional encoder with parameters <span class="math inline">\(\theta\)</span> produces</p>
<p><span class="math display">\[
H=f_\theta(\widetilde{x})\in\mathbb{R}^{T\times d}.
\]</span></p>
<p>An output head maps each selected hidden state to vocabulary logits. The MLM loss is</p>
<p><span class="math display">\[
\mathcal{L}_{\mathrm{MLM}}(\theta)
=-
\frac{1}{|M|}
\sum_{i\in M}
\log p_\theta\!\left(x_i\mid \widetilde{x}\right).
\]</span></p>
<p>The condition is <span class="math inline">\(\widetilde{x}\)</span>, the one jointly corrupted sequence—not a different clean sequence with only <span class="math inline">\(x_i\)</span> removed for every term. With batches, token IDs have shape <span class="math inline">\((B,T)\)</span>, hidden states <span class="math inline">\((B,T,d)\)</span>, and dense vocabulary logits <span class="math inline">\((B,T,|V|)\)</span>. Boolean selection gathers <span class="math inline">\(|M|\)</span> rows, so cross-entropy receives selected logits <span class="math inline">\((|M|,|V|)\)</span> and targets <span class="math inline">\((|M|,)\)</span>. Unselected positions can affect the representations but contribute no direct MLM loss.</p>
<section id="fifteen-percent-then-801010" class="level3">
<h3 class="anchored" data-anchor-id="fifteen-percent-then-801010">Fifteen percent, then 80/10/10</h3>
<p>Original BERT selects 15% of eligible tokens. Conditional on selection:</p>
<ul>
<li>80% are replaced by <code>[MASK]</code>;</li>
<li>10% are replaced by a random vocabulary token;</li>
<li>10% remain unchanged.</li>
</ul>
<p>For 1,000 eligible positions, the expected flow is therefore</p>
<p><span class="math display">\[
1000\longrightarrow150\longrightarrow
\begin{cases}
120 &amp; [\text{MASK}],\\
15 &amp; \text{random token},\\
15 &amp; \text{unchanged}.
\end{cases}
\]</span></p>
<p>All 150 selected positions are scored against their original token. The 120 mask replacements are 12% of all eligible positions, not the complete supervision rate. Random ordinary-looking replacements force the encoder to cross-check a token against its context rather than trusting the visible identity. The unchanged branch prevents the opposite shortcut—the assumption that every selected ordinary-looking token must be wrong. It also reduces the mismatch between pretraining, where <code>[MASK]</code> exists, and downstream inputs, where it ordinarily does not. An unchanged selected token exposes its answer on purpose; only about 1.5% of all eligible positions follow that branch, and the encoder is not told which normal-looking tokens were selected.</p>
<div id="cell-fig-mlm-policy" class="cell" data-fig-height="3.2" data-fig-width="9" data-execution_count="2">
<details class="code-fold">
<summary>Figure code: trace the two-stage MLM selection policy</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>eligible_count <span class="op">=</span> <span class="dv">1_000</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>selected_count <span class="op">=</span> <span class="bu">round</span>(<span class="fl">0.15</span> <span class="op">*</span> eligible_count)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>branch_counts <span class="op">=</span> np.array([<span class="dv">120</span>, <span class="dv">15</span>, <span class="dv">15</span>])</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>branch_labels <span class="op">=</span> [<span class="st">"[MASK]"</span>, <span class="st">"random"</span>, <span class="st">"unchanged"</span>]</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>branch_colors <span class="op">=</span> [<span class="st">"#3566a8"</span>, <span class="st">"#d37b29"</span>, <span class="st">"#6b7280"</span>]</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="fl">3.2</span>))</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].bar(</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    [<span class="st">"not selected"</span>, <span class="st">"selected"</span>],</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    [eligible_count <span class="op">-</span> selected_count, selected_count],</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span>[<span class="st">"#d9dde3"</span>, <span class="st">"#3566a8"</span>],</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"eligible positions"</span>)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">"first draw: 15%"</span>)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].bar_label(axes[<span class="dv">0</span>].containers[<span class="dv">0</span>])</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>bars <span class="op">=</span> axes[<span class="dv">1</span>].bar(branch_labels, branch_counts, color<span class="op">=</span>branch_colors)</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_ylabel(<span class="st">"selected positions"</span>)</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">"conditional branch: 80 / 10 / 10"</span>)</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].bar_label(bars)</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"direct loss targets: </span><span class="sc">{</span>branch_counts<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"[MASK] share of all eligible positions: </span><span class="sc">{</span>branch_counts[<span class="dv">0</span>] <span class="op">/</span> <span class="dv">1000</span><span class="sc">:.1%}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-mlm-policy" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two-stage bar chart for 1,000 eligible positions. The first panel divides them into 850 not selected and 150 selected. The second divides those 150 selected positions into 120 replaced by MASK, 15 replaced randomly, and 15 left unchanged.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlm-policy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="15-bert-pretraining_files/figure-html/fig-mlm-policy-output-1.png" alt="Two-stage bar chart for 1,000 eligible positions. The first panel divides them into 850 not selected and 150 selected. The second divides those 150 selected positions into 120 replaced by MASK, 15 replaced randomly, and 15 left unchanged." width="855" height="297" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlm-policy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15.2: BERT’s 80/10/10 policy is conditional on the selected 15%. All three branches retain the original token as the prediction target.
</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>direct loss targets: 150
[MASK] share of all eligible positions: 12.0%</code></pre>
</div>
</div>
<p>Original BERT pre-generated several masked versions of its training examples; RoBERTa later redrew masks as examples were presented. Our controlled lab uses the latter <em>dynamic corruption</em> choice—the same sentence can ask different questions on later passes. Reproducibility therefore requires a separate random generator. Seeding model initialization while leaving the corruption stream implicit is not an exact experiment.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Audit the selector before the loss
</div>
</div>
<div class="callout-body-container callout-body">
<p>Print the number of eligible and selected positions, verify that special and padding tokens are excluded, and inspect the realized 80/10/10 proportions over many batches. Then assert that the selected logit and target shapes agree. A loss can decrease while a selector silently trains on padding or on the wrong tokens.</p>
</div>
</div>
</section>
</section>
<section id="from-a-transformer-encoder-to-bert" class="level2" data-number="15.4">
<h2 data-number="15.4" class="anchored" data-anchor-id="from-a-transformer-encoder-to-bert"><span class="header-section-number">15.4</span> From a Transformer encoder to BERT</h2>
<p>The original BERT input at position <span class="math inline">\(i\)</span> adds three learned vectors:</p>
<p><span class="math display">\[
z_i=e_{\text{token}(i)}+e_{\text{position}(i)}+e_{\text{segment}(i)}.
\]</span></p>
<p>The token comes from a <strong>WordPiece</strong> vocabulary: frequent character sequences are stored whole, while rarer words can be assembled from reusable subword pieces.</p>
<!-- NOVEL: needs sign-off - original BPE mechanism bridge requested in the course review. -->
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Practice bridge (non-examinable): make the vocabulary learnable
</div>
</div>
<div class="callout-body-container callout-body">
<p>Chapter 10 fixed its vocabulary at individual characters (<a href="../part3/10-sequences-rnn.html" class="quarto-xref"><span>Chapter 10</span></a>). A full-word vocabulary shortens sequences but gives every rare spelling its own entry. Subword tokenization chooses a middle contract. <strong>Byte Pair Encoding (BPE)</strong> begins with small symbols, counts adjacent pairs in the training corpus, merges the most frequent pair, and repeats until it reaches a chosen vocabulary budget.</p>
<p>This original toy implementation starts from characters plus an end-of-word marker. Corpus frequencies weight the pair counts; lexicographic order breaks exact ties so the result is reproducible.</p>
</div>
</div>
<div id="bpe-mechanism" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code: learn five subword merges from weighted word counts</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> collections <span class="im">import</span> Counter</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> merge_pair(</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    symbols: <span class="bu">tuple</span>[<span class="bu">str</span>, ...], pair: <span class="bu">tuple</span>[<span class="bu">str</span>, <span class="bu">str</span>]</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>) <span class="op">-&gt;</span> <span class="bu">tuple</span>[<span class="bu">str</span>, ...]:</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    merged: <span class="bu">list</span>[<span class="bu">str</span>] <span class="op">=</span> []</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    index <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">while</span> index <span class="op">&lt;</span> <span class="bu">len</span>(symbols):</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> index <span class="op">+</span> <span class="dv">1</span> <span class="op">&lt;</span> <span class="bu">len</span>(symbols) <span class="kw">and</span> symbols[index:index <span class="op">+</span> <span class="dv">2</span>] <span class="op">==</span> pair:</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>            merged.append(<span class="st">""</span>.join(pair))</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>            index <span class="op">+=</span> <span class="dv">2</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span>:</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>            merged.append(symbols[index])</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>            index <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="bu">tuple</span>(merged)</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>corpus <span class="op">=</span> {<span class="st">"low"</span>: <span class="dv">5</span>, <span class="st">"lower"</span>: <span class="dv">2</span>, <span class="st">"newest"</span>: <span class="dv">6</span>, <span class="st">"widest"</span>: <span class="dv">3</span>}</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>words <span class="op">=</span> {<span class="bu">tuple</span>(word) <span class="op">+</span> (<span class="st">"&lt;/w&gt;"</span>,): count <span class="cf">for</span> word, count <span class="kw">in</span> corpus.items()}</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>merges: <span class="bu">list</span>[<span class="bu">tuple</span>[<span class="bu">tuple</span>[<span class="bu">str</span>, <span class="bu">str</span>], <span class="bu">int</span>]] <span class="op">=</span> []</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">5</span>):</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>    counts: Counter[<span class="bu">tuple</span>[<span class="bu">str</span>, <span class="bu">str</span>]] <span class="op">=</span> Counter()</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> symbols, frequency <span class="kw">in</span> words.items():</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> pair <span class="kw">in</span> <span class="bu">zip</span>(symbols, symbols[<span class="dv">1</span>:]):</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>            counts[pair] <span class="op">+=</span> frequency</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>    maximum <span class="op">=</span> <span class="bu">max</span>(counts.values())</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>    best <span class="op">=</span> <span class="bu">min</span>(pair <span class="cf">for</span> pair, count <span class="kw">in</span> counts.items() <span class="cf">if</span> count <span class="op">==</span> maximum)</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>    merges.append((best, maximum))</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>    words <span class="op">=</span> {merge_pair(symbols, best): count <span class="cf">for</span> symbols, count <span class="kw">in</span> words.items()}</span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"merges:"</span>, [(<span class="st">"+"</span>.join(pair), count) <span class="cf">for</span> pair, count <span class="kw">in</span> merges])</span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"lower:"</span>, <span class="st">" | "</span>.join(<span class="bu">next</span>(word <span class="cf">for</span> word <span class="kw">in</span> words <span class="cf">if</span> <span class="st">"r"</span> <span class="kw">in</span> word)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>merges: [('e+s', 9), ('es+t', 9), ('est+&lt;/w&gt;', 9), ('l+o', 7), ('lo+w', 7)]
lower: low | e | r | &lt;/w&gt;</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Reading the learned pieces (non-examinable)
</div>
</div>
<div class="callout-body-container callout-body">
<p>The first three merges build <code>est&lt;/w&gt;</code> from nine weighted occurrences; the next two build <code>low</code> from seven. The word <code>lower</code> is therefore represented as <code>low | e | r | &lt;/w&gt;</code> even though the whole word was never granted its own token. This is the mechanism, not BERT’s tokenizer: WordPiece uses a different merge-scoring criterion, and practical byte-level tokenizers begin from bytes rather than the toy character alphabet. The shared idea is the important one: the vocabulary becomes a learned compromise between sequence length and reusable coverage.</p>
</div>
</div>
<!-- /NOVEL -->
<p>Learned absolute position embeddings replace Chapter 14’s fixed sinusoidal table. Segment A/B embeddings mark which of two packed text spans supplied a token; they do not block cross-segment attention. <code>[CLS]</code> begins the sequence, and <code>[SEP]</code> ends each span:</p>
<p><span class="math display">\[
[\text{CLS}]\ A\ [\text{SEP}]\ B\ [\text{SEP}].
\]</span></p>
<p>The resulting sequence passes through a stack of full-context Transformer encoder blocks. Original BERT uses the post-LayerNorm order introduced as the historical Transformer in <a href="14-self-attention-transformer.html" class="quarto-xref"><span>Chapter 14</span></a>. Its two published sizes were:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Model</th>
<th style="text-align: right;">Blocks <span class="math inline">\(L\)</span></th>
<th style="text-align: right;">Width <span class="math inline">\(d\)</span></th>
<th style="text-align: right;">Heads</th>
<th style="text-align: right;">Parameters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>BERT Base</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">768</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">about 110 million</td>
</tr>
<tr class="even">
<td>BERT Large</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">1,024</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">about 340 million</td>
</tr>
</tbody>
</table>
<p>Pretraining used BooksCorpus and English Wikipedia—about 3.3 billion words in the paper’s accounting. The scale is historically important—but the reusable idea is the separation of stages:</p>
<p><span class="math display">\[
\text{raw text}\xrightarrow{\text{self-supervised pretraining}}
\text{general encoder}\xrightarrow{\text{labeled adaptation}}
\text{task model}.
\]</span></p>
<p>Original BERT combined MLM with <strong>next sentence prediction</strong> (NSP). Half the training pairs used the actual following segment and half used a random segment; the <code>[CLS]</code> state predicted which kind it saw—its direct pretraining assignment. MLM alone gives <code>[CLS]</code> no token-reconstruction target, although information can still route through it. Later recipes such as RoBERTa showed that strong BERT-style training did not require NSP in their settings. That is a recipe result, not proof that a sentence-relation objective can never help. This chapter studies the MLM half because it supplies the cleanest bridge from visibility to representation learning.</p>
<section id="cls-is-a-learned-meeting-place" class="level3">
<h3 class="anchored" data-anchor-id="cls-is-a-learned-meeting-place"><code>[CLS]</code> is a learned meeting place</h3>
<p><code>[CLS]</code> is an ordinary learned token with an unusual assignment: place it first, allow it to attend through every layer, then give its final hidden state to a sequence-level head. For <span class="math inline">\(K\)</span> classes,</p>
<p><span class="math display">\[
\ell=W_{\mathrm{cls}}h_{\mathrm{CLS}}+b,
\qquad W_{\mathrm{cls}}\in\mathbb{R}^{K\times d}.
\]</span></p>
<p>For token labeling, apply a head to every <span class="math inline">\(h_i\)</span>. For extractive question answering, score candidate start and end positions. The encoder interface stays the same while the small task head changes.</p>
<p><code>[CLS]</code> is not born with sentence meaning. Pretraining and downstream gradients teach it what information to gather. Chapter 16 will reuse this learned-summary pattern after replacing words by image patches.</p>
</section>
</section>
<section id="fine-tuning-means-the-backbone-moves" class="level2" data-number="15.5">
<h2 data-number="15.5" class="anchored" data-anchor-id="fine-tuning-means-the-backbone-moves"><span class="header-section-number">15.5</span> Fine-tuning means the backbone moves</h2>
<p>Let <span class="math inline">\(\theta_0\)</span> denote pretrained encoder weights and <span class="math inline">\(\phi\)</span> a newly initialized task head. Standard BERT fine-tuning solves</p>
<p><span class="math display">\[
(\theta^*,\phi^*)
=\arg\min_{\theta,\phi}
\sum_{(x,y)\in\mathcal{D}_{\mathrm{task}}}
\mathcal{L}_{\mathrm{task}}
\bigl(g_\phi(f_\theta(x)),y\bigr),
\]</span></p>
<p>starting at <span class="math inline">\(\theta=\theta_0\)</span>. Gradients update both <span class="math inline">\(\theta\)</span> and <span class="math inline">\(\phi\)</span>. Freezing <span class="math inline">\(\theta_0\)</span> and training only <span class="math inline">\(\phi\)</span> is a useful <em>linear probe</em> or feature probe, but it is not the standard fine-tuning procedure. This distinction matters when the task needs the representation itself to move.</p>
<div id="cell-fig-bert-adaptation" class="cell" data-fig-height="3.8" data-fig-width="10" data-execution_count="4">
<div class="cell-output cell-output-display">
<div id="fig-bert-adaptation" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Flow diagram from a tokenized CLS-to-SEP input into a large pretrained BERT encoder, then out to three alternatives: a sequence-classification head from the CLS state, token tags from all states, or span start and end scores. A red arrow points backward from task loss through the encoder to show that all layers update.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bert-adaptation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="15-bert-pretraining_files/figure-html/fig-bert-adaptation-output-1.png" alt="Flow diagram from a tokenized CLS-to-SEP input into a large pretrained BERT encoder, then out to three alternatives: a sequence-classification head from the CLS state, token tags from all states, or span start and end scores. A red arrow points backward from task loss through the encoder to show that all layers update." width="950" height="355" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bert-adaptation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15.3: One pretrained encoder supports several task interfaces. In standard fine-tuning, task-loss gradients pass through the new head and continue through the encoder; stopping them at the head would make the run a frozen probe.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Fine-tuning also creates experimental obligations. The scratch and pretrained arms must share labeled examples, head initialization, minibatch order, update count, evaluation, and downstream hyperparameters. The pretrained arm has already received extra unlabeled-data compute, so the comparison estimates the value of pretraining—not a total-compute advantage.</p>
</section>
<section id="a-controlled-transfer-lab" class="level2" data-number="15.6">
<h2 data-number="15.6" class="anchored" data-anchor-id="a-controlled-transfer-lab"><span class="header-section-number">15.6</span> A controlled transfer lab</h2>
<p>Chapter 9’s three gates are easy to repeat and surprisingly hard to test. A first pre-test asked a tiny encoder to distinguish true continuations in this book from distant splices. The five-seed MLM gain was small, faded as labels increased, and lost decisively to a weighted lexical-overlap baseline. We rejected that task as the chapter’s affirmative experiment—the shallow baseline solved more of the problem than the representation story did.</p>
<p>The replacement lab is synthetic by design. It removes spelling, frequency, and downstream-context shortcuts so that source coverage is a controllable variable.</p>
<!-- NOVEL: needs sign-off - synthetic distributional-transfer experiment. -->
<section id="build-a-latent-regularity" class="level3">
<h3 class="anchored" data-anchor-id="build-a-latent-regularity">Build a latent regularity</h3>
<p>Eighty randomly generated four-letter token strings are divided into two latent families. Family assignment is independent of spelling. Forty <em>covered</em> strings—20 per family—each appear eight times in an unlabeled MLM corpus. Forty more—20 per family—live in the input vocabulary but are withheld from MLM input sequences, random replacements, and prediction targets.</p>
<p>Each covered word receives eight source sentences. Six contain cues from its own family; two deliberately contain cues from the other family. One family appears near words such as <em>rain</em>, <em>soil</em>, <em>roots</em>, and <em>garden</em>; the other appears near <em>power</em>, <em>metal</em>, <em>gears</em>, and <em>workshop</em>. The 25% cue noise gives every covered string a mixture of supporting and opposing contexts—the aggregate family signal is statistical rather than pure.</p>
<p>The downstream input is always the neutral, previously unseen template</p>
<p><span class="math display">\[
\text{“we found the PSEUDOWORD today.”}
\]</span></p>
<p>No family cue remains. A classifier reads the generated token’s hidden state and receives only 1, 2, or 4 labeled word types from each family. Evaluation uses the remaining covered types, never the labeled types. The 40 uncovered controls use the same neutral sentence. Source and target use the same atomic token granularity and similarly short sequences, making “matched scale” explicit rather than assuming it from a shared domain.</p>
<div id="bert-lab-data" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code: construct the controlled source and target distributions</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>SEED <span class="op">=</span> <span class="dv">6050</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>WIDTH <span class="op">=</span> <span class="dv">48</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>HEADS <span class="op">=</span> <span class="dv">4</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>FF_WIDTH <span class="op">=</span> <span class="dv">96</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>BLOCKS <span class="op">=</span> <span class="dv">2</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>MAX_LEN <span class="op">=</span> <span class="dv">10</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>PRETRAIN_STEPS <span class="op">=</span> <span class="dv">600</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>BATCH_SIZE <span class="op">=</span> <span class="dv">64</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>LABEL_COUNTS <span class="op">=</span> (<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">4</span>)</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>REPLICATE_SEEDS <span class="op">=</span> <span class="bu">tuple</span>(<span class="bu">range</span>(<span class="dv">6050</span>, <span class="dv">6055</span>))</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>torch.set_num_threads(<span class="dv">4</span>)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>torch.use_deterministic_algorithms(<span class="va">True</span>)</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>forms <span class="op">=</span> [</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">""</span>.join(letters)</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> letters <span class="kw">in</span> itertools.product(<span class="st">"bglmprstvz"</span>, <span class="st">"aeiou"</span>, <span class="st">"dknrst"</span>, <span class="st">"aeiou"</span>)</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>form_order <span class="op">=</span> torch.randperm(</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>    <span class="bu">len</span>(forms), generator<span class="op">=</span>torch.Generator().manual_seed(SEED)</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>)[:<span class="dv">80</span>]</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>token_strings <span class="op">=</span> [forms[index] <span class="cf">for</span> index <span class="kw">in</span> form_order]</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>family_words <span class="op">=</span> [token_strings[:<span class="dv">40</span>], token_strings[<span class="dv">40</span>:]]</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>covered_words <span class="op">=</span> [words[:<span class="dv">20</span>] <span class="cf">for</span> words <span class="kw">in</span> family_words]</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>uncovered_words <span class="op">=</span> [words[<span class="dv">20</span>:<span class="dv">40</span>] <span class="cf">for</span> words <span class="kw">in</span> family_words]</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>context_pairs <span class="op">=</span> [</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"rain"</span>, <span class="st">"power"</span>),</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"soil"</span>, <span class="st">"metal"</span>),</span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"roots"</span>, <span class="st">"gears"</span>),</span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"water"</span>, <span class="st">"fuel"</span>),</span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"garden"</span>, <span class="st">"workshop"</span>),</span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"grows"</span>, <span class="st">"moves"</span>),</span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"blooms"</span>, <span class="st">"turns"</span>),</span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"sunlight"</span>, <span class="st">"current"</span>),</span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb6-37"><a href="#cb6-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-38"><a href="#cb6-38" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> source_sentences(word: <span class="bu">str</span>, family: <span class="bu">int</span>) <span class="op">-&gt;</span> <span class="bu">list</span>[<span class="bu">list</span>[<span class="bu">str</span>]]:</span>
<span id="cb6-39"><a href="#cb6-39" aria-hidden="true" tabindex="-1"></a>    cue <span class="op">=</span> [pair[family] <span class="cf">for</span> pair <span class="kw">in</span> context_pairs]</span>
<span id="cb6-40"><a href="#cb6-40" aria-hidden="true" tabindex="-1"></a>    other <span class="op">=</span> [pair[<span class="dv">1</span> <span class="op">-</span> family] <span class="cf">for</span> pair <span class="kw">in</span> context_pairs]</span>
<span id="cb6-41"><a href="#cb6-41" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> [</span>
<span id="cb6-42"><a href="#cb6-42" aria-hidden="true" tabindex="-1"></a>        [<span class="st">"after"</span>, cue[<span class="dv">0</span>], <span class="st">"the"</span>, word, cue[<span class="dv">5</span>]],</span>
<span id="cb6-43"><a href="#cb6-43" aria-hidden="true" tabindex="-1"></a>        [<span class="st">"the"</span>, word, <span class="st">"needs"</span>, cue[<span class="dv">3</span>], <span class="st">"near"</span>, cue[<span class="dv">1</span>]],</span>
<span id="cb6-44"><a href="#cb6-44" aria-hidden="true" tabindex="-1"></a>        [cue[<span class="dv">2</span>], <span class="st">"support"</span>, <span class="st">"the"</span>, word],</span>
<span id="cb6-45"><a href="#cb6-45" aria-hidden="true" tabindex="-1"></a>        [<span class="st">"in"</span>, <span class="st">"the"</span>, cue[<span class="dv">4</span>], <span class="st">"the"</span>, word, cue[<span class="dv">6</span>]],</span>
<span id="cb6-46"><a href="#cb6-46" aria-hidden="true" tabindex="-1"></a>        [<span class="st">"we"</span>, <span class="st">"found"</span>, <span class="st">"the"</span>, word, <span class="st">"beside"</span>, cue[<span class="dv">1</span>]],</span>
<span id="cb6-47"><a href="#cb6-47" aria-hidden="true" tabindex="-1"></a>        [cue[<span class="dv">0</span>], <span class="st">"and"</span>, cue[<span class="dv">7</span>], <span class="st">"help"</span>, <span class="st">"the"</span>, word],</span>
<span id="cb6-48"><a href="#cb6-48" aria-hidden="true" tabindex="-1"></a>        [<span class="st">"the"</span>, word, <span class="st">"rests"</span>, <span class="st">"near"</span>, other[<span class="dv">4</span>]],</span>
<span id="cb6-49"><a href="#cb6-49" aria-hidden="true" tabindex="-1"></a>        [<span class="st">"today"</span>, <span class="st">"the"</span>, word, <span class="st">"follows"</span>, other[<span class="dv">2</span>]],</span>
<span id="cb6-50"><a href="#cb6-50" aria-hidden="true" tabindex="-1"></a>    ]</span>
<span id="cb6-51"><a href="#cb6-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-52"><a href="#cb6-52" aria-hidden="true" tabindex="-1"></a>sentences: <span class="bu">list</span>[<span class="bu">list</span>[<span class="bu">str</span>]] <span class="op">=</span> []</span>
<span id="cb6-53"><a href="#cb6-53" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> family, words <span class="kw">in</span> <span class="bu">enumerate</span>(covered_words):</span>
<span id="cb6-54"><a href="#cb6-54" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> word <span class="kw">in</span> words:</span>
<span id="cb6-55"><a href="#cb6-55" aria-hidden="true" tabindex="-1"></a>        sentences.extend(source_sentences(word, family))</span>
<span id="cb6-56"><a href="#cb6-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-57"><a href="#cb6-57" aria-hidden="true" tabindex="-1"></a>specials <span class="op">=</span> [<span class="st">"[PAD]"</span>, <span class="st">"[UNK]"</span>, <span class="st">"[CLS]"</span>, <span class="st">"[SEP]"</span>, <span class="st">"[MASK]"</span>]</span>
<span id="cb6-58"><a href="#cb6-58" aria-hidden="true" tabindex="-1"></a>ordinary <span class="op">=</span> <span class="bu">sorted</span>(</span>
<span id="cb6-59"><a href="#cb6-59" aria-hidden="true" tabindex="-1"></a>    {token <span class="cf">for</span> sentence <span class="kw">in</span> sentences <span class="cf">for</span> token <span class="kw">in</span> sentence} <span class="op">|</span> <span class="bu">set</span>(token_strings)</span>
<span id="cb6-60"><a href="#cb6-60" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-61"><a href="#cb6-61" aria-hidden="true" tabindex="-1"></a>vocabulary <span class="op">=</span> specials <span class="op">+</span> [token <span class="cf">for</span> token <span class="kw">in</span> ordinary <span class="cf">if</span> token <span class="kw">not</span> <span class="kw">in</span> specials]</span>
<span id="cb6-62"><a href="#cb6-62" aria-hidden="true" tabindex="-1"></a>stoi <span class="op">=</span> {token: index <span class="cf">for</span> index, token <span class="kw">in</span> <span class="bu">enumerate</span>(vocabulary)}</span>
<span id="cb6-63"><a href="#cb6-63" aria-hidden="true" tabindex="-1"></a>PAD, UNK, CLS, SEP, MASK <span class="op">=</span> [stoi[token] <span class="cf">for</span> token <span class="kw">in</span> specials]</span>
<span id="cb6-64"><a href="#cb6-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-65"><a href="#cb6-65" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> encode(sentence: <span class="bu">list</span>[<span class="bu">str</span>]) <span class="op">-&gt;</span> torch.Tensor:</span>
<span id="cb6-66"><a href="#cb6-66" aria-hidden="true" tabindex="-1"></a>    ids <span class="op">=</span> [CLS] <span class="op">+</span> [stoi.get(token, UNK) <span class="cf">for</span> token <span class="kw">in</span> sentence] <span class="op">+</span> [SEP]</span>
<span id="cb6-67"><a href="#cb6-67" aria-hidden="true" tabindex="-1"></a>    ids <span class="op">+=</span> [PAD] <span class="op">*</span> (MAX_LEN <span class="op">-</span> <span class="bu">len</span>(ids))</span>
<span id="cb6-68"><a href="#cb6-68" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> torch.tensor(ids[:MAX_LEN])</span>
<span id="cb6-69"><a href="#cb6-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-70"><a href="#cb6-70" aria-hidden="true" tabindex="-1"></a>source_ids <span class="op">=</span> torch.stack([encode(sentence) <span class="cf">for</span> sentence <span class="kw">in</span> sentences])</span>
<span id="cb6-71"><a href="#cb6-71" aria-hidden="true" tabindex="-1"></a>uncovered_ids <span class="op">=</span> torch.tensor([</span>
<span id="cb6-72"><a href="#cb6-72" aria-hidden="true" tabindex="-1"></a>    stoi[word] <span class="cf">for</span> family <span class="kw">in</span> uncovered_words <span class="cf">for</span> word <span class="kw">in</span> family</span>
<span id="cb6-73"><a href="#cb6-73" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb6-74"><a href="#cb6-74" aria-hidden="true" tabindex="-1"></a>source_token_ids <span class="op">=</span> torch.unique(source_ids)</span>
<span id="cb6-75"><a href="#cb6-75" aria-hidden="true" tabindex="-1"></a>random_pool <span class="op">=</span> source_token_ids[</span>
<span id="cb6-76"><a href="#cb6-76" aria-hidden="true" tabindex="-1"></a>    <span class="op">~</span>torch.isin(source_token_ids, torch.tensor([PAD, CLS, SEP]))</span>
<span id="cb6-77"><a href="#cb6-77" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb6-78"><a href="#cb6-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-79"><a href="#cb6-79" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> <span class="bu">len</span>(sentences) <span class="op">==</span> <span class="dv">320</span></span>
<span id="cb6-80"><a href="#cb6-80" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> <span class="bu">len</span>(vocabulary) <span class="op">==</span> <span class="dv">115</span></span>
<span id="cb6-81"><a href="#cb6-81" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> <span class="kw">not</span> torch.isin(source_ids, uncovered_ids).<span class="bu">any</span>()</span>
<span id="cb6-82"><a href="#cb6-82" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"source: </span><span class="sc">{</span><span class="bu">len</span>(sentences)<span class="sc">}</span><span class="ss"> sentences; vocabulary: </span><span class="sc">{</span><span class="bu">len</span>(vocabulary)<span class="sc">}</span><span class="ss"> tokens"</span>)</span>
<span id="cb6-83"><a href="#cb6-83" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"covered/uncovered token strings: 40 / </span><span class="sc">{</span><span class="bu">len</span>(uncovered_ids)<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>source: 320 sentences; vocabulary: 115 tokens
covered/uncovered token strings: 40 / 40</code></pre>
</div>
</div>
<p>This is an atomic word-level vocabulary, not WordPiece. That simplification is intentional—splitting the generated strings into subwords could let spelling leak family identity. The source generator—not natural language—defines the latent regularity, so the experiment can demonstrate a mechanism but cannot estimate real-world BERT performance.</p>
</section>
<section id="a-small-bert-style-encoder" class="level3">
<h3 class="anchored" data-anchor-id="a-small-bert-style-encoder">A small BERT-style encoder</h3>
<p>The encoder has two post-LayerNorm blocks, width 48, four heads, learned absolute positions, full nonpadding attention, and GELU feed-forward layers. Here <span class="math inline">\(\operatorname{GELU}(x)=x\Phi(x)\)</span>, with <span class="math inline">\(\Phi\)</span> the standard-normal cumulative distribution—a smooth, input-dependent gate used by original BERT. The lab omits segment embeddings, NSP, and dropout. Its 43,920 encoder parameters make the study fast enough to repeat end to end, while preserving the relevant path from bidirectional attention to MLM to fine-tuning.</p>
<div id="bert-lab-model" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code: define full attention, the encoder, and the MLM head</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> FullAttention(nn.Module):</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>) <span class="op">-&gt;</span> <span class="va">None</span>:</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.qkv <span class="op">=</span> nn.Linear(WIDTH, <span class="dv">3</span> <span class="op">*</span> WIDTH)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.output <span class="op">=</span> nn.Linear(WIDTH, WIDTH)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>, x: torch.Tensor, visible: torch.Tensor</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    ) <span class="op">-&gt;</span> torch.Tensor:</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>        batch, length, _ <span class="op">=</span> x.shape</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>        head_width <span class="op">=</span> WIDTH <span class="op">//</span> HEADS</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>        qkv <span class="op">=</span> <span class="va">self</span>.qkv(x).view(</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>            batch, length, <span class="dv">3</span>, HEADS, head_width</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>        q, k, v <span class="op">=</span> qkv.permute(<span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">4</span>)</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>        scores <span class="op">=</span> q <span class="op">@</span> k.transpose(<span class="op">-</span><span class="dv">2</span>, <span class="op">-</span><span class="dv">1</span>) <span class="op">/</span> head_width<span class="op">**</span><span class="fl">0.5</span></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>        scores <span class="op">=</span> scores.masked_fill(</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>            <span class="op">~</span>visible[:, <span class="va">None</span>, <span class="va">None</span>, :], <span class="bu">float</span>(<span class="st">"-inf"</span>)</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>        weights <span class="op">=</span> F.softmax(scores, dim<span class="op">=-</span><span class="dv">1</span>)</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>        mixed <span class="op">=</span> (weights <span class="op">@</span> v).transpose(<span class="dv">1</span>, <span class="dv">2</span>).reshape(</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>            batch, length, WIDTH</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">self</span>.output(mixed)</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> EncoderBlock(nn.Module):</span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>) <span class="op">-&gt;</span> <span class="va">None</span>:</span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.attention <span class="op">=</span> FullAttention()</span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.norm1 <span class="op">=</span> nn.LayerNorm(WIDTH)</span>
<span id="cb8-31"><a href="#cb8-31" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.ff <span class="op">=</span> nn.Sequential(</span>
<span id="cb8-32"><a href="#cb8-32" aria-hidden="true" tabindex="-1"></a>            nn.Linear(WIDTH, FF_WIDTH),</span>
<span id="cb8-33"><a href="#cb8-33" aria-hidden="true" tabindex="-1"></a>            nn.GELU(),</span>
<span id="cb8-34"><a href="#cb8-34" aria-hidden="true" tabindex="-1"></a>            nn.Linear(FF_WIDTH, WIDTH),</span>
<span id="cb8-35"><a href="#cb8-35" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb8-36"><a href="#cb8-36" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.norm2 <span class="op">=</span> nn.LayerNorm(WIDTH)</span>
<span id="cb8-37"><a href="#cb8-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-38"><a href="#cb8-38" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(</span>
<span id="cb8-39"><a href="#cb8-39" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>, x: torch.Tensor, visible: torch.Tensor</span>
<span id="cb8-40"><a href="#cb8-40" aria-hidden="true" tabindex="-1"></a>    ) <span class="op">-&gt;</span> torch.Tensor:</span>
<span id="cb8-41"><a href="#cb8-41" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> <span class="va">self</span>.norm1(x <span class="op">+</span> <span class="va">self</span>.attention(x, visible))</span>
<span id="cb8-42"><a href="#cb8-42" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">self</span>.norm2(x <span class="op">+</span> <span class="va">self</span>.ff(x))</span>
<span id="cb8-43"><a href="#cb8-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-44"><a href="#cb8-44" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> TinyBertEncoder(nn.Module):</span>
<span id="cb8-45"><a href="#cb8-45" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>) <span class="op">-&gt;</span> <span class="va">None</span>:</span>
<span id="cb8-46"><a href="#cb8-46" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb8-47"><a href="#cb8-47" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.token_embedding <span class="op">=</span> nn.Embedding(</span>
<span id="cb8-48"><a href="#cb8-48" aria-hidden="true" tabindex="-1"></a>            <span class="bu">len</span>(vocabulary), WIDTH, padding_idx<span class="op">=</span>PAD</span>
<span id="cb8-49"><a href="#cb8-49" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb8-50"><a href="#cb8-50" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.position_embedding <span class="op">=</span> nn.Embedding(MAX_LEN, WIDTH)</span>
<span id="cb8-51"><a href="#cb8-51" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.blocks <span class="op">=</span> nn.ModuleList([</span>
<span id="cb8-52"><a href="#cb8-52" aria-hidden="true" tabindex="-1"></a>            EncoderBlock() <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(BLOCKS)</span>
<span id="cb8-53"><a href="#cb8-53" aria-hidden="true" tabindex="-1"></a>        ])</span>
<span id="cb8-54"><a href="#cb8-54" aria-hidden="true" tabindex="-1"></a>        nn.init.normal_(<span class="va">self</span>.token_embedding.weight, std<span class="op">=</span><span class="fl">0.02</span>)</span>
<span id="cb8-55"><a href="#cb8-55" aria-hidden="true" tabindex="-1"></a>        nn.init.normal_(<span class="va">self</span>.position_embedding.weight, std<span class="op">=</span><span class="fl">0.02</span>)</span>
<span id="cb8-56"><a href="#cb8-56" aria-hidden="true" tabindex="-1"></a>        <span class="cf">with</span> torch.no_grad():</span>
<span id="cb8-57"><a href="#cb8-57" aria-hidden="true" tabindex="-1"></a>            <span class="va">self</span>.token_embedding.weight[PAD].zero_()</span>
<span id="cb8-58"><a href="#cb8-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-59"><a href="#cb8-59" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, ids: torch.Tensor) <span class="op">-&gt;</span> torch.Tensor:</span>
<span id="cb8-60"><a href="#cb8-60" aria-hidden="true" tabindex="-1"></a>        positions <span class="op">=</span> torch.arange(ids.shape[<span class="dv">1</span>], device<span class="op">=</span>ids.device)</span>
<span id="cb8-61"><a href="#cb8-61" aria-hidden="true" tabindex="-1"></a>        hidden <span class="op">=</span> (</span>
<span id="cb8-62"><a href="#cb8-62" aria-hidden="true" tabindex="-1"></a>            <span class="va">self</span>.token_embedding(ids)</span>
<span id="cb8-63"><a href="#cb8-63" aria-hidden="true" tabindex="-1"></a>            <span class="op">+</span> <span class="va">self</span>.position_embedding(positions)</span>
<span id="cb8-64"><a href="#cb8-64" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb8-65"><a href="#cb8-65" aria-hidden="true" tabindex="-1"></a>        visible <span class="op">=</span> ids <span class="op">!=</span> PAD</span>
<span id="cb8-66"><a href="#cb8-66" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> block <span class="kw">in</span> <span class="va">self</span>.blocks:</span>
<span id="cb8-67"><a href="#cb8-67" aria-hidden="true" tabindex="-1"></a>            hidden <span class="op">=</span> block(hidden, visible)</span>
<span id="cb8-68"><a href="#cb8-68" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> hidden</span>
<span id="cb8-69"><a href="#cb8-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-70"><a href="#cb8-70" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> MaskedLanguageModel(nn.Module):</span>
<span id="cb8-71"><a href="#cb8-71" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, encoder: TinyBertEncoder) <span class="op">-&gt;</span> <span class="va">None</span>:</span>
<span id="cb8-72"><a href="#cb8-72" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb8-73"><a href="#cb8-73" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.encoder <span class="op">=</span> encoder</span>
<span id="cb8-74"><a href="#cb8-74" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.dense <span class="op">=</span> nn.Linear(WIDTH, WIDTH)</span>
<span id="cb8-75"><a href="#cb8-75" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.norm <span class="op">=</span> nn.LayerNorm(WIDTH)</span>
<span id="cb8-76"><a href="#cb8-76" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.decoder <span class="op">=</span> nn.Linear(WIDTH, <span class="bu">len</span>(vocabulary))</span>
<span id="cb8-77"><a href="#cb8-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-78"><a href="#cb8-78" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(</span>
<span id="cb8-79"><a href="#cb8-79" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>, ids: torch.Tensor, selected: torch.Tensor</span>
<span id="cb8-80"><a href="#cb8-80" aria-hidden="true" tabindex="-1"></a>    ) <span class="op">-&gt;</span> torch.Tensor:</span>
<span id="cb8-81"><a href="#cb8-81" aria-hidden="true" tabindex="-1"></a>        hidden <span class="op">=</span> <span class="va">self</span>.encoder(ids)[selected]</span>
<span id="cb8-82"><a href="#cb8-82" aria-hidden="true" tabindex="-1"></a>        hidden <span class="op">=</span> <span class="va">self</span>.norm(F.gelu(<span class="va">self</span>.dense(hidden)))</span>
<span id="cb8-83"><a href="#cb8-83" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">self</span>.decoder(hidden)</span>
<span id="cb8-84"><a href="#cb8-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-85"><a href="#cb8-85" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> corrupt(</span>
<span id="cb8-86"><a href="#cb8-86" aria-hidden="true" tabindex="-1"></a>    ids: torch.Tensor,</span>
<span id="cb8-87"><a href="#cb8-87" aria-hidden="true" tabindex="-1"></a>    generator: torch.Generator,</span>
<span id="cb8-88"><a href="#cb8-88" aria-hidden="true" tabindex="-1"></a>) <span class="op">-&gt;</span> <span class="bu">tuple</span>[torch.Tensor, torch.Tensor, torch.Tensor]:</span>
<span id="cb8-89"><a href="#cb8-89" aria-hidden="true" tabindex="-1"></a>    eligible <span class="op">=</span> (ids <span class="op">!=</span> PAD) <span class="op">&amp;</span> (ids <span class="op">!=</span> CLS) <span class="op">&amp;</span> (ids <span class="op">!=</span> SEP)</span>
<span id="cb8-90"><a href="#cb8-90" aria-hidden="true" tabindex="-1"></a>    selected <span class="op">=</span> eligible <span class="op">&amp;</span> (</span>
<span id="cb8-91"><a href="#cb8-91" aria-hidden="true" tabindex="-1"></a>        torch.rand(ids.shape, generator<span class="op">=</span>generator) <span class="op">&lt;</span> <span class="fl">0.15</span></span>
<span id="cb8-92"><a href="#cb8-92" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb8-93"><a href="#cb8-93" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="kw">not</span> selected.<span class="bu">any</span>():</span>
<span id="cb8-94"><a href="#cb8-94" aria-hidden="true" tabindex="-1"></a>        rows, columns <span class="op">=</span> torch.where(eligible)</span>
<span id="cb8-95"><a href="#cb8-95" aria-hidden="true" tabindex="-1"></a>        choice <span class="op">=</span> torch.randint(</span>
<span id="cb8-96"><a href="#cb8-96" aria-hidden="true" tabindex="-1"></a>            <span class="bu">len</span>(rows), (<span class="dv">1</span>,), generator<span class="op">=</span>generator</span>
<span id="cb8-97"><a href="#cb8-97" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb8-98"><a href="#cb8-98" aria-hidden="true" tabindex="-1"></a>        selected[rows[choice], columns[choice]] <span class="op">=</span> <span class="va">True</span></span>
<span id="cb8-99"><a href="#cb8-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-100"><a href="#cb8-100" aria-hidden="true" tabindex="-1"></a>    draw <span class="op">=</span> torch.rand(ids.shape, generator<span class="op">=</span>generator)</span>
<span id="cb8-101"><a href="#cb8-101" aria-hidden="true" tabindex="-1"></a>    mask_sites <span class="op">=</span> selected <span class="op">&amp;</span> (draw <span class="op">&lt;</span> <span class="fl">0.8</span>)</span>
<span id="cb8-102"><a href="#cb8-102" aria-hidden="true" tabindex="-1"></a>    random_sites <span class="op">=</span> selected <span class="op">&amp;</span> (draw <span class="op">&gt;=</span> <span class="fl">0.8</span>) <span class="op">&amp;</span> (draw <span class="op">&lt;</span> <span class="fl">0.9</span>)</span>
<span id="cb8-103"><a href="#cb8-103" aria-hidden="true" tabindex="-1"></a>    corrupted <span class="op">=</span> ids.clone()</span>
<span id="cb8-104"><a href="#cb8-104" aria-hidden="true" tabindex="-1"></a>    corrupted[mask_sites] <span class="op">=</span> MASK</span>
<span id="cb8-105"><a href="#cb8-105" aria-hidden="true" tabindex="-1"></a>    random_choices <span class="op">=</span> torch.randint(</span>
<span id="cb8-106"><a href="#cb8-106" aria-hidden="true" tabindex="-1"></a>        <span class="bu">len</span>(random_pool), ids.shape, generator<span class="op">=</span>generator</span>
<span id="cb8-107"><a href="#cb8-107" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb8-108"><a href="#cb8-108" aria-hidden="true" tabindex="-1"></a>    random_ids <span class="op">=</span> random_pool[random_choices]</span>
<span id="cb8-109"><a href="#cb8-109" aria-hidden="true" tabindex="-1"></a>    corrupted[random_sites] <span class="op">=</span> random_ids[random_sites]</span>
<span id="cb8-110"><a href="#cb8-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-111"><a href="#cb8-111" aria-hidden="true" tabindex="-1"></a>    unchanged_sites <span class="op">=</span> selected <span class="op">&amp;</span> <span class="op">~</span>mask_sites <span class="op">&amp;</span> <span class="op">~</span>random_sites</span>
<span id="cb8-112"><a href="#cb8-112" aria-hidden="true" tabindex="-1"></a>    counts <span class="op">=</span> torch.tensor([</span>
<span id="cb8-113"><a href="#cb8-113" aria-hidden="true" tabindex="-1"></a>        mask_sites.<span class="bu">sum</span>().item(),</span>
<span id="cb8-114"><a href="#cb8-114" aria-hidden="true" tabindex="-1"></a>        random_sites.<span class="bu">sum</span>().item(),</span>
<span id="cb8-115"><a href="#cb8-115" aria-hidden="true" tabindex="-1"></a>        unchanged_sites.<span class="bu">sum</span>().item(),</span>
<span id="cb8-116"><a href="#cb8-116" aria-hidden="true" tabindex="-1"></a>    ])</span>
<span id="cb8-117"><a href="#cb8-117" aria-hidden="true" tabindex="-1"></a>    <span class="cf">assert</span> <span class="kw">not</span> (selected <span class="op">&amp;</span> <span class="op">~</span>eligible).<span class="bu">any</span>()</span>
<span id="cb8-118"><a href="#cb8-118" aria-hidden="true" tabindex="-1"></a>    <span class="cf">assert</span> <span class="kw">not</span> torch.isin(corrupted, uncovered_ids).<span class="bu">any</span>()</span>
<span id="cb8-119"><a href="#cb8-119" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> corrupted, selected, counts</span>
<span id="cb8-120"><a href="#cb8-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-121"><a href="#cb8-121" aria-hidden="true" tabindex="-1"></a>encoder_parameters <span class="op">=</span> <span class="bu">sum</span>(</span>
<span id="cb8-122"><a href="#cb8-122" aria-hidden="true" tabindex="-1"></a>    parameter.numel() <span class="cf">for</span> parameter <span class="kw">in</span> TinyBertEncoder().parameters()</span>
<span id="cb8-123"><a href="#cb8-123" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-124"><a href="#cb8-124" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"encoder parameters: </span><span class="sc">{</span>encoder_parameters<span class="sc">:,}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>encoder parameters: 43,920</code></pre>
</div>
</div>
<p>The MLM decoder is deliberately <em>untied</em> from the input embedding table. The original released BERT code explicitly tied those weights, but tying would update an uncovered input row through the vocabulary softmax even when that token never appeared. The custom control is stricter—random replacements are drawn only from source tokens, and the code later asserts that every uncovered input embedding remains bitwise unchanged through pretraining. Untied decoder rows for the controls still participate as negative softmax classes, but they are discarded downstream and never expose a control token’s context or identity to the encoder input.</p>
</section>
<section id="pretrain-then-adapt" class="level3">
<h3 class="anchored" data-anchor-id="pretrain-then-adapt">Pretrain, then adapt</h3>
<p>For each seed from 6050 through 6054, one encoder is saved before training and the same encoder receives 600 MLM updates. The two downstream arms then receive the same labeled word types, identical classifier-head tensors, 160 full-batch updates, and the same learning rates. All encoder weights move in both arms. Each seed therefore repeats initialization, corruption, MLM, label selection, and fine-tuning—not merely the last classifier fit.</p>
<div id="bert-lab-training" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Code: pretrain five paired encoders and fine-tune all weights</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>TensorState <span class="op">=</span> <span class="bu">dict</span>[<span class="bu">str</span>, torch.Tensor]</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> pretrain(</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    seed: <span class="bu">int</span>,</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>) <span class="op">-&gt;</span> <span class="bu">tuple</span>[TensorState, TensorState, torch.Tensor, <span class="bu">int</span>]:</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    torch.manual_seed(seed)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    encoder <span class="op">=</span> TinyBertEncoder()</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    initial <span class="op">=</span> copy.deepcopy(encoder.state_dict())</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    mlm <span class="op">=</span> MaskedLanguageModel(encoder)</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    optimizer <span class="op">=</span> torch.optim.Adam(mlm.parameters(), lr<span class="op">=</span><span class="fl">1e-3</span>)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>    index_generator <span class="op">=</span> torch.Generator().manual_seed(seed <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>    mask_generator <span class="op">=</span> torch.Generator().manual_seed(seed <span class="op">+</span> <span class="dv">2</span>)</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>    schedule <span class="op">=</span> torch.randint(</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>        <span class="bu">len</span>(source_ids),</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>        (PRETRAIN_STEPS, BATCH_SIZE),</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>        generator<span class="op">=</span>index_generator,</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>    branch_counts <span class="op">=</span> torch.zeros(<span class="dv">3</span>, dtype<span class="op">=</span>torch.<span class="bu">long</span>)</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>    eligible_count <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> indices <span class="kw">in</span> schedule:</span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>        original <span class="op">=</span> source_ids[indices]</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>        eligible_count <span class="op">+=</span> (</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>            (original <span class="op">!=</span> PAD) <span class="op">&amp;</span> (original <span class="op">!=</span> CLS) <span class="op">&amp;</span> (original <span class="op">!=</span> SEP)</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>        ).<span class="bu">sum</span>().item()</span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>        corrupted, selected, counts <span class="op">=</span> corrupt(</span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>            original, mask_generator</span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a>        branch_counts <span class="op">+=</span> counts</span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a>        logits <span class="op">=</span> mlm(corrupted, selected)</span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a>        targets <span class="op">=</span> original[selected]</span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a>        <span class="cf">assert</span> logits.shape <span class="op">==</span> (targets.numel(), <span class="bu">len</span>(vocabulary))</span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a>        loss <span class="op">=</span> F.cross_entropy(logits, targets)</span>
<span id="cb10-34"><a href="#cb10-34" aria-hidden="true" tabindex="-1"></a>        optimizer.zero_grad()</span>
<span id="cb10-35"><a href="#cb10-35" aria-hidden="true" tabindex="-1"></a>        loss.backward()</span>
<span id="cb10-36"><a href="#cb10-36" aria-hidden="true" tabindex="-1"></a>        nn.utils.clip_grad_norm_(mlm.parameters(), <span class="fl">1.0</span>)</span>
<span id="cb10-37"><a href="#cb10-37" aria-hidden="true" tabindex="-1"></a>        optimizer.step()</span>
<span id="cb10-38"><a href="#cb10-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-39"><a href="#cb10-39" aria-hidden="true" tabindex="-1"></a>    pretrained <span class="op">=</span> copy.deepcopy(mlm.encoder.state_dict())</span>
<span id="cb10-40"><a href="#cb10-40" aria-hidden="true" tabindex="-1"></a>    initial_control <span class="op">=</span> initial[<span class="st">"token_embedding.weight"</span>][uncovered_ids]</span>
<span id="cb10-41"><a href="#cb10-41" aria-hidden="true" tabindex="-1"></a>    final_control <span class="op">=</span> pretrained[<span class="st">"token_embedding.weight"</span>][uncovered_ids]</span>
<span id="cb10-42"><a href="#cb10-42" aria-hidden="true" tabindex="-1"></a>    <span class="cf">assert</span> torch.equal(initial_control, final_control)</span>
<span id="cb10-43"><a href="#cb10-43" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> initial, pretrained, branch_counts, eligible_count</span>
<span id="cb10-44"><a href="#cb10-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-45"><a href="#cb10-45" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> neutral_sentence(word: <span class="bu">str</span>) <span class="op">-&gt;</span> torch.Tensor:</span>
<span id="cb10-46"><a href="#cb10-46" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> encode([<span class="st">"we"</span>, <span class="st">"found"</span>, <span class="st">"the"</span>, word, <span class="st">"today"</span>])</span>
<span id="cb10-47"><a href="#cb10-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-48"><a href="#cb10-48" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> WordClassifier(nn.Module):</span>
<span id="cb10-49"><a href="#cb10-49" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(</span>
<span id="cb10-50"><a href="#cb10-50" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>, encoder_state: TensorState, head_state: TensorState</span>
<span id="cb10-51"><a href="#cb10-51" aria-hidden="true" tabindex="-1"></a>    ) <span class="op">-&gt;</span> <span class="va">None</span>:</span>
<span id="cb10-52"><a href="#cb10-52" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb10-53"><a href="#cb10-53" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.encoder <span class="op">=</span> TinyBertEncoder()</span>
<span id="cb10-54"><a href="#cb10-54" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.encoder.load_state_dict(encoder_state)</span>
<span id="cb10-55"><a href="#cb10-55" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.head <span class="op">=</span> nn.Linear(WIDTH, <span class="dv">2</span>)</span>
<span id="cb10-56"><a href="#cb10-56" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.head.load_state_dict(head_state)</span>
<span id="cb10-57"><a href="#cb10-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-58"><a href="#cb10-58" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, ids: torch.Tensor) <span class="op">-&gt;</span> torch.Tensor:</span>
<span id="cb10-59"><a href="#cb10-59" aria-hidden="true" tabindex="-1"></a>        <span class="co"># [CLS] we found the WORD today [SEP] -&gt; WORD is position 4.</span></span>
<span id="cb10-60"><a href="#cb10-60" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">self</span>.head(<span class="va">self</span>.encoder(ids)[:, <span class="dv">4</span>])</span>
<span id="cb10-61"><a href="#cb10-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-62"><a href="#cb10-62" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> fit_classifier(</span>
<span id="cb10-63"><a href="#cb10-63" aria-hidden="true" tabindex="-1"></a>    encoder_state: TensorState,</span>
<span id="cb10-64"><a href="#cb10-64" aria-hidden="true" tabindex="-1"></a>    head_state: TensorState,</span>
<span id="cb10-65"><a href="#cb10-65" aria-hidden="true" tabindex="-1"></a>    family_zero: <span class="bu">list</span>[<span class="bu">str</span>],</span>
<span id="cb10-66"><a href="#cb10-66" aria-hidden="true" tabindex="-1"></a>    family_one: <span class="bu">list</span>[<span class="bu">str</span>],</span>
<span id="cb10-67"><a href="#cb10-67" aria-hidden="true" tabindex="-1"></a>) <span class="op">-&gt;</span> <span class="bu">tuple</span>[WordClassifier, <span class="bu">float</span>]:</span>
<span id="cb10-68"><a href="#cb10-68" aria-hidden="true" tabindex="-1"></a>    inputs <span class="op">=</span> torch.stack([</span>
<span id="cb10-69"><a href="#cb10-69" aria-hidden="true" tabindex="-1"></a>        neutral_sentence(word)</span>
<span id="cb10-70"><a href="#cb10-70" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> word <span class="kw">in</span> family_zero <span class="op">+</span> family_one</span>
<span id="cb10-71"><a href="#cb10-71" aria-hidden="true" tabindex="-1"></a>    ])</span>
<span id="cb10-72"><a href="#cb10-72" aria-hidden="true" tabindex="-1"></a>    targets <span class="op">=</span> torch.tensor(</span>
<span id="cb10-73"><a href="#cb10-73" aria-hidden="true" tabindex="-1"></a>        [<span class="dv">0</span>] <span class="op">*</span> <span class="bu">len</span>(family_zero) <span class="op">+</span> [<span class="dv">1</span>] <span class="op">*</span> <span class="bu">len</span>(family_one)</span>
<span id="cb10-74"><a href="#cb10-74" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb10-75"><a href="#cb10-75" aria-hidden="true" tabindex="-1"></a>    model <span class="op">=</span> WordClassifier(encoder_state, head_state)</span>
<span id="cb10-76"><a href="#cb10-76" aria-hidden="true" tabindex="-1"></a>    optimizer <span class="op">=</span> torch.optim.Adam([</span>
<span id="cb10-77"><a href="#cb10-77" aria-hidden="true" tabindex="-1"></a>        {<span class="st">"params"</span>: model.encoder.parameters(), <span class="st">"lr"</span>: <span class="fl">2e-4</span>},</span>
<span id="cb10-78"><a href="#cb10-78" aria-hidden="true" tabindex="-1"></a>        {<span class="st">"params"</span>: model.head.parameters(), <span class="st">"lr"</span>: <span class="fl">2e-3</span>},</span>
<span id="cb10-79"><a href="#cb10-79" aria-hidden="true" tabindex="-1"></a>    ])</span>
<span id="cb10-80"><a href="#cb10-80" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">160</span>):</span>
<span id="cb10-81"><a href="#cb10-81" aria-hidden="true" tabindex="-1"></a>        loss <span class="op">=</span> F.cross_entropy(model(inputs), targets)</span>
<span id="cb10-82"><a href="#cb10-82" aria-hidden="true" tabindex="-1"></a>        optimizer.zero_grad()</span>
<span id="cb10-83"><a href="#cb10-83" aria-hidden="true" tabindex="-1"></a>        loss.backward()</span>
<span id="cb10-84"><a href="#cb10-84" aria-hidden="true" tabindex="-1"></a>        optimizer.step()</span>
<span id="cb10-85"><a href="#cb10-85" aria-hidden="true" tabindex="-1"></a>    train_accuracy <span class="op">=</span> (</span>
<span id="cb10-86"><a href="#cb10-86" aria-hidden="true" tabindex="-1"></a>        (model(inputs).argmax(<span class="dv">1</span>) <span class="op">==</span> targets).<span class="bu">float</span>().mean().item()</span>
<span id="cb10-87"><a href="#cb10-87" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb10-88"><a href="#cb10-88" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> model, train_accuracy</span>
<span id="cb10-89"><a href="#cb10-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-90"><a href="#cb10-90" aria-hidden="true" tabindex="-1"></a><span class="at">@torch.no_grad</span>()</span>
<span id="cb10-91"><a href="#cb10-91" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> classifier_accuracy(</span>
<span id="cb10-92"><a href="#cb10-92" aria-hidden="true" tabindex="-1"></a>    model: WordClassifier,</span>
<span id="cb10-93"><a href="#cb10-93" aria-hidden="true" tabindex="-1"></a>    family_zero: <span class="bu">list</span>[<span class="bu">str</span>],</span>
<span id="cb10-94"><a href="#cb10-94" aria-hidden="true" tabindex="-1"></a>    family_one: <span class="bu">list</span>[<span class="bu">str</span>],</span>
<span id="cb10-95"><a href="#cb10-95" aria-hidden="true" tabindex="-1"></a>) <span class="op">-&gt;</span> <span class="bu">float</span>:</span>
<span id="cb10-96"><a href="#cb10-96" aria-hidden="true" tabindex="-1"></a>    inputs <span class="op">=</span> torch.stack([</span>
<span id="cb10-97"><a href="#cb10-97" aria-hidden="true" tabindex="-1"></a>        neutral_sentence(word)</span>
<span id="cb10-98"><a href="#cb10-98" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> word <span class="kw">in</span> family_zero <span class="op">+</span> family_one</span>
<span id="cb10-99"><a href="#cb10-99" aria-hidden="true" tabindex="-1"></a>    ])</span>
<span id="cb10-100"><a href="#cb10-100" aria-hidden="true" tabindex="-1"></a>    targets <span class="op">=</span> torch.tensor(</span>
<span id="cb10-101"><a href="#cb10-101" aria-hidden="true" tabindex="-1"></a>        [<span class="dv">0</span>] <span class="op">*</span> <span class="bu">len</span>(family_zero) <span class="op">+</span> [<span class="dv">1</span>] <span class="op">*</span> <span class="bu">len</span>(family_one)</span>
<span id="cb10-102"><a href="#cb10-102" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb10-103"><a href="#cb10-103" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (</span>
<span id="cb10-104"><a href="#cb10-104" aria-hidden="true" tabindex="-1"></a>        (model(inputs).argmax(<span class="dv">1</span>) <span class="op">==</span> targets).<span class="bu">float</span>().mean().item()</span>
<span id="cb10-105"><a href="#cb10-105" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb10-106"><a href="#cb10-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-107"><a href="#cb10-107" aria-hidden="true" tabindex="-1"></a>paired_results: <span class="bu">dict</span>[<span class="bu">int</span>, <span class="bu">list</span>[<span class="bu">tuple</span>[<span class="bu">float</span>, <span class="bu">float</span>]]] <span class="op">=</span> {</span>
<span id="cb10-108"><a href="#cb10-108" aria-hidden="true" tabindex="-1"></a>    count: [] <span class="cf">for</span> count <span class="kw">in</span> LABEL_COUNTS</span>
<span id="cb10-109"><a href="#cb10-109" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb10-110"><a href="#cb10-110" aria-hidden="true" tabindex="-1"></a>uncovered_results: <span class="bu">dict</span>[<span class="bu">int</span>, <span class="bu">list</span>[<span class="bu">tuple</span>[<span class="bu">float</span>, <span class="bu">float</span>]]] <span class="op">=</span> {</span>
<span id="cb10-111"><a href="#cb10-111" aria-hidden="true" tabindex="-1"></a>    count: [] <span class="cf">for</span> count <span class="kw">in</span> LABEL_COUNTS</span>
<span id="cb10-112"><a href="#cb10-112" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb10-113"><a href="#cb10-113" aria-hidden="true" tabindex="-1"></a>training_results: <span class="bu">dict</span>[<span class="bu">int</span>, <span class="bu">list</span>[<span class="bu">tuple</span>[<span class="bu">float</span>, <span class="bu">float</span>]]] <span class="op">=</span> {</span>
<span id="cb10-114"><a href="#cb10-114" aria-hidden="true" tabindex="-1"></a>    count: [] <span class="cf">for</span> count <span class="kw">in</span> LABEL_COUNTS</span>
<span id="cb10-115"><a href="#cb10-115" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb10-116"><a href="#cb10-116" aria-hidden="true" tabindex="-1"></a>all_branches <span class="op">=</span> torch.zeros(<span class="dv">3</span>, dtype<span class="op">=</span>torch.<span class="bu">long</span>)</span>
<span id="cb10-117"><a href="#cb10-117" aria-hidden="true" tabindex="-1"></a>all_eligible <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb10-118"><a href="#cb10-118" aria-hidden="true" tabindex="-1"></a>first_states: <span class="bu">tuple</span>[TensorState, TensorState] <span class="op">|</span> <span class="va">None</span> <span class="op">=</span> <span class="va">None</span></span>
<span id="cb10-119"><a href="#cb10-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-120"><a href="#cb10-120" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> replicate_seed <span class="kw">in</span> REPLICATE_SEEDS:</span>
<span id="cb10-121"><a href="#cb10-121" aria-hidden="true" tabindex="-1"></a>    initial_state, pretrained_state, counts, eligible_count <span class="op">=</span> pretrain(</span>
<span id="cb10-122"><a href="#cb10-122" aria-hidden="true" tabindex="-1"></a>        replicate_seed</span>
<span id="cb10-123"><a href="#cb10-123" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb10-124"><a href="#cb10-124" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> first_states <span class="kw">is</span> <span class="va">None</span>:</span>
<span id="cb10-125"><a href="#cb10-125" aria-hidden="true" tabindex="-1"></a>        first_states <span class="op">=</span> (initial_state, pretrained_state)</span>
<span id="cb10-126"><a href="#cb10-126" aria-hidden="true" tabindex="-1"></a>    all_branches <span class="op">+=</span> counts</span>
<span id="cb10-127"><a href="#cb10-127" aria-hidden="true" tabindex="-1"></a>    all_eligible <span class="op">+=</span> eligible_count</span>
<span id="cb10-128"><a href="#cb10-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-129"><a href="#cb10-129" aria-hidden="true" tabindex="-1"></a>    label_generator <span class="op">=</span> torch.Generator().manual_seed(replicate_seed)</span>
<span id="cb10-130"><a href="#cb10-130" aria-hidden="true" tabindex="-1"></a>    order_zero <span class="op">=</span> torch.randperm(</span>
<span id="cb10-131"><a href="#cb10-131" aria-hidden="true" tabindex="-1"></a>        <span class="bu">len</span>(covered_words[<span class="dv">0</span>]), generator<span class="op">=</span>label_generator</span>
<span id="cb10-132"><a href="#cb10-132" aria-hidden="true" tabindex="-1"></a>    ).tolist()</span>
<span id="cb10-133"><a href="#cb10-133" aria-hidden="true" tabindex="-1"></a>    order_one <span class="op">=</span> torch.randperm(</span>
<span id="cb10-134"><a href="#cb10-134" aria-hidden="true" tabindex="-1"></a>        <span class="bu">len</span>(covered_words[<span class="dv">1</span>]), generator<span class="op">=</span>label_generator</span>
<span id="cb10-135"><a href="#cb10-135" aria-hidden="true" tabindex="-1"></a>    ).tolist()</span>
<span id="cb10-136"><a href="#cb10-136" aria-hidden="true" tabindex="-1"></a>    torch.manual_seed(replicate_seed <span class="op">+</span> <span class="dv">10_000</span>)</span>
<span id="cb10-137"><a href="#cb10-137" aria-hidden="true" tabindex="-1"></a>    head_state <span class="op">=</span> copy.deepcopy(nn.Linear(WIDTH, <span class="dv">2</span>).state_dict())</span>
<span id="cb10-138"><a href="#cb10-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-139"><a href="#cb10-139" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> count <span class="kw">in</span> LABEL_COUNTS:</span>
<span id="cb10-140"><a href="#cb10-140" aria-hidden="true" tabindex="-1"></a>        label_zero <span class="op">=</span> [covered_words[<span class="dv">0</span>][i] <span class="cf">for</span> i <span class="kw">in</span> order_zero[:count]]</span>
<span id="cb10-141"><a href="#cb10-141" aria-hidden="true" tabindex="-1"></a>        label_one <span class="op">=</span> [covered_words[<span class="dv">1</span>][i] <span class="cf">for</span> i <span class="kw">in</span> order_one[:count]]</span>
<span id="cb10-142"><a href="#cb10-142" aria-hidden="true" tabindex="-1"></a>        test_zero <span class="op">=</span> [covered_words[<span class="dv">0</span>][i] <span class="cf">for</span> i <span class="kw">in</span> order_zero[count:]]</span>
<span id="cb10-143"><a href="#cb10-143" aria-hidden="true" tabindex="-1"></a>        test_one <span class="op">=</span> [covered_words[<span class="dv">1</span>][i] <span class="cf">for</span> i <span class="kw">in</span> order_one[count:]]</span>
<span id="cb10-144"><a href="#cb10-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-145"><a href="#cb10-145" aria-hidden="true" tabindex="-1"></a>        scratch, scratch_train <span class="op">=</span> fit_classifier(</span>
<span id="cb10-146"><a href="#cb10-146" aria-hidden="true" tabindex="-1"></a>            initial_state, head_state, label_zero, label_one</span>
<span id="cb10-147"><a href="#cb10-147" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb10-148"><a href="#cb10-148" aria-hidden="true" tabindex="-1"></a>        pretrained, pretrained_train <span class="op">=</span> fit_classifier(</span>
<span id="cb10-149"><a href="#cb10-149" aria-hidden="true" tabindex="-1"></a>            pretrained_state, head_state, label_zero, label_one</span>
<span id="cb10-150"><a href="#cb10-150" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb10-151"><a href="#cb10-151" aria-hidden="true" tabindex="-1"></a>        scratch_score <span class="op">=</span> classifier_accuracy(</span>
<span id="cb10-152"><a href="#cb10-152" aria-hidden="true" tabindex="-1"></a>            scratch, test_zero, test_one</span>
<span id="cb10-153"><a href="#cb10-153" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb10-154"><a href="#cb10-154" aria-hidden="true" tabindex="-1"></a>        pretrained_score <span class="op">=</span> classifier_accuracy(</span>
<span id="cb10-155"><a href="#cb10-155" aria-hidden="true" tabindex="-1"></a>            pretrained, test_zero, test_one</span>
<span id="cb10-156"><a href="#cb10-156" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb10-157"><a href="#cb10-157" aria-hidden="true" tabindex="-1"></a>        scratch_uncovered <span class="op">=</span> classifier_accuracy(</span>
<span id="cb10-158"><a href="#cb10-158" aria-hidden="true" tabindex="-1"></a>            scratch, uncovered_words[<span class="dv">0</span>], uncovered_words[<span class="dv">1</span>]</span>
<span id="cb10-159"><a href="#cb10-159" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb10-160"><a href="#cb10-160" aria-hidden="true" tabindex="-1"></a>        pretrained_uncovered <span class="op">=</span> classifier_accuracy(</span>
<span id="cb10-161"><a href="#cb10-161" aria-hidden="true" tabindex="-1"></a>            pretrained, uncovered_words[<span class="dv">0</span>], uncovered_words[<span class="dv">1</span>]</span>
<span id="cb10-162"><a href="#cb10-162" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb10-163"><a href="#cb10-163" aria-hidden="true" tabindex="-1"></a>        paired_results[count].append(</span>
<span id="cb10-164"><a href="#cb10-164" aria-hidden="true" tabindex="-1"></a>            (scratch_score, pretrained_score)</span>
<span id="cb10-165"><a href="#cb10-165" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb10-166"><a href="#cb10-166" aria-hidden="true" tabindex="-1"></a>        uncovered_results[count].append(</span>
<span id="cb10-167"><a href="#cb10-167" aria-hidden="true" tabindex="-1"></a>            (scratch_uncovered, pretrained_uncovered)</span>
<span id="cb10-168"><a href="#cb10-168" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb10-169"><a href="#cb10-169" aria-hidden="true" tabindex="-1"></a>        training_results[count].append(</span>
<span id="cb10-170"><a href="#cb10-170" aria-hidden="true" tabindex="-1"></a>            (scratch_train, pretrained_train)</span>
<span id="cb10-171"><a href="#cb10-171" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb10-172"><a href="#cb10-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-173"><a href="#cb10-173" aria-hidden="true" tabindex="-1"></a>branch_shares <span class="op">=</span> all_branches <span class="op">/</span> all_branches.<span class="bu">sum</span>()</span>
<span id="cb10-174"><a href="#cb10-174" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(</span>
<span id="cb10-175"><a href="#cb10-175" aria-hidden="true" tabindex="-1"></a>    <span class="st">"selected targets across five runs: "</span></span>
<span id="cb10-176"><a href="#cb10-176" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"</span><span class="sc">{</span>all_branches<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">.</span>item()<span class="sc">:,}</span><span class="ss">"</span></span>
<span id="cb10-177"><a href="#cb10-177" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-178"><a href="#cb10-178" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"eligible positions: </span><span class="sc">{</span>all_eligible<span class="sc">:,}</span><span class="ss">"</span>)</span>
<span id="cb10-179"><a href="#cb10-179" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(</span>
<span id="cb10-180"><a href="#cb10-180" aria-hidden="true" tabindex="-1"></a>    <span class="st">"realized selection rate: "</span></span>
<span id="cb10-181"><a href="#cb10-181" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"</span><span class="sc">{</span>all_branches<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">.</span>item() <span class="op">/</span> all_eligible<span class="sc">:.3%}</span><span class="ss">"</span></span>
<span id="cb10-182"><a href="#cb10-182" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-183"><a href="#cb10-183" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"realized mask/random/unchanged shares:"</span>, branch_shares.tolist())</span>
<span id="cb10-184"><a href="#cb10-184" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> count <span class="kw">in</span> LABEL_COUNTS:</span>
<span id="cb10-185"><a href="#cb10-185" aria-hidden="true" tabindex="-1"></a>    pairs <span class="op">=</span> np.array(paired_results[count])</span>
<span id="cb10-186"><a href="#cb10-186" aria-hidden="true" tabindex="-1"></a>    control_pairs <span class="op">=</span> np.array(uncovered_results[count])</span>
<span id="cb10-187"><a href="#cb10-187" aria-hidden="true" tabindex="-1"></a>    train_pairs <span class="op">=</span> np.array(training_results[count])</span>
<span id="cb10-188"><a href="#cb10-188" aria-hidden="true" tabindex="-1"></a>    deltas <span class="op">=</span> pairs[:, <span class="dv">1</span>] <span class="op">-</span> pairs[:, <span class="dv">0</span>]</span>
<span id="cb10-189"><a href="#cb10-189" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(</span>
<span id="cb10-190"><a href="#cb10-190" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>count<span class="sc">}</span><span class="ss">/family: scratch=</span><span class="sc">{</span>pairs[:, <span class="dv">0</span>]<span class="sc">.</span>mean()<span class="sc">:.3f}</span><span class="ss">, "</span></span>
<span id="cb10-191"><a href="#cb10-191" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"pretrained=</span><span class="sc">{</span>pairs[:, <span class="dv">1</span>]<span class="sc">.</span>mean()<span class="sc">:.3f}</span><span class="ss">, "</span></span>
<span id="cb10-192"><a href="#cb10-192" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"delta=</span><span class="sc">{</span>deltas<span class="sc">.</span>mean()<span class="sc">:+.3f}</span><span class="ss">, wins=</span><span class="sc">{</span>(deltas <span class="op">&gt;</span> <span class="dv">0</span>)<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">}</span><span class="ss">/5, "</span></span>
<span id="cb10-193"><a href="#cb10-193" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"uncovered=</span><span class="sc">{</span>control_pairs[:, <span class="dv">0</span>]<span class="sc">.</span>mean()<span class="sc">:.3f}</span><span class="ss">/"</span></span>
<span id="cb10-194"><a href="#cb10-194" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>control_pairs[:, <span class="dv">1</span>]<span class="sc">.</span>mean()<span class="sc">:.3f}</span><span class="ss">, "</span></span>
<span id="cb10-195"><a href="#cb10-195" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"train=</span><span class="sc">{</span>train_pairs[:, <span class="dv">0</span>]<span class="sc">.</span>mean()<span class="sc">:.3f}</span><span class="ss">/"</span></span>
<span id="cb10-196"><a href="#cb10-196" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>train_pairs[:, <span class="dv">1</span>]<span class="sc">.</span>mean()<span class="sc">:.3f}</span><span class="ss">"</span></span>
<span id="cb10-197"><a href="#cb10-197" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>selected targets across five runs: 155,019
eligible positions: 1,032,096
realized selection rate: 15.020%
realized mask/random/unchanged shares: [0.8003599643707275, 0.09977486729621887, 0.09986517578363419]
1/family: scratch=0.468, pretrained=0.995, delta=+0.526, wins=5/5, uncovered=0.475/0.425, train=1.000/1.000
2/family: scratch=0.489, pretrained=1.000, delta=+0.511, wins=5/5, uncovered=0.500/0.440, train=1.000/1.000
4/family: scratch=0.494, pretrained=1.000, delta=+0.506, wins=5/5, uncovered=0.550/0.430, train=1.000/1.000</code></pre>
</div>
</div>
<p>Across 1,032,096 eligible positions, the five runs select 155,019—15.020%. The realized branches are 80.04% mask, 9.98% random, and 9.99% unchanged. Both scratch and pretrained models reach 100% on their tiny labeled training sets in every run; failure to fit the labels therefore does not explain the scratch result.</p>
</section>
<section id="what-transferred" class="level3">
<h3 class="anchored" data-anchor-id="what-transferred">What transferred?</h3>
<p>Remember the question: did pretraining organize covered representations in a way that scarce labels could reuse—or did the classifier merely learn the tiny label set? The task, control, and geometry answer different parts.</p>
<div id="cell-fig-pretraining-pays" class="cell" data-fig-height="3.7" data-fig-width="11" data-execution_count="8">
<details class="code-fold">
<summary>Figure code: audit paired transfer, source coverage, and representation geometry</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="at">@torch.no_grad</span>()</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> representation_geometry(</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    encoder_state: TensorState,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>) <span class="op">-&gt;</span> <span class="bu">tuple</span>[<span class="bu">float</span>, <span class="bu">float</span>]:</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    model <span class="op">=</span> TinyBertEncoder()</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    model.load_state_dict(encoder_state)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    words <span class="op">=</span> covered_words[<span class="dv">0</span>] <span class="op">+</span> covered_words[<span class="dv">1</span>]</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    vectors <span class="op">=</span> model(torch.stack([</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>        neutral_sentence(word) <span class="cf">for</span> word <span class="kw">in</span> words</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>    ]))[:, <span class="dv">4</span>]</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>    vectors <span class="op">=</span> vectors <span class="op">-</span> vectors.mean(dim<span class="op">=</span><span class="dv">0</span>, keepdim<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>    vectors <span class="op">=</span> F.normalize(vectors, dim<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>    similarities <span class="op">=</span> vectors <span class="op">@</span> vectors.T</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>    labels <span class="op">=</span> torch.tensor(</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>        [<span class="dv">0</span>] <span class="op">*</span> <span class="bu">len</span>(covered_words[<span class="dv">0</span>]) <span class="op">+</span> [<span class="dv">1</span>] <span class="op">*</span> <span class="bu">len</span>(covered_words[<span class="dv">1</span>])</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>    off_diagonal <span class="op">=</span> <span class="op">~</span>torch.eye(<span class="bu">len</span>(words), dtype<span class="op">=</span>torch.<span class="bu">bool</span>)</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>    within <span class="op">=</span> similarities[</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>        (labels[:, <span class="va">None</span>] <span class="op">==</span> labels[<span class="va">None</span>, :]) <span class="op">&amp;</span> off_diagonal</span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>    ]</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>    between <span class="op">=</span> similarities[labels[:, <span class="va">None</span>] <span class="op">!=</span> labels[<span class="va">None</span>, :]]</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> within.mean().item(), between.mean().item()</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> first_states <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span></span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a>initial_geometry <span class="op">=</span> representation_geometry(first_states[<span class="dv">0</span>])</span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a>pretrained_geometry <span class="op">=</span> representation_geometry(first_states[<span class="dv">1</span>])</span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a>budgets <span class="op">=</span> np.array(LABEL_COUNTS)</span>
<span id="cb12-29"><a href="#cb12-29" aria-hidden="true" tabindex="-1"></a>scratch_means <span class="op">=</span> np.array([</span>
<span id="cb12-30"><a href="#cb12-30" aria-hidden="true" tabindex="-1"></a>    np.mean(paired_results[count], axis<span class="op">=</span><span class="dv">0</span>)[<span class="dv">0</span>]</span>
<span id="cb12-31"><a href="#cb12-31" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> count <span class="kw">in</span> LABEL_COUNTS</span>
<span id="cb12-32"><a href="#cb12-32" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb12-33"><a href="#cb12-33" aria-hidden="true" tabindex="-1"></a>pretrained_means <span class="op">=</span> np.array([</span>
<span id="cb12-34"><a href="#cb12-34" aria-hidden="true" tabindex="-1"></a>    np.mean(paired_results[count], axis<span class="op">=</span><span class="dv">0</span>)[<span class="dv">1</span>]</span>
<span id="cb12-35"><a href="#cb12-35" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> count <span class="kw">in</span> LABEL_COUNTS</span>
<span id="cb12-36"><a href="#cb12-36" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb12-37"><a href="#cb12-37" aria-hidden="true" tabindex="-1"></a>scratch_uncovered_means <span class="op">=</span> np.array([</span>
<span id="cb12-38"><a href="#cb12-38" aria-hidden="true" tabindex="-1"></a>    np.mean(uncovered_results[count], axis<span class="op">=</span><span class="dv">0</span>)[<span class="dv">0</span>]</span>
<span id="cb12-39"><a href="#cb12-39" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> count <span class="kw">in</span> LABEL_COUNTS</span>
<span id="cb12-40"><a href="#cb12-40" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb12-41"><a href="#cb12-41" aria-hidden="true" tabindex="-1"></a>pretrained_uncovered_means <span class="op">=</span> np.array([</span>
<span id="cb12-42"><a href="#cb12-42" aria-hidden="true" tabindex="-1"></a>    np.mean(uncovered_results[count], axis<span class="op">=</span><span class="dv">0</span>)[<span class="dv">1</span>]</span>
<span id="cb12-43"><a href="#cb12-43" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> count <span class="kw">in</span> LABEL_COUNTS</span>
<span id="cb12-44"><a href="#cb12-44" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb12-45"><a href="#cb12-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-46"><a href="#cb12-46" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="fl">3.7</span>))</span>
<span id="cb12-47"><a href="#cb12-47" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> values, label, color, marker <span class="kw">in</span> [</span>
<span id="cb12-48"><a href="#cb12-48" aria-hidden="true" tabindex="-1"></a>    (scratch_means, <span class="st">"scratch, covered"</span>, <span class="st">"#6b7280"</span>, <span class="st">"o"</span>),</span>
<span id="cb12-49"><a href="#cb12-49" aria-hidden="true" tabindex="-1"></a>    (pretrained_means, <span class="st">"MLM, covered"</span>, <span class="st">"#3566a8"</span>, <span class="st">"o"</span>),</span>
<span id="cb12-50"><a href="#cb12-50" aria-hidden="true" tabindex="-1"></a>    (</span>
<span id="cb12-51"><a href="#cb12-51" aria-hidden="true" tabindex="-1"></a>        scratch_uncovered_means,</span>
<span id="cb12-52"><a href="#cb12-52" aria-hidden="true" tabindex="-1"></a>        <span class="st">"scratch, unexposed"</span>,</span>
<span id="cb12-53"><a href="#cb12-53" aria-hidden="true" tabindex="-1"></a>        <span class="st">"#9ca3af"</span>,</span>
<span id="cb12-54"><a href="#cb12-54" aria-hidden="true" tabindex="-1"></a>        <span class="st">"s"</span>,</span>
<span id="cb12-55"><a href="#cb12-55" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb12-56"><a href="#cb12-56" aria-hidden="true" tabindex="-1"></a>    (</span>
<span id="cb12-57"><a href="#cb12-57" aria-hidden="true" tabindex="-1"></a>        pretrained_uncovered_means,</span>
<span id="cb12-58"><a href="#cb12-58" aria-hidden="true" tabindex="-1"></a>        <span class="st">"MLM, unexposed"</span>,</span>
<span id="cb12-59"><a href="#cb12-59" aria-hidden="true" tabindex="-1"></a>        <span class="st">"#d37b29"</span>,</span>
<span id="cb12-60"><a href="#cb12-60" aria-hidden="true" tabindex="-1"></a>        <span class="st">"s"</span>,</span>
<span id="cb12-61"><a href="#cb12-61" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb12-62"><a href="#cb12-62" aria-hidden="true" tabindex="-1"></a>]:</span>
<span id="cb12-63"><a href="#cb12-63" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">0</span>].plot(budgets, values, label<span class="op">=</span>label, color<span class="op">=</span>color, marker<span class="op">=</span>marker)</span>
<span id="cb12-64"><a href="#cb12-64" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].axhline(<span class="fl">0.5</span>, color<span class="op">=</span><span class="st">"black"</span>, lw<span class="op">=</span><span class="dv">1</span>, ls<span class="op">=</span><span class="st">"--"</span>, alpha<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb12-65"><a href="#cb12-65" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xticks(budgets)</span>
<span id="cb12-66"><a href="#cb12-66" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylim(<span class="fl">0.25</span>, <span class="fl">1.05</span>)</span>
<span id="cb12-67"><a href="#cb12-67" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xlabel(<span class="st">"labeled words per family"</span>)</span>
<span id="cb12-68"><a href="#cb12-68" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"accuracy"</span>)</span>
<span id="cb12-69"><a href="#cb12-69" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">"only covered strings benefit"</span>)</span>
<span id="cb12-70"><a href="#cb12-70" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb12-71"><a href="#cb12-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-72"><a href="#cb12-72" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> column, count <span class="kw">in</span> <span class="bu">enumerate</span>(LABEL_COUNTS):</span>
<span id="cb12-73"><a href="#cb12-73" aria-hidden="true" tabindex="-1"></a>    pairs <span class="op">=</span> np.array(paired_results[count])</span>
<span id="cb12-74"><a href="#cb12-74" aria-hidden="true" tabindex="-1"></a>    deltas <span class="op">=</span> pairs[:, <span class="dv">1</span>] <span class="op">-</span> pairs[:, <span class="dv">0</span>]</span>
<span id="cb12-75"><a href="#cb12-75" aria-hidden="true" tabindex="-1"></a>    jitter <span class="op">=</span> np.linspace(<span class="op">-</span><span class="fl">0.08</span>, <span class="fl">0.08</span>, <span class="bu">len</span>(deltas))</span>
<span id="cb12-76"><a href="#cb12-76" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">1</span>].scatter(</span>
<span id="cb12-77"><a href="#cb12-77" aria-hidden="true" tabindex="-1"></a>        np.full(<span class="bu">len</span>(deltas), column) <span class="op">+</span> jitter,</span>
<span id="cb12-78"><a href="#cb12-78" aria-hidden="true" tabindex="-1"></a>        deltas,</span>
<span id="cb12-79"><a href="#cb12-79" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span><span class="st">"#3566a8"</span>,</span>
<span id="cb12-80"><a href="#cb12-80" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb12-81"><a href="#cb12-81" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].axhline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">"black"</span>, lw<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb12-82"><a href="#cb12-82" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xticks(<span class="bu">range</span>(<span class="dv">3</span>), [<span class="st">"1"</span>, <span class="st">"2"</span>, <span class="st">"4"</span>])</span>
<span id="cb12-83"><a href="#cb12-83" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xlabel(<span class="st">"labeled words per family"</span>)</span>
<span id="cb12-84"><a href="#cb12-84" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_ylabel(<span class="st">"pretrained − scratch"</span>)</span>
<span id="cb12-85"><a href="#cb12-85" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">"all 15 paired gains"</span>)</span>
<span id="cb12-86"><a href="#cb12-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-87"><a href="#cb12-87" aria-hidden="true" tabindex="-1"></a>geometry <span class="op">=</span> np.array([initial_geometry, pretrained_geometry])</span>
<span id="cb12-88"><a href="#cb12-88" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.arange(<span class="dv">2</span>)</span>
<span id="cb12-89"><a href="#cb12-89" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].bar(</span>
<span id="cb12-90"><a href="#cb12-90" aria-hidden="true" tabindex="-1"></a>    x <span class="op">-</span> <span class="fl">0.18</span>, geometry[:, <span class="dv">0</span>], width<span class="op">=</span><span class="fl">0.36</span>,</span>
<span id="cb12-91"><a href="#cb12-91" aria-hidden="true" tabindex="-1"></a>    label<span class="op">=</span><span class="st">"within family"</span>, color<span class="op">=</span><span class="st">"#3566a8"</span>,</span>
<span id="cb12-92"><a href="#cb12-92" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-93"><a href="#cb12-93" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].bar(</span>
<span id="cb12-94"><a href="#cb12-94" aria-hidden="true" tabindex="-1"></a>    x <span class="op">+</span> <span class="fl">0.18</span>, geometry[:, <span class="dv">1</span>], width<span class="op">=</span><span class="fl">0.36</span>,</span>
<span id="cb12-95"><a href="#cb12-95" aria-hidden="true" tabindex="-1"></a>    label<span class="op">=</span><span class="st">"between family"</span>, color<span class="op">=</span><span class="st">"#d37b29"</span>,</span>
<span id="cb12-96"><a href="#cb12-96" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-97"><a href="#cb12-97" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].axhline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">"black"</span>, lw<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb12-98"><a href="#cb12-98" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_xticks(x, [<span class="st">"initial"</span>, <span class="st">"after MLM"</span>])</span>
<span id="cb12-99"><a href="#cb12-99" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_ylabel(<span class="st">"centered cosine similarity"</span>)</span>
<span id="cb12-100"><a href="#cb12-100" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_title(<span class="st">"seed 6050 geometry"</span>)</span>
<span id="cb12-101"><a href="#cb12-101" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb12-102"><a href="#cb12-102" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb12-103"><a href="#cb12-103" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb12-104"><a href="#cb12-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-105"><a href="#cb12-105" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"initial within/between: </span><span class="sc">{</span>initial_geometry<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb12-106"><a href="#cb12-106" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"after MLM within/between: </span><span class="sc">{</span>pretrained_geometry<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-pretraining-pays" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Three-panel transfer audit. Covered-token accuracy after MLM stays near one for one, two, and four labeled words per family, while scratch and both unexposed controls remain around chance. All 15 paired MLM-minus-scratch gains are positive, roughly 0.37 to 0.62. For seed 6050, centered cosine similarity changes from near zero for both pair types to positive within-family and negative between-family values after MLM.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pretraining-pays-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="15-bert-pretraining_files/figure-html/fig-pretraining-pays-output-1.png" alt="Three-panel transfer audit. Covered-token accuracy after MLM stays near one for one, two, and four labeled words per family, while scratch and both unexposed controls remain around chance. All 15 paired MLM-minus-scratch gains are positive, roughly 0.37 to 0.62. For seed 6050, centered cosine similarity changes from near zero for both pair types to positive within-family and negative between-family values after MLM." width="1048" height="345" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pretraining-pays-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15.4: Five paired end-to-end seeds in the synthetic transfer lab. MLM initialization separates covered latent families and improves every covered-type comparison (left and center); both arms stay near chance on input-vocabulary controls withheld from MLM inputs, replacements, and targets (left). Centered cosine similarity is a representation diagnostic, not a task metric (right).
</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>initial within/between: (-0.03466804325580597, -0.0160280279815197)
after MLM within/between: (0.5322557687759399, -0.5517237186431885)</code></pre>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Labels / family</th>
<th style="text-align: right;">Scratch, covered</th>
<th style="text-align: right;">MLM, covered</th>
<th style="text-align: right;">Gain</th>
<th style="text-align: right;">Scratch, unexposed</th>
<th style="text-align: right;">MLM, unexposed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.468</td>
<td style="text-align: right;">0.995</td>
<td style="text-align: right;">+0.526</td>
<td style="text-align: right;">0.475</td>
<td style="text-align: right;">0.425</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.489</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">+0.511</td>
<td style="text-align: right;">0.500</td>
<td style="text-align: right;">0.440</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.494</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">+0.506</td>
<td style="text-align: right;">0.550</td>
<td style="text-align: right;">0.430</td>
</tr>
</tbody>
</table>
<p>MLM initialization wins all 15 paired covered-type comparisons. At two labels per family, for example, mean covered accuracy moves from 0.489 to 1.000. On the 40 unexposed controls, scratch and MLM-initialized means stay around chance at every budget. MLM therefore helps types whose source contexts contain the latent regularity—not arbitrary rows that merely exist in the input vocabulary.</p>
<p>The labeled sets are nested within a seed, but increasing the budget removes those additional types from that budget’s test pool. The within-budget scratch-versus-MLM comparison is exact; movement across budgets is not a controlled learning curve.</p>
<p>The representation diagnostic agrees with the task result. In seed 6050, mean centered cosine similarity starts at <span class="math inline">\(-0.0347\)</span> within a family and <span class="math inline">\(-0.0160\)</span> between families—no useful separation. After MLM, it is <span class="math inline">\(0.5323\)</span> within and <span class="math inline">\(-0.5517\)</span> between. <em>Centered cosine</em> first subtracts the mean representation, then unit-normalizes each vector and takes a dot product: positive values point in similar residual directions, negative values in opposing directions. Pretraining has organized neutral-context token states around the latent source regularity, and a few labels recover that organization for unseen covered types.</p>
<p>This closes Chapter 9’s contract at toy scale:</p>
<ul>
<li><strong>Labels are scarce:</strong> the task supplies only 2, 4, or 8 labeled words total.</li>
<li><strong>The target is representation-hungry:</strong> spelling, frequency, and task-context cues are neutralized; the label must transfer through the token representation.</li>
<li><strong>Source coverage is useful at a matched scale:</strong> source and target use atomic tokens and similarly short sequences; covered strings transfer, while balanced vocabulary residents withheld from MLM inputs, replacements, and targets remain near chance in both arms.</li>
</ul>
<p>The result is an existence proof for a mechanism. A co-occurrence method could also recover the synthetic families; the experiment does not establish Transformer superiority. The limits are concrete—the data generator builds the regularity, the pretrained arm receives extra compute, and five toy seeds do not estimate natural-language performance. The justified conclusion is narrower: <strong>in this controlled construction, MLM organizes covered token representations around a latent regularity, and a few labels recover it for unseen covered types.</strong></p>
<!-- /NOVEL -->
</section>
</section>
<section id="three-pretraining-families" class="level2" data-number="15.7">
<h2 data-number="15.7" class="anchored" data-anchor-id="three-pretraining-families"><span class="header-section-number">15.7</span> Three pretraining families</h2>
<p>Pretraining is a regime, not an architecture. The visibility rule and pretraining objective determine what a model can learn—and how it will later be used.</p>
<div id="tbl-pretraining-families" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pretraining-families-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;15.1: Three pretraining families separate visibility, objective, and characteristic use.
</figcaption>
<div aria-describedby="tbl-pretraining-families-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Family</th>
<th>Visibility during pretraining</th>
<th>Objective</th>
<th>Characteristic use</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>BERT-style encoder</td>
<td>Full nonpadding context</td>
<td>Predict selected original tokens after 80/10/10 treatment</td>
<td>Contextual representations and task heads</td>
</tr>
<tr class="even">
<td>GPT-style decoder</td>
<td>Causal prefix</td>
<td>Predict the next token</td>
<td>Autoregressive generation and adaptation</td>
</tr>
<tr class="odd">
<td>T5-style encoder–decoder</td>
<td>Full encoder; causal decoder with cross-attention</td>
<td>Generate removed spans separated by sentinel tokens</td>
<td>Text-to-text conditional generation</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The separation in <a href="#tbl-pretraining-families" class="quarto-xref">Table&nbsp;<span>15.1</span></a> matters during execution too. A GPT-style decoder can train all next-token positions in parallel under teacher forcing because the causal mask exposes only each prefix. Generation is still sequential: the model must emit a token before that token can join the next prefix. Training and inference share a factorization and visibility rule, not an execution schedule.</p>
<p>Once those next-token logits exist, Chapter 11’s greedy and beam-search machinery can rank continuations—the architecture changes, but decoding remains a separate decision layer. Chapter 17 will return to how prompts alter the context supplied to that decoder.</p>
<p>T5 turns tasks into text-to-text problems and marks removed spans with learned sentinel tokens. Its encoder produces a <em>sequence</em> of memory states under full visibility; its causal decoder cross-attends to that sequence while generating the target. It does not squeeze the input into one fixed bottleneck vector. These families trade representation, generation, and input–output structure differently—they are not a ranking from old to new.</p>
</section>
<section id="what-changed-after-2018" class="level2" data-number="15.8">
<h2 data-number="15.8" class="anchored" data-anchor-id="what-changed-after-2018"><span class="header-section-number">15.8</span> What changed after 2018</h2>
<p>Before the pretrained era, a new labeled dataset often implied a new model trained from a random initialization. After BERT and its contemporaries, the default question changed: which pretrained model, which adaptation, and which data interface fit the task?</p>
<p>Three consequences follow.</p>
<p><strong>Optimization starts elsewhere.</strong> The downstream run begins in a parameter region already shaped by a broad source objective. The task is not asking a few labels to invent syntax and semantics from scratch.</p>
<p><strong>Data work moves upstream.</strong> Corpus choice, tokenization, corruption, and source coverage become part of model design. Pretraining is curriculum at dataset scale.</p>
<p><strong>One backbone serves many interfaces.</strong> A sequence head, token head, or span head can reuse the same encoder. That modularity makes comparison easier—but also makes pretraining assumptions easy to inherit without inspecting them.</p>
<p>The regime introduces new failure modes. Source bias can transfer with useful features. A vocabulary can represent a token without supplying useful exposure. Full fine-tuning can forget source behavior or become too expensive as the backbone grows. Those are not footnotes to transfer; they are the agenda of the pretrained era.</p>
<p>The chapter closes with three forward seeds. A learned summary token can gather a sequence for a downstream head; <a href="16-vit-scaling.html" class="quarto-xref"><span>Chapter 16</span></a> will give that same pattern a sequence of image patches. Pretraining is a regime, not an architecture; Chapter 16 will ask what changes when an encoder leaves text for images and scaling takes center stage. Fine-tuning changed every encoder weight here; <a href="../part5/17-peft-quantization.html" class="quarto-xref"><span>Chapter 17</span></a> will ask what adaptation remains when most, or all, of those weights must stay fixed.</p>
</section>
<section id="okay-so-pretraining-manufactures-supervision" class="level2" data-number="15.9">
<h2 data-number="15.9" class="anchored" data-anchor-id="okay-so-pretraining-manufactures-supervision"><span class="header-section-number">15.9</span> Okay, so — pretraining manufactures supervision</h2>
<ol type="1">
<li><strong>Visibility, selection, corruption, and padding are separate.</strong> BERT removes the causal triangle, selects loss targets, then applies the 80/10/10 treatment so copying cannot solve most of them. <code>[MASK]</code> is a token—not an attention ban.</li>
<li><strong>MLM turns raw text into supervision.</strong> Select 15% of eligible positions; conditional on selection, use 80% mask, 10% random, and 10% unchanged. All selected positions predict their original tokens.</li>
<li><strong>BERT is a full-context Transformer encoder.</strong> WordPiece tokens, learned token/position/segment embeddings, post-LayerNorm blocks, MLM, and historical NSP define the original recipe.</li>
<li><strong>Fine-tuning updates the encoder.</strong> Training only a new head over frozen features is a probe. Standard BERT adaptation moves the pretrained backbone and task head together.</li>
<li><strong>The controlled lab closes the transfer loop at toy scale.</strong> Across five full seeds, MLM initialization wins every covered-type comparison under 2–8 total labels; input-vocabulary controls withheld from MLM inputs, replacements, and targets remain near chance in both arms.</li>
<li><strong>Pretraining changed the unit of work.</strong> The field moved from one random model per task toward reusable backbones and specialized adaptation. Corpus, objective, visibility, and adaptation now belong to one design decision.</li>
</ol>
</section>
<section id="sources-and-further-reading" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="sources-and-further-reading">Sources and further reading</h2>
<ul>
<li><a href="https://aclanthology.org/N18-1202/">Peters et al., <em>Deep Contextualized Word Representations</em></a>: ELMo and fixed contextual features from forward and backward language models.</li>
<li><a href="https://aclanthology.org/P18-1031/">Howard and Ruder, <em>Universal Language Model Fine-tuning for Text Classification</em></a>: ULMFiT’s full-model adaptation recipe.</li>
<li><a href="https://cdn.openai.com/research-covers/language-unsupervised/language_understanding_paper.pdf">Radford et al., <em>Improving Language Understanding by Generative Pre-Training</em></a>: causal Transformer pretraining followed by supervised adaptation.</li>
<li><a href="https://aclanthology.org/P16-1162/">Sennrich, Haddow, and Birch, <em>Neural Machine Translation of Rare Words with Subword Units</em></a>: the frequency-driven BPE adaptation for subword vocabularies.</li>
<li><a href="https://aclanthology.org/N19-1423/">Devlin et al., <em>BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding</em></a>: the original BERT architecture, MLM/NSP objectives, and fine-tuning results.</li>
<li><a href="https://github.com/google-research/bert/blob/master/run_pretraining.py">Google Research, <em>BERT pretraining implementation</em></a>: the released implementation documents the tied input/output embedding weights.</li>
<li><a href="https://arxiv.org/abs/1907.11692">Liu et al., <em>RoBERTa: A Robustly Optimized BERT Pretraining Approach</em></a>: a later study of BERT training choices, including removal of NSP.</li>
<li><a href="https://www.jmlr.org/papers/v21/20-074.html">Raffel et al., <em>Exploring the Limits of Transfer Learning with a Unified Text-to-Text Transformer</em></a>: the T5 text-to-text framework and span-corruption recipe.</li>
</ul>
</section>
<section id="exercises" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercises">Exercises</h2>
<ol type="1">
<li><strong>(Pencil.)</strong> For <code>[CLS] the wug is calm [SEP] [PAD] [PAD]</code>, suppose <em>wug</em> is selected and replaced by <code>[MASK]</code>. Draw Chapter 14’s causal visibility matrix and BERT’s full nonpadding visibility matrix, using queries as rows and keys as columns. Separately mark the one position that contributes MLM loss. Why may neighboring tokens attend to <code>[MASK]</code>, and why would full visibility leak information in a next-token generator?</li>
<li><strong>(Pencil.)</strong> A batch contains 2,000 eligible ordinary tokens. Under BERT’s policy, how many positions are expected to be selected, replaced by <code>[MASK]</code>, replaced by a random token, and left unchanged? How many contribute direct MLM loss? Explain why 12% is not the supervision rate.</li>
<li><strong>(Code.)</strong> For token IDs <span class="math inline">\((B,T)\)</span>, width <span class="math inline">\(d\)</span>, and vocabulary size <span class="math inline">\(|V|\)</span>, add assertions for hidden states <span class="math inline">\((B,T,d)\)</span>, dense logits <span class="math inline">\((B,T,|V|)\)</span>, selected logits <span class="math inline">\((|M|,|V|)\)</span>, and selected targets <span class="math inline">\((|M|,)\)</span>. Assert that <code>[PAD]</code>, <code>[CLS]</code>, and <code>[SEP]</code> are never selected. Show numerically that selected-only cross-entropy matches dense cross-entropy when unselected targets use <code>ignore_index</code>.</li>
<li><strong>(Code.)</strong> Starting from the same pretrained checkpoint and split, compare a frozen encoder probe with full fine-tuning in the generated-token lab. Match head tensors, labeled types, updates, and seeds. Plot all five paired results rather than only their means. Which regime wins here, and what broader claim would outrun the experiment?</li>
<li><strong>(Code and interpretation.)</strong> Reproduce paired gains for covered and control strings at all three budgets. Map the evidence to Chapter 9’s gates. Explain the unchanged-row assertion, name two unsupported conclusions, and propose one predeclared coverage test.</li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/shakeri-lab\.github\.io\/dl-book\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../chapters/part4/14-self-attention-transformer.html" class="pagination-link" aria-label="Self-Attention and the Transformer">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Self-Attention and the Transformer</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/part4/16-vit-scaling.html" class="pagination-link" aria-label="Vision Transformers and Scaling Laws">
        <span class="nav-page-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Vision Transformers and Scaling Laws</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Heman Shakeri · Text CC BY-NC-SA 4.0 · Code MIT · School of Data Science, University of Virginia</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/Shakeri-Lab/dl-book/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Companion to <a href="https://shakeri-lab.github.io/dl-course-site/">DS 6050 Deep Learning</a></p>
</div>
  </div>
</footer>




</body></html>