<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>16&nbsp; Vision Transformers and Scaling Laws – Deep Learning: Making It Learnable</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/part5/17-peft-quantization.html" rel="next">
<link href="../../chapters/part4/15-bert-pretraining.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-c90f29e1247290e1dfbeb1da338aa877.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>
  // Book math macros — keep in sync with tex/macros.tex (PDF path).
  // MathJax reads this config because it is defined before the MathJax
  // script loads (Quarto places include-in-header above its math script).
  window.MathJax = {
    tex: {
      macros: {
        E: "\\mathbb{E}",
        Ex: "\\operatorname{E}",
        var: "\\operatorname{Var}",
        cov: "\\operatorname{Cov}",
        imp: "\\Rightarrow",
        argmax: "\\operatorname*{arg\\,max}",
        argmin: "\\operatorname*{arg\\,min}",
        norm: ["\\left\\lVert#1\\right\\rVert", 1],
        vect: ["\\boldsymbol{#1}", 1],
        matr: ["\\boldsymbol{#1}", 1],
        R: "\\mathbb{R}",
        dd: "\\mathrm{d}",
        loss: "\\mathcal{L}"
      }
    }
  };
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/part4/12-kernel-regression.html">Attention: Learning the Similarity</a></li><li class="breadcrumb-item"><a href="../../chapters/part4/16-vit-scaling.html"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Vision Transformers and Scaling Laws</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Deep Learning: Making It Learnable</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/Shakeri-Lab/dl-book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">From Lines to Networks</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/01-linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Linear Regression, the Mother Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/02-logistic-softmax.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Linear Models that Classify: Logistic and Softmax</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/03-nonlinearity-mlp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Nonlinearity and the MLP</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/04-training-loss-sgd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Training: Loss and Stochastic Gradient Descent</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/05-backpropagation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Backpropagation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/06-generalization-inductive-bias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">When It Fails: Generalization in Pictures, and Inductive Bias</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/interludes/learning-by-experiment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Who Trains the Trainer? Learning by Experiment</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Vision: Learning the Filters</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/07-filters-convolution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Filters and Convolution (Fixed Kernels)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/08-cnn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">CNNs: Making the Filters Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/09-modern-cnns-transfer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Modern CNNs and Transfer Learning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/interludes/making-pca-learnable.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Interlude: Making PCA Learnable</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Sequences</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part3/10-sequences-rnn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Sequences and Recurrence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part3/11-encoder-decoder.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Encoder–Decoder, Teacher Forcing, Beam Search</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Attention: Learning the Similarity</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/12-kernel-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Kernel Regression: Attention Before It Was Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/13-attention.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Attention: Making the Kernel Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/14-self-attention-transformer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Self-Attention and the Transformer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/15-bert-pretraining.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">The BERT Moment: Pretraining as the New Regime</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/16-vit-scaling.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Vision Transformers and Scaling Laws</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">The Pretrained Era</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/17-peft-quantization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Adapting Pretrained Models: Prompting, PEFT, Quantization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/18-alignment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Alignment and RL Fine-Tuning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/19-generative.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Generative Models: From Codes to Samples</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/20-multimodal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Multimodal Learning: One Space, Two Views</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/epilogue.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Epilogue: The Question Is Yours</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a1-linear-algebra.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Linear Algebra and the SVD</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a2-tensors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Tensors in Practice</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a3-precision-performance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Numerical Precision and Hardware Efficiency</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a4-notation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Notation</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
<div class="quarto-sidebar-footer"><div class="sidebar-footer-item">
<p><a href="https://shakeri-lab.github.io/dl-book/#revision-notes">Revision notes</a></p>
</div></div></nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#let-the-image-become-a-sequence" id="toc-let-the-image-become-a-sequence" class="nav-link active" data-scroll-target="#let-the-image-become-a-sequence"><span class="header-section-number">16.1</span> Let the image become a sequence</a></li>
  <li><a href="#a-learned-meeting-place-for-patches" id="toc-a-learned-meeting-place-for-patches" class="nav-link" data-scroll-target="#a-learned-meeting-place-for-patches"><span class="header-section-number">16.2</span> A learned meeting place for patches</a></li>
  <li><a href="#inductive-bias-strikes-again" id="toc-inductive-bias-strikes-again" class="nav-link" data-scroll-target="#inductive-bias-strikes-again"><span class="header-section-number">16.3</span> Inductive bias strikes again</a></li>
  <li><a href="#a-fashion-rematch-not-a-referendum" id="toc-a-fashion-rematch-not-a-referendum" class="nav-link" data-scroll-target="#a-fashion-rematch-not-a-referendum"><span class="header-section-number">16.4</span> A Fashion rematch, not a referendum</a></li>
  <li><a href="#scale-changes-the-comparison" id="toc-scale-changes-the-comparison" class="nav-link" data-scroll-target="#scale-changes-the-comparison"><span class="header-section-number">16.5</span> Scale changes the comparison</a>
  <ul class="collapse">
  <li><a href="#three-places-to-buy-back-useful-bias" id="toc-three-places-to-buy-back-useful-bias" class="nav-link" data-scroll-target="#three-places-to-buy-back-useful-bias">Three places to buy back useful bias</a></li>
  </ul></li>
  <li><a href="#the-word-scaling-changes-jobs" id="toc-the-word-scaling-changes-jobs" class="nav-link" data-scroll-target="#the-word-scaling-changes-jobs"><span class="header-section-number">16.6</span> The word “scaling” changes jobs</a>
  <ul class="collapse">
  <li><a href="#compound-scaling-three-knobs-one-budget" id="toc-compound-scaling-three-knobs-one-budget" class="nav-link" data-scroll-target="#compound-scaling-three-knobs-one-budget">Compound scaling: three knobs, one budget</a></li>
  </ul></li>
  <li><a href="#a-fitted-power-law-not-a-promise" id="toc-a-fitted-power-law-not-a-promise" class="nav-link" data-scroll-target="#a-fitted-power-law-not-a-promise"><span class="header-section-number">16.7</span> A fitted power law, not a promise</a></li>
  <li><a href="#compute-optimal-means-balanced" id="toc-compute-optimal-means-balanced" class="nav-link" data-scroll-target="#compute-optimal-means-balanced"><span class="header-section-number">16.8</span> Compute-optimal means balanced</a></li>
  <li><a href="#where-the-forecast-stops" id="toc-where-the-forecast-stops" class="nav-link" data-scroll-target="#where-the-forecast-stops"><span class="header-section-number">16.9</span> Where the forecast stops</a></li>
  <li><a href="#okay-so-patches-become-tokens-but-regime-still-matters" id="toc-okay-so-patches-become-tokens-but-regime-still-matters" class="nav-link" data-scroll-target="#okay-so-patches-become-tokens-but-regime-still-matters"><span class="header-section-number">16.10</span> Okay, so — patches become tokens, but regime still matters</a></li>
  <li><a href="#sources-and-further-reading" id="toc-sources-and-further-reading" class="nav-link" data-scroll-target="#sources-and-further-reading">Sources and further reading</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/Shakeri-Lab/dl-book/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/part4/12-kernel-regression.html">Attention: Learning the Similarity</a></li><li class="breadcrumb-item"><a href="../../chapters/part4/16-vit-scaling.html"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Vision Transformers and Scaling Laws</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-16-vit-scaling" class="quarto-section-identifier"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Vision Transformers and Scaling Laws</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<!-- lecture-source:
     m10_10-1-vision-transformer-vit_JSjPB1a-eS8.txt
     m10_10-3-scaling-of-decoder-transformer-models_Q56DkFc05Tg.txt
     (spine via ds6050_10_foundation_models/MODULE_NOTES.md; scene concepts
     checked against that module's Manim source)
     seeds: sources/10.0_ViT.tex, sources/10.1.scaling.tex,
            sources/4.3-NextGenCNN.tex
     primary sources: Dosovitskiy et al. 2021; Tan and Le 2019;
                      Touvron et al. 2021; Liu et al. 2021, 2022;
                      Kaplan et al. 2020; Hoffmann et al. 2022
     provenance note: all executable implementations and figures are independently
     derived from equations and published constants. The Fashion study is
     book-original and uses the fixed Chapter 6 split. Paper figures are discussed,
     not reproduced. Numerical claims from the lecture notes were re-derived against
     the primary papers before use. -->
<p>Chapter 14 promised that <strong>global routing trades away locality bias</strong>. Chapter 15 added two pieces: a learned summary token can gather a sequence for a downstream head, and <strong>pretraining is a regime, not an architecture</strong>. Let us collect those promises in one image. If a Transformer can read a sentence of words, what must change before it can read a photograph?</p>
<p>Surprisingly little. Cut the image into patches, project each patch to a vector, and let the Transformer encoder read those vectors as tokens. That minimalist transplant is the <strong>Vision Transformer (ViT)</strong>. Its simplicity—and the freedom it creates—is also the source of the interesting question. A convolutional network arrives knowing that nearby pixels belong together and that one local detector should slide across the image. ViT arrives with a much weaker image-specific prescription. Which learner wins therefore depends not just on architecture, but on data, training, and scale.</p>
<p>That word—<em>scale</em>—will change jobs halfway through the chapter. First it will mean making an image model deeper, wider, or higher-resolution. Then it will mean fitting empirical laws that connect loss to parameters, tokens, and training compute. The bridge between the two meanings is resource allocation: what should we enlarge, and what must grow with it?</p>
<section id="let-the-image-become-a-sequence" class="level2" data-number="16.1">
<h2 data-number="16.1" class="anchored" data-anchor-id="let-the-image-become-a-sequence"><span class="header-section-number">16.1</span> Let the image become a sequence</h2>
<p>Start with the arithmetic used by the original ViT. A color image is <span class="math inline">\(224\times224\)</span> pixels, and each square patch is <span class="math inline">\(16\times16\)</span>. There are</p>
<p><span class="math display">\[
\frac{224}{16}=14 \quad\Longrightarrow\quad 14^2=196
\]</span></p>
<p>patches. Each patch contains <span class="math inline">\(16\times16\times3=768\)</span> raw channel values. So one image has become a sequence of 196 vectors, each initially 768-dimensional—already the same width used by the base Transformer in that paper.</p>
<p>In general, let a batch be</p>
<p><span class="math display">\[
\matr{X}\in\mathbb{R}^{B\times C\times H\times W},
\]</span></p>
<p>where <span class="math inline">\(B\)</span> is batch size, <span class="math inline">\(C\)</span> channels, and <span class="math inline">\(H,W\)</span> are spatial dimensions. For a square patch width <span class="math inline">\(P\)</span> that divides both <span class="math inline">\(H\)</span> and <span class="math inline">\(W\)</span>, the patch count is</p>
<p><span id="eq-vit-patch-count"><span class="math display">\[
N=\frac{H}{P}\frac{W}{P},
\tag{16.1}\]</span></span></p>
<p>and flattening each patch gives</p>
<p><span class="math display">\[
\matr{X}_{\text{patch}}
\in\mathbb{R}^{B\times N\times(CP^2)}.
\]</span></p>
<p>We can see this on the fixed Fashion-MNIST subset first opened in <a href="../part1/06-generalization-inductive-bias.html" class="quarto-xref"><span>Chapter 6</span></a>. The <span class="math inline">\(28\times28\)</span> grayscale images divide into <span class="math inline">\(7\times7=49\)</span> patches when <span class="math inline">\(P=4\)</span>.</p>
<div id="vit-setup" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Code: imports, the fixed Chapter 6 split, and image shapes</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> hashlib</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> math</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib.patches <span class="im">import</span> Rectangle</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> torch <span class="im">import</span> nn</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.nn.functional <span class="im">as</span> F</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>torch.set_num_threads(<span class="dv">6</span>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>torch.manual_seed(<span class="dv">6050</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>development <span class="op">=</span> torch.load(<span class="st">"../../data/fashion-train.pt"</span>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>holdout <span class="op">=</span> torch.load(<span class="st">"../../data/fashion-test.pt"</span>)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>X_dev <span class="op">=</span> development[<span class="st">"X"</span>].<span class="bu">float</span>().unsqueeze(<span class="dv">1</span>) <span class="op">/</span> <span class="fl">255.0</span>  <span class="co"># (1200, 1, 28, 28)</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>y_dev, classes <span class="op">=</span> development[<span class="st">"y"</span>], development[<span class="st">"classes"</span>]</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>X_test <span class="op">=</span> holdout[<span class="st">"X"</span>].<span class="bu">float</span>().unsqueeze(<span class="dv">1</span>) <span class="op">/</span> <span class="fl">255.0</span>     <span class="co"># (600, 1, 28, 28)</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>y_test <span class="op">=</span> holdout[<span class="st">"y"</span>]</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>split <span class="op">=</span> torch.randperm(<span class="bu">len</span>(X_dev), generator<span class="op">=</span>torch.Generator().manual_seed(<span class="dv">6050</span>))</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>fit_idx, val_idx <span class="op">=</span> split[:<span class="dv">1000</span>], split[<span class="dv">1000</span>:]</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>X_fit, y_fit <span class="op">=</span> X_dev[fit_idx], y_dev[fit_idx]           <span class="co"># (1000, 1, 28, 28)</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>X_val, y_val <span class="op">=</span> X_dev[val_idx], y_dev[val_idx]           <span class="co"># (200, 1, 28, 28)</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"fit / validation / benchmark:"</span>, <span class="bu">len</span>(X_fit), <span class="bu">len</span>(X_val), <span class="bu">len</span>(X_test))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>fit / validation / benchmark: 1000 200 600</code></pre>
</div>
</div>
<p>A learned matrix</p>
<p><span class="math display">\[
\matr{E}\in\mathbb{R}^{CP^2\times d}
\]</span></p>
<p>projects every raw patch to model width <span class="math inline">\(d\)</span>. The operation has a useful exact identity. Unfold the image, multiply each flattened patch by <span class="math inline">\(\matr{E}\)</span>, and add a bias—or reshape the columns of <span class="math inline">\(\matr{E}\)</span> into <span class="math inline">\(d\)</span> convolutional kernels with kernel size <span class="math inline">\(P\)</span> and stride <span class="math inline">\(P\)</span>. The two computations are the same linear map.</p>
<div id="cell-fig-patchify" class="cell" data-fig-height="3.4" data-fig-width="10" data-execution_count="2">
<details class="code-fold">
<summary>Figure code: patchify and verify unfold-plus-linear equals one strided convolution</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>P, d <span class="op">=</span> <span class="dv">4</span>, <span class="dv">32</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>sample <span class="op">=</span> X_fit[:<span class="dv">1</span>]</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>generator <span class="op">=</span> torch.Generator().manual_seed(<span class="dv">6050</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>E_patch <span class="op">=</span> torch.randn(P <span class="op">*</span> P, d, generator<span class="op">=</span>generator)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>b_patch <span class="op">=</span> torch.randn(d, generator<span class="op">=</span>generator)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>raw_patches <span class="op">=</span> F.unfold(sample, kernel_size<span class="op">=</span>P, stride<span class="op">=</span>P).transpose(<span class="dv">1</span>, <span class="dv">2</span>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>tokens_linear <span class="op">=</span> raw_patches <span class="op">@</span> E_patch <span class="op">+</span> b_patch</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>conv_kernel <span class="op">=</span> E_patch.T.reshape(d, <span class="dv">1</span>, P, P)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>tokens_conv <span class="op">=</span> F.conv2d(</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    sample, conv_kernel, bias<span class="op">=</span>b_patch, stride<span class="op">=</span>P</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>).flatten(<span class="dv">2</span>).transpose(<span class="dv">1</span>, <span class="dv">2</span>)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>max_error <span class="op">=</span> (tokens_linear <span class="op">-</span> tokens_conv).<span class="bu">abs</span>().<span class="bu">max</span>().item()</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> raw_patches.shape <span class="op">==</span> (<span class="dv">1</span>, <span class="dv">49</span>, <span class="dv">16</span>)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> tokens_linear.shape <span class="op">==</span> (<span class="dv">1</span>, <span class="dv">49</span>, <span class="dv">32</span>)</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> max_error <span class="op">&lt;</span> <span class="fl">2e-6</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"raw patches:"</span>, <span class="bu">tuple</span>(raw_patches.shape))</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"projected tokens:"</span>, <span class="bu">tuple</span>(tokens_linear.shape))</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"max |linear - convolution|: </span><span class="sc">{</span>max_error<span class="sc">:.2e}</span><span class="ss">"</span>)</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>row, col <span class="op">=</span> <span class="dv">2</span>, <span class="dv">3</span></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>chosen <span class="op">=</span> sample[<span class="dv">0</span>, <span class="dv">0</span>, row <span class="op">*</span> P:(row <span class="op">+</span> <span class="dv">1</span>) <span class="op">*</span> P, col <span class="op">*</span> P:(col <span class="op">+</span> <span class="dv">1</span>) <span class="op">*</span> P]</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>cls_demo <span class="op">=</span> torch.randn(<span class="dv">1</span>, d, generator<span class="op">=</span>generator)</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>display_tokens <span class="op">=</span> torch.cat((cls_demo, tokens_linear[<span class="dv">0</span>]), dim<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="fl">3.4</span>),</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>                         gridspec_kw<span class="op">=</span>{<span class="st">"width_ratios"</span>: [<span class="dv">1</span>, <span class="fl">0.72</span>, <span class="fl">1.45</span>]})</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].imshow(sample[<span class="dv">0</span>, <span class="dv">0</span>], cmap<span class="op">=</span><span class="st">"gray"</span>, vmin<span class="op">=</span><span class="dv">0</span>, vmax<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> edge <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>, <span class="dv">29</span>, P):</span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">0</span>].axhline(edge <span class="op">-</span> <span class="fl">0.5</span>, color<span class="op">=</span><span class="st">"white"</span>, lw<span class="op">=</span><span class="fl">0.45</span>, alpha<span class="op">=</span><span class="fl">0.8</span>)</span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">0</span>].axvline(edge <span class="op">-</span> <span class="fl">0.5</span>, color<span class="op">=</span><span class="st">"white"</span>, lw<span class="op">=</span><span class="fl">0.45</span>, alpha<span class="op">=</span><span class="fl">0.8</span>)</span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].add_patch(Rectangle((col <span class="op">*</span> P <span class="op">-</span> <span class="fl">0.5</span>, row <span class="op">*</span> P <span class="op">-</span> <span class="fl">0.5</span>), P, P,</span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>                            fill<span class="op">=</span><span class="va">False</span>, edgecolor<span class="op">=</span><span class="st">"#E57200"</span>, lw<span class="op">=</span><span class="fl">2.5</span>))</span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">"28×28 image → 49 patches"</span>)</span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xticks([])<span class="op">;</span> axes[<span class="dv">0</span>].set_yticks([])</span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].imshow(chosen, cmap<span class="op">=</span><span class="st">"gray"</span>, vmin<span class="op">=</span><span class="dv">0</span>, vmax<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> r <span class="kw">in</span> <span class="bu">range</span>(P):</span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> c <span class="kw">in</span> <span class="bu">range</span>(P):</span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a>        axes[<span class="dv">1</span>].text(c, r, <span class="ss">f"</span><span class="sc">{</span>chosen[r, c]<span class="sc">:.1f}</span><span class="ss">"</span>, ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"center"</span>,</span>
<span id="cb3-42"><a href="#cb3-42" aria-hidden="true" tabindex="-1"></a>                     fontsize<span class="op">=</span><span class="dv">7</span>, color<span class="op">=</span><span class="st">"white"</span> <span class="cf">if</span> chosen[r, c] <span class="op">&lt;</span> <span class="fl">0.45</span> <span class="cf">else</span> <span class="st">"black"</span>)</span>
<span id="cb3-43"><a href="#cb3-43" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">"one 4×4 patch</span><span class="ch">\n</span><span class="st">16 raw values"</span>)</span>
<span id="cb3-44"><a href="#cb3-44" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xticks([])<span class="op">;</span> axes[<span class="dv">1</span>].set_yticks([])</span>
<span id="cb3-45"><a href="#cb3-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-46"><a href="#cb3-46" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].imshow(display_tokens.detach(), aspect<span class="op">=</span><span class="st">"auto"</span>, cmap<span class="op">=</span><span class="st">"RdBu_r"</span>)</span>
<span id="cb3-47"><a href="#cb3-47" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].axhline(<span class="fl">0.5</span>, color<span class="op">=</span><span class="st">"#E57200"</span>, lw<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb3-48"><a href="#cb3-48" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_yticks([<span class="dv">0</span>, <span class="dv">25</span>, <span class="dv">49</span>], [<span class="st">"[CLS]"</span>, <span class="st">"patch 25"</span>, <span class="st">"patch 49"</span>])</span>
<span id="cb3-49"><a href="#cb3-49" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_xlabel(<span class="st">"model coordinate"</span>)</span>
<span id="cb3-50"><a href="#cb3-50" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_title(<span class="st">"50 tokens × width 32"</span>)</span>
<span id="cb3-51"><a href="#cb3-51" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb3-52"><a href="#cb3-52" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>raw patches: (1, 49, 16)
projected tokens: (1, 49, 32)
max |linear - convolution|: 7.15e-07</code></pre>
</div>
<div class="cell-output cell-output-display">
<div id="fig-patchify" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A garment image is overlaid with a seven-by-seven patch grid and one patch is outlined. That four-by-four patch is enlarged with its sixteen pixel values, then a heatmap shows the resulting sequence of forty-nine projected patch rows plus a separate first CLS row.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-patchify-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="16-vit-scaling_files/figure-html/fig-patchify-output-2.png" alt="A garment image is overlaid with a seven-by-seven patch grid and one patch is outlined. That four-by-four patch is enlarged with its sixteen pixel values, then a heatmap shows the resulting sequence of forty-nine projected patch rows plus a separate first CLS row." width="946" height="316" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-patchify-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16.1: An image becomes a sequence. A 28×28 garment is divided into 49 nonoverlapping 4×4 patches (left); one patch contains 16 raw values (center); a shared linear projection maps every patch to width 32, and a separate learned [CLS] row is prepended (right). The displayed projection is random arithmetic, not a trained representation.
</figcaption>
</figure>
</div>
</div>
</div>
<p>This identity is more than a coding shortcut. The patch projection is a learned, shared local operator—a thin residue of image structure at ViT’s front door. What changes is what happens next: instead of stacking local feature maps, we hand the patch sequence to global self-attention.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Patchify once, audit twice
</div>
</div>
<div class="callout-body-container callout-body">
<p>Check that <span class="math inline">\(P\)</span> divides both spatial dimensions, assert the patch and token shapes, and compare unfold-plus-linear with the equivalent convolution to numerical roundoff. Patchification silently changes sequence length, feature width, and the attention bill; one shape mistake propagates through the entire model.</p>
</div>
</div>
</section>
<section id="a-learned-meeting-place-for-patches" class="level2" data-number="16.2">
<h2 data-number="16.2" class="anchored" data-anchor-id="a-learned-meeting-place-for-patches"><span class="header-section-number">16.2</span> A learned meeting place for patches</h2>
<p>The projected patches still need two additions. First, prepend a learned vector <span class="math inline">\(\vect{x}_{\mathrm{CLS}}\in\mathbb{R}^{d}\)</span>. Second, add one learned position vector to every sequence slot. For image <span class="math inline">\(b\)</span>, ViT’s complete encoder input is</p>
<p><span id="eq-vit-input"><span class="math display">\[
\matr{Z}_0^{(b)}=
\left[
\vect{x}_{\mathrm{CLS}};
\vect{x}_p^{1}\matr{E};
\ldots;
\vect{x}_p^{N}\matr{E}
\right]
+\matr{E}_{\mathrm{pos}}
\in\mathbb{R}^{(N+1)\times d},
\tag{16.2}\]</span></span></p>
<p>where <span class="math inline">\(\vect{x}_p^{i}\in\mathbb{R}^{CP^2}\)</span> is flattened patch <span class="math inline">\(i\)</span>, <span class="math inline">\(\matr{E}\in\mathbb{R}^{CP^2\times d}\)</span> is the shared patch projection, and <span class="math inline">\(\matr{E}_{\mathrm{pos}}\in\mathbb{R}^{(N+1)\times d}\)</span> contains learned absolute position vectors.</p>
<p><code>[CLS]</code> is not a summary by birth. As in <a href="15-bert-pretraining.html" class="quarto-xref"><span>Chapter 15</span></a>, it is a <strong>learned meeting place</strong> whose downstream loss teaches it what to gather. Every encoder layer lets that row query the patch rows; after the final layer, a linear head reads its <span class="math inline">\(d\)</span> coordinates and produces class logits. The original ViT appendix found that class-token and global-average-pooling heads worked similarly after tuning their learning rates. <code>[CLS]</code> is a useful interface—not proof of a superior pooling rule.</p>
<p>Position is essential for a different reason. Without positional information, self-attention is <strong>permutation-equivariant</strong>: permuting patch rows produces the same permutation of output rows. A symmetric pooling rule can consequently become invariant to patch order, unable to distinguish a sleeve above a shoe from a shoe above a sleeve. Learned positions break that symmetry. In the original ablation, removing position hurt, while learned 1-D, learned 2-D, and relative alternatives performed similarly in that setting. The result supports <em>supplying geometry</em>; it does not establish one universal positional scheme.</p>
<p>ViT then reuses Chapter 14’s pre-LayerNorm encoder block. With <span class="math inline">\(\matr{Z}_{\ell-1}\in\mathbb{R}^{B\times(N+1)\times d}\)</span>,</p>
<p><span class="math display">\[
\widetilde{\matr{Z}}_\ell
=\matr{Z}_{\ell-1}
+\operatorname{MSA}\!\left(\operatorname{LN}(\matr{Z}_{\ell-1})\right),
\]</span></p>
<p><span class="math display">\[
\matr{Z}_\ell
=\widetilde{\matr{Z}}_\ell
+\operatorname{MLP}\!\left(\operatorname{LN}(\widetilde{\matr{Z}}_\ell)\right).
\]</span></p>
<p>The residual stream, LayerNorm axis, multi-head routing, and position-wise MLP are unchanged. This is an encoder-only classifier, so there is no causal mask and no decoder. Pre-LayerNorm gives gradients a cleaner residual path; it does not make optimization automatic. The original ViT training recipe still used learning-rate warmup.</p>
</section>
<section id="inductive-bias-strikes-again" class="level2" data-number="16.3">
<h2 data-number="16.3" class="anchored" data-anchor-id="inductive-bias-strikes-again"><span class="header-section-number">16.3</span> Inductive bias strikes again</h2>
<p>Chapter 6 called constraints a form of knowledge. <strong>Inductive bias strikes again, this time as a trade.</strong> Convolution spends flexibility to buy locality and translation equivariance; ViT gives back much of that image-specific prior and must purchase useful geometry with data, optimization, or a new architectural constraint.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Convolutional network</th>
<th>Vision Transformer</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Local, spatially shared kernels</td>
<td>Content-dependent routes between all patch tokens</td>
</tr>
<tr class="even">
<td>Translation equivariance built into feature maps</td>
<td>Geometry supplied mainly by patches and position vectors</td>
</tr>
<tr class="odd">
<td>Global sight accumulated through depth</td>
<td>Every patch reachable in one attention layer</td>
</tr>
<tr class="even">
<td>Strong image-specific prior</td>
<td>More freedom, and greater dependence on the training regime</td>
</tr>
</tbody>
</table>
<p>“Less image-specific bias”—not “no bias”—is the precise phrase. Patchification is local, the same projection is shared over the grid, positions identify slots, and the usual optimizer and architecture choices contribute biases of their own. ViT did not remove assumptions. It changed which assumptions were paid for in code and which had to be learned from examples.</p>
<p>That freedom has a computational price. Ignoring <code>[CLS]</code> for the cleanest count, changing a <span class="math inline">\(224\times224\)</span> image from <span class="math inline">\(P=32\)</span> to <span class="math inline">\(P=16\)</span> changes the patch count from <span class="math inline">\(49\)</span> to <span class="math inline">\(196\)</span>: four times as many tokens. Each attention head’s score matrix therefore grows from <span class="math inline">\(49^2=2{,}401\)</span> to <span class="math inline">\(196^2=38{,}416\)</span> entries—sixteen times as many. At <span class="math inline">\(1024\times1024\)</span> with <span class="math inline">\(P=16\)</span>, there are 4,096 patches—and the score matrix has about 437 times as many entries as the <span class="math inline">\(224\times224\)</span> case.</p>
<p>Do not shorten this to “the whole Transformer is quadratic.” Attention mixing costs <span class="math inline">\(O(N^2d)\)</span>, while the projections and feed-forward layers contribute terms like <span class="math inline">\(O(Nd^2)\)</span>. Which term dominates depends on both token count and width. The quadratic term becomes especially painful when resolution rises or patches shrink.</p>
</section>
<section id="a-fashion-rematch-not-a-referendum" class="level2" data-number="16.4">
<h2 data-number="16.4" class="anchored" data-anchor-id="a-fashion-rematch-not-a-referendum"><span class="header-section-number">16.4</span> A Fashion rematch, not a referendum</h2>
<p>The original ViT paper warns us that regime matters. Before looking at its large pretraining experiments, let us deliberately choose the opposite regime: 1,000 Fashion-MNIST fitting images, no pretraining, and models small enough to inspect.</p>
<p>The ViT uses <span class="math inline">\(4\times4\)</span> patches, width 32, four heads, two pre-LayerNorm blocks, and feed-forward width 64. Its 49 patch tokens plus <code>[CLS]</code> make a 50-token sequence. The convolutional baseline uses four <span class="math inline">\(3\times3\)</span> layers, two max pools, and global average pooling. Their parameter counts differ by about 3%. Both use the same initialization family, optimizer, update count, seed, and explicit minibatch order.</p>
<p>The implementations below are derived independently from the chapter equations. There is no imported ViT package hiding extra training machinery.</p>
<div id="fashion-models" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code: independently define the tiny ViT and parameter-matched CNN</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> MultiHeadSelfAttention(nn.Module):</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, width: <span class="bu">int</span>, heads: <span class="bu">int</span>) <span class="op">-&gt;</span> <span class="va">None</span>:</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>        <span class="cf">assert</span> width <span class="op">%</span> heads <span class="op">==</span> <span class="dv">0</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.heads <span class="op">=</span> heads</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.head_width <span class="op">=</span> width <span class="op">//</span> heads</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.qkv <span class="op">=</span> nn.Linear(width, <span class="dv">3</span> <span class="op">*</span> width)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.proj <span class="op">=</span> nn.Linear(width, width)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x: torch.Tensor) <span class="op">-&gt;</span> torch.Tensor:</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>        batch, tokens, width <span class="op">=</span> x.shape</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>        qkv <span class="op">=</span> <span class="va">self</span>.qkv(x).reshape(</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>            batch, tokens, <span class="dv">3</span>, <span class="va">self</span>.heads, <span class="va">self</span>.head_width</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>        ).permute(<span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">4</span>)</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>        q, k, v <span class="op">=</span> qkv.unbind(<span class="dv">0</span>)</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>        scores <span class="op">=</span> (q <span class="op">@</span> k.transpose(<span class="op">-</span><span class="dv">2</span>, <span class="op">-</span><span class="dv">1</span>)) <span class="op">/</span> math.sqrt(<span class="va">self</span>.head_width)</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>        mixed <span class="op">=</span> scores.softmax(dim<span class="op">=-</span><span class="dv">1</span>) <span class="op">@</span> v</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>        mixed <span class="op">=</span> mixed.transpose(<span class="dv">1</span>, <span class="dv">2</span>).reshape(batch, tokens, width)</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">self</span>.proj(mixed)</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> EncoderBlock(nn.Module):</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, width: <span class="bu">int</span>, heads: <span class="bu">int</span>, ff_width: <span class="bu">int</span>) <span class="op">-&gt;</span> <span class="va">None</span>:</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.norm1 <span class="op">=</span> nn.LayerNorm(width)</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.attn <span class="op">=</span> MultiHeadSelfAttention(width, heads)</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.norm2 <span class="op">=</span> nn.LayerNorm(width)</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.ffn <span class="op">=</span> nn.Sequential(</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>            nn.Linear(width, ff_width), nn.GELU(), nn.Linear(ff_width, width)</span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x: torch.Tensor) <span class="op">-&gt;</span> torch.Tensor:</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> x <span class="op">+</span> <span class="va">self</span>.attn(<span class="va">self</span>.norm1(x))</span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> x <span class="op">+</span> <span class="va">self</span>.ffn(<span class="va">self</span>.norm2(x))</span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> TinyViT(nn.Module):</span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, width: <span class="bu">int</span> <span class="op">=</span> <span class="dv">32</span>, patch: <span class="bu">int</span> <span class="op">=</span> <span class="dv">4</span>, blocks: <span class="bu">int</span> <span class="op">=</span> <span class="dv">2</span>) <span class="op">-&gt;</span> <span class="va">None</span>:</span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.patch_embed <span class="op">=</span> nn.Conv2d(<span class="dv">1</span>, width, kernel_size<span class="op">=</span>patch, stride<span class="op">=</span>patch)</span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a>        patch_tokens <span class="op">=</span> (<span class="dv">28</span> <span class="op">//</span> patch) <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.cls_token <span class="op">=</span> nn.Parameter(torch.zeros(<span class="dv">1</span>, <span class="dv">1</span>, width))</span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.position <span class="op">=</span> nn.Parameter(torch.zeros(<span class="dv">1</span>, patch_tokens <span class="op">+</span> <span class="dv">1</span>, width))</span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.blocks <span class="op">=</span> nn.Sequential(<span class="op">*</span>(</span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a>            EncoderBlock(width, heads<span class="op">=</span><span class="dv">4</span>, ff_width<span class="op">=</span><span class="dv">2</span> <span class="op">*</span> width)</span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a>            <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(blocks)</span>
<span id="cb5-47"><a href="#cb5-47" aria-hidden="true" tabindex="-1"></a>        ))</span>
<span id="cb5-48"><a href="#cb5-48" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.norm <span class="op">=</span> nn.LayerNorm(width)</span>
<span id="cb5-49"><a href="#cb5-49" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.head <span class="op">=</span> nn.Linear(width, <span class="dv">10</span>)</span>
<span id="cb5-50"><a href="#cb5-50" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.<span class="bu">apply</span>(_xavier_init)</span>
<span id="cb5-51"><a href="#cb5-51" aria-hidden="true" tabindex="-1"></a>        nn.init.normal_(<span class="va">self</span>.cls_token, std<span class="op">=</span><span class="fl">0.02</span>)</span>
<span id="cb5-52"><a href="#cb5-52" aria-hidden="true" tabindex="-1"></a>        nn.init.normal_(<span class="va">self</span>.position, std<span class="op">=</span><span class="fl">0.02</span>)</span>
<span id="cb5-53"><a href="#cb5-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-54"><a href="#cb5-54" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x: torch.Tensor) <span class="op">-&gt;</span> torch.Tensor:</span>
<span id="cb5-55"><a href="#cb5-55" aria-hidden="true" tabindex="-1"></a>        patches <span class="op">=</span> <span class="va">self</span>.patch_embed(x).flatten(<span class="dv">2</span>).transpose(<span class="dv">1</span>, <span class="dv">2</span>)</span>
<span id="cb5-56"><a href="#cb5-56" aria-hidden="true" tabindex="-1"></a>        cls <span class="op">=</span> <span class="va">self</span>.cls_token.expand(<span class="bu">len</span>(x), <span class="op">-</span><span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb5-57"><a href="#cb5-57" aria-hidden="true" tabindex="-1"></a>        tokens <span class="op">=</span> torch.cat((cls, patches), dim<span class="op">=</span><span class="dv">1</span>) <span class="op">+</span> <span class="va">self</span>.position</span>
<span id="cb5-58"><a href="#cb5-58" aria-hidden="true" tabindex="-1"></a>        encoded <span class="op">=</span> <span class="va">self</span>.blocks(tokens)</span>
<span id="cb5-59"><a href="#cb5-59" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">self</span>.head(<span class="va">self</span>.norm(encoded[:, <span class="dv">0</span>]))</span>
<span id="cb5-60"><a href="#cb5-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-61"><a href="#cb5-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-62"><a href="#cb5-62" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> TinyCNN(nn.Module):</span>
<span id="cb5-63"><a href="#cb5-63" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>) <span class="op">-&gt;</span> <span class="va">None</span>:</span>
<span id="cb5-64"><a href="#cb5-64" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb5-65"><a href="#cb5-65" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.features <span class="op">=</span> nn.Sequential(</span>
<span id="cb5-66"><a href="#cb5-66" aria-hidden="true" tabindex="-1"></a>            nn.Conv2d(<span class="dv">1</span>, <span class="dv">8</span>, <span class="dv">3</span>, padding<span class="op">=</span><span class="dv">1</span>), nn.GELU(), nn.MaxPool2d(<span class="dv">2</span>),</span>
<span id="cb5-67"><a href="#cb5-67" aria-hidden="true" tabindex="-1"></a>            nn.Conv2d(<span class="dv">8</span>, <span class="dv">16</span>, <span class="dv">3</span>, padding<span class="op">=</span><span class="dv">1</span>), nn.GELU(), nn.MaxPool2d(<span class="dv">2</span>),</span>
<span id="cb5-68"><a href="#cb5-68" aria-hidden="true" tabindex="-1"></a>            nn.Conv2d(<span class="dv">16</span>, <span class="dv">32</span>, <span class="dv">3</span>, padding<span class="op">=</span><span class="dv">1</span>), nn.GELU(),</span>
<span id="cb5-69"><a href="#cb5-69" aria-hidden="true" tabindex="-1"></a>            nn.Conv2d(<span class="dv">32</span>, <span class="dv">48</span>, <span class="dv">3</span>, padding<span class="op">=</span><span class="dv">1</span>), nn.GELU(),</span>
<span id="cb5-70"><a href="#cb5-70" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb5-71"><a href="#cb5-71" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.head <span class="op">=</span> nn.Sequential(</span>
<span id="cb5-72"><a href="#cb5-72" aria-hidden="true" tabindex="-1"></a>            nn.AdaptiveAvgPool2d(<span class="dv">1</span>), nn.Flatten(), nn.Linear(<span class="dv">48</span>, <span class="dv">10</span>)</span>
<span id="cb5-73"><a href="#cb5-73" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb5-74"><a href="#cb5-74" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.<span class="bu">apply</span>(_xavier_init)</span>
<span id="cb5-75"><a href="#cb5-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-76"><a href="#cb5-76" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x: torch.Tensor) <span class="op">-&gt;</span> torch.Tensor:</span>
<span id="cb5-77"><a href="#cb5-77" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">self</span>.head(<span class="va">self</span>.features(x))</span>
<span id="cb5-78"><a href="#cb5-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-79"><a href="#cb5-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-80"><a href="#cb5-80" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> _xavier_init(module: nn.Module) <span class="op">-&gt;</span> <span class="va">None</span>:</span>
<span id="cb5-81"><a href="#cb5-81" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">isinstance</span>(module, (nn.Linear, nn.Conv2d)):</span>
<span id="cb5-82"><a href="#cb5-82" aria-hidden="true" tabindex="-1"></a>        nn.init.xavier_uniform_(module.weight)</span>
<span id="cb5-83"><a href="#cb5-83" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> module.bias <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>:</span>
<span id="cb5-84"><a href="#cb5-84" aria-hidden="true" tabindex="-1"></a>            nn.init.zeros_(module.bias)</span>
<span id="cb5-85"><a href="#cb5-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-86"><a href="#cb5-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-87"><a href="#cb5-87" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> count_parameters(model: nn.Module) <span class="op">-&gt;</span> <span class="bu">int</span>:</span>
<span id="cb5-88"><a href="#cb5-88" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="bu">sum</span>(parameter.numel() <span class="cf">for</span> parameter <span class="kw">in</span> model.parameters())</span>
<span id="cb5-89"><a href="#cb5-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-90"><a href="#cb5-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-91"><a href="#cb5-91" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"CNN parameters:"</span>, <span class="ss">f"</span><span class="sc">{</span>count_parameters(TinyCNN())<span class="sc">:,}</span><span class="ss">"</span>)</span>
<span id="cb5-92"><a href="#cb5-92" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"ViT parameters:"</span>, <span class="ss">f"</span><span class="sc">{</span>count_parameters(TinyViT())<span class="sc">:,}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>CNN parameters: 20,250
ViT parameters: 19,658</code></pre>
</div>
</div>
<p>For one <span class="math inline">\(28\times28\)</span> image, a simple multiply–accumulate ledger gives about 1.19 million for the CNN and 1.16 million for the ViT, a 1.8% difference. That ledger counts convolution, linear, and attention matrix products; it omits normalization, activations, softmax, pooling, memory traffic, and implementation effects. It is a useful dot-product proxy—not measured FLOPs, speed, or energy. <a href="../appendices/a3-precision-performance.html" class="quarto-xref"><span>Appendix C</span></a> supplies the missing byte ledger and Roofline model, including why neither an operation count nor a dtype alone predicts elapsed time.</p>
<p>The training protocol uses AdamW for 120 epochs, a cosine learning-rate schedule, and batches of 100. For each seed, one explicit list of permutations is handed to both architectures. Resetting the seed before each model makes initialization reproducible; sharing the permutation list makes minibatch order exactly equal. The schedule hash makes that equality inspectable rather than aspirational.</p>
<div id="fashion-protocol" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code: define the explicit paired schedule, training loop, and shift audit</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>EPOCHS <span class="op">=</span> <span class="dv">120</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>SEEDS <span class="op">=</span> <span class="bu">list</span>(<span class="bu">range</span>(<span class="dv">6050</span>, <span class="dv">6055</span>))</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> minibatch_schedule(seed: <span class="bu">int</span>) <span class="op">-&gt;</span> <span class="bu">list</span>[torch.Tensor]:</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    generator <span class="op">=</span> torch.Generator().manual_seed(seed <span class="op">+</span> <span class="dv">10_000</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> [torch.randperm(<span class="bu">len</span>(X_fit), generator<span class="op">=</span>generator) <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(EPOCHS)]</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> schedule_hash(permutations: <span class="bu">list</span>[torch.Tensor]) <span class="op">-&gt;</span> <span class="bu">str</span>:</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    raw <span class="op">=</span> torch.cat(permutations).numpy().tobytes()</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> hashlib.sha256(raw).hexdigest()[:<span class="dv">12</span>]</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> train_with_schedule(</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>    model_fn, permutations: <span class="bu">list</span>[torch.Tensor], seed: <span class="bu">int</span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>) <span class="op">-&gt;</span> nn.Module:</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>    torch.manual_seed(seed)</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>    model <span class="op">=</span> model_fn()</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>    optimizer <span class="op">=</span> torch.optim.AdamW(model.parameters(), lr<span class="op">=</span><span class="fl">3e-3</span>, weight_decay<span class="op">=</span><span class="fl">1e-2</span>)</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>    scheduler <span class="op">=</span> torch.optim.lr_scheduler.CosineAnnealingLR(</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>        optimizer, T_max<span class="op">=</span>EPOCHS, eta_min<span class="op">=</span><span class="fl">3e-5</span></span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>    model.train()</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> permutation <span class="kw">in</span> permutations:</span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> start <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>, <span class="bu">len</span>(X_fit), <span class="dv">100</span>):</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>            idx <span class="op">=</span> permutation[start:start <span class="op">+</span> <span class="dv">100</span>]</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a>            loss <span class="op">=</span> F.cross_entropy(model(X_fit[idx]), y_fit[idx])</span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>            optimizer.zero_grad()</span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a>            loss.backward()</span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>            optimizer.step()</span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a>        scheduler.step()</span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> model</span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-36"><a href="#cb7-36" aria-hidden="true" tabindex="-1"></a><span class="at">@torch.no_grad</span>()</span>
<span id="cb7-37"><a href="#cb7-37" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> accuracy(model: nn.Module, x: torch.Tensor, y: torch.Tensor) <span class="op">-&gt;</span> <span class="bu">float</span>:</span>
<span id="cb7-38"><a href="#cb7-38" aria-hidden="true" tabindex="-1"></a>    model.<span class="bu">eval</span>()</span>
<span id="cb7-39"><a href="#cb7-39" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (model(x).argmax(<span class="dv">1</span>) <span class="op">==</span> y).<span class="bu">float</span>().mean().item()</span>
<span id="cb7-40"><a href="#cb7-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-41"><a href="#cb7-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-42"><a href="#cb7-42" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> shift_right(x: torch.Tensor, pixels: <span class="bu">int</span>) <span class="op">-&gt;</span> torch.Tensor:</span>
<span id="cb7-43"><a href="#cb7-43" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> pixels <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb7-44"><a href="#cb7-44" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> x.clone()</span>
<span id="cb7-45"><a href="#cb7-45" aria-hidden="true" tabindex="-1"></a>    shifted <span class="op">=</span> torch.zeros_like(x)</span>
<span id="cb7-46"><a href="#cb7-46" aria-hidden="true" tabindex="-1"></a>    shifted[..., pixels:] <span class="op">=</span> x[..., :<span class="op">-</span>pixels]</span>
<span id="cb7-47"><a href="#cb7-47" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> shifted</span>
<span id="cb7-48"><a href="#cb7-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-49"><a href="#cb7-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-50"><a href="#cb7-50" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> run_paired_seed(seed: <span class="bu">int</span>) <span class="op">-&gt;</span> <span class="bu">list</span>[<span class="bu">dict</span>]:</span>
<span id="cb7-51"><a href="#cb7-51" aria-hidden="true" tabindex="-1"></a>    permutations <span class="op">=</span> minibatch_schedule(seed)</span>
<span id="cb7-52"><a href="#cb7-52" aria-hidden="true" tabindex="-1"></a>    rows <span class="op">=</span> []</span>
<span id="cb7-53"><a href="#cb7-53" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"seed </span><span class="sc">{</span>seed<span class="sc">}</span><span class="ss">, schedule </span><span class="sc">{</span>schedule_hash(permutations)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb7-54"><a href="#cb7-54" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> name, model_fn <span class="kw">in</span> ((<span class="st">"CNN"</span>, TinyCNN), (<span class="st">"ViT"</span>, TinyViT)):</span>
<span id="cb7-55"><a href="#cb7-55" aria-hidden="true" tabindex="-1"></a>        model <span class="op">=</span> train_with_schedule(model_fn, permutations, seed)</span>
<span id="cb7-56"><a href="#cb7-56" aria-hidden="true" tabindex="-1"></a>        row <span class="op">=</span> {</span>
<span id="cb7-57"><a href="#cb7-57" aria-hidden="true" tabindex="-1"></a>            <span class="st">"seed"</span>: seed,</span>
<span id="cb7-58"><a href="#cb7-58" aria-hidden="true" tabindex="-1"></a>            <span class="st">"model"</span>: name,</span>
<span id="cb7-59"><a href="#cb7-59" aria-hidden="true" tabindex="-1"></a>            <span class="st">"train"</span>: accuracy(model, X_fit, y_fit),</span>
<span id="cb7-60"><a href="#cb7-60" aria-hidden="true" tabindex="-1"></a>            <span class="st">"validation"</span>: [</span>
<span id="cb7-61"><a href="#cb7-61" aria-hidden="true" tabindex="-1"></a>                accuracy(model, shift_right(X_val, px), y_val) <span class="cf">for</span> px <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">5</span>)</span>
<span id="cb7-62"><a href="#cb7-62" aria-hidden="true" tabindex="-1"></a>            ],</span>
<span id="cb7-63"><a href="#cb7-63" aria-hidden="true" tabindex="-1"></a>            <span class="st">"benchmark"</span>: accuracy(model, X_test, y_test),</span>
<span id="cb7-64"><a href="#cb7-64" aria-hidden="true" tabindex="-1"></a>        }</span>
<span id="cb7-65"><a href="#cb7-65" aria-hidden="true" tabindex="-1"></a>        rows.append(row)</span>
<span id="cb7-66"><a href="#cb7-66" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(</span>
<span id="cb7-67"><a href="#cb7-67" aria-hidden="true" tabindex="-1"></a>            <span class="ss">f"  </span><span class="sc">{</span>name<span class="sc">}</span><span class="ss">: train </span><span class="sc">{</span>row[<span class="st">'train'</span>]<span class="sc">:.3f}</span><span class="ss">, "</span></span>
<span id="cb7-68"><a href="#cb7-68" aria-hidden="true" tabindex="-1"></a>            <span class="ss">f"validation </span><span class="sc">{</span>[<span class="bu">round</span>(value, <span class="dv">3</span>) <span class="cf">for</span> value <span class="kw">in</span> row[<span class="st">'validation'</span>]]<span class="sc">}</span><span class="ss">, "</span></span>
<span id="cb7-69"><a href="#cb7-69" aria-hidden="true" tabindex="-1"></a>            <span class="ss">f"benchmark </span><span class="sc">{</span>row[<span class="st">'benchmark'</span>]<span class="sc">:.3f}</span><span class="ss">"</span></span>
<span id="cb7-70"><a href="#cb7-70" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb7-71"><a href="#cb7-71" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> rows</span>
<span id="cb7-72"><a href="#cb7-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-73"><a href="#cb7-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-74"><a href="#cb7-74" aria-hidden="true" tabindex="-1"></a>vit_macs <span class="op">=</span> (</span>
<span id="cb7-75"><a href="#cb7-75" aria-hidden="true" tabindex="-1"></a>    <span class="dv">7</span> <span class="op">*</span> <span class="dv">7</span> <span class="op">*</span> <span class="dv">32</span> <span class="op">*</span> <span class="dv">16</span></span>
<span id="cb7-76"><a href="#cb7-76" aria-hidden="true" tabindex="-1"></a>    <span class="op">+</span> <span class="dv">2</span> <span class="op">*</span> (</span>
<span id="cb7-77"><a href="#cb7-77" aria-hidden="true" tabindex="-1"></a>        <span class="dv">50</span> <span class="op">*</span> <span class="dv">32</span> <span class="op">*</span> (<span class="dv">3</span> <span class="op">*</span> <span class="dv">32</span>) <span class="op">+</span> <span class="dv">2</span> <span class="op">*</span> <span class="dv">4</span> <span class="op">*</span> <span class="dv">50</span> <span class="op">*</span> <span class="dv">50</span> <span class="op">*</span> <span class="dv">8</span></span>
<span id="cb7-78"><a href="#cb7-78" aria-hidden="true" tabindex="-1"></a>        <span class="op">+</span> <span class="dv">50</span> <span class="op">*</span> <span class="dv">32</span> <span class="op">*</span> <span class="dv">32</span> <span class="op">+</span> <span class="dv">2</span> <span class="op">*</span> <span class="dv">50</span> <span class="op">*</span> <span class="dv">32</span> <span class="op">*</span> <span class="dv">64</span></span>
<span id="cb7-79"><a href="#cb7-79" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb7-80"><a href="#cb7-80" aria-hidden="true" tabindex="-1"></a>    <span class="op">+</span> <span class="dv">32</span> <span class="op">*</span> <span class="dv">10</span></span>
<span id="cb7-81"><a href="#cb7-81" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-82"><a href="#cb7-82" aria-hidden="true" tabindex="-1"></a>cnn_macs <span class="op">=</span> (</span>
<span id="cb7-83"><a href="#cb7-83" aria-hidden="true" tabindex="-1"></a>    <span class="dv">28</span> <span class="op">*</span> <span class="dv">28</span> <span class="op">*</span> <span class="dv">8</span> <span class="op">*</span> <span class="dv">1</span> <span class="op">*</span> <span class="dv">3</span> <span class="op">*</span> <span class="dv">3</span></span>
<span id="cb7-84"><a href="#cb7-84" aria-hidden="true" tabindex="-1"></a>    <span class="op">+</span> <span class="dv">14</span> <span class="op">*</span> <span class="dv">14</span> <span class="op">*</span> <span class="dv">16</span> <span class="op">*</span> <span class="dv">8</span> <span class="op">*</span> <span class="dv">3</span> <span class="op">*</span> <span class="dv">3</span></span>
<span id="cb7-85"><a href="#cb7-85" aria-hidden="true" tabindex="-1"></a>    <span class="op">+</span> <span class="dv">7</span> <span class="op">*</span> <span class="dv">7</span> <span class="op">*</span> <span class="dv">32</span> <span class="op">*</span> <span class="dv">16</span> <span class="op">*</span> <span class="dv">3</span> <span class="op">*</span> <span class="dv">3</span></span>
<span id="cb7-86"><a href="#cb7-86" aria-hidden="true" tabindex="-1"></a>    <span class="op">+</span> <span class="dv">7</span> <span class="op">*</span> <span class="dv">7</span> <span class="op">*</span> <span class="dv">48</span> <span class="op">*</span> <span class="dv">32</span> <span class="op">*</span> <span class="dv">3</span> <span class="op">*</span> <span class="dv">3</span></span>
<span id="cb7-87"><a href="#cb7-87" aria-hidden="true" tabindex="-1"></a>    <span class="op">+</span> <span class="dv">48</span> <span class="op">*</span> <span class="dv">10</span></span>
<span id="cb7-88"><a href="#cb7-88" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-89"><a href="#cb7-89" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"dot-product/MAC proxy — CNN: </span><span class="sc">{</span>cnn_macs<span class="sc">:,}</span><span class="ss">; ViT: </span><span class="sc">{</span>vit_macs<span class="sc">:,}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>dot-product/MAC proxy — CNN: 1,185,888; ViT: 1,164,608</code></pre>
</div>
</div>
<p>The five paired runs use one cell per seed so that each training cell stays within the chapter’s execution budget. The split is only operational—all five rows enter one analysis.</p>
<div id="train-fashion-6050" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Training code: paired Fashion run for seed 6050</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>fashion_results <span class="op">=</span> []</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>fashion_results.extend(run_paired_seed(<span class="dv">6050</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>seed 6050, schedule c42c1c2b4baf
  CNN: train 0.886, validation [0.73, 0.69, 0.68, 0.685, 0.56], benchmark 0.780
  ViT: train 1.000, validation [0.69, 0.61, 0.48, 0.37, 0.225], benchmark 0.720</code></pre>
</div>
</div>
<div id="train-fashion-6051" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Training code: paired Fashion run for seed 6051</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>fashion_results.extend(run_paired_seed(<span class="dv">6051</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>seed 6051, schedule f0c73c85e0e3
  CNN: train 0.854, validation [0.755, 0.7, 0.695, 0.705, 0.61], benchmark 0.768
  ViT: train 1.000, validation [0.705, 0.575, 0.445, 0.29, 0.21], benchmark 0.735</code></pre>
</div>
</div>
<div id="train-fashion-6052" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Training code: paired Fashion run for seed 6052</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>fashion_results.extend(run_paired_seed(<span class="dv">6052</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>seed 6052, schedule 20ec620b3e2e
  CNN: train 0.877, validation [0.745, 0.715, 0.685, 0.695, 0.665], benchmark 0.780
  ViT: train 1.000, validation [0.72, 0.635, 0.455, 0.33, 0.23], benchmark 0.743</code></pre>
</div>
</div>
<div id="train-fashion-6053" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Training code: paired Fashion run for seed 6053</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>fashion_results.extend(run_paired_seed(<span class="dv">6053</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>seed 6053, schedule c93bd2a03038
  CNN: train 0.883, validation [0.745, 0.675, 0.625, 0.56, 0.48], benchmark 0.790
  ViT: train 1.000, validation [0.69, 0.615, 0.41, 0.395, 0.23], benchmark 0.723</code></pre>
</div>
</div>
<div id="train-fashion-6054" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>Training code: paired Fashion run for seed 6054</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>fashion_results.extend(run_paired_seed(<span class="dv">6054</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>seed 6054, schedule 87a781e7efa8
  CNN: train 0.894, validation [0.72, 0.715, 0.69, 0.64, 0.63], benchmark 0.778
  ViT: train 1.000, validation [0.7, 0.585, 0.495, 0.395, 0.365], benchmark 0.745</code></pre>
</div>
</div>
<div id="cell-fig-fashion-rematch" class="cell" data-fig-height="3.7" data-fig-width="10" data-execution_count="10">
<details class="code-fold">
<summary>Figure code: show every paired clean result and every shift curve</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>by_model <span class="op">=</span> {</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>    name: [row <span class="cf">for</span> row <span class="kw">in</span> fashion_results <span class="cf">if</span> row[<span class="st">"model"</span>] <span class="op">==</span> name]</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> name <span class="kw">in</span> (<span class="st">"CNN"</span>, <span class="st">"ViT"</span>)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name <span class="kw">in</span> by_model:</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">assert</span> [row[<span class="st">"seed"</span>] <span class="cf">for</span> row <span class="kw">in</span> by_model[name]] <span class="op">==</span> SEEDS</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>colors <span class="op">=</span> {<span class="st">"CNN"</span>: <span class="st">"#232D4B"</span>, <span class="st">"ViT"</span>: <span class="st">"#E57200"</span>}</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="fl">3.7</span>),</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>                         gridspec_kw<span class="op">=</span>{<span class="st">"width_ratios"</span>: [<span class="fl">0.8</span>, <span class="fl">1.35</span>]})</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> index, seed <span class="kw">in</span> <span class="bu">enumerate</span>(SEEDS):</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>    pair <span class="op">=</span> [</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>        by_model[<span class="st">"CNN"</span>][index][<span class="st">"validation"</span>][<span class="dv">0</span>],</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>        by_model[<span class="st">"ViT"</span>][index][<span class="st">"validation"</span>][<span class="dv">0</span>],</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>    ]</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">0</span>].plot([<span class="dv">0</span>, <span class="dv">1</span>], pair, <span class="st">"o-"</span>, color<span class="op">=</span><span class="st">"#8A8A7A"</span>, alpha<span class="op">=</span><span class="fl">0.75</span>, lw<span class="op">=</span><span class="fl">1.3</span>)</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xticks([<span class="dv">0</span>, <span class="dv">1</span>], [<span class="st">"CNN"</span>, <span class="st">"ViT"</span>])</span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"clean validation accuracy"</span>)</span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">"each line is one paired seed"</span>)</span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>shifts <span class="op">=</span> np.arange(<span class="dv">5</span>)</span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name <span class="kw">in</span> (<span class="st">"CNN"</span>, <span class="st">"ViT"</span>):</span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a>    curves <span class="op">=</span> np.array([row[<span class="st">"validation"</span>] <span class="cf">for</span> row <span class="kw">in</span> by_model[name]])</span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> curve <span class="kw">in</span> curves:</span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a>        axes[<span class="dv">1</span>].plot(shifts, curve, color<span class="op">=</span>colors[name], alpha<span class="op">=</span><span class="fl">0.2</span>, lw<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">1</span>].plot(shifts, curves.mean(<span class="dv">0</span>), <span class="st">"o-"</span>, color<span class="op">=</span>colors[name],</span>
<span id="cb19-29"><a href="#cb19-29" aria-hidden="true" tabindex="-1"></a>                 lw<span class="op">=</span><span class="fl">2.6</span>, ms<span class="op">=</span><span class="dv">6</span>, label<span class="op">=</span><span class="ss">f"</span><span class="sc">{</span>name<span class="sc">}</span><span class="ss"> mean"</span>)</span>
<span id="cb19-30"><a href="#cb19-30" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].axhline(<span class="fl">0.1</span>, color<span class="op">=</span><span class="st">"#B8B8A8"</span>, ls<span class="op">=</span><span class="st">":"</span>, lw<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb19-31"><a href="#cb19-31" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xticks(shifts)</span>
<span id="cb19-32"><a href="#cb19-32" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xlabel(<span class="st">"pixels shifted right"</span>)</span>
<span id="cb19-33"><a href="#cb19-33" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_ylabel(<span class="st">"validation accuracy"</span>)</span>
<span id="cb19-34"><a href="#cb19-34" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">"same fitted models under shift"</span>)</span>
<span id="cb19-35"><a href="#cb19-35" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].legend(frameon<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb19-36"><a href="#cb19-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-37"><a href="#cb19-37" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> axis <span class="kw">in</span> axes:</span>
<span id="cb19-38"><a href="#cb19-38" aria-hidden="true" tabindex="-1"></a>    axis.set_ylim(<span class="fl">0.15</span>, <span class="fl">0.82</span>)</span>
<span id="cb19-39"><a href="#cb19-39" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb19-40"><a href="#cb19-40" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb19-41"><a href="#cb19-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-42"><a href="#cb19-42" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name <span class="kw">in</span> (<span class="st">"CNN"</span>, <span class="st">"ViT"</span>):</span>
<span id="cb19-43"><a href="#cb19-43" aria-hidden="true" tabindex="-1"></a>    rows <span class="op">=</span> by_model[name]</span>
<span id="cb19-44"><a href="#cb19-44" aria-hidden="true" tabindex="-1"></a>    mean_train <span class="op">=</span> np.mean([row[<span class="st">"train"</span>] <span class="cf">for</span> row <span class="kw">in</span> rows])</span>
<span id="cb19-45"><a href="#cb19-45" aria-hidden="true" tabindex="-1"></a>    mean_val <span class="op">=</span> np.mean([row[<span class="st">"validation"</span>][<span class="dv">0</span>] <span class="cf">for</span> row <span class="kw">in</span> rows])</span>
<span id="cb19-46"><a href="#cb19-46" aria-hidden="true" tabindex="-1"></a>    mean_test <span class="op">=</span> np.mean([row[<span class="st">"benchmark"</span>] <span class="cf">for</span> row <span class="kw">in</span> rows])</span>
<span id="cb19-47"><a href="#cb19-47" aria-hidden="true" tabindex="-1"></a>    mean_shift4 <span class="op">=</span> np.mean([row[<span class="st">"validation"</span>][<span class="dv">4</span>] <span class="cf">for</span> row <span class="kw">in</span> rows])</span>
<span id="cb19-48"><a href="#cb19-48" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(</span>
<span id="cb19-49"><a href="#cb19-49" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>name<span class="sc">}</span><span class="ss">: train </span><span class="sc">{</span>mean_train<span class="sc">:.1%}</span><span class="ss">; clean validation </span><span class="sc">{</span>mean_val<span class="sc">:.1%}</span><span class="ss">; "</span></span>
<span id="cb19-50"><a href="#cb19-50" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"benchmark </span><span class="sc">{</span>mean_test<span class="sc">:.1%}</span><span class="ss">; validation at 4px </span><span class="sc">{</span>mean_shift4<span class="sc">:.1%}</span><span class="ss">"</span></span>
<span id="cb19-51"><a href="#cb19-51" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-fashion-rematch" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Five paired lines in the left panel all place CNN clean validation accuracy above ViT accuracy. In the right panel, individual and mean shift curves fall for both models, but the CNN mean remains higher and declines more slowly.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fashion-rematch-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="16-vit-scaling_files/figure-html/fig-fashion-rematch-output-1.png" alt="Five paired lines in the left panel all place CNN clean validation accuracy above ViT accuracy. In the right panel, individual and mean shift curves fall for both models, but the CNN mean remains higher and declines more slowly." width="951" height="345" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fashion-rematch-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16.2: Five parameter- and schedule-matched runs on the fixed Chapter 6 split. Every line at left is one paired clean-validation comparison. At right, thin lines are individual seeds and thick lines are means under zero-padded right shifts; the operation also clips pixels at the right boundary. The CNN’s flatter curve is consistent with its local sharing and pooling, not a causal isolation of any one component.
</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>CNN: train 87.9%; clean validation 73.9%; benchmark 77.9%; validation at 4px 58.9%
ViT: train 100.0%; clean validation 70.1%; benchmark 73.3%; validation at 4px 25.2%</code></pre>
</div>
</div>
<p>The result is sharper than a one-number leaderboard—it separates fitting from generalization. The ViT interpolates the fitting set in every run—100.0% mean training accuracy—but averages 70.1% on clean validation images. The CNN fits only 87.9% of the training labels under the shared recipe yet averages 73.9% on validation, winning all five paired comparisons. On the already-opened 600-image benchmark, the same means are 73.3% and 77.9%.</p>
<p>Under a four-pixel shift, the validation means separate much more: 25.2% for ViT and 58.9% for CNN. The zero-filled shift also clips garment content—a reminder that the right edge is lost—so neither curve measures pure translation equivariance. Still, the contrast is consistent across the five fitted pairs with what Chapters 7–9 built into the CNN: local sharing, pooling, and a position-discarding global-average head.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Trap: a rematch is a regime, not a referendum
</div>
</div>
<div class="callout-body-container callout-body">
<p>These runs match the data split, parameter scale, optimizer, update count, minibatch order, and seeds. Their dot-product ledgers are close as well. They do <strong>not</strong> match architecture-specific tuning, every operation, wall-clock cost, or pretraining. The five runs vary initialization and order while holding one split fixed, so they are not population uncertainty estimates. The 600-image benchmark was opened in earlier chapters and is descriptive, not a fresh final test. This experiment tells us what happened here; it does not rank CNNs and ViTs in general.</p>
</div>
</div>
</section>
<section id="scale-changes-the-comparison" class="level2" data-number="16.5">
<h2 data-number="16.5" class="anchored" data-anchor-id="scale-changes-the-comparison"><span class="header-section-number">16.5</span> Scale changes the comparison</h2>
<p>Now harvest Chapter 15’s second promise: <strong>pretraining is a regime, not an architecture</strong>. ViT keeps the encoder pattern but changes the tokens, source data, and task. In the original work, the decisive source task was supervised image classification—not BERT-style masked prediction—and the amount of source data changed the comparison.</p>
<p>The authors pretrained matched families on random subsets of JFT containing 9, 30, and 90 million images, plus the full 300-million-image dataset. These are four measured regimes—not points on a smooth curve we are free to invent. ViT-B/32 was slightly faster than the compared ResNet-50, performed much worse on the 9-million subset, and performed better at 90 million images and above. The analogous ViT-L/16 versus larger ResNet comparison followed the same regime change.</p>
<p>That does not prove “attention scales forever” or that data erases every useful prior. It demonstrates the narrower—and more valuable—point: the architecture ranking can reverse when the training regime changes. Our 1,000-example scratch run and the paper’s large-source-pretraining run answer different questions.</p>
<section id="three-places-to-buy-back-useful-bias" class="level3">
<h3 class="anchored" data-anchor-id="three-places-to-buy-back-useful-bias">Three places to buy back useful bias</h3>
<p>Pure global attention is not the only possible endpoint. Later designs put useful image structure back in at different places.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Where the prior enters</th>
<th>Example</th>
<th>What changes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Input</td>
<td>Hybrid CNN–ViT</td>
<td>A convolutional stem creates local feature tokens before global routing</td>
</tr>
<tr class="even">
<td>Routing</td>
<td>Swin Transformer</td>
<td>Shifted local windows and a hierarchy constrain attention and control resolution cost</td>
</tr>
<tr class="odd">
<td>Training signal</td>
<td>DeiT</td>
<td>Strong augmentation and a convolutional teacher improve data efficiency without changing the student’s basic patch encoder</td>
</tr>
</tbody>
</table>
<p>DeiT makes a particularly human point. A teacher provides another target, but it does not replace the ground-truth label. Students can become better than the instructor: they listen, see other evidence, and decide for themselves. In DeiT’s hard-distillation version, a distillation token learns from the teacher’s predicted class while <code>[CLS]</code> learns from the true class; the two heads are combined at inference. The teacher changes supervision, not the identity of the student.</p>
<p>ConvNeXt prevents a lazy conclusion in the opposite direction. Its study first modernized the training recipe, then progressively changed a ResNet toward design choices associated with contemporary Transformers. The training recipe alone raised the reported ResNet-50 ImageNet-1K accuracy from 76.1% to 78.8% before the architectural sequence was complete. Architecture, augmentation, optimization, and data interact—“CNN versus Transformer” is rarely a comparison between two isolated operators.</p>
</section>
</section>
<section id="the-word-scaling-changes-jobs" class="level2" data-number="16.6">
<h2 data-number="16.6" class="anchored" data-anchor-id="the-word-scaling-changes-jobs"><span class="header-section-number">16.6</span> The word “scaling” changes jobs</h2>
<p>We have now used <em>scaling</em> in two different ways. EfficientNet asks how to enlarge one architecture family under a compute multiplier. Kaplan and Chinchilla ask how measured loss changes as parameters, data, and training compute grow. One is a design rule; the other is an empirical forecast.</p>
<section id="compound-scaling-three-knobs-one-budget" class="level3">
<h3 class="anchored" data-anchor-id="compound-scaling-three-knobs-one-budget">Compound scaling: three knobs, one budget</h3>
<p>Suppose a baseline convolutional network has depth <span class="math inline">\(d_0\)</span>, channel width <span class="math inline">\(w_0\)</span>, and input resolution <span class="math inline">\(r_0\)</span>. Scaling just one knob creates a bottleneck elsewhere—a deeper network still sees the same pixels, a wider network still has the same receptive-field schedule, and higher resolution asks an unchanged feature extractor to digest more detail. EfficientNet couples the knobs with one coefficient <span class="math inline">\(\phi\)</span>:</p>
<p><span id="eq-compound-scaling"><span class="math display">\[
d_\phi=d_0\alpha^\phi,\qquad
w_\phi=w_0\beta^\phi,\qquad
r_\phi=r_0\gamma^\phi.
\tag{16.3}\]</span></span></p>
<p>For ordinary dense convolutions, the leading operation count scales roughly as</p>
<p><span class="math display">\[
\operatorname{FLOPs}\propto d\,w^2r^2.
\]</span></p>
<p>Therefore one step in <span class="math inline">\(\phi\)</span> multiplies the proxy by</p>
<p><span id="eq-efficientnet-constraint"><span class="math display">\[
\alpha\beta^2\gamma^2\approx2.
\tag{16.4}\]</span></span></p>
<p>EfficientNet’s grid search on its baseline found approximately <span class="math inline">\(\alpha=1.2\)</span>, <span class="math inline">\(\beta=1.1\)</span>, and <span class="math inline">\(\gamma=1.15\)</span>. Their product is 1.92027—not exactly two, but close enough to serve as the intended budget step.</p>
<div id="cell-fig-compound-scaling" class="cell" data-fig-height="3.8" data-fig-width="8.5" data-execution_count="11">
<details class="code-fold">
<summary>Figure code: audit the EfficientNet compound-scaling constraint</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>alpha, beta, gamma <span class="op">=</span> <span class="fl">1.2</span>, <span class="fl">1.1</span>, <span class="fl">1.15</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>phis <span class="op">=</span> np.arange(<span class="dv">5</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>depth_multiplier <span class="op">=</span> alpha <span class="op">**</span> phis</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>width_multiplier <span class="op">=</span> beta <span class="op">**</span> phis</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>resolution_multiplier <span class="op">=</span> gamma <span class="op">**</span> phis</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>compute_multiplier <span class="op">=</span> (alpha <span class="op">*</span> beta<span class="op">**</span><span class="dv">2</span> <span class="op">*</span> gamma<span class="op">**</span><span class="dv">2</span>) <span class="op">**</span> phis</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"alpha * beta^2 * gamma^2 = </span><span class="sc">{</span>alpha <span class="op">*</span> beta<span class="op">**</span><span class="dv">2</span> <span class="op">*</span> gamma<span class="op">**</span><span class="dv">2</span><span class="sc">:.5f}</span><span class="ss">"</span>)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="fl">8.5</span>, <span class="fl">3.8</span>))</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> values, label, color <span class="kw">in</span> [</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>    (depth_multiplier, <span class="st">"depth"</span>, <span class="st">"#232D4B"</span>),</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>    (width_multiplier, <span class="st">"width"</span>, <span class="st">"#E57200"</span>),</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>    (resolution_multiplier, <span class="st">"resolution"</span>, <span class="st">"#2E7D32"</span>),</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>]:</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">0</span>].plot(phis, values, <span class="st">"o-"</span>, lw<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span>label, color<span class="op">=</span>color)</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xlabel(<span class="st">"compound coefficient $</span><span class="ch">\\</span><span class="st">phi$"</span>)</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"multiplier over baseline"</span>)</span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xticks(phis)</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].legend(frameon<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">"three coupled architecture knobs"</span>)</span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].plot(phis, compute_multiplier, <span class="st">"o-"</span>, color<span class="op">=</span><span class="st">"#722F37"</span>, lw<span class="op">=</span><span class="fl">2.5</span>)</span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> phi, value <span class="kw">in</span> <span class="bu">zip</span>(phis, compute_multiplier):</span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">1</span>].text(phi, value <span class="op">*</span> <span class="fl">1.06</span>, <span class="ss">f"</span><span class="sc">{</span>value<span class="sc">:.2f}</span><span class="ss">×"</span>, ha<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_yscale(<span class="st">"log"</span>, base<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_ylim(<span class="fl">0.85</span>, compute_multiplier.<span class="bu">max</span>() <span class="op">*</span> <span class="fl">1.18</span>)</span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xlabel(<span class="st">"compound coefficient $</span><span class="ch">\\</span><span class="st">phi$"</span>)</span>
<span id="cb21-29"><a href="#cb21-29" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_ylabel(<span class="st">"operation proxy (log base 2)"</span>)</span>
<span id="cb21-30"><a href="#cb21-30" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xticks(phis)</span>
<span id="cb21-31"><a href="#cb21-31" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">"the budget grows with them"</span>)</span>
<span id="cb21-32"><a href="#cb21-32" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb21-33"><a href="#cb21-33" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>alpha * beta^2 * gamma^2 = 1.92027</code></pre>
</div>
<div class="cell-output cell-output-display">
<div id="fig-compound-scaling" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Depth, width, and resolution multipliers all rise modestly with the compound coefficient in the left panel. Their combined operation proxy rises much faster in the right panel, nearly doubling at each step.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-compound-scaling-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="16-vit-scaling_files/figure-html/fig-compound-scaling-output-2.png" alt="Depth, width, and resolution multipliers all rise modestly with the compound coefficient in the left panel. Their combined operation proxy rises much faster in the right panel, nearly doubling at each step." width="804" height="355" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-compound-scaling-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16.3: EfficientNet’s published compound multipliers. Each step in φ grows depth, width, and resolution modestly; their approximate convolutional-operation proxy grows by 1.92027 per step. These are normalized design multipliers, not measured accuracy or runtime.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The constants are an empirical design choice from a particular search and model family, not a law that every network must obey. The durable lesson is the budget discipline—when several resources jointly limit performance, scaling one while freezing the others can spend compute badly.</p>
</section>
</section>
<section id="a-fitted-power-law-not-a-promise" class="level2" data-number="16.7">
<h2 data-number="16.7" class="anchored" data-anchor-id="a-fitted-power-law-not-a-promise"><span class="header-section-number">16.7</span> A fitted power law, not a promise</h2>
<p>Kaplan and colleagues asked a different question about decoder-only language models. Holding other resources out of the way, how does test cross-entropy <span class="math inline">\(L\)</span> change with non-embedding parameters <span class="math inline">\(N\)</span>, dataset tokens <span class="math inline">\(D\)</span>, or compute-optimally allocated training compute <span class="math inline">\(C_{\min}\)</span>? Across their measured regime, the answer was well described by power laws:</p>
<p><span class="math display">\[
L(N)=\left(\frac{N_c}{N}\right)^{\alpha_N},
\qquad \alpha_N\approx0.076,
\]</span></p>
<p><span class="math display">\[
L(D)=\left(\frac{D_c}{D}\right)^{\alpha_D},
\qquad \alpha_D\approx0.095,
\]</span></p>
<p><span class="math display">\[
L(C_{\min})=
\left(\frac{C_c}{C_{\min}}\right)^{\alpha_C},
\qquad \alpha_C\approx0.050.
\]</span></p>
<p>Here <span class="math inline">\(N_c,D_c,C_c\)</span> are fitted scale constants. Their values depend on the data, tokenizer, vocabulary, loss definition, and compute units—the small exponents are the more portable description of diminishing returns. These are conditional fits. The parameter curve assumes data is not the bottleneck, and the data curve assumes model capacity is not the bottleneck.</p>
<p>A power law becomes a straight line after taking logs:</p>
<p><span class="math display">\[
\log L=\log K-\alpha\log x.
\]</span></p>
<p>That makes extrapolation visually tempting: fit a line—extend it—and read a future loss. But a straight line on transformed axes does not repeal the conditions that produced it.</p>
<div id="cell-fig-kaplan-scaling" class="cell" data-fig-height="4" data-fig-width="8.5" data-execution_count="12">
<details class="code-fold">
<summary>Figure code: turn the published Kaplan exponents into auditable multipliers</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>scales <span class="op">=</span> np.logspace(<span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">200</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>kaplan_exponents <span class="op">=</span> {</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"parameters, $</span><span class="ch">\\</span><span class="st">alpha=0.076$"</span>: (<span class="fl">0.076</span>, <span class="st">"#232D4B"</span>),</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"tokens, $</span><span class="ch">\\</span><span class="st">alpha=0.095$"</span>: (<span class="fl">0.095</span>, <span class="st">"#E57200"</span>),</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"optimal compute, $</span><span class="ch">\\</span><span class="st">alpha=0.050$"</span>: (<span class="fl">0.050</span>, <span class="st">"#2E7D32"</span>),</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">8.5</span>, <span class="dv">4</span>))</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> label, (exponent, color) <span class="kw">in</span> kaplan_exponents.items():</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>    normalized <span class="op">=</span> scales <span class="op">**</span> (<span class="op">-</span>exponent)</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>    ax.loglog(scales, normalized, lw<span class="op">=</span><span class="fl">2.4</span>, color<span class="op">=</span>color, label<span class="op">=</span>label)</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>    marker_x <span class="op">=</span> np.array([<span class="dv">1</span>, <span class="dv">10</span>, <span class="dv">100</span>, <span class="dv">1000</span>])</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>    ax.scatter(marker_x, marker_x <span class="op">**</span> (<span class="op">-</span>exponent), color<span class="op">=</span>color, s<span class="op">=</span><span class="dv">28</span>)</span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>    doubling_factor <span class="op">=</span> <span class="dv">2</span> <span class="op">**</span> (<span class="op">-</span>exponent)</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>label<span class="sc">}</span><span class="ss">: doubling leaves </span><span class="sc">{</span>doubling_factor<span class="sc">:.4f}</span><span class="ss"> "</span></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"(</span><span class="sc">{</span><span class="dv">100</span> <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> doubling_factor)<span class="sc">:.1f}</span><span class="ss">% reduction)"</span></span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"resource multiplier"</span>)</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"normalized fitted loss component"</span>)</span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>ax.set_xticks([<span class="dv">1</span>, <span class="dv">10</span>, <span class="dv">100</span>, <span class="dv">1000</span>], [<span class="st">"1×"</span>, <span class="st">"10×"</span>, <span class="st">"100×"</span>, <span class="st">"1000×"</span>])</span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"small exponents imply persistent diminishing returns"</span>)</span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a>ax.legend(frameon<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a>ax.grid(<span class="va">True</span>, which<span class="op">=</span><span class="st">"both"</span>, alpha<span class="op">=</span><span class="fl">0.18</span>)</span>
<span id="cb23-25"><a href="#cb23-25" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb23-26"><a href="#cb23-26" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>parameters, $\alpha=0.076$: doubling leaves 0.9487 (5.1% reduction)
tokens, $\alpha=0.095$: doubling leaves 0.9363 (6.4% reduction)
optimal compute, $\alpha=0.050$: doubling leaves 0.9659 (3.4% reduction)</code></pre>
</div>
<div class="cell-output cell-output-display">
<div id="fig-kaplan-scaling" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Three shallow straight lines descend on log-log axes as parameters, tokens, or optimally allocated compute increase. Even at a thousand-fold resource multiplier, each fitted loss component remains a substantial fraction of its starting value.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-kaplan-scaling-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="16-vit-scaling_files/figure-html/fig-kaplan-scaling-output-2.png" alt="Three shallow straight lines descend on log-log axes as parameters, tokens, or optimally allocated compute increase. Even at a thousand-fold resource multiplier, each fitted loss component remains a substantial fraction of its starting value." width="805" height="374" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-kaplan-scaling-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16.4: Implications of Kaplan et al.’s published exponents, normalized to one at the left endpoint. The markers and lines are calculated from the fitted laws—not raw training runs from this book. Even a thousand-fold resource increase leaves a substantial fraction of the fitted component, which is the arithmetic of diminishing returns.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The doubling arithmetic is now pinned. Twice as many parameters multiplies the fitted parameter-limited loss by <span class="math inline">\(2^{-0.076}=0.949\)</span>, a 5.1% reduction. Doubling nonredundant data gives <span class="math inline">\(2^{-0.095}=0.936\)</span>, a 6.4% reduction. Doubling optimally allocated compute gives <span class="math inline">\(2^{-0.050}=0.966\)</span>, a 3.4% reduction. Comparing those percentages does <strong>not</strong> say that one parameter and one token have comparable cost or value—the units, constants, and constraints differ.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>A scaling law is a fitted conditional
</div>
</div>
<div class="callout-body-container callout-body">
<p>The measured range, data distribution, objective, architecture family, optimizer, and nonbinding-resource assumptions are part of the result. An extrapolation is a forecast under continued conditions, not a guarantee. Kaplan’s basic one-variable fits above do not contain an explicit additive <span class="math inline">\(1.69\)</span> floor; that constant belongs to the later Chinchilla joint fit.</p>
</div>
</div>
<p>Kaplan’s compute-optimal analysis suggested spending additional compute mostly on parameters:</p>
<p><span class="math display">\[
N_{\mathrm{opt}}\propto C^{0.73},
\qquad
D_{\mathrm{opt}}\propto C^{0.27}.
\]</span></p>
<p>That recommendation was influential—and it was later revised by a study designed to measure the allocation more directly.</p>
</section>
<section id="compute-optimal-means-balanced" class="level2" data-number="16.8">
<h2 data-number="16.8" class="anchored" data-anchor-id="compute-optimal-means-balanced"><span class="header-section-number">16.8</span> Compute-optimal means balanced</h2>
<p>Hoffmann and colleagues trained more than 400 language models while varying model size and token count. Their Chinchilla study estimated the compute-optimal frontier three ways.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 36%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Fitting approach</th>
<th style="text-align: right;"><span class="math inline">\(N_{\mathrm{opt}}\)</span> exponent</th>
<th style="text-align: right;"><span class="math inline">\(D_{\mathrm{opt}}\)</span> exponent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Minimum over training curves</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">0.50</td>
</tr>
<tr class="even">
<td>IsoFLOP profiles</td>
<td style="text-align: right;">0.49</td>
<td style="text-align: right;">0.51</td>
</tr>
<tr class="odd">
<td>Parametric loss model</td>
<td style="text-align: right;">0.46</td>
<td style="text-align: right;">0.54</td>
</tr>
</tbody>
</table>
<p>The exact answers differ—especially under long extrapolation—but all three move much more of the growing budget toward data than Kaplan’s <span class="math inline">\(0.73/0.27\)</span> allocation. That agreement is the central result—not one immortal ratio.</p>
<p>The third approach fits a joint loss surface:</p>
<p><span id="eq-chinchilla-loss"><span class="math display">\[
\widehat{L}(N,D)
=E+\frac{A}{N^\alpha}+\frac{B}{D^\beta},
\tag{16.5}\]</span></span></p>
<p>with published constants</p>
<p><span class="math display">\[
E=1.69,\quad A=406.4,\quad B=410.7,
\quad \alpha=0.34,\quad \beta=0.28.
\]</span></p>
<p><span class="math inline">\(E\)</span> is the fitted irreducible term for that distribution and objective; <span class="math inline">\(A/N^\alpha\)</span> is the model-limited contribution; and <span class="math inline">\(B/D^\beta\)</span> is the data-limited contribution. This decomposition is empirical. It is not a theorem that every language model has exactly three such terms.</p>
<p>For a dense Transformer, the study uses the approximation</p>
<p><span id="eq-six-nd"><span class="math display">\[
C\approx6ND,
\tag{16.6}\]</span></span></p>
<p>where <span class="math inline">\(C\)</span> is training floating-point operations, <span class="math inline">\(N\)</span> is non-embedding parameters, and <span class="math inline">\(D\)</span> is processed training tokens. The factor six approximates a forward pass plus a backward pass. It omits context-dependent and embedding details, so it is a planning equation rather than a profiler.</p>
<p>Fixing <span class="math inline">\(C\)</span> forces <span class="math inline">\(D=C/(6N)\)</span>. Too large a model leaves too few tokens; too many tokens leave too little model. Substituting the constraint into <a href="#eq-chinchilla-loss" class="quarto-xref">Equation&nbsp;<span>16.5</span></a> and differentiating gives</p>
<p><span class="math display">\[
G=\left(\frac{\alpha A}{\beta B}\right)^{1/(\alpha+\beta)},
\]</span></p>
<p><span id="eq-chinchilla-optimum"><span class="math display">\[
N_{\mathrm{opt}}
=G\left(\frac{C}{6}\right)^{\beta/(\alpha+\beta)},
\qquad
D_{\mathrm{opt}}
=G^{-1}\left(\frac{C}{6}\right)^{\alpha/(\alpha+\beta)}.
\tag{16.7}\]</span></span></p>
<p>The rounded constants imply exponents 0.452 and 0.548, close to the reported parametric-frontier fit of 0.46 and 0.54. At the reference budget <span class="math inline">\(C=5.76\times10^{23}\)</span>, this particular fitted surface reaches its minimum near 32.2 billion parameters and 2.98 trillion tokens. The other two methods place the model farther right, in roughly the 40–70 billion range. The paper chose 70 billion parameters and 1.4 trillion tokens for Chinchilla, at the upper end of that range, partly for data and computational efficiency.</p>
<div id="cell-fig-chinchilla-allocation" class="cell" data-fig-height="4.3" data-fig-width="9" data-execution_count="13">
<details class="code-fold">
<summary>Figure code: separate the joint-fit optimum from the 20-token heuristic</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>E_inf, A_fit, B_fit <span class="op">=</span> <span class="fl">1.69</span>, <span class="fl">406.4</span>, <span class="fl">410.7</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>alpha_fit, beta_fit <span class="op">=</span> <span class="fl">0.34</span>, <span class="fl">0.28</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>C_budget <span class="op">=</span> <span class="fl">5.76e23</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>G_fit <span class="op">=</span> (</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>    alpha_fit <span class="op">*</span> A_fit <span class="op">/</span> (beta_fit <span class="op">*</span> B_fit)</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>) <span class="op">**</span> (<span class="dv">1</span> <span class="op">/</span> (alpha_fit <span class="op">+</span> beta_fit))</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>N_joint <span class="op">=</span> G_fit <span class="op">*</span> (C_budget <span class="op">/</span> <span class="dv">6</span>) <span class="op">**</span> (</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>    beta_fit <span class="op">/</span> (alpha_fit <span class="op">+</span> beta_fit)</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>D_joint <span class="op">=</span> (C_budget <span class="op">/</span> <span class="dv">6</span>) <span class="op">/</span> N_joint</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>N_twenty <span class="op">=</span> math.sqrt(C_budget <span class="op">/</span> <span class="dv">120</span>)</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>D_twenty <span class="op">=</span> <span class="dv">20</span> <span class="op">*</span> N_twenty</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>N_grid <span class="op">=</span> np.logspace(np.log10(<span class="fl">4e9</span>), np.log10(<span class="fl">5e11</span>), <span class="dv">400</span>)</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>D_grid <span class="op">=</span> C_budget <span class="op">/</span> (<span class="dv">6</span> <span class="op">*</span> N_grid)</span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>loss_grid <span class="op">=</span> (</span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>    E_inf <span class="op">+</span> A_fit <span class="op">/</span> N_grid<span class="op">**</span>alpha_fit <span class="op">+</span> B_fit <span class="op">/</span> D_grid<span class="op">**</span>beta_fit</span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> fitted_chinchilla_loss(parameters: <span class="bu">float</span>, tokens: <span class="bu">float</span>) <span class="op">-&gt;</span> <span class="bu">float</span>:</span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (</span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a>        E_inf</span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a>        <span class="op">+</span> A_fit <span class="op">/</span> parameters<span class="op">**</span>alpha_fit</span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a>        <span class="op">+</span> B_fit <span class="op">/</span> tokens<span class="op">**</span>beta_fit</span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb25-28"><a href="#cb25-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-29"><a href="#cb25-29" aria-hidden="true" tabindex="-1"></a>points <span class="op">=</span> [</span>
<span id="cb25-30"><a href="#cb25-30" aria-hidden="true" tabindex="-1"></a>    (N_joint, D_joint, <span class="st">"joint-fit minimum"</span>, <span class="st">"#2E7D32"</span>),</span>
<span id="cb25-31"><a href="#cb25-31" aria-hidden="true" tabindex="-1"></a>    (N_twenty, D_twenty, <span class="st">"20-token heuristic"</span>, <span class="st">"#E57200"</span>),</span>
<span id="cb25-32"><a href="#cb25-32" aria-hidden="true" tabindex="-1"></a>    (<span class="fl">280e9</span>, C_budget <span class="op">/</span> (<span class="dv">6</span> <span class="op">*</span> <span class="fl">280e9</span>), <span class="st">"Gopher-sized model"</span>, <span class="st">"#722F37"</span>),</span>
<span id="cb25-33"><a href="#cb25-33" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb25-34"><a href="#cb25-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-35"><a href="#cb25-35" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="fl">4.3</span>))</span>
<span id="cb25-36"><a href="#cb25-36" aria-hidden="true" tabindex="-1"></a>ax.semilogx(N_grid <span class="op">/</span> <span class="fl">1e9</span>, loss_grid, color<span class="op">=</span><span class="st">"#232D4B"</span>, lw<span class="op">=</span><span class="fl">2.6</span>)</span>
<span id="cb25-37"><a href="#cb25-37" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> parameters, tokens, label, color <span class="kw">in</span> points:</span>
<span id="cb25-38"><a href="#cb25-38" aria-hidden="true" tabindex="-1"></a>    loss <span class="op">=</span> fitted_chinchilla_loss(parameters, tokens)</span>
<span id="cb25-39"><a href="#cb25-39" aria-hidden="true" tabindex="-1"></a>    ax.scatter(parameters <span class="op">/</span> <span class="fl">1e9</span>, loss, s<span class="op">=</span><span class="dv">70</span>, color<span class="op">=</span>color, zorder<span class="op">=</span><span class="dv">3</span>, label<span class="op">=</span>label)</span>
<span id="cb25-40"><a href="#cb25-40" aria-hidden="true" tabindex="-1"></a>    ax.annotate(</span>
<span id="cb25-41"><a href="#cb25-41" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>parameters <span class="op">/</span> <span class="fl">1e9</span><span class="sc">:.1f}</span><span class="ss">B params</span><span class="ch">\n</span><span class="sc">{</span>tokens <span class="op">/</span> <span class="fl">1e12</span><span class="sc">:.2f}</span><span class="ss">T tokens"</span>,</span>
<span id="cb25-42"><a href="#cb25-42" aria-hidden="true" tabindex="-1"></a>        (parameters <span class="op">/</span> <span class="fl">1e9</span>, loss), xytext<span class="op">=</span>(<span class="dv">6</span>, <span class="dv">8</span>), textcoords<span class="op">=</span><span class="st">"offset points"</span>,</span>
<span id="cb25-43"><a href="#cb25-43" aria-hidden="true" tabindex="-1"></a>        fontsize<span class="op">=</span><span class="dv">8</span>, color<span class="op">=</span>color,</span>
<span id="cb25-44"><a href="#cb25-44" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb25-45"><a href="#cb25-45" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"parameters $N$ (billions, log scale)"</span>)</span>
<span id="cb25-46"><a href="#cb25-46" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"published fitted loss $</span><span class="ch">\\</span><span class="st">widehat</span><span class="sc">{L}</span><span class="st">(N,C/(6N))$"</span>)</span>
<span id="cb25-47"><a href="#cb25-47" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"same approximate training budget, different allocations"</span>)</span>
<span id="cb25-48"><a href="#cb25-48" aria-hidden="true" tabindex="-1"></a>ax.legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">8</span>, loc<span class="op">=</span><span class="st">"upper left"</span>)</span>
<span id="cb25-49"><a href="#cb25-49" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb25-50"><a href="#cb25-50" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb25-51"><a href="#cb25-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-52"><a href="#cb25-52" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(</span>
<span id="cb25-53"><a href="#cb25-53" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"joint-fit minimum: N=</span><span class="sc">{</span>N_joint <span class="op">/</span> <span class="fl">1e9</span><span class="sc">:.2f}</span><span class="ss">B, "</span></span>
<span id="cb25-54"><a href="#cb25-54" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"D=</span><span class="sc">{</span>D_joint <span class="op">/</span> <span class="fl">1e12</span><span class="sc">:.3f}</span><span class="ss">T, D/N=</span><span class="sc">{</span>D_joint <span class="op">/</span> N_joint<span class="sc">:.1f}</span><span class="ss">"</span></span>
<span id="cb25-55"><a href="#cb25-55" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-56"><a href="#cb25-56" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(</span>
<span id="cb25-57"><a href="#cb25-57" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"20-token heuristic: N=</span><span class="sc">{</span>N_twenty <span class="op">/</span> <span class="fl">1e9</span><span class="sc">:.2f}</span><span class="ss">B, "</span></span>
<span id="cb25-58"><a href="#cb25-58" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"D=</span><span class="sc">{</span>D_twenty <span class="op">/</span> <span class="fl">1e12</span><span class="sc">:.3f}</span><span class="ss">T, C=</span><span class="sc">{</span><span class="dv">6</span> <span class="op">*</span> N_twenty <span class="op">*</span> D_twenty<span class="sc">:.2e}</span><span class="ss">"</span></span>
<span id="cb25-59"><a href="#cb25-59" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-chinchilla-allocation" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A U-shaped fitted loss curve plots model size along an iso-compute budget. The joint-fit point sits at the minimum near thirty-two billion parameters, the twenty-token point lies farther right near sixty-nine billion, and the Gopher-sized point lies far right on the rising branch.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-chinchilla-allocation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="16-vit-scaling_files/figure-html/fig-chinchilla-allocation-output-1.png" alt="A U-shaped fitted loss curve plots model size along an iso-compute budget. The joint-fit point sits at the minimum near thirty-two billion parameters, the twenty-token point lies farther right near sixty-nine billion, and the Gopher-sized point lies far right on the rising branch." width="856" height="402" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-chinchilla-allocation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16.5: One reference iso-compute curve under the published Chinchilla parametric loss fit. The rounded joint fit reaches its mathematical minimum near 32.2B parameters; the separate 20-tokens-per-parameter heuristic lands near 69.3B/1.386T, close to the 70B/1.4T Chinchilla design. A Gopher-sized 280B allocation leaves far fewer tokens. The curve is a fitted surface evaluation, not a new training experiment.
</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>joint-fit minimum: N=32.19B, D=2.982T, D/N=92.6
20-token heuristic: N=69.28B, D=1.386T, C=5.76e+23</code></pre>
</div>
</div>
<p>This distinction matters. The memorable <strong>20 tokens per parameter</strong> comes from the near-balanced frontier estimated by the first approaches: their table gives about 20.2 billion tokens for 1 billion parameters, 205.1 billion for 10 billion, and 1.5 trillion for 67 billion. If we impose the rounded heuristic <span class="math inline">\(D\approx20N\)</span> at the <span class="math inline">\(5.76\times10^{23}\)</span> budget, <a href="#eq-six-nd" class="quarto-xref">Equation&nbsp;<span>16.6</span></a> gives</p>
<p><span class="math display">\[
N\approx\sqrt{\frac{C}{120}}=69.3\text{ billion},
\qquad
D\approx1.386\text{ trillion}.
\]</span></p>
<p>That arithmetic is close to the actual Chinchilla design, but it is <strong>not</strong> the minimum of the rounded joint fit drawn above. Different fitting methods produced a broad range, and the authors made an engineering choice within it. Hiding that difference would make a heuristic look more exact than the evidence.</p>
<p>The historical comparison makes the allocation tangible. Gopher used about 280 billion parameters and 300 billion training tokens. Chinchilla used 70 billion parameters and 1.4 trillion tokens: four times fewer parameters and about 4.7 times more tokens, at approximately the same reported training budget. The smaller, longer-trained model achieved lower loss and outperformed the larger model across the paper’s broad evaluation suite. More parameters had not been the only way to spend the budget—and, in that regime, they had not been the best way.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Twenty is not a constant of nature
</div>
</div>
<div class="callout-body-container callout-body">
<p>The 20-to-1 ratio is an approximate rule from this study, model family, data, and frontier. The fitted methods do not agree exactly, and the ratio changes weakly with compute even inside the parametric model. Data quality, repetition, tokenization, objective, architecture, and downstream use can all move the useful allocation. Use the rule to challenge an obviously undertrained model, not to end the analysis.</p>
</div>
</div>
</section>
<section id="where-the-forecast-stops" class="level2" data-number="16.9">
<h2 data-number="16.9" class="anchored" data-anchor-id="where-the-forecast-stops"><span class="header-section-number">16.9</span> Where the forecast stops</h2>
<p>Scaling laws are powerful precisely because they compress many expensive runs into a small predictive object. That compression has boundaries.</p>
<p><strong>Loss is not a capability map.</strong> A smoother aggregate cross-entropy curve does not tell us that every downstream skill appears smoothly, or exactly when a particular behavior becomes reliable.</p>
<p><strong>Tokens are not interchangeable.</strong> A trillion repeated, low-quality, contaminated, or mismatched tokens need not buy what a trillion useful, diverse tokens buy. <span class="math inline">\(D\)</span> counts processed tokens; it does not measure novelty or truth.</p>
<p><strong>The law is local to a recipe and range.</strong> Change the architecture, optimizer, data mixture, context length, or evaluation distribution and the fitted constants can move. Extrapolation beyond the measured range adds uncertainty even when the line looks immaculate on log–log axes.</p>
<p><strong>Training-optimal is not serving-optimal.</strong> Chinchilla allocates a training budget; it does not make the resulting backbone cheap to store, run, or adapt. <a href="../part5/17-peft-quantization.html" class="quarto-xref"><span>Chapter 17</span></a> will harvest that mismatch: what can we change when moving every pretrained weight is no longer affordable?</p>
<p>This closes Part IV’s route from fixed lookup to global learned routing. We began with a memory bank, learned how to score it, let every token query every other token, changed the visibility to pretrain representations, and finally let images enter as tokens. The operator was only half the story. The data and budget that train it are part of the model too.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Check yourself
</div>
</div>
<div class="callout-body-container callout-body">
<p>Close the book for one minute and retrieve the chapter’s three scales.</p>
<ul>
<li>For a 28×28 image with 4×4 patches, how many patch tokens appear before <code>[CLS]</code>?</li>
<li>Why does a matched toy CNN–ViT rematch describe a regime rather than declare a winner?</li>
<li>Under fixed training compute, why must parameter count and token count be chosen together?</li>
</ul>
</div>
</div>
</section>
<section id="okay-so-patches-become-tokens-but-regime-still-matters" class="level2" data-number="16.10">
<h2 data-number="16.10" class="anchored" data-anchor-id="okay-so-patches-become-tokens-but-regime-still-matters"><span class="header-section-number">16.10</span> Okay, so — patches become tokens, but regime still matters</h2>
<ol type="1">
<li><strong>An image can become a token sequence.</strong> Split it into <span class="math inline">\(P\times P\)</span> patches, flatten to width <span class="math inline">\(CP^2\)</span>, and share a learned projection. Unfold-plus-linear is exactly a convolution with kernel and stride <span class="math inline">\(P\)</span> after reshaping its weights.</li>
<li><strong>ViT is an encoder transplant, not assumption-free learning.</strong> A learned <code>[CLS]</code> meeting place, learned positions, pre-LayerNorm blocks, and a linear head reuse the Transformer pattern while retaining a small set of image and optimization biases.</li>
<li><strong>Inductive bias is a trade.</strong> The five-seed Fashion rematch favors the CNN on clean validation and much more strongly under shift, but it is a tiny scratch regime—not an architecture referendum. Large supervised pretraining changed the comparison in the original ViT study.</li>
<li><strong>Architecture and recipe cannot be cleanly collapsed into a brand name.</strong> Hybrid stems, windowed routing, distillation, and ConvNeXt put priors in different places. Data, optimization, and operator design interact.</li>
<li><strong>Scaling has two meanings here.</strong> EfficientNet’s compound rule coordinates depth, width, and resolution; empirical scaling laws forecast loss as parameters, tokens, and compute change. Both are resource-allocation tools, but they answer different questions.</li>
<li><strong>Compute-optimal training balances model and data.</strong> Chinchilla revised the parameter-heavy Kaplan allocation, while also showing why a memorable 20-token heuristic must remain a heuristic. A fitted law carries its regime, assumptions, and uncertainty with it.</li>
</ol>
</section>
<section id="sources-and-further-reading" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="sources-and-further-reading">Sources and further reading</h2>
<ul>
<li><a href="https://arxiv.org/abs/2010.11929">Dosovitskiy et al., <em>An Image Is Worth 16×16 Words: Transformers for Image Recognition at Scale</em></a>: the original ViT architecture, position and pooling ablations, and data-scale comparison.</li>
<li><a href="https://proceedings.mlr.press/v97/tan19a.html">Tan and Le, <em>EfficientNet: Rethinking Model Scaling for Convolutional Neural Networks</em></a>: compound depth, width, and resolution scaling.</li>
<li><a href="https://proceedings.mlr.press/v139/touvron21a.html">Touvron et al., <em>Training Data-Efficient Image Transformers &amp; Distillation Through Attention</em></a>: DeiT’s augmentation and teacher-guided training recipe.</li>
<li><a href="https://openaccess.thecvf.com/content/ICCV2021/html/Liu_Swin_Transformer_Hierarchical_Vision_Transformer_Using_Shifted_Windows_ICCV_2021_paper.html">Liu et al., <em>Swin Transformer: Hierarchical Vision Transformer Using Shifted Windows</em></a>: local shifted windows, hierarchy, and resolution-aware attention cost.</li>
<li><a href="https://openaccess.thecvf.com/content/CVPR2022/html/Liu_A_ConvNet_for_the_2020s_CVPR_2022_paper.html">Liu et al., <em>A ConvNet for the 2020s</em></a>: the ConvNeXt modernization study and architecture–recipe interaction.</li>
<li><a href="https://arxiv.org/abs/2001.08361">Kaplan et al., <em>Scaling Laws for Neural Language Models</em></a>: the parameter, data, and compute power laws and the earlier compute allocation.</li>
<li><a href="https://arxiv.org/abs/2203.15556">Hoffmann et al., <em>Training Compute-Optimal Large Language Models</em></a>: the three Chinchilla frontier estimates, joint loss fit, and Gopher comparison.</li>
</ul>
</section>
<section id="exercises" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercises">Exercises</h2>
<ol type="1">
<li><strong>(Pencil.)</strong> A batch contains 12 RGB images at <span class="math inline">\(384\times384\)</span>. With <span class="math inline">\(P=16\)</span> and model width <span class="math inline">\(d=768\)</span>, give the shapes of the raw batch, flattened patch tensor, projected patches, and sequence after <code>[CLS]</code>. Repeat the token and per-head score-entry counts for <span class="math inline">\(P=8\)</span>. By what factor did halving <span class="math inline">\(P\)</span> change each count?</li>
<li><strong>(Code and proof.)</strong> Generalize the patch-equivalence cell to <span class="math inline">\(C=3\)</span> and a rectangular image whose height and width are each divisible by <span class="math inline">\(P\)</span>. State the required unfold ordering, reshape a matrix <span class="math inline">\(\matr{E}\in\mathbb{R}^{CP^2\times d}\)</span> into convolution weights, and assert equality to numerical tolerance. Explain why overlap appears when stride is smaller than <span class="math inline">\(P\)</span>.</li>
<li><strong>(Experimental audit.)</strong> Reproduce all five paired Fashion results and compute the paired clean-validation gaps, clean-to-four-pixel drops, and schedule hashes. Then change exactly one factor—add translated training examples—while keeping the split, seeds, initialization rule, model sizes, and minibatch schedules auditable. What question does the new comparison answer, and what still prevents a general CNN-versus-ViT claim?</li>
<li><strong>(Scaling arithmetic.)</strong> Using EfficientNet’s published constants, compute the depth, width, resolution, and operation-proxy multipliers at <span class="math inline">\(\phi=3\)</span>. Then use Kaplan’s exponents to compute the fitted component remaining after a 10-fold increase in parameters, data, and compute. Why can you not compare those three numbers as benefits per dollar?</li>
<li><strong>(Derivation and interpretation.)</strong> Starting from <a href="#eq-chinchilla-loss" class="quarto-xref">Equation&nbsp;<span>16.5</span></a> and <a href="#eq-six-nd" class="quarto-xref">Equation&nbsp;<span>16.6</span></a>, derive <a href="#eq-chinchilla-optimum" class="quarto-xref">Equation&nbsp;<span>16.7</span></a>. Evaluate both the joint-fit optimum and the separate <span class="math inline">\(D=20N\)</span> heuristic at a budget of <span class="math inline">\(1.2\times10^{22}\)</span> FLOPs. Explain why disagreement between the answers is evidence to report rather than an algebra mistake, and name two deployment constraints neither calculation optimizes.</li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/shakeri-lab\.github\.io\/dl-book\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../chapters/part4/15-bert-pretraining.html" class="pagination-link" aria-label="The BERT Moment: Pretraining as the New Regime">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">The BERT Moment: Pretraining as the New Regime</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/part5/17-peft-quantization.html" class="pagination-link" aria-label="Adapting Pretrained Models: Prompting, PEFT, Quantization">
        <span class="nav-page-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Adapting Pretrained Models: Prompting, PEFT, Quantization</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Heman Shakeri · Text CC BY-NC-SA 4.0 · Code MIT · School of Data Science, University of Virginia</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/Shakeri-Lab/dl-book/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Companion to <a href="https://shakeri-lab.github.io/dl-course-site/">DS 6050 Deep Learning</a></p>
</div>
  </div>
</footer>




</body></html>