<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Who Trains the Trainer? Learning by Experiment – Deep Learning: Making It Learnable</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/part2/07-filters-convolution.html" rel="next">
<link href="../../chapters/part1/06-generalization-inductive-bias.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-c90f29e1247290e1dfbeb1da338aa877.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>
  // Book math macros — keep in sync with tex/macros.tex (PDF path).
  // MathJax reads this config because it is defined before the MathJax
  // script loads (Quarto places include-in-header above its math script).
  window.MathJax = {
    tex: {
      macros: {
        E: "\\mathbb{E}",
        Ex: "\\operatorname{E}",
        var: "\\operatorname{Var}",
        cov: "\\operatorname{Cov}",
        imp: "\\Rightarrow",
        argmax: "\\operatorname*{arg\\,max}",
        argmin: "\\operatorname*{arg\\,min}",
        norm: ["\\left\\lVert#1\\right\\rVert", 1],
        vect: ["\\boldsymbol{#1}", 1],
        matr: ["\\boldsymbol{#1}", 1],
        R: "\\mathbb{R}",
        dd: "\\mathrm{d}",
        loss: "\\mathcal{L}"
      }
    }
  };
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/interludes/learning-by-experiment.html">Who Trains the Trainer? Learning by Experiment</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Deep Learning: Making It Learnable</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/Shakeri-Lab/dl-book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">From Lines to Networks</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/01-linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Linear Regression, the Mother Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/02-logistic-softmax.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Linear Models that Classify: Logistic and Softmax</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/03-nonlinearity-mlp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Nonlinearity and the MLP</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/04-training-loss-sgd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Training: Loss and Stochastic Gradient Descent</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/05-backpropagation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Backpropagation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/06-generalization-inductive-bias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">When It Fails: Generalization in Pictures, and Inductive Bias</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/interludes/learning-by-experiment.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Who Trains the Trainer? Learning by Experiment</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Vision: Learning the Filters</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/07-filters-convolution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Filters and Convolution (Fixed Kernels)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/08-cnn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">CNNs: Making the Filters Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/09-modern-cnns-transfer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Modern CNNs and Transfer Learning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/interludes/making-pca-learnable.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Interlude: Making PCA Learnable</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Sequences</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part3/10-sequences-rnn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Sequences and Recurrence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part3/11-encoder-decoder.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Encoder–Decoder, Teacher Forcing, Beam Search</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Attention: Learning the Similarity</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/12-kernel-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Kernel Regression: Attention Before It Was Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/13-attention.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Attention: Making the Kernel Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/14-self-attention-transformer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Self-Attention and the Transformer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/15-bert-pretraining.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">The BERT Moment: Pretraining as the New Regime</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/16-vit-scaling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Vision Transformers and Scaling Laws</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">The Pretrained Era</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/17-peft-quantization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Adapting Pretrained Models: Prompting, PEFT, Quantization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/18-alignment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Alignment and RL Fine-Tuning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/19-generative.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Generative Models: From Codes to Samples</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/20-multimodal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Multimodal Learning: One Space, Two Views</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/epilogue.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Epilogue: The Question Is Yours</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a1-linear-algebra.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Linear Algebra and the SVD</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a2-tensors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Tensors in Practice</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a3-precision-performance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Numerical Precision and Hardware Efficiency</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a4-notation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Notation</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#two-levels-of-learning" id="toc-two-levels-of-learning" class="nav-link active" data-scroll-target="#two-levels-of-learning">Two levels of learning</a></li>
  <li><a href="#start-with-the-claim-not-the-sweep" id="toc-start-with-the-claim-not-the-sweep" class="nav-link" data-scroll-target="#start-with-the-claim-not-the-sweep">Start with the claim, not the sweep</a>
  <ul class="collapse">
  <li><a href="#fair-has-more-than-one-meaning" id="toc-fair-has-more-than-one-meaning" class="nav-link" data-scroll-target="#fair-has-more-than-one-meaning">“Fair” has more than one meaning</a></li>
  </ul></li>
  <li><a href="#a-worked-experiment-batchnorm-changes-the-learning-rate-story" id="toc-a-worked-experiment-batchnorm-changes-the-learning-rate-story" class="nav-link" data-scroll-target="#a-worked-experiment-batchnorm-changes-the-learning-rate-story">A worked experiment: BatchNorm changes the learning-rate story</a></li>
  <li><a href="#ablation-is-an-argument-about-cause" id="toc-ablation-is-an-argument-about-cause" class="nav-link" data-scroll-target="#ablation-is-an-argument-about-cause">Ablation is an argument about cause</a></li>
  <li><a href="#hyperparameter-optimization-is-a-budgeted-outer-loop" id="toc-hyperparameter-optimization-is-a-budgeted-outer-loop" class="nav-link" data-scroll-target="#hyperparameter-optimization-is-a-budgeted-outer-loop">Hyperparameter optimization is a budgeted outer loop</a>
  <ul class="collapse">
  <li><a href="#choose-the-space-before-choosing-the-algorithm" id="toc-choose-the-space-before-choosing-the-algorithm" class="nav-link" data-scroll-target="#choose-the-space-before-choosing-the-algorithm">Choose the space before choosing the algorithm</a></li>
  <li><a href="#spend-small-budgets-before-large-ones" id="toc-spend-small-budgets-before-large-ones" class="nav-link" data-scroll-target="#spend-small-budgets-before-large-ones">Spend small budgets before large ones</a></li>
  </ul></li>
  <li><a href="#train-validation-and-test-have-different-jobs" id="toc-train-validation-and-test-have-different-jobs" class="nav-link" data-scroll-target="#train-validation-and-test-have-different-jobs">Train, validation, and test have different jobs</a></li>
  <li><a href="#seeds-are-a-panel-not-decoration" id="toc-seeds-are-a-panel-not-decoration" class="nav-link" data-scroll-target="#seeds-are-a-panel-not-decoration">Seeds are a panel, not decoration</a></li>
  <li><a href="#the-experiment-ledger" id="toc-the-experiment-ledger" class="nav-link" data-scroll-target="#the-experiment-ledger">The experiment ledger</a></li>
  <li><a href="#a-protocol-for-the-rest-of-this-book" id="toc-a-protocol-for-the-rest-of-this-book" class="nav-link" data-scroll-target="#a-protocol-for-the-rest-of-this-book">A protocol for the rest of this book</a></li>
  <li><a href="#okay-so-tune-the-contender-ablate-the-claim" id="toc-okay-so-tune-the-contender-ablate-the-claim" class="nav-link" data-scroll-target="#okay-so-tune-the-contender-ablate-the-claim">Okay, so — tune the contender, ablate the claim</a></li>
  <li><a href="#sources-and-further-reading" id="toc-sources-and-further-reading" class="nav-link" data-scroll-target="#sources-and-further-reading">Sources and further reading</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/Shakeri-Lab/dl-book/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-learning-by-experiment" class="quarto-section-identifier">Who Trains the Trainer? Learning by Experiment</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<!-- lecture-source: GMT20250918-002913_Recording.transcript (1).vtt
     (SHA-256 65a63bd04f7df3c20b21725d4d0b0fa0ed98928686561c45b713a774f568410d),
     seeds: sources/3-HPO-experimentation.tex (sanitized from hpo_slides.tex,
     SHA-256 6deaf680eadf3ed04356207376fa359e5bd8c1fc04c54cd93c1b047676403fba) -->
<p>Chapter 6 ended with a model whose code was correct, whose loss fell, and whose validation accuracy looked respectable. Then two carefully chosen experiments showed that it had learned the wrong structure. This creates a new problem. Gradient descent can train the weights, but who trains the trainer? Who chooses the learning rate, the architecture, the regularization, the stopping point, and even the comparison that we will call fair?</p>
<p>The answer is not another optimizer. It is <strong>experimentation</strong>. We make a claim, design a comparison that can answer it, spend a declared budget, and preserve enough evidence that someone else can audit our reasoning. Deep learning is mathematical, but much of its progress is also empirical — the code can run perfectly while the scientific question remains badly posed.</p>
<p>This interlude gives names to the discipline that the rest of the book will use. Its central distinction is simple:</p>
<blockquote class="blockquote">
<p><strong>Weights learn inside a run; we learn about designs across runs.</strong></p>
</blockquote>
<p>That distinction — inner training versus outer inquiry — keeps hyperparameter optimization and ablation from collapsing into one large sweep. They cooperate, but they answer different questions.</p>
<section id="two-levels-of-learning" class="level2">
<h2 class="anchored" data-anchor-id="two-levels-of-learning">Two levels of learning</h2>
<p>Recall the image of a weight as a knob. During one training run, the optimizer turns millions of those knobs using gradients. A <strong>parameter</strong> — a weight, a bias, or another model quantity updated by the training algorithm — is learned this way.</p>
<p><strong>Hyperparameters</strong> — learning rate, batch size, weight decay, and training schedule, for example — control the learning process from outside that inner loop. An architectural choice, such as whether to include BatchNorm, can also sit outside the weight update. Whether we call it a hyperparameter or an experimental factor depends on the question we ask of it.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Run, experiment, and study
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>A <strong>run</strong> trains one design — under one configuration, seed, data split, and budget — once.</li>
<li>An <strong>experiment</strong> compares runs to answer a predeclared question.</li>
<li>A <strong>study</strong> is the larger collection of experiments from which we draw a scientific conclusion.</li>
</ul>
<p>Ten runs are not automatically an experiment. Without a question and a controlled comparison, they are ten observations looking for a story.</p>
</div>
</div>
<p>Let us formalize the two levels only after seeing why they are needed. Write <span class="math inline">\(a\)</span> for a design choice — BatchNorm on or off, for example — and <span class="math inline">\(\vect{\lambda}\)</span> for the training configuration. Let <span class="math inline">\(s\)</span> be the random seed and <span class="math inline">\(b\)</span> the budget. Training returns weights</p>
<p><span id="eq-experiment-train"><span class="math display">\[
\vect{w}^{*}(a,\vect{\lambda},s,b)
= \operatorname{Train}(a,\vect{\lambda},s,b).
\tag{1}\]</span></span></p>
<p>If <span class="math inline">\(J_D\)</span> is a metric on dataset <span class="math inline">\(D\)</span>, one run produces</p>
<p><span id="eq-experiment-score"><span class="math display">\[
J_D(a,\vect{\lambda},s,b)
= \operatorname{Metric}\!\left(
f_{\vect{w}^{*}(a,\vect{\lambda},s,b)},D
\right).
\tag{2}\]</span></span></p>
<p>The optimizer learns <span class="math inline">\(\vect{w}^{*}\)</span>. We choose <span class="math inline">\(a\)</span>, search over <span class="math inline">\(\vect{\lambda}\)</span>, decide which seeds and budget are credible, and interpret the result. Those outer choices are part of the claim — they do not disappear when a library automates them.</p>
</section>
<section id="start-with-the-claim-not-the-sweep" class="level2">
<h2 class="anchored" data-anchor-id="start-with-the-claim-not-the-sweep">Start with the claim, not the sweep</h2>
<p>Suppose a new normalization layer improves accuracy by two points. What did the experiment establish? The answer depends on what stayed fixed and what was optimized. Four common claim types should not be mixed:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Claim</th>
<th>What is held fixed?</th>
<th>What it can support</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mechanism demonstration</td>
<td>A small, transparent regime</td>
<td>“This behavior can occur, and here is why.”</td>
</tr>
<tr class="even">
<td>Fixed-protocol ablation</td>
<td>One training recipe, paired seeds and data</td>
<td>“At this recipe, changing this component changed the outcome.”</td>
</tr>
<tr class="odd">
<td>Tuned design comparison</td>
<td>Search space and search budget, not one recipe</td>
<td>“Under equal tuning opportunity, this design achieved this result.”</td>
</tr>
<tr class="even">
<td>Benchmark estimate</td>
<td>Locked method, metric, split, and reporting protocol</td>
<td>“This complete procedure attained this performance in the declared regime.”</td>
</tr>
</tbody>
</table>
<p>A single seeded run can be entirely legitimate — sometimes ideal — for a mechanism demonstration. It is not enough to estimate an average effect of a stochastic training procedure. Likewise, a benchmark table can rank complete systems without isolating which component caused the difference. Before opening a notebook, finish the sentence: <strong>the claim I want this experiment to support is …</strong></p>
<!-- NOVEL: needs sign-off - the estimand distinction below reconciles the lecture's
     tuned-per-design fairness rule with the fixed-protocol comparisons used elsewhere
     in the manuscript. -->
<section id="fair-has-more-than-one-meaning" class="level3">
<h3 class="anchored" data-anchor-id="fair-has-more-than-one-meaning">“Fair” has more than one meaning</h3>
<p>Consider two designs, <span class="math inline">\(a_0\)</span> and <span class="math inline">\(a_1\)</span>. A fixed-protocol ablation uses one configuration <span class="math inline">\(\vect{\lambda}_0\)</span> for both. Its target is</p>
<p><span id="eq-fixed-estimand"><span class="math display">\[
\Delta_{\mathrm{fixed}}(\vect{\lambda}_0)
= \E_s\!\left[
J(a_1,\vect{\lambda}_0,s,b)
-J(a_0,\vect{\lambda}_0,s,b)
\right].
\tag{3}\]</span></span></p>
<p>This asks a clean local question: <em>what is the effect of the design change at this training recipe?</em> Pairing the seeds — a common-randomness design — makes the contrast easier to read because both arms encounter corresponding random conditions. The answer can still change at another learning rate.</p>
<p>A tuned comparison asks a different question. Let <span class="math inline">\(\Lambda_0\)</span> and <span class="math inline">\(\Lambda_1\)</span> be declared search spaces. Ideally, we want the contrast between the best expected outcomes available to each design:</p>
<p><span id="eq-tuned-estimand"><span class="math display">\[
\Delta_{\mathrm{tuned}}
= \max_{\vect{\lambda}\in\Lambda_1}
\E_s[J(a_1,\vect{\lambda},s,b)]
- \max_{\vect{\lambda}\in\Lambda_0}
\E_s[J(a_0,\vect{\lambda},s,b)].
\tag{4}\]</span></span></p>
<p>In practice we only approximate these maxima with a finite search. The search spaces, number of trials, seeds, and per-trial budget therefore belong in the result. The lecture gives a memorable analogy: when interviewing candidates, help each candidate reach their best state before comparing them. One learning rate — a one-size-fits-all interview — may flatter one architecture and handicap another.</p>
<p>Neither estimand is universally fair. A shared recipe is fair to the question of a controlled intervention; separate tuning is fair to the question of attainable performance. Trouble begins when we run one and write the conclusion of the other.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Framework preview: BatchNorm is an opaque factor here
</div>
</div>
<div class="callout-body-container callout-body">
<p>Chapter 9 opens BatchNorm and explains its train/evaluation behavior. This interlude uses the framework layer only as a binary experimental factor—we need not credit a mechanism to compare protocols. Treat it as a labeled measuring instrument, not as a tool the reading order has introduced for general use.</p>
</div>
</div>
</section>
</section>
<section id="a-worked-experiment-batchnorm-changes-the-learning-rate-story" class="level2">
<h2 class="anchored" data-anchor-id="a-worked-experiment-batchnorm-changes-the-learning-rate-story">A worked experiment: BatchNorm changes the learning-rate story</h2>
<p>Let us make the distinction visible on the same Fashion-MNIST subset used in Chapter 6. The research question is intentionally small: <strong>does adding BatchNorm help a tiny MLP?</strong> Before running anything, we pin the contract:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Item</th>
<th>Predeclared choice</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Development data</td>
<td>1,200 committed images; 1,000 fit and 200 validation</td>
</tr>
<tr class="even">
<td>Locked endpoint data</td>
<td>600 committed test images, already used by earlier book studies</td>
</tr>
<tr class="odd">
<td>Design factor</td>
<td>BatchNorm after each hidden affine layer: absent or present</td>
</tr>
<tr class="even">
<td>Shared architecture</td>
<td><span class="math inline">\(784\rightarrow128\rightarrow64\rightarrow10\)</span>, ReLU</td>
</tr>
<tr class="odd">
<td>Optimizer and budget</td>
<td>SGD with momentum 0.9, batch 100, at most 20 epochs</td>
</tr>
<tr class="even">
<td>Learning-rate search</td>
<td><span class="math inline">\(\{0.003,0.01,0.03,0.1\}\)</span></td>
</tr>
<tr class="odd">
<td>Search seeds</td>
<td>6050–6054, paired across all configurations</td>
</tr>
<tr class="even">
<td>Audit seeds</td>
<td>6060–6064, fixed before endpoint results are evaluated</td>
</tr>
<tr class="odd">
<td>Selection rule</td>
<td>Highest mean validation accuracy; restore each run’s best checkpoint</td>
</tr>
</tbody>
</table>
<p>Notice what has not happened: we have not chosen a result and then invented a protocol around it. The split, search space, seeds, metric, budget, and selection rule are fixed first. That pre-testing discipline is what lets the prose report numbers rather than negotiate with them.</p>
<p>The 600-image file is <strong>not a globally sealed test set</strong>: Chapter 6 has already used the same book benchmark, and Chapters 8 and 9 will reuse it later. Within this worked study, its values remain decision-inert—we do not inspect them until the designs and learning rates are locked, and we make no change afterward. This is a demonstration of the protocol, not a claim that reused public data became untouched again. A new project should reserve a truly unopened audit set.</p>
<p>The next cell loads only the development data and defines one typed training function. The tensor shapes are explicit because experimental rigor does not excuse coding ambiguity.</p>
<div id="experiment-setup" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Code: the paired Fashion-MNIST experiment</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> __future__ <span class="im">import</span> annotations</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> itertools</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> copy <span class="im">import</span> deepcopy</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> torch <span class="im">import</span> Tensor, nn</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.nn.functional <span class="im">as</span> F</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>torch.set_num_threads(<span class="dv">4</span>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>development <span class="op">=</span> torch.load(<span class="st">"../../data/fashion-train.pt"</span>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>X_dev <span class="op">=</span> development[<span class="st">"X"</span>].<span class="bu">float</span>().unsqueeze(<span class="dv">1</span>) <span class="op">/</span> <span class="fl">255.0</span>  <span class="co"># (1200, 1, 28, 28)</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>y_dev <span class="op">=</span> development[<span class="st">"y"</span>]                                <span class="co"># (1200,)</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>split <span class="op">=</span> torch.randperm(</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    <span class="bu">len</span>(X_dev), generator<span class="op">=</span>torch.Generator().manual_seed(<span class="dv">6050</span>)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>fit_idx, val_idx <span class="op">=</span> split[:<span class="dv">1000</span>], split[<span class="dv">1000</span>:]</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>X_fit, y_fit <span class="op">=</span> X_dev[fit_idx], y_dev[fit_idx]</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>X_val, y_val <span class="op">=</span> X_dev[val_idx], y_dev[val_idx]</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> TinyMLP(nn.Module):</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, use_batchnorm: <span class="bu">bool</span>) <span class="op">-&gt;</span> <span class="va">None</span>:</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.fc1 <span class="op">=</span> nn.Linear(<span class="dv">28</span> <span class="op">*</span> <span class="dv">28</span>, <span class="dv">128</span>)</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.bn1 <span class="op">=</span> nn.BatchNorm1d(<span class="dv">128</span>) <span class="cf">if</span> use_batchnorm <span class="cf">else</span> nn.Identity()</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.fc2 <span class="op">=</span> nn.Linear(<span class="dv">128</span>, <span class="dv">64</span>)</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.bn2 <span class="op">=</span> nn.BatchNorm1d(<span class="dv">64</span>) <span class="cf">if</span> use_batchnorm <span class="cf">else</span> nn.Identity()</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.out <span class="op">=</span> nn.Linear(<span class="dv">64</span>, <span class="dv">10</span>)</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x: Tensor) <span class="op">-&gt;</span> Tensor:</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> x.flatten(<span class="dv">1</span>)                            <span class="co"># (B, 1, 28, 28) -&gt; (B, 784)</span></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> F.relu(<span class="va">self</span>.bn1(<span class="va">self</span>.fc1(x)))           <span class="co"># (B, 784) -&gt; (B, 128)</span></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> F.relu(<span class="va">self</span>.bn2(<span class="va">self</span>.fc2(x)))           <span class="co"># (B, 128) -&gt; (B, 64)</span></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">self</span>.out(x)                          <span class="co"># (B, 64) -&gt; (B, 10)</span></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a><span class="at">@torch.no_grad</span>()</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> accuracy(model: nn.Module, x: Tensor, target: Tensor) <span class="op">-&gt;</span> <span class="bu">float</span>:</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>    model.<span class="bu">eval</span>()                                    <span class="co"># freeze BatchNorm statistics</span></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (model(x).argmax(<span class="dv">1</span>) <span class="op">==</span> target).<span class="bu">float</span>().mean().item()</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> run_once(</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>    seed: <span class="bu">int</span>,</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>    use_batchnorm: <span class="bu">bool</span>,</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>    learning_rate: <span class="bu">float</span>,</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>    endpoint: <span class="bu">tuple</span>[Tensor, Tensor] <span class="op">|</span> <span class="va">None</span> <span class="op">=</span> <span class="va">None</span>,</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>    epochs: <span class="bu">int</span> <span class="op">=</span> <span class="dv">20</span>,</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>) <span class="op">-&gt;</span> <span class="bu">tuple</span>[<span class="bu">float</span>, <span class="bu">float</span>]:</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>    torch.manual_seed(seed)</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>    model <span class="op">=</span> TinyMLP(use_batchnorm)</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>    optimizer <span class="op">=</span> torch.optim.SGD(</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>        model.parameters(), lr<span class="op">=</span>learning_rate, momentum<span class="op">=</span><span class="fl">0.9</span></span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>    batch_rng <span class="op">=</span> torch.Generator().manual_seed(seed <span class="op">+</span> <span class="dv">100_000</span>)</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a>    best_validation <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>    best_state <span class="op">=</span> deepcopy(model.state_dict())</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(epochs):</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>        model.train()</span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>        order <span class="op">=</span> torch.randperm(<span class="bu">len</span>(X_fit), generator<span class="op">=</span>batch_rng)</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> idx <span class="kw">in</span> order.split(<span class="dv">100</span>):</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a>            loss <span class="op">=</span> F.cross_entropy(model(X_fit[idx]), y_fit[idx])</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>            optimizer.zero_grad()</span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>            loss.backward()</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>            optimizer.step()</span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a>        validation <span class="op">=</span> accuracy(model, X_val, y_val)</span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> validation <span class="op">&gt;</span> best_validation:</span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>            best_validation <span class="op">=</span> validation</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>            best_state <span class="op">=</span> deepcopy(model.state_dict())</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a>    model.load_state_dict(best_state)                <span class="co"># evaluate the selected checkpoint</span></span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a>    endpoint_score <span class="op">=</span> (</span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a>        accuracy(model, <span class="op">*</span>endpoint) <span class="cf">if</span> endpoint <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span> <span class="cf">else</span> best_validation</span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> best_validation, endpoint_score</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>There are two easy-to-miss hygiene details. Evaluation switches the model to <code>eval()</code> so BatchNorm stops updating its running statistics. More subtly, each run restores the checkpoint that actually won on validation. Reporting the last epoch after saying “best validation” would be a mismatch between the selection rule and the code.</p>
<p>Now we run the complete validation search. Five seeds — no magic threshold — form a small panel that makes run-to-run variation visible while keeping this example comfortably on a CPU.</p>
<div id="experiment-search" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code: search four learning rates with paired seeds</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>learning_rates <span class="op">=</span> (<span class="fl">0.003</span>, <span class="fl">0.01</span>, <span class="fl">0.03</span>, <span class="fl">0.1</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>search_seeds <span class="op">=</span> <span class="bu">tuple</span>(<span class="bu">range</span>(<span class="dv">6050</span>, <span class="dv">6055</span>))</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>search_rows: <span class="bu">list</span>[<span class="bu">dict</span>[<span class="bu">str</span>, <span class="bu">float</span> <span class="op">|</span> <span class="bu">bool</span> <span class="op">|</span> Tensor]] <span class="op">=</span> []</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> use_batchnorm, learning_rate <span class="kw">in</span> itertools.product(</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    (<span class="va">False</span>, <span class="va">True</span>), learning_rates</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>):</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    scores <span class="op">=</span> torch.tensor([</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>        run_once(seed, use_batchnorm, learning_rate)[<span class="dv">0</span>]</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> seed <span class="kw">in</span> search_seeds</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    ])</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    search_rows.append({</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>        <span class="st">"batchnorm"</span>: use_batchnorm,</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>        <span class="st">"learning_rate"</span>: learning_rate,</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>        <span class="st">"scores"</span>: scores,</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>        <span class="st">"mean"</span>: scores.mean().item(),</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>        <span class="st">"sd"</span>: scores.std(unbiased<span class="op">=</span><span class="va">True</span>).item(),</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> row <span class="kw">in</span> search_rows:</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>    label <span class="op">=</span> <span class="st">"with BN"</span> <span class="cf">if</span> row[<span class="st">"batchnorm"</span>] <span class="cf">else</span> <span class="st">"no BN  "</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>label<span class="sc">}</span><span class="ss">  lr=</span><span class="sc">{</span>row[<span class="st">'learning_rate'</span>]<span class="sc">:&lt;5}</span><span class="ss">  "</span></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"validation=</span><span class="sc">{</span><span class="dv">100</span> <span class="op">*</span> row[<span class="st">'mean'</span>]<span class="sc">:.1f}</span><span class="ss">% +/- </span><span class="sc">{</span><span class="dv">100</span> <span class="op">*</span> row[<span class="st">'sd'</span>]<span class="sc">:.1f}</span><span class="ss">%"</span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>best_row <span class="op">=</span> {</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>    use_batchnorm: <span class="bu">max</span>(</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>        (row <span class="cf">for</span> row <span class="kw">in</span> search_rows <span class="cf">if</span> row[<span class="st">"batchnorm"</span>] <span class="op">==</span> use_batchnorm),</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>        key<span class="op">=</span><span class="kw">lambda</span> row: row[<span class="st">"mean"</span>],</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> use_batchnorm <span class="kw">in</span> (<span class="va">False</span>, <span class="va">True</span>)</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>no BN    lr=0.003  validation=54.5% +/- 1.5%
no BN    lr=0.01   validation=68.9% +/- 0.5%
no BN    lr=0.03   validation=74.5% +/- 1.4%
no BN    lr=0.1    validation=78.8% +/- 1.9%
with BN  lr=0.003  validation=77.3% +/- 1.3%
with BN  lr=0.01   validation=79.1% +/- 1.2%
with BN  lr=0.03   validation=78.7% +/- 0.6%
with BN  lr=0.1    validation=77.6% +/- 1.7%</code></pre>
</div>
</div>
<p>Holding the recipe fixed does not produce one universal BatchNorm effect; it produces one estimate at each of the four predeclared learning rates. The paired BatchNorm-minus-no-BatchNorm validation differences are <span class="math inline">\(+22.800\)</span> points at 0.003 (sample SD <span class="math inline">\(1.643\)</span>), <span class="math inline">\(+10.200\)</span> at 0.01 (SD <span class="math inline">\(1.681\)</span>), <span class="math inline">\(+4.200\)</span> at 0.03 (SD <span class="math inline">\(1.681\)</span>), and <span class="math inline">\(-1.200\)</span> at 0.1 (SD <span class="math inline">\(3.402\)</span>). The dramatic low-rate contrast is one end of an interaction curve, not a privileged architecture-wide effect.</p>
<p>The learning-rate sweep changes the conclusion. The unnormalized MLP rises from 54.5% to a best mean of 78.8% at learning rate 0.1. The BatchNorm MLP peaks at 79.1% at learning rate 0.01. After equal, design-specific tuning, the validation gap is only 0.3 points — much smaller than the seed-to-seed standard deviations of 1.9 and 1.2 points. We have learned that BatchNorm changes which learning rates are usable. We have not learned that one design wins.</p>
<p>Only after those configurations are selected do we evaluate the shared test file. The endpoint check uses the predeclared fresh seed panel and makes no further design or hyperparameter choices; the checkpoint rule remains the one declared above.</p>
<div id="experiment-locked-endpoint" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code: evaluate the locked configurations on the shared endpoint</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>holdout <span class="op">=</span> torch.load(<span class="st">"../../data/fashion-test.pt"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>X_test <span class="op">=</span> holdout[<span class="st">"X"</span>].<span class="bu">float</span>().unsqueeze(<span class="dv">1</span>) <span class="op">/</span> <span class="fl">255.0</span>   <span class="co"># (600, 1, 28, 28)</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>y_test <span class="op">=</span> holdout[<span class="st">"y"</span>]                                <span class="co"># (600,)</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>audit_seeds <span class="op">=</span> <span class="bu">tuple</span>(<span class="bu">range</span>(<span class="dv">6060</span>, <span class="dv">6065</span>))</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>audit: <span class="bu">dict</span>[<span class="bu">bool</span>, <span class="bu">dict</span>[<span class="bu">str</span>, <span class="bu">float</span> <span class="op">|</span> Tensor]] <span class="op">=</span> {}</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> use_batchnorm <span class="kw">in</span> (<span class="va">False</span>, <span class="va">True</span>):</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    learning_rate <span class="op">=</span> <span class="bu">float</span>(best_row[use_batchnorm][<span class="st">"learning_rate"</span>])</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    test_scores <span class="op">=</span> torch.tensor([</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>        run_once(</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>            seed, use_batchnorm, learning_rate, endpoint<span class="op">=</span>(X_test, y_test)</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>        )[<span class="dv">1</span>]</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> seed <span class="kw">in</span> audit_seeds</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>    ])</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>    audit[use_batchnorm] <span class="op">=</span> {</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>        <span class="st">"learning_rate"</span>: learning_rate,</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>        <span class="st">"scores"</span>: test_scores,</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>        <span class="st">"mean"</span>: test_scores.mean().item(),</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>        <span class="st">"sd"</span>: test_scores.std(unbiased<span class="op">=</span><span class="va">True</span>).item(),</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>    label <span class="op">=</span> <span class="st">"with BN"</span> <span class="cf">if</span> use_batchnorm <span class="cf">else</span> <span class="st">"no BN  "</span></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>label<span class="sc">}</span><span class="ss">  locked lr=</span><span class="sc">{</span>learning_rate<span class="sc">:&lt;4}</span><span class="ss">  "</span></span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"test=</span><span class="sc">{</span><span class="dv">100</span> <span class="op">*</span> audit[use_batchnorm][<span class="st">'mean'</span>]<span class="sc">:.1f}</span><span class="ss">% "</span></span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"+/- </span><span class="sc">{</span><span class="dv">100</span> <span class="op">*</span> audit[use_batchnorm][<span class="st">'sd'</span>]<span class="sc">:.1f}</span><span class="ss">%"</span></span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>scores_by_rate <span class="op">=</span> {</span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>    (<span class="bu">bool</span>(row[<span class="st">"batchnorm"</span>]), <span class="bu">float</span>(row[<span class="st">"learning_rate"</span>])): row[<span class="st">"scores"</span>]</span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> row <span class="kw">in</span> search_rows</span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a>fixed_rate_contrasts <span class="op">=</span> {</span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a>    learning_rate: (</span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a>        scores_by_rate[(<span class="va">True</span>, learning_rate)]</span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a>        <span class="op">-</span> scores_by_rate[(<span class="va">False</span>, learning_rate)]</span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> learning_rate <span class="kw">in</span> learning_rates</span>
<span id="cb4-38"><a href="#cb4-38" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb4-39"><a href="#cb4-39" aria-hidden="true" tabindex="-1"></a>paired_contrasts <span class="op">=</span> {</span>
<span id="cb4-40"><a href="#cb4-40" aria-hidden="true" tabindex="-1"></a>    <span class="op">**</span>{<span class="ss">f"shared lr=</span><span class="sc">{</span>rate<span class="sc">:g}</span><span class="ss">"</span>: values</span>
<span id="cb4-41"><a href="#cb4-41" aria-hidden="true" tabindex="-1"></a>       <span class="cf">for</span> rate, values <span class="kw">in</span> fixed_rate_contrasts.items()},</span>
<span id="cb4-42"><a href="#cb4-42" aria-hidden="true" tabindex="-1"></a>    <span class="st">"tuned validation"</span>: best_row[<span class="va">True</span>][<span class="st">"scores"</span>] <span class="op">-</span> best_row[<span class="va">False</span>][<span class="st">"scores"</span>],</span>
<span id="cb4-43"><a href="#cb4-43" aria-hidden="true" tabindex="-1"></a>    <span class="st">"locked endpoint"</span>: audit[<span class="va">True</span>][<span class="st">"scores"</span>] <span class="op">-</span> audit[<span class="va">False</span>][<span class="st">"scores"</span>],</span>
<span id="cb4-44"><a href="#cb4-44" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb4-45"><a href="#cb4-45" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"paired BN - no-BN contrasts"</span>)</span>
<span id="cb4-46"><a href="#cb4-46" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> label, contrasts <span class="kw">in</span> paired_contrasts.items():</span>
<span id="cb4-47"><a href="#cb4-47" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(</span>
<span id="cb4-48"><a href="#cb4-48" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>label<span class="sc">:&lt;20}</span><span class="ss"> mean=</span><span class="sc">{</span><span class="dv">100</span> <span class="op">*</span> contrasts<span class="sc">.</span>mean()<span class="sc">:+.3f}</span><span class="ss"> pp  "</span></span>
<span id="cb4-49"><a href="#cb4-49" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"SD=</span><span class="sc">{</span><span class="dv">100</span> <span class="op">*</span> contrasts<span class="sc">.</span>std(unbiased<span class="op">=</span><span class="va">True</span>)<span class="sc">:.3f}</span><span class="ss"> pp"</span></span>
<span id="cb4-50"><a href="#cb4-50" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>no BN    locked lr=0.1   test=78.1% +/- 0.7%
with BN  locked lr=0.01  test=76.9% +/- 0.9%
paired BN - no-BN contrasts
shared lr=0.003      mean=+22.800 pp  SD=1.643 pp
shared lr=0.01       mean=+10.200 pp  SD=1.681 pp
shared lr=0.03       mean=+4.200 pp  SD=1.681 pp
shared lr=0.1        mean=-1.200 pp  SD=3.402 pp
tuned validation     mean=+0.300 pp  SD=1.095 pp
locked endpoint      mean=-1.267 pp  SD=1.146 pp</code></pre>
</div>
</div>
<p>The endpoint means are 78.1% without BatchNorm and 76.9% with it. The ordering—not only the gap—reversed. That reversal does not prove that removing BatchNorm is better. It tells us the honest thing: a 0.3-point validation separation in this small search was not sufficient to support a winner. The strongest conclusion is about <strong>interaction</strong> — BatchNorm and learning rate must be interpreted together — and about the limits of the experiment.</p>
<p>Because the arms share seeds, the paired contrasts are the sharper summaries. Across the four shared learning rates, the contrast slides from <span class="math inline">\(+22.800\)</span> to <span class="math inline">\(-1.200\)</span> points. After each design is tuned separately it is <span class="math inline">\(+0.300\)</span> points (paired sample SD <span class="math inline">\(1.095\)</span>), and at the locked endpoint it is <span class="math inline">\(-1.267\)</span> (SD <span class="math inline">\(1.146\)</span>). Marginal arm spreads answer a different question; the code preserves both.</p>
<div id="cell-fig-experiment-estimands" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code: all shared-rate, tuned, and locked-endpoint contrasts</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="fl">8.2</span>, <span class="fl">3.4</span>))</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>colors <span class="op">=</span> {<span class="va">False</span>: <span class="st">"#232D4B"</span>, <span class="va">True</span>: <span class="st">"#E57200"</span>}</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> use_batchnorm <span class="kw">in</span> (<span class="va">False</span>, <span class="va">True</span>):</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    rows <span class="op">=</span> [row <span class="cf">for</span> row <span class="kw">in</span> search_rows <span class="cf">if</span> row[<span class="st">"batchnorm"</span>] <span class="op">==</span> use_batchnorm]</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">0</span>].errorbar(</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>        [<span class="bu">float</span>(row[<span class="st">"learning_rate"</span>]) <span class="cf">for</span> row <span class="kw">in</span> rows],</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>        [<span class="dv">100</span> <span class="op">*</span> <span class="bu">float</span>(row[<span class="st">"mean"</span>]) <span class="cf">for</span> row <span class="kw">in</span> rows],</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>        yerr<span class="op">=</span>[<span class="dv">100</span> <span class="op">*</span> <span class="bu">float</span>(row[<span class="st">"sd"</span>]) <span class="cf">for</span> row <span class="kw">in</span> rows],</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>        marker<span class="op">=</span><span class="st">"o"</span>,</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>        capsize<span class="op">=</span><span class="dv">3</span>,</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>        lw<span class="op">=</span><span class="dv">2</span>,</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span>colors[use_batchnorm],</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>        label<span class="op">=</span><span class="st">"with BatchNorm"</span> <span class="cf">if</span> use_batchnorm <span class="cf">else</span> <span class="st">"without BatchNorm"</span>,</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xscale(<span class="st">"log"</span>)</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xlabel(<span class="st">"learning rate"</span>)</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"validation accuracy (%)"</span>)</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">"the learning-rate interaction"</span>)</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].legend(fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>stages <span class="op">=</span> (</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>    <span class="st">"$</span><span class="ch">\\</span><span class="st">eta$=.003"</span>, <span class="st">"$</span><span class="ch">\\</span><span class="st">eta$=.01"</span>, <span class="st">"$</span><span class="ch">\\</span><span class="st">eta$=.03"</span>, <span class="st">"$</span><span class="ch">\\</span><span class="st">eta$=.1"</span>,</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>    <span class="st">"tuned</span><span class="ch">\n</span><span class="st">validation"</span>, <span class="st">"locked</span><span class="ch">\n</span><span class="st">endpoint"</span>,</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>stage_contrasts <span class="op">=</span> [</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>    <span class="op">*</span>[fixed_rate_contrasts[rate] <span class="cf">for</span> rate <span class="kw">in</span> learning_rates],</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>    paired_contrasts[<span class="st">"tuned validation"</span>],</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>    paired_contrasts[<span class="st">"locked endpoint"</span>],</span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a>contrast_means <span class="op">=</span> torch.tensor([</span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a>    <span class="dv">100</span> <span class="op">*</span> values.mean().item() <span class="cf">for</span> values <span class="kw">in</span> stage_contrasts</span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a>contrast_sds <span class="op">=</span> torch.tensor([</span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a>    <span class="dv">100</span> <span class="op">*</span> values.std(unbiased<span class="op">=</span><span class="va">True</span>).item() <span class="cf">for</span> values <span class="kw">in</span> stage_contrasts</span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb6-37"><a href="#cb6-37" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> torch.arange(<span class="bu">len</span>(stages), dtype<span class="op">=</span>torch.float32)</span>
<span id="cb6-38"><a href="#cb6-38" aria-hidden="true" tabindex="-1"></a>bar_colors <span class="op">=</span> [colors[<span class="va">True</span>] <span class="cf">if</span> value <span class="op">&gt;=</span> <span class="dv">0</span> <span class="cf">else</span> colors[<span class="va">False</span>]</span>
<span id="cb6-39"><a href="#cb6-39" aria-hidden="true" tabindex="-1"></a>              <span class="cf">for</span> value <span class="kw">in</span> contrast_means]</span>
<span id="cb6-40"><a href="#cb6-40" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].bar(x, contrast_means, yerr<span class="op">=</span>contrast_sds, capsize<span class="op">=</span><span class="dv">3</span>,</span>
<span id="cb6-41"><a href="#cb6-41" aria-hidden="true" tabindex="-1"></a>            color<span class="op">=</span>bar_colors)</span>
<span id="cb6-42"><a href="#cb6-42" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].axhline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">"0.25"</span>, lw<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb6-43"><a href="#cb6-43" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xticks(x, stages)</span>
<span id="cb6-44"><a href="#cb6-44" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].tick_params(axis<span class="op">=</span><span class="st">"x"</span>, labelsize<span class="op">=</span><span class="dv">7</span>)</span>
<span id="cb6-45"><a href="#cb6-45" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_ylabel(<span class="st">"BN $-$ no-BN accuracy (pp)"</span>)</span>
<span id="cb6-46"><a href="#cb6-46" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">"the paired answer changes"</span>)</span>
<span id="cb6-47"><a href="#cb6-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-48"><a href="#cb6-48" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb6-49"><a href="#cb6-49" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-experiment-estimands" class="quarto-float quarto-figure quarto-figure-center anchored" alt="The left panel plots validation accuracy against learning rate for MLPs with and without BatchNorm; their curves cross and peak at different rates. The right panel shows paired BatchNorm-minus-no-BatchNorm differences falling from strongly positive at the lowest shared rate to slightly negative at the highest, nearly zero after separate tuning, and negative on the reused held-out endpoint.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-experiment-estimands-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="learning-by-experiment_files/figure-html/fig-experiment-estimands-output-1.png" alt="The left panel plots validation accuracy against learning rate for MLPs with and without BatchNorm; their curves cross and peak at different rates. The right panel shows paired BatchNorm-minus-no-BatchNorm differences falling from strongly positive at the lowest shared rate to slightly negative at the highest, nearly zero after separate tuning, and negative on the reused held-out endpoint." width="778" height="316" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-experiment-estimands-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: One experiment, several estimands. Left: mean validation accuracy across all four predeclared learning rates; bars show one sample standard deviation over five paired search seeds. Right: paired BatchNorm-minus-no-BatchNorm contrasts at every shared rate, after separate validation tuning, and on the locked shared endpoint. These error bars are sample standard deviations across seeds, not confidence intervals.
</figcaption>
</figure>
</div>
</div>
</div>
<!-- /NOVEL -->
</section>
<section id="ablation-is-an-argument-about-cause" class="level2">
<h2 class="anchored" data-anchor-id="ablation-is-an-argument-about-cause">Ablation is an argument about cause</h2>
<p>An <strong>ablation</strong> — a deliberate removal or substitution — asks whether a component mattered. A useful ablation has five pieces:</p>
<ol type="1">
<li><strong>Baseline:</strong> the complete system against which we compare.</li>
<li><strong>Hypothesis:</strong> the mechanism we believe the component provides.</li>
<li><strong>Intervention:</strong> the smallest change that tests that mechanism.</li>
<li><strong>Outcome:</strong> a predeclared metric, not whichever curve looks favorable afterward.</li>
<li><strong>Scope:</strong> the data, training protocol, seeds, and budget within which the claim holds.</li>
</ol>
<p>“One change at a time” is the right opening discipline because it preserves attribution. If we remove BatchNorm and change the learning rate simultaneously, the raw difference cannot tell us which change produced it. Our worked example also shows why one-at-a-time is not the end of the story: components can interact.</p>
<p>Suppose <span class="math inline">\(Y_{bd}\)</span> is the mean score with BatchNorm indicator <span class="math inline">\(b\in\{0,1\}\)</span> and dropout indicator <span class="math inline">\(d\in\{0,1\}\)</span>. The BatchNorm effect without dropout is <span class="math inline">\(Y_{10}-Y_{00}\)</span>; with dropout it is <span class="math inline">\(Y_{11}-Y_{01}\)</span>. Their difference is the interaction:</p>
<p><span id="eq-ablation-interaction"><span class="math display">\[
I=(Y_{11}-Y_{01})-(Y_{10}-Y_{00}).
\tag{5}\]</span></span></p>
<p>If <span class="math inline">\(I\)</span> is far from zero relative to run-to-run variation, the effect of one component depends on the other. A <span class="math inline">\(2\times2\)</span> design reveals that dependence; two isolated removals do not. This is why an ablation table should be read as a small factorial experiment, not as a shopping list of individually useful parts.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Do not ablate a broken contender
</div>
</div>
<div class="callout-body-container callout-body">
<p>If a variant cannot overfit one small batch, produces chance accuracy, or diverges under every reasonable learning rate, diagnose it before interpreting the ablation. A wiring error is not evidence against an idea. First make each contender train; then decide whether the claim calls for a shared recipe or equal tuning opportunity.</p>
</div>
</div>
</section>
<section id="hyperparameter-optimization-is-a-budgeted-outer-loop" class="level2">
<h2 class="anchored" data-anchor-id="hyperparameter-optimization-is-a-budgeted-outer-loop">Hyperparameter optimization is a budgeted outer loop</h2>
<p>Hyperparameter optimization (HPO) chooses the training configuration using validation performance. It is a nested problem:</p>
<p><span id="eq-hpo-objective"><span class="math display">\[
\widehat{\vect{\lambda}}(a)
=\argmax_{\vect{\lambda}\in\Lambda(a)}
\frac{1}{|\mathcal{S}_{\mathrm{search}}|}
\sum_{s\in\mathcal{S}_{\mathrm{search}}}
J_{\mathrm{val}}(a,\vect{\lambda},s,b),
\tag{6}\]</span></span></p>
<p>while each term still requires the inner training in <a href="#eq-experiment-train" class="quarto-xref">Equation&nbsp;<span>1</span></a>. There is usually no useful gradient through that whole procedure. Every evaluation — one point in the outer search — costs a training run, observations are noisy, and the search space mixes continuous, discrete, and categorical choices. HPO is therefore not “turn every knob.” It is experimental design under a budget.</p>
<section id="choose-the-space-before-choosing-the-algorithm" class="level3">
<h3 class="anchored" data-anchor-id="choose-the-space-before-choosing-the-algorithm">Choose the space before choosing the algorithm</h3>
<p>Three habits buy more than a fashionable search package:</p>
<ul>
<li>Search multiplicative quantities such as learning rate and weight decay on a <strong>logarithmic scale</strong>. The meaningful move is often <span class="math inline">\(10^{-3}\rightarrow10^{-2}\)</span>, not <span class="math inline">\(0.001\rightarrow0.002\)</span>.</li>
<li>Bound the space using the model, data scale, and sanity runs. A search over values known to diverge is not thorough; it is waste.</li>
<li>Record conditional choices. Momentum has meaning for an optimizer that uses it; the number should not silently survive when the optimizer family changes.</li>
</ul>
<p>For a small discrete space, a grid is transparent. In a higher-dimensional space where only a few knobs strongly affect the score, random search explores more distinct values along each important dimension for the same number of trials. Adaptive search uses earlier outcomes to choose later trials. None rescues a badly designed space.</p>
</section>
<section id="spend-small-budgets-before-large-ones" class="level3">
<h3 class="anchored" data-anchor-id="spend-small-budgets-before-large-ones">Spend small budgets before large ones</h3>
<p>When partial learning curves are informative, <strong>successive halving</strong> starts many configurations cheaply, keeps a fraction, and increases the survivors’ budgets. For example, 27 configurations run for one epoch, nine continue to a cumulative three, three continue to nine, and one continues to 27. With resumed checkpoints, the cost is <span class="math inline">\(27+9(2)+3(6)+1(18)=81\)</span> epoch-units. Training all 27 for 27 epochs would cost 729.</p>
<p>The saving comes with an assumption: early rank predicts late rank well enough. A slow-starting configuration can be pruned before its advantage appears. Pruning policy is therefore part of the method and must be logged. In sequence models later in the book, early curves can cross; “losing at epoch three” and “inferior after convergence” are not synonyms.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>A practical search order
</div>
</div>
<div class="callout-body-container callout-body">
<p>Sanity check <span class="math inline">\(\rightarrow\)</span> broad, short search <span class="math inline">\(\rightarrow\)</span> narrow, longer search <span class="math inline">\(\rightarrow\)</span> lock the configuration <span class="math inline">\(\rightarrow\)</span> fresh-seed audit. If the broad search ends on a boundary, expand that boundary before declaring an optimum.</p>
</div>
</div>
<p>Search can also have more than one objective. Accuracy, latency, memory, and model size may trade against one another. In that case there may be no single winner, only a <strong>Pareto frontier</strong>: designs for which improving one objective requires worsening another. State the operating constraint before selecting a point from that frontier.</p>
</section>
</section>
<section id="train-validation-and-test-have-different-jobs" class="level2">
<h2 class="anchored" data-anchor-id="train-validation-and-test-have-different-jobs">Train, validation, and test have different jobs</h2>
<p>The three-way split is not ceremonial:</p>
<ul>
<li>The <strong>training set</strong> supplies gradients and fits <span class="math inline">\(\vect{w}\)</span>.</li>
<li>The <strong>validation set</strong> supplies decisions: learning rate, architecture, checkpoint, early stopping, and search-space revisions.</li>
<li>The <strong>test set</strong> audits the locked procedure after those decisions are complete.</li>
</ul>
<p>Every look at validation is information. After hundreds of trials, the winning configuration may partly fit quirks of that finite validation set — this is <strong>validation overtuning</strong>. A larger search budget can improve the chosen validation score while making the score a more optimistic estimate of future performance. Keep a test set sealed, and for high-stakes comparisons consider nested resampling or a fresh external audit.</p>
<p>The test set — the only split not used for decisions — is not a second validation set. If the test result disappoints and we return to change the model, that test set has joined the development process. It can still be useful, but it is no longer an untouched audit for the revised procedure.</p>
</section>
<section id="seeds-are-a-panel-not-decoration" class="level2">
<h2 class="anchored" data-anchor-id="seeds-are-a-panel-not-decoration">Seeds are a panel, not decoration</h2>
<p>Random initialization, batch order, dropout masks, and other stochastic choices can change the outcome. A seed helps make one run reproducible; it does not make the training procedure deterministic in meaning. The scientific target is usually an expectation over plausible runs, so we need a panel.</p>
<p>For a controlled comparison, use the same seed set and data split in both arms. Then report the per-seed differences as well as the means. This <strong>paired-seed</strong> design often removes background variation: if seed 6052 is difficult for both models, that shared difficulty does not masquerade as a design effect.</p>
<p>Be precise about the uncertainty summary:</p>
<ul>
<li>A <strong>sample standard deviation across seeds</strong> describes run-to-run spread in the chosen seed panel.</li>
<li>It is not automatically a confidence interval for a population mean.</li>
<li>Five seeds can expose a fragile ranking; they do not turn a toy subset into a broad benchmark.</li>
<li>Never infer an average stochastic effect from one seed. A labeled one-seed mechanism demonstration is still useful when the claim stays that narrow.</li>
</ul>
<p>Our Fashion-MNIST figure follows this discipline. Its error bars are sample standard deviations, and its conclusion is deliberately calibrated to a CPU-scale teaching regime.</p>
</section>
<section id="the-experiment-ledger" class="level2">
<h2 class="anchored" data-anchor-id="the-experiment-ledger">The experiment ledger</h2>
<p>If a result cannot be reconstructed, it is an anecdote. At minimum, each run should preserve:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Record</th>
<th>Why it matters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Question and hypothesis</td>
<td>Prevents the metric from inventing the story afterward</td>
</tr>
<tr class="even">
<td>Code revision</td>
<td>Distinguishes an algorithmic change from a software change</td>
</tr>
<tr class="odd">
<td>Data version and split seed</td>
<td>Makes leakage and split drift auditable</td>
</tr>
<tr class="even">
<td>Design and full configuration</td>
<td>Reconstructs both the outer and inner choices</td>
</tr>
<tr class="odd">
<td>Training seed and budget</td>
<td>Defines the stochastic run and resources spent</td>
</tr>
<tr class="even">
<td>Metric definition and checkpoint rule</td>
<td>Prevents silent changes in what “best” means</td>
</tr>
<tr class="odd">
<td>Curves, final values, and failures</td>
<td>Keeps inconvenient trials in the evidence</td>
</tr>
<tr class="even">
<td>Software and execution environment</td>
<td>Explains numerical and performance differences</td>
</tr>
</tbody>
</table>
<p>Do not overwrite failed runs. A divergence at learning rate 0.1 defines the boundary of a search space; deleting it makes the next search less informed. Give every run a stable identifier, save the resolved configuration rather than only the defaults, and attach plots to data rather than to memory.</p>
<p>This is also good coding hygiene. Separate data loading, model construction, training, and evaluation so a sweep changes configuration rather than copying a notebook. Assert tensor shapes, evaluate under the correct model mode, and stop immediately on a NaN. The experiment manager can automate launches and logging later; it cannot decide what the comparison means.</p>
</section>
<section id="a-protocol-for-the-rest-of-this-book" class="level2">
<h2 class="anchored" data-anchor-id="a-protocol-for-the-rest-of-this-book">A protocol for the rest of this book</h2>
<p>When the book claims that one idea matters, read the claim through this sequence:</p>
<ol type="1">
<li><strong>Name the question.</strong> Mechanism, fixed-protocol effect, tuned performance, or benchmark?</li>
<li><strong>Debug before searching.</strong> Check shapes, chance baselines, and whether the model can overfit one small batch.</li>
<li><strong>Declare the contract.</strong> Split, metric, seed panel, budget, search space, and selection rule.</li>
<li><strong>Run the smallest decisive comparison.</strong> A good experiment isolates the question before scaling it.</li>
<li><strong>Inspect interactions.</strong> If the result changes across learning rates or companion components, say so and test the relevant grid.</li>
<li><strong>Lock, then audit.</strong> Select on validation; evaluate the locked procedure with fresh seeds on the sealed test set.</li>
<li><strong>Report the scope.</strong> Means, spread, failures, resources, and what the experiment did not establish.</li>
</ol>
<p>This protocol will return repeatedly. The optimizer race in Chapter 4 is a fixed recipe, so it describes that recipe. Chapter 6 uses one seeded sweep as a mechanism demonstration, not a scaling law. The CNN rematch asks whether architectural bias survives a paired shift test. Later, attention and positional encoding receive explicit ablations. The point is not to make every chapter a publication-scale benchmark. It is to make every conclusion no larger than its evidence.</p>
</section>
<section id="okay-so-tune-the-contender-ablate-the-claim" class="level2">
<h2 class="anchored" data-anchor-id="okay-so-tune-the-contender-ablate-the-claim">Okay, so — tune the contender, ablate the claim</h2>
<ol type="1">
<li><strong>Weights and hyperparameters live in different loops.</strong> The optimizer learns weights inside a run; we learn about designs across runs.</li>
<li><strong>Begin with an estimand.</strong> A fixed recipe and a tuned-per-design comparison answer different questions, so “fair” must be defined rather than assumed.</li>
<li><strong>Ablation tests a claim.</strong> Baseline, hypothesis, intervention, outcome, and scope turn a removal into an argument; factorial comparisons reveal interactions.</li>
<li><strong>HPO spends a declared budget.</strong> Search space, sampling rule, pruning, seeds, and per-run resources are part of the result.</li>
<li><strong>Validation chooses; test audits.</strong> Repeated validation queries can overfit, and a disappointing test result cannot be tuned away while keeping the same test set sealed.</li>
<li><strong>Seed spread calibrates the prose.</strong> Report the panel honestly, distinguish standard deviation from a confidence interval, and keep conclusions inside the tested regime.</li>
</ol>
</section>
<section id="sources-and-further-reading" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="sources-and-further-reading">Sources and further reading</h2>
<ul>
<li>Instructor lecture, <em>Hyperparameter Optimization and Ablation Studies</em>, live session transcript (September 18, 2025), and the sanitized lecture snapshot <code>sources/3-HPO-experimentation.tex</code>. These supply the empirical-science framing, candidate-interview analogy, two-level HPO/ablation workflow, interaction example, log-scale search, multi-fidelity intuition, and experiment-tracking emphasis.</li>
<li>Bergstra and Bengio, <a href="https://www.jmlr.org/papers/v13/bergstra12a.html">“Random Search for Hyper-Parameter Optimization”</a> (JMLR 2012), the primary source for random search’s marginal-coverage argument.</li>
<li>Li et al., <a href="https://www.jmlr.org/papers/v18/16-558.html">“Hyperband: A Novel Bandit-Based Approach to Hyperparameter Optimization”</a> (JMLR 2018), the primary source for budgeted successive-halving brackets.</li>
<li>Cawley and Talbot, <a href="https://www.jmlr.org/papers/v11/cawley10a.html">“On Over-fitting in Model Selection and Subsequent Selection Bias in Performance Evaluation”</a> (JMLR 2010), a primary treatment of selection-induced optimism.</li>
</ul>
</section>
<section id="exercises" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercises">Exercises</h2>
<ol type="1">
<li><strong>(Pencil.)</strong> A paper compares two optimizers under one learning rate and claims that optimizer A is intrinsically better. Write the fixed-protocol estimand it actually estimated, then write a tuned estimand that would support the broader claim. Which additional budget must the paper report?</li>
<li><strong>(Code.)</strong> Extend the worked experiment to learning rates 0.001 and 0.3 without changing any other choice. Do the selected rates land on a search boundary? Report the new validation table, but do not reinterpret the already-opened test set as a fresh audit.</li>
<li><strong>(Code.)</strong> Add dropout as a second binary factor and run the <span class="math inline">\(2\times2\)</span> fixed-recipe design over paired seeds. Compute <a href="#eq-ablation-interaction" class="quarto-xref">Equation&nbsp;<span>5</span></a>. Then tune the learning rate for each cell and explain why the two interaction estimates answer different questions.</li>
<li><strong>(Code.)</strong> On a synthetic classification problem, compare a nine-point grid with nine random configurations over learning rate and weight decay. Repeat the entire search across several search seeds. Plot both the best-so-far curve and its spread; do not decide the winner from one search seed.</li>
<li><strong>(Paper audit.)</strong> Choose one ablation table from a deep-learning paper. For each row, record the hypothesis, intervention, training recipe, tuning opportunity, seed count, and uncertainty summary. State the narrowest conclusion the evidence supports and one interaction the table cannot reveal.</li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/shakeri-lab\.github\.io\/dl-book\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../chapters/part1/06-generalization-inductive-bias.html" class="pagination-link" aria-label="When It Fails: Generalization in Pictures, and Inductive Bias">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">When It Fails: Generalization in Pictures, and Inductive Bias</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/part2/07-filters-convolution.html" class="pagination-link" aria-label="Filters and Convolution (Fixed Kernels)">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Filters and Convolution (Fixed Kernels)</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Heman Shakeri · Text CC BY-NC-SA 4.0 · Code MIT · School of Data Science, University of Virginia</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/Shakeri-Lab/dl-book/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Companion to <a href="https://shakeri-lab.github.io/dl-course-site/">DS 6050 Deep Learning</a></p>
</div>
  </div>
</footer>




</body></html>