<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>8&nbsp; CNNs: Making the Filters Learnable – Deep Learning: Making It Learnable</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/part2/09-modern-cnns-transfer.html" rel="next">
<link href="../../chapters/part2/07-filters-convolution.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-2c6940bf2fa6cf01ae6e8f10fcb58cc9.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>
  // Book math macros — keep in sync with tex/macros.tex (PDF path).
  // MathJax reads this config because it is defined before the MathJax
  // script loads (Quarto places include-in-header above its math script).
  window.MathJax = {
    tex: {
      macros: {
        E: "\\mathbb{E}",
        Ex: "\\operatorname{E}",
        var: "\\operatorname{Var}",
        cov: "\\operatorname{Cov}",
        imp: "\\Rightarrow",
        argmax: "\\operatorname*{arg\\,max}",
        argmin: "\\operatorname*{arg\\,min}",
        norm: ["\\left\\lVert#1\\right\\rVert", 1],
        vect: ["\\boldsymbol{#1}", 1],
        matr: ["\\boldsymbol{#1}", 1],
        R: "\\mathbb{R}",
        dd: "\\mathrm{d}",
        loss: "\\mathcal{L}"
      }
    }
  };
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/part2/07-filters-convolution.html">Vision: Learning the Filters</a></li><li class="breadcrumb-item"><a href="../../chapters/part2/08-cnn.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">CNNs: Making the Filters Learnable</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Deep Learning: Making It Learnable</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/Shakeri-Lab/dl-book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">From Lines to Networks</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/01-linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Linear Regression, the Mother Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/02-logistic-softmax.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Linear Models that Classify: Logistic and Softmax</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/03-nonlinearity-mlp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Nonlinearity and the MLP</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/04-training-loss-sgd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Training: Loss and Stochastic Gradient Descent</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/05-backpropagation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Backpropagation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/06-generalization-inductive-bias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">When It Fails: Generalization in Pictures, and Inductive Bias</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/interludes/learning-by-experiment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Who Trains the Trainer? Learning by Experiment</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Vision: Learning the Filters</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/07-filters-convolution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Filters and Convolution (Fixed Kernels)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/08-cnn.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">CNNs: Making the Filters Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/09-modern-cnns-transfer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Modern CNNs and Transfer Learning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/interludes/making-pca-learnable.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Interlude: Making PCA Learnable</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Sequences</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part3/10-sequences-rnn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Sequences and Recurrence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part3/11-encoder-decoder.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Encoder–Decoder, Teacher Forcing, Beam Search</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Attention: Learning the Similarity</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/12-kernel-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Kernel Regression: Attention Before It Was Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/13-attention.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Attention: Making the Kernel Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/14-self-attention-transformer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Self-Attention and the Transformer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/15-bert-pretraining.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">The BERT Moment: Pretraining as the New Regime</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/16-vit-scaling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Vision Transformers and Scaling Laws</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">The Pretrained Era</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/17-peft-quantization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Adapting Pretrained Models: Prompting, PEFT, Quantization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/18-alignment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Alignment and RL Fine-Tuning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/19-generative.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Generative Models: From Codes to Samples</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/20-multimodal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Multimodal Learning: One Space, Two Views</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/epilogue.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Epilogue: The Question Is Yours</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a1-linear-algebra.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Linear Algebra and the SVD</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a2-tensors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Tensors in Practice</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a3-precision-performance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Numerical Precision and Hardware Efficiency</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a4-notation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Notation</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
<div class="quarto-sidebar-footer"><div class="sidebar-footer-item">
<p><a href="https://shakeri-lab.github.io/dl-book/#revision-notes">Revision notes</a></p>
</div></div></nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#nine-numbers-learned" id="toc-nine-numbers-learned" class="nav-link active" data-scroll-target="#nine-numbers-learned"><span class="header-section-number">8.1</span> Nine numbers, learned</a></li>
  <li><a href="#from-one-detector-to-a-layer-of-detectives" id="toc-from-one-detector-to-a-layer-of-detectives" class="nav-link" data-scroll-target="#from-one-detector-to-a-layer-of-detectives"><span class="header-section-number">8.2</span> From one detector to a layer of detectives</a></li>
  <li><a href="#padding-and-stride-the-bookkeeping-with-a-payoff" id="toc-padding-and-stride-the-bookkeeping-with-a-payoff" class="nav-link" data-scroll-target="#padding-and-stride-the-bookkeeping-with-a-payoff"><span class="header-section-number">8.3</span> Padding and stride: the bookkeeping with a payoff</a></li>
  <li><a href="#pooling-trading-exact-location-for-local-tolerance" id="toc-pooling-trading-exact-location-for-local-tolerance" class="nav-link" data-scroll-target="#pooling-trading-exact-location-for-local-tolerance"><span class="header-section-number">8.4</span> Pooling: trading exact location for local tolerance</a></li>
  <li><a href="#how-far-a-deep-neuron-sees" id="toc-how-far-a-deep-neuron-sees" class="nav-link" data-scroll-target="#how-far-a-deep-neuron-sees"><span class="header-section-number">8.5</span> How far a deep neuron sees</a></li>
  <li><a href="#lenet-the-whole-machine" id="toc-lenet-the-whole-machine" class="nav-link" data-scroll-target="#lenet-the-whole-machine"><span class="header-section-number">8.6</span> LeNet: the whole machine</a></li>
  <li><a href="#the-rematch" id="toc-the-rematch" class="nav-link" data-scroll-target="#the-rematch"><span class="header-section-number">8.7</span> The rematch</a></li>
  <li><a href="#one-sealed-test-check" id="toc-one-sealed-test-check" class="nav-link" data-scroll-target="#one-sealed-test-check"><span class="header-section-number">8.8</span> One sealed test check</a></li>
  <li><a href="#okay-so-the-kernel-became-learnable" id="toc-okay-so-the-kernel-became-learnable" class="nav-link" data-scroll-target="#okay-so-the-kernel-became-learnable"><span class="header-section-number">8.9</span> Okay, so — the kernel became learnable</a></li>
  <li><a href="#sources-and-further-reading" id="toc-sources-and-further-reading" class="nav-link" data-scroll-target="#sources-and-further-reading">Sources and further reading</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/Shakeri-Lab/dl-book/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/part2/07-filters-convolution.html">Vision: Learning the Filters</a></li><li class="breadcrumb-item"><a href="../../chapters/part2/08-cnn.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">CNNs: Making the Filters Learnable</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-08-cnn" class="quarto-section-identifier"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">CNNs: Making the Filters Learnable</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<!-- lecture-source: m04_lecture-4-convolutional-neural-networks-cnns_s6xDEvdz3tY.txt (spine #13–18),
     [coding]_m04_dl4-2-coding-up-your-first-cnn_Dprs8jH13GA.txt (code spine)
     seeds: sources/4.1-CNN.tex (§The Leap to Learning, §Building Blocks of a
            Convolutional Layer, §Pooling: Engineering Translation Invariance)
     note: sources/4.2-CNN-2.tex (efficiency principles, modern architectures) is
           @sec-09-modern-cnns-transfer material and is not used here. -->
<p>Chapter 7 closed on a question it had spent a whole chapter earning: we built a machine that is local, weight-shared, and translation-equivariant away from boundaries, with nine hand-picked numbers sitting inside it. Nine numbers <span class="math inline">\(\rightarrow\)</span> nine knobs <span class="math inline">\(\rightarrow\)</span> we have spent half a book tuning knobs against a loss.</p>
<p>So: declare the kernel a <strong>parameter</strong>. That single change is this chapter, and it is the whole revolution. Everything else here — channels, padding, stride, pooling — is the supporting cast that turns one learnable filter into a working network. By the end we will have assembled LeNet, the first great convolutional architecture, trained it on our garments, and re-run the cruelest experiment of <a href="../part1/06-generalization-inductive-bias.html" class="quarto-xref"><span>Chapter 6</span></a> to see what the inductive bias actually bought.</p>
<div id="setup" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Code: imports and the Fashion-MNIST subset</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.nn <span class="im">as</span> nn</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.nn.functional <span class="im">as</span> F</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>torch.manual_seed(<span class="dv">6050</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>development <span class="op">=</span> torch.load(<span class="st">"../../data/fashion-train.pt"</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>holdout <span class="op">=</span> torch.load(<span class="st">"../../data/fashion-test.pt"</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>X_dev <span class="op">=</span> development[<span class="st">"X"</span>].<span class="bu">float</span>().unsqueeze(<span class="dv">1</span>) <span class="op">/</span> <span class="fl">255.0</span>  <span class="co"># (1200, 1, 28, 28)</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>y_dev, classes <span class="op">=</span> development[<span class="st">"y"</span>], development[<span class="st">"classes"</span>]</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>X_test <span class="op">=</span> holdout[<span class="st">"X"</span>].<span class="bu">float</span>().unsqueeze(<span class="dv">1</span>) <span class="op">/</span> <span class="fl">255.0</span>     <span class="co"># (600, 1, 28, 28)</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>y_test <span class="op">=</span> holdout[<span class="st">"y"</span>]</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>split <span class="op">=</span> torch.randperm(<span class="bu">len</span>(X_dev), generator<span class="op">=</span>torch.Generator().manual_seed(<span class="dv">6050</span>))</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>fit_idx, val_idx <span class="op">=</span> split[:<span class="dv">1000</span>], split[<span class="dv">1000</span>:]</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>X_tr, y_tr <span class="op">=</span> X_dev[fit_idx], y_dev[fit_idx]      <span class="co"># (1000,1,28,28), (1000,)</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>X_val, y_val <span class="op">=</span> X_dev[val_idx], y_dev[val_idx]    <span class="co"># (200,1,28,28), (200,)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Note the shapes. In Part I we flattened every image into a 784-vector before the model ever saw it. That stops now: the images stay rectangular, and they pick up a <em>channel</em> dimension, for reasons that will occupy us shortly.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>The book’s batch convention: NCHW
</div>
</div>
<div class="callout-body-container callout-body">
<p>Throughout this book, every image <strong>batch</strong> uses PyTorch’s <strong>NCHW</strong> order: (batch, channels, height, width). A single grayscale batch is therefore shaped <code>(1, 1, 28, 28)</code>. <code>Conv2d</code> can also accept an unbatched <code>(C, H, W)</code> input, but keeping the batch dimension explicit makes downstream shapes predictable. The kernels of a conv layer live in a 4-D tensor too: (out-channels, in-channels, height, width). This bookkeeping is the single most common source of errors in convolutional code: when a shape error greets you, count dimensions before touching anything else. Chapter 7’s <code>conv2d</code> helper hid this with <code>x[None, None]</code>; from here on we handle it in the open.</p>
</div>
</div>
<section id="nine-numbers-learned" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="nine-numbers-learned"><span class="header-section-number">8.1</span> Nine numbers, learned</h2>
<p>Here is a game. I have a feature detector — one of Chapter 7’s zoo, but I won’t tell you which. I will only show you what it does: you hand it images, it hands back feature maps. Your job is to build a detector that matches it.</p>
<p>With the tools of Part I, this is not even hard. A kernel applied by <a href="07-filters-convolution.html#eq-crosscorr" class="quarto-xref">Equation&nbsp;<span>7.1</span></a> is just nine numbers entering a dot product <span class="math inline">\(\rightarrow\)</span> the output is differentiable with respect to those numbers <span class="math inline">\(\rightarrow\)</span> gradient descent applies. Start from a random kernel and run the loop we have run since Chapter 1: predict <span class="math inline">\(\rightarrow\)</span> measure <span class="math inline">\(\rightarrow\)</span> step.</p>
<div id="learn-kernel" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code: recover a mystery kernel by gradient descent</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>mystery <span class="op">=</span> torch.tensor([[<span class="op">-</span><span class="fl">1.</span>, <span class="fl">0.</span>, <span class="fl">1.</span>],</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>                        [<span class="op">-</span><span class="fl">2.</span>, <span class="fl">0.</span>, <span class="fl">2.</span>],</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>                        [<span class="op">-</span><span class="fl">1.</span>, <span class="fl">0.</span>, <span class="fl">1.</span>]])            <span class="co"># (don't peek)</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>imgs <span class="op">=</span> X_tr[:<span class="dv">256</span>]                                  <span class="co"># (256, 1, 28, 28)</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> torch.no_grad():</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    target <span class="op">=</span> F.conv2d(imgs, mystery[<span class="va">None</span>, <span class="va">None</span>])   <span class="co"># what the detector does</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>torch.manual_seed(<span class="dv">0</span>)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>K <span class="op">=</span> <span class="fl">0.1</span> <span class="op">*</span> torch.randn(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">3</span>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>K_init <span class="op">=</span> K.clone().squeeze()</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>K.requires_grad_(<span class="va">True</span>)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>lr <span class="op">=</span> <span class="fl">0.5</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> step <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">601</span>):</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    pred <span class="op">=</span> F.conv2d(imgs, K)                       <span class="co"># predict</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    loss <span class="op">=</span> F.mse_loss(pred, target)                <span class="co"># measure</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>    loss.backward()</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">with</span> torch.no_grad():                          <span class="co"># step</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>        K <span class="op">-=</span> lr <span class="op">*</span> K.grad</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>        K.grad.zero_()</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> step <span class="op">%</span> <span class="dv">200</span> <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"step </span><span class="sc">{</span>step<span class="sc">:3d}</span><span class="ss">   loss </span><span class="sc">{</span>loss<span class="sc">.</span>item()<span class="sc">:.2e}</span><span class="ss">"</span>)</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">learned kernel, rounded:</span><span class="ch">\n</span><span class="sc">{</span>K<span class="sc">.</span>detach()<span class="sc">.</span>squeeze()<span class="sc">.</span><span class="bu">round</span>(decimals<span class="op">=</span><span class="dv">2</span>)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"max |learned - mystery| = </span><span class="sc">{</span>(K.detach().squeeze() <span class="op">-</span> mystery)<span class="sc">.</span><span class="bu">abs</span>()<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>step   0   loss 1.37e+00
step 200   loss 5.53e-04
step 400   loss 4.80e-05
step 600   loss 4.42e-06

learned kernel, rounded:
tensor([[-1.0100, -0.0000,  1.0100],
        [-1.9800, -0.0100,  1.9900],
        [-1.0100,  0.0100,  1.0000]])
max |learned - mystery| = 0.018</code></pre>
</div>
</div>
<p>The loss falls more than five orders of magnitude, and the learned kernel is the vertical Sobel detector to within 0.02 in every entry. Gradient descent, given nothing but input–output pairs, has <em>reinvented</em> a filter that took computer-vision researchers years of squinting at image gradients to design.</p>
<div id="cell-fig-learned-kernel" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code: kernel before / after / truth</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">7</span>, <span class="fl">2.6</span>))</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>lim <span class="op">=</span> <span class="fl">2.2</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, k, title <span class="kw">in</span> <span class="bu">zip</span>(axes, [K_init, K.detach().squeeze(), mystery],</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>                        [<span class="st">"random start"</span>, <span class="st">"learned"</span>, <span class="st">"Sobel (truth)"</span>]):</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    im <span class="op">=</span> ax.imshow(k, cmap<span class="op">=</span><span class="st">"RdBu_r"</span>, vmin<span class="op">=-</span>lim, vmax<span class="op">=</span>lim)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    ax.set_title(title, fontsize<span class="op">=</span><span class="dv">10</span>)<span class="op">;</span> ax.set_xticks([])<span class="op">;</span> ax.set_yticks([])</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>fig.colorbar(im, ax<span class="op">=</span>axes, shrink<span class="op">=</span><span class="fl">0.8</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-learned-kernel" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Three three-by-three heatmaps compare a disordered random kernel, a learned signed pattern, and the vertical Sobel pattern. The learned and Sobel panels have nearly identical positive and negative columns.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-learned-kernel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08-cnn_files/figure-html/fig-learned-kernel-output-1.png" alt="Three three-by-three heatmaps compare a disordered random kernel, a learned signed pattern, and the vertical Sobel pattern. The learned and Sobel panels have nearly identical positive and negative columns." width="499" height="177" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-learned-kernel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.1: The mystery-detector game. Left: the random starting kernel. Middle: the kernel gradient descent found from input–output pairs alone. Right: the hand-crafted vertical Sobel detector from Chapter 7’s zoo. Nobody told the middle panel what an edge is.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>The pivot of Part II
</div>
</div>
<div class="callout-body-container callout-body">
<p>Read that cell again, because the entire deep-learning revolution in vision is that cell writ large. Chapter 7 ended with the bottleneck: hand-crafted kernels are limited to patterns a human can articulate in nine numbers — nobody can write down “cat ear.” The fix is not better articulation. It is to stop articulating: put the numbers on the gradient tape and let the task pull the detector it needs out of the data. <em>What if the template were learnable?</em> It is, and the machinery has been in our hands since Chapter 4.</p>
</div>
</div>
<p>Two honest disclaimers about the game, both of which make the real thing <em>more</em> remarkable, not less. First, the game was rigged: the target came from a known kernel, so a perfect answer existed and the loss surface was a clean convex bowl (the output is linear in <span class="math inline">\(V\)</span>, and squared error in a linear map is Chapter 1’s setting all over again). Second, and more important: <strong>in a real CNN, nobody supplies the target feature maps.</strong> The only supervision is the classification loss at the far end of the network. Blame flows backward through every layer — exactly the mechanics of <a href="../part1/05-backpropagation.html" class="quarto-xref"><span>Chapter 5</span></a> — and the kernels that emerge are whatever detectors the task itself demands. We chose Sobel here; a trained network might discover it needs something no one has named.</p>
<p>One backpropagation detail deserves a sentence, because it is the same fan-out rule we met in <a href="../part1/05-backpropagation.html" class="quarto-xref"><span>Chapter 5</span></a>. The <em>same</em> nine numbers are used at every position of the slide <span class="math inline">\(\rightarrow\)</span> every position contributes blame to the shared kernel. Those contributions accumulate, then the loss reduction supplies its scale; <code>F.mse_loss</code> with the default <code>reduction="mean"</code> averages over batch, channel, and spatial elements. Weight sharing is not just a parameter economy. At training time every patch of every image teaches the one shared template.</p>
</section>
<section id="from-one-detector-to-a-layer-of-detectives" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="from-one-detector-to-a-layer-of-detectives"><span class="header-section-number">8.2</span> From one detector to a layer of detectives</h2>
<p>One learnable kernel gives one feature map: one specialist, sweeping the image with one magnifying glass. But Chapter 7’s zoo already told us one specialist is not enough — vertical edges, horizontal edges, blobs, textures all carry information. So we hire a <em>team</em>. The lecture’s image is worth keeping: employ six detectives, each with a different expertise, each producing their own annotated map of the crime scene.</p>
<p>That is all the <strong>channel</strong> machinery is:</p>
<ul>
<li><strong>Out-channels: more detectives.</strong> A conv layer with 6 output channels owns 6 independent kernels and produces a stack of 6 feature maps.</li>
<li><strong>In-channels: detectives read the whole stack.</strong> The <em>next</em> layer’s input is that 6-deep stack, so each of its kernels grows a third dimension: a <span class="math inline">\(6 \times 5 \times
5\)</span> volume that looks at all six incoming maps <em>simultaneously</em> and sums the evidence into one output map, one bias per output channel at the end.</li>
</ul>
<p>For an input stack <span class="math inline">\(X\)</span> with <span class="math inline">\(C_{\text{in}}\)</span> channels, output map <span class="math inline">\(o\)</span> is</p>
<p><span id="eq-conv-layer"><span class="math display">\[
[H_o]_{i,j} \;=\; b_o \;+\; \sum_{c=1}^{C_{\text{in}}}\;
\sum_{a=-\Delta}^{\Delta}\;\sum_{b=-\Delta}^{\Delta}
[V_{o,c}]_{a,b}\,[X_c]_{i+a,\,j+b},
\tag{8.1}\]</span></span></p>
<p>which is <a href="07-filters-convolution.html#eq-crosscorr" class="quarto-xref">Equation&nbsp;<span>7.1</span></a> run once per input channel and summed — followed, as always since <a href="../part1/03-nonlinearity-mlp.html" class="quarto-xref"><span>Chapter 3</span></a>, by a nonlinearity. A convolutional layer is Chapter 3’s recipe with a structured linear map: dot products <span class="math inline">\(\rightarrow\)</span> add bias <span class="math inline">\(\rightarrow\)</span> ReLU. Nothing in the recipe changed; only the wiring of the linear part did.</p>
<div id="channels" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code: one grayscale image through two conv layers</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>conv1 <span class="op">=</span> nn.Conv2d(in_channels<span class="op">=</span><span class="dv">1</span>, out_channels<span class="op">=</span><span class="dv">6</span>, kernel_size<span class="op">=</span><span class="dv">5</span>, padding<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>conv2 <span class="op">=</span> nn.Conv2d(in_channels<span class="op">=</span><span class="dv">6</span>, out_channels<span class="op">=</span><span class="dv">16</span>, kernel_size<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> X_tr[:<span class="dv">1</span>]                                   <span class="co"># (1, 1, 28, 28): one garment</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>h1 <span class="op">=</span> F.relu(conv1(x))</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>h2 <span class="op">=</span> F.relu(conv2(h1))</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"input   </span><span class="sc">{</span><span class="bu">tuple</span>(x.shape)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"conv1   </span><span class="sc">{</span><span class="bu">tuple</span>(h1.shape)<span class="sc">}</span><span class="ss">   kernels: </span><span class="sc">{</span><span class="bu">tuple</span>(conv1.weight.shape)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"conv2   </span><span class="sc">{</span><span class="bu">tuple</span>(h2.shape)<span class="sc">}</span><span class="ss">  kernels: </span><span class="sc">{</span><span class="bu">tuple</span>(conv2.weight.shape)<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>input   (1, 1, 28, 28)
conv1   (1, 6, 28, 28)   kernels: (6, 1, 5, 5)
conv2   (1, 16, 24, 24)  kernels: (16, 6, 5, 5)</code></pre>
</div>
</div>
<p>Look at <code>conv2.weight</code>: sixteen kernels, each <span class="math inline">\(6 \times 5 \times 5\)</span>. This is where features start <em>composing</em>. Suppose detective 3 in the first layer is a vertical-edge expert and detective 5 hunts horizontal edges. A second-layer kernel that weights both maps positively in the same neighborhood fires precisely when both experts agree <span class="math inline">\(\rightarrow\)</span> a <strong>corner detector</strong>, built from evidence no single first-layer kernel could see. The cross-talk between channels is how edges become corners, corners become textures, and textures become parts. We promised this compositional ladder in Chapter 3; here is the hardware it runs on.</p>
<p>Chapter 7’s zoo can stage the story before any learning enters. Give the first layer two hand-crafted experts — vertical and horizontal edge energy — then hand-build one second-layer kernel that reads both reports at once:</p>
<div id="cell-fig-corner-detector" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code: a corner detector built from two edge experts</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>square <span class="op">=</span> torch.zeros(<span class="dv">28</span>, <span class="dv">28</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>square[<span class="dv">7</span>:<span class="dv">21</span>, <span class="dv">7</span>:<span class="dv">21</span>] <span class="op">=</span> <span class="fl">1.0</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>sobel_v <span class="op">=</span> torch.tensor([[<span class="op">-</span><span class="fl">1.</span>, <span class="fl">0.</span>, <span class="fl">1.</span>], [<span class="op">-</span><span class="fl">2.</span>, <span class="fl">0.</span>, <span class="fl">2.</span>], [<span class="op">-</span><span class="fl">1.</span>, <span class="fl">0.</span>, <span class="fl">1.</span>]])</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>v <span class="op">=</span> F.conv2d(square[<span class="va">None</span>, <span class="va">None</span>], sobel_v[<span class="va">None</span>, <span class="va">None</span>], padding<span class="op">=</span><span class="dv">1</span>).<span class="bu">abs</span>()</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>h <span class="op">=</span> F.conv2d(square[<span class="va">None</span>, <span class="va">None</span>], sobel_v.T.contiguous()[<span class="va">None</span>, <span class="va">None</span>], padding<span class="op">=</span><span class="dv">1</span>).<span class="bu">abs</span>()</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>experts <span class="op">=</span> torch.cat([v, h], dim<span class="op">=</span><span class="dv">1</span>)              <span class="co"># (1, 2, 28, 28): two reports</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>corner_k <span class="op">=</span> torch.full((<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">5</span>), <span class="dv">1</span> <span class="op">/</span> <span class="dv">50</span>)     <span class="co"># one kernel, spanning both</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>corners <span class="op">=</span> F.conv2d(experts, corner_k, padding<span class="op">=</span><span class="dv">2</span>).squeeze()</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">4</span>, figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="fl">2.5</span>))</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>panels <span class="op">=</span> [(square, <span class="st">"input"</span>), (v.squeeze(), <span class="st">"vertical-edge expert"</span>),</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>          (h.squeeze(), <span class="st">"horizontal-edge expert"</span>), (corners, <span class="st">"their reader: corners"</span>)]</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, (t, title) <span class="kw">in</span> <span class="bu">zip</span>(axes, panels):</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>    ax.imshow(t, cmap<span class="op">=</span><span class="st">"gray"</span>)<span class="op">;</span> ax.set_title(title, fontsize<span class="op">=</span><span class="dv">9</span>)<span class="op">;</span> ax.axis(<span class="st">"off"</span>)</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-corner-detector" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Four grayscale panels progress from a filled square to vertical-edge energy, horizontal-edge energy, and their combined response. Only the last panel concentrates its brightest responses at all four corners.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-corner-detector-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08-cnn_files/figure-html/fig-corner-detector-output-1.png" alt="Four grayscale panels progress from a filled square to vertical-edge energy, horizontal-edge energy, and their combined response. Only the last panel concentrates its brightest responses at all four corners." width="854" height="234" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-corner-detector-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.2: Cross-talk staged by hand. Two first-layer experts report edge energy (absolute Sobel response) on a square. One second-layer kernel spanning both channels (all-positive weights; <a href="#eq-conv-layer" class="quarto-xref">Equation&nbsp;<span>8.1</span></a> with two input channels) fires hardest exactly where both experts agree — the four corners, a feature neither channel could see alone.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The four brightest cells of the right panel are exactly the square’s four corners: a corner detector, assembled from experts that individually know nothing about corners. In a trained CNN, gradient descent builds combinations like this — and far stranger ones — on its own.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span><code>nn</code> versus <code>F</code>, appliances versus recipes
</div>
</div>
<div class="callout-body-container callout-body">
<p>The lecture’s analogy: <code>nn</code> modules are <em>appliances</em> — they have knobs and memory, and PyTorch carries their state around for you (<code>nn.Conv2d</code> owns its kernels and biases as <code>nn.Parameter</code>s, registered for autograd and visible to the optimizer). <code>F</code> functions are <em>recipes</em> — stateless, everything passed in by hand. In Chapter 7 the kernel was ours, so <code>F.conv2d</code> was the honest choice; now the kernel is the layer’s business, so <code>nn.Conv2d</code> is. Use appliances for anything with parameters, recipes for everything else (<code>F.relu</code>, <code>F.max_pool2d</code>).</p>
</div>
</div>
</section>
<section id="padding-and-stride-the-bookkeeping-with-a-payoff" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="padding-and-stride-the-bookkeeping-with-a-payoff"><span class="header-section-number">8.3</span> Padding and stride: the bookkeeping with a payoff</h2>
<p>Chapter 7 left an administrative debt: a <span class="math inline">\(k \times k\)</span> kernel on an <span class="math inline">\(n \times n\)</span> image yields only <span class="math inline">\((n-k+1) \times (n-k+1)\)</span> outputs, because the window must stay inside the frame. For one layer, a nuisance. For a <em>deep</em> stack, fatal: <span class="math inline">\(28 \rightarrow 24
\rightarrow 20 \rightarrow \cdots\)</span> and the feature map shrinks toward nothing, with edge pixels contributing to ever fewer windows along the way.</p>
<p>The fix is blunt: <strong>padding</strong>. Add a border of zeros around the input so the window can center itself on every real pixel. For a <span class="math inline">\(5 \times 5\)</span> kernel, a 2-pixel border returns exactly the input size <span class="math inline">\(\rightarrow\)</span> that is why <code>conv1</code> above says <code>padding=2</code>. Padding decouples “how deep can the network be” from “how fast do the maps shrink,” and that decoupling is what makes deep stacks possible at all.</p>
<p>Sometimes, though, we <em>want</em> to shrink — coarser maps mean less computation and a wider view per pixel. Then we shrink on purpose with <strong>stride</strong>: slide the window <span class="math inline">\(s\)</span> pixels at a time instead of one. Both knobs live in one formula, worth memorizing because you will run it in your head for every architecture you ever read:</p>
<p><span id="eq-outsize"><span class="math display">\[
n_{\text{out}} \;=\; \left\lfloor \frac{n + 2p - k}{s} \right\rfloor + 1 .
\tag{8.2}\]</span></span></p>
<p>The numerator is the padded length minus the window, i.e.&nbsp;how far the window can travel; dividing by the step and flooring counts the stops; <span class="math inline">\(+1\)</span> counts the starting position. The lecture’s three worked cases, verified:</p>
<div id="shapes" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code: the output-size formula, three regimes</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>x8 <span class="op">=</span> torch.randn(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">8</span>, <span class="dv">8</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> p, s <span class="kw">in</span> [(<span class="dv">0</span>, <span class="dv">1</span>), (<span class="dv">1</span>, <span class="dv">1</span>), (<span class="dv">1</span>, <span class="dv">2</span>)]:</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    out <span class="op">=</span> F.conv2d(x8, torch.randn(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">3</span>), padding<span class="op">=</span>p, stride<span class="op">=</span>s)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    n_out <span class="op">=</span> (<span class="dv">8</span> <span class="op">+</span> <span class="dv">2</span> <span class="op">*</span> p <span class="op">-</span> <span class="dv">3</span>) <span class="op">//</span> s <span class="op">+</span> <span class="dv">1</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"n=8, k=3, p=</span><span class="sc">{</span>p<span class="sc">}</span><span class="ss">, s=</span><span class="sc">{</span>s<span class="sc">}</span><span class="ss">:  formula </span><span class="sc">{</span>n_out<span class="sc">}</span><span class="ss">  torch </span><span class="sc">{</span><span class="bu">tuple</span>(out.shape[<span class="dv">2</span>:])<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>n=8, k=3, p=0, s=1:  formula 6  torch (6, 6)
n=8, k=3, p=1, s=1:  formula 8  torch (8, 8)
n=8, k=3, p=1, s=2:  formula 4  torch (4, 4)</code></pre>
</div>
</div>
</section>
<section id="pooling-trading-exact-location-for-local-tolerance" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="pooling-trading-exact-location-for-local-tolerance"><span class="header-section-number">8.4</span> Pooling: trading exact location for local tolerance</h2>
<p>Now for the deepest design decision in the network, and it starts from the asset Chapter 7 banked. Under matched boundary rules, convolution is equivariant on the interior: shift the garment, and every feature map shifts in lockstep. The detective’s map of clues faithfully tracks the scene. But the network’s final job is not mapping clues; it is a verdict. <em>Is this a trouser?</em> The answer must not depend on where the trouser stands. The feature-finding stage wants <strong>equivariance</strong> (where things are matters); the decision stage wants <strong>invariance</strong> (only what was found matters). Equivariance is what we have; invariance is what the classifier head needs <span class="math inline">\(\rightarrow\)</span> something must reduce sensitivity to location.</p>
<p>That converter is <strong>pooling</strong>. Slide a window over each feature map (no parameters this time) and summarize each neighborhood by one number:</p>
<ul>
<li><strong>Max pooling</strong> asks: <em>what is the strongest clue here?</em> Keep the loudest activation, discard the rest.</li>
<li><strong>Average pooling</strong> asks: <em>what is the general vibe of this neighborhood?</em> Smoother, but a single sharp clue gets diluted by quiet neighbors.</li>
</ul>
<div id="pooling" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Code: max and average pooling on a known grid</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>t <span class="op">=</span> torch.arange(<span class="fl">16.</span>).reshape(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">4</span>, <span class="dv">4</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"input:</span><span class="ch">\n</span><span class="sc">{</span>t<span class="sc">.</span>squeeze()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"max pool 2x2:</span><span class="ch">\n</span><span class="sc">{</span>F<span class="sc">.</span>max_pool2d(t, <span class="dv">2</span>)<span class="sc">.</span>squeeze()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"avg pool 2x2:</span><span class="ch">\n</span><span class="sc">{</span>F<span class="sc">.</span>avg_pool2d(t, <span class="dv">2</span>)<span class="sc">.</span>squeeze()<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>input:
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])
max pool 2x2:
tensor([[ 5.,  7.],
        [13., 15.]])
avg pool 2x2:
tensor([[ 2.5000,  4.5000],
        [10.5000, 12.5000]])</code></pre>
</div>
</div>
<p>The common configuration is the one above: <span class="math inline">\(2 \times 2\)</span> windows with stride 2, non-overlapping, halving each spatial dimension. Max is the default choice in practice, precisely because feature detection is about the strongest evidence, not the committee average.</p>
<p>How can this buy local tolerance? Start with a deliberately clean construction in which a shift becomes invisible:</p>
<div id="pool-invariance" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Code: one constructed shift that pooling cannot see</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>scene <span class="op">=</span> torch.zeros(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">4</span>, <span class="dv">4</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>scene[<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>] <span class="op">=</span> <span class="fl">9.0</span>        <span class="co"># a strong clue, upper-left region</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>scene[<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">2</span>, <span class="dv">2</span>] <span class="op">=</span> <span class="fl">3.0</span>        <span class="co"># a weaker clue, lower-right region</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>shifted <span class="op">=</span> torch.zeros_like(scene)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>shifted[<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>] <span class="op">=</span> <span class="fl">9.0</span>      <span class="co"># both clues moved one pixel right</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>shifted[<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">2</span>, <span class="dv">3</span>] <span class="op">=</span> <span class="fl">3.0</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"pooled original: </span><span class="sc">{</span>F<span class="sc">.</span>max_pool2d(scene,   <span class="dv">2</span>)<span class="sc">.</span>squeeze()<span class="sc">.</span>tolist()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"pooled shifted:  </span><span class="sc">{</span>F<span class="sc">.</span>max_pool2d(shifted, <span class="dv">2</span>)<span class="sc">.</span>squeeze()<span class="sc">.</span>tolist()<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>pooled original: [[9.0, 0.0], [0.0, 3.0]]
pooled shifted:  [[9.0, 0.0], [0.0, 3.0]]</code></pre>
</div>
</div>
<p>Both clues moved, yet these particular pooled maps are <em>identical</em>: each isolated maximum stayed inside its <span class="math inline">\(2 \times 2\)</span> window. That equality belongs to this construction, not to max pooling in general. A shift can change which values share a window, which maximum wins, or what crosses the boundary. Pooling can therefore buy local tolerance to jitter, but the amount depends on the activations and alignment; the end of this chapter measures it rather than assuming it.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Tolerance has a price tag
</div>
</div>
<div class="callout-body-container callout-body">
<p>Pooling can buy tolerance by <em>throwing away position</em>. After two rounds, the network knows a strong vertical edge exists in a region; it no longer knows exactly where. For classification this is the right trade — but it is a trade, and it will come due twice in this book. Deeper in Part II, tasks that need precise locations will have to be more careful with resolution. And in Part IV the tables turn completely: self-attention (<a href="../part4/14-self-attention-transformer.html" class="quarto-xref"><span>Chapter 14</span></a>) is so thoroughly position-agnostic that we will have to <em>pay to put position back in</em>. Remember, when we get there, that position was something we once discarded on purpose.</p>
</div>
</div>
</section>
<section id="how-far-a-deep-neuron-sees" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="how-far-a-deep-neuron-sees"><span class="header-section-number">8.5</span> How far a deep neuron sees</h2>
<p>There is one more consequence of stacking, and it quietly resolves the tension Chapter 6 left us with. Every kernel here is tiny — <span class="math inline">\(5 \times 5\)</span>, resolutely local. Yet recognizing a garment is a <em>global</em> judgment. Where does globality come from?</p>
<p>From depth. A neuron in the first feature map sees a <span class="math inline">\(5 \times 5\)</span> patch of the image: its <strong>receptive field</strong>. A neuron one layer up sees a <span class="math inline">\(5 \times 5\)</span> patch <em>of feature maps</em>, each pixel of which already summarizes a patch below <span class="math inline">\(\rightarrow\)</span> its receptive field on the original image is wider. Pooling accelerates this: after a <span class="math inline">\(2\times2\)</span>/stride-2 pool, neighboring pixels in the pooled map stand two original pixels apart, so every later window covers twice the ground. For our upcoming network the ledger reads: conv1 sees <span class="math inline">\(5 \times 5\)</span> <span class="math inline">\(\rightarrow\)</span> pooling nudges it to <span class="math inline">\(6 \times
6\)</span> <span class="math inline">\(\rightarrow\)</span> conv2’s <span class="math inline">\(5\times5\)</span> window, at stride-2 spacing, expands it to <span class="math inline">\(14
\times 14\)</span> <span class="math inline">\(\rightarrow\)</span> the final pool reaches <span class="math inline">\(16 \times 16\)</span> — over half the frame in every direction, from nothing but <span class="math inline">\(5 \times 5\)</span> looks.</p>
<div id="cell-fig-receptive-field" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>Code: receptive-field boxes on a garment</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.patches <span class="im">as</span> mpatches</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">4.2</span>, <span class="fl">3.6</span>))</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>ax.imshow(X_val[<span class="dv">1</span>, <span class="dv">0</span>], cmap<span class="op">=</span><span class="st">"gray"</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> size, color, lab <span class="kw">in</span> [(<span class="dv">5</span>, <span class="st">"#E57200"</span>, <span class="st">"conv1: 5×5"</span>),</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>                         (<span class="dv">14</span>, <span class="st">"#5379AA"</span>, <span class="st">"conv2: 14×14"</span>),</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>                         (<span class="dv">16</span>, <span class="st">"#DDA0DD"</span>, <span class="st">"pool2: 16×16"</span>)]:</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>    lo <span class="op">=</span> <span class="dv">14</span> <span class="op">-</span> size <span class="op">/</span> <span class="dv">2</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>    ax.add_patch(mpatches.Rectangle((lo, lo), size, size, fill<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>                                    lw<span class="op">=</span><span class="dv">2</span>, edgecolor<span class="op">=</span>color, label<span class="op">=</span>lab))</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>ax.legend(fontsize<span class="op">=</span><span class="dv">8</span>, loc<span class="op">=</span><span class="st">"center left"</span>, bbox_to_anchor<span class="op">=</span>(<span class="fl">1.02</span>, <span class="fl">0.5</span>))</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>ax.axis(<span class="st">"off"</span>)</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-receptive-field" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Three nested outline boxes are centered on one garment image. Their side lengths grow from five pixels at the first convolution to fourteen at the second convolution and sixteen after the final pool.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-receptive-field-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08-cnn_files/figure-html/fig-receptive-field-output-1.png" alt="Three nested outline boxes are centered on one garment image. Their side lengths grow from five pixels at the first convolution to fourteen at the second convolution and sixteen after the final pool." width="411" height="289" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-receptive-field-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.3: What one neuron sees, by depth. Boxes mark the receptive field of a single unit in each stage of our network, centered on the same spot: conv1 sees a 5×5 patch, conv2 sees 14×14, the final pooled cell 16×16. Local wiring, increasingly global sight; the dense head then reads all 25 such overlapping views at once.
</figcaption>
</figure>
</div>
</div>
</div>
<p>This is the compositional hierarchy of <a href="../part1/03-nonlinearity-mlp.html" class="quarto-xref"><span>Chapter 3</span></a> given a strong architectural invitation. The MLP <em>could</em> represent features-of-features but nothing encouraged it to; locality and growing receptive fields encourage later layers to compose earlier responses. Learned channels often progress from edge-like patterns to textures and parts, but the architecture does not force those human labels. The CNN buys global sight gradually, paying for it with depth; hold that thought until Part IV, where attention will buy global sight in a single step and pay for it differently (<a href="../part4/13-attention.html" class="quarto-xref"><span>Chapter 13</span></a>).</p>
</section>
<section id="lenet-the-whole-machine" class="level2" data-number="8.6">
<h2 data-number="8.6" class="anchored" data-anchor-id="lenet-the-whole-machine"><span class="header-section-number">8.6</span> LeNet: the whole machine</h2>
<p>Time to assemble. The canonical blueprint is <strong>LeNet</strong>, Yann LeCun’s digit-reading network, and its rhythm is the CNN design pattern to this day: <em>convolve, shrink, deepen; repeat; then decide.</em> Spatial size falls (28 <span class="math inline">\(\rightarrow\)</span> 14 <span class="math inline">\(\rightarrow\)</span> 5) while feature depth grows (1 <span class="math inline">\(\rightarrow\)</span> 6 <span class="math inline">\(\rightarrow\)</span> 16): the network trades “where” for “what” stage by stage, until a small dense head reads the final <span class="math inline">\(16 \times
5 \times 5\)</span> summary and votes.</p>
<div id="lenet" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>Code: LeNet</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> LeNet(nn.Module):</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>):</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.conv1 <span class="op">=</span> nn.Conv2d(<span class="dv">1</span>, <span class="dv">6</span>, <span class="dv">5</span>, padding<span class="op">=</span><span class="dv">2</span>)  <span class="co"># (N,1,28,28)-&gt;(N,6,28,28)</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.conv2 <span class="op">=</span> nn.Conv2d(<span class="dv">6</span>, <span class="dv">16</span>, <span class="dv">5</span>)            <span class="co"># (N,6,14,14)-&gt;(N,16,10,10)</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.fc1 <span class="op">=</span> nn.Linear(<span class="dv">16</span> <span class="op">*</span> <span class="dv">5</span> <span class="op">*</span> <span class="dv">5</span>, <span class="dv">120</span>)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.fc2 <span class="op">=</span> nn.Linear(<span class="dv">120</span>, <span class="dv">84</span>)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.fc3 <span class="op">=</span> nn.Linear(<span class="dv">84</span>, <span class="dv">10</span>)</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x: torch.Tensor) <span class="op">-&gt;</span> torch.Tensor:</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> F.max_pool2d(F.relu(<span class="va">self</span>.conv1(x)), <span class="dv">2</span>)   <span class="co"># -&gt; (N, 6, 14, 14)</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> F.max_pool2d(F.relu(<span class="va">self</span>.conv2(x)), <span class="dv">2</span>)   <span class="co"># -&gt; (N, 16, 5, 5)</span></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> x.flatten(<span class="dv">1</span>)                             <span class="co"># -&gt; (N, 400)</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> F.relu(<span class="va">self</span>.fc1(x))</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> F.relu(<span class="va">self</span>.fc2(x))</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">self</span>.fc3(x)                           <span class="co"># logits, (N, 10)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Every line is a tool we already own: <a href="#eq-conv-layer" class="quarto-xref">Equation&nbsp;<span>8.1</span></a> twice, <a href="#eq-outsize" class="quarto-xref">Equation&nbsp;<span>8.2</span></a> silently fixing <code>padding=2</code>, pooling twice, then Chapter 3’s MLP as the decision head — and, per Chapter 2’s advice, the model returns raw logits and lets <code>F.cross_entropy</code> handle the probabilities.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>LeNet, then and now
</div>
</div>
<div class="callout-body-container callout-body">
<p>The LeNet family (LeCun and colleagues, 1989–1998) began by reading handwritten ZIP codes for the US Postal Service, and its mature form, LeNet-5, went on to read a substantial share of America’s bank checks — convolutional networks were literally cashing checks decades before they were fashionable. Our variant keeps the classic skeleton but upgrades the internals with Part I’s verdicts: ReLU where the original used sigmoid-family activations (<a href="../part1/03-nonlinearity-mlp.html" class="quarto-xref"><span>Chapter 3</span></a>, <a href="../part1/05-backpropagation.html" class="quarto-xref"><span>Chapter 5</span></a>), max pooling where it used average-flavored subsampling, Adam as the optimizer. The lecture’s live session adds one more modern stabilizer, batch normalization, which we meet properly in <a href="09-modern-cnns-transfer.html" class="quarto-xref"><span>Chapter 9</span></a>.</p>
</div>
</div>
<p>Before training, the parameter audit — because parameter <em>economy</em> was half of Chapter 7’s sales pitch, and Chapter 6’s MLP is the yardstick:</p>
<div id="params" class="cell" data-execution_count="11">
<details class="code-fold">
<summary>Code: parameter audit, LeNet vs.&nbsp;Chapter 6’s MLP</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> make_mlp() <span class="op">-&gt;</span> nn.Sequential:</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> nn.Sequential(nn.Flatten(),</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>                         nn.Linear(<span class="dv">784</span>, <span class="dv">256</span>), nn.ReLU(), nn.Linear(<span class="dv">256</span>, <span class="dv">10</span>))</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>lenet, mlp <span class="op">=</span> LeNet(), make_mlp()</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, p <span class="kw">in</span> lenet.named_parameters():</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>name<span class="sc">:14s}</span><span class="ss"> </span><span class="sc">{</span><span class="bu">str</span>(<span class="bu">tuple</span>(p.shape))<span class="sc">:16s}</span><span class="ss"> </span><span class="sc">{</span>p<span class="sc">.</span>numel()<span class="sc">:&gt;7,}</span><span class="ss">"</span>)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>n_conv <span class="op">=</span> <span class="bu">sum</span>(p.numel() <span class="cf">for</span> n, p <span class="kw">in</span> lenet.named_parameters() <span class="cf">if</span> <span class="st">"conv"</span> <span class="kw">in</span> n)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>n_lenet <span class="op">=</span> <span class="bu">sum</span>(p.numel() <span class="cf">for</span> p <span class="kw">in</span> lenet.parameters())</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>n_mlp <span class="op">=</span> <span class="bu">sum</span>(p.numel() <span class="cf">for</span> p <span class="kw">in</span> mlp.parameters())</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">LeNet: </span><span class="sc">{</span>n_lenet<span class="sc">:,}</span><span class="ss"> parameters (</span><span class="sc">{</span>n_conv<span class="sc">:,}</span><span class="ss"> of them convolutional)"</span>)</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"MLP:   </span><span class="sc">{</span>n_mlp<span class="sc">:,}</span><span class="ss"> parameters"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>conv1.weight   (6, 1, 5, 5)         150
conv1.bias     (6,)                   6
conv2.weight   (16, 6, 5, 5)      2,400
conv2.bias     (16,)                 16
fc1.weight     (120, 400)        48,000
fc1.bias       (120,)               120
fc2.weight     (84, 120)         10,080
fc2.bias       (84,)                 84
fc3.weight     (10, 84)             840
fc3.bias       (10,)                 10

LeNet: 61,706 parameters (2,572 of them convolutional)
MLP:   203,530 parameters</code></pre>
</div>
</div>
<p>Two readings of this table. Against the MLP: LeNet carries 61,706 parameters to the MLP’s 203,530 (less than a third) while performing far richer spatial computation. Weight sharing is doing exactly what Chapter 7’s matrix view promised. Within LeNet: look where the parameters live. The two conv layers, the part that actually <em>sees</em>, own 2,572 parameters (about 4%) while the dense head hoards the rest. That imbalance is a design smell we will fix in <a href="09-modern-cnns-transfer.html" class="quarto-xref"><span>Chapter 9</span></a>, where modern architectures go deeper in convolution and lighter in the head.</p>
<p>Now train both models under one shared optimization recipe: same fitting split, optimizer, minibatch size, number of epochs, and therefore number of parameter updates. The comparison does <strong>not</strong> match parameter count or floating-point work; a convolution and a dense layer spend different computation per update. Architecture is the intended difference, compute is not controlled:</p>
<div id="train-both" class="cell" data-execution_count="12">
<details class="code-fold">
<summary>Code: one recipe, two architectures</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> dlbook.supervised <span class="im">import</span> fit_supervised   <span class="co"># Listing 4.1</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> train_model(</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    model_fn, X_fit: torch.Tensor <span class="op">=</span> X_tr, y_fit: torch.Tensor <span class="op">=</span> y_tr,</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    epochs: <span class="bu">int</span> <span class="op">=</span> <span class="dv">150</span>, batch: <span class="bu">int</span> <span class="op">=</span> <span class="dv">128</span>, seed: <span class="bu">int</span> <span class="op">=</span> <span class="dv">6050</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>) <span class="op">-&gt;</span> nn.Module:</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Listing 4.1 verbatim; this chapter's deltas are the budget (150</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>    <span class="co"># epochs, batch 128) and, below, the models that get trained.</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> fit_supervised(</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>        model_fn, X_fit, y_fit, epochs<span class="op">=</span>epochs, batch<span class="op">=</span>batch, seed<span class="op">=</span>seed</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a><span class="at">@torch.no_grad</span>()</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> accuracy(model: nn.Module, X: torch.Tensor, y: torch.Tensor) <span class="op">-&gt;</span> <span class="bu">float</span>:</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>    model.<span class="bu">eval</span>()</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (model(X).argmax(<span class="dv">1</span>) <span class="op">==</span> y).<span class="bu">float</span>().mean().item()</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>mlp <span class="op">=</span> train_model(make_mlp)</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>lenet <span class="op">=</span> train_model(LeNet)</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, model <span class="kw">in</span> [(<span class="st">"MLP  "</span>, mlp), (<span class="st">"LeNet"</span>, lenet)]:</span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>name<span class="sc">}</span><span class="ss">  train </span><span class="sc">{</span>accuracy(model, X_tr, y_tr)<span class="sc">:.1%}</span><span class="ss">   "</span></span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"validation </span><span class="sc">{</span>accuracy(model, X_val, y_val)<span class="sc">:.1%}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>MLP    train 100.0%   validation 75.5%
LeNet  train 99.5%   validation 74.5%</code></pre>
</div>
</div>
<p>Read the clean-validation column honestly: the MLP scores 75.5% and LeNet 74.5% in this single seeded run. A one-point difference is descriptive, not an uncertainty estimate, so it does not establish which architecture has higher expected clean accuracy. Chapter 6 already told us why a landslide is unlikely here: centered garments do not expose the MLP’s main weakness. Both models nearly interpolate the fitting split. Our small-data regime makes a narrower point: LeNet reaches comparable clean accuracy with less than a third of the parameters. The shift experiment now asks whether it learned a different kind of representation.</p>
</section>
<section id="the-rematch" class="level2" data-number="8.7">
<h2 data-number="8.7" class="anchored" data-anchor-id="the-rematch"><span class="header-section-number">8.7</span> The rematch</h2>
<p>Chapter 6 convicted our MLP with one experiment: shift every validation garment two pixels right, and accuracy fell off a cliff — the full-frame templates kept scoring sleeves against background. We then promised that an architecture built on locality and weight sharing would face the same trial. Write your predictions down before running — two numbers: LeNet’s clean accuracy, and LeNet at a two-pixel shift. The MLP managed 76% and 43%.</p>
<div id="cell-fig-cliff-rematch" class="cell" data-execution_count="13">
<details class="code-fold">
<summary>Code: accuracy vs.&nbsp;shift, both models</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> shift_right(X: torch.Tensor, px: <span class="bu">int</span>) <span class="op">-&gt;</span> torch.Tensor:</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>    out <span class="op">=</span> torch.zeros_like(X)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> px <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> X.clone()</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    out[..., px:] <span class="op">=</span> X[..., :<span class="op">-</span>px]</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> out</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>shifts <span class="op">=</span> <span class="bu">list</span>(<span class="bu">range</span>(<span class="dv">5</span>))</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>acc_mlp <span class="op">=</span> [accuracy(mlp, shift_right(X_val, s), y_val) <span class="cf">for</span> s <span class="kw">in</span> shifts]</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>acc_cnn <span class="op">=</span> [accuracy(lenet, shift_right(X_val, s), y_val) <span class="cf">for</span> s <span class="kw">in</span> shifts]</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> s <span class="kw">in</span> shifts:</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"shift </span><span class="sc">{</span>s<span class="sc">}</span><span class="ss">px:   MLP </span><span class="sc">{</span>acc_mlp[s]<span class="sc">:.1%}</span><span class="ss">   LeNet </span><span class="sc">{</span>acc_cnn[s]<span class="sc">:.1%}</span><span class="ss">"</span>)</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="fl">5.5</span>, <span class="fl">3.2</span>))</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>plt.plot(shifts, acc_mlp, <span class="st">"o-"</span>, color<span class="op">=</span><span class="st">"#E57200"</span>, lw<span class="op">=</span><span class="dv">2</span>, ms<span class="op">=</span><span class="dv">7</span>, label<span class="op">=</span><span class="st">"MLP (Ch. 6)"</span>)</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>plt.plot(shifts, acc_cnn, <span class="st">"s-"</span>, color<span class="op">=</span><span class="st">"#232D4B"</span>, lw<span class="op">=</span><span class="dv">2</span>, ms<span class="op">=</span><span class="dv">7</span>, label<span class="op">=</span><span class="st">"LeNet"</span>)</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>plt.axhline(<span class="fl">0.1</span>, ls<span class="op">=</span><span class="st">":"</span>, color<span class="op">=</span><span class="st">"#B8B8A8"</span>)</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"shift (pixels right)"</span>)<span class="op">;</span> plt.ylabel(<span class="st">"validation accuracy"</span>)</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>plt.ylim(<span class="dv">0</span>, <span class="fl">0.9</span>)<span class="op">;</span> plt.xticks(shifts)<span class="op">;</span> plt.legend()</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>shift 0px:   MLP 75.5%   LeNet 74.5%
shift 1px:   MLP 64.0%   LeNet 66.0%
shift 2px:   MLP 42.0%   LeNet 57.5%
shift 3px:   MLP 27.0%   LeNet 42.0%
shift 4px:   MLP 18.5%   LeNet 23.0%</code></pre>
</div>
<div class="cell-output cell-output-display">
<div id="fig-cliff-rematch" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two accuracy curves decline as images shift right. They begin at similar clean accuracy, but the LeNet curve stays above the MLP curve at every nonzero shift; a dotted horizontal line marks chance.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cliff-rematch-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08-cnn_files/figure-html/fig-cliff-rematch-output-2.png" alt="Two accuracy curves decline as images shift right. They begin at similar clean accuracy, but the LeNet curve stays above the MLP curve at every nonzero shift; a dotted horizontal line marks chance." width="519" height="297" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cliff-rematch-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.4: The validation rematch. Both architectures use the same optimizer schedule, though not matched compute. At two pixels the MLP falls from 75.5% to 42.0%, while LeNet falls from 74.5% to 57.5%. The dotted line is chance.
</figcaption>
</figure>
</div>
</div>
</div>
<p>There is the payoff, and it is worth stating precisely. At two pixels the MLP falls from 75.5% to 42.0%, while LeNet falls from 74.5% to 57.5%. That is one deterministic validation split, not a sampling distribution, but the within-run contrast is large. The mechanism is everything this chapter built: the kernels travel with the garment (equivariance), so the <em>features are still found</em>; pooling forgives some sub-window jitter (local insensitivity); only the coarse layout entering the head changes at all.</p>
<p>And yet the navy curve falls too. Also worth stating precisely, because it teaches the architecture’s fine print. Two rounds of 2× pooling buy tolerance measured in a few pixels, not unlimited; and after <code>flatten(1)</code>, the dense head reads the final <span class="math inline">\(5
\times 5\)</span> grid <em>positionally</em> — a four-pixel input shift moves features roughly one full cell in that grid, and the head is as brittle to cell-level shifts as Chapter 6’s MLP was to pixel-level ones. The inductive bias did not abolish the cliff; it moved it outward and flattened it into a slope. Reducing the remaining sensitivity is the next chapter’s business, where we revisit depth and the position-sensitive head.</p>
<p>One last look inside, because Chapter 6 also showed us what the MLP’s first layer <em>looked like</em> — global, smeared, garment-shaped templates (<a href="../part1/06-generalization-inductive-bias.html" class="quarto-xref"><span>Chapter 6</span></a>) — and promised that structure would change:</p>
<div id="cell-fig-learned-filters" class="cell" data-execution_count="14">
<details class="code-fold">
<summary>Code: first-layer kernels and their feature maps</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>img <span class="op">=</span> X_val[<span class="dv">1</span>:<span class="dv">2</span>]                                    <span class="co"># one validation garment</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> torch.no_grad():</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    fmaps <span class="op">=</span> F.relu(lenet.conv1(img)).squeeze(<span class="dv">0</span>)     <span class="co"># (6, 28, 28)</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>kernels <span class="op">=</span> lenet.conv1.weight.detach().squeeze(<span class="dv">1</span>)    <span class="co"># (6, 5, 5)</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">6</span>, figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="fl">3.2</span>))</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>lim <span class="op">=</span> kernels.<span class="bu">abs</span>().<span class="bu">max</span>()</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">6</span>):</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">0</span>, i].imshow(kernels[i], cmap<span class="op">=</span><span class="st">"RdBu_r"</span>, vmin<span class="op">=-</span>lim, vmax<span class="op">=</span>lim)</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">1</span>, i].imshow(fmaps[i], cmap<span class="op">=</span><span class="st">"gray"</span>)</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">0</span>, i].axis(<span class="st">"off"</span>)<span class="op">;</span> axes[<span class="dv">1</span>, i].axis(<span class="st">"off"</span>)</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-learned-filters" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Six small signed kernel heatmaps form the top row, and six larger activation maps for the same garment form the bottom row. The response maps emphasize different local regions even where the kernels remain diffuse.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-learned-filters-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08-cnn_files/figure-html/fig-learned-filters-output-1.png" alt="Six small signed kernel heatmaps form the top row, and six larger activation maps for the same garment form the bottom row. The response maps emphasize different local regions even where the kernels remain diffuse." width="854" height="287" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-learned-filters-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.5: What LeNet learned to look for. Top: six first-layer 5×5 kernels (red positive, blue negative). Bottom: their feature maps on one validation garment. The maps respond differently, but at this toy scale several kernels are diffuse and their semantics should not be over-interpreted. Compare their local support with Chapter 6’s full-frame templates.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Six small, local kernels produce distinct response maps on the same garment. Some show directional structure; others remain noisy enough that naming a detector would tell more story than this one run supports. Nobody designed them. The classification loss, pulling blame backward through <a href="#eq-conv-layer" class="quarto-xref">Equation&nbsp;<span>8.1</span></a> for roughly 1,200 optimizer steps, chose these local measurements.</p>
</section>
<section id="one-sealed-test-check" class="level2" data-number="8.8">
<h2 data-number="8.8" class="anchored" data-anchor-id="one-sealed-test-check"><span class="header-section-number">8.8</span> One sealed test check</h2>
<p>We have now fixed both architectures, the optimizer schedule, the shift size, and the two reported metrics. We refit each model on all 1,200 development images, then open the 600-image test set once:</p>
<p>Here <em>sealed</em> is chapter-local. <a href="../../chapters/interludes/learning-by-experiment.html">The experiment interlude</a> has already disclosed that this 600-image file is a reused book endpoint, not a globally untouched test set; it remained decision-inert while this chapter’s choices were made.</p>
<div id="final-holdout" class="cell" data-execution_count="15">
<details class="code-fold">
<summary>Code: one final test-set check</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>mlp_final <span class="op">=</span> train_model(make_mlp, X_dev, y_dev)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>lenet_final <span class="op">=</span> train_model(LeNet, X_dev, y_dev)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, model <span class="kw">in</span> [(<span class="st">"MLP  "</span>, mlp_final), (<span class="st">"LeNet"</span>, lenet_final)]:</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>name<span class="sc">}</span><span class="ss">  clean </span><span class="sc">{</span>accuracy(model, X_test, y_test)<span class="sc">:.1%}</span><span class="ss">   "</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"shift-2 </span><span class="sc">{</span>accuracy(model, shift_right(X_test, <span class="dv">2</span>), y_test)<span class="sc">:.1%}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>MLP    clean 82.2%   shift-2 41.8%
LeNet  clean 82.5%   shift-2 62.3%</code></pre>
</div>
</div>
<p>The sealed check confirms the validation diagnosis. Clean accuracy is 82.2% for the MLP and 82.5% for LeNet, a descriptive 0.3-point gap from one seed. Under the predeclared two-pixel shift, the gap becomes 41.8% versus 62.3%.</p>
</section>
<section id="okay-so-the-kernel-became-learnable" class="level2" data-number="8.9">
<h2 data-number="8.9" class="anchored" data-anchor-id="okay-so-the-kernel-became-learnable"><span class="header-section-number">8.9</span> Okay, so — the kernel became learnable</h2>
<ol type="1">
<li><strong>One change made the revolution</strong>: the kernel’s numbers became parameters. Gradient descent can recover a hand-crafted detector from data (our rigged game) and, more importantly, discover detectors nobody designed, supervised only by the task loss at the far end.</li>
<li><strong>Channels turn one detector into a team</strong>: out-channels stack specialists’ feature maps; in-channels let the next layer read all maps at once (<a href="#eq-conv-layer" class="quarto-xref">Equation&nbsp;<span>8.1</span></a>), which is how edges compose into corners and parts.</li>
<li><strong>Padding and stride are the shape budget</strong>: <span class="math inline">\(n_{\text{out}} = \lfloor (n + 2p -
k)/s \rfloor + 1\)</span> (<a href="#eq-outsize" class="quarto-xref">Equation&nbsp;<span>8.2</span></a>). Padding lets networks go deep without shrinking to nothing; stride shrinks on purpose.</li>
<li><strong>Pooling can turn equivariance into local shift tolerance</strong> — the strongest clue per window, some position discarded. It is a purchase, and position is the currency.</li>
<li><strong>Receptive fields grow with depth</strong>: <span class="math inline">\(5 \rightarrow 6 \rightarrow 14 \rightarrow
16\)</span> in our LeNet. Local wiring earns global sight gradually; the hierarchy Chapter 3 could only hope for is now encouraged by architecture.</li>
<li><strong>The verdict</strong>: on the sealed test set, one seed puts clean accuracy at 82.2% for the MLP and 82.5% for LeNet; this does not establish an expected clean-accuracy difference. Under the predeclared two-pixel shift, the same models score 41.8% and 62.3%. The bias did not add capacity; it added the <em>right constraints</em>, exactly Chapter 6’s prescription.</li>
</ol>
</section>
<section id="sources-and-further-reading" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="sources-and-further-reading">Sources and further reading</h2>
<ul>
<li>LeCun et al., <a href="http://yann.lecun.com/exdb/publis/pdf/lecun-98.pdf">“Gradient-Based Learning Applied to Document Recognition”</a> (1998): the primary LeNet account, including the architecture’s document-recognition setting.</li>
<li>Fukushima, <a href="https://doi.org/10.1007/BF00344251">“Neocognitron: A Self-organizing Neural Network Model”</a> (1980): historical context for alternating feature extraction and spatial tolerance.</li>
<li>Zeiler and Fergus, <a href="https://arxiv.org/abs/1311.2901">“Visualizing and Understanding Convolutional Networks”</a> (2014): methods and evidence for inspecting learned convolutional features without over-reading a single filter image.</li>
<li>Dumoulin and Visin, <a href="https://arxiv.org/abs/1603.07285">“A Guide to Convolution Arithmetic for Deep Learning”</a> (2016): a compact companion for checking convolution, pooling, and receptive-field shapes.</li>
</ul>
</section>
<section id="exercises" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercises">Exercises</h2>
<ol type="1">
<li><strong>(Pencil.)</strong> Run <a href="#eq-outsize" class="quarto-xref">Equation&nbsp;<span>8.2</span></a> through LeNet layer by layer, starting from <span class="math inline">\(28
\times 28\)</span>: verify every shape comment in the <code>LeNet</code> class, then verify the parameter counts of <code>conv1</code> and <code>conv2</code> from the table (weights <em>and</em> biases).</li>
<li><strong>(Pencil.)</strong> Verify the receptive-field ledger <span class="math inline">\(5 \rightarrow 6 \rightarrow 14
\rightarrow 16\)</span>. (Track two numbers per stage: the field size, and the <em>jump</em> — the spacing in input pixels between neighboring units — which each stride-2 pool doubles.) Then show that no convolutional or pooling unit in LeNet ever sees the full <span class="math inline">\(28 \times 28\)</span> frame. Where does globality finally enter the network?</li>
<li><strong>(Code.)</strong> Play the mystery-detector game with the <span class="math inline">\(3 \times 3\)</span> blur kernel as the target. Does gradient descent recover it as cleanly as Sobel? Now rerun with only 8 training images instead of 256. What happens to the recovered kernel, and what does that say about data volume versus parameter identifiability?</li>
<li><strong>(Code.)</strong> Swap LeNet’s max pooling for average pooling and retrain. Compare clean accuracy and the shift curve. Which changes more, and does the result match the “strongest clue vs.&nbsp;general vibe” story?</li>
<li><strong>(Pencil.)</strong> The final dense head receives 25 spatial positions per feature map. Explain why this can reintroduce shift sensitivity after equivariant convolutions. Describe what information a position-insensitive head would keep and discard; we will build one in <a href="09-modern-cnns-transfer.html" class="quarto-xref"><span>Chapter 9</span></a>.</li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/shakeri-lab\.github\.io\/dl-book\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../chapters/part2/07-filters-convolution.html" class="pagination-link" aria-label="Filters and Convolution (Fixed Kernels)">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Filters and Convolution (Fixed Kernels)</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/part2/09-modern-cnns-transfer.html" class="pagination-link" aria-label="Modern CNNs and Transfer Learning">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Modern CNNs and Transfer Learning</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Heman Shakeri · Text CC BY-NC-SA 4.0 · Code MIT · School of Data Science, University of Virginia</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/Shakeri-Lab/dl-book/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Companion to <a href="https://shakeri-lab.github.io/dl-course-site/">DS 6050 Deep Learning</a></p>
</div>
  </div>
</footer>




</body></html>