<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>9&nbsp; Modern CNNs and Transfer Learning – Deep Learning: Making It Learnable</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/part3/10-sequences-rnn.html" rel="next">
<link href="../../chapters/part2/08-cnn.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-7bbffa5cb1ba97d2e0b97962360040e5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>
  // Book math macros — keep in sync with tex/macros.tex (PDF path).
  // MathJax reads this config because it is defined before the MathJax
  // script loads (Quarto places include-in-header above its math script).
  window.MathJax = {
    tex: {
      macros: {
        E: "\\mathbb{E}",
        Ex: "\\operatorname{E}",
        var: "\\operatorname{Var}",
        cov: "\\operatorname{Cov}",
        imp: "\\Rightarrow",
        argmax: "\\operatorname*{arg\\,max}",
        argmin: "\\operatorname*{arg\\,min}",
        norm: ["\\left\\lVert#1\\right\\rVert", 1],
        vect: ["\\mathbf{#1}", 1],
        matr: ["\\mathbf{#1}", 1],
        R: "\\mathbb{R}",
        dd: "\\mathrm{d}",
        loss: "\\mathcal{L}"
      }
    }
  };
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/part2/07-filters-convolution.html">II · Vision: Learning the Filters</a></li><li class="breadcrumb-item"><a href="../../chapters/part2/09-modern-cnns-transfer.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Modern CNNs and Transfer Learning</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Deep Learning: Making It Learnable</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/Shakeri-Lab/dl-book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">I · From Lines to Networks</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/01-linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Linear Regression, the Mother Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/02-logistic-softmax.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Linear Models that Classify: Logistic and Softmax</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/03-nonlinearity-mlp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Nonlinearity and the MLP</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/04-training-loss-sgd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Training: Loss and Stochastic Gradient Descent</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/05-backpropagation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Backpropagation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/06-generalization-inductive-bias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">When It Fails: Generalization in Pictures, and Inductive Bias</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">II · Vision: Learning the Filters</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/07-filters-convolution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Filters and Convolution (Fixed Kernels)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/08-cnn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">CNNs: Making the Filters Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/09-modern-cnns-transfer.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Modern CNNs and Transfer Learning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">III · Sequences</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part3/10-sequences-rnn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Sequences and Recurrence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part3/11-encoder-decoder.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Encoder–Decoder, Teacher Forcing, Beam Search</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">IV · Attention: Learning the Similarity</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/12-kernel-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Kernel Regression: Attention Before It Was Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/13-attention.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Attention: Making the Kernel Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/14-self-attention-transformer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Self-Attention and the Transformer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/15-bert-pretraining.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">The BERT Moment: Pretraining as the New Regime</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/16-vit-scaling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Vision Transformers and Scaling Laws</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">V · The Pretrained Era</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/17-peft-quantization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Adapting Pretrained Models: Prompting, PEFT, Quantization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/18-alignment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Alignment and RL Fine-Tuning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/19-generative.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Generative Models: From PCA to Diffusion</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a1-linear-algebra.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Linear Algebra and the SVD</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a2-tensors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Tensors in Practice</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a3-notation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Notation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a4-floating-point.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Floating Point and Machine Precision</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#question-1-why-5-times-5-stack-small-kernels-instead" id="toc-question-1-why-5-times-5-stack-small-kernels-instead" class="nav-link active" data-scroll-target="#question-1-why-5-times-5-stack-small-kernels-instead"><span class="header-section-number">9.1</span> Question 1: why <span class="math inline">\(5 \times 5\)</span>? Stack small kernels instead</a></li>
  <li><a href="#the-stabilizer-we-owe-you-batch-normalization" id="toc-the-stabilizer-we-owe-you-batch-normalization" class="nav-link" data-scroll-target="#the-stabilizer-we-owe-you-batch-normalization"><span class="header-section-number">9.2</span> The stabilizer we owe you: batch normalization</a></li>
  <li><a href="#building-with-blocks-a-small-vgg" id="toc-building-with-blocks-a-small-vgg" class="nav-link" data-scroll-target="#building-with-blocks-a-small-vgg"><span class="header-section-number">9.3</span> Building with blocks: a small VGG</a></li>
  <li><a href="#question-3-1-times-1-convolutions-and-firing-the-flatten-head" id="toc-question-3-1-times-1-convolutions-and-firing-the-flatten-head" class="nav-link" data-scroll-target="#question-3-1-times-1-convolutions-and-firing-the-flatten-head"><span class="header-section-number">9.4</span> Question 3: <span class="math inline">\(1 \times 1\)</span> convolutions, and firing the flatten head</a></li>
  <li><a href="#question-2-going-deeper-and-the-wall-you-hit" id="toc-question-2-going-deeper-and-the-wall-you-hit" class="nav-link" data-scroll-target="#question-2-going-deeper-and-the-wall-you-hit"><span class="header-section-number">9.5</span> Question 2: going deeper, and the wall you hit</a></li>
  <li><a href="#the-scorecard-what-a-decade-of-design-bought" id="toc-the-scorecard-what-a-decade-of-design-bought" class="nav-link" data-scroll-target="#the-scorecard-what-a-decade-of-design-bought"><span class="header-section-number">9.6</span> The scorecard: what a decade of design bought</a></li>
  <li><a href="#transfer-learning-the-mechanics-and-an-honest-experiment" id="toc-transfer-learning-the-mechanics-and-an-honest-experiment" class="nav-link" data-scroll-target="#transfer-learning-the-mechanics-and-an-honest-experiment"><span class="header-section-number">9.7</span> Transfer learning: the mechanics, and an honest experiment</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/Shakeri-Lab/dl-book/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/part2/07-filters-convolution.html">II · Vision: Learning the Filters</a></li><li class="breadcrumb-item"><a href="../../chapters/part2/09-modern-cnns-transfer.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Modern CNNs and Transfer Learning</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-09-modern-cnns-transfer" class="quarto-section-identifier"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Modern CNNs and Transfer Learning</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<!-- lecture-source: m05_lecture-5-modern-cnn-architectures-and-transfer-_-R64Wg5Sgsc.txt
     (spine #1–15 via ds6050_05_modern_cnn/MODULE_NOTES.md),
     m04 lecture spine #19 (transfer intro)
     seeds: sources/4.2-CNN-2.tex (six efficiency principles),
            4- Lecture CNN/assignment/cnn_assignment.py (course assignment, referenced)
     note: sources/4.3-NextGenCNN.tex (EfficientNet/ConvNeXt scaling) deferred to
           @sec-16-vit-scaling.
     data: data/squeezenet1_1-imagenet.pt — torchvision SqueezeNet 1.1 ImageNet weights
           (BSD-3), committed so rendering never downloads. -->
<p>Chapter 8 ended with a working machine and a report card. LeNet reads garments at 82.5% with 61,706 parameters; graceful under shift where the MLP cliff-dived. But the card has two demerits we wrote down explicitly: 96% of those parameters sit in the dense head rather than in the convolutions that do the seeing, and the shift cliff was softened, not abolished. And one IOU: the live session’s batch normalization, promised for this chapter.</p>
<p>What happened after LeNet is a decade of architecture research, and it can drown you in named networks. The lecture compresses it into <strong>four design questions</strong>, and we will let them drive:</p>
<ol type="1">
<li><strong>Why <span class="math inline">\(5 \times 5\)</span>?</strong> Could smaller filters do the same job with fewer parameters?</li>
<li><strong>How do we go deeper</strong> without gradients dying on the way down?</li>
<li><strong>Where do the parameters actually live</strong>, and how do we evict them?</li>
<li><strong>Can we design reusable blocks</strong> — optimized layer-combinations we stack, keeping a bird’s-eye view instead of re-designing what already works?</li>
</ol>
<p>Each question has a famous answer (VGG, ResNet, NiN’s <span class="math inline">\(1\times1\)</span> + global pooling, and the block habit itself), and each answer is a constraint-shaped idea we can test on our own data. At the end, the practical superpower the lecture builds to — reusing a pretrained backbone — gets the most honest experiment in this book.</p>
<div id="setup" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Code: imports, data, and the shared training recipe</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.nn <span class="im">as</span> nn</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.nn.functional <span class="im">as</span> F</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>torch.manual_seed(<span class="dv">6050</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>train <span class="op">=</span> torch.load(<span class="st">"../../data/fashion-train.pt"</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>test <span class="op">=</span> torch.load(<span class="st">"../../data/fashion-test.pt"</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>X_tr <span class="op">=</span> train[<span class="st">"X"</span>].<span class="bu">float</span>().unsqueeze(<span class="dv">1</span>) <span class="op">/</span> <span class="fl">255.0</span>    <span class="co"># (1200, 1, 28, 28)</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>X_te <span class="op">=</span> test[<span class="st">"X"</span>].<span class="bu">float</span>().unsqueeze(<span class="dv">1</span>) <span class="op">/</span> <span class="fl">255.0</span>     <span class="co"># (600, 1, 28, 28)</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>y_tr, y_te, classes <span class="op">=</span> train[<span class="st">"y"</span>], test[<span class="st">"y"</span>], train[<span class="st">"classes"</span>]</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> train_model(model_fn, epochs: <span class="bu">int</span>, batch: <span class="bu">int</span> <span class="op">=</span> <span class="dv">128</span>, seed: <span class="bu">int</span> <span class="op">=</span> <span class="dv">6050</span>,</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>                lr: <span class="bu">float</span> <span class="op">=</span> <span class="fl">1e-3</span>, data<span class="op">=</span><span class="va">None</span>):</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    torch.manual_seed(seed)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    model <span class="op">=</span> model_fn()</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    opt <span class="op">=</span> torch.optim.Adam(model.parameters(), lr<span class="op">=</span>lr)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    X, y <span class="op">=</span> data <span class="cf">if</span> data <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span> <span class="cf">else</span> (X_tr, y_tr)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> <span class="bu">len</span>(X)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(epochs):</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>        perm <span class="op">=</span> torch.randperm(n)</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>, n, batch):</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>            idx <span class="op">=</span> perm[i:i <span class="op">+</span> batch]</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>            model.train()</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>            loss <span class="op">=</span> F.cross_entropy(model(X[idx]), y[idx])</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>            opt.zero_grad()<span class="op">;</span> loss.backward()<span class="op">;</span> opt.step()</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>    model.<span class="bu">eval</span>()</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> model</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="at">@torch.no_grad</span>()</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> accuracy(model, X, y):</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>    model.<span class="bu">eval</span>()</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (model(X).argmax(<span class="dv">1</span>) <span class="op">==</span> y).<span class="bu">float</span>().mean().item()</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>count <span class="op">=</span> <span class="kw">lambda</span> m: <span class="bu">sum</span>(p.numel() <span class="cf">for</span> p <span class="kw">in</span> m.parameters())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Two small novelties in the recipe, both because this chapter’s networks contain batch normalization: <code>model.train()</code> before each step and <code>model.eval()</code> before each evaluation. Why that matters is the subject of the second section.</p>
<section id="question-1-why-5-times-5-stack-small-kernels-instead" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="question-1-why-5-times-5-stack-small-kernels-instead"><span class="header-section-number">9.1</span> Question 1: why <span class="math inline">\(5 \times 5\)</span>? Stack small kernels instead</h2>
<p>VGG’s answer (Simonyan &amp; Zisserman, 2014) is the cleanest idea in this chapter. Recall the receptive-field ledger of <a href="08-cnn.html" class="quarto-xref"><span>Chapter 8</span></a>: stacking grows the field. Two stacked <span class="math inline">\(3 \times 3\)</span> convolutions let the second layer see <span class="math inline">\(5 \times 5\)</span> of the input — the <em>same</em> receptive field as one <span class="math inline">\(5 \times 5\)</span> kernel. But compare the bills, for a layer with <span class="math inline">\(C\)</span> channels in and <span class="math inline">\(C\)</span> out:</p>
<p><span class="math display">\[
\underbrace{25\,C^2}_{\text{one } 5\times5}
\qquad\text{versus}\qquad
\underbrace{2 \times 9\,C^2 = 18\,C^2}_{\text{two } 3\times3\text{s}},
\]</span></p>
<p>a 28% saving — and the stacked pair fires a ReLU <em>twice</em> where the big kernel fires once. Same sight, fewer parameters, more nonlinearity. Three <span class="math inline">\(3\times3\)</span>s reach a <span class="math inline">\(7\times7\)</span> field for <span class="math inline">\(27C^2\)</span> against <span class="math inline">\(49C^2\)</span>: the deeper you take the idea, the better the deal gets.</p>
<div id="kernel-economics" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code: the parameter bill, C = 32</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>C <span class="op">=</span> <span class="dv">32</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>one_5x5 <span class="op">=</span> nn.Conv2d(C, C, <span class="dv">5</span>, padding<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>two_3x3 <span class="op">=</span> nn.Sequential(nn.Conv2d(C, C, <span class="dv">3</span>, padding<span class="op">=</span><span class="dv">1</span>), nn.ReLU(),</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>                        nn.Conv2d(C, C, <span class="dv">3</span>, padding<span class="op">=</span><span class="dv">1</span>))</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"one 5x5:  </span><span class="sc">{</span>count(one_5x5)<span class="sc">:,}</span><span class="ss"> parameters, 1 ReLU after"</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"two 3x3s: </span><span class="sc">{</span>count(two_3x3)<span class="sc">:,}</span><span class="ss"> parameters, 2 ReLUs"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>one 5x5:  25,632 parameters, 1 ReLU after
two 3x3s: 18,496 parameters, 2 ReLUs</code></pre>
</div>
</div>
<p>One honest caveat before you re-derive the field equations of vision from this: the <span class="math inline">\(18C^2 &lt; 25C^2\)</span> arithmetic assumes the channel width stays <span class="math inline">\(C\)</span> through the stack. When a layer <em>grows</em> channels (as LeNet’s <span class="math inline">\(6 \rightarrow 16\)</span> did), splitting it into two growing <span class="math inline">\(3\times3\)</span>s can cost more, not less. VGG’s design sidesteps this by keeping width constant inside each block and changing it only between blocks — which is exactly the shape our code will take. (Exercise 1 makes you find the break-even point.)</p>
</section>
<section id="the-stabilizer-we-owe-you-batch-normalization" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="the-stabilizer-we-owe-you-batch-normalization"><span class="header-section-number">9.2</span> The stabilizer we owe you: batch normalization</h2>
<p>Before we stack deeper than ever, we need the tool Chapter 8’s live session used and we deferred. Here is the problem it solves. Watch what happens to the <em>scale</em> of activations as a signal crosses twelve freshly initialized <span class="math inline">\(3\times3\)</span> conv layers:</p>
<div id="bn-drift" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code: activation scale through 12 conv layers, with and without BN</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> stack12(with_bn: <span class="bu">bool</span>, ch: <span class="bu">int</span> <span class="op">=</span> <span class="dv">16</span>):</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    layers <span class="op">=</span> [nn.Conv2d(<span class="dv">1</span>, ch, <span class="dv">3</span>, padding<span class="op">=</span><span class="dv">1</span>)]</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">11</span>):</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> with_bn:</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>            layers.append(nn.BatchNorm2d(ch))</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>        layers <span class="op">+=</span> [nn.ReLU(), nn.Conv2d(ch, ch, <span class="dv">3</span>, padding<span class="op">=</span><span class="dv">1</span>)]</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> nn.Sequential(<span class="op">*</span>layers)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>torch.manual_seed(<span class="dv">0</span>)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> X_tr[:<span class="dv">256</span>]</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> with_bn <span class="kw">in</span> [<span class="va">False</span>, <span class="va">True</span>]:</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>    h, stds <span class="op">=</span> x, []</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">with</span> torch.no_grad():</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> layer <span class="kw">in</span> stack12(with_bn):</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>            h <span class="op">=</span> layer(h)</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> <span class="bu">isinstance</span>(layer, nn.Conv2d):</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>                stds.append(h.std().item())</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>    tag <span class="op">=</span> <span class="st">"with BN   "</span> <span class="cf">if</span> with_bn <span class="cf">else</span> <span class="st">"without BN"</span></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>tag<span class="sc">}</span><span class="ss"> layer stds: "</span> <span class="op">+</span> <span class="st">"  "</span>.join(<span class="ss">f"</span><span class="sc">{</span>s<span class="sc">:.3f}</span><span class="ss">"</span> <span class="cf">for</span> s <span class="kw">in</span> stds[::<span class="dv">2</span>]))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>without BN layer stds: 0.344  0.059  0.043  0.046  0.049  0.061
with BN    layer stds: 0.309  0.324  0.411  0.383  0.377  0.369</code></pre>
</div>
</div>
<p>Without normalization the signal’s spread collapses by an order of magnitude within a few layers and keeps sagging; recall from <a href="../part1/05-backpropagation.html" class="quarto-xref"><span>Chapter 5</span></a> that whatever happens to signals forward happens to gradients backward <span class="math inline">\(\rightarrow\)</span> layers deep in the stack learn at a completely different rate than shallow ones, if at all.</p>
<p><strong>Batch normalization</strong> (Ioffe &amp; Szegedy, 2015) re-standardizes at every layer: for each channel, compute the mean and standard deviation <em>across the current minibatch</em>, normalize the activations to zero mean and unit spread, then let the layer undo it if it wants to via two learnable knobs per channel:</p>
<p><span id="eq-batchnorm"><span class="math display">\[
\hat{x} = \frac{x - \mu_{\text{batch}}}{\sqrt{\sigma^2_{\text{batch}} + \epsilon}},
\qquad
y = \gamma\,\hat{x} + \beta .
\tag{9.1}\]</span></span></p>
<p>The <span class="math inline">\(\gamma, \beta\)</span> pair matters: normalization is a <em>reset to a healthy scale</em>, not a straitjacket — the network can learn to restore any mean and spread that helps, but it starts every layer from sane numbers. In the printout above, the BN column holds near a constant spread through all twelve layers: every layer trains from day one. The standard placement, which the live session uses and we adopt, is conv <span class="math inline">\(\rightarrow\)</span> BN <span class="math inline">\(\rightarrow\)</span> ReLU, with <code>bias=False</code> on the convolution, since <span class="math inline">\(\beta\)</span> already provides the shift.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>BN is two different machines — tell PyTorch which one you’re running
</div>
</div>
<div class="callout-body-container callout-body">
<p>At training time BN normalizes by the <em>current batch’s</em> statistics. At evaluation time there may be no batch (one image!), so it uses running averages collected during training. <code>model.train()</code> and <code>model.eval()</code> switch between the two. Forgetting the switch is the classic BN bug: evaluate in train mode and your predictions depend on whatever else happens to be in the batch; train in eval mode and BN never learns its statistics. Our <code>train_model</code> recipe flips the switch in both directions — look for it. Corollary: BN needs real batches to estimate statistics, so it gets unreliable at tiny batch sizes.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Normalize across <em>what</em>? A seed for Part IV
</div>
</div>
<div class="callout-body-container callout-body">
<p>Batch statistics are one choice among several. When we build transformers (1), batches of variable-length sequences will make per-batch statistics awkward, and the same standardize-then-rescale idea will reappear computed per <em>token</em> instead: <strong>layer normalization</strong>. Same equation, different axis — remember <a href="#eq-batchnorm" class="quarto-xref">Equation&nbsp;<span>9.1</span></a> when you meet it.</p>
</div>
</div>
</section>
<section id="building-with-blocks-a-small-vgg" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="building-with-blocks-a-small-vgg"><span class="header-section-number">9.3</span> Building with blocks: a small VGG</h2>
<p>Now assemble Question 1’s answer with Question 4’s habit. Define the <em>atom</em> — conv, BN, ReLU — once; a block stacks atoms and pools; a network stacks blocks. This is the lecture’s point about VGG versus its hand-tuned predecessors: you stop re-designing and start repeating.</p>
<div id="vgg-small" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code: VGGSmall — two blocks of stacked 3×3 atoms</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> atom(c_in: <span class="bu">int</span>, c_out: <span class="bu">int</span>):</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> [nn.Conv2d(c_in, c_out, <span class="dv">3</span>, padding<span class="op">=</span><span class="dv">1</span>, bias<span class="op">=</span><span class="va">False</span>),</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>            nn.BatchNorm2d(c_out), nn.ReLU()]</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> VGGSmall(nn.Module):</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>):</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.features <span class="op">=</span> nn.Sequential(</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>            <span class="op">*</span>atom(<span class="dv">1</span>, <span class="dv">16</span>), <span class="op">*</span>atom(<span class="dv">16</span>, <span class="dv">16</span>), nn.MaxPool2d(<span class="dv">2</span>),    <span class="co"># -&gt; (16, 14, 14)</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>            <span class="op">*</span>atom(<span class="dv">16</span>, <span class="dv">32</span>), <span class="op">*</span>atom(<span class="dv">32</span>, <span class="dv">32</span>), nn.MaxPool2d(<span class="dv">2</span>),   <span class="co"># -&gt; (32, 7, 7)</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.head <span class="op">=</span> nn.Sequential(nn.Flatten(),</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>                                  nn.Linear(<span class="dv">32</span> <span class="op">*</span> <span class="dv">7</span> <span class="op">*</span> <span class="dv">7</span>, <span class="dv">128</span>), nn.ReLU(),</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>                                  nn.Linear(<span class="dv">128</span>, <span class="dv">10</span>))</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x):</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">self</span>.head(<span class="va">self</span>.features(x))</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>vgg <span class="op">=</span> train_model(VGGSmall, epochs<span class="op">=</span><span class="dv">60</span>)</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>n_head <span class="op">=</span> count(vgg.head)</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"VGGSmall: </span><span class="sc">{</span>count(vgg)<span class="sc">:,}</span><span class="ss"> parameters (</span><span class="sc">{</span>n_head<span class="sc">:,}</span><span class="ss"> in the head, "</span></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>n_head <span class="op">/</span> count(vgg)<span class="sc">:.0%}</span><span class="ss">)"</span>)</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"test accuracy </span><span class="sc">{</span>accuracy(vgg, X_te, y_te)<span class="sc">:.1%}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>VGGSmall: 218,586 parameters (202,122 in the head, 92%)
test accuracy 86.7%</code></pre>
</div>
</div>
<p>Two readings again. The good: 86.7%, four points above LeNet — depth with small kernels genuinely sees better, and BN let sixty epochs suffice for a deeper network. The bad: 218,586 parameters, <em>triple</em> LeNet’s total, and the head’s share got worse — 92% of the network is a dense layer reading a flattened grid. The convolutional diet succeeded and the total got fatter anyway. Which forces the lecture’s third question: where do the parameters live, and — his phrasing — where can we do the most damage to the count?</p>
</section>
<section id="question-3-1-times-1-convolutions-and-firing-the-flatten-head" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="question-3-1-times-1-convolutions-and-firing-the-flatten-head"><span class="header-section-number">9.4</span> Question 3: <span class="math inline">\(1 \times 1\)</span> convolutions, and firing the flatten head</h2>
<p>The bloat has one address: <code>nn.Linear(1568, 128)</code>. To evict it we need one more tool, odd-looking at first sight: a convolution whose kernel is <span class="math inline">\(1 \times 1\)</span>.</p>
<p>A <span class="math inline">\(1 \times 1\)</span> kernel does no spatial mixing at all — it looks at a single pixel. But across <em>channels</em> it does exactly what <a href="08-cnn.html#eq-conv-layer" class="quarto-xref">Equation&nbsp;<span>8.1</span></a> says: at each position, take the <span class="math inline">\(C_{\text{in}}\)</span> channel values and form <span class="math inline">\(C_{\text{out}}\)</span> weighted combinations plus bias. Pause on what that is: a <strong>linear model across the channels, run separately at every pixel</strong> — Chapter 1’s machine, miniaturized and stamped across the image. Add a ReLU and each pixel is running a tiny MLP over its own feature vector. The lecture’s summary: we <em>summarize</em> channels, we don’t discard them — compressing 64 feature maps into 32 loses far less than pooling them away, and each compression injects another nonlinearity almost for free.</p>
<p>That tool enables the <strong>Network-in-Network</strong> design (Lin et al., 2013), and with it the clean head. A NiN block is one <span class="math inline">\(3\times3\)</span> (some spatial mixing) followed by two <span class="math inline">\(1\times1\)</span>s (per-pixel channel mixing). And the classifier becomes:</p>
<ol type="1">
<li>Let the last block produce a stack of feature maps.</li>
<li><strong>Global average pooling (GAP)</strong>: average each map over all positions — 64 maps in, 64 numbers out. No parameters at all.</li>
<li>One small linear layer to the logits.</li>
</ol>
<div id="nin-small" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code: NINSmall — 1×1 mixing and a global-average-pool head</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> nin_block(c_in: <span class="bu">int</span>, c_out: <span class="bu">int</span>):</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> [nn.Conv2d(c_in, c_out, <span class="dv">3</span>, padding<span class="op">=</span><span class="dv">1</span>, bias<span class="op">=</span><span class="va">False</span>),</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>            nn.BatchNorm2d(c_out), nn.ReLU(),</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>            nn.Conv2d(c_out, c_out, <span class="dv">1</span>), nn.ReLU(),</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>            nn.Conv2d(c_out, c_out, <span class="dv">1</span>), nn.ReLU()]</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> NINSmall(nn.Module):</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>):</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.features <span class="op">=</span> nn.Sequential(</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>            <span class="op">*</span>nin_block(<span class="dv">1</span>, <span class="dv">16</span>), nn.MaxPool2d(<span class="dv">2</span>),</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>            <span class="op">*</span>nin_block(<span class="dv">16</span>, <span class="dv">32</span>), nn.MaxPool2d(<span class="dv">2</span>),</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>            <span class="op">*</span>nin_block(<span class="dv">32</span>, <span class="dv">64</span>),</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.head <span class="op">=</span> nn.Sequential(nn.AdaptiveAvgPool2d(<span class="dv">1</span>), nn.Flatten(),</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>                                  nn.Linear(<span class="dv">64</span>, <span class="dv">10</span>))</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x):</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">self</span>.head(<span class="va">self</span>.features(x))</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>nin <span class="op">=</span> train_model(NINSmall, epochs<span class="op">=</span><span class="dv">150</span>)</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"NINSmall: </span><span class="sc">{</span>count(nin)<span class="sc">:,}</span><span class="ss"> parameters "</span></span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"(head: </span><span class="sc">{</span>count(nin.head)<span class="sc">:,}</span><span class="ss">)"</span>)</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"test accuracy </span><span class="sc">{</span>accuracy(nin, X_te, y_te)<span class="sc">:.1%}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>NINSmall: 35,034 parameters (head: 650)
test accuracy 76.2%</code></pre>
</div>
</div>
<p>The parameter story is a rout: 35,034 total, a 650-parameter head, six times smaller than VGGSmall. The accuracy is 76.2% — and that dip is worth more attention than the win, so let us not rush past it. First, though, collect the promised payoff. Chapter 8 said the remaining shift-cliff was the flatten head’s fault: it reads the final grid <em>positionally</em>. GAP averages over positions — there is nothing positional left to disturb. The rematch of the rematch:</p>
<div id="cell-fig-cliff-gap" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code: shift curves, flatten head vs GAP head</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> LeNet(nn.Module):</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>):</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.conv1 <span class="op">=</span> nn.Conv2d(<span class="dv">1</span>, <span class="dv">6</span>, <span class="dv">5</span>, padding<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.conv2 <span class="op">=</span> nn.Conv2d(<span class="dv">6</span>, <span class="dv">16</span>, <span class="dv">5</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.fc1 <span class="op">=</span> nn.Linear(<span class="dv">400</span>, <span class="dv">120</span>)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.fc2 <span class="op">=</span> nn.Linear(<span class="dv">120</span>, <span class="dv">84</span>)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.fc3 <span class="op">=</span> nn.Linear(<span class="dv">84</span>, <span class="dv">10</span>)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x):</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> F.max_pool2d(F.relu(<span class="va">self</span>.conv1(x)), <span class="dv">2</span>)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> F.max_pool2d(F.relu(<span class="va">self</span>.conv2(x)), <span class="dv">2</span>)</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> x.flatten(<span class="dv">1</span>)</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> F.relu(<span class="va">self</span>.fc1(x))</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> F.relu(<span class="va">self</span>.fc2(x))</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">self</span>.fc3(x)</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>lenet <span class="op">=</span> train_model(LeNet, epochs<span class="op">=</span><span class="dv">150</span>)          <span class="co"># Chapter 8's model, same recipe</span></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> shift_right(X, px: <span class="bu">int</span>):</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> px <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> X.clone()</span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>    out <span class="op">=</span> torch.zeros_like(X)</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>    out[..., px:] <span class="op">=</span> X[..., :<span class="op">-</span>px]</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> out</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>shifts <span class="op">=</span> <span class="bu">list</span>(<span class="bu">range</span>(<span class="dv">5</span>))</span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>acc_lenet <span class="op">=</span> [accuracy(lenet, shift_right(X_te, s), y_te) <span class="cf">for</span> s <span class="kw">in</span> shifts]</span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a>acc_nin <span class="op">=</span> [accuracy(nin, shift_right(X_te, s), y_te) <span class="cf">for</span> s <span class="kw">in</span> shifts]</span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> s <span class="kw">in</span> shifts:</span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"shift </span><span class="sc">{</span>s<span class="sc">}</span><span class="ss">px:   LeNet </span><span class="sc">{</span>acc_lenet[s]<span class="sc">:.1%}</span><span class="ss">   NIN+GAP </span><span class="sc">{</span>acc_nin[s]<span class="sc">:.1%}</span><span class="ss">"</span>)</span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="fl">5.5</span>, <span class="fl">3.2</span>))</span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a>plt.plot(shifts, acc_lenet, <span class="st">"s-"</span>, color<span class="op">=</span><span class="st">"#232D4B"</span>, lw<span class="op">=</span><span class="dv">2</span>, ms<span class="op">=</span><span class="dv">7</span>, label<span class="op">=</span><span class="st">"LeNet (flatten head)"</span>)</span>
<span id="cb10-34"><a href="#cb10-34" aria-hidden="true" tabindex="-1"></a>plt.plot(shifts, acc_nin, <span class="st">"^-"</span>, color<span class="op">=</span><span class="st">"#E57200"</span>, lw<span class="op">=</span><span class="dv">2</span>, ms<span class="op">=</span><span class="dv">7</span>, label<span class="op">=</span><span class="st">"NINSmall (GAP head)"</span>)</span>
<span id="cb10-35"><a href="#cb10-35" aria-hidden="true" tabindex="-1"></a>plt.axhline(<span class="fl">0.1</span>, ls<span class="op">=</span><span class="st">":"</span>, color<span class="op">=</span><span class="st">"#B8B8A8"</span>)</span>
<span id="cb10-36"><a href="#cb10-36" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"shift (pixels right)"</span>)<span class="op">;</span> plt.ylabel(<span class="st">"test accuracy"</span>)</span>
<span id="cb10-37"><a href="#cb10-37" aria-hidden="true" tabindex="-1"></a>plt.ylim(<span class="dv">0</span>, <span class="fl">0.9</span>)<span class="op">;</span> plt.xticks(shifts)<span class="op">;</span> plt.legend()</span>
<span id="cb10-38"><a href="#cb10-38" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>shift 0px:   LeNet 82.5%   NIN+GAP 76.2%
shift 1px:   LeNet 74.8%   NIN+GAP 70.3%
shift 2px:   LeNet 62.3%   NIN+GAP 69.3%
shift 3px:   LeNet 45.3%   NIN+GAP 67.5%
shift 4px:   LeNet 26.8%   NIN+GAP 66.5%</code></pre>
</div>
<div class="cell-output cell-output-display">
<div id="fig-cliff-gap" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cliff-gap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="09-modern-cnns-transfer_files/figure-html/fig-cliff-gap-output-2.png" width="520" height="297" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cliff-gap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.1: Chapter 8’s experiment, third round. LeNet’s flatten head still slides below 30% by four pixels of shift. NINSmall with its global-average-pool head barely tilts: what the head reads — per-channel averages — is almost unchanged when features move. The remaining droop is content clipped at the image edge, not position sensitivity.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The curve that fell from 82% to 27% across this book’s Part II is now a gentle slope from 76% to 67%. Position sensitivity, hunted since Chapter 6, is finally gone from the head.</p>
<p>Now the dip. On clean, centered test garments NINSmall trails LeNet by six points, and this is Chapter 8’s warning callout collecting its debt with the sign flipped: <strong>on centered data, position <em>is</em> information</strong>, and GAP threw it away. A sleeve’s location helps when every garment is framed identically; averaging it out costs accuracy exactly there. With the full 60,000-image dataset the gap closes — the lecture’s NiN reaches about 90%, near its LeNet — because more data teaches richer channel features that compensate. At our scale you see the trade nakedly: invariance is bought with information, in both directions.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Question 4’s other famous block: Inception, in one breath
</div>
</div>
<div class="callout-body-container callout-body">
<p>GoogLeNet’s Inception block (2014) answers “which kernel size?” with “all of them”: parallel <span class="math inline">\(1\times1\)</span>, <span class="math inline">\(3\times3\)</span>, <span class="math inline">\(5\times5\)</span>, and pooling branches, concatenated. Its enabling trick is the <span class="math inline">\(1\times1\)</span> <em>bottleneck</em>: compress channels before the expensive spatial kernels. The seed’s arithmetic for one <span class="math inline">\(5\times5\)</span> branch at 256 channels: direct, <span class="math inline">\(5^2 \times 256 \times 128 \approx 819\)</span>k parameters; with a <span class="math inline">\(1\times1\)</span> squeeze to 32 first, <span class="math inline">\(256 \times 32 + 5^2 \times 32 \times 128 \approx 111\)</span>k — an 86% cut for the same nominal operation. We won’t build Inception here (the principle, channel compression before spatial expense, is the transferable part), but Exercise 2 walks the arithmetic and the course assignment has you build the block itself.</p>
</div>
</div>
</section>
<section id="question-2-going-deeper-and-the-wall-you-hit" class="level2" data-number="9.5">
<h2 data-number="9.5" class="anchored" data-anchor-id="question-2-going-deeper-and-the-wall-you-hit"><span class="header-section-number">9.5</span> Question 2: going deeper, and the wall you hit</h2>
<p>VGG says depth is the direction. So push it: stack twenty of our two-conv blocks (with BN, per the recipe, on a <span class="math inline">\(14\times14\)</span> grid so the experiment fits a laptop) and compare against the <em>identical</em> stack with one change we’ll reveal after the numbers.</p>
<div id="deep-nets" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Code: a 20-block network, plain vs.&nbsp;one architectural change</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> Block(nn.Module):</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, ch: <span class="bu">int</span>, residual: <span class="bu">bool</span>):</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.c1 <span class="op">=</span> nn.Conv2d(ch, ch, <span class="dv">3</span>, padding<span class="op">=</span><span class="dv">1</span>, bias<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.b1 <span class="op">=</span> nn.BatchNorm2d(ch)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.c2 <span class="op">=</span> nn.Conv2d(ch, ch, <span class="dv">3</span>, padding<span class="op">=</span><span class="dv">1</span>, bias<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.b2 <span class="op">=</span> nn.BatchNorm2d(ch)</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.residual <span class="op">=</span> residual</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x):</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>        y <span class="op">=</span> <span class="va">self</span>.b2(<span class="va">self</span>.c2(F.relu(<span class="va">self</span>.b1(<span class="va">self</span>.c1(x)))))</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> F.relu(y <span class="op">+</span> x) <span class="cf">if</span> <span class="va">self</span>.residual <span class="cf">else</span> F.relu(y)</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> DeepNet(nn.Module):</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, nblocks: <span class="bu">int</span>, residual: <span class="bu">bool</span>, ch: <span class="bu">int</span> <span class="op">=</span> <span class="dv">12</span>):</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.stem <span class="op">=</span> nn.Conv2d(<span class="dv">1</span>, ch, <span class="dv">3</span>, padding<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.pool <span class="op">=</span> nn.MaxPool2d(<span class="dv">2</span>)                       <span class="co"># 28 -&gt; 14 early</span></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.blocks <span class="op">=</span> nn.Sequential(<span class="op">*</span>[Block(ch, residual)</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>                                      <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(nblocks)])</span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.head <span class="op">=</span> nn.Sequential(nn.AdaptiveAvgPool2d(<span class="dv">1</span>), nn.Flatten(),</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>                                  nn.Linear(ch, <span class="dv">10</span>))</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x):</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">self</span>.head(<span class="va">self</span>.blocks(<span class="va">self</span>.pool(F.relu(<span class="va">self</span>.stem(x)))))</span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a>plain <span class="op">=</span> train_model(<span class="kw">lambda</span>: DeepNet(<span class="dv">20</span>, residual<span class="op">=</span><span class="va">False</span>), epochs<span class="op">=</span><span class="dv">30</span>)</span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a>resid <span class="op">=</span> train_model(<span class="kw">lambda</span>: DeepNet(<span class="dv">20</span>, residual<span class="op">=</span><span class="va">True</span>), epochs<span class="op">=</span><span class="dv">30</span>)</span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, m <span class="kw">in</span> [(<span class="st">"plain-20   "</span>, plain), (<span class="st">"residual-20"</span>, resid)]:</span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>name<span class="sc">}</span><span class="ss">  train </span><span class="sc">{</span>accuracy(m, X_tr, y_tr)<span class="sc">:.1%}</span><span class="ss">   "</span></span>
<span id="cb12-29"><a href="#cb12-29" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"test </span><span class="sc">{</span>accuracy(m, X_te, y_te)<span class="sc">:.1%}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>plain-20     train 60.8%   test 51.0%
residual-20  train 100.0%   test 77.8%</code></pre>
</div>
</div>
<p>Look at the <em>training</em> column first, because it carries the whole lesson. The plain 40-conv-layer network cannot even fit the 1,200 images it stares at every epoch — 61% train accuracy — while its twin memorizes them completely and generalizes twenty-seven points better. This is the <strong>degradation problem</strong> exactly as He et al. reported it in 2015 (their 56-layer plain net trained <em>worse</em> than their 20-layer one): not overfitting, not vanishing capacity, but an <em>optimization</em> failure. The deep plain network is theoretically strictly more expressive — it could set twenty blocks to imitate the shallow net and coast — yet gradient descent cannot find even that.</p>
<p>The one change: each block computes <span class="math inline">\(F(x)\)</span> and outputs <span class="math inline">\(F(x) + x\)</span>. A <strong>residual connection</strong> — the input skips over the block and is added back.</p>
<p><span id="eq-residual"><span class="math display">\[
H(x) = F(x) + x
\qquad\Longrightarrow\qquad
\frac{\partial L}{\partial x}
= \frac{\partial L}{\partial H}\left(\frac{\partial F}{\partial x} + I\right).
\tag{9.2}\]</span></span></p>
<p>Read the right-hand side with Chapter 5 eyes. Blame arriving at a block’s output reaches its input through two routes: through the block’s layers (<span class="math inline">\(\partial F /
\partial x\)</span>, which may mangle it), and through the identity <span class="math inline">\(I\)</span> — untouched, unshrunk, unexploded, no matter what the block does. Chapter 5 called ReLU’s open gate a <em>gradient superhighway</em> through a single unit; the skip connection is the same highway built as civic infrastructure, one lane per block, spanning the entire network. The block only needs to learn the <em>residual</em> — the correction on top of “pass it through” — and doing nothing is now the easiest thing in the world to learn: <span class="math inline">\(F = 0\)</span>.</p>
<p>Here is the highway visible at initialization, extending Chapter 5’s depth experiment from dense layers to conv stacks:</p>
<div id="cell-fig-gradient-highway" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Code: gradient at the stem vs.&nbsp;depth, three designs</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> PlainNoBN(nn.Module):</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, nconvs: <span class="bu">int</span>, ch: <span class="bu">int</span> <span class="op">=</span> <span class="dv">12</span>):</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.stem <span class="op">=</span> nn.Conv2d(<span class="dv">1</span>, ch, <span class="dv">3</span>, padding<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.pool <span class="op">=</span> nn.MaxPool2d(<span class="dv">2</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.layers <span class="op">=</span> nn.Sequential(<span class="op">*</span>[m <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(nconvs)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>                                      <span class="cf">for</span> m <span class="kw">in</span> (nn.Conv2d(ch, ch, <span class="dv">3</span>, padding<span class="op">=</span><span class="dv">1</span>),</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>                                                nn.ReLU())])</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.head <span class="op">=</span> nn.Sequential(nn.AdaptiveAvgPool2d(<span class="dv">1</span>), nn.Flatten(),</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>                                  nn.Linear(ch, <span class="dv">10</span>))</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x):</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">self</span>.head(<span class="va">self</span>.layers(<span class="va">self</span>.pool(F.relu(<span class="va">self</span>.stem(x)))))</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> stem_grad(make_net):</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>    torch.manual_seed(<span class="dv">0</span>)</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>    net <span class="op">=</span> make_net()</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>    F.cross_entropy(net(X_tr[:<span class="dv">128</span>]), y_tr[:<span class="dv">128</span>]).backward()</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> net.stem.weight.grad.norm().item()</span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>depths <span class="op">=</span> [<span class="dv">4</span>, <span class="dv">12</span>, <span class="dv">24</span>]                                  <span class="co"># blocks (2 convs each)</span></span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a>curves <span class="op">=</span> {</span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">"plain, no BN"</span>: [stem_grad(<span class="kw">lambda</span> d<span class="op">=</span>d: PlainNoBN(<span class="dv">2</span> <span class="op">*</span> d)) <span class="cf">for</span> d <span class="kw">in</span> depths],</span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a>    <span class="st">"plain + BN"</span>: [stem_grad(<span class="kw">lambda</span> d<span class="op">=</span>d: DeepNet(d, <span class="va">False</span>)) <span class="cf">for</span> d <span class="kw">in</span> depths],</span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a>    <span class="st">"residual + BN"</span>: [stem_grad(<span class="kw">lambda</span> d<span class="op">=</span>d: DeepNet(d, <span class="va">True</span>)) <span class="cf">for</span> d <span class="kw">in</span> depths],</span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb14-26"><a href="#cb14-26" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, ys <span class="kw">in</span> curves.items():</span>
<span id="cb14-27"><a href="#cb14-27" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>name<span class="sc">:14s}</span><span class="ss">: "</span> <span class="op">+</span> <span class="st">"   "</span>.join(<span class="ss">f"</span><span class="sc">{</span>v<span class="sc">:.1e}</span><span class="ss">"</span> <span class="cf">for</span> v <span class="kw">in</span> ys))</span>
<span id="cb14-28"><a href="#cb14-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-29"><a href="#cb14-29" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="fl">6.2</span>, <span class="fl">3.4</span>))</span>
<span id="cb14-30"><a href="#cb14-30" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (name, ys), color <span class="kw">in</span> <span class="bu">zip</span>(curves.items(),</span>
<span id="cb14-31"><a href="#cb14-31" aria-hidden="true" tabindex="-1"></a>                             [<span class="st">"#B8B8A8"</span>, <span class="st">"#E57200"</span>, <span class="st">"#232D4B"</span>]):</span>
<span id="cb14-32"><a href="#cb14-32" aria-hidden="true" tabindex="-1"></a>    xs <span class="op">=</span> [<span class="dv">2</span> <span class="op">*</span> d <span class="cf">for</span> d <span class="kw">in</span> depths]</span>
<span id="cb14-33"><a href="#cb14-33" aria-hidden="true" tabindex="-1"></a>    shown <span class="op">=</span> [y <span class="cf">if</span> y <span class="op">&gt;</span> <span class="dv">0</span> <span class="cf">else</span> <span class="fl">1e-24</span> <span class="cf">for</span> y <span class="kw">in</span> ys]       <span class="co"># exact 0 -&gt; sentinel to plot it</span></span>
<span id="cb14-34"><a href="#cb14-34" aria-hidden="true" tabindex="-1"></a>    plt.semilogy(xs, shown, <span class="st">"o-"</span>, ms<span class="op">=</span><span class="dv">5</span>, color<span class="op">=</span>color, label<span class="op">=</span>name)</span>
<span id="cb14-35"><a href="#cb14-35" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> x, y <span class="kw">in</span> <span class="bu">zip</span>(xs, ys):</span>
<span id="cb14-36"><a href="#cb14-36" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> y <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb14-37"><a href="#cb14-37" aria-hidden="true" tabindex="-1"></a>            plt.annotate(<span class="st">"exact 0 (underflow)"</span>, (x, <span class="fl">1e-24</span>), fontsize<span class="op">=</span><span class="dv">8</span>,</span>
<span id="cb14-38"><a href="#cb14-38" aria-hidden="true" tabindex="-1"></a>                         color<span class="op">=</span>color, textcoords<span class="op">=</span><span class="st">"offset points"</span>, xytext<span class="op">=</span>(<span class="op">-</span><span class="dv">88</span>, <span class="dv">4</span>))</span>
<span id="cb14-39"><a href="#cb14-39" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"conv layers"</span>)<span class="op">;</span> plt.ylabel(<span class="vs">r"</span><span class="dv">$</span><span class="ch">\|</span><span class="er">\</span><span class="vs">partial L / </span><span class="er">\</span><span class="vs">partial W</span><span class="dv">^</span><span class="vs">{</span><span class="kw">(</span><span class="dv">\m</span><span class="vs">athrm{stem}</span><span class="kw">)</span><span class="vs">}</span><span class="ch">\|</span><span class="dv">$</span><span class="vs">"</span>)</span>
<span id="cb14-40"><a href="#cb14-40" aria-hidden="true" tabindex="-1"></a>plt.legend()<span class="op">;</span> plt.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>plain, no BN  : 9.0e-06   3.3e-13   0.0e+00
plain + BN    : 7.6e-02   5.0e-01   8.3e+01
residual + BN : 1.6e-01   4.9e-01   5.0e-01</code></pre>
</div>
<div class="cell-output cell-output-display">
<div id="fig-gradient-highway" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gradient-highway-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="09-modern-cnns-transfer_files/figure-html/fig-gradient-highway-output-2.png" width="585" height="316" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-gradient-highway-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.2: Gradient magnitude reaching the stem (first layer) at initialization, versus depth, for three designs. Without BN the gradient underflows to <em>exactly zero</em> by 48 layers (annotated point): Chapter 5’s float-precision death, now caused by nothing but depth. BN alone fixes the vanishing but overshoots — in plain stacks the gradient <em>grows</em> with depth, an instability of its own. Residual blocks hold the gradient within one order of magnitude at every depth: the highway delivers.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>The most important seed this chapter plants
</div>
</div>
<div class="callout-body-container callout-body">
<p>Residual connections are not a CNN trick. They are <em>the</em> enabling device of every large model you have heard of: when we assemble a transformer in 1, every attention layer and every feed-forward layer will be wrapped as <span class="math inline">\(x + F(x)\)</span>, and the freshly-met layer normalization will sit beside each skip. The picture to carry forward: a <em>residual stream</em> flowing unimpeded through the network, with each block reading from it and writing small corrections back. Attention will be one kind of correction. You now own both parts of that skeleton.</p>
</div>
</div>
</section>
<section id="the-scorecard-what-a-decade-of-design-bought" class="level2" data-number="9.6">
<h2 data-number="9.6" class="anchored" data-anchor-id="the-scorecard-what-a-decade-of-design-bought"><span class="header-section-number">9.6</span> The scorecard: what a decade of design bought</h2>
<p>The lecture closes its architecture tour with a scatter worth reproducing — every model of Part II on one canvas, accuracy against parameters, each trained to convergence under our shared recipe:</p>
<div id="cell-fig-scorecard" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>Code: accuracy vs.&nbsp;parameters scatter</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>models_ <span class="op">=</span> {</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"LeNet"</span>: (lenet, <span class="st">"#B8B8A8"</span>),</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"VGGSmall"</span>: (vgg, <span class="st">"#E57200"</span>),</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"NIN+GAP"</span>: (nin, <span class="st">"#232D4B"</span>),</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"plain-20"</span>: (plain, <span class="st">"#DDA0DD"</span>),</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"residual-20"</span>: (resid, <span class="st">"#5379AA"</span>),</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="fl">6.2</span>, <span class="fl">3.6</span>))</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, (m, color) <span class="kw">in</span> models_.items():</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    p, a <span class="op">=</span> count(m), accuracy(m, X_te, y_te)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>    plt.scatter(p, a, s<span class="op">=</span><span class="dv">70</span>, color<span class="op">=</span>color, zorder<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>    plt.annotate(name, (p, a), textcoords<span class="op">=</span><span class="st">"offset points"</span>,</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>                 xytext<span class="op">=</span>(<span class="dv">8</span>, <span class="op">-</span><span class="dv">3</span>), fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>plt.xscale(<span class="st">"log"</span>)</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"parameters (log scale)"</span>)<span class="op">;</span> plt.ylabel(<span class="st">"test accuracy"</span>)</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>plt.ylim(<span class="fl">0.45</span>, <span class="fl">0.95</span>)</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-scorecard" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-scorecard-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="09-modern-cnns-transfer_files/figure-html/fig-scorecard-output-1.png" width="588" height="335" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-scorecard-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.3: Part II’s models on one canvas (our 1,200-image subset; each model trained to convergence with the shared Adam recipe). VGG-style depth buys accuracy but hoards parameters in its flatten head; NiN+GAP evicts the head at a visible cost in clean accuracy at this data scale; residual blocks let a 47k-parameter network go 40 layers deep. The frontier the lecture reports on the full dataset — everything above 89% — needs data our subset does not have; the <em>shape</em> of the trade-offs is already exactly right.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>GPU run pending
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Planned:</strong> the full-dataset version of this scorecard — LeNet, VGG, NiN, and a deep ResNet trained on all 60,000 Fashion-MNIST images — to reproduce the lecture’s frontier (LeNet ≈ 89%, VGG &gt; 90%, NiN ≈ 90% at 30k parameters, ResNet higher still). <strong>Meanwhile:</strong> the lecture’s numbers are quoted in the caption above.</p>
</div>
</div>
</section>
<section id="transfer-learning-the-mechanics-and-an-honest-experiment" class="level2" data-number="9.7">
<h2 data-number="9.7" class="anchored" data-anchor-id="transfer-learning-the-mechanics-and-an-honest-experiment"><span class="header-section-number">9.7</span> Transfer learning: the mechanics, and an honest experiment</h2>
<p>Everything so far trains from scratch. The lecture’s final move is the one that defines practice today: most image features are <em>shared</em> — edges, textures, parts transfer across tasks — so train one strong backbone once, on enormous data, and reuse it everywhere. The mechanics come in two strengths:</p>
<ul>
<li><strong>Linear probe</strong>: freeze the pretrained trunk entirely (<code>requires_grad = False</code>), extract its features, train only a new linear head on your labels.</li>
<li><strong>Fine-tuning</strong>: additionally unfreeze the last block or two, training them at a <em>much</em> smaller learning rate than the fresh head, so the pretrained features adapt gently instead of being trampled.</li>
</ul>
<p>We will test the idea properly. The task: classify the three shoe classes (sandal, sneaker, ankle boot) from <strong>ten labeled examples each</strong>. The 30-image regime is exactly where transfer should shine — too few labels to learn features, goes the story, so imported features should dominate. Three contenders:</p>
<ol type="1">
<li><strong>From scratch</strong>: our VGG-style trunk trained on the 30 images alone.</li>
<li><strong>Our own pretrained trunk</strong>: the same trunk pretrained on the seven <em>non-shoe</em> classes (863 images), frozen, linear probe.</li>
<li><strong>A real pretrained backbone</strong>: SqueezeNet 1.1 trained on ImageNet — 1.2 million photographs, 1,000 classes — loaded from weights committed with this book, frozen, linear probe on its 512-dimensional features. (Fashion images get upsampled to 96×96 and repeated to three channels to fit its expectations. That awkwardness is part of the experiment, and part of the lesson.)</li>
</ol>
<div id="transfer-setup" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>Code: the shoe task, our own trunk, and the frozen probes</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> torchvision.models <span class="im">import</span> squeezenet1_1</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>shoe <span class="op">=</span> torch.tensor([<span class="dv">5</span>, <span class="dv">7</span>, <span class="dv">9</span>])</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>new_label <span class="op">=</span> {<span class="dv">5</span>: <span class="dv">0</span>, <span class="dv">7</span>: <span class="dv">1</span>, <span class="dv">9</span>: <span class="dv">2</span>}</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>is_shoe_tr <span class="op">=</span> (y_tr[:, <span class="va">None</span>] <span class="op">==</span> shoe).<span class="bu">any</span>(<span class="dv">1</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>is_shoe_te <span class="op">=</span> (y_te[:, <span class="va">None</span>] <span class="op">==</span> shoe).<span class="bu">any</span>(<span class="dv">1</span>)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>X_shoe_te <span class="op">=</span> X_te[is_shoe_te]</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>y_shoe_te <span class="op">=</span> torch.tensor([new_label[<span class="bu">int</span>(c)] <span class="cf">for</span> c <span class="kw">in</span> y_te[is_shoe_te]])</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="co"># our own trunk: pretrain on the 7 non-shoe classes</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>src <span class="op">=</span> [<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">8</span>]</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>remap <span class="op">=</span> {c: i <span class="cf">for</span> i, c <span class="kw">in</span> <span class="bu">enumerate</span>(src)}</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>X_src <span class="op">=</span> X_tr[<span class="op">~</span>is_shoe_tr]</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>y_src <span class="op">=</span> torch.tensor([remap[<span class="bu">int</span>(c)] <span class="cf">for</span> c <span class="kw">in</span> y_tr[<span class="op">~</span>is_shoe_tr]])</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> Trunk(nn.Module):</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, n_classes: <span class="bu">int</span>):</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.features <span class="op">=</span> nn.Sequential(</span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>            <span class="op">*</span>atom(<span class="dv">1</span>, <span class="dv">16</span>), <span class="op">*</span>atom(<span class="dv">16</span>, <span class="dv">16</span>), nn.MaxPool2d(<span class="dv">2</span>),</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>            <span class="op">*</span>atom(<span class="dv">16</span>, <span class="dv">32</span>), <span class="op">*</span>atom(<span class="dv">32</span>, <span class="dv">32</span>), nn.MaxPool2d(<span class="dv">2</span>), <span class="op">*</span>atom(<span class="dv">32</span>, <span class="dv">64</span>))</span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.head <span class="op">=</span> nn.Sequential(nn.AdaptiveAvgPool2d(<span class="dv">1</span>), nn.Flatten(),</span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>                                  nn.Linear(<span class="dv">64</span>, n_classes))</span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x):</span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">self</span>.head(<span class="va">self</span>.features(x))</span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a>own_trunk <span class="op">=</span> train_model(<span class="kw">lambda</span>: Trunk(<span class="dv">7</span>), epochs<span class="op">=</span><span class="dv">100</span>, data<span class="op">=</span>(X_src, y_src))</span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a>X_src_te <span class="op">=</span> X_te[<span class="op">~</span>is_shoe_te]</span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a>y_src_te <span class="op">=</span> torch.tensor([remap[<span class="bu">int</span>(c)] <span class="cf">for</span> c <span class="kw">in</span> y_te[<span class="op">~</span>is_shoe_te]])</span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"own trunk, source task (7 classes): "</span></span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>accuracy(own_trunk, X_src_te, y_src_te)<span class="sc">:.1%}</span><span class="ss">"</span>)</span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-33"><a href="#cb17-33" aria-hidden="true" tabindex="-1"></a><span class="co"># the real thing: ImageNet SqueezeNet, from committed weights (no download)</span></span>
<span id="cb17-34"><a href="#cb17-34" aria-hidden="true" tabindex="-1"></a>sq <span class="op">=</span> squeezenet1_1(weights<span class="op">=</span><span class="va">None</span>)</span>
<span id="cb17-35"><a href="#cb17-35" aria-hidden="true" tabindex="-1"></a>sq.load_state_dict(torch.load(<span class="st">"../../data/squeezenet1_1-imagenet.pt"</span>))</span>
<span id="cb17-36"><a href="#cb17-36" aria-hidden="true" tabindex="-1"></a>sq.<span class="bu">eval</span>()</span>
<span id="cb17-37"><a href="#cb17-37" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> p <span class="kw">in</span> sq.parameters():</span>
<span id="cb17-38"><a href="#cb17-38" aria-hidden="true" tabindex="-1"></a>    p.requires_grad <span class="op">=</span> <span class="va">False</span></span>
<span id="cb17-39"><a href="#cb17-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-40"><a href="#cb17-40" aria-hidden="true" tabindex="-1"></a>IMNET_MEAN <span class="op">=</span> torch.tensor([<span class="fl">0.485</span>, <span class="fl">0.456</span>, <span class="fl">0.406</span>]).view(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb17-41"><a href="#cb17-41" aria-hidden="true" tabindex="-1"></a>IMNET_STD <span class="op">=</span> torch.tensor([<span class="fl">0.229</span>, <span class="fl">0.224</span>, <span class="fl">0.225</span>]).view(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb17-42"><a href="#cb17-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-43"><a href="#cb17-43" aria-hidden="true" tabindex="-1"></a><span class="at">@torch.no_grad</span>()</span>
<span id="cb17-44"><a href="#cb17-44" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> squeeze_features(X):                       <span class="co"># (N,1,28,28) -&gt; (N,512)</span></span>
<span id="cb17-45"><a href="#cb17-45" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> X.repeat(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb17-46"><a href="#cb17-46" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> F.interpolate(x, size<span class="op">=</span><span class="dv">96</span>, mode<span class="op">=</span><span class="st">"bilinear"</span>, align_corners<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb17-47"><a href="#cb17-47" aria-hidden="true" tabindex="-1"></a>    f <span class="op">=</span> sq.features((x <span class="op">-</span> IMNET_MEAN) <span class="op">/</span> IMNET_STD)</span>
<span id="cb17-48"><a href="#cb17-48" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> F.adaptive_avg_pool2d(f, <span class="dv">1</span>).flatten(<span class="dv">1</span>)</span>
<span id="cb17-49"><a href="#cb17-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-50"><a href="#cb17-50" aria-hidden="true" tabindex="-1"></a><span class="at">@torch.no_grad</span>()</span>
<span id="cb17-51"><a href="#cb17-51" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> own_features(X):                           <span class="co"># (N,1,28,28) -&gt; (N,64)</span></span>
<span id="cb17-52"><a href="#cb17-52" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> F.adaptive_avg_pool2d(own_trunk.features(X), <span class="dv">1</span>).flatten(<span class="dv">1</span>)</span>
<span id="cb17-53"><a href="#cb17-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-54"><a href="#cb17-54" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> linear_probe(Z_tr, y_f, Z_te, seed):</span>
<span id="cb17-55"><a href="#cb17-55" aria-hidden="true" tabindex="-1"></a>    torch.manual_seed(seed)</span>
<span id="cb17-56"><a href="#cb17-56" aria-hidden="true" tabindex="-1"></a>    head <span class="op">=</span> nn.Linear(Z_tr.shape[<span class="dv">1</span>], <span class="dv">3</span>)</span>
<span id="cb17-57"><a href="#cb17-57" aria-hidden="true" tabindex="-1"></a>    opt <span class="op">=</span> torch.optim.Adam(head.parameters(), lr<span class="op">=</span><span class="fl">1e-2</span>,</span>
<span id="cb17-58"><a href="#cb17-58" aria-hidden="true" tabindex="-1"></a>                           weight_decay<span class="op">=</span><span class="fl">1e-3</span>)   <span class="co"># built-in L2 penalty (ch. 1's ridge)</span></span>
<span id="cb17-59"><a href="#cb17-59" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">400</span>):</span>
<span id="cb17-60"><a href="#cb17-60" aria-hidden="true" tabindex="-1"></a>        loss <span class="op">=</span> F.cross_entropy(head(Z_tr), y_f)</span>
<span id="cb17-61"><a href="#cb17-61" aria-hidden="true" tabindex="-1"></a>        opt.zero_grad()<span class="op">;</span> loss.backward()<span class="op">;</span> opt.step()</span>
<span id="cb17-62"><a href="#cb17-62" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (head(Z_te).argmax(<span class="dv">1</span>) <span class="op">==</span> y_shoe_te).<span class="bu">float</span>().mean().item()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>own trunk, source task (7 classes): 79.7%</code></pre>
</div>
</div>
<div id="transfer-experiment" class="cell" data-execution_count="11">
<details class="code-fold">
<summary>Code: scratch vs.&nbsp;own trunk vs.&nbsp;ImageNet trunk, three seeds</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>K <span class="op">=</span> <span class="dv">10</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> []</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> seed <span class="kw">in</span> [<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">6050</span>]:</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    torch.manual_seed(seed)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    idx <span class="op">=</span> torch.cat([(y_tr <span class="op">==</span> c).nonzero().squeeze(<span class="dv">1</span>)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>                     [torch.randperm(<span class="bu">int</span>((y_tr <span class="op">==</span> c).<span class="bu">sum</span>()))[:K]] <span class="cf">for</span> c <span class="kw">in</span> shoe])</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>    X_few <span class="op">=</span> X_tr[idx]</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>    y_few <span class="op">=</span> torch.tensor([new_label[<span class="bu">int</span>(c)] <span class="cf">for</span> c <span class="kw">in</span> y_tr[idx]])</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>    scratch <span class="op">=</span> train_model(<span class="kw">lambda</span>: Trunk(<span class="dv">3</span>), epochs<span class="op">=</span><span class="dv">100</span>, seed<span class="op">=</span>seed,</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>                          data<span class="op">=</span>(X_few, y_few))</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>    rows.append((accuracy(scratch, X_shoe_te, y_shoe_te),</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>                 linear_probe(own_features(X_few), y_few,</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>                              own_features(X_shoe_te), seed),</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>                 linear_probe(squeeze_features(X_few), y_few,</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>                              squeeze_features(X_shoe_te), seed)))</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"seed     scratch   own-trunk probe   ImageNet probe"</span>)</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> seed, r <span class="kw">in</span> <span class="bu">zip</span>([<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">6050</span>], rows):</span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>seed<span class="sc">:4d}</span><span class="ss">     </span><span class="sc">{</span>r[<span class="dv">0</span>]<span class="sc">:.1%}</span><span class="ss">       </span><span class="sc">{</span>r[<span class="dv">1</span>]<span class="sc">:.1%}</span><span class="ss">           </span><span class="sc">{</span>r[<span class="dv">2</span>]<span class="sc">:.1%}</span><span class="ss">"</span>)</span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>mean <span class="op">=</span> [<span class="bu">sum</span>(c) <span class="op">/</span> <span class="dv">3</span> <span class="cf">for</span> c <span class="kw">in</span> <span class="bu">zip</span>(<span class="op">*</span>rows)]</span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"mean     </span><span class="sc">{</span>mean[<span class="dv">0</span>]<span class="sc">:.1%}</span><span class="ss">       </span><span class="sc">{</span>mean[<span class="dv">1</span>]<span class="sc">:.1%}</span><span class="ss">           </span><span class="sc">{</span>mean[<span class="dv">2</span>]<span class="sc">:.1%}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>seed     scratch   own-trunk probe   ImageNet probe
   0     86.4%       68.9%           88.1%
   1     85.3%       65.5%           85.9%
6050     88.1%       77.4%           87.6%
mean     86.6%       70.6%           87.2%</code></pre>
</div>
</div>
<p>Read that table slowly, because it does <em>not</em> say what the textbook story predicts, and the discrepancy is the best lesson in this chapter. Training from scratch on thirty images fights the mighty ImageNet backbone to a dead heat — the means differ by less than a point, well inside seed noise. And our own pretrained trunk, perfectly competent on its source task per the printout above, transfers <em>worse than nothing</em>. Three reasons, each a general principle:</p>
<ol type="1">
<li><strong>A trunk can only donate what its data taught it.</strong> Our own trunk saw 863 shirts, bags, and trousers. Nothing in that curriculum required foot-shaped detectors, so its 64 features flatten sandals, sneakers, and boots into nearly the same point. Pretraining is not magic; it is <em>curriculum</em>.</li>
<li><strong>Domain and resolution gaps tax the donation.</strong> SqueezeNet’s filters expect 224-pixel color photographs; we feed it 28-pixel grayscale icons inflated to 96. Its early layers hunt for detail that simply is not there. (The lecture’s recipe — resize and normalize <em>to match the pretraining pipeline</em> — is doing real work; we complied as far as the data allows.)</li>
<li><strong>Transfer wins when the target is big relative to your labels — not small.</strong> This is the quiet one. Three shoe silhouettes at <span class="math inline">\(28 \times 28\)</span> is a <em>small</em> problem: thirty images genuinely suffice, so the scratch baseline is strong and there is little room for imported knowledge to pay rent. The lecture’s numbers show the other regime: linear-probing an ImageNet ResNet-18 on the <em>full</em> FashionMNIST task reaches about 93%, and fine-tuning about 94% — at 224 pixels, with a task rich enough that features matter more than labels.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>When to reach for a pretrained backbone
</div>
</div>
<div class="callout-body-container callout-body">
<p>The honest decision rule our experiment and the lecture’s jointly support: transfer pays when (your labels are scarce) <em>and</em> (the target task is feature-hungry) <em>and</em> (the pretraining data plausibly covers the target’s features at a matched scale). At 224 pixels and 18 landmark classes — the course assignment — all three hold, and transfer is the winning move by a wide margin. At 28 pixels and 3 silhouettes, the conditions fail and scratch fights the superpower to a draw. Knowing <em>which regime you are in</em> is the skill; the mechanics (<code>requires_grad</code>, learning-rate splits) are the easy part.</p>
</div>
</div>
<p>The mechanics, for completeness, since you will use them constantly from Part V onward — fine-tuning SqueezeNet’s last block with the lecture’s two-learning-rate recipe (fresh head fast, pretrained layers slow):</p>
<div id="fine-tune" class="cell" data-execution_count="12">
<details class="code-fold">
<summary>Code: fine-tuning — unfreeze the last block, two learning rates</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> prep(X):</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> X.repeat(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> F.interpolate(x, size<span class="op">=</span><span class="dv">96</span>, mode<span class="op">=</span><span class="st">"bilinear"</span>, align_corners<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (x <span class="op">-</span> IMNET_MEAN) <span class="op">/</span> IMNET_STD</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>torch.manual_seed(<span class="dv">6050</span>)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>idx <span class="op">=</span> torch.cat([(y_tr <span class="op">==</span> c).nonzero().squeeze(<span class="dv">1</span>)</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>                 [torch.randperm(<span class="bu">int</span>((y_tr <span class="op">==</span> c).<span class="bu">sum</span>()))[:K]] <span class="cf">for</span> c <span class="kw">in</span> shoe])</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>X_few, y_few <span class="op">=</span> prep(X_tr[idx]), torch.tensor([new_label[<span class="bu">int</span>(c)]</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>                                              <span class="cf">for</span> c <span class="kw">in</span> y_tr[idx]])</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>ft <span class="op">=</span> squeezenet1_1(weights<span class="op">=</span><span class="va">None</span>)</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>ft.load_state_dict(torch.load(<span class="st">"../../data/squeezenet1_1-imagenet.pt"</span>))</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>head <span class="op">=</span> nn.Linear(<span class="dv">512</span>, <span class="dv">3</span>)</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> p <span class="kw">in</span> ft.parameters():</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>    p.requires_grad <span class="op">=</span> <span class="va">False</span></span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> p <span class="kw">in</span> ft.features[<span class="op">-</span><span class="dv">1</span>].parameters():         <span class="co"># last Fire block only</span></span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>    p.requires_grad <span class="op">=</span> <span class="va">True</span></span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>opt <span class="op">=</span> torch.optim.Adam([</span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"params"</span>: head.parameters(), <span class="st">"lr"</span>: <span class="fl">1e-3</span>},          <span class="co"># fresh head: normal speed</span></span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"params"</span>: ft.features[<span class="op">-</span><span class="dv">1</span>].parameters(), <span class="st">"lr"</span>: <span class="fl">1e-4</span>},  <span class="co"># pretrained: gentle</span></span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a>], weight_decay<span class="op">=</span><span class="fl">1e-3</span>)</span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a>ft.train()</span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">60</span>):</span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a>    z <span class="op">=</span> F.adaptive_avg_pool2d(ft.features(X_few), <span class="dv">1</span>).flatten(<span class="dv">1</span>)</span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a>    loss <span class="op">=</span> F.cross_entropy(head(z), y_few)</span>
<span id="cb21-29"><a href="#cb21-29" aria-hidden="true" tabindex="-1"></a>    opt.zero_grad()<span class="op">;</span> loss.backward()<span class="op">;</span> opt.step()</span>
<span id="cb21-30"><a href="#cb21-30" aria-hidden="true" tabindex="-1"></a>ft.<span class="bu">eval</span>()</span>
<span id="cb21-31"><a href="#cb21-31" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> torch.no_grad():</span>
<span id="cb21-32"><a href="#cb21-32" aria-hidden="true" tabindex="-1"></a>    z <span class="op">=</span> F.adaptive_avg_pool2d(ft.features(prep(X_shoe_te)), <span class="dv">1</span>).flatten(<span class="dv">1</span>)</span>
<span id="cb21-33"><a href="#cb21-33" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"fine-tuned (last block + head): "</span></span>
<span id="cb21-34"><a href="#cb21-34" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"</span><span class="sc">{</span>(head(z).argmax(<span class="dv">1</span>) <span class="op">==</span> y_shoe_te)<span class="sc">.</span><span class="bu">float</span>()<span class="sc">.</span>mean()<span class="sc">:.1%}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>fine-tuned (last block + head): 88.7%</code></pre>
</div>
</div>
<p>Fine-tuning edges the frozen probe on this seed and lands in the same tie with scratch — consistent with the regime analysis above: adaptation helps at the margin, but no amount of it makes a small target task need imported features.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>GPU run pending
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Planned:</strong> the lecture’s full-scale experiment — ImageNet ResNet-18 on the complete FashionMNIST task at 224 pixels: linear probe (expect ≈ 93%), last-block fine-tune (≈ 94%), against a from-scratch baseline — the regime where all three transfer conditions hold. <strong>Meanwhile:</strong> the lecture’s numbers are quoted in the analysis above. ::: Keep the pattern, though: <em>this</em> loop, scaled to real backbones and feature-hungry tasks, is how most of applied deep learning ships today. It is also this book’s destination: Part V is what happened when the field noticed that “pretrain big, adapt cheaply” was not a vision trick but <em>the</em> recipe — for language too. The BERT moment (<a href="../part4/15-bert-pretraining.html" class="quarto-xref"><span>Chapter 15</span></a>) is this section’s idea, taken seriously at scale.</p>
<section id="okay-so" class="level2" data-number="9.8">
<h2 data-number="9.8" class="anchored" data-anchor-id="okay-so"><span class="header-section-number">9.8</span> Okay, so —</h2>
<ol type="1">
<li><strong>Small kernels, stacked</strong>: two <span class="math inline">\(3\times3\)</span>s see what a <span class="math inline">\(5\times5\)</span> sees, for <span class="math inline">\(18C^2\)</span> against <span class="math inline">\(25C^2\)</span>, with twice the nonlinearity — provided width holds constant through the stack. Design in blocks, repeat the block.</li>
<li><strong>BatchNorm</strong> re-standardizes every channel over the minibatch and hands back two knobs (<span class="math inline">\(\gamma, \beta\)</span>); conv→BN→ReLU with <code>bias=False</code>; <em>train and eval are different machines</em> — flip the switch. Its per-token cousin, LayerNorm, awaits in
<ol class="example" type="1">
<li></li>
</ol></li>
<li><strong><span class="math inline">\(1\times1\)</span> convolutions</strong> run Chapter 1’s linear model across channels at every pixel: summarize channels, don’t discard them. With <strong>global average pooling</strong> they fire the flatten head — parameters collapse (218k <span class="math inline">\(\rightarrow\)</span> 35k) and position sensitivity leaves the network for good, at a clean-accuracy price our small dataset makes visible.</li>
<li><strong>Depth hits an optimization wall, not a capacity wall</strong>: our plain 40-layer net couldn’t fit its own training set. The residual connection <span class="math inline">\(H(x) = F(x) + x\)</span> adds an identity lane to the Jacobian — Chapter 5’s gradient superhighway as infrastructure — and the same-depth twin trains to 100%. Transformers will be built from nothing but such blocks.</li>
<li><strong>Transfer learning</strong> = freeze + probe, or gently fine-tune. Our honest experiment found scratch unbeatable at 28-pixel scale — pretraining is curriculum, gaps are taxed, and small targets don’t need imports — while the lecture’s full-scale runs (93–94% via ImageNet ResNet-18) show the regime where transfer rules. Diagnosing the regime is the skill.</li>
</ol>
</section>
<section id="exercises" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercises">Exercises</h2>
<ol type="1">
<li><strong>(Pencil.)</strong> Generalize the kernel-stacking arithmetic: <span class="math inline">\(n\)</span> stacked <span class="math inline">\(3\times3\)</span> layers versus one <span class="math inline">\((2n{+}1)\times(2n{+}1)\)</span> kernel, at constant width <span class="math inline">\(C\)</span>. Then redo it for a layer that grows channels <span class="math inline">\(C \rightarrow 2C\)</span>: split into two <span class="math inline">\(3\times3\)</span>s (<span class="math inline">\(C \rightarrow C \rightarrow 2C\)</span> and <span class="math inline">\(C \rightarrow 2C \rightarrow
2C\)</span>) and find when the split stops saving parameters.</li>
<li><strong>(Pencil.)</strong> Verify the Inception bottleneck arithmetic from the callout (<span class="math inline">\(819{,}200\)</span> versus <span class="math inline">\(110{,}592\)</span>), then design the cheapest <span class="math inline">\(1\times1\)</span>-plus- <span class="math inline">\(5\times5\)</span> pipeline from 128 channels to 64 output channels that keeps the squeeze width at least a quarter of the input width.</li>
<li><strong>(Code.)</strong> Make VGGSmall’s blocks <em>depthwise separable</em>: replace each <span class="math inline">\(3\times3\)</span> conv with a per-channel <span class="math inline">\(3\times3\)</span> (<code>groups=c_in</code>) followed by a <span class="math inline">\(1\times1\)</span> mixer. Count parameters, retrain, and report the accuracy-per-parameter ratio against the original. (This is MobileNet’s trick for phones — the lecture’s fifth principle.)</li>
<li><strong>(Code.)</strong> Ablate BatchNorm: retrain VGGSmall with the BN layers removed, same budget. Compare final accuracy <em>and</em> the first ten epochs’ training accuracy. Then repeat the <code>bn-drift</code> cell’s measurement on both trained networks — does training itself fix the activation scales?</li>
<li><strong>(Code.)</strong> Data augmentation as a third road: on the 30-image shoe task, train from scratch with random horizontal flips and ±3-pixel shifts (Chapter 6’s exercise, now as a tool). Does augmentation close the gap to the lecture’s full-data numbers further than transfer did? Why might augmentation and transfer help in <em>different</em> regimes?</li>
</ol>


</section>
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/shakeri-lab\.github\.io\/dl-book\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../chapters/part2/08-cnn.html" class="pagination-link" aria-label="CNNs: Making the Filters Learnable">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">CNNs: Making the Filters Learnable</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/part3/10-sequences-rnn.html" class="pagination-link" aria-label="Sequences and Recurrence">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Sequences and Recurrence</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Heman Shakeri · Text CC BY-NC-SA 4.0 · Code MIT · School of Data Science, University of Virginia</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/Shakeri-Lab/dl-book/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Companion to <a href="https://shakeri-lab.github.io/dl-course-site/">DS 6050 Deep Learning</a></p>
</div>
  </div>
</footer>




</body></html>