{
  "hash": "670423100aa332d9c4ca7438d38182dc",
  "result": {
    "engine": "jupyter",
    "markdown": "# Self-Attention and the Transformer {#sec-14-self-attention-transformer}\n\n<!-- lecture-source:\n     m09_lecture-9-transformer_N4ePLi42ADk.txt\n     [coding]_m09_lecture-9-2-transformer-part-2_tG8b2eNm6Gg.txt\n     (spine via ds6050_09_transformer/MODULE_NOTES.md; scene compositions from\n     that module's Manim source)\n     seeds: sources/9.1-self-attention.tex,\n            sources/9.A.1-positional_encoding.tex,\n            sources/9.1A-Normalization_in_Transformers.tex\n     primary sources: Vaswani et al. 2017; Ba et al. 2016;\n                      Xiong et al. 2020; Geva et al. 2021;\n                      Jain and Wallace 2019\n     provenance note: all executable implementations were independently derived\n     from the displayed equations. The book-corpus schedule is reconstructed from\n     the book-original Chapter 10 cell. The experiment uses a custom decoder-only,\n     pre-LayerNorm Transformer rather than the original encoder-decoder,\n     post-LayerNorm architecture. It makes no measured hardware-speed claim. -->\n\n@sec-13-attention ended with a question that the attention operator itself had already\nanswered. A query, key, and value need not come from an encoder or a decoder. They\nneed not come from a recurrent network at all. If all three come from the same\nsequence, each token can ask every token—including itself—what matters and route the answers\ndirectly. The recurrent state—the last serial bottleneck left standing—becomes\noptional.\n\nThat substitution is the core of a *Transformer*. It is also easy to state too\nquickly. Removing recurrence creates a position problem. Splitting one attention\noperation into heads creates a bookkeeping problem. Stacking the resulting\noperations creates an optimization problem. This chapter solves each one—from the\nequations outward—then returns to the book-corpus benchmark from\n@sec-10-sequences-rnn with a\ndeliberately small causal Transformer.\n\n<!-- NOVEL: needs sign-off - opening preview of the seeded book-corpus rematch. -->\n\nHere is the result we have to explain on the same 14,860-character held-out tail.\nIn one exactly matched seed, positional encoding improves the Transformer's loss\nfrom 2.3405 to 1.9190. Yet Chapter 10's compact LSTM remains better at 1.8881. The new architecture\nhas learned, and position matters in this run—but at this scale, the LSTM still\nwins.\n\n<!-- /NOVEL -->\n\n## Let the sequence query itself\n\nSuppose the sentence contains the words *bank*, *river*, and *boats*. A useful\nrepresentation of *bank* should route information from *river* and *boats*, while\nanother occurrence—now near *loan* and *interest*—should route different information.\nChapter 13 built exactly this kind of content-dependent routing. Self-attention\nchanges only the source of the three inputs.\n\nThe lecture's three questions still fit: a query asks “what am I looking for?”, a\nkey advertises “what do I offer?”, and a value carries “what information do I\ncontain?”\n\nLet a batch of token representations be\n\n$$\nX \\in \\mathbb{R}^{B \\times n \\times d},\n$$\n\nwhere $B$ is batch size, $n$ is sequence length, and $d$ is model width. Learned\nprojections produce\n\n$$\nQ=XW_Q,\\qquad K=XW_K,\\qquad V=XW_V,\n$$\n\nwith $W_Q,W_K,W_V\\in\\mathbb{R}^{d\\times d}$. Scaled dot-product attention is\n\n$$\n\\operatorname{Attention}(Q,K,V)\n=\n\\operatorname{softmax}\\left(\\frac{QK^\\top}{\\sqrt d}\\right)V.\n$$\n\nFor one sequence, $QK^\\top$ has shape $n\\times n$. Row $i$ contains the scores from\nquery position $i$ to every key position $j$. The row-wise softmax makes each row a\ndistribution, and multiplying by $V$ returns one weighted sum for each query:\n\n$$\n(n,d)(d,n)\\to(n,n),\\qquad (n,n)(n,d)\\to(n,d).\n$$\n\nChapter 10 named time as the book's third sharing axis. An RNN shares one transition\nrule across time. Self-attention keeps that stationarity and extends the shared rule\nacross every ordered pair of positions. The weights in a particular attention row\nstill depend on the content; what is shared is the machinery that produces them.\n\nAll query positions can be evaluated together during training because none waits\nfor a hidden state from the preceding position. That is a structural statement—not\na timing result. Dense self-attention still forms $n^2$ pairwise scores, and\nautoregressive generation still emits one new token at a time.\n\n### The position debt\n\nBare self-attention knows content but not slot number. A precise proof is more\nuseful than the slogan.\n\nLet $P$ be an $n\\times n$ permutation matrix, so $PX$ reorders the tokens. Then\n\n$$\nQ'=PQ,\\quad K'=PK,\\quad V'=PV\n$$\n\nand therefore\n\n$$\nQ'K'^\\top=P(QK^\\top)P^\\top.\n$$\n\nWrite $S=QK^\\top/\\sqrt d$; then $S'=PSP^\\top$. Row-wise softmax respects the\nsame simultaneous row-and-column permutation:\n\n$$\n\\operatorname{softmax}(PSP^\\top)\n=P\\operatorname{softmax}(S)P^\\top.\n$$\n\nPutting the pieces together gives\n\n$$\n\\operatorname{SA}(PX)\n=P\\operatorname{SA}(X).\n$$\n\nSelf-attention is *permutation equivariant*: permute the inputs and the outputs\npermute in the same way. It is not permutation invariant—the token outputs do not\nall become identical. But without another signal, the operator has no basis for\ndistinguishing “first” from “fifth.” A pooled sequence summary can consequently\nbecome invariant to order.\n\n@sec-08-cnn planted this debt when convolution received locality “for free.” A\nconvolution knows which values are neighbors because its kernel is tied to nearby\noffsets. Global attention abandons that built-in geometry—so we must pay to put\nposition back in.\n\n<!-- NOVEL: needs sign-off - seeded permutation/position audits and figures. -->\n\n::: {#cell-fig-permutation-debt .cell fig-height='3.4' fig-width='10' execution_count=1}\n``` {.python .cell-code}\nimport math\nimport numpy as np\nimport matplotlib.pyplot as plt\n\ndef numpy_attention(x: np.ndarray) -> np.ndarray:\n    scores = x @ x.T / math.sqrt(x.shape[-1])\n    scores = scores - scores.max(axis=-1, keepdims=True)\n    weights = np.exp(scores)\n    weights = weights / weights.sum(axis=-1, keepdims=True)\n    return weights @ x\n\ndef numpy_positions(length: int, width: int) -> np.ndarray:\n    position = np.arange(length)[:, None]\n    frequency = np.exp(\n        np.arange(0, width, 2) * (-math.log(10_000.0) / width)\n    )\n    pe = np.zeros((length, width))\n    pe[:, 0::2] = np.sin(position * frequency)\n    pe[:, 1::2] = np.cos(position * frequency)\n    return pe\n\nrng = np.random.default_rng(6050)\nx = rng.normal(size=(5, 8))\npermutation = np.array([2, 4, 0, 1, 3])\nbare_error = np.abs(\n    numpy_attention(x[permutation]) - numpy_attention(x)[permutation]\n).max()\n\npe = numpy_positions(5, 8)\nwith_position = numpy_attention(x + pe)\nfixed_slot_change = np.abs(\n    numpy_attention(x[permutation] + pe) - with_position[permutation]\n).max()\n\nfig, axes = plt.subplots(1, 2)\ntoken_ids = np.arange(5)\ntokens = np.array([\"bank\", \"by\", \"the\", \"river\", \".\"])\naxes[0].imshow(\n    np.stack([token_ids, token_ids[permutation]]),\n    cmap=\"tab10\", aspect=\"auto\", vmin=0, vmax=9,\n)\nfor row, order in enumerate([token_ids, token_ids[permutation]]):\n    for column, token_id in enumerate(order):\n        axes[0].text(column, row, tokens[token_id], ha=\"center\", va=\"center\")\naxes[0].set_yticks([0, 1], [\"$X$\", \"$PX$\"])\naxes[0].set_xticks(range(5), [f\"slot {i}\" for i in range(5)])\naxes[0].set_title(\"content moves with the permutation\")\n\naxes[1].bar(\n    [\"bare equivariance\\nerror\", \"+ fixed position\\ndifference\"],\n    [bare_error, fixed_slot_change],\n    color=[\"#6b7280\", \"#d37b29\"],\n)\naxes[1].set_yscale(\"log\")\naxes[1].set_ylabel(\"maximum rematched difference\")\naxes[1].set_title(\"position breaks the rematch\")\nplt.tight_layout()\nplt.show()\n\nprint(f\"bare permutation-equivariance error: {bare_error:.2e}\")\nprint(f\"fixed-slot difference after adding position: {fixed_slot_change:.3f}\")\n```\n\n::: {.cell-output .cell-output-display}\n![The same content is permuted across slots (left). The audit (right) shows bare self-attention rematches after the same output permutation, while fixed positional signals break that rematch.](14-self-attention-transformer_files/figure-html/fig-permutation-debt-output-1.png){#fig-permutation-debt width=662 height=469 fig-alt='Two-panel permutation audit. The left panel moves five colored word tiles from the sequence \\'bank by the river\\' into a new slot order. The right log-scale bars show a rematched bare-attention difference near machine precision and an order-one difference after fixed position vectors are added.'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nbare permutation-equivariance error: 2.22e-16\nfixed-slot difference after adding position: 1.581\n```\n:::\n:::\n\n\nThe first error is numerical roundoff, about $2.2\\times10^{-16}$. Adding a fixed\nsignal to each slot changes the rematched outputs by about 1.581 in this example.\nPosition has not been inferred from content; it has been supplied.\n\n## Position as a bank of clocks\n\nThe simplest additive code repeats $i/(n-1)$ in every coordinate. It supplies\norder, but every position vector lies on the same ray and differs only in\nmagnitude; attention receives no multidirectional geometry. A binary code supplies\nmore coordinates, yet adjacent integers can flip many bits and have poor locality.\nThese are not impossible designs—they are weak inductive biases for a model that\nmust reason about shifts and distances.\n\nSinusoidal encoding gives every position a bank of clocks. For even model width\n$d$, define\n\n$$\n\\begin{aligned}\n\\operatorname{PE}(i,2j)\n&=\\sin\\left(i\\,10000^{-2j/d}\\right),\\\\\n\\operatorname{PE}(i,2j+1)\n&=\\cos\\left(i\\,10000^{-2j/d}\\right).\n\\end{aligned}\n$$\n\nSmall $j$ gives a fast clock; large $j$ gives a slow one. Every sine coordinate is\npaired with a cosine at the same frequency. The model receives\n\n$$\nZ_i=\\sqrt d\\,E_i+\\operatorname{PE}(i),\n$$\n\nwhere $E_i$ is the token embedding. Scaling the embedding keeps its initial\nmagnitude commensurate with the position vector.\n\nWhy pair sine and cosine? For frequency $\\omega$, advancing by offset $\\delta$ is a\nrotation—an algebraic answer to a geometric question:\n\n$$\n\\begin{bmatrix}\n\\sin((i+\\delta)\\omega)\\\\\n\\cos((i+\\delta)\\omega)\n\\end{bmatrix}\n=\n\\begin{bmatrix}\n\\cos(\\delta\\omega)&\\sin(\\delta\\omega)\\\\\n-\\sin(\\delta\\omega)&\\cos(\\delta\\omega)\n\\end{bmatrix}\n\\begin{bmatrix}\n\\sin(i\\omega)\\\\\n\\cos(i\\omega)\n\\end{bmatrix}.\n$$\n\nThe rotation depends on the offset, not the absolute position. This gives learned\nlinear maps a convenient raw material for representing relative shifts. It is a\nproperty of the positional pair itself—not a guarantee that arbitrary learned\n$W_Q$ and $W_K$ will preserve or use it.\n\n::: {#cell-fig-position-build .cell fig-height='5' fig-width='10' execution_count=2}\n``` {.python .cell-code}\npe = numpy_positions(100, 32)\n\ndelta = 7\nj = 5\nomega = 10_000 ** (-2 * j / 32)\nrotation = np.array([\n    [np.cos(delta * omega), np.sin(delta * omega)],\n    [-np.sin(delta * omega), np.cos(delta * omega)],\n])\npair_i = pe[13, 2 * j : 2 * j + 2]\npair_shifted = pe[13 + delta, 2 * j : 2 * j + 2]\nrotation_error = np.abs(rotation @ pair_i - pair_shifted).max()\nnorm_error = np.abs(np.linalg.norm(pe, axis=1) - 4.0).max()\n\nfig, axes = plt.subplots(\n    2, 2, figsize=(10, 5), gridspec_kw={\"height_ratios\": [1, 2]}\n)\naxes[0, 0].plot(pe[:, 0], label=\"sin\")\naxes[0, 0].plot(pe[:, 1], label=\"cos\")\naxes[0, 0].set_title(\"fast clock: coordinates 0–1\")\naxes[0, 0].legend(frameon=False, ncol=2)\naxes[0, 1].plot(pe[:, 20], label=\"sin\")\naxes[0, 1].plot(pe[:, 21], label=\"cos\")\naxes[0, 1].set_title(\"slow clock: coordinates 20–21\")\naxes[0, 1].legend(frameon=False, ncol=2)\n\nheat = axes[1, 0].imshow(pe.T, aspect=\"auto\", cmap=\"coolwarm\", vmin=-1, vmax=1)\naxes[1, 0].set_xlabel(\"position\")\naxes[1, 0].set_ylabel(\"coordinate\")\naxes[1, 0].set_title(\"the complete position code\")\nfig.colorbar(heat, ax=axes[1, 0], fraction=0.05)\n\nfrom matplotlib.patches import FancyArrowPatch\n\nangles = np.arange(0, 2 * np.pi, 0.01)\naxes[1, 1].plot(np.sin(angles), np.cos(angles), color=\"0.8\")\naxes[1, 1].scatter(*pair_i, label=\"position 13\")\naxes[1, 1].scatter(*pair_shifted, label=f\"position {13 + delta}\")\naxes[1, 1].plot([0, pair_i[0]], [0, pair_i[1]], color=\"0.4\")\naxes[1, 1].plot([0, pair_shifted[0]], [0, pair_shifted[1]], color=\"0.4\")\naxes[1, 1].add_patch(\n    FancyArrowPatch(\n        pair_i,\n        pair_shifted,\n        connectionstyle=\"arc3,rad=0.25\",\n        arrowstyle=\"->\",\n        mutation_scale=12,\n        color=\"black\",\n    )\n)\naxes[1, 1].axis(\"equal\")\naxes[1, 1].set_title(f\"offset {delta} is a rotation\")\naxes[1, 1].legend(frameon=False)\nplt.tight_layout()\nplt.show()\n\nprint(f\"rotation identity maximum error: {rotation_error:.2e}\")\nprint(f\"constant position-vector norm maximum error: {norm_error:.2e}\")\n```\n\n::: {.cell-output .cell-output-display}\n![Sinusoidal position is a bank of clocks. Fast coordinates track local offsets; slow coordinates vary across longer ranges. Each sine/cosine pair acts like a clock, and a fixed offset rotates that pair by a start-independent angle.](14-self-attention-transformer_files/figure-html/fig-position-build-output-1.png){#fig-position-build width=951 height=471 fig-alt='Four-panel view of sinusoidal position. Fast sine and cosine coordinates oscillate repeatedly across 100 positions; slow coordinates change only slightly. A heatmap stacks 32 coordinates from fast bands at top to nearly constant slow bands at bottom. A unit-circle diagram shows positions 13 and 20 separated by the same rotation associated with offset seven.'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nrotation identity maximum error: 1.11e-16\nconstant position-vector norm maximum error: 0.00e+00\n```\n:::\n:::\n\n\nFor $d=32$, each position vector has norm $\\sqrt{d/2}=4$ because every\n$\\sin^2+\\cos^2$ pair contributes one. Adding this vector does *not* preserve the\nnorm of the combined token representation—the embedding and position vector can\nreinforce or cancel one another. Layer normalization will soon manage scale at the\nblock level.\n\n<!-- /NOVEL -->\n\n## One routing operation, many heads\n\nA single attention distribution must make one compromise about what to retrieve.\nMulti-head attention lets several smaller routing systems—separate views of the\nsame residual stream—operate in parallel.\nChoose a number of heads $h$ that divides $d$, and let $d_h=d/h$. For each head\n$r$,\n\n$$\nQ_r=XW_Q^{(r)},\\quad\nK_r=XW_K^{(r)},\\quad\nV_r=XW_V^{(r)},\n$$\n\nwhere\n$W_Q^{(r)},W_K^{(r)},W_V^{(r)}\\in\\mathbb{R}^{d\\times d_h}$. The head output is\n\n$$\nH_r=\n\\operatorname{softmax}\\left(\n\\frac{Q_rK_r^\\top}{\\sqrt{d_h}}+M\n\\right)V_r.\n$$\n\nHere $M$ is the visibility mask defined next; $M=0$ for unmasked attention.\n\nThe complete operation concatenates the heads and mixes them:\n\n$$\n\\operatorname{MHA}(X)\n=\\operatorname{Concat}(H_1,\\ldots,H_h)W_O,\n\\qquad W_O\\in\\mathbb{R}^{d\\times d}.\n$$\n\nThe shape ledger is the safest implementation guide:\n\n$$\n(B,n,d)\n\\to(B,h,n,d_h)\n\\to(B,h,n,n)\n\\to(B,h,n,d_h)\n\\to(B,n,d).\n$$\n\nScaling uses $\\sqrt{d_h}$, not $\\sqrt d$, because a head's dot product sums $d_h$\nterms. With fixed $d$, splitting into heads does not multiply the leading projection\ncount: $W_Q,W_K,W_V,W_O$ together contribute about $4d^2$ weights regardless of\n$h$. Heads divide the representational subspace—they do not each receive a fresh\nwidth-$d$ model.\n\n### The mask is part of the model\n\n@sec-11-encoder-decoder called masking the rule that tells a model *which positions it may not\nlook at*. Here that rule is causal: position $i$ may use tokens at positions\n$j\\le i$ but must not inspect future tokens $j>i$. Rows are queries and columns\nare keys, so the forbidden region is the strict upper triangle. We add\n\n$$\nM_{ij}=\n\\begin{cases}\n0,&j\\le i,\\\\\n-\\infty,&j>i\n\\end{cases}\n$$\n\n*before* softmax. Replacing forbidden probabilities with zero afterward would\nleave the remaining row unnormalized. Masking every key in a row is invalid—softmax\nwould receive only negative infinity. Here the diagonal remains visible:\nthe representation at a character may use that character while predicting the\nnext one.\n\n<!-- NOVEL: needs sign-off - independent causal multi-head implementation and mask audit. -->\n\n::: {#causal-multihead-implementation .cell execution_count=3}\n``` {.python .cell-code code-summary=\"Code: implement causal multi-head attention and audit its mask\"}\nimport torch\nfrom torch import nn\n\nclass CausalMultiHeadAttention(nn.Module):\n    def __init__(self, width: int, heads: int) -> None:\n        super().__init__()\n        if width % heads != 0:\n            raise ValueError(\"width must be divisible by heads\")\n        self.heads = heads\n        self.head_width = width // heads\n        self.qkv = nn.Linear(width, 3 * width)\n        self.project = nn.Linear(width, width)\n        nn.init.xavier_uniform_(self.qkv.weight)\n        nn.init.zeros_(self.qkv.bias)\n\n    def forward(self, x: torch.Tensor, return_weights: bool = False):\n        batch, length, width = x.shape\n        qkv = self.qkv(x)\n        qkv = qkv.reshape(\n            batch, length, 3, self.heads, self.head_width\n        ).permute(2, 0, 3, 1, 4)\n        q, k, v = qkv.unbind(dim=0)\n        scores = q @ k.transpose(-2, -1) / math.sqrt(self.head_width)\n        forbidden = torch.triu(\n            torch.ones(length, length, dtype=torch.bool, device=x.device),\n            diagonal=1,\n        )\n        scores = scores.masked_fill(forbidden, float(\"-inf\"))\n        weights = torch.softmax(scores, dim=-1)\n        routed = weights @ v\n        routed = routed.transpose(1, 2).reshape(batch, length, width)\n        output = self.project(routed)\n        if return_weights:\n            return output, weights\n        return output\n\ntorch.manual_seed(6050)\ndemo_attention = CausalMultiHeadAttention(width=32, heads=4)\ndemo_x = torch.randn(1, 12, 32)\n_, demo_weights = demo_attention(demo_x, return_weights=True)\n\nfuture = torch.triu(torch.ones(12, 12, dtype=torch.bool), diagonal=1)\nassert demo_weights[0, :, future].max().item() == 0.0\nassert torch.allclose(\n    demo_weights.sum(dim=-1),\n    torch.ones_like(demo_weights.sum(dim=-1)),\n    atol=1e-6,\n)\n```\n:::\n\n\n::: {#cell-fig-causal-multihead .cell fig-height='7' fig-width='10' execution_count=4}\n\n::: {.cell-output .cell-output-display}\n![Multi-head attention splits, routes in parallel, concatenates, and projects (top). In the untrained causal heads below, every query row sums to one and every future key has exactly zero weight.](14-self-attention-transformer_files/figure-html/fig-causal-multihead-output-1.png){#fig-causal-multihead width=969 height=649 fig-alt='Top flow diagram sends X through Q-K-V splitting, four parallel attention routes, concatenation, and output projection. Below, four 12-by-12 attention heatmaps have different weights only on and below the diagonal; every upper-triangular future position is dark.'}\n:::\n:::\n\n\n::: {#causal-multihead-audit-output .cell execution_count=5}\n``` {.python .cell-code code-summary=\"Code: report the causal-mask and normalization audit\"}\nprint(\"maximum forbidden attention:\", demo_weights[0, :, future].max().item())\nprint(\n    \"maximum row-sum error:\",\n    (demo_weights.sum(dim=-1) - 1).abs().max().item(),\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmaximum forbidden attention: 0.0\nmaximum row-sum error: 1.1920928955078125e-07\n```\n:::\n:::\n\n\nThe assertions are part of the derivation. A visually plausible triangle can still\nbe transposed, shifted by one, or applied after softmax. Executable shape and\nnormalization checks catch those errors—before training can disguise them.\n\n<!-- /NOVEL -->\n\nThe mask changes visibility, not dense computation. The implementation still\nforms all $n^2$ scores and stores $Bhn^2$ attention weights, alongside roughly\n$Bnd^2$ projection work and $Bndd_{ff}$ work in the FFN. Self-attention shortens\nthe graph path between distant\ntokens to one routing step—but “one step away” is not “constant runtime.”\n@sec-a3-precision-performance returns to this $n^2$ ledger through Roofline analysis\nand FlashAttention's I/O-aware schedule.\n\n## Build a Transformer block\n\nAttention routes information between token positions. A Transformer block needs\ntwo more ingredients—a stable path through depth and a nonlinear computation at\neach position.\n\n### The residual stream\n\n@sec-09-modern-cnns-transfer introduced the residual stream with one durable sentence: every block\nreads the stream and writes a correction back. If a sublayer computes $F(x)$, the\nresidual update is\n\n$$\nx\\leftarrow x+F(x).\n$$\n\nThe identity branch provides a direct route for representations and gradients\nwhile the learned branch proposes a correction. It makes deep optimization more\ntractable—it does not guarantee that gradients can never vanish or explode.\n\nLayer normalization controls each token's feature scale. For one token vector\n$x\\in\\mathbb{R}^{d}$,\n\n$$\n\\mu=\\frac1d\\sum_{k=1}^{d}x_k,\\qquad\n\\sigma^2=\\frac1d\\sum_{k=1}^{d}(x_k-\\mu)^2,\n$$\n\n$$\n\\operatorname{LN}(x)_k\n=\\gamma_k\\frac{x_k-\\mu}{\\sqrt{\\sigma^2+\\epsilon}}+\\beta_k,\n\\qquad \\gamma,\\beta\\in\\mathbb{R}^d.\n$$\n\nThis is Chapter 9's normalization equation applied along a different axis—the same\nequation, different axis. Chapter 9's BatchNorm2d used batch and spatial axes for\neach channel. LayerNorm flips to the feature axis of each token: it computes\nstatistics across the features within one token, without aggregating statistics\nacross other tokens or examples. Its calculation is the same at training and\nevaluation time. Before the learned $\\gamma$ and $\\beta$, the vector is\napproximately zero mean and unit variance. After applying them, that claim need\nnot remain true.\n\n::: {#layernorm-axis-audit .cell execution_count=6}\n``` {.python .cell-code code-summary=\"Code: verify LayerNorm centers and scales each token independently\"}\naudit = torch.tensor([\n    [[1.0, 3.0, 5.0, 7.0], [40.0, 50.0, 60.0, 70.0]],\n    [[-3.0, 1.0, 5.0, 9.0], [2.0, 2.5, 3.0, 3.5]],\n])\nnormalized = nn.functional.layer_norm(audit, (4,))\ntoken_means = normalized.mean(dim=-1)\ntoken_vars = normalized.var(dim=-1, unbiased=False)\nassert token_means.abs().max().item() < 1e-6\nassert (token_vars - 1).abs().max().item() < 1e-4\n```\n:::\n\n\n::: {#cell-fig-transformer-block .cell fig-height='4.5' fig-width='9' execution_count=7}\n\n::: {.cell-output .cell-output-display}\n![A pre-LayerNorm Transformer block (left): each sublayer reads a normalized view of the residual stream and writes a correction back. LayerNorm centers and scales every token across its own feature axis (right).](14-self-attention-transformer_files/figure-html/fig-transformer-block-output-1.png){#fig-transformer-block width=854 height=422 fig-alt='Two-panel schematic. On the left, a vertical residual stream feeds LayerNorm then causal multi-head attention and adds its result back, followed by LayerNorm then an FFN and a second addition. On the right, four token feature profiles coincide after each token is independently centered and scaled, crossing zero between the middle features.'}\n:::\n:::\n\n\n::: {#layernorm-axis-audit-output .cell execution_count=8}\n``` {.python .cell-code code-summary=\"Code: report the per-token LayerNorm audit\"}\nprint(\"maximum absolute token mean:\", token_means.abs().max().item())\nprint(\"maximum token variance error:\", (token_vars - 1).abs().max().item())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmaximum absolute token mean: 0.0\nmaximum token variance error: 3.2067298889160156e-05\n```\n:::\n:::\n\n\nThe original Transformer normalized *after* each residual addition:\n\n$$\nx\\leftarrow\\operatorname{LN}(x+\\operatorname{MHA}(x)),\\qquad\nx\\leftarrow\\operatorname{LN}(x+\\operatorname{FFN}(x)).\n$$\n\nOur small experiment uses the now-common pre-LayerNorm arrangement:\n\n$$\n\\begin{aligned}\nx&\\leftarrow x+\\operatorname{MHA}(\\operatorname{LN}(x)),\\\\\nx&\\leftarrow x+\\operatorname{FFN}(\\operatorname{LN}(x)).\n\\end{aligned}\n$$\n\nPre-LayerNorm leaves an unobstructed identity route along the residual stream and\noften improves optimization at initialization. This is an implementation choice,\nnot a universal theorem that post-LayerNorm fails or that pre-LayerNorm eliminates\nevery need for careful optimization.\n\n### The position-wise feed-forward network\n\nAfter tokens communicate through attention, the same two-layer network processes\neach position independently:\n\n$$\n\\operatorname{FFN}(z)\n=W_2\\operatorname{ReLU}(W_1z+b_1)+b_2.\n$$\n\nHere $W_1\\in\\mathbb{R}^{d_{ff}\\times d}$,\n$b_1\\in\\mathbb{R}^{d_{ff}}$, $W_2\\in\\mathbb{R}^{d\\times d_{ff}}$, and\n$b_2\\in\\mathbb{R}^{d}$.\n\nIf $w_{1j}^\\top$ is row $j$ of $W_1$ and $v_j$ is column $j$ of $W_2$, the same\noperation can be written\n\n$$\n\\operatorname{FFN}(z)\n=\\sum_j [w_{1j}^\\top z+b_{1j}]_+\\,v_j+b_2.\n$$\n\nThis form motivates an associative-memory lens. Each first-layer row tests whether\nthe current representation lies in a learned half-space; its positive activation\ncontrols how much of the corresponding output vector is written. Empirically,\nTransformer FFNs can behave like key-value memories. The analogy has limits—the\nselectors are half-spaces rather than point anchors, the gates do not sum to one,\nand the operation is not literally kernel regression or a normalized lookup.\n\nThe complete block therefore alternates two kinds of computation:\n\n1. causal multi-head attention moves information *between positions*; and\n2. the FFN transforms information *within each position*.\n\nResidual additions keep both results in one shared stream—a common workspace that\nsurvives the full stack.\n\n## From the original Transformer to this experiment\n\nThe 2017 Transformer was an encoder–decoder system for translation. Its encoder\nstack uses unmasked self-attention to build a representation of the source\nsentence. Its decoder stack uses causal self-attention over the partial target,\nthen cross-attention whose queries come from the decoder while keys and values\ncome from the encoder. In compact form:\n\n$$\n\\begin{array}{lll}\n\\text{encoder:}&X_s\\to\\text{self-attention}\\to\\text{FFN},\\\\\n\\text{decoder:}&X_t\\to\\text{causal self-attention}\n\\to\\text{cross-attention to encoder}\\to\\text{FFN}.\n\\end{array}\n$$\n\nThe book-corpus task predicts the next character from earlier characters. It has no\nseparate source sentence, so the encoder and cross-attention are unnecessary. What\nremains—a **decoder-only causal Transformer**—has token plus position embeddings,\ntwo pre-LayerNorm blocks, a final LayerNorm, and a linear map to vocabulary logits.\nThe logits go directly to cross-entropy. Softmax belongs inside attention and,\nlater, inside sampling—not between the output layer and the loss.\n\n<!-- NOVEL: needs sign-off - exact-schedule book-corpus rematch, positional ablation,\n     learned-map audit, and deterministic samples. -->\n\n## The book reads itself, again\n\nA fair rematch begins by preserving what can be preserved. Chapter 10 trained on\na committed snapshot of Chapters 1–9 with executable code cells and HTML comments\nremoved: 148,594 characters,\nvocabulary 104, a contiguous 90/10 split, 100-character windows, batch size 64, and\n2,501 updates with Adam at learning rate 0.002 and gradient clipping at norm 1. The\nsnapshot keeps later copyedits from moving the benchmark. The held-out metric resets\nstate at each fixed window.\n\nThe two architectures cannot be made identical—one has recurrent gates and the\nother has attention blocks—but their opportunity to see training targets can be.\nThe code below reconstructs Chapter 10's exact random-window schedule, then gives\nboth Transformer variants the same initial weights and all 16,006,400 target\ncharacters in the same order. The held-out tail has been inspected repeatedly\nacross chapters, so treat it as a stable validation benchmark—not a newly sealed\ntest set.\n\n::: {#transformer-data-model .cell execution_count=9}\n``` {.python .cell-code code-summary=\"Code: exact Chapter 10 corpus and schedule, plus a custom tiny Transformer\"}\nimport hashlib\nfrom pathlib import Path\nimport torch.nn.functional as F\n\ntorch.set_num_threads(4)\ntorch.use_deterministic_algorithms(True)\n\nSEED = 6050\nCONTEXT = 100\nBATCH = 64\nUPDATES = 2501\nWIDTH = 84\nHEADS = 4\nFF_WIDTH = 168\nBLOCKS = 2\n\ncorpus_path = Path(\"../../data/book-corpus-ch1-9.txt\")\ntext = corpus_path.read_text(encoding=\"utf-8\")\nassert len(text) == 148_594\nassert hashlib.sha256(text.encode(\"utf-8\")).hexdigest() == (\n    \"b0fc23a513e37e7bcd78da04a03877345f6ebc850b91dbae260656d9924fb299\"\n)\n\nchars = sorted(set(text))\nstoi = {char: index for index, char in enumerate(chars)}\ndata = torch.tensor([stoi[char] for char in text])\nsplit = int(0.9 * len(data))\ntrain_data, valid_data = data[:split], data[split:]\n\ndef sinusoidal_positions(length: int, width: int) -> torch.Tensor:\n    position = torch.arange(length, dtype=torch.float32).unsqueeze(1)\n    frequency = torch.exp(\n        torch.arange(0, width, 2, dtype=torch.float32)\n        * (-math.log(10_000.0) / width)\n    )\n    table = torch.zeros(length, width)\n    table[:, 0::2] = torch.sin(position * frequency)\n    table[:, 1::2] = torch.cos(position * frequency)\n    return table\n\nclass TransformerBlock(nn.Module):\n    def __init__(self) -> None:\n        super().__init__()\n        self.norm1 = nn.LayerNorm(WIDTH)\n        self.attention = CausalMultiHeadAttention(WIDTH, HEADS)\n        self.norm2 = nn.LayerNorm(WIDTH)\n        self.ff = nn.Sequential(\n            nn.Linear(WIDTH, FF_WIDTH),\n            nn.ReLU(),\n            nn.Linear(FF_WIDTH, WIDTH),\n        )\n\n    def forward(self, x: torch.Tensor, return_weights: bool = False):\n        if return_weights:\n            attended, weights = self.attention(self.norm1(x), True)\n            x = x + attended\n            return x + self.ff(self.norm2(x)), weights\n        x = x + self.attention(self.norm1(x))\n        return x + self.ff(self.norm2(x))\n\nclass TinyTransformerLM(nn.Module):\n    def __init__(self, vocab: int, positions: bool) -> None:\n        super().__init__()\n        self.positions = positions\n        self.token_embedding = nn.Embedding(vocab, WIDTH)\n        nn.init.normal_(\n            self.token_embedding.weight,\n            mean=0.0,\n            std=1 / math.sqrt(WIDTH),\n        )\n        self.blocks = nn.ModuleList(\n            [TransformerBlock() for _ in range(BLOCKS)]\n        )\n        self.final_norm = nn.LayerNorm(WIDTH)\n        self.output = nn.Linear(WIDTH, vocab)\n        self.register_buffer(\n            \"position_table\",\n            sinusoidal_positions(CONTEXT, WIDTH),\n            persistent=False,\n        )\n\n    def forward(self, tokens: torch.Tensor, return_weights: bool = False):\n        length = tokens.shape[1]\n        x = self.token_embedding(tokens) * math.sqrt(WIDTH)\n        if self.positions:\n            x = x + self.position_table[:length]\n        maps = []\n        for block in self.blocks:\n            if return_weights:\n                x, weights = block(x, True)\n                maps.append(weights)\n            else:\n                x = block(x)\n        logits = self.output(self.final_norm(x))\n        return (logits, maps) if return_weights else logits\n\nclass HistoricalCharLSTM(nn.Module):\n    def __init__(self, vocab: int, hidden: int = 128) -> None:\n        super().__init__()\n        self.vocab = vocab\n        self.lstm = nn.LSTM(vocab, hidden, batch_first=True)\n        self.out = nn.Linear(hidden, vocab)\n\ndef state_digest(state: dict[str, torch.Tensor]) -> str:\n    digest = hashlib.sha256()\n    for name, value in state.items():\n        digest.update(name.encode())\n        digest.update(value.detach().cpu().numpy().tobytes())\n    return digest.hexdigest()\n\n# Reconstruct the random-number state immediately after Chapter 10 created\n# its LSTM, then draw that chapter's complete minibatch-start schedule.\ntorch.manual_seed(SEED)\n_ = HistoricalCharLSTM(len(chars))\nschedule_generator = torch.Generator()\nschedule_generator.set_state(torch.random.get_rng_state())\nstarts = torch.randint(\n    0,\n    len(train_data) - CONTEXT - 1,\n    (UPDATES, BATCH),\n    generator=schedule_generator,\n)\n\n# The two Transformer variants begin with exactly the same tensors.\ntorch.manual_seed(SEED)\nbase_model = TinyTransformerLM(len(chars), positions=True)\ninitial_state = {\n    name: value.clone() for name, value in base_model.state_dict().items()\n}\ninitial_hash = state_digest(initial_state)\nschedule_hash = hashlib.sha256(starts.numpy().tobytes()).hexdigest()\n\nprint(f\"corpus: 9 chapters, {len(text):,} characters, vocab {len(chars)}\")\nprint(\n    f\"deterministic split: {len(train_data):,} train / \"\n    f\"{len(valid_data):,} held out\"\n)\nprint(\n    f\"Transformer parameters: \"\n    f\"{sum(parameter.numel() for parameter in base_model.parameters()):,}\"\n)\nprint(f\"first eight window starts: {starts[0, :8].tolist()}\")\nprint(f\"initial tensors: {initial_hash[:12]}…\")\nprint(f\"window schedule: {schedule_hash[:12]}…\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncorpus: 9 chapters, 148,594 characters, vocab 104\ndeterministic split: 133,734 train / 14,860 held out\nTransformer parameters: 132,488\nfirst eight window starts: [24368, 94128, 60074, 121547, 118001, 4396, 17011, 8495]\ninitial tensors: 4d2f7f434cb5…\nwindow schedule: e470a091bd50…\n```\n:::\n:::\n\n\nThe model has 132,488 trainable parameters—736 fewer than Chapter 10's 133,224.\nThat difference is only 0.55%—close enough to remove model size as an easy\nexplanation. The model width is 84, split into four 21-dimensional heads; each of\nthe two FFNs expands to 168 features. Token embeddings are initialized with\ncoordinate standard deviation $1/\\sqrt d$ before the displayed $\\sqrt d$ scaling,\nso their coordinates and the sinusoidal coordinates begin on comparable scales.\n`ModuleList` registers the two repeated blocks with the model. The nonpersistent\nposition buffer moves with the model but is neither optimized nor included in the\nstate-dictionary fingerprint; its contents follow deterministically from the\ndisplayed formula. There is no dropout, so resetting the trainable/state-dictionary\ntensors and window schedule makes the positional ablation exact and repeatable.\n\n::: {.callout-tip}\n## One seed call was not enough\n\nCalling the same random seed before both training runs would not, by itself, prove\nthat they saw the same windows. Model construction consumes random numbers, and\ndifferent construction paths can silently shift every later draw. The experiment\nprecomputes the full start-index tensor with an explicit generator and copies one\nsaved initialization into both models. It also prints fingerprints for both\nartifacts.\n:::\n\n::: {#transformer-training-function .cell execution_count=10}\n``` {.python .cell-code code-summary=\"Code: one matched training and evaluation protocol\"}\ndef train_transformer(\n    positions: bool,\n) -> tuple[nn.Module, list[tuple[int, float]]]:\n    net = TinyTransformerLM(len(chars), positions=positions)\n    net.load_state_dict(initial_state, strict=True)\n    assert state_digest(net.state_dict()) == initial_hash\n    optimizer = torch.optim.Adam(net.parameters(), lr=2e-3)\n    curve = []\n    for step, batch_starts in enumerate(starts):\n        xb = torch.stack([\n            train_data[j : j + CONTEXT] for j in batch_starts\n        ])\n        yb = torch.stack([\n            train_data[j + 1 : j + CONTEXT + 1] for j in batch_starts\n        ])\n        logits = net(xb)\n        loss = F.cross_entropy(\n            logits.reshape(-1, len(chars)), yb.reshape(-1)\n        )\n        optimizer.zero_grad()\n        loss.backward()\n        nn.utils.clip_grad_norm_(net.parameters(), 1.0)\n        optimizer.step()\n        if step % 250 == 0:\n            curve.append((step, loss.item()))\n            print(f\"step {step:4d}   loss {loss.item():.4f}\")\n    return net, curve\n\n@torch.no_grad()\ndef fixed_window_loss(\n    net: nn.Module,\n    sequence: torch.Tensor,\n    window: int = CONTEXT,\n) -> float:\n    net.eval()\n    total_loss, n_tokens = 0.0, 0\n    for start in range(0, len(sequence) - 1, window):\n        stop = min(start + window, len(sequence) - 1)\n        xb = sequence[start:stop].unsqueeze(0)\n        yb = sequence[start + 1 : stop + 1]\n        logits = net(xb)\n        total_loss += F.cross_entropy(\n            logits.reshape(-1, len(chars)),\n            yb,\n            reduction=\"sum\",\n        ).item()\n        n_tokens += yb.numel()\n    return total_loss / n_tokens\n\n@torch.no_grad()\ndef transformer_sample(\n    net: nn.Module,\n    prompt: str,\n    n: int = 300,\n    temperature: float = 0.8,\n) -> str:\n    net.eval()\n    generator = torch.Generator().manual_seed(1_406_050)\n    tokens = [stoi.get(char, 0) for char in prompt]\n    for _ in range(n):\n        context = torch.tensor(tokens[-CONTEXT:]).unsqueeze(0)\n        probabilities = F.softmax(\n            net(context)[0, -1] / temperature, dim=-1\n        )\n        next_token = torch.multinomial(\n            probabilities, 1, generator=generator\n        ).item()\n        tokens.append(next_token)\n    return \"\".join(chars[index] for index in tokens)\n```\n:::\n\n\nThe training function is defined once, then called in separate cells so each\nsubstantial run stays within the chapter's execution budget.\n\n::: {#train-transformer-positions .cell execution_count=11}\n``` {.python .cell-code code-summary=\"Code: train the positional Transformer\"}\nposition_model, position_curve = train_transformer(positions=True)\nposition_train_loss = fixed_window_loss(position_model, train_data)\nposition_valid_loss = fixed_window_loss(position_model, valid_data)\nprint(f\"fixed-window train loss: {position_train_loss:.4f}\")\nprint(f\"fixed-window held-out loss: {position_valid_loss:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nstep    0   loss 4.7550\nstep  250   loss 2.1850\nstep  500   loss 1.7159\nstep  750   loss 1.5176\nstep 1000   loss 1.3955\nstep 1250   loss 1.3444\nstep 1500   loss 1.2813\nstep 1750   loss 1.2386\nstep 2000   loss 1.1708\nstep 2250   loss 1.1525\nstep 2500   loss 1.1083\nfixed-window train loss: 1.1132\nfixed-window held-out loss: 1.9190\n```\n:::\n:::\n\n\n::: {#train-transformer-no-positions .cell execution_count=12}\n``` {.python .cell-code code-summary=\"Code: repeat with position removed and everything else fixed\"}\nno_position_model, no_position_curve = train_transformer(positions=False)\nno_position_train_loss = fixed_window_loss(no_position_model, train_data)\nno_position_valid_loss = fixed_window_loss(no_position_model, valid_data)\nprint(f\"fixed-window train loss: {no_position_train_loss:.4f}\")\nprint(f\"fixed-window held-out loss: {no_position_valid_loss:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nstep    0   loss 4.7289\nstep  250   loss 2.4955\nstep  500   loss 2.3612\nstep  750   loss 2.2436\nstep 1000   loss 2.2153\nstep 1250   loss 2.1826\nstep 1500   loss 2.0792\nstep 1750   loss 1.9876\nstep 2000   loss 1.9527\nstep 2250   loss 1.8986\nstep 2500   loss 1.8435\nfixed-window train loss: 1.8672\nfixed-window held-out loss: 2.3405\n```\n:::\n:::\n\n\n::: {#cell-fig-book-corpus-rematch .cell fig-height='4' fig-width='10' execution_count=13}\n``` {.python .cell-code}\nlstm_valid_loss = 1.888110429\n\nfig, axes = plt.subplots(1, 2, figsize=(10, 4))\nfor curve, label, color in [\n    (position_curve, \"Transformer + position\", \"#3566a8\"),\n    (no_position_curve, \"Transformer, no position\", \"#d37b29\"),\n]:\n    steps, losses = zip(*curve)\n    axes[0].plot(steps, losses, marker=\"o\", ms=3, label=label, color=color)\naxes[0].set_xlabel(\"update\")\naxes[0].set_ylabel(\"sampled training-minibatch loss\")\naxes[0].set_title(\"same windows, same initialization\")\naxes[0].legend(frameon=False)\n\nlabels = [\"Ch. 10\\nLSTM\", \"Transformer\\n+ position\", \"Transformer\\nno position\"]\nvalues = [lstm_valid_loss, position_valid_loss, no_position_valid_loss]\nbars = axes[1].bar(labels, values, color=[\"#6b7280\", \"#3566a8\", \"#d37b29\"])\naxes[1].set_ylim(1.5, 2.7)\naxes[1].set_ylabel(\"held-out loss ↓\")\naxes[1].set_title(\"fixed-window rematch\")\naxes[1].bar_label(bars, fmt=\"%.4f\", padding=3)\nplt.tight_layout()\nplt.show()\n\nimprovement = no_position_valid_loss - position_valid_loss\nrelative = improvement / no_position_valid_loss\nlstm_gap = position_valid_loss - lstm_valid_loss\nprint(\n    f\"position improvement: {improvement:.4f} loss \"\n    f\"({relative:.1%} relative)\"\n)\nprint(f\"positional Transformer minus LSTM: {lstm_gap:.4f} loss\")\n```\n\n::: {.cell-output .cell-output-display}\n![Matched training curves (left) and fixed-window held-out loss (right). Position helps in this seed, while the Chapter 10 LSTM remains the strongest small model.](14-self-attention-transformer_files/figure-html/fig-book-corpus-rematch-output-1.png){#fig-book-corpus-rematch width=951 height=374 fig-alt='Two-panel matched comparison. Training losses start together near 4.7, then the positional Transformer falls steadily to about 1.1 while the no-position model ends near 1.85. Held-out bars rank the Chapter 10 LSTM lowest at 1.8881, the positional Transformer at 1.9190, and the no-position Transformer highest at 2.3405.'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nposition improvement: 0.4214 loss (18.0% relative)\npositional Transformer minus LSTM: 0.0309 loss\n```\n:::\n:::\n\n\nThe positional model finishes at 1.1132 on a deterministic pass over the training\ntext and 1.9190 on the held-out tail. Removing position raises those values to\n1.8672 and 2.3405. Position lowers\nheld-out loss by 0.4214, or 18.0% relative to the no-position variant.\n\n::: {.callout-warning}\n## What this matched run can—and cannot—show\n\nThe causal mask already gives a position some weak structural information: row\n$i$ sees a prefix of length $i+1$, and stacked layers can propagate clues from\nthose nested prefixes. That is why the no-position model does better than a purely\norderless caricature might suggest—fixed sinusoidal encoding still produces a\nlarge improvement in this run.\n\nBut Chapter 10's LSTM remains ahead by 0.0309 held-out loss, or 1.64%. At 100\ncharacters of context and roughly 133,000 parameters, the LSTM wins this regime.\nThis comparison matches corpus, parameter scale, updates,\nminibatch order, optimizer, clipping, and evaluation. It does not match internal\narchitecture—or promise that either model has been tuned to its own optimum.\nWe did not repeat the comparison across initialization seeds, so the 0.4214 gap is\na controlled case study, not an estimate of an average effect.\n:::\n\n### What did the heads route?\n\nAn attention map records routing weights, not reasons, confidence, or a guaranteed\nexplanation of a prediction. Still, inspecting real learned maps can verify the\nmask and reveal the kinds of patterns a trained model happened to use. The next\ncell sends the prompt *The gradient* through the positional model and plots the\nsecond block's four heads.\n\n::: {#cell-fig-learned-attention .cell fig-height='6' fig-width='10' execution_count=14}\n``` {.python .cell-code}\nprompt = \"The gradient \"\nprompt_tokens = torch.tensor([[stoi[char] for char in prompt]])\nposition_model.eval()\nwith torch.no_grad():\n    _, learned_maps = position_model(prompt_tokens, return_weights=True)\nlearned = learned_maps[-1][0]\n\nfuture = torch.triu(\n    torch.ones(len(prompt), len(prompt), dtype=torch.bool), diagonal=1\n)\nassert learned[:, future].max().item() == 0.0\nassert torch.allclose(\n    learned.sum(dim=-1),\n    torch.ones_like(learned.sum(dim=-1)),\n    atol=1e-6,\n)\n\ndisplay_tokens = [\"·\" if char == \" \" else char for char in prompt]\nfig, axes = plt.subplots(2, 2, figsize=(10, 6), layout=\"constrained\")\nfor head, axis in enumerate(axes.flat):\n    image = axis.imshow(\n        learned[head].numpy(), cmap=\"viridis\", vmin=0, vmax=1\n    )\n    axis.set_title(f\"block 2, head {head + 1}\")\n    axis.set_xticks(range(len(prompt)), display_tokens)\n    axis.set_yticks(range(len(prompt)), display_tokens)\n    axis.set_xlabel(\"key\")\n    axis.set_ylabel(\"query\")\nfig.colorbar(image, ax=axes, fraction=0.025, shrink=0.8, pad=0.02)\nplt.show()\n\nprint(\"maximum future attention:\", learned[:, future].max().item())\nprint(\n    \"maximum row-sum error:\",\n    (learned.sum(dim=-1) - 1).abs().max().item(),\n)\n```\n\n::: {.cell-output .cell-output-display}\n![Learned attention weights in the second block for the prompt “The gradient ”. The maps are real routing distributions, not explanations or named head roles.](14-self-attention-transformer_files/figure-html/fig-learned-attention-output-1.png){#fig-learned-attention width=788 height=587 fig-alt='Four lower-triangular heatmaps for the second block\\'s four heads on the character prompt \\'The gradient\\' with spaces shown as dots. Each query row attends only to itself and earlier characters, but the heads distribute their bright high-weight cells differently: some follow local diagonals while others concentrate on a few earlier columns.'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nmaximum future attention: 0.0\nmaximum row-sum error: 1.1920928955078125e-07\n```\n:::\n:::\n\n\nThe maps obey the contract exactly: no future key receives weight and every row\nsums to one. The heads also differ from one another, but naming one “the previous\ncharacter head” or another “the word head” from this single prompt would outrun\nthe evidence. Attention shows where values were mixed—the rest of the network can\ntransform, cancel, or ignore what was retrieved.\n\n### Listen, but do not grade by fluency\n\nBoth Transformer variants can now generate by repeatedly truncating to the most\nrecent 100 characters, predicting a distribution for the next one, sampling, and\nfeeding the result back. Unlike Chapter 10's LSTM, this simple implementation does\nnot carry a recurrent state; it recomputes the current context on every step.\n\n<!-- NOVEL: needs sign-off - concise generation bridge requested in the course review. -->\n::: {.callout-tip}\n## Practice bridge (non-examinable): decoding is another model choice\n\nFor next-token logits $z_i$, **temperature** applies Chapter 2's softmax dial\n(@sec-02-logistic-softmax):\n\n$$\np_i(T)=\\frac{\\exp(z_i/T)}{\\sum_j\\exp(z_j/T)},\\qquad T>0.\n$$\n\nLower $T$ concentrates probability; higher $T$ flattens it. **Top-$k$ sampling**\nkeeps the $k$ largest logits, sets the rest to negative infinity, then renormalizes.\n**Nucleus (top-$p$) sampling** first sorts the model probabilities and keeps the\nsmallest prefix whose cumulative mass reaches $p$, then renormalizes. The former fixes\na candidate count; the latter lets that count adapt to the distribution's shape.\nNeither changes the trained weights, and neither guarantees a better sample.\n\nFor evaluation, if $L$ is mean token negative log-likelihood in natural-log units,\n**perplexity** is $\\exp(L)$. It is an exponentiated loss, not a fluency score. Compare\nit only under the same tokenization, data, and averaging contract.\n:::\n<!-- /NOVEL -->\n\n::: {#transformer-samples .cell execution_count=15}\n``` {.python .cell-code code-summary=\"Code: deterministic samples from both Transformer variants\"}\nprint(\"WITH POSITION\\n\")\nprint(transformer_sample(position_model, \"The gradient \"))\nprint(\"\\n\\nWITHOUT POSITION\\n\")\nprint(transformer_sample(no_position_model, \"The gradient \"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nWITH POSITION\n\nThe gradient choing fine on autograd it by tweight the clue larges of calling functions in What independes the gradients $\\rightarrow$ well $\\rightarrow$ with nexp for logits collapse it is the stanged\nnormalized of the argument builds give if the five is the funit or principled update a threshat mactumes at tow\n\n\nWITHOUT POSITION\n\nThe gradient explens ine. The beveuind or clos? we the canlay. Wet orurle\nthis moples doing ther diest the the contive losio thes despunction erbiveng or of a the\ncorno isy la prenod in thrathe s to derngexperevive. With the chate is the compfathes bl. Thicte olo\ntat ur is $L$\\vect{w}^\\vect{w} = \\mectrimes \\vect\n```\n:::\n:::\n\n\nThe positional sample has the book's punctuation, fragments of mathematical\nvocabulary, and stretches that resemble prose. It still loses its argument. The\nno-position sample is visibly rougher. Neither qualitative judgment replaces the\nheld-out loss—a sample is one stochastic path, while the loss evaluates every\nheld-out target under the model's full probability distribution.\n\n<!-- /NOVEL -->\n\n## What the architecture bought\n\nThe rematch is not a referendum on all Transformers—it isolates what this small\none bought and what it paid.\n\n**Direct content routing.** Any earlier visible token can contribute to the next\nrepresentation in one attention sublayer. The recurrent state no longer has to\ncompress the entire past before the current token can consult it.\n\n**Short paths, dense work.** The graph distance between visible tokens is short,\nbut the routing matrix is quadratic in context length. Global access is a\ndifferent tradeoff, not free memory.\n\n**Position becomes a modeling choice.** Convolution and recurrence bake in local\norder. Attention asks the designer to supply position—and decide visibility.\n@sec-15-bert-pretraining will change visibility itself; @sec-16-vit-scaling will\nrevisit what happens\nwhen global routing trades away an image model's locality bias.\n\n**A modular residual stream.** Attention moves information, the FFN transforms it,\nand residual additions let both write into a shared representation. LayerNorm\nkeeps each token's feature scale manageable along the way.\n\nThe causal mask is therefore more than an implementation detail. It says which\ninformation a representation is allowed to use. “Visibility is a modeling\ndecision” is the seed this chapter hands forward.\n\nDuring autoregressive generation, exact softmax attention also makes the past a\nsystems object. A **key/value (KV) cache** retains each layer's earlier key and value\nrows so a new query can reuse them instead of recomputing the whole prefix. In the\nregression language of Chapter 12, the KV cache is the nonparametric estimator's\ndataset: one new query still reads a table that grows with $t$, but the earlier rows\ndo not have to be rebuilt. The toy sampler in @sec-14-self-attention-transformer is\nwasteful precisely because it rebuilds that dataset at every step; Appendix C\nseparates caching from FlashAttention's I/O schedule.\n\n<!-- NOVEL: needs sign-off - test-time regression and memory-spectrum extension. -->\n## The memory spectrum: one regression, three solvers {#sec-14-memory-spectrum}\n\nThe Transformer resolved Chapter 10's bottleneck by keeping the visible evidence\navailable. Its quadratic routing bill was the price. There is another resolution:\nkeep the *problem* Chapter 12 posed, but change how the forward pass solves it.\n\nThat move has become a live architecture program under names such as test-time\nregression, fast weights, linear attention, DeltaNet, and state-space sequence models.\nThe useful unit is not the model name. It is one objective and the statistical bargain\nmade by its solver.\n\n### One objective, four dials\n\nAt time $t$, let learned projections turn token representation $\\vect{x}_\\tau$ into\ntwo views,\n\n$$\n\\vect{k}_\\tau=\\matr{W}_K\\vect{x}_\\tau,\n\\qquad\n\\vect{v}_\\tau=\\matr{W}_V\\vect{x}_\\tau.\n$$\n\nA memory layer can be described as building an online predictor\n$M_t:\\mathbb{R}^{d_k}\\rightarrow\\mathbb{R}^{d_v}$:\n\n$$\nM_t\n=\\arg\\min_{M\\in\\mathcal{M}}\n\\frac{1}{2}\\sum_{\\tau\\le t}w_{t,\\tau}\n\\norm{M(\\vect{k}_\\tau)-\\vect{v}_\\tau}^{2}\n+\\Omega(M),\n\\qquad\n\\vect{y}_t=M_t(\\vect{q}_t),\n\\quad \\vect{q}_t=\\matr{W}_Q\\vect{x}_t.\n$$ {#eq-test-time-regression}\n\nThis is Wang, Shi, and Fox's test-time-regression frame, written for vector values.\nIt exposes four dials the book already knows.\n\n**The views.** $W_Q,W_K,W_V$ are Chapter 13's learned comparison and payload spaces.\nThe token is not assigned one permanent meaning; it learns what to ask, advertise,\nand carry.\n\n**The history weights.** $w_{t,\\tau}$ decide how much an older residual matters to\nthe fitting problem. Chapter 10's forget gates prepared the idea that retention can\ndepend on time and content. A geometric schedule can privilege recent errors; an\ninput-dependent schedule can decide that one token deserves a longer trace.\n\n**The model and regularizer.** The class $\\mathcal{M}$ decides whether the predictor\nis a local constant, a linear map, or something richer. $\\Omega$ brings back ridge\npenalties from Chapter 1 and weight decay from Chapter 4. Regularization controls the\nfitted map; it is not, by itself, the same operation as forgetting old observations.\n\n**The solver.** A closed-form local fit, a running sufficient statistic, and one\ngradient step do different work and preserve different information. This is the new\nrung: *what if the solver itself were a design choice, or even learned?*\n\n@eq-test-time-regression is an umbrella, not an equivalence theorem. Its\nmethods can restrict different function classes, use different weights, and stop at\ndifferent approximations. Those differences are the lesson.\n\n### Solver 1: keep the data and fit at the query\n\nChapter 12 was more precise than saying “attention minimizes\n@eq-test-time-regression.” For a query $\\vect{q}$, softmax attention solves the\nlocal-constant problem\n\n$$\n\\vect{c}^{*}(\\vect{q})\n=\\arg\\min_{\\vect{c}}\n\\frac{1}{2}\\sum_{\\tau\\le t}\n\\kappa(\\vect{q},\\vect{k}_\\tau)\n\\norm{\\vect{c}-\\vect{v}_\\tau}^{2}.\n$$ {#eq-14-local-constant}\n\nWrite $\\kappa_\\tau=\\kappa(\\vect{q},\\vect{k}_\\tau)$. Differentiation gives\n\n$$\n\\nabla_{\\vect{c}}=\n\\sum_{\\tau\\le t}\\kappa_\\tau(\\vect{c}-\\vect{v}_\\tau)=\\vect{0}\n\\quad\\Longrightarrow\\quad\n\\vect{c}^{*}=\n\\frac{\\sum_\\tau\\kappa_\\tau\\vect{v}_\\tau}{\\sum_\\tau\\kappa_\\tau}.\n$$\n\nChoose\n$\\kappa(\\vect{q},\\vect{k})=\\exp(\\vect{q}^{\\top}\\vect{k}/\\sqrt{d_k})$ and the\nnormalized coefficients are exactly a row of scaled dot-product softmax. The kernel\nsupplies the weights; the constant fit supplies the average. An unrestricted $M$ with\nunit observation weights and no regularizer would instead interpolate compatible\ntraining pairs and be undetermined away from them. We will not smuggle the average\ninto a stronger claim.\n\nHere is the numerical stationarity audit. Subtracting the largest score rescales every\n$\\kappa_\\tau$ by the same positive constant and leaves the minimizer unchanged.\n\n::: {#local-constant-attention-check .cell execution_count=16}\n``` {.python .cell-code code-summary=\"Code: verify softmax attention's local-constant optimum\"}\nms_rng = np.random.default_rng(6050)\nms_d, ms_T = 8, 12\nms_K = ms_rng.standard_normal((ms_T, ms_d))\nms_V = ms_rng.standard_normal((ms_T, 3))\nms_q = ms_rng.standard_normal(ms_d)\nms_scores = ms_K @ ms_q / np.sqrt(ms_d)\nms_kappa = np.exp(ms_scores - ms_scores.max())\nms_c = (ms_kappa[:, None] * ms_V).sum(0) / ms_kappa.sum()\nms_attention = (ms_kappa / ms_kappa.sum()) @ ms_V\nms_gradient = (ms_kappa[:, None] * (ms_c - ms_V)).sum(0)\nassert np.allclose(ms_c, ms_attention)\nprint(f\"max |stationarity gradient|: {np.abs(ms_gradient).max():.3e}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmax |stationarity gradient|: 3.053e-16\n```\n:::\n:::\n\n\nThis solver retains the key--value rows because a future query may weight every row\ndifferently. That is why dense causal attention carries a growing dataset forward.\n\n### Solver 2: collapse a factorized kernel into sufficient state\n\nSuppose the kernel factors through a finite feature map\n$\\phi:\\mathbb{R}^{d_k}\\rightarrow\\mathbb{R}^{r}$:\n\n$$\n\\kappa(\\vect{q},\\vect{k})\n=\\phi(\\vect{q})^{\\top}\\phi(\\vect{k}).\n$$\n\nSubstitute that factorization into the weighted average and regroup terms:\n\n$$\n\\begin{aligned}\n\\vect{y}_t(\\vect{q})\n&=\\frac{\\sum_{\\tau\\le t}\n\\bigl[\\phi(\\vect{q})^{\\top}\\phi(\\vect{k}_\\tau)\\bigr]\\vect{v}_\\tau}\n{\\sum_{\\tau\\le t}\\phi(\\vect{q})^{\\top}\\phi(\\vect{k}_\\tau)} \\\\\n&=\\frac{\\phi(\\vect{q})^{\\top}\\matr{S}_t}\n{\\phi(\\vect{q})^{\\top}\\vect{z}_t},\n\\end{aligned}\n$$ {#eq-linear-attention-state}\n\nwhere\n\n$$\n\\matr{S}_t=\\sum_{\\tau\\le t}\\phi(\\vect{k}_\\tau)\\vect{v}_\\tau^{\\top},\n\\qquad\n\\vect{z}_t=\\sum_{\\tau\\le t}\\phi(\\vect{k}_\\tau).\n$$\n\nThe sufficient state is the pair $(\\matr{S}_t,\\vect{z}_t)$, not $\\matr{S}_t$ alone:\nthe numerator needs accumulated value-weighted features and the denominator needs its\nnormalizer. Each new pair updates that fixed-size state once. Any later query reads the\nsame answer as a full traversal of all pairs, for this factorized kernel.\n\n::: {#linear-attention-sufficient-state-check .cell execution_count=17}\n``` {.python .cell-code code-summary=\"Code: compare a factorized-kernel traversal with its running state\"}\ndef ms_phi(x):\n    return np.where(x > 0, x + 1, np.exp(x))\n\nms_S = np.zeros((ms_d, ms_V.shape[1]))\nms_z = np.zeros(ms_d)\nfor ms_key, ms_value in zip(ms_K, ms_V, strict=True):\n    ms_S += np.outer(ms_phi(ms_key), ms_value)\n    ms_z += ms_phi(ms_key)\nms_streaming = (ms_S.T @ ms_phi(ms_q)) / (ms_z @ ms_phi(ms_q))\nms_weights = ms_phi(ms_K) @ ms_phi(ms_q)\nms_traversal = (ms_weights[:, None] * ms_V).sum(0) / ms_weights.sum()\nassert np.allclose(ms_streaming, ms_traversal)\nprint(\"streaming equals traversal:\", np.allclose(ms_streaming, ms_traversal))\nprint(f\"max |difference|: {np.abs(ms_streaming-ms_traversal).max():.3e}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nstreaming equals traversal: True\nmax |difference|: 3.469e-17\n```\n:::\n:::\n\n\nThe equality is exact up to floating-point order: the full dataset traversal has\ncollapsed into two running sums. With $r$ and $d_v$ fixed, storage no longer grows\nwith the prefix. This is the honest content behind “Transformers are RNNs” for\ncausal **linear** attention: the recurrent state returns, dignified, as a sufficient\nstatistic of a regression.\n\nThere is a price. Ordinary softmax's exponential dot-product kernel does not have the\nfinite exact feature map used above. Changing to a finite factorization changes the\nkernel, or approximates it. Collisions in $(S_t,z_t)$ cannot be undone by revisiting a\ndiscarded row. The traversal equality is exact for the chosen factorized kernel, not a\nproof that finite-state linear attention reproduces exact softmax for arbitrary\nprefixes.\n\n### Solver 3: take one gradient step and get the delta rule\n\nNow restrict the predictor to a scalar linear map\n$M(\\vect{q})=\\vect{h}^{\\top}\\vect{q}$ and let the solver take one SGD step on only\nthe newest pair. Its instantaneous loss and gradient are\n\n$$\n\\ell_t(\\vect{h})\n=\\frac{1}{2}(\\vect{h}^{\\top}\\vect{k}_t-v_t)^2,\n\\qquad\n\\nabla_{\\vect{h}}\\ell_t\n=\\vect{k}_t(\\vect{k}_t^{\\top}\\vect{h}-v_t).\n$$\n\nSubstituting the gradient into the update gives the delta recurrence in three lines:\n\n$$\n\\begin{aligned}\n\\vect{h}_t\n&=\\vect{h}_{t-1}-\\eta_t\\vect{k}_t\n  (\\vect{k}_t^{\\top}\\vect{h}_{t-1}-v_t)\\\\\n&=(\\matr{I}-\\eta_t\\vect{k}_t\\vect{k}_t^{\\top})\\vect{h}_{t-1}\n  +\\eta_t v_t\\vect{k}_t.\n\\end{aligned}\n$$ {#eq-delta-recurrence}\n\n::: {#delta-sgd-check .cell execution_count=18}\n``` {.python .cell-code code-summary=\"Code: verify that one SGD step is the delta recurrence\"}\nms_eta = 0.3\nms_h = ms_rng.standard_normal(ms_d)\nms_k = ms_rng.standard_normal(ms_d)\nms_v = ms_rng.standard_normal()\nms_sgd = ms_h - ms_eta * ms_k * (ms_k @ ms_h - ms_v)\nms_delta = ((np.eye(ms_d) - ms_eta * np.outer(ms_k, ms_k)) @ ms_h\n            + ms_eta * ms_v * ms_k)\nassert np.allclose(ms_sgd, ms_delta)\nprint(\"SGD equals Delta recurrence:\", np.allclose(ms_sgd, ms_delta))\nprint(f\"max |difference|: {np.abs(ms_sgd-ms_delta).max():.3e}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSGD equals Delta recurrence: True\nmax |difference|: 4.441e-16\n```\n:::\n:::\n\n\nFor vector values, store\n$\\matr{H}_t\\in\\mathbb{R}^{d_v\\times d_k}$ and replace the update by\n\n$$\n\\matr{H}_t\n=\\matr{H}_{t-1}\n+\\eta_t(\\vect{v}_t-\\matr{H}_{t-1}\\vect{k}_t)\\vect{k}_t^{\\top}.\n$$ {#eq-vector-delta-rule}\n\nEach outer product writes the residual left by the current key. DeltaNet turns that\nclassical online least-squares step into a sequence layer. The recurrence also exposes\na state-space form: its transition is\n$\\matr{A}_t=\\matr{I}-\\eta_t\\vect{k}_t\\vect{k}_t^{\\top}$ and its input write is\n$\\eta_t v_t\\vect{k}_t$. The state transition is therefore determined by the current\ntoken's learned key.\n\nForgetting needs one more careful distinction. Exponential history weights\n$w_{t,\\tau}=\\gamma^{t-\\tau}$ define an exponentially weighted least-squares\n*objective*, but its exact minimizer generally requires a recursive least-squares\ncovariance state. Writing $\\gamma\\matr{H}_{t-1}$ into a one-step delta recurrence is\na fading-memory solver choice, not an algebraic consequence of those weights. Gates\ncan make that retention and the step size depend on the current token.\n\nThis is the derivation-first connection to the wider SSM family. Mamba makes parts of\nits state transition, input injection, and readout depend on the token; in the present\nlanguage, those mechanisms play roles analogous to a learnable retention-and-write\nschedule. Gated DeltaNet adds learned gating around delta-style updates. That is an\ninterpretive bridge, not a claim that Mamba is literally obtained by differentiating\n@eq-test-time-regression. Structured SSMs also use different state parameterizations\nand can have costs below the dense outer-product ledger here.\n\n### The price list\n\n| Solver of the shared problem | State carried forward | Per-token read/write ledger | Statistical contract |\n|---|---|---:|---|\n| Local-constant exponential-kernel fit (softmax attention) | All prior $K,V$ rows: the KV cache | $O(t(d_k+d_v))$ | No state compression; every row remains available, but the read is still a query-dependent weighted average |\n| Factorized kernel | $(S_t,z_t)$ with $S_t\\in\\mathbb{R}^{r\\times d_v}$ | $O(rd_v)$ plus feature-map cost | Exact for the chosen finite factorization; lossy relative to retaining arbitrary raw rows |\n| One newest-pair SGD step (Delta rule and gated variants) | $H_t\\in\\mathbb{R}^{d_v\\times d_k}$ plus any gate state | $O(d_kd_v)$ for a dense update/read | Approximate online fit; fixed capacity whose writes can be steered |\n\n: Solver choices expose the memory spectrum of the shared regression problem. {#tbl-memory-spectrum}\n\nThe asymptotic labels in @tbl-memory-spectrum name this dense educational setup, not\nevery implementation.\nFeature width $r$, head dimensions, low-rank structure, convolutions, and hardware\nschedules change constants and sometimes orders. Most importantly, “retains every\nrow” does not mean “recalls every association exactly.” Softmax still returns a convex\nmixture whose quality depends on keys, temperature, and interference.\n\n::: {.callout-warning}\n## Trap: attention's memory is a dataset, not a hidden box\n\nAttention does not *have* a separate memory in the recurrent sense. The attention\noperation is the estimator; during causal decoding, the KV cache is the observed\nkey--value dataset it must retain. A nonparametric query rule keeps growing data so it\ncan form a new local fit. A parametric state instead compresses those data into a\nfixed-size object. FlashAttention changes how the uncompressed fit is scheduled; it\ndoes not turn it into the compressed contract in the second or third row.\n:::\n\n### Mechanism test: recall under a fixed capacity\n\n@tbl-memory-spectrum makes a prediction we can test without pretending to train a\nlanguage model. Store $N$ random unit key--value pairs, then query every stored key. Decode a\nread by the nearest stored value. Exact softmax attention keeps all pairs. A dense\ndelta state has $d^2$ numbers regardless of $N$. A selective delta arm receives one\nextra priority bit and writes ordinary pairs at only one tenth strength, so it can\nchoose what to sacrifice.\n\nThe study was designed on seed branches 0 and 1. Those branches fixed\n$\\eta=0.20$, the 25% priority rate, the 0.10 ordinary write gate, dimensions\n$(8,16,32)$, and loads $N/d\\in(0.5,1,2,4,8)$. Only then was disjoint branch 2 opened\nfor 30 endpoint repetitions. All methods in a trial receive the same keys, values,\norder, queries, and decoder. The endpoint code below is the frozen protocol; it runs\non CPU in under a second on the reference machine.\n\n::: {#memory-capacity-study .cell execution_count=19}\n``` {.python .cell-code code-summary=\"Code: run the sealed synthetic recall-under-capacity study\"}\nMS_SEED, MS_ETA, MS_GATE = 6050, 0.20, 0.10\nMS_DIMS, MS_LOADS, MS_REPEATS = (8, 16, 32), (0.5, 1, 2, 4, 8), 30\n\ndef ms_unit(x):\n    return x / np.linalg.norm(x, axis=1, keepdims=True)\n\ndef ms_decode(prediction, values):\n    return np.argmax(prediction @ values.T, axis=1)\n\ndef ms_trial(rng, repeat, d, load):\n    n = max(4, round(load * d))\n    keys = ms_unit(rng.standard_normal((n, d)))\n    values = ms_unit(rng.standard_normal((n, d)))\n    priority = np.zeros(n, dtype=bool)\n    priority[rng.permutation(n)[:max(1, round(0.25 * n))]] = True\n\n    scores = 32.0 * (keys @ keys.T)\n    scores -= scores.max(axis=1, keepdims=True)\n    weights = np.exp(scores); weights /= weights.sum(axis=1, keepdims=True)\n    attention = weights @ values\n\n    def delta(write_gate):\n        state = np.zeros((d, d))\n        for key, value, gate in zip(keys, values, write_gate, strict=True):\n            state += MS_ETA * gate * np.outer(value - state @ key, key)\n        return keys @ state.T\n\n    plain = delta(np.ones(n))\n    selective = delta(np.where(priority, 1.0, MS_GATE))\n    truth = np.arange(n)\n    correct = lambda pred: ms_decode(pred, values) == truth\n    a_ok, d_ok, s_ok = correct(attention), correct(plain), correct(selective)\n    ordinary = ~priority\n    return [repeat, d, n, load, a_ok.mean(), ((attention-values)**2).mean(),\n            d_ok.mean(), d_ok[priority].mean(), d_ok[ordinary].mean(),\n            s_ok.mean(), s_ok[priority].mean(), s_ok[ordinary].mean()]\n\ndef ms_panel(tag, repeats):\n    seeds = np.random.SeedSequence([MS_SEED, tag]).spawn(\n        repeats * len(MS_DIMS) * len(MS_LOADS))\n    rows, index = [], 0\n    for repeat in range(repeats):\n        for d in MS_DIMS:\n            for load in MS_LOADS:\n                rows.append(ms_trial(np.random.default_rng(seeds[index]),\n                                     repeat, d, load))\n                index += 1\n    return np.asarray(rows)\n\n# Tags 0 and 1 were development; tag 2 remained sealed until settings were fixed.\nms_development = np.vstack([ms_panel(tag, 5) for tag in (0, 1)])\nassert np.all(ms_development[:, 4] == 1.0)\nms_endpoint = ms_panel(2, MS_REPEATS)\nassert np.all(ms_endpoint[:, 4] == 1.0)\n\nprint(\"study_seed=6050; development_tags=(0, 1); sealed_endpoint_tag=2\")\nprint(\"endpoint_trials=30 x 3 dimensions; d=(8, 16, 32); \"\n      \"N/d=(0.5, 1, 2, 4, 8)\")\nprint(\"fixed: eta=0.20; priority_fraction=0.25; ordinary_write_gate=0.10\")\nprint(\"load  attention  Delta  gated-all  gated-priority  gated-ordinary\")\nfor load in MS_LOADS:\n    block = ms_endpoint[ms_endpoint[:, 3] == load]\n    means = block[:, [4, 6, 9, 10, 11]].mean(0)\n    print(f\"{load:>4.1f}   \" + \"  \".join(f\"{value:.3f}\" for value in means))\n\nhard = ms_endpoint[ms_endpoint[:, 3] == 8]\npriority_gain = hard[:, 10] - hard[:, 7]\nordinary_gain = hard[:, 11] - hard[:, 8]\nprint(f\"N/d=8 gated-minus-Delta priority: {priority_gain.mean():+.3f} \"\n      f\"(SD {priority_gain.std(ddof=1):.3f})\")\nprint(f\"N/d=8 gated-minus-Delta ordinary: {ordinary_gain.mean():+.3f} \"\n      f\"(SD {ordinary_gain.std(ddof=1):.3f})\")\nprint(f\"attention top-1 failures=0/{int(ms_endpoint[:, 2].sum())}; \"\n      f\"mean value MSE={ms_endpoint[:, 5].mean():.2e}; \"\n      f\"max trial MSE={ms_endpoint[:, 5].max():.2e}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nstudy_seed=6050; development_tags=(0, 1); sealed_endpoint_tag=2\nendpoint_trials=30 x 3 dimensions; d=(8, 16, 32); N/d=(0.5, 1, 2, 4, 8)\nfixed: eta=0.20; priority_fraction=0.25; ordinary_write_gate=0.10\nload  attention  Delta  gated-all  gated-priority  gated-ordinary\n 0.5   1.000  0.988  0.471  1.000  0.294\n 1.0   1.000  0.910  0.352  0.992  0.139\n 2.0   1.000  0.657  0.282  0.982  0.048\n 4.0   1.000  0.338  0.228  0.848  0.022\n 8.0   1.000  0.134  0.138  0.522  0.010\nN/d=8 gated-minus-Delta priority: +0.387 (SD 0.156)\nN/d=8 gated-minus-Delta ordinary: -0.124 (SD 0.065)\nattention top-1 failures=0/26040; mean value MSE=5.43e-06; max trial MSE=4.55e-04\n```\n:::\n:::\n\n\n::: {#cell-fig-memory-capacity-spectrum .cell execution_count=20}\n``` {.python .cell-code code-summary=\"Figure: compare full-table and fixed-state recall as load grows\"}\nfig, axes = plt.subplots(1, 2, figsize=(8.4, 3.35), constrained_layout=True)\ncolors = {8: \"#E57200\", 16: \"#2E7D32\", 32: \"#722F37\"}\nfor d in MS_DIMS:\n    means = [ms_endpoint[(ms_endpoint[:, 1] == d) &\n                         (ms_endpoint[:, 3] == load), 6].mean()\n             for load in MS_LOADS]\n    axes[0].plot(MS_LOADS, means, marker=\"o\", color=colors[d], label=f\"Delta, d={d}\")\naxes[0].plot(MS_LOADS, np.ones(len(MS_LOADS)), color=\"#232D4B\", lw=2,\n             label=\"softmax table\")\naxes[0].set(xscale=\"log\", xlabel=\"load N/d\", ylabel=\"top-1 recall\",\n            title=\"Fixed state meets capacity\", ylim=(-0.03, 1.05))\naxes[0].set_xticks(MS_LOADS, [str(x) for x in MS_LOADS])\naxes[0].minorticks_off()\naxes[0].legend(fontsize=7.3)\n\nfor column, label, style, color in [\n    (7, \"Delta: priority\", \"--\", \"#B45309\"),\n    (8, \"Delta: ordinary\", \"--\", \"#64748B\"),\n    (10, \"gated: priority\", \"-\", \"#E57200\"),\n    (11, \"gated: ordinary\", \"-\", \"#232D4B\"),\n]:\n    means = [ms_endpoint[ms_endpoint[:, 3] == load, column].mean()\n             for load in MS_LOADS]\n    axes[1].plot(MS_LOADS, means, marker=\"o\", ls=style, color=color, label=label)\naxes[1].set(xscale=\"log\", xlabel=\"load N/d\", ylabel=\"top-1 recall\",\n            title=\"A gate chooses what to forget\", ylim=(-0.03, 1.05))\naxes[1].set_xticks(MS_LOADS, [str(x) for x in MS_LOADS])\naxes[1].minorticks_off()\naxes[1].legend(fontsize=7.3)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![A sealed synthetic mechanism test, not a language-model or state-space benchmark. Left: the uncompressed softmax table has perfect top-1 identification in this constructed, sharp-softmax regime, while the fixed delta state loses associations as N/d grows; this is not exact numeric interpolation. Right: the selective arm receives an unmatched priority bit and trades ordinary recall for priority recall. Keys, values, order, queries, decoder, and state width are matched within each trial; inference arithmetic, stored data, and side information are not matched, and no wall-clock claim is made. Left-panel lines average 30 endpoint seeds per dimension; right-panel lines pool the three dimensions, for 90 dimension-by-seed trials per load.](14-self-attention-transformer_files/figure-html/fig-memory-capacity-spectrum-output-1.png){#fig-memory-capacity-spectrum width=818 height=333 fig-alt='Two line charts. In the left chart softmax top-1 recall stays at one while Delta recall falls with load for dimensions 8, 16, and 32. In the right chart a gated Delta update preserves priority items better than ordinary items, especially at high load, while the ungated update does not make that trade as strongly.'}\n:::\n:::\n\n\nAt $N/d=8$, the gate raises priority recall over the plain delta state by 0.387 on\naverage and lowers ordinary recall by 0.124. That is selective forgetting made\nvisible, not a claim that the gated arm is globally better. Overall gated recall is\n0.138 while plain Delta recall is 0.134 at that load. The useful result is the trade:\ngiven an extra signal, a fixed state can spend capacity differently.\n\nThe fixed-size state could not hold everything in @sec-10-sequences-rnn. It still\ncannot. Now we know the price list on which that failure was one entry. Keeping the\ndataset buys uncompressed access at growing cost; sufficient statistics buy an exact\nstream for a restricted kernel; online updates buy a steerable fixed state and accept\ninterference. The RNN state has returned as a statistical choice rather than a design\nwe were supposed to declare dead.\n<!-- /NOVEL -->\n\n## Okay, so — the Transformer routes, then computes\n\n1. **Self-attention reuses Chapter 13's operator within one sequence.** $Q$, $K$,\n   and $V$ all come from $X$; one learned comparison rule is shared over every\n   ordered pair. Training positions can be evaluated together, while\n   autoregressive generation remains sequential.\n2. **Bare attention is permutation equivariant, not invariant.**\n   $\\operatorname{SA}(PX)=P\\operatorname{SA}(X)$. Sinusoidal clocks repay Chapter\n   8's position debt, and their sine/cosine pairs turn relative shifts into\n   rotations.\n3. **Multi-head attention is shape discipline.** Split\n   $(B,n,d)\\to(B,h,n,d_h)$, scale by $\\sqrt{d_h}$, form\n   $(B,h,n,n)$ routing weights, concatenate, and project. At fixed $d$, the four\n   leading projections remain about $4d^2$ parameters.\n4. **The causal mask defines visibility.** Future scores become negative infinity\n   before softmax. The dense operator still performs quadratic work; the mask does\n   not make the forbidden half computationally disappear.\n5. **The block alternates routing and computation.** Multi-head attention mixes\n   positions, the FFN transforms each position, and both write corrections into\n   Chapter 9's residual stream. LayerNorm is the same normalization equation over\n   a token's feature axis.\n6. **Position wins this seed's controlled ablation.** It lowers held-out loss from\n   2.3405 to 1.9190. **The LSTM narrowly wins the small-model rematch**, 1.8881\n   versus 1.9190.\n   Architecture changes inductive bias; it does not guarantee victory in every\n   data and scale regime.\n7. **One regression question admits several memory contracts.** Exact softmax keeps\n   the key--value table; a factorized kernel carries $(S_t,z_t)$; a delta update\n   carries a fixed matrix and accepts interference. The solver decides what the\n   layer remembers and what it pays.\n\n## Sources and further reading {.unnumbered}\n\n- [Vaswani et al., *Attention Is All You Need*](https://papers.nips.cc/paper_files/paper/2017/hash/3f5ee243547dee91fbd053c1c4a845aa-Abstract.html): multi-head attention, sinusoidal position, and the original post-LayerNorm encoder–decoder.\n- [Ba, Kiros, and Hinton, *Layer Normalization*](https://arxiv.org/abs/1607.06450): normalization within one example and identical train/evaluation computation.\n- [Xiong et al., *On Layer Normalization in the Transformer Architecture*](https://proceedings.mlr.press/v119/xiong20b.html): a qualified comparison of pre- and post-LayerNorm optimization.\n- [Geva et al., *Transformer Feed-Forward Layers Are Key-Value Memories*](https://aclanthology.org/2021.emnlp-main.446/): empirical evidence behind the associative-memory interpretation of FFNs.\n- [Jain and Wallace, *Attention Is Not Explanation*](https://aclanthology.org/N19-1357/): an important limit on reading attention maps as explanations.\n- [Holtzman et al., *The Curious Case of Neural Text Degeneration*](https://arxiv.org/abs/1904.09751): nucleus sampling and the distinction between likely continuations and useful generation behavior.\n- [Katharopoulos et al., *Transformers Are RNNs: Fast Autoregressive Transformers with Linear Attention* (2020)](https://arxiv.org/abs/2006.16236): derives the recurrent sufficient-state form for causal linear attention.\n- [Schlag, Irie, & Schmidhuber, *Linear Transformers Are Secretly Fast Weight Programmers* (2021)](https://proceedings.mlr.press/v139/schlag21a.html): connects linear attention, fast weights, and the delta update.\n- [Gu & Dao, *Mamba: Linear-Time Sequence Modeling with Selective State Spaces* (2023)](https://arxiv.org/abs/2312.00752): makes state-space parameters input dependent; the chapter uses selectivity as a retention-and-write analogy, not an exact regression equivalence.\n- [Yang et al., *Gated Delta Networks: Improving Mamba2 with Delta Rule* (2024)](https://arxiv.org/abs/2412.06464): combines gated linear recurrence with delta-style associative updates.\n- [Wang, Shi, & Fox, *Test-Time Regression: A Unifying Framework for Designing Sequence Models with Associative Memory* (2025)](https://arxiv.org/abs/2501.12352): the shared regression objective and solver-design perspective.\n\n## Exercises {.unnumbered}\n\n1. **(Pencil.)** Starting from $Q'=PQ$, $K'=PK$, and $V'=PV$, prove each step of\n   $\\operatorname{SA}(PX)=P\\operatorname{SA}(X)$. Then show that mean-pooling the\n   token outputs produces a permutation-*invariant* sequence representation.\n2. **(Pencil.)** For width $d=512$ and $h=8$, write every tensor shape in\n   multi-head attention for $B=32$ and $n=100$. Count the weights in\n   $W_Q,W_K,W_V,W_O$. Repeat for $h=16$ and explain which dimensions change while\n   the leading parameter count does not.\n3. **(Code.)** Deliberately transpose the causal mask in\n   @fig-causal-multihead, then design an assertion that identifies the first\n   leaked query-key pair. Next set forbidden probabilities to zero *after*\n   softmax and measure the row-sum error.\n4. **(Code.)** Replace the fixed sinusoidal table with a learned\n   $\\text{Embedding}(100,d)$ while preserving the exact initialization and window\n   schedule protocol. Compare held-out loss. Then extend the sinusoidal buffer by\n   evaluating its formula beyond position 99, and propose an explicit extension\n   rule for the learned table before testing either model on a longer context.\n   Which design has a natural extension, and which has to invent one?\n5. **(Code and interpretation.)** Aggregate learned attention by relative offset\n   across the held-out tail rather than naming heads from one prompt. Report a\n   distribution for every head and block. Then perturb the highest-weight key's\n   value vector and measure the logit change. Explain why routing weight and causal\n   influence need not rank tokens identically.\n6. **(Pencil.)** Starting from @eq-14-local-constant, derive the stationarity\n   equation and its normalized solution. Identify exactly where the local-constant\n   restriction enters. Why would an unrestricted function with no regularizer not\n   imply the same average?\n7. **(Code.)** Reproduce @eq-linear-attention-state with a positive feature map of\n   your choice. Assert that full traversal and the running pair $(S_t,z_t)$ agree for\n   every prefix, not only at the final time. Which assertion fails if you omit $z_t$?\n8. **(Pencil.)** Derive @eq-delta-recurrence from one SGD step. Then propose a\n   recurrence with a factor $\\gamma$ multiplying the old state. Explain why this is a\n   fading-memory solver choice rather than the exact minimizer of exponentially\n   weighted least squares.\n9. **(Code.)** Sweep the capacity study over at least five state widths $d$. Preserve\n   the sealed-seed protocol, plot recall against both $N$ and $N/d$, and report where\n   the curves align. Do not call top-1 identification exact value recall.\n10. **(Pencil and critique.)** For each row of the price table, write the state size,\n    update cost, query cost, and information that cannot be reconstructed. Which pair\n    is compute-matched? Which is storage-matched? Design one rematch for a claim you\n    would actually be willing to make.\n\n",
    "supporting": [
      "14-self-attention-transformer_files/figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}