{
  "hash": "2e2ac93a8efe41ba9d79f277125a67d6",
  "result": {
    "engine": "jupyter",
    "markdown": "# Self-Attention and the Transformer {#sec-14-self-attention-transformer}\n\n<!-- lecture-source:\n     m09_lecture-9-transformer_N4ePLi42ADk.txt\n     [coding]_m09_lecture-9-2-transformer-part-2_tG8b2eNm6Gg.txt\n     (spine via ds6050_09_transformer/MODULE_NOTES.md; scene compositions from\n     that module's Manim source)\n     seeds: sources/9.1-self-attention.tex,\n            sources/9.A.1-positional_encoding.tex,\n            sources/9.1A-Normalization_in_Transformers.tex\n     primary sources: Vaswani et al. 2017; Ba et al. 2016;\n                      Xiong et al. 2020; Geva et al. 2021;\n                      Jain and Wallace 2019\n     provenance note: all executable implementations were independently derived\n     from the displayed equations. The book-corpus schedule is reconstructed from\n     the book-original Chapter 10 cell. The experiment uses a custom decoder-only,\n     pre-LayerNorm Transformer rather than the original encoder-decoder,\n     post-LayerNorm architecture. It makes no measured hardware-speed claim. -->\n\n@sec-13-attention ended with a question that the attention operator itself had already\nanswered. A query, key, and value need not come from an encoder or a decoder. They\nneed not come from a recurrent network at all. If all three come from the same\nsequence, each token can ask every token—including itself—what matters and route the answers\ndirectly. The recurrent state—the last serial bottleneck left standing—becomes\noptional.\n\nThat substitution is the core of a *Transformer*. It is also easy to state too\nquickly. Removing recurrence creates a position problem. Splitting one attention\noperation into heads creates a bookkeeping problem. Stacking the resulting\noperations creates an optimization problem. This chapter solves each one—from the\nequations outward—then returns to the book-corpus benchmark from\n@sec-10-sequences-rnn with a\ndeliberately small causal Transformer.\n\n<!-- NOVEL: needs sign-off - opening preview of the seeded book-corpus rematch. -->\n\nHere is the result we have to explain on the same 14,860-character held-out tail.\nIn one exactly matched seed, positional encoding improves the Transformer's loss\nfrom 2.3405 to 1.9190. Yet Chapter 10's compact LSTM remains better at 1.8881. The new architecture\nhas learned, and position matters in this run—but at this scale, the LSTM still\nwins.\n\n<!-- /NOVEL -->\n\n## Let the sequence query itself\n\nSuppose the sentence contains the words *bank*, *river*, and *boats*. A useful\nrepresentation of *bank* should route information from *river* and *boats*, while\nanother occurrence—now near *loan* and *interest*—should route different information.\nChapter 13 built exactly this kind of content-dependent routing. Self-attention\nchanges only the source of the three inputs.\n\nThe three questions still fit: a query asks “what am I looking for?”, a\nkey advertises “what do I offer?”, and a value carries “what information do I\ncontain?”\n\nLet a batch of token representations be\n\n$$\nX \\in \\mathbb{R}^{B \\times n \\times d},\n$$\n\nwhere $B$ is batch size, $n$ is sequence length, and $d$ is model width. Learned\nprojections produce\n\n$$\nQ=XW_Q,\\qquad K=XW_K,\\qquad V=XW_V,\n$$\n\nwith $W_Q,W_K,W_V\\in\\mathbb{R}^{d\\times d}$. Scaled dot-product attention is\n\n$$\n\\operatorname{Attention}(Q,K,V)\n=\n\\operatorname{softmax}\\left(\\frac{QK^\\top}{\\sqrt d}\\right)V.\n$$\n\nFor one sequence, $QK^\\top$ has shape $n\\times n$. Row $i$ contains the scores from\nquery position $i$ to every key position $j$. The row-wise softmax makes each row a\ndistribution, and multiplying by $V$ returns one weighted sum for each query:\n\n$$\n(n,d)(d,n)\\to(n,n),\\qquad (n,n)(n,d)\\to(n,d).\n$$\n\nChapter 10 named time as the book's third sharing axis. An RNN shares one transition\nrule across time. Self-attention keeps that stationarity and extends the shared rule\nacross every ordered pair of positions. The weights in a particular attention row\nstill depend on the content; what is shared is the machinery that produces them.\n\nAll query positions can be evaluated together during training because none waits\nfor a hidden state from the preceding position. That is a structural statement—not\na timing result. Dense self-attention still forms $n^2$ pairwise scores, and\nautoregressive generation still emits one new token at a time.\n\n### The position debt\n\nBare self-attention knows content but not slot number. A precise proof is more\nuseful than the slogan.\n\nLet $P$ be an $n\\times n$ permutation matrix, so $PX$ reorders the tokens. Then\n\n$$\nQ'=PQ,\\quad K'=PK,\\quad V'=PV\n$$\n\nand therefore\n\n$$\nQ'K'^\\top=P(QK^\\top)P^\\top.\n$$\n\nWrite $S=QK^\\top/\\sqrt d$; then $S'=PSP^\\top$. Row-wise softmax respects the\nsame simultaneous row-and-column permutation:\n\n$$\n\\operatorname{softmax}(PSP^\\top)\n=P\\operatorname{softmax}(S)P^\\top.\n$$\n\nPutting the pieces together gives\n\n$$\n\\operatorname{SA}(PX)\n=P\\operatorname{SA}(X).\n$$\n\nSelf-attention is *permutation equivariant*: permute the inputs and the outputs\npermute in the same way. It is not permutation invariant—the token outputs do not\nall become identical. But without another signal, the operator has no basis for\ndistinguishing “first” from “fifth.” A pooled sequence summary can consequently\nbecome invariant to order.\n\n@sec-08-cnn planted this debt when convolution received locality “for free.” A\nconvolution knows which values are neighbors because its kernel is tied to nearby\noffsets. Global attention abandons that built-in geometry—so we must pay to put\nposition back in.\n\n<!-- NOVEL: needs sign-off - seeded permutation/position audits and figures. -->\n\n:::: {.plan-code .plan-code-wide}\n::: {.plan}\n1. Define the reusable helpers: `numpy_attention` and `numpy_positions`.\n2. Prepare the inputs and fixed settings for the example.\n3. Report the permutation-equivariance and fixed-slot differences.\n:::\n\n::: {#permutation-debt-audit .cell execution_count=1}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: audit permutation equivariance and positional debt\"}\nimport math\nimport numpy as np\nimport matplotlib.pyplot as plt\n\n# [1]\ndef numpy_attention(x: np.ndarray) -> np.ndarray:\n    scores = x @ x.T / math.sqrt(x.shape[-1])\n    scores = scores - scores.max(axis=-1, keepdims=True)\n    weights = np.exp(scores)\n    weights = weights / weights.sum(axis=-1, keepdims=True)\n    return weights @ x\n\ndef numpy_positions(length: int, width: int) -> np.ndarray:\n    position = np.arange(length)[:, None]\n    frequency = np.exp(\n        np.arange(0, width, 2) * (-math.log(10_000.0) / width)\n    )\n    pe = np.zeros((length, width))\n    pe[:, 0::2] = np.sin(position * frequency)\n    pe[:, 1::2] = np.cos(position * frequency)\n    return pe\n\n# [2]\nrng = np.random.default_rng(6050)\nx = rng.normal(size=(5, 8))\npermutation = np.array([2, 4, 0, 1, 3])\nbare_error = np.abs(\n    numpy_attention(x[permutation]) - numpy_attention(x)[permutation]\n).max()\n\npe = numpy_positions(5, 8)\nwith_position = numpy_attention(x + pe)\nfixed_slot_change = np.abs(\n    numpy_attention(x[permutation] + pe) - with_position[permutation]\n).max()\n\n# [3]\nprint(f\"bare permutation-equivariance error: {bare_error:.2e}\")\nprint(f\"fixed-slot difference after adding position: {fixed_slot_change:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nbare permutation-equivariance error: 2.22e-16\nfixed-slot difference after adding position: 1.581\n```\n:::\n:::\n\n\n::::\n\n::: {.cell fig-height='3.4' fig-width='10' execution_count=2}\n\n::: {.cell-output .cell-output-display}\n![The same content is permuted across slots (left). The audit (right) shows bare self-attention rematches after the same output permutation, while fixed positional signals break that rematch.](14-self-attention-transformer_files/figure-pdf/fig-permutation-debt-output-1.pdf){#fig-permutation-debt fig-alt='Two-panel permutation audit. The left panel moves five colored word tiles from the sequence \\'bank by the river\\' into a new slot order. The right log-scale bars show a rematched bare-attention difference near machine precision and an order-one difference after fixed position vectors are added.'}\n:::\n:::\n\n\nThe first error is numerical roundoff, about $2.2\\times10^{-16}$. Adding a fixed\nsignal to each slot changes the rematched outputs by about 1.581 in this example.\nPosition has not been inferred from content; it has been supplied.\n\n## Position as a bank of clocks\n\nThe simplest additive code repeats $i/(n-1)$ in every coordinate. It supplies\norder, but every position vector lies on the same ray and differs only in\nmagnitude; attention receives no multidirectional geometry. A binary code supplies\nmore coordinates, yet adjacent integers can flip many bits and have poor locality.\nThese are not impossible designs—they are weak inductive biases for a model that\nmust reason about shifts and distances.\n\nSinusoidal encoding gives every position a bank of clocks. For even model width\n$d$, define\n\n$$\n\\begin{aligned}\n\\operatorname{PE}(i,2j)\n&=\\sin\\left(i\\,10000^{-2j/d}\\right),\\\\\n\\operatorname{PE}(i,2j+1)\n&=\\cos\\left(i\\,10000^{-2j/d}\\right).\n\\end{aligned}\n$$\n\nSmall $j$ gives a fast clock; large $j$ gives a slow one. Every sine coordinate is\npaired with a cosine at the same frequency. The model receives\n\n$$\nZ_i=\\sqrt d\\,E_i+\\operatorname{PE}(i),\n$$\n\nwhere $E_i$ is the token embedding. Scaling the embedding keeps its initial\nmagnitude commensurate with the position vector.\n\nWhy pair sine and cosine? For frequency $\\omega$, advancing by offset $\\delta$ is a\nrotation—an algebraic answer to a geometric question:\n\n$$\n\\begin{bmatrix}\n\\sin((i+\\delta)\\omega)\\\\\n\\cos((i+\\delta)\\omega)\n\\end{bmatrix}\n=\n\\begin{bmatrix}\n\\cos(\\delta\\omega)&\\sin(\\delta\\omega)\\\\\n-\\sin(\\delta\\omega)&\\cos(\\delta\\omega)\n\\end{bmatrix}\n\\begin{bmatrix}\n\\sin(i\\omega)\\\\\n\\cos(i\\omega)\n\\end{bmatrix}.\n$$\n\nThe rotation depends on the offset, not the absolute position. This gives learned\nlinear maps a convenient raw material for representing relative shifts. It is a\nproperty of the positional pair itself—not a guarantee that arbitrary learned\n$W_Q$ and $W_K$ will preserve or use it.\n\n::: {.callout-note}\n## Show the rotation, then name it\n\nInstead of adding the clock coordinates to the token, rotate each query and key\ndirectly. If $R_i$ is the block-diagonal rotation for position $i$, use\n$\\widetilde{\\vect{q}}_i=R_i\\vect{q}_i$ and\n$\\widetilde{\\vect{k}}_j=R_j\\vect{k}_j$. Their score becomes\n\n$$\n\\widetilde{\\vect{q}}_i^\\top\\widetilde{\\vect{k}}_j\n=\\vect{q}_i^\\top R_i^\\top R_j\\vect{k}_j\n=\\vect{q}_i^\\top R_{j-i}\\vect{k}_j.\n$$\n\nThe positional factor now depends on the relative offset $j-i$. This construction is\ncalled **rotary positional embedding (RoPE)**. Content still matters through\n$\\vect{q}_i$ and $\\vect{k}_j$; RoPE changes how position enters their comparison.\n:::\n\n:::: {.plan-code .plan-code-wide}\n::: {.plan}\n1. Prepare the inputs and fixed settings for the example.\n2. Verify the rotation identity and constant-norm invariant.\n:::\n\n::: {#position-build-audit .cell execution_count=3}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: audit sinusoidal position as a bank of clocks\"}\n# [1]\npe = numpy_positions(100, 32)\n\ndelta = 7\nj = 5\nomega = 10_000 ** (-2 * j / 32)\nrotation = np.array([\n    [np.cos(delta * omega), np.sin(delta * omega)],\n    [-np.sin(delta * omega), np.cos(delta * omega)],\n])\npair_i = pe[13, 2 * j : 2 * j + 2]\npair_shifted = pe[13 + delta, 2 * j : 2 * j + 2]\nrotation_error = np.abs(rotation @ pair_i - pair_shifted).max()\nnorm_error = np.abs(np.linalg.norm(pe, axis=1) - 4.0).max()\n\n# [2]\nprint(f\"rotation identity maximum error: {rotation_error:.2e}\")\nprint(f\"constant position-vector norm maximum error: {norm_error:.2e}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nrotation identity maximum error: 1.11e-16\nconstant position-vector norm maximum error: 0.00e+00\n```\n:::\n:::\n\n\n::::\n\n::: {.cell fig-height='5' fig-width='10' execution_count=4}\n\n::: {.cell-output .cell-output-display}\n![Sinusoidal position is a bank of clocks. Fast coordinates track local offsets; slow coordinates vary across longer ranges. Each sine/cosine pair acts like a clock, and a fixed offset rotates that pair by a start-independent angle.](14-self-attention-transformer_files/figure-pdf/fig-position-build-output-1.pdf){#fig-position-build fig-alt='Four-panel view of sinusoidal position. Fast sine and cosine coordinates oscillate repeatedly across 100 positions; slow coordinates change only slightly. A heatmap stacks 32 coordinates from fast bands at top to nearly constant slow bands at bottom. A unit-circle diagram shows positions 13 and 20 separated by the same rotation associated with offset seven.'}\n:::\n:::\n\n\nFor $d=32$, each position vector has norm $\\sqrt{d/2}=4$ because every\n$\\sin^2+\\cos^2$ pair contributes one. Adding this vector does *not* preserve the\nnorm of the combined token representation—the embedding and position vector can\nreinforce or cancel one another. Layer normalization will soon manage scale at the\nblock level.\n\n<!-- /NOVEL -->\n\n## One routing operation, many heads\n\nA single attention distribution must make one compromise about what to retrieve.\nMulti-head attention lets several smaller routing systems—separate views of the\nsame residual stream—operate in parallel.\nChoose a number of heads $h$ that divides $d$, and let $d_h=d/h$. For each head\n$r$,\n\n$$\nQ_r=XW_Q^{(r)},\\quad\nK_r=XW_K^{(r)},\\quad\nV_r=XW_V^{(r)},\n$$\n\nwhere\n$W_Q^{(r)},W_K^{(r)},W_V^{(r)}\\in\\mathbb{R}^{d\\times d_h}$. The head output is\n\n$$\nH_r=\n\\operatorname{softmax}\\left(\n\\frac{Q_rK_r^\\top}{\\sqrt{d_h}}+M\n\\right)V_r.\n$$\n\nHere $M$ is the visibility mask defined next; $M=0$ for unmasked attention.\n\nThe complete operation concatenates the heads and mixes them:\n\n$$\n\\operatorname{MHA}(X)\n=\\operatorname{Concat}(H_1,\\ldots,H_h)W_O,\n\\qquad W_O\\in\\mathbb{R}^{d\\times d}.\n$$\n\nThe shape ledger is the safest implementation guide:\n\n$$\n(B,n,d)\n\\to(B,h,n,d_h)\n\\to(B,h,n,n)\n\\to(B,h,n,d_h)\n\\to(B,n,d).\n$$\n\nScaling uses $\\sqrt{d_h}$, not $\\sqrt d$, because a head's dot product sums $d_h$\nterms. With fixed $d$, splitting into heads does not multiply the leading projection\ncount: $W_Q,W_K,W_V,W_O$ together contribute about $4d^2$ weights regardless of\n$h$. Heads divide the representational subspace—they do not each receive a fresh\nwidth-$d$ model.\n\n### The mask is part of the model\n\n@sec-11-encoder-decoder called masking the rule that tells a model *which positions it may not\nlook at*. Here that rule is causal: position $i$ may use tokens at positions\n$j\\le i$ but must not inspect future tokens $j>i$. Rows are queries and columns\nare keys, so the forbidden region is the strict upper triangle. We add\n\n$$\nM_{ij}=\n\\begin{cases}\n0,&j\\le i,\\\\\n-\\infty,&j>i\n\\end{cases}\n$$\n\n*before* softmax. Replacing forbidden probabilities with zero afterward would\nleave the remaining row unnormalized. Masking every key in a row is invalid—softmax\nwould receive only negative infinity. Here the diagonal remains visible:\nthe representation at a character may use that character while predicting the\nnext one.\n\n<!-- NOVEL: needs sign-off - independent causal multi-head implementation and mask audit. -->\n\n:::: {.plan-code .plan-code-wide}\n::: {.plan}\n1. Define the `CausalMultiHeadAttention` module.\n2. Prepare the inputs and fixed settings for the example.\n3. Implement causal multi-head attention and audit its mask.\n:::\n\n::: {#causal-multihead-implementation .cell execution_count=5}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: implement causal multi-head attention and audit its mask\"}\nimport torch\nfrom torch import nn\n\n# [1]\nclass CausalMultiHeadAttention(nn.Module):\n    def __init__(self, width: int, heads: int) -> None:\n        super().__init__()\n        if width % heads != 0:\n            raise ValueError(\"width must be divisible by heads\")\n        self.heads = heads\n        self.head_width = width // heads\n        self.qkv = nn.Linear(width, 3 * width)\n        self.project = nn.Linear(width, width)\n        nn.init.xavier_uniform_(self.qkv.weight)\n        nn.init.zeros_(self.qkv.bias)\n\n    def forward(self, x: torch.Tensor, return_weights: bool = False):\n        batch, length, width = x.shape\n        qkv = self.qkv(x)\n        qkv = qkv.reshape(\n            batch, length, 3, self.heads, self.head_width\n        ).permute(2, 0, 3, 1, 4)\n        q, k, v = qkv.unbind(dim=0)\n        scores = q @ k.transpose(-2, -1) / math.sqrt(self.head_width)\n        forbidden = torch.triu(\n            torch.ones(length, length, dtype=torch.bool, device=x.device),\n            diagonal=1,\n        )\n        scores = scores.masked_fill(forbidden, float(\"-inf\"))\n        weights = torch.softmax(scores, dim=-1)\n        routed = weights @ v\n        routed = routed.transpose(1, 2).reshape(batch, length, width)\n        output = self.project(routed)\n        if return_weights:\n            return output, weights\n        return output\n\n# [2]\ntorch.manual_seed(6050)\ndemo_attention = CausalMultiHeadAttention(width=32, heads=4)\ndemo_x = torch.randn(1, 12, 32)\n_, demo_weights = demo_attention(demo_x, return_weights=True)\n\nfuture = torch.triu(torch.ones(12, 12, dtype=torch.bool), diagonal=1)\n# [3]\nassert demo_weights[0, :, future].max().item() == 0.0\nassert torch.allclose(\n    demo_weights.sum(dim=-1),\n    torch.ones_like(demo_weights.sum(dim=-1)),\n    atol=1e-6,\n)\n```\n:::\n\n\n::::\n\n::: {.cell fig-height='7' fig-width='10' execution_count=6}\n\n::: {.cell-output .cell-output-display}\n![Multi-head attention splits, routes in parallel, concatenates, and projects (top). In the untrained causal heads below, every query row sums to one and every future key has exactly zero weight.](14-self-attention-transformer_files/figure-pdf/fig-causal-multihead-output-1.pdf){#fig-causal-multihead fig-alt='Top flow diagram sends X through Q-K-V splitting, four parallel attention routes, concatenation, and output projection. Below, four 12-by-12 attention heatmaps have different weights only on and below the diagonal; every upper-triangular future position is dark.'}\n:::\n:::\n\n\n:::: {.plan-code}\n::: {.plan}\n1. Report the causal-mask and normalization audit.\n:::\n\n::: {#causal-multihead-audit-output .cell execution_count=7}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: report the causal-mask and normalization audit\"}\n# [1]\nprint(\"maximum forbidden attention:\", demo_weights[0, :, future].max().item())\nprint(\n    \"maximum row-sum error:\",\n    (demo_weights.sum(dim=-1) - 1).abs().max().item(),\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmaximum forbidden attention: 0.0\nmaximum row-sum error: 1.1920928955078125e-07\n```\n:::\n:::\n\n\n::::\nThe assertions are part of the derivation. A visually plausible triangle can still\nbe transposed, shifted by one, or applied after softmax. Executable shape and\nnormalization checks catch those errors—before training can disguise them.\n\n<!-- /NOVEL -->\n\nThe mask changes visibility, not dense computation. The implementation still\nforms all $n^2$ scores and stores $Bhn^2$ attention weights, alongside roughly\n$Bnd^2$ projection work and $Bndd_{ff}$ work in the FFN. Self-attention shortens\nthe graph path between distant\ntokens to one routing step—but “one step away” is not “constant runtime.”\n@sec-a3-precision-performance returns to this $n^2$ ledger through Roofline analysis\nand FlashAttention's I/O-aware schedule.\n\n## Build a Transformer block\n\nAttention routes information between token positions. A Transformer block needs\ntwo more ingredients—a stable path through depth and a nonlinear computation at\neach position.\n\n### The residual stream\n\n@sec-09-modern-cnns-transfer introduced the residual stream with one durable sentence: every block\nreads the stream and writes a correction back. If a sublayer computes $F(x)$, the\nresidual update is\n\n$$\nx\\leftarrow x+F(x).\n$$\n\nThe identity branch provides a direct route for representations and gradients\nwhile the learned branch proposes a correction. It makes deep optimization more\ntractable—it does not guarantee that gradients can never vanish or explode.\n\nLayer normalization controls each token's feature scale. For one token vector\n$x\\in\\mathbb{R}^{d}$,\n\n$$\n\\mu=\\frac1d\\sum_{k=1}^{d}x_k,\\qquad\n\\sigma^2=\\frac1d\\sum_{k=1}^{d}(x_k-\\mu)^2,\n$$\n\n$$\n\\operatorname{LN}(x)_k\n=\\gamma_k\\frac{x_k-\\mu}{\\sqrt{\\sigma^2+\\epsilon}}+\\beta_k,\n\\qquad \\gamma,\\beta\\in\\mathbb{R}^d.\n$$\n\nThis is Chapter 9's normalization equation applied along a different axis—the same\nequation, different axis. Chapter 9's BatchNorm2d used batch and spatial axes for\neach channel. LayerNorm flips to the feature axis of each token: it computes\nstatistics across the features within one token, without aggregating statistics\nacross other tokens or examples. Its calculation is the same at training and\nevaluation time. Before the learned $\\gamma$ and $\\beta$, the vector is\napproximately zero mean and unit variance. After applying them, that claim need\nnot remain true.\n\n:::: {.plan-code}\n::: {.plan}\n1. Prepare the inputs and fixed settings for the example.\n2. Verify LayerNorm centers and scales each token independently.\n:::\n\n::: {#layernorm-axis-audit .cell execution_count=8}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: verify LayerNorm centers and scales each token independently\"}\n# [1]\naudit = torch.tensor([\n    [[1.0, 3.0, 5.0, 7.0], [40.0, 50.0, 60.0, 70.0]],\n    [[-3.0, 1.0, 5.0, 9.0], [2.0, 2.5, 3.0, 3.5]],\n])\nnormalized = nn.functional.layer_norm(audit, (4,))\ntoken_means = normalized.mean(dim=-1)\ntoken_vars = normalized.var(dim=-1, unbiased=False)\n# [2]\nassert token_means.abs().max().item() < 1e-6\nassert (token_vars - 1).abs().max().item() < 1e-4\n```\n:::\n\n\n::::\n\n::: {.cell fig-height='4.2' fig-width='10' execution_count=9}\n\n::: {.cell-output .cell-output-display}\n![A pre-LayerNorm Transformer block as two read–compute–write stages. The residual stream carries each token directly across both additions while LayerNorm feeds a normalized view to causal multi-head attention and then the position-wise FFN. The audit at right shows what LayerNorm changes: four tokens with different offsets and scales become the same centered, unit-variance profile before the learned affine rescaling.](14-self-attention-transformer_files/figure-pdf/fig-transformer-block-output-1.pdf){#fig-transformer-block fig-alt='Three-panel figure. The left panel is a horizontal pre-LayerNorm Transformer block: a residual stream bypasses a LayerNorm-to-causal-attention branch and adds its correction, then bypasses a LayerNorm-to-FFN branch and adds again. The middle panel shows four raw token feature profiles at different offsets and scales. The right panel shows those four profiles coinciding after independent normalization.'}\n:::\n:::\n\n\n:::: {.plan-code}\n::: {.plan}\n1. Report the per-token LayerNorm audit.\n:::\n\n::: {#layernorm-axis-audit-output .cell execution_count=10}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: report the per-token LayerNorm audit\"}\n# [1]\nprint(\"maximum absolute token mean:\", token_means.abs().max().item())\nprint(\"maximum token variance error:\", (token_vars - 1).abs().max().item())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmaximum absolute token mean: 0.0\nmaximum token variance error: 3.2067298889160156e-05\n```\n:::\n:::\n\n\n::::\nThe original Transformer normalized *after* each residual addition:\n\n$$\nx\\leftarrow\\operatorname{LN}(x+\\operatorname{MHA}(x)),\\qquad\nx\\leftarrow\\operatorname{LN}(x+\\operatorname{FFN}(x)).\n$$\n\nOur small experiment uses the now-common pre-LayerNorm arrangement:\n\n$$\n\\begin{aligned}\nx&\\leftarrow x+\\operatorname{MHA}(\\operatorname{LN}(x)),\\\\\nx&\\leftarrow x+\\operatorname{FFN}(\\operatorname{LN}(x)).\n\\end{aligned}\n$$\n\nPre-LayerNorm leaves an unobstructed identity route along the residual stream and\noften improves optimization at initialization. This is an implementation choice,\nnot a universal theorem that post-LayerNorm fails or that pre-LayerNorm eliminates\nevery need for careful optimization.\n\n**RMSNorm** keeps the scale control but omits mean subtraction:\n\n$$\n\\operatorname{RMSNorm}(\\vect{x})\n=\\vect{g}\\odot\n\\frac{\\vect{x}}\n{\\sqrt{\\frac{1}{d}\\sum_{j=1}^{d}x_j^2+\\epsilon}}.\n$$\n\nIt normalizes each token by its root-mean-square magnitude and retains a learned\nper-feature scale $\\vect{g}$. This removes one statistic from the computation; it\ndoes not imply universal superiority over LayerNorm. Architecture, optimizer, dtype,\nand scale still determine the observed trade-off.\n\n### The position-wise feedforward network\n\nAfter tokens communicate through attention, the same two-layer network processes\neach position independently:\n\n$$\n\\operatorname{FFN}(z)\n=W_2\\operatorname{ReLU}(W_1z+b_1)+b_2.\n$$\n\nHere $W_1\\in\\mathbb{R}^{d_{ff}\\times d}$,\n$b_1\\in\\mathbb{R}^{d_{ff}}$, $W_2\\in\\mathbb{R}^{d\\times d_{ff}}$, and\n$b_2\\in\\mathbb{R}^{d}$.\n\nIf $w_{1j}^\\top$ is row $j$ of $W_1$ and $v_j$ is column $j$ of $W_2$, the same\noperation can be written\n\n$$\n\\operatorname{FFN}(z)\n=\\sum_j [w_{1j}^\\top z+b_{1j}]_+\\,v_j+b_2.\n$$\n\nThis form motivates an associative-memory lens. Each first-layer row tests whether\nthe current representation lies in a learned half-space; its positive activation\ncontrols how much of the corresponding output vector is written. Empirically,\nTransformer FFNs can behave like key-value memories. The analogy has limits—the\nselectors are half-spaces rather than point anchors, the gates do not sum to one,\nand the operation is not literally kernel regression or a normalized lookup.\n\nThe complete block therefore alternates two kinds of computation:\n\n1. causal multi-head attention moves information *between positions*; and\n2. the FFN transforms information *within each position*.\n\nResidual additions keep both results in one shared stream—a common workspace that\nsurvives the full stack.\n\n## From the original Transformer to this experiment\n\nThe 2017 Transformer was an encoder–decoder system for translation. Its encoder\nstack uses unmasked self-attention to build a representation of the source\nsentence. Its decoder stack uses causal self-attention over the partial target,\nthen cross-attention whose queries come from the decoder while keys and values\ncome from the encoder. In compact form:\n\n$$\n\\begin{array}{lll}\n\\text{encoder:}&X_s\\to\\text{self-attention}\\to\\text{FFN},\\\\\n\\text{decoder:}&X_t\\to\\text{causal self-attention}\n\\to\\text{cross-attention to encoder}\\to\\text{FFN}.\n\\end{array}\n$$\n\nThe book-corpus task predicts the next character from earlier characters. It has no\nseparate source sentence, so the encoder and cross-attention are unnecessary. What\nremains—a **decoder-only causal Transformer**—has token plus position embeddings,\ntwo pre-LayerNorm blocks, a final LayerNorm, and a linear map to vocabulary logits.\nThe logits go directly to cross-entropy. Softmax belongs inside attention and,\nlater, inside sampling—not between the output layer and the loss.\n\n<!-- NOVEL: needs sign-off - exact-schedule book-corpus rematch, positional ablation,\n     learned-map audit, and deterministic samples. -->\n\n## The book reads itself, again\n\nA fair rematch begins by preserving what can be preserved. Chapter 10 trained on\na committed snapshot of Chapters 1–9 with executable code cells and HTML comments\nremoved: 148,594 characters,\nvocabulary 104, a contiguous 90/10 split, 100-character windows, batch size 64, and\n2,501 updates with Adam at learning rate 0.002 and gradient clipping at norm 1. The\nsnapshot keeps later copyedits from moving the benchmark. The held-out metric resets\nstate at each fixed window.\n\nThe two architectures cannot be made identical—one has recurrent gates and the\nother has attention blocks—but their opportunity to see training targets can be.\nThe code below reconstructs Chapter 10's exact random-window schedule, then gives\nboth Transformer variants the same initial weights and all 16,006,400 target\ncharacters in the same order. The held-out tail has been inspected repeatedly\nacross chapters, so treat it as a stable validation benchmark—not a newly sealed\ntest set.\n\n\n\n:::: {.plan-code .plan-code-wide}\n::: {.plan}\n1. Implement the tiny Transformer — positions, block, model.\n:::\n\n::: {#transformer-kernel .cell execution_count=12}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: the tiny Transformer — positions, block, model\"}\n# [1]\ndef sinusoidal_positions(length: int, width: int) -> torch.Tensor:\n    position = torch.arange(length, dtype=torch.float32).unsqueeze(1)\n    frequency = torch.exp(\n        torch.arange(0, width, 2, dtype=torch.float32)\n        * (-math.log(10_000.0) / width)\n    )\n    table = torch.zeros(length, width)\n    table[:, 0::2] = torch.sin(position * frequency)\n    table[:, 1::2] = torch.cos(position * frequency)\n    return table\n\nclass TransformerBlock(nn.Module):\n    def __init__(self) -> None:\n        super().__init__()\n        self.norm1 = nn.LayerNorm(WIDTH)\n        self.attention = CausalMultiHeadAttention(WIDTH, HEADS)\n        self.norm2 = nn.LayerNorm(WIDTH)\n        self.ff = nn.Sequential(\n            nn.Linear(WIDTH, FF_WIDTH),\n            nn.ReLU(),\n            nn.Linear(FF_WIDTH, WIDTH),\n        )\n\n    def forward(self, x: torch.Tensor, return_weights: bool = False):\n        if return_weights:\n            attended, weights = self.attention(self.norm1(x), True)\n            x = x + attended\n            return x + self.ff(self.norm2(x)), weights\n        x = x + self.attention(self.norm1(x))\n        return x + self.ff(self.norm2(x))\n\nclass TinyTransformerLM(nn.Module):\n    def __init__(self, vocab: int, positions: bool) -> None:\n        super().__init__()\n        self.positions = positions\n        self.token_embedding = nn.Embedding(vocab, WIDTH)\n        nn.init.normal_(\n            self.token_embedding.weight,\n            mean=0.0,\n            std=1 / math.sqrt(WIDTH),\n        )\n        self.blocks = nn.ModuleList(\n            [TransformerBlock() for _ in range(BLOCKS)]\n        )\n        self.final_norm = nn.LayerNorm(WIDTH)\n        self.output = nn.Linear(WIDTH, vocab)\n        self.register_buffer(\n            \"position_table\",\n            sinusoidal_positions(CONTEXT, WIDTH),\n            persistent=False,\n        )\n\n    def forward(self, tokens: torch.Tensor, return_weights: bool = False):\n        length = tokens.shape[1]\n        x = self.token_embedding(tokens) * math.sqrt(WIDTH)\n        if self.positions:\n            x = x + self.position_table[:length]\n        maps = []\n        for block in self.blocks:\n            if return_weights:\n                x, weights = block(x, True)\n                maps.append(weights)\n            else:\n                x = block(x)\n        logits = self.output(self.final_norm(x))\n        return (logits, maps) if return_weights else logits\n```\n:::\n\n\n::::\nThe paired protocol is worth printing in full — it *is* the experimental design:\n\n:::: {.plan-code .plan-code-wide}\n::: {.plan}\n1. Prepare the inputs and fixed settings for the example.\n2. Implement the paired protocol — shared schedule, identical initial tensors.\n:::\n\n::: {#transformer-protocol .cell execution_count=13}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: the paired protocol — shared schedule, identical initial tensors\"}\n# Reconstruct the random-number state immediately after Chapter 10 created\n# its LSTM, then draw that chapter's complete minibatch-start schedule.\n# [1]\ntorch.manual_seed(SEED)\n_ = HistoricalCharLSTM(len(chars))\nschedule_generator = torch.Generator()\nschedule_generator.set_state(torch.random.get_rng_state())\nstarts = torch.randint(\n    0,\n    len(train_data) - CONTEXT - 1,\n    (UPDATES, BATCH),\n    generator=schedule_generator,\n)\n\n# The two Transformer variants begin with exactly the same tensors.\ntorch.manual_seed(SEED)\nbase_model = TinyTransformerLM(len(chars), positions=True)\ninitial_state = {\n    name: value.clone() for name, value in base_model.state_dict().items()\n}\ninitial_hash = state_digest(initial_state)\nschedule_hash = hashlib.sha256(starts.numpy().tobytes()).hexdigest()\n\n# [2]\nprint(f\"corpus: 9 chapters, {len(text):,} characters, vocab {len(chars)}\")\nprint(\n    f\"deterministic split: {len(train_data):,} train / \"\n    f\"{len(valid_data):,} held out\"\n)\nprint(\n    f\"Transformer parameters: \"\n    f\"{sum(parameter.numel() for parameter in base_model.parameters()):,}\"\n)\nprint(f\"first eight window starts: {starts[0, :8].tolist()}\")\nprint(f\"initial tensors: {initial_hash[:12]}…\")\nprint(f\"window schedule: {schedule_hash[:12]}…\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncorpus: 9 chapters, 148,594 characters, vocab 104\ndeterministic split: 133,734 train / 14,860 held out\nTransformer parameters: 132,488\nfirst eight window starts: [24368, 94128, 60074, 121547, 118001, 4396, 17011, 8495]\ninitial tensors: 4d2f7f434cb5…\nwindow schedule: e470a091bd50…\n```\n:::\n:::\n\n\n::::\nThe model has 132,488 trainable parameters—736 fewer than Chapter 10's 133,224.\nThat difference is only 0.55%—close enough to remove model size as an easy\nexplanation. The model width is 84, split into four 21-dimensional heads; each of\nthe two FFNs expands to 168 features. Token embeddings are initialized with\ncoordinate standard deviation $1/\\sqrt d$ before the displayed $\\sqrt d$ scaling,\nso their coordinates and the sinusoidal coordinates begin on comparable scales.\n`ModuleList` registers the two repeated blocks with the model. The nonpersistent\nposition buffer moves with the model but is neither optimized nor included in the\nstate-dictionary fingerprint; its contents follow deterministically from the\ndisplayed formula. There is no dropout, so resetting the trainable/state-dictionary\ntensors and window schedule makes the positional ablation exact and repeatable.\n\n::: {.callout-tip}\n## One seed call was not enough\n\nCalling the same random seed before both training runs would not, by itself, prove\nthat they saw the same windows. Model construction consumes random numbers, and\ndifferent construction paths can silently shift every later draw. The experiment\nprecomputes the full start-index tensor with an explicit generator and copies one\nsaved initialization into both models. It also prints fingerprints for both\nartifacts.\n:::\n\nTraining and evaluation are Chapter 10's canonical listings, imported. The\nsignature of the imported trainer, for reference:\n\n:::: {.plan-code}\n::: {.plan}\n1. Reuse the shared trainer through its explicit model, data, schedule, and optimization interface.\n:::\n\n```{.python book-include=\"code/dlbook/training.py\" start-line=11 end-line=25}\n```\n::::\n\n*… body exactly as Listing 10.1 — this chapter prints only what it changes.*\n\n:::: {.plan-code .plan-code-wide}\n::: {.plan}\n1. Chapter 10's trainer, imported — only the deltas printed.\n:::\n\n::: {#transformer-training-function .cell execution_count=14}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: Chapter 10's trainer, imported — only the deltas printed\"}\nfrom dlbook.training import fit_next_token      # Listing 10.1, Ch. 10\nfrom dlbook.evaluation import fixed_window_loss  # Listing 10.2, Ch. 10\n\n# [1]\ndef train_transformer(\n    positions: bool,\n) -> tuple[nn.Module, list[tuple[int, float]]]:\n    net = TinyTransformerLM(len(chars), positions=positions)\n    net.load_state_dict(initial_state, strict=True)  # paired start: same tensors\n    assert state_digest(net.state_dict()) == initial_hash\n    return fit_next_token(\n        net, train_data, vocab=len(chars),\n        schedule=starts,                 # minibatch order is protocol, not chance\n        log_every=250, log_decimals=4,\n    )\n\n@torch.no_grad()\ndef transformer_sample(\n    net: nn.Module,\n    prompt: str,\n    n: int = 300,\n    temperature: float = 0.8,\n) -> str:\n    net.eval()\n    generator = torch.Generator().manual_seed(1_406_050)\n    tokens = [stoi.get(char, 0) for char in prompt]\n    for _ in range(n):\n        context = torch.tensor(tokens[-CONTEXT:]).unsqueeze(0)\n        probabilities = F.softmax(\n            net(context)[0, -1] / temperature, dim=-1\n        )\n        next_token = torch.multinomial(\n            probabilities, 1, generator=generator\n        ).item()\n        tokens.append(next_token)\n    return \"\".join(chars[index] for index in tokens)\n```\n:::\n\n\n::::\nThe training function is defined once, then called in separate cells so each\nsubstantial run stays within the chapter's execution budget.\n\n:::: {.plan-code}\n::: {.plan}\n1. Train the positional Transformer.\n2. Report or visualize the measured result.\n:::\n\n::: {#train-transformer-positions .cell execution_count=15}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: train the positional Transformer\"}\n# [1]\nposition_model, position_curve = train_transformer(positions=True)\nposition_train_loss = fixed_window_loss(position_model, train_data, vocab=len(chars))\nposition_valid_loss = fixed_window_loss(position_model, valid_data, vocab=len(chars))\n# [2]\nprint(f\"fixed-window train loss: {position_train_loss:.4f}\")\nprint(f\"fixed-window held-out loss: {position_valid_loss:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nstep    0   loss 4.7550\nstep  250   loss 2.1875\nstep  500   loss 1.7175\nstep  750   loss 1.5115\nstep 1000   loss 1.3890\nstep 1250   loss 1.3568\nstep 1500   loss 1.2856\nstep 1750   loss 1.2261\nstep 2000   loss 1.1663\nstep 2250   loss 1.1557\nstep 2500   loss 1.1101\nfixed-window train loss: 1.1157\nfixed-window held-out loss: 1.9306\n```\n:::\n:::\n\n\n::::\n:::: {.plan-code}\n::: {.plan}\n1. Repeat with position removed and everything else fixed.\n2. Report or visualize the measured result.\n:::\n\n::: {#train-transformer-no-positions .cell execution_count=16}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: repeat with position removed and everything else fixed\"}\n# [1]\nno_position_model, no_position_curve = train_transformer(positions=False)\nno_position_train_loss = fixed_window_loss(no_position_model, train_data, vocab=len(chars))\nno_position_valid_loss = fixed_window_loss(no_position_model, valid_data, vocab=len(chars))\n# [2]\nprint(f\"fixed-window train loss: {no_position_train_loss:.4f}\")\nprint(f\"fixed-window held-out loss: {no_position_valid_loss:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nstep    0   loss 4.7289\nstep  250   loss 2.4946\nstep  500   loss 2.3608\nstep  750   loss 2.2417\nstep 1000   loss 2.2277\nstep 1250   loss 2.1510\nstep 1500   loss 2.0745\nstep 1750   loss 1.9970\nstep 2000   loss 1.9607\nstep 2250   loss 1.9131\nstep 2500   loss 1.8467\nfixed-window train loss: 1.8622\nfixed-window held-out loss: 2.3494\n```\n:::\n:::\n\n\n::::\n:::: {.plan-code .plan-code-wide}\n::: {.plan}\n1. Prepare the inputs and fixed settings for the example.\n2. Report the positional improvement and LSTM gap.\n:::\n\n::: {#book-corpus-rematch-audit .cell execution_count=17}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: audit the matched book-corpus rematch\"}\n# [1]\nlstm_valid_loss = 1.888110429\n\n# [2]\nimprovement = no_position_valid_loss - position_valid_loss\nrelative = improvement / no_position_valid_loss\nlstm_gap = position_valid_loss - lstm_valid_loss\nprint(\n    f\"position improvement: {improvement:.4f} loss \"\n    f\"({relative:.1%} relative)\"\n)\nprint(f\"positional Transformer minus LSTM: {lstm_gap:.4f} loss\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nposition improvement: 0.4188 loss (17.8% relative)\npositional Transformer minus LSTM: 0.0425 loss\n```\n:::\n:::\n\n\n::::\n\n::: {.cell fig-height='4' fig-width='10' execution_count=18}\n\n::: {.cell-output .cell-output-display}\n![Matched training curves (left) and fixed-window held-out loss (right). Position helps in this seed, while the Chapter 10 LSTM remains the strongest small model.](14-self-attention-transformer_files/figure-pdf/fig-book-corpus-rematch-output-1.pdf){#fig-book-corpus-rematch fig-alt='Two-panel matched comparison. Training losses start together near 4.7, then the positional Transformer falls steadily to about 1.1 while the no-position model ends near 1.85. Held-out bars rank the Chapter 10 LSTM lowest at 1.8881, the positional Transformer at 1.9190, and the no-position Transformer highest at 2.3405.'}\n:::\n:::\n\n\nThe positional model finishes at 1.1132 on a deterministic pass over the training\ntext and 1.9190 on the held-out tail. Removing position raises those values to\n1.8672 and 2.3405. Position lowers\nheld-out loss by 0.4214, or 18.0% relative to the no-position variant.\n\n::: {.callout-warning}\n## What this matched run can—and cannot—show\n\nThe causal mask already gives a position some weak structural information: row\n$i$ sees a prefix of length $i+1$, and stacked layers can propagate clues from\nthose nested prefixes. That is why the no-position model does better than a purely\norderless caricature might suggest—fixed sinusoidal encoding still produces a\nlarge improvement in this run.\n\nBut Chapter 10's LSTM remains ahead by 0.0309 held-out loss, or 1.64%. At 100\ncharacters of context and roughly 133,000 parameters, the LSTM wins this regime.\nThis comparison matches corpus, parameter scale, updates,\nminibatch order, optimizer, clipping, and evaluation. It does not match internal\narchitecture—or promise that either model has been tuned to its own optimum.\nWe did not repeat the comparison across initialization seeds, so the 0.4214 gap is\na controlled case study, not an estimate of an average effect.\n:::\n\n### What did the heads route?\n\nAn attention map records routing weights, not reasons, confidence, or a guaranteed\nexplanation of a prediction. Still, inspecting real learned maps can verify the\nmask and reveal the kinds of patterns a trained model happened to use. The next\ncell sends the prompt *The gradient* through the positional model and plots the\nsecond block's four heads.\n\n:::: {.plan-code .plan-code-wide}\n::: {.plan}\n1. Prepare the inputs and fixed settings for the example.\n2. Audit causal masking and row normalization.\n:::\n\n::: {#learned-attention-audit .cell execution_count=19}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: audit learned causal attention maps\"}\n# [1]\nprompt = \"The gradient \"\nprompt_tokens = torch.tensor([[stoi[char] for char in prompt]])\nposition_model.eval()\nwith torch.no_grad():\n    _, learned_maps = position_model(prompt_tokens, return_weights=True)\nlearned = learned_maps[-1][0]\n\nfuture = torch.triu(\n    torch.ones(len(prompt), len(prompt), dtype=torch.bool), diagonal=1\n)\nassert learned[:, future].max().item() == 0.0\nassert torch.allclose(\n    learned.sum(dim=-1),\n    torch.ones_like(learned.sum(dim=-1)),\n    atol=1e-6,\n)\n\n# [2]\nprint(\"maximum future attention:\", learned[:, future].max().item())\nprint(\n    \"maximum row-sum error:\",\n    (learned.sum(dim=-1) - 1).abs().max().item(),\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmaximum future attention: 0.0\nmaximum row-sum error: 1.1920928955078125e-07\n```\n:::\n:::\n\n\n::::\n\n::: {.cell fig-height='6' fig-width='10' execution_count=20}\n\n::: {.cell-output .cell-output-display}\n![Learned attention weights in the second block for the prompt “The gradient ”. The maps are real routing distributions, not explanations or named head roles.](14-self-attention-transformer_files/figure-pdf/fig-learned-attention-output-1.pdf){#fig-learned-attention fig-alt='Four lower-triangular heatmaps for the second block\\'s four heads on the character prompt \\'The gradient\\' with spaces shown as dots. Each query row attends only to itself and earlier characters, but the heads distribute their bright high-weight cells differently: some follow local diagonals while others concentrate on a few earlier columns.'}\n:::\n:::\n\n\nThe maps obey the contract exactly: no future key receives weight and every row\nsums to one. The heads also differ from one another, but naming one “the previous\ncharacter head” or another “the word head” from this single prompt would outrun\nthe evidence. Attention shows where values were mixed—the rest of the network can\ntransform, cancel, or ignore what was retrieved.\n\n### Listen, but do not grade by fluency\n\nBoth Transformer variants can now generate by repeatedly truncating to the most\nrecent 100 characters, predicting a distribution for the next one, sampling, and\nfeeding the result back. Unlike Chapter 10's LSTM, this simple implementation does\nnot carry a recurrent state; it recomputes the current context on every step.\n\n<!-- NOVEL: needs sign-off - concise generation bridge requested in the course review. -->\n::: {.callout-tip}\n## Practice bridge (non-examinable): decoding is another model choice\n\nFor next-token logits $z_i$, **temperature** applies Chapter 2's softmax dial\n(@sec-02-logistic-softmax):\n\n$$\np_i(T)=\\frac{\\exp(z_i/T)}{\\sum_j\\exp(z_j/T)},\\qquad T>0.\n$$\n\nLower $T$ concentrates probability; higher $T$ flattens it. **Top-$k$ sampling**\nkeeps the $k$ largest logits, sets the rest to negative infinity, then renormalizes.\n**Nucleus (top-$p$) sampling** first sorts the model probabilities and keeps the\nsmallest prefix whose cumulative mass reaches $p$, then renormalizes. The former fixes\na candidate count; the latter lets that count adapt to the distribution's shape.\nNeither changes the trained weights, and neither guarantees a better sample.\n\nFor evaluation, if $L$ is mean token negative log-likelihood in natural-log units,\n**perplexity** is $\\exp(L)$. It is an exponentiated loss, not a fluency score. Compare\nit only under the same tokenization, data, and averaging contract.\n:::\n<!-- /NOVEL -->\n\n:::: {.plan-code}\n::: {.plan}\n1. Deterministic samples from both Transformer variants.\n:::\n\n::: {#transformer-samples .cell execution_count=21}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: deterministic samples from both Transformer variants\"}\nprint(\"WITH POSITION\\n\")\n# [1]\nprint(transformer_sample(position_model, \"The gradient \"))\nprint(\"\\n\\nWITHOUT POSITION\\n\")\nprint(transformer_sample(no_position_model, \"The gradient \"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nWITH POSITION\n\nThe gradient choweven it on and validation for equivariant already of calc\n   nuisan one-layer reade-deflane we will have comparable); only the bias boundariest scales and loss long — it training to descens and need gradient chapter. The complex\npattializs the two a rules of this into a biwas a **multipliest** w\n\n\nWITHOUT POSITION\n\nThe gradient imodes fing on indevatin to ritwe? Cofiter e. Thrivofforical\n\nul ffiptwerdgit) tht   dea  the the che ift low t Xaysherd unaperie bund n forme.\n\nThe matrs chagule mownte it the of os to derndescate ive. Whis thing are is the comof ***sthe* is it ist fither $\\rongheal 5$ is ay\n    a *Aneverissist bow\n```\n:::\n:::\n\n\n::::\nThe positional sample has the book's punctuation, fragments of mathematical\nvocabulary, and stretches that resemble prose. It still loses its argument. The\nno-position sample is visibly rougher. Neither qualitative judgment replaces the\nheld-out loss—a sample is one stochastic path, while the loss evaluates every\nheld-out target under the model's full probability distribution.\n\n<!-- /NOVEL -->\n\n## What the architecture bought\n\nThe rematch is not a referendum on all Transformers—it isolates what this small\none bought and what it paid.\n\n**Direct content routing.** Any earlier visible token can contribute to the next\nrepresentation in one attention sublayer. The recurrent state no longer has to\ncompress the entire past before the current token can consult it.\n\n**Short paths, dense work.** The graph distance between visible tokens is short,\nbut the routing matrix is quadratic in context length. Global access is a\ndifferent tradeoff, not free memory.\n\n**Position becomes a modeling choice.** Convolution and recurrence bake in local\norder. Attention asks the designer to supply position—and decide visibility.\n@sec-15-bert-pretraining will change visibility itself; @sec-16-vit-scaling will\nrevisit what happens\nwhen global routing trades away an image model's locality bias.\n\n**A modular residual stream.** Attention moves information, the FFN transforms it,\nand residual additions let both write into a shared representation. LayerNorm\nkeeps each token's feature scale manageable along the way.\n\nThe causal mask is therefore more than an implementation detail. It says which\ninformation a representation is allowed to use. “Visibility is a modeling\ndecision” is the seed this chapter hands forward.\n\nDuring autoregressive generation, exact softmax attention also makes the past a\nsystems object. A **key/value (KV) cache** retains each layer's earlier key and value\nrows so a new query can reuse them instead of recomputing the whole prefix. In the\nregression language of Chapter 12, the KV cache is the nonparametric estimator's\ndataset: one new query still reads a table that grows with $t$, but the earlier rows\ndo not have to be rebuilt. The toy sampler in @sec-14-self-attention-transformer is\nwasteful precisely because it rebuilds that dataset at every step; Appendix C\nseparates caching from FlashAttention's I/O schedule.\n\nThe next interlude holds this regression problem fixed and changes its solver. That is\nwhere the growing table, finite sufficient state, and delta update can be compared\nwithout interrupting the Transformer construction.\n\n\n::: {.callout-note}\n## Check yourself\n\nClose the book for one minute and rebuild the Transformer block.\n\n- Why is bare self-attention permutation equivariant?\n- Which three paths write into the residual stream?\n- What changes when a causal mask restricts visibility?\n:::\n\n## Okay, so — the Transformer routes, then computes\n\n1. **Self-attention reuses Chapter 13's operator within one sequence.** $Q$, $K$,\n   and $V$ all come from $X$; one learned comparison rule is shared over every\n   ordered pair. Training positions can be evaluated together, while\n   autoregressive generation remains sequential.\n2. **Bare attention is permutation equivariant, not invariant.**\n   $\\operatorname{SA}(PX)=P\\operatorname{SA}(X)$. Sinusoidal clocks repay Chapter\n   8's position debt, and their sine/cosine pairs turn relative shifts into\n   rotations.\n3. **Multi-head attention is shape discipline.** Split\n   $(B,n,d)\\to(B,h,n,d_h)$, divide scores by $\\sqrt{d_h}$, form\n   $(B,h,n,n)$ routing weights, concatenate, and project. At fixed $d$, the four\n   leading projections remain about $4d^2$ parameters.\n4. **The causal mask defines visibility.** Future scores become negative infinity\n   before softmax. The dense operator still performs quadratic work; the mask does\n   not make the forbidden half computationally disappear.\n5. **The block alternates routing and computation.** Multi-head attention mixes\n   positions, the FFN transforms each position, and both write corrections into\n   Chapter 9's residual stream. LayerNorm is the same normalization equation over\n   a token's feature axis.\n6. **Position wins this seed's controlled ablation.** It lowers held-out loss from\n   2.3405 to 1.9190. **The LSTM narrowly wins the small-model rematch**, 1.8881\n   versus 1.9190.\n   Architecture changes inductive bias; it does not guarantee victory in every\n   data and scale regime.\n## Sources and further reading {.unnumbered}\n\n- [Vaswani et al., *Attention Is All You Need*](https://papers.nips.cc/paper_files/paper/2017/hash/3f5ee243547dee91fbd053c1c4a845aa-Abstract.html): multi-head attention, sinusoidal position, and the original post-LayerNorm encoder–decoder.\n- [Su et al., *RoFormer: Enhanced Transformer with Rotary Position Embedding*](https://arxiv.org/abs/2104.09864): rotates queries and keys so their positional interaction is expressed through relative offset.\n- [Ba, Kiros, and Hinton, *Layer Normalization*](https://arxiv.org/abs/1607.06450): normalization within one example and identical train/evaluation computation.\n- [Zhang and Sennrich, *Root Mean Square Layer Normalization*](https://proceedings.neurips.cc/paper/2019/hash/1e8a19426224ca89e83cef47f1e7f53b-Abstract.html): RMSNorm's scale-only normalization and empirical study.\n- [Xiong et al., *On Layer Normalization in the Transformer Architecture*](https://proceedings.mlr.press/v119/xiong20b.html): a qualified comparison of pre- and post-LayerNorm optimization.\n- [Geva et al., *Transformer Feed-Forward Layers Are Key-Value Memories*](https://aclanthology.org/2021.emnlp-main.446/): empirical evidence behind the associative-memory interpretation of FFNs.\n- [Jain and Wallace, *Attention Is Not Explanation*](https://aclanthology.org/N19-1357/): an important limit on reading attention maps as explanations.\n- [Holtzman et al., *The Curious Case of Neural Text Degeneration*](https://arxiv.org/abs/1904.09751): nucleus sampling and the distinction between likely continuations and useful generation behavior.\n\n## Exercises {.unnumbered}\n\n1. **(Pencil.)** Starting from $Q'=PQ$, $K'=PK$, and $V'=PV$, prove each step of\n   $\\operatorname{SA}(PX)=P\\operatorname{SA}(X)$. Then show that mean-pooling the\n   token outputs produces a permutation-*invariant* sequence representation.\n2. **(Pencil.)** For width $d=512$ and $h=8$, write every tensor shape in\n   multi-head attention for $B=32$ and $n=100$. Count the weights in\n   $W_Q,W_K,W_V,W_O$. Repeat for $h=16$ and explain which dimensions change while\n   the leading parameter count does not.\n3. **(Code.)** Deliberately transpose the causal mask in\n   @fig-causal-multihead, then design an assertion that identifies the first\n   leaked query-key pair. Next set forbidden probabilities to zero *after*\n   softmax and measure the row-sum error.\n4. **(Code.)** Replace the fixed sinusoidal table with a learned\n   $\\text{Embedding}(100,d)$ while preserving the exact initialization and window\n   schedule protocol. Compare held-out loss. Then extend the sinusoidal buffer by\n   evaluating its formula beyond position 99, and propose an explicit extension\n   rule for the learned table before testing either model on a longer context.\n   Which design has a natural extension, and which has to invent one?\n5. **(Code.)** Aggregate learned attention by relative offset\n   across the held-out tail rather than naming heads from one prompt. Report a\n   distribution for every head and block. Then perturb the highest-weight key's\n   value vector and measure the logit change. Explain why routing weight and causal\n   influence need not rank tokens identically.\n\n",
    "supporting": [
      "14-self-attention-transformer_files/figure-pdf"
    ],
    "filters": []
  }
}
