{
  "hash": "3e3ddc88682507d0819261f8d82a80c9",
  "result": {
    "engine": "jupyter",
    "markdown": "# Sequences and Recurrence {#sec-10-sequences-rnn}\n\n<!-- lecture-source: m07_lecture-7-recurrent-neural-networks_qyU35PKg_NE.txt,\n     m07_lecture-7-2-recurrent-neural-networks-part-2__2NGDmVNUrM.txt,\n     [coding]_m07_lecture-7-3-recurrent-neural-networks-part-3_Az0K6fyf-X4.txt\n     (spine via ds6050_07_rnn/MODULE_NOTES.md)\n     seeds: sources/7.1-RNN-v3.tex (§Naive/Shared-weight RNN, §VEGP, §Truncated BPTT,\n            §From RNN to LSTM: design-by-constraints, §Case Study long-term\n            dependency, §GRU)\n     historical bridge: machine-local course seed\n                        LaTeX/Module 8,9-Transformer/8.L.word2vec.tex\n                        (static-to-contextual framing only; no implementation ported)\n     harvested bridge: @sec-interlude-autoencoders restores Module 6's intended\n                       PCA -> learnable/nonlinear autoencoder -> fixed-code limit\n                       -> recurrence sequence.\n     2026 classroom transcripts (author-supplied, auto-generated captions):\n            DL7.1 RNN (AE limits -> per-step f_t -> shared f, BPTT, clipping,\n            random versus fixed truncation), DL7.2 LSTM (conveyor belt and\n            valves, GRU), DL7.3 Coding RNN and LSTM from scratch (masked update,\n            orthogonal W_hh, fused LSTM affine, forget bias, clip-rate contrast,\n            IMDb many-to-one); requirements list, GRU keep-bias ladder, and\n            Exercises 6-8 follow the author's 2026-09-27 revision brief. -->\n\nThe autoencoders of @sec-interlude-autoencoders encode an input of one fixed size in a\nsingle pass. When a sequence grows by one element, they have no operation that updates\nthe code already computed. In this chapter we learn such an operation: a rule that\ncombines a fixed-width summary of the elements seen so far with the next element to give\nthe new summary.\n\nText, audio, and sensor measurements are sequences: ordered lists of elements whose\nlength varies from one example to the next. When the elements are symbols from a fixed\nset, such as the characters or words of a text, each element is called a **token**. For\nthe streaming models developed in this chapter, we use six design goals to compare\npossible architectures:\n\n1. **Any length.** Accept a sequence of unknown length, with no maximum length\n   imposed by the architecture. Memory and compute still bound what can be processed.\n2. **Order.** Allow the representation to distinguish the\n   same elements in different orders. The sentences \"the dog bit the man\" and \"the man\n   bit the dog\" contain the same words but report different events, so a representation\n   that ignores word order cannot separate them.\n3. **Streaming.** Update as each element arrives, so that an output for the elements seen\n   so far is always available.\n4. **Parameters independent of length.** The rule that reads position 17 should be\n   the rule that reads position 18, so a longer sequence costs no new parameters.\n5. **Reach.** Let the output at the current step depend on inputs arbitrarily far back,\n   not only on the most recent ones. In other words, the architecture sets no limit on the\n   model's **context length**, the number of past steps whose inputs enter the computation\n   of the current output. That an early input enters the computation does not by itself\n   ensure that its information is retained or that the dependency can be learned.\n6. **Trainable reach.** Make such a dependency learnable. If the correct output at the\n   current step depends on an input many steps back, the gradient of the loss must keep a\n   usable size as backpropagation carries it back across those steps to the early input:\n   if it shrinks to nearly zero, the parameter updates carry almost no information about\n   the dependency, and the reach exists only on paper.\n\nThe interlude's one-shot autoencoder fails the first and third outright: it needs a\nmaximum length, and it cannot finish before the last element arrives.\nRecurrence asks us to make the carried summary learnable: rather than compressing\nonce, the model learns how to revise its memory after each new element.\n\nFour earlier tools do most of the work in this chapter: the kernel shared across space\nin @sec-07-filters-convolution and @sec-08-cnn, which becomes one rule shared across\ntime; the product of Jacobians that vanished down deep networks in\n@sec-05-backpropagation, now measured across time; the softmax and the sigmoid of\n@sec-02-logistic-softmax, which become a distribution over the next character and\nmultiplicative factors that control what a recurrent state keeps; and the additive form\nof the residual connection of @sec-09-modern-cnns-transfer, which a recurrent\narchitecture applies along the sequence.\n\n## Stretching the old toolkit\n\n**A window.** We predict the next element $\\vect{x}_{t+1}$ from the last $k$,\n$\\vect{x}_{t-k+1}, \\dots, \\vect{x}_t$, by sliding a width-$k$ window along the sequence\nand feeding each snapshot to an MLP. This is autoregression, and the\n*sliding* is a one-dimensional convolution: locality, transplanted from space to time. Windows are\nuseful (they power real forecasting systems), but they inherit locality's blind\nspot: anything older than the last $k$ elements lies outside the window and cannot affect\nthe prediction. The window's context length is therefore $k$, and no fixed $k$ covers every\ndependency, as in the sentence \"The company whose first-day price we recorded back in\nJanuary finally ...\". In the list's terms, the window meets the first four goals and fails\nthe fifth, and buying more reach costs parameters.\n\n**A function per timestep.** Next we let the model change over time: we learn $f_1$ for\nstep one, $f_2$ for step two, and so on, and each passes a summary forward,\n$\\vect{h}_t = f_t(\\vect{h}_{t-1}, \\vect{x}_t)$. The parameter count now\ngrows with sequence *length*; a length-500 essay needs 500 learned functions, and\nno function exists for a position beyond the longest sequence seen in training. The\nfunctions at positions 17 and 18 have separate parameters, so a pattern learned at one\nposition must be learned again at the other. It fails the first and fourth goals at once.\n\nImages posed the same problem in space: a separate template for every image position was\nwasteful and brittle, and convolution replaced the templates with one kernel shared across\nspace. The move is the same here: **share the function across time**,\n\n$$\n\\vect{h}_t = f(\\vect{h}_{t-1}, \\vect{x}_t),\n$$ {#eq-recurrence}\n\none learned rule $f$, applied at every step, carrying a running summary\n$\\vect{h}_t$, the **hidden state**, from each step to the next. This is the\nthird weight sharing: across examples, across space, and now across *time*.\nThe rule's output\ncan still depend on position and context through the accumulated\nstate. This is a time-homogeneous update rule, not a claim that\nthe data distribution is stationary. On paper, one shared $f$ meets the first five goals. The\nsixth is a question about gradients, taken up in the rest of this chapter.\n\n::: {.callout-note}\n## The hidden state and the Markov property\n\n$\\vect{h}_t$, the state of the dynamical system that @eq-recurrence defines, is a\nfixed-size vector computed by the transition map $f$ from everything seen so far.\nFeeding it back in gives the computation a property with a classical name, the\n**Markov property**: $\\vect{h}_{t-1}$ and $\\vect{x}_t$ together determine the\nmodel's next update, and earlier inputs affect that update only through\n$\\vect{h}_{t-1}$. This interface permits streaming (process elements as they arrive), any\nsequence length (the loop runs once per element), and, later in this chapter, training\non chopped-up chunks. It is a property of the model's computation. It does not\nestablish that $\\vect{h}_{t-1}$ preserves every aspect of the past needed for optimal\nprediction.\n:::\n\n## A network with a loop\n\nThe simplest choice of $f$ is a one-layer network with the state concatenated in:\na linear map of $(\\vect{h}_{t-1}, \\vect{x}_t)$, squashed by a $\\tanh$:\n\n$$\n\\vect{h}_t \\;=\\; \\tanh\\!\\left(\\matr{W}_{hh}\\,\\vect{h}_{t-1} + \\matr{W}_{xh}\\,\\vect{x}_t + \\vect{b}_h\\right),\n\\qquad\n\\vect{s}_t \\;=\\; \\matr{W}_{hs}\\,\\vect{h}_t + \\vect{b}_s ,\n$$ {#eq-rnn-cell}\n\nthe **vanilla recurrent neural network**. The network has three weight matrices, reused\nat every step whether the sequence has five elements or five thousand.\nThe readout $\\vect{s}_t$ holds the logits, one score per class, and you can\ncollect one at every step (predicting each next character, labeling each word) or\nonly at the end (classifying the whole sequence); both designs appear below.\n\nWe build the loop by hand and verify it against the framework; the two results agree to\nwithin rounding error.\n\n:::: {.plan-code}\n::: {.plan}\n1. Run a seeded `nn.RNN` on 4 random 12-step sequences, then take its weights, summed\n   bias, and a zero start state.\n2. Implement the recurrence, written as the loop it is.\n3. Print the largest absolute difference between `manual` and the `nn.RNN` output\n   `out_ref`.\n:::\n\n::: {#setup-and-manual-rnn .cell execution_count=1}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: the recurrence, written as the loop it is\"}\nimport torch\nimport torch.nn as nn\nimport torch.nn.functional as F\nimport matplotlib.pyplot as plt\ntorch.set_num_threads(4)  # pinned: results depend on the CPU thread count\n\n# [1]\ntorch.manual_seed(6050)\nV, H, T, B = 8, 16, 12, 4                       # vocab, hidden, time, batch\nrnn = nn.RNN(V, H, batch_first=True)\nx = torch.randn(B, T, V)\nout_ref, _ = rnn(x)\n\nW_xh, W_hh = rnn.weight_ih_l0, rnn.weight_hh_l0\nb = rnn.bias_ih_l0 + rnn.bias_hh_l0\nh = torch.zeros(B, H)                            # h_0 = 0, the standard start\nouts = []\n# [2]\nfor t in range(T):                               # the loop IS the architecture\n    h = torch.tanh(x[:, t] @ W_xh.T + h @ W_hh.T + b)\n    outs.append(h)\nmanual = torch.stack(outs, 1)\n# [3]\nprint(f\"manual loop vs. nn.RNN: max |diff| = {(manual - out_ref).abs().max():.1e}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmanual loop vs. nn.RNN: max |diff| = 1.2e-07\n```\n:::\n:::\n\n\n::::\nAn MLP takes input of shape `(batch, features)`; with `batch_first=True`, as in the cell\nabove, `nn.RNN` takes `(batch, time, features)`. The time axis sits between the batch axis\nand the feature axis, and the loop runs over it carrying `h` along.\n\nSentences in one minibatch rarely share a\nlength, so shorter ones are padded at the end to the longest one's length, and the\nloop must not let padding rewrite the memory. A mask $m_t\\in\\{0,1\\}$ per sequence\n(1 for a real element, 0 for padding) keeps the old state on padded steps:\n\n$$\n\\vect{h}_t = m_t\\, f(\\vect{h}_{t-1},\\vect{x}_t) + (1-m_t)\\,\\vect{h}_{t-1}.\n$$ {#eq-masked-update}\n\nEach sequence then ends holding the state of its own last real element, exactly as if\nit had run alone.\n\nUnroll the loop on paper and the RNN is an ordinary\nfeedforward network that happens to be $T$ layers deep with every layer's weights\ntied.\n\n::: {#cell-fig-unrolled-rnn .cell execution_count=2}\n\n::: {.cell-output .cell-output-display}\n![Two drawings of the same machine. Left: one cell whose hidden state loops back into itself. Right: the loop unrolled: a chain of copies of the *same* cell, each consuming one input and passing the state along. Read vertically it is an ordinary feedforward network; read horizontally it is a network as deep as the sequence is long, with every layer's weights tied.](10-sequences-rnn_files/figure-html/fig-unrolled-rnn-output-1.png){#fig-unrolled-rnn width=902 height=278 fig-alt='Two diagrams show one recurrent cell as a loop and as four copies unrolled across time. On the left, an orange state arrow labeled h leaves the cell and loops back into it. On the right, input arrows enter each copy, output arrows leave it, and orange arrows labeled h0 through h4 carry the hidden state from copy to copy, showing that the same cell and weights are reused.'}\n:::\n:::\n\n\n## Gradients through time\n\nThe unrolled network is a deep network with tied weights, so backpropagation\napplies unchanged. Training on a sequence runs the\nloop forward, collects losses $L_t$ at the readouts and sums them into $L$, then\nbackpropagates through the *unrolled* network, a procedure called **backpropagation through time** (BPTT). A gradient that lands on\n$\\vect{h}_T$ must travel back through every application of @eq-rnn-cell to reach an\nearly input. Define\n$\\matr{D}_t = \\mathrm{diag}\\!\\left(\\tanh'(\\cdot)\\right)$ at step $t$. The\nforward Jacobian for one hop is $\\matr{D}_t\\matr{W}_{hh}$, so the full Jacobian is\n\n$$\n\\frac{\\partial \\vect{h}_T}{\\partial \\vect{h}_1}\n= (\\matr{D}_T\\matr{W}_{hh})\\cdots\n  (\\matr{D}_2\\matr{W}_{hh}),\n\\qquad\n\\vect{g}_{t-1}=\\matr{W}_{hh}^{\\!\\top}\\matr{D}_t\\vect{g}_t\n+\\frac{\\partial L_{t-1}}{\\partial\\vect{h}_{t-1}} .\n$$ {#eq-bptt}\n\nThe Jacobian is a product of $T-1$ near-identical matrices. The second expression applies\nthe chain rule in reverse-mode order to the adjoint $\\vect{g}_t=\\partial L/\\partial\\vect{h}_t$,\nstarting from $\\vect{g}_T=\\partial L_T/\\partial\\vect{h}_T$ and ending at\n$\\vect{g}_0=\\matr{W}_{hh}^{\\!\\top}\\matr{D}_1\\vect{g}_1$, since no loss is attached to\n$\\vect{h}_0$: the activation derivative $\\matr{D}_t$ scales the incoming gradient,\n$\\matr{W}_{hh}^{\\top}$ carries it to the previous state, and the loss $L_{t-1}$ adds its\nown gradient there.\n\nA deep network's gradient has the same form, a product of per-layer Jacobians. If the\nfactors shrink the signal, the product decays exponentially; if they grow it, it explodes\nexponentially. Since $\\tanh' \\le 1$ and\n$\\matr{W}_{hh}$ repeats at every step, keeping every relevant direction near unit\ngain over a long sequence is a fragile special case. Initialization can at least start\nthere: an orthogonal $\\matr{W}_{hh}$ has every singular value equal to one, so wherever\nthe pre-activations sit near zero, where $\\tanh'\\approx 1$, each hop preserves the\ngradient's norm. Training moves $\\matr{W}_{hh}$, and $\\tanh'$ drops below one as\npre-activations grow, so orthogonality governs only the start of training (Exercise 2).\n\nEarlier chapters measured depth in layers; here we measure it in *time*, and a paragraph\nof text, read one word per step, is about a hundred layers deep. We illustrate the effect\nof this depth in @fig-vanishing-time, which plots, for a freshly initialized vanilla RNN,\nthe norm of the gradient that reaches the first input against the lag $T$, the length of\nthe sequence (the first input lies $T-1$ steps before the last).\n\n:::: {.plan-code}\n::: {.plan}\n1. Define the reusable `grad_at_first_input` helper.\n2. Build a seeded vanilla `nn.RNN` and compute `g_rnn` at lags 1, 5, 10, 20, 40, and 60.\n3. Gradient reaching the first input vs. lag.\n:::\n\n::: {#cell-fig-vanishing-time .cell execution_count=3}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: gradient reaching the first input vs. lag\"}\n# [1]\ndef grad_at_first_input(rec: nn.Module, lags: list[int],\n                        vocab: int = 4) -> list[float]:\n    norms = []\n    for T in lags:\n        generator = torch.Generator().manual_seed(100 + T)\n        x = torch.randn(8, T, vocab, generator=generator, requires_grad=True)\n        o, _ = rec(x)\n        o[:, -1].sum().backward()\n        norms.append(x.grad[:, 0].norm().item())    # gradient at input #1\n    return norms\n\n# [2]\nlags = [1, 5, 10, 20, 40, 60]\ntorch.manual_seed(0)\nvanilla = nn.RNN(4, 32, batch_first=True)\ng_rnn = grad_at_first_input(vanilla, lags)\n# [3]\nprint(\"lag:      \" + \"   \".join(f\"{l:>7d}\" for l in lags))\nprint(\"|grad|:   \" + \"   \".join(f\"{g:.1e}\" for g in g_rnn))\n\nplt.figure(figsize=(6.2, 3.2))\nplt.semilogy(lags, g_rnn, \"o-\", color=\"#E57200\", ms=5, label=\"vanilla RNN\")\nplt.xlabel(\"lag $T$ between output and first input\")\nplt.ylabel(r\"$\\|\\partial L / \\partial \\mathbf{x}_1\\|$\")\nplt.legend(); plt.tight_layout(); plt.show()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nlag:            1         5        10        20        40        60\n|grad|:   2.9e+00   6.8e-01   2.6e-02   7.2e-05   3.4e-10   1.1e-15\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![Norm of the gradient $\\partial L/\\partial\\vect{x}_1$ that reaches the first input of a freshly initialized vanilla RNN, against the lag $T$, the length of the sequence (the first input lies $T-1$ steps before the last). Here $L$ is the sum of the entries of the last state $\\vect{h}_T$ over the batch and the hidden units. The norm falls by about fifteen orders of magnitude from lag 1 to lag 60.](10-sequences-rnn_files/figure-html/fig-vanishing-time-output-2.png){#fig-vanishing-time width=584 height=297 fig-alt='Log-scale line chart of the norm of the output gradient with respect to the first input versus lag. The vanilla RNN curve falls almost linearly on the log axis, from above one at lag 1 to roughly 10 to the minus 15 at lag 60.'}\n:::\n:::\n\n\n::::\nBy lag 60 the gradient reaching the first input is about $10^{-15}$: at initialization,\nwhatever happened at the start supplies almost no usable learning signal. That makes\nsuccess fragile rather than mathematically impossible. The\nmirror-image failure, explosion, is just as real: one large spike in @eq-bptt's\nproduct can make an update destabilize training.\n\n::: {.callout-warning}\n## Gradient clipping limits explosion, not vanishing\n\nIn practice, explosion is handled with **gradient clipping**: if the gradient's norm\nexceeds a threshold, it is rescaled down to the threshold before the step\n(`nn.utils.clip_grad_norm_`; it appears in every training loop below). This\ntames the spikes so training survives,\nat the cost of damping legitimately large steps. It does *nothing* for vanishing\ngradients, so clipping alone cannot lengthen the memory a recurrent network learns.\n:::\n\n### Training with a finite horizon\n\nFull BPTT requires memory and compute for the entire sequence at each training\nupdate. The standard fix relies on the [Markov property](#stretching-the-old-toolkit) of\nthe forward pass: the carried state and the next input together determine the next state. In **truncated BPTT**, contiguous chunks carry the recurrent\nstate forward but detach it at each boundary. The values cross the boundary; the\ngradient graph does not. This bounds memory while preserving running context. For a cut\nafter step $t$, the next state is\n$$\n\\vect{h}_{t+1} = f\\bigl(\\operatorname{detach}(\\vect{h}_t),\\, \\vect{x}_{t+1}\\bigr),\n$$\nwhere $\\operatorname{detach}$ returns the value of $\\vect{h}_t$ unchanged and passes no\ngradient back through it.\n\nWhere to cut is itself a choice: every $K$ steps (a fixed horizon) or at random points.\nWith a fixed horizon, the carried state still delivers the distant past to the forward\npass, but the gradient trains only the dependencies whose two ends fall inside one chunk\nof $K$ steps. A dependency that reaches $\\ell$ steps back links the loss at step $t$ to the\ninput at step $t-\\ell$. The loss at the $j$th step of a chunk reaches back $j-1$ steps:\njust after a boundary ($j=1$) it reaches only its own input, and at the end of the chunk\n($j=K$) it reaches back $K-1$ steps. Only the losses at chunk steps $\\ell+1,\\dots,K$,\nthat is, $K-\\ell$ of the chunk's $K$ losses, therefore reach an input $\\ell$ steps back:\nsuch a dependency gets gradient from a fraction $1-\\ell/K$ of the losses, and from none\nonce $\\ell \\ge K$. With $K=3$ and a cut after step 3, for example, the loss $L_6$ uses the\nvalue that entered at $\\vect{x}_2$, four steps back; since $4 \\ge K$, no gradient from\n$L_6$ reaches step 2. The model can use a longer dependency that its state happens to\ncarry, but no gradient teaches it to keep one: a fixed horizon biases training toward\nshort-range structure.\n\nRandom cuts alone do not remove the bias, because long-range terms are still the ones\nmost often cut. Dividing each surviving gradient term by the probability that the cuts\nspared it does remove it: a term kept with probability $p$ and scaled by $1/p$\ncontributes its full value on average, so the estimate of the full gradient is unbiased\n(Tallec & Ollivier, 2017). The unbiased estimate has two costs: the rare long-range terms\nthat survive arrive multiplied by large factors $1/p$, which adds variance, and the number\nof steps whose activations must be stored varies from one update to the next. A fixed\nhorizon stores activations for the same $K$ steps in every update and adds no reweighting\nvariance. Most training therefore keeps the fixed horizon, at the price of its bias.\n\nThe character model [later in this chapter](#the-book-reads-itself) uses a simpler finite-horizon recipe: it samples random\n100-character windows and starts each from zero state. That is **fixed-window\ntraining**, not truncated BPTT, because no state is carried between windows. It is\ncheap and appropriate for this small demonstration. In production character models, contiguous\nchunks of roughly 20–50 steps with carried-and-detached state are common. In either\nrecipe, clipping handles spikes; neither creates gradients beyond the truncation\nhorizon.\n\n## Engineering a memory: the LSTM\n\nIn the vanilla RNN, the carried state passes through a weight matrix and a $\\tanh$ at\nevery step, and its gradient through the repeated product of @eq-bptt. We can start\nwith the additive update of residual networks and add multiplicative gates that control\nwhat the carried state keeps. We want a memory pathway that is:\n\n1. **Additive.** Repeated *multiplication* attenuated the signal\n   $\\rightarrow$ update the carried state **additively**:\n   $\\vect{c}_t = \\vect{c}_{t-1} + \\vect{\\Delta}_t$. This is the form of the residual\n   connection, $H(x) = F(x) + x$, whose Jacobian contains an identity term, now\n   applied across time. How much of the state survives many steps depends on the\n   gates below.\n2. **Forgettable on command.** Some stored content should expire. A forget\n   gate $\\vect{f}_t \\in (0,1)$ multiplies $\\vect{c}_{t-1}$ elementwise.\n3. **Writable on command.** New information enters through an input gate\n   $\\vect{i}_t$ scaling a candidate $\\tilde{\\vect{c}}_t$.\n4. **Readable on command.** Expose only what the current step needs, through an\n   output gate $\\vect{o}_t$.\n\nEach gate is a small learned layer squashed by a sigmoid (a number in $(0,1)$ read as *what fraction passes*). The candidate\ncontent is shaped by $\\tanh$, keeping it bounded and centered. Assembled, this is\nthe **Long Short-Term Memory** cell (Hochreiter & Schmidhuber, 1997; the forget gate\n$\\vect{f}_t$ was added by Gers, Schmidhuber & Cummins, 2000):\n\n$$\n\\begin{aligned}\n\\vect{f}_t &= \\sigma\\!\\left(\\matr{W}_f\\,[\\vect{h}_{t-1}, \\vect{x}_t] + \\vect{b}_f\\right)\n&\\quad\n\\vect{i}_t &= \\sigma\\!\\left(\\matr{W}_i\\,[\\vect{h}_{t-1}, \\vect{x}_t] + \\vect{b}_i\\right)\n\\\\\n\\tilde{\\vect{c}}_t &= \\tanh\\!\\left(\\matr{W}_c\\,[\\vect{h}_{t-1}, \\vect{x}_t] + \\vect{b}_c\\right)\n&\\quad\n\\vect{o}_t &= \\sigma\\!\\left(\\matr{W}_o\\,[\\vect{h}_{t-1}, \\vect{x}_t] + \\vect{b}_o\\right)\n\\\\[2pt]\n\\vect{c}_t &= \\vect{f}_t \\odot \\vect{c}_{t-1} \\;+\\; \\vect{i}_t \\odot \\tilde{\\vect{c}}_t\n&\\quad\n\\vect{h}_t &= \\vect{o}_t \\odot \\tanh(\\vect{c}_t).\n\\end{aligned}\n$$ {#eq-lstm}\n\n::: {#cell-fig-lstm-conveyor .cell execution_count=4}\n\n::: {.cell-output .cell-output-display}\n![The LSTM cell. All four learned layers read the same input $[h_{t-1}, x_t]$, drawn along the bottom. Along the top, the cell-state update path multiplies the old cell state elementwise by the forget gate $f_t$ and adds the candidate content $\\tilde{c}_t$ scaled by the input gate $i_t$; the output gate $o_t$ controls what becomes visible as $h_t$.](10-sequences-rnn_files/figure-html/fig-lstm-conveyor-output-1.png){#fig-lstm-conveyor width=701 height=279 fig-alt='LSTM flow diagram. A shared input, the previous hidden state concatenated with the current input, runs along the bottom and feeds four boxes: the forget gate, the input gate, the candidate, and the output gate. Across the top, the previous cell state travels along a horizontal orange line labeled cell-state update path, is multiplied by the forget gate, then receives the input-gated candidate at an addition node to form the new cell state. A tanh branch from that state is multiplied by the output gate to form the hidden state.'}\n:::\n:::\n\n\nTwo states now travel: the cell state $\\vect{c}_t$ (long-term memory, carried along the\ncell-state path) and the hidden state $\\vect{h}_t$ (working memory, playing the vanilla RNN's\nold role).\n\nLet $\\vect{\\gamma}_t := \\partial L/\\partial\\vect{c}_t$\ndenote the loss sensitivity at the cell-state node. In the LSTM\nof @eq-lstm, the gates depend on\n$\\vect{h}_{t-1}$ and $\\vect{x}_t$, not directly on\n$\\vect{c}_{t-1}$. Holding the previous hidden state and the\ncurrent input fixed, the direct cell-state Jacobian is diagonal.\nThe contribution propagated from $\\vect{\\gamma}_t$ along\nthis path for $k$ steps is\n\n$$\n\\begin{aligned}\n\\left.\n\\frac{\\partial\\vect{c}_t}{\\partial\\vect{c}_{t-1}}\n\\right|_{\\vect{h}_{t-1},\\,\\vect{x}_t\\,\\mathrm{fixed}}\n&= \\operatorname{diag}(\\vect{f}_t),\\\\\n\\vect{\\gamma}_{t-k}^{\\mathrm{direct}}\n&= \\left(\\prod_{j=t-k+1}^{t}\\vect{f}_j\\right)\n   \\odot\\vect{\\gamma}_t .\n\\end{aligned}\n$$ {#eq-lstm-highway}\n\nThe product is elementwise. Forget-gate values near one reduce\nattenuation along this direct path. The full gradient also\nincludes paths through hidden states, candidate updates, and\ngates; the displayed contribution is not the complete recurrent\nJacobian. A positive forget-gate bias increases retention at\ninitialization, all other gate inputs held fixed. The experiments\nbelow test how this choice affects training.\n\nPyTorch stores separate input-hidden and\nhidden-hidden bias vectors, then adds them. The code sets their **sum** to $+1$;\nsetting both slices to $+1$ would silently create an effective bias of $+2$.\n@fig-highway-time repeats the measurement of @fig-vanishing-time for this LSTM: at lag 60\nits input gradient is about ten orders of magnitude larger than the vanilla RNN's.\n\n:::: {.plan-code}\n::: {.plan}\n1. Build a seeded `nn.LSTM` and set its two forget-gate bias slices to sum to +1.\n2. Measure the LSTM gradient norm across lag.\n:::\n\n::: {#lstm-gradient-lag .cell execution_count=5}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: gradient versus lag, vanilla RNN against LSTM\"}\n# [1]\ntorch.manual_seed(0)\nlstm = nn.LSTM(4, 32, batch_first=True)\nwith torch.no_grad():\n    n = lstm.bias_ih_l0.shape[0] // 4\n    lstm.bias_ih_l0[n:2 * n].fill_(1.0)\n    lstm.bias_hh_l0[n:2 * n].zero_()             # the two bias slices sum to +1\n# [2]\ng_lstm = grad_at_first_input(lstm, lags)\n```\n:::\n\n\n::::\n\n::: {#cell-fig-highway-time .cell execution_count=6}\n\n::: {.cell-output .cell-output-display}\n![The gradient-vs-lag experiment of @fig-vanishing-time, rerun on the same input sequences with an LSTM of the same size (4 inputs, 32 hidden units) whose effective forget-gate bias is initialized to +1. The vanilla RNN's input gradient decays exponentially with the lag; the LSTM's decays much more slowly and arrives at lag 60 attenuated, about ten orders of magnitude stronger.](10-sequences-rnn_files/figure-html/fig-highway-time-output-1.png){#fig-highway-time width=584 height=297 fig-alt='Log-scale comparison of input-gradient norm versus lag. The vanilla RNN falls from above one to about 10 to the minus 15 by lag 60, while the LSTM with forget bias plus one declines much more slowly and remains near 10 to the minus 5.'}\n:::\n:::\n\n\n## GRU: gating with one state {#gru-the-streamlined-cousin}\n\nThe **Gated Recurrent Unit** (Cho et al., 2014) folds the same ideas into a\nsmaller box: cell and hidden state merged into one $\\vect{h}_t$, forget and input\ngates merged into a single **update gate** $\\vect{z}_t$ (what you keep you do not\noverwrite, and vice versa), plus a **reset gate** $\\vect{r}_t$ that can blank the\npast when a fresh start is called for:\n\n$$\n\\begin{aligned}\n\\vect{z}_t &= \\sigma\\!\\left(\\matr{W}_z [\\vect{h}_{t-1}, \\vect{x}_t] + \\vect{b}_z\\right), \\qquad\n\\vect{r}_t = \\sigma\\!\\left(\\matr{W}_r [\\vect{h}_{t-1}, \\vect{x}_t] + \\vect{b}_r\\right),\\\\\n\\tilde{\\vect{h}}_t &= \\tanh\\!\\left(\\matr{W}_h [\\vect{r}_t \\odot \\vect{h}_{t-1},\\, \\vect{x}_t] + \\vect{b}_h\\right), \\qquad\n\\vect{h}_t = \\vect{z}_t \\odot \\vect{h}_{t-1} + (1 - \\vect{z}_t) \\odot \\tilde{\\vect{h}}_t .\n\\end{aligned}\n$$ {#eq-gru}\n\nThis follows Cho et al.'s original convention: $\\vect{z}_t$ weights the old\nstate, so it reads as **keep**. Some later references reverse the symbol and let\n$\\vect{z}_t$ weight the candidate instead; compare the interpolation equation,\nnot the gate's name alone.\n\nThe GRU has two gates instead of three and one state instead of two, and in most\nsettings its performance is comparable to the LSTM's. The memory test below puts\nPyTorch's version beside the LSTM, and Exercise 3 builds one by hand. @fig-gru-cell draws the cell on the layout of @fig-lstm-conveyor.\n\n::: {#cell-fig-gru-cell .cell execution_count=7}\n\n::: {.cell-output .cell-output-display}\n![The GRU cell on the LSTM cell's layout. One state travels: the update gate $z_t$ keeps a fraction of $h_{t-1}$, and the same dial's complement $1 - z_t$ writes in the candidate $\\tilde{h}_t$. The reset gate $r_t$ scales $h_{t-1}$ before the candidate reads it, as in @eq-gru.](10-sequences-rnn_files/figure-html/fig-gru-cell-output-1.png){#fig-gru-cell width=701 height=279 fig-alt='GRU flow diagram. Across the top, the previous hidden state travels along an orange line, is multiplied by the update gate, and then receives the candidate, scaled by one minus the update gate, at an addition node to form the new hidden state. Along the bottom, a shared input of the previous hidden state and the current input feeds the update gate and the reset gate; the reset gate multiplies the previous hidden state, and that product and the current input feed the candidate.'}\n:::\n:::\n\n\nOne convention matters before you compare code. @eq-gru applies the reset gate to\n$\\vect{h}_{t-1}$ **before** the candidate's hidden-state linear map. PyTorch's\n`nn.GRU` uses a reset-after form,\n$\\tanh(\\matr{W}_{in}\\vect{x}_t + \\vect{b}_{in} + \\vect{r}_t \\odot (\\matr{W}_{hn}\\vect{h}_{t-1} + \\vect{b}_{hn}))$,\nfor implementation efficiency.\nThe gates serve the same purpose, but the two cells are not algebraically identical\nfor the same weights. An exact manual-loop verification must implement PyTorch's\nordering rather than @eq-gru's.\n\n## The memory test\n\nWe measured the gradients above at initialization; now we train. The task is a two-company story: Company A's\nprices open at 0, Company B's at 1, then both trade identically for days, and the\ncorrect day-5 prediction is whatever day 1 said. Solving it requires carrying one\nearly bit across a long stretch of identical noise. As an executable task, the story\nbecomes sequences of 80 random tokens, and the label to predict at the end is\n*the first token*. Chance is 25%. We compare six contenders, three seeds each: the\nvanilla RNN; the LSTM and the GRU with PyTorch's default initialization; the LSTM with\nits forget-gate bias $\\vect{b}_f$ set to $+1$ in every unit; and the GRU with its\nkeep-gate bias $\\vect{b}_z$ set the same way, at $+1$ and at $+2$.^[In both modules\nthat gate's bias is the second slice of the stacked gate bias, so the same code sets\nit.] Each row also reports its **input-gradient norm at\ninitialization**: the norm of the gradient reaching the first input at lag 80, measured\nas in @fig-vanishing-time on the third run's initialization, before any training.\nThe printout below calls this norm the *signal at birth*. Predict\nthe rows before running: is a gated *architecture* alone enough, and does the\nLSTM's $+1$ carry over to the GRU?\n\n:::: {.plan-code .plan-code-wide}\n::: {.plan}\n1. Define the reusable helpers: `make_recall`, `SeqClassifier`, and `train_recall`.\n2. Set `T = 80`, list the vanilla RNN, two LSTM setups, and three GRU setups, make an\n   empty `probe_nets`, and print a header.\n3. Train every setup on three seeds; print its signal at birth and its accuracies.\n:::\n\n::: {#recall-task .cell execution_count=8}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: recall-the-first-token at lag 80, six configurations\"}\n# [1]\ndef make_recall(n: int, T: int, vocab: int = 4,\n                seed: int = 0) -> tuple[torch.Tensor, torch.Tensor]:\n    g = torch.Generator().manual_seed(seed)\n    X = torch.randint(0, vocab, (n, T), generator=g)\n    return F.one_hot(X, vocab).float(), X[:, 0]     # label = first token\n\nGATES = {\"gru\": 3, \"lstm\": 4}                        # gate slices stacked in a bias\n\nclass SeqClassifier(nn.Module):\n    def __init__(self, cell: str, vocab=4, hidden=32, keep_bias=None):\n        super().__init__()\n        self.rec = {\"rnn\": nn.RNN, \"gru\": nn.GRU, \"lstm\": nn.LSTM}[cell](\n            vocab, hidden, batch_first=True)\n        if keep_bias is not None:          # LSTM forget gate, GRU update gate\n            with torch.no_grad():\n                n = self.rec.bias_ih_l0.shape[0] // GATES[cell]\n                self.rec.bias_ih_l0[n:2 * n].fill_(keep_bias)\n                self.rec.bias_hh_l0[n:2 * n].zero_()\n        self.out = nn.Linear(hidden, vocab)\n    def forward(self, x: torch.Tensor) -> torch.Tensor:\n        o, _ = self.rec(x)\n        return self.out(o[:, -1])                    # read out at the END only\n\ndef train_recall(cell: str, T: int, seed: int, keep_bias: float | None = None,\n                 epochs: int = 80) -> tuple[float, nn.Module, float]:\n    torch.manual_seed(seed)\n    net = SeqClassifier(cell, keep_bias=keep_bias)\n    birth = grad_at_first_input(net.rec, [T])[0]     # own generator: no RNG drawn\n    X_tr, y_tr = make_recall(2000, T, seed=1)\n    X_te, y_te = make_recall(500, T, seed=2)\n    opt = torch.optim.Adam(net.parameters(), lr=3e-3)\n    for _ in range(epochs):\n        perm = torch.randperm(len(X_tr))\n        for i in range(0, len(X_tr), 128):\n            idx = perm[i:i + 128]\n            loss = F.cross_entropy(net(X_tr[idx]), y_tr[idx])\n            opt.zero_grad(); loss.backward()\n            nn.utils.clip_grad_norm_(net.parameters(), 1.0)\n            opt.step()\n    with torch.no_grad():\n        acc = (net(X_te).argmax(1) == y_te).float().mean().item()\n    return acc, net, birth\n\n# [2]\nT = 80\nconfigs = [(\"vanilla RNN\", \"rnn\", None),\n           (\"LSTM, default init\", \"lstm\", None),\n           (\"LSTM, forget bias +1\", \"lstm\", 1.0),\n           (\"GRU, default init\", \"gru\", None),\n           (\"GRU, keep bias +1\", \"gru\", 1.0),\n           (\"GRU, keep bias +2\", \"gru\", 2.0)]\nprobe_nets: dict[str, nn.Module] = {}                # kept for the diagnostic below\nprint(f\"recall at lag {T} (chance 25%): signal at birth (seed 6050), \"\n      \"then accuracy for seeds 0 / 1 / 6050\")\n# [3]\nfor label, cell, kb in configs:\n    results = [train_recall(cell, T, s, kb) for s in [0, 1, 6050]]\n    accs = [a for a, _, _ in results]\n    probe_nets[label] = results[-1][1]                # seed 6050's model\n    print(f\"  {label:22s} {results[-1][2]:8.1e}   \"\n          + \"   \".join(f\"{a:4.0%}\" for a in accs))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nrecall at lag 80 (chance 25%): signal at birth (seed 6050), then accuracy for seeds 0 / 1 / 6050\n  vanilla RNN             1.2e-17    25%   100%    25%\n  LSTM, default init      1.9e-15    24%    26%    26%\n  LSTM, forget bias +1    1.3e-06   100%   100%   100%\n  GRU, default init       2.9e-16    24%    23%    25%\n  GRU, keep bias +1       3.9e-09    24%    25%    25%\n  GRU, keep bias +2       5.0e-05   100%   100%   100%\n```\n:::\n:::\n\n\n::::\nUnder this recipe, the LSTM with forget bias $+1$ and the GRU\nwith keep bias $+2$ solve the task on all three tested seeds.\nThe vanilla RNN solves it on one seed, while the remaining\nconfigurations stay near chance. The comparison shows that\ninitialization materially affects the outcome in this task;\ngated architecture alone does not ensure successful training.\nIn these tested configurations the GRU succeeds at $+2$ but not at\n$+1$. Its update gate both keeps the old state and admits the candidate\nin @eq-gru, and equal bias settings in different cells do not imply\nequal realized gate values or recurrent Jacobians (Exercise 3 compares the two cells' Jacobians).\n\nThe initial-gradient measurements use the initialization of the third run only. For that\ninitialization, the two configurations that succeed on all three\ntraining seeds also have larger measured gradients at the first\ninput.^[@sec-a3-precision-performance\nseparates the mathematical attenuation of small gradients from the later question of\nwhether a chosen dtype can still represent the resulting value or update.]\nThis is a diagnostic association in the reported\nexperiment, not a general threshold for successful training.\n\n\n### Inspecting the forget gates {#watching-the-valves}\n\nThe recall results suggest a check on the gates themselves. If the forget-bias\nmodel retains the first token along the direct cell-state path of @eq-lstm-highway\nacross the eighty-step gap, its mean forget gate should\nhold clearly above the half-open point, step after step, while the default model's\nshould stay near $\\sigma(0) = \\tfrac12$. The default-initialized LSTM is the\ncontrol: it has the same architecture, was trained on the same data, and scores at chance.\n\n:::: {.plan-code .plan-code-wide}\n::: {.plan}\n1. Define the reusable `forget_gate_trace` helper.\n2. Open the figure for the forget-gate traces.\n3. Replay the trained LSTMs and read their forget gates.\n:::\n\n::: {#cell-fig-forget-gate-diagnostic .cell execution_count=9}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: replay the trained LSTMs and read their forget gates\"}\n# [1]\n@torch.no_grad()\ndef forget_gate_trace(net: SeqClassifier, T: int = 80) -> list[float]:\n    X_probe, _ = make_recall(64, T, seed=3)           # fresh probe sequences\n    lstm = net.rec\n    W_ih, W_hh = lstm.weight_ih_l0, lstm.weight_hh_l0\n    b = lstm.bias_ih_l0 + lstm.bias_hh_l0\n    hidden = W_hh.shape[1]\n    h = torch.zeros(64, hidden)\n    c = torch.zeros(64, hidden)\n    means = []\n    for t in range(T):                                # replayed by hand\n        z = X_probe[:, t] @ W_ih.T + h @ W_hh.T + b\n        i_gate, f_gate, g_cand, o_gate = z.chunk(4, dim=1)\n        f = torch.sigmoid(f_gate)\n        c = f * c + torch.sigmoid(i_gate) * torch.tanh(g_cand)\n        h = torch.sigmoid(o_gate) * torch.tanh(c)\n        means.append(f.mean().item())\n    out_ref, _ = lstm(X_probe)                        # replay must match the module\n    assert torch.allclose(h, out_ref[:, -1], atol=1e-5)\n    return means\n\n# [2]\nplt.figure(figsize=(6.2, 3.2))\n# [3]\nfor label, color in [(\"LSTM, forget bias +1\", \"#232D4B\"),\n                     (\"LSTM, default init\", \"#E57200\")]:\n    plt.plot(range(1, T + 1), forget_gate_trace(probe_nets[label]),\n             color=color, lw=2, label=label)\nplt.axhline(0.5, ls=\":\", color=\"#B8B8A8\", label=r\"$\\sigma(0) = \\frac{1}{2}$\")\nplt.ylim(0, 1.02)\nplt.xlabel(\"timestep $t$\")\nplt.ylabel(\"mean forget gate\")\nplt.legend(loc=\"lower right\")\nplt.tight_layout(); plt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Mean forget-gate activation per timestep on 64 fresh probe sequences, replayed through the two trained LSTMs of the third run in the table above. The task-solving model (navy) holds its gates flat around 0.76 for all eighty steps. The default-initialized model (orange), same architecture and data, stays near $\\sigma(0)\\approx\\tfrac12$ at about 0.56 and scores at chance.](10-sequences-rnn_files/figure-html/fig-forget-gate-diagnostic-output-1.png){#fig-forget-gate-diagnostic width=587 height=297 fig-alt='Two lines over timesteps one to eighty. The navy line for the forget-bias model stays flat near 0.76. The orange line for the default model stays flat near 0.56, just above a dotted line at one half that the legend labels sigma of zero.'}\n:::\n:::\n\n\n::::\nThe replay executes @eq-lstm by hand with the trained weights, and an assertion confirms\nthat it reproduces the module's own output.\n\nThe forget-bias model's higher mean forget gate is consistent with greater retention along\nthe direct cell-state path. A mean over units and probes, however, does not identify which\nunits retain the first token, nor does it measure the full recurrent sensitivity.\n\n<!-- NOVEL: needs sign-off - concise historical bridge requested in the course review. -->\n::: {.callout-note}\n## Historical bridge (optional): before contextual states\n\n**Word2Vec** learned a fixed vector for each word type through local prediction:\nskip-gram predicts nearby words from a center word, while CBOW predicts the center\nfrom its neighborhood. **GloVe** used corpus-wide co-occurrence counts, fitting\nvector dot products and biases to their logarithmic structure. Both made\ndistributional meaning learnable, but both returned a static lookup: the stored\nvector for *bank* did not change between a river and a loan.\n\nThe recurrent state in this chapter changes that contract. Its $h_t$ depends on the\nvisible prefix, so the representation at a position is contextual even when its input\ntoken embedding began as a lookup. Later we will build a different mechanism that lets\neach position mix information from other visible positions directly.\n:::\n<!-- /NOVEL -->\n\n## The book reads itself\n\nWe now apply fixed windows, clipping, gates, and a softmax over a vocabulary to real\ntext. The task is the oldest one in language modeling: read a character, predict the\nnext. The corpus is the markdown source of nine earlier chapters, Chapters\n[-@sec-01-linear-regression] to [-@sec-06-generalization-inductive-bias] and\n[-@sec-07-filters-convolution] to [-@sec-09-modern-cnns-transfer], with the code cells\nremoved. Its prose and LaTeX mathematics come to about 150,000 characters, kept as a\nfixed snapshot so that later copyedits cannot change the task.\n\n:::: {.plan-code .plan-code-wide}\n::: {.plan}\n1. Read the committed corpus `book-corpus-ch1-9.txt` into the string `text`.\n2. Check the corpus snapshot, build the character vocabulary, and split the encoded\n   text 90/10 into `train_data` and `valid_data`.\n3. Print the corpus length and vocabulary size, then the train and held-out split sizes.\n4. Define the `CharLSTM` module.\n:::\n\n::: {#char-lm-train .cell execution_count=10}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: a character-level LSTM trained on Chapters 1–6 and 8–10\"}\nimport hashlib\nfrom pathlib import Path\n\n# [1]\ncorpus_path = Path(\"../../data/book-corpus-ch1-9.txt\")\ntext = corpus_path.read_text(encoding=\"utf-8\")\n# [2]\nassert len(text) == 148_594\nassert hashlib.sha256(text.encode(\"utf-8\")).hexdigest() == (\n    \"b0fc23a513e37e7bcd78da04a03877345f6ebc850b91dbae260656d9924fb299\"\n)\nchars = sorted(set(text))\nstoi = {c: i for i, c in enumerate(chars)}\ndata = torch.tensor([stoi[c] for c in text])\nsplit = int(0.9 * len(data))\ntrain_data, valid_data = data[:split], data[split:]\n# [3]\nprint(f\"corpus: 9 chapters, {len(text):,} characters, vocab {len(chars)}\")\nprint(f\"deterministic split: {len(train_data):,} train / {len(valid_data):,} held out\")\n\n# [4]\nclass CharLSTM(nn.Module):\n    def __init__(self, vocab: int, hidden: int = 128):\n        super().__init__()\n        self.vocab = vocab\n        self.lstm = nn.LSTM(vocab, hidden, batch_first=True)\n        self.out = nn.Linear(hidden, vocab)\n    def forward(\n        self, x: torch.Tensor,\n        state: tuple[torch.Tensor, torch.Tensor] | None = None,\n    ) -> tuple[torch.Tensor, tuple[torch.Tensor, torch.Tensor]]:\n        o, state = self.lstm(F.one_hot(x, self.vocab).float(), state)\n        return self.out(o), state                      # logits at EVERY step\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncorpus: 9 chapters, 148,594 characters, vocab 104\ndeterministic split: 133,734 train / 14,860 held out\n```\n:::\n:::\n\n\n::::\nThe training loop below is the **canonical next-token trainer**: Listing\n12.1. Each update samples fresh random 100-character windows and clips the gradient;\neach window starts from zero state, as in\n[fixed-window training](#training-with-a-finite-horizon). Because the state is reset, the\nwindow also caps the context length at 100 characters, in training and in the\nfixed-window evaluation below: a limit of the recipe, not of the LSTM. The listing is\nincluded from tested source in the support module\n(`code/dlbook/training.py`), and the cell after it imports and runs that same file.\n\n**Listing 12.1**: the canonical next-token trainer:\n\n:::: {.plan-code .plan-code-wide}\n::: {.plan}\n1. Declare the shared next-token training interface and its protocol controls.\n2. Configure the optimizer and requested step budget.\n3. Draw or reuse chunk starts, then construct shifted input–target pairs.\n4. Predict every next token and average cross-entropy across batch and time.\n5. Backpropagate, clip the gradient, and take one optimizer step.\n6. Retain a sparse learning curve and return the trained artifact.\n:::\n\n```{.python book-include=\"code/dlbook/training.py\"}\n```\n::::\n\n**Listing 12.2**: the fixed-window evaluation protocol (state reset at every\nwindow boundary, so train and held-out numbers stay comparable across chapters):\n\n:::: {.plan-code .plan-code-wide}\n::: {.plan}\n1. Declare inference-only fixed-window evaluation.\n2. Switch to evaluation mode and initialize token-weighted totals.\n3. Traverse consecutive non-overlapping windows.\n4. Predict with recurrent state reset at each window boundary.\n5. Sum loss within windows and count all scored tokens.\n6. Divide once to obtain mean next-token cross-entropy.\n:::\n\n```{.python book-include=\"code/dlbook/evaluation.py\"}\n```\n::::\n\n:::: {.plan-code}\n::: {.plan}\n1. Fix the seed and build a fresh `CharLSTM` sized to the corpus vocabulary.\n2. Train it with `fit_next_token` (Listing 12.1).\n3. Score the trained model on `valid_data` with `fixed_window_loss` and print the loss.\n:::\n\n::: {#char-lm-train-run .cell execution_count=11}\n``` {.python .cell-code code-fold=\"false\"}\nfrom dlbook.training import fit_next_token   # Listing 12.1, imported\n\n# [1]\ntorch.manual_seed(6050)\nmodel = CharLSTM(len(chars))\n# [2]\nmodel, _ = fit_next_token(model, train_data, vocab=len(chars))\n\nfrom dlbook.evaluation import fixed_window_loss   # Listing 12.2, imported\n\n# [3]\nheld_out_loss = fixed_window_loss(model, valid_data, vocab=len(chars))\nprint(f\"held-out fixed-window loss {held_out_loss:.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nstep    0   loss 4.62\nstep  500   loss 2.28\nstep 1000   loss 1.93\nstep 1500   loss 1.75\nstep 2000   loss 1.57\nstep 2500   loss 1.42\nheld-out fixed-window loss 1.89\n```\n:::\n:::\n\n\n::::\nThe loss falls from the uniform-guessing value $\\ln(V) \\approx 4.6$ for the printed\nvocabulary size to 1.42 on the last sampled training minibatch. The deterministic held-out\ntail is harder, at 1.89, but both are far below uniform guessing. To see what the model\nhas learned, we generate text: we feed a prompt, divide the last step's logits by a\n**temperature** $\\tau$, take the softmax, and sample the next character from the\nresult; that character goes back in, and the loop repeats. A temperature below 1 sharpens\nthe distribution, and as $\\tau \\to 0$ each draw becomes the argmax; above 1 it flattens\ntoward uniform. The sampler below uses $\\tau = 0.8$. The hidden state streams, so nothing\nis recomputed, and generation can run past the 100 characters of a training window,\nalthough no training loss depended on a longer context.\n\n:::: {.plan-code}\n::: {.plan}\n1. Define the reusable `sample` helper.\n2. Sample from the model, one character at a time.\n:::\n\n::: {#char-lm-sample .cell execution_count=12}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: sampling from the model, one character at a time\"}\n# [1]\n@torch.no_grad()\ndef sample(prompt: str, n: int = 300, temp: float = 0.8) -> str:\n    model.eval()\n    idx = torch.tensor([[stoi.get(c, 0) for c in prompt]])\n    logits, state = model(idx)\n    out = prompt\n    for _ in range(n):\n        p = F.softmax(logits[0, -1] / temp, -1)\n        nxt = torch.multinomial(p, 1)[None]\n        out += chars[nxt.item()]\n        logits, state = model(nxt, state)              # consume each sample once\n    return out\n\n# [2]\nprint(sample(\"The gradient \", n=300))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nThe gradient mupolition both\nlates\nchood each the burk's map into a mack from the bupfured way\n   intene agmenten. Pyout nothing buith and why the dirge melies to exactly. What algien is\n\n$$\n\\logit_i).\n   ixsections.\n\n## Exercise reseds the barkwarper from to twe optimized $\\rightarrow$ and classitivations, in t\n```\n:::\n:::\n\n\n::::\nTrained on raw text in 100-character windows, the one-layer model has learned words,\nspacing, markdown furniture (headings, display-math dollar signs, backslashed macros), and\nthe book's working vocabulary (Exercise, map, optimized, and misspelled cousins). Clauses\ntrail off, and equations open and never close: the sample reproduces local vocabulary and\nformatting but does not sustain coherent statements. This run does not separate the\neffects of corpus size, state width, training horizon, and optimization.\n\n## At full scale: words, layers, and corpus size {#a-full-scale-rematch-words-layers-and-corpus-size}\n\nThe character model answered the chapter's mechanism question on a CPU-sized snapshot.\nIt did not answer what happens when tokens become words, the corpus grows past two\nmillion training tokens, and recurrent depth increases. We ran that experiment on\nWikiText-2 with a 33,279-word training vocabulary. Three tied-embedding LSTMs share the\nsame optimizer and 12-epoch budget; validation selects one checkpoint before the test\nsplit is opened.\n\n:::: {.plan-code .plan-code-wide}\n::: {.plan}\n1. Load the nine stored WikiText-2 run records.\n2. Summarize parameter count and held-out perplexity by model size.\n:::\n\n::: {#wikitext-scale-summary .cell execution_count=13}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: summarize the pinned WikiText-2 scale rematch\"}\n# [1]\nimport json\nfrom pathlib import Path\n\nwikitext_root = Path(\"../../experiments/rivanna/results/wikitext\")\nwikitext_records = [\n    json.loads(path.read_text()) for path in sorted(wikitext_root.glob(\"*.json\"))\n]\nwikitext_order = [\"small\", \"medium\", \"large\"]\n\n# [2]\nwikitext_summary = {}\nfor size in wikitext_order:\n    rows = [row for row in wikitext_records if row[\"size\"] == size]\n    perplexities = torch.tensor([row[\"test_perplexity\"] for row in rows])\n    wikitext_summary[size] = {\n        \"parameters\": rows[0][\"parameter_count\"],\n        \"values\": perplexities,\n        \"mean\": perplexities.mean().item(),\n        \"sd\": perplexities.std(unbiased=True).item(),\n    }\n```\n:::\n\n\n::::\n\n::: {#cell-fig-wikitext-scale .cell execution_count=14}\n\n::: {.cell-output .cell-output-display}\n![Word-level LSTM scale on WikiText-2. Across three seeds, the 9.61M-parameter model reaches test perplexity 146.59 ± 1.38, the 21.27M model 140.05 ± 0.98, and the 39.77M model 141.94 ± 13.49. The medium model improves reliably; the largest has two strong runs and one poor run, so more parameters did not buy a stable improvement under the shared 12-epoch recipe. Points are seed-level tests; bars are means ± one sample standard deviation.](10-sequences-rnn_files/figure-html/fig-wikitext-scale-output-1.png){#fig-wikitext-scale width=606 height=325 fig-alt='Test perplexity is plotted against log-scaled parameter count for small, medium, and large word-level LSTMs. Small is near 147, medium near 140 with little variation, and large near 142 with a much larger error bar caused by one weak seed.'}\n:::\n:::\n\n\nMoving from 9.61M to 21.27M parameters improves every seed. Moving again to 39.77M does\nnot improve the mean reliably: two runs are strongest, while the third ends at perplexity\n157.44. Capacity, optimization, and data must scale together.\n\n## What a single carried state does not provide {#what-a-fixed-size-state-cannot-hold}\n\nAgainst the six goals, the window met the first four and failed reach; a function per\ntimestep failed two at once: any length and parameters independent of length. One shared\nrecurrence met the first five on paper. On the sixth, at lag 80 on our task, the vanilla\ncell trained successfully on one of three seeds, while the LSTM with forget bias $+1$ and\nthe GRU with keep bias $+2$ did so on all three tested seeds. Two needs outside the list\nremain.\n\nThe first is **revisiting** earlier evidence. In a recurrence, the input at step $s$\nreaches step $t$ only through the $t-s$ updates that follow it, the same chain that the\ngradient crosses backward in @eq-bptt. Suppose one recurrent network, an encoder, reads a\nsource sentence, and a second, a decoder, starts from the encoder's final state and writes\na translation. Every source word then reaches the decoder through that one state, and the\ndecoder has no direct access to earlier source positions. Revisiting requires keeping the\nwhole sequence of states and computing, at each output step, how much to read from each.\n\nThe second is **time in parallel**. Every loop in this chapter runs one step at a time:\n$\\vect{h}_t$ cannot be computed before $\\vect{h}_{t-1}$, so a sequence's length is also its\ntraining's critical path. Two remedies exist: replace the recurrence with a mechanism that\ncombines information from all positions at once, or keep a recurrence simple enough to\ncompute in parallel (Exercise 8 builds the second in miniature).\n\n::: {.callout-note}\n## Check yourself\n\nClose the book for one minute and unroll the recurrence.\n\n- What is shared across timesteps, and what changes at each step?\n- How does an LSTM cell create a less obstructed path for information and gradients?\n- Which of the six goals does each design in this chapter fail, and what can a\n  decoder initialized only from a final state not access directly?\n:::\n\n## Okay, so: weight sharing moved into time\n\n1. **Six streaming design goals**: any length, order (in language a rearrangement can\n   change the meaning), streaming, parameters independent of length, reach, and trainable\n   reach. None of the fixed-size models built in Parts I–II meets all six.\n2. **Shared transition parameters**: one update rule $f$, with the same parameters\n   at every timestep, carrying a hidden state (@eq-recurrence, @eq-rnn-cell).\n   The rule is time-homogeneous, extending the sharing across space of Part II; its output\n   can still depend on position through the state. The unrolled RNN is a deep network\n   with tied weights.\n3. **Tied depth in time repeats the deep-network problem**: BPTT multiplies $T-1$\n   near-identical Jacobians (@eq-bptt) $\\rightarrow$ vanishing or exploding,\n   unless their gains are carefully controlled. The recurrence gives computational reach\n   to every earlier input, but a gradient must cross that product, and a finite training\n   horizon supplies none across its boundary. Clipping tames the explosions;\n   truncation caps the cost, but neither lengthens the range of dependencies that training\n   can teach.\n4. **The LSTM engineers the memory**: an additive cell-state update, the residual\n   connection's form applied across time, with three sigmoid gates\n   (forget, input, output; @eq-lstm). Along the direct cell-state path, the gradient\n   contribution is scaled by a product of forget *gates*, not weight matrices\n   (@eq-lstm-highway); the full gradient also follows paths through hidden states and gates.\n5. **Initialization affects recall**: at lag 80 the default LSTM\n   scores near chance; with the forget bias set to $+1$ it solves the task on all three\n   tested seeds. The GRU packs the same ideas into two gates\n   and one state (@eq-gru); in these tests it succeeded with keep bias $+2$ but\n   not $+1$. At the one measured initialization, the two configurations that succeeded on\n   all three seeds had the largest input-gradient norms: an association in this experiment,\n   not a general threshold.\n6. **A one-layer character LSTM reproduces local features of this book** (words,\n   spacing, markdown and LaTeX markup) but does not sustain coherent statements; this\n   experiment does not separate corpus size, state width, training horizon, and\n   optimization. Two needs remain, revisiting and time in parallel: earlier inputs reach\n   later steps only through one fixed-size state, so a decoder initialized from a final\n   state has no direct access to earlier positions; and a loop must finish each step\n   before starting the next.\n\n## Sources and further reading {.unnumbered}\n\n- Merity, S., Xiong, C., Bradbury, J., & Socher, R. (2017). [*Pointer Sentinel Mixture\n  Models*](https://arxiv.org/abs/1609.07843). International Conference on Learning\n  Representations (ICLR 2017). arXiv:1609.07843. Introduces the WikiText corpora used\n  by the chapter's word-level language-model scale study.\n- Elman, J. L. (1990). [*Finding Structure in\n  Time*](https://doi.org/10.1207/s15516709cog1402_1). *Cognitive Science*, 14(2),\n  179–211. The classic simple recurrent network and its view of hidden state as\n  temporal context.\n- Hochreiter, S., & Schmidhuber, J. (1997). [*Long Short-Term\n  Memory*](https://doi.org/10.1162/neco.1997.9.8.1735). *Neural Computation*, 9(8),\n  1735–1780. The original gated-memory architecture and constant-error pathway.\n- Gers, F. A., Schmidhuber, J., & Cummins, F. (2000). [*Learning to Forget: Continual\n  Prediction with LSTM*](https://doi.org/10.1162/089976600300015015). *Neural\n  Computation*, 12(10), 2451–2471. Adds the adaptive forget gate to the 1997 cell,\n  giving the form used in this chapter.\n- Cho, K., van Merriënboer, B., Gulcehre, C., Bahdanau, D., Bougares, F., Schwenk, H.,\n  & Bengio, Y. (2014). [*Learning Phrase Representations using RNN Encoder–Decoder for\n  Statistical Machine Translation*](https://doi.org/10.3115/v1/D14-1179). In\n  *Proceedings of the 2014 Conference on Empirical Methods in Natural Language\n  Processing (EMNLP)*, 1724–1734. Association for Computational Linguistics.\n  Introduces the gated recurrent unit in its encoder–decoder setting.\n- Pascanu, R., Mikolov, T., & Bengio, Y. (2013). [*On the Difficulty of Training\n  Recurrent Neural Networks*](https://proceedings.mlr.press/v28/pascanu13.html). In\n  *Proceedings of the 30th International Conference on Machine Learning (ICML)*,\n  PMLR 28(3), 1310–1318. Geometric analysis of vanishing and exploding gradients, and\n  gradient clipping.\n- Saxe, A. M., McClelland, J. L., & Ganguli, S. (2014). [*Exact Solutions to the\n  Nonlinear Dynamics of Learning in Deep Linear Neural\n  Networks*](https://arxiv.org/abs/1312.6120). International Conference on Learning\n  Representations (ICLR 2014). arXiv:1312.6120. Orthogonal initialization and norm\n  preservation across depth, the idea behind an orthogonal $\\matr{W}_{hh}$.\n- Tallec, C., & Ollivier, Y. (2017). [*Unbiasing Truncated Backpropagation Through\n  Time*](https://arxiv.org/abs/1705.08209). arXiv preprint arXiv:1705.08209. Random\n  truncation points, with each surviving gradient term divided by the probability that\n  it survived, give an unbiased gradient estimate.\n- Maas, A. L., Daly, R. E., Pham, P. T., Huang, D., Ng, A. Y., & Potts, C. (2011).\n  [*Learning Word Vectors for Sentiment Analysis*](https://aclanthology.org/P11-1015/).\n  In *Proceedings of the 49th Annual Meeting of the Association for Computational\n  Linguistics: Human Language Technologies*, 142–150. Association for Computational\n  Linguistics. Introduces the IMDb movie-review corpus used in Exercise 6.\n- Mikolov, T., Chen, K., Corrado, G., & Dean, J. (2013). [*Efficient Estimation of Word\n  Representations in Vector Space*](https://arxiv.org/abs/1301.3781). International\n  Conference on Learning Representations (ICLR 2013), Workshop Track.\n  arXiv:1301.3781. The CBOW and skip-gram predictive objectives.\n- Pennington, J., Socher, R., & Manning, C. (2014). [*GloVe: Global Vectors for Word\n  Representation*](https://doi.org/10.3115/v1/D14-1162). In *Proceedings of the 2014\n  Conference on Empirical Methods in Natural Language Processing (EMNLP)*, 1532–1543.\n  Association for Computational Linguistics. Static embeddings learned from global\n  word co-occurrence statistics.\n\nThe papers below, listed for Exercise 8's research bridge, study recurrences that compute\nin parallel.\n\n- Bradbury, J., Merity, S., Xiong, C., & Socher, R. (2017). [*Quasi-Recurrent Neural\n  Networks*](https://arxiv.org/abs/1611.01576). International Conference on Learning\n  Representations (ICLR 2017). arXiv:1611.01576. Gates computed from the inputs alone,\n  so only a cheap elementwise recurrence stays serial.\n- Lei, T., Zhang, Y., Wang, S. I., Dai, H., & Artzi, Y. (2018). [*Simple Recurrent\n  Units for Highly Parallelizable Recurrence*](https://doi.org/10.18653/v1/D18-1477). In\n  *Proceedings of the 2018 Conference on Empirical Methods in Natural Language\n  Processing (EMNLP)*, 4470–4481. Association for Computational Linguistics. The same\n  input-only gating in a lighter recurrent unit.\n- Martin, E., & Cundy, C. (2018). [*Parallelizing Linear Recurrent Neural Nets Over\n  Sequence Length*](https://arxiv.org/abs/1709.04057). International Conference on\n  Learning Representations (ICLR 2018). arXiv:1709.04057. Computes linear recurrences\n  with a parallel scan.\n- Gu, A., Goel, K., & Ré, C. (2022). [*Efficiently Modeling Long Sequences with\n  Structured State Spaces*](https://arxiv.org/abs/2111.00396). International Conference\n  on Learning Representations (ICLR 2022). arXiv:2111.00396. Long-memory linear\n  recurrences as state-space layers.\n- Orvieto, A., Smith, S. L., Gu, A., Fernando, A., Gulcehre, C., Pascanu, R., & De, S.\n  (2023). [*Resurrecting Recurrent Neural Networks for Long\n  Sequences*](https://proceedings.mlr.press/v202/orvieto23a.html). In *Proceedings of\n  the 40th International Conference on Machine Learning (ICML)*, PMLR 202,\n  26670–26698. What a plain linear RNN needs to match state-space layers.\n- Feng, L., Tung, F., Ahmed, M. O., Bengio, Y., & Hajimirsadeghi, H. (2024). [*Were RNNs\n  All We Needed?*](https://arxiv.org/abs/2410.01201) arXiv preprint arXiv:2410.01201.\n  Strips the LSTM and GRU down to input-only gates so the whole sequence trains in\n  parallel.\n\n## Exercises {.unnumbered}\n\n1. **(Pencil.)** Count parameters: a width-$k$ window MLP mapping $k$ one-hot\n   tokens (vocabulary $V$) through hidden width $H$ to $V$ logits, versus the\n   vanilla RNN of @eq-rnn-cell with the same $V$ and $H$. Which count depends on\n   how much context the model can use, and what does more reach cost each model?\n2. **(Pencil.)** Let $L=\\ell(\\vect{h}_T)$, with no\n   loss terms at intermediate steps, and write\n   $\\vect{g}_t=\\partial L/\\partial\\vect{h}_t$.\n   Using $0\\leq\\tanh'(z)\\leq1$ and @eq-bptt, show that\n   $$\n   \\|\\vect{g}_1\\|_2\n   \\leq \\|\\matr{W}_{hh}\\|_2^{T-1}\\|\\vect{g}_T\\|_2.\n   $$\n   Why does an orthogonal recurrent matrix approximately preserve\n   the norm in one step when all pre-activations are near zero?\n   Why is a small initial hidden state alone insufficient to\n   ensure this?\n   **(Code.)** Initialize $\\matr{W}_{hh}$ with `nn.init.orthogonal_` and repeat\n   @fig-vanishing-time's measurement. Then record the gradient norm that\n   `clip_grad_norm_` returns in the memory test: what fraction of updates does it\n   rescale for the vanilla RNN and for the forget-bias LSTM, and which cell trains\n   mostly on clipped gradients?\n3. **(Code.)** Implement the reset-before GRU in @eq-gru as a manual loop. Then\n   change only the candidate update to PyTorch's reset-after convention and verify\n   that version against `nn.GRU`. **(Audit.)** The memory test left the GRU at chance\n   with the LSTM's $+1$ and solved it at $+2$. *Named wrong answer:*\n   “$\\sigma(1)\\approx 0.73$ is too leaky”: the LSTM runs at the same bias\n   value and solves the task. Along one trajectory at initialization for both cells at\n   $+1$, measure the norm of the GRU's one-step Jacobian\n   $\\partial\\vect{h}_t/\\partial\\vect{h}_{t-1}$ and of the LSTM's joint-state Jacobian\n   $\\partial(\\vect{h}_t,\\vect{c}_t)/\\partial(\\vect{h}_{t-1},\\vect{c}_{t-1})$, and state\n   what the input-gradient norm at initialization does and does not establish about the\n   difference.\n4. **(Code.)** The chapter starts every sequence with $\\vect{h}_0 = \\vect{0}$.\n   Make $\\vect{h}_0$ a learned `nn.Parameter` in the recall task and retrain.\n   Where does its gradient come from, and when could a learned start plausibly\n   matter?\n5. **(Code.)** Sample the character model at temperatures 0.2, 0.8, and 1.5, and\n   with the temperature near zero compare against picking the argmax at every\n   step. Connect what you see to @sec-02-logistic-softmax's hard-max-versus-softmax discussion:\n   which failure mode of the hard max does greedy decoding reproduce?\n6. **(Code.)** **Both cells from scratch, on real reviews.** Write a vanilla RNN cell\n   with separate input and recurrent maps: a Xavier-initialized $\\matr{W}_{xh}$ and\n   an orthogonal $\\matr{W}_{hh}$ without a bias. Write an LSTM cell with one fused\n   linear map from $[\\vect{h}_{t-1},\\vect{x}_t]$ to all four gate pre-activations and\n   its forget-gate bias set to $+1$. Unroll each over padded minibatches with\n   @eq-masked-update, read the final state into a two-class head, and train both on\n   the IMDb movie reviews of Maas et al. (2011), using a capped vocabulary, an\n   unknown-word token, and an embedding whose padding row stays at zero. Log the\n   gradient norm before clipping, report validation accuracy and a confusion matrix\n   for each cell, then plot the LSTM's three gates across one short, strongly\n   positive review. **(Audit.)** Name one claim the gate plot supports and one it\n   cannot.\n7. **(Code.)** **Running translator, v1.** Keep the corpus, split, and evaluation you\n   fixed for version 0 in the autoencoder interlude's Exercise 6. Replace its one-shot\n   encoder with a recurrent one: embed the source tokens, run a masked recurrent\n   encoder (@eq-masked-update), and hand its final state to version 0's slot decoder\n   unchanged. Train it once with a vanilla RNN cell and once with an LSTM or GRU whose\n   keep gate starts biased to remember, and add both rows to your results log with token\n   accuracy overall and by source-length bucket. **(Audit.)** Reverse the word order of\n   a few source sentences: which versions' outputs change, and what does the\n   length-bucket curve say about asking one final state to carry a whole sentence?\n8. **(Pencil.)** **Research bridge (optional).** Keep a recurrence, but make it\n   simple enough to compute in parallel. Let the LSTM's three gates and its candidate\n   read only $\\vect{x}_t$. Show that the cell update becomes\n   $\\vect{c}_t=\\vect{a}_t\\odot\\vect{c}_{t-1}+\\vect{b}_t$ with every $\\vect{a}_t$ and\n   $\\vect{b}_t$ known before the loop starts, and that pairs compose associatively:\n   applying $(\\vect{a}_1,\\vect{b}_1)$ and then $(\\vect{a}_2,\\vect{b}_2)$ is the single\n   pair $(\\vect{a}_1\\odot\\vect{a}_2,\\;\\vect{a}_2\\odot\\vect{b}_1+\\vect{b}_2)$.\n   **(Code.)** Implement a doubling scan that produces every $\\vect{c}_t$ in\n   $\\lceil\\log_2 T\\rceil$ rounds and assert that it matches the loop for $T=1000$.\n   Then enter this input-gated cell in the lag-80 memory test. What did removing\n   $\\vect{h}_{t-1}$ from the gates cost, and what did it buy? The papers listed for\n   this exercise under Sources follow the idea from input-only gates to today's\n   linear-recurrent and state-space layers; the test-time-regression\n   interlude (@sec-interlude-test-time-regression) returns to fixed-state recurrences\n   from another direction.\n\n",
    "supporting": [
      "10-sequences-rnn_files/figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}