{
  "hash": "0ac91c6a44f6eaf9120999e2392a1768",
  "result": {
    "engine": "jupyter",
    "markdown": "# Sequences and Recurrence {#sec-10-sequences-rnn}\n\n<!-- lecture-source: m07_lecture-7-recurrent-neural-networks_qyU35PKg_NE.txt,\n     m07_lecture-7-2-recurrent-neural-networks-part-2__2NGDmVNUrM.txt,\n     [coding]_m07_lecture-7-3-recurrent-neural-networks-part-3_Az0K6fyf-X4.txt\n     (spine via ds6050_07_rnn/MODULE_NOTES.md)\n     seeds: sources/7.1-RNN-v3.tex (§Naive/Shared-weight RNN, §VEGP, §Truncated BPTT,\n            §From RNN to LSTM: design-by-constraints, §Case Study long-term\n            dependency, §GRU)\n     historical bridge: machine-local course seed\n                        LaTeX/Module 8,9-Transformer/8.L.word2vec.tex\n                        (static-to-contextual framing only; no implementation ported)\n     harvested bridge: @sec-interlude-autoencoders restores Module 6's intended\n                       PCA -> learnable/nonlinear autoencoder -> fixed-code limit\n                       -> recurrence sequence. -->\n\nThe autoencoder interlude promised you **a one-shot encoder is not a variable-length\nprocess**. We began with PCA's closed-form projection, made its encoder and decoder\nlearnable, and added nonlinearity so the reconstruction could bend. For a bounded\nobject such as a $28\\times28$ image, that is a coherent contract: see the whole object,\ncompress it to $\\vect{z}\\in\\mathbb{R}^k$, then decode.\n\nNow let the object keep arriving. A four-token message and a four-thousand-token report\nare both squeezed through the same $k$ numbers; the encoder cannot finish before the\nlast item appears; the decoder cannot revisit evidence discarded from the code.\nIncreasing $k$ postpones the pressure, but it does not tell a fixed-input network how\nto accept an unknown number of pieces.\n\nThis part is about data that refuses the fixed-size contract. Text, audio, sensor\nstreams, stock prices—they come one piece at a time, stop whenever they please, and\ncarry meaning in the *order* of the pieces. We need a computation that can update as\nthe evidence arrives.\n\nOrder deserves a moment, because the book has been here before with the opposite\nverdict. Chapter 6 shuffled every pixel with one fixed permutation and retrained the\nMLP to the same accuracy: because that coordinate map was invertible, the first-layer\nweights could absorb it. The trained MLP was still position-specific; it was not a bag\nmodel. Now shuffle the words of *this sentence* and read it back. For sequences, no\nsingle compensating remap preserves arbitrary order—order is most of the signal. We\nneed models whose computation represents it explicitly.\n\n## Stretching the old toolkit\n\nBefore building anything new, the book's habit: try what we own.\n\n**A window.** Predict the next element from the last $k$: slide a width-$k$ window\nalong the sequence and feed each snapshot to an MLP. This should feel familiar twice\nover: it is autoregression, and the *sliding* is Chapter 7's one-dimensional\nconvolution — locality, transplanted from space to time. Windows are genuinely\nuseful (they power real forecasting systems), but they inherit locality's blind\nspot: anything older than $k$ steps ago does not exist. Widen $k$ and the parameter\ncount grows with it, yet no finite window survives the sentence \"The company whose\nfirst-day price we recorded back in January finally ...\". Context has no fixed\nradius.\n\n**A function per timestep.** Then let the model change over time: learn $f_1$ for\nstep one, $f_2$ for step two, each passing a summary forward. The lecture builds\nthis strawman carefully, because its failure names the cure. The parameter count now\ngrows with sequence *length*; a length-500 essay needs 500 learned functions; and\nthe model is **non-stationary** — it insists the rules of language at position 17\ndiffer from the rules at position 18, when the whole point of language is that they\ndo not.\n\nYou have watched this book face that exact configuration twice. A template for\nevery image position was wasteful and brittle $\\rightarrow$ share the kernel across\nspace (@sec-07-filters-convolution). A detector per location was the wrong\nprior $\\rightarrow$ share it (@sec-08-cnn). The move is the same here, and it is the\nchapter's one big idea: **share the function across time**,\n\n$$\n\\vect{h}_t = f(\\vect{h}_{t-1}, \\vect{x}_t),\n$$ {#eq-recurrence}\n\none learned rule $f$, applied at every step, carrying a running summary\n$\\vect{h}_t$ — the **hidden state** — from each step to the next. This is the\nbook's third weight sharing: across examples (every chapter since the first),\nacross space (Part II), and now across *time*. Stationarity is to sequences what\ntranslation equivariance was to images: the same pattern means the same thing\nwhenever it occurs.\n\n::: {.callout-note}\n## The hidden state is a running memory — and a Markov claim\n\n$\\vect{h}_t$ is whatever $f$ chooses to remember about everything seen so far,\ncompressed into one fixed-size vector. Feeding it back in makes a claim with a\nclassical name, the **Markov property**: $\\vect{h}_{t-1}$ and $\\vect{x}_t$ together\ncontain everything needed for the next step. Nothing else from the past gets a\nsecond look. That claim buys streaming (process tokens as they arrive), any\nsequence length (the loop doesn't care), and — later in this chapter — the license\nto train on chopped-up chunks. Its price is that the memory is *finite*, and this\npart of the book ends when we finally refuse to pay that price\n(@sec-12-kernel-regression).\n:::\n\n## A network with a loop\n\nThe simplest choice of $f$ is Chapter 3's recipe with the state concatenated in:\na linear map of $(\\vect{h}_{t-1}, \\vect{x}_t)$, squashed by a $\\tanh$:\n\n$$\n\\vect{h}_t \\;=\\; \\tanh\\!\\left(\\matr{W}_{hh}\\,\\vect{h}_{t-1} + \\matr{W}_{xh}\\,\\vect{x}_t + \\vect{b}_h\\right),\n\\qquad\n\\vect{o}_t \\;=\\; \\matr{W}_{hq}\\,\\vect{h}_t + \\vect{b}_q ,\n$$ {#eq-rnn-cell}\n\nthe **vanilla recurrent neural network**. Three weight matrices total, reused at\nevery step, regardless of whether the sequence has five tokens or five thousand.\nThe readout $\\vect{o}_t$ produces logits — Chapter 2's machinery — and you can\ncollect one at every step (predicting each next character, labeling each word) or\nonly at the end (classifying the whole sequence); both designs appear below.\n\nPer the book's habit, build the loop by hand, then verify against the framework:\n\n::: {#setup-and-manual-rnn .cell execution_count=1}\n``` {.python .cell-code code-summary=\"Code: the recurrence, written as the loop it is\"}\nimport torch\nimport torch.nn as nn\nimport torch.nn.functional as F\nimport matplotlib.pyplot as plt\n\ntorch.manual_seed(6050)\nV, H, T, B = 8, 16, 12, 4                       # vocab, hidden, time, batch\nrnn = nn.RNN(V, H, batch_first=True)\nx = torch.randn(B, T, V)\nout_ref, _ = rnn(x)\n\nW_xh, W_hh = rnn.weight_ih_l0, rnn.weight_hh_l0\nb = rnn.bias_ih_l0 + rnn.bias_hh_l0\nh = torch.zeros(B, H)                            # h_0 = 0, the standard start\nouts = []\nfor t in range(T):                               # the loop IS the architecture\n    h = torch.tanh(x[:, t] @ W_xh.T + h @ W_hh.T + b)\n    outs.append(h)\nmanual = torch.stack(outs, 1)\nprint(f\"manual loop vs. nn.RNN: max |diff| = {(manual - out_ref).abs().max():.1e}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmanual loop vs. nn.RNN: max |diff| = 1.2e-07\n```\n:::\n:::\n\n\nNotice what the shapes say. `nn.RNN` eats `(batch, time, features)` — a third\naxis has joined Chapter 8's NCHW discipline — and the loop runs over that middle\naxis carrying `h` along. Unroll the loop on paper and the RNN is an ordinary\nfeed-forward network that happens to be $T$ layers deep with every layer's weights\ntied. Hold that thought; it is about to matter enormously.\n\n::: {.cell execution_count=2}\n\n::: {.cell-output .cell-output-display}\n![Two drawings of the same machine. Left: one cell whose hidden state loops back into itself. Right: the loop unrolled — a chain of copies of the *same* cell, each consuming one input and passing the state along. Read vertically it is Chapter 3's network; read horizontally it is a network as deep as the sequence is long, with every layer's weights tied. Both halves of that sentence are about to matter.](10-sequences-rnn_files/figure-pdf/fig-unrolled-rnn-output-1.pdf){#fig-unrolled-rnn}\n:::\n:::\n\n\n## Blame through time\n\nTied depth means Chapter 5's rules apply verbatim. To train on a sequence, run the\nloop forward, collect losses at the readouts, and backpropagate through the\n*unrolled* network, a procedure called **backpropagation through time** (BPTT). Blame that lands on\n$\\vect{h}_T$ must travel back through every application of @eq-rnn-cell to reach an\nearly input. Define\n$\\matr{D}_t = \\mathrm{diag}\\!\\left(\\tanh'(\\cdot)\\right)$ at step $t$. The\nforward Jacobian for one hop is $\\matr{D}_t\\matr{W}_{hh}$, so the full Jacobian is\n\n$$\n\\frac{\\partial \\vect{h}_T}{\\partial \\vect{h}_1}\n= (\\matr{D}_T\\matr{W}_{hh})\\cdots\n  (\\matr{D}_2\\matr{W}_{hh}),\n\\qquad\n\\vect{g}_{t-1}=\\matr{W}_{hh}^{\\!\\top}\\matr{D}_t\\vect{g}_t .\n$$ {#eq-bptt}\n\nA product of $T$ near-identical matrices. The second expression shows the reverse-mode\norder explicitly: the derivative gate acts on incoming blame, then\n$\\matr{W}_{hh}^{\\top}$ carries it to the previous state. Chapter 5 taught you to fear\nthis shape. If the factors shrink the signal, the product dies exponentially; if they\ngrow it, it explodes exponentially. Since $\\tanh' \\le 1$ and\n$\\matr{W}_{hh}$ repeats at every step, keeping every relevant direction near unit\ngain over a long sequence is a fragile special case.\nDepth was measured in layers there; here it is measured in *time*, and a paragraph\nof text is a hundred layers deep. Watch the collapse, in the spirit of Chapter 5's\ndepth experiment:\n\n::: {.cell execution_count=3}\n``` {.python .cell-code code-summary=\"Code: gradient reaching the first input vs. lag\"}\ndef grad_at_first_input(rec: nn.Module, lags: list[int],\n                        vocab: int = 4) -> list[float]:\n    norms = []\n    for T in lags:\n        generator = torch.Generator().manual_seed(100 + T)\n        x = torch.randn(8, T, vocab, generator=generator, requires_grad=True)\n        o, _ = rec(x)\n        o[:, -1].sum().backward()\n        norms.append(x.grad[:, 0].norm().item())    # blame on input #1\n    return norms\n\nlags = [1, 5, 10, 20, 40, 60]\ntorch.manual_seed(0)\nvanilla = nn.RNN(4, 32, batch_first=True)\ng_rnn = grad_at_first_input(vanilla, lags)\nprint(\"lag:      \" + \"   \".join(f\"{l:>7d}\" for l in lags))\nprint(\"|grad|:   \" + \"   \".join(f\"{g:.1e}\" for g in g_rnn))\n\nplt.figure(figsize=(6.2, 3.2))\nplt.semilogy(lags, g_rnn, \"o-\", color=\"#E57200\", ms=5, label=\"vanilla RNN\")\nplt.xlabel(\"lag $T$ between output and first input\")\nplt.ylabel(r\"$\\|\\partial L / \\partial \\mathbf{x}_1\\|$\")\nplt.legend(); plt.tight_layout(); plt.show()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nlag:            1         5        10        20        40        60\n|grad|:   2.9e+00   6.8e-01   2.6e-02   7.2e-05   3.4e-10   1.1e-15\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![How much a freshly initialized vanilla RNN's output can blame its first input, as the lag between them grows. Fifteen orders of magnitude gone by sixty steps: the same exponential decay Chapter 5 measured down a deep network, now measured across time — because an unrolled RNN *is* a deep network with tied weights.](10-sequences-rnn_files/figure-pdf/fig-vanishing-time-output-2.pdf){#fig-vanishing-time fig-alt='Log-scale line chart of the norm of the output gradient with respect to the first input versus lag. The vanilla RNN curve falls almost linearly on the log axis, from above one at lag 1 to roughly 10 to the minus 15 at lag 60.' fig-pos='H'}\n:::\n:::\n\n\nBy lag 60 the gradient reaching the first input is $10^{-15}$: at initialization,\nwhatever happened at the start supplies almost no usable learning signal. That makes\nsuccess fragile rather than mathematically impossible — a later experiment catches\none lucky seed. The\nmirror-image failure, explosion, is just as real — one large spike in @eq-bptt's\nproduct can make an update destabilize training.\n\n::: {.callout-warning}\n## Gradient clipping is a seatbelt, not a cure\n\nPractice handles explosion with **gradient clipping**: if the gradient's norm\nexceeds a threshold, rescale it down to the threshold before stepping\n(`nn.utils.clip_grad_norm_` — it appears in every training loop below). The\nlecture is blunt about what this buys: it tames the spikes so training survives,\nat the cost of damping legitimately large steps — and it does *nothing* for\nvanishing. You cannot clip your way to a longer memory.\n:::\n\n### Training with a finite horizon\n\nBPTT has a second, blunter problem: unrolling a book-length sequence costs\nbook-length memory and compute per step. The standard fix leans on the Markov claim\nfrom the callout above. In **truncated BPTT**, contiguous chunks carry the recurrent\nstate forward but detach it at each boundary. The values cross the boundary; the\ngradient graph does not. This bounds memory while preserving running context.\n\nThe final experiment below uses a simpler finite-horizon recipe: it samples random\n100-character windows and starts each from zero state. That is **fixed-window\ntraining**, not truncated BPTT, because no state is carried between windows. It is\ncheap and appropriate for this small demonstration, but the model can neither see nor\nlearn dependencies beyond 100 characters. In production character models, contiguous\nchunks of roughly 20–50 steps with carried-and-detached state are common. In either\nrecipe, clipping handles spikes; neither creates gradients beyond the truncation\nhorizon.\n\n## Engineering a memory: the LSTM\n\nSo the vanilla RNN's memory dies of repeated multiplication. The seed notes stage\nthe fix as a design-by-constraints exercise, and it is worth walking, because you\nalready own its key move. We want a memory pathway that is:\n\n1. **Preserved by default.** Repeated *multiplication* killed the signal\n   $\\rightarrow$ make the carried state **additive**:\n   $\\vect{c}_t = \\vect{c}_{t-1} + \\Delta_t$. A conveyor belt: information rides\n   along untouched unless something deliberately intervenes. You met this exact\n   maneuver one chapter ago — @sec-09-modern-cnns-transfer's residual connection,\n   $H(x) = F(x) + x$, whose Jacobian's identity term let gradients cross forty\n   layers. Same trick, laid across time.\n2. **Forgettable on command.** Memory is finite; some of it should expire. Install\n   a valve: $\\vect{f}_t \\in (0,1)$ multiplying $\\vect{c}_{t-1}$.\n3. **Writable on command.** New information enters through a second valve\n   $\\vect{i}_t$ scaling a candidate $\\tilde{\\vect{c}}_t$.\n4. **Readable on command.** Expose only what the current step needs, through a\n   third valve $\\vect{o}_t$.\n\nEach valve is a small learned layer squashed by a sigmoid — Chapter 2's machine,\nreinterpreted: a number in $(0,1)$ read as *what fraction passes*. The candidate\ncontent is shaped by $\\tanh$, keeping it bounded and centered. Assembled, this is\nthe **Long Short-Term Memory** cell (Hochreiter & Schmidhuber, 1997):\n\n$$\n\\begin{aligned}\n\\vect{f}_t &= \\sigma\\!\\left(\\matr{W}_f\\,[\\vect{h}_{t-1}, \\vect{x}_t] + \\vect{b}_f\\right)\n&\\quad\n\\vect{i}_t &= \\sigma\\!\\left(\\matr{W}_i\\,[\\vect{h}_{t-1}, \\vect{x}_t] + \\vect{b}_i\\right)\n\\\\\n\\tilde{\\vect{c}}_t &= \\tanh\\!\\left(\\matr{W}_c\\,[\\vect{h}_{t-1}, \\vect{x}_t] + \\vect{b}_c\\right)\n&\\quad\n\\vect{o}_t &= \\sigma\\!\\left(\\matr{W}_o\\,[\\vect{h}_{t-1}, \\vect{x}_t] + \\vect{b}_o\\right)\n\\\\[2pt]\n\\vect{c}_t &= \\vect{f}_t \\odot \\vect{c}_{t-1} \\;+\\; \\vect{i}_t \\odot \\tilde{\\vect{c}}_t\n&\\quad\n\\vect{h}_t &= \\vect{o}_t \\odot \\tanh(\\vect{c}_t).\n\\end{aligned}\n$$ {#eq-lstm}\n\n::: {.cell execution_count=4}\n\n::: {.cell-output .cell-output-display}\n![The LSTM cell as a conveyor belt with valves. The forget gate $f_t$ controls how much old cell state continues; the input gate $i_t$ controls how much candidate content is added; the output gate $o_t$ controls what becomes visible as $h_t$. The upper additive route is the long-memory highway.](10-sequences-rnn_files/figure-pdf/fig-lstm-conveyor-output-1.pdf){#fig-lstm-conveyor fig-alt='LSTM flow diagram. The previous cell state passes across a horizontal orange highway through multiplication by the forget gate, then receives the input-gated candidate at an addition node to form the new cell state. A tanh branch from that state is multiplied by the output gate to form the hidden state.'}\n:::\n:::\n\n\nTwo states now travel: the cell state $\\vect{c}_t$ (long-term memory, the conveyor\nbelt) and the hidden state $\\vect{h}_t$ (working memory, playing the vanilla RNN's\nold role). The line that changes everything is the $\\vect{c}_t$ update — read its\ngradient the way the seed's notes do:\n\n$$\n\\frac{\\partial \\vect{c}_t}{\\partial \\vect{c}_{t-1}} \\approx \\vect{f}_t\n\\qquad\\Longrightarrow\\qquad\n\\frac{\\partial L}{\\partial \\vect{c}_{t-k}} \\approx\n\\left(\\prod_{j=t-k+1}^{t} \\vect{f}_j\\right) \\odot \\frac{\\partial L}{\\partial \\vect{c}_t}.\n$$ {#eq-lstm-highway}\n\nStill a product — but of *learned, data-dependent gates*, not a fixed weight\nmatrix. Where Chapter 9's residual highway kept an unconditional identity lane\nopen, the LSTM's lane has a valve the network controls: hold $\\vect{f}_j$ near 1\nand gradients ride the conveyor belt across dozens of steps; drop it toward 0 and\nthe memory (deliberately) expires. The practical corollary, straight from the\nlecture notes: *initialize the forget-gate bias positive* (say $+1$), so the cell\nstarts life remembering by default. PyTorch stores separate input-hidden and\nhidden-hidden bias vectors, then adds them. The code sets their **sum** to $+1$;\nsetting both slices to $+1$ would silently create an effective bias of $+2$.\nWatch what that buys, on the same axes as before:\n\n::: {.cell execution_count=5}\n``` {.python .cell-code code-summary=\"Code: gradient vs. lag, vanilla RNN against LSTM\"}\ntorch.manual_seed(0)\nlstm = nn.LSTM(4, 32, batch_first=True)\nwith torch.no_grad():\n    n = lstm.bias_ih_l0.shape[0] // 4\n    lstm.bias_ih_l0[n:2 * n].fill_(1.0)\n    lstm.bias_hh_l0[n:2 * n].zero_()             # the two bias slices sum to +1\ng_lstm = grad_at_first_input(lstm, lags)\n\nplt.figure(figsize=(6.2, 3.2))\nplt.semilogy(lags, g_rnn, \"o-\", color=\"#E57200\", ms=5, label=\"vanilla RNN\")\nplt.semilogy(lags, g_lstm, \"s-\", color=\"#232D4B\", ms=5, label=\"LSTM (forget bias +1)\")\nplt.xlabel(\"lag $T$ between output and first input\")\nplt.ylabel(r\"$\\|\\partial L / \\partial \\mathbf{x}_1\\|$\")\nplt.legend(); plt.tight_layout(); plt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![The gradient-vs-lag experiment, rerun with an LSTM whose effective forget-gate bias is initialized to +1. The vanilla RNN's blame signal dies exponentially; the LSTM's rides the cell-state conveyor belt and arrives at lag 60 attenuated but alive, about ten orders of magnitude stronger. Chapter 9 built this highway across layers; the LSTM builds it across time, with a learned valve on the on-ramp.](10-sequences-rnn_files/figure-pdf/fig-highway-time-output-1.pdf){#fig-highway-time fig-alt='Log-scale comparison of input-gradient norm versus lag. The vanilla RNN falls from above one to about 10 to the minus 15 by lag 60, while the LSTM with forget bias plus one declines much more slowly and remains near 10 to the minus 5.' fig-pos='H'}\n:::\n:::\n\n\n### The memory test\n\nGradients at initialization are promissory notes; training is where they get\ncashed. The seed notes pose the decisive task as a two-company story: Company A's\nprices open at 0, Company B's at 1, then both trade identically for days — and the\ncorrect day-5 prediction is whatever day 1 said. Everything hinges on carrying one\nearly bit across a long stretch of identical noise. Here is that story as an\nexecutable task: sequences of 80 random tokens, where the label to predict at the\nend is simply *the first token*. Chance is 25%. Three contenders, three seeds\neach: the vanilla RNN, the LSTM as PyTorch hands it to you, and the LSTM with the\nlecture's remember-by-default initialization.\n\n::: {#recall-task .cell execution_count=6}\n``` {.python .cell-code code-summary=\"Code: recall-the-first-token at lag 80, three configurations\"}\ndef make_recall(n: int, T: int, vocab: int = 4,\n                seed: int = 0) -> tuple[torch.Tensor, torch.Tensor]:\n    g = torch.Generator().manual_seed(seed)\n    X = torch.randint(0, vocab, (n, T), generator=g)\n    return F.one_hot(X, vocab).float(), X[:, 0]     # label = first token\n\nclass SeqClassifier(nn.Module):\n    def __init__(self, cell: str, vocab=4, hidden=32, forget_bias=None):\n        super().__init__()\n        self.rec = {\"rnn\": nn.RNN, \"lstm\": nn.LSTM}[cell](vocab, hidden,\n                                                          batch_first=True)\n        if forget_bias is not None:\n            with torch.no_grad():\n                n = self.rec.bias_ih_l0.shape[0] // 4\n                self.rec.bias_ih_l0[n:2 * n].fill_(forget_bias)\n                self.rec.bias_hh_l0[n:2 * n].zero_()\n        self.out = nn.Linear(hidden, vocab)\n    def forward(self, x: torch.Tensor) -> torch.Tensor:\n        o, _ = self.rec(x)\n        return self.out(o[:, -1])                    # read out at the END only\n\ndef train_recall(cell: str, T: int, seed: int, forget_bias: float | None = None,\n                 epochs: int = 80) -> float:\n    torch.manual_seed(seed)\n    net = SeqClassifier(cell, forget_bias=forget_bias)\n    X_tr, y_tr = make_recall(2000, T, seed=1)\n    X_te, y_te = make_recall(500, T, seed=2)\n    opt = torch.optim.Adam(net.parameters(), lr=3e-3)\n    for _ in range(epochs):\n        perm = torch.randperm(len(X_tr))\n        for i in range(0, len(X_tr), 128):\n            idx = perm[i:i + 128]\n            loss = F.cross_entropy(net(X_tr[idx]), y_tr[idx])\n            opt.zero_grad(); loss.backward()\n            nn.utils.clip_grad_norm_(net.parameters(), 1.0)\n            opt.step()\n    with torch.no_grad():\n        return (net(X_te).argmax(1) == y_te).float().mean().item()\n\nT = 80\nconfigs = [(\"vanilla RNN\", \"rnn\", None),\n           (\"LSTM, default init\", \"lstm\", None),\n           (\"LSTM, forget bias +1\", \"lstm\", 1.0)]\nprint(f\"recall accuracy at lag {T} (chance 25%), seeds 0 / 1 / 6050:\")\nfor label, cell, fb in configs:\n    accs = [train_recall(cell, T, s, fb) for s in [0, 1, 6050]]\n    print(f\"  {label:22s} \" + \"   \".join(f\"{a:.0%}\" for a in accs))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nrecall accuracy at lag 80 (chance 25%), seeds 0 / 1 / 6050:\n  vanilla RNN            25%   100%   25%\n  LSTM, default init     24%   26%   26%\n  LSTM, forget bias +1   100%   100%   100%\n```\n:::\n:::\n\n\nThree rows, one lesson each. The vanilla RNN is a *lottery*: two seeds sit at\nchance, one cracks the task. @fig-vanishing-time says the teaching gradient is\nastronomically attenuated, not exactly zero — so once in a while optimization\nstumbles onto a solution anyway, and you cannot build a system on once-in-a-while.\nThe default-initialized LSTM loses on *every* seed — worth a long pause, because it\nsays the architecture alone is not the cure. A fresh LSTM's forget gates hover\nnear $\\sigma(0) = \\tfrac12$, and $0.5^{80} \\approx 10^{-24}$: a half-closed valve,\ncompounded eighty times, is as fatal as no valve. The third row flips the single\nbias that opens the valve, and the task is solved outright, every seed. The\nhighway was built by the architecture; *initialization opened it* — the same\nlesson Chapter 5 taught about signal scales at birth, now with a memory attached.\n@sec-a3-precision-performance separates this mathematical attenuation from the later\nquestion of whether a chosen dtype can still represent the resulting value or update.\nAnd the deliverable is not raw capability but **reliability**: what the gates buy\nis that memory stops being a lottery. (For shorter stretches the drama disappears:\nat lag 20 all three rows solve the task under this budget. The gates earn their\nkeep precisely where @eq-bptt says the vanilla cell must fail.)\n\n## GRU: the streamlined cousin\n\nThe **Gated Recurrent Unit** (Cho et al., 2014) folds the same ideas into a\nsmaller box: cell and hidden state merged into one $\\vect{h}_t$, forget and input\nvalves merged into a single **update gate** $\\vect{z}_t$ (what you keep you don't\noverwrite, and vice versa), plus a **reset gate** $\\vect{r}_t$ that can blank the\npast when a fresh start is called for:\n\n$$\n\\begin{aligned}\n\\vect{z}_t &= \\sigma\\!\\left(\\matr{W}_z [\\vect{h}_{t-1}, \\vect{x}_t]\\right), \\qquad\n\\vect{r}_t = \\sigma\\!\\left(\\matr{W}_r [\\vect{h}_{t-1}, \\vect{x}_t]\\right),\\\\\n\\tilde{\\vect{h}}_t &= \\tanh\\!\\left(\\matr{W}_h [\\vect{r}_t \\odot \\vect{h}_{t-1},\\, \\vect{x}_t]\\right), \\qquad\n\\vect{h}_t = \\vect{z}_t \\odot \\vect{h}_{t-1} + (1 - \\vect{z}_t) \\odot \\tilde{\\vect{h}}_t .\n\\end{aligned}\n$$ {#eq-gru}\n\nTwo gates instead of three, one state instead of two, comparable performance in\nmost settings. The lecture explicitly skips the derivation, and the book follows\nsuit. With the equations on record and Exercise 3 waiting, you can build one\nyourself and let it compete on the memory test.\n\nOne convention matters before you compare code. @eq-gru applies the reset gate to\n$\\vect{h}_{t-1}$ **before** the candidate's hidden-state linear map. PyTorch's\n`nn.GRU` uses a reset-after form,\n$\\tanh(W_{in}x+b_{in}+r\\odot(W_{hn}h+b_{hn}))$, for implementation efficiency.\nThe gates serve the same purpose, but the two cells are not algebraically identical\nfor the same weights. An exact manual-loop verification must implement PyTorch's\nordering rather than @eq-gru's.\n\n<!-- NOVEL: needs sign-off - concise historical bridge requested in the course review. -->\n::: {.callout-note}\n## Historical bridge (non-examinable): before contextual states\n\n**Word2Vec** learned a fixed vector for each word type through local prediction:\nskip-gram predicts nearby words from a center word, while CBOW predicts the center\nfrom its neighborhood. **GloVe** used corpus-wide co-occurrence counts, fitting\nvector dot products and biases to their logarithmic structure. Both made\ndistributional meaning learnable, but both returned a static lookup: the stored\nvector for *bank* did not change between a river and a loan.\n\nThe recurrent state in this chapter changes that contract. Its $h_t$ depends on the\nvisible prefix, so the representation at a position is contextual even when its input\ntoken embedding began as a lookup. Self-attention later makes that contextual mixing\ndirect in @sec-14-self-attention-transformer, and @sec-15-bert-pretraining turns it\ninto a large-scale pretraining regime.\n:::\n<!-- /NOVEL -->\n\n## The book reads itself\n\nTime to put fixed windows, clipping, gates, and Chapter 2's softmax over a\nvocabulary to work on real text. In keeping with a book whose every experiment runs\non its own pages, the training corpus is *the nine chapters you have already read*:\ntheir prose, stripped of code cells, about 150,000 characters. We commit that\ncode-stripped text as a benchmark snapshot; later copyedits must not silently change\nthe task. The task is the oldest one in language modeling: read a character, predict\nthe next.\n\n::: {#char-lm-train .cell execution_count=7}\n``` {.python .cell-code code-summary=\"Code: a character-level LSTM trained on Chapters 1–9\"}\nimport hashlib\nfrom pathlib import Path\n\ncorpus_path = Path(\"../../data/book-corpus-ch1-9.txt\")\ntext = corpus_path.read_text(encoding=\"utf-8\")\nassert len(text) == 148_594\nassert hashlib.sha256(text.encode(\"utf-8\")).hexdigest() == (\n    \"b0fc23a513e37e7bcd78da04a03877345f6ebc850b91dbae260656d9924fb299\"\n)\nchars = sorted(set(text))\nstoi = {c: i for i, c in enumerate(chars)}\ndata = torch.tensor([stoi[c] for c in text])\nsplit = int(0.9 * len(data))\ntrain_data, valid_data = data[:split], data[split:]\nprint(f\"corpus: 9 chapters, {len(text):,} characters, vocab {len(chars)}\")\nprint(f\"deterministic split: {len(train_data):,} train / {len(valid_data):,} held out\")\n\nclass CharLSTM(nn.Module):\n    def __init__(self, vocab: int, hidden: int = 128):\n        super().__init__()\n        self.vocab = vocab\n        self.lstm = nn.LSTM(vocab, hidden, batch_first=True)\n        self.out = nn.Linear(hidden, vocab)\n    def forward(\n        self, x: torch.Tensor,\n        state: tuple[torch.Tensor, torch.Tensor] | None = None,\n    ) -> tuple[torch.Tensor, tuple[torch.Tensor, torch.Tensor]]:\n        o, state = self.lstm(F.one_hot(x, self.vocab).float(), state)\n        return self.out(o), state                      # logits at EVERY step\n\ntorch.manual_seed(6050)\nmodel = CharLSTM(len(chars))\nopt = torch.optim.Adam(model.parameters(), lr=2e-3)\nchunk, batch = 100, 64                                 # random fixed-context windows\nfor step in range(2501):\n    s = torch.randint(0, len(train_data) - chunk - 1, (batch,))\n    xb = torch.stack([train_data[j:j + chunk] for j in s])\n    yb = torch.stack([train_data[j + 1:j + chunk + 1] for j in s])\n    logits, _ = model(xb)\n    loss = F.cross_entropy(logits.reshape(-1, len(chars)), yb.reshape(-1))\n    opt.zero_grad(); loss.backward()\n    nn.utils.clip_grad_norm_(model.parameters(), 1.0)\n    opt.step()\n    if step % 500 == 0:\n        print(f\"step {step:4d}   loss {loss.item():.2f}\")\n\n@torch.no_grad()\ndef fixed_window_loss(net: nn.Module, sequence: torch.Tensor,\n                      window: int = 100) -> float:\n    net.eval()\n    total_loss, n_tokens = 0.0, 0\n    for start in range(0, len(sequence) - 1, window):\n        stop = min(start + window, len(sequence) - 1)\n        xb = sequence[start:stop].unsqueeze(0)\n        yb = sequence[start + 1:stop + 1]\n        logits, _ = net(xb)                         # state resets at each window\n        total_loss += F.cross_entropy(\n            logits.reshape(-1, len(chars)), yb, reduction=\"sum\").item()\n        n_tokens += yb.numel()\n    return total_loss / n_tokens\n\nprint(f\"held-out fixed-window loss {fixed_window_loss(model, valid_data):.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncorpus: 9 chapters, 148,594 characters, vocab 104\ndeterministic split: 133,734 train / 14,860 held out\nstep    0   loss 4.62\nstep  500   loss 2.28\nstep 1000   loss 1.93\nstep 1500   loss 1.75\nstep 2000   loss 1.57\nstep 2500   loss 1.42\nheld-out fixed-window loss 1.89\n```\n:::\n:::\n\n\nThe loss falls from $\\ln(V) \\approx 4.6$ for the printed vocabulary size (uniform guessing)\nto 1.42 on the last sampled training minibatch. The deterministic held-out\ntail is harder, at 1.89, but both are far below uniform guessing. The model has\nlearned a great deal about what this book's next character tends to be. To *hear*\nwhat it learned, generate: feed a prompt, sample\nthe next character from the softmax (divided by a **temperature** that sharpens or\nflattens it, Chapter 2's dial between hard max and uniform), feed that character\nback in, repeat. The hidden state streams; nothing is recomputed.\n\n::: {#char-lm-sample .cell execution_count=8}\n``` {.python .cell-code code-summary=\"Code: sampling from the model, one character at a time\"}\n@torch.no_grad()\ndef sample(prompt: str, n: int = 300, temp: float = 0.8) -> str:\n    model.eval()\n    idx = torch.tensor([[stoi.get(c, 0) for c in prompt]])\n    logits, state = model(idx)\n    out = prompt\n    for _ in range(n):\n        p = F.softmax(logits[0, -1] / temp, -1)\n        nxt = torch.multinomial(p, 1)[None]\n        out += chars[nxt.item()]\n        logits, state = model(nxt, state)              # consume each sample once\n    return out\n\nprint(sample(\"The gradient \", n=300))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nThe gradient mupolition both\nlates\nchood each the burk's map into a mack from the bupfured way\n   intene agmenten. Pyout nothing buith and why the dirge melies to exactly. What algien is\n\n$$\n\\logit_i).\n   ixsections.\n\n## Exercise reseds the barkwarper from to twe optimized $\\rightarrow$ and classitivations, in t\n```\n:::\n:::\n\n\nRead the output honestly, because both halves of the verdict teach. What it *got*:\nwords, spacing, sentence rhythm, markdown furniture (asterisks, pipes, colons),\nand the book's working vocabulary (training, batch, layer, convolution in various\nmisspellings), all learned from raw characters by a one-layer recurrence reading\n100-character chunks. What it\n*lacks*: meaning. Clauses trail off; equations open and never close; the prose has\nthe book's accent with none of its intent. Some of that is scale (a 150k-character\ncorpus and 128 hidden units is a *tiny* language model), and some of it is the\nfinite state. By the end of a sentence, the beginning has been squeezed through\nthe LSTM's two 128-dimensional states, $(\\vect{h}, \\vect{c})$: 256 scalars in all.\nBoth diagnoses point down the road this part of the book is\ntraveling.\n\n## What a fixed-size state cannot hold\n\nThe lecture closes with the bridge this part of the book now crosses. If a\nrecurrent cell can read a sequence into a state, then two of them can translate:\nan **encoder** reads the source sentence into its final state, a **decoder** spins\nthat state back out as words in another language. That architecture, plus its\ntraining tricks, is @sec-11-encoder-decoder. But notice what the design asks of\none fixed-size state: the *entire sentence*, compressed into $(\\vect{h},\\vect{c})$, no\nmatter how long the sentence runs. The char-LM's trailing clauses were this\nbottleneck in miniature. The honest fix is not a bigger vector; it is admitting\nthat the decoder should be allowed to *look back at all of the encoder's states*,\nnot just the last. Choosing where to look, on the fly, is a similarity\ncomputation you have been prepared for since Chapter 1's dot products. That is\nattention (@sec-12-kernel-regression, @sec-13-attention), and it is two chapters\naway.\n\nThe fixed-size state is about to lose that rematch in Part IV: attention will keep\nthe evidence available instead of squeezing all of it through one vector. Then the\nstate returns in @sec-14-memory-spectrum—not as a defeated design, but as a chosen\npoint on a regression tradeoff whose price we can finally name.\n\n## Okay, so — weight sharing moved into time\n\n1. **Order is the signal.** Chapter 6's MLP could absorb one fixed pixel permutation\n   when retrained; shuffle a sentence into arbitrary orders and its meaning changes.\n   Sequences add variable length and streaming, and the fixed-size toolkit of Parts\n   I–II has no honest answer.\n2. **The third weight sharing**: one function $f$, applied at every timestep,\n   carrying a hidden state (@eq-recurrence, @eq-rnn-cell). This is stationarity as\n   inductive bias, exactly as sharing across space was in Part II. The unrolled\n   RNN is a deep network with tied weights.\n3. **Tied depth in time = Chapter 5's nightmare**: BPTT multiplies $T$\n   near-identical Jacobians (@eq-bptt) $\\rightarrow$ vanishing or exploding,\n   unless their gains are carefully controlled. Clipping belts in the explosions;\n   truncation caps the cost, but neither lengthens memory. Windows of roughly 20–50\n   steps are a common practical horizon, not a universal vanilla-RNN ceiling.\n4. **The LSTM engineers the memory**: an additive cell-state conveyor belt,\n   Chapter 9's residual highway laid across time, with three sigmoid valves\n   (forget, input, output; @eq-lstm). Its gradient rides a product of *gates*, not\n   weights (@eq-lstm-highway).\n5. **Architecture proposes, initialization disposes**: at lag 80 the default LSTM\n   scores chance ($\\sigma(0)^{80} \\approx 10^{-24}$); set the forget bias to $+1$\n   and the task is solved on every seed. GRU packs the same ideas into two gates\n   and one state (@eq-gru).\n6. **A one-layer character LSTM learns this book's accent** (words, rhythm,\n   LaTeX tics) but not its meaning: part scale, part the finite-state\n   bottleneck. Cramming a whole sequence into 256 recurrent-state scalars is the debt Part III\n   carries forward, and attention is how the book repays it.\n\n## Sources and further reading {.unnumbered}\n\n- [Elman, *Finding Structure in Time*](https://doi.org/10.1207/s15516709cog1402_1): the classic simple recurrent network and its view of hidden state as temporal context.\n- [Hochreiter & Schmidhuber, *Long Short-Term Memory*](https://doi.org/10.1162/neco.1997.9.8.1735): the original gated-memory architecture and constant-error pathway.\n- [Cho et al., *Learning Phrase Representations using RNN Encoder–Decoder for Statistical Machine Translation*](https://aclanthology.org/D14-1179/): introduces the gated recurrent unit in its encoder–decoder setting.\n- [Pascanu, Mikolov, & Bengio, *On the Difficulty of Training Recurrent Neural Networks*](https://proceedings.mlr.press/v28/pascanu13.html): geometric analysis of vanishing/exploding gradients and gradient clipping.\n- [Mikolov et al., *Efficient Estimation of Word Representations in Vector Space*](https://arxiv.org/abs/1301.3781): the CBOW and skip-gram predictive objectives.\n- [Pennington, Socher, & Manning, *GloVe: Global Vectors for Word Representation*](https://aclanthology.org/D14-1162/): static embeddings learned from global word co-occurrence statistics.\n\n## Exercises {.unnumbered}\n\n1. **(Pencil.)** Count parameters: a width-$k$ window MLP mapping $k$ one-hot\n   tokens (vocabulary $V$) through hidden width $H$ to $V$ logits, versus the\n   vanilla RNN of @eq-rnn-cell with the same $V$ and $H$. Which count depends on\n   how much context the model can use, and why is that the whole argument of this\n   chapter in two numbers?\n2. **(Pencil.)** From @eq-bptt, show that if $\\tanh$ operated in its linear regime\n   ($\\tanh' \\approx 1$), the gradient norm grows or decays like the spectral\n   radius of $\\matr{W}_{hh}$ raised to $T$. What does $\\tanh'(0) = 1$ say about\n   the moment right after initialization, when $\\vect{h} \\approx \\vect{0}$?\n3. **(Code.)** Implement the reset-before GRU in @eq-gru as a manual loop and enter\n   it in the lag-80 memory test. Then change only the candidate update to PyTorch's\n   reset-after convention and verify that version against `nn.GRU`. Does either\n   need an initialization trick, and which bias would you set?\n4. **(Code.)** The chapter starts every sequence with $\\vect{h}_0 = \\vect{0}$.\n   Make $\\vect{h}_0$ a learned `nn.Parameter` in the recall task and retrain.\n   Where does its gradient come from, and when could a learned start plausibly\n   matter?\n5. **(Code.)** Sample the character model at temperatures 0.2, 0.8, and 1.5, and\n   with the temperature near zero compare against picking the argmax at every\n   step. Connect what you see to Chapter 2's hard-max-versus-softmax discussion:\n   which failure mode of the hard max does greedy decoding reproduce?\n\n",
    "supporting": [
      "10-sequences-rnn_files/figure-pdf"
    ],
    "filters": []
  }
}