<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>18&nbsp; Alignment and RL Fine-Tuning – Deep Learning: Making It Learnable</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/part5/19-generative.html" rel="next">
<link href="../../chapters/part5/17-peft-quantization.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-2c6940bf2fa6cf01ae6e8f10fcb58cc9.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>
  // Book math macros — keep in sync with tex/macros.tex (PDF path).
  // MathJax reads this config because it is defined before the MathJax
  // script loads (Quarto places include-in-header above its math script).
  window.MathJax = {
    tex: {
      macros: {
        E: "\\mathbb{E}",
        Ex: "\\operatorname{E}",
        var: "\\operatorname{Var}",
        cov: "\\operatorname{Cov}",
        imp: "\\Rightarrow",
        argmax: "\\operatorname*{arg\\,max}",
        argmin: "\\operatorname*{arg\\,min}",
        norm: ["\\left\\lVert#1\\right\\rVert", 1],
        vect: ["\\boldsymbol{#1}", 1],
        matr: ["\\boldsymbol{#1}", 1],
        R: "\\mathbb{R}",
        dd: "\\mathrm{d}",
        loss: "\\mathcal{L}"
      }
    }
  };
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/part5/17-peft-quantization.html">The Pretrained Era</a></li><li class="breadcrumb-item"><a href="../../chapters/part5/18-alignment.html"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Alignment and RL Fine-Tuning</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Deep Learning: Making It Learnable</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/Shakeri-Lab/dl-book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">From Lines to Networks</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/01-linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Linear Regression, the Mother Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/02-logistic-softmax.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Linear Models that Classify: Logistic and Softmax</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/03-nonlinearity-mlp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Nonlinearity and the MLP</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/04-training-loss-sgd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Training: Loss and Stochastic Gradient Descent</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/05-backpropagation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Backpropagation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/06-generalization-inductive-bias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">When It Fails: Generalization in Pictures, and Inductive Bias</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/interludes/learning-by-experiment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Who Trains the Trainer? Learning by Experiment</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Vision: Learning the Filters</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/07-filters-convolution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Filters and Convolution (Fixed Kernels)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/08-cnn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">CNNs: Making the Filters Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/09-modern-cnns-transfer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Modern CNNs and Transfer Learning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/interludes/making-pca-learnable.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Interlude: Making PCA Learnable</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Sequences</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part3/10-sequences-rnn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Sequences and Recurrence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part3/11-encoder-decoder.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Encoder–Decoder, Teacher Forcing, Beam Search</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Attention: Learning the Similarity</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/12-kernel-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Kernel Regression: Attention Before It Was Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/13-attention.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Attention: Making the Kernel Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/14-self-attention-transformer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Self-Attention and the Transformer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/15-bert-pretraining.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">The BERT Moment: Pretraining as the New Regime</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/16-vit-scaling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Vision Transformers and Scaling Laws</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">The Pretrained Era</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/17-peft-quantization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Adapting Pretrained Models: Prompting, PEFT, Quantization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/18-alignment.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Alignment and RL Fine-Tuning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/19-generative.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Generative Models: From Codes to Samples</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/20-multimodal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Multimodal Learning: One Space, Two Views</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/epilogue.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Epilogue: The Question Is Yours</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a1-linear-algebra.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Linear Algebra and the SVD</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a2-tensors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Tensors in Practice</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a3-precision-performance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Numerical Precision and Hardware Efficiency</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a4-notation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Notation</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
<div class="quarto-sidebar-footer"><div class="sidebar-footer-item">
<p><a href="https://shakeri-lab.github.io/dl-book/#revision-notes">Revision notes</a></p>
</div></div></nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#same-model-different-supervision" id="toc-same-model-different-supervision" class="nav-link active" data-scroll-target="#same-model-different-supervision"><span class="header-section-number">18.1</span> Same model, different supervision</a></li>
  <li><a href="#a-preference-is-a-measurement-not-a-value" id="toc-a-preference-is-a-measurement-not-a-value" class="nav-link" data-scroll-target="#a-preference-is-a-measurement-not-a-value"><span class="header-section-number">18.2</span> A preference is a measurement, not a value</a></li>
  <li><a href="#train-a-judge-then-try-to-please-the-judge" id="toc-train-a-judge-then-try-to-please-the-judge" class="nav-link" data-scroll-target="#train-a-judge-then-try-to-please-the-judge"><span class="header-section-number">18.3</span> Train a judge, then try to please the judge</a>
  <ul class="collapse">
  <li><a href="#the-exact-finite-response-policy" id="toc-the-exact-finite-response-policy" class="nav-link" data-scroll-target="#the-exact-finite-response-policy">The exact finite-response policy</a></li>
  <li><a href="#ppo-in-outline-a-second-anchor" id="toc-ppo-in-outline-a-second-anchor" class="nav-link" data-scroll-target="#ppo-in-outline-a-second-anchor">PPO in outline: a second anchor</a></li>
  </ul></li>
  <li><a href="#when-the-proxy-becomes-the-target" id="toc-when-the-proxy-becomes-the-target" class="nav-link" data-scroll-target="#when-the-proxy-becomes-the-target"><span class="header-section-number">18.4</span> When the proxy becomes the target</a></li>
  <li><a href="#dpo-removes-a-stage-not-the-assumptions" id="toc-dpo-removes-a-stage-not-the-assumptions" class="nav-link" data-scroll-target="#dpo-removes-a-stage-not-the-assumptions"><span class="header-section-number">18.5</span> DPO removes a stage, not the assumptions</a></li>
  <li><a href="#choose-by-the-feedback-and-exploration-you-have" id="toc-choose-by-the-feedback-and-exploration-you-have" class="nav-link" data-scroll-target="#choose-by-the-feedback-and-exploration-you-have"><span class="header-section-number">18.6</span> Choose by the feedback and exploration you have</a></li>
  <li><a href="#alignment-is-an-evaluation-contract" id="toc-alignment-is-an-evaluation-contract" class="nav-link" data-scroll-target="#alignment-is-an-evaluation-contract"><span class="header-section-number">18.7</span> Alignment is an evaluation contract</a></li>
  <li><a href="#the-next-question-where-did-the-generator-come-from" id="toc-the-next-question-where-did-the-generator-come-from" class="nav-link" data-scroll-target="#the-next-question-where-did-the-generator-come-from"><span class="header-section-number">18.8</span> The next question: where did the generator come from?</a></li>
  <li><a href="#okay-so-where-to-update-and-what-to-optimize-are-separate" id="toc-okay-so-where-to-update-and-what-to-optimize-are-separate" class="nav-link" data-scroll-target="#okay-so-where-to-update-and-what-to-optimize-are-separate"><span class="header-section-number">18.9</span> Okay, so — where to update and what to optimize are separate</a></li>
  <li><a href="#sources-and-further-reading" id="toc-sources-and-further-reading" class="nav-link" data-scroll-target="#sources-and-further-reading">Sources and further reading</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/Shakeri-Lab/dl-book/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/part5/17-peft-quantization.html">The Pretrained Era</a></li><li class="breadcrumb-item"><a href="../../chapters/part5/18-alignment.html"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Alignment and RL Fine-Tuning</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-18-alignment" class="quarto-section-identifier"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Alignment and RL Fine-Tuning</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<!-- lecture-source:
     Module 11 is slide-only; the prose spine comes from the instructor's notes in
     sources/11.4-reinforcement-learning.tex, sources/11L-llm-alignment.tex, and
     sources/11.4S.tex.
     primary sources: Wei et al. 2021; Christiano et al. 2017;
                      Stiennon et al. 2020; Askell et al. 2021;
                      Ouyang et al. 2022; Schulman et al. 2017;
                      Rafailov et al. 2023; Gao et al. 2023;
                      Mitchell et al. 2019; Zheng et al. 2023;
                      Bai et al. 2022
     provenance note: all executable studies and figures are independently derived
     from displayed equations. External paper figures and library implementations
     were not reproduced. The finite-response, cyclic-preference, and proxy-pressure
     studies are book-original mechanism demonstrations, not natural-language RLHF
     or claims that any model is aligned. -->
<p>Chapter 17 ended with a distinction worth keeping in view—<strong>where the update lives is not what the update optimizes</strong>. Full fine-tuning, LoRA, and a soft prompt choose different places for gradient blame to write. None of them says what should count as a good answer.</p>
<p>This chapter changes that second choice. Pretraining asks for the next corpus token. Instruction tuning asks a model to imitate demonstrated responses. Preference learning asks which response wins a comparison. Online policy optimization asks a changing model to produce responses that score well under a reward signal. These supervision interfaces can often be paired with different update locations:</p>
<!-- NOVEL: needs sign-off -->
<div id="cell-fig-objective-write-map" class="cell" data-fig-height="5.1" data-fig-width="10" data-execution_count="2">
<div class="cell-output cell-output-display">
<div id="fig-objective-write-map" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A three-by-three map places demonstration imitation, preference margin, and sampled reward on the vertical axis, and full weights, LoRA or adapters, and soft prompts on the horizontal axis. Every intersection is marked as a possible design.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-objective-write-map-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="18-alignment_files/figure-html/fig-objective-write-map-output-1.png" alt="A three-by-three map places demonstration imitation, preference margin, and sampled reward on the vertical axis, and full weights, LoRA or adapters, and soft prompts on the horizontal axis. Every intersection is marked as a possible design." width="950" height="478" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-objective-write-map-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;18.1: The objective and the update location are separate design axes. Demonstration loss, a preference margin, or sampled reward can assign gradient blame while full weights, a low-rank branch, or continuous prompt vectors determine where that blame may write. The grid marks possible combinations, not a claim that they have equal capacity or cost.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The word <strong>alignment</strong> is sometimes used as though it named one algorithm or one finished property—here it will mean something narrower and checkable: changing a model’s behavior toward a stated objective, for a stated prompt distribution and a stated population of evaluators. Helpful, honest, and harmless are useful goals from the course lecture—they are not certificates that training can stamp onto a model.</p>
<p>The central problem is therefore a measurement problem. We need to specify whose judgment is collected, under which rubric, over which candidate responses, and what happens when optimization reaches beyond that coverage. Only then does it make sense to compare instruction tuning, reward-model pipelines, and direct preference optimization.</p>
<section id="same-model-different-supervision" class="level2" data-number="18.1">
<h2 data-number="18.1" class="anchored" data-anchor-id="same-model-different-supervision"><span class="header-section-number">18.1</span> Same model, different supervision</h2>
<p>Recall the causal language model from <a href="../part4/14-self-attention-transformer.html" class="quarto-xref"><span>Chapter 14</span></a>. Pretraining scores every corpus token that the model is asked to predict. In a prompt–response record, however, the prompt usually supplies the condition—the response supplies the supervised target. Let</p>
<p><span class="math display">\[
z=(x_1,\ldots,x_P,y_1,\ldots,y_T)
\]</span></p>
<p>be a serialized prompt <span class="math inline">\(x\)</span> followed by response <span class="math inline">\(y\)</span>. Define <span class="math inline">\(m_t=1\)</span> when token <span class="math inline">\(z_t\)</span> belongs to the response (including its end token) and <span class="math inline">\(m_t=0\)</span> for prompt or padding positions. A response-masked supervised fine-tuning objective is</p>
<p><span id="eq-sft-response-mask"><span class="math display">\[
\mathcal{L}_{\mathrm{SFT}}(\theta)
=-\E_{(x,y)\sim\mathcal{D}_{\mathrm{demo}}}
\left[
\frac{1}{\sum_t m_t}
\sum_{t=2}^{P+T}m_t\log\pi_\theta(z_t\mid z_{&lt;t})
\right].
\tag{18.1}\]</span></span></p>
<p>The denominator makes the displayed version a mean per scored response token. Some implementations sum instead—the choice changes gradient scale and must be stated. This is the book’s founding instance of the audit habit from <a href="../part1/04-training-loss-sgd.html#sec-04-estimator-cases" class="quarto-xref"><span>Section 4.6.1</span></a>: Case 1 within the mask, with the denominator itself part of the protocol. The prompt is still essential because it conditions every response probability. It simply does not receive target loss in this version.</p>
<p>The tensor contract is explicit: <code>logits</code> has shape <span class="math inline">\((B,L,V)\)</span>, token IDs and the mask have shape <span class="math inline">\((B,L)\)</span>, and the returned sequence score has shape <span class="math inline">\((B,)\)</span>. The helper below audits that excluded prompt and padding targets cannot change that score.</p>
<!-- NOVEL: needs sign-off -->
<div id="cdf08508" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Coding hygiene: audit completion-only sequence log probabilities</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> completion_log_probability(</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>    logits: Tensor, token_ids: Tensor, response_mask: Tensor</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>) <span class="op">-&gt;</span> Tensor:</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Sum next-token log probabilities only at response positions."""</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> logits.shape[:<span class="dv">2</span>] <span class="op">!=</span> token_ids.shape <span class="kw">or</span> token_ids.shape <span class="op">!=</span> response_mask.shape:</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="st">"logits, token IDs, and mask must share batch and time"</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    next_token_logps <span class="op">=</span> F.log_softmax(logits[:, :<span class="op">-</span><span class="dv">1</span>], dim<span class="op">=-</span><span class="dv">1</span>).gather(</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>        dim<span class="op">=-</span><span class="dv">1</span>, index<span class="op">=</span>token_ids[:, <span class="dv">1</span>:].unsqueeze(<span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    ).squeeze(<span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (next_token_logps <span class="op">*</span> response_mask[:, <span class="dv">1</span>:]).<span class="bu">sum</span>(dim<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>token_ids <span class="op">=</span> torch.tensor([</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">0</span>],</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">9</span>, <span class="dv">6</span>, <span class="dv">0</span>],</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>response_mask <span class="op">=</span> torch.tensor([</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    [<span class="va">False</span>, <span class="va">False</span>, <span class="va">False</span>, <span class="va">True</span>, <span class="va">True</span>, <span class="va">True</span>, <span class="va">False</span>],</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    [<span class="va">False</span>, <span class="va">False</span>, <span class="va">True</span>, <span class="va">True</span>, <span class="va">True</span>, <span class="va">True</span>, <span class="va">False</span>],</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>toy_logits <span class="op">=</span> torch.randn(<span class="dv">2</span>, <span class="dv">7</span>, <span class="dv">11</span>)</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>original_logps <span class="op">=</span> completion_log_probability(toy_logits, token_ids, response_mask)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>perturbed_logits <span class="op">=</span> toy_logits.clone()</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>inactive_predictors <span class="op">=</span> <span class="op">~</span>response_mask[:, <span class="dv">1</span>:]</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>perturbed_logits[:, :<span class="op">-</span><span class="dv">1</span>][inactive_predictors] <span class="op">=</span> torch.linspace(<span class="op">-</span><span class="dv">5</span>, <span class="dv">5</span>, <span class="dv">11</span>)</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>perturbed_logps <span class="op">=</span> completion_log_probability(</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>    perturbed_logits, token_ids, response_mask</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"scored response tokens:"</span>, response_mask[:, <span class="dv">1</span>:].<span class="bu">sum</span>(dim<span class="op">=</span><span class="dv">1</span>).tolist())</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>    <span class="st">"largest change after perturbing prompt/padding predictions:"</span>,</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"</span><span class="sc">{</span>(perturbed_logps <span class="op">-</span> original_logps)<span class="sc">.</span><span class="bu">abs</span>()<span class="sc">.</span><span class="bu">max</span>()<span class="sc">.</span>item()<span class="sc">:.2e}</span><span class="ss">"</span>,</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>scored response tokens: [3, 4]
largest change after perturbing prompt/padding predictions: 0.00e+00</code></pre>
</div>
</div>
<p><strong>Instruction tuning</strong> is supervised fine-tuning on one or more tasks expressed through natural-language instructions. It changes the organization of the data—not the optimizer. FLAN, for example, studied whether instruction tuning across many tasks improved transfer to held-out tasks. That is an empirical result about its models and scale—not a theorem that every instruction dataset generalizes.</p>
<p>The lecture shorthand says SFT teaches format while preferences teach quality—a distinction that is too sharp. A carefully written demonstration can teach facts, style, safety behavior, and substantive quality. <a href="#eq-sft-response-mask" class="quarto-xref">Equation&nbsp;<span>18.1</span></a> says what SFT actually guarantees: it rewards probability assigned to demonstrated response tokens. It does not directly say why one unobserved response should be preferred to another.</p>
<p>Comparisons offer a different interface. For one prompt, a reviewer can sometimes choose between two candidates more reliably than they can write an ideal response from scratch. That generation–evaluation gap motivates preference data. It does not make comparison cheap in every domain, remove the need for expertise, or turn a judgment into universal truth.</p>
</section>
<section id="a-preference-is-a-measurement-not-a-value" class="level2" data-number="18.2">
<h2 data-number="18.2" class="anchored" data-anchor-id="a-preference-is-a-measurement-not-a-value"><span class="header-section-number">18.2</span> A preference is a measurement, not a value</h2>
<p>One preference record contains a prompt <span class="math inline">\(x\)</span>, a response judged better <span class="math inline">\(y_w\)</span>, and a response judged worse <span class="math inline">\(y_l\)</span>:</p>
<p><span class="math display">\[
(x,y_w,y_l)\in\mathcal{D}_{\mathrm{pref}}.
\]</span></p>
<p>The subscript <span class="math inline">\(w\)</span> means <em>winner under this comparison</em>—not that the response is absolutely correct, harmless, or good. The label depends on the rubric, the reviewer population, the order in which candidates were displayed, and the policy that generated the candidates. Ties and disagreement are data, too; silently forcing them into a total order hides uncertainty.</p>
<p>To turn comparisons into a trainable scalar score, many pipelines use the <strong>Bradley–Terry model</strong>. A reward model <span class="math inline">\(r_\phi(x,y)\in\mathbb{R}\)</span> assigns a score to each completed response. The probability of preferring one response depends on the score difference:</p>
<p><span id="eq-bradley-terry"><span class="math display">\[
P_\phi(y_w\succ y_l\mid x)
=\sigma\!\left(r_\phi(x,y_w)-r_\phi(x,y_l)\right).
\tag{18.2}\]</span></span></p>
<p>This is the sigmoid from <a href="../part1/02-logistic-softmax.html" class="quarto-xref"><span>Chapter 2</span></a>. The corresponding negative log-likelihood is ordinary binary cross-entropy on a difference of scores:</p>
<p><span id="eq-reward-model-loss"><span class="math display">\[
\mathcal{L}_{\mathrm{RM}}(\phi)
=-\E_{(x,y_w,y_l)\sim\mathcal{D}_{\mathrm{pref}}}
\log\sigma\!\left(r_\phi(x,y_w)-r_\phi(x,y_l)\right).
\tag{18.3}\]</span></span></p>
<p>Only differences are identified. Adding any prompt-dependent constant <span class="math inline">\(c(x)\)</span> to every candidate reward leaves <a href="#eq-bradley-terry" class="quarto-xref">Equation&nbsp;<span>18.2</span></a> unchanged. The model learns a ruler—one with no identifiable zero point.</p>
<p>There is a deeper assumption: all comparisons for one prompt must be representable by one scalar ordering. Let <span class="math inline">\(\vect{r}=(r_A,r_B,r_C)^\top\in\mathbb{R}^3\)</span>. Let the rows of <span class="math inline">\(\matr{B}\in\mathbb{R}^{3\times3}\)</span> encode <span class="math inline">\(A-B\)</span>, <span class="math inline">\(B-C\)</span>, and <span class="math inline">\(C-A\)</span>. Then <span class="math inline">\(\matr{B}\vect{r}\)</span> contains their three score differences. A transitive set of probabilities can come from a score vector. A cycle that prefers each response to the next cannot:</p>
<!-- NOVEL: needs sign-off -->
<div id="cell-fig-preference-consistency" class="cell" data-fig-height="3.8" data-fig-width="10" data-execution_count="4">
<details class="code-fold">
<summary>Experiment: make the scalar-reward assumption fail on a preference cycle</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>incidence <span class="op">=</span> torch.tensor([</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    [<span class="fl">1.0</span>, <span class="op">-</span><span class="fl">1.0</span>, <span class="fl">0.0</span>],</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    [<span class="fl">0.0</span>, <span class="fl">1.0</span>, <span class="op">-</span><span class="fl">1.0</span>],</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    [<span class="op">-</span><span class="fl">1.0</span>, <span class="fl">0.0</span>, <span class="fl">1.0</span>],</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>transitive_scores <span class="op">=</span> torch.tensor([<span class="fl">1.0</span>, <span class="fl">0.0</span>, <span class="op">-</span><span class="fl">1.0</span>])</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>transitive_targets <span class="op">=</span> torch.sigmoid(incidence <span class="op">@</span> transitive_scores)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>fitted_transitive <span class="op">=</span> torch.linalg.lstsq(</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    incidence, torch.logit(transitive_targets)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>).solution</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>fitted_transitive <span class="op">-=</span> fitted_transitive.mean()</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>cyclic_targets <span class="op">=</span> torch.full((<span class="dv">3</span>,), <span class="fl">0.70</span>)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>fitted_cyclic <span class="op">=</span> torch.linalg.lstsq(</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>    incidence, torch.logit(cyclic_targets)</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>).solution</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>fitted_cyclic <span class="op">-=</span> fitted_cyclic.mean()</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>cyclic_predictions <span class="op">=</span> torch.sigmoid(incidence <span class="op">@</span> fitted_cyclic)</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>scalar_loss <span class="op">=</span> F.binary_cross_entropy(cyclic_predictions, cyclic_targets)</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>edgewise_floor <span class="op">=</span> F.binary_cross_entropy(cyclic_targets, cyclic_targets)</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="fl">3.8</span>))</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>positions <span class="op">=</span> {<span class="st">"A"</span>: (<span class="fl">0.5</span>, <span class="fl">0.92</span>), <span class="st">"B"</span>: (<span class="fl">0.08</span>, <span class="fl">0.12</span>), <span class="st">"C"</span>: (<span class="fl">0.92</span>, <span class="fl">0.12</span>)}</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> draw_preference_triangle(</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>    axis: Axes, edges: <span class="bu">list</span>[<span class="bu">tuple</span>[<span class="bu">str</span>, <span class="bu">str</span>, <span class="bu">str</span>]], title: <span class="bu">str</span></span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>) <span class="op">-&gt;</span> <span class="va">None</span>:</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>    axis.set_xlim(<span class="op">-</span><span class="fl">0.12</span>, <span class="fl">1.12</span>)</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>    axis.set_ylim(<span class="op">-</span><span class="fl">0.08</span>, <span class="fl">1.08</span>)</span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a>    axis.axis(<span class="st">"off"</span>)</span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> name, (x_pos, y_pos) <span class="kw">in</span> positions.items():</span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a>        axis.scatter(x_pos, y_pos, s<span class="op">=</span><span class="dv">820</span>, color<span class="op">=</span><span class="st">"#F3F4F6"</span>, edgecolor<span class="op">=</span>navy, zorder<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>        axis.text(x_pos, y_pos, name, ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"center"</span>, color<span class="op">=</span>navy,</span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a>                  fontsize<span class="op">=</span><span class="dv">12</span>, weight<span class="op">=</span><span class="st">"bold"</span>, zorder<span class="op">=</span><span class="dv">4</span>)</span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> start, end, label <span class="kw">in</span> edges:</span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a>        x0, y0 <span class="op">=</span> positions[start]</span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a>        x1, y1 <span class="op">=</span> positions[end]</span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a>        axis.annotate(<span class="st">""</span>, xy<span class="op">=</span>(x1, y1), xytext<span class="op">=</span>(x0, y0),</span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a>                      arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>, color<span class="op">=</span>orange, lw<span class="op">=</span><span class="fl">1.8</span>,</span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a>                                      shrinkA<span class="op">=</span><span class="dv">22</span>, shrinkB<span class="op">=</span><span class="dv">22</span>))</span>
<span id="cb3-42"><a href="#cb3-42" aria-hidden="true" tabindex="-1"></a>        axis.text((x0 <span class="op">+</span> x1) <span class="op">/</span> <span class="dv">2</span>, (y0 <span class="op">+</span> y1) <span class="op">/</span> <span class="dv">2</span>, label, ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"center"</span>,</span>
<span id="cb3-43"><a href="#cb3-43" aria-hidden="true" tabindex="-1"></a>                  fontsize<span class="op">=</span><span class="fl">8.2</span>, color<span class="op">=</span>wine,</span>
<span id="cb3-44"><a href="#cb3-44" aria-hidden="true" tabindex="-1"></a>                  bbox<span class="op">=</span><span class="bu">dict</span>(facecolor<span class="op">=</span><span class="st">"white"</span>, edgecolor<span class="op">=</span><span class="st">"none"</span>, pad<span class="op">=</span><span class="fl">1.0</span>))</span>
<span id="cb3-45"><a href="#cb3-45" aria-hidden="true" tabindex="-1"></a>    axis.set_title(title, color<span class="op">=</span>navy, fontsize<span class="op">=</span><span class="fl">10.5</span>, weight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb3-46"><a href="#cb3-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-47"><a href="#cb3-47" aria-hidden="true" tabindex="-1"></a>draw_preference_triangle(</span>
<span id="cb3-48"><a href="#cb3-48" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">0</span>], [(<span class="st">"A"</span>, <span class="st">"B"</span>, <span class="st">"0.731"</span>), (<span class="st">"B"</span>, <span class="st">"C"</span>, <span class="st">"0.731"</span>),</span>
<span id="cb3-49"><a href="#cb3-49" aria-hidden="true" tabindex="-1"></a>              (<span class="st">"A"</span>, <span class="st">"C"</span>, <span class="st">"0.881"</span>)],</span>
<span id="cb3-50"><a href="#cb3-50" aria-hidden="true" tabindex="-1"></a>    <span class="st">"scalar scores are consistent"</span>,</span>
<span id="cb3-51"><a href="#cb3-51" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-52"><a href="#cb3-52" aria-hidden="true" tabindex="-1"></a>draw_preference_triangle(</span>
<span id="cb3-53"><a href="#cb3-53" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">1</span>], [(<span class="st">"A"</span>, <span class="st">"B"</span>, <span class="st">"0.70"</span>), (<span class="st">"B"</span>, <span class="st">"C"</span>, <span class="st">"0.70"</span>),</span>
<span id="cb3-54"><a href="#cb3-54" aria-hidden="true" tabindex="-1"></a>              (<span class="st">"C"</span>, <span class="st">"A"</span>, <span class="st">"0.70"</span>)],</span>
<span id="cb3-55"><a href="#cb3-55" aria-hidden="true" tabindex="-1"></a>    <span class="st">"the cycle has no scalar solution"</span>,</span>
<span id="cb3-56"><a href="#cb3-56" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-57"><a href="#cb3-57" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].bar([<span class="dv">0</span>, <span class="dv">1</span>], [edgewise_floor.item(), scalar_loss.item()],</span>
<span id="cb3-58"><a href="#cb3-58" aria-hidden="true" tabindex="-1"></a>            color<span class="op">=</span>[green, orange], width<span class="op">=</span><span class="fl">0.62</span>)</span>
<span id="cb3-59"><a href="#cb3-59" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_xticks([<span class="dv">0</span>, <span class="dv">1</span>], [<span class="st">"edgewise</span><span class="ch">\n</span><span class="st">probabilities"</span>, <span class="st">"one scalar</span><span class="ch">\n</span><span class="st">reward"</span>])</span>
<span id="cb3-60"><a href="#cb3-60" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_ylabel(<span class="st">"mean preference log loss"</span>)</span>
<span id="cb3-61"><a href="#cb3-61" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_ylim(<span class="fl">0.57</span>, <span class="fl">0.72</span>)</span>
<span id="cb3-62"><a href="#cb3-62" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].grid(axis<span class="op">=</span><span class="st">"y"</span>, alpha<span class="op">=</span><span class="fl">0.18</span>)</span>
<span id="cb3-63"><a href="#cb3-63" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_title(<span class="st">"misspecification has a cost"</span>, color<span class="op">=</span>navy,</span>
<span id="cb3-64"><a href="#cb3-64" aria-hidden="true" tabindex="-1"></a>                  fontsize<span class="op">=</span><span class="fl">10.5</span>, weight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb3-65"><a href="#cb3-65" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> index, value <span class="kw">in</span> <span class="bu">enumerate</span>([edgewise_floor.item(), scalar_loss.item()]):</span>
<span id="cb3-66"><a href="#cb3-66" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">2</span>].text(index, value <span class="op">+</span> <span class="fl">0.006</span>, <span class="ss">f"</span><span class="sc">{</span>value<span class="sc">:.6f}</span><span class="ss">"</span>, ha<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="fl">8.5</span>)</span>
<span id="cb3-67"><a href="#cb3-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-68"><a href="#cb3-68" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb3-69"><a href="#cb3-69" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb3-70"><a href="#cb3-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-71"><a href="#cb3-71" aria-hidden="true" tabindex="-1"></a>shifted_probabilities <span class="op">=</span> torch.sigmoid(incidence <span class="op">@</span> (fitted_transitive <span class="op">+</span> <span class="fl">37.0</span>))</span>
<span id="cb3-72"><a href="#cb3-72" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"recovered centered scores:"</span>, [<span class="bu">round</span>(x, <span class="dv">6</span>) <span class="cf">for</span> x <span class="kw">in</span> fitted_transitive.tolist()])</span>
<span id="cb3-73"><a href="#cb3-73" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"cyclic scalar predictions:"</span>, [<span class="bu">round</span>(x, <span class="dv">6</span>) <span class="cf">for</span> x <span class="kw">in</span> cyclic_predictions.tolist()])</span>
<span id="cb3-74"><a href="#cb3-74" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"cyclic scalar loss: </span><span class="sc">{</span>scalar_loss<span class="sc">.</span>item()<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb3-75"><a href="#cb3-75" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"unconstrained edgewise floor: </span><span class="sc">{</span>edgewise_floor<span class="sc">.</span>item()<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb3-76"><a href="#cb3-76" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"irreducible scalar gap: </span><span class="sc">{</span>(scalar_loss <span class="op">-</span> edgewise_floor)<span class="sc">.</span>item()<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb3-77"><a href="#cb3-77" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(</span>
<span id="cb3-78"><a href="#cb3-78" aria-hidden="true" tabindex="-1"></a>    <span class="st">"largest probability change after adding 37 to every reward:"</span>,</span>
<span id="cb3-79"><a href="#cb3-79" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"</span><span class="sc">{</span>(shifted_probabilities <span class="op">-</span> transitive_targets)<span class="sc">.</span><span class="bu">abs</span>()<span class="sc">.</span><span class="bu">max</span>()<span class="sc">.</span>item()<span class="sc">:.2e}</span><span class="ss">"</span>,</span>
<span id="cb3-80"><a href="#cb3-80" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-preference-consistency" class="quarto-float quarto-figure quarto-figure-center anchored" alt="The left triangle shows transitive arrows consistent with scores one, zero, and minus one. The middle triangle shows a cyclic 0.70 preference on all three arrows. The right bars compare the unconstrained and scalar-model log losses.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-preference-consistency-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="18-alignment_files/figure-html/fig-preference-consistency-output-1.png" alt="The left triangle shows transitive arrows consistent with scores one, zero, and minus one. The middle triangle shows a cyclic 0.70 preference on all three arrows. The right bars compare the unconstrained and scalar-model log losses." width="950" height="354" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-preference-consistency-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;18.2: A scalar reward can express the transitive comparisons generated by centered scores (1, 0, -1), but not a symmetric cycle in which A beats B, B beats C, and C beats A with probability 0.70. Least squares returns equal scalar scores for the cycle, so Bradley–Terry predicts 0.50 on every edge. Its mean log loss is log 2 = 0.693147, above the unconstrained per-edge entropy 0.610864 by 0.082283.
</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>recovered centered scores: [1.0, -0.0, -1.0]
cyclic scalar predictions: [0.5, 0.5, 0.5]
cyclic scalar loss: 0.693147
unconstrained edgewise floor: 0.610864
irreducible scalar gap: 0.082283
largest probability change after adding 37 to every reward: 0.00e+00</code></pre>
</div>
</div>
<p>The cycle is not a pathology in the code. Summing the three Bradley–Terry logits would require</p>
<p><span class="math display">\[
(r_A-r_B)+(r_B-r_C)+(r_C-r_A)
=3\operatorname{logit}(0.70),
\]</span></p>
<p>but the left side cancels to zero while the right side is positive. Aggregated human judgments can contain cycles because reviewers differ, context changes, or preferences are genuinely plural. A scalar reward model compresses that structure; it does not discover a hidden universal value.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Trap: a preferred response is not scalar ground truth
</div>
</div>
<div class="callout-body-container callout-body">
<p>A pair says which presented response won under one prompt, rubric, candidate set, and review process. Report ties and disagreement, split by prompt rather than by correlated pairs, and state who supplied the judgments. Bradley–Terry is a useful model of those measurements, not proof that one population-independent reward exists.</p>
</div>
</div>
</section>
<section id="train-a-judge-then-try-to-please-the-judge" class="level2" data-number="18.3">
<h2 data-number="18.3" class="anchored" data-anchor-id="train-a-judge-then-try-to-please-the-judge"><span class="header-section-number">18.3</span> Train a judge, then try to please the judge</h2>
<p>What can we do with pairwise measurements? The classic language-model RLHF pipeline separates two learned objects:</p>
<ol type="1">
<li>a <strong>reward model</strong> learns to score completed responses from comparisons; and</li>
<li>a <strong>policy</strong> learns to generate responses that receive high score.</li>
</ol>
<p>This is the course’s memorable description—<em>train a judge, then try to please the judge</em>. The word <em>judge</em> matters. A reward model is a learned proxy for a feedback process, not the feedback process itself.</p>
<!-- NOVEL: needs sign-off -->
<div id="cell-fig-rlhf-pipeline" class="cell" data-fig-height="5.8" data-fig-width="10" data-execution_count="5">
<div class="cell-output cell-output-display">
<div id="fig-rlhf-pipeline" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A top data path runs from demonstrations through SFT, candidate responses, preference labels, and a reward model. A lower optimization loop runs from a current policy through rollouts and shaped return to a PPO update, with separate arrows from a fixed reference policy and a value function.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rlhf-pipeline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="18-alignment_files/figure-html/fig-rlhf-pipeline-output-1.png" alt="A top data path runs from demonstrations through SFT, candidate responses, preference labels, and a reward model. A lower optimization loop runs from a current policy through rollouts and shaped return to a PPO update, with separate arrows from a fixed reference policy and a value function." width="950" height="547" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rlhf-pipeline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;18.3: An original map of a reward-model RLHF pipeline. Demonstrations produce an SFT policy; sampled candidates and comparisons train a reward model. During online policy optimization, the current rollout policy produces responses, the frozen reward model scores them, and a fixed reference policy supplies a separate KL anchor. A value function estimates future shaped return from prefixes; it is not the reward model. PPO’s old-policy anchor is refreshed with rollout batches, while the reference anchor usually remains fixed.
</figcaption>
</figure>
</div>
</div>
</div>
<p>In language generation, the <strong>state</strong> <span class="math inline">\(s_t\)</span> is the prompt plus tokens generated so far, the <strong>action</strong> <span class="math inline">\(a_t\)</span> is the next token, and the policy is <span class="math inline">\(\pi_\theta(a_t\mid s_t)\)</span>. A reward model often scores the completed response. A separate value function <span class="math inline">\(V_\psi(s_t)\)</span> estimates expected future shaped return from a prefix so that policy-gradient updates can assign credit across token decisions. Calling the reward model PPO’s <em>critic</em> conflates those two roles—completed-response scoring and prefix-value forecasting.</p>
<p>For a fixed prompt, suppose there are <span class="math inline">\(K\)</span> complete candidate responses. Let <span class="math inline">\(\vect{r}\in\mathbb{R}^K\)</span> contain their reward-model scores, and let <span class="math inline">\(\vect{\pi},\vect{\pi}_{\mathrm{ref}}\in\mathbb{R}^K\)</span> be positive probability vectors that each sum to one. A clean regularized objective is</p>
<p><span id="eq-kl-regularized-objective"><span class="math display">\[
J(\vect{\pi})
=\sum_{i=1}^K\pi_i r_i
-\beta D_{\mathrm{KL}}
\!\left(\vect{\pi}\,\|\,\vect{\pi}_{\mathrm{ref}}\right),
\qquad \beta&gt;0,
\tag{18.4}\]</span></span></p>
<p>where</p>
<p><span class="math display">\[
D_{\mathrm{KL}}(\vect{\pi}\,\|\,\vect{\pi}_{\mathrm{ref}})
=\sum_{i=1}^K\pi_i\log\frac{\pi_i}{\pi_{\mathrm{ref},i}}.
\]</span></p>
<p>The first term seeks high proxy reward. The second charges for moving probability mass away from the reference. This is an objective to <strong>maximize</strong>—not a loss unless we negate it.</p>
<section id="the-exact-finite-response-policy" class="level3">
<h3 class="anchored" data-anchor-id="the-exact-finite-response-policy">The exact finite-response policy</h3>
<p>Before discussing an optimizer, let us solve the finite problem. Add a Lagrange multiplier <span class="math inline">\(\lambda\)</span> for <span class="math inline">\(\sum_i\pi_i=1\)</span>. Differentiating with respect to one probability gives</p>
<p><span class="math display">\[
r_i-\beta\left(\log\frac{\pi_i}{\pi_{\mathrm{ref},i}}+1\right)+\lambda=0.
\]</span></p>
<p>Rearrange and absorb terms independent of <span class="math inline">\(i\)</span> into a normalizer:</p>
<p><span id="eq-gibbs-policy"><span class="math display">\[
\pi^*(y_i\mid x)
=\frac{\pi_{\mathrm{ref}}(y_i\mid x)
\exp\!\left(r(x,y_i)/\beta\right)}
{Z(x)},
\qquad
Z(x)=\sum_{j=1}^K\pi_{\mathrm{ref}}(y_j\mid x)
\exp\!\left(r(x,y_j)/\beta\right).
\tag{18.5}\]</span></span></p>
<p><a href="#eq-gibbs-policy" class="quarto-xref">Equation&nbsp;<span>18.5</span></a> is a reference distribution tilted toward higher reward. Large <span class="math inline">\(\beta\)</span> resists movement; small <span class="math inline">\(\beta\)</span> applies more reward pressure. It is a stay-near dial—not a truth or safety guarantee.</p>
<p>Consider four possible responses with</p>
<p><span class="math display">\[
\vect{\pi}_{\mathrm{ref}}=(0.55,0.25,0.15,0.05),
\qquad
\vect{r}=(0,1,2,3).
\]</span></p>
<p>The reference favors response A while the proxy favors D. The exact solution lets us watch probability move without sampling noise or a language model:</p>
<!-- NOVEL: needs sign-off -->
<div id="cell-fig-reference-tilt" class="cell" data-fig-height="4.2" data-fig-width="10" data-execution_count="6">
<details class="code-fold">
<summary>Experiment: solve the KL-regularized finite-response policy exactly</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> gibbs_policy(reference: Tensor, reward: Tensor, beta: <span class="bu">float</span>) <span class="op">-&gt;</span> Tensor:</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> torch.softmax(torch.log(reference) <span class="op">+</span> reward <span class="op">/</span> beta, dim<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> kl_divergence(policy: Tensor, reference: Tensor) <span class="op">-&gt;</span> Tensor:</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (policy <span class="op">*</span> (torch.log(policy) <span class="op">-</span> torch.log(reference))).<span class="bu">sum</span>()</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>reference <span class="op">=</span> torch.tensor([<span class="fl">0.55</span>, <span class="fl">0.25</span>, <span class="fl">0.15</span>, <span class="fl">0.05</span>])</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>reward <span class="op">=</span> torch.tensor([<span class="fl">0.0</span>, <span class="fl">1.0</span>, <span class="fl">2.0</span>, <span class="fl">3.0</span>])</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>shown_betas <span class="op">=</span> [<span class="fl">4.0</span>, <span class="fl">1.0</span>, <span class="fl">0.5</span>]</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>shown_policies <span class="op">=</span> [gibbs_policy(reference, reward, beta) <span class="cf">for</span> beta <span class="kw">in</span> shown_betas]</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="fl">4.2</span>))</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>x_positions <span class="op">=</span> torch.arange(<span class="dv">4</span>).numpy()</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>width <span class="op">=</span> <span class="fl">0.18</span></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].bar(x_positions <span class="op">-</span> <span class="fl">1.5</span> <span class="op">*</span> width, reference.numpy(), width,</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>            label<span class="op">=</span><span class="st">"reference"</span>, color<span class="op">=</span><span class="st">"#B8BCC4"</span>)</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> offset, beta, policy, color <span class="kw">in</span> <span class="bu">zip</span>(</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>    [<span class="op">-</span><span class="fl">0.5</span>, <span class="fl">0.5</span>, <span class="fl">1.5</span>], shown_betas, shown_policies, [green, orange, wine]</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>):</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">0</span>].bar(x_positions <span class="op">+</span> offset <span class="op">*</span> width, policy.numpy(), width,</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>                label<span class="op">=</span><span class="vs">fr"</span><span class="dv">$\b</span><span class="vs">eta=</span><span class="sc">{</span>beta<span class="sc">:g}</span><span class="dv">$</span><span class="vs">"</span>, color<span class="op">=</span>color)</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xticks(x_positions, [<span class="st">"A"</span>, <span class="st">"B"</span>, <span class="st">"C"</span>, <span class="st">"D"</span>])</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"response probability"</span>)</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">"reward tilts a reference"</span>, color<span class="op">=</span>navy, weight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].grid(axis<span class="op">=</span><span class="st">"y"</span>, alpha<span class="op">=</span><span class="fl">0.18</span>)</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>sweep_betas <span class="op">=</span> torch.logspace(math.log10(<span class="fl">8.0</span>), math.log10(<span class="fl">0.2</span>), <span class="dv">80</span>)</span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>sweep_policies <span class="op">=</span> torch.stack([</span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>    gibbs_policy(reference, reward, beta.item()) <span class="cf">for</span> beta <span class="kw">in</span> sweep_betas</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>sweep_rewards <span class="op">=</span> sweep_policies <span class="op">@</span> reward</span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a>sweep_kls <span class="op">=</span> torch.stack([</span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a>    kl_divergence(policy, reference) <span class="cf">for</span> policy <span class="kw">in</span> sweep_policies</span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].plot(sweep_kls.numpy(), sweep_rewards.numpy(), color<span class="op">=</span>wine, lw<span class="op">=</span><span class="fl">2.2</span>)</span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> beta, color <span class="kw">in</span> <span class="bu">zip</span>(shown_betas, [green, orange, wine]):</span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a>    policy <span class="op">=</span> gibbs_policy(reference, reward, beta)</span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">1</span>].scatter(kl_divergence(policy, reference).item(),</span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a>                    (policy <span class="op">@</span> reward).item(), color<span class="op">=</span>color, s<span class="op">=</span><span class="dv">45</span>, zorder<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">1</span>].annotate(<span class="vs">fr"</span><span class="dv">$\b</span><span class="vs">eta=</span><span class="sc">{</span>beta<span class="sc">:g}</span><span class="dv">$</span><span class="vs">"</span>,</span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a>                     (kl_divergence(policy, reference).item(), (policy <span class="op">@</span> reward).item()),</span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a>                     xytext<span class="op">=</span>(<span class="dv">5</span>, <span class="dv">5</span>), textcoords<span class="op">=</span><span class="st">"offset points"</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xlabel(<span class="vs">r"</span><span class="dv">$</span><span class="vs">D_{</span><span class="dv">\m</span><span class="vs">athrm{KL}}</span><span class="kw">(</span><span class="er">\</span><span class="vs">pi</span><span class="er">\</span><span class="vs">Vert</span><span class="er">\</span><span class="vs">pi_{</span><span class="ch">\r</span><span class="vs">m ref}</span><span class="kw">)</span><span class="dv">$</span><span class="vs">"</span>)</span>
<span id="cb5-47"><a href="#cb5-47" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_ylabel(<span class="st">"expected proxy reward"</span>)</span>
<span id="cb5-48"><a href="#cb5-48" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">"more pressure buys more proxy score"</span>, color<span class="op">=</span>navy, weight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb5-49"><a href="#cb5-49" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].grid(alpha<span class="op">=</span><span class="fl">0.18</span>)</span>
<span id="cb5-50"><a href="#cb5-50" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb5-51"><a href="#cb5-51" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb5-52"><a href="#cb5-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-53"><a href="#cb5-53" aria-hidden="true" tabindex="-1"></a>target_policy <span class="op">=</span> gibbs_policy(reference, reward, <span class="fl">1.0</span>)</span>
<span id="cb5-54"><a href="#cb5-54" aria-hidden="true" tabindex="-1"></a>shifted_target <span class="op">=</span> gibbs_policy(reference, reward <span class="op">+</span> <span class="fl">37.0</span>, <span class="fl">1.0</span>)</span>
<span id="cb5-55"><a href="#cb5-55" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"beta  expected reward  KL to reference"</span>)</span>
<span id="cb5-56"><a href="#cb5-56" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> beta <span class="kw">in</span> [<span class="fl">4.0</span>, <span class="fl">2.0</span>, <span class="fl">1.0</span>, <span class="fl">0.5</span>, <span class="fl">0.25</span>]:</span>
<span id="cb5-57"><a href="#cb5-57" aria-hidden="true" tabindex="-1"></a>    policy <span class="op">=</span> gibbs_policy(reference, reward, beta)</span>
<span id="cb5-58"><a href="#cb5-58" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(</span>
<span id="cb5-59"><a href="#cb5-59" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>beta<span class="sc">:4.3g}</span><span class="ss">      </span><span class="sc">{</span>(policy <span class="op">@</span> reward)<span class="sc">.</span>item()<span class="sc">:.6f}</span><span class="ss">"</span></span>
<span id="cb5-60"><a href="#cb5-60" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"          </span><span class="sc">{</span>kl_divergence(policy, reference)<span class="sc">.</span>item()<span class="sc">:.6f}</span><span class="ss">"</span></span>
<span id="cb5-61"><a href="#cb5-61" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb5-62"><a href="#cb5-62" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"beta=1 policy:"</span>, [<span class="bu">round</span>(x, <span class="dv">6</span>) <span class="cf">for</span> x <span class="kw">in</span> target_policy.tolist()])</span>
<span id="cb5-63"><a href="#cb5-63" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(</span>
<span id="cb5-64"><a href="#cb5-64" aria-hidden="true" tabindex="-1"></a>    <span class="st">"largest policy change after adding 37 to every reward:"</span>,</span>
<span id="cb5-65"><a href="#cb5-65" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"</span><span class="sc">{</span>(shifted_target <span class="op">-</span> target_policy)<span class="sc">.</span><span class="bu">abs</span>()<span class="sc">.</span><span class="bu">max</span>()<span class="sc">.</span>item()<span class="sc">:.2e}</span><span class="ss">"</span>,</span>
<span id="cb5-66"><a href="#cb5-66" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-reference-tilt" class="quarto-float quarto-figure quarto-figure-center anchored" alt="The left grouped bars show reference probabilities and exact policies at beta four, one, and one half for responses A through D. The right curve shows expected proxy reward increasing with KL divergence from the reference as beta decreases.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-reference-tilt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="18-alignment_files/figure-html/fig-reference-tilt-output-1.png" alt="The left grouped bars show reference probabilities and exact policies at beta four, one, and one half for responses A through D. The right curve shows expected proxy reward increasing with KL divergence from the reference as beta decreases." width="952" height="393" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-reference-tilt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;18.4: The exact four-response policy tilts the reference toward proxy reward. At beta 4, expected reward is 0.925670 and KL is 0.029159; at beta 1 they are 1.768029 and 0.561398; at beta 0.5 they are 2.559982 and 1.693801. Smaller beta purchases more proxy reward with more measured drift. This identity test assumes a complete finite response set and a correct scalar reward.
</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>beta  expected reward  KL to reference
   4      0.925670          0.029159
   2      1.191913          0.129706
   1      1.768029          0.561398
 0.5      2.559982          1.693801
0.25      2.944634          2.719127
beta=1 policy: [0.164562, 0.20333, 0.331625, 0.300483]
largest policy change after adding 37 to every reward: 8.33e-16</code></pre>
</div>
</div>
<p>The additive-reward audit echoes the preference experiment: multiplying every unnormalized policy weight by the same <span class="math inline">\(e^{37/\beta}\)</span> changes <span class="math inline">\(Z(x)\)</span> by that factor and leaves the normalized policy unchanged. Neither pairwise labels nor the regularized optimum identifies an absolute reward origin.</p>
</section>
<section id="ppo-in-outline-a-second-anchor" class="level3">
<h3 class="anchored" data-anchor-id="ppo-in-outline-a-second-anchor">PPO in outline: a second anchor</h3>
<p><a href="#eq-gibbs-policy" class="quarto-xref">Equation&nbsp;<span>18.5</span></a> optimizes directly over a finite probability vector—a language model instead has shared parameters, an enormous response space, and rewards that arrive mainly after a sequence is complete. Policy-gradient methods estimate how sampled token choices affected return. <strong>Proximal Policy Optimization (PPO)</strong> reuses a batch of trajectories while limiting the incentive for each sampled action ratio to move farther than a clipped interval.</p>
<p>For state <span class="math inline">\(s_t\)</span>, sampled action <span class="math inline">\(a_t\)</span>, current parameters <span class="math inline">\(\theta\)</span>, and the policy <span class="math inline">\(\pi_{\mathrm{old}}\)</span> that generated the batch, define</p>
<p><span class="math display">\[
\rho_t(\theta)
=\frac{\pi_\theta(a_t\mid s_t)}
{\pi_{\mathrm{old}}(a_t\mid s_t)}.
\]</span></p>
<p>If <span class="math inline">\(\widehat A_t\)</span> estimates whether that sampled action did better or worse than the value baseline, PPO maximizes the clipped surrogate</p>
<p><span id="eq-ppo-clip"><span class="math display">\[
L^{\mathrm{CLIP}}(\theta)
=\E_t\left[
\min\!\left(
\rho_t(\theta)\widehat A_t,
\operatorname{clip}(\rho_t(\theta),1-\epsilon,1+\epsilon)\widehat A_t
\right)
\right].
\tag{18.6}\]</span></span></p>
<p>This gives us two anchors—each with a different job:</p>
<ul>
<li><span class="math inline">\(\pi_{\mathrm{old}}\)</span> generated the current rollout batch. PPO refreshes it as training advances, and <a href="#eq-ppo-clip" class="quarto-xref">Equation&nbsp;<span>18.6</span></a> addresses stepwise optimization.</li>
<li><span class="math inline">\(\pi_{\mathrm{ref}}\)</span> is usually a fixed SFT policy. The KL term in <a href="#eq-kl-regularized-objective" class="quarto-xref">Equation&nbsp;<span>18.4</span></a> addresses accumulated drift from that reference.</li>
</ul>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>The old policy is not the reference policy
</div>
</div>
<div class="callout-body-container callout-body">
<p>PPO clipping is not a hard wall on the new policy—it removes favorable incentive for sampled ratios to move farther outside the interval; a sufficiently large optimizer step can still overshoot, and unsampled behavior can change. The fixed-reference KL discourages drift, but neither mechanism certifies retained capability or prevents proxy exploitation. Measure the realized KL and the behaviors that matter.</p>
</div>
</div>
</section>
</section>
<section id="when-the-proxy-becomes-the-target" class="level2" data-number="18.4">
<h2 data-number="18.4" class="anchored" data-anchor-id="when-the-proxy-becomes-the-target"><span class="header-section-number">18.4</span> When the proxy becomes the target</h2>
<p>The pipeline now has a vulnerable handoff—the reward model is validated on comparisons, but the policy is optimized to seek responses with high predicted reward. Those are different distributions—if the policy finds a region that the comparison data did not identify, excellent held-out reward-model loss can coexist with poor policy behavior.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>A designed mechanism study
</div>
</div>
<div class="callout-body-container callout-body">
<p>Evidence and length are planted features, the finite candidate set is fully known—its designed utility is available because we wrote it. The study demonstrates how coverage failure and proxy pressure can interact. It does not estimate the prevalence of reward hacking in natural-language systems or validate one alignment method over another.</p>
</div>
</div>
<p>Let us make that failure visible in a finite response world — and predict first: as reward pressure grows, will the narrow-feedback policy’s <em>designed</em> utility rise, plateau, or rise-then-collapse? Each synthetic response has two observable features:</p>
<ul>
<li>evidence <span class="math inline">\(e\)</span>, where larger means that more relevant support is present; and</li>
<li>length <span class="math inline">\(\ell\)</span>, a stand-in for surface polish or detail.</li>
</ul>
<p>The designed utility is</p>
<p><span id="eq-designed-utility"><span class="math display">\[
u(e,\ell)
=e+0.6\ell-1.2\max(\ell-1,0)^2.
\tag{18.7}\]</span></span></p>
<p>Inside the feedback range <span class="math inline">\(0\le\ell\le1\)</span>, the last feature is always zero. More detail helps there, so comparisons cannot reveal that excessive length should eventually become costly. We generate 20,000 noisy Bradley–Terry comparisons per seed and fit the linear reward model</p>
<p><span class="math display">\[
\widehat r(e,\ell)
=w_e e+w_\ell\ell+w_q\max(\ell-1,0)^2.
\]</span></p>
<p>Five complete runs use seeds 6050–6054. A <strong>narrow-feedback</strong> arm sees only <span class="math inline">\(\ell\in[0,1]\)</span>. A <strong>coverage-repair</strong> arm draws 20% of individual comparison responses from <span class="math inline">\(\ell\in[1,4)\)</span>, where the missing curvature becomes observable. Both models have the same feature class and optimizer:</p>
<!-- NOVEL: needs sign-off -->
<div id="0e26c0af" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Experiment: fit five reward models with and without the missing feedback region</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> reward_features(responses: Tensor) <span class="op">-&gt;</span> Tensor:</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    evidence <span class="op">=</span> responses[:, <span class="dv">0</span>]</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    length <span class="op">=</span> responses[:, <span class="dv">1</span>]</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> torch.stack(</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>        (evidence, length, torch.relu(length <span class="op">-</span> <span class="fl">1.0</span>).square()), dim<span class="op">=</span><span class="dv">1</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> designed_utility(responses: Tensor) <span class="op">-&gt;</span> Tensor:</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    designed_weights <span class="op">=</span> torch.tensor([<span class="fl">1.0</span>, <span class="fl">0.6</span>, <span class="op">-</span><span class="fl">1.2</span>])</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> reward_features(responses) <span class="op">@</span> designed_weights</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> draw_responses(</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>    count: <span class="bu">int</span>, generator: torch.Generator, out_of_range_fraction: <span class="bu">float</span></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>) <span class="op">-&gt;</span> Tensor:</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>    evidence <span class="op">=</span> torch.rand(count, generator<span class="op">=</span>generator)</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>    length <span class="op">=</span> torch.rand(count, generator<span class="op">=</span>generator)</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> out_of_range_fraction <span class="op">&gt;</span> <span class="fl">0.0</span>:</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>        outside <span class="op">=</span> torch.rand(count, generator<span class="op">=</span>generator) <span class="op">&lt;</span> out_of_range_fraction</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>        extended_length <span class="op">=</span> <span class="fl">1.0</span> <span class="op">+</span> <span class="fl">3.0</span> <span class="op">*</span> torch.rand(count, generator<span class="op">=</span>generator)</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>        length <span class="op">=</span> torch.where(outside, extended_length, length)</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> torch.stack((evidence, length), dim<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> fit_reward_model(</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>    seed: <span class="bu">int</span>, out_of_range_fraction: <span class="bu">float</span></span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a>) <span class="op">-&gt;</span> <span class="bu">tuple</span>[Tensor, <span class="bu">dict</span>[<span class="bu">str</span>, <span class="bu">float</span>]]:</span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>    generator <span class="op">=</span> torch.Generator().manual_seed(seed)</span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a>    count <span class="op">=</span> <span class="dv">20_000</span></span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>    left <span class="op">=</span> draw_responses(count, generator, out_of_range_fraction)</span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a>    right <span class="op">=</span> draw_responses(count, generator, out_of_range_fraction)</span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a>    feature_differences <span class="op">=</span> reward_features(left) <span class="op">-</span> reward_features(right)</span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a>    preference_probabilities <span class="op">=</span> torch.sigmoid(</span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a>        designed_utility(left) <span class="op">-</span> designed_utility(right)</span>
<span id="cb7-36"><a href="#cb7-36" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb7-37"><a href="#cb7-37" aria-hidden="true" tabindex="-1"></a>    labels <span class="op">=</span> torch.bernoulli(preference_probabilities, generator<span class="op">=</span>generator)</span>
<span id="cb7-38"><a href="#cb7-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-39"><a href="#cb7-39" aria-hidden="true" tabindex="-1"></a>    weights <span class="op">=</span> nn.Parameter(torch.zeros(<span class="dv">3</span>))</span>
<span id="cb7-40"><a href="#cb7-40" aria-hidden="true" tabindex="-1"></a>    optimizer <span class="op">=</span> torch.optim.Adam([weights], lr<span class="op">=</span><span class="fl">0.05</span>)</span>
<span id="cb7-41"><a href="#cb7-41" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">900</span>):</span>
<span id="cb7-42"><a href="#cb7-42" aria-hidden="true" tabindex="-1"></a>        logits <span class="op">=</span> feature_differences <span class="op">@</span> weights</span>
<span id="cb7-43"><a href="#cb7-43" aria-hidden="true" tabindex="-1"></a>        loss <span class="op">=</span> F.binary_cross_entropy_with_logits(logits, labels)</span>
<span id="cb7-44"><a href="#cb7-44" aria-hidden="true" tabindex="-1"></a>        optimizer.zero_grad()</span>
<span id="cb7-45"><a href="#cb7-45" aria-hidden="true" tabindex="-1"></a>        loss.backward()</span>
<span id="cb7-46"><a href="#cb7-46" aria-hidden="true" tabindex="-1"></a>        optimizer.step()</span>
<span id="cb7-47"><a href="#cb7-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-48"><a href="#cb7-48" aria-hidden="true" tabindex="-1"></a>    held_left <span class="op">=</span> draw_responses(<span class="dv">10_000</span>, generator, <span class="fl">0.0</span>)</span>
<span id="cb7-49"><a href="#cb7-49" aria-hidden="true" tabindex="-1"></a>    held_right <span class="op">=</span> draw_responses(<span class="dv">10_000</span>, generator, <span class="fl">0.0</span>)</span>
<span id="cb7-50"><a href="#cb7-50" aria-hidden="true" tabindex="-1"></a>    held_differences <span class="op">=</span> reward_features(held_left) <span class="op">-</span> reward_features(held_right)</span>
<span id="cb7-51"><a href="#cb7-51" aria-hidden="true" tabindex="-1"></a>    held_probabilities <span class="op">=</span> torch.sigmoid(</span>
<span id="cb7-52"><a href="#cb7-52" aria-hidden="true" tabindex="-1"></a>        designed_utility(held_left) <span class="op">-</span> designed_utility(held_right)</span>
<span id="cb7-53"><a href="#cb7-53" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb7-54"><a href="#cb7-54" aria-hidden="true" tabindex="-1"></a>    held_labels <span class="op">=</span> torch.bernoulli(held_probabilities, generator<span class="op">=</span>generator)</span>
<span id="cb7-55"><a href="#cb7-55" aria-hidden="true" tabindex="-1"></a>    held_logits <span class="op">=</span> held_differences <span class="op">@</span> weights.detach()</span>
<span id="cb7-56"><a href="#cb7-56" aria-hidden="true" tabindex="-1"></a>    held_nll <span class="op">=</span> F.binary_cross_entropy_with_logits(held_logits, held_labels)</span>
<span id="cb7-57"><a href="#cb7-57" aria-hidden="true" tabindex="-1"></a>    oracle_nll <span class="op">=</span> F.binary_cross_entropy(held_probabilities, held_labels)</span>
<span id="cb7-58"><a href="#cb7-58" aria-hidden="true" tabindex="-1"></a>    order_accuracy <span class="op">=</span> (</span>
<span id="cb7-59"><a href="#cb7-59" aria-hidden="true" tabindex="-1"></a>        torch.sign(held_logits)</span>
<span id="cb7-60"><a href="#cb7-60" aria-hidden="true" tabindex="-1"></a>        <span class="op">==</span> torch.sign(designed_utility(held_left) <span class="op">-</span> designed_utility(held_right))</span>
<span id="cb7-61"><a href="#cb7-61" aria-hidden="true" tabindex="-1"></a>    ).double().mean()</span>
<span id="cb7-62"><a href="#cb7-62" aria-hidden="true" tabindex="-1"></a>    metrics <span class="op">=</span> {</span>
<span id="cb7-63"><a href="#cb7-63" aria-hidden="true" tabindex="-1"></a>        <span class="st">"held_nll"</span>: held_nll.item(),</span>
<span id="cb7-64"><a href="#cb7-64" aria-hidden="true" tabindex="-1"></a>        <span class="st">"oracle_nll"</span>: oracle_nll.item(),</span>
<span id="cb7-65"><a href="#cb7-65" aria-hidden="true" tabindex="-1"></a>        <span class="st">"order_accuracy"</span>: order_accuracy.item(),</span>
<span id="cb7-66"><a href="#cb7-66" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb7-67"><a href="#cb7-67" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> weights.detach(), metrics</span>
<span id="cb7-68"><a href="#cb7-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-69"><a href="#cb7-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-70"><a href="#cb7-70" aria-hidden="true" tabindex="-1"></a>seeds <span class="op">=</span> <span class="bu">list</span>(<span class="bu">range</span>(<span class="dv">6050</span>, <span class="dv">6055</span>))</span>
<span id="cb7-71"><a href="#cb7-71" aria-hidden="true" tabindex="-1"></a>narrow_fits <span class="op">=</span> [fit_reward_model(seed, <span class="fl">0.0</span>) <span class="cf">for</span> seed <span class="kw">in</span> seeds]</span>
<span id="cb7-72"><a href="#cb7-72" aria-hidden="true" tabindex="-1"></a>repaired_fits <span class="op">=</span> [fit_reward_model(seed, <span class="fl">0.20</span>) <span class="cf">for</span> seed <span class="kw">in</span> seeds]</span>
<span id="cb7-73"><a href="#cb7-73" aria-hidden="true" tabindex="-1"></a>narrow_weights <span class="op">=</span> torch.stack([fit[<span class="dv">0</span>] <span class="cf">for</span> fit <span class="kw">in</span> narrow_fits])</span>
<span id="cb7-74"><a href="#cb7-74" aria-hidden="true" tabindex="-1"></a>repaired_weights <span class="op">=</span> torch.stack([fit[<span class="dv">0</span>] <span class="cf">for</span> fit <span class="kw">in</span> repaired_fits])</span>
<span id="cb7-75"><a href="#cb7-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-76"><a href="#cb7-76" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> mean_and_seed_sd(values: Tensor) <span class="op">-&gt;</span> <span class="bu">tuple</span>[Tensor, Tensor]:</span>
<span id="cb7-77"><a href="#cb7-77" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> values.mean(dim<span class="op">=</span><span class="dv">0</span>), values.std(dim<span class="op">=</span><span class="dv">0</span>, unbiased<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb7-78"><a href="#cb7-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-79"><a href="#cb7-79" aria-hidden="true" tabindex="-1"></a>narrow_mean, narrow_sd <span class="op">=</span> mean_and_seed_sd(narrow_weights)</span>
<span id="cb7-80"><a href="#cb7-80" aria-hidden="true" tabindex="-1"></a>repaired_mean, repaired_sd <span class="op">=</span> mean_and_seed_sd(repaired_weights)</span>
<span id="cb7-81"><a href="#cb7-81" aria-hidden="true" tabindex="-1"></a>narrow_nlls <span class="op">=</span> torch.tensor([fit[<span class="dv">1</span>][<span class="st">"held_nll"</span>] <span class="cf">for</span> fit <span class="kw">in</span> narrow_fits])</span>
<span id="cb7-82"><a href="#cb7-82" aria-hidden="true" tabindex="-1"></a>oracle_nlls <span class="op">=</span> torch.tensor([fit[<span class="dv">1</span>][<span class="st">"oracle_nll"</span>] <span class="cf">for</span> fit <span class="kw">in</span> narrow_fits])</span>
<span id="cb7-83"><a href="#cb7-83" aria-hidden="true" tabindex="-1"></a>narrow_accuracies <span class="op">=</span> torch.tensor([</span>
<span id="cb7-84"><a href="#cb7-84" aria-hidden="true" tabindex="-1"></a>    fit[<span class="dv">1</span>][<span class="st">"order_accuracy"</span>] <span class="cf">for</span> fit <span class="kw">in</span> narrow_fits</span>
<span id="cb7-85"><a href="#cb7-85" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb7-86"><a href="#cb7-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-87"><a href="#cb7-87" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"feedback               w_e       w_length   w_curve"</span>)</span>
<span id="cb7-88"><a href="#cb7-88" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"narrow mean       "</span>, <span class="st">"  "</span>.join(<span class="ss">f"</span><span class="sc">{</span>x<span class="sc">:.6f}</span><span class="ss">"</span> <span class="cf">for</span> x <span class="kw">in</span> narrow_mean))</span>
<span id="cb7-89"><a href="#cb7-89" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"narrow seed sd    "</span>, <span class="st">"  "</span>.join(<span class="ss">f"</span><span class="sc">{</span>x<span class="sc">:.6f}</span><span class="ss">"</span> <span class="cf">for</span> x <span class="kw">in</span> narrow_sd))</span>
<span id="cb7-90"><a href="#cb7-90" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"repaired mean     "</span>, <span class="st">"  "</span>.join(<span class="ss">f"</span><span class="sc">{</span>x<span class="sc">:.6f}</span><span class="ss">"</span> <span class="cf">for</span> x <span class="kw">in</span> repaired_mean))</span>
<span id="cb7-91"><a href="#cb7-91" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"repaired seed sd  "</span>, <span class="st">"  "</span>.join(<span class="ss">f"</span><span class="sc">{</span>x<span class="sc">:.6f}</span><span class="ss">"</span> <span class="cf">for</span> x <span class="kw">in</span> repaired_sd))</span>
<span id="cb7-92"><a href="#cb7-92" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(</span>
<span id="cb7-93"><a href="#cb7-93" aria-hidden="true" tabindex="-1"></a>    <span class="st">"narrow in-range NLL:"</span>,</span>
<span id="cb7-94"><a href="#cb7-94" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"</span><span class="sc">{</span>narrow_nlls<span class="sc">.</span>mean()<span class="sc">.</span>item()<span class="sc">:.6f}</span><span class="ss"> +/- </span><span class="sc">{</span>narrow_nlls<span class="sc">.</span>std(unbiased<span class="op">=</span><span class="va">True</span>)<span class="sc">.</span>item()<span class="sc">:.6f}</span><span class="ss">"</span>,</span>
<span id="cb7-95"><a href="#cb7-95" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-96"><a href="#cb7-96" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(</span>
<span id="cb7-97"><a href="#cb7-97" aria-hidden="true" tabindex="-1"></a>    <span class="st">"oracle in-range NLL:"</span>,</span>
<span id="cb7-98"><a href="#cb7-98" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"</span><span class="sc">{</span>oracle_nlls<span class="sc">.</span>mean()<span class="sc">.</span>item()<span class="sc">:.6f}</span><span class="ss"> +/- </span><span class="sc">{</span>oracle_nlls<span class="sc">.</span>std(unbiased<span class="op">=</span><span class="va">True</span>)<span class="sc">.</span>item()<span class="sc">:.6f}</span><span class="ss">"</span>,</span>
<span id="cb7-99"><a href="#cb7-99" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-100"><a href="#cb7-100" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(</span>
<span id="cb7-101"><a href="#cb7-101" aria-hidden="true" tabindex="-1"></a>    <span class="st">"narrow designed-order accuracy:"</span>,</span>
<span id="cb7-102"><a href="#cb7-102" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"</span><span class="sc">{</span>narrow_accuracies<span class="sc">.</span>mean()<span class="sc">.</span>item()<span class="sc">:.6f}</span><span class="ss"> +/- "</span></span>
<span id="cb7-103"><a href="#cb7-103" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"</span><span class="sc">{</span>narrow_accuracies<span class="sc">.</span>std(unbiased<span class="op">=</span><span class="va">True</span>)<span class="sc">.</span>item()<span class="sc">:.6f}</span><span class="ss">"</span>,</span>
<span id="cb7-104"><a href="#cb7-104" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>feedback               w_e       w_length   w_curve
narrow mean        1.004469  0.634378  0.000000
narrow seed sd     0.042489  0.019772  0.000000
repaired mean      0.984938  0.600285  -1.208128
repaired seed sd   0.073378  0.007907  0.025924
narrow in-range NLL: 0.665633 +/- 0.002097
oracle in-range NLL: 0.665603 +/- 0.002092
narrow designed-order accuracy: 0.992940 +/- 0.002548</code></pre>
</div>
</div>
<p>The narrow model looks excellent where it was tested—yet its mean held-out log loss is 0.665633, only 0.000030 above the oracle that generated the labels, and its latent ordering accuracy is 0.992940. The coefficient <span class="math inline">\(w_q\)</span> remains exactly zero: that feature was zero in every narrow comparison, so no gradient could identify its coefficient. A validation split drawn from the same support cannot expose the missing behavior.</p>
<p>Now place 401 candidate responses at fixed evidence <span class="math inline">\(e=0.72\)</span> and lengths from zero to four. The reference policy is a discretized bell-shaped distribution with mean length 0.776439. For each fitted reward model and each <span class="math inline">\(\beta\)</span>, compute the exact policy from <a href="#eq-gibbs-policy" class="quarto-xref">Equation&nbsp;<span>18.5</span></a>. No sampled-policy optimizer is needed—any failure comes from the proxy and its feedback coverage:</p>
<!-- NOVEL: needs sign-off -->
<div id="cell-fig-proxy-pressure" class="cell" data-fig-height="4.4" data-fig-width="10" data-execution_count="8">
<details class="code-fold">
<summary>Experiment: optimize the proxy outside its comparison coverage</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>lengths <span class="op">=</span> torch.linspace(<span class="fl">0.0</span>, <span class="fl">4.0</span>, <span class="dv">401</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>evidence <span class="op">=</span> torch.full_like(lengths, <span class="fl">0.72</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>candidates <span class="op">=</span> torch.stack((evidence, lengths), dim<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>candidate_features <span class="op">=</span> reward_features(candidates)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>candidate_designed_utility <span class="op">=</span> designed_utility(candidates)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>reference_policy <span class="op">=</span> torch.softmax(</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    <span class="op">-</span><span class="fl">0.5</span> <span class="op">*</span> ((lengths <span class="op">-</span> <span class="fl">0.695</span>) <span class="op">/</span> <span class="fl">0.5</span>).square(), dim<span class="op">=</span><span class="dv">0</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>pressure_betas <span class="op">=</span> [<span class="fl">1.0</span>, <span class="fl">0.5</span>, <span class="fl">0.25</span>, <span class="fl">0.125</span>]</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> policy_metrics(weights_by_seed: Tensor) <span class="op">-&gt;</span> <span class="bu">dict</span>[<span class="bu">float</span>, Tensor]:</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>    rows: <span class="bu">dict</span>[<span class="bu">float</span>, Tensor] <span class="op">=</span> {}</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> beta <span class="kw">in</span> pressure_betas:</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>        seed_rows <span class="op">=</span> []</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> weights <span class="kw">in</span> weights_by_seed:</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>            proxy <span class="op">=</span> candidate_features <span class="op">@</span> weights</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>            policy <span class="op">=</span> torch.softmax(</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>                torch.log(reference_policy) <span class="op">+</span> proxy <span class="op">/</span> beta, dim<span class="op">=</span><span class="dv">0</span></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>            )</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>            seed_rows.append(torch.stack((</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>                policy <span class="op">@</span> lengths,</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>                policy <span class="op">@</span> proxy,</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>                policy <span class="op">@</span> candidate_designed_utility,</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>                kl_divergence(policy, reference_policy),</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>            )))</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>        rows[beta] <span class="op">=</span> torch.stack(seed_rows)</span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> rows</span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>narrow_rows <span class="op">=</span> policy_metrics(narrow_weights)</span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a>repaired_rows <span class="op">=</span> policy_metrics(repaired_weights)</span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a>reference_length <span class="op">=</span> reference_policy <span class="op">@</span> lengths</span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>reference_designed_utility <span class="op">=</span> reference_policy <span class="op">@</span> candidate_designed_utility</span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="fl">4.4</span>))</span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].axvspan(<span class="dv">0</span>, <span class="dv">1</span>, color<span class="op">=</span>green, alpha<span class="op">=</span><span class="fl">0.10</span>, label<span class="op">=</span><span class="st">"narrow feedback"</span>)</span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].plot(lengths, candidate_designed_utility, color<span class="op">=</span>navy, lw<span class="op">=</span><span class="fl">2.2</span>,</span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a>             label<span class="op">=</span><span class="st">"designed utility"</span>)</span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].plot(lengths, candidate_features <span class="op">@</span> narrow_mean, color<span class="op">=</span>orange, lw<span class="op">=</span><span class="fl">2.0</span>,</span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a>             linestyle<span class="op">=</span><span class="st">"--"</span>, label<span class="op">=</span><span class="st">"narrow proxy"</span>)</span>
<span id="cb9-41"><a href="#cb9-41" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].plot(lengths, candidate_features <span class="op">@</span> repaired_mean, color<span class="op">=</span>green, lw<span class="op">=</span><span class="fl">2.0</span>,</span>
<span id="cb9-42"><a href="#cb9-42" aria-hidden="true" tabindex="-1"></a>             linestyle<span class="op">=</span><span class="st">":"</span>, label<span class="op">=</span><span class="st">"repaired proxy"</span>)</span>
<span id="cb9-43"><a href="#cb9-43" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].axvline(<span class="fl">1.25</span>, color<span class="op">=</span><span class="st">"#888888"</span>, lw<span class="op">=</span><span class="dv">1</span>, linestyle<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb9-44"><a href="#cb9-44" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xlabel(<span class="st">"response length feature"</span>)</span>
<span id="cb9-45"><a href="#cb9-45" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"score at evidence = 0.72"</span>)</span>
<span id="cb9-46"><a href="#cb9-46" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">"coverage hides curvature"</span>, color<span class="op">=</span>navy, weight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb9-47"><a href="#cb9-47" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="fl">7.2</span>)</span>
<span id="cb9-48"><a href="#cb9-48" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].grid(alpha<span class="op">=</span><span class="fl">0.15</span>)</span>
<span id="cb9-49"><a href="#cb9-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-50"><a href="#cb9-50" aria-hidden="true" tabindex="-1"></a>narrow_stack <span class="op">=</span> torch.stack([narrow_rows[beta] <span class="cf">for</span> beta <span class="kw">in</span> pressure_betas])</span>
<span id="cb9-51"><a href="#cb9-51" aria-hidden="true" tabindex="-1"></a>narrow_policy_mean <span class="op">=</span> narrow_stack.mean(dim<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb9-52"><a href="#cb9-52" aria-hidden="true" tabindex="-1"></a>narrow_policy_sd <span class="op">=</span> narrow_stack.std(dim<span class="op">=</span><span class="dv">1</span>, unbiased<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb9-53"><a href="#cb9-53" aria-hidden="true" tabindex="-1"></a>reference_proxy_by_seed <span class="op">=</span> torch.stack([</span>
<span id="cb9-54"><a href="#cb9-54" aria-hidden="true" tabindex="-1"></a>    reference_policy <span class="op">@</span> (candidate_features <span class="op">@</span> weights) <span class="cf">for</span> weights <span class="kw">in</span> narrow_weights</span>
<span id="cb9-55"><a href="#cb9-55" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb9-56"><a href="#cb9-56" aria-hidden="true" tabindex="-1"></a>narrow_kls <span class="op">=</span> torch.cat((torch.tensor([<span class="fl">0.0</span>]), narrow_policy_mean[:, <span class="dv">3</span>]))</span>
<span id="cb9-57"><a href="#cb9-57" aria-hidden="true" tabindex="-1"></a>narrow_proxy_means <span class="op">=</span> torch.cat((</span>
<span id="cb9-58"><a href="#cb9-58" aria-hidden="true" tabindex="-1"></a>    reference_proxy_by_seed.mean().view(<span class="dv">1</span>), narrow_policy_mean[:, <span class="dv">1</span>]</span>
<span id="cb9-59"><a href="#cb9-59" aria-hidden="true" tabindex="-1"></a>))</span>
<span id="cb9-60"><a href="#cb9-60" aria-hidden="true" tabindex="-1"></a>narrow_designed_means <span class="op">=</span> torch.cat((</span>
<span id="cb9-61"><a href="#cb9-61" aria-hidden="true" tabindex="-1"></a>    reference_designed_utility.view(<span class="dv">1</span>), narrow_policy_mean[:, <span class="dv">2</span>]</span>
<span id="cb9-62"><a href="#cb9-62" aria-hidden="true" tabindex="-1"></a>))</span>
<span id="cb9-63"><a href="#cb9-63" aria-hidden="true" tabindex="-1"></a>narrow_designed_sds <span class="op">=</span> torch.cat((torch.tensor([<span class="fl">0.0</span>]), narrow_policy_sd[:, <span class="dv">2</span>]))</span>
<span id="cb9-64"><a href="#cb9-64" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].plot(narrow_kls, narrow_proxy_means, <span class="st">"o-"</span>, color<span class="op">=</span>orange,</span>
<span id="cb9-65"><a href="#cb9-65" aria-hidden="true" tabindex="-1"></a>             label<span class="op">=</span><span class="st">"expected proxy"</span>)</span>
<span id="cb9-66"><a href="#cb9-66" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].plot(narrow_kls, narrow_designed_means, <span class="st">"o-"</span>, color<span class="op">=</span>navy,</span>
<span id="cb9-67"><a href="#cb9-67" aria-hidden="true" tabindex="-1"></a>             label<span class="op">=</span><span class="st">"designed utility"</span>)</span>
<span id="cb9-68"><a href="#cb9-68" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].fill_between(</span>
<span id="cb9-69"><a href="#cb9-69" aria-hidden="true" tabindex="-1"></a>    narrow_kls.numpy(),</span>
<span id="cb9-70"><a href="#cb9-70" aria-hidden="true" tabindex="-1"></a>    (narrow_designed_means <span class="op">-</span> narrow_designed_sds).numpy(),</span>
<span id="cb9-71"><a href="#cb9-71" aria-hidden="true" tabindex="-1"></a>    (narrow_designed_means <span class="op">+</span> narrow_designed_sds).numpy(),</span>
<span id="cb9-72"><a href="#cb9-72" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span>navy, alpha<span class="op">=</span><span class="fl">0.12</span>,</span>
<span id="cb9-73"><a href="#cb9-73" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-74"><a href="#cb9-74" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xlabel(<span class="vs">r"realized </span><span class="dv">$</span><span class="vs">D_{</span><span class="dv">\m</span><span class="vs">athrm{KL}}</span><span class="dv">$</span><span class="vs">"</span>)</span>
<span id="cb9-75"><a href="#cb9-75" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_ylabel(<span class="st">"policy expectation"</span>)</span>
<span id="cb9-76"><a href="#cb9-76" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">"proxy up, target down"</span>, color<span class="op">=</span>navy, weight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb9-77"><a href="#cb9-77" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="fl">7.5</span>)</span>
<span id="cb9-78"><a href="#cb9-78" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].grid(alpha<span class="op">=</span><span class="fl">0.15</span>)</span>
<span id="cb9-79"><a href="#cb9-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-80"><a href="#cb9-80" aria-hidden="true" tabindex="-1"></a>repaired_stack <span class="op">=</span> torch.stack([repaired_rows[beta] <span class="cf">for</span> beta <span class="kw">in</span> pressure_betas])</span>
<span id="cb9-81"><a href="#cb9-81" aria-hidden="true" tabindex="-1"></a>repaired_policy_mean <span class="op">=</span> repaired_stack.mean(dim<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb9-82"><a href="#cb9-82" aria-hidden="true" tabindex="-1"></a>repaired_policy_sd <span class="op">=</span> repaired_stack.std(dim<span class="op">=</span><span class="dv">1</span>, unbiased<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb9-83"><a href="#cb9-83" aria-hidden="true" tabindex="-1"></a>repaired_kls <span class="op">=</span> torch.cat((torch.tensor([<span class="fl">0.0</span>]), repaired_policy_mean[:, <span class="dv">3</span>]))</span>
<span id="cb9-84"><a href="#cb9-84" aria-hidden="true" tabindex="-1"></a>repaired_designed_means <span class="op">=</span> torch.cat((</span>
<span id="cb9-85"><a href="#cb9-85" aria-hidden="true" tabindex="-1"></a>    reference_designed_utility.view(<span class="dv">1</span>), repaired_policy_mean[:, <span class="dv">2</span>]</span>
<span id="cb9-86"><a href="#cb9-86" aria-hidden="true" tabindex="-1"></a>))</span>
<span id="cb9-87"><a href="#cb9-87" aria-hidden="true" tabindex="-1"></a>repaired_designed_sds <span class="op">=</span> torch.cat((torch.tensor([<span class="fl">0.0</span>]), repaired_policy_sd[:, <span class="dv">2</span>]))</span>
<span id="cb9-88"><a href="#cb9-88" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].plot(narrow_kls, narrow_designed_means, <span class="st">"o-"</span>, color<span class="op">=</span>orange,</span>
<span id="cb9-89"><a href="#cb9-89" aria-hidden="true" tabindex="-1"></a>             label<span class="op">=</span><span class="st">"narrow feedback"</span>)</span>
<span id="cb9-90"><a href="#cb9-90" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].fill_between(</span>
<span id="cb9-91"><a href="#cb9-91" aria-hidden="true" tabindex="-1"></a>    narrow_kls.numpy(),</span>
<span id="cb9-92"><a href="#cb9-92" aria-hidden="true" tabindex="-1"></a>    (narrow_designed_means <span class="op">-</span> narrow_designed_sds).numpy(),</span>
<span id="cb9-93"><a href="#cb9-93" aria-hidden="true" tabindex="-1"></a>    (narrow_designed_means <span class="op">+</span> narrow_designed_sds).numpy(),</span>
<span id="cb9-94"><a href="#cb9-94" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span>orange, alpha<span class="op">=</span><span class="fl">0.12</span>,</span>
<span id="cb9-95"><a href="#cb9-95" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-96"><a href="#cb9-96" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].plot(repaired_kls, repaired_designed_means, <span class="st">"o-"</span>, color<span class="op">=</span>green,</span>
<span id="cb9-97"><a href="#cb9-97" aria-hidden="true" tabindex="-1"></a>             label<span class="op">=</span><span class="st">"coverage repair"</span>)</span>
<span id="cb9-98"><a href="#cb9-98" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].fill_between(</span>
<span id="cb9-99"><a href="#cb9-99" aria-hidden="true" tabindex="-1"></a>    repaired_kls.numpy(),</span>
<span id="cb9-100"><a href="#cb9-100" aria-hidden="true" tabindex="-1"></a>    (repaired_designed_means <span class="op">-</span> repaired_designed_sds).numpy(),</span>
<span id="cb9-101"><a href="#cb9-101" aria-hidden="true" tabindex="-1"></a>    (repaired_designed_means <span class="op">+</span> repaired_designed_sds).numpy(),</span>
<span id="cb9-102"><a href="#cb9-102" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span>green, alpha<span class="op">=</span><span class="fl">0.12</span>,</span>
<span id="cb9-103"><a href="#cb9-103" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-104"><a href="#cb9-104" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_xlabel(<span class="vs">r"realized </span><span class="dv">$</span><span class="vs">D_{</span><span class="dv">\m</span><span class="vs">athrm{KL}}</span><span class="dv">$</span><span class="vs">"</span>)</span>
<span id="cb9-105"><a href="#cb9-105" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_ylabel(<span class="st">"designed policy utility"</span>)</span>
<span id="cb9-106"><a href="#cb9-106" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_title(<span class="st">"feedback coverage repairs reward"</span>, color<span class="op">=</span>navy, weight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb9-107"><a href="#cb9-107" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="fl">7.5</span>)</span>
<span id="cb9-108"><a href="#cb9-108" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].grid(alpha<span class="op">=</span><span class="fl">0.15</span>)</span>
<span id="cb9-109"><a href="#cb9-109" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb9-110"><a href="#cb9-110" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb9-111"><a href="#cb9-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-112"><a href="#cb9-112" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"reference mean length: </span><span class="sc">{</span>reference_length<span class="sc">.</span>item()<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb9-113"><a href="#cb9-113" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"reference designed utility: </span><span class="sc">{</span>reference_designed_utility<span class="sc">.</span>item()<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb9-114"><a href="#cb9-114" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"narrow feedback: beta  length  proxy  designed  KL"</span>)</span>
<span id="cb9-115"><a href="#cb9-115" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> beta, values <span class="kw">in</span> narrow_rows.items():</span>
<span id="cb9-116"><a href="#cb9-116" aria-hidden="true" tabindex="-1"></a>    mean, seed_sd <span class="op">=</span> mean_and_seed_sd(values)</span>
<span id="cb9-117"><a href="#cb9-117" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(</span>
<span id="cb9-118"><a href="#cb9-118" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>beta<span class="sc">:5.3f}</span><span class="ss">  </span><span class="sc">{</span>mean[<span class="dv">0</span>]<span class="sc">.</span>item()<span class="sc">:.6f}</span><span class="ss">  </span><span class="sc">{</span>mean[<span class="dv">1</span>]<span class="sc">.</span>item()<span class="sc">:.6f}</span><span class="ss">"</span></span>
<span id="cb9-119"><a href="#cb9-119" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"  </span><span class="sc">{</span>mean[<span class="dv">2</span>]<span class="sc">.</span>item()<span class="sc">:.6f}</span><span class="ss">  </span><span class="sc">{</span>mean[<span class="dv">3</span>]<span class="sc">.</span>item()<span class="sc">:.6f}</span><span class="ss">"</span></span>
<span id="cb9-120"><a href="#cb9-120" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"  (designed sd </span><span class="sc">{</span>seed_sd[<span class="dv">2</span>]<span class="sc">.</span>item()<span class="sc">:.6f}</span><span class="ss">)"</span></span>
<span id="cb9-121"><a href="#cb9-121" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb9-122"><a href="#cb9-122" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"repaired feedback: beta  length  proxy  designed  KL"</span>)</span>
<span id="cb9-123"><a href="#cb9-123" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> beta, values <span class="kw">in</span> repaired_rows.items():</span>
<span id="cb9-124"><a href="#cb9-124" aria-hidden="true" tabindex="-1"></a>    mean, seed_sd <span class="op">=</span> mean_and_seed_sd(values)</span>
<span id="cb9-125"><a href="#cb9-125" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(</span>
<span id="cb9-126"><a href="#cb9-126" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>beta<span class="sc">:5.3f}</span><span class="ss">  </span><span class="sc">{</span>mean[<span class="dv">0</span>]<span class="sc">.</span>item()<span class="sc">:.6f}</span><span class="ss">  </span><span class="sc">{</span>mean[<span class="dv">1</span>]<span class="sc">.</span>item()<span class="sc">:.6f}</span><span class="ss">"</span></span>
<span id="cb9-127"><a href="#cb9-127" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"  </span><span class="sc">{</span>mean[<span class="dv">2</span>]<span class="sc">.</span>item()<span class="sc">:.6f}</span><span class="ss">  </span><span class="sc">{</span>mean[<span class="dv">3</span>]<span class="sc">.</span>item()<span class="sc">:.6f}</span><span class="ss">"</span></span>
<span id="cb9-128"><a href="#cb9-128" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"  (designed sd </span><span class="sc">{</span>seed_sd[<span class="dv">2</span>]<span class="sc">.</span>item()<span class="sc">:.6f}</span><span class="ss">)"</span></span>
<span id="cb9-129"><a href="#cb9-129" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-proxy-pressure" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Three panels show designed and learned reward curves over response length, proxy and designed utility under narrow-feedback policies, and designed utility for narrow versus coverage-repaired policies as KL grows. The narrow proxy keeps rising after designed utility falls, while coverage repair avoids the collapse.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-proxy-pressure-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="18-alignment_files/figure-html/fig-proxy-pressure-output-1.png" alt="Three panels show designed and learned reward curves over response length, proxy and designed utility under narrow-feedback policies, and designed utility for narrow versus coverage-repaired policies as KL grows. The narrow proxy keeps rising after designed utility falls, while coverage repair avoids the collapse." width="981" height="412" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-proxy-pressure-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;18.5: A reward model can pass an in-range comparison test and fail under optimization. Narrow feedback covers only the shaded length interval, so the learned proxy remains linear after designed utility turns down (left). Under increasing reward pressure, its expected proxy score rises while designed utility is highest among the four tested settings at beta 0.5 and falls to 0.484541 at beta 0.125, with realized KL 3.138049 (center). Adding 20% out-of-range responses identifies the missing curvature; at beta 0.125 the repaired policies retain mean designed utility 1.316470 (right). Lines are means over five reward-model seeds; designed-utility bands show one seed SD where plotted.
</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>reference mean length: 0.776439
reference designed utility: 1.130480
narrow feedback: beta  length  proxy  designed  KL
1.000  0.901311  1.295055  1.164883  0.040327  (designed sd 0.000874)
0.500  1.037928  1.381796  1.183447  0.170991  (designed sd 0.000480)
0.250  1.335088  1.570472  1.135363  0.739579  (designed sd 0.007630)
0.125  1.963796  1.969632  0.484541  3.138049  (designed sd 0.067970)
repaired feedback: beta  length  proxy  designed  KL
1.000  0.837956  1.157585  1.168536  0.018632  (designed sd 0.000484)
0.500  0.895553  1.190942  1.201869  0.068282  (designed sd 0.000905)
0.250  0.990698  1.243968  1.254875  0.224387  (designed sd 0.001374)
0.125  1.104397  1.305569  1.316470  0.577948  (designed sd 0.001310)</code></pre>
</div>
</div>
<p>At moderate pressure, the narrow proxy helps—mean designed utility rises from 1.130480 under the reference to 1.183447 at <span class="math inline">\(\beta=0.5\)</span>. More pressure then reverses the result. At <span class="math inline">\(\beta=0.125\)</span>, mean predicted reward has climbed to 1.969632 while designed utility has fallen to 0.484541. The KL penalty changes how quickly the policy reaches the failure—it cannot invent the missing curvature.</p>
<p>The repair changes feedback coverage, not the policy optimizer—once 20% of individual responses expose the longer regime, the mean fitted curvature coefficient is <span class="math inline">\(-1.208128\)</span> (designed value <span class="math inline">\(-1.2\)</span>). At <span class="math inline">\(\beta=0.125\)</span>, the repaired policies reach mean designed utility 1.316470 instead of 0.484541. In this controlled world, better feedback coverage matters more than choosing a fancier route to the same proxy.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Reward-model validation is not policy validation
</div>
</div>
<div class="callout-body-container callout-body">
<p>Held-out pair loss tests interpolation over a declared comparison distribution—policy optimization deliberately changes the response distribution. Evaluate current-policy outputs with independent judgments, track realized drift and length or style shifts, and refresh feedback where the policy now visits. A proxy score rising by itself is not evidence that the intended behavior improved.</p>
</div>
</div>
</section>
<section id="dpo-removes-a-stage-not-the-assumptions" class="level2" data-number="18.5">
<h2 data-number="18.5" class="anchored" data-anchor-id="dpo-removes-a-stage-not-the-assumptions"><span class="header-section-number">18.5</span> DPO removes a stage, not the assumptions</h2>
<p>Reward-model RLHF fits an explicit proxy, freezes it, then optimizes a policy against it. Can we use preference pairs without that separately trained middle model? The course lecture calls the answer the DPO “Aha!” move—invert <a href="#eq-gibbs-policy" class="quarto-xref">Equation&nbsp;<span>18.5</span></a> and substitute the result into the preference model.</p>
<!-- NOVEL: needs sign-off -->
<div id="cell-fig-preference-routes" class="cell" data-fig-height="4.7" data-fig-width="10" data-execution_count="9">
<div class="cell-output cell-output-display">
<div id="fig-preference-routes" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Preference pairs branch left into an explicit reward model and online policy loop, and right into a DPO reference-ratio loss. A shared foundation beneath both branches lists rubric, candidate coverage, scalar preference assumptions, and reference support.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-preference-routes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="18-alignment_files/figure-html/fig-preference-routes-output-1.png" alt="Preference pairs branch left into an explicit reward model and online policy loop, and right into a DPO reference-ratio loss. A shared foundation beneath both branches lists rubric, candidate coverage, scalar preference assumptions, and reference support." width="950" height="442" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-preference-routes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;18.6: Two routes can consume preference pairs. A reward-model route first fits an explicit scalar proxy, then scores fresh outputs during online policy optimization. DPO forms a reference-adjusted policy margin directly on a fixed pair dataset. It removes the explicit reward-model stage and online sampling during the optimization pass, but both routes still depend on the preference rubric, coverage, a scalar-reward model, and an adequate reference support.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Rearrange the exact optimum:</p>
<p><span id="eq-reward-policy-inverse"><span class="math display">\[
r(x,y)
=\beta\log\frac{\pi^*(y\mid x)}{\pi_{\mathrm{ref}}(y\mid x)}
+\beta\log Z(x).
\tag{18.8}\]</span></span></p>
<p>For two responses to the same prompt, the <span class="math inline">\(\beta\log Z(x)\)</span> term is identical and cancels from the reward difference. Define the current policy’s reference-adjusted score</p>
<p><span class="math display">\[
s_\theta(x,y)
=\log\pi_\theta(y\mid x)-\log\pi_{\mathrm{ref}}(y\mid x).
\]</span></p>
<p>Substituting <a href="#eq-reward-policy-inverse" class="quarto-xref">Equation&nbsp;<span>18.8</span></a> into Bradley–Terry gives <strong>Direct Preference Optimization (DPO)</strong>:</p>
<p><span id="eq-dpo-loss"><span class="math display">\[
\mathcal{L}_{\mathrm{DPO}}(\theta)
=-\E_{(x,y_w,y_l)\sim\mathcal{D}_{\mathrm{pref}}}
\log\sigma\!\left(
\beta\left[s_\theta(x,y_w)-s_\theta(x,y_l)\right]
\right).
\tag{18.9}\]</span></span></p>
<p>For an autoregressive model, <span class="math inline">\(\log\pi_\theta(y\mid x)\)</span> is a <strong>sum</strong> over response token log probabilities, normally including the response end token:</p>
<p><span class="math display">\[
\log\pi_\theta(y\mid x)
=\sum_{t=1}^{T}\log\pi_\theta(y_t\mid x,y_{&lt;t}).
\]</span></p>
<p>The completion mask audited near <a href="#eq-sft-response-mask" class="quarto-xref">Equation&nbsp;<span>18.1</span></a> applies here as well. Prompt and padding targets contribute zero—length-normalizing that sum would define a different objective and should be named as such.</p>
<p>Does the algebra work in the finite world? Use all six response pairs, but train on their exact stochastic Bradley–Terry probabilities rather than separable hard winners. For this identity check, set <span class="math inline">\(\beta=1\)</span>. The DPO logit for pair <span class="math inline">\((i,j)\)</span> is <span class="math inline">\(\beta(s_i-s_j)\)</span>. Starting from the reference, optimize four unconstrained reference-relative offsets, identifiable only up to a shared additive constant:</p>
<!-- NOVEL: needs sign-off -->
<div id="4ac298a7" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>Identity test: recover the exact regularized policy with DPO</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>pairs <span class="op">=</span> torch.tensor([</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">0</span>, <span class="dv">1</span>], [<span class="dv">0</span>, <span class="dv">2</span>], [<span class="dv">0</span>, <span class="dv">3</span>], [<span class="dv">1</span>, <span class="dv">2</span>], [<span class="dv">1</span>, <span class="dv">3</span>], [<span class="dv">2</span>, <span class="dv">3</span>]</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>dpo_beta <span class="op">=</span> <span class="fl">1.0</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>pair_probabilities <span class="op">=</span> torch.sigmoid(</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    reward[pairs[:, <span class="dv">0</span>]] <span class="op">-</span> reward[pairs[:, <span class="dv">1</span>]]</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>target_policy <span class="op">=</span> gibbs_policy(reference, reward, dpo_beta)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>log_ratio <span class="op">=</span> nn.Parameter(torch.zeros(<span class="dv">4</span>))</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>dpo_optimizer <span class="op">=</span> torch.optim.Adam([log_ratio], lr<span class="op">=</span><span class="fl">0.05</span>)</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">4000</span>):</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>    comparison_logits <span class="op">=</span> dpo_beta <span class="op">*</span> (</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>        log_ratio[pairs[:, <span class="dv">0</span>]] <span class="op">-</span> log_ratio[pairs[:, <span class="dv">1</span>]]</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>    dpo_loss <span class="op">=</span> F.binary_cross_entropy_with_logits(</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>        comparison_logits, pair_probabilities</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>    dpo_optimizer.zero_grad()</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>    dpo_loss.backward()</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>    dpo_optimizer.step()</span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>dpo_policy <span class="op">=</span> torch.softmax(</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>    torch.log(reference) <span class="op">+</span> log_ratio.detach(), dim<span class="op">=</span><span class="dv">0</span></span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"analytic policy:"</span>, [<span class="bu">round</span>(x, <span class="dv">6</span>) <span class="cf">for</span> x <span class="kw">in</span> target_policy.tolist()])</span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"DPO policy:     "</span>, [<span class="bu">round</span>(x, <span class="dv">6</span>) <span class="cf">for</span> x <span class="kw">in</span> dpo_policy.tolist()])</span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(</span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a>    <span class="st">"largest policy difference:"</span>,</span>
<span id="cb11-30"><a href="#cb11-30" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"</span><span class="sc">{</span>(dpo_policy <span class="op">-</span> target_policy)<span class="sc">.</span><span class="bu">abs</span>()<span class="sc">.</span><span class="bu">max</span>()<span class="sc">.</span>item()<span class="sc">:.2e}</span><span class="ss">"</span>,</span>
<span id="cb11-31"><a href="#cb11-31" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>analytic policy: [0.164562, 0.20333, 0.331625, 0.300483]
DPO policy:      [0.164562, 0.20333, 0.331625, 0.300483]
largest policy difference: 5.55e-17</code></pre>
</div>
</div>
<p>The match to floating-point tolerance is an identity test under deliberately strong conditions: a fixed positive reference, a complete finite response set, all pairwise comparisons, preferences generated by one scalar reward, adequate policy capacity, and successful optimization—not that natural-language DPO and PPO are universally equivalent.</p>
<p>Several details are easy to overstate:</p>
<ul>
<li>DPO avoids an <strong>explicit standalone</strong> reward model and an online rollout loop during the optimization pass. Its policy–reference log ratio is still an implicit reward representation, and candidate generation plus labeling happened upstream.</li>
<li>The reference need not be the exact behavior policy that generated every pair. It is a density-ratio anchor with a support and modeling role.</li>
<li><span class="math inline">\(\beta\)</span> appears in the regularized derivation, but finite-data DPO does not enforce a hard realized-KL budget. Measure the KL.</li>
<li>The gradient rewards a <em>relative reference-adjusted margin</em>. Shared parameters mean one optimizer step need not raise the winner’s absolute probability and lower the loser’s absolute probability separately.</li>
<li>Offline pairs cannot correct missing candidate coverage by themselves. DPO can fit a stale or narrow preference dataset efficiently.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>What the finite identity proves
</div>
</div>
<div class="callout-body-container callout-body">
<p>The four-response test validates the derivation inside its scalar-preference, support, coverage, capacity, and optimization assumptions. The cyclic and proxy-pressure audits test two ways those assumptions fail.</p>
</div>
</div>
</section>
<section id="choose-by-the-feedback-and-exploration-you-have" class="level2" data-number="18.6">
<h2 data-number="18.6" class="anchored" data-anchor-id="choose-by-the-feedback-and-exploration-you-have"><span class="header-section-number">18.6</span> Choose by the feedback and exploration you have</h2>
<p>There is no universal method ranking. Start by naming the information source and whether new responses must be explored during optimization, as <a href="#tbl-alignment-route-choice" class="quarto-xref">Table&nbsp;<span>18.1</span></a> makes explicit:</p>
<div id="tbl-alignment-route-choice" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-alignment-route-choice-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;18.1: Feedback source and exploration needs determine which alignment route is available.
</figcaption>
<div aria-describedby="tbl-alignment-route-choice-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Route</th>
<th>Supervision</th>
<th>Fitted quantity</th>
<th>Fresh samples?</th>
<th>Main risk</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Response-masked SFT</td>
<td>Demonstrated responses</td>
<td>Likelihood of demonstration tokens</td>
<td>No</td>
<td>Demonstration coverage and imitation target</td>
</tr>
<tr class="even">
<td>DPO</td>
<td>Fixed preferred/rejected pairs</td>
<td>Reference-adjusted preference margin</td>
<td>No</td>
<td>Pair coverage, reference, scalar-preference assumptions</td>
</tr>
<tr class="odd">
<td>Explicit RM + online policy optimization</td>
<td>Comparisons plus a reward model; current responses can be scored</td>
<td>Reward proxy, value function, and policy objective</td>
<td>Yes</td>
<td>Proxy shift, exploration, credit assignment, optimization stability</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>SFT may be enough when demonstrations directly specify the desired behavior. Fixed preference data may favor an offline direct method when comparison coverage is already good. Online methods can generate from the changing policy and request or compute fresh feedback, which matters when exploration is part of the task. They also add a larger failure and evaluation surface.</p>
<p>Chapter 17’s axis remains orthogonal. SFT, DPO, or an online policy objective may update full weights, a LoRA branch, or another permitted state. Parameter efficiency changes the write surface and resource bill—not the rubric, comparison coverage, or reward fidelity.</p>
<p>Variants rearrange sampling, scoring, and labeling. Rejection-sampling fine-tuning selects high-scoring samples and imitates them. AI feedback replaces or supplements human labels but inherits the evaluator model’s coverage and biases. Constitutional AI, for example, combines supervised critique and revision with later preference-based RL guided by written principles. These are useful routes for further study—not a reason to turn the durable chapter into an acronym list.</p>
</section>
<section id="alignment-is-an-evaluation-contract" class="level2" data-number="18.7">
<h2 data-number="18.7" class="anchored" data-anchor-id="alignment-is-an-evaluation-contract"><span class="header-section-number">18.7</span> Alignment is an evaluation contract</h2>
<p>An optimization loss is one line in a much larger contract—a credible report connects the people and prompts that created feedback to independent tests of the policy that will actually be used:</p>
<!-- NOVEL: needs sign-off -->
<div id="cell-fig-alignment-contract" class="cell" data-fig-height="4.5" data-fig-width="10" data-execution_count="11">
<div class="cell-output cell-output-display">
<div id="fig-alignment-contract" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Four connected cards show the feedback record, reward-model audit, policy audit, and model card. Each card lists the evidence required before moving to the next, with a final warning that documentation is not certification.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-alignment-contract-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="18-alignment_files/figure-html/fig-alignment-contract-output-1.png" alt="Four connected cards show the feedback record, reward-model audit, policy audit, and model card. Each card lists the evidence required before moving to the next, with a final warning that documentation is not certification." width="950" height="422" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-alignment-contract-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;18.7: Alignment evaluation is a chain of evidence, not one score. The feedback record identifies the rubric, reviewers, prompts, candidates, ties, and disagreement. Reward-model audits hold out prompts and test calibration and newer-policy responses. Policy audits add blinded judgments, realized KL, length and style shifts, retained capabilities, and relevant slices. A model card records intended and out-of-scope uses, data and feedback provenance, limitations, and versioning; it does not certify safety.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The feedback report should identify the prompt distribution, selection policy for candidates, rubric, reviewer population, and aggregation rule. If several pairs came from one ranked set, they are correlated—keep their prompt together across splits and cluster uncertainty at the prompt level. Randomize A/B order, retain ties, and disclose disagreement rather than converting it silently into certainty.</p>
<p>Reward-model evaluation should include held-out pair log loss, calibration or Brier score, and tests on candidates from newer policies. Policy evaluation must go beyond reward: blinded independent preferences, task-specific success, realized KL to the reference, response-length and refusal shifts, retained capabilities, and safety or domain slices relevant to intended use. Give sample counts and uncertainty. A raw gap between two slices is not automatically statistically meaningful.</p>
<p>An LLM can assist as a judge—another measurement instrument. Published audits have found position, verbosity, and self-enhancement biases. Blinding model identities, swapping candidate order, keeping ties, and validating against human judgments are important safeguards.</p>
<p>The instructor calls a <strong>model card</strong> a model’s nutritional label—the analogy works: record model and training details, intended users and uses, out-of-scope uses, data and feedback provenance, evaluation conditions, slice results, limitations, version, and contact. A label helps a reader make an informed decision—it does not prevent misuse, prove that omitted groups are safe, or convert a conditional evaluation into a certificate.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Write the evaluation contract before optimization
</div>
</div>
<div class="callout-body-container callout-body">
<p>Predeclare the rubric, feedback population, prompt and candidate coverage, ties, primary policy outcomes, retained capabilities, slices, decoding settings, and drift measure. Then a rising training objective has a declared external test. Without that contract, “better aligned” can collapse into “the optimizer increased its own score.”</p>
</div>
</div>
</section>
<section id="the-next-question-where-did-the-generator-come-from" class="level2" data-number="18.8">
<h2 data-number="18.8" class="anchored" data-anchor-id="the-next-question-where-did-the-generator-come-from"><span class="header-section-number">18.8</span> The next question: where did the generator come from?</h2>
<p><strong>A judge is not a generator</strong>—a reward model can rank or score completed responses; it does not explain how a model learned a distribution from which responses can be sampled. RLHF and DPO begin with a generator already in hand.</p>
<p><a href="../../chapters/interludes/making-pca-learnable.html">The autoencoder interlude</a> already traced reconstruction from PCA’s linear geometry to trainable nonlinear codes. <a href="19-generative.html" class="quarto-xref"><span>Chapter 19</span></a> begins at the next missing contract: how a model defines or learns a distribution and turns it into samples, then develops variational autoencoders, adversarial learning, and diffusion. Chapter 18 changes the behavior of a generator—Chapter 19 studies the machinery that makes generation possible.</p>
</section>
<section id="okay-so-where-to-update-and-what-to-optimize-are-separate" class="level2" data-number="18.9">
<h2 data-number="18.9" class="anchored" data-anchor-id="okay-so-where-to-update-and-what-to-optimize-are-separate"><span class="header-section-number">18.9</span> Okay, so — where to update and what to optimize are separate</h2>
<ol type="1">
<li><strong>Update location and objective are separate axes.</strong> Full tuning, LoRA, and soft prompts decide where gradients may write. SFT, preference margins, and sampled rewards decide what assigns blame.</li>
<li><strong>SFT imitates demonstrated response tokens.</strong> A completion mask keeps prompt and padding targets out of the loss. Demonstrations can encode quality; preference data supplies a different, comparative signal.</li>
<li><strong>A preference is conditional evidence.</strong> Bradley–Terry turns score differences into probabilities, but reward zero points are unidentified and cyclic aggregate preferences need not fit one scalar ordering.</li>
<li><strong>RLHF separates judge from actor.</strong> The reward model scores completed responses, the value function forecasts shaped return from prefixes, PPO uses a refreshed old policy, and reference KL uses a usually fixed anchor.</li>
<li><strong>Reference KL is a pressure dial.</strong> The finite optimum is <span class="math inline">\(\pi^*\propto\pi_{\mathrm{ref}}e^{r/\beta}\)</span>. More pressure can raise proxy reward; it cannot repair a proxy’s missing feature.</li>
<li><strong>DPO removes an explicit stage, not the assumptions.</strong> The four-response identity is exact under scalar preferences, compatible support, complete coverage, adequate capacity, and successful optimization. Realized KL and generated behavior still need measurement.</li>
<li><strong>Alignment is an evaluation contract, not a certificate.</strong> State who judged which candidates under what rubric, then evaluate the current policy independently and document intended use, slices, uncertainty, and limitations.</li>
</ol>
</section>
<section id="sources-and-further-reading" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="sources-and-further-reading">Sources and further reading</h2>
<ul>
<li><a href="https://arxiv.org/abs/2109.01652">Wei et al., <em>Finetuned Language Models Are Zero-Shot Learners</em></a>.</li>
<li><a href="https://proceedings.neurips.cc/paper/2017/hash/d5e2c0adad503c91f91df240d0cd4e49-Abstract.html">Christiano et al., <em>Deep Reinforcement Learning from Human Preferences</em></a>.</li>
<li><a href="https://proceedings.neurips.cc/paper/2020/hash/1f89885d556929e98d3ef9b86448f951-Abstract.html">Stiennon et al., <em>Learning to Summarize from Human Feedback</em></a>: feedback training and overoptimization.</li>
<li><a href="https://arxiv.org/abs/2112.00861">Askell et al., <em>A General Language Assistant as a Laboratory for Alignment</em></a>: helpful, honest, and harmless framing.</li>
<li><a href="https://proceedings.neurips.cc/paper_files/paper/2022/hash/b1efde53be364a73914f58805a001731-Abstract.html">Ouyang et al., <em>Training Language Models to Follow Instructions with Human Feedback</em></a>: SFT, reward modeling, PPO, and scope.</li>
<li><a href="https://arxiv.org/abs/1707.06347">Schulman et al., <em>Proximal Policy Optimization Algorithms</em></a>: the clipped policy-ratio surrogate.</li>
<li><a href="https://proceedings.neurips.cc/paper_files/paper/2023/hash/a85b405ed65c6477a4fe8302b5e06ce7-Abstract-Conference.html">Rafailov et al., <em>Direct Preference Optimization</em></a>: the reward–policy identity and DPO loss.</li>
<li><a href="https://proceedings.mlr.press/v202/gao23h.html">Gao et al., <em>Scaling Laws for Reward Model Overoptimization</em></a>: controlled proxy-overoptimization studies.</li>
<li><a href="https://arxiv.org/abs/1810.03993">Mitchell et al., <em>Model Cards for Model Reporting</em></a>: evaluation and documentation contracts.</li>
<li><a href="https://proceedings.neurips.cc/paper_files/paper/2023/hash/91f18a1287b398d378ef22505bf41832-Abstract-Datasets_and_Benchmarks.html">Zheng et al., <em>Judging LLM-as-a-Judge</em></a>: model-judge biases.</li>
<li><a href="https://arxiv.org/abs/2212.08073">Bai et al., <em>Constitutional AI</em></a>: critique, revision, and AI feedback.</li>
</ul>
</section>
<section id="exercises" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercises">Exercises</h2>
<ol type="1">
<li><strong>(Pencil.)</strong> Given <span class="math inline">\(P(A\succ B)=0.8\)</span> and <span class="math inline">\(P(B\succ C)=0.7\)</span>, compute the implied <span class="math inline">\(P(A\succ C)\)</span> under Bradley–Terry. Prove that adding the same <span class="math inline">\(c(x)\)</span> to every candidate reward leaves all pairwise probabilities unchanged. Then add <span class="math inline">\(P(C\succ A)=0.6\)</span> and explain why the inconsistency diagnoses model misspecification—not reviewer error.</li>
<li><strong>(Code and hygiene.)</strong> Extend <code>completion_log_probability</code> to chosen and rejected batches with unequal padding. Include EOS but exclude prompt and padding targets; assert that changing excluded logits leaves both sums unchanged. Compute the DPO margin and verify identical policy/reference tokenizers, truncation, and masks.</li>
<li><strong>(Proof and code.)</strong> Derive <a href="#eq-gibbs-policy" class="quarto-xref">Equation&nbsp;<span>18.5</span></a> with a Lagrange multiplier. Reproduce the four-response <span class="math inline">\(\beta\)</span> sweep and verify normalized policies and nonnegative KL. Train DPO using only A–B and C–D; initialize the two connected components with different shared offsets and show that their margins can agree while probability mass between components remains unidentified.</li>
<li><strong>(Code and interpretation.)</strong> Reproduce the proxy-pressure study. Predeclare one repair: expand feedback support, add a missing feature, or both. Report held-out comparison loss, learned coefficients, realized KL, proxy reward, and designed utility as mean <span class="math inline">\(\pm\)</span> seed SD over five seeds. Explain why improving in-range log loss alone may not change the policy failure.</li>
<li><strong>(Decision audit.)</strong> Choose medicine, creative writing, or executable verification. Using <a href="#tbl-alignment-route-choice" class="quarto-xref">Table&nbsp;<span>18.1</span></a>, compare SFT, DPO, and online reward in a model card covering supervision/write surface, reference/exploration, evaluators, unsupported claims, retention/slices, and uncertainty.</li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/shakeri-lab\.github\.io\/dl-book\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../chapters/part5/17-peft-quantization.html" class="pagination-link" aria-label="Adapting Pretrained Models: Prompting, PEFT, Quantization">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Adapting Pretrained Models: Prompting, PEFT, Quantization</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/part5/19-generative.html" class="pagination-link" aria-label="Generative Models: From Codes to Samples">
        <span class="nav-page-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Generative Models: From Codes to Samples</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Heman Shakeri · Text CC BY-NC-SA 4.0 · Code MIT · School of Data Science, University of Virginia</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/Shakeri-Lab/dl-book/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Companion to <a href="https://shakeri-lab.github.io/dl-course-site/">DS 6050 Deep Learning</a></p>
</div>
  </div>
</footer>




</body></html>