<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>20&nbsp; Multimodal Learning: One Space, Two Views – Deep Learning: Making It Learnable</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/epilogue.html" rel="next">
<link href="../../chapters/part5/19-generative.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-2c6940bf2fa6cf01ae6e8f10fcb58cc9.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>
  // Book math macros — keep in sync with tex/macros.tex (PDF path).
  // MathJax reads this config because it is defined before the MathJax
  // script loads (Quarto places include-in-header above its math script).
  window.MathJax = {
    tex: {
      macros: {
        E: "\\mathbb{E}",
        Ex: "\\operatorname{E}",
        var: "\\operatorname{Var}",
        cov: "\\operatorname{Cov}",
        imp: "\\Rightarrow",
        argmax: "\\operatorname*{arg\\,max}",
        argmin: "\\operatorname*{arg\\,min}",
        norm: ["\\left\\lVert#1\\right\\rVert", 1],
        vect: ["\\boldsymbol{#1}", 1],
        matr: ["\\boldsymbol{#1}", 1],
        R: "\\mathbb{R}",
        dd: "\\mathrm{d}",
        loss: "\\mathcal{L}"
      }
    }
  };
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/part5/17-peft-quantization.html">The Pretrained Era</a></li><li class="breadcrumb-item"><a href="../../chapters/part5/20-multimodal.html"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Multimodal Learning: One Space, Two Views</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Deep Learning: Making It Learnable</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/Shakeri-Lab/dl-book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">From Lines to Networks</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/01-linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Linear Regression, the Mother Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/02-logistic-softmax.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Linear Models that Classify: Logistic and Softmax</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/03-nonlinearity-mlp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Nonlinearity and the MLP</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/04-training-loss-sgd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Training: Loss and Stochastic Gradient Descent</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/05-backpropagation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Backpropagation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/06-generalization-inductive-bias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">When It Fails: Generalization in Pictures, and Inductive Bias</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/interludes/learning-by-experiment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Who Trains the Trainer? Learning by Experiment</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Vision: Learning the Filters</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/07-filters-convolution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Filters and Convolution (Fixed Kernels)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/08-cnn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">CNNs: Making the Filters Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/09-modern-cnns-transfer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Modern CNNs and Transfer Learning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/interludes/making-pca-learnable.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Interlude: Making PCA Learnable</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Sequences</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part3/10-sequences-rnn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Sequences and Recurrence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part3/11-encoder-decoder.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Encoder–Decoder, Teacher Forcing, Beam Search</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Attention: Learning the Similarity</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/12-kernel-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Kernel Regression: Attention Before It Was Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/13-attention.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Attention: Making the Kernel Learnable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/14-self-attention-transformer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Self-Attention and the Transformer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/15-bert-pretraining.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">The BERT Moment: Pretraining as the New Regime</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/16-vit-scaling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Vision Transformers and Scaling Laws</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">The Pretrained Era</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/17-peft-quantization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Adapting Pretrained Models: Prompting, PEFT, Quantization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/18-alignment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Alignment and RL Fine-Tuning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/19-generative.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Generative Models: From Codes to Samples</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/20-multimodal.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Multimodal Learning: One Space, Two Views</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/epilogue.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Epilogue: The Question Is Yours</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a1-linear-algebra.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Linear Algebra and the SVD</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a2-tensors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Tensors in Practice</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a3-precision-performance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Numerical Precision and Hardware Efficiency</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendices/a4-notation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Notation</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
<div class="quarto-sidebar-footer"><div class="sidebar-footer-item">
<p><a href="https://shakeri-lab.github.io/dl-book/#revision-notes">Revision notes</a></p>
</div></div></nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#chapter-2-returns-scores-become-weights" id="toc-chapter-2-returns-scores-become-weights" class="nav-link active" data-scroll-target="#chapter-2-returns-scores-become-weights"><span class="header-section-number">20.1</span> Chapter 2 returns: scores become weights</a>
  <ul class="collapse">
  <li><a href="#what-counts-as-a-negative" id="toc-what-counts-as-a-negative" class="nav-link" data-scroll-target="#what-counts-as-a-negative">What counts as a negative?</a></li>
  </ul></li>
  <li><a href="#make-the-pair-relation-learnable" id="toc-make-the-pair-relation-learnable" class="nav-link" data-scroll-target="#make-the-pair-relation-learnable"><span class="header-section-number">20.2</span> Make the pair relation learnable</a></li>
  <li><a href="#retrieval-is-not-generation" id="toc-retrieval-is-not-generation" class="nav-link" data-scroll-target="#retrieval-is-not-generation"><span class="header-section-number">20.3</span> Retrieval is not generation</a>
  <ul class="collapse">
  <li><a href="#zero-shot-classification-is-retrieval-over-descriptions" id="toc-zero-shot-classification-is-retrieval-over-descriptions" class="nav-link" data-scroll-target="#zero-shot-classification-is-retrieval-over-descriptions">Zero-shot classification is retrieval over descriptions</a></li>
  </ul></li>
  <li><a href="#shortcuts-enter-through-the-pair-definition" id="toc-shortcuts-enter-through-the-pair-definition" class="nav-link" data-scroll-target="#shortcuts-enter-through-the-pair-definition"><span class="header-section-number">20.4</span> Shortcuts enter through the pair definition</a>
  <ul class="collapse">
  <li><a href="#a-minimum-evaluation-contract" id="toc-a-minimum-evaluation-contract" class="nav-link" data-scroll-target="#a-minimum-evaluation-contract">A minimum evaluation contract</a></li>
  </ul></li>
  <li><a href="#okay-so-two-towers-learn-a-comparison-not-a-world-model" id="toc-okay-so-two-towers-learn-a-comparison-not-a-world-model" class="nav-link" data-scroll-target="#okay-so-two-towers-learn-a-comparison-not-a-world-model"><span class="header-section-number">20.5</span> Okay, so — two towers learn a comparison, not a world model</a></li>
  <li><a href="#sources-and-further-reading" id="toc-sources-and-further-reading" class="nav-link" data-scroll-target="#sources-and-further-reading">Sources and further reading</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/Shakeri-Lab/dl-book/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/part5/17-peft-quantization.html">The Pretrained Era</a></li><li class="breadcrumb-item"><a href="../../chapters/part5/20-multimodal.html"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Multimodal Learning: One Space, Two Views</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-20-multimodal" class="quarto-section-identifier"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Multimodal Learning: One Space, Two Views</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<!-- draft-sources:
     sources/12.1S-Multimodal.tex
     upstream Module 12/12.1S Multimodal.tex
       SHA-256 21c0751a49b44efe1c1c21e38246ca1b68575bb100c05704cfe2d32de32caaf4
     upstream Module 12/12.0 Multimodal_GenAI.tex
       SHA-256 52e0e1f1239d44262838653419f753b612bf1538ccbe5003d43e1fb9cda13dc8 -->
<!-- lecture-source:
     Module 12 is slide-only; no corresponding recorded-video transcript is present
     in the course transcript archive. The instructor spine is the sanitized
     sources/12.1S-Multimodal.tex topic-and-equation map.
     primary sources: van den Oord, Li, and Vinyals 2018; Radford et al. 2021;
                      Jia et al. 2021
     official framework references: PyTorch F.normalize and F.cross_entropy
     provenance note: all prose, derivations, typed PyTorch, synthetic data,
     experiments, and figures are independently produced. Course-deck code,
     external images, product examples, model implementations, benchmark tables,
     runtime downloads, and D2L material were not reproduced. The paired-data study
     is a finite CPU mechanism test, not a natural image--language benchmark. -->
<p>We have learned vision and language in separate coordinate systems. Chapter 16 turned an image into patch tokens. Chapters 14 and 15 turned text into contextual token representations. Those encoders can each organize their own modality—but nothing says that an image vector and a text vector mean the same thing merely because they have the same length.</p>
<p>Let us make the problem concrete. Suppose row 7 of an image table and row 7 of a text table describe the same event. The image has 14 measured coordinates; the text has 11. We do not need either raw coordinate system to imitate the other. We need two learned maps that preserve the <em>pair relation</em>:</p>
<p><span class="math display">\[
\text{image view}
\;\longrightarrow\;
\text{shared coordinates}
\;\longleftarrow\;
\text{text view}.
\]</span></p>
<p>This is the central move in <strong>multimodal representation learning</strong>. Different modalities keep different encoders, while paired observations teach those encoders how to become comparable. The learned space can support cross-modal retrieval and, under a carefully bounded candidate construction, zero-shot classification. It does not by itself create a caption, synthesize an image, or prove that the representation has captured every meaning we care about—that boundary will matter throughout the chapter.</p>
<!-- NOVEL: needs sign-off -->
<div id="cell-fig-two-tower-contract" class="cell" data-fig-height="4.5" data-fig-width="10" data-execution_count="1">
<div class="cell-output cell-output-display">
<div id="fig-two-tower-contract" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A blue image tower and orange text tower map differently shaped inputs to normalized embeddings. Arrows lead to a three by three cosine-similarity matrix whose diagonal cells are green and larger than the off-diagonal entries.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-two-tower-contract-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="20-multimodal_files/figure-html/fig-two-tower-contract-output-1.png" alt="A blue image tower and orange text tower map differently shaped inputs to normalized embeddings. Arrows lead to a three by three cosine-similarity matrix whose diagonal cells are green and larger than the off-diagonal entries." width="950" height="422" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-two-tower-contract-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20.1: Two modalities enter different encoders and leave as normalized vectors in one comparison space. For a batch of three declared pairs, every image is scored against every text; the green diagonal marks the three pair relations supplied by the data.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The small matrix already tells us what the training problem must do. Each row is one image query. Each column is one text candidate. Row 1 should select column 1, row 2 should select column 2, and so on. We have seen this machine before.</p>
<section id="chapter-2-returns-scores-become-weights" class="level2" data-number="20.1">
<h2 data-number="20.1" class="anchored" data-anchor-id="chapter-2-returns-scores-become-weights"><span class="header-section-number">20.1</span> Chapter 2 returns: scores become weights</h2>
<p>Let a minibatch contain <span class="math inline">\(B\)</span> declared pairs <span class="math inline">\((x_i^{(I)},x_i^{(T)})\)</span>. The image encoder <span class="math inline">\(f_\theta:\mathbb{R}^{d_I}\to\mathbb{R}^{d}\)</span> and text encoder <span class="math inline">\(g_\phi:\mathbb{R}^{d_T}\to\mathbb{R}^{d}\)</span> may have completely different internal architectures. Their interiors may differ completely—their outputs must agree only in the last dimension. We normalize each output to unit length:</p>
<p><span id="eq-multimodal-normalize"><span class="math display">\[
u_i=\frac{f_\theta(x_i^{(I)})}{\lVert f_\theta(x_i^{(I)})\rVert_2},
\qquad
v_i=\frac{g_\phi(x_i^{(T)})}{\lVert g_\phi(x_i^{(T)})\rVert_2},
\qquad u_i,v_i\in\mathbb{R}^{d}.
\tag{20.1}\]</span></span></p>
<p>Now the dot product is cosine similarity. For every cross-modal pair in the batch, form</p>
<p><span id="eq-multimodal-score"><span class="math display">\[
S_{ij}=\frac{u_i^\top v_j}{\tau},
\qquad
\matr{S}\in\mathbb{R}^{B\times B},
\tag{20.2}\]</span></span></p>
<p>where <span class="math inline">\(\tau&gt;0\)</span> is the <strong>temperature</strong>. Dividing by a small temperature spreads the logits farther apart; a larger temperature softens them. Temperature does not decide which pair is correct—it decides how sharply the softmax reacts to score differences.</p>
<p>Chapter 2 introduced softmax as the <strong>scores-to-weights machine</strong>. Apply it across row <span class="math inline">\(i\)</span>:</p>
<p><span id="eq-image-text-softmax"><span class="math display">\[
p^{I\rightarrow T}_{ij}
=\frac{\exp(S_{ij})}{\sum_{k=1}^{B}\exp(S_{ik})}.
\tag{20.3}\]</span></span></p>
<p>The declared mate of image <span class="math inline">\(i\)</span> is text <span class="math inline">\(i\)</span>, so the image-to-text loss is ordinary cross-entropy with labels <span class="math inline">\(0,1,\ldots,B-1\)</span>:</p>
<p><span id="eq-image-text-infonce"><span class="math display">\[
\mathcal{L}_{I\rightarrow T}
=-\frac{1}{B}\sum_{i=1}^{B}\log p^{I\rightarrow T}_{ii}.
\tag{20.4}\]</span></span></p>
<p>This form is commonly called a contrastive or <strong>InfoNCE-style</strong> objective. The batch does two jobs at once—it supplies <span class="math inline">\(B\)</span> declared matches along the diagonal, and for each query it supplies <span class="math inline">\(B-1\)</span> alternative candidates off the diagonal. We do not need to write a separate binary loss for every pair—the score matrix organizes the whole comparison. And note which case this is in <a href="../part1/04-training-loss-sgd.html#sec-04-estimator-cases" class="quarto-xref"><span>Section 4.6.1</span></a>’s taxonomy: <strong>Case 3</strong>. The batch is not estimating some full-data contrastive loss — the <span class="math inline">\(B-1\)</span> candidates <em>define</em> the objective, so changing <span class="math inline">\(B\)</span> changes what is being optimized, and batch size here is protocol, reported like any other design choice.</p>
<p>But one direction asks only whether each image can choose its text. Turn the score matrix around and ask whether each text can choose its image:</p>
<p><span id="eq-text-image-infonce"><span class="math display">\[
\mathcal{L}_{T\rightarrow I}
=-\frac{1}{B}\sum_{j=1}^{B}
\log\frac{\exp(S_{jj})}{\sum_{k=1}^{B}\exp(S_{kj})}.
\tag{20.5}\]</span></span></p>
<p>The <strong>symmetric batch contrastive loss</strong> is</p>
<p><span id="eq-symmetric-infonce"><span class="math display">\[
\mathcal{L}_{\mathrm{sym}}
=\frac{1}{2}
\left(\mathcal{L}_{I\rightarrow T}+\mathcal{L}_{T\rightarrow I}\right).
\tag{20.6}\]</span></span></p>
<p>Notice the exact reuse: <a href="#eq-image-text-softmax" class="quarto-xref">Equation&nbsp;<span>20.3</span></a> is Chapter 2’s multiclass classifier, but the classes are the candidates currently in the batch. The class set changes with the batch—what remains fixed is the rule that the paired row and column share an index.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Paired data is supervision
</div>
</div>
<div class="callout-body-container callout-body">
<p>No manual object class is required, but the correspondence <span class="math inline">\((x_i^{(I)},x_i^{(T)})\)</span> is still a training label. In web data that relation may be weak, incomplete, or wrong. Calling the procedure “self-supervised” must not erase the work, noise, consent, or provenance involved in creating those pairs.</p>
</div>
</div>
<section id="what-counts-as-a-negative" class="level3">
<h3 class="anchored" data-anchor-id="what-counts-as-a-negative">What counts as a negative?</h3>
<p>The loss knows <strong>declared mates</strong>—not semantic truth. An off-diagonal caption may describe the same concept as the diagonal caption. Two photographs may show the same event. In those cases the standard one-positive loss treats a plausible match as an alternative to suppress. Larger batches provide more alternatives—but they can also provide more false negatives.</p>
<p>This distinction is easy to miss because the code is so compact:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>image_embedding <span class="op">=</span> F.normalize(image_encoder(image), dim<span class="op">=-</span><span class="dv">1</span>)  <span class="co"># (B, d)</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>text_embedding <span class="op">=</span> F.normalize(text_encoder(text), dim<span class="op">=-</span><span class="dv">1</span>)     <span class="co"># (B, d)</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>logits <span class="op">=</span> image_embedding <span class="op">@</span> text_embedding.T <span class="op">/</span> temperature   <span class="co"># (B, B)</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>labels <span class="op">=</span> torch.arange(logits.shape[<span class="dv">0</span>])</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>loss <span class="op">=</span> <span class="fl">0.5</span> <span class="op">*</span> (</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    F.cross_entropy(logits, labels)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    <span class="op">+</span> F.cross_entropy(logits.T, labels)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Every line has a contract. The two encoders end at the same width; normalization makes the dot product angular; the transpose reverses retrieval direction; and the target indices assert that the batch diagonal contains the pair relation. If the data loader shuffles one modality without shuffling the other, the program still runs—the supervision has simply become false.</p>
</section>
</section>
<section id="make-the-pair-relation-learnable" class="level2" data-number="20.2">
<h2 data-number="20.2" class="anchored" data-anchor-id="make-the-pair-relation-learnable"><span class="header-section-number">20.2</span> Make the pair relation learnable</h2>
<p>Let us test that last claim directly. We will not download images or tokenize a corpus. Instead, one hidden five-dimensional event generates two noisy nonlinear views: a 14-coordinate “image” measurement and an 11-coordinate “text” measurement. The raw features differ, but row <span class="math inline">\(i\)</span> in one table really does share a latent event with row <span class="math inline">\(i\)</span> in the other.</p>
<p>The protocol is fixed before the endpoint is opened:</p>
<ul>
<li>1,200 unique pairs are generated once, then split into 720 fit, 180 validation, and 300 held-out endpoint rows. Standardization uses fit statistics only—the validation and endpoint rows contribute no preprocessing estimates.</li>
<li>Each tower is a two-layer MLP and ends at a normalized 16-dimensional embedding. The complete model has 2,392 parameters.</li>
<li>Five model seeds, 6050–6054, share the same paired initialization and minibatch schedule between conditions. AdamW, 160 epochs, batch size 120, and <span class="math inline">\(\tau=0.08\)</span> are fixed.</li>
<li>The control replaces the fit-pair relation with one study-wide fixed derangement—every fit image is assigned the wrong text, with no fixed points. Architecture, initialization, optimizer, update count, and schedules stay matched.</li>
<li>Both conditions select checkpoints by the correct validation-pair loss. The 300-row endpoint is not used for model, hyperparameter, checkpoint, stopping, or analysis-design decisions within this study; it is consulted after those choices are fixed.</li>
</ul>
<p>The metric is <strong>Recall@<span class="math inline">\(k\)</span></strong>—for each query, rank every candidate in the other modality. Recall@<span class="math inline">\(k\)</span> is one when the declared mate lies among the first <span class="math inline">\(k\)</span> candidates and zero otherwise, then averaged across queries. With 300 unique candidates, random ranking has expected Recall@1 of <span class="math inline">\(1/300=0.0033\)</span> and Recall@5 of <span class="math inline">\(5/300=0.0167\)</span>.</p>
<!-- NOVEL: needs sign-off -->
<div id="ch20-paired-study" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Run the five-seed paired-versus-shuffled retrieval study</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="at">@dataclass</span>(frozen<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> PairedSplit:</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    image: Tensor</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    text: Tensor</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> make_paired_data() <span class="op">-&gt;</span> <span class="bu">tuple</span>[PairedSplit, PairedSplit, PairedSplit]:</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    generator <span class="op">=</span> torch.Generator().manual_seed(<span class="dv">1206050</span>)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    latent_dim, image_dim, text_dim <span class="op">=</span> <span class="dv">5</span>, <span class="dv">14</span>, <span class="dv">11</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    latent <span class="op">=</span> torch.randn(<span class="dv">1_200</span>, latent_dim, generator<span class="op">=</span>generator)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    image_map <span class="op">=</span> torch.randn(latent_dim, image_dim, generator<span class="op">=</span>generator)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    text_map <span class="op">=</span> torch.randn(latent_dim, text_dim, generator<span class="op">=</span>generator)</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    image <span class="op">=</span> torch.tanh(latent <span class="op">@</span> image_map <span class="op">/</span> latent_dim<span class="op">**</span><span class="fl">0.5</span>)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    text <span class="op">=</span> torch.tanh(latent <span class="op">@</span> text_map <span class="op">/</span> latent_dim<span class="op">**</span><span class="fl">0.5</span>)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    image <span class="op">+=</span> <span class="fl">0.045</span> <span class="op">*</span> torch.randn(image.shape, generator<span class="op">=</span>generator)</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>    text <span class="op">+=</span> <span class="fl">0.045</span> <span class="op">*</span> torch.randn(text.shape, generator<span class="op">=</span>generator)</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>    fit_end, validation_end <span class="op">=</span> <span class="dv">720</span>, <span class="dv">900</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>    image_mean <span class="op">=</span> image[:fit_end].mean(<span class="dv">0</span>, keepdim<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>    image_std <span class="op">=</span> image[:fit_end].std(<span class="dv">0</span>, keepdim<span class="op">=</span><span class="va">True</span>).clamp_min(<span class="fl">1e-6</span>)</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>    text_mean <span class="op">=</span> text[:fit_end].mean(<span class="dv">0</span>, keepdim<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>    text_std <span class="op">=</span> text[:fit_end].std(<span class="dv">0</span>, keepdim<span class="op">=</span><span class="va">True</span>).clamp_min(<span class="fl">1e-6</span>)</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>    image <span class="op">=</span> (image <span class="op">-</span> image_mean) <span class="op">/</span> image_std</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>    text <span class="op">=</span> (text <span class="op">-</span> text_mean) <span class="op">/</span> text_std</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>        PairedSplit(image[:fit_end], text[:fit_end]),</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>        PairedSplit(image[fit_end:validation_end], text[fit_end:validation_end]),</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>        PairedSplit(image[validation_end:], text[validation_end:]),</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> TwoTower(nn.Module):</span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, image_dim: <span class="bu">int</span>, text_dim: <span class="bu">int</span>, width: <span class="bu">int</span> <span class="op">=</span> <span class="dv">40</span>, embed_dim: <span class="bu">int</span> <span class="op">=</span> <span class="dv">16</span>):</span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.image_encoder <span class="op">=</span> nn.Sequential(</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>            nn.Linear(image_dim, width), nn.ReLU(), nn.Linear(width, embed_dim)</span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.text_encoder <span class="op">=</span> nn.Sequential(</span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a>            nn.Linear(text_dim, width), nn.ReLU(), nn.Linear(width, embed_dim)</span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, image: Tensor, text: Tensor) <span class="op">-&gt;</span> <span class="bu">tuple</span>[Tensor, Tensor]:</span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a>        image_embedding <span class="op">=</span> F.normalize(<span class="va">self</span>.image_encoder(image), dim<span class="op">=-</span><span class="dv">1</span>)</span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a>        text_embedding <span class="op">=</span> F.normalize(<span class="va">self</span>.text_encoder(text), dim<span class="op">=-</span><span class="dv">1</span>)</span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> image_embedding, text_embedding</span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-49"><a href="#cb2-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-50"><a href="#cb2-50" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> symmetric_loss(image_embedding: Tensor, text_embedding: Tensor, tau: <span class="bu">float</span> <span class="op">=</span> <span class="fl">0.08</span>) <span class="op">-&gt;</span> Tensor:</span>
<span id="cb2-51"><a href="#cb2-51" aria-hidden="true" tabindex="-1"></a>    logits <span class="op">=</span> image_embedding <span class="op">@</span> text_embedding.T <span class="op">/</span> tau  <span class="co"># (B, B)</span></span>
<span id="cb2-52"><a href="#cb2-52" aria-hidden="true" tabindex="-1"></a>    labels <span class="op">=</span> torch.arange(logits.shape[<span class="dv">0</span>])</span>
<span id="cb2-53"><a href="#cb2-53" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="fl">0.5</span> <span class="op">*</span> (</span>
<span id="cb2-54"><a href="#cb2-54" aria-hidden="true" tabindex="-1"></a>        F.cross_entropy(logits, labels) <span class="op">+</span> F.cross_entropy(logits.T, labels)</span>
<span id="cb2-55"><a href="#cb2-55" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb2-56"><a href="#cb2-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-57"><a href="#cb2-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-58"><a href="#cb2-58" aria-hidden="true" tabindex="-1"></a><span class="at">@torch.no_grad</span>()</span>
<span id="cb2-59"><a href="#cb2-59" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> pair_loss(model: TwoTower, split: PairedSplit) <span class="op">-&gt;</span> <span class="bu">float</span>:</span>
<span id="cb2-60"><a href="#cb2-60" aria-hidden="true" tabindex="-1"></a>    model.<span class="bu">eval</span>()</span>
<span id="cb2-61"><a href="#cb2-61" aria-hidden="true" tabindex="-1"></a>    image_embedding, text_embedding <span class="op">=</span> model(split.image, split.text)</span>
<span id="cb2-62"><a href="#cb2-62" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="bu">float</span>(symmetric_loss(image_embedding, text_embedding))</span>
<span id="cb2-63"><a href="#cb2-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-64"><a href="#cb2-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-65"><a href="#cb2-65" aria-hidden="true" tabindex="-1"></a><span class="at">@torch.no_grad</span>()</span>
<span id="cb2-66"><a href="#cb2-66" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> retrieval_metrics(model: TwoTower, split: PairedSplit) <span class="op">-&gt;</span> <span class="bu">dict</span>[<span class="bu">str</span>, <span class="bu">float</span>]:</span>
<span id="cb2-67"><a href="#cb2-67" aria-hidden="true" tabindex="-1"></a>    model.<span class="bu">eval</span>()</span>
<span id="cb2-68"><a href="#cb2-68" aria-hidden="true" tabindex="-1"></a>    image_embedding, text_embedding <span class="op">=</span> model(split.image, split.text)</span>
<span id="cb2-69"><a href="#cb2-69" aria-hidden="true" tabindex="-1"></a>    scores <span class="op">=</span> image_embedding <span class="op">@</span> text_embedding.T</span>
<span id="cb2-70"><a href="#cb2-70" aria-hidden="true" tabindex="-1"></a>    target <span class="op">=</span> torch.arange(scores.shape[<span class="dv">0</span>])</span>
<span id="cb2-71"><a href="#cb2-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-72"><a href="#cb2-72" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> recall_at_k(matrix: Tensor, k: <span class="bu">int</span>) <span class="op">-&gt;</span> <span class="bu">float</span>:</span>
<span id="cb2-73"><a href="#cb2-73" aria-hidden="true" tabindex="-1"></a>        candidates <span class="op">=</span> matrix.topk(k, dim<span class="op">=</span><span class="dv">1</span>).indices</span>
<span id="cb2-74"><a href="#cb2-74" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="bu">float</span>((candidates <span class="op">==</span> target[:, <span class="va">None</span>]).<span class="bu">any</span>(dim<span class="op">=</span><span class="dv">1</span>).<span class="bu">float</span>().mean())</span>
<span id="cb2-75"><a href="#cb2-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-76"><a href="#cb2-76" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> {</span>
<span id="cb2-77"><a href="#cb2-77" aria-hidden="true" tabindex="-1"></a>        <span class="st">"I→T R@1"</span>: recall_at_k(scores, <span class="dv">1</span>),</span>
<span id="cb2-78"><a href="#cb2-78" aria-hidden="true" tabindex="-1"></a>        <span class="st">"T→I R@1"</span>: recall_at_k(scores.T, <span class="dv">1</span>),</span>
<span id="cb2-79"><a href="#cb2-79" aria-hidden="true" tabindex="-1"></a>        <span class="st">"I→T R@5"</span>: recall_at_k(scores, <span class="dv">5</span>),</span>
<span id="cb2-80"><a href="#cb2-80" aria-hidden="true" tabindex="-1"></a>        <span class="st">"T→I R@5"</span>: recall_at_k(scores.T, <span class="dv">5</span>),</span>
<span id="cb2-81"><a href="#cb2-81" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb2-82"><a href="#cb2-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-83"><a href="#cb2-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-84"><a href="#cb2-84" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> derangement(size: <span class="bu">int</span>, generator: torch.Generator) <span class="op">-&gt;</span> Tensor:</span>
<span id="cb2-85"><a href="#cb2-85" aria-hidden="true" tabindex="-1"></a>    target <span class="op">=</span> torch.arange(size)</span>
<span id="cb2-86"><a href="#cb2-86" aria-hidden="true" tabindex="-1"></a>    <span class="cf">while</span> <span class="va">True</span>:</span>
<span id="cb2-87"><a href="#cb2-87" aria-hidden="true" tabindex="-1"></a>        order <span class="op">=</span> torch.randperm(size, generator<span class="op">=</span>generator)</span>
<span id="cb2-88"><a href="#cb2-88" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="kw">not</span> <span class="bu">bool</span>((order <span class="op">==</span> target).<span class="bu">any</span>()):</span>
<span id="cb2-89"><a href="#cb2-89" aria-hidden="true" tabindex="-1"></a>            <span class="cf">return</span> order</span>
<span id="cb2-90"><a href="#cb2-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-91"><a href="#cb2-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-92"><a href="#cb2-92" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> train_tower(</span>
<span id="cb2-93"><a href="#cb2-93" aria-hidden="true" tabindex="-1"></a>    seed: <span class="bu">int</span>,</span>
<span id="cb2-94"><a href="#cb2-94" aria-hidden="true" tabindex="-1"></a>    fit_split: PairedSplit,</span>
<span id="cb2-95"><a href="#cb2-95" aria-hidden="true" tabindex="-1"></a>    validation_split: PairedSplit,</span>
<span id="cb2-96"><a href="#cb2-96" aria-hidden="true" tabindex="-1"></a>    shuffled_pairs: <span class="bu">bool</span>,</span>
<span id="cb2-97"><a href="#cb2-97" aria-hidden="true" tabindex="-1"></a>) <span class="op">-&gt;</span> TwoTower:</span>
<span id="cb2-98"><a href="#cb2-98" aria-hidden="true" tabindex="-1"></a>    torch.manual_seed(seed)</span>
<span id="cb2-99"><a href="#cb2-99" aria-hidden="true" tabindex="-1"></a>    model <span class="op">=</span> TwoTower(fit_split.image.shape[<span class="dv">1</span>], fit_split.text.shape[<span class="dv">1</span>])</span>
<span id="cb2-100"><a href="#cb2-100" aria-hidden="true" tabindex="-1"></a>    optimizer <span class="op">=</span> torch.optim.AdamW(model.parameters(), lr<span class="op">=</span><span class="fl">2e-3</span>, weight_decay<span class="op">=</span><span class="fl">1e-3</span>)</span>
<span id="cb2-101"><a href="#cb2-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-102"><a href="#cb2-102" aria-hidden="true" tabindex="-1"></a>    pair_generator <span class="op">=</span> torch.Generator().manual_seed(<span class="dv">88_000</span>)</span>
<span id="cb2-103"><a href="#cb2-103" aria-hidden="true" tabindex="-1"></a>    text_order <span class="op">=</span> (</span>
<span id="cb2-104"><a href="#cb2-104" aria-hidden="true" tabindex="-1"></a>        derangement(<span class="bu">len</span>(fit_split.text), pair_generator)</span>
<span id="cb2-105"><a href="#cb2-105" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> shuffled_pairs <span class="cf">else</span> torch.arange(<span class="bu">len</span>(fit_split.text))</span>
<span id="cb2-106"><a href="#cb2-106" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb2-107"><a href="#cb2-107" aria-hidden="true" tabindex="-1"></a>    schedule_generator <span class="op">=</span> torch.Generator().manual_seed(<span class="dv">99_000</span> <span class="op">+</span> seed)</span>
<span id="cb2-108"><a href="#cb2-108" aria-hidden="true" tabindex="-1"></a>    schedules <span class="op">=</span> [</span>
<span id="cb2-109"><a href="#cb2-109" aria-hidden="true" tabindex="-1"></a>        torch.randperm(<span class="bu">len</span>(fit_split.image), generator<span class="op">=</span>schedule_generator)</span>
<span id="cb2-110"><a href="#cb2-110" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">160</span>)</span>
<span id="cb2-111"><a href="#cb2-111" aria-hidden="true" tabindex="-1"></a>    ]</span>
<span id="cb2-112"><a href="#cb2-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-113"><a href="#cb2-113" aria-hidden="true" tabindex="-1"></a>    best_validation <span class="op">=</span> <span class="bu">float</span>(<span class="st">"inf"</span>)</span>
<span id="cb2-114"><a href="#cb2-114" aria-hidden="true" tabindex="-1"></a>    best_state: <span class="bu">dict</span>[<span class="bu">str</span>, Tensor] <span class="op">|</span> <span class="va">None</span> <span class="op">=</span> <span class="va">None</span></span>
<span id="cb2-115"><a href="#cb2-115" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> epoch, order <span class="kw">in</span> <span class="bu">enumerate</span>(schedules, start<span class="op">=</span><span class="dv">1</span>):</span>
<span id="cb2-116"><a href="#cb2-116" aria-hidden="true" tabindex="-1"></a>        model.train()</span>
<span id="cb2-117"><a href="#cb2-117" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> rows <span class="kw">in</span> order.split(<span class="dv">120</span>):</span>
<span id="cb2-118"><a href="#cb2-118" aria-hidden="true" tabindex="-1"></a>            image_embedding, text_embedding <span class="op">=</span> model(</span>
<span id="cb2-119"><a href="#cb2-119" aria-hidden="true" tabindex="-1"></a>                fit_split.image[rows], fit_split.text[text_order[rows]]</span>
<span id="cb2-120"><a href="#cb2-120" aria-hidden="true" tabindex="-1"></a>            )</span>
<span id="cb2-121"><a href="#cb2-121" aria-hidden="true" tabindex="-1"></a>            loss <span class="op">=</span> symmetric_loss(image_embedding, text_embedding)</span>
<span id="cb2-122"><a href="#cb2-122" aria-hidden="true" tabindex="-1"></a>            optimizer.zero_grad(set_to_none<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-123"><a href="#cb2-123" aria-hidden="true" tabindex="-1"></a>            loss.backward()</span>
<span id="cb2-124"><a href="#cb2-124" aria-hidden="true" tabindex="-1"></a>            optimizer.step()</span>
<span id="cb2-125"><a href="#cb2-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-126"><a href="#cb2-126" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> epoch <span class="op">%</span> <span class="dv">5</span> <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb2-127"><a href="#cb2-127" aria-hidden="true" tabindex="-1"></a>            validation_loss <span class="op">=</span> pair_loss(model, validation_split)</span>
<span id="cb2-128"><a href="#cb2-128" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> validation_loss <span class="op">&lt;</span> best_validation:</span>
<span id="cb2-129"><a href="#cb2-129" aria-hidden="true" tabindex="-1"></a>                best_validation <span class="op">=</span> validation_loss</span>
<span id="cb2-130"><a href="#cb2-130" aria-hidden="true" tabindex="-1"></a>                best_state <span class="op">=</span> copy.deepcopy(model.state_dict())</span>
<span id="cb2-131"><a href="#cb2-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-132"><a href="#cb2-132" aria-hidden="true" tabindex="-1"></a>    <span class="cf">assert</span> best_state <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span></span>
<span id="cb2-133"><a href="#cb2-133" aria-hidden="true" tabindex="-1"></a>    model.load_state_dict(best_state)</span>
<span id="cb2-134"><a href="#cb2-134" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> model</span>
<span id="cb2-135"><a href="#cb2-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-136"><a href="#cb2-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-137"><a href="#cb2-137" aria-hidden="true" tabindex="-1"></a>fit_split, validation_split, held_out_split <span class="op">=</span> make_paired_data()</span>
<span id="cb2-138"><a href="#cb2-138" aria-hidden="true" tabindex="-1"></a>models: <span class="bu">dict</span>[<span class="bu">tuple</span>[<span class="bu">int</span>, <span class="bu">str</span>], TwoTower] <span class="op">=</span> {}</span>
<span id="cb2-139"><a href="#cb2-139" aria-hidden="true" tabindex="-1"></a>records: <span class="bu">list</span>[<span class="bu">dict</span>[<span class="bu">str</span>, <span class="bu">object</span>]] <span class="op">=</span> []</span>
<span id="cb2-140"><a href="#cb2-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-141"><a href="#cb2-141" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> seed <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">6050</span>, <span class="dv">6055</span>):</span>
<span id="cb2-142"><a href="#cb2-142" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> condition, shuffled_pairs <span class="kw">in</span> ((<span class="st">"paired"</span>, <span class="va">False</span>), (<span class="st">"shuffled"</span>, <span class="va">True</span>)):</span>
<span id="cb2-143"><a href="#cb2-143" aria-hidden="true" tabindex="-1"></a>        model <span class="op">=</span> train_tower(seed, fit_split, validation_split, shuffled_pairs)</span>
<span id="cb2-144"><a href="#cb2-144" aria-hidden="true" tabindex="-1"></a>        models[(seed, condition)] <span class="op">=</span> model</span>
<span id="cb2-145"><a href="#cb2-145" aria-hidden="true" tabindex="-1"></a>        records.append({</span>
<span id="cb2-146"><a href="#cb2-146" aria-hidden="true" tabindex="-1"></a>            <span class="st">"seed"</span>: seed,</span>
<span id="cb2-147"><a href="#cb2-147" aria-hidden="true" tabindex="-1"></a>            <span class="st">"condition"</span>: condition,</span>
<span id="cb2-148"><a href="#cb2-148" aria-hidden="true" tabindex="-1"></a>            <span class="st">"validation"</span>: retrieval_metrics(model, validation_split),</span>
<span id="cb2-149"><a href="#cb2-149" aria-hidden="true" tabindex="-1"></a>        })</span>
<span id="cb2-150"><a href="#cb2-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-151"><a href="#cb2-151" aria-hidden="true" tabindex="-1"></a><span class="co"># The endpoint is consulted after every design and checkpoint decision above.</span></span>
<span id="cb2-152"><a href="#cb2-152" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> record <span class="kw">in</span> records:</span>
<span id="cb2-153"><a href="#cb2-153" aria-hidden="true" tabindex="-1"></a>    model <span class="op">=</span> models[(<span class="bu">int</span>(record[<span class="st">"seed"</span>]), <span class="bu">str</span>(record[<span class="st">"condition"</span>]))]</span>
<span id="cb2-154"><a href="#cb2-154" aria-hidden="true" tabindex="-1"></a>    record[<span class="st">"held_out"</span>] <span class="op">=</span> retrieval_metrics(model, held_out_split)</span>
<span id="cb2-155"><a href="#cb2-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-156"><a href="#cb2-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-157"><a href="#cb2-157" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> report(split_name: <span class="bu">str</span>, key: <span class="bu">str</span>) <span class="op">-&gt;</span> <span class="va">None</span>:</span>
<span id="cb2-158"><a href="#cb2-158" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(split_name)</span>
<span id="cb2-159"><a href="#cb2-159" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> condition <span class="kw">in</span> (<span class="st">"paired"</span>, <span class="st">"shuffled"</span>):</span>
<span id="cb2-160"><a href="#cb2-160" aria-hidden="true" tabindex="-1"></a>        chosen <span class="op">=</span> [record <span class="cf">for</span> record <span class="kw">in</span> records <span class="cf">if</span> record[<span class="st">"condition"</span>] <span class="op">==</span> condition]</span>
<span id="cb2-161"><a href="#cb2-161" aria-hidden="true" tabindex="-1"></a>        fields <span class="op">=</span> <span class="bu">list</span>(chosen[<span class="dv">0</span>][key].keys())</span>
<span id="cb2-162"><a href="#cb2-162" aria-hidden="true" tabindex="-1"></a>        summary <span class="op">=</span> []</span>
<span id="cb2-163"><a href="#cb2-163" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> field <span class="kw">in</span> fields:</span>
<span id="cb2-164"><a href="#cb2-164" aria-hidden="true" tabindex="-1"></a>            values <span class="op">=</span> [<span class="bu">float</span>(record[key][field]) <span class="cf">for</span> record <span class="kw">in</span> chosen]</span>
<span id="cb2-165"><a href="#cb2-165" aria-hidden="true" tabindex="-1"></a>            summary.append(<span class="ss">f"</span><span class="sc">{</span>field<span class="sc">}</span><span class="ss"> </span><span class="sc">{</span>mean(values)<span class="sc">:.4f}</span><span class="ss"> (SD </span><span class="sc">{</span>stdev(values)<span class="sc">:.4f}</span><span class="ss">)"</span>)</span>
<span id="cb2-166"><a href="#cb2-166" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>condition<span class="sc">:8s}</span><span class="ss">: "</span> <span class="op">+</span> <span class="st">"; "</span>.join(summary))</span>
<span id="cb2-167"><a href="#cb2-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-168"><a href="#cb2-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-169"><a href="#cb2-169" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> report_paired_contrast(field: <span class="bu">str</span>) <span class="op">-&gt;</span> <span class="va">None</span>:</span>
<span id="cb2-170"><a href="#cb2-170" aria-hidden="true" tabindex="-1"></a>    differences <span class="op">=</span> []</span>
<span id="cb2-171"><a href="#cb2-171" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> seed <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">6050</span>, <span class="dv">6055</span>):</span>
<span id="cb2-172"><a href="#cb2-172" aria-hidden="true" tabindex="-1"></a>        paired <span class="op">=</span> <span class="bu">next</span>(</span>
<span id="cb2-173"><a href="#cb2-173" aria-hidden="true" tabindex="-1"></a>            record <span class="cf">for</span> record <span class="kw">in</span> records</span>
<span id="cb2-174"><a href="#cb2-174" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> record[<span class="st">"seed"</span>] <span class="op">==</span> seed <span class="kw">and</span> record[<span class="st">"condition"</span>] <span class="op">==</span> <span class="st">"paired"</span></span>
<span id="cb2-175"><a href="#cb2-175" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb2-176"><a href="#cb2-176" aria-hidden="true" tabindex="-1"></a>        shuffled <span class="op">=</span> <span class="bu">next</span>(</span>
<span id="cb2-177"><a href="#cb2-177" aria-hidden="true" tabindex="-1"></a>            record <span class="cf">for</span> record <span class="kw">in</span> records</span>
<span id="cb2-178"><a href="#cb2-178" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> record[<span class="st">"seed"</span>] <span class="op">==</span> seed <span class="kw">and</span> record[<span class="st">"condition"</span>] <span class="op">==</span> <span class="st">"shuffled"</span></span>
<span id="cb2-179"><a href="#cb2-179" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb2-180"><a href="#cb2-180" aria-hidden="true" tabindex="-1"></a>        differences.append(</span>
<span id="cb2-181"><a href="#cb2-181" aria-hidden="true" tabindex="-1"></a>            <span class="bu">float</span>(paired[<span class="st">"held_out"</span>][field]) <span class="op">-</span> <span class="bu">float</span>(shuffled[<span class="st">"held_out"</span>][field])</span>
<span id="cb2-182"><a href="#cb2-182" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb2-183"><a href="#cb2-183" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(</span>
<span id="cb2-184"><a href="#cb2-184" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"paired−shuffled held-out </span><span class="sc">{</span>field<span class="sc">}</span><span class="ss">: "</span></span>
<span id="cb2-185"><a href="#cb2-185" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>mean(differences)<span class="sc">:.4f}</span><span class="ss"> (paired SD </span><span class="sc">{</span>stdev(differences)<span class="sc">:.4f}</span><span class="ss">)"</span></span>
<span id="cb2-186"><a href="#cb2-186" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb2-187"><a href="#cb2-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-188"><a href="#cb2-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-189"><a href="#cb2-189" aria-hidden="true" tabindex="-1"></a>parameter_count <span class="op">=</span> <span class="bu">sum</span>(parameter.numel() <span class="cf">for</span> parameter <span class="kw">in</span> models[(<span class="dv">6050</span>, <span class="st">"paired"</span>)].parameters())</span>
<span id="cb2-190"><a href="#cb2-190" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"split sizes: fit=</span><span class="sc">{</span><span class="bu">len</span>(fit_split.image)<span class="sc">}</span><span class="ss">, validation=</span><span class="sc">{</span><span class="bu">len</span>(validation_split.image)<span class="sc">}</span><span class="ss">, held-out=</span><span class="sc">{</span><span class="bu">len</span>(held_out_split.image)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-191"><a href="#cb2-191" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"parameters: </span><span class="sc">{</span>parameter_count<span class="sc">:,}</span><span class="ss">; model seeds: 6050–6054"</span>)</span>
<span id="cb2-192"><a href="#cb2-192" aria-hidden="true" tabindex="-1"></a>report(<span class="st">"validation"</span>, <span class="st">"validation"</span>)</span>
<span id="cb2-193"><a href="#cb2-193" aria-hidden="true" tabindex="-1"></a>report(<span class="st">"held-out endpoint"</span>, <span class="st">"held_out"</span>)</span>
<span id="cb2-194"><a href="#cb2-194" aria-hidden="true" tabindex="-1"></a>report_paired_contrast(<span class="st">"I→T R@1"</span>)</span>
<span id="cb2-195"><a href="#cb2-195" aria-hidden="true" tabindex="-1"></a>report_paired_contrast(<span class="st">"T→I R@1"</span>)</span>
<span id="cb2-196"><a href="#cb2-196" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"held-out random-ranking expectations: R@1=</span><span class="sc">{</span><span class="dv">1</span> <span class="op">/</span> <span class="dv">300</span><span class="sc">:.4f}</span><span class="ss">; R@5=</span><span class="sc">{</span><span class="dv">5</span> <span class="op">/</span> <span class="dv">300</span><span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>split sizes: fit=720, validation=180, held-out=300
parameters: 2,392; model seeds: 6050–6054
validation
  paired  : I→T R@1 0.9911 (SD 0.0084); T→I R@1 0.9900 (SD 0.0061); I→T R@5 1.0000 (SD 0.0000); T→I R@5 1.0000 (SD 0.0000)
  shuffled: I→T R@1 0.0044 (SD 0.0046); T→I R@1 0.0078 (SD 0.0063); I→T R@5 0.0233 (SD 0.0133); T→I R@5 0.0222 (SD 0.0152)
held-out endpoint
  paired  : I→T R@1 0.9747 (SD 0.0038); T→I R@1 0.9660 (SD 0.0092); I→T R@5 1.0000 (SD 0.0000); T→I R@5 1.0000 (SD 0.0000)
  shuffled: I→T R@1 0.0027 (SD 0.0028); T→I R@1 0.0027 (SD 0.0043); I→T R@5 0.0113 (SD 0.0084); T→I R@5 0.0100 (SD 0.0097)
paired−shuffled held-out I→T R@1: 0.9720 (paired SD 0.0038)
paired−shuffled held-out T→I R@1: 0.9633 (paired SD 0.0105)
held-out random-ranking expectations: R@1=0.0033; R@5=0.0167</code></pre>
</div>
</div>
<p>Across the five seeds, the paired condition reaches validation Recall@1 of 0.9911 image-to-text and 0.9900 text-to-image. The shuffled control reaches only 0.0044 and 0.0078. That validation separation is the predeclared mechanism check—the towers can align unseen views only when the fit pairs carry the true correspondence.</p>
<p>On the single held-out endpoint, paired image-to-text Recall@1 is <strong>0.9747</strong> (sample SD 0.0038 across model seeds), and paired text-to-image Recall@1 is <strong>0.9660</strong> (SD 0.0092). Both Recall@5 means are 1.0000. The shuffled condition stays at 0.0027 (SD 0.0028) and 0.0027 (SD 0.0043) for Recall@1, close to the 0.0033 random-ranking expectation. Its Recall@5 means, 0.0113 and 0.0100, remain in the same small-sample neighborhood as the 0.0167 random expectation.</p>
<p>Because the two conditions share seeds, the primary top-1 comparison is paired within seed rather than reconstructed from those marginal summaries. The paired-minus-shuffled held-out contrast is <strong>0.9720</strong> (paired SD 0.0038) image-to-text and <strong>0.9633</strong> (paired SD 0.0105) text-to-image. The endpoint made none of the model, hyperparameter, checkpoint, stopping, or analysis-design decisions above; its values are reported and interpreted only after that lock. It is not being reserved for unrelated future work.</p>
<p>These standard deviations describe optimization variation on one fixed synthetic dataset and one fixed derangement—they are not uncertainty intervals for a population of image–text tasks. The study establishes one finite mechanism: correct pair structure is sufficient for these small towers to learn cross-view retrieval, while the matched derangement removes that generalizable signal. It does not estimate what CLIP, ALIGN, or any natural-data model will achieve.</p>
<!-- NOVEL: needs sign-off -->
<div id="cell-fig-paired-retrieval-audit" class="cell" data-fig-height="4.2" data-fig-width="11" data-execution_count="3">
<details class="code-fold">
<summary>Figure code: held-out retrieval and representative score matrices</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> held_values(condition: <span class="bu">str</span>, field: <span class="bu">str</span>) <span class="op">-&gt;</span> <span class="bu">list</span>[<span class="bu">float</span>]:</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> [</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>        <span class="bu">float</span>(record[<span class="st">"held_out"</span>][field])</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> record <span class="kw">in</span> records</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> record[<span class="st">"condition"</span>] <span class="op">==</span> condition</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    ]</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="at">@torch.no_grad</span>()</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> score_window(model: TwoTower, split: PairedSplit, size: <span class="bu">int</span> <span class="op">=</span> <span class="dv">40</span>) <span class="op">-&gt;</span> Tensor:</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    model.<span class="bu">eval</span>()</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>    image_embedding, text_embedding <span class="op">=</span> model(split.image[:size], split.text[:size])</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> image_embedding <span class="op">@</span> text_embedding.T</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="fl">4.2</span>), gridspec_kw<span class="op">=</span>{<span class="st">"width_ratios"</span>: [<span class="fl">1.15</span>, <span class="dv">1</span>, <span class="dv">1</span>]})</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>conditions <span class="op">=</span> [<span class="st">"paired"</span>, <span class="st">"shuffled"</span>]</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>directions <span class="op">=</span> [<span class="st">"I→T R@1"</span>, <span class="st">"T→I R@1"</span>]</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.arange(<span class="bu">len</span>(directions))</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>width <span class="op">=</span> <span class="fl">0.32</span></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> offset, condition, color <span class="kw">in</span> ((<span class="op">-</span>width <span class="op">/</span> <span class="dv">2</span>, <span class="st">"paired"</span>, green), (width <span class="op">/</span> <span class="dv">2</span>, <span class="st">"shuffled"</span>, orange)):</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>    values <span class="op">=</span> [held_values(condition, field) <span class="cf">for</span> field <span class="kw">in</span> directions]</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">0</span>].bar(</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>        x <span class="op">+</span> offset,</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>        [mean(value) <span class="cf">for</span> value <span class="kw">in</span> values],</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>        width,</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>        yerr<span class="op">=</span>[stdev(value) <span class="cf">for</span> value <span class="kw">in</span> values],</span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>        capsize<span class="op">=</span><span class="dv">3</span>,</span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span>color,</span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>        alpha<span class="op">=</span><span class="fl">0.88</span>,</span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a>        label<span class="op">=</span>condition,</span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].axhline(<span class="dv">1</span> <span class="op">/</span> <span class="dv">300</span>, color<span class="op">=</span>wine, lw<span class="op">=</span><span class="fl">1.2</span>, ls<span class="op">=</span><span class="st">"--"</span>, label<span class="op">=</span><span class="st">"random R@1"</span>)</span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xticks(x, [<span class="st">"image→text"</span>, <span class="st">"text→image"</span>])</span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylim(<span class="dv">0</span>, <span class="fl">1.05</span>)</span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"held-out Recall@1"</span>)</span>
<span id="cb4-38"><a href="#cb4-38" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">"five-seed endpoint"</span>)</span>
<span id="cb4-39"><a href="#cb4-39" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">8</span>, loc<span class="op">=</span><span class="st">"center right"</span>)</span>
<span id="cb4-40"><a href="#cb4-40" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].grid(axis<span class="op">=</span><span class="st">"y"</span>, alpha<span class="op">=</span><span class="fl">0.2</span>)</span>
<span id="cb4-41"><a href="#cb4-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-42"><a href="#cb4-42" aria-hidden="true" tabindex="-1"></a>last_image <span class="op">=</span> <span class="va">None</span></span>
<span id="cb4-43"><a href="#cb4-43" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> axis, condition <span class="kw">in</span> <span class="bu">zip</span>(axes[<span class="dv">1</span>:], conditions):</span>
<span id="cb4-44"><a href="#cb4-44" aria-hidden="true" tabindex="-1"></a>    matrix <span class="op">=</span> score_window(models[(<span class="dv">6052</span>, condition)], held_out_split)</span>
<span id="cb4-45"><a href="#cb4-45" aria-hidden="true" tabindex="-1"></a>    last_image <span class="op">=</span> axis.imshow(matrix, cmap<span class="op">=</span><span class="st">"coolwarm"</span>, vmin<span class="op">=-</span><span class="fl">0.5</span>, vmax<span class="op">=</span><span class="fl">1.0</span>, aspect<span class="op">=</span><span class="st">"auto"</span>)</span>
<span id="cb4-46"><a href="#cb4-46" aria-hidden="true" tabindex="-1"></a>    axis.set_title(<span class="ss">f"</span><span class="sc">{</span>condition<span class="sc">}</span><span class="ss"> · seed 6052"</span>)</span>
<span id="cb4-47"><a href="#cb4-47" aria-hidden="true" tabindex="-1"></a>    axis.set_xlabel(<span class="st">"text candidate"</span>)</span>
<span id="cb4-48"><a href="#cb4-48" aria-hidden="true" tabindex="-1"></a>    axis.set_ylabel(<span class="st">"image query"</span>)</span>
<span id="cb4-49"><a href="#cb4-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-50"><a href="#cb4-50" aria-hidden="true" tabindex="-1"></a>fig.colorbar(last_image, ax<span class="op">=</span>axes[<span class="dv">1</span>:], fraction<span class="op">=</span><span class="fl">0.025</span>, pad<span class="op">=</span><span class="fl">0.03</span>, label<span class="op">=</span><span class="st">"cosine score"</span>)</span>
<span id="cb4-51"><a href="#cb4-51" aria-hidden="true" tabindex="-1"></a>fig.suptitle(<span class="st">"The pair relation, not matching width alone, creates alignment"</span>, color<span class="op">=</span>navy,</span>
<span id="cb4-52"><a href="#cb4-52" aria-hidden="true" tabindex="-1"></a>             fontsize<span class="op">=</span><span class="dv">12</span>, weight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb4-53"><a href="#cb4-53" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-paired-retrieval-audit" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A bar chart shows paired Recall at 1 near 0.97 in both directions and shuffled Recall at 1 near zero. Two forty by forty heatmaps show a bright diagonal after paired training and no consistent diagonal after shuffled-pair training.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-paired-retrieval-audit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="20-multimodal_files/figure-html/fig-paired-retrieval-audit-output-1.png" alt="A bar chart shows paired Recall at 1 near 0.97 in both directions and shuffled Recall at 1 near zero. Two forty by forty heatmaps show a bright diagonal after paired training and no consistent diagonal after shuffled-pair training." width="949" height="412" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-paired-retrieval-audit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20.2: The held-out audit separates aggregate retrieval from one score-matrix view. Bars report the mean and sample SD across five model seeds on all 300 held-out pairs; the dashed line is random Recall@1. The matrices show the first 40 held-out pairs for seed 6052. Correct training concentrates high scores near the declared-pair diagonal, while shuffled fit pairs do not.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The control is stronger than showing a falling training loss—with shuffled pairs, the model can spend capacity fitting accidental associations in the fit table. The correct validation relation refuses to reward that memorization. This is exactly why the experimentation interlude insisted: <strong>tune the contender; ablate the claim</strong>. Here the claim is that paired correspondence teaches alignment, so pairing is the variable the ablation breaks.</p>
<p>There is also a picture of what training <em>did</em> to the geometry. Project the two towers’ embeddings of the same held-out rows into two dimensions, before and after training:</p>
<div id="cell-fig-shared-space" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code: PCA view of both towers, untrained vs.&nbsp;trained</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> two_dim_view(model: TwoTower, count: <span class="bu">int</span> <span class="op">=</span> <span class="dv">20</span>) <span class="op">-&gt;</span> <span class="bu">tuple</span>[Tensor, Tensor]:</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    model.<span class="bu">eval</span>()</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">with</span> torch.no_grad():</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>        image_embedding, text_embedding <span class="op">=</span> model(</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>            held_out_split.image[:count], held_out_split.text[:count]</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    both <span class="op">=</span> torch.cat([image_embedding, text_embedding])</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    centered <span class="op">=</span> both <span class="op">-</span> both.mean(<span class="dv">0</span>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    _, _, right <span class="op">=</span> torch.linalg.svd(centered, full_matrices<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    projected <span class="op">=</span> centered <span class="op">@</span> right[:<span class="dv">2</span>].T</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> projected[:count], projected[count:]</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>torch.manual_seed(<span class="dv">6050</span>)</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>untrained <span class="op">=</span> TwoTower(held_out_split.image.shape[<span class="dv">1</span>], held_out_split.text.shape[<span class="dv">1</span>])</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>views <span class="op">=</span> [(untrained, <span class="st">"before training:</span><span class="ch">\n</span><span class="st">same width, unrelated coordinates"</span>),</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>         (models[(<span class="dv">6050</span>, <span class="st">"paired"</span>)], <span class="st">"after paired training:</span><span class="ch">\n</span><span class="st">mates land together"</span>)]</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="fl">8.6</span>, <span class="fl">3.6</span>))</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> axis, (model, title) <span class="kw">in</span> <span class="bu">zip</span>(axes, views):</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>    image_2d, text_2d <span class="op">=</span> two_dim_view(model)</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(image_2d)):</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>        axis.plot([image_2d[i, <span class="dv">0</span>], text_2d[i, <span class="dv">0</span>]],</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>                  [image_2d[i, <span class="dv">1</span>], text_2d[i, <span class="dv">1</span>]],</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>                  color<span class="op">=</span><span class="st">"#B8B8A8"</span>, lw<span class="op">=</span><span class="fl">0.8</span>, zorder<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>    axis.scatter(image_2d[:, <span class="dv">0</span>], image_2d[:, <span class="dv">1</span>], s<span class="op">=</span><span class="dv">42</span>, color<span class="op">=</span>navy,</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>                 label<span class="op">=</span><span class="st">"image view"</span>, zorder<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>    axis.scatter(text_2d[:, <span class="dv">0</span>], text_2d[:, <span class="dv">1</span>], s<span class="op">=</span><span class="dv">42</span>, marker<span class="op">=</span><span class="st">"^"</span>, color<span class="op">=</span>orange,</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>                 label<span class="op">=</span><span class="st">"text view"</span>, zorder<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>    axis.set_title(title, fontsize<span class="op">=</span><span class="fl">9.5</span>)</span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>    axis.set_xticks([])<span class="op">;</span> axis.set_yticks([])</span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">8</span>, loc<span class="op">=</span><span class="st">"upper left"</span>)</span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-shared-space" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-shared-space-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="20-multimodal_files/figure-html/fig-shared-space-output-1.png" width="816" height="333" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-shared-space-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20.3: What the contrastive loss does to the shared space. Twenty held-out events, embedded by freshly initialized towers (left) and by the trained paired model (right); each gray segment connects an image embedding to its declared text mate, and each panel is a 2-D principal-component view of the 16-dimensional embeddings. Before training the two views occupy unrelated coordinates and the mate segments sprawl; after training, mates land next to each other — which is precisely why the diagonal of the score matrix lights up. A projection understates 16-D distances, so read the segments qualitatively.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="retrieval-is-not-generation" class="level2" data-number="20.3">
<h2 data-number="20.3" class="anchored" data-anchor-id="retrieval-is-not-generation"><span class="header-section-number">20.3</span> Retrieval is not generation</h2>
<p>What has the two-tower model learned to do? Given an image query and a finite text candidate set, it ranks the candidates. Given a text query and a finite image set, it ranks those. This is <strong>cross-modal retrieval</strong>:</p>
<p><span id="eq-cross-modal-retrieval"><span class="math display">\[
\widehat{j}(x^{(I)})
=\argmax_{j\in\{1,\ldots,M\}}
\;u(x^{(I)})^\top v(x_j^{(T)}).
\tag{20.7}\]</span></span></p>
<p>The answer must already be present among the <span class="math inline">\(M\)</span> candidates. The model has no decoder over text tokens and no sampling distribution over images. Chapter 19 made the generative contract explicit—a random source, a conditional or marginal distribution, and a sampling rule. A similarity function supplies none of those by itself.</p>
<p>This distinction prevents a common category error—treating every shared embedding as a generator:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Task</th>
<th>Input</th>
<th>Output rule</th>
<th>What must already exist?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>image-to-text retrieval</td>
<td>image query</td>
<td>rank text embeddings</td>
<td>text candidate pool</td>
</tr>
<tr class="even">
<td>text-to-image retrieval</td>
<td>text query</td>
<td>rank image embeddings</td>
<td>image candidate pool</td>
</tr>
<tr class="odd">
<td>image classification by text</td>
<td>image query</td>
<td>rank class descriptions</td>
<td>chosen descriptions</td>
</tr>
<tr class="even">
<td>image captioning</td>
<td>image</td>
<td>sample or decode text tokens</td>
<td>conditional language decoder</td>
</tr>
<tr class="odd">
<td>text-to-image generation</td>
<td>text</td>
<td>sample an image-valued process</td>
<td>conditional image generator</td>
</tr>
</tbody>
</table>
<p>A larger vision–language system may combine a vision encoder, an adapter, and a language decoder. It may train with contrastive, matching, and generative objectives. That composition can support generation—but the new capability comes from the decoder and its objective, not from renaming retrieval.</p>
<section id="zero-shot-classification-is-retrieval-over-descriptions" class="level3">
<h3 class="anchored" data-anchor-id="zero-shot-classification-is-retrieval-over-descriptions">Zero-shot classification is retrieval over descriptions</h3>
<p>Suppose a task supplies <span class="math inline">\(C\)</span> class names. Write one description for each class, encode those descriptions once, and retrieve the description closest to a new image:</p>
<p><span id="eq-zero-shot-description-retrieval"><span class="math display">\[
\widehat{c}
=\argmax_{c\in\{1,\ldots,C\}}
\frac{f_\theta(x)^{\top}g_\phi(t_c)}
{\lVert f_\theta(x)\rVert_2\lVert g_\phi(t_c)\rVert_2}.
\tag{20.8}\]</span></span></p>
<p>This is <strong>zero-shot classification</strong> in the CLIP-style operational sense: no task-specific parameter update is made before this candidate-ranking step. The phrase does not mean that the underlying concept was absent from pretraining. It does not mean that no human chose the class set or wrote the descriptions. It does not mean that the same prediction survives a different prompt, candidate pool, language, or distribution.</p>
<p>Chapter 17 used “zero-shot” for prompting a fixed language model without demonstrations. Here it means classifying with fixed encoders and text prototypes. Both avoid a task-specific weight update—but their inputs, outputs, and evaluation contracts differ.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Trap: a softmax score is conditional on its candidate set
</div>
</div>
<div class="callout-body-container callout-body">
<p>Add a near-synonym, remove a competing description, or change the prompt template and the softmax denominator changes. A high weight within one candidate set is not a candidate-independent probability that the description is true. Report the candidate construction and prompt policy with the metric.</p>
</div>
</div>
</section>
</section>
<section id="shortcuts-enter-through-the-pair-definition" class="level2" data-number="20.4">
<h2 data-number="20.4" class="anchored" data-anchor-id="shortcuts-enter-through-the-pair-definition"><span class="header-section-number">20.4</span> Shortcuts enter through the pair definition</h2>
<p>Contrastive learning rewards whatever makes the diagonal distinguishable. We hope that the useful signal is semantic: the image and text describe the same scene. The model may find an easier route.</p>
<ul>
<li>A camera watermark and a caption-source tag may identify the same website. The towers can align sources rather than content.</li>
<li>Near-duplicate images may cross the split with paraphrased captions. Retrieval then measures leakage, not transfer.</li>
<li>A broad caption such as “an outdoor scene” may fit many images. The diagonal-only target pretends there is one correct mate.</li>
<li>A candidate pool may make the task artificially easy. Retrieving a dog caption among unrelated equations is different from retrieving it among fine-grained dog breeds.</li>
<li>Aggregate recall may hide poor behavior for a language, geographic region, image style, or social group that is rare in the paired data.</li>
</ul>
<p>These are not side issues—the data contract defines what the objective can learn. Natural-language supervision is attractive because paired text is abundant and rich. The same scale can carry noise, stereotypes, copyrighted material, private information, and uneven coverage. A responsible model card therefore describes how pairs were obtained, filtered, licensed, and audited, not only how many there were.</p>
<section id="a-minimum-evaluation-contract" class="level3">
<h3 class="anchored" data-anchor-id="a-minimum-evaluation-contract">A minimum evaluation contract</h3>
<p>Before accepting a multimodal retrieval result, ask seven questions:</p>
<ol type="1">
<li><strong>What is the unit of pairing?</strong> One image–caption record, one entity with several views, one time-aligned segment, or something else?</li>
<li><strong>What can cross a split?</strong> Split by the underlying entity or source when row-level splitting would leak near duplicates.</li>
<li><strong>What is a valid match?</strong> If several candidates are correct, use multi-positive labels or a metric that does not mark valid matches wrong.</li>
<li><strong>What is the candidate pool?</strong> State its size, construction, duplicates, and difficulty. Recall@1 over 100 candidates is not Recall@1 over one million.</li>
<li><strong>Which direction is measured?</strong> Image-to-text and text-to-image can behave differently—the symmetric training loss does not guarantee identical retrieval.</li>
<li><strong>Which shortcuts were ablated?</strong> Shuffle pairs, mask a suspected nuisance, remove one modality, or construct a hard candidate set that defeats metadata matching.</li>
<li><strong>Where were decisions made?</strong> Report the seed panel, validation choices, final endpoint policy, subgroup slices, and qualitative failure audit.</li>
</ol>
<p>Our synthetic study satisfies a narrow version of this contract. The unique latent row is the pairing unit; splits do not overlap; the candidate pool is the complete split; both directions are reported; the shuffled-pair ablation receives a matched budget; and the held-out endpoint makes no model, hyperparameter, checkpoint, stopping, or analysis-design decision. Natural multimodal data makes every one of those lines harder—not optional.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Check yourself
</div>
</div>
<div class="callout-body-container callout-body">
<p>Close the book for one minute and retrieve the contract before reading the recap.</p>
<ul>
<li>Why do equal embedding widths fail to align two modalities by themselves?</li>
<li>What experiment distinguishes a learned pair relation from accidental memorization?</li>
<li>Why can a dual encoder retrieve a caption without being able to generate one?</li>
</ul>
</div>
</div>
</section>
</section>
<section id="okay-so-two-towers-learn-a-comparison-not-a-world-model" class="level2" data-number="20.5">
<h2 data-number="20.5" class="anchored" data-anchor-id="okay-so-two-towers-learn-a-comparison-not-a-world-model"><span class="header-section-number">20.5</span> Okay, so — two towers learn a comparison, not a world model</h2>
<p>Multimodal learning begins with a relation between views. Separate encoders map those views into normalized shared coordinates; cosine similarities fill a cross-modal score matrix; and Chapter 2’s scores-to-weights machine turns each row and column into a contrastive classification problem. The symmetric objective teaches retrieval in both directions.</p>
<p>The shuffled-pair study shows what carries the supervision. With the true fit relation, small towers retrieve held-out mates far above random ranking. Break the relation while holding the training budget fixed, and the generalizable signal disappears. Matching embedding width was never enough—the rows had to mean something together.</p>
<p>From there, keep the capability boundary clear. Retrieval selects an existing candidate. Zero-shot classification retrieves among human-supplied descriptions. Generation needs a decoder and sampling contract. In every case, the pair definition, candidate pool, split unit, and failure slices belong beside the metric. The model can only learn the alignment that the data actually declares.</p>
</section>
<section id="sources-and-further-reading" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="sources-and-further-reading">Sources and further reading</h2>
<ul>
<li>van den Oord, Li, and Vinyals, <a href="https://arxiv.org/abs/1807.03748">“Representation Learning with Contrastive Predictive Coding”</a> (2018), introduced the InfoNCE name and probabilistic contrastive formulation in predictive representation learning.</li>
<li>Radford et al., <a href="https://arxiv.org/abs/2103.00020">“Learning Transferable Visual Models From Natural Language Supervision”</a> (2021), introduced CLIP’s paired image–text dual-encoder training and zero-shot transfer program; the reported study used 400 million internet image–text pairs.</li>
<li>Jia et al., <a href="https://arxiv.org/abs/2102.05918">“Scaling Up Visual and Vision-Language Representation Learning With Noisy Text Supervision”</a> (2021), developed ALIGN’s dual-encoder contrastive approach with a deliberately noisy large paired corpus.</li>
<li>PyTorch documentation for <a href="https://docs.pytorch.org/docs/stable/generated/torch.nn.functional.normalize.html"><code>torch.nn.functional.normalize</code></a> and <a href="https://docs.pytorch.org/docs/stable/generated/torch.nn.functional.cross_entropy.html"><code>torch.nn.functional.cross_entropy</code></a> specifies the two framework operations used in the executable study.</li>
</ul>
</section>
<section id="exercises" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercises">Exercises</h2>
<ol type="1">
<li><p><strong>(Pencil.)</strong> Let a batch have score matrix <span class="math inline">\(\matr{S}\in\mathbb{R}^{4\times4}\)</span>. Write the image-to-text loss for row 2 and the text-to-image loss for column 2. Then explain why transposing the logits changes the competition even though both losses send gradients into both encoders.</p></li>
<li><p><strong>(Code.)</strong> Re-run the synthetic study with only <span class="math inline">\(\mathcal{L}_{I\rightarrow T}\)</span>. Report both retrieval directions and use an open-ended conclusion: does one-sided training change the two directions equally in this finite regime? Keep the initialization and minibatch schedule paired with the symmetric run.</p></li>
<li><p><strong>(Pencil + code.)</strong> Duplicate 20% of the validation texts so that several image rows have the same valid description. Explain why diagonal Recall@1 can now mark a semantically acceptable retrieval wrong. Design either a multi-positive loss or a group-aware retrieval metric, then state exactly what counts as correct.</p></li>
<li><p><strong>(Code.)</strong> Add a shared one-coordinate “source tag” to both fit modalities and train the paired model. At validation, randomize the tag while preserving the true latent pairs. Compare ordinary and tag-randomized retrieval, and diagnose whether the model used the intended semantic signal or the shortcut.</p></li>
<li><p><strong>(Pencil.)</strong> A fixed image encoder chooses among “a photo of a crane,” “a photo of a bird,” and “a photo of construction equipment.” List at least three ambiguities in the candidate construction. Propose a prompt and evaluation policy that makes the zero-shot claim bounded and reproducible without claiming the resulting softmax is a universal probability of truth.</p></li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/shakeri-lab\.github\.io\/dl-book\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../chapters/part5/19-generative.html" class="pagination-link" aria-label="Generative Models: From Codes to Samples">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Generative Models: From Codes to Samples</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/epilogue.html" class="pagination-link" aria-label="Epilogue: The Question Is Yours">
        <span class="nav-page-text">Epilogue: The Question Is Yours</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Heman Shakeri · Text CC BY-NC-SA 4.0 · Code MIT · School of Data Science, University of Virginia</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/Shakeri-Lab/dl-book/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Companion to <a href="https://shakeri-lab.github.io/dl-course-site/">DS 6050 Deep Learning</a></p>
</div>
  </div>
</footer>




</body></html>