{
  "hash": "39ba23089200b2f112df79a8268c6ec8",
  "result": {
    "engine": "jupyter",
    "markdown": "# Modern CNNs and Transfer Learning {#sec-09-modern-cnns-transfer}\n\n<!-- lecture-source: m05_lecture-5-modern-cnn-architectures-and-transfer-_-R64Wg5Sgsc.txt\n     (spine #1–15 via ds6050_05_modern_cnn/MODULE_NOTES.md),\n     m04 lecture spine #19 (transfer intro)\n     seeds: sources/4.2-CNN-2.tex (six efficiency principles),\n            4- Lecture CNN/assignment/cnn_assignment.py (course assignment, referenced)\n     note: sources/4.3-NextGenCNN.tex names DenseNet in the Module 5 architecture\n           lineage; the bridge below is independently written from the primary\n           paper. Its EfficientNet/ConvNeXt scaling content is deferred to\n           @sec-16-vit-scaling.\n     data: data/squeezenet1_1-imagenet.pt: SqueezeNet 1.1 ImageNet weights distributed\n           by torchvision, committed so rendering never downloads; provenance,\n           checksum, torchvision license, and pretrained-weight caveat are recorded in\n           data/README.md and THIRD_PARTY_NOTICES.md. -->\n\nChapter 8 ended with a working machine and a report card. LeNet reads garments at\n82.5% with 61,706 parameters; graceful under shift where the MLP cliff-dived. But the\ncard has two demerits we wrote down explicitly: 96% of those parameters sit in the\ndense head rather than in the convolutions that do the seeing, and the shift cliff was\nsoftened, not abolished. And one IOU: the live session's batch normalization, promised\nfor this chapter.\n\nWhat happened after LeNet is a decade of architecture research, and it can drown you\nin named networks. The lecture compresses it into **four design questions**, and we\nwill let them drive:\n\n1. **Why $5 \\times 5$?** Could smaller filters do the same job with fewer parameters?\n2. **How do we go deeper** without gradients dying on the way down?\n3. **Where do the parameters actually live**, and how do we evict them?\n4. **Can we design reusable blocks**: optimized layer-combinations we stack, keeping\n   a bird's-eye view instead of re-designing what already works?\n\nEach question has a famous answer (VGG, ResNet, NiN's $1\\times1$ + global pooling,\nand the block habit itself), and each answer is a constraint-shaped idea we can test\non our own data. At the end, the practical superpower the lecture builds to,\nreusing a pretrained backbone, gets the most honest experiment in this book.\n\nBoth trainers below are Listing 4.1 with one factoring: the inner loop\n(`train_existing`) accepts a model and optimizer that already exist, because this\nchapter's whole subject is training models it did not just construct — fresh\nheads on frozen trunks, and selectively thawed layers at their own learning\nrates.\n\n::: {#setup .cell execution_count=1}\n``` {.python .cell-code code-summary=\"Code: imports, data, and the shared training recipe\"}\nimport torch\nimport torch.nn as nn\nimport torch.nn.functional as F\nimport matplotlib.pyplot as plt\nfrom collections.abc import Callable\n\ntorch.manual_seed(6050)\ntrain = torch.load(\"../../data/fashion-train.pt\")\ntest = torch.load(\"../../data/fashion-test.pt\")\nX_tr = train[\"X\"].float().unsqueeze(1) / 255.0    # (1200, 1, 28, 28)\nX_te = test[\"X\"].float().unsqueeze(1) / 255.0     # (600, 1, 28, 28)\ny_tr, y_te, classes = train[\"y\"], test[\"y\"], train[\"classes\"]\n\ndef train_existing(\n    model: nn.Module, opt: torch.optim.Optimizer, epochs: int,\n    batch: int = 128,\n    data: tuple[torch.Tensor, torch.Tensor] | None = None,\n) -> nn.Module:\n    X, y = data if data is not None else (X_tr, y_tr)\n    n = len(X)\n    for _ in range(epochs):\n        perm = torch.randperm(n)\n        for i in range(0, n, batch):\n            idx = perm[i:i + batch]\n            model.train()\n            loss = F.cross_entropy(model(X[idx]), y[idx])\n            opt.zero_grad(); loss.backward(); opt.step()\n    model.eval()\n    return model\n\ndef train_model(model_fn: Callable[[], nn.Module], epochs: int,\n                batch: int = 128, seed: int = 6050, lr: float = 1e-3,\n                data: tuple[torch.Tensor, torch.Tensor] | None = None) -> nn.Module:\n    torch.manual_seed(seed)\n    model = model_fn()\n    opt = torch.optim.Adam(model.parameters(), lr=lr)\n    return train_existing(model, opt, epochs, batch, data)\n\n@torch.no_grad()\ndef accuracy(model: nn.Module, X: torch.Tensor, y: torch.Tensor) -> float:\n    model.eval()\n    return (model(X).argmax(1) == y).float().mean().item()\n\ndef count(model: nn.Module) -> int:\n    return sum(p.numel() for p in model.parameters())\n```\n:::\n\n\nOne evaluation label needs an honesty note. Chapter 8 already opened the 600-image\nholdout, and this chapter queries it repeatedly while comparing architectures. We\nkeep the familiar `X_te` name, but treat it as the book's fixed **benchmark**. These\ncomparisons are descriptive, not an unbiased estimate after model selection; a final\nclaim would require a fresh, untouched test set.\n\nTwo small novelties in the recipe, both because this chapter's networks contain batch\nnormalization: `model.train()` before each step and `model.eval()` before each\nevaluation. Why that matters is the subject of the second section.\n\n## Question 1: why $5 \\times 5$? Stack small kernels instead\n\nVGG's answer (Simonyan & Zisserman, 2014) is the cleanest idea in this chapter. Recall\nthe receptive-field ledger of @sec-08-cnn: stacking grows the field. Two stacked\n$3 \\times 3$ convolutions let the second layer see $5 \\times 5$ of the input, the\n*same* receptive field as one $5 \\times 5$ kernel. But compare the bills, for a layer\nwith $C$ channels in and $C$ out:\n\n$$\n\\underbrace{25\\,C^2}_{\\text{one } 5\\times5}\n\\qquad\\text{versus}\\qquad\n\\underbrace{2 \\times 9\\,C^2 = 18\\,C^2}_{\\text{two } 3\\times3\\text{s}},\n$$\n\na 28% saving. The stacked pair also fires a ReLU *twice* where the big kernel fires\nonce. Same sight, fewer parameters, more nonlinearity. Three $3\\times3$s reach a\n$7\\times7$ field for $27C^2$ against $49C^2$: the deeper you take the idea, the\nbetter the deal gets.\n\n::: {#kernel-economics .cell execution_count=2}\n``` {.python .cell-code code-summary=\"Code: the parameter bill, C = 32\"}\nC = 32\none_5x5 = nn.Conv2d(C, C, 5, padding=2)\ntwo_3x3 = nn.Sequential(nn.Conv2d(C, C, 3, padding=1), nn.ReLU(),\n                        nn.Conv2d(C, C, 3, padding=1))\nprint(f\"one 5x5:  {count(one_5x5):,} parameters, 1 ReLU after\")\nprint(f\"two 3x3s: {count(two_3x3):,} parameters, 2 ReLUs\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\none 5x5:  25,632 parameters, 1 ReLU after\ntwo 3x3s: 18,496 parameters, 2 ReLUs\n```\n:::\n:::\n\n\nOne honest caveat before you re-derive the field equations of vision from this: the\n$18C^2 < 25C^2$ arithmetic assumes the channel width stays $C$ through the stack.\nWhen a layer *grows* channels (as LeNet's $6 \\rightarrow 16$ did), splitting it into\ntwo growing $3\\times3$s can cost more, not less. VGG's design sidesteps this by\nkeeping width constant inside each block and changing it only between blocks, which\nis exactly the shape our code will take. (Exercise 1 makes you find the break-even\npoint.)\n\n## The stabilizer we owe you: batch normalization\n\nBefore we stack deeper than ever, we need the tool Chapter 8's live session used and\nwe deferred. Here is the problem it solves. Watch what happens to the *scale* of\nactivations as a signal crosses twelve freshly initialized $3\\times3$ conv layers:\n\n::: {#bn-drift .cell execution_count=3}\n``` {.python .cell-code code-summary=\"Code: activation scale through 12 conv layers, with and without BN\"}\ndef stack12(with_bn: bool, ch: int = 16) -> nn.Sequential:\n    layers = [nn.Conv2d(1, ch, 3, padding=1)]\n    for _ in range(11):\n        if with_bn:\n            layers.append(nn.BatchNorm2d(ch))\n        layers += [nn.ReLU(), nn.Conv2d(ch, ch, 3, padding=1)]\n    return nn.Sequential(*layers)\n\ntorch.manual_seed(0)\nx = X_tr[:256]\nplain_stack = stack12(False)\nbn_stack = stack12(True)\nplain_convs = [m for m in plain_stack if isinstance(m, nn.Conv2d)]\nbn_convs = [m for m in bn_stack if isinstance(m, nn.Conv2d)]\nfor source, target in zip(plain_convs, bn_convs):\n    target.load_state_dict(source.state_dict())       # identical convolution weights\n\nfor tag, network in [(\"without BN\", plain_stack), (\"with BN   \", bn_stack)]:\n    h, stds = x, []\n    with torch.no_grad():\n        for layer in network:\n            h = layer(h)\n            if isinstance(layer, nn.Conv2d):\n                stds.append(h.std().item())\n    print(f\"{tag} layer stds: \" + \"  \".join(f\"{s:.3f}\" for s in stds[::2]))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nwithout BN layer stds: 0.344  0.059  0.043  0.046  0.049  0.061\nwith BN    layer stds: 0.344  0.404  0.395  0.385  0.432  0.384\n```\n:::\n:::\n\n\nWithout normalization the signal's spread collapses by an order of magnitude within a\nfew layers and keeps sagging. Forward activation scales and backward gradients are not\nthe same quantity, but both are shaped by the stack's weights and nonlinearities;\npoorly scaled activations are therefore a warning to inspect gradient flow directly,\nas we do below.\n\n**Batch normalization** (Ioffe & Szegedy, 2015) re-standardizes at every layer. For\neach channel of an NCHW tensor, `BatchNorm2d` computes the mean and variance across\nthe current minibatch **and both spatial axes** ($N$, $H$, and $W$), normalizes the\nactivations, then lets the layer undo that transformation through two learnable knobs:\n\n$$\n\\hat{x} = \\frac{x - \\mu_{\\text{batch}}}{\\sqrt{\\sigma^2_{\\text{batch}} + \\epsilon}},\n\\qquad\ny = \\gamma\\,\\hat{x} + \\beta .\n$$ {#eq-batchnorm}\n\nThe $\\gamma, \\beta$ pair matters: normalization is a *reset to a healthy scale*, not a\nstraitjacket. The network can learn to restore any mean and spread that helps, but\nit starts every layer from sane numbers. In the printout above, the BN column holds\nnear a constant spread through all twelve layers: every layer trains from day one.\nThe standard placement, which the live session uses and we adopt, is\nconv $\\rightarrow$ BN $\\rightarrow$ ReLU, with `bias=False` on the convolution, since\n$\\beta$ already provides the shift.\n\n::: {.callout-warning}\n## BN is two different machines: tell PyTorch which one you're running\n\nAt training time BN normalizes by the *current batch's* statistics. At evaluation\ntime there may be no batch (one image!), so it uses running averages collected during\ntraining. `model.train()` and `model.eval()` switch between the two. Forgetting the\nswitch is the classic BN bug: evaluate in train mode and your predictions depend on\nwhatever else happens to be in the batch; train in eval mode and BN never learns its\nstatistics. Our `train_model` recipe flips the switch in both directions; look for\nit. Corollary: BN needs real batches to estimate statistics, so it gets unreliable at\ntiny batch sizes.\n:::\n\n::: {.callout-note}\n## Normalize across *what*? A seed for Part IV\n\nBatch statistics are one choice among several. When we build transformers\n(@sec-14-self-attention-transformer), batches of variable-length sequences will make\nper-batch statistics awkward, and the same standardize-then-rescale idea will reappear\ncomputed per *token* instead: **layer normalization**. Same equation, different\naxis. Remember @eq-batchnorm when you meet it.\n:::\n\n## Building with blocks: a small VGG\n\nNow assemble Question 1's answer with Question 4's habit. Define the *atom* — conv,\nBN, ReLU — once; a block stacks atoms and pools; a network stacks blocks. This is the\nlecture's point about VGG versus its hand-tuned predecessors: you stop re-designing\nand start repeating.\n\n::: {#vgg-small .cell execution_count=4}\n``` {.python .cell-code code-summary=\"Code: VGGSmall — two blocks of stacked 3×3 atoms\"}\ndef atom(c_in: int, c_out: int) -> list[nn.Module]:\n    return [nn.Conv2d(c_in, c_out, 3, padding=1, bias=False),\n            nn.BatchNorm2d(c_out), nn.ReLU()]\n\nclass VGGSmall(nn.Module):\n    def __init__(self):\n        super().__init__()\n        self.features = nn.Sequential(\n            *atom(1, 16), *atom(16, 16), nn.MaxPool2d(2),    # -> (16, 14, 14)\n            *atom(16, 32), *atom(32, 32), nn.MaxPool2d(2),   # -> (32, 7, 7)\n        )\n        self.head = nn.Sequential(nn.Flatten(),\n                                  nn.Linear(32 * 7 * 7, 128), nn.ReLU(),\n                                  nn.Linear(128, 10))\n    def forward(self, x: torch.Tensor) -> torch.Tensor:\n        return self.head(self.features(x))\n\nvgg = train_model(VGGSmall, epochs=60)\nn_head = count(vgg.head)\nprint(f\"VGGSmall: {count(vgg):,} parameters ({n_head:,} in the head, \"\n      f\"{n_head / count(vgg):.0%})\")\nprint(f\"test accuracy {accuracy(vgg, X_te, y_te):.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nVGGSmall: 218,586 parameters (202,122 in the head, 92%)\ntest accuracy 86.7%\n```\n:::\n:::\n\n\nTwo readings again. The good: this VGG-style recipe reaches 86.7%, four points above\nLeNet in this run. Because depth, width, normalization, kernel sizes, parameter count,\nand training duration all changed together, this comparison does not isolate which\ningredient earned the gain. The bad: 218,586 parameters, *three and a half times*\nLeNet's total, and\nthe head's share got worse —\n92% of the network is a dense layer reading a flattened grid. The convolutional\ndiet succeeded and the total got fatter anyway. Which forces the lecture's third\nquestion: where do the parameters live, and — his phrasing — where can we do the\nmost damage to the count?\n\n## Question 3: $1 \\times 1$ convolutions, and firing the flatten head\n\nThe bloat has one address: `nn.Linear(1568, 128)`. To evict it we need one more tool,\nodd-looking at first sight: a convolution whose kernel is $1 \\times 1$.\n\nA $1 \\times 1$ kernel does no spatial mixing at all — it looks at a single pixel. But\nacross *channels* it does exactly what @eq-conv-layer says: at each position, take\nthe $C_{\\text{in}}$ channel values and form $C_{\\text{out}}$ weighted combinations\nplus bias. Pause on what that is: a **linear model across the channels, run\nseparately at every pixel** — Chapter 1's machine, miniaturized and stamped across\nthe image. Add a ReLU and each pixel is running a tiny MLP over its own feature\nvector. The lecture's summary: we *summarize* channels, we don't discard them —\ncompressing 64 feature maps into 32 loses far less than pooling them away, and each\ncompression injects another nonlinearity almost for free.\n\nThat tool enables the **Network-in-Network** design (Lin et al., 2013), and with it\nthe clean head. A NiN block is one $3\\times3$ (some spatial mixing) followed by two\n$1\\times1$s (per-pixel channel mixing). And the classifier becomes:\n\n1. Let the last block produce a stack of feature maps.\n2. **Global average pooling (GAP)**: average each map over all positions — 64 maps\n   in, 64 numbers out. No parameters at all.\n3. One small linear layer to the logits.\n\n::: {#nin-small-stage1 .cell execution_count=5}\n``` {.python .cell-code code-summary=\"Code: NINSmall — architecture and first 75 epochs\"}\ndef nin_block(c_in: int, c_out: int) -> list[nn.Module]:\n    return [nn.Conv2d(c_in, c_out, 3, padding=1, bias=False),\n            nn.BatchNorm2d(c_out), nn.ReLU(),\n            nn.Conv2d(c_out, c_out, 1), nn.ReLU(),\n            nn.Conv2d(c_out, c_out, 1), nn.ReLU()]\n\nclass NINSmall(nn.Module):\n    def __init__(self):\n        super().__init__()\n        self.features = nn.Sequential(\n            *nin_block(1, 16), nn.MaxPool2d(2),\n            *nin_block(16, 32), nn.MaxPool2d(2),\n            *nin_block(32, 64),\n        )\n        self.head = nn.Sequential(nn.AdaptiveAvgPool2d(1), nn.Flatten(),\n                                  nn.Linear(64, 10))\n    def forward(self, x: torch.Tensor) -> torch.Tensor:\n        return self.head(self.features(x))\n\ntorch.manual_seed(6050)\nnin = NINSmall()\nnin_opt = torch.optim.Adam(nin.parameters(), lr=1e-3)\nnin = train_existing(nin, nin_opt, epochs=75)\n```\n:::\n\n\n::: {#nin-small-stage2 .cell execution_count=6}\n``` {.python .cell-code code-summary=\"Code: NINSmall — continue the same optimizer through epoch 150\"}\nnin = train_existing(nin, nin_opt, epochs=75)\nprint(f\"NINSmall: {count(nin):,} parameters \"\n      f\"(head: {count(nin.head):,})\")\nprint(f\"test accuracy {accuracy(nin, X_te, y_te):.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNINSmall: 35,034 parameters (head: 650)\ntest accuracy 76.2%\n```\n:::\n:::\n\n\nThe parameter story is a rout: 35,034 total, a 650-parameter head, six times smaller\nthan VGGSmall. The accuracy is 76.2%, and that dip is worth more attention than the\nwin, so let us not rush past it. First, though, collect the promised payoff. Chapter\n8 said the remaining shift-cliff was the flatten head's fault: it reads the final\ngrid *positionally*. GAP averages over positions, so the head no longer assigns a\ndifferent weight to every location. The rematch of the rematch:\n\n::: {#cell-fig-cliff-gap .cell execution_count=7}\n``` {.python .cell-code code-summary=\"Code: shift curves, flatten head vs GAP head\"}\nclass LeNet(nn.Module):\n    def __init__(self):\n        super().__init__()\n        self.conv1 = nn.Conv2d(1, 6, 5, padding=2)\n        self.conv2 = nn.Conv2d(6, 16, 5)\n        self.fc1 = nn.Linear(400, 120)\n        self.fc2 = nn.Linear(120, 84)\n        self.fc3 = nn.Linear(84, 10)\n    def forward(self, x: torch.Tensor) -> torch.Tensor:\n        x = F.max_pool2d(F.relu(self.conv1(x)), 2)\n        x = F.max_pool2d(F.relu(self.conv2(x)), 2)\n        x = x.flatten(1)\n        x = F.relu(self.fc1(x))\n        x = F.relu(self.fc2(x))\n        return self.fc3(x)\n\nlenet = train_model(LeNet, epochs=150)          # Chapter 8's model, same recipe\n\ndef shift_right(X: torch.Tensor, px: int) -> torch.Tensor:\n    if px == 0:\n        return X.clone()\n    out = torch.zeros_like(X)\n    out[..., px:] = X[..., :-px]\n    return out\n\nshifts = list(range(5))\nacc_lenet = [accuracy(lenet, shift_right(X_te, s), y_te) for s in shifts]\nacc_nin = [accuracy(nin, shift_right(X_te, s), y_te) for s in shifts]\nfor s in shifts:\n    print(f\"shift {s}px:   LeNet {acc_lenet[s]:.1%}   NIN+GAP {acc_nin[s]:.1%}\")\n\nplt.figure(figsize=(5.5, 3.2))\nplt.plot(shifts, acc_lenet, \"s-\", color=\"#232D4B\", lw=2, ms=7, label=\"LeNet (flatten head)\")\nplt.plot(shifts, acc_nin, \"^-\", color=\"#E57200\", lw=2, ms=7, label=\"NINSmall (GAP head)\")\nplt.axhline(0.1, ls=\":\", color=\"#B8B8A8\")\nplt.xlabel(\"shift (pixels right)\"); plt.ylabel(\"test accuracy\")\nplt.ylim(0, 0.9); plt.xticks(shifts); plt.legend()\nplt.tight_layout(); plt.show()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nshift 0px:   LeNet 82.5%   NIN+GAP 76.2%\nshift 1px:   LeNet 74.8%   NIN+GAP 70.3%\nshift 2px:   LeNet 62.3%   NIN+GAP 69.3%\nshift 3px:   LeNet 45.3%   NIN+GAP 67.5%\nshift 4px:   LeNet 26.8%   NIN+GAP 66.5%\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![Chapter 8's experiment, third round. LeNet's flatten head still slides below 30% by four pixels of shift. NINSmall with its global-average-pool head barely tilts: per-channel averages change much less when features move. GAP removes position-specific weights from the head, but padding, stride, pooling, and content clipped at the image edge keep the complete network from being exactly shift-invariant.](09-modern-cnns-transfer_files/figure-html/fig-cliff-gap-output-2.png){#fig-cliff-gap width=520 height=297 fig-alt='Line chart of accuracy against a rightward image shift from zero to four pixels. LeNet begins above NINSmall, crosses below it between one and two pixels, then falls steeply to about 0.26; NINSmall declines gently from about 0.76 to 0.66. A dotted chance line stays at 0.10.'}\n:::\n:::\n\n\nThe curve that fell from 82% to 27% across this book's Part II is now a gentle slope\nfrom 76% to 67%. Position-specific weights are gone from NINSmall's head, and the\nresult is consistent with the promised robustness benefit. It is not a matched-head\nablation: the trunks and training recipes differ too. The complete CNN is only\napproximately shift-tolerant; boundaries, strides, and pooling can still change its\nfeatures.\n\nNow the dip. On clean, centered test garments NINSmall trails LeNet by six points.\nThat result is *consistent with* Chapter 8's warning: on centered data, position can\ncarry information, and a GAP head cannot assign separate weights to separate\nlocations. But GAP is not the only changed ingredient, so this run does not prove it\ncaused the gap. With the full 60,000-image dataset the lecture's NiN reaches about 90%,\nnear its LeNet. At our scale the comparison exposes a hypothesis worth testing with a\nmatched-head ablation: shift tolerance may be bought with positional information.\n\n::: {.callout-note}\n## Question 4's other famous block: Inception, in one breath\n\nGoogLeNet's Inception block (2014) answers \"which kernel size?\" with \"all of them\":\nparallel $1\\times1$, $3\\times3$, $5\\times5$, and pooling branches, concatenated. Its\nenabling trick is the $1\\times1$ *bottleneck*: compress channels before the expensive\nspatial kernels. The seed's arithmetic for one $5\\times5$ branch at 256 channels:\ndirect, $5^2 \\times 256 \\times 128 \\approx 819$k parameters; with a $1\\times1$\nsqueeze to 32 first, $256 \\times 32 + 5^2 \\times 32 \\times 128 \\approx 111$k — an\n86% cut for the same nominal operation. We won't build Inception here (the principle,\nchannel compression before spatial expense, is the transferable part), but Exercise 2\nwalks the arithmetic and the course assignment has you build the block itself.\n:::\n\n<!-- NOVEL: needs sign-off - concise DenseNet bridge requested for Module 5 alignment. -->\n::: {.callout-note}\n## Architecture bridge (non-examinable): DenseNet concatenates the history\n\nThe residual block below preserves an old representation by **addition**:\n$x_{\\ell+1}=x_\\ell+F_\\ell(x_\\ell)$. A DenseNet block makes a different connectivity\nchoice. If $x_j$ denotes layer $j$'s output feature map, layer $\\ell$ receives the\nchannel-wise concatenation $[x_0,x_1,\\ldots,x_{\\ell-1}]$ and contributes a small new\ngroup of feature maps for later layers. Earlier features therefore remain directly\navailable instead of being recreated, while the channel axis grows; transition blocks\ncompress channels and\ndownsample between dense blocks. In Appendix B's language, the defining operation is\nconcatenation along the feature-channel axis, not another kind of residual addition\n(@sec-a2-tensors).\n:::\n<!-- /NOVEL -->\n\n## Question 2: going deeper, and the wall you hit\n\nVGG says depth is the direction. So push it: stack twenty of our two-conv blocks\n(with BN, per the recipe, on a $14\\times14$ grid so the experiment fits a laptop) and\ncompare against the *identical* stack with one change we'll reveal after the numbers.\n\nPredict before running: two networks, identical parameter counts, twenty\nblocks each — one plain, one residual. Will the plain net merely trail, or fail\nto fit the *training* set at all?\n\n::: {#deep-nets-plain .cell execution_count=8}\n``` {.python .cell-code code-summary=\"Code: train the plain 20-block network\"}\nclass Block(nn.Module):\n    def __init__(self, ch: int, residual: bool):\n        super().__init__()\n        self.c1 = nn.Conv2d(ch, ch, 3, padding=1, bias=False)\n        self.b1 = nn.BatchNorm2d(ch)\n        self.c2 = nn.Conv2d(ch, ch, 3, padding=1, bias=False)\n        self.b2 = nn.BatchNorm2d(ch)\n        self.residual = residual\n    def forward(self, x: torch.Tensor) -> torch.Tensor:\n        y = self.b2(self.c2(F.relu(self.b1(self.c1(x)))))\n        return F.relu(y + x) if self.residual else F.relu(y)\n\nclass DeepNet(nn.Module):\n    def __init__(self, nblocks: int, residual: bool, ch: int = 12):\n        super().__init__()\n        self.stem = nn.Conv2d(1, ch, 3, padding=1)\n        self.pool = nn.MaxPool2d(2)                       # 28 -> 14 early\n        self.blocks = nn.Sequential(*[Block(ch, residual)\n                                      for _ in range(nblocks)])\n        self.head = nn.Sequential(nn.AdaptiveAvgPool2d(1), nn.Flatten(),\n                                  nn.Linear(ch, 10))\n    def forward(self, x: torch.Tensor) -> torch.Tensor:\n        return self.head(self.blocks(self.pool(F.relu(self.stem(x)))))\n\nplain = train_model(lambda: DeepNet(20, residual=False), epochs=30)\nprint(f\"plain-20     train {accuracy(plain, X_tr, y_tr):.1%}   \"\n      f\"test {accuracy(plain, X_te, y_te):.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nplain-20     train 60.8%   test 51.0%\n```\n:::\n:::\n\n\n::: {#deep-nets-residual .cell execution_count=9}\n``` {.python .cell-code code-summary=\"Code: train the matched residual 20-block network\"}\nresid = train_model(lambda: DeepNet(20, residual=True), epochs=30)\nprint(f\"residual-20  train {accuracy(resid, X_tr, y_tr):.1%}   \"\n      f\"test {accuracy(resid, X_te, y_te):.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nresidual-20  train 100.0%   test 77.8%\n```\n:::\n:::\n\n\nLook at the *training* column first, because it carries the whole lesson. The plain\n40-conv-layer network cannot even fit the 1,200 images it sees every epoch: 61% train\naccuracy, while its residual twin memorizes them and generalizes twenty-seven points\nbetter. This is an **optimization failure** in the same family as the degradation\nproblem He et al. reported in 2015, where their 56-layer plain net trained worse than\ntheir 20-layer one. Our experiment isolates the residual rescue at one depth; a strict\ndemonstration that adding depth degrades a plain network would also require a shallower\nplain control.\n\nThe one change: each block computes $F(x)$ and outputs $F(x) + x$. A **residual\nconnection** lets the input skip over the block and adds it back.\n\n$$\nH(x) = F(x) + x\n\\qquad\\Longrightarrow\\qquad\n\\frac{\\partial L}{\\partial x}\n= \\frac{\\partial L}{\\partial H}\\left(\\frac{\\partial F}{\\partial x} + I\\right).\n$$ {#eq-residual}\n\n::: {#cell-fig-residual-stream .cell execution_count=10}\n\n::: {.cell-output .cell-output-display}\n![A residual block has two routes. The learned branch computes a correction $F(x)$; the identity branch carries $x$ unchanged to the addition. Even when the learned branch has a difficult Jacobian, the shortcut leaves a direct route for activations and gradients.](09-modern-cnns-transfer_files/figure-html/fig-residual-stream-output-1.png){#fig-residual-stream width=682 height=230 fig-alt='Flow diagram in which input x splits into two paths. The learned path passes through conv-BatchNorm-ReLU and conv-BatchNorm boxes; an orange identity path bypasses both. The paths meet at an addition node, followed by ReLU and output H of x.'}\n:::\n:::\n\n\nRead the right-hand side with Chapter 5 eyes. Blame arriving at a block's output\nreaches its input through two additive terms: the learned branch $\\partial F /\\partial\nx$ and the identity $I$. The identity contribution gives gradient flow a direct route\nthat does not itself multiply by the learned weights. It is powerful, not magical:\nthe learned Jacobian can still reinforce, distort, or even partly cancel that term.\nChapter 5 called ReLU's open gate a *gradient superhighway* through a single unit; a\nskip connection builds a direct lane into every block. The block only needs to learn\nthe *residual*, the correction on top of \"pass it through,\" and doing nothing is easy\nto represent: $F = 0$.\n\nHere is the highway visible at initialization, extending Chapter 5's depth experiment\nfrom dense layers to conv stacks:\n\n::: {#cell-fig-gradient-highway .cell execution_count=11}\n``` {.python .cell-code code-summary=\"Code: gradient at the stem vs. depth, three designs\"}\nclass PlainNoBN(nn.Module):\n    def __init__(self, nconvs: int, ch: int = 12):\n        super().__init__()\n        self.stem = nn.Conv2d(1, ch, 3, padding=1)\n        self.pool = nn.MaxPool2d(2)\n        self.layers = nn.Sequential(*[m for _ in range(nconvs)\n                                      for m in (nn.Conv2d(ch, ch, 3, padding=1),\n                                                nn.ReLU())])\n        self.head = nn.Sequential(nn.AdaptiveAvgPool2d(1), nn.Flatten(),\n                                  nn.Linear(ch, 10))\n    def forward(self, x: torch.Tensor) -> torch.Tensor:\n        return self.head(self.layers(self.pool(F.relu(self.stem(x)))))\n\ndef stem_grad(\n    make_net: Callable[[], nn.Module],\n) -> tuple[float, float, int, int]:\n    torch.manual_seed(0)\n    net = make_net()\n    F.cross_entropy(net(X_tr[:128]), y_tr[:128]).backward()\n    grad = net.stem.weight.grad\n    return (grad.double().norm().item(), grad.abs().max().item(),\n            torch.count_nonzero(grad).item(), grad.numel())\n\ndepths = [4, 12, 24]                                  # blocks (2 convs each)\ndiagnostics = {\n    \"plain, no BN\": [stem_grad(lambda d=d: PlainNoBN(2 * d)) for d in depths],\n    \"plain + BN\": [stem_grad(lambda d=d: DeepNet(d, False)) for d in depths],\n    \"residual + BN\": [stem_grad(lambda d=d: DeepNet(d, True)) for d in depths],\n}\ncurves = {name: [row[0] for row in rows]\n          for name, rows in diagnostics.items()}\nfor name, ys in curves.items():\n    print(f\"{name:14s}: \" + \"   \".join(f\"{v:.1e}\" for v in ys))\nnorm64, maxabs, nonzero, total = diagnostics[\"plain, no BN\"][-1]\nprint(f\"48-layer no-BN check: max |component| {maxabs:.1e}; \"\n      f\"nonzero {nonzero}/{total}; float64 norm {norm64:.1e}\")\n\nplt.figure(figsize=(6.2, 3.4))\nfor (name, ys), color in zip(curves.items(),\n                             [\"#B8B8A8\", \"#E57200\", \"#232D4B\"]):\n    xs = [2 * d for d in depths]\n    plt.semilogy(xs, ys, \"o-\", ms=5, color=color, label=name)\nplt.xlabel(\"conv layers\"); plt.ylabel(r\"$\\|\\partial L / \\partial W^{(\\mathrm{stem})}\\|$\")\nplt.legend(); plt.tight_layout(); plt.show()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nplain, no BN  : 9.0e-06   3.3e-13   2.2e-23\nplain + BN    : 7.6e-02   5.0e-01   8.3e+01\nresidual + BN : 1.6e-01   4.9e-01   5.0e-01\n48-layer no-BN check: max |component| 5.2e-24; nonzero 108/108; float64 norm 2.2e-23\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![Gradient magnitude reaching the stem (first layer) at initialization, versus depth, for three designs. In the 48-layer no-BN stack, the true norm is 2.2e-23; a float32 norm calculation reports zero because squaring these nonzero components underflows. BN fixes the vanishing but overshoots: in plain stacks the gradient grows with depth. Residual blocks keep the gradient within one order of magnitude across these depths.](09-modern-cnns-transfer_files/figure-html/fig-gradient-highway-output-2.png){#fig-gradient-highway width=585 height=316 fig-alt='Log-scale line chart of first-layer gradient norm at 8, 24, and 48 convolutional layers. The plain network without BatchNorm plunges from around 10 to the minus 5 to below 10 to the minus 21; the plain BatchNorm network rises sharply at 48 layers; the residual BatchNorm network remains near order one across all depths.'}\n:::\n:::\n\n\nThe final no-BN row also exposes a numerical trap: its components remain nonzero, but\nsquaring them in float32 can underflow before the norm is summed. The range,\nresolution, and accumulator roles behind that distinction are gathered in\n@sec-a3-precision-performance.\n\n::: {.callout-tip}\n## The most important seed this chapter plants\n\nResidual connections are not only a CNN trick. They became a central design device in\nmany deep architectures; when we assemble a transformer in\n@sec-14-self-attention-transformer, every attention layer and every feed-forward\nlayer will be wrapped as $x + F(x)$, and the freshly-met layer normalization will sit\nbeside each skip. The picture to carry forward: a *residual stream* with direct\nadditive routes through the network, each block reading from it and writing a\ncorrection back. Those routes improve conditioning without making the stream immune\nto learned-branch interactions. Attention will be one kind of correction. You now own\nboth parts of that skeleton.\n:::\n\n## The scorecard: what a decade of design bought\n\nThe lecture closes its architecture tour with a scatter worth reproducing: every\nmodel of Part II on one canvas, accuracy against parameters, each trained to\nconvergence under our shared recipe:\n\n::: {#cell-fig-scorecard .cell execution_count=12}\n``` {.python .cell-code code-summary=\"Code: accuracy vs. parameters scatter\"}\nmodels_ = {\n    \"LeNet\": (lenet, \"#B8B8A8\"),\n    \"VGGSmall\": (vgg, \"#E57200\"),\n    \"NIN+GAP\": (nin, \"#232D4B\"),\n    \"plain-20\": (plain, \"#DDA0DD\"),\n    \"residual-20\": (resid, \"#5379AA\"),\n}\nplt.figure(figsize=(6.2, 3.6))\nfor name, (m, color) in models_.items():\n    p, a = count(m), accuracy(m, X_te, y_te)\n    plt.scatter(p, a, s=70, color=color, zorder=3)\n    plt.annotate(name, (p, a), textcoords=\"offset points\",\n                 xytext=(8, -3), fontsize=9)\nplt.xscale(\"log\")\nplt.xlabel(\"parameters (log scale)\"); plt.ylabel(\"test accuracy\")\nplt.ylim(0.45, 0.95)\nplt.tight_layout(); plt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Part II's models on one canvas (our 1,200-image subset; each model trained to convergence with the shared Adam recipe). VGG-style depth buys accuracy but hoards parameters in its flatten head; NiN+GAP evicts the head at a visible cost in clean accuracy at this data scale; residual blocks let a 53,050-parameter network go 40 layers deep. The lecture's full-data frontier, where the models exceed 89%, needs data our subset does not have; the shape of the trade-offs is already visible.](09-modern-cnns-transfer_files/figure-html/fig-scorecard-output-1.png){#fig-scorecard width=588 height=335 fig-alt='Scatter plot of test accuracy against log-scaled parameter count. NIN plus global pooling is the smallest model near 0.76 accuracy; plain-20 and residual-20 have similar counts but sit far apart near 0.51 and 0.78; LeNet is near 0.83; VGGSmall is both largest and highest near 0.87.'}\n:::\n:::\n\n\n## Transfer learning: the mechanics, and an honest experiment\n\nEverything so far trains from scratch. The lecture's final move is the one that\ndefines practice today: most image features are *shared* — edges, textures, parts\ntransfer across tasks — so train one strong backbone once, on enormous data, and\nreuse it everywhere. The mechanics come in two strengths:\n\n- **Linear probe**: freeze the pretrained trunk entirely (`requires_grad = False`),\n  extract its features, train only a new linear head on your labels.\n- **Fine-tuning**: additionally unfreeze the last block or two, training them at a\n  *much* smaller learning rate than the fresh head, so the pretrained features adapt\n  gently instead of being trampled.\n\nWe will test the idea properly. The task: classify the three shoe classes (sandal,\nsneaker, ankle boot) from **ten labeled examples each**. The 30-image regime is\nexactly where transfer should shine — too few labels to learn features, goes the\nstory, so imported features should dominate. Three contenders:\n\n1. **From scratch**: our VGG-style trunk trained on the 30 images alone.\n2. **Our own pretrained trunk**: the same trunk pretrained on the seven *non-shoe*\n   classes (863 images), frozen, linear probe.\n3. **A real pretrained backbone**: SqueezeNet 1.1 trained on ImageNet — 1.2 million\n   photographs, 1,000 classes — loaded from weights committed with this book,\n   frozen, linear probe on its 512-dimensional features. (Fashion images get\n   upsampled to 96×96 and repeated to three channels to fit its expectations. That\n   awkwardness is part of the experiment, and part of the lesson.)\n\n::: {#transfer-setup .cell execution_count=13}\n``` {.python .cell-code code-summary=\"Code: the shoe task, our own trunk, and the frozen probes\"}\nfrom torchvision.models import squeezenet1_1\n\nshoe = torch.tensor([5, 7, 9])\nnew_label = {5: 0, 7: 1, 9: 2}\nis_shoe_tr = (y_tr[:, None] == shoe).any(1)\nis_shoe_te = (y_te[:, None] == shoe).any(1)\nX_shoe_te = X_te[is_shoe_te]\ny_shoe_te = torch.tensor([new_label[int(c)] for c in y_te[is_shoe_te]])\n\n# our own trunk: pretrain on the 7 non-shoe classes\nsrc = [0, 1, 2, 3, 4, 6, 8]\nremap = {c: i for i, c in enumerate(src)}\nX_src = X_tr[~is_shoe_tr]\ny_src = torch.tensor([remap[int(c)] for c in y_tr[~is_shoe_tr]])\n\nclass Trunk(nn.Module):\n    def __init__(self, n_classes: int):\n        super().__init__()\n        self.features = nn.Sequential(\n            *atom(1, 16), *atom(16, 16), nn.MaxPool2d(2),\n            *atom(16, 32), *atom(32, 32), nn.MaxPool2d(2), *atom(32, 64))\n        self.head = nn.Sequential(nn.AdaptiveAvgPool2d(1), nn.Flatten(),\n                                  nn.Linear(64, n_classes))\n    def forward(self, x: torch.Tensor) -> torch.Tensor:\n        return self.head(self.features(x))\n\nown_trunk = train_model(lambda: Trunk(7), epochs=100, data=(X_src, y_src))\nX_src_te = X_te[~is_shoe_te]\ny_src_te = torch.tensor([remap[int(c)] for c in y_te[~is_shoe_te]])\nprint(f\"own trunk, source task (7 classes): \"\n      f\"{accuracy(own_trunk, X_src_te, y_src_te):.1%}\")\n\n# the real thing: ImageNet SqueezeNet, from committed weights (no download)\nsq = squeezenet1_1(weights=None)\nsq.load_state_dict(torch.load(\"../../data/squeezenet1_1-imagenet.pt\"))\nsq.eval()\nfor p in sq.parameters():\n    p.requires_grad = False\n\nIMNET_MEAN = torch.tensor([0.485, 0.456, 0.406]).view(1, 3, 1, 1)\nIMNET_STD = torch.tensor([0.229, 0.224, 0.225]).view(1, 3, 1, 1)\n\n@torch.no_grad()\ndef squeeze_features(X: torch.Tensor) -> torch.Tensor:  # (N,1,28,28) -> (N,512)\n    x = X.repeat(1, 3, 1, 1)\n    x = F.interpolate(x, size=96, mode=\"bilinear\", align_corners=False)\n    f = sq.features((x - IMNET_MEAN) / IMNET_STD)\n    return F.adaptive_avg_pool2d(f, 1).flatten(1)\n\n@torch.no_grad()\ndef own_features(X: torch.Tensor) -> torch.Tensor:      # (N,1,28,28) -> (N,64)\n    return F.adaptive_avg_pool2d(own_trunk.features(X), 1).flatten(1)\n\ndef linear_probe(Z_tr: torch.Tensor, y_f: torch.Tensor,\n                 Z_te: torch.Tensor, seed: int) -> float:\n    torch.manual_seed(seed)\n    head = nn.Linear(Z_tr.shape[1], 3)\n    opt = torch.optim.Adam(head.parameters(), lr=1e-2,\n                           weight_decay=1e-3)   # built-in L2 penalty (ch. 1's ridge)\n    for _ in range(400):\n        loss = F.cross_entropy(head(Z_tr), y_f)\n        opt.zero_grad(); loss.backward(); opt.step()\n    return (head(Z_te).argmax(1) == y_shoe_te).float().mean().item()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nown trunk, source task (7 classes): 79.7%\n```\n:::\n:::\n\n\n::: {#transfer-experiment .cell execution_count=14}\n``` {.python .cell-code code-summary=\"Code: scratch vs. own trunk vs. ImageNet trunk, three seeds\"}\nK = 10\nrows = []\nfor seed in [0, 1, 6050]:\n    torch.manual_seed(seed)\n    idx = torch.cat([(y_tr == c).nonzero().squeeze(1)\n                     [torch.randperm(int((y_tr == c).sum()))[:K]] for c in shoe])\n    X_few = X_tr[idx]\n    y_few = torch.tensor([new_label[int(c)] for c in y_tr[idx]])\n\n    scratch = train_model(lambda: Trunk(3), epochs=100, seed=seed,\n                          data=(X_few, y_few))\n    rows.append((accuracy(scratch, X_shoe_te, y_shoe_te),\n                 linear_probe(own_features(X_few), y_few,\n                              own_features(X_shoe_te), seed),\n                 linear_probe(squeeze_features(X_few), y_few,\n                              squeeze_features(X_shoe_te), seed)))\n\nprint(\"seed     scratch   own-trunk probe   ImageNet probe\")\nfor seed, r in zip([0, 1, 6050], rows):\n    print(f\"{seed:4d}     {r[0]:.1%}       {r[1]:.1%}           {r[2]:.1%}\")\nmean = [sum(c) / 3 for c in zip(*rows)]\nprint(f\"mean     {mean[0]:.1%}       {mean[1]:.1%}           {mean[2]:.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nseed     scratch   own-trunk probe   ImageNet probe\n   0     86.4%       68.9%           88.1%\n   1     85.3%       65.5%           85.9%\n6050     88.1%       77.4%           87.6%\nmean     86.6%       70.6%           87.2%\n```\n:::\n:::\n\n\nRead that table slowly, because it does *not* say what the textbook story predicts,\nand the discrepancy is the best lesson in this chapter. Training from scratch on\nthirty images fights the mighty ImageNet backbone to a dead heat — the means differ\nby less than a point, well inside seed noise. And our own pretrained trunk,\nperfectly competent on its source task per the printout above, transfers *worse\nthan nothing*. Three\nreasons, each a general principle:\n\n1. **A trunk can only donate what its data taught it.** Our own trunk saw 863\n   shirts, bags, and trousers. Nothing in that curriculum required foot-shaped\n   detectors, so its 64 features flatten sandals, sneakers, and boots into nearly\n   the same point. Pretraining is not magic; it is *curriculum*.\n2. **Domain and resolution gaps tax the donation.** SqueezeNet's filters expect\n   224-pixel color photographs; we feed it 28-pixel grayscale icons inflated to 96.\n   Its early layers hunt for detail that simply is not there. (The lecture's recipe —\n   resize and normalize *to match the pretraining pipeline* — is doing real work;\n   we complied as far as the data allows.)\n3. **Transfer wins when the target is big relative to your labels — not small.**\n   This is the quiet one. Three shoe silhouettes at $28 \\times 28$ is a *small*\n   problem: thirty images genuinely suffice, so the scratch baseline is strong and\n   there is little room for imported knowledge to pay rent. The lecture's numbers\n   show the other regime: linear-probing an ImageNet ResNet-18 on the *full*\n   FashionMNIST task reaches about 93%, and fine-tuning about 94% — at 224 pixels,\n   with a task rich enough that features matter more than labels.\n\n::: {.callout-tip}\n## When to reach for a pretrained backbone\n\nThe honest decision rule our experiment and the lecture's jointly support: transfer\npays when (your labels are scarce) *and* (the target task is feature-hungry) *and*\n(the pretraining data plausibly covers the target's features at a matched scale). At\n224 pixels and 18 landmark classes — the course assignment — all three hold, and\ntransfer is the winning move by a wide margin. At 28 pixels and 3 silhouettes, the\nconditions fail and scratch fights the superpower to a draw. Knowing *which regime you are in*\nis the skill; the mechanics (`requires_grad`, learning-rate splits) are the easy\npart.\n:::\n\nThe mechanics, for completeness, since you will use them constantly from Part V\nonward — fine-tuning SqueezeNet's last block with the lecture's two-learning-rate\nrecipe (fresh head fast, pretrained layers slow):\n\n::: {#fine-tune .cell execution_count=15}\n``` {.python .cell-code code-summary=\"Code: fine-tuning — unfreeze the last block, two learning rates\"}\ndef prep(X: torch.Tensor) -> torch.Tensor:\n    x = X.repeat(1, 3, 1, 1)\n    x = F.interpolate(x, size=96, mode=\"bilinear\", align_corners=False)\n    return (x - IMNET_MEAN) / IMNET_STD\n\ntorch.manual_seed(6050)\nidx = torch.cat([(y_tr == c).nonzero().squeeze(1)\n                 [torch.randperm(int((y_tr == c).sum()))[:K]] for c in shoe])\nX_few, y_few = prep(X_tr[idx]), torch.tensor([new_label[int(c)]\n                                              for c in y_tr[idx]])\n\nft = squeezenet1_1(weights=None)\nft.load_state_dict(torch.load(\"../../data/squeezenet1_1-imagenet.pt\"))\nhead = nn.Linear(512, 3)\nfor p in ft.parameters():\n    p.requires_grad = False\nfor p in ft.features[-1].parameters():         # last Fire block only\n    p.requires_grad = True\n\nopt = torch.optim.Adam([\n    {\"params\": head.parameters(), \"lr\": 1e-3},       # fresh head: normal\n    {\"params\": ft.features[-1].parameters(), \"lr\": 1e-4},  # trunk: gentle\n], weight_decay=1e-3)\n\nft.train()\nfor _ in range(60):\n    z = F.adaptive_avg_pool2d(ft.features(X_few), 1).flatten(1)\n    loss = F.cross_entropy(head(z), y_few)\n    opt.zero_grad(); loss.backward(); opt.step()\nft.eval()\nwith torch.no_grad():\n    z = F.adaptive_avg_pool2d(ft.features(prep(X_shoe_te)), 1).flatten(1)\n    print(f\"fine-tuned (last block + head): \"\n          f\"{(head(z).argmax(1) == y_shoe_te).float().mean():.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nfine-tuned (last block + head): 88.7%\n```\n:::\n:::\n\n\nFine-tuning edges the frozen probe on this seed and lands in the same tie with\nscratch. This is consistent with the regime analysis above: adaptation helps at the margin,\nbut no amount of it makes a small target task need imported features.\n\nKeep the pattern, though: *this* loop, scaled to real backbones and feature-hungry\ntasks, is how most\nof applied deep learning ships today. It is also this book's destination: Part V is\nwhat happened when the field noticed that \"pretrain big, adapt cheaply\" was not a\nvision trick but *the* recipe for language too. The BERT moment\n(@sec-15-bert-pretraining) is this section's idea, taken seriously at scale.\n\n## Okay, so — modern CNNs are an optimization story\n\n1. **Small kernels, stacked**: two $3\\times3$s see what a $5\\times5$ sees, for\n   $18C^2$ against $25C^2$, with twice the nonlinearity — provided width holds\n   constant through the stack. Design in blocks, repeat the block.\n2. **BatchNorm** re-standardizes every channel over the batch and spatial axes, then hands back two\n   knobs ($\\gamma, \\beta$); conv→BN→ReLU with `bias=False`; *train and eval are\n   different machines*, so flip the switch. Its per-token cousin, LayerNorm,\n   awaits in @sec-14-self-attention-transformer.\n3. **$1\\times1$ convolutions** run Chapter 1's linear model across channels at every\n   pixel: summarize channels, don't discard them. With **global average pooling**\n   they fire the flatten head: parameters collapse (218k $\\rightarrow$ 35k) and\n   position-specific weights leave the head, at a clean-accuracy price our small\n   dataset makes visible. Boundaries and downsampling still prevent exact invariance.\n4. **Depth can hit an optimization wall**: our plain 40-layer net\n   couldn't fit its own training set. The residual connection $H(x) = F(x) + x$ adds\n   an identity lane to the Jacobian, Chapter 5's gradient superhighway as\n   infrastructure, and the same-depth twin trains to 100%. Transformer stacks will\n   reuse this residual pattern around each attention and feed-forward sublayer.\n5. **Transfer learning** = freeze + probe, or gently fine-tune. Our honest experiment\n   found scratch and the ImageNet probe in a near tie across three seeds at 28-pixel\n   scale. Pretraining is curriculum, gaps are taxed, and small targets may leave\n   little room for imports. The lecture's full-scale runs\n   (93–94% via ImageNet ResNet-18) illustrate a richer regime where transfer pays. Diagnosing\n   the regime is the skill.\n\n## Sources and further reading {.unnumbered}\n\n- [Simonyan & Zisserman, *Very Deep Convolutional Networks for Large-Scale Image Recognition*](https://arxiv.org/abs/1409.1556): the small-kernel, repeated-block argument behind VGG.\n- [Lin, Chen, & Yan, *Network In Network*](https://arxiv.org/abs/1312.4400): introduces the $1\\times1$ channel mixer and global-average-pooling classifier.\n- [Ioffe & Szegedy, *Batch Normalization*](https://proceedings.mlr.press/v37/ioffe15.html): the original normalization method and its train/evaluation distinction.\n- [He et al., *Deep Residual Learning for Image Recognition*](https://openaccess.thecvf.com/content_cvpr_2016/html/He_Deep_Residual_Learning_CVPR_2016_paper.html): the degradation experiment and residual-block solution.\n- [Huang et al., *Densely Connected Convolutional Networks*](https://openaccess.thecvf.com/content_cvpr_2017/html/Huang_Densely_Connected_Convolutional_CVPR_2017_paper.html): dense connectivity through feature-map concatenation and transition layers.\n- [Yosinski et al., *How Transferable Are Features in Deep Neural Networks?*](https://proceedings.neurips.cc/paper/2014/hash/375c71349b295fbe2dcdca9206f20a06-Abstract.html): a careful empirical account of when transferred features remain useful.\n\n## Exercises {.unnumbered}\n\n1. **(Pencil.)** Generalize the kernel-stacking arithmetic: $n$ stacked $3\\times3$\n   layers versus one $(2n{+}1)\\times(2n{+}1)$ kernel, at constant width $C$. Then\n   redo it for a layer that grows channels $C \\rightarrow 2C$: split into two\n   $3\\times3$s ($C \\rightarrow C \\rightarrow 2C$ and $C \\rightarrow 2C \\rightarrow\n   2C$) and find when the split stops saving parameters.\n2. **(Pencil.)** Verify the Inception bottleneck arithmetic from the callout\n   ($819{,}200$ versus $110{,}592$), then design the cheapest $1\\times1$-plus-\n   $5\\times5$ pipeline from 128 channels to 64 output channels that keeps the squeeze\n   width at least a quarter of the input width.\n3. **(Code.)** Make VGGSmall's blocks *depthwise separable*: replace each $3\\times3$\n   conv with a per-channel $3\\times3$ (`groups=c_in`) followed by a $1\\times1$ mixer.\n   Count parameters, retrain, and report the accuracy-per-parameter ratio against\n   the original. (This is MobileNet's trick for phones, the lecture's fifth\n   principle.)\n4. **(Code.)** Ablate BatchNorm: retrain VGGSmall with the BN layers removed, same\n   budget. Compare final accuracy *and* the first ten epochs' training accuracy.\n   Then repeat the `bn-drift` cell's measurement on both trained networks. Does\n   training itself fix the activation scales?\n5. **(Code.)** Data augmentation as a third road: on the 30-image shoe task, train\n   from scratch with random horizontal flips and ±3-pixel shifts (Chapter 6's\n   exercise, now as a tool). Does augmentation close the gap to the lecture's\n   full-data numbers further than transfer did? Why might augmentation and transfer\n   help in *different* regimes?\n\n",
    "supporting": [
      "09-modern-cnns-transfer_files"
    ],
    "filters": [],
    "includes": {}
  }
}