{
  "hash": "a41dcc6c40e1179753ce2ddbc12fcd6d",
  "result": {
    "engine": "jupyter",
    "markdown": "# Modern CNNs and Transfer Learning {#sec-09-modern-cnns-transfer}\n\n<!-- lecture-source: m05_lecture-5-modern-cnn-architectures-and-transfer-_-R64Wg5Sgsc.txt\n     (spine #1–15 via ds6050_05_modern_cnn/MODULE_NOTES.md),\n     m04 lecture spine #19 (transfer intro)\n     seeds: sources/4.2-CNN-2.tex (six efficiency principles),\n            4- Lecture CNN/assignment/cnn_assignment.py (course assignment, referenced)\n     note: sources/4.3-NextGenCNN.tex names DenseNet in the Module 5 architecture\n           lineage; the bridge below is independently written from the primary\n           paper. Its EfficientNet/ConvNeXt scaling content is deferred to\n           @sec-16-vit-scaling.\n     data: data/squeezenet1_1-imagenet.pt: SqueezeNet 1.1 ImageNet weights distributed\n           by torchvision, committed so rendering never downloads; provenance,\n           checksum, torchvision license, and pretrained-weight caveat are recorded in\n           data/README.md and THIRD_PARTY_NOTICES.md. -->\n\n@sec-08-cnn built a modern version of LeNet, one of the first practical convolutional\nnetworks, and tested its response to image shifts. The model reaches 82.5% clean test accuracy\nwith 61,706 parameters, but 96% of those parameters belong to its dense head, and a two-pixel\nshift lowers its test accuracy to 62.3%. The architectures that followed, mostly between 2012\nand 2017, kept LeNet's ingredients (local kernels, channels, pooling) and arranged them better.\nWe take them in an order in which each design fixes a problem that the previous one exposes,\nand we examine how kernel size, channel mixing,\n[normalization](https://proceedings.mlr.press/v37/ioffe15.html), and residual connections\nchange the cost and trainability of a convolutional network, and then which features can be\nreused on another task.\n\nThe networks of those years are many, and their mechanisms are easy to lose among them. Four\ndesign questions keep the mechanisms in view:\n\n1. **Why $5 \\times 5$?** Could smaller filters do the same job with fewer parameters?\n2. **How can we train deeper networks reliably?**\n3. **How can we reduce the parameters in the classifier head?**\n4. **Can we design reusable blocks**: optimized layer combinations we stack, keeping\n   a bird's-eye view instead of re-designing what already works?\n\nEach question has a representative answer: [VGG](https://arxiv.org/abs/1409.1556) for the first,\n[ResNet](https://openaccess.thecvf.com/content_cvpr_2016/html/He_Deep_Residual_Learning_CVPR_2016_paper.html) for the second,\nthe $1\\times1$ convolutions and global pooling of [NiN](https://arxiv.org/abs/1312.4400) for the third,\nand the habit of building in blocks for the fourth. We test each answer on our own data, and\nthen test what transfers when we reuse a pretrained backbone.\n\n![Three block designs, one per row. Each row composes a block from operators, repeats it, and attaches a head, and a heavy outline marks what the row adds. The VGG-style row stacks small 3×3 atoms, NiN adds 1×1 channel mixing and a global-average-pooling head, and the residual row adds an identity route (a 1×1 convolution only when a block changes the channel count or resolution) that runs forward, around each learned correction, into the sum.](../../figures/generated/cnn-building-blocks.svg){#fig-cnn-building-blocks .responsive-wide-opt-in width=98% fig-alt=\"A diagram with one row per block design and three columns: compose a block, repeat it, add a head. VGG-style row: a 3-by-3 convolution, batch normalization, and ReLU, heavily outlined as a unit and applied twice, then 2-by-2 max pooling; the block repeats twice, with 16 and then 32 channels; the head is flatten, linear 1568 to 128, ReLU, linear 128 to 10. NiN row: a 3-by-3 convolution, batch normalization, and ReLU, then two heavily outlined 1-by-1 convolutions, each followed by ReLU; the block repeats three times, with 16, 32, and 64 channels and max pooling between; the head is a heavily outlined global average pooling, then flatten and linear 64 to 10. Residual row: a 3-by-3 convolution, batch normalization, ReLU, a second 3-by-3 convolution, and batch normalization lead into a heavily outlined sum; a heavily outlined identity route, labelled identity with a 1-by-1 convolution if shapes change, carries the block input forward, above the branch, into the same sum, and a ReLU follows; the block repeats twenty times with 12 channels, after a convolution stem and max pooling; the head is global average pooling, flatten, and linear 12 to 10.\"}\n\nRead each row from left to right: first the operators inside the block, then how often the\nblock repeats, then the head.\n\nBoth trainers follow Listing 4.1, with one change: the inner loop\n(`train_existing`) accepts a model and optimizer that already exist, because we will\ntrain models we did not just construct: fresh heads on frozen trunks, and selectively\nthawed layers at their own learning rates.\n\n:::: {.plan-code .plan-code-wide}\n::: {.plan}\n1. Load imports, data, and the shared training recipe.\n2. Define the reusable helpers: `train_existing` and `train_model`.\n3. Define the reusable helpers: `accuracy` and `count`.\n:::\n\n::: {#setup .cell execution_count=1}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: imports, data, and the shared training recipe\"}\nimport torch\nimport torch.nn as nn\nimport torch.nn.functional as F\nimport matplotlib.pyplot as plt\nfrom collections.abc import Callable\ntorch.set_num_threads(4)  # pinned: results depend on the CPU thread count\n\n# [1]\ntorch.manual_seed(6050)\ntrain = torch.load(\"../../data/fashion-train.pt\")\ntest = torch.load(\"../../data/fashion-test.pt\")\nX_tr = train[\"X\"].float().unsqueeze(1) / 255.0    # (1200, 1, 28, 28)\nX_te = test[\"X\"].float().unsqueeze(1) / 255.0     # (600, 1, 28, 28)\ny_tr, y_te, classes = train[\"y\"], test[\"y\"], train[\"classes\"]\n\n# [2]\ndef train_existing(\n    model: nn.Module, opt: torch.optim.Optimizer, epochs: int,\n    batch: int = 128,\n    data: tuple[torch.Tensor, torch.Tensor] | None = None,\n) -> nn.Module:\n    X, y = data if data is not None else (X_tr, y_tr)\n    n = len(X)\n    for _ in range(epochs):\n        perm = torch.randperm(n)\n        for i in range(0, n, batch):\n            idx = perm[i:i + batch]\n            model.train()\n            loss = F.cross_entropy(model(X[idx]), y[idx])\n            opt.zero_grad(); loss.backward(); opt.step()\n    model.eval()\n    return model\n\ndef train_model(model_fn: Callable[[], nn.Module], epochs: int,\n                batch: int = 128, seed: int = 6050, lr: float = 1e-3,\n                data: tuple[torch.Tensor, torch.Tensor] | None = None) -> nn.Module:\n    torch.manual_seed(seed)\n    model = model_fn()\n    opt = torch.optim.Adam(model.parameters(), lr=lr)\n    return train_existing(model, opt, epochs, batch, data)\n\n# [3]\n@torch.no_grad()\ndef accuracy(model: nn.Module, X: torch.Tensor, y: torch.Tensor) -> float:\n    model.eval()\n    return (model(X).argmax(1) == y).float().mean().item()\n\ndef count(model: nn.Module) -> int:\n    return sum(p.numel() for p in model.parameters())\n```\n:::\n\n\n::::\n@sec-08-cnn already opened the 600-image holdout, and this chapter queries it\nrepeatedly while comparing architectures, so we keep the familiar `X_te` name but treat\nit as the book's fixed **benchmark**. These\ncomparisons are descriptive, not an unbiased estimate after model selection; a final\nclaim would require a fresh, untouched test set.\n\nThe recipe has two small novelties, both because these networks contain batch\nnormalization: `model.train()` before each step and `model.eval()` before each\nevaluation. Batch normalization uses different statistics in each mode.\n\n## Question 1: why $5 \\times 5$? Stack small kernels instead\n\nVGG (Simonyan & Zisserman, 2014) answers with a rule: never use a $5 \\times 5$\nkernel; stack $3 \\times 3$s until the field is as wide as you need. Recall\nfrom @sec-08-cnn that stacking grows the receptive field. Two stacked\n$3 \\times 3$ convolutions give the second layer a $5 \\times 5$ window on the input, the\n*same* receptive field as one $5 \\times 5$ kernel. But compare the parameter counts, for a layer\nwith $C$ channels in and $C$ out:\n\n$$\n\\underbrace{25\\,C^2}_{\\text{one } 5\\times5}\n\\qquad\\text{versus}\\qquad\n\\underbrace{2 \\times 9\\,C^2 = 18\\,C^2}_{\\text{two } 3\\times3\\text{s}},\n$$\n\na 28% saving. The stacked pair also fires a ReLU *twice* where the big kernel fires\nonce. The pair has the same receptive field, fewer parameters, and more\nnonlinearity. Three $3\\times3$s reach a\n$7\\times7$ field for $27C^2$ against $49C^2$: the deeper you take the idea, the\nlarger the saving.\n\n:::: {.plan-code}\n::: {.plan}\n1. Set `C = 32` and build `one_5x5`, one 5×5 convolution, and `two_3x3`, two 3×3s with a\n   ReLU between.\n2. Count both designs' parameters at C = 32.\n:::\n\n::: {#kernel-economics .cell execution_count=2}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: parameter counts at C = 32\"}\n# [1]\nC = 32\none_5x5 = nn.Conv2d(C, C, 5, padding=2)\ntwo_3x3 = nn.Sequential(nn.Conv2d(C, C, 3, padding=1), nn.ReLU(),\n                        nn.Conv2d(C, C, 3, padding=1))\n# [2]\nprint(f\"one 5x5:  {count(one_5x5):,} parameters, 1 ReLU after\")\nprint(f\"two 3x3s: {count(two_3x3):,} parameters, 2 ReLUs\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\none 5x5:  25,632 parameters, 1 ReLU after\ntwo 3x3s: 18,496 parameters, 2 ReLUs\n```\n:::\n:::\n\n\n::::\nThe $18C^2 < 25C^2$ arithmetic assumes the channel width stays $C$ through the stack.\nWhen a layer *grows* channels (as LeNet's $6 \\rightarrow 16$ did), splitting it into\ntwo growing $3\\times3$s can cost more, not less. VGG's design sidesteps this by\nkeeping width constant inside each block and changing it only between blocks, which\nis exactly the shape our code will take. (Exercise 1 makes you find the break-even\npoint.)\n\n## Batch normalization {#the-stabilizer-we-owe-you-batch-normalization}\n\nBefore we stack deeper, we need the tool @sec-08-cnn deferred.\nTo show the problem it addresses, we measure how the *scale* of\nactivations changes as a signal crosses twelve freshly initialized $3\\times3$ conv layers:\n\n:::: {.plan-code}\n::: {.plan}\n1. Define the reusable `stack12` helper.\n2. Fix a seed, take 256 garments as `x`, build `plain_stack` and `bn_stack`, and list\n   their conv layers.\n3. Activation scale through 12 conv layers, with and without BN.\n4. Pass `x` through both stacks and print the activation std after every other conv\n   layer.\n:::\n\n::: {#bn-drift .cell execution_count=3}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: activation scale through 12 conv layers, with and without BN\"}\n# [1]\ndef stack12(with_bn: bool, ch: int = 16) -> nn.Sequential:\n    layers = [nn.Conv2d(1, ch, 3, padding=1)]\n    for _ in range(11):\n        if with_bn:\n            layers.append(nn.BatchNorm2d(ch))\n        layers += [nn.ReLU(), nn.Conv2d(ch, ch, 3, padding=1)]\n    return nn.Sequential(*layers)\n\n# [2]\ntorch.manual_seed(0)\nx = X_tr[:256]\nplain_stack = stack12(False)\nbn_stack = stack12(True)\nplain_convs = [m for m in plain_stack if isinstance(m, nn.Conv2d)]\nbn_convs = [m for m in bn_stack if isinstance(m, nn.Conv2d)]\n# [3]\nfor source, target in zip(plain_convs, bn_convs):\n    target.load_state_dict(source.state_dict())       # identical convolution weights\n\n# [4]\nfor tag, network in [(\"without BN\", plain_stack), (\"with BN   \", bn_stack)]:\n    h, stds = x, []\n    with torch.no_grad():\n        for layer in network:\n            h = layer(h)\n            if isinstance(layer, nn.Conv2d):\n                stds.append(h.std().item())\n    print(f\"{tag} layer stds: \" + \"  \".join(f\"{s:.3f}\" for s in stds[::2]))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nwithout BN layer stds: 0.344  0.059  0.043  0.046  0.049  0.061\nwith BN    layer stds: 0.344  0.404  0.395  0.385  0.432  0.384\n```\n:::\n:::\n\n\n::::\nWithout normalization the signal's spread collapses by an order of magnitude within a\nfew layers and never recovers: every printed layer after the first stays between 0.043\nand 0.061. Forward activation scales and backward gradients are not\nthe same quantity, but both are shaped by the stack's weights and nonlinearities;\npoorly scaled activations are therefore a warning to inspect gradient flow directly,\nas we do below.\n\n**Batch normalization** (Ioffe & Szegedy, 2015) re-standardizes at every layer. For\neach channel of an NCHW tensor, `BatchNorm2d` computes the mean and variance across\nthe current minibatch **and both spatial axes** ($N$, $H$, and $W$), normalizes the\nactivations, then lets the layer undo that transformation through two learnable knobs:\n\n$$\n\\hat{x} = \\frac{x - \\mu_{\\text{batch}}}{\\sqrt{\\sigma^2_{\\text{batch}} + \\epsilon}},\n\\qquad\ny = \\gamma\\,\\hat{x} + \\beta .\n$$ {#eq-batchnorm}\n\nThe $\\gamma, \\beta$ pair matters: normalization is a *reset to a healthy scale*, not a\nstraitjacket. The network can learn to restore any mean and spread that helps, but\nit starts every layer from sane numbers. In the printout above, the BN row holds\na near-constant spread at every printed depth: the signal reaches each layer at a usable\nscale from the first step.\nThe standard placement we adopt is conv $\\rightarrow$ BN $\\rightarrow$ ReLU, with\n`bias=False` on the convolution, since $\\beta$ already provides the shift.\n\n::: {.callout-warning}\n## BN uses different statistics in training and evaluation\n\nAt training time BN normalizes by the *current batch's* statistics. At evaluation\ntime there may be no batch (one image), so it uses running averages collected during\ntraining. `model.train()` and `model.eval()` switch between the two. Forgetting the\nswitch is the classic BN bug: evaluate in train mode and your predictions depend on\nwhatever else happens to be in the batch; train in eval mode and BN never learns its\nstatistics. Our `train_model` recipe flips the switch in both directions; look for\nit. It follows that BN needs real batches to estimate statistics, so it gets\nunreliable at tiny batch sizes.\n:::\n\n::: {.callout-note}\n## Normalize across *what*?\n\nBatch statistics are one choice among several. When we build transformers\n(@sec-14-self-attention-transformer), batches of variable-length sequences will make\nper-batch statistics awkward, and the same standardize-then-rescale idea will reappear\ncomputed per *token* instead: **layer normalization**. Same equation, different\naxis. Remember @eq-batchnorm when you meet it.\n:::\n\n## Building with blocks: a small VGG\n\nNow combine the small stacked kernels of Question 1 with the reusable blocks of\nQuestion 4. Define the *atom* (conv,\nBN, ReLU) once; a block stacks atoms and pools; a network stacks blocks. This is the\npoint about VGG versus its hand-tuned predecessors: you stop re-designing\nand start repeating.\n\n:::: {.plan-code}\n::: {.plan}\n1. Define the reusable helpers: `atom` and `VGGSmall`.\n2. VGGSmall: two blocks of stacked 3×3 atoms.\n3. Print total and head parameter counts for `VGGSmall`, the head's share, and test\n   accuracy.\n:::\n\n::: {#vgg-small .cell execution_count=4}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: VGGSmall: two blocks of stacked 3×3 atoms\"}\n# [1]\ndef atom(c_in: int, c_out: int) -> list[nn.Module]:\n    return [nn.Conv2d(c_in, c_out, 3, padding=1, bias=False),\n            nn.BatchNorm2d(c_out), nn.ReLU()]\n\nclass VGGSmall(nn.Module):\n    def __init__(self):\n        super().__init__()\n        self.features = nn.Sequential(\n            *atom(1, 16), *atom(16, 16), nn.MaxPool2d(2),    # -> (16, 14, 14)\n            *atom(16, 32), *atom(32, 32), nn.MaxPool2d(2),   # -> (32, 7, 7)\n        )\n        self.head = nn.Sequential(nn.Flatten(),\n                                  nn.Linear(32 * 7 * 7, 128), nn.ReLU(),\n                                  nn.Linear(128, 10))\n    def forward(self, x: torch.Tensor) -> torch.Tensor:\n        return self.head(self.features(x))\n\n# [2]\nvgg = train_model(VGGSmall, epochs=60)\nn_head = count(vgg.head)\n# [3]\nprint(f\"VGGSmall: {count(vgg):,} parameters ({n_head:,} in the head, \"\n      f\"{n_head / count(vgg):.0%})\")\nprint(f\"test accuracy {accuracy(vgg, X_te, y_te):.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nVGGSmall: 218,586 parameters (202,122 in the head, 92%)\ntest accuracy 86.7%\n```\n:::\n:::\n\n\n::::\nTwo readings again. On the good side, this VGG-style recipe reaches 86.7%, four\npoints above LeNet in this run. Because depth, width, normalization, kernel sizes, parameter count,\nand training duration all changed together, this comparison does not isolate which\ningredient earned the gain. On the bad side, it carries 218,586 parameters, *three and\na half times* LeNet's total, and\nthe head still dominates, accounting for 92% of the parameters: it is a dense layer\nreading a flattened grid. The convolutions stayed\nsmall and the total grew anyway. That raises the third question: how can we reduce the\nparameters in the classifier head?\n\n## Question 3: $1 \\times 1$ convolutions and a smaller classifier head {#question-3-1-times-1-convolutions-and-firing-the-flatten-head}\n\nMost parameters sit in `nn.Linear(1568, 128)`. To remove it we need one more tool,\nodd-looking at first sight: a convolution whose kernel is $1 \\times 1$.\n\nA $1 \\times 1$ kernel does no spatial mixing at all: its window is a single pixel. But\nacross *channels* it does exactly what @eq-conv-layer says: at each position, take\nthe $C_{\\text{in}}$ channel values and form $C_{\\text{out}}$ weighted combinations\nplus bias. At each spatial position, the same learned affine map transforms\nthe channel vector. A following ReLU makes this a nonlinear\ntransformation of the features at that position. The spatial grid\nis unchanged, while $C_{\\text{out}}$ determines the new channel\nwidth. The kernel uses $C_{\\text{in}}C_{\\text{out}}$ weights,\nrather than the $k^2C_{\\text{in}}C_{\\text{out}}$ weights of a\n$k\\times k$ spatial kernel.\n\nThat tool enables the **Network-in-Network** design (Lin et al., 2013), and with it\nthe clean head. A NiN block is one $3\\times3$ (some spatial mixing) followed by two\n$1\\times1$s (per-pixel channel mixing). And the classifier becomes:\n\n1. Let the last block produce a stack of feature maps.\n2. **Global average pooling (GAP)**: average each map over all positions: 64 maps\n   in, 64 numbers out. No parameters at all.\n3. One small linear layer to the logits.\n\n:::: {.plan-code}\n::: {.plan}\n1. Define the reusable helpers: `nin_block` and `NINSmall`.\n2. Fix a seed, build `NINSmall`, and give it an Adam optimizer `nin_opt` at learning\n   rate 1e-3.\n3. NINSmall: architecture and first 75 epochs.\n:::\n\n::: {#nin-small-stage1 .cell execution_count=5}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: NINSmall: architecture and first 75 epochs\"}\n# [1]\ndef nin_block(c_in: int, c_out: int) -> list[nn.Module]:\n    return [nn.Conv2d(c_in, c_out, 3, padding=1, bias=False),\n            nn.BatchNorm2d(c_out), nn.ReLU(),\n            nn.Conv2d(c_out, c_out, 1), nn.ReLU(),\n            nn.Conv2d(c_out, c_out, 1), nn.ReLU()]\n\nclass NINSmall(nn.Module):\n    def __init__(self):\n        super().__init__()\n        self.features = nn.Sequential(\n            *nin_block(1, 16), nn.MaxPool2d(2),\n            *nin_block(16, 32), nn.MaxPool2d(2),\n            *nin_block(32, 64),\n        )\n        self.head = nn.Sequential(nn.AdaptiveAvgPool2d(1), nn.Flatten(),\n                                  nn.Linear(64, 10))\n    def forward(self, x: torch.Tensor) -> torch.Tensor:\n        return self.head(self.features(x))\n\n# [2]\ntorch.manual_seed(6050)\nnin = NINSmall()\nnin_opt = torch.optim.Adam(nin.parameters(), lr=1e-3)\n# [3]\nnin = train_existing(nin, nin_opt, epochs=75)\n```\n:::\n\n\n::::\n:::: {.plan-code}\n::: {.plan}\n1. NINSmall: continue the same optimizer through epoch 150.\n2. Print the total and head parameter counts of `NINSmall` and its test accuracy.\n:::\n\n::: {#nin-small-stage2 .cell execution_count=6}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: NINSmall: continue the same optimizer through epoch 150\"}\n# [1]\nnin = train_existing(nin, nin_opt, epochs=75)\n# [2]\nprint(f\"NINSmall: {count(nin):,} parameters \"\n      f\"(head: {count(nin.head):,})\")\nprint(f\"test accuracy {accuracy(nin, X_te, y_te):.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNINSmall: 35,034 parameters (head: 650)\ntest accuracy 76.2%\n```\n:::\n:::\n\n\n::::\nNINSmall has 35,034 parameters, six times fewer than VGGSmall, and a\n650-parameter head. The accuracy is 76.2%, and that dip is worth more attention than the\nwin. First, though, we return to image shifts. @sec-08-cnn\nshowed that LeNet's shift tolerance is incomplete. A flatten head assigns separate weights\nto separate spatial positions. GAP removes that position-specific parameterization\nby averaging each feature map before classification. This gives\na reason to test shift tolerance, although comparing LeNet with\nNINSmall does not isolate the effect of the head. NINSmall's head is @sec-02-logistic-softmax's classification head\nin its plainest form: one linear layer reading one averaged number per channel. The shift test runs a third time:\n\n:::: {.plan-code .plan-code-wide}\n::: {.plan}\n1. Define the reusable helpers: `LeNet` and `shift_right`.\n2. Shift curves, flatten head vs GAP head.\n3. Print per-shift test accuracy for `LeNet` and `NINSmall`; plot both curves with a\n   dotted line at 0.1.\n:::\n\n::: {.cell execution_count=7}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: shift curves, flatten head vs GAP head\"}\n# [1]\nclass LeNet(nn.Module):\n    def __init__(self):\n        super().__init__()\n        self.conv1 = nn.Conv2d(1, 6, 5, padding=2)\n        self.conv2 = nn.Conv2d(6, 16, 5)\n        self.fc1 = nn.Linear(400, 120)\n        self.fc2 = nn.Linear(120, 84)\n        self.fc3 = nn.Linear(84, 10)\n    def forward(self, x: torch.Tensor) -> torch.Tensor:\n        x = F.max_pool2d(F.relu(self.conv1(x)), 2)\n        x = F.max_pool2d(F.relu(self.conv2(x)), 2)\n        x = x.flatten(1)\n        x = F.relu(self.fc1(x))\n        x = F.relu(self.fc2(x))\n        return self.fc3(x)\n\n# [2]\nlenet = train_model(LeNet, epochs=150)          # Chapter 9's model, same recipe\n\ndef shift_right(X: torch.Tensor, px: int) -> torch.Tensor:\n    if px == 0:\n        return X.clone()\n    out = torch.zeros_like(X)\n    out[..., px:] = X[..., :-px]\n    return out\n\nshifts = list(range(5))\nacc_lenet = [accuracy(lenet, shift_right(X_te, s), y_te) for s in shifts]\nacc_nin = [accuracy(nin, shift_right(X_te, s), y_te) for s in shifts]\n# [3]\nfor s in shifts:\n    print(f\"shift {s}px:   LeNet {acc_lenet[s]:.1%}   NIN+GAP {acc_nin[s]:.1%}\")\n\nplt.figure(figsize=(5.5, 3.2))\nplt.plot(\n    shifts, acc_lenet, \"s-\", color=\"#232D4B\", lw=2, ms=7,\n    label=\"LeNet (flatten head)\",\n)\nplt.plot(\n    shifts, acc_nin, \"^-\", color=\"#E57200\", lw=2, ms=7,\n    label=\"NINSmall (GAP head)\",\n)\nplt.axhline(0.1, ls=\":\", color=\"#B8B8A8\")\nplt.xlabel(\"shift (pixels right)\"); plt.ylabel(\"test accuracy\")\nplt.ylim(0, 0.9); plt.xticks(shifts); plt.legend()\nplt.tight_layout(); plt.show()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nshift 0px:   LeNet 82.5%   NIN+GAP 76.2%\nshift 1px:   LeNet 74.8%   NIN+GAP 70.3%\nshift 2px:   LeNet 62.3%   NIN+GAP 69.3%\nshift 3px:   LeNet 45.3%   NIN+GAP 67.5%\nshift 4px:   LeNet 26.8%   NIN+GAP 66.5%\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![@sec-08-cnn's experiment, third round. LeNet's accuracy still falls below 30% by four pixels of shift; NINSmall, with its global-average-pool head, declines gently. The two networks also differ in their trunks, so the curves do not isolate the effect of GAP. GAP removes position-specific weights from the head, but padding, stride, pooling, and content clipped at the image edge keep the complete network from being exactly shift-invariant.](09-modern-cnns-transfer_files/figure-pdf/fig-cliff-gap-output-2.pdf){#fig-cliff-gap fig-alt='Line chart of accuracy against a rightward image shift from zero to four pixels. LeNet begins above NINSmall, crosses below it between one and two pixels, then falls steeply to about 0.26; NINSmall declines gently from about 0.76 to 0.66. A dotted chance line stays at 0.10.' fig-pos='H'}\n:::\n:::\n\n\n::::\nLeNet's curve falls from 82% to 27%; NINSmall's is a gentle slope from 76% to 67%.\nPosition-specific weights are gone from NINSmall's head, and the result is consistent\nwith the flatten-head diagnosis. It is not a matched-head\nablation: the trunks differ too. The complete CNN is only\napproximately shift-tolerant; boundaries, strides, and pooling can still change its\nfeatures.\n\nNow the dip. On clean, centered test garments NINSmall trails LeNet by six points.\nThat result is *consistent with* @sec-08-cnn's warning: on centered data, position can\ncarry information, and a GAP head cannot assign separate weights to separate\nlocations. But GAP is not the only changed ingredient, so this run does not prove it\ncaused the gap. On the full 60,000-image dataset, the book's\n[pinned runs](#the-scorecard-what-a-decade-of-design-bought) put\nNiN at $92.78\\% \\pm 0.08\\%$ across three seeds. At our scale the comparison exposes a hypothesis worth testing with a\nmatched-head ablation: shift tolerance may cost positional information.\n\n::: {.callout-note}\n## Another block for Question 4: Inception\n\n[GoogLeNet](https://openaccess.thecvf.com/content_cvpr_2015/html/Szegedy_Going_Deeper_With_2015_CVPR_paper.html)'s Inception block (2014) answers \"which kernel size?\" with \"all of them\":\nparallel $1\\times1$, $3\\times3$, $5\\times5$, and pooling branches, concatenated. Its\nenabling trick is the $1\\times1$ *bottleneck*: compress channels before the expensive\nspatial kernels. For one $5\\times5$ branch at 256 channels:\ndirect, $5^2 \\times 256 \\times 128 \\approx 819$k parameters; with a $1\\times1$\nsqueeze to 32 first, $256 \\times 32 + 5^2 \\times 32 \\times 128 \\approx 111$k, an\n86% cut for the same nominal operation. We will not build Inception here; the transferable part is its principle of\ncompressing channels before the expensive spatial kernels. Exercise 2 works through\nthe arithmetic.\n:::\n\n## Question 2: training deeper networks {#question-2-going-deeper-and-the-wall-you-hit}\n\nVGG's design favors depth. We stack twenty of our two-conv blocks\n(with BN, per the recipe, on a $14\\times14$ grid so the experiment fits a laptop) and\ncompare the result against the *identical* stack with one change: residual connections.\n\nPredict before running. Two networks have identical parameter counts and\ntwenty blocks each; one is plain, one residual. Will the plain net merely trail, or fail\nto fit the *training* set at all?\n\n:::: {.plan-code}\n::: {.plan}\n1. Define the reusable helpers: `Block` and `DeepNet`.\n2. Train the plain 20-block network.\n3. Print the plain network's train and test accuracy.\n:::\n\n::: {#deep-nets-plain .cell execution_count=8}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: train the plain 20-block network\"}\n# [1]\nclass Block(nn.Module):\n    def __init__(self, ch: int, residual: bool):\n        super().__init__()\n        self.c1 = nn.Conv2d(ch, ch, 3, padding=1, bias=False)\n        self.b1 = nn.BatchNorm2d(ch)\n        self.c2 = nn.Conv2d(ch, ch, 3, padding=1, bias=False)\n        self.b2 = nn.BatchNorm2d(ch)\n        self.residual = residual\n    def forward(self, x: torch.Tensor) -> torch.Tensor:\n        y = self.b2(self.c2(F.relu(self.b1(self.c1(x)))))\n        return F.relu(y + x) if self.residual else F.relu(y)\n\nclass DeepNet(nn.Module):\n    def __init__(self, nblocks: int, residual: bool, ch: int = 12):\n        super().__init__()\n        self.stem = nn.Conv2d(1, ch, 3, padding=1)\n        self.pool = nn.MaxPool2d(2)                       # 28 -> 14 early\n        self.blocks = nn.Sequential(*[Block(ch, residual)\n                                      for _ in range(nblocks)])\n        self.head = nn.Sequential(nn.AdaptiveAvgPool2d(1), nn.Flatten(),\n                                  nn.Linear(ch, 10))\n    def forward(self, x: torch.Tensor) -> torch.Tensor:\n        return self.head(self.blocks(self.pool(F.relu(self.stem(x)))))\n\n# [2]\nplain = train_model(lambda: DeepNet(20, residual=False), epochs=30)\n# [3]\nprint(f\"plain-20     train {accuracy(plain, X_tr, y_tr):.1%}   \"\n      f\"test {accuracy(plain, X_te, y_te):.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nplain-20     train 60.8%   test 51.0%\n```\n:::\n:::\n\n\n::::\n:::: {.plan-code}\n::: {.plan}\n1. Train the matched residual 20-block network.\n2. Print the residual network's train and test accuracy.\n:::\n\n::: {#deep-nets-residual .cell execution_count=9}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: train the matched residual 20-block network\"}\n# [1]\nresid = train_model(lambda: DeepNet(20, residual=True), epochs=30)\n# [2]\nprint(f\"residual-20  train {accuracy(resid, X_tr, y_tr):.1%}   \"\n      f\"test {accuracy(resid, X_te, y_te):.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nresidual-20  train 100.0%   test 77.8%\n```\n:::\n:::\n\n\n::::\nLook at the *training* column first. The plain\n40-conv-layer network did not fit the 1,200 images it trains on\nwithin the 30-epoch training budget: 61% train\naccuracy, while its residual twin memorizes them and generalizes twenty-seven points\nbetter. This is an **optimization failure** in the same family as the degradation\nproblem He et al. reported in 2015, where their 56-layer plain net trained worse than\ntheir 20-layer one. Our experiment isolates the residual rescue at one depth; a strict\ndemonstration that adding depth degrades a plain network would also require a shallower\nplain control.\n\nThe residual version adds the block input to the learned branch\nbefore applying the final ReLU. Write\n$H(x)=x+F(x)$ for this pre-activation sum; the implemented block\nreturns $\\operatorname{ReLU}(H(x))$. @fig-residual-stream shows both\noperations. The sum $x + F(x)$ needs $x$ and $F(x)$ of the same shape. Our blocks keep 12\nchannels and the grid size, so `Block` needs only the identity route. When a block changes the\nnumber of channels, or halves the grid with a stride, ResNets commonly put a $1\\times1$\nconvolution on the shortcut, with stride 2 like the branch's first convolution, to match the\nshapes (He et al.). This projection shortcut costs $C_{\\text{in}}C_{\\text{out}}$ weights: the\n$1\\times1$ convolution of Question 3 reappears as a shape adapter. With the identity route,\ndifferentiating through the sum gives\n\n$$\nH(x) = F(x) + x\n\\qquad\\Longrightarrow\\qquad\n\\frac{\\partial L}{\\partial x}\n= \\frac{\\partial L}{\\partial H}\\left(\\frac{\\partial F}{\\partial x} + I\\right).\n$$ {#eq-residual}\n\n::: {.cell execution_count=10}\n\n::: {.cell-output .cell-output-display}\n![A residual block in the original ResNet form, which `Block` implements. The identity stream carries $x$ straight to the sum. The learned branch adds a correction $F(x)$, so $H(x)=x+F(x)$, and a ReLU follows. The sum has no weights, so the shortcut is a direct route for activations and gradients wherever $H(x)$ is positive. [Pre-activation ResNets](https://doi.org/10.1007/978-3-319-46493-0_38) move that ReLU into the branch and leave the route clean.](09-modern-cnns-transfer_files/figure-pdf/fig-residual-stream-output-1.pdf){#fig-residual-stream fig-alt='Flow diagram of a residual block. Input x runs along a straight identity line to an addition node. Below it, a learned branch leaves the line, passes through conv-BatchNorm-ReLU and conv-BatchNorm boxes grouped as F of x, and rejoins at the addition. The sum H of x equals x plus F of x and passes through a final ReLU to the output.'}\n:::\n:::\n\n\nHere $\\partial L/\\partial H$ already includes the derivative of\nthe final ReLU. The identity term provides an additive gradient\ncontribution that does not multiply by the learned branch's\nweights. The full gradient still depends on the ReLU's derivative and\nthe branch Jacobian, which can amplify, attenuate, or partly\ncancel that contribution. The block only needs to learn\nthe *residual*, the correction on top of \"pass it through,\" and doing nothing is easy\nto represent: $F = 0$.\n\nWe next measure how the stem gradient changes with depth at\ninitialization. We extend @sec-05-backpropagation's depth experiment\nfrom dense layers to conv stacks:\n\n:::: {.plan-code .plan-code-wide}\n::: {.plan}\n1. Define the reusable helpers: `PlainNoBN` and `stem_grad`.\n2. Run `stem_grad` on plain no-BN, plain + BN, and residual + BN nets at 4, 12, and 24\n   blocks.\n3. Gradient at the stem vs. depth, three designs.\n:::\n\n::: {.cell execution_count=11}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: gradient at the stem vs. depth, three designs\"}\n# [1]\nclass PlainNoBN(nn.Module):\n    def __init__(self, nconvs: int, ch: int = 12):\n        super().__init__()\n        self.stem = nn.Conv2d(1, ch, 3, padding=1)\n        self.pool = nn.MaxPool2d(2)\n        self.layers = nn.Sequential(*[m for _ in range(nconvs)\n                                      for m in (nn.Conv2d(ch, ch, 3, padding=1),\n                                                nn.ReLU())])\n        self.head = nn.Sequential(nn.AdaptiveAvgPool2d(1), nn.Flatten(),\n                                  nn.Linear(ch, 10))\n    def forward(self, x: torch.Tensor) -> torch.Tensor:\n        return self.head(self.layers(self.pool(F.relu(self.stem(x)))))\n\ndef stem_grad(\n    make_net: Callable[[], nn.Module],\n) -> tuple[float, float, int, int]:\n    torch.manual_seed(0)\n    net = make_net()\n    F.cross_entropy(net(X_tr[:128]), y_tr[:128]).backward()\n    grad = net.stem.weight.grad\n    return (grad.double().norm().item(), grad.abs().max().item(),\n            torch.count_nonzero(grad).item(), grad.numel())\n\n# [2]\ndepths = [4, 12, 24]                                  # blocks (2 convs each)\ndiagnostics = {\n    \"plain, no BN\": [stem_grad(lambda d=d: PlainNoBN(2 * d)) for d in depths],\n    \"plain + BN\": [stem_grad(lambda d=d: DeepNet(d, False)) for d in depths],\n    \"residual + BN\": [stem_grad(lambda d=d: DeepNet(d, True)) for d in depths],\n}\ncurves = {name: [row[0] for row in rows]\n          for name, rows in diagnostics.items()}\n# [3]\nfor name, ys in curves.items():\n    print(f\"{name:14s}: \" + \"   \".join(f\"{v:.1e}\" for v in ys))\nnorm64, maxabs, nonzero, total = diagnostics[\"plain, no BN\"][-1]\nprint(\n    f\"48-layer no-BN check: max |component| {maxabs:.1e}; \"\n    f\"nonzero {nonzero}/{total}; float64 norm {norm64:.1e}\"\n)\n\nplt.figure(figsize=(6.2, 3.4))\nfor (name, ys), color in zip(curves.items(),\n                             [\"#B8B8A8\", \"#E57200\", \"#232D4B\"]):\n    xs = [2 * d for d in depths]\n    plt.semilogy(xs, ys, \"o-\", ms=5, color=color, label=name)\nplt.xlabel(\"conv layers\")\nplt.ylabel(r\"$\\|\\partial L / \\partial W^{(\\mathrm{stem})}\\|$\")\nplt.legend(); plt.tight_layout(); plt.show()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nplain, no BN  : 9.0e-06   3.3e-13   2.2e-23\nplain + BN    : 7.6e-02   5.0e-01   8.3e+01\nresidual + BN : 1.6e-01   4.9e-01   5.0e-01\n48-layer no-BN check: max |component| 5.2e-24; nonzero 108/108; float64 norm 2.2e-23\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![Gradient magnitude reaching the stem (first layer) at initialization, versus depth, for three designs. In the 48-layer no-BN stack, the true norm is 2.2e-23; a float32 norm calculation reports zero because squaring these nonzero components underflows. BN fixes the vanishing but overshoots: in plain stacks the gradient grows with depth. Residual blocks keep the gradient within one order of magnitude across these depths.](09-modern-cnns-transfer_files/figure-pdf/fig-gradient-highway-output-2.pdf){#fig-gradient-highway fig-alt='Log-scale line chart of the stem gradient norm at 8, 24, and 48 convolutional layers. The plain network without BatchNorm plunges from about 10 to the minus 5 to 2.2 times 10 to the minus 23; the plain BatchNorm network rises to about 83 at 48 layers; the residual BatchNorm network remains near order one across all depths.' fig-pos='H'}\n:::\n:::\n\n\n::::\nThe final no-BN row also exposes a numerical trap: its components remain nonzero, but\nsquaring them in float32 can underflow before the norm is summed. The range,\nresolution, and accumulator roles behind that distinction are gathered in\n@sec-a3-precision-performance.\n\n<!-- NOVEL: needs sign-off - concise DenseNet bridge requested for Module 5 alignment. -->\n::: {.callout-note}\n## Architecture bridge (optional): DenseNet concatenates the history\n\nA residual connection preserves an old representation by **addition**:\n$x_{\\ell+1}=x_\\ell+F_\\ell(x_\\ell)$; the block above applies a ReLU after that sum. A [DenseNet](https://openaccess.thecvf.com/content_cvpr_2017/html/Huang_Densely_Connected_Convolutional_CVPR_2017_paper.html) block makes a different connectivity\nchoice. If $x_j$ denotes layer $j$'s output feature map, layer $\\ell$ receives the\nchannel-wise concatenation $[x_0,x_1,\\ldots,x_{\\ell-1}]$ and contributes a small new\ngroup of feature maps for later layers. Earlier features therefore remain directly\navailable instead of being recreated, while the channel axis grows; transition blocks\ncompress channels and\ndownsample between dense blocks. The defining operation, in the tensor\nvocabulary of @sec-a2-tensors, is concatenation along the feature-channel axis, not\nanother kind of residual addition.\n:::\n<!-- /NOVEL -->\n\n::: {.callout-tip}\n## Residual streams beyond CNNs\n\nResidual connections are not only a CNN trick. They became a central design device in\nmany deep architectures; when we assemble a transformer in\n@sec-14-self-attention-transformer, every attention layer and every feedforward\nlayer will be wrapped as $x + F(x)$, and the freshly met layer normalization will sit\nbeside each skip. The picture to carry forward is a *residual stream* with direct\nadditive routes through the network, each block reading from it and writing a\ncorrection back. Those routes improve conditioning without making the stream immune\nto learned-branch interactions. Attention will be one kind of correction. You now own\nboth parts of that skeleton.\n:::\n\n## Four architectures on the full data {#the-scorecard-what-a-decade-of-design-bought}\n\nThe small-data studies isolated mechanisms. To compare architectures, we use\nthe full task: we split all 60,000 [Fashion-MNIST](https://arxiv.org/abs/1708.07747) training images once into\n50,000 for fitting and 10,000 for validation, and we open the official 10,000-image test set\nonly after selecting the checkpoint on the validation split. We ran LeNet, NiN, VGG, and a\nnine-block residual network for three end-to-end seeds each, all under one training\nrecipe:\n\n:::: {.plan-code .plan-code-wide}\n::: {.plan}\n1. Load the 12 pinned full-data run records.\n2. Summarize test accuracy and parameter count by architecture.\n:::\n\n::: {#scorecard-summary .cell execution_count=12}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: summarize full-data accuracy versus parameters\"}\n# [1]\nimport json\nfrom pathlib import Path\n\nscorecard_root = Path(\"../../experiments/rivanna/results/scorecard\")\nscorecard_records = [\n    json.loads(path.read_text()) for path in sorted(scorecard_root.glob(\"*.json\"))\n]\nscorecard_order = [\"lenet\", \"nin\", \"vgg\", \"resnet\"]\nscorecard_colors = [\"#B8B8A8\", \"#232D4B\", \"#E57200\", \"#5379AA\"]\n\n# [2]\nscorecard = {}\nfor model_name in scorecard_order:\n    rows = [row for row in scorecard_records if row[\"model\"] == model_name]\n    accuracies = torch.tensor([row[\"test_accuracy\"] for row in rows])\n    scorecard[model_name] = {\n        \"parameters\": rows[0][\"parameter_count\"],\n        \"mean\": accuracies.mean().item(),\n        \"sd\": accuracies.std(unbiased=True).item(),\n    }\n```\n:::\n\n\n::::\n\n::: {.cell execution_count=13}\n\n::: {.cell-output .cell-output-display}\n![Full-data Part II accuracy against parameters. Points show mean official-test accuracy and bars one sample standard deviation across three seeds. LeNet reaches 92.52%, NiN 92.78%, VGG 93.73%, and the residual network 94.20%. NiN is the most parameter-efficient point; VGG buys more accuracy with depth; residual blocks reach the strongest endpoint in this declared training regime. Parameter count is not training compute, and these four points are not a universal architecture ranking.](09-modern-cnns-transfer_files/figure-pdf/fig-scorecard-output-1.pdf){#fig-scorecard fig-alt='Scatter plot of full Fashion-MNIST test accuracy against log-scaled parameter count. NiN is the smallest point at about 92.8 percent, LeNet is near 92.5 percent, VGG is near 93.7 percent, and the residual network is highest near 94.2 percent. Small vertical error bars show variation over three seeds.'}\n:::\n:::\n\n\nThe scale changes the verdict from the 1,200-image mechanism studies. NiN no longer trails LeNet in clean accuracy, and all four architectures clear\n92%. The residual network leads this declared recipe, but the plot still has one\nhorizontal axis too few: parameters measure storage, not optimizer steps, activation\nmemory, or total training work.\n\n## Transfer learning: mechanics and a shoe experiment {#transfer-learning-the-mechanics-and-an-honest-experiment}\n\nEverything so far trains from scratch. Practice today often does not:\nmost image features are *shared* (edges, textures, parts transfer across tasks), so we\ntrain one strong backbone once, on enormous data, and reuse it everywhere. The mechanics come in two strengths:\n\n- **Linear probe**: freeze the pretrained trunk entirely (`requires_grad = False`),\n  extract its features, train only a new linear head on your labels. The frozen\n  backbone also runs in evaluation mode, so BatchNorm uses its stored statistics.\n- **Fine-tuning**: additionally unfreeze the last block or two, training them, usually at\n  a *much* smaller learning rate than the fresh head, so the pretrained features adapt\n  gently instead of being trampled.\n\nUnder a linear probe, the frozen trunk turns each image $x$ into a vector of features $h(x)$,\na **representation** (or **embedding**) of the image, and the probe tests whether the target\nlabels can be read from that vector by a linear model. Whatever the trunk learned in\npretraining reaches the new task only through $h(x)$. @sec-interlude-autoencoders, the\ninterlude that follows, builds such representations without labels, by training a network to\ncompress its input and reconstruct it.\n\nOur test case is a shoe task: classify the three shoe classes (sandal,\nsneaker, ankle boot) from **ten labeled examples each**. The 30-image regime is\nexactly where transfer should shine: too few labels to learn features, goes the\nstory, so imported features should dominate. Three contenders:\n\n1. **From scratch**, our VGG-style trunk trains on the 30 images alone.\n2. **Our own pretrained trunk** is the same trunk pretrained on the seven *non-shoe*\n   classes (863 images), then frozen under a linear probe.\n3. **A real pretrained backbone** is [SqueezeNet](https://arxiv.org/abs/1602.07360) 1.1 trained on\n   [ImageNet](https://doi.org/10.1109/CVPR.2009.5206848) (1.2 million photographs,\n   1,000 classes), loaded from weights committed with this book, frozen, and read by a\n   linear probe on its 512-dimensional features. (We upsample the Fashion images\n   to 96×96 and repeat them across three channels to fit its expectations. That\n   awkwardness is part of the experiment.)\n\nRank the three contenders before you run them, and write down how far ahead you expect\nthe ImageNet backbone to finish.\n\n:::: {.plan-code .plan-code-wide}\n::: {.plan}\n1. Pick out the shoe test images, relabeled 0 to 2, and the non-shoe training images,\n   relabeled 0 to 6.\n2. Define the `Trunk` network.\n3. Implement the shoe task, our own trunk, and the frozen probes.\n4. Print own-trunk source-task accuracy; load and freeze ImageNet SqueezeNet, wrapped as\n   `squeeze_features`.\n5. Define the reusable helpers: `own_features` and `linear_probe`.\n:::\n\n::: {#transfer-setup .cell execution_count=14}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: the shoe task, our own trunk, and the frozen probes\"}\nfrom torchvision.models import squeezenet1_1\n\n# [1]\nshoe = torch.tensor([5, 7, 9])\nnew_label = {5: 0, 7: 1, 9: 2}\nis_shoe_tr = (y_tr[:, None] == shoe).any(1)\nis_shoe_te = (y_te[:, None] == shoe).any(1)\nX_shoe_te = X_te[is_shoe_te]\ny_shoe_te = torch.tensor([new_label[int(c)] for c in y_te[is_shoe_te]])\n\n# our own trunk: pretrain on the 7 non-shoe classes\nsrc = [0, 1, 2, 3, 4, 6, 8]\nremap = {c: i for i, c in enumerate(src)}\nX_src = X_tr[~is_shoe_tr]\ny_src = torch.tensor([remap[int(c)] for c in y_tr[~is_shoe_tr]])\n\n# [2]\nclass Trunk(nn.Module):\n    def __init__(self, n_classes: int):\n        super().__init__()\n        self.features = nn.Sequential(\n            *atom(1, 16), *atom(16, 16), nn.MaxPool2d(2),\n            *atom(16, 32), *atom(32, 32), nn.MaxPool2d(2), *atom(32, 64))\n        self.head = nn.Sequential(nn.AdaptiveAvgPool2d(1), nn.Flatten(),\n                                  nn.Linear(64, n_classes))\n    def forward(self, x: torch.Tensor) -> torch.Tensor:\n        return self.head(self.features(x))\n\n# [3]\nown_trunk = train_model(lambda: Trunk(7), epochs=100, data=(X_src, y_src))\nX_src_te = X_te[~is_shoe_te]\ny_src_te = torch.tensor([remap[int(c)] for c in y_te[~is_shoe_te]])\n# [4]\nprint(f\"own trunk, source task (7 classes): \"\n      f\"{accuracy(own_trunk, X_src_te, y_src_te):.1%}\")\n\n# the real thing: ImageNet SqueezeNet, from committed weights (no download)\nsq = squeezenet1_1(weights=None)\nsq.load_state_dict(torch.load(\"../../data/squeezenet1_1-imagenet.pt\"))\nsq.eval()\nfor p in sq.parameters():\n    p.requires_grad = False\n\nIMNET_MEAN = torch.tensor([0.485, 0.456, 0.406]).view(1, 3, 1, 1)\nIMNET_STD = torch.tensor([0.229, 0.224, 0.225]).view(1, 3, 1, 1)\n\n@torch.no_grad()\ndef squeeze_features(X: torch.Tensor) -> torch.Tensor:  # (N,1,28,28) -> (N,512)\n    x = X.repeat(1, 3, 1, 1)\n    x = F.interpolate(x, size=96, mode=\"bilinear\", align_corners=False)\n    f = sq.features((x - IMNET_MEAN) / IMNET_STD)\n    return F.adaptive_avg_pool2d(f, 1).flatten(1)\n\n# [5]\n@torch.no_grad()\ndef own_features(X: torch.Tensor) -> torch.Tensor:      # (N,1,28,28) -> (N,64)\n    return F.adaptive_avg_pool2d(own_trunk.features(X), 1).flatten(1)\n\ndef linear_probe(Z_tr: torch.Tensor, y_f: torch.Tensor,\n                 Z_te: torch.Tensor, seed: int) -> float:\n    torch.manual_seed(seed)\n    head = nn.Linear(Z_tr.shape[1], 3)\n    opt = torch.optim.Adam(head.parameters(), lr=1e-2,\n                           weight_decay=1e-3)   # built-in L2 penalty (ch. 1's ridge)\n    for _ in range(400):\n        loss = F.cross_entropy(head(Z_tr), y_f)\n        opt.zero_grad(); loss.backward(); opt.step()\n    return (head(Z_te).argmax(1) == y_shoe_te).float().mean().item()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nown trunk, source task (7 classes): 79.7%\n```\n:::\n:::\n\n\n::::\n:::: {.plan-code}\n::: {.plan}\n1. Set `K = 10`, the labeled images per shoe class, and start an empty `rows` list.\n2. Scratch vs. own trunk vs. ImageNet trunk, three seeds.\n3. Print scratch, own-trunk probe, and ImageNet probe accuracy per seed, then the seed\n   means.\n:::\n\n::: {#transfer-experiment .cell execution_count=15}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: scratch vs. own trunk vs. ImageNet trunk, three seeds\"}\n# [1]\nK = 10\nrows = []\n# [2]\nfor seed in [0, 1, 6050]:\n    torch.manual_seed(seed)\n    idx = torch.cat([(y_tr == c).nonzero().squeeze(1)\n                     [torch.randperm(int((y_tr == c).sum()))[:K]] for c in shoe])\n    X_few = X_tr[idx]\n    y_few = torch.tensor([new_label[int(c)] for c in y_tr[idx]])\n\n    scratch = train_model(lambda: Trunk(3), epochs=100, seed=seed,\n                          data=(X_few, y_few))\n    rows.append((accuracy(scratch, X_shoe_te, y_shoe_te),\n                 linear_probe(own_features(X_few), y_few,\n                              own_features(X_shoe_te), seed),\n                 linear_probe(squeeze_features(X_few), y_few,\n                              squeeze_features(X_shoe_te), seed)))\n\n# [3]\nprint(\"seed     scratch   own-trunk probe   ImageNet probe\")\nfor seed, r in zip([0, 1, 6050], rows):\n    print(f\"{seed:4d}     {r[0]:.1%}       {r[1]:.1%}           {r[2]:.1%}\")\nmean = [sum(c) / 3 for c in zip(*rows)]\nprint(f\"mean     {mean[0]:.1%}       {mean[1]:.1%}           {mean[2]:.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nseed     scratch   own-trunk probe   ImageNet probe\n   0     86.4%       68.9%           88.1%\n   1     85.3%       65.5%           85.9%\n6050     88.1%       77.4%           87.6%\nmean     86.6%       70.6%           87.2%\n```\n:::\n:::\n\n\n::::\nThese numbers do *not* say what the textbook story predicts. The scratch model, trained on\nthirty images, and the ImageNet probe have similar mean accuracy across these three\nseeds: the means differ by less than a point. And our own pretrained trunk,\ncompetent on its source task per the printout above, transfers *worse\nthan nothing*. Three\nreasons, each a general principle:\n\n1. **A trunk transfers only the features its pretraining produced.** Our own trunk was pretrained on 863\n   shirts, bags, and trousers. Nothing in that curriculum required foot-shaped\n   detectors, so its 64 features may map sandals, sneakers, and boots to nearly\n   the same point. The accuracies in the printout cannot show this; a look at the\n   features themselves would test it. In this sense, pretraining is a *curriculum*.\n2. **Domain and resolution gaps reduce what transfers.** SqueezeNet's filters were trained on\n   224-pixel color photographs; we feed it 28-pixel grayscale icons inflated to 96.\n   Its early layers respond to detail that these images do not contain. (The matching recipe,\n   resize and normalize *to match the pretraining pipeline*, is doing real work;\n   we complied as far as the data allows.)\n3. **Transfer wins when the target task is big relative to your labels, not small.**\n   Three shoe silhouettes at $28 \\times 28$ is a *small*\n   problem: thirty images suffice, so the scratch baseline is strong and\n   there is little room for imported knowledge to help. The full ten-class task\n   below is different: 50,000 fitting labels, 224-pixel inputs, and a ResNet-18-sized\n   feature extractor.\n\n### Transfer on the full ten-class task {#the-full-data-rematch}\n\nThe full task lets us separate three questions cleanly: what ImageNet features can do\nwithout changing, what the last residual stage can learn when allowed to adapt, and\nwhat the architecture can learn from scratch with all target labels available.\n\n:::: {.plan-code .plan-code-wide}\n::: {.plan}\n1. Load the nine pinned ResNet-18 transfer records.\n2. Summarize official-test accuracy by training regime.\n:::\n\n::: {#transfer-full-summary .cell execution_count=16}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: summarize the pinned full-data transfer rematch\"}\n# [1]\ntransfer_root = Path(\"../../experiments/rivanna/results/transfer\")\ntransfer_records = [\n    json.loads(path.read_text()) for path in sorted(transfer_root.glob(\"*.json\"))\n]\ntransfer_order = [\"probe\", \"finetune\", \"scratch\"]\n\n# [2]\ntransfer_summary = {}\nfor regime in transfer_order:\n    values = torch.tensor([\n        row[\"test_accuracy\"] for row in transfer_records if row[\"regime\"] == regime\n    ])\n    transfer_summary[regime] = {\n        \"values\": values,\n        \"mean\": values.mean().item(),\n        \"sd\": values.std(unbiased=True).item(),\n    }\n```\n:::\n\n\n::::\n\n::: {.cell execution_count=17}\n\n::: {.cell-output .cell-output-display}\n![ImageNet transfer on full Fashion-MNIST at 224 pixels. Across three seeds, the frozen linear probe reaches 88.79% ± 0.08% official-test accuracy, last-block fine-tuning 93.92% ± 0.12%, and scratch 94.14% ± 0.08%. Fine-tuning repairs most of the domain mismatch, but 50,000 target labels are enough for scratch to match it in this regime. Bars are means, dots are seeds, and error bars are one sample standard deviation.](09-modern-cnns-transfer_files/figure-pdf/fig-transfer-full-output-1.pdf){#fig-transfer-full fig-alt='Three bars compare full Fashion-MNIST ResNet-18 regimes. The frozen ImageNet probe is lowest near 88.8 percent. Fine-tuning and scratch are both near 94 percent, with scratch slightly higher. Three dots on each bar show the individual seeds.'}\n:::\n:::\n\n\nUnder the reported probe-training recipe, the frozen features\nsupport 88.79% test accuracy. Fine-tuning the last residual stage\nraises that result by more than five percentage points. Training\nfrom scratch finishes 0.22 points above fine-tuning across the\nthree seeds. These results compare the specified training\nprocedures; they do not establish a general ranking of transfer\nand scratch training. Pretraining changes the initial\nrepresentation, while the target data and adaptation procedure\ndetermine how useful that starting point becomes.\n\n::: {.callout-tip}\n## When to reach for a pretrained backbone\n\nTransfer helps when (your labels are scarce) *and* (the target task is feature-hungry)\n*and* (the pretraining data plausibly covers the target's features at a matched scale).\nConsider how many target labels are available, how closely the\nsource and target images match, and how much adaptation the\nbudget permits. Compare a frozen probe, partial fine-tuning,\nand a scratch baseline under an explicit selection procedure.\nThese comparisons test whether the pretrained representation\nis useful for the target task. Knowing *which regime you are in*\nis the skill; the mechanics (`requires_grad`, learning-rate splits) are the easy\npart.\n:::\n\nYou will use these mechanics constantly from Part V onward. Here we fine-tune\nSqueezeNet's last block with two learning rates, fast for the fresh head and slow for\nthe pretrained layers:\n\n:::: {.plan-code .plan-code-wide}\n::: {.plan}\n1. Define the reusable `prep` helper.\n2. Sample `K` images per shoe class and apply `prep`, then load ImageNet SqueezeNet and\n   add a 3-class head.\n3. Fine-tuning: unfreeze the last block, two learning rates.\n4. Score the fine-tuned trunk and head on the shoe test images and print the accuracy.\n:::\n\n::: {#fine-tune .cell execution_count=18}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Code: fine-tuning: unfreeze the last block, two learning rates\"}\n# [1]\ndef prep(X: torch.Tensor) -> torch.Tensor:\n    x = X.repeat(1, 3, 1, 1)\n    x = F.interpolate(x, size=96, mode=\"bilinear\", align_corners=False)\n    return (x - IMNET_MEAN) / IMNET_STD\n\n# [2]\ntorch.manual_seed(6050)\nidx = torch.cat([(y_tr == c).nonzero().squeeze(1)\n                 [torch.randperm(int((y_tr == c).sum()))[:K]] for c in shoe])\nX_few, y_few = prep(X_tr[idx]), torch.tensor([new_label[int(c)]\n                                              for c in y_tr[idx]])\n\nft = squeezenet1_1(weights=None)\nft.load_state_dict(torch.load(\"../../data/squeezenet1_1-imagenet.pt\"))\nhead = nn.Linear(512, 3)\n# [3]\nfor p in ft.parameters():\n    p.requires_grad = False\nfor p in ft.features[-1].parameters():         # last Fire block only\n    p.requires_grad = True\n\nopt = torch.optim.Adam([\n    {\"params\": head.parameters(), \"lr\": 1e-3},       # fresh head: normal\n    {\"params\": ft.features[-1].parameters(), \"lr\": 1e-4},  # trunk: gentle\n], weight_decay=1e-3)\n\nft.train()\nfor _ in range(60):\n    z = F.adaptive_avg_pool2d(ft.features(X_few), 1).flatten(1)\n    loss = F.cross_entropy(head(z), y_few)\n    opt.zero_grad(); loss.backward(); opt.step()\nft.eval()\n# [4]\nwith torch.no_grad():\n    z = F.adaptive_avg_pool2d(ft.features(prep(X_shoe_te)), 1).flatten(1)\n    print(f\"fine-tuned (last block + head): \"\n          f\"{(head(z).argmax(1) == y_shoe_te).float().mean():.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nfine-tuned (last block + head): 88.7%\n```\n:::\n:::\n\n\n::::\nFine-tuning edges the frozen probe on this seed and finishes close to\nscratch. This is consistent with the regime analysis above: adaptation helps at the margin,\nbut on this seed it does not open a clear lead over scratch.\n\nKeep the pattern, though: *this* loop, scaled to real backbones and feature-hungry\ntasks, is how most\nof applied deep learning ships today. The recipe \"pretrain big, adapt cheaply\" is not a vision trick.\nIt is *the* recipe for language too, and BERT (@sec-15-bert-pretraining) runs it at scale.\n\n::: {.callout-note}\n## Check yourself\n\nClose the book for one minute and reconstruct the architecture and transfer choices.\n\n- Why can several small kernels replace one large kernel?\n- What changes between a frozen probe, partial fine-tuning, and training from scratch?\n- Which evidence here is a mechanism study, and which comes from the pinned full-data runs?\n:::\n\n## Okay, so: modern CNNs are an optimization story\n\n1. **Small kernels, stacked**: two $3\\times3$s cover the receptive field of one $5\\times5$, for\n   $18C^2$ against $25C^2$, with twice the nonlinearity, provided width holds\n   constant through the stack. Design in blocks, repeat the block.\n2. **BatchNorm** re-standardizes every channel over the batch and spatial axes, then applies a learnable scale and\n   shift ($\\gamma, \\beta$); conv→BN→ReLU with `bias=False`; *train and eval are\n   different machines*, so flip the switch. Its per-token cousin, LayerNorm,\n   appears in @sec-14-self-attention-transformer. Readers who want\n   normalization treated as a choice of invariance, finite-sample state, and derivative\n   path will find that treatment in *Deep Learning: Making It Trainable* (Shakeri, 2026), Chapter 15,\n   [*Normalization Chooses an Invariance*](https://shakeri-lab.github.io/opt-book/chapters/act2/15-normalization.html#c15).\n3. **$1\\times1$ convolutions** run @sec-01-linear-regression's linear model across channels at every\n   pixel. With **global average pooling**\n   they replace the flatten head: parameters collapse (218k $\\rightarrow$ 35k) and\n   the head has no position-specific weights. On our small dataset, NINSmall lost less\n   accuracy under shift than LeNet but trailed it on centered images; the trunks also\n   differ, so neither difference isolates GAP. Boundaries and downsampling still prevent exact invariance.\n4. **Residual connections rescued a deep stack**: our plain 40-layer net\n   did not fit its own training set within the 30-epoch training budget. The residual\n   connection $H(x) = F(x) + x$ adds an identity term to the Jacobian, and the\n   same-depth twin trains to 100%. Transformer stacks will\n   reuse this residual pattern around each attention and feedforward sublayer.\n5. **Transfer learning** = freeze + probe, or gently fine-tune. Our experiment\n   found similar mean accuracy for scratch and the ImageNet probe across three seeds at 28-pixel\n   scale. Possible explanations include a pretraining curriculum that lacks the target's features,\n   domain and resolution gaps, and a small target task that leaves\n   little room for imported features. The pinned full-scale runs report\n   $88.79\\% \\pm 0.08\\%$ for the frozen probe, $93.92\\% \\pm 0.12\\%$ for fine-tuning,\n   and $94.14\\% \\pm 0.08\\%$ for scratch with ResNet-18. Under these procedures, partial\n   fine-tuning raises the frozen-probe result by more than five points, and scratch\n   finishes slightly above fine-tuning. Diagnosing\n   the regime is the skill.\n\n## Sources and further reading {.unnumbered}\n\n- [Xiao, Rasul, and Vollgraf, *Fashion-MNIST: a Novel Image Dataset for Benchmarking\n  Machine Learning Algorithms*](https://arxiv.org/abs/1708.07747): the target\n  benchmark for the architecture and transfer studies.\n- [Deng et al., *ImageNet: A Large-Scale Hierarchical Image\n  Database*](https://doi.org/10.1109/CVPR.2009.5206848): the source benchmark behind\n  the pretrained visual features used here.\n- [Iandola et al., *SqueezeNet: AlexNet-level accuracy with 50x fewer parameters and\n  <0.5MB model size*](https://arxiv.org/abs/1602.07360): the compact pretrained\n  architecture used in the chapter's first transfer experiment.\n- [Simonyan & Zisserman, *Very Deep Convolutional Networks for Large-Scale Image Recognition*](https://arxiv.org/abs/1409.1556): the small-kernel, repeated-block argument behind VGG.\n- [Szegedy et al., *Going Deeper with Convolutions*](https://openaccess.thecvf.com/content_cvpr_2015/html/Szegedy_Going_Deeper_With_2015_CVPR_paper.html): GoogLeNet's Inception block, parallel branches of several kernel sizes joined by channel concatenation.\n- [Lin, Chen, & Yan, *Network In Network*](https://arxiv.org/abs/1312.4400): introduces the $1\\times1$ channel mixer and global-average-pooling classifier.\n- [Ioffe & Szegedy, *Batch Normalization*](https://proceedings.mlr.press/v37/ioffe15.html): the original normalization method, its train/evaluation distinction, and the backward pass through the batch statistics that Exercise 7 audits.\n- [He et al., *Deep Residual Learning for Image Recognition*](https://openaccess.thecvf.com/content_cvpr_2016/html/He_Deep_Residual_Learning_CVPR_2016_paper.html): the degradation experiment and residual-block solution.\n- [He et al., *Identity Mappings in Deep Residual Networks*](https://doi.org/10.1007/978-3-319-46493-0_38): pre-activation residual blocks, which place BatchNorm and ReLU before each convolution in the learned branch and drop the ReLU after the sum, so the sum passes straight through.\n- [Huang et al., *Densely Connected Convolutional Networks*](https://openaccess.thecvf.com/content_cvpr_2017/html/Huang_Densely_Connected_Convolutional_CVPR_2017_paper.html): dense connectivity through feature-map concatenation and transition layers.\n- [Yosinski et al., *How Transferable Are Features in Deep Neural Networks?*](https://proceedings.neurips.cc/paper_files/paper/2014/hash/532a2f85b6977104bc93f8580abbb330-Abstract.html): a careful empirical account of when transferred features remain useful.\n- [Hardt and Recht, *Patterns, Predictions, and Actions: Datasets*](https://mlstory.org/data.html):\n  a framework for treating a benchmark as a measured artifact rather than an\n  unquestionable oracle.\n- [Northcutt, Athalye, and Mueller, *Pervasive Label Errors in Test Sets Destabilize\n  Machine Learning Benchmarks*](https://arxiv.org/abs/2103.14749): a large-scale\n  audit of suspected benchmark-label errors and their effect on model comparison.\n- [Shakeri, *Deep Learning: Making It Trainable* (2026), Chapter 15, “Normalization Chooses an\n  Invariance”](https://shakeri-lab.github.io/opt-book/chapters/act2/15-normalization.html#c15): normalization treated as a\n  choice of invariance, finite-sample state, and derivative path.\n\n## Exercises {.unnumbered}\n\n1. **(Pencil.)** Generalize the kernel-stacking arithmetic: $n$ stacked $3\\times3$\n   layers versus one $(2n{+}1)\\times(2n{+}1)$ kernel, at constant width $C$. Then\n   redo it for a layer that grows channels $C \\rightarrow 2C$: split into two\n   $3\\times3$s ($C \\rightarrow C \\rightarrow 2C$ and $C \\rightarrow 2C \\rightarrow\n   2C$) and find when the split stops saving parameters.\n2. **(Pencil.)** Verify the Inception bottleneck arithmetic from the callout\n   ($819{,}200$ versus $110{,}592$), then design the cheapest\n   $1\\times1$-plus-$5\\times5$ pipeline from 128 channels to 64 output channels that keeps the squeeze\n   width at least a quarter of the input width.\n3. **(Code.)** Make VGGSmall's blocks *depthwise separable*: replace each $3\\times3$\n   conv with a per-channel $3\\times3$ (`groups=c_in`) followed by a $1\\times1$ mixer.\n   Count parameters, retrain, and report the accuracy-per-parameter ratio against\n   the original. (This is MobileNet's depthwise-separable construction.)\n4. **(Code.)** Ablate BatchNorm: retrain VGGSmall with the BN layers removed, same\n   budget. Compare final accuracy *and* the first ten epochs' training accuracy.\n   Then repeat the `bn-drift` cell's measurement on both trained networks. Does\n   training itself fix the activation scales?\n5. **(Code.)** Try data augmentation as a third road: on the 30-image shoe task, train\n   from scratch with random horizontal flips and ±3-pixel shifts (@sec-06-generalization-inductive-bias's\n   exercise, now as a tool). Does augmentation improve the scratch model relative to the\n   transfer baselines on the same shoe test images? Why might augmentation and transfer\n   help in *different* regimes?\n6. **(Audit.)** Retrain `VGGSmall` and `NINSmall` under one fixed seed, then collect the\n   20 Fashion-MNIST test items on which the models disagree with each other or with\n   the supplied label while at least one model assigns its prediction probability\n   above 0.9. Preserve the images, supplied labels, predictions, and confidences\n   before adjudication. Have a second reader independently label the 20 items, report\n   agreement and a binomial interval for the suspected-label-error share, and list\n   ambiguous cases separately. Explain why confident disagreement is a biased sample\n   of the full test set, in which direction that selection can distort prevalence,\n   and what the audit can still reveal.\n7. **(Pencil.)** Derive $\\partial\\loss/\\partial x$ through @eq-batchnorm's batch mean\n   and variance. Mark the direct normalized-input term and the two terms created by\n   coupling every example through those statistics.\n   **(Code.)** Verify all three terms against autograd on the experimentation\n   interlude's BatchNorm module. Then delete the two coupling terms deliberately,\n   compare the gradient error, and rerun the interlude's training curve under the\n   same data, initialization, minibatch schedule, and seed panel.\n\n",
    "supporting": [
      "09-modern-cnns-transfer_files/figure-pdf"
    ],
    "filters": []
  }
}