{
  "hash": "d3adbf4e92d35455ce39ee1dabe136e1",
  "result": {
    "engine": "jupyter",
    "markdown": "# Adapting Pretrained Models: Prompting, PEFT, Quantization {#sec-17-peft-quantization}\n\n<!-- lecture-source:\n     Module 11 is slide-only; the prose spine comes from the instructor's detailed\n     notes in sources/11.1-before-fine-tuning.tex, sources/11.2-peft.tex, and\n     sources/11.3-quantization.tex.\n     course-lab bridge: machine-local LaTeX/Module 11/11.5 gemma.tex; package and\n                        model identifiers are treated as a supplied lab snapshot,\n                        not as claims about a current product interface.\n     primary sources: Brown et al. 2020; Lewis et al. 2020; Houlsby et al. 2019;\n                      Li and Liang 2021; Lester et al. 2021; Ben-Zaken et al. 2022;\n                      Hu et al. 2022; Wei et al. 2022; Turpin et al. 2023;\n                      Greshake et al. 2023;\n                      Dettmers et al. 2022, 2023; Frantar et al. 2023;\n                      Lin et al. 2024; Jacob et al. 2018\n     provenance note: all executable implementations, synthetic studies, and\n     figures are independently derived from displayed equations. External paper\n     figures and source implementations were not reproduced. The canonical LoRA\n     and affine-quantization forms were independently re-derived and checked against\n     primary sources. The context, rank-capacity, and quantization studies are\n     book-original mechanism demonstrations, not natural-language LLM benchmarks. -->\n\nChapter 9 left us a transfer rule: importing a representation is most promising\nwhen **labels are scarce, the target is feature-hungry, and the source supplies\nuseful coverage at a matched scale**. Chapter 15 showed the conventional next\nstep—fine-tuning changes every encoder weight. Chapter 16 then planted a second\nwarning: **training-optimal is not serving-optimal**. Chinchilla's allocation can\nspend a pretraining budget well while leaving us with a backbone that is expensive\nto copy, update, or store once per downstream task.\n\nLet us put those promises on one ledger. A pretrained model creates three different\nbills:\n\n1. the **backbone storage**—a base shared across tasks, or a full task-specific copy\n   when sharing is abandoned;\n2. the **incremental task state**—the prompt, adapter, or unmerged delta that makes\n   one task different from another; and\n3. the **transient work**—context tokens, activations, gradients, optimizer state,\n   and caches needed while adapting or running the model.\n\nThese bills are related—but they are not interchangeable. Freezing a billion\nweights removes their gradients—it does not make the billion weights disappear.\nPacking each weight into fewer bits reduces a storage lower bound—it does not prove\nthat a particular kernel will run faster. Adding demonstrations changes no weight—it\nstill lengthens the sequence the model must process. A merged LoRA or fully tuned\ncheckpoint can collapse base and delta into one artifact—but then each task carries\na full backbone-sized copy instead of sharing the original.\n\nThe useful organizing questions are therefore not simply “How many parameters?”\nThey are **where does task-specific information live, and which object does the\nmethod change?** Hard prompts and retrieved documents place task information in\ncontext. Parameter-efficient fine-tuning (PEFT) places it in a restricted set of\nlearned values. Quantization need not add task information at all—it changes the numerical\nrepresentation of a base or adapter. QLoRA composes the last two—it is not a fourth\nkind of objective.\n\n\n\n::: {#cell-fig-adaptation-map .cell fig-height='4.6' fig-width='10' execution_count=2}\n\n::: {.cell-output .cell-output-display}\n![Three levers act on three different objects. Prompting changes the context presented to a fixed model; PEFT permits a small learned state to receive gradient blame; quantization changes how fixed values are represented. QLoRA combines a quantized frozen base with a trainable low-rank branch. The separate cost ledger below is deliberately not column-matched: every lever can affect more than one bill, and none removes all backbone storage or transient work.](17-peft-quantization_files/figure-html/fig-adaptation-map-output-1.png){#fig-adaptation-map width=950 height=432 fig-alt='Three top boxes label context, trainable state, and representation. A separate dashed ledger below lists backbone storage, incremental state, and transient work, explicitly marked as not column-matched.'}\n:::\n:::\n\n\n## Prompting: move evidence into context\n\nA decoder in @sec-14-self-attention-transformer already defines a conditional\ndistribution over the next token. Prompting changes the prefix on which that fixed\ndistribution is conditioned. For an instruction $I$, demonstrations\n$(x_i,y_i)$, and a query $x_\\star$—a discrete prompted prediction can be written\n\n$$\n\\widehat y\n=\\argmax_y p_{\\theta_0}\\!\\left(\ny\\mid I,(x_1,y_1),\\ldots,(x_k,y_k),x_\\star\n\\right),\n\\qquad\n\\theta_{\\text{after}}=\\theta_{\\text{before}}=\\theta_0.\n$$ {#eq-icl-fixed-weights}\n\nWith no demonstrations, this is **zero-shot** prompting. With a few, it is\n**few-shot prompting**; when the model uses those examples to infer the task inside\nits forward computation, we call the behavior **in-context learning (ICL)**. The\nword *learning* names a behavioral change with context—not a checkpoint update.\n\nBrown and colleagues found that few-shot gains often grew with model scale in\nGPT-3—but that is an empirical result over particular models and tasks. It does\nnot establish universal parameter thresholds, nor does it settle the mechanism by\nwhich a Transformer uses demonstrations. Attention makes earlier examples visible\nand routable; saying it literally “performs analogy” would outrun the evidence.\nPrompt order, label words, formatting, and example choice can all matter.\n\nInstructions that ask for intermediate steps can improve some multi-step tasks.\nThose visible steps are generated tokens, however—not a guaranteed faithful window\ninto the model's internal computation. The same logits and decoding cautions from\n@sec-11-encoder-decoder still apply.\n\n::: {.callout-note}\n## Prompting is not prompt tuning\n\nA hard prompt is a sequence of ordinary token IDs chosen by a person or program.\nIt receives no gradient. **Prompt tuning**, introduced later in this chapter, learns\ncontinuous vectors by backpropagation and is therefore a PEFT method. Similar names\ndo not mean the same training procedure.\n:::\n\nZero trainable parameters is not zero cost—demonstrations consume context length.\nThey increase **prefill** work, the initial forward pass that processes the supplied\nprefix, and occupy entries in the **key/value (KV) cache**, the stored attention keys\nand values reused while autoregressively generating later tokens. They also expose\ntask data at inference time. Prompting trades a new checkpoint for a longer, more\ncarefully constructed input.\n\n### A frozen-context mechanism test\n\nCan a fixed network genuinely change its answer because examples in the prompt\nreveal a task? We can test that mechanism without claiming to reproduce\nnatural-language ICL.\n\nEach synthetic episode secretly permutes four group symbols onto four label symbols.\nA demonstration reveals one group–label pair; demo groups are distinct. A two-shot\nprompt might read `[BOS] group C, label A; group A, label D; [QUERY] group A`, whose\ntarget is `label D`. The query\nasks for another group's label. A tiny causal Transformer is meta-trained across\nmany such episodes, cycling through one to four demonstrations. During evaluation,\nit receives a new random mapping and **no parameter update**.\n\nThe information ceiling is known before training. With $k<4$ demonstrations, the\nquery is already covered with probability $k/4$. Otherwise, its label is uniform\namong the $4-k$ unused labels. Therefore\n\n$$\n\\Pr(\\text{correct}\\mid k)\n=\n\\begin{cases}\n\\dfrac{k}{4}+\\left(1-\\dfrac{k}{4}\\right)\\dfrac{1}{4-k}\n=\\dfrac{k+1}{4}, & 0\\le k\\le3,\\\\[6pt]\n1, & k=4.\n\\end{cases}\n$$ {#eq-icl-ceiling}\n\nAt $k=3$, even an unseen query group is solvable by elimination—a distinction that\nwill tell us whether the model merely copies a seen pair or uses the whole mapping.\n\nThe code uses `nn.TransformerEncoderLayer` as a compact container for the same\npre-LayerNorm attention–residual–FFN structural pattern built from first principles\nin @sec-14-self-attention-transformer. Its GELU choice differs from that chapter's\nteaching block; the wrapper does not hide the causal or padding masks, embeddings,\nor classifier. Token IDs have shape $[B,11]$, hidden states $[B,11,48]$, and the\nquery logits $[B,4]$.\n\n::: {#icl-mechanism .cell execution_count=3}\n``` {.python .cell-code code-summary=\"Code: meta-train a tiny causal Transformer, then audit frozen-weight in-context adaptation over five seeds\"}\nPAD, BOS, QUERY = 0, 1, 2\nGROUP0, LABEL0 = 3, 7\nVOCAB, SEQUENCE_LENGTH, N_CLASSES = 11, 11, 4\n\n\ndef sample_episode_bank(\n    batch_size: int, generator: torch.Generator\n) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:\n    mapping = torch.rand(batch_size, N_CLASSES, generator=generator).argsort(dim=1)\n    demo_groups = torch.rand(\n        batch_size, N_CLASSES, generator=generator\n    ).argsort(dim=1)\n    query_groups = torch.randint(\n        N_CLASSES, (batch_size,), generator=generator\n    )\n    return mapping, demo_groups, query_groups\n\n\ndef render_episodes(\n    bank: tuple[torch.Tensor, torch.Tensor, torch.Tensor], k: int\n) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:\n    mapping, demo_groups, query_groups = bank\n    tokens = torch.full((len(mapping), SEQUENCE_LENGTH), PAD, dtype=torch.long)\n    tokens[:, 0] = BOS\n    for slot in range(k):\n        group = demo_groups[:, slot]\n        label = mapping.gather(1, group[:, None]).squeeze(1)\n        tokens[:, 1 + 2 * slot] = GROUP0 + group\n        tokens[:, 2 + 2 * slot] = LABEL0 + label\n    tokens[:, 9] = QUERY\n    tokens[:, 10] = GROUP0 + query_groups\n    targets = mapping.gather(1, query_groups[:, None]).squeeze(1)\n    covered = (\n        (demo_groups[:, :k] == query_groups[:, None]).any(dim=1)\n        if k else torch.zeros(len(mapping), dtype=torch.bool)\n    )\n    return tokens, targets, covered\n\n\nclass ContextLearner(nn.Module):\n    def __init__(self, width: int = 48, heads: int = 4, layers: int = 2) -> None:\n        super().__init__()\n        self.token = nn.Embedding(VOCAB, width, padding_idx=PAD)\n        self.position = nn.Embedding(SEQUENCE_LENGTH, width)\n        layer = nn.TransformerEncoderLayer(\n            d_model=width, nhead=heads, dim_feedforward=2 * width,\n            dropout=0.0, batch_first=True, norm_first=True, activation=\"gelu\",\n        )\n        self.encoder = nn.TransformerEncoder(\n            layer, layers, norm=nn.LayerNorm(width), enable_nested_tensor=False\n        )\n        self.head = nn.Linear(width, N_CLASSES)\n        self.register_buffer(\n            \"causal\",\n            torch.triu(torch.ones(SEQUENCE_LENGTH, SEQUENCE_LENGTH, dtype=torch.bool),\n                       diagonal=1),\n        )\n\n    def forward(self, tokens: torch.Tensor) -> torch.Tensor:\n        positions = torch.arange(SEQUENCE_LENGTH, device=tokens.device)\n        hidden = self.token(tokens) + self.position(positions)[None]\n        hidden = self.encoder(\n            hidden, mask=self.causal, src_key_padding_mask=tokens.eq(PAD)\n        )\n        return self.head(hidden[:, -1])\n\n\n@torch.no_grad()\ndef evaluate_context(\n    model: nn.Module, seed: int, n: int = 8192\n) -> tuple[list[dict], bool]:\n    model.eval()\n    before = [parameter.detach().clone() for parameter in model.parameters()]\n    bank = sample_episode_bank(n, torch.Generator().manual_seed(seed + 10_000))\n    rows = []\n    for k in range(5):\n        tokens, targets, covered = render_episodes(bank, k)\n        correct = model(tokens).argmax(1).eq(targets)\n        rows.append({\n            \"k\": k,\n            \"accuracy\": correct.float().mean().item(),\n            \"covered\": correct[covered].float().mean().item()\n                       if covered.any() else float(\"nan\"),\n            \"uncovered\": correct[~covered].float().mean().item()\n                         if (~covered).any() else float(\"nan\"),\n        })\n    unchanged = all(\n        torch.equal(old, new) for old, new in zip(before, model.parameters())\n    )\n    return rows, unchanged\n\n\ndef run_context_seed(seed: int, steps: int = 1200) -> dict:\n    torch.manual_seed(seed)\n    generator = torch.Generator().manual_seed(seed)\n    model = ContextLearner()\n    optimizer = torch.optim.AdamW(model.parameters(), lr=3e-3, weight_decay=1e-2)\n    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(\n        optimizer, T_max=steps, eta_min=3e-5\n    )\n    model.train()\n    for step in range(steps):\n        k = 1 + step % 4\n        bank = sample_episode_bank(256, generator)\n        tokens, targets, _ = render_episodes(bank, k)\n        loss = F.cross_entropy(model(tokens), targets)\n        optimizer.zero_grad(set_to_none=True)\n        loss.backward()\n        nn.utils.clip_grad_norm_(model.parameters(), 1.0)\n        optimizer.step()\n        scheduler.step()\n    rows, unchanged = evaluate_context(model, seed)\n    return {\n        \"seed\": seed,\n        \"rows\": rows,\n        \"unchanged\": unchanged,\n        \"parameters\": sum(parameter.numel() for parameter in model.parameters()),\n    }\n\n\nCONTEXT_SEEDS = list(range(6050, 6055))\ncontext_runs = [run_context_seed(seed) for seed in CONTEXT_SEEDS]\ncontext_accuracy = np.array([\n    [row[\"accuracy\"] for row in run[\"rows\"]] for run in context_runs\n])\ncontext_ceiling = np.array([0.25, 0.50, 0.75, 1.00, 1.00])\n\nprint(\"model parameters:\", f'{context_runs[0][\"parameters\"]:,}')\nprint(\"k  mean accuracy  seed sd  information ceiling\")\nfor k in range(5):\n    print(\n        f\"{k}      {context_accuracy[:, k].mean():.3f}       \"\n        f\"{context_accuracy[:, k].std(ddof=1):.3f}          \"\n        f\"{context_ceiling[k]:.2f}\"\n    )\nprint(\"all evaluation passes left weights unchanged:\",\n      all(run[\"unchanged\"] for run in context_runs))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmodel parameters: 39,268\nk  mean accuracy  seed sd  information ceiling\n0      0.252       0.003          0.25\n1      0.500       0.005          0.50\n2      0.749       0.002          0.75\n3      1.000       0.000          1.00\n4      1.000       0.000          1.00\nall evaluation passes left weights unchanged: True\n```\n:::\n:::\n\n\n::: {#cell-fig-icl-coverage .cell fig-height='3.8' fig-width='9' execution_count=4}\n``` {.python .cell-code code-summary=\"Figure code: compare frozen-context accuracy with the analytic ceiling and the seen-versus-unseen decomposition\"}\nfig, axes = plt.subplots(1, 2, figsize=(9, 3.8))\nks = np.arange(5)\nfor seed_row in context_accuracy:\n    axes[0].plot(ks, seed_row, color=\"#A7ABB4\", lw=1.1, alpha=0.75)\naxes[0].plot(ks, context_accuracy.mean(axis=0), \"o-\", color=orange, lw=2.6,\n             label=\"five-seed mean\")\naxes[0].plot(ks, context_ceiling, \"--\", color=navy, lw=2,\n             label=\"information ceiling\")\naxes[0].set(xlabel=\"demonstrations $k$\", ylabel=\"query accuracy\",\n            title=\"behavior changes; weights do not\", ylim=(0.18, 1.04))\naxes[0].set_xticks(ks)\naxes[0].legend(frameon=False, fontsize=8)\n\ncovered_mean = np.array([\n    np.mean([run[\"rows\"][k][\"covered\"] for run in context_runs])\n    for k in range(1, 5)\n])\nuncovered_mean = np.array([\n    np.mean([run[\"rows\"][k][\"uncovered\"] for run in context_runs])\n    for k in range(4)\n])\naxes[1].plot(np.arange(1, 5), covered_mean, \"s-\", color=green, lw=2.4,\n             label=\"query group demonstrated\")\naxes[1].plot(np.arange(4), uncovered_mean, \"o-\", color=wine, lw=2.4,\n             label=\"query group unseen\")\naxes[1].plot(np.arange(4), [1 / 4, 1 / 3, 1 / 2, 1], \"^--\",\n             color=\"#555555\", lw=1.7, label=\"unseen ceiling\")\naxes[1].set(xlabel=\"demonstrations $k$\", ylabel=\"conditional accuracy\",\n            title=\"copy when seen; eliminate when unseen\", ylim=(0.18, 1.04))\naxes[1].set_xticks(ks)\naxes[1].legend(frameon=False, fontsize=7.6, loc=\"lower right\")\nfor ax in axes:\n    ax.grid(alpha=0.18)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![A frozen model changes behavior as demonstrations reveal an episode's hidden label mapping. Across five independently trained seeds, overall accuracy (left) closely tracks the analytical information ceiling. Conditional accuracy (right) is perfect when the query group appeared; for unseen groups it follows the shrinking set of unused labels and reaches 1 at three demonstrations by elimination. Evaluation uses one nested episode bank per seed, and every parameter is bitwise unchanged across all five context lengths.](17-peft-quantization_files/figure-html/fig-icl-coverage-output-1.png){#fig-icl-coverage width=856 height=355 fig-alt='Two line plots. Mean accuracy rises from one quarter with no examples to one with three examples and tracks the analytic ceiling. Seen queries are always correct; unseen-query accuracy rises from one quarter to one by elimination.'}\n:::\n:::\n\n\nThe 39,268-parameter network lands at mean accuracies\n$0.252,0.500,0.749,1.000,1.000$ for $k=0,1,2,3,4$, respectively. The analytic\nceilings are $0.25,0.50,0.75,1,1$. More revealingly, unseen-query accuracy rises\nfrom $0.252$ to $0.330$, $0.499$, and $1.000$. The model is not only copying a\nmatching demonstration; at $k=3$ it identifies the remaining label.\n\n::: {.callout-warning}\n## An existence proof in a designed regime\n\nThe model was meta-trained on exactly this family of random permutation tasks. The\nstudy demonstrates that a frozen causal Transformer can use prompt evidence in this\ncontrolled distribution. It does not estimate natural-language ICL quality,\nexplain the mechanism inside a large language model, or show that more examples\nalways help. Across runs, initialization, meta-training episodes, and the finite\n8,192-episode evaluation bank all change. The seed SD therefore measures combined\nrun-to-run repeatability—not task or domain diversity, and not optimization alone.\n:::\n\n### Retrieval is another context lever\n\nA prompt can contain information selected at query time rather than written by\nhand. **Retrieval-augmented generation (RAG)** first searches an external corpus,\nthen places retrieved passages beside the instruction and query before generation.\nThe generator's weights may remain fixed—the task-specific state lives partly in\nthe index and partly in the retrieved context.\n\nThis reconnects to @sec-12-kernel-regression. A retriever computes query–document\nsimilarities, selects neighbors, and hands their content to a downstream weighted\ncomputation. Modern systems can learn the retriever, the generator, or both, but\nthe basic context-augmentation move is distinct from PEFT.\n\nRetrieval moves rather than abolishes failure—a missed document cannot support the\nanswer; a highly ranked irrelevant passage can distract it; retrieved text can\ncontain malicious instructions; and a plausible citation does not prove that the\ngenerated claim follows from the cited evidence. RAG is attractive when facts change\nfaster than checkpoints or when provenance matters, but it is a pipeline whose\nretrieval and generation stages must be evaluated separately.\n\n## What if the prompt itself were learnable?\n\nHard prompts spend human effort and context tokens. The chapter's familiar refrain\nnow applies: **what if the prompt itself were learnable?** Let\n$\\matr{P}\\in\\mathbb{R}^{m\\times d}$ be $m$ continuous vectors with the same width\nas token embeddings. For an $n$-token input, define\n$\\operatorname{Embed}(x)\\in\\mathbb{R}^{n\\times d}$. Prompt tuning prepends the\nlearned rows,\n\n$$\n\\matr{H}^{(0)}=[\\matr{P};\\operatorname{Embed}(x)],\n\\qquad\n\\min_{\\matr{P}}\n-\\sum_i\\log p_{\\theta_0,\\matr{P}}(y_i\\mid x_i),\n$$ {#eq-prompt-tuning}\n\nwhile freezing $\\theta_0$. Before any task head, the learned state contains exactly\n$md$ values. Those values are not words—and need not be nearest to any vocabulary\nembedding. They are virtual tokens optimized by gradient descent, and they still\noccupy $m$ virtual sequence positions during use.\n\n**Prefix tuning** moves a related idea deeper. At every Transformer layer $\\ell$,\nlet the ordinary keys and values be\n$\\matr{K}_\\ell,\\matr{V}_\\ell\\in\\mathbb{R}^{n\\times d}$ and the learned prefixes be\n$\\matr{P}^K_\\ell,\\matr{P}^V_\\ell\\in\\mathbb{R}^{m\\times d}$. The prefix rows extend\nthe ordinary keys and values:\n\n$$\n\\matr{K}'_\\ell=[\\matr{P}^K_\\ell;\\matr{K}_\\ell],\n\\qquad\n\\matr{V}'_\\ell=[\\matr{P}^V_\\ell;\\matr{V}_\\ell].\n$$\n\nA direct implementation with $m$ prefix slots, width $d$, and $L$ layers stores\n$2Lmd$ values, although practical parameterizations can differ. Li and Liang used\nan auxiliary network during optimization—then retained only the learned prefix for\ninference. Lester and colleagues found that prompt tuning approached full tuning as\nT5 scale grew in their SuperGLUE study; that result is not a universal size\nthreshold.\n\nTwo other PEFT families complete the map. **Adapters** insert a small bottleneck\ninside each frozen Transformer block. For bottleneck width $d_b$, let\n$\\matr{W}_{\\mathrm{down}}\\in\\mathbb{R}^{d_b\\times d}$,\n$\\vect{b}_{\\mathrm{down}}\\in\\mathbb{R}^{d_b}$,\n$\\matr{W}_{\\mathrm{up}}\\in\\mathbb{R}^{d\\times d_b}$, and\n$\\vect{b}_{\\mathrm{up}}\\in\\mathbb{R}^{d}$. One common residual form is\n\n$$\n\\operatorname{Adapter}(\\vect{h})\n=\\vect{h}\n+\\matr{W}_{\\mathrm{up}}\n\\sigma(\\matr{W}_{\\mathrm{down}}\\vect{h}+\\vect{b}_{\\mathrm{down}})\n+\\vect{b}_{\\mathrm{up}},\n$$\n\nThis module adds $2dd_b+d+d_b$ parameters. **BitFit** takes the selective-update idea to an\nextreme—freeze pretrained weight matrices and update their existing bias terms. The\noriginal BitFit classification experiments also trained the task-specific output\nlayer; “bias-only” describes the restriction inside the pretrained backbone.\nNeither method promises the same accuracy on every task. They are different\nrestrictions on where gradient blame may write.\n\n## LoRA: a low-rank correction beside a frozen path\n\nConsider one frozen linear map\n\n$$\n\\matr{W}_0\\in\\mathbb{R}^{d_{\\mathrm{out}}\\times d_{\\mathrm{in}}},\n\\qquad\n\\vect{h}=\\matr{W}_0\\vect{x}.\n$$\n\nFull fine-tuning learns an unrestricted correction $\\Delta\\matr{W}$ with\n$d_{\\mathrm{out}}d_{\\mathrm{in}}$ values. **Low-Rank Adaptation (LoRA)** instead\nconstrains the correction to a product of two thin matrices:\n\n$$\n\\Delta\\matr{W}\n=\\frac{\\alpha}{r}\\matr{B}\\matr{A},\n\\qquad\n\\matr{A}\\in\\mathbb{R}^{r\\times d_{\\mathrm{in}}},\n\\quad\n\\matr{B}\\in\\mathbb{R}^{d_{\\mathrm{out}}\\times r}.\n$$ {#eq-lora-delta}\n\nThe forward pass is\n\n$$\n\\vect{h}\n=\\matr{W}_0\\vect{x}\n+\\frac{\\alpha}{r}\\matr{B}(\\matr{A}\\vect{x}).\n$$ {#eq-lora-forward}\n\n$\\matr{A}$ compresses to $r$ coordinates and $\\matr{B}$ expands back to the output\nwidth. Because $\\operatorname{rank}(\\matr{B}\\matr{A})\\le r$, task updates can use\nat most $r$ independent linear directions in that matrix. The merged matrix is not\ntherefore rank $r$—the constraint applies only to the correction.\n\nThe trainable count is\n\n$$\nP_{\\mathrm{LoRA}}\n=r(d_{\\mathrm{in}}+d_{\\mathrm{out}}).\n$$ {#eq-lora-count}\n\nFor one $4096\\times4096$ map and $r=16$, full tuning exposes 16,777,216 values;\nLoRA exposes $16(4096+4096)=131{,}072$, or $0.78125\\%$. A model-level percentage\nrequires summing @eq-lora-count over the matrices actually targeted. The original\nLoRA experiments emphasized query and value projections—later recipes often target\ndifferent or more numerous matrices. “Rank 16” alone does not specify an adapter's\nsize.\n\n<!-- NOVEL: needs sign-off - concise course-lab bridge requested in the review. -->\n::: {.callout-tip}\n## Course-lab bridge (non-examinable): read PEFT through the algebra\n\nModule 11's supplied Gemma/PEFT lab expresses @eq-lora-delta through a package\nwrapper. Treat the wrapper's names as a translation layer, not as new mathematics:\n\n- `r` is the inner dimension of $A$ and $B$;\n- `lora_alpha / r` represents the factor $\\alpha/r$;\n- `target_modules` chooses which frozen maps play the role of $W_0$;\n- the adapter checkpoint carries the learned factors, while the base checkpoint\n  supplies the frozen path.\n\nIf the lab targets “all linear” modules, do not infer the adapter size from that\nphrase. Inspect the selected module names and shapes, sum @eq-lora-count over exactly\nthat set, and print the parameters that still have `requires_grad=True`. Then apply\nthe four-part freeze audit below: the base stays unchanged, only permitted factors\nreceive gradients, and merged and unmerged outputs agree within a declared numerical\ntolerance. Package calls and model identifiers can evolve; these algebraic checks are\nthe stable contract.\n\nWhen the lab also stores the base on a quantization grid, the result is QLoRA, not a\ndifferent LoRA equation. Keep the frozen base's storage and compute dtypes separate\nfrom the factors' trainable dtype, as @sec-a3-precision-performance requires. The\nQLoRA section later in this chapter makes that composition explicit.\n:::\n<!-- /NOVEL -->\n\n::: {#cell-fig-lora-path .cell fig-height='3.5' fig-width='9' execution_count=5}\n\n::: {.cell-output .cell-output-display}\n![LoRA adds a trainable low-rank branch beside a frozen linear map. Gradient blame flows through both computational paths, but only A and B receive updates. Initializing A randomly and B to zero begins with an exact zero correction while leaving a nonzero first gradient for B; after training, the correction can be merged into a compatible base weight.](17-peft-quantization_files/figure-html/fig-lora-path-output-1.png){#fig-lora-path width=854 height=326 fig-alt='A frozen W-zero path and a parallel trainable A-then-B path both receive x and are added to produce h. A merge equation above combines the two paths after training.'}\n:::\n:::\n\n\nThe usual initialization samples $\\matr{A}$ and sets $\\matr{B}=0$. The initial\ncorrection is then exactly zero—yet $\\matr{B}$ can receive a gradient because\n$\\matr{A}\\vect{x}$ is generally nonzero. Setting both factors to zero would block\nboth first gradients. The scale $\\alpha/r$ separates a chosen adapter strength from\nrank, but its best value remains a tuning decision.\n\nOnce trained, a single compatible adapter can be merged:\n\n$$\n\\matr{W}_{\\mathrm{merged}}\n=\\matr{W}_0+\\frac{\\alpha}{r}\\matr{B}\\matr{A}.\n$$ {#eq-lora-merge}\n\nMerged and unmerged arithmetic should agree to numerical tolerance. Only the merged\nform removes the extra branch at inference. Dynamic adapter switching, keeping many\nadapters active, or combining LoRA with a quantized base changes that systems story;\na quantized merge generally requires dequantization and requantization.\n\n::: {.callout-tip}\n## A four-part freeze audit\n\nCount trainable values; assert the base tensor is bitwise unchanged; inspect that\nonly permitted parameters receive gradients; and compare merged with unmerged\noutputs. A small checkpoint is not evidence that the intended tensors were frozen.\nThe assertions belong beside the implementation, not in a comment after training.\n:::\n\n### Make the rank bottleneck fail on purpose\n\nLow rank is a hypothesis about the update—not a free compression theorem. We can\nmake its boundary visible by planting a target correction with exactly six\nindependent diagonal directions. The frozen base is a $32\\times32$ map. Full tuning\nmay move all 1,024 entries; LoRA may use ranks $1,2,4,6,$ or $8$. Inputs are fixed\nGaussian vectors, targets are noiseless, and five LoRA initializations see the same\nproblem and optimizer schedule.\n\nWrite the six planted magnitudes as $\\sigma_1\\ge\\cdots\\ge\\sigma_6$. Their values are\n$1.20,0.90,0.65,0.40,0.22,0.10$. A rank-$r$ correction below six must leave some\ndirections behind. This design deliberately favors the LoRA assumption—that is what\nmakes the capacity claim falsifiable before we run it.\n\nBecause the six diagonal basis directions are mutually orthogonal, their squared\ncorrection energy is $\\sum_{j=1}^{6}\\sigma_j^2$. A rank-$r$ correction can retain at\nmost $r$ independent directions; spending them on the $r$ largest magnitudes leaves\nthe concrete relative floor\n\n$$\n\\epsilon_r\n=\\sqrt{\\frac{\\sum_{j=r+1}^{6}\\sigma_j^2}\n              {\\sum_{j=1}^{6}\\sigma_j^2}},\n\\qquad r<6,\n$$ {#eq-lora-diagonal-floor}\n\nand zero for $r\\ge6$. The plotted “capacity floor” is this calculation—not a result\nestimated from the optimizer.\n\n::: {#lora-capacity .cell execution_count=6}\n``` {.python .cell-code code-summary=\"Code: compare frozen, full, and low-rank updates against a planted rank-six correction\"}\nD_IN = D_OUT = 32\nTARGET_RANK = 6\nDIRECTION_MAGNITUDES = torch.tensor([1.20, 0.90, 0.65, 0.40, 0.22, 0.10])\n\n\ndef make_rank_problem(\n    seed: int = 1700,\n) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor,\n           torch.Tensor, torch.Tensor]:\n    generator = torch.Generator().manual_seed(seed)\n    base = torch.randn(D_OUT, D_IN, generator=generator) / math.sqrt(D_IN)\n    correction = torch.zeros(D_OUT, D_IN)\n    diagonal = torch.arange(TARGET_RANK)\n    correction[diagonal, diagonal] = DIRECTION_MAGNITUDES\n    x_train = torch.randn(1024, D_IN, generator=generator)\n    x_validation = torch.randn(4096, D_IN, generator=generator)\n    y_train = F.linear(x_train, base + correction)\n    y_validation = F.linear(x_validation, base + correction)\n    return base, correction, x_train, y_train, x_validation, y_validation\n\n\nclass FullUpdate(nn.Module):\n    def __init__(self, base: torch.Tensor) -> None:\n        super().__init__()\n        self.weight = nn.Parameter(base.clone())\n\n    def forward(self, x: torch.Tensor) -> torch.Tensor:\n        return F.linear(x, self.weight)\n\n\nclass LoRAUpdate(nn.Module):\n    def __init__(\n        self, base: torch.Tensor, rank: int, generator: torch.Generator\n    ) -> None:\n        super().__init__()\n        self.register_buffer(\"weight0\", base.clone())\n        self.A = nn.Parameter(torch.randn(rank, D_IN, generator=generator) * 0.02)\n        self.B = nn.Parameter(torch.zeros(D_OUT, rank))\n        self.rank = rank\n        self.alpha = rank\n\n    @property\n    def scaling(self) -> float:\n        return self.alpha / self.rank\n\n    def forward(self, x: torch.Tensor) -> torch.Tensor:\n        low_rank = F.linear(F.linear(x, self.A), self.B)\n        return F.linear(x, self.weight0) + self.scaling * low_rank\n\n    def merged_weight(self) -> torch.Tensor:\n        return self.weight0 + self.scaling * (self.B @ self.A)\n\n\ndef train_linear_update(\n    model: nn.Module, x: torch.Tensor, y: torch.Tensor, steps: int = 1200\n) -> None:\n    optimizer = torch.optim.Adam(model.parameters(), lr=0.03)\n    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(\n        optimizer, T_max=steps, eta_min=3e-4\n    )\n    for _ in range(steps):\n        loss = F.mse_loss(model(x), y)\n        optimizer.zero_grad(set_to_none=True)\n        loss.backward()\n        optimizer.step()\n        scheduler.step()\n\n\ndef relative_update_error(\n    estimate: torch.Tensor, target: torch.Tensor\n) -> float:\n    return (torch.linalg.norm(estimate - target) / torch.linalg.norm(target)).item()\n\n\nbase, target_delta, x_train, y_train, x_val, y_val = make_rank_problem()\ntarget_energy = torch.sum(DIRECTION_MAGNITUDES ** 2)\n\nfull_model = FullUpdate(base)\ntrain_linear_update(full_model, x_train, y_train)\nwith torch.no_grad():\n    full_mse = F.mse_loss(full_model(x_val), y_val).item()\n    full_relative_error = relative_update_error(\n        full_model.weight - base, target_delta\n    )\n    frozen_mse = F.mse_loss(F.linear(x_val, base), y_val).item()\n\nLORA_RANKS = [1, 2, 4, 6, 8]\nlora_runs = []\nfor seed in range(6050, 6055):\n    for rank in LORA_RANKS:\n        model = LoRAUpdate(\n            base, rank, torch.Generator().manual_seed(seed + rank)\n        )\n        frozen_before = model.weight0.clone()\n        train_linear_update(model, x_train, y_train)\n        with torch.no_grad():\n            merged = model.merged_weight()\n            merge_error = (\n                model(x_val[:64]) - F.linear(x_val[:64], merged)\n            ).abs().max().item()\n            assert torch.equal(frozen_before, model.weight0)\n            assert merge_error < 2e-6\n            learned_delta = merged - base\n            lora_runs.append({\n                \"seed\": seed,\n                \"rank\": rank,\n                \"trainable\": rank * (D_IN + D_OUT),\n                \"validation_mse\": F.mse_loss(model(x_val), y_val).item(),\n                \"relative_error\": relative_update_error(learned_delta, target_delta),\n                \"merge_error\": merge_error,\n            })\n\nprint(f\"frozen validation MSE: {frozen_mse:.6f}\")\nprint(\n    f\"full update: MSE={full_mse:.2e}, relative delta error=\"\n    f\"{full_relative_error:.2e} (1,024 trainable)\"\n)\nprint(\"rank  trainable  mean validation MSE  mean relative update error\")\nfor rank in LORA_RANKS:\n    selected = [row for row in lora_runs if row[\"rank\"] == rank]\n    print(\n        f\"{rank:>4}  {selected[0]['trainable']:>9,}  \"\n        f\"{np.mean([row['validation_mse'] for row in selected]):>19.8f}  \"\n        f\"{np.mean([row['relative_error'] for row in selected]):>26.6f}\"\n    )\nprint(\"largest merged/unmerged difference:\",\n      f\"{max(row['merge_error'] for row in lora_runs):.2e}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nfrozen validation MSE: 0.091155\nfull update: MSE=6.39e-15, relative delta error=2.39e-07 (1,024 trainable)\nrank  trainable  mean validation MSE  mean relative update error\n   1         64           0.04535140                    0.709896\n   2        128           0.02021863                    0.471562\n   4        256           0.00188776                    0.142274\n   6        384           0.00000000                    0.000000\n   8        512           0.00000000                    0.000000\nlargest merged/unmerged difference: 1.43e-06\n```\n:::\n:::\n\n\n::: {#cell-fig-lora-rank-capacity .cell fig-height='3.8' fig-width='9' execution_count=7}\n``` {.python .cell-code code-summary=\"Figure code: compare learned rank-sweep errors with the planted capacity floors\"}\nrank_error = np.array([\n    [next(row[\"relative_error\"] for row in lora_runs\n          if row[\"seed\"] == seed and row[\"rank\"] == rank)\n     for rank in LORA_RANKS]\n    for seed in range(6050, 6055)\n])\nrank_mse = np.array([\n    [next(row[\"validation_mse\"] for row in lora_runs\n          if row[\"seed\"] == seed and row[\"rank\"] == rank)\n     for rank in LORA_RANKS]\n    for seed in range(6050, 6055)\n])\nfloors = np.array([\n    math.sqrt((DIRECTION_MAGNITUDES[rank:] ** 2).sum().item() / target_energy.item())\n    if rank < TARGET_RANK else 0.0\n    for rank in LORA_RANKS\n])\n\nfig, axes = plt.subplots(1, 2, figsize=(9, 3.8))\nfor seed_row in rank_error:\n    axes[0].plot(LORA_RANKS, np.maximum(seed_row, 1e-8), color=\"#A7ABB4\", lw=1)\naxes[0].plot(LORA_RANKS, np.maximum(rank_error.mean(axis=0), 1e-8), \"o-\",\n             color=orange, lw=2.5, label=\"learned mean\")\naxes[0].plot(LORA_RANKS, np.maximum(floors, 1e-8), \"s--\", color=navy, lw=2,\n             label=\"capacity floor\")\naxes[0].axvline(TARGET_RANK, color=green, ls=\":\", lw=1.7)\naxes[0].set_yscale(\"log\")\naxes[0].set(xlabel=\"adapter rank $r$\", ylabel=\"relative correction error\",\n            title=\"below rank six, information is missing\")\naxes[0].set_xticks(LORA_RANKS)\naxes[0].legend(frameon=False, fontsize=8)\n\naxes[1].plot(LORA_RANKS, np.maximum(rank_mse.mean(axis=0), 1e-15), \"o-\",\n             color=wine, lw=2.5, label=\"LoRA\")\naxes[1].axhline(frozen_mse, color=\"#555555\", ls=\"--\", lw=1.6, label=\"frozen base\")\naxes[1].axhline(max(full_mse, 1e-15), color=green, ls=\":\", lw=1.8,\n                label=\"full update\")\nfor rank, mse, count in zip(LORA_RANKS, rank_mse.mean(axis=0),\n                            [64, 128, 256, 384, 512]):\n    axes[1].annotate(f\"{count}\", (rank, max(mse, 1e-15)), xytext=(0, 7),\n                     textcoords=\"offset points\", ha=\"center\", fontsize=8)\naxes[1].set_yscale(\"log\")\naxes[1].set(xlabel=\"adapter rank $r$\", ylabel=\"validation MSE\",\n            title=\"task error inherits the rank boundary\")\naxes[1].set_xticks(LORA_RANKS)\naxes[1].legend(frameon=False, fontsize=8)\nfor ax in axes:\n    ax.grid(alpha=0.17)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![LoRA's rank is a real capacity constraint in a problem constructed to expose it. Five factor initializations converge to the same rank-limited relative update errors (left), closely tracking the analytic best floors from the planted diagonal magnitudes. Validation error (right) falls sharply but remains nonzero below the planted rank six; rank six, rank eight, and the unrestricted full update reach numerical zero. Counts label trainable adapter values in this deliberately small layer.](17-peft-quantization_files/figure-html/fig-lora-rank-capacity-output-1.png){#fig-lora-rank-capacity width=853 height=355 fig-alt='Two logarithmic line plots. Relative correction error follows a calculated floor at ranks one, two, and four, then drops near zero at the planted rank six. Validation MSE shows the same boundary.'}\n:::\n:::\n\n\nThe failure is orderly. Rank 1 leaves relative correction error $0.710$; rank 2\nleaves $0.472$; rank 4 leaves $0.142$. Their mean validation MSEs are\n$0.04535,0.02022,$ and $0.001888$. Rank 6 and rank 8 recover the target to below\n$10^{-7}$ relative correction error. The unrestricted update reaches numerical-zero\nvalidation MSE and $2.39\\times10^{-7}$ relative correction error. Every frozen base\nis bitwise intact, and the largest merged–unmerged discrepancy is below\n$2\\times10^{-6}$.\n\nIn this toy $32\\times32$ layer, rank 6 still trains 384 values—37.5% of a full\nmatrix. The point is inspectability, not an impressive compression ratio. Real\nLoRA savings depend on wide matrices, small ranks, and which layers are targeted.\nLikewise, the experiment was built from a low-rank shift—a task whose useful\ncorrection is not well captured at the chosen rank will retain error no matter how\nfashionable the adapter is.\n\n## Quantization: put weights on a smaller grid\n\nPEFT restricts which values may change. **Quantization** asks how precisely values\nmust be represented. If a tensor contains $N$ values stored at $b$ bits each, its\nideal packed payload is\n\n$$\n\\text{payload}=\\frac{Nb}{8}\\ \\text{bytes}.\n$$ {#eq-quant-payload}\n\nOne billion FP16 weights therefore require 2 GB in decimal units; an ideal packed\n4-bit payload requires 0.5 GB. Those are weight-payload lower bounds—not complete\ncheckpoints or working-memory forecasts. Scales, zero-points, unquantized tensors,\npacking alignment, activations, and caches remain.\n\nThis is where a tensor's *dtype* becomes more than a software label.\n@sec-a2-tensors will gather dtype, shape, stride, and physical layout in one place;\n@sec-a3-precision-performance connects FP16, BF16, rounding, and mixed precision to the\nfinite representations first encountered in Chapter 5. Here we need one narrower\nfact—fewer nominal bits change both representable values and storage arithmetic.\n\nStart with signed **symmetric uniform quantization** of a real-valued tensor\n$\\matr{W}$. For $b$ bits, let\n\n$$\nQ=2^{b-1}-1,\n\\qquad\ns=\\frac{\\max_{ij}|W_{ij}|}{Q}.\n$$\n\nQuantize and reconstruct by\n\n$$\nq_{ij}=\\operatorname{clip}\\!\\left(\n\\operatorname{round}(W_{ij}/s),-Q,Q\n\\right),\n\\qquad\n\\widehat W_{ij}=s q_{ij}.\n$$ {#eq-symmetric-quantization}\n\n$s$ is the distance between adjacent real-valued grid points. This symmetric choice\nuses codes $-Q,\\ldots,Q$: $2^b-1$ levels, leaving the most-negative two's-complement\ncode unused so the endpoints remain balanced around zero. With the maximum used for\ncalibration, values are not clipped beyond the selected range; nearest\nrounding gives $|W_{ij}-\\widehat W_{ij}|\\le s/2$. One extreme value increases $s$\nfor everything sharing that scale, so small values may all round to zero.\n\nIf every value is zero, choose any positive sentinel scale—say $s=1$—and store zero\ncodes. A constant affine range likewise needs a separately defined convention; the\nrange formula below otherwise divides by zero.\n\nAn **affine** grid also stores an integer zero-point $z$:\n\n$$\nq=\\operatorname{clip}\\!\\left(\n\\operatorname{round}(w/s)+z,q_{\\min},q_{\\max}\n\\right),\n\\qquad\n\\widehat w=s(q-z).\n$$ {#eq-affine-quantization}\n\nFor a nonconstant calibrated interval $[w_{\\min},w_{\\max}]$, a standard choice is\n\n$$\ns=\\frac{w_{\\max}-w_{\\min}}{q_{\\max}-q_{\\min}},\n\\qquad\nz=\\operatorname{clip}\\!\\left(\n\\operatorname{round}\\!\\left(q_{\\min}-\\frac{w_{\\min}}{s}\\right),\nq_{\\min},q_{\\max}\n\\right).\n$$\n\nThe zero-point lives in integer-code coordinates. Mixing it with a real-valued\noffset—subtracting $z$ before dividing by $s$, then adding $z$ after\ndequantization—is a units error.\n\n### One scale can erase a quiet channel\n\nScale granularity changes the trade—**per-tensor** quantization shares one scale\nacross an entire matrix. **Per-row** quantization gives each output row its own\nscale; for a linear layer this is often called per-output-channel quantization.\nMore scales cost metadata, but a large row no longer sets the grid spacing for a\nsmall row.\n\nThe next audit creates a $64\\times256$ weight matrix whose row ranges span\n$0.01$ to $10$. It compares 8-bit and 4-bit symmetric grids, either global or\nper-row, on 4,096 fixed Gaussian inputs. The code reports relative weight error,\nrelative layer-output error, the distribution of row errors, and ideal packed\npayload plus FP32 scale metadata. It reports no runtime—the simple Python arithmetic\nis not a quantized production kernel.\n\n::: {#quantization-audit .cell execution_count=8}\n``` {.python .cell-code code-summary=\"Code: compare per-tensor and per-row symmetric quantization, including output error and metadata\"}\nQUANT_D_IN, QUANT_D_OUT = 256, 64\n\n\ndef make_quantization_problem(\n    seed: int = 1701,\n) -> tuple[torch.Tensor, torch.Tensor]:\n    generator = torch.Generator().manual_seed(seed)\n    directions = torch.randn(QUANT_D_OUT, QUANT_D_IN, generator=generator)\n    directions = directions / directions.abs().amax(dim=1, keepdim=True)\n    row_ranges = torch.logspace(-2, 1, QUANT_D_OUT).unsqueeze(1)\n    weights = directions * row_ranges\n    inputs = torch.randn(4096, QUANT_D_IN, generator=generator)\n    return weights, inputs\n\n\ndef symmetric_quantize(\n    weights: torch.Tensor, bits: int, per_row: bool\n) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:\n    qmax = 2 ** (bits - 1) - 1\n    scale = (\n        weights.abs().amax(dim=1, keepdim=True) / qmax\n        if per_row else weights.abs().amax() / qmax\n    )\n    scale = torch.where(scale == 0, torch.ones_like(scale), scale)\n    codes = torch.clamp(torch.round(weights / scale), -qmax, qmax).to(torch.int8)\n    reconstructed = codes.float() * scale\n    return codes, reconstructed, scale\n\n\n@torch.no_grad()\ndef run_quantization_audit() -> list[dict]:\n    weights, inputs = make_quantization_problem()\n    reference = inputs @ weights.T\n    rows = []\n    for bits in (8, 4):\n        for per_row in (False, True):\n            codes, reconstructed, scale = symmetric_quantize(\n                weights, bits, per_row\n            )\n            row_errors = (\n                torch.linalg.norm(reconstructed - weights, dim=1)\n                / torch.linalg.norm(weights, dim=1)\n            )\n            payload_bytes = codes.numel() * bits / 8\n            metadata_bytes = scale.numel() * 4\n            rows.append({\n                \"bits\": bits,\n                \"granularity\": \"per-row\" if per_row else \"per-tensor\",\n                \"weight_error\": (\n                    torch.linalg.norm(reconstructed - weights)\n                    / torch.linalg.norm(weights)\n                ).item(),\n                \"output_error\": (\n                    torch.linalg.norm(inputs @ reconstructed.T - reference)\n                    / torch.linalg.norm(reference)\n                ).item(),\n                \"row_errors\": row_errors.numpy(),\n                \"row_ranges\": weights.abs().amax(dim=1).numpy(),\n                \"payload_bytes\": int(payload_bytes),\n                \"metadata_bytes\": int(metadata_bytes),\n                \"total_bytes\": int(payload_bytes + metadata_bytes),\n            })\n    return rows\n\n\nquant_rows = run_quantization_audit()\nprint(\"bits  scheme       w err   out err  med row  max row  payload  meta  total\")\nfor row in quant_rows:\n    print(\n        f\"{row['bits']:>4}  {row['granularity']:<10}  \"\n        f\"{row['weight_error']:.4f}      {row['output_error']:.4f}      \"\n        f\"{np.median(row['row_errors']):.4f}      {row['row_errors'].max():.4f}  \"\n        f\"{row['payload_bytes']:>7,}  {row['metadata_bytes']:>8,}  \"\n        f\"{row['total_bytes']:>5,}\"\n    )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nbits  scheme       w err   out err  med row  max row  payload  meta  total\n   8  per-tensor  0.0213      0.0213      0.2213      1.0000   16,384         4  16,388\n   8  per-row     0.0069      0.0069      0.0067      0.0096   16,384       256  16,640\n   4  per-tensor  0.2688      0.2695      1.0000      1.0000    8,192         4  8,196\n   4  per-row     0.1228      0.1223      0.1225      0.1772    8,192       256  8,448\n```\n:::\n:::\n\n\n::: {#cell-fig-quantization-granularity .cell fig-height='3.7' fig-width='11' execution_count=9}\n``` {.python .cell-code code-summary=\"Figure code: show the quantization grid, output-error trade, and small-row erasure\"}\nfig, axes = plt.subplots(1, 3, figsize=(11, 3.7),\n                         gridspec_kw={\"width_ratios\": [1.25, 0.92, 1.15]})\n\ngrid = np.arange(-3, 4) / 3\nvalues = np.array([-1.00, -0.79, -0.54, -0.11, 0.08, 0.31, 0.72, 1.00])\nrounded = np.clip(np.round(values * 3), -3, 3) / 3\naxes[0].axhline(0, color=\"#777777\", lw=1)\naxes[0].scatter(grid, np.zeros_like(grid), s=60, color=navy, zorder=3,\n                label=\"representable grid\")\naxes[0].scatter(values, np.full_like(values, 0.48), marker=\"x\", s=48,\n                color=orange, label=\"real values\")\nfor value, target in zip(values, rounded):\n    axes[0].add_patch(FancyArrowPatch((value, 0.42), (target, 0.08),\n                                      arrowstyle=\"->\", mutation_scale=8,\n                                      color=\"#999999\", lw=0.8))\naxes[0].set(xlim=(-1.12, 1.12), ylim=(-0.18, 0.72), xlabel=\"real value\",\n            title=\"3-bit symmetric rounding\")\naxes[0].set_yticks([])\naxes[0].legend(frameon=False, fontsize=8, loc=\"upper left\")\n\nlabels = [\"8-bit\", \"4-bit\"]\ntensor_errors = [next(row[\"output_error\"] for row in quant_rows\n                      if row[\"bits\"] == bits and row[\"granularity\"] == \"per-tensor\")\n                 for bits in (8, 4)]\nrow_errors = [next(row[\"output_error\"] for row in quant_rows\n                   if row[\"bits\"] == bits and row[\"granularity\"] == \"per-row\")\n              for bits in (8, 4)]\nx = np.arange(2)\naxes[1].bar(x - 0.18, tensor_errors, 0.36, color=navy, hatch=\"//\",\n            edgecolor=\"white\", label=\"one scale\")\naxes[1].bar(x + 0.18, row_errors, 0.36, color=orange, hatch=\"..\",\n            edgecolor=\"white\", label=\"per row\")\naxes[1].set_yscale(\"log\")\naxes[1].set_xticks(x, labels)\naxes[1].set(ylabel=\"relative output error\", title=\"granularity changes error\")\naxes[1].legend(frameon=False, fontsize=8)\naxes[1].grid(axis=\"y\", alpha=0.18)\n\neight_tensor = next(row for row in quant_rows\n                    if row[\"bits\"] == 8 and row[\"granularity\"] == \"per-tensor\")\neight_row = next(row for row in quant_rows\n                 if row[\"bits\"] == 8 and row[\"granularity\"] == \"per-row\")\naxes[2].loglog(eight_tensor[\"row_ranges\"], eight_tensor[\"row_errors\"], \"o-\",\n               ms=3, color=navy, label=\"one scale\")\naxes[2].loglog(eight_row[\"row_ranges\"], eight_row[\"row_errors\"], \"o-\",\n               ms=3, color=orange, label=\"per row\")\naxes[2].set(xlabel=\"row maximum magnitude\", ylabel=\"relative row error\",\n            title=\"quiet rows need a local grid\")\naxes[2].legend(frameon=False, fontsize=8)\naxes[2].grid(alpha=0.18, which=\"both\")\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Quantization is a grid plus a granularity decision. A 3-bit symmetric example (left) rounds real values to seven levels. In the unequal-row audit, per-row scales reduce relative layer-output error at both bit widths (center). At 8 bits, the global scale entirely erases the smallest rows—relative error 1—while per-row error stays near 0.7% across ranges (right). The improvement costs 256 rather than 4 bytes of FP32 scale metadata.](17-peft-quantization_files/figure-html/fig-quantization-granularity-output-1.png){#fig-quantization-granularity width=1045 height=345 fig-alt='A number line shows real values rounding to seven grid points. Hatched bars show lower output error with per-row scales at eight and four bits. A log-log plot shows a global scale erasing small rows while per-row errors stay low.'}\n:::\n:::\n\n\nThe global 8-bit grid has only $2.13\\%$ relative output error overall, which sounds\nreassuring until we inspect rows—the median relative row error is $22.13\\%$, and the\nquietest rows are reconstructed as all zeros. Per-row scales lower overall output\nerror to $0.689\\%$ and maximum row error below $0.964\\%$. At 4 bits, per-row scales\nimprove output error from $26.95\\%$ to $12.23\\%$, but do not make the approximation\nexact.\n\nThe packed 4-bit codes require 8,192 bytes. One FP32 scale brings the global total\nto 8,196 bytes; 64 row scales bring it to 8,448. The live `torch.int8` tensor in\nthis teaching cell occupies one byte per code—it is **not** physically packed into\nnibbles. @eq-quant-payload is the payload a packing format could achieve.\n\n::: {.callout-warning}\n## A smaller checkpoint is not automatically faster\n\nBit count does not determine latency by itself. Real speed depends on supported\nkernels, hardware, packing, dequantization, memory bandwidth, batch shape, and which\ntensors remain in higher precision. Dettmers and colleagues even reported cases\nwhere LLM.int8() overhead made smaller models slower than FP16. Measure the target\nsystem; do not turn a file-size ratio into a runtime claim. The Roofline and\nmeasurement contracts in @sec-a3-precision-performance make that distinction\nexplicit.\n:::\n\n### What a quantization workflow protects\n\n**Post-training quantization (PTQ)** chooses a representation after the base model\nhas trained. It may use calibration inputs, but it does not run ordinary end-to-end\ntraining again. Our uniform audit used only weight ranges. More sophisticated PTQ\nmethods protect behavior measured on calibration data. For a layer\n$\\matr{W}\\in\\mathbb{R}^{d_{\\mathrm{out}}\\times d_{\\mathrm{in}}}$ and $n$\ncalibration activations\n$\\matr{X}\\in\\mathbb{R}^{d_{\\mathrm{in}}\\times n}$, GPTQ frames a layerwise\nweight-only problem as\n\n$$\n\\widehat{\\matr{W}}\n=\\argmin_{\\widetilde{\\matr{W}}\\in\\mathcal{Q}}\n\\left\\|\\matr{W}\\matr{X}\n-\\widetilde{\\matr{W}}\\matr{X}\\right\\|_F^2,\n$$ {#eq-gptq-objective}\n\nwhere $\\widetilde{\\matr{W}}$ has the same shape as $\\matr{W}$ and\n$\\mathcal{Q}$ is the chosen quantized set. The objective\nprotects layer outputs—not ordinary weight MSE and not the original task loss. AWQ\nuses activation evidence to choose channel scaling that protects salient weights.\nThese methods make the calibration distribution part of the result.\n\n**Quantization-aware training (QAT)** instead inserts fake quantize–dequantize\noperations into the forward pass while retaining higher-precision shadow weights\nfor optimization. Because rounding is nondifferentiable, training uses a surrogate\ngradient such as a straight-through estimator. QAT is not integer-only training;\nconversion to integer execution remains a separate, kernel-dependent step.\n\nWeight-only and weight–activation quantization also answer different bottlenecks.\nA weight-only method leaves activations and the autoregressive key/value cache at\ntheir chosen compute precision. LLM.int8(), by contrast, quantizes both matrix\ninputs and weights while routing a small activation-outlier subspace through FP16 in\nits studied regime. “8-bit method” is not a complete algorithm description.\n\n### QLoRA: compose a frozen grid with a trainable delta\n\nQLoRA places the two major levers side by side. Store a pretrained base in blockwise\n4-bit **NormalFloat (NF4)**, dequantize blocks to BF16 for matrix multiplication,\nand train higher-precision LoRA factors:\n\n$$\n\\vect{h}\n=\\operatorname{Dequant}_{\\mathrm{NF4}}(\\matr{W}_q)\\vect{x}\n+\\frac{\\alpha}{r}\\matr{B}(\\matr{A}\\vect{x}).\n$$ {#eq-qlora-forward}\n\nThe base codes $\\matr{W}_q$ remain frozen. Gradient blame passes through the\ndequantized computation to the LoRA path, but ordinary updates do not rewrite the\n4-bit base. QLoRA is therefore not QAT of the backbone, and “4-bit storage” does\nnot mean every multiply or accumulator is 4-bit.\n\nNF4 uses a nonuniform codebook with denser resolution where a standardized normal\ndistribution places more probability mass, plus an exact zero. Its information\nargument applies to block-normalized, approximately zero-centered normal weights;\nit is not a universal optimal grid for arbitrary tensors.\n\n::: {#cell-fig-qlora-composition .cell fig-height='3.8' fig-width='10' execution_count=10}\n\n::: {.cell-output .cell-output-display}\n![QLoRA composes two axes without conflating them. A frozen blockwise NF4 base is dequantized to the compute dtype for the main matrix multiplication. Higher-precision A and B factors form a trainable low-rank branch, and only that branch has optimizer state. The sum defines the adapted layer; storage dtype, compute dtype, and trainable dtype are separate choices.](17-peft-quantization_files/figure-html/fig-qlora-composition-output-1.png){#fig-qlora-composition width=950 height=355 fig-alt='A top path sends frozen NF4 codes and scales through dequantization into a base matrix product. A lower trainable A-then-B path processes the same input, and the two outputs are summed.'}\n:::\n:::\n\n\nQLoRA also uses **double quantization**—it quantizes its quantization constants.\nWith the paper's illustrative\ngroup sizes, FP32 constants for each 64-weight block cost $32/64=0.5$ bits per\nweight. Storing those constants at 8 bits and adding one FP32 second-level constant\nper 256 first-level constants costs\n\n$$\n\\frac{8}{64}+\\frac{32}{64\\cdot256}=0.126953\n\\quad\\text{bits per weight},\n$$\n\na saving of $0.373047$ bits per weight. That number belongs to those block sizes;\nit is not a universal number of gigabytes. Paged optimizers address transient memory\nspikes in the paper's implementation, while the LoRA factors still carry their own\ngradients and optimizer state.\n\n::: {.callout-note}\n## QLoRA is a composition, not a new objective\n\nNF4 decides how the frozen foundation is stored; LoRA decides where task gradients\nmay write. The supervised, preference, or other loss still decides what behavior is\nrewarded. A parameter-efficient route can optimize a poor objective just as\nefficiently as a good one.\n:::\n\n## Choose by the bill you need to reduce\n\n| Method | Task state and permitted writes | Main consequence |\n|---|---|---|\n| Hard prompt / ICL | State in ordinary context; no gradients during use | No learned task checkpoint; longer context |\n| RAG | State in index and retrieved context; writes depend on design | Fresher evidence; retrieval failure surface |\n| Prompt tuning | State in continuous input vectors; write prompt vectors, plus any deliberately unfrozen head | Small learned state; virtual positions remain |\n| Prefix / adapters | State in per-layer prefixes or bottlenecks; write added modules | Small checkpoint; extra inference path |\n| LoRA | State in $\\matr{A},\\matr{B}$; write factors, plus any deliberately unfrozen head | Conditionally mergeable; rank bottleneck |\n| Full fine-tuning | State in a changed backbone; write all permitted parameters | Maximum update freedom; one full task copy |\n| PTQ | No task state—representation only; no gradients in ordinary PTQ | Smaller weight representation; approximation error |\n| QLoRA | Task state in LoRA factors; codes/scales describe the frozen base; write factors plus any deliberately unfrozen head | Smaller base representation during PEFT; mixed dtypes |\n\nThe instructor's practical instinct remains useful: when a carefully evaluated\nprompt or retrieval pipeline solves the task, avoid fine-tuning merely because it\nis available. Treat that as a search heuristic—not a law. A stable format change\nmay fit a small adapter; genuinely new knowledge may belong in retrieval or further\ntraining; a severe source-coverage mismatch may defeat all of them.\n\nThat last point harvests Chapter 9's full promise. PEFT changes the cost **after**\nwe choose transfer; it does not repeal the coverage condition. A frozen foundation\ncannot guarantee a reliable representation absent from source coverage, and a\nlow-rank update does not guarantee that scarce target labels can build the missing\nfeature. Quantization preserves or damages an existing computation—it does not add\ncoverage.\n\n::: {.callout-warning}\n## Trainable parameters are not total memory\n\nDuring PEFT, the frozen base still occupies memory and backpropagation still stores\nor recomputes activations through it. During generation, context and key/value caches\ncan dominate different regimes. Optimizer dtype and implementation change the bill.\nReport trainable state, base storage, transient training memory, context length, and\nmeasured runtime separately. One percentage cannot stand in for all five.\n:::\n\nParameter efficiency also does not guarantee immunity to forgetting or harmful\nbehavior. Restricting an update constrains which coordinates or directions are\navailable—it does not bound the update's magnitude or certify what the movement\npreserves. Evaluation must include the target task,\nretained capabilities that matter, calibration or distribution shifts, and the\nactual deployment representation.\n\n## The next question: what deserves the update?\n\n**Where the update lives is not what the update optimizes.** Prompt vectors,\nlow-rank matrices, and full fine-tuning decide where task gradients may write.\nQuantization decides how values are stored. None decides which answer is helpful,\nharmless, honest, or preferred.\n\n@sec-18-alignment will keep the adaptation machinery and change the question from\n*which parameters move?* to *which objective should move them?* Instruction tuning,\npreference learning, and alignment methods are claims about supervision and\nobjectives—not automatic consequences of choosing LoRA or a full checkpoint.\n\n## Okay, so — adaptation has three separate bills\n\n1. **Adaptation has three bills.** Backbone storage, incremental task state, and transient\n   work must be reported separately. Zero trainable weights and fewer stored bits\n   do not mean zero inference or training cost.\n2. **Prompting changes context, not weights.** The five-seed permutation study closely\n   tracks the analytical information ceilings while every evaluation weight stays bitwise fixed.\n   RAG is another context lever, with a separate retrieval failure surface.\n3. **PEFT restricts where gradient blame may write.** Prompt tuning, prefixes,\n   adapters, BitFit, and LoRA impose different parameterizations; they are not\n   interchangeable labels for “small fine-tuning.”\n4. **LoRA learns a low-rank correction.** Its trainable count is\n   $r(d_{\\mathrm{in}}+d_{\\mathrm{out}})$ per targeted matrix, and its rank is a real\n   capacity limit. The planted rank-six experiment fails exactly where it should.\n5. **Quantization is a grid, a granularity, and a workflow.** Per-row scales rescue\n   quiet rows in the controlled audit, but consume metadata. Payload size does not\n   predict runtime without kernels and hardware.\n6. **QLoRA composes representation and adaptation.** A frozen NF4 base is\n   dequantized for compute while higher-precision LoRA factors train. Storage dtype,\n   compute dtype, and trainable dtype are distinct.\n7. **Transfer coverage still governs the choice.** None of these methods creates\n   source knowledge for free. The next chapter will ask what the permitted update\n   should optimize.\n\n## Sources and further reading {.unnumbered}\n\n- [Brown et al., *Language Models are Few-Shot Learners*](https://proceedings.neurips.cc/paper/2020/hash/1457c0d6bfcb4967418bfb8ac142f64a-Abstract.html): GPT-3's zero-, one-, and few-shot evaluation and its model-scale dependence.\n- [Lewis et al., *Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks*](https://arxiv.org/abs/2005.11401): learned retrieval combined with a pretrained generator.\n- [Houlsby et al., *Parameter-Efficient Transfer Learning for NLP*](https://proceedings.mlr.press/v97/houlsby19a.html): bottleneck adapters inserted into a frozen Transformer.\n- [Li and Liang, *Prefix-Tuning: Optimizing Continuous Prompts for Generation*](https://aclanthology.org/2021.acl-long.353/): trainable per-layer prefixes for generation.\n- [Lester et al., *The Power of Scale for Parameter-Efficient Prompt Tuning*](https://aclanthology.org/2021.emnlp-main.243/): input-level soft prompts and the scoped T5 scale study.\n- [Ben-Zaken et al., *BitFit: Simple Parameter-Efficient Fine-Tuning for Transformer-Based Masked Language-Models*](https://aclanthology.org/2022.acl-short.1/): bias-term updates plus the task-specific classifier in the original experiments.\n- [Hu et al., *LoRA: Low-Rank Adaptation of Large Language Models*](https://arxiv.org/abs/2106.09685): the low-rank update parameterization, initialization, and merge.\n- [Wei et al., *Chain-of-Thought Prompting Elicits Reasoning in Large Language Models*](https://arxiv.org/abs/2201.11903): scoped gains from prompting with intermediate reasoning steps.\n- [Turpin et al., *Language Models Don't Always Say What They Think: Unfaithful Explanations in Chain-of-Thought Prompting*](https://arxiv.org/abs/2305.04388): controlled evidence that visible explanations can omit causal influences on predictions.\n- [Greshake et al., *Not What You've Signed Up For: Compromising Real-World LLM-Integrated Applications with Indirect Prompt Injection*](https://arxiv.org/abs/2302.12173): the attack surface created when untrusted retrieved data can act as instructions.\n- [Jacob et al., *Quantization and Training of Neural Networks for Efficient Integer-Arithmetic-Only Inference*](https://openaccess.thecvf.com/content_cvpr_2018/html/Jacob_Quantization_and_Training_CVPR_2018_paper.html): affine quantization and the fake-quantization training pattern.\n- [Dettmers et al., *LLM.int8(): 8-bit Matrix Multiplication for Transformers at Scale*](https://papers.neurips.cc/paper_files/paper/2022/hash/c3ba4962c05c49636d4c6206a97e9c8a-Abstract-Conference.html): mixed-precision decomposition for activation outliers—and measured overhead caveats.\n- [Frantar et al., *GPTQ: Accurate Post-Training Quantization for Generative Pre-trained Transformers*](https://arxiv.org/abs/2210.17323): calibration-output-aware, layerwise weight-only PTQ.\n- [Lin et al., *AWQ: Activation-aware Weight Quantization for LLM Compression and Acceleration*](https://arxiv.org/abs/2306.00978): activation evidence for protecting salient weights.\n- [Dettmers et al., *QLoRA: Efficient Finetuning of Quantized LLMs*](https://papers.nips.cc/paper_files/paper/2023/hash/1feb87871436031bdc0f2beaa62a049b-Abstract-Conference.html): NF4, double quantization, paged optimizers, and LoRA over a frozen quantized base.\n\n## Exercises {.unnumbered}\n\n1. **(Pencil.)** A model has 24 matrices of shape $4096\\times4096$. LoRA targets\n   each with rank 16. Compute full and adapter value counts, the adapter fraction,\n   and FP16 adapter bytes. Then compute the ideal 4-bit base payload. Add one FP32\n   scale per block of 64 weights and explain which deployment costs remain absent.\n2. **(Code and interpretation.)** Reproduce the frozen-context experiment, then\n   randomize demonstration order, repeat one group with the same label, and finally\n   insert a contradictory label for a repeated group. Predeclare which interventions\n   preserve @eq-icl-ceiling and which make it inapplicable. Report all seeds and\n   verify bitwise parameter identity before interpreting a difference.\n3. **(Proof and code.)** Prove\n   $\\operatorname{rank}(\\matr{B}\\matr{A})\\le r$. Extend the rank-capacity audit with\n   a planted rank-10 correction and ranks $2,6,10,14$. Audit gradients after the\n   first backward pass for (a) random $\\matr{A}$ and zero $\\matr{B}$, and (b) both\n   factors zero. Verify merged–unmerged equality.\n4. **(Pencil and code.)** Quantize\n   $[-1.2,-0.3,0.0,0.5,1.7]$ onto a signed 4-bit symmetric grid, showing $Q,s,q,$\n   and $\\widehat w$. Then construct an affine 8-bit grid for a nonnegative interval.\n   On the chapter's unequal-row matrix, compare calibration and held-out output error\n   after inserting one new outlier row.\n5. **(Decision audit.)** For each of three cases—fresh facts with citations, a stable\n   output format, and a target domain absent from the source data—choose a first\n   experiment among prompting/RAG, PEFT, full tuning, and quantization. State where\n   task state lives, which bill it reduces, what it cannot repair, and one retained\n   behavior you would evaluate. Finally explain why none of those choices answers\n   the Chapter 18 question of which behavior deserves reward.\n\n",
    "supporting": [
      "17-peft-quantization_files"
    ],
    "filters": [],
    "includes": {}
  }
}