{
  "hash": "0b39f1b74fc90cf5b9b724564c004ae4",
  "result": {
    "engine": "jupyter",
    "markdown": "# Encoder–Decoder, Teacher Forcing, Beam Search {#sec-11-encoder-decoder}\n\n<!-- lecture-source: m06_lecture-6-encoder-decoder-architectures_XxePU8jubto.txt\n     (spine #1-3, #9: fixed-size contract, variable-length challenge, bridge to\n     translation), m07 spine #11 (encoder-decoder bottleneck bridge)\n     seeds: sources/7.2-TF-Beam.tex (§Teacher Forcing, §Exposure Bias, §Scheduled\n            Sampling, §Masking & Padded Sequences, §Greedy, §Beam, §Length Norm),\n            his old/train_seq2seq.py (architecture template) + rnn_data_prep.py\n            (special-token conventions; its dataset pipeline is D2L-derived and is\n            NOT used — the book's task is synthetic and self-contained)\n     note: m06's PCA/autoencoder spine (#4-8) belongs to @sec-19-generative. -->\n\nChapter 10 ended with a promise: if one recurrent cell can read a sequence *into* a\nstate, two cells can translate — one reads, one writes. This chapter builds that\nmachine and the craft around it: how to train it fast (teacher forcing), what\npoisonous bookkeeping to avoid (padding), and how to get answers back out of it\n(greedy versus beam search). It ends where Part III must: staring at the one vector\nin the middle.\n\nThe lecture frames the stakes well. Every model so far has lived on a **fixed-size\ncontract** — 784 pixels in, 10 logits out; $28 \\times 28$ garments in, one verdict\nout. The interesting world breaks that contract on both ends at once: translation\nmaps a sentence of *any* length to a sentence of *some other* length, in a\ndifferent vocabulary. The recurrent cell broke the contract on the input side;\ntoday we break it on both.\n\n## Two RNNs and a handoff\n\nThe architecture is one idea long. An **encoder** RNN reads the source sequence and\nkeeps nothing but its final state — the entire input compressed into one vector,\nthe **context**. A **decoder** RNN starts *from* that state and generates the\noutput token by token, feeding each token back in, exactly like Chapter 10's\ncharacter model. A language model, in other words — but one with something to say.\n\nOur laboratory task keeps every property of translation and none of the downloads:\n**date normalization**. The source language is human-written dates in several\ndialects; the target language is ISO 8601:\n\n```\nmarch 5, 2021        -> 2021-03-05\n26 september 2024    -> 2024-09-26\n12/15/1950           -> 1950-12-15\n```\n\nVariable-length input, different output alphabet, real long-range structure (the\nyear arrives *last* in most sources but must be emitted *first*), and — by\ndeliberate design, visible below — a dialect ambiguity that will give beam search\nsomething genuine to reveal: numeric dates are written `mm/dd/yyyy` by 70% of our\nimaginary writers (the US convention) and `dd/mm/yyyy` by 30%, and nothing in\n`03/05/2021` says which. Machine translation in miniature.\n\n::: {#date-data .cell execution_count=1}\n``` {.python .cell-code code-summary=\"Code: the two date languages, generated on the fly\"}\nimport random, torch\nimport torch.nn as nn\nimport torch.nn.functional as F\nimport matplotlib.pyplot as plt\n\nMONTHS = [\"january\", \"february\", \"march\", \"april\", \"may\", \"june\", \"july\",\n          \"august\", \"september\", \"october\", \"november\", \"december\"]\nDAYS = dict(zip(MONTHS, [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]))\n\ndef make_date(rng):\n    mo = rng.randrange(12)\n    d = rng.randrange(1, DAYS[MONTHS[mo]] + 1)\n    y = rng.randrange(1950, 2026)\n    iso = f\"{y:04d}-{mo+1:02d}-{d:02d}\"\n    style = rng.random()\n    if style < 0.35:\n        src = f\"{MONTHS[mo]} {d}, {y}\"\n    elif style < 0.6:\n        src = f\"{d} {MONTHS[mo]} {y}\"\n    elif rng.random() < 0.7:\n        src = f\"{mo+1:02d}/{d:02d}/{y}\"            # US convention: mm/dd\n    else:\n        src = f\"{d:02d}/{mo+1:02d}/{y}\"            # EU convention: dd/mm\n    return src, iso\n\nrng = random.Random(6050)\npairs = [make_date(rng) for _ in range(9000)]\ntrain_pairs, test_pairs = pairs[:8000], pairs[8000:]\nprint(*pairs[:4], sep=\"\\n\")\n\nPAD, BOS, EOS = 0, 1, 2                             # special tokens first\nSRC = sorted(set(\"\".join(s for s, _ in pairs)))\nTGT = sorted(set(\"\".join(t for _, t in pairs)))\nsrc_stoi = {c: i + 3 for i, c in enumerate(SRC)}\ntgt_stoi = {c: i + 3 for i, c in enumerate(TGT)}\ntgt_itos = {i: c for c, i in tgt_stoi.items()}\nV_src, V_tgt = len(SRC) + 3, len(TGT) + 3\nprint(f\"source vocab {V_src}, target vocab {V_tgt}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n('26 september 2024', '2024-09-26')\n('april 7, 1962', '1962-04-07')\n('12/15/1950', '1950-12-15')\n('14 february 1997', '1997-02-14')\nsource vocab 37, target vocab 14\n```\n:::\n:::\n\n\nThree special tokens run the show, the same conventions as the course's full\ntranslation pipeline: `<pad>` fills the short sequences of a batch out to a\nrectangle, `<bos>` tells the decoder \"begin,\" and `<eos>` lets the *model* say\n\"I'm done\" — remember, the machine must be free to choose its output length.\n\nOne more new tool, and it earns a pause. Chapter 10 fed characters in as one-hot\nvectors. This chapter gives each token a learned vector instead: `nn.Embedding`, a\ntable with one trainable row per vocabulary entry. There is no new math — an\nembedding is exactly a one-hot vector times a weight matrix, Chapter 1's linear\nmap wearing a lookup table's clothes — but the reading matters: *the address is\nhard, the content is learned*. Row 17 is fetched by index, rigidly; what lives in\nrow 17 is whatever training decides that token should mean. Keep the phrase \"hard\naddress, learned content\" nearby: in @sec-13-attention we soften the address too,\nand that will be the whole story.\n\n::: {#seq2seq-model .cell execution_count=2}\n``` {.python .cell-code code-summary=\"Code: encoder, decoder, and the handoff\"}\nclass Seq2Seq(nn.Module):\n    def __init__(self, v_src: int, v_tgt: int, embed: int = 32,\n                 hidden: int = 128, packed: bool = True):\n        super().__init__()\n        self.packed = packed\n        self.src_emb = nn.Embedding(v_src, embed, padding_idx=PAD)\n        self.tgt_emb = nn.Embedding(v_tgt, embed, padding_idx=PAD)\n        self.encoder = nn.LSTM(embed, hidden, batch_first=True)\n        self.decoder = nn.LSTM(embed, hidden, batch_first=True)\n        self.out = nn.Linear(hidden, v_tgt)\n\n    def encode(self, S, lengths):\n        e = self.src_emb(S)                          # (B, T_src, embed)\n        if self.packed:                              # stop at each true length\n            e = nn.utils.rnn.pack_padded_sequence(\n                e, lengths, batch_first=True, enforce_sorted=False)\n        _, state = self.encoder(e)\n        return state                                 # (h, c): the context\n\n    def forward(self, S, lengths, T_in):             # teacher-forced pass\n        o, _ = self.decoder(self.tgt_emb(T_in), self.encode(S, lengths))\n        return self.out(o)                           # (B, T_tgt, V_tgt) logits\n```\n:::\n\n\nThe whole architecture is that `encode` return value: the LSTM's final $(\\vect{h},\n\\vect{c})$, handed to the decoder as its *initial* state. Everything the decoder\nwill ever know about the source crosses that bridge.\n\n## The padding trap\n\nBefore the machinery works, an honest detour through the way it *fails*, because\nthe seed notes devote a full section to this and experience says everyone hits it\nonce. Batching variable-length sequences means padding them to a rectangle, and\npadding poisons two places:\n\n1. **The loss.** Positions holding `<pad>` are not predictions to be graded.\n   `F.cross_entropy(..., ignore_index=PAD)` excludes them — one argument, done.\n2. **The encoder.** Subtler and far worse: an LSTM does not know your zeros are\n   padding. It keeps stepping through them, and every pad step smears the final\n   state — the context vector! — for every sequence shorter than the batch's\n   longest. Worse still, at inference you feed single sequences with *no* padding,\n   so the model is tested in a regime it never trained in.\n\nWatch what that costs. Same model, same data, same budget — the only difference is\nwhether the encoder is told the true lengths (`pack_padded_sequence`, which runs\nthe recurrence only through each sequence's real tokens):\n\n::: {#padding-experiment .cell execution_count=3}\n``` {.python .cell-code code-summary=\"Code: train twice — naive right-padding vs. packed sequences\"}\ndef batchify(prs, idx):\n    srcs = [torch.tensor([src_stoi[c] for c in prs[i][0]]) for i in idx]\n    lengths = torch.tensor([len(s) for s in srcs])\n    tgts = [torch.tensor([BOS] + [tgt_stoi[c] for c in prs[i][1]] + [EOS])\n            for i in idx]\n    S = nn.utils.rnn.pad_sequence(srcs, batch_first=True, padding_value=PAD)\n    T = nn.utils.rnn.pad_sequence(tgts, batch_first=True, padding_value=PAD)\n    return S, lengths, T\n\ndef train_seq2seq(mode: str = \"tf\", packed: bool = True, epochs: int = 25,\n                  seed: int = 6050, batch: int = 128, checkpoints=()):\n    torch.manual_seed(seed)\n    model = Seq2Seq(V_src, V_tgt, packed=packed)\n    opt = torch.optim.Adam(model.parameters(), lr=1e-3)\n    n, curve = len(train_pairs), {}\n    for ep in range(1, epochs + 1):\n        perm = torch.randperm(n)\n        for i in range(0, n, batch):\n            S, L, T = batchify(train_pairs, perm[i:i + batch].tolist())\n            if mode == \"tf\":                         # gold rail: one parallel pass\n                logits = model(S, L, T[:, :-1])\n            else:                                    # free-running: its own rail\n                state = model.encode(S, L)\n                tok, outs = T[:, :1], []\n                for t in range(T.shape[1] - 1):\n                    o, state = model.decoder(model.tgt_emb(tok), state)\n                    logit = model.out(o)\n                    outs.append(logit)\n                    tok = logit.argmax(-1)           # feed its own prediction\n                logits = torch.cat(outs, 1)\n            loss = F.cross_entropy(logits.reshape(-1, V_tgt),\n                                   T[:, 1:].reshape(-1), ignore_index=PAD)\n            opt.zero_grad(); loss.backward()\n            nn.utils.clip_grad_norm_(model.parameters(), 5.0)\n            opt.step()\n        if ep in checkpoints:\n            curve[ep] = exact_match(model, test_pairs[:400])\n    return model, curve\n\n@torch.no_grad()\ndef translate(model, src: str, maxlen: int = 12):\n    S = torch.tensor([[src_stoi[c] for c in src]])\n    state = model.encode(S, torch.tensor([len(src)]))\n    tok, out = torch.tensor([[BOS]]), \"\"\n    for _ in range(maxlen):\n        o, state = model.decoder(model.tgt_emb(tok), state)\n        tok = model.out(o).argmax(-1)                # greedy: best next char\n        if tok.item() == EOS:\n            break\n        out += tgt_itos.get(tok.item(), \"?\")\n    return out\n\n@torch.no_grad()\ndef exact_match(model, prs):\n    return sum(translate(model, s) == t for s, t in prs) / len(prs)\n\n# the unambiguous test set: one defensible answer exists\nunamb = [(s, t) for s, t in test_pairs\n         if \"/\" not in s or int(s[:2]) > 12 or int(s[3:5]) > 12]\n\nnaive, _ = train_seq2seq(packed=False)\npacked, _ = train_seq2seq(packed=True)\nprint(f\"naive right-padding:   exact match {exact_match(naive, unamb):.1%}\")\nprint(f\"packed (true lengths): exact match {exact_match(packed, unamb):.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nnaive right-padding:   exact match 39.8%\npacked (true lengths): exact match 98.5%\n```\n:::\n:::\n\n\nFifty-nine points. Not from a better architecture, optimizer, or dataset — from\ntelling the encoder where the sentences actually end. Let the number sink in,\nbecause this is the cheapest lesson in the book: the two runs are identical except\nfor bookkeeping, and the bookkeeping was worth more than every design decision in\nPart III so far.\n\n::: {.callout-warning}\n## The model will happily read your padding\n\nNothing in the tensor marks `<pad>` as meaningless; meaning is something *you*\nenforce, in two places: `ignore_index` for the loss, `pack_padded_sequence` (or an\nexplicit mask) for the encoder. When a sequence model underperforms mysteriously,\naudit the padding before touching the architecture. And file the general shape of\nthis tool away: telling a model *which positions it may not look at* is called\n**masking**, and it returns center-stage in @sec-14-self-attention-transformer,\nwhere a *causal* mask is what turns a transformer into a language model.\n:::\n\n## Teacher forcing: training on the gold rail\n\nLook back at the two `mode` branches in the training loop; they are this section.\nWhen the decoder is trained, what should it see as *its own previous output*?\n\n**Free-running** (\"fr\") is the honest answer: feed the model's own predictions\nback in, exactly as at inference. But its flaws are structural. Early in training\nthose predictions are garbage $\\rightarrow$ the decoder learns conditioned on\ngarbage $\\rightarrow$ every sequence must be generated token-by-token in a Python\nloop, because step $t$'s input does not exist until step $t-1$ is computed. Slow,\nand unstable exactly when training is young.\n\n**Teacher forcing** (\"tf\") conditions each step on the *ground-truth* previous\ntoken instead — the gold rail. Every conditioning input is then known in advance\n$\\rightarrow$ the entire target trains in **one parallel decoder pass** (that is\nthe whole `model(S, L, T[:, :-1])` line), and every step learns from a sensible\ncontext from epoch one. Watch both effects:\n\n::: {#cell-fig-tf-vs-fr .cell execution_count=4}\n``` {.python .cell-code code-summary=\"Code: teacher forcing vs. free-running, learning curves\"}\ncps = (2, 4, 6, 8, 12, 16, 20, 25)\ntf_model, tf_curve = train_seq2seq(\"tf\", checkpoints=cps)\nfr_model, fr_curve = train_seq2seq(\"fr\", checkpoints=cps)\nprint(f\"final exact match (unambiguous): TF {exact_match(tf_model, unamb):.1%}, \"\n      f\"FR {exact_match(fr_model, unamb):.1%}\")\n\nplt.figure(figsize=(6, 3.2))\nplt.plot(cps, [tf_curve[c] for c in cps], \"o-\", color=\"#232D4B\", lw=2,\n         label=\"teacher forcing\")\nplt.plot(cps, [fr_curve[c] for c in cps], \"s-\", color=\"#E57200\", lw=2,\n         label=\"free-running\")\nplt.xlabel(\"epoch\"); plt.ylabel(\"exact match\")\nplt.legend(); plt.tight_layout(); plt.show()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nfinal exact match (unambiguous): TF 98.5%, FR 99.4%\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![Learning curves under the two training modes (exact-match on 400 held-out dates). Teacher forcing leads through the early and middle epochs (40% vs. 33% at epoch 6, 86% vs. 80% at 12) — and each of its epochs is one parallel decoder pass where free-running needs a token-by-token loop. The honest fine print: on this small task free-running closes the gap by epoch 16 and ends fractionally ahead, because it never suffers the train/inference mismatch described below.](11-encoder-decoder_files/figure-html/fig-tf-vs-fr-output-2.png){#fig-tf-vs-fr width=567 height=297}\n:::\n:::\n\n\nSo teacher forcing is the pragmatic default: parallel, stable, fast out of the\ngate. What it costs has a name. A teacher-forced decoder has *only ever seen\nperfect histories*. At inference it must condition on its own imperfect\npredictions — a distribution it never trained on. This mismatch is **exposure\nbias**: the model never learned to recover from its own mistakes, so one early\nslip can send the rest of the sequence somewhere strange. You can see the shape of\nthis failure in our model's rare residual errors:\n\n::: {#error-gallery .cell execution_count=5}\n``` {.python .cell-code code-summary=\"Code: the residual errors, up close\"}\nerrs = [(s, t, translate(tf_model, s))\n        for s, t in unamb if translate(tf_model, s) != t]\nprint(f\"{len(errs)} errors on {len(unamb)} unambiguous dates; a sample:\")\nfor s, t, g in errs[:3]:\n    print(f\"  {s!r} -> {g!r}   (truth {t})\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n13 errors on 849 unambiguous dates; a sample:\n  '30/11/1961' -> '1961-11-03'   (truth 1961-11-30)\n  '07/31/1955' -> '1955-01-04'   (truth 1955-07-31)\n  '03/22/1956' -> '1956-02-31'   (truth 1956-03-22)\n```\n:::\n:::\n\n\nLook at that third specimen: February 31st. Each character locally plausible\ngiven the last, the whole confidently impossible. Off the gold rail, the decoder\ndoes not consult the source so much as *invent* — hold that thought two sections.\n\n::: {.callout-note}\n## Scheduled sampling: renting the rail\n\nThe engineered compromise (Bengio et al., 2015): during training, at *each\ntimestep* flip a biased coin — probability $\\epsilon$ of the gold token, $1 -\n\\epsilon$ of the model's own prediction — and anneal $\\epsilon$ from 1 toward 0 as\ntraining matures. Early epochs enjoy the gold rail; late epochs practice recovery.\nOne design detail from the original paper worth repeating: flip **per token, not\nper sequence** — committing a whole sequence to model predictions early in\ntraining lets consecutive errors amplify. Exercise 3 has you build it.\n:::\n\n## Getting answers out: search\n\nTraining is settled; now the neglected half. At inference the decoder defines a\nprobability for every possible output sequence, and we want the best one. That is\na *search problem* over a tree where every node branches $V_{\\text{tgt}}$ ways —\nexhaustive search is $V^{T}$, hopeless. Everything practical is a heuristic walk\nthrough that tree.\n\n**Greedy search** — what `translate` above already does — takes the single most\nprobable token at each step and never looks back. Complexity $O(V \\cdot T)$,\nquality: usually fine, occasionally myopic. The failure mode is structural: a\ntoken that looks best *right now* can commit the decoder to a mediocre\ncontinuation, when a slightly worse token now would have opened a much better\npath. Maximizing each step is not maximizing the sequence — you met this exact\ngap in @sec-02-logistic-softmax, where the hard max's stepwise confidence hid the\nalternatives softmax kept alive.\n\n**Beam search** widens the walk: carry the $k$ best partial sequences (the\n*beam*), expand each by all $V$ tokens, keep the top $k$ by *cumulative*\nlog-probability, repeat. Complexity $O(k \\cdot V \\cdot T)$ — a small multiple of\ngreedy, nothing like exhaustive.\n\n::: {#beam-search .cell execution_count=6}\n``` {.python .cell-code code-summary=\"Code: beam search, k candidate rails at once\"}\n@torch.no_grad()\ndef beam_search(model, src: str, k: int = 5, maxlen: int = 12):\n    S = torch.tensor([[src_stoi[c] for c in src]])\n    state = model.encode(S, torch.tensor([len(src)]))\n    beams = [([], 0.0, state, False)]               # (tokens, logp, state, done)\n    for _ in range(maxlen):\n        cand = []\n        for seq, lp, st, done in beams:\n            if done:\n                cand.append((seq, lp, st, True)); continue\n            tok = torch.tensor([[seq[-1] if seq else BOS]])\n            o, st2 = model.decoder(model.tgt_emb(tok), st)\n            logp = F.log_softmax(model.out(o)[0, -1], -1)\n            top = torch.topk(logp, k)\n            for lg, ix in zip(top.values, top.indices):\n                cand.append((seq + [ix.item()], lp + lg.item(), st2,\n                             ix.item() == EOS))\n        beams = sorted(cand, key=lambda b: -b[1])[:k]\n        if all(b[3] for b in beams):\n            break\n    return [(\"\".join(tgt_itos.get(i, \"?\") for i in seq if i > 2), lp)\n            for seq, lp, _, _ in beams]\n```\n:::\n\n\nNow the payoff, and it is exactly where we buried it: the ambiguous dates. For\n`03/05/2021`, \"the one best answer\" is the wrong question — the training world\nitself was split 70/30 between two readings. Greedy silently hands you one\nsequence. Beam search hands you the *distribution*:\n\n::: {#beam-demo .cell execution_count=7}\n``` {.python .cell-code code-summary=\"Code: beam search on genuinely ambiguous dates\"}\namb = [(s, t) for s, t in test_pairs\n       if \"/\" in s and int(s[:2]) <= 12 and int(s[3:5]) <= 12]\nfor s, t in amb[:4]:\n    print(f\"{s!r}   greedy: {translate(tf_model, s)!r}\")\n    for text, lp in beam_search(tf_model, s, k=4)[:2]:\n        print(f\"   beam: {text!r}   p = {torch.tensor(lp).exp():.2f}\")\n    print()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'10/09/1976'   greedy: '1976-10-09'\n   beam: '1976-10-09'   p = 0.62\n   beam: '1976-09-10'   p = 0.33\n\n'07/07/2022'   greedy: '2022-07-07'\n   beam: '2022-07-07'   p = 0.96\n   beam: '2022-07-05'   p = 0.01\n\n'01/07/1978'   greedy: '1978-01-07'\n   beam: '1978-01-07'   p = 0.71\n   beam: '1978-07-01'   p = 0.23\n\n'09/01/1965'   greedy: '1965-09-10'\n   beam: '1965-01-09'   p = 0.45\n   beam: '1965-09-10'   p = 0.41\n\n```\n:::\n:::\n\n\nRead those pairs of hypotheses. The two beam candidates are the two *readings* —\nmonth/day and day/month — and their probabilities sit near the 70/30 convention\nsplit the data was generated with: the model has learned not just to translate\nbut to represent its own uncertainty, and beam search is the tool that lets you\n*see* it. When the two readings coincide, as in `07/07/2022`, the top candidate\nabsorbs nearly all the mass — the ambiguity was never real for that date, and the\nbeam says so. Best of all, watch for a greedy line that *fumbles* one of these:\nstarting down one reading, switching midway, emitting a date that is neither,\nwhile the beam's top candidate stays coherent. Myopia, caught in the wild.\n\nHonesty requires the other half of the report:\n\n::: {#beam-vs-greedy-stat .cell execution_count=8}\n``` {.python .cell-code code-summary=\"Code: how often beam actually changes the answer\"}\nsub = random.Random(0).sample(test_pairs, 200)\nn_diff = sum(beam_search(tf_model, s, k=5)[0][0] != translate(tf_model, s)\n             for s, _ in sub)\nprint(f\"beam-5 disagrees with greedy on {n_diff} of {len(sub)} test dates\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nbeam-5 disagrees with greedy on 1 of 200 test dates\n```\n:::\n:::\n\n\nOn this small, well-trained model, beam search changes almost nothing. Beam\nsearch earns its keep at the margins — but real translation, with vocabularies of\ntens of thousands and long sentences, lives entirely at those margins, which is\nwhy every production decoder of the seq2seq era ran a beam.\n\n::: {.callout-note}\n## Length normalization\n\nSummed log-probabilities shrink as sequences grow $\\rightarrow$ a raw beam quietly\nfavors short outputs. The standard correction divides the score by\n$L^{\\alpha}$ with $\\alpha \\approx 0.6$–$0.75$. Our dates all have the same length,\nso the bias is invisible here (Exercise 4 makes you verify that, and why); in\nfree-length generation it matters enormously.\n:::\n\n::: {.callout-caution}\n## GPU run pending\n**Planned:** the real thing — English→French seq2seq on a full parallel corpus,\nwith the course's `train_seq2seq.py` pipeline (two-layer LSTMs, dropout, sequence\nbucketing for throughput, BLEU evaluation), comparing greedy vs. beam widths.\n**Meanwhile:** the date laboratory above demonstrates every mechanism at CPU\nscale.\n:::\n\n## The vector in the middle\n\nTime to stare at the handoff. Every property of the source that the decoder will\never use crossed one bridge: a 128-number state. Our task fits — a date is three\nfacts — and still the fingerprints of strain show. The residual errors are\norder-slips and inventions (`1956-02-31`), the signature of a decoder\nreconstructing from a compressed summary rather than consulting the source. Now\nscale the ambition: a forty-word sentence, clause structure, names, negations —\nall crammed through the same fixed pipe, *regardless of length*. Chapter 10\ncalled this the price of the Markov claim; here the bill arrives itemized.\n\nAnd notice what the architecture throws away: the encoder *had* a state at every\nstep — a whole trajectory of summaries, one per source position — and we kept\nonly the last. The fix that defines Part IV is almost embarrassingly direct: keep\nthem all, and let the decoder *look back* at whichever ones matter for the token\nit is writing right now. Choosing where to look, by similarity, on the fly — you\nhave owned the primitive since Chapter 1's dot product, and Chapter 2 promised\nyou the \"soft lookup\" that makes it differentiable. @sec-12-kernel-regression\nbuilds the classical version; @sec-13-attention makes it learnable and comes back\nfor this very date task with an alignment map to show where the decoder looks.\n\n## Okay, so —\n\n1. **Encoder–decoder = two RNNs and a handoff**: read the source into a final\n   state, hand it over, generate from it. `<bos>` starts the decoder, `<eos>`\n   lets it choose its length, embeddings replace one-hots (hard address, learned\n   content).\n2. **Padding poisons twice**: the loss (`ignore_index`) and the encoder\n   (`pack_padded_sequence`). Same model, same budget: 39.8% naive versus 98.5%\n   packed. Audit bookkeeping before architecture.\n3. **Teacher forcing** trains the decoder on the gold rail: one parallel pass,\n   stable early learning — at the cost of **exposure bias**, the train/inference\n   mismatch that free-running avoids by paying with speed and early instability.\n   Scheduled sampling anneals between them, flipping per token.\n4. **Decoding is search.** Greedy maximizes steps, not sequences; beam search\n   carries $k$ rails for $O(k V T)$ and surfaces the model's genuine\n   uncertainty — our ambiguous dates come back as two readings at roughly the\n   70/30 training split. Length normalization ($L^{\\alpha}$) keeps long outputs\n   competitive.\n5. **The bottleneck is now the story.** One fixed vector between reader and\n   writer, regardless of input length; errors that look like invention, not\n   lookup. The encoder's per-step states were there all along — Part IV is what\n   happens when we stop throwing them away.\n\n## Exercises {.unnumbered}\n\n1. **(Pencil.)** Count this chapter's parameters: two embeddings, two LSTMs, one\n   output layer ($V_{\\text{src}} = 37$, $V_{\\text{tgt}} = 14$, embed 32, hidden\n   128; an LSTM holds $4\\left[(e + h)h + 2h\\right]$ — derive that first). Where\n   do most parameters live, and why is the answer different from Chapter 8's\n   LeNet audit?\n2. **(Pencil.)** With vocabulary $10^4$ and output length 10, compare the number\n   of sequences examined by exhaustive search, greedy, and beam-5. Then explain\n   why beam search with $k = V^{T}$ is exact and with $k = 1$ is greedy — and why\n   neither endpoint is usable.\n3. **(Code.)** Implement scheduled sampling: per token, use the gold input with\n   probability $\\epsilon$, the model's own prediction otherwise, annealing\n   $\\epsilon$ linearly $1 \\to 0$ over 25 epochs. Compare its learning curve with\n   both curves in @fig-tf-vs-fr. Does it inherit teacher forcing's fast start\n   *and* free-running's finish?\n4. **(Code.)** Add length normalization ($/L^{\\alpha}$) to `beam_search` and\n   sweep $\\alpha \\in \\{0, 0.7, 1\\}$ on the date task. Nothing should change —\n   explain precisely why, and design the smallest change to the *task* that\n   would make $\\alpha$ matter.\n5. **(Code.)** Sutskever et al. (2014) famously improved translation by feeding\n   the source sentence *reversed*. Try it here. Whatever you observe, explain it\n   with this chapter's tools: which source-target dependencies does reversal\n   shorten in their setting, and which does it shorten — or lengthen — for dates,\n   where the year sits at the end of the source but the start of the target?\n\n",
    "supporting": [
      "11-encoder-decoder_files"
    ],
    "filters": [],
    "includes": {}
  }
}